### ISSUE TITLE
better place for test utilities

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#10]
How about a `testUtil/` directory in `src/`, containing test utils like `testRule`?

The current position (in `src/rules/__tests__/utils`) seems to me very unintuitive and requires a long import like `import testRule from "../../__tests__/utils/testRule"`.

Open to that?

**Comment by MoOx** [comment]
I moved it into a __tests__ folder so it's ignored when we publish. Maybe we can put it in a shorter folder then add the path in npmignore too.

**Comment by davidtheclark** [comment]
Sure, sounds good.

**Comment by davidtheclark** [comment]
Main problem wasn't with the length of the import (probably inevitable with this dir structure) but the unintuitive path. I'm committing a change in one sec to have a testUtils dir.

**Comment by MoOx** [comment]
We can also just ignore this folder in npmignore too

**Comment by davidtheclark** [comment]
Ok, did it.

**Comment by MoOx** [comment]
:+1:
