### ISSUE TITLE
Add ignoreProperties: {} option to unit-blacklist and unit-whitelist

### ISSUE THREAD

**Issue by wroughtec** [stylelint/stylelint#1062]
If you have a global rule to say blacklist px there is no current way to add an exception ie blacklist px globally except on borders, text-shadow, etc. as by whitelisting these in property-unit-whitelist the rule is overwritten. I assume it is the same with  unit-whitelist and property-unit-blacklist (although have not used it this way around so cannot verify).

I would either expect you can add exceptions to the global blacklist or the property-unit acts like an exception.

> Which rule, if any, is this issue related to?

'unit-blacklist'
'property-unit-whitelist'

'unit-whitelist'
'property-unit-blacklist'

> What CSS is needed to reproduce this issue?
 Both of these will error even though we are asking for the px on border
e.g.

```css
.foo {
  border: 1px solid purple;
}

.bar {
  border: 1rem solid purple;
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
    "unit-blacklist": ["px"],

    "property-unit-blacklist": {
      "/^border/": ["em", "rem", "%"]
    },
    "property-unit-whitelist": {
      "/^border/": ["px"]
    },
```

> Which version of stylelint are you using?

'5.4.0'

> How are you running stylelint: CLI, PostCSS plugin, Node API?

SublimeText 3

> What did you expect to happen?

No warnings when border uses px

> What actually happened (e.g. what warnings or errors you are getting)?

The unit is blacklisted

**Comment by jeddy3** [comment]
@wroughtec Thanks for the detailed write-up.

I think there is perhaps three misconceptions at work here:

1. Whitelists are for saying *only these things are allowed and nothing else*. They aren't used for specifying exceptions.
2. Each rule stands alone and isn't (for complexity reasons) aware of how other rules are configured.
3. The `*-blacklist` and `-whitelist` rules aren't generally used together.

So you can either use `unit-whitelist` *or* `unit-blacklist`, but not both. Likewise for `property-whitelist` and `property-blacklist`. However, `property-unit-blacklist` and `property-unit-whitelist` can be used together, but *the same key should not be appear in both*.

The `property-unit-blacklist` and `property-unit-whitelist` rules were added after `unit-whitelist` and `unit-blacklist` to provide finer-grain control. These sets of rules can be used together. Here's a couple of use cases for example:

- "I always want to disallow pixel units."
- "*Additionally*, I'd like to disallow percentages for `width` property."

You'd achieve that with:

```json
{ 
  "unit-blacklist": ["px"],
  "property-unit-blacklist": { "width: "%" }
}
```

Or another use case is:

- "I only want to allow the use of relative units"
- "*Additionally*, I want to disallow `em` units for the `font-size` property.

You'd achieve that with:

```json
{ 
  "unit-whitelist": ["ch", "em", "ex", "rem", "%"],
  "property-unit-blacklist": { "font-size": "%" }
}
```

Does that make sense? It feels like you might need to approach your requirements *from the other way around*. Let us know if I've misunderstood your request though.

**Comment by wroughtec** [comment]
Hmmm thanks for clarifying the expected behaviour. It looks like I will need to write a lot of "rules" to get my desired result:

- I always want to disallow pixel units except on certain properties

**Comment by jeddy3** [comment]
You're right. I think what we've got now works well for the two use cases I mentioned, but your use case won't be much fun to configure.

Suggestions?

Perhaps there's scope to bring [our usual](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#determine-options) `"except"` secondary option to `unit-whitelist` and `unit-blacklist` e.g.

- I always want to disallow percentages. 
- And I always want to disallow pixels, except for the `font-size` and `margin` properties.

```json
{
  "unit-blacklist": [["%", "px"], {
    "exceptProperties": [
      {
         "px": ["font-size", "margin"]
      }
    ]
  }]
}
```

This might muddy the waters somewhat i.e. when's blacklist not a blacklist? and they'll be two ways of providing fine-grain control, but it would make configuring your use case much easier.

Anybody else have any thoughts on this?

**Comment by davidtheclark** [comment]
Couldn't `ignoreProperties` just be an object, instead of an array?

**Comment by jeddy3** [comment]
> Couldn't ignoreProperties just be an object, instead of an array?

Oops. I got a bit carried away with the brackets :) Yes, I think just an object is fine.

Do you think the approach would work though? I think it seems pretty solid and extensible e.g. if anyone ever needs the same control for, for example, [feature names](https://www.w3.org/TR/mediaqueries-4/#mq-features) then they can add that in like so:

```json
{
  "unit-blacklist": [["%", "px"], {
    "ignoreProperties": {
       "px": ["font-size", "margin"]
    }, 
    "ignoreFeatureNames": {
       "px": ["min-width"] 
    }
  }]
}
```

**Comment by wroughtec** [comment]
Looks good to me 👍

**Comment by jeddy3** [comment]
@davidtheclark If you're happy with this solution I'll mark it up as "help wanted"?

**Comment by davidtheclark** [comment]
Yeah, I think it will work. Good idea.

**Comment by jeddy3** [comment]
@wroughtec Would you like to have a go at contributing this feature? We wrote [a guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) to help people get started with rules. There's [a section](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-options-to-existing-rules) on adding a new option.

The [`block-opening-brace-space-before`](https://github.com/stylelint/stylelint/tree/master/src/rules/block-opening-brace-space-before) rule already has a similar option and you can look to it for help with: [options validation](https://github.com/stylelint/stylelint/blob/master/src/rules/block-opening-brace-space-before/index.js#L39-L45), [conditionals](https://github.com/stylelint/stylelint/blob/master/src/rules/block-opening-brace-space-before/index.js#L57), [tests](https://github.com/stylelint/stylelint/blob/master/src/rules/block-opening-brace-space-before/__tests__/index.js#L60-L78) and [docs](https://github.com/stylelint/stylelint/tree/master/src/rules/block-opening-brace-space-before#optional-options).

If you would like to give it a go, please don't hesistate to ask questions or push up a work-in-progress pull request :)

**Comment by wroughtec** [comment]
I'll give it ago at the weekend. Hopefully I can figure it all out

**Comment by jeddy3** [comment]
Great! Give us a holler if you have any questions.

**Comment by dryoma** [comment]
Just wanted to note this is a good suggestion. Since I first saw CSS linters I've wanted to be able to force unitless `line-height`.

BTW SCSS-lint uses [a whitelist](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyunits) for that.

**Comment by jeddy3** [comment]
> Since I first saw CSS linters I've wanted to be able to force unitless line-height.

@dryoma You can do this already using [`property-unit-whitelist`](https://github.com/stylelint/stylelint/blob/master/src/rules/property-unit-whitelist/README.md#property-unit-whitelist):

```json
{ 
  "rules": {
    "property-unit-whitelist": {
      "line-height": []
    }
  }
}
```

You can use `property-unit-whitelist` and `property-unit-blacklist` to do everything. The proposal in this issue is just to add *an alternative* method for black/whitelisting property value pairs *that makes it a little easier* to blacklist a unit *everywhere except in a couple of cases*. It's a convenience thing.

**Comment by dryoma** [comment]
Thanks @jeddy3 ! I really did miss that rule.

**Comment by davidtheclark** [comment]
@wroughtec Any interest in following up on this?

**Comment by wroughtec** [comment]
@davidtheclark to be honest real life got in the way so have not had a chance to sit down and actually look at this. Definetly a rule I still need If anyone else has the time please feel free to go ahead and build it I am probably at least a couple of months away from having any real free time :(

**Comment by gaidarenko** [comment]
Let me implement this option. Mark this issue as a `wip`.

**Comment by evilebottnawi** [comment]
@gaidarenko fire :smile:

**Comment by jeddy3** [comment]
Done in e0b1d22daa08fcdfd4a722a73a5f7ccc5cd1de16 and e0b1d22daa08fcdfd4a722a73a5f7ccc5cd1de16.
