### ISSUE TITLE
Apology

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#1065]
Sorry for being a jerk. It wasn't right.

I was frustrated over spending a lot of free time on developing something and it not working. It was immature and entitled as hell.

Thanks for your free work on this project.

**Comment by davidtheclark** [comment]
Thanks for the apology. I hope that some of the progress that's been made has helped with fill some of the holes that frustrated you.

**Comment by jeddy3** [comment]
> Thanks for the apology.

Agreed. An apology is never an easy thing to say. 

Quite a few additional contributors have gotten involved in the last couple of months and, with their help, I think the linter has continued to improve.  

My hope for this project is that it simply makes our lives, those of the contributors and those of our fellow CSS developers a little bit easier by reducing some of the burden usually associated with maintaining CSS code. Fingers crossed :)

**Comment by corysimmons** [comment]
Tbh I haven't been keeping track of the project or anything. I just realized I was being a jerk.

Glad to hear the project is going well. I'll resume work on a super thorough/strict ruleset sooner or later. 👍
