### ISSUE TITLE
Put lists of keywords in a single place

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1071]
Scattered throughout the rules are lists of keywords. Units, properties, values, etc. I was thinking it might be a good idea to pull these out and put them in one place. A `keywordLists` directory or something. And we make them maximally reusable. 

I just want to avoid the situation where a list gets updated in one place and should have been but wasn't updated in another.

**Comment by evilebottnawi** [comment]
@davidtheclark How about a separate repository for this?

**Comment by jeddy3** [comment]
This initiative sounds great to me. Perhaps we should also include the color representations for `color-named` in there too?

**Comment by jeddy3** [comment]
Here's what I've found so far:

- [ ] known units [ref](https://github.com/stylelint/stylelint/blob/master/src/utils/isKnownUnit.js)
- [ ] property shorthands [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-shorthand-property-overrides/shorthands.js)
- [ ] animation shorthand keywords [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/no-unknown-animations/index.js#L18)
- [ ] animation name keywords [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/no-unknown-animations/index.js#L24)
- [ ] level 1 pseudo elements [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-pseudo-class-case/index.js#L15)
- [ ] operators [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/value-keyword-case/index.js#L17)
- [ ] named colors representations [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/color-named/representations.js)
- [ ] font family keywords [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/font-family-name-quotes/index.js#L15)
- [ ] ignore property value combinations [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-ignored-properties/index.js#L15)
- [ ] weight keywords [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/font-weight-notation/index.js#L19)
- [ ] media feature punctuation [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/media-feature-no-missing-punctuation/index.js#L15)
- [ ] selector combinators [ref](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-combinator-space-after/index.js#L16)

Is this what you had in mind @davidtheclark?

Some, e.g. level 1 pseudo elements, are already duplicated across a couple of rules. So this does feel like a worthwhile initiative.

**Comment by evilebottnawi** [comment]
@davidtheclark i think we should done this to v7, also https://github.com/stylelint/stylelint/issues/1101 done to v7

**Comment by davidtheclark** [comment]
Why, if these are not breaking changes?

**Comment by evilebottnawi** [comment]
@davidtheclark be good complete this issue, since they are already well hang time
