### ISSUE TITLE
All rules have default "error" level severity

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [stylelint/stylelint#1075]
>Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request: 

I think it would be great if the default configuration could specify a severity for each rule, instead of just setting [`"error"` for all of them](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#severities-error--warning).

Not all rules are errors, some are minor warning (like the maximum number of blank spaces). In my opinion, the default configuration should have a severity set intelligently for each rule.

This would probably be trivial to implement by adding an extra configuration option for each rule. I'm not sure where to put it, I haven't studied the code much, but if I decide it bothers me a lot I'll likely submit a PR. 

I'm using the latest version,`5.4.0`.

**Comment by jeddy3** [comment]
@The-Penultimate-Defenestrator Thanks for the suggestion.

> I think it would be great if the default configuration could specify a severity for each rule

By "default configuration" are you referring to the [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) shareable config? If so, we can certainly discuss (over in that repo) whether there is value in adding severities other than "error" to that configuration object. 

If you're suggesting a default severity on a per-rule basis *within stylelint*, then can you go into a bit more detail about how this might work? There are rules who's severity isn't immediately obvious and would likely be decided by the user: [`selector-class-pattern`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-class-pattern/) (and the other `*-pattern` rules) and [`unit-blacklist`](https://github.com/stylelint/stylelint/tree/master/src/rules/unit-blacklist) (and the other `*-black/whitelist` rules) spring to mind.

**Comment by The-Penultimate-Defenestrator** [comment]
Sorry, yes. I am indeed talking about the standard config. Didn't realize it had a second repo.
