### ISSUE TITLE
selector-pseudo-class-no-unknown

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1098]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

with option `ignore` for custom pseudo classes (from postcss plugins).

**Comment by jeddy3** [comment]
Sgtm.

- Name: `selector-pseudo-class-no-unknown`
- Primary option: `true`
- Secondary options: `ignorePseudoClasses: []` (user defined array of custom pseudo classes)
- Message: "Unexpected unknown pseudo-class selector"

Lets make sure we include all the [Level 4 selectors](https://drafts.csswg.org/selectors-4/).

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/1223
