### ISSUE TITLE
selector-pseudo-element-no-unknown

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1099]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

https://github.com/stylelint/stylelint/issues/1098

**Comment by jeddy3** [comment]
Sgtm.

- Name: `selector-pseudo-element-no-unknown`
- Primary option: `true`
- Secondary options: `ignorePseudoElements: []` (user defined array of custom pseudo elements)
- Message: "Unexpected unknown pseudo-element selector"

Lets make sure we include all the [Level 4 selectors](https://drafts.csswg.org/selectors-4/) and also account for [Level 1 & 2 pseudo elements](https://drafts.csswg.org/selectors-4/#pseudo-element%20syntax).

**Comment by evilebottnawi** [comment]
Close. Merged. Ref: https://github.com/stylelint/stylelint/pull/1158
