### ISSUE TITLE
start rule documentation

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#11]
Anybody have a preference about whether documentation for rules goes in the Readme or in a separate `rules.md` file?

I guess I'm leaning towards `rules.md` myself.

I could get that started.

**Comment by MoOx** [comment]
I think we should put doc of a rule in `src/rules/*/README.md` or `src/rules/*/index.md`
Each folder in `src/rules` is kind a standalone this way.
Then we will be able to get all of thoses for a generated doc on the website.

**Comment by davidtheclark** [comment]
I like the idea of having relatively standalone rules, I think. But for docs I'd much rather build a markdown document that is easy to navigate & provides a useful doc *now* and then if we do break it into isolated parts do so once there actually is a website alternative.

**Comment by MoOx** [comment]
We can also just build a md from multiples md.

**Comment by davidtheclark** [comment]
True, that's a possibility.

**Comment by MoOx** [comment]
(I am going to do that for cssnext cause the README is just a pain to maintain)

**Comment by jeddy3** [comment]
Can we close this now?

When the time comes to, and if there is a need to, build one big md from the individual rule README's, we can open a new issue.  Sound good?

**Comment by MoOx** [comment]
If you are ok with `src/rules/*/README.md` yep :)

**Comment by jeddy3** [comment]
I am :)
