### ISSUE TITLE
Error: Column start (15) greater than line length (13)

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#1100]
Please see https://github.com/AtomLinter/linter-stylelint/issues/166#issuecomment-212704696 for details and links to files.

**Comment by evilebottnawi** [comment]
@smlombardi Can you formalize issue as template and show example code with issue?

**Comment by smlombardi** [comment]
[http://cl.ly/1X2R2Q1C0p36/documentation.scss](http://cl.ly/1X2R2Q1C0p36/documentation.scss) is the file. 

I deleted the semicolon at the end of line 27. stylelint and scss-lint report the error in the status bar correctly. I put the semicolon back and I get

````
Error: Column start (4) greater than line length (2)
    at Object.rangeFromLineNumber (/Users/stevelombardi/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/stevelombardi/.atom/packages/editorconfig/node_modules/lazy-req/index.js:20:26
    at createRange (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:41:10)
    at /Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:80:14
    at Array.map (native)
    at stylelint.lint.then.error.type (/Users/stevelombardi/.atom/packages/linter-stylelint/lib/index.js:76:38)
````
and the line where the error was is still underlined and the error remains in the statusbar, although it's now fixed.

**Comment by Arcanemagus** [comment]
I've minimized this down to the following setup: [stylelint_GH1100.zip](https://github.com/stylelint/stylelint/files/230416/stylelint_GH1100.zip)

Looks like it's a bug in `max-empty-lines`, but not the `CRLF` one fixed in v6.0.3.

**Comment by evilebottnawi** [comment]
@smlombardi what version stylelint you use?

**Comment by Arcanemagus** [comment]
@evilebottnawi Assuming they were keeping their `linter-stylelint` package up to date, v6.0.1 would probably have been the initial version.

As you can see above though, this is present in v6.0.3.
