### ISSUE TITLE
declaration-colon-* rules should ignore sass lists

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1116]
Ref: https://github.com/stylelint/stylelint/issues/767#issuecomment-213773506

Scss [lists](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#lists) don't contain colons and so aren't picked up the `cssDeclarationIsMap` util.

**Comment by jeddy3** [comment]
@thasmo Thanks for raising the original issue. Subscribe to this issue if you want to keep track of when this fix will be released :)

**Comment by thasmo** [comment]
Thanks! You subscribed me by mentioned me. :)

**Comment by thasmo** [comment]
Just for the record - if it's relevant - lists can be defined in [several ways](http://hugogiraudel.com/2013/07/15/understanding-sass-lists/).

**Comment by jeddy3** [comment]
That's crazy....

I don't think it'll be possible to distinguish something like this from a standard declaration:

```scss
/* Nested lists without braces using different separators to distinguish levels */
$list: "item-1.1" "item-1.2" "item-1.3", 
       "item-2.1" "item-2.2" "item-2.3",
       "item-3.1" "item-3.2" "item-3.3";
```

And so I think we should probably leave the Pull Request as it is for now.

Thanks for the heads up though :)

**Comment by thasmo** [comment]
It's eihter a list if the value is wrapped in parentheses or if there are no parentheses but a comma-separated value. So matching the `$`, a colon and checking if there are either parentheses or commas in the value should do it. One case which would be harder to detect is if the value is actuall a string containing a comma, like `$var: "value, value";`.

**Comment by thasmo** [comment]
Throwing in some thoughts. What if parentheses get ignored by `declaration-colon-newline-after`? I'm new to using `stylelint`, so I don't know if this has any implications on other declarations. Not sure if this would make it more unstable tho.

**Comment by thasmo** [comment]
> What if parentheses get ignored by declaration-colon-newline-after?
If the property starts with a `$`.

**Comment by davidtheclark** [comment]
> I'm wondering whether we should just say that any declaration who's "property" starts with a "$" is either a map, list or variable and therefore should be ignored by the declaration-colon-* rules.

I like this idea. 

All the Sass exceptions are starting to make me crazy.

**Comment by jeddy3** [comment]
> I like this idea.

Groovy. I'll update the PR accordingly tomorrow.

> All the Sass exceptions are starting to make me crazy.

Agreed. Going forward I think we should try to find the broadest ways of ignoring non-standard syntax when confronted with similar issues.
