### ISSUE TITLE
selector-pseudo-class-black/whitelist

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1119]
From [a comment](https://css-tricks.com/stylelint/#comment-1601121) on the css-tricks article.

Funnily enough, I was thinking we should probably have a rule for (dis)allowing specific pseudo-class last night when working through `selector-no-qualifying-type`. And then that comment appeared :)

- [x] Name: `selector-pseudo-class-whitelist`
- [x] Name: `selector-pseudo-class-blacklist`
- Primary options: `["string", "/regex/"]`
- Secondary options: none
- Message: `Unexpected pseudo-class selector "${selector}"`.

Any objections to the proposals?

**Comment by davidtheclark** [comment]
I like it. Do you want to respond to that comment or should I?

**Comment by jeddy3** [comment]
> Do you want to respond to that comment or should I?

Do you mind doing it? I'm about to crash for the night :)
