### ISSUE TITLE
.stylelintignore should be respected when —config is used

### ISSUE THREAD

**Issue by ndarville** [stylelint/stylelint#1127]
I’ve started exploring a `node_modules/` workflow where I define my configs in a separate repo and install it with npm.

This means I currently have:

1. `.stylelintrc` in `node_modules/style/css/.stylelintrc`
2. `.stylelintignore` in root

* * *

> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When I specify a config in the CLI, `.stylelintignore` in root is ignored.

> What stylelint configuration is needed to reproduce this issue?

You can see the [full project](https://github.com/ndarville/style/) (aside from `.stylelintignore`), if you want. `.stylelintrc` is in /css/, and the `.stylelintignore` there is just an empty placeholder that isn’t loaded by stylelint automatically anyway; I’ve tested.

`.stylelintignore`: 

```
static/css/pesticide.scss
static/css/print.scss
static/css/reset.scss
*.min.css
```

> Which version of stylelint are you using?

`6.1.0`.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint foo.css bar/baz.css —config node_modules/style/css/.stylelintrc`.

> What did you expect to happen?

I expect the files specified in `.stylelintignore` to not be linted—ie ignored.

It works, when I use a `.stylelintrc` in root (instead of `node_modules/style/css/.stylelintrc` and don’t specify a config in the CLI (`stylelint foo.css bar/baz.css`).

> What actually happened (e.g. what warnings or errors you are getting)?

The files in `.stylelintignore` are linted—ie not ignored.

PS: I consider this a bug first of all, but a CLI arg for specifying the location of the ignore file, too, would be dope.

<3

**Comment by jeddy3** [comment]
@ndarville Thanks for the detailed report. I'm going to label this as "needs investigation". Feel free to dig around in the code yourself though.

**Comment by davidtheclark** [comment]
What if we made this happen:

By default we look for `.stylelintignore` in `cmd` (the dir you ran the command from), no matter what. Otherwise (like [ESLint](http://eslint.org/docs/user-guide/command-line-interface#ignoring-files)) you could use an `--ignore-path` variable to specify the file.

Sound good?

**Comment by ndarville** [comment]
Fine by me. :)

**Comment by davidtheclark** [comment]
Seems important. Adding this to 7.0 milestone.
