### ISSUE TITLE
Utility for finding functions in values by name

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#114]
This will be needed by a few rules, e.g. `function-calc-operator-*` and a bunch of `color-no-*` rules.

**Comment by MoOx** [comment]
Maybe you can check code of https://github.com/MoOx/reduce-function-call

**Comment by MoOx** [comment]
Using balanced-match will probably helps a lot.

**Comment by davidtheclark** [comment]
Thanks for the suggestions. I'll look into that stuff.

**Comment by davidtheclark** [comment]
Done with `functionArguments()`
