### ISSUE TITLE
Only display the ignored file info message when the verbose formatter is used

### ISSUE THREAD

**Issue by juliancwirko** [stylelint/stylelint#1144]
Is there a way to disable warnings about ignored files? I mean this line: https://github.com/stylelint/stylelint/blob/master/src/postcssPlugin.js#L41 

If there are many ignored files this is quite ureadable in the console output.

**Comment by jeddy3** [comment]
Ref: https://github.com/stylelint/stylelint/pull/1064#issuecomment-212968037

We should only display this information when the verbose formatter is used. Marking this as "help wanted". @juliancwirko Feel free to jump in :)

**Comment by davidtheclark** [comment]
I think this is important. I'm going to add it to the 7.0 milestone.

**Comment by jeddy3** [comment]
Agreed.

**Comment by davidtheclark** [comment]
Closed by #1384.
