### ISSUE TITLE
Export `codeFilename` as CLI parameter

### ISSUE THREAD

**Issue by xswordsx** [stylelint/stylelint#1145]
[ESLint's CLI](http://eslint.org/docs/user-guide/command-line-interface) has a `stdin-filename` parameter which lets you easily integrate it for a pre-commit hook. It would be very nice to have it here as well.

The Node API [has this option](https://github.com/stylelint/stylelint/issues/722).

**Comment by davidtheclark** [comment]
OK. Since the Node API already has the option, adding it to the CLI should be easy.
