### ISSUE TITLE
Error no longer showing in  sublime Text 3

### ISSUE THREAD

**Issue by wroughtec** [stylelint/stylelint#1146]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Since the update to version 6 errors are no longer showing in the UI of Sublime text 3

> Which rule, if any, is this issue related to?

Everything

> Which version of stylelint are you using?

e.g. `6.2.2`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

via sublime text 3

Have mentioned in the repo for this for sumblime text 3:
https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/issues/27?_pjax=%23js-repo-pjax-container

Its probably something missing from the sublime side but thought it was worth mentioning in here encase someone knows what the issues is.

**Comment by davidtheclark** [comment]
I think you nailed it here: https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/issues/27#issuecomment-214746528 That was a breaking change, so SublimeLinter needs to change to accommodate that.

**Comment by davidtheclark** [comment]
Even if that's not the issue, though, unless the same issue can be reproduced in the CLI it the problem almost certainly restricted to the Sublime Text plugin.
