### ISSUE TITLE
Set option syntax based on file extension

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1154]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

We have many issue when people forget set syntax option, it is good to add this feature. For less and scss.

**Comment by evilebottnawi** [comment]
@davidtheclark @jeddy3 ping

**Comment by davidtheclark** [comment]
Seems like a good idea to me, and I can't right now foresee any downside.

**Comment by evilebottnawi** [comment]
@davidtheclark Most of the issues related to the fact  that people simply forget to specify the syntax, it probably would reduce the number of these issues

**Comment by jeddy3** [comment]
> Most of the issues related to the fact that people simply forget to specify the syntax, it probably would reduce the number of these issues

Agreed.

- `.less` - Less
- `.scss` - SCSS
- `.sss` - SugarSS

**Comment by Nirazul** [comment]
The only thing I'd do is dropping a notice that syntax was automatically changed to `xy` based on file extension.

**Comment by ntwb** [comment]
Via https://github.com/AtomLinter/linter-stylelint/issues/135#issuecomment-208752902

> So, in total stylelint supports four syntaxes:
>
> > Standard CSS  (default) (files usually has the extensions `.css`, `.pcss` and `.postcss`)
> > SCSS (files usually has the extension `.scss`)
> > Less (files usually has the extension `.less`)
> > SugarSS (files usually has the extension `.sss`)

**Comment by jeddy3** [comment]
> Via AtomLinter/linter-stylelint#135 (comment)

Yep, it would use the standard parser *unless* the file has a `.less`, `.scss` or `.sss` file extension.

**Comment by davidtheclark** [comment]
Closed by #1154.
