### ISSUE TITLE
selector-attribute-operator-whitelist/blacklist

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1163]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Allow enable and disable some operators

**Comment by davidtheclark** [comment]
Can you describe why someone would want this? The use-case?

**Comment by evilebottnawi** [comment]
@davidtheclark disable usage `*=`, because he was poor perfomance

**Comment by evilebottnawi** [comment]
@davidtheclark also other can disable all `~=`, `|=`, `^=`, `$=` and `*=` operators for best perfomance

**Comment by davidtheclark** [comment]
I guess, if people do that. (Seems like an unnecessary optimization to me.)

**Comment by evilebottnawi** [comment]
@davidtheclark difficult to control when many people to working on project, we spent a lot of time to catch these selectors

**Comment by jeddy3** [comment]
>  difficult to control when many people to working on project, we spent a lot of time to catch these selectors

I'm fascinated by your situation @evilebottnawi as you've alluded to being part of large team e.g. requesting the `*-case` rules as divergences were in an issue. Do you mind me asking how big your CSS code base is and how many people touch it? 

I don't mind seeing this rule in core. It's on the outside edge of "control what languages features can be used" use-case, but it seems useful to teams who want to be very specific about what features are whitelisted.

**Comment by evilebottnawi** [comment]
@jeddy3 The main problem is not really in the amount of teams, but because we work and help the students (they do a lot of stupid mistakes) in the future to invent them in the members of our team, and for me stylelint like a breath of fresh air, I'm saving both a lot of time .

**Comment by evilebottnawi** [comment]
@jeddy3 ping

**Comment by jeddy3** [comment]
>  but because we work and help the students (they do a lot of stupid mistakes)

Oh, it's interesting that you're working with students.

I'm happy to see these rules in core, but lets wait for @davidtheclark say.

As an aside, I think the plan is to focus on closing down a few of the bug issues before adding new rules. In particular, https://github.com/stylelint/stylelint/issues/1173 is pressing.

**Comment by evilebottnawi** [comment]
@jeddy3 i agree with bug must be fixed, just change label

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark  maybe change label :cat:?

**Comment by evilebottnawi** [comment]
@davidtheclark Yet we include these rules into the core (I would be glad if we include these, it is help me work with students, and will not create plugin) or not?

**Comment by davidtheclark** [comment]
Sure, PR welcome.

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/1277
