### ISSUE TITLE
Add an "Articles" section to the docs 

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1172]
I think it would be great to link from stylelint's docs to external articles:

e.g:
• https://css-tricks.com/stylelint/
• http://www.sitepoint.com/improving-the-quality-of-your-css-with-postcss/

Originally Via https://github.com/stylelint/stylelint.io/issues/9

Anyone else have some good, great, exceptional stylelint articles we should include?

**Comment by jeddy3** [comment]
- http://www.creativenightly.com/2016/02/How-to-lint-your-css-with-stylelint/
- https://benfrain.com/floss-your-style-sheets-with-stylelint/

`/docs/user-guide/articles.md`
