### ISSUE TITLE
Update postcss-less version

### ISSUE THREAD

**Issue by webschik** [stylelint/stylelint#1179]
Hi guys! 
I've fixed [some major bugs](https://github.com/webschik/postcss-less/issues/35) in `postcss-less` and released a new version 0.10.0. It would be nice to update it in `Stylelint's` dependencies list to provide working solution for users :)

**Comment by evilebottnawi** [comment]
@webschik thanks

**Comment by evilebottnawi** [comment]
Merged. Close.

**Comment by jeddy3** [comment]
@webschik Thanks again for your continued work on the Less parser! :)

**Comment by webschik** [comment]
@jeddy3 , no problem :) My front-end team are using `Stylelint` for Less, we wanted to have an instrument like this for our Less code, that's why I've started to work on parser.
