### ISSUE TITLE
Update to postcss-selector-parser 2.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1182]
Ref: https://github.com/postcss/postcss-selector-parser/blob/master/CHANGELOG.md#200

**Comment by evilebottnawi** [comment]
> Now parses & as the nesting selector, rather than a tag selector.
Maybe it is allow drop `resolvedNestedSelector`

**Comment by jeddy3** [comment]
> Maybe it is allow drop resolvedNestedSelector

I think that's something different. `resolvedNestedSelector` unravels the nesting selector i.e. `a { &:hover {}}` becomes `a:hover {}`. The change in `postcss-selector-parser` is simply that `&` is now typed as the [*nesting selector*](https://tabatkins.github.io/specs/css-nesting/#nest-selector), rather than a *tag selector*. Which is something we currently [work around](https://github.com/stylelint/stylelint/blob/master/src/utils/isStandardTypeSelector.js#L21).
