### ISSUE TITLE
Evaluate postcss-values-parser

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1183]
Ref: https://github.com/lesshint/postcss-values-parser

e.g. would consistent walk methods across PostCSS, the selector and value parser be useful?:
https://github.com/lesshint/postcss-values-parser/blob/master/API.md#containerwalk-proxies

**Comment by evilebottnawi** [comment]
@jeddy3 look as we can create https://github.com/stylelint/stylelint/issues/1031

**Comment by davidtheclark** [comment]
PostCSS is considering integration of selector and value parsers for v6, so I might want to hold off on switching libraries if we might just switch again soon: https://github.com/postcss/postcss/issues/754

**Comment by evilebottnawi** [comment]
@jeddy3 i think we can close this issue, and wait postcss v6

**Comment by evilebottnawi** [comment]
@jeddy3 close issue?

**Comment by jeddy3** [comment]
> @jeddy3 close issue?

Yep. I'm just working my way down though the issues and I've finally arrived here :)
