### ISSUE TITLE
exact versions for devDependencies

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#12]
What would you think about using exact versions for `devDependencies`?

I have seen and run into problems with CI when using carets for these (CI installs later version than you have locally, that version was improperly versioned so has some breaking change, etc.); and at the same time I don't know of any advantage to using the caret for devDependencies, since people will only install them for development so we don't have to worry about overcomplicated the dependency tree. Seems to me clearer and less error prone to be exact. Thoughts?

**Comment by MoOx** [comment]
See https://github.com/postcss/postcss/issues/312

**Comment by davidtheclark** [comment]
I'm all on board with using carets for `dependencies`, but I still don't see the value in doing it for `devDependencies`, where certainty about which version you, other devs, and CI will be using is more important than the convenience of downloading the new version without knowing. So I'm in agreement with @ai, I think.

**Comment by MoOx** [comment]
Again, I think we should encourage semver, not be afraid of it. And if some package break "all the times" by minor, maybe we should just stop using them :)

**Comment by MoOx** [comment]
Currently, I am pretty confident that babel, eslint and tape follow semver correctly.

**Comment by davidtheclark** [comment]
You have strong feelings so we should just go with them.

**Comment by MoOx** [comment]
Haha. If we got issues in the future, we might reconsider this.

**Comment by davidtheclark** [comment]
Yep, that's what I figure. If we have no problems, then everything's fine!
