### ISSUE TITLE
Integrate bounty label as eslint

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1208]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

As in https://github.com/eslint/eslint
@davidtheclark 
@jeddy3 invite me(https://www.bountysource.com/people/37574-evilebottnawi) in team https://www.bountysource.com/teams/stylelint

**Comment by davidtheclark** [comment]
SGTM

**Comment by davidtheclark** [comment]
Right now the team is not "claimed": it is just open. Is there any reason we should "claim" it?

**Comment by jeddy3** [comment]
> Integrate bounty label as eslint

I'm not sure what you mean? Are we talking about the:

> Want to back this issue? Post a bounty on it! We accept bounties via Bountysource.

That's appeared at the bottom of each new issue? If so, SGTM.

> @jeddy3 invite me(https://www.bountysource.com/people/37574-evilebottnawi) in team https://www.bountysource.com/teams/stylelint

I don't think I'm registered on bountysource.

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark who registered the team)

**Comment by evilebottnawi** [comment]
@jeddy3 add label about bounty and link

**Comment by evilebottnawi** [comment]
claim in progress.

**Comment by davidtheclark** [comment]
What is the status of this?

**Comment by evilebottnawi** [comment]
@davidtheclark 
I was given, if it is necessary to invite someone write nicknames
I create PR today and we can close this issue

**Comment by jeddy3** [comment]
@evilebottnawi I'm "jeddy3" - please invite me as admin.

**Comment by evilebottnawi** [comment]
@jeddy3 Give `Email or PersonID` and i send invite :smile:

**Comment by ntwb** [comment]
Both @davidtheclark & I @ntwb email addresses are on our profiles:
• https://github.com/davidtheclark
• https://github.com/ntwb

@jeddy3 Doesn't list his email address publicly

@evilebottnawi If you add David as an admin then he can (presuming he has Richards email address) then add Richard as an admin 😏

**Comment by evilebottnawi** [comment]
@ntwb i add @davidtheclark already, send you invite.

**Comment by ntwb** [comment]
Sweet, looks good, @davidtheclark if you have @jeddy3's email inviting should be straightforward from the looks of it :)

**Comment by jeddy3** [comment]
I requested an invite via the bountysource website. Hopefully it goes to one of you guys.

**Comment by evilebottnawi** [comment]
@jeddy3 i don't see you invite

**Comment by evilebottnawi** [comment]
@jeddy3 maybe throw email be faster

**Comment by jeddy3** [comment]
@evilebottnawi bountysource@richardhallows.com

**Comment by evilebottnawi** [comment]
@jeddy3 done

**Comment by jeddy3** [comment]
Thanks

**Comment by evilebottnawi** [comment]
@jeddy3 I think we should merge label before close :)

**Comment by davidtheclark** [comment]
Everything seems to be taken care of while I was sleeping. Let me know if you need anything else from me.
