### ISSUE TITLE
declaration-block-no-ignored-properties falls at nested selectors

### ISSUE THREAD

**Issue by dzhiriki** [stylelint/stylelint#1209]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Stylelint crashes on nested selector when `declaration-block-no-ignored-properties` enabled

> Which rule, if any, is this issue related to?

`declaration-block-no-ignored-properties`

> What CSS is needed to reproduce this issue?

```css
.root {
	display: block;

	&::before {
		content: '';
	}
}

```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "declaration-block-no-ignored-properties": true
  }
}
```

> Which version of stylelint are you using?

`6.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to nesting.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

Stylelint crashed.

```shell
TypeError: Cannot read property 'toLowerCase' of undefined
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:34:50
    at Array.forEach (native)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:33:27
    at Array.forEach (native)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/stylelint/dist/rules/declaration-block-no-ignored-properties/index.js:23:15
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:94:28
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:81:26
    at Rule.each (/Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk (/Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:80:21)
    at /Users/dzhiriki/Documents/csssr.ru/node_modules/postcss/lib/container.js:83:32
```

**Comment by evilebottnawi** [comment]
@dzhiriki Thanks for report

**Comment by Zmokizmoghi** [comment]
+1

**Comment by evilebottnawi** [comment]
WIP. Ref: https://github.com/stylelint/stylelint/pull/1210
