### ISSUE TITLE
Use walk* iterators where ever possible

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1211]
I think it'll help mitigate unforeseen problems with nested rules.

`declaration-block-no-ignored-properties` makes use of [`decl.parent.nodes.forEach`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-ignored-properties/index.js#L92).

Perhaps it can be refactored to use `root.walkRules(rule => { rule.walkDecls(decl => {}) })`, similar to how `custom-property-no-outside-root` [does](https://github.com/stylelint/stylelint/blob/master/src/rules/custom-property-no-outside-root/index.js#L18-L30)

It's probably worth doing a quick audit/search of other instance of `forEach` or `each`, to see if their use is avoidable.

**Comment by evilebottnawi** [comment]
@jeddy3 sgtm

**Comment by jeddy3** [comment]
Docs done in https://github.com/stylelint/stylelint/commit/967d480888e066e6ad3e74b74070ab8d0f67e582

Audit looks good.
