### ISSUE TITLE
Be able to filter rules on the website by version

### ISSUE THREAD

**Issue by dan-gamble** [stylelint/stylelint#1228]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

One thing i struggle to do is keep up with Stylelint's quick release cycle. I work at an agency where our projects probably last 6-8 weeks and we do everything based off of a project template (which houses Stylelint). I believe our current project template is still on `3.3.6`.. (:D) and i've recently started a project that was on `5.4.0` and i can see the current version is `6.3.3`.

What would be helpful for me would be to have a dropdown on the rules list with each version number showing the additions / removals etc. of rules so i can quickly update our config. The current way i have to do it is check the releases on Github then go to the site to find the rule and read up on that.

**Comment by evilebottnawi** [comment]
@dan-gamble sound good

**Comment by evilebottnawi** [comment]
I think be cool see near rules version when rule be added.

**Comment by davidtheclark** [comment]
> I think be cool see near rules version when rule be added.

Agreed, @evilebottnawi.

@dan-gamble:

> showing the additions / removals etc. of rules so i can quickly update our config

Doesn't the changelog provide that information?

**Comment by davidtheclark** [comment]
@dan-gamble: Also curious — although I understand *starting* the project from a template, I don't understand why you can't subsequently *update* the dependencies once the project has been started?

**Comment by dan-gamble** [comment]
@davidtheclark Yea the release notes are perfect for it but it involves me having to have 2 tabs and `cmd-f`'ing on the rules page to find the rule and check that (especially new ones). It would be just more of an ease of use thing.

They definitely can, after i made this issue i updated my current `5.4.0` build to `6.3.3` and there were barely any changes. It's more the project template can get neglected if i have to chain jump onto projects so that can end up quite out of date so if i have to initially do the upgrade jump it would be nice to be able to see a clear rule upgrade path :)

**Comment by davidtheclark** [comment]
Using the changelog will be more accurate in the end because it will also include modifications to existing rules. Right?

I don't know ... I'm a little wary of adding additional documentation burden, and additional places for documentation to be inaccurate or out of date, just to avoid `cmd-f`s.

> a dropdown on the rules list with each version number showing the additions / removals etc. of rules so i can quickly update our config.

How are you envisioning it would show the additions/removals (and modifications?)?

**Comment by dan-gamble** [comment]
Tbh a fixed dropdown on http://stylelint.io/user-guide/rules/ in the top right or so that is just a dropdown of the released versions and will filter out the rules that were changed in that version would be a help to me.

Or another alternative could be `[ruleName] - [versionNumberAdded/Reworked]`

i.e.: `font-weight-notation [v6.3]`

Now you mention it showing additions / removals could be potentially hard. 1 idea would be showing the release notes of that version if a version has been chosen in the dropdown but then you are duplicating content which isn't great..

I'll see if i can think up of a graceful way to do it :)

**Comment by evilebottnawi** [comment]
@dan-gamble i think about this changes best see changelog

**Comment by davidtheclark** [comment]
We might be able to automatically create a separate index page that does this, without additional documentation burden. I'm thinking a script could analyze the changelog, which follows some formatting conventions, then create a list of every rule and notes about when it was added, deleted, or modified.

**Comment by dan-gamble** [comment]
That sounds like a good idea, i'm not sure how wide spread this issue is tbh, it's probably a very small minority of people, maybe even just me.. But having the version a rule was added might be of some benefit on the rule page in itself (imo) though.

**Comment by davidtheclark** [comment]
I agree with you, @dan-gamble, and don't think you're the only person who would benefit from this at all.

I'm just very wary of adding more documentation burden and room for error. So I'm all for anything we can automate to make this happen.

**Comment by dan-gamble** [comment]
100% agree :)

**Comment by jeddy3** [comment]
> I'm just very wary of adding more documentation burden and room for error

I'm very much the same. I can see the how we could create something (whether it's a tool or a documentation system) that would benefit users in this situation, but I think the changelog is good enough (and why we maintain one).

New users aren't affect by this and existing users can read the changelog from the version they're upgrading from. We list the new rules at the top of each release changelog.

We can leave this open with a "help wanted" label, but I doubt anything will come of it and so I'm just as happy to see it closed.

**Comment by davidtheclark** [comment]
@dan-gamble Interested in taking this on? If not, I'd agree with @jeddy3 that we should close it, or else it will just sit here and stagnate.

**Comment by dan-gamble** [comment]
Yea i think closing it for now is okay, i'm not sure what type of tool could be built (from my PoV) to aid this. If i can think of something in the future that would help me with this upgrade (if i face it again, again i'm pretty sure i'm in a very small niche for this) i'll shout :)
