### ISSUE TITLE
`declaration-block-no-ignored-properties` now detects use of `min-width` and `max-width`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1230]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

@davidtheclark @jeddy3  ops sorry, accident push in the master branch.
About push:
https://www.w3.org/TR/CSS22/visudet.html#propdef-width
https://www.w3.org/TR/CSS22/visudet.html#propdef-height
https://www.w3.org/TR/CSS22/visudet.html#propdef-min-width
https://www.w3.org/TR/CSS22/visudet.html#propdef-min-height

**Comment by davidtheclark** [comment]
That's commit 4bbba1d61b88f31d99ca4cd3b0029096f672aec4

**Comment by davidtheclark** [comment]
Looks ok to me. Thanks for the heads up.
