### ISSUE TITLE
New rule: no-color-literal

### ISSUE THREAD

**Issue by adidahiya** [stylelint/stylelint#1251]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

New rule called `no-color-literal` to ban custom colors in a stylesheet.

I intend to create this as a custom rule for my project. Our applications depend on a common UI library for defining color variables, so there should be very little need for applications to define custom colors. This rule would be superset of the `color-no-hex` rule -- it would ban all syntaxes for defining colors, including hex, rgb, etc.

### Questions

1. Would you accept this as a core stylelint rule? Are others interested in using it?
2. Any other name suggestions? `no-color` perhaps?

### Notes

It took a little digging to find documentation on custom rules that one might create on a per-project basis. All I could find was some [plugins documentation](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md). Is this the right approach for custom rules that are not part of the stylelint core? If so, some additional docs in the top-level README which use the keywords "custom rules" would be helpful to guide users like me.

**Comment by evilebottnawi** [comment]
@jeddy3 that do you think?

**Comment by mehcode** [comment]
I think that something like https://github.com/kristerkari/stylelint-scss/issues/13 will serve this use case far better.

**Comment by evilebottnawi** [comment]
Yep, out of stylelint.

**Comment by evilebottnawi** [comment]
@adidahiya you can use *=blacklist rules for disable all your need

**Comment by davidtheclark** [comment]
@adidahiya Thanks for the proposal. I agree with the others: because this rule relies on non-standard syntax *only*, it should not be part of core. 

Regarding the terminology "plugin" vs. "custom rule" —— if you'd like to PR an addition to the README that you think would have helped you find the info you needed, go for it. Sounds like a fine idea to me.

**Comment by xereda** [comment]
Any news?

**Comment by rdewolff** [comment]
Does using `color-literal` has any downside ? I couldn't find any info about why use this `no-color-literal` rule.
