### ISSUE TITLE
New rules: media parentheses ...

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#127]
Right now we have in #1 the rule name `media-query-opening-parenthesis-space`.

This would ultimately expand into four rules, I believe, with `-before` and `-after` for the `opening-parenthesis` and another pair for the `closing-parenthesis`.

I'm wondering if we shouldn't instead follow the precedent in `function-parentheses-inside-space` and assume (very reasonably, I think) that people will want the same amount of space on either end of the parentheses. Then we'd create `media-query-parentheses-inside-space` and `media-query-parentheses-outside-space`.

(I can see that somebody *might* want to require a space before but not after the parentheses, in which case that second rule could instead split into the: `media-query-opening-parenthesis-space-before` and `media-query-closing-parenthesis-space-after`.)

**Comment by MoOx** [comment]
> Then we'd create media-query-parentheses-inside-space and media-query-parentheses-outside-space.

no objection :)

**Comment by jeddy3** [comment]
> I'm wondering if we shouldn't instead follow the precedent in function-parentheses-inside-space and assume (very reasonably, I think) that people will want the same amount of space on either end of the parentheses. 

SGTM. Lets stick with that precedent.

**Comment by davidtheclark** [comment]
Closed by d49d125f9dceddc3de3da672d3bfaec2d6a2eecf
