### ISSUE TITLE
Support for either 2 or 4 spaces 

### ISSUE THREAD

**Issue by mikeerickson** [stylelint/stylelint#1270]
Is there a way to allow either 2 or 4 spaces for indentation, or is it one or the other.   I guess I could always remove `indentation` rule and not really worry about?

**Comment by evilebottnawi** [comment]
@mikeerickson 
```json
{
  "rules": {
    "indentation": 2
  }
}
```

**Comment by evilebottnawi** [comment]
@mikeerickson or 4

**Comment by mehcode** [comment]
@evilebottnawi I believe that @mikeerickson is asking for an OR in the linting rules. Which (in my opinion) goes against the very thing linting is built to do, ensure consistency. There isn't a linter for any language that does this that I can recall.

@mikeerickson I'd pick one and just stick with it. If you're converting an existing codebase, look into https://github.com/morishitter/stylefmt

**Comment by evilebottnawi** [comment]
@mehcode misunderstood what you mean, autocorrect?

**Comment by evilebottnawi** [comment]
@mikeerickson you have and 2 and 4 spaces, right?

**Comment by mikeerickson** [comment]
@evilebottnawi I work with code as a team... Some devs use 2 spaces, while others use 4.  Getting them to decide on one is a battle I dont want to have.,   

I think the best way to handle this situation in my case is to just disable the rule.  I always use the same as defined my team lead (2 js, 2 css, 4 php)

:-)

**Comment by mehcode** [comment]
> @evilebottnawi I work with code as a team... Some devs use 2 spaces, while others use 4. Getting them to decide on one is a battle I dont want to have.,

I don't want to press or intrude .. but, this *is* a battle you want to have. Team consistency is key to a long-lived codebase. You don't want to read through a git diff that is 10% bugfix and 90% style _adjustments_ around the bugfix. A team should strive to code as a team. An outsider should not be able to tell (just from reading the code) that more than 1 person worked on it.

Some points to convince your team:
 - Don't come in with a set convention. Start the conversation with "I don't mind what we decide on (2 or 4 spaces, tabs, etc.) but I would like for us to set a standard"

 - State the importance of being able to reliably maintain each other's code. Presumably a team is responsible for the project as a whole. If a member is absent and a feature has to be done, someone else needs to do it. You don't want to have traverse through a mountain of coding style that you're not used to. This works both ways.

 - A strong linter (stylelint, eslint) and a strong formatter (stylefmt, eslint --fix) can do wonders to getting a team on a standard style

**Comment by davidtheclark** [comment]
@mikeerickson If you want 98% of rules to be the same but 2% to have variations, another possibility (besides turning the rule off) is to create a base config that both of the others extend. Team A could extend base and add `indent: 2`. Team B could extend base and add `indent: 4`. (I agree with @mehcode that it's better not to compromise like this; but if necessary `extends` is a powerful option for sharing and varying.)
