### ISSUE TITLE
Add font-family-no-duplicate-names rule

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1284]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new rule to detect duplicate font names used in `font` or `font-family` properties

> Which rule, if any, is this issue related to?

`font-family-no-duplicate-names`

> The following patterns are considered warnings:

`a { font-family: 'Times', Times, "serif", serif; }`
`b { font: normal 14px/32px -apple-system, BlinkMacSystemFont, sans-serif, sans-serif;`

> And the following patterns are **not** considered warnings:

`a { font-family: Times, serif; }`
`b { font: normal 14px/32px -apple-system, BlinkMacSystemFont, sans-serif;`

**Comment by davidtheclark** [comment]
Sure! (I'm assuming this request means you ran across this problem in your codebase?)

**Comment by jeddy3** [comment]
Sgtm.

- Name: `font-family-no-duplicate-names`
- Primary options: `true`
- Secondary options: none
- Message: `Unexpected duplicate name ${name} `
- Section: "Font family" [ref](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#font-family)

I think the rule should be called `font-family-no-duplicate-names` as [it applies](https://www.w3.org/TR/css-fonts-3/#propdef-font-family) to the names within each separate font-family *value*.

**Comment by ntwb** [comment]
> I'm assuming this request means you ran across this problem in your codebase?

Indeed, sneaky little [`sans-serif`](https://core.trac.wordpress.org/changeset/37419) 😏

**Comment by evilebottnawi** [comment]
@ntwb @jeddy3 @davidtheclark  `"sans-serif"` and `sans-serif`(other values too) are difference fonts, it is not correctly, probably is a typo, but you can see this if write css `font-family: "sans-serif"` and then remove quotes(you see what font is really difference).

**Comment by ntwb** [comment]
> "sans-serif" and sans-serif(other values too) are different fonts

Correct, yes, I believe `"sans-serif"` is treated as a different font to `sans-serif`

**Comment by jeddy3** [comment]
> Correct, yes, I believe "sans-serif" is treated as a different font to sans-serif

Lets make sure we account for that in the rule. We should check for duplicates inside of quotes, *unless the font family name is a keyword*.

**Comment by ben-eb** [comment]
Just FYI, this rule should not affect `monospace, monospace`, as specifying this twice corrects rendering issues across browsers. http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/

**Comment by evilebottnawi** [comment]
@ben-eb Thanks for link, but i think it is browser bug and fixed now, btw in chrome 52 not reproduced.

**Comment by ben-eb** [comment]
Some nice details here too. 😄 

https://github.com/necolas/normalize.css/issues/519#issuecomment-197131966

**Comment by ntwb** [comment]
> http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/

One of the many reasons I dislike SEO and their practices, this said post has no date, no comments and makes it impossible to determine if this was posted 10 years ago or yesterday. Hence I place next to zero value on content of this manner.

**Comment by evilebottnawi** [comment]
@ntwb very old post, now it is normalize handle, this rule is good, if you want have two `monospace` fonts, you can used `stylelint-disable` and i think it is right

**Comment by gaidarenko** [comment]
Please label this issue as `wip`.

**Comment by m-allanson** [comment]
@gaidarenko Let's rock
