### ISSUE TITLE
Is v7 the next release?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1294]
@stylelint/core Are we going to get any releases out before v7?

I would say that we should release all the fixes and additions we have now, but for this one:

> Fixed: declaration-block-no-ignored-properties now detects use of overflow, overflow-x and overflow-y with inline elements.

We've determined that that's actually a *breaking change* that should cause a major release. 

So I guess we could either try to move that particular change over to the `v7` branch, or commit ourselves to our next release being v7.

Thoughts?

**Comment by ntwb** [comment]
It has taken me a while to truly grok semantic versioning but now that I do I think it is fine to release all outstanding fixes and additions in a version `7.0.0` release, there doesn't have to be anything _special_ about a new `X.0.0` release, its just a number used by machines...

**Comment by evilebottnawi** [comment]
@davidtheclark i agree with @ntwb

**Comment by jeddy3** [comment]
> there doesn't have to be anything special about a new X.0.0 release, its just a number used by machines...

I agree with this.

**Comment by davidtheclark** [comment]
Well, I mostly agree. It's not just used by machines, though: it's used by people upgrading dependencies. And a major upgrade means they need to put more work into figuring out what changed and whether it affects them. Major releases is that they are typically more annoying to users — that's why it's better not to have a ton of them.

After all the above, though — is what ya'll are saying that we should make v7 the next release? Because if so we should just merge the v7 branch into this one, mark milestones, etc.

**Comment by jeddy3** [comment]
> Major releases is that they are typically more annoying to users — that's why it's better not to have a ton of them.

Good point.

> Fixed: declaration-block-no-ignored-properties now detects use of overflow, overflow-x and overflow-y with inline elements.

How difficult is it to pull this fix out of `master` and into the `v7` branch? If it's not difficult then I think we can continue using the `v7` branch for breaking changes/fixes (there's a few issues with the `7.0.0` milestone that can be worked on leisurely), as it seems to be the best balance between work for us and work for the users.

**Comment by davidtheclark** [comment]
I can try this later tonight.

**Comment by ntwb** [comment]
> How difficult is it to pull this fix out of master and into the v7 branch? If it's not difficult then I think we can continue using the v7 branch for breaking changes/fixes (there's a few issues with the 7.0.0 milestone that can be worked on leisurely), as it seems to be the best balance between work for us and work for the users.

Right, I think now that we are a little more conscious of breaking changes we *could* hold off on a v7 release until there are a few more breaking changes to release in v7 and continue for now with a few more minor 6.x.x releases until that time.

**Comment by davidtheclark** [comment]
I think I took care of it (with the pending PR). Please review, and if you feel like it's suitable maybe cut a release with the bug fixes and feature additions?

**Comment by ntwb** [comment]
:+1:
