### ISSUE TITLE
Docs: Support `stylelint-plugin` and `stylelint-config` package keywords

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1298]
Currently an unofficial practice is to label stylelint plugins in `package.json` with the keyword `styelelint-plugin`, likewise for shared configs with `stylelint-config`, we should document this and make these as a standard for stylelint plugins and shared configs

Tasks `stylelint-plugin`:
- [ ] Add docs and link to https://www.npmjs.com/browse/keyword/stylelint-plugin on the http://stylelint.io/user-guide/plugins/ page
- [ ] Document `stylelint-plugin` on http://stylelint.io/developer-guide/plugins/

Tasks `stylelint-config`:
- [ ] Add docs and link to https://www.npmjs.com/browse/keyword/stylelint-config on the http://stylelint.io/user-guide/configs/ page **
- [ ] Document `stylelint-config` on http://stylelint.io/developer-guide/configs/ ** 

** Note: Both http://stylelint.io/user-guide/configs/ and http://stylelint.io/developer-guide/configs/ document pages currently don't exist though my thinking is they should

**Comment by jeddy3** [comment]
I agree we should add documentation to the developer guides.

We need to discuss the benefits of having a curated list of plugins and configs though.

The only reasons I can see for preferring a curated lists over the ones generated automatically by [npmsearch](http://npmsearch.com/?q=stylelint-config) are:

1. We get to vet and bless those that appear on the curated lists.
2. We can group and categorise items within the curated lists.

This, for me, rules out having a list of configs as neither of those reasons add much.

I can see the benefit for plugins though.

What do we think?

**Comment by davidtheclark** [comment]
Agreed, I'd be interested in curating a plugin list but not a config list.

**Comment by ntwb** [comment]
Cool 👍
