### ISSUE TITLE
Deprecate hierarchicalSelectors option in indentation

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1309]

**Comment by evilebottnawi** [comment]
@jeddy3 I support this idea.

**Comment by davidtheclark** [comment]
Agreed.

**Comment by jeddy3** [comment]
Closed in #1333

**Comment by cmalven** [comment]
I'm sure you had a good reason to remove this rule way back when, but we just started implementing stylelint for our team and the lack of this feature means we can't lint for indentation on any of our projects. Anybody aware if a community-backed plugin for this has popped up? I can't seem to find one.

**Comment by jeddy3** [comment]
> I'm sure you had a good reason to remove this rule way back

It was a seldom-used feature that was complex and difficult to maintain in core.

> Anybody aware if a community-backed plugin for this has popped up?

I'm not aware of one. Feel free to create a [plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) for this (using the [removed code](https://github.com/stylelint/stylelint/pull/1385/files#diff-6e0886c2e5740536e1cdb6a69210e694) as a foundation), and then share it with the community [via the list of plugins](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md).

**Comment by cmalven** [comment]
Yep, I'd probably want to get rid of that code, too. Thanks for the tip and the code reference. Pretty short on extra time right now so we'll probably just disable the indentation rule, but if I find myself in need of a side project in the near future I'll look into doing this.
