### ISSUE TITLE
New rule: selector-attribute-quotes

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#131]
In #1 we have three options: double, single, none (corresponding to `string-quotes`).

However, I wonder if "none" is a good option to have. I just read https://mathiasbynens.be/notes/unquoted-attribute-values about it, and it seems that it would not be a good idea to blanketly enforce no quotes around attribute values, because that's not always going to be work.

So if a person wants to use no quotes *sometimes*, they would need either
1. to not use this rule; or
2. to have a rule that forces her to use no quotes *whenever it's valid to do so* but then forces her to use quotes (either single or double) when no quotes is invalid.

Case 1 is the easy way out for the linter. If we want to allow case 2, I think we could do it as follows:
- Four options: double, single, none-or-double, none-or-single
- If user picks a "none-or-*" option, we find selector attributes values and check whether each would be valid without quotes (via regex described in the article); if it would be valid without quotes, expect no quotes; and if it would not be valid, expect the `-or-*` mark designated.

Thoughts?

**Comment by MoOx** [comment]
I would only implement case 1 for now. I think someone which want to lint case 2 is not born yet (I really hope so) :D

**Comment by jeddy3** [comment]
> I would only implement case 1 for now.

SGTM :)

**Comment by davidtheclark** [comment]
Closing this following discussion in https://github.com/stylelint/stylelint/issues/96
