### ISSUE TITLE
declaration-block-max-empty-lines

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1312]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

What do you think about this? If we deprecated "group objects", this support control count empty lines.

**Comment by davidtheclark** [comment]
Could you explain why you want this instead of using `max-empty-lines`?

**Comment by jeddy3** [comment]
@evilebottnawi Is `declaration-empty-line-before: "always"|"never"` what you're after? 

We have two sets of rules for controlling empty lines: the `*-empty-line-before` and the `*-max-empty-lines` rules. 

The `*-max-empty-lines` are used when the *thing* can't be broken down into smaller pieces (e.g. a function or selector). As a *block* can also contain nested rules and at-rules, then I think `declaration-empty-line-before` would be more appropriate.

**Comment by evilebottnawi** [comment]
@jeddy3 how about `declaration-empty-line-after`?

**Comment by jeddy3** [comment]
`*-before` is the convention.

**Comment by evilebottnawi** [comment]
@jeddy3 Can give example in code?

**Comment by jeddy3** [comment]
@evilebottnawi https://github.com/stylelint/stylelint/blob/master/src/rules/rule-nested-empty-line-before/README.md#except-first-nested

**Comment by jeddy3** [comment]
Closing this in favour of this functionality being covered by a `block-structure` plugin.
