### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by vn38minhtran** [stylelint/stylelint#1316]
After upgrade `stylelint` to version 6.4.x my project throw error when buid.
Error:
```
Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/home/.../node_modules/stylelint/node_modules/babel-polyfill/lib/index.js:12:9)
...
```
My project use `stylelint` via [stylelint-webpack-plugin](https://github.com/vieron/stylelint-webpack-plugin) with webpack@1.x and babel@5.x

**Comment by evilebottnawi** [comment]
@vn38minhtran can you show package.json with dep and devDeps?

**Comment by vn38minhtran** [comment]
@evilebottnawi My project base on my [starter](https://github.com/vn38minhtran/react-flux-starter).

**Comment by evilebottnawi** [comment]
@vn38minhtran try to add `babel-polyfill` to package.json

**Comment by MoOx** [comment]
The change come from #1264. This is a serious problem.

This change creates a real problem. babel-polyfill **must be only included once only** in a process (otherwise, babel throw an error). Now that you included it, all projects that include it too (example phenomic does this) are broken (don't understand: it's your fault, cause phenomic does the same right now).
I think we should remove it in all project that might be used in other user process to avoid this issues. Any thoughts?

**Comment by vn38minhtran** [comment]
@evilebottnawi I installed 'babel-polyfill' and import it on [`app.js`](https://github.com/vn38minhtran/react-flux-starter/blob/v1/app/app.js#L1) instead of `babel-core/polyfill` but error still appears.

Git diff
```
diff --git a/app/app.js b/app/app.js
index 88389dd..28b9b12 100644
--- a/app/app.js
+++ b/app/app.js
@@ -1,4 +1,4 @@
-import 'babel-core/polyfill';
+import 'babel-polyfill';
 
 import React from 'react';
 import ReactDOM from 'react-dom';
diff --git a/package.json b/package.json
index 137a88c..1f6d642 100644
--- a/package.json
+++ b/package.json
@@ -23,6 +23,7 @@
     "babel-eslint": "^4.1.8",
     "babel-loader": "^5.4.0",
     "babel-plugin-react-transform": "^1.1.1",
+    "babel-polyfill": "^6.9.0",
     "babel-runtime": "^5.8.38",
     "clean-webpack-plugin": "^0.1.9",
     "css-loader": "^0.23.1",
```

**Comment by davidtheclark** [comment]
Ugh. I seriously regret having this codebase in ES2015, compiled with babel, and this is the latest serious annoyance it causes ... Sounds to me like what you propose @MoOx is the only viable option.

So in stylelint we need to remove the polyfill and remove all uses of spread.

**Comment by evilebottnawi** [comment]
@vn38minhtran version of node?

**Comment by evilebottnawi** [comment]
@davidtheclark why use ECMA6 if we dropped this feature?

**Comment by evilebottnawi** [comment]
@davidtheclark Who said that the problems are only with spread?

**Comment by evilebottnawi** [comment]
And i think it is bug in babel and we report about this and wait answer before do this.

**Comment by vn38minhtran** [comment]
I use node v4 and I think issue can be solved if we safely require babel-polyfill 

```js
if (!global._babelPolyfill) {
   require('babel-polyfill');
}
```

**Comment by evilebottnawi** [comment]
@davidtheclark what do you think about above solution? Looks good.

**Comment by MoOx** [comment]
I think babel-polyfill is the culprit. It should be able, like all polyfill to detect and adjust the definition. This behavior (from a user point of view) is just stupid.

@vn38minhtran did you try this? If so why this simple hook is not included in the polyfill itself?!

**Comment by vn38minhtran** [comment]
@MoOx 
No I didn't. I just search with key `only one instance of babel-polyfill is allowed` and view some results.
- https://github.com/ParsePlatform/parse-server/issues/1520
- https://phabricator.babeljs.io/T1019
- https://phabricator.babeljs.io/T1943
- https://phabricator.babeljs.io/T2931

**Comment by davidtheclark** [comment]
Sure, if it works, I'm fine with it.

**Comment by MoOx** [comment]
This workaround don't works for me, now I have an error like if babel polyfill was not included :/

**Comment by evilebottnawi** [comment]
@MoOx you try to reinstall node modules?

**Comment by MoOx** [comment]
I am having a fresh node modules. This error occures for me when I run all tests of phenomic.

**Comment by evilebottnawi** [comment]
@MoOx can you create repo to reproduce this error, solution above work fine for me too.

**Comment by MoOx** [comment]
```
git clone https://github.com/MoOx/phenomic.git
cd phenomic
npm i
npm test
```

**Comment by MoOx** [comment]
I clean travis cache and restarted the build on travis https://travis-ci.org/MoOx/phenomic/builds/131184110

**Comment by MoOx** [comment]
Boom :) https://travis-ci.org/MoOx/phenomic/jobs/131184111#L2655

**Comment by davidtheclark** [comment]
@evilebottnawi to answer your question above: we know that only the spread operator requires us to use the polyfill because it's documented here: https://babeljs.io/docs/usage/caveats/

**Comment by MoOx** [comment]
Otherwise, you can cherry-pick require polyfill (eg: Array.from)

**Comment by davidtheclark** [comment]
That is a good point!

**Comment by MoOx** [comment]
Do you need a hand on this? This issue is blocking me for cutting a release :)

**Comment by davidtheclark** [comment]
I can get to it tonight but not right now.

**Comment by jeddy3** [comment]
I've got to hit the hay now I'm afraid. If you do get around to it tonight @davidtheclark, feel free to merge and release without review.

**Comment by MoOx** [comment]
No rush from my side, I am going to bed and won't cut a release until tomorrow :)
Thanks for you hard work!

**Comment by vn38minhtran** [comment]
Thanks!
