### ISSUE TITLE
Cannot read property 'toString' of undefined: selector-no-vendor-prefix with a missing semicolon followed by a nested block

### ISSUE THREAD

**Issue by kevinkorngut** [stylelint/stylelint#1347]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A missing semicolon is causing a `TypeError: Cannot read property 'toString' of undefined` to occur when followed by a nested block.

> Which rule, if any, is this issue related to?

This might relate to #1346 and what was done to fix #1153  

> What CSS is needed to reproduce this issue?

```css
.hello-world {
  max-width: 95vw

  & div {
    display: block;
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

```
{
  extends: [
  ],
  rules: {
    "selector-no-vendor-prefix": true
  }
}
```

> Which version of stylelint are you using?

`6.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI `stylelint '*.css' --verbose`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

It may have to do with the line being followed by a nested block; but I'm not sure.

> What did you expect to happen?

Not to see an error.

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
TypeError: Cannot read property 'toString' of undefined
    at /Users/kevin/Code/personal/react/lint_test/node_modules/stylelint/dist/formatters/stringFormatter.js:138:87
    at /Users/kevin/Code/personal/react/lint_test/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/Users/kevin/Code/personal/react/lint_test/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/Users/kevin/Code/personal/react/lint_test/node_modules/lodash/lodash.js:12254:24)
    at calculateWidths (/Users/kevin/Code/personal/react/lint_test/node_modules/stylelint/dist/formatters/stringFormatter.js:137:22)
    at /Users/kevin/Code/personal/react/lint_test/node_modules/stylelint/dist/formatters/stringFormatter.js:158:5
    at Array.map (native)
    at formatter (/Users/kevin/Code/personal/react/lint_test/node_modules/stylelint/dist/formatters/stringFormatter.js:150:41)
    at /Users/kevin/Code/personal/react/lint_test/node_modules/stylelint/dist/formatters/stringFormatter.js:12:15
    at Array.reduce (native)
```

**Comment by jeddy3** [comment]
@kevinkorngut Thanks for the detailed report. This bug was actually related to the formatter. 

Without the trailing semicolon PostCSS doesn't parse the following as a declaration followed by a rule, [but rather](https://astexplorer.net/#/nmyFjMlrWB) a single rule with `max-width: 95vw\n\n & div` as its selector:

```css
.hello-world {
  max-width: 95vw

  & div {
    display: block;
  }
}
```

And that information is normally passed to the formatter. But a bug in the formatter meant it crashed instead of showing the warning.

There's [a pending PR](https://github.com/stylelint/stylelint/issues/1358) to fix the bug.
