### ISSUE TITLE
Add formatter tests

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1359]
Similar to [this](https://github.com/jeddy3/stylelint-formatter-yhw/tree/master/__tests__)? To avoid issues like https://github.com/stylelint/stylelint/issues/1347

**Comment by jeddy3** [comment]
@evilebottnawi If you get the itch to work on stylelint over the next couple of weeks, feel free to take a stab at the [improving our test coverage and integration tests](https://github.com/stylelint/stylelint/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+tests%22).

**Comment by davidtheclark** [comment]
Yep. I think our two biggest priorities at this point should be:

- Close out existing PRs.
- Create integration tests.

**Comment by jeddy3** [comment]
Agreed.

**Comment by evilebottnawi** [comment]
@jeddy3 ok

**Comment by jeddy3** [comment]
[This is how eslint](https://github.com/eslint/eslint/blob/master/tests/lib/formatters/stylish.js) tests their string formatter.
