### ISSUE TITLE
Create article about writing plugins

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#1371]
I think we should write a article about writing a custom rules for Stylelint and send it to Smashing Magazine or CSS Trick.
1. What is Stylelint
2. Modular philosophy
3. Some examples with local company rules
4. Good advices about CI. Like “if you saw this issue twice in code review, create a tool to find it again” or “don’t use a code style rules, that can’t be checked by program”.
5. How to write a rule with Stylelint

I think custom rules is a very big benefit of Stylelint. And we could promote it from this way too.

Also it will give us more rule developers, so Stylelint will be even smarter.

@davidtheclark you are really great in technical writing.

@hudochenkov you also had successful experience in articles

**Comment by evilebottnawi** [comment]
@ai sounds great

**Comment by hudochenkov** [comment]
I can't help with that, because I never wrote a custom rule for stylelint, and never faced 4th problem :(

**Comment by jeddy3** [comment]
Perhaps the [`stylelint-scss`](https://github.com/kristerkari/stylelint-scss) developers fancy giving it a shot as they've been nailing plenty of plugins recently. Either way, perhaps we can close this issue as such a guide will probably come around naturally (like @hudochenkov's smashing magazine one did) when their is a will for it. (We're trying to reduce the burden of triaging issues).

In the meantime, we have our own [internal documentation](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md).

**Comment by ai** [comment]
@jeddy3 this issue is not about docs, but about promotion

**Comment by davidtheclark** [comment]
Haha, @ai is just a better marketer than us, @jeddy3!

**Comment by jeddy3** [comment]
Just saw this tweet: https://twitter.com/src_contribute/status/808012959473664000

Sounds promising :)

**Comment by davidtheclark** [comment]
I don't have the time to write such an article right now, so I'm going to close the issue. If a stylelint user wants to write this articles, three cheers for them!
