### ISSUE TITLE
Ensure clarity and consistency in "newline" expectations

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1374]
Re: https://github.com/stylelint/stylelint/pull/1258/files#r63021519

It may be that we just have to refresh our memories — but I wonder if this is a generally undocumented detail: rules that check for a newline often seem to expect a *single newline only*, complaining about multiple newlines (empty lines). For examples, just check a bunch of `*-newline-*` rules.

We need to make sure that this detail is documented. If the rule expects a *single* newline, it should say so. Whether or not we document that multiple newlines are possible might depend on the rule.

While working on this documentation we should double-check the rules to ensure consistency and sanity.

**Comment by ntwb** [comment]
SGTM

**Comment by jeddy3** [comment]
Ouch. We should definitely double-check things for consistency and sanity. In my head I thought *all* the `*-newline-*` rules check for *one or more* newlines, as it's the responsibility of the `*-empty-line-before*` and `*-max-empty-lines` rules to control empty lines.
