### ISSUE TITLE
Add Options: true to each no- rule's README

### ISSUE THREAD

**Issue by s10wen** [stylelint/stylelint#1380]
https://github.com/stylelint/stylelint/blob/master/src/rules/color-no-invalid-hex/README.md

I'm guessing this should be `"color-no-invalid-hex": true,`?

Would be nice if all the rules showed an example value? If so I can create a PR for this.

**Comment by s10wen** [comment]
or is there another place where all the rules / values are that I've missed?

**Comment by m-allanson** [comment]
Hey @s10wen, yes that's correct. There's a small example config in the [config section of the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md) that might be useful. 

And you can find some more comprehensive config examples below:

- an [example config that includes every rule](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/example-config.md)
- the [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) project for some sensible defaults

Does that help?

**Comment by s10wen** [comment]
I missed the 'every rule example' that's perfect, thanks 👌🏻

**Comment by jeddy3** [comment]
I'm going to reopen this as it's a legitimate documentation issue.

I think each of the `no-*` rules documentation should explicitly state that their primary option is `true`. I think that the missing primary option is a legacy of the old numeric severity system, where rules could be "turned on" using a severity. Whereas now they must be configured with a primary option.
