### ISSUE TITLE
no-extra-semicolons line number is incorrect

### ISSUE THREAD

**Issue by epmatsw** [stylelint/stylelint#1382]
With stylelint 6.5.1 and stylelint-config-standard 8.0.0, the `no-extra-semicolons` rule appears to return the wrong line number for errors.

The following styles:
```
div a {
    float: left;
}

div {
    float: left;;
}
```
triggers an error at line 2, column 15, when the error is at line 6 column 15 (or maybe 14?).

**Comment by m-allanson** [comment]
I can replicate this issue, marking as a bug.
