### ISSUE TITLE
Features list for no-unsupported-browser-features

### ISSUE THREAD

**Issue by nathanjessen** [stylelint/stylelint#1388]
For the rule, no-unsupported-browser-features, the documentation should be updated to link to the features.js file in the doiuse repo. Or the warning for this rule should output the feature name needed in the ignore array.

Replicating the issue:
The warning says something like:
"Unexpected browser feature CSS Appearance not supported by: ... (no-unsupported-browser-features)"

So I would put "CSS Appearance" in the list of ignored features in the stylelint config. However, this did not allow me to ignore this feature. I had to track down the code in the features.js file of a dependency's repository.

The warning message would be more useful if it said something like:
"Unexpected browser feature 'css-appearance' not supported by: ... (no-unsupported-browser-features)"

**Comment by jeddy3** [comment]
> "Unexpected browser feature 'css-appearance' not supported by ... (no-unsupported-browser-features)"

Yep, that's exactly what we should be aiming for here.
