### ISSUE TITLE
Deprecate the exposure of styleSearch

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1396]
- [x] Deprecate in `master`
- [x] Remove in `v7` branch.

Include suggestion to extract `styleSearch` into its own npm module if you currently use it within deprecation warning.

Ref: https://github.com/stylelint/stylelint/issues/1365#issuecomment-223814080

**Comment by jeddy3** [comment]
@davidtheclark I could do with your advice on this one. Is is possible to add a deprecation notice to styleSearch only when it's used via a plugin and not internally?

**Comment by davidtheclark** [comment]
I have an idea that will be more effective to try out in code than to write out in sentences, so I'll give it a go ...

**Comment by davidtheclark** [comment]
Well ... I actually don't have an idea that will be reported well, like the other deprecations, without a huge pain (because it is not passed the PostCSS Result to attach warnings to). I think that it's probably fine to just *document* this deprecation and its existence as an external module, and then document its removal in the changelog. Do you disagree?

> Include suggestion to extract styleSearch into its own npm module if you currently use it within deprecation warning.

Aren't we going to do that ourselves, and use it in stylelint?

**Comment by jeddy3** [comment]
> I think that it's probably fine to just document this deprecation and its existence as an external module, and then document its removal in the changelog. Do you disagree?

That's what I figured. Just documenting it SGTM.

> Aren't we going to do that ourselves, and use it in stylelint?

Well, I was hoping the first person in the community that needs it does the work of extracting it out (and changing stylelint's code to use the new module).

**Comment by davidtheclark** [comment]
Oh, I see. Eh, I might just pull it out myself to ensure its done right, since it's kind of complex.

**Comment by jeddy3** [comment]
> Oh, I see. Eh, I might just pull it out myself to ensure its done right, since it's kind of complex.

Coolio. Would probably be good to have an example for the community to follow too.

**Comment by davidtheclark** [comment]
@jeddy3 While looking at the code I decided to refactor the options some. What do you think of https://github.com/davidtheclark/style-search? (Not yet released, just WIP)

**Comment by jeddy3** [comment]
Much cleaner! 

Good thinking taking this opportunity to refactor the options, the previous one had become less intuitive as the module had grown and grown in scope.

**Comment by davidtheclark** [comment]
@jeddy3 Want to do a release after these PRs are finished and the feature is deprecated? We have a big chunk of changelog.

**Comment by jeddy3** [comment]
Yep, I was thinking the same and was just going to open a issue about that.

I wouldn't mind discussing https://github.com/stylelint/stylelint/issues/1421 first, as I'd like to roll those deprecation warning in with the next release.

And there's https://github.com/stylelint/stylelint/issues/1101, which @evilebottnawi hopes to get done later.

There are the only two from the [`6.next` milestone](https://github.com/stylelint/stylelint/milestones/6.next) I'd like to see in.

**Comment by jeddy3** [comment]
Done in #1426
