### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#14]
I probably will spend some time writing more rules this coming weekend. I don't know if anybody else was thinking of contributing yet; but I want to make sure we don't overlap efforts. So I was thinking about the following workflow: Before starting work to add a rule, you should open an issue about that rule and state there that you are going to start working on it. If anybody doesn't check the issues before starting a rule and duplicates effort, that's their bad. But this should prevent that.

Sound ok?

**Comment by jeddy3** [comment]
Sounds good to me!

**Comment by MoOx** [comment]
lgtm too !

I also propose:
- this github labels: https://github.com/cssnext/cssnext/labels
- pr all the times with at least 2 go from some "core" members (well we are not too many for now :D)
- a feature: a pr + minor bump (if > 0.x, minor as patch)
- a fix: pr, automerged if needed
- release: proper tag + changelog + github release (fyi, I use this to https://github.com/MoOx/setup/blob/master/functions/npmpublish, kind of oldschool but works like a charm. I generate github release from changelog using this https://github.com/MoOx/setup/blob/master/bin/npmrelease (called from npmpublish)

**Comment by davidtheclark** [comment]
Ok. But @MoOx would you be ok with batching new features more in these early stages?

I have a question, too: I don't know if I've messed with your intended Git workflow already. I see that you created a 0.1.0 branch. How do you want the Git workflow to proceed? (What I'm used to is different, I think, because it's just using master to represent the latest accepted changes, creating feature branches that merge back into master, and tagging releases from master.)

**Comment by MoOx** [comment]
Yeah sure you can push push push :)

I don't really care about branch name. I prefer relying on github labels to sort stuff.
You workflow is totally fine:
- master is only stable (released most of the time)
- we use branch for feature or fix or whatever
- I tag from master using package.json version (I bump version "by hand" when I edit the changelog)

When I push stuff that will not be released asap for some reason, I add edit the changelog prefixed by "HEAD" or "Unreleased".

We can go as you want, we can adjust if we got trouble later ;)
What you are doing is great (start to work on this). Really nice to see someone on this project !!

**Comment by jeddy3** [comment]
And I'm more than happy to follow your two leads on things like issues labels, git workflow and releases.

**Comment by tunnckoCore** [comment]
https://github.com/tj/git-extras

**Comment by MoOx** [comment]
@tunnckoCore very interesting. Thanks for sharing.

**Comment by MoOx** [comment]
@tunnckoCore I just take a quick look to git-extras, and I prefer to fill changelog on each commit with accurate ordered messages (breaking changes first etc). For release I also prefer my simple and stupid script since this one include tests from fresh modules and handle automatic github release from changelog (which is not handled by git extras). It's still interesting tho.

**Comment by davidtheclark** [comment]
I think this discussion has had its start and we'll figure out what works more precisely, if necessary, as we build more.
