### ISSUE TITLE
Help the Bootstrap team try out stylelint

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#1402]
It will be huge affect for Stylelint marketing if Bootstrap will migrate from scss-lint to Stylelint.

We should collect Stylelint over scss-lint benefits:

1. Useful rules for Bootstrap.
2. Easy way to write a new rules to cover Bootstrap specifil cases.
3. Stylelint is more popular than scss-lint. Also we should show big users like 18F (who else?).
4. `stylefmt`
5. Stylelint don’t lock you on one preprocessor.
6 . what other benefits?

Then we should write a good text with all thisbenefits and real examples and create a issue. In that issue we will suggest our help (that we will do all works and send PR if maintainers will be agree).

@davidtheclark @jeddy3 what do you think about it?

We need some leader for this task with good English for communication. Who want to do it?

**Comment by ntwb** [comment]
🙋  I'd be happy to take this on, I've contributed a handful of PR's to and used Bootstrap for years

**Comment by davidtheclark** [comment]
@ntwb Fantastic! Let me know if you need any help.

Another huge benefit, I think, is that the stylelint codebase is JavaScript, instead of Ruby, which will be more familiar to most Bootstrap users and contributors. If they want to contribute to stylelint or write some Bootstrap-specific plugins, JavaScript should be easier for them to deal with.

**Comment by jeddy3** [comment]
I think something that's pretty unique to stylelint is our rules that allow a team to ["Specify acceptable selector types, units, properties, functions and words in comments"](https://github.com/stylelint/stylelint-config-standard#suggested-additions). Being able to whitelist/blacklist these things can really help keep a codebase consistent.

**Comment by ai** [comment]
@evilebottnawi we didn’t prepare a good review. Why you asked Bootstrap team already? ;)

**Comment by evilebottnawi** [comment]
@ai may be they add good point to our discussion

**Comment by evilebottnawi** [comment]
@ai It can guide us on the right path

**Comment by mdo** [comment]
:wave: No pressure y'all! We switched to Stylelint at GitHub (shoutout @jonrohan) and it seems to be going over well. Anything we can do to speed up our builds is super important and high priority to me with Bootstrap. We've seen great improvements on GitHub's builds, so I'm interested in trying it out.

**Comment by evilebottnawi** [comment]
@mdo it is super good, perhaps there are some rules that would be nice to add, we are interested in it.

**Comment by ai** [comment]
@mdo so GitHub uses Stylelint? =^_^=

**Comment by mdo** [comment]
> @mdo so GitHub uses Stylelint? =^_^=

Yup! One of our designers switched us over just a few weeks ago.

**Comment by evilebottnawi** [comment]
@mdo It would be cool if we had a link to us, it would increase the number of contribution. I do not hope so, but it's true it would be cool.

**Comment by jeddy3** [comment]
@ntwb It's great you'd like to head-up this initiative!

You might already be aware of these, but here's a few pointers that could help you on your way:

1. Here's a rather handy guide to [migrating from scss-lint to stylelint](https://github.com/PhilippBaschke/convert-to-stylelint/blob/master/docs/conversion-tables/scss-lint.md).
2. I highly recommend *extend*ing [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) in the config. It's the easiest way to stay up to date with new error-checking rules.
3. The [`stylelint-scss`](https://github.com/kristerkari/stylelint-scss) developers are doing a great job build SCSS-syntax specific rules, while adhering to the stylelint conventions. You might find some very useful rules there.
4. There's a [suggested additions](https://github.com/stylelint/stylelint-config-standard#suggested-additions) section in the `stylelint-config-standard` README that could prove useful. Especially the "Specify acceptable selector types, units, properties, functions and words in comments" set of rules.

Good luck! Ping us when you have something to show as I'm sure we'd all like to see :)

**Comment by ntwb** [comment]
As the 🐱  is out of the 👜  so to speak, I've created https://github.com/ntwb/stylelint-config-bootstrap and this config extends the [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) config.

As it stands it is not much more than a fully functional initial config, it just needs _all the rules_ now.

I'll create some issues over in the [ntwb/stylelint-config-bootstrap](https://github.com/ntwb/stylelint-config-bootstrap/issues) repo, some issues along the lines of:

* Publish to NPM an initial 0.0.0-alpha version of `stylelint-config-bootstrap` so it can be shared, tested, or contributed to publicly

* Convert the current twbs/bootstrap SCSS Line config [https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scss-lint.yml](https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scss-lint.yml) to a styellint config in [ntwb/stylelint-config-bootstrap/blob/master/index.js](https://github.com/ntwb/stylelint-config-bootstrap/blob/master/index.js)

* Update and contribute any changes back to the [migrating from scss-lint to stylelint](https://github.com/PhilippBaschke/convert-to-stylelint/blob/master/docs/conversion-tables/scss-lint.md) guide 

* Create and/or acquire some Bootstrap example SCSS to write tests against

* Create _stylelint_, or _stylelint-scss_ issues as they arise

* Create a _work in progress_ pull request for Bootstrap's `v4-dev` branch

* ... and whatever else comes to mind...

**Comment by davidtheclark** [comment]
Fantastic plan 🍩

**Comment by ntwb** [comment]
Progress is full steam ahead: https://github.com/ntwb/stylelint-config-bootstrap/issues/1

• Less than a dozen outstand rules grok
• Around ten new rule idea/proposals to document and create for stylelint/stylelint-scss combined

**Comment by jeddy3** [comment]
Looking good! :)

**Comment by jeddy3** [comment]
I had a chance to look through the closed issues in your `stylelint-config-bootstrap` repo and "Looking good!" doesn't really do it justice! It looks like you've put in lots of legwork on this one, and it's looking great :)

**Comment by ntwb** [comment]
Thanks, @PhilippBaschke's scsslint to stylelint has been tremendously helpful and a great head start

**Comment by jeddy3** [comment]
@ntwb Is this blocked because of https://github.com/ntwb/stylelint-config-bootstrap/issues/9?

**Comment by ntwb** [comment]
> @ntwb Is this blocked because of ntwb/stylelint-config-bootstrap#9?

No, just time, I've not had much of it this past week, hopefully this week I can get it sorted

**Comment by jeddy3** [comment]
Coolio, no rush. Just doing to issue house-keeping :)

It looks like [they've started migrating to stylelint already](https://github.com/twbs/bootstrap/pull/20332). Woohoo! Their config seems to contain their preferred property order, which should help us resolve https://github.com/ntwb/stylelint-config-bootstrap/issues/9.

The stylelint migration seems to be bundled in a change in tooling PR. Therefore, perhaps it's best to wait until they finish adding it themselves to their tool chain? We can then suggest merging your config in as I can spot a few benefits in using yours:

- It's a standalone shareable config, and so people building on top of bootstrap can use it to lint their CSS code. (We can suggest moving it to the *twbs* org).
2. It extends `stylelint-config-standard`, giving easier access to the latest error-checking rules.
3. Their config appears to misuse the primer-specific [`stylelint-selector-no-utility`](https://github.com/primer/stylelint-selector-no-utility) plugin. I think this is because they used the github config as a blue print.

What do you think?

**Comment by sendilkumarn** [comment]
great work guys 👍

**Comment by ntwb** [comment]
> It looks like they've started migrating to stylelint already. Woohoo! Their config seems to contain their preferred property order, which should help us resolve ntwb/stylelint-config-bootstrap#9.

I've merged that propert order into `stylelint-config-bootstrap` and cut a new release 0.1.0

> The stylelint migration seems to be bundled in a change in tooling PR. Therefore, perhaps it's best to wait until they finish adding it themselves to their tool chain?

I've just submitted a pull request that switches from the `.stylelintrc` to `stylelint-config-bootstrap` change, quite a minor change in the scheme of things for the original tooling changes in my opinion: https://github.com/twbs/bootstrap/pull/20402

> It's a standalone shareable config, and so people building on top of bootstrap can use it to lint their CSS code. (We can suggest moving it to the twbs org).

Agreed, I've added @mdo to the `stylelint-config-bootstrap` repo and NPM, so moving this to the twbs GitHub org can happen whenever....

> It extends stylelint-config-standard, giving easier access to the latest error-checking rules.

You can see the ~72 rules removed from the `.stylelintrc` file in my pull request [here](https://github.com/twbs/bootstrap/pull/20402/files#diff-a836e63586e010a7586ba2a487fcc3a1)

> Their config appears to misuse the primer-specific stylelint-selector-no-utility plugin. I think this is because they used the github config as a blue print.

I'll look at the rule differences and create some new issues  for rules that were added to `.stylelintrc` vs `stylelint-config-bootstrap` now, all up it's approximately 10 rules with slight differences.

**Comment by jeddy3** [comment]
Excellent work @ntwb!

It looks like any further discussion will be happening in the `bootstrap` and `stylelint-config-bootstrap` repos themselves. So, I'll close this issue.
