### ISSUE TITLE
no-empty-source

### ISSUE THREAD

**Issue by s10wen** [stylelint/stylelint#1404]
Specifically, in my case, I found an empty partial file, in a code base of `.scss` files.

Wondering if it would be useful to be able to check for empty files, `.css` or otherwise.

**Comment by evilebottnawi** [comment]
@s10wen sounds good

**Comment by jeddy3** [comment]
I guess this is something that we can include in `config-standard` as a harmless rule that catches the occasional empty file.

@davidtheclark Any qualms about including this and opening it out to contribution?

**Comment by davidtheclark** [comment]
No qualms.

**Comment by jeddy3** [comment]
@s10wen Please consider contributing this feature. It should be easy to do as examples of everything (docs, tests, 99% of the code etc) you need has already been done in the [`no-missing-eof-newline`](https://github.com/stylelint/stylelint/tree/master/src/rules/no-missing-eof-newline). A [typical new rule PR](https://github.com/stylelint/stylelint/pull/1410) contains additions/edits to 7 files. And there are [step-by-step instructions](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) in the developer guide.

- Names: `no-empty-file`
- Primary options: `true`
- Secondary options: none
- Message: `Unexpected empty file`
- Section: "General / Sheet"

**Comment by evilebottnawi** [comment]
Ref: https://github.com/stylelint/stylelint/pull/1436

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/1436
