### ISSUE TITLE
"Error: Column width must be greater than 0." on OSX

### ISSUE THREAD

**Issue by xPaw** [stylelint/stylelint#1405]
I've enabled OSX testing on Travis on one of our projects, and the builds just fail with the following stacktrace:
```
Error: Column width must be greater than 0.
    at exports.default (/Users/travis/build/thelounge/lounge/node_modules/table/dist/calculateCellHeight.js:48:15)
    at /Users/travis/build/thelounge/lounge/node_modules/table/dist/calculateRowHeightIndex.js:63:73
    at arrayEach (/Users/travis/build/thelounge/lounge/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/travis/build/thelounge/lounge/node_modules/lodash/forEach.js:38:7)
    at /Users/travis/build/thelounge/lounge/node_modules/table/dist/calculateRowHeightIndex.js:54:31
    at arrayEach (/Users/travis/build/thelounge/lounge/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/travis/build/thelounge/lounge/node_modules/lodash/forEach.js:38:7)
    at exports.default (/Users/travis/build/thelounge/lounge/node_modules/table/dist/calculateRowHeightIndex.js:49:27)
    at exports.default (/Users/travis/build/thelounge/lounge/node_modules/table/dist/table.js:128:58)
    at formatter (/Users/travis/build/thelounge/lounge/node_modules/stylelint/dist/formatters/stringFormatter.js:148:33)
```

This error only happens on OSX (travis), but not on Windows or Linux.

Build log: https://travis-ci.org/thelounge/lounge/jobs/136374638
Stylelint config: https://github.com/thelounge/lounge/blob/master/.stylelintrc

**Comment by wizardfrag** [comment]
This test appears to work fine on my local OS X machine (10.11.4)

```
$ node -v
v6.2.1
$ npm -v
3.9.3
$npm test

> thelounge@2.0.0-pre.2 test /Users/david/Projects/thelounge/lounge
> npm-run-all -c test:mocha lint


> thelounge@2.0.0-pre.2 test:mocha /Users/david/Projects/thelounge/lounge
> mocha -r test/fixtures/env.js test/**/*.js



  Chan
    #sortUsers(irc)
      ✓ should sort a simple user list
      ✓ should group users by modes
      ✓ should sort a mix of users and modes
      ✓ should be case-insensitive
      ✓ should parse special characters successfully

  Network
    #export()
      ✓ should produce an valid object

  Link plugin
    ✓ should be able to fetch basic information about URLs (53ms)

  Nickname highlights
    ✓ should NOT highlight nickname
    ✓ should highlight nickname
    ✓ changing name should update regex


  10 passing (81ms)


> thelounge@2.0.0-pre.2 lint /Users/david/Projects/thelounge/lounge
> npm-run-all -c lint:js lint:css


> thelounge@2.0.0-pre.2 lint:js /Users/david/Projects/thelounge/lounge
> eslint .


> thelounge@2.0.0-pre.2 lint:css /Users/david/Projects/thelounge/lounge
> stylelint "**/*.css"



client/css/bootstrap.css
      ℹ  This file is ignored
$ echo $?
0
```

**Comment by evilebottnawi** [comment]
@xPaw please format your issue as template

**Comment by evilebottnawi** [comment]
@xPaw update stylelint to last version, may be in https://github.com/stylelint/stylelint/issues/1198 was fixed.

**Comment by xPaw** [comment]
@evilebottnawi stylelint 6.5.1 does not fix this issue.

**Comment by ntwb** [comment]
> stylelint 6.5.1 does not fix this issue.

I've just created a pull request to see if there any differences between stylelint 6.2.1 and 6.5.1 in the Travis CI job logs

**Comment by ntwb** [comment]
@xPaw All tests passed using stylelint 6.5.1

**Comment by xPaw** [comment]
@ntwb Your PR tests passed cause `master` does not have a config to run OSX builds. I was testing it in a branch: https://github.com/thelounge/lounge/compare/xpaw/travis

**Comment by evilebottnawi** [comment]
@ntwb That do you think it is good add `osx` os to travis build?

**Comment by evilebottnawi** [comment]
@jeddy3 that do you think about add `osx` to travis build?

**Comment by jeddy3** [comment]
> that do you think about add osx to travis build?

I think we need to weigh-up if the extra build time is worth it. And to do that I think we need to get to the bottom of what's causing this crash.

@xPaw It looks like something is causing the string formatter to crash. It's likely one of the rules in your config interacting with a particular line in your CSS. It would be very helpful if you could narrow this down to a small reproducible test case for us.

**Comment by xPaw** [comment]
@jeddy3 It's not really feasible to test 70 unique rules when you have to let Travis build them individually.

**Comment by jeddy3** [comment]
> It's not really feasible to test 70 unique rules when you have to let Travis build them individually.

Good point.

Any ideas how, and in what way, the travis' `osx` environment differs from @wizardfrag's local osx environment?

**Comment by xPaw** [comment]
I really don't know, @astorije said it builds fine for him on OSX too.

**Comment by jeddy3** [comment]
> Could be an issue isolated to travis?

That's possible. Do you want to play around with your [travis settings](https://docs.travis-ci.com/user/osx-ci-environment/)? Perhaps ensuring the latest `xcode` is used?

**Comment by xPaw** [comment]
I added `osx_image: xcode7.3`, it still fails with same error.

https://travis-ci.org/thelounge/lounge/jobs/136932515

**Comment by xPaw** [comment]
Uh oh, this issue does not happen on a new repository with 4 lines of CSS and using `stylelint-config-standard` rules.

https://github.com/xPaw/stylelint-travis-osx-bug
https://travis-ci.org/xPaw/stylelint-travis-osx-bug/jobs/136933689

**Comment by jeddy3** [comment]
@xPaw Very nice. Thank you for putting in the legwork on this one!

**Comment by ltchronus** [comment]
This issue appears in v6.6.0. After debugging for a while, I found that getMessageWidth() returns a negative number. Maybe the reason is that I was using three columns of panes in split view iTerm2 which results in a small process.stdout.columns value.

**Comment by jeddy3** [comment]
@ltchronus Thanks for debugging. I think your problem *is related* to this issue, but perhaps has a different root cause. As such, can you create a new separate issue using our template. We can then hopefully get to the bottom of it.
