### ISSUE TITLE
at-rule-blacklist/whitelist

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1411]
Ref: https://github.com/kristerkari/stylelint-scss/issues/30#issuecomment-223780830

- Names: `at-rule-blacklist/whitelist`
- Primary options: `[ ]`
- Secondary options: none
- Message: `Unexpected at-rule ${name} `
- Section: "At-rules"

**Comment by davidtheclark** [comment]
Closed by #1410.
