### ISSUE TITLE
Create rule testing guide & checklist

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1418]
I think we should try to create a checklist to guide us creating tests for rules. We have a lot of knowledge floating around about best practices (e.g. ensure you're testing errors in multiple positions, not the same place every time), common consideration (e.g. vendor prefixes and variables), and edge-cases (e.g. ensure you're accounting for alternate capitalization). I think we've figured out enough about what *should* be tested that none of us can successfully remember *all* of the details every time — and outside contributors don't stand a chance.

So let's create a guide to testing rules that lists these discoveries. Sound good?

**Comment by jeddy3** [comment]
> I think we've figured out enough about what should be tested that none of us can successfully remember all of the details every time — and outside contributors don't stand a chance.

Very true!

> I think we should try to create a checklist to guide us creating tests for rules

Agreed. We can revise [this section](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#write-tests) of the developer guide.
