### ISSUE TITLE
Align last few rule names with conventions

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1421]
As part of looking through the docs with fresh eyes last week (and for the first time since we started this project), I also got the opportunity to step-back and review all the rule names. They seem remarkable coherent, but I did notice a couple that were wrong (i.e. wrongly *scoped*). I think getting these into `7.0` would be a nice touch as stylelint is starting to feel "finished" (i.e. I think most new stuff can be pushed to plugins) and having everything ship-shape as we move to a more sustainable development pace would be super. If only because I think it'll lead to a slightly better (i.e. consistent) user experience for the next surge of new users.

Anyhow, onto the rules in question...

* `number-zero-length-no-unit`: Disallow units for zero lengths.

I think this should be `length-zero-no-unit`. As I think it should be scoped to the *length* type i.e. a number followed by an optional length unit. It's not just a number, unlike say `number-max-precision` or `number-leading-zero`. It'll also align with any value type specific rules we add in the future (or the community adds as plugins).

And then these four:

* `property-unit-blacklist`
* `property-unit-whitelist`
* `property-value-blacklist`
* `property-value-whitelist`

In a issue or two I've noticed these rules being overlooked. I suspect this is because what the rules actually do is blacklist *declarations* based on the combination of property and unit/value. They're lost within the "Property" section of the list. I've also notice a few plugins adopt this incorrect naming convention for plugins that disallow specific property and value combinations.

I think these rule should be scoped to `declaration`. This will also help to distinguish these rules from the `property-whitelist/blacklist` rules, which *are* scoped to just property. So we end up with:

* `declaration-property-unit-blacklist` etc.

I think once this is done, *all* the rules will follow the same scoping convention. Conventions that seems to holding together well as we've added lots of new rules since first creating the rules listed above.

Thoughts?

**Comment by davidtheclark** [comment]
Yes, good analysis. I agree with your suggested changes.
