### ISSUE TITLE
Release 6.next

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1429]
Once [milestone issues](https://github.com/stylelint/stylelint/milestones/6.next) are done.

**Comment by jeddy3** [comment]
@davidtheclark Once my [pending PRs](https://github.com/stylelint/stylelint/pulls?q=is%3Apr+is%3Aopen+label%3A%22PR%3A+review+needed%22+author%3Ajeddy3) are in. I think we can release `6.6`. I'll need to clean-up the changelog once the PRs are merged, but other than that I think things are looking pretty ship-shape.

Sound good?

**Comment by evilebottnawi** [comment]
We can do release :tada:

**Comment by jeddy3** [comment]
@davidtheclark Actually, can I get your thoughts on https://github.com/stylelint/stylelint/issues/1439 first. As that will require a deprecation warning that I'd like to include in `6.6`.

**Comment by evilebottnawi** [comment]
@jeddy3 https://github.com/stylelint/stylelint/issues/1438 made too?

**Comment by jeddy3** [comment]
@davidtheclark and @evilebottnawi Shall I release once the CLI changes are in?

**Comment by davidtheclark** [comment]
Yes. This is plenty for one release :) We can still do another release before v7 if needed.

**Comment by evilebottnawi** [comment]
@jeddy3 yes

**Comment by jeddy3** [comment]
🎉

Congrats everyone! Thanks for all your hard work on this release :)

- [stylelint@6.6.0](https://github.com/stylelint/stylelint/releases/tag/6.6.0)
- [stylelint-config-standard@9.0.0](https://github.com/stylelint/stylelint-config-standard/releases/tag/9.0.0)
- http://stylelint.io/ updated

**Comment by davidtheclark** [comment]
Thanks for doing the release @jeddy3 !

**Comment by ntwb** [comment]
Thanks everyone 💯
