### ISSUE TITLE
Support prefixed property and at-rules in all rules.

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1437]
Two step:
- [x] Add tests to some rules for check they support vendor prefix value (merge in master)
- [x] Add support prefixed property, value and etc in all rules (merge in v7)
  - keyframe-declaration-no-important
  - no-unknown-animations
  - time-no-imperceptible

For other issue and PR:
 - [x] Recheck on support case insensitivity
  - number-max-precision (import)
  - function-linear-gradient-no-nonstandard-direction (add flag `i` to `isStandardDirection`) and to check `deg`, `grad`, `rad`, `turn` (line 34)

I think it is breaking changes and should completed in v7.
Example https://github.com/stylelint/stylelint/blob/master/src/rules/no-unknown-animations/index.js#L28 we see only `keyframes`, `kEyFrAmEs`, `KEYFRAMES`, but not see on `-webkit-keyframes` and etc.

**Comment by jeddy3** [comment]
This issue is for the work started in https://github.com/stylelint/stylelint/pull/1278, right?

**Comment by evilebottnawi** [comment]
@jeddy3 right, in order not to forget and put v7 milestone.

**Comment by jeddy3** [comment]
Agreed.

**Comment by evilebottnawi** [comment]
@jeddy3 @ntwb @davidtheclark I checked all the rules twice, but still fear miss, it would be great if you ran bu code the second eyes, see first post (above) that i found

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/1591#issuecomment-230872130
