### ISSUE TITLE
Use -v as an alias for --version (instead of --verbose) in the CLI

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1439]
And move `--verbose` into `-f`/`--formatter` options.

This latter change will align the CLI with the [Node API](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#formatter).

This would be for `v7`, although the deprecation would happen in `6.next`.

Related to https://github.com/stylelint/stylelint/issues/1438

**Comment by davidtheclark** [comment]
Common practice I've seen is to use `-v` as alias for `--verbose` and `-V` as alias for `--version`.

Do you mean creating a new `--formatter` keyword like `string-verbose`?

**Comment by jeddy3** [comment]
> Do you mean creating a new --formatter keyword like string-verbose?

Yep, in the [Node API](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#formatter) we have the following options: "string", "json" and "verbose".

In the CLI we have the following `--formatter` options: "string" and "json". Whereas "verbose" is available under a separate flag. So, I was suggesting creating a new `--formatter` keyword as `verbose`.

> Common practice I've seen is to use -v as alias for --verbose and -V as alias for --version.

You're more well-versed in this things than I am, so happy to follow your recommendation on this though. I was going off how eslint [does it](http://eslint.org/docs/user-guide/command-line-interface).

**Comment by davidtheclark** [comment]
Ok, let's
- [ ] deprecate the `--verbose` flag 
- [ ] add a `verbose` option for `--formatter`

That SGTM
