### ISSUE TITLE
support `--ignore-path` to load all ignored from `.gitignore` 

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1452]

**Comment by jeddy3** [comment]
You can do that already, right?

```console
stylelint css/*.css --ignore-path .gitignore
```

I tried it locally (with `-f verbose`) and it worked fine.

**Comment by evilebottnawi** [comment]
@jeddy3 
```shell
stylelint '**/*.{css,scss}' --syntax scss --ignore-path .gitignore
```
and in .gitignore
```
build/*
```
But i get error in in files inside build directory, strange, Tomorrow i investigation this.

**Comment by evilebottnawi** [comment]
@davidtheclark i think we should more best solution, maybe not `minimatch`.
```shell
stylelint '**/*.{css,scss}' --syntax scss --ignore-path .gitignore
```

Composer packages in (some packages have *.css)
```.gitignore
lib/vendor
build
```
But file located in `lib/vendor/some/path/to/style.css` and `minimatch` return false on this check.
But if i change `lib/vendor/**` all work fine. Also this happened with `build` directory.

**Comment by davidtheclark** [comment]
Know of a module we can use to interpret the syntax of `.gitignore` files? If so, it's worth looking into.

**Comment by ntwb** [comment]
I'm pretty sure ESLint has most of this functionality, maybe even more...

> > Know of a module we can use to interpret the syntax of .gitignore files? If so, it's worth looking into.

> Globs are matched using [node-ignore](https://github.com/kaelzhang/node-ignore), so a number of features are available:
> Ignore patterns behave according to the `.gitignore` [specification](http://git-scm.com/docs/gitignore)

It's probably worth reading the ESLint docs on their implementation and to scope out this stylelint funcionality along the same lines: [docs/user-guide/configuring.md#ignoring-files-and-directories](https://github.com/eslint/eslint/blob/master/docs/user-guide/configuring.md#ignoring-files-and-directories)

**Comment by jeddy3** [comment]
Shall we swap in [node-ignore](https://github.com/kaelzhang/node-ignore) in `v7`?

**Comment by davidtheclark** [comment]
Ok, thanks everybody. Closing this in favor of #1498.
