### ISSUE TITLE
Add custom Facebook rules to core

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#1472]
We should start to looking into companies configs and copy custom rules to core. For example [Facebook](https://code.facebook.com/posts/879890885467584/improving-css-quality-at-facebook-and-beyond) has interesting ideas.

**Comment by jeddy3** [comment]
> We should start to looking into companies configs and copy custom rules to core.

I think there is merit to this initiative, as long as we are *very selective* about what gets pulled into core. We had some [recent](https://github.com/stylelint/stylelint/issues/1308#issuecomment-220208911) [discussions](https://github.com/stylelint/stylelint/issues/1238#issuecomment-219236893) about the sustainability of development. These accumulated into the decision to [remove some features](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md) in `7.0` and push a number of proposed rules and options [to plugins](https://github.com/stylelint/stylelint/issues?q=label%3A%22type%3A+plugin%22+is%3Aclosed).

I think it's important that we don't lose sight of this decision and slip back into unsustainable development.

As such, we developed a strict criteria for including a rule in core:

- Applicable to standard CSS syntax only.
- Useful to the majority of users.
- Having a clear and unambiguous finished state.

And we decided that everything else would be a community plugin.

As an example, I think Facebook's `slow-css-properties` is great as a plugin as it has an unclear and ambiguous finished state i.e. the performance of properties can evolve over time as changes are made to browser's CSS engines. It'll always need to be adapted and will therefore never be finished.

**Comment by ai** [comment]
@jeddy3 hm. In one hand I agree with you about keeping core simple.

But in other hand I hear many times, that “Stylelint has no real smart rules, it checks only whitespaces”. Of course, it is just “hatters gonna hate” talks, but I think it will be good to show some real powerful rules.

Maybe we should promote some of this useful but not core rules in docs? Should we ask @kangax to open source this rules and add to some list?

Maybe we should promote interesting third-party rules in Twitter? Most of people follow PostCSS twitter because of plugins links.

**Comment by jeddy3** [comment]
What I'm struggling to understand is the *purpose* of actively marketing this project. What is it that we're trying to achieve? 

I think that's the crux of the issue, but I'll try to answer your questions as well:

We have [lots of powerful non-stylistic rules](https://github.com/stylelint/stylelint-config-standard#suggested-additions) in stylelint. My favourites being the 3 that help to control specificity, the 25 that restrict the use of language features (the [most powerful of which](https://github.com/stylelint/stylelint/pull/689) was kindly contributed by @kangax), and the 15 or so\* subtle error checking ones. I don't think we need to spell-out the quality and depth of the rules to users, as this becomes self-evident when the docs are read.

I already [tweet about](https://twitter.com/KristerKari/status/730786235648778241) well-written plugins. I think the amount of overall tweets we've made this last year is indicative of how much effort we've wanted to put into it. We use twitter to notify people of new release, new articles, new well-written plugins and answer the occasional query. I'm not sure what else there is? 

We have a curated [plugin list within the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md). The motivation for that list is [here](https://github.com/stylelint/stylelint/issues/1298#issuecomment-220304864).

There's no requirement to open source stylelint plugins that people or companies write, and I'm cautious to ask anyone to do so as it could create an implied requirement. When there is none.

The other @stylelint/core contributors might feel differently about the points above, but I figured it was worth sharing my thoughts :)

---

\*Some of the subtle error checking rules I dug out:

- `color-no-invalid-hex`
- `declaration-block-no-duplicate-properties`
- `declaration-block-no-ignored-properties`
- `declaration-block-no-shorthand-property-overrides`
- `function-linear-gradient-no-nonstandard-direction`
- `keyframe-declaration-no-important`
- `media-feature-no-missing-punctuation`
- `no-extra-semicolons`
- `no-descending-specificity`
- `no-duplicate-selectors`
- `selector-pseudo-class-no-unknown`
- `selector-type-no-unknown`
- `time-no-imperceptible`
- `unit-no-unknown`

**Comment by ai** [comment]
You really ask why marketing is important for Stylelint? Any open source project will be unknown without good marketing. So marketing is a key to make project popular.

Right now Stylelint twitter account has only 251 followers. It is extremely small for such open source project. [csslint](http://npm-stat.com/charts.html?package=csslint) still have 2x more downloads, than [Stylelint](http://npm-stat.com/charts.html?package=stylelint).

And it could be fixed only with marketing.

**Comment by jeddy3** [comment]
> You really ask why marketing is important for Stylelint?

Yep, that's what I'm asking. Hear me out on this... I understand that marketing would make stylelint more popular, but to what end would we want to do that?

I contribute to stylelint because this tool helps make my day job easier and more enjoyable. The number of twitter followers we have or the number of downloads compared to csslint seems irrelevant to that goal. I understand why someone might want to actively grow a commercial product (for more money), but what's the motivation for an open source project?

Popularity over this last year has been a double-edged sword. We've received more contributions (and gathered an awesome group of contributors!), but we've also had to deal with an overwhelming number of issues and questions. Right now, it feels like we've reached an enjoyable size (of early adopters) where not too many new issues are created and contributors add occasional features that benefit themselves. I'm fearful that becoming more popular (and attracting a larger, less technical user base) could put that delicate balance in jeopardy, and make things less enjoyable.

Perhaps the other contributors have other motivations for their involvement in stylelint, and becoming more popular will help them fulfil what ever they may be. I'm just cautious that we don't create work without first discussing and clearly defining a reason for doing so. Hopefully such a reason will be the product of this issue :)

**Comment by ai** [comment]
@jeddy3 ha, it is a big philosophical question :D.

My motivation is simple: more popular Stylelint → more popular PostCSS → more benefits we all have as popular open source maintainers :D.

But making Stylelint popular is win-win for everyone here. In IT it is easy to use standard tools. And it is very hard to use unpopular tools. If tool is popular, you will have integration in text editors and IDE. You will have more eyes to find issues.

So even you are happy with Stylelint right now, without growing your team was force you to move to some standard tool after few years. Because everyone want to have easy solution and popular solution with big docs, many answers in StackOverflow, many side-tools is always easier.

**Comment by davidtheclark** [comment]
Fun conversation. I understand both sides. Of course the limiting factors are time, energy, and interest. I think that @jeddy3 and I have both been working, in the time we have, on aspects of the project that really interest us. It would be awesome if we had another contributor who was more interested in marketing than we are! I every once in a while muster the energy to write an article, because I find writing interesting ...

The immediate question — whether to add custom Facebook rules to core — I think just has to be decided on a concrete rule-by-rule basis. I agree with @jeddy3 that `slow-css-rules` doesn't really belong in core (at least not unless someone else champions it). I'd have to consider other specifics individually.

@ai I appreciate how you open up tickets with marketing ideas and rule ideas!

**Comment by ai** [comment]
To be clear, I am making this issue not to force you to finish it :). Of course, this task should be done by developers who have interest in it :).

**Comment by ai** [comment]
@kangax so, is it possible to open source your custom rules? They are really interesting and will be important for community. Your can put it in some repo like `stylelint-config-facebook` to save your time.

Of course, it is not a problem if you can’t do it.

**Comment by evilebottnawi** [comment]
@ai i think there a lot of rule we yet need in core. First be good get all popular linters and investigate their for their rules (some rules in stylelint-scss, stylelint-less and etc, maybe add experimental plugins), next write script to translation popular linters config to stylelint config.

**Comment by davidtheclark** [comment]
Good ideas @evilebottnawi!

**Comment by evilebottnawi** [comment]
@davidtheclark I think you need to create a separate issue on the analysis of known popular css, scss, less and etc linters, and then for each to create a more detailed issue(with rules and other stuff) and add milestone to related issues(example `csscomb compatibility`).

**Comment by ai** [comment]
“csscomb compatibility” will be very useful for marketing :smiling_imp:

**Comment by jeddy3** [comment]
@ai Thank you for hearing me out :)

 >  In IT it is easy to use standard tools. And it is very hard to use unpopular tools.

That's a very good point. I now see the longer term benefits i.e. my day job (and I guess everyone else's too) will become easier and more enjoyable :)

I think it's important to remember that we *were* overwhelmed in the last couple of months though, and so I think we need to carefully tread the path to achieving this longer term goal i.e. ensuring we don't make the shorter term unenjoyable.

As such, I'm very much in support of initiatives like [helping the bootstrap team evaluate stylelint](https://github.com/stylelint/stylelint/issues/1402) and [publishing a "how to write a plugin" article](https://github.com/stylelint/stylelint/issues/1371). As these will grow our popularity without adding features to core. 

But, as @davidtheclark said, we need to decide what plugins go into core on *a concrete rule-by-rule basis*. Selectively picking only those that meet the criteria I laid out above.

> The immediate question — whether to add custom Facebook rules to core 

In [my 2nd post](https://github.com/stylelint/stylelint/issues/1472#issuecomment-226442748) I said I was opposed asking for the following reason:

> There's no requirement to open source stylelint plugins that people or companies write, and I'm cautious to ask anyone to do so as it could create an implied requirement. When there is none.

Do you guys feel differently about that? As we've gone ahead and asked them again without further discussion...

> next write script to translation popular linters config to stylelint config.

Agreed, this is a great idea. Perhaps such a thing could be an extension of [this](https://github.com/PhilippBaschke/convert-to-stylelint/blob/master/docs/conversion-tables/scss-lint.md) and live in that separate project.

> I think you need to create a separate issue on the analysis of known popular css, scss, less and etc linters

SCSS issue are tracked in `stylelint-scss` and not here, and so the analysis of SCSS linters can happen there. If you'd like to start an equivalent `stylelint-less` project, that would be awesome. The analysis of less linter can then live there. We can link to it from the "Non-standard syntax -> Plugin packs" section of the plugins list.

Keeping stylelint focus (both code and issues) on standard CSS syntax, and pushing non-standard syntax things to outside the org, was [a decision made](https://github.com/stylelint/stylelint/issues/550#issuecomment-163060940) on the assumption that CSS Processors come and go, but standard CSS is going to be around longer. It also makes for a nice separation of responsibilities :)

**Comment by evilebottnawi** [comment]
@jeddy3 some rules in scss, other syntax work not only for scss, this rules also validate and standard css, so we should started start analyzing here.

**Comment by evilebottnawi** [comment]
@jeddy3 and if rules out of scope stylelint standard create issue in other repo(exaple stylelint-scss)

**Comment by jeddy3** [comment]
> this rules also validate standard css, so we should started start analyzing here.

Sure, create standard syntax rule proposals issues here.

**Comment by evilebottnawi** [comment]
@jeddy3 i think we should create first issue - 'csscomb compatibility' and starting analyzing. csscomb check standard syntax.

**Comment by kangax** [comment]
I'll ask our open source folks on what we need to do to open source them. It might take some time and I'm a little swamped right now. Will do my best.

**Comment by jeddy3** [comment]
@kangax Thanks! Let us know how you get on. I'll close this issue for now as we can always reopen it if you're able to open source them.
