### ISSUE TITLE
More user-friendly message on invalid CLI arguments

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1483]
Strange or invalid error on CLI argument:
- [ ] `--custom-formatter` (need more user-friendly, like do `eslint` - `package not found, maybe you should run npm install stylelint-formatter-test`)
- [ ] `--formatter` (invalid error)
```shell
stylelint '**/*.css' --formatter test
```
```shell
TypeError: chosenFormatter is not a function
    at /home/itgalaxy/web/dev0.cms.dev.itgalaxy.company/public_html/wp-content/themes/insteria/node_modules/stylelint/dist/standalone.js:58:20
```
- [ ] `--ignore-path` (no errors if file not found in path).
```shell
stylelint '**/*.css' --ignore-path fakepath
```
- [ ] `--syntax` (no throw error if syntax incorrectly)
```shell
stylelint '**/*.css' --syntax fake
```

**Comment by jeddy3** [comment]
Are you specifically referring to the error above? The one that is shown when you use specify a formatter other than "string", "verbose" or "json".

Or are you referring to other "invalid CLI arguments" too?

If it's the former, then I'll update the title of the issue. If it's the latter, can you please list all the message which are unhelpful so we can get a better idea of the scope of the issue?

**Comment by evilebottnawi** [comment]
@jeddy3 All arguments, now I'll check them all

**Comment by evilebottnawi** [comment]
@jeddy3 ping

**Comment by jeddy3** [comment]
Thanks for digging deeper. Are those four the only flags that had unhelpful messages?

**Comment by evilebottnawi** [comment]
@jeddy3 It looks like all :) @davidtheclark what do you think?

**Comment by jeddy3** [comment]
> @jeddy3 It looks like all :)

Good stuff. Adding improved messages for this four things sounds like a good idea to me.

**Comment by davidtheclark** [comment]
Sure.
