### ISSUE TITLE
Use `ava` instead `tape` in stylelint-rule-tester

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1484]
`ava` have more user-friendly messages and have some features as `skip`, `todo` and etc, it is helping in testing very well.
@davidtheclark @jeddy3

**Comment by jeddy3** [comment]
Have you investigated if stability/performance has changed since https://github.com/stylelint/stylelint/pull/824?

**Comment by evilebottnawi** [comment]
@jeddy3 intresting, i investigated this in next week and reported all here.

**Comment by m-allanson** [comment]
By default ava's behaviour is "to spin up an isolated process for every test file immediately, and then run all your tests". That might have contributed to the problem of running stylelint's tests with ava :)

ava has an experimental flag to limit the concurrency which might be useful. Check out the ["Limited Concurrency EXPERIMENTAL"](https://github.com/avajs/ava/releases/tag/v0.15.0) section of their 0.15.0 release notes.

**Comment by evilebottnawi** [comment]
@m-allanson so I see the opportunity to test faster and more convenient

**Comment by davidtheclark** [comment]
You can write an Ava runner for the rule testing scheme and see what happens. If you can accomplish the same thing but better, then great.

**Comment by jeddy3** [comment]
> You can write an Ava runner for the rule testing scheme and see what happens. If you can accomplish the same thing but better, then great.

Agreed.

@evilebottnawi Bare in mind that the feature to limit concurrency in ava is *experimental*, and so could be removed at anytime. So, I recommend factoring that into deciding whether you want to put the legwork into this investigation this possible migration or not.

**Comment by evilebottnawi** [comment]
@jeddy3 Most important for me is actually user-friendly output of ava, we should check speed, if speed tape and ava equals, I would go in the direction of ava.

**Comment by davidtheclark** [comment]
You can also try different TAP formatters.

**Comment by davidtheclark** [comment]
I am not sure about the value of leaving this issue open. It's the kind of thing that somebody is welcome to submit as a PR when they can demonstrate that using AVA for stylelint will simplify the code, speed up the tests, improve development, etc. But I don't think there's anything to discuss, really, unless that can be demonstrated. So I'm in favor of closing this.

**Comment by jeddy3** [comment]
> So I'm in favor of closing this.

Agreed. Triaging and tracking issues is time consuming. One less is better in my opinion.

I'm in favour of closing these types of issues with a note explaining what action can be taken next. Like we do with plugins. These closed issued can still be searched through.
