### ISSUE TITLE
Improve visible readability of wrong/correct syntax on stylelint.io

### ISSUE THREAD

**Issue by Nirazul** [stylelint/stylelint#1488]
I'm just linking to a (solved) issue I've created some time ago over at eslint:
https://github.com/eslint/eslint.github.io/issues/108

It's about visually improving code blocks that are currently hard to read whether they are correct examples or failing examples, creating warnings.

I'm not sure how the documentation on the homepage is created, but maybe the solution found on this issue could point you in the right direction.

**Comment by evilebottnawi** [comment]
@Nirazul sound good 
/cc @jeddy3

**Comment by jeddy3** [comment]
@Nirazul Thanks for the suggestion! Can you please recreate this issue over at https://github.com/stylelint/stylelint.io? Also, if you'd like to help us investigate the feasibility using their solution with our tech stack (which look pretty similar), then that'd be greatly appreciated as I agree that visually distinguishing the two types of code blocks would be very useful :)
