### ISSUE TITLE
--ignore-path fails for when --config is defined

### ISSUE THREAD

**Issue by ndarville** [stylelint/stylelint#1492]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where my ignore list is not loaded, when

> Which rule, if any, is this issue related to?

#1127.

> What stylelint configuration is needed to reproduce this issue?

<https://github.com/ndarville/style/blob/bd9f41d96ebc10826ece3501e5aa84ae15cc85fa/css/.stylelintrc>

`.styleignore`:

```
static/css/pesticide.scss
static/css/print.scss
static/css/reset.scss
*.min.css
```

> Which version of stylelint are you using?

`6.6.0` (latest).

> How are you running stylelint: CLI, PostCSS plugin, Node API?

This doesn’t load the ignore list:

```sh
stylelint static/css/*.scss --syntax scss --config node_modules/style/css/.stylelintrc --ignore-path .stylelintignore 
```

This loads the ignore list—difference being the `--config` path in project root instead of `node_modules/`:

```sh
stylelint static/css/*.scss --syntax scss --config .stylelintrc --ignore-path .stylelintignore
```

This also loads the ignore list:

```sh
$ stylelint static/css/*.scss --syntax scss --ignore-path .stylelintignore # no explicit --config
```

    $ diff node_modules/style/css/.stylelintrc .stylelintrc
    [blank]

This happens in a private repo, so I can’t show you the ins and outs beyond that.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SCSS.

> What did you expect to happen?

For my ignore list to be loaded.

> What actually happened (e.g. what warnings or errors you are getting)?

I get warnings and errors for the ignored files.

* * *

I’ve also tried removing `ignoreFiles` in `.stylelintrc`, but that didn’t make a difference. Maybe something fails silently, but it apparently doesn’t make a difference.

* * *

Might be something obvious, but I can’t quite spot it.

<3

**Comment by davidtheclark** [comment]
The intended function is described [here](http://stylelint.io/user-guide/configuration/#stylelintignore):

> If they are relative, they are analyzed relative to
- configBasedir, if it's provided;
- the config's filepath, if the config is a file that stylelint found a loaded;
- or process.cwd().

Are the relative paths in your `.stylelintignore` file written with that in mind?

Do you think there's a more intuitive way to handle relative paths?

**Comment by ndarville** [comment]
The ignoreFile is in the project root (let’s call it `~/projects/myproject/.stylelintignore`), and in case the ignorePath is figured out relative to the configPath, I also tried using `../../../.stylelintignore` for the path, in case it’s computed from the configPath.

`.stylelintignore` is only one in the project root in that whole dir, so there’s no other file that should be matched.

**Comment by davidtheclark** [comment]
I mean, are the paths in `.stylelintignore` relative to *the config file's path*?

**Comment by ndarville** [comment]
Ah, of course. That did it.

```
../../../static/css/pesticide.scss
../../../static/css/print.scss
../../../static/css/reset.scss
../../../*/*.min.css
```

```sh
stylelint -f verbose static/css/*.scss --syntax scss --config
node_modules/style/css/.stylelintrc --ignore-path .stylelintignore
```

Cheers.


On 19 June 2016 at 16:32, David Clark <notifications@github.com> wrote:

> I mean, are the paths in .stylelintignore relative to *the config file's
> path*?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/stylelint/stylelint/issues/1492#issuecomment-227000474>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMIGhDotSuv8Jmjb8Sj3bASsPPmZK97ks5qNVMLgaJpZM4I5BA7>
> .
>



-- 
twitter.com/pessimism
github.com/ndarville
ndarville.com

8ACC 17A5 EA8B BC19 <https://keybase.io/ndarville>
