### ISSUE TITLE
Use node-ignore for ignore patterns instead of globs

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1498]
See discussion at https://github.com/stylelint/stylelint/issues/1452.

**Comment by davidtheclark** [comment]
Turns out this is a pain.

We need to change the structure of what `.stylelintignore` paths are relative to. They need to always be relative to `process.cwd()`, never anything else. I *believe* that's what happens with ESLint and other programs that use `.gitignore` syntax.

Probably that means we need to treat `config.ignorePath` differently from `.stylelintignore` patterns. I guess `config.ignorePath` globs should be minimatch globs (like other globs in the config) and relative to their config file.

I have made some progress on this, but it is annoying so I am probably stopping for the day ...

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1624
