### ISSUE TITLE
stylelint-declaration-block-order

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#1500]
Stylelint doesn't support linting rules structure. I want to add this feature using [PostCSS Sorting](https://github.com/hudochenkov/postcss-sorting). It will require adding linting functionality in PostCSS Sorting, which I'll add when things got clearer :) Also when stylelint can check rule structure, it can be great to integrate PostCSS Sorting in [stylefmt](https://github.com/morishitter/stylefmt).

1. Should I add this functionality as a rule or plugin? If it will be as a plugin, can it be used in stylefmt? Stylefmt support only stylelint's config. /cc @morishitter
2. What name rule or plugin should have? As a plugin name @jeddy3 [suggested](https://github.com/hudochenkov/postcss-sorting/issues/18#issuecomment-223791271) `stylelint-block-structure`.
3. What to do with tests? PostCSS Sorting has [a lot of tests](https://github.com/hudochenkov/postcss-sorting/tree/master/test/fixtures). Should all they be copied to rule/plugin?
4. What to do with options description? Options description is a long document. Should I maintain it in both places (postcss-sorting repository and stylelint/plugin repository)?
5. I have no idea what [primary option](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#primary) should be for this rule.

P. S. Nice issue number :)

**Comment by jeddy3** [comment]
@hudochenkov Thanks for kickstarting the discussion about this! I'll try to answer each of your questions.

> Should I add this functionality as a rule or plugin?

Definitely a plugin. We had some [recent](https://github.com/stylelint/stylelint/issues/1308#issuecomment-220208911) [discussions](https://github.com/stylelint/stylelint/issues/1238#issuecomment-219236893) about the sustainability of development. These accumulated into the decision to [remove some features](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md) in `7.0`, including from the existing `declaration-block-properties-order` rule, and push a number of proposed rules and options [to plugins](https://github.com/stylelint/stylelint/issues?q=label%3A%22type%3A+plugin%22+is%3Aclosed).

> What name rule or plugin should have?

Each rule/plugin follows [these naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#about-rules). `block` is the *thing* that this rule is *scoped* to. I choose `structure` because it's unique in stylelint as no other plugin/rule deals with *both* whitespace *and* the order of things. Perhaps there's a better word for it though?

> What to do with tests? What to do with options description? I have no idea what primary option should be for this rule. 

We can look to the existing plugin [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern) for precedence here i.e. "[just a couple of quick tests to ensure `postcss-bem-linter`
 is getting the hard work done](https://github.com/davidtheclark/stylelint-selector-bem-pattern/blob/master/test/index.js)", docs [that say look at the `postcss-bem-linter` docs for options](https://github.com/davidtheclark/stylelint-selector-bem-pattern#usage), and a primary option that is a object containing what options `postcss-bem-linter` expects.

Right, I think that's probably enough to keep the ball rolling. Anyone else have anything to add?

> P. S. Nice issue number :)

Agreed :)

**Comment by davidtheclark** [comment]
Nothing to add :)

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark  Today I thought about this plugin and concluded: i write some project on pure CSS or cssnext, i don't need this plugin, but i want to control some things:
```css
div {
  // Lines before properties
  display: inline;
  // Lines between properties
  color: red;
  // Lines after properties
}
```
I think plugin `sorting` should control ordering `declaration` and `nested declaration`, but not empty lines in ideal, rule `declaration-block-properties-order` responds only for `order`, not empty lines and i think we should create rules for control empty lines inside `declaration block`. As previously said, some may not need this plugin at all.

**Comment by hudochenkov** [comment]
@evilebottnawi It's impossible to preserve empty lines. For example, there is CSS:

```css
.masthead {


	padding-bottom: 64px;
	padding-top: 34px;

	background: #f3f6f8 url("img/masthead-bg.jpg") 50% 50% no-repeat;

	text-align: center;


	background-size: cover;

}
```

And this `sort-order`:

```json
[
	"padding-top",
	"padding-bottom",
	"background",
	"background-size",
	"text-align"
]
```

I can't even image what output should be with preserved empty lines.

-----------

Maybe you can provide another example for me to understand what use cases do you have?

**Comment by evilebottnawi** [comment]
@hudochenkov i say about if i don't have `sorting` plugin in own config, i need to control some empty lines.

**Comment by evilebottnawi** [comment]
@hudochenkov you plugin can check newlines, people just disable rules about i say above.

**Comment by hudochenkov** [comment]
@evilebottnawi I understand that you want to have rules to control three things:

* Lines before properties
* Lines between properties
* Lines after properties

I understand “Lines before properties” and “Lines after properties”. For example, if `Lines before properties == 2` and `Lines after properties == 1`, this is a valid structure:

```css
div {


	display: block;
	margin: auto;
	background: #ccc;

}
```

But what about “Lines between properties”? With `Lines between properties == 2` this is valid structure?

```css
div {
	display: block;
	
	
	margin: auto;
	
	
	background: #ccc;
}
```

**Comment by evilebottnawi** [comment]
@hudochenkov all right

**Comment by bjankord** [comment]
I'm interested in this functionality to replace scss-lint's [declaration order rule](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#declarationorder), specifically checking the order of @extend declarations, @include declarations without inner @content, properties, @include declarations with inner @content, then nested rule sets.

It seems like [PostCSS Sorting would be able to check the order of at-rules](https://github.com/hudochenkov/postcss-sorting#at-rules), though I'm not familiar enough with PostCSS Sorting to know if it would be able to check the more nuanced @includes deleclartions with and without inner @content.

For people writing scss / using scss-lint, having the ability to lint this with stylelint would be a nice attraction.

**Comment by bjankord** [comment]
In regards to @evilebottnawi comment
> I think plugin sorting should control ordering declaration and nested declaration, but not empty lines 
I like the idea of declaration order and declaration line spaces being two separate linting rules.

I don't think a stylelint rule / plugin should be concerned about preserving empty lines, that sounds more like the functionality of Stylefmt.

Giving this css
```
.masthead {


    padding-bottom: 64px;
    padding-top: 34px;

    background: #f3f6f8 url("img/masthead-bg.jpg") 50% 50% no-repeat;

    text-align: center;


    background-size: cover;

}
```

And this sort order for the stylelint rule / pluign

```
[
    "padding-top",
    "padding-bottom",
    "background",
    "background-size",
    "text-align"
]
```

I'd expect linting errors on the following:

*  `padding-top` expected to be 1st in order
*  `padding-bottom`  expected to be 2nd in order
*  ` text-align` expected to be 5th in order
*  `background-size` expected to be 4th in order

No lint errors around preserving empty lines would be generated from this rule. A separate rule would check for that.

The idea behind this is to keep the order rule simple. Have it do 1 thing and 1 thing well which should make it easier to maintain/test.

Just something to think about.

**Comment by evilebottnawi** [comment]
@bjankord i say about linting empty lines, not correct them(`Stylefmt`). I write pure css and i do not need a plugin for order, only lint empty lines.
> Lines before properties
> Lines between properties
> Lines after properties

**Comment by bjankord** [comment]
> i say about linting empty lines, not correct them(Stylefmt)

@evilebottnawi  Yeah, I agree with that. I'm suggesting consider making two rules: one for empty lines as you describe, and one for order.

**Comment by evilebottnawi** [comment]
@bjankord for order we have rule `declaration-block-properties-order`.

**Comment by bjankord** [comment]
@evilebottnawi True, the declaration-block-properties-order rule works well for property order. However, it does not seem well suited for [ordering items in a declaration block which are not properties](https://github.com/stylelint/stylelint/issues/973), e.g. at rules. 

I'd like to see this plugin take into account ordering nested statements within a declaration block as [described above](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229120741). This is one linting rule scss-lint does really well, but stylelint (stylelint-scss) hasn't achieved. If a plugin was made that would handle this, I think it would be really beneficial and attract people from scss-lint to make the jump to stylelint as well as [help projects like Bootstrap switch from scss-lint to stylelint](https://github.com/stylelint/stylelint/issues/1402).

@jeddy3's [comment](https://github.com/hudochenkov/postcss-sorting/issues/18#issuecomment-223791271) is one that encouraged me to comment here. It sounds like supporting more robust declaration block ordering is something that prompted this issue.

> FYI, in stylelint@7.0.0 we're going to reduce the scope of declaration-block-properties-order to, as the name implies, check only the order of properties within a declaration block. Our hope is that the community develops a more powerful stylelint-block-structure plugin, which is concerned with not only the order of declarations but that of nested (at-)rules, as well as the empty lines between things.

My comment is simply consider making two plugins, one concerned with ordering (including ordering of non-property nested statements) and one to handle [line spacing](https://github.com/stylelint/stylelint/issues/705) [concerns](https://github.com/stylelint/stylelint/issues/752). 

Two plugins seem like they would be easier to maintain / test. 
To your points of only needing a line spacing linter, separating the two concerns into individual plugins would work well for your use case.

> I write pure css and i do not need a plugin for order, only lint empty lines.

You wouldn't have to include a plugin for order.

**Comment by bjankord** [comment]
1 plugin that does both the ordering of properties / nested statements like @extends, @includes, @media etc. and the line space linting sounds good to me too, I'm just trying to emphasize the need for the ordering of properties / nested statements like @extends, @includes, @media etc. functionality.

**Comment by jeddy3** [comment]
@bjankord Thank you for your input. I especially appreciate that you looked through the spider's web of historical issues to get a grip on this :) 

As you can see there are a number of use-cases to consider and fair few competing interests. I think I have a proposal that might be satisfactory to all parties, and I'll try to outline that below.

> My comment is simply consider making two plugins, one concerned with ordering (including ordering of non-property nested statements) and one to handle line spacing concerns...[vs] 1 plugin that does both the ordering of properties / nested statements like `@extends`, `@includes`, `@media` etc. and the line space linting sounds good to me too.

I believe this to be the crux of the issue. We've been very careful in the past to create very focused rules who's functionality *does not* overlap. Currently we already have one sorting rule (for properties), a number of non-overlapping empty line rules and number of non-overlapping newline rules in core. My suggestion is that, where possible, any new plugin complements these existing rules, rather than overlaps them.

I think the following example and config will help us all understand what can be linted with the existing rules, and where there are holes to fill:

```css
/* cssnext example */
a {
  @apply: --my-custom-property-set;
  @apply: --my-other-custom-property-set;

  color: red;
  display: block;

  /* inline comment */
  float: right;
  
  &:hover,
  &:focus {
    background-size: 
      0,
      0;
    color: blue;
  }
  
  /* inline comment */
  @nest .class & { 
     color: green;
     transform: translate(
       1,
       1
     );
  }

  @nest .other-class & { 
     color: yellow;
  }

  @media (width < 10em) {
     & {
       color: blue;
     }
  }
}
```

And with the following abbreviated config:

```json
{
  "rules": {
    "at-rule-empty-line-before": [ "always", {
      "except": [ "blockless-group", "first-nested" ],
      "ignore": ["after-comment"],
    } ],
    "at-rule-semicolon-newline-after": "always",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-space-before": "always",
    "comment-empty-line-before": [ "always", {
      "except": ["first-nested"],
      "ignore": ["stylelint-commands"],
    } ],
    "declaration-block-properties-order": [
      "background-size",
      "color",
      "display",
      "float",
      "transform"
    ],
    "declaration-block-semicolon-newline-after": "always-multi-line",
    "function-comma-newline-after": "always-multi-line",
    "function-max-empty-lines": 0,
    "max-empty-lines": 1,
    "media-query-list-comma-newline-after": "always-multi-line",
    "rule-nested-empty-line-before": [ "always-multi-line", {
      "ignore": ["after-comment"],
    } ],
    "selector-list-comma-newline-after": "always",
    "selector-max-empty-lines": 0,
    "value-list-comma-newline-after": "always-multi-line",
  }
}
```

As you can see, we can already lint the *vast majority* of newlines and empty lines, including:

- Allowing and disallowing empty lines before different types of statements, including options for dealing with blockless at-rules and preceding comments.  
- Limiting the number of empty lines, including within selectors and functions.

And we can lint the order of properties.

So, I think we are only lacking three features:

1. Linting the empty line before the closing brace of a block ([stackoverflow question](https://stackoverflow.com/questions/37487317/how-to-make-stylelint-prevent-an-empty-line-after-the-last-brace-in-a-nested-blo)).
2. Linting the order of non-properties.
3. Linting the empty lines between declarations (and, in a more advanced use-case, between property groups).

I think we can simply address the first one with a new `block-closing-brace-empty-line-before: "always"|"never"` rule. This rule would only check multi-line blocks and check whether the closing brace is preceded by an empty line.

I think the second feature is the responsibility of plugin called `stylelint-block-non-properties-order: []` (and the focus of this issue). The inspiration (and internals) for which could be taken from PostCSS sorting's [at-rule](https://github.com/hudochenkov/postcss-sorting#at-rules), [nested rule](https://github.com/hudochenkov/postcss-sorting#nested-rules) and [variable](https://github.com/hudochenkov/postcss-sorting#variables) options. This plugin would *not* be concerned with any whitespace nor the order of properties. An example rule config for the above CSS example could be:

```json
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      "@apply",
      "declarations",
      "nested-rules",
      "@nest",
      "@media"
     ]
   }
}
```

The above example shows the use of pre-defined keywords (like `"declarations"` and `"nested-rules"`) as well as user-defined at-rule names (like `"@apply"`, `"@nest"` and `"@media"`).

Lastly, I think we can address the simpler use-case of the third feature in core with a new `declaration-empty-line-before": [ "always"|"never", { "ignore": ["after-comment"] } ]` rule ([ref](https://github.com/stylelint/stylelint/issues/1312)).

Whereas, I think linting empty lines *before property groups* should be a plugin as there are all sorts of edge-cases in and around this feature. One option could be a plugin (perhaps called `stylelint-property-group-empty-line-before`) that [builds on top of](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#stylelintrules) `declaration-block-properties-order`. This kind of mixes the concerns of empty lines with ordering, but I can't see away around this in this very specific situation. I'm OK with having the mixing of concerns in community-land, but only if it's absolutely necessary. 

> I'm just trying to emphasize the need for the ordering of properties / nested statements like `@extends`, `@includes`, `@media` etc. functionality.

If we're happy to go down the route I proposed above, then I'll create separate issue for `block-closing-brace-empty-line-before` and `declaration-empty-line-before` rule, and we can keep this issue focused on the ordering of non-properties within a block.

**Comment by bjankord** [comment]
That sounds like a great proposal, I appreciate the thought put into this issue :)

**Comment by evilebottnawi** [comment]
@jeddy3 It would be nice to see the line and emphasizing the conclusion which rules need to implement, as you normally do :smile:

**Comment by jeddy3** [comment]
@davidtheclark Do you have any concerns about this proposal, or shall I create those new issues and get everything written?

**Comment by davidtheclark** [comment]
> a new block-closing-brace-empty-line-before: "always"|"never" rule.

Sounds good.

> plugin called stylelint-block-non-properties-order: []

Sounds good.

> a new declaration-empty-line-before": [ "always"|"never", { "except": ["first-nested"], "ignore": ["after-comment"] } ]

I don't understand the value of this one. Have we seen any requests to enforce an empty line before every declaration?

```css
a {
  
  color: pink;

  background: orange;
}
```

**Comment by evilebottnawi** [comment]
maybe `block-closing-brace-empty-line-before` and `block-opening-brace-empty-line-after`?

**Comment by evilebottnawi** [comment]
With option `"always"|"never"`

**Comment by jeddy3** [comment]
> I don't understand the value of this one. Have we seen any requests to enforce an empty line before every declaration?

You're right. It should be `declaration-empty-line-before": [ "never", { "except": ["first-nested"], "ignore": ["after-comment"] } ]`.

> maybe block-closing-brace-empty-line-before and block-opening-brace-empty-line-after?

We don't have `*-empty-line-after` rules, only `*-empty-line-before` rules. We do this to avoid conflicts. If you look at the example and config above you'll see that, once we have `declaration-empty-line-before": [ "always" ]` done, you'll be able to control (with the use of all the `*-empty-line-before` rules) whether an empty line appears before the first node in a block or not.

I'll create new issues for `declaration-empty-line-before` and `block-closing-brace-empty-line-before`. This thread, going forward, should be for discussing `stylelint-block-non-properties-order`.

**Comment by hudochenkov** [comment]
@jeddy3 what is your proposal for `stylelint-block-non-properties-order`? What should it do? What options should it have?

**Comment by evilebottnawi** [comment]
@jeddy3 how about newlines between properties?

**Comment by evilebottnawi** [comment]
@jeddy3 stupid question, i understand you can not answer :smile:

**Comment by davidtheclark** [comment]
> declaration-empty-line-before

@jeddy3 : If the only option here is "never", shouldn't it be `declaration-no-empty-line-before`?

**Comment by jeddy3** [comment]
> what is your proposal for stylelint-block-non-properties-order? What should it do? What options should it have?

The gist of `stylelint-block-non-properties-order` is outlined in [my comment above](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229300139). However, it's interwoven into a larger proposal about how rules work together. For everyone's sanity, including my own, I'll pull out and extend on the `stylelint-block-non-properties-order` stuff below :)

The first thing to keep in mind is that we still need to finalise the name and exact options. What is decided on is *the scope* of the plugin and how the plugin will *work together with the existing rules* and with these two new rules: https://github.com/stylelint/stylelint/issues/1574 & https://github.com/stylelint/stylelint/issues/1573. How and why this works is covered in [my comment above](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229300139) and by examples I gave.

OK, so my suggestion for the general outline of this plugin is:

- Name: `stylelint-block-non-properties-order`
- Primary option: `["array", "of", "predefined-keywords", "and", "userdefined-at-rule-names"]`
- Secondary options: none
- Message: `Expected "${first}" to come before "${second}"`

Its singular purpose is to lint the order of non-properties (excluding comments) within a block. It is *not* concerned with any whitespace nor the order of properties.

The inspiration (and internals) for the keywords within the primary object array could be taken from PostCSS sorting's [at-rule](https://github.com/hudochenkov/postcss-sorting#at-rules), [nested rule](https://github.com/hudochenkov/postcss-sorting#nested-rules) and [variable](https://github.com/hudochenkov/postcss-sorting#variables) options.  

An example rule config using all of these keywords could be:

```js
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      "dollar-variables",  // predefined keyword for dollar variables i.e. "$variables" from PostCSS Sorting
      "@apply", // user-defined at-rule with a specific name
      "@mixin clearfix", // user-defined at-rule with a specific name and parameter
      "declarations", // predefined keyword for declarations* 
      "nested-rules",  // predefined keyword for nested rules i.e. ">child" from PostCSS Sorting
      "at-rules" // predefined keyword for non-specific at-rules i.e. "@atrule" from PostCSS Sorting
     ]
   }
}
```

*To reiterate this plugin isn't concerned with the order of properties/declarations. Only that the declarations appear at the right place within the block.

And again, the keywords within the primary option array of just suggestions. We need to ask ourselves whether they allow people enough control to specify exactly the order of non-properties they want? e.g. does it allow for [this](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229120741)?

Some examples, given the config above...

```css
a {
  @media (width < 10px) {
     b { color :red }
  }
  display: block;
}
```

Would yield:

```console
5:2 Expected declaration to come before at-rule (plugin/block-non-properties-order)
```

And:

```css
a {
  display: block;
  @media (width < 10px) {
    b { color :red }
  }

  &:hover {
    display: inline;
  }
}
```

Would yield:

```console
7:2 Expected nested rule to come before at-rule (plugin/block-non-properties-order)
```

**Comment by hudochenkov** [comment]
Like how you describe everything, Richard! Very detailed and understandable.

Primary option as an array of strings looks good for now, but if we will think about future it's not futureproof. At some point there will be necessity to check if there is an empty line before some “entities”. For example, check empty line before first `@media` rule, but not between `@media` rules. Or check empty line before each `@media` rules. Array of strings won't handle future options. Maybe this option should accept objects too, like [declaration-block-properties-order](https://github.com/stylelint/stylelint/tree/master/src/rules/declaration-block-properties-order) does?

```json
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      "declarations",
      {
        "emptyLineBefore": "always",
        "name": "@media"
      },
      "at-rules"
     ]
   }
}
```

Also instead of `dollar-variables` it's better to use `variables`. `$var` is for PreCSS and SCSS, but we have CSS custom properties (`--var`) and Less (`@var`).

P. S. I want to make this plugin. Please, don't take this opportunity from me :)

**Comment by jeddy3** [comment]
> At some point there will be necessity to check if there is an empty line before some “entities”. 

My proposal above hinges upon the assumption that this *isn't* the case. There are already *individual and laser-focused* rules for linting empty lines before *things*. The addition of the `emptyLineBefore` option to `declaration-block-properties-order` was a mistake, and why it is being [removed](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md#release-planning) in `7.0.0`. This is to ensure that the `declaration-block-properties-order` rule, like all the other rules, has a singular purpose (whether that's linting for an empty line, *or* checking the order of things). This is [one of the core design philosophies](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md) of stylelint, and one of the main reasons there are no overlaps between the rules, despite there being over 140 of them. 

In [my original proposal](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229300139), I showed an example config that illustrated how all these individual whitespace and empty line rules work together. For clarity, I'll focus on just the empty lines rules below:

```json
{
  "rules": {
    "at-rule-empty-line-before": [ "always", {
      "except": [ "blockless-group", "first-nested" ],
      "ignore": ["after-comment"],
    } ],
    "comment-empty-line-before": [ "always", {
      "except": ["first-nested"],
      "ignore": ["stylelint-commands"],
    } ],
    "function-max-empty-lines": 0,
    "max-empty-lines": 1,
    "rule-nested-empty-line-before": [ "always-multi-line", {
      "ignore": ["after-comment"],
    } ],
    "selector-max-empty-lines": 0,
  }
}
```

I believe these laser-focused rules, with the help of their secondary options, work together well to lint empty lines within blocks. In my original proposal I mentioned that there *are* a couple of holes to fill, and I've created separate issues for those:

- `declaration-no-empty-line-before`: https://github.com/stylelint/stylelint/issues/1573
- `custom-property-no-empty-line-before`: https://github.com/stylelint/stylelint/issues/1578
- `block-closing-brace-empty-line-before`: https://github.com/stylelint/stylelint/issues/1574
- `dollar-variable-no-empty-line-before`: https://github.com/kristerkari/stylelint-scss/issues/53

Hopefully the above explanation has made it a little clearer why I believe this new plugin should only be focused on the *order* of non-properties within a block, and *not* concerned with whitespace or empty lines?

> Maybe this option should accept objects too

Having said all that... I think you're on to something with accepting objects, *but for a different reason than controlling whitespace*. I think you're right that objects are more extensible, which will be especially useful for the user-defined at-rules. For example:

```js
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      "custom-properties", // predefined keyword for custom properties
      "dollar-variables",  // predefined keyword for dollar variables
      {
        atRuleName: "apply", // user-defined at-rule with a specific name
      },
      {
         atRuleName: "mixin", // user-defined at-rule with a specific name and parameter
         atRuleParameter: "clearfix"
      },
      "declarations", // predefined keyword for declarations* 
      "nested-rules",  // predefined keyword for nested rules
      "at-rules" // predefined keyword for non-specific at-rules
     ]
   }
}
```

I like this approach as:

1. It clearly distinguishes between predefined keywords (e.g. `"at-rules"`, `"nested-rules"`, `"declarations"`, `"custom-properties"`, `"dollar-variables"` etc.) and user-defined at-rules.
2. It's extensible for the user-defined at-rules.

Off hand, I can think of the following ways to extend that object:

```js
{
  atRuleName: "mixin", // user-defined at-rule with a specific name and parameter
  atRuleParameter: "/^clear/", // accept regex as well as strings
  atRuleBlockContent: "/@content/", // regex for the contents of the at-rule's block
  hasBlock: true // bool for whether the at-rule has a block or not
}
```

I believe this makes achieving @bjankord's [requirements](https://github.com/stylelint/stylelint/issues/1500#issuecomment-229120741) viable.

Can you think of any other useful ways that this object could be extended? 

> Also instead of `dollar-variables` it's better to use `variables`.

In the example above I've used two separate keywords, `"custom-properties"` and `"dollar-variables"`, as this is in-keeping with how we [categorise](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#custom-property) [things](https://github.com/kristerkari/stylelint-scss#-variable). I believe this fine-grain categorisation is more future proof e.g. it's possible to use custom properties and dollar variables side-by-side i.e. dollar variables for build-time variables, and custom properties for [computed-time](https://drafts.csswg.org/css-variables/#using-variables) variables.

> P. S. I want to make this plugin. Please, don't take this opportunity from me :)

Don't worry, I have no intention of writing or maintaining this plugin :) My interest here is to ensure that the plugin works *together with the other rules* and *overlapping functionality is avoided*.

**Comment by hudochenkov** [comment]
> Hopefully the above explanation has made it a little clearer why I believe this new plugin should only be focused on the order of non-properties within a block, and not concerned with whitespace or empty lines?

Yes, I understand that it should concern only about an order. And now you open my eyes about existing rules for empty lines :)

Can you explain, please, what `atRuleBlockContent` will be for?

> it's possible to use custom properties and dollar variables side-by-side

Damn, you're good! I didn't think about that, and it's definitely will be the case when browsers will have better custom properties support.

**Comment by jeddy3** [comment]
> Can you think of any other useful ways that this object could be extended?

While this plugin is on my mind, I'll answer my own question...

I like to order my nested rules and nested media queries in a specific order. I believe this helps to keep things findable and scannable for larger teams, especially when there are many nested rules within a block. We use the following order:

1. pseudo-classes e.g. `&:hover`, and `&:not()`
2. pseudo-elements e.g. `&::before` and `&::after`
3. *directly nested* descendent rules e.g. `& .a {}`
4. *at-nest nested* rules e.g. `@nest .a & {}
5. at-media rules `@media (width < 100px) {}`

The object within the config array could be expanded to accommodate this, as such:
(I've kept the `extends` and `include` at-rules in for illustrative purposes, as they are not something I use)

```js
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      {
        type: "atRule"
        name: "extend", // user-defined at-rule with a specific name
      },
      {
        type: "atRule"
        name: "include", // user-defined at-rule with a specific name without a block
        hasBlock: false
      },
      {
        type: "atRule"
        name: "include", // user-defined at-rule with a specific name with a block
        hasBlock: true
      },
      "declarations", // predefined keyword for declarations
      {
        type: "rule", // user-defined rule with specific selector regex
        selector: "/^&:\d/" // in this case matching pseudo-classes
      }, {
        type: "rule", // user-defined rule with specific selector regex
        selector: "/^&::\d/" // in this case matching pseudo-elements
      },
      "rules",  // predefined keyword for rules (used here for directly nested descendent rules)
      {
        type: "atRule"
        name: "nest", // user-defined at-rule with a specific name
      },
      "at-rules" // predefined keyword for non-specific at-rules (used here for @media)
     ]
   }
}
```

Incidentally, this is a great illustration of why this will be community plugin rather than a core rule i.e. it doesn't have a "[clear and unambiguous finished state](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#let-everyone-know)".

One of the advantages of being a plugin is that you can iterate often and release breaking changes to the config syntax. So, it's probably best to release something that works for at-rules first and maybe tackle the above, more involved, use-case at a later date.

Do you feel that you now have enough information to make a start on this plugin? I'm keen to see how you get on, and so would you mind posting a link to your repo once you've something to show? There is a "[Writing plugins](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md)" section of the developer guide that you might find useful. In terms of reference material, the [stylelint-scss](https://github.com/kristerkari/stylelint-scss) team is doing a great job and any of their plugins would make a great blueprint. In particular, there is their [`at-mixin-pattern`](https://github.com/kristerkari/stylelint-scss/tree/master/src/rules/at-mixin-pattern) plugin, which has a [great set of tests](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/at-mixin-pattern/__tests__/index.js) that use various configurations and syntax options. And, of course, there is also the `7.0.0` version of [`declaration-block-properties-order`](https://github.com/stylelint/stylelint/tree/v7/src/rules/declaration-block-properties-order) for reference.

Does anyone else have any feedback on the proposal or shall we get the ball rolling?

**Comment by hudochenkov** [comment]
I summed up config with all options plugin will have. Do I miss something?

```js
{
  "plugins": {
    "block-non-properties-order": "stylelint-block-non-properties-order"
  },
  "rules": {
    "plugin/block-non-properties-order": [
      "custom-properties", // predefined keyword for custom properties
      "dollar-variables",  // predefined keyword for dollar variables
      "declarations", // predefined keyword for declarations
      "rules",  // predefined keyword for rules
      "at-rules", // predefined keyword for non-specific at-rules
      {
        type: "atRule",
        name: "nest", // user-defined at-rule with a specific name
      },
      {
        type: "atRule",
        name: "include", // user-defined at-rule with a specific name without a block
        hasBlock: false
      },
      {
        type: "atRule",
        name: "include", // user-defined at-rule with a specific name with a block
        hasBlock: true
      },
      {
        type: "rule", // user-defined rule with specific selector regex
        selector: "/^&:\w/" // in this case matching pseudo-classes
      },
      {
        type: "rule", // user-defined rule with specific selector regex
        selector: "/^&::\w/" // in this case matching pseudo-elements
      }
    ]
  }
}
```

**Comment by jeddy3** [comment]
Looks good to me :)

**Comment by bjankord** [comment]
lgtm :)

**Comment by jeddy3** [comment]
@hudochenkov What do you think about the name `declaration-block-order`? I now think `non-properties` is an odd thing to include in the name as other *things* might also be excluded if specific rules are written in the future e.g. `declaration-block-custom-properties-order` or `scss/declaration-block-dollar-variables-order`.

**Comment by hudochenkov** [comment]
@jeddy3 I like it. It's simpler.

**Comment by jeddy3** [comment]
Closing this here as any further work and/or discussion should happen in the plugin's repo. 

@hudochenkov When you have something to show, or if you just create a holding repo, please can you add a note here pointing in that direction so people know where to go.

**Comment by hudochenkov** [comment]
I finally started to work on this plugin :) I have a problem with development, though. I want to use Chrome Dev Tools to debug my plugin (`node --inspect run.js` in Node 6.3.0+), because `console.log()` isn't enough. But I don't know how to teach stylelint that current folder is a plugin and use it. I have this `run.js`:

```js
const stylelint = require('stylelint');

const config = {
	plugins: {
		'declaration-block-order': 'stylelint-declaration-block-order'
	},
	rules: {
		'plugin/declaration-block-order': [
			'custom-properties',
			'dollar-variables',
			'declarations',
			'rules',
			'at-rules',
		],
	},
};

stylelint.lint({
	code: `
		a {
			display: none;
			--width: 10px;
		}
	`,
	config,
}).then(function (data) {
	console.log(data);
}, function (err) {
	console.log(err);
});
```

P. S. Developing stylelint plugin is not a straightforward task 😥

**Comment by jeddy3** [comment]
> I finally started to work on this plugin :)

That's great news! 

> But I don't know how to teach stylelint that current folder is a plugin and use it. I have this `run.js`:

Plugins are [configured as an array](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#plugins), and not as an object.

If your plugin is at `index.js`, then changing your configuration to the following should suffice:

```js
const config = {
    plugins: [
       './'
    ],
    rules: {
        'plugin/declaration-block-order': [
            'custom-properties',
            'dollar-variables',
            'declarations',
            'rules',
            'at-rules',
        ],
    },
};
```

Be sure to [define](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin) the name of your plugin with the plugin itself.

Good luck :)

**Comment by hudochenkov** [comment]
@jeddy3 thank you! Working like a charm :)

**Comment by hudochenkov** [comment]
@jeddy3 I made [`stylelint-declaration-block-order`](https://github.com/hudochenkov/stylelint-declaration-block-order). It's not published on npm yet. Can you, please, take a look? Maybe you'll have some suggestions :)

**Comment by evilebottnawi** [comment]
@hudochenkov what about separate `ava` test runner from plugin in other repo?

**Comment by hudochenkov** [comment]
@evilebottnawi you mean extract it in separate module like https://github.com/stylelint/stylelint-test-rule-tape?

**Comment by evilebottnawi** [comment]
@hudochenkov yep, it may be useful to many

**Comment by hudochenkov** [comment]
@evilebottnawi done https://github.com/hudochenkov/stylelint-test-rule-ava Would you like to move it to stylelint organisation?

**Comment by evilebottnawi** [comment]
@stylelint/core what do you think about move to main repo? Also we can try tested with ava? maybe faster?

**Comment by davidtheclark** [comment]
@evilebottnawi: Regarding the rule: I think the point of keeping it in an external package for a little while is to see how it works, what kind of requests come in, etc. So we should keep it in mind but wait a minute. Regarding ava: You're always welcome to try it out :)

**Comment by evilebottnawi** [comment]
@davidtheclark agree about rule

**Comment by jeddy3** [comment]
@hudochenkov First of all I'd just like say a big thank you for making `stylelint-declaration-block-order`. I've just tried it on the `stylelint.io` CSS code and it seems to work like a charm in both Atom and via the CLI. 

I'll have a look through your repo now and any add further feedback into that repo's issue tracker.

Thanks again for the great work!

🎉

**Comment by hudochenkov** [comment]
@jeddy3 thank you for kind words! Thank you for discussion and planning this plugin :)
