### ISSUE TITLE
Rename no-missing-eof-newline and media-query-parentheses-space-inside

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1511]
`no-missing-eof-newline` ref: https://github.com/stylelint/stylelint/pull/1436#issuecomment-227738765

I know we told ourselves that we were kind of done renaming rules, but the `no-missing-eof-newline` rename seems legit.

So, I figured I'd piggy back on that one and throw `media-query-parentheses-space-inside` in, as I think it should be called `media-feature-parentheses-space-inside`. Ref: https://github.com/kristerkari/stylelint-scss/pull/47#issuecomment-225701307

Media feature spec: https://www.w3.org/TR/mediaqueries-4/#mq-features
Media query spec: https://www.w3.org/TR/mediaqueries-4/#media

**Comment by evilebottnawi** [comment]
@jeddy3 agree

**Comment by davidtheclark** [comment]
Ok, you're right :/
