### ISSUE TITLE
Check indentation of parens by default

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1517]
Ref: https://github.com/kristerkari/stylelint-scss/issues/20#issuecomment-227980317

In `7.0` perhaps we should change the default behaviour of `indentation` to check parens are indented by one level? That would be consistent with how we check *blocks*, *values* etc.

We can then add an `"inside-parens"` value to the [`ignore: []` secondary option](https://github.com/stylelint/stylelint/blob/master/src/rules/indentation/README.md#ignore-value-param).

And remove the `"once"` value from `indentInsideParens`, which then becomes an option for changing the indentation behaviour inside of parens to something not consistent with the rest of the rule.

**Comment by evilebottnawi** [comment]
@jeddy3 agree

**Comment by jeddy3** [comment]
@davidtheclark What do you think as you're closest to this rule?

**Comment by davidtheclark** [comment]
Sure. If that option seems to be working well now for people. I don't know myself but haven't seen other bugs —— do you feel confident it's going well?

**Comment by evilebottnawi** [comment]
@davidtheclark i think by default we should see indentation everywhere and get option to ignore some in rule.
@jeddy3 We also have rule `*-max-empty-lines`, i think we should deprecated all `*-max-empty-lines` and combine all in one rule `max-empty-lines` with option `ignore: ['selector', 'function', 'declaration']` and maybe etc.

**Comment by jeddy3** [comment]
> do you feel confident it's going well?

I think so. I could always turn on the current `indentInsideParens: "once"` option in the next `config-standard` major release to test the water. If things go well we can make it the default behaviour.

> @jeddy3 We also have rule *-max-empty-lines...

Lets create a separate issue for that discussion, and lets keep threads focused on one topic so we can close them off when they're done.

**Comment by jeddy3** [comment]
I tested the `indentInsideParens: "once"` on a couple of my projects and seemed great. So, I enabled it in `config-standard`. Hopefully that'll give us enough time to gauge the stability of it before `v7` come around.

**Comment by davidtheclark** [comment]
Nicely done.

**Comment by jeddy3** [comment]
No complaints yet, and from a cursory glance quite a few of the repos using `stylelint-config-standard` updated to `9.0.0`.

**Comment by jeddy3** [comment]
Done in #1626
