### ISSUE TITLE
Using pre-commit with Stylelint

### ISSUE THREAD

**Issue by shadeed** [stylelint/stylelint#1520]
Hello there,

I'm using Stylelint with grunt-postcss and wonder if there is a way to add a pre-commit hook to check for Stylelint, if no errors/warning then the commit should be valid.

Would appreciate any ideas to make that happen.

Thanks a lot,

**Comment by ntwb** [comment]
I've personally never used any pre-commit hooks myself, I had a quick look around and it apears there are a few different packages/tools that implement pre-commit hooks.

The two most common scenarios I saw was a shell script or node module, so converting your `grunt-postcss` an equivalent configuration to use either stylelint's CLI or Node API seems like the way to go:

http://stylelint.io/user-guide/cli/ http://stylelint.io/user-guide/node-api/

@shadeed Will one of those work for you?

**Comment by jeddy3** [comment]
@shadeed I think is [lint-staged](https://github.com/okonet/lint-staged) is what you're after. [Here is](https://medium.com/@okonetchnikov/make-linting-great-again-f3890e1ad6b8#.wn3jbvrxo) an article about it.

@ntwb Lets update the FAQ and complementary tool docs accordingly.

**Comment by shadeed** [comment]
@ntwb I installed stylelint via CLI and followed @jeddy3 `lint-staged`, works like a charm! 😃

Thank you both :)

**Comment by ntwb** [comment]
Nice, I'll have to have a read and see where I can best use this 👍
