### ISSUE TITLE
Add Wikimedia to Growing community list?

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1524]
Now that Wikimedia are also using stylelint should add that the _Growing community_ [list](https://github.com/stylelint/stylelint/blob/master/README.md#features)?

https://github.com/wikimedia?utf8=%E2%9C%93&query=stylelint

**Comment by ntwb** [comment]
@evilebottnawi It sure does look like Wikimedia are using it a lot:

[github.com/search?l=&q=stylelint+user%3Awikimedia&ref=advsearch&type=Issues&utf8=%E2%9C%93](https://github.com/search?l=&q=stylelint+user%3Awikimedia&ref=advsearch&type=Issues&utf8=%E2%9C%93)

https://github.com/wikimedia/stylelint-config-wikimedia/commits?author=jdforrester

**Comment by evilebottnawi** [comment]
@ntwb good, I think we should add to the list.

**Comment by jdforrester** [comment]
A little bit; currently it's in only 19 of our repos (out of the 489 tracked in [the CI version tracker](mediawiki.org/wiki/User:Legoktm/ci)), but those include MediaWiki itself. :-) I'm slowly working on getting it added to the rest as part of our standard CI package. Progress!

**Comment by evilebottnawi** [comment]
@jdforrester Great!

**Comment by ntwb** [comment]
Awesome 🎉
