### ISSUE TITLE
Undefined rule "function-name-case"

### ISSUE THREAD

**Issue by nicothin** [stylelint/stylelint#1525]
I lint LESS.
Settings take with https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md
When checking see a error 'Undefined rule "function-name-case"', but https://github.com/stylelint/stylelint/blob/master/src/rules/function-name-case/README.md
Please tell me where my error?

Repo: https://github.com/nicothin/stylelint-less-test
Config: https://github.com/nicothin/stylelint-less-test/blob/master/.stylelintrc

```
nicothin@nicwin10 MINGW64 /d/projects/stylelint-less-test (master)
$ npm list --depth=0
stylelint-less-test@1.0.0 D:\projects\stylelint-less-test
├── gulp@4.0.0-alpha.2 (git://github.com/gulpjs/gulp.git#cf0bddf1416e381f926a2b59a1a7c9238495bfa4)
├── gulp-postcss@6.1.1
├── postcss-reporter@1.3.3
├── stylelint@4.5.1
└── stylelint-selector-bem-pattern@1.0.0
```

**Comment by evilebottnawi** [comment]
@nicothin please format your issue

**Comment by evilebottnawi** [comment]
@nicinabox update you stylelint version

**Comment by jeddy3** [comment]
@nicothin We also [recommend](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-lint-using-my-task-runner-of-choice) using [gulp-stylelint](https://github.com/olegskl/gulp-stylelint), rather than `gulp-postcss`.
