### ISSUE TITLE
[feature request] Ability to pass a single value OR an array of values to almost any rule

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#1528]
I'd like to config: `always-for-single-line` and, hopefully a new option, `never-for-multiline` for [function-comma-space-after](http://stylelint.io/user-guide/rules/function-comma-space-after/), but it'd need to be able to accept an array of options.

Have you guys ran into this kind of request before? I'll probably run into this need pretty often. Would it be a good idea to make all rules extensible enough that they accept a single value _or_ an array of values?

**Comment by Nirazul** [comment]
I think what you are looking for is the more common [`no-eol-whitespace`](http://stylelint.io/user-guide/rules/no-eol-whitespace/) rule which makes much more sense in your use case.

**Comment by ntwb** [comment]
Please use and fill out our GitHub issue template when filing issues, the information supplied in the template helps us significantly, particularly example CSS and if it relates to non-standard syntaxes such as SCSS or LESS are important in scoping out any issues...

_We cannot read minds so please help us help you :)_

**Comment by jeddy3** [comment]
The [About rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md) section of the [User guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide.md) goes into a lot of detail about how the whitespace rules work together to provide the most flexibility possible.

You'll want to use a combination of the following rules:

- `function-comma-newline-after`
- `function-comma-newline-before`
- `function-comma-space-after`
- `function-comma-space-before`

Please read the docs more throughly before creating issues. And, @ntwb said, we'd appreciate it if you used the issue template in the future.
