### ISSUE TITLE
Should false work in all cases?

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#1529]
`'media-feature-name-no-vendor-prefix': false` is an unexpected option. Is this a bug or is the idea if you don't want it, just don't include it? If so, is it possible to stack configs on top of each other? If so, what if I'm using a boilerplate where `media-feature-name-no-vendor-prefix` is `true` and want to cancel that out?

Regardless, I think it'd be nice to have a config with every single rule organized and defined so they're easy to toggle.

**Comment by ntwb** [comment]
Use `"media-feature-name-no-vendor-prefix": null` to overwrite a configuration 

Please read the rules configuration docs: http://stylelint.io/user-guide/configuration/#rules

_Again, in future please use our GitHub issue template to supply the information we need to help you._
