### ISSUE TITLE
Trying to real-world test current rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#153]
As per #15, here are the details of a couple of hurdles I'm trying to get over to start real-world testing our current rules. I've tried to debug what's going on a couple of times myself, but I figured (with your knowledge of postcss and its plugins) you two will be able to help me get to the bottom of things much faster.

With the config:

```js
"rules": {
   "declaration-no-important": 2
}
```

And the input.css of:

```css
body { color: !important; }
```

I get:

```console
Can not read property `1` of undefined`
```

I think that's because `declaration-no-important` doesn't have any options and the line `rules[rule](ruleSettings[1])(css, result)` triggers the error.

If I get around that then I get:

```console
object is not a function
```

And I think that's because `result.warn` is undefined within `declaration-no-important/index.js`. Is this something to do with how the plugin calls the rules?

Have you guys tried to run the plugin yet and, if so, how far did you get?

**Comment by davidtheclark** [comment]
See the commit c9befe50e54f95a56891366a6f72c30beecbfbad for a start on addressing these problems.

**Comment by jeddy3** [comment]
Thanks again! :)
