### ISSUE TITLE
Uncovered statement in selector-no-qualifying-type

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1545]
`selector-no-qualifying-type` is the only rule without 100% statement coverage in the `v7` branch. Istanbul complains about [line 33](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-qualifying-type/index.js#L33). @evilebottnawi I believe you wrote this rule. Do you know if that line is testable or should we get Istanbul to ignore it?

**Comment by ntwb** [comment]
Thanks for creating this, I looked at this the other day myself, I got confused and planned on revisiting 👍

**Comment by evilebottnawi** [comment]
@jeddy3 see today and PR this.

**Comment by jeddy3** [comment]
@evilebottnawi Thanks :)
