### ISSUE TITLE
Release 6.8?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1555]
Any objection to a minor release once https://github.com/stylelint/stylelint/pull/1547 is in?

**Comment by evilebottnawi** [comment]
@jeddy3 Maybe also close https://github.com/stylelint/stylelint/pull/1436?

**Comment by jeddy3** [comment]
Yep, I figured that and https://github.com/stylelint/stylelint/pull/1537 would get into the release too.

**Comment by davidtheclark** [comment]
No objection.

**Comment by jeddy3** [comment]
Done :)

- `stylelint`
- `stylelint-config-standard`
- http://stylelint.io

🎉

**Comment by Arcanemagus** [comment]
Atom's `linter-stylelint` package is now updated to this release pair 😉.
