### ISSUE TITLE
Is this already possible, or should I put in a feature request?

### ISSUE THREAD

**Issue by octoxan** [stylelint/stylelint#1558]
Trying to nest arrays for the declaration order rule, so let's say I want my rule to force padding and all the padding directions to be in a certain order, as well as the margin and margin directions.. but don't care which block comes first?
http://stackoverflow.com/questions/38105928/stylelint-nesting-declaration-order-arrays

**Comment by jeddy3** [comment]
Answered in stackoverflow. This feature is unlikely to be included in core as it's not useful to the majority of users. But if it's something you really want to do, then [writing a plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) will give you all the flexibility to need.
