### ISSUE TITLE
npm install complains about unmet dependency

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#1559]
npm install always gives this error when installing:

```
staryu:~ stevelombardi$ npm install -g stylelint-config-standard
/Users/stevelombardi/.nvm/versions/node/v5.10.0/lib
├── UNMET PEER DEPENDENCY stylelint@^6.6.0
└── stylelint-config-standard@9.0.0 
```

but then, if I do an `npm ls` I get this

```
├── stylelint@6.7.1
├── stylelint-config-standard@9.0.0
```

Showing not only do I have the dependency, but 9.0.0 installed despite the error.

**Comment by evilebottnawi** [comment]
@smlombardi try to remove `node_modules` and run `npm i`

**Comment by Arcanemagus** [comment]
Global installs will _always_ show that error, since there is no `package.json` to show `npm` that the package is _listed_ as being installed at the same time (it makes no checks as to whether it is installed or not).
