### ISSUE TITLE
New rule: comment-empty-line-before

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#156]
This one might need more option keywords than always/never. How about:

- always
- never
- always-except-inline (e.g. `color: pink; /* because it has been decreed */`)

We could have always-except-nested (i.e. expect a new line only if the comment is a child of `root`), or we could split out two rules, `comment-non-nested-empty-line-before` and `comment-nested-empty-line-before`.

Thoughts?

**Comment by MoOx** [comment]
I think one rule is enough.

**Comment by jeddy3** [comment]
sgtm.
