### ISSUE TITLE
Bump minimum NodeJS supported version to 4.x LTS

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1580]
Via https://github.com/stylelint/eslint-config-stylelint/pull/6 and https://github.com/stylelint/eslint-config-stylelint/pull/7

ESLint 3.0.0 has dropped supported for NodeJS version 0.12, their summary:

> http://eslint.org/blog/2016/07/eslint-v3.0.0-released#breaking-changes
> > _"ESLint v3.0.0 now requires Node.js 4 or higher. Going forward, our plan is always to support the LTS version of Node.js and periodically end-of-life support for older Node.js versions. As both Node.js v0.10 and v0.12 will be out of maintenance mode at the end of 2016, we hope that this change won’t affect too many users."_

This also makes sense for stylelint repo's so including this breaking change in stylelint v7 is the go

- [x] Use a node4+ feature (like spread) somewhere. Edit: This or any new NodeJS features can be used after stylelint v7 is released.
- [x] Declare minimum NodeJS v4.2.1 LTS version in `package.json`, see https://github.com/stylelint/eslint-config-stylelint/pull/7/commits/f7ff89cc676b53b1cf1f82cd9936b0a0199b67b6 see #1594
- [x] Remove NodeJS `0.12` from  `.travis.yml` See #1594
- [x] Remove NodeJS `0.12` from   `appveyor.yml`, this was removed previously for performance

**Comment by davidtheclark** [comment]
Would we be able to simplify our code in any way?

I agree that we *could* drop support for Node 0.12, but I wonder if we gain anything from doing so.

**Comment by jeddy3** [comment]
> I agree that we could drop support for Node 0.12, but I wonder if we gain anything from doing so.

I'm not 100% sure on the semver approach here... if we have `eslint@3.0.0` (which only works on node 4+) as a devDependency do we also need to declare (via the `engine` property in our `package.json`) that node +4 is needed for stylelint, even if that's only relevant if you're *developing for* rather than just consuming stylelint?

**Comment by ntwb** [comment]
> I'm not 100% sure on how semver exactly works in this situation, or how we declare our minimum development requirements vs our minimum consumer requirements. For example, if we have eslint@3.0.0 (which only works on node 4+) as a devDependency do we also need to declare (via the engine property in our package.json) that node +4 is needed for stylelint, even if that's only relevant if you're developing for rather than just consuming stylelint?

I'm not sure on this either actually, I'll look into this further.

One thing I am sure of is NodeJS 0.12 support ends at 31st December 2016, technically the 0.12.x branch is now only in "maintenance mode" and only receives security updates https://github.com/nodejs/LTS/

**Comment by davidtheclark** [comment]
> if we have eslint@3.0.0 (which only works on node 4+) as a devDependency do we also need to declare (via the engine property in our package.json) that node +4 is needed for stylelint, even if that's only relevant if you're developing for rather than just consuming stylelint?

No, I don't think so. stylelint's version numbers should reflect the needs for running the program, not for developing it.

**Comment by ntwb** [comment]
> > if we have eslint@3.0.0 (which only works on node 4+) as a devDependency do we also need to declare (via the engine property in our package.json) that node +4 is needed for stylelint, even if that's only relevant if you're developing for rather than just consuming stylelint?
> No, I don't think so. stylelint's version numbers should reflect the needs for running the program, not for developing it.

Yes, this, you are correct it isn't needed 👍

**Comment by jeddy3** [comment]
> No, I don't think so. stylelint's version numbers should reflect the needs for running the program, not for developing it.

Groovy. I'll split the eslint stuff out of this issue then, as we can resolve that now with a release of `eslint-config-stylelint` and a devDependency update. This issue can just just focus on discussing bumping minimum NodeJS supported version to 4.x LTS.

**Comment by ntwb** [comment]
Also this from https://github.com/stylelint/stylelint/pull/1521#issuecomment-228327547
> _"I thought the Travis CI Node 0.12.x tests had stalled and read `common-tags` requires NodeJS 4.0.0 or above https://github.com/declandewet/common-tags#requirements, turns out the 0.12.x test passed anyway ¯\_(ツ)_/¯"_

Now following https://github.com/stylelint/stylelint/pull/1587 we have 3 warnings when testing the NodeJS [0.12.x branch on Travis CI](https://travis-ci.org/stylelint/stylelint/jobs/141960745#L143):

```shell
npm WARN engine eslint-config-stylelint@3.0.0: wanted: {"node":">=4.2.1"} (current: {"node":"0.12.15","npm":"2.15.1"})
npm WARN engine common-tags@1.3.0: wanted: {"node":">=4.0.0","npm":">=3.0.0"} (current: {"node":"0.12.15","npm":"2.15.1"})
npm WARN engine eslint@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.15","npm":"2.15.1"})
```

**Comment by jeddy3** [comment]
Does this mean that we won't be able to test on `0.12.x` anymore?  It looks like we can still run the tests *at the moment*, but at anytime the tests could stop working (as any of these dev dependencies can now start using a node4+ only feature under a patch or minor release)?

**Comment by ntwb** [comment]
> It looks like we can still run the tests at the _moment_, but at anytime the tests could stop working 

Yes

Extra to this is `common-tags` could also do the same for NPM as well as NodeJS because it requires NPM 3.x.x, by default NodeJS 4.x.x uses the NPM 2.x.x LTS version and NodeJS > 5.x.x uses NPM 3.x.x branch, I've opened an issue for `common-tags` on potentially removing the NPM 3.x.x requirement [here](https://github.com/declandewet/common-tags/issues/43)

**Comment by jeddy3** [comment]
> No, I don't think so. stylelint's version numbers should reflect the needs for running the program, not for developing it.

That originally made sense to me, but now it feels like there's an odd chicken and egg thing going i.e. at some point stylelint *might* still run on `0.12.x` but we won't be able to test it. So, do we wait for this to happen and then deal with it, or do we use `7.0` to mitigate any future problems by bumping our supported version to `4+` now? 

> Would we be able to simplify our code in any way?

So, if we're including simplification of test code in this... I'll add that `common-tags` made testing the formatters much neater. Also, there [are three nice error-checking rules](http://eslint.org/docs/user-guide/migrating-to-3.0.0#changes-to-eslintrecommended) in `eslint@3.0.0` that would be nice to keep.

**Comment by ntwb** [comment]
> That originally made sense to me, but now it feels like there's an odd chicken and egg thing going i.e. at some point stylelint might still run on 0.12.x but we won't be able to test it. 

I wouldn't say stylelint's hand has been forced as there are workarounds such as pinning previous package versions in our `package.json` file but the fact is other packages we depend on have made this decision already and removed support for NPM 0.12.x.

Regardless of what other packages do or do not do or what stylelint does now or not we should be prepared for NodeJS _end-of-life_ on 31st December 2016.

> So, do we wait for this to happen and then deal with it, or do we use 7.0 to mitigate any future problems by bumping our supported version to 4+ now?

NodeJS _end-of-life_ is ~6 mths from now, no updates except security updates will be released for NodeJS in this coming ~6 months.

> Also, there are three nice error-checking rules in eslint@3.0.0 that would be nice to keep.

We're using these 3 new rules now in `master` since merging https://github.com/stylelint/stylelint/pull/1587 😄 

_____

Overall I don't see any reason in not dropping NodeJS 0.12.x now as part of stylelint v7.

I also see the core of this issue is the _end-of-life_ of NodeJS 0.12.x not what enhancements are available or included with NodeJS 4.x.

**Comment by jeddy3** [comment]
> I also see the core of this issue is the end-of-life of NodeJS 0.12.x not what enhancements are available or included with NodeJS 4.x.

Sgtm :)

**Comment by jeddy3** [comment]
> i.e. at some point stylelint might still run on 0.12.x but we won't be able to test it.

That didn't take long: https://travis-ci.org/stylelint/stylelint/jobs/142545588

**Comment by ntwb** [comment]
> That didn't take long: https://travis-ci.org/stylelint/stylelint/jobs/142545588

Maybe revert https://github.com/stylelint/stylelint/commit/087879e61e41c6ba1c6020e3ce600b8137d36329 and then include this as part of #1594 so that _all the NodeJS changes_ are v7 only breaking changes?

**Comment by jeddy3** [comment]
Can we pin to `eslint@3.0.0` and the current version of `common-tags` in `master` as those didn't fail? This problem going to go away in `7.0.0` if we merge https://github.com/stylelint/stylelint/pull/1594 and so I'm eager to do whatever is the least amount of work for `master`.

**Comment by ntwb** [comment]
> Can we pin to eslint@3.0.0 and the current version

In #1600 I've pinned ESLint `3.0.0` and all looks good 👍 

I don't think `common-tags` will be an issue, a pull request has been added by the repo owner removing the NPM > 3.0.0 requirement so that shouldn't be an issue once a new version is released.

So I think, for now in `master` we should be right with the _least_ amount of work here?

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1594
