### ISSUE TITLE
add github labels

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#16]
I need to fix a bug and finish import to get smart labels :)

**Comment by MoOx** [comment]
I've added a bunch. Please tell me if it's looks good to you

**Comment by jeddy3** [comment]
Thanks!

What's "type: css feature"? Is it something left over from cssnext?

Otherwise, lgtm :)

**Comment by MoOx** [comment]
haha yes. I have use this https://gist.github.com/MoOx/93c2853fee760f42d97f and this https://github.com/popomore/github-labels

**Comment by jeddy3** [comment]
Nice!

The labels look great to me. If @davidtheclark is happy, we can close this?

**Comment by davidtheclark** [comment]
Very good.
