### ISSUE TITLE
function-url-path

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1602]
Ref:  https://github.com/stylelint/stylelint/pull/1577

**Comment by davidtheclark** [comment]
What's the intention of this issue? To continue the discussion about whether to create the rule or not?

**Comment by jeddy3** [comment]
> To continue the discussion about whether to create the rule or not?

I had originally thought that, but now that you mention it it seems odd not to keep the discussion going in one place within the [PR](https://github.com/stylelint/stylelint/pull/1577). Closing now.

It was related to https://github.com/stylelint/stylelint/issues/1084#issuecomment-231074538 (i.e. one new rule per issue) as I think things like the scheme whitelist and blacklist rules need fleshing out before they're started on.
