### ISSUE TITLE
declaration-block-trailing-semicolon is not compatible with less mixins and inline double-slash comments

### ISSUE THREAD

**Issue by kachkaev** [stylelint/stylelint#1608]
Looks like the parser struggles with finding `declaration-block-trailing-semicolon` in a few cases, even in 6.9.0.

## MWE

`test.less`
```less
.class1 {
  color: green
}

.class2 {
  color: green // some comment at the end of line
}

.class3 {
  .mixin()
}

.class4 {
  .mixin2
}

.class5 {
  color: green
  .mixin()
  .mixin2
}
```

`.stylelintrc`
```json
{
  "extends": "stylelint-config-standard"
}
```

```bash
$ node_modules/.bin/stylelint --version
6.9.0
$ node_modules/.bin/stylelint test.less --syntax less

test.less
  2:14  ✖  Expected a trailing semicolon                              declaration-block-trailing-semicolon
 18:8   ✖  Expected newline after ":" with a multi-line declaration   declaration-colon-newline-after
 19:3   ✖  Expected indentation of 4 spaces                           indentation
 20:3   ✖  Expected indentation of 4 spaces                           indentation
 20:9   ✖  Expected a trailing semicolon                              declaration-block-trailing-semicolon
```

__Expected output__
```
test.less
 2:14   ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
 6:14   ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
10:10   ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
18:14   ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
19:10   ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
20:9    ✖  Expected a trailing semicolon   declaration-block-trailing-semicolon
```

**Comment by jeddy3** [comment]
@kachkaev Thanks for writing this one up too.

As with https://github.com/stylelint/stylelint/issues/1607, the semicolon (or lack there of) is ignored. This issue highlights the limitation of that approach i.e. erroneous other warnings are flagged around the missing semicolon. However, this is something we're [discussed before](https://github.com/stylelint/stylelint/issues/1346) and we concluded then that these parser-level issues *might not be feasible fixable* in stylelint. I'm inclined to take a similar approach here i.e. document this limitation and close the issue with a note. Does anyone else feel differently?

We could update the current limitation note in the `declaration-block-trailing-semicolon` to read:

*"This rule is not compatible with Less mixins, trailing inline double-slash comments, nor declaration blocks containing nested rules and at-rules."

**Comment by evilebottnawi** [comment]
@jeddy3 problems again in postcss-less
```css
.class5 {
  color: green
  .mixin()
  .mixin2
}
```
output:
```shell
Declaration {
  raws: { before: '\n  ', between: ': ' },
  type: 'decl',
  parent: 
   Rule {
     raws: { before: '', between: ' ', semicolon: false, after: '\n' },
     type: 'rule',
     nodes: [ [Circular] ],
     parent: 
      Root {
        raws: [Object],
        type: 'root',
        nodes: [Object],
        source: [Object],
        lastEach: 36,
        indexes: [Object] },
     source: { start: [Object], input: [Object], end: [Object] },
     selector: '.class5',
     lastEach: 37,
     indexes: { '37': 0 } },
  source: 
   { start: { line: 2, column: 3 },
     input: 
      Input {
        css: '.class5 {\n  color: green\n  .mixin()\n  .mixin2\n}\n',
        file: '/home/sheo13666q/IdeaProjects/stylelint/test/test.less' },
     end: { line: 4, column: 9 } },
  prop: 'color',
  value: 'green\n  .mixin()\n  .mixin2' }
```
It is crazy :disappointed:

**Comment by jeddy3** [comment]
> It is crazy 😞

I'm not sure it is. As with https://github.com/stylelint/stylelint/issues/1346, something like:

```
.class5 {
  color: green .mixin() .mixin2
}
```

could be a declaration. In fact, the standard PostCSS parser [parses the above](https://astexplorer.net/#/wglK87gmzj) in the same way as `postcss-less`.

Which is why we can't lint for missing semicolons in these contexts and why I'm in favour of just documenting this limitation.

**Comment by evilebottnawi** [comment]
@jeddy3 maybe see as Less parses this construction?

**Comment by jeddy3** [comment]
> @jeddy3 maybe see as Less parses this construction?

I think I'd rather just document the limitation here (as that's all stylelint can do). I think investigating whether the postcss-less parser aligns with the actual Less parser can happen in the `postcss-less` repo.

**Comment by evilebottnawi** [comment]
@jeddy3 agree, need create issue in `postcss-less` repo and close this issue here.

**Comment by jeddy3** [comment]
> need create issue in postcss-less repo and close this issue here.

Groovy. I just checked an online less tool and the following produces a parse error:

```
.class5 {
  color: green .mixin() .mixin2
}
```

So `postcss-selector` should probably throw a parse error too.
