### ISSUE TITLE
Attaching a warning to `root` produces no output when run as plugin.

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#161]
`no-eol-whitespace`, `no-missing-eof-newline` and `string-quotes` attach their warnings to the `root` node e.g. `result.warn(messages.rejected(lineCount), {node: root});`.

Enabling these rules produces no output in the console, even if other rules should be producing warnings.

Changing each of these three rules so that the warning is attached to the first node, in each of these rules, e.g. `result.warn(messages.rejected(lineCount), {node: root.first});` seems to mitigate this issue. Should we go down this route for now?

I'm not sure why this issue only presents itself when the rules are run through the plugin.

Any ideas?

**Comment by davidtheclark** [comment]
First step in fixing these the right way would be managing to write some tests that currently fail. Any ideas about how we'd need to do that?

**Comment by davidtheclark** [comment]
This is a problem with `postcss-log-warnings`, I believe: https://github.com/davidtheclark/postcss-log-warnings/issues/11

**Comment by davidtheclark** [comment]
@jeddy3 Please try updating to log-warnings v0.3.1 and see if that solves the problem.

**Comment by jeddy3** [comment]
@davidtheclark  Working now thanks! :)
