### ISSUE TITLE
selector-max-specificity crashes on :matches() pseudo class

### ISSUE THREAD

**Issue by bjb568** [stylelint/stylelint#1620]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where using :matches() in a selector causes stylelint 6.7.0+ (but not 6.6.0) to return the string 'undefined' with exit code `1`.

stylelint 6.6.0:

    $ stylelint ./*/*.css ./*/*/*.css -f verbose
    
    16 sources checked
     ...
    
    0 problems found

stylelint 6.7.0:

    $ stylelint ./*/*.css ./*/*/*.css -f verbose
    undefined
> Which rule, if any, is this issue related to?

Probably the parser.

> What CSS is needed to reproduce this issue?

```css
.noumar, :matches(.pad, .resp-block, .program) h2:first-child, .comment > :matches(:first-child, :last-child) { margin-top: 0 }
```

> What stylelint configuration is needed to reproduce this issue?

Doesn't matter

> Which version of stylelint are you using?

6.7.0 and all versions up to 6.9.0 have this issue.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No, this is a regular vanilla CSS file.

> What did you expect to happen?

The behavior in 6.6.0 and lower should be preserved.

> What actually happened (e.g. what warnings or errors you are getting)?

Undefined and an error exit code were returned.

**Comment by davidtheclark** [comment]
I am unable to reproduce this in 6.9.0.

My config is just `block-no-empty`. I have your CSS, copied from above, along with a `a {}` to trigger a warning. When I run stylelint I get the expected warning.

So we'll need to narrow down the problem in order to fix it. If you toggle different rules on and off, can you find a specific rule that might be ruining things for you, @bjb568?

**Comment by bjb568** [comment]
Apparently this only happens with the `selector-max-specificity` rule.

**Comment by bjb568** [comment]
The bug was probably introduced at https://github.com/stylelint/stylelint/commit/9053ac548b71dac2750c0af14d18908c4bf4c929#diff-77b1dd624d23c9c3444ceb368ee45195R38 where [the specificity module](https://www.npmjs.com/package/specificity) would [throw](https://tonicdev.com/575787fa93e613130091fb38/5781c6de4a548b1400e43a46).

It can be fixed by try-catching the specificity compare call.

**Comment by davidtheclark** [comment]
Thanks @bjb568! Yes, we should try-catch calls to that library, same as we are try-catching calls to postcss-selector-parser, which also breaks with non-standard syntax.

**Comment by jeddy3** [comment]
In the interim, should we return early with selectors containing the `matches` pseudo class? Like [we recently did](https://github.com/stylelint/stylelint/pull/1582) with the `not` pseudo class?

**Comment by davidtheclark** [comment]
I don't think there has to be an "interim". Implementing a try-catch won't be more time-consuming than implementing an earlier return.

**Comment by jeddy3** [comment]
> Implementing a try-catch won't be more time-consuming than implementing an earlier return.

Ok, agreed. A try-catch will also be more future-proof that tracking and returning early for incompatible pseudo classes.

**Comment by sendilkumarn** [comment]
We have to add this try-catch, all the places where we use compare. 

both in selector-max-specificity and no-descending-specificity. If it is correct, I will submit a PR.

**Comment by jeddy3** [comment]
> both in `selector-max-specificity` and `no-descending-specificity`. If it is correct, I will submit a PR.

Thanks. I believe those are the only two rules that use the `specificity` module.
