### ISSUE TITLE
Partial imports lints node_modules

### ISSUE THREAD

**Issue by jmeas** [stylelint/stylelint#1623]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where stylelint lints ignored files which are imported.

> Which rule, if any, is this issue related to?

It's not related to a particular rule.

> What CSS is needed to reproduce this issue?

```css
@import 'path/to/ignored/file';
```

> What stylelint configuration is needed to reproduce this issue?

```sh
# .stylelintignore
path/to/ignored
```

and some rules which fail for an ignored file. I've tried configuring this ignored directory a number of different ways, and in a number of different places such as the Gulp options, and the `.stylelintrc` file.

> Which version of stylelint are you using?

`6.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

The gulp plugin. The start of the config is...

```js
return gulp.src(cssFiles)
    .pipe($.postcss([
      easyImport({glob: true}),
      stylelint({
        ignoreFiles: './node_modules/**/*'
      }),
      precss({import: {prefix: ''}}),
    ], {parser: postcssSass}))
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Not non-standard syntax, but non-standard parsing of imports.

> What did you expect to happen?

The file would be ignored.

> What actually happened (e.g. what warnings or errors you are getting)?

The file was linted.

---

Honestly, I'm pretty new to the PostCSS ecosystem, so I'm not sure which of these plugins is responsible for this issue. Lmk if you think it might be something else!

Also, there are other ways I could load 3rd party libs, like concatenating them with Gulp, but I want to keep things simple and rely on a single mechanism for bringing my CSS together. It should work similar to importing JS files, I think – linters ignore require'd files that are in ignored directories.

**Comment by jmeas** [comment]
Gonna close as resolved. I solved it by treating my CSS like my JS, and separated out CSS linting into its own Gulp task. Works great!

**Comment by jeddy3** [comment]
@jmeas We [recommend](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-lint-using-my-task-runner-of-choice) using [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) as it exposes stylelint's [built-in formatters](https://cloud.githubusercontent.com/assets/808227/14970067/063e5802-10be-11e6-8774-6557d80c443b.png).

For anyone stumbling into this issue after a search... if a dedicated stylelint plugin isn't available for your task runner of choice, then doing what @jmeas did (i.e. a separate lint task) is one of [three viable](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#usage-examples) solutions. However, if a dedicated plugin [is available](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#build-tool-plugins) we recommend using that.
