### ISSUE TITLE
Error with missing rule, but it definitely exists

### ISSUE THREAD

**Issue by mikeerickson** [stylelint/stylelint#1670]
Receiving the following error when running Stylelint

```
Undefined rule "media-query-parentheses-space-inside"
```

But it does indeed exists

```
...
	"media-query-list-comma-space-before": "never",
	"media-query-parentheses-space-inside": "always",
	"no-eol-whitespace": true,
	"number-leading-zero": "always",
...
```

Calling as

```
$ stylelint "app/components/*.sass" --config .stylelintrc --syntax sass
```

Stylelint Versions

```
- stylelint --version ==> 7.0.3
- ./node_modules/.bin/stylelint --version ==> 7.0.3
```

Also, I have `stylelint-config-standard` installed

```
"stylelint-config-standard": "^11.0.0",
```

**Comment by Arcanemagus** [comment]
It may exist in your configuration, but it's not in the [current list](http://stylelint.io/user-guide/rules/#media-query-list) of `media-query-*` rules.

**Comment by davidtheclark** [comment]
Yep, that rule has been renamed in v7.

**Comment by mikeerickson** [comment]
@davidtheclark So what is the fix?  Removing these from `.stylelintrc` still produces the error.  I have also changed to 

```
"media-feature-parentheses-space-inside": "never"
```

**Comment by davidtheclark** [comment]
You're saying that if you change the config so that it does not contain `media-query-parentheses-space-inside`, but instead contains `media-feature-parentheses-space-inside`, you are still getting the error message `Undefined rule "media-query-parentheses-space-inside"`?

If that's the case, that means you're not loading the config you think you're loading.

**Comment by mikeerickson** [comment]
Here is my issue

![image](https://cloud.githubusercontent.com/assets/183153/16957613/f4d51d74-4d91-11e6-9f26-cf8ebab06d9c.png)

I have created a barebone sample

![image](https://cloud.githubusercontent.com/assets/183153/16957636/121a9b16-4d92-11e6-8573-c78816193f15.png)

And I have the associated `.stylelintrc` referenced above

**Comment by mikeerickson** [comment]
Here is contents of test.sass

```
$bgColor: red
$fgColor: white

body
  foreground-color: $fgColor
  background-color: $bgColor

```

**Comment by jeddy3** [comment]
Stylelint only supports SCSS syntax, not the whitespace-based SASS once.

If you like whitespace-based syntaxes you could use [SugarSS](https://github.com/postcss/sugarss) which has a PostCSS-based parser and is integrated into stylelint.

I don't think a SASS parser exists for PostCSS. You [could write one](https://github.com/postcss/postcss/blob/master/docs/syntax.md#how-to-write-custom-syntax) though.

**Comment by mikeerickson** [comment]
@jeddy3 Ahhhhh... well that explains it :-)  

Sorry for the noise mate.  I am sure this is documented somewhere, but like many "hackers" I just jump in and try to use the tool.   My apologies for not reading the docs and avoiding all of this nose.

**Comment by jeddy3** [comment]
No worries :)

FYI, the supported syntaxes are documented [here](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/css-processors.md#parsing-non-standard-syntax) and [here](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#syntax).
