### ISSUE TITLE
feature request  : add css like a valid syntax option

### ISSUE THREAD

**Issue by grrseguin** [stylelint/stylelint#1676]
Hello,

When `stylelint-loader` is a preLoader in webpack.config file with the test `/\.css$/` this error appeared : [`You must use a valid syntax option, either: scss, less or sugarss`](https://github.com/stylelint/stylelint/blob/7.0.3/src/standalone.js#L139).

The stylelint configuration is below : 
```json
  "devDependencies": {
    "stylelint": "7.0.3",
    "stylelint-config-standard": "11.0.0",
    "stylelint-loader": "6.0.0"
  },
  "stylelint": {
    "extends": "stylelint-config-standard"
  },
```

```javascript
// webpack.config.js
module: {
    preLoaders: [{
      test: /\.css$/,
      loader: 'stylelint-loader'
    }],
```

The version using is `7.0.3`.

PostCSS can transform styles in any syntax, CSS file extension include. 
Stylelint is powered by PostCSS.

Therefore, is it possible to add CSS file extension in the [`lintString`](https://github.com/stylelint/stylelint/blob/7.0.3/src/standalone.js#L132) method ?

> No problem to parse CSS with the CLI.

**Comment by jeddy3** [comment]
I think this is a 7.0.0 compatibility issue downstream in `stylelint-loader`.

This [line of code](https://github.com/adrianhall/stylelint-loader/blob/master/index.js#L89) isn't compatible with `7.0.0`. The [peer dependency](https://github.com/adrianhall/stylelint-loader/blob/master/package.json#L30-L32) is set to `stylelint@^6.0.0`, so you'll need to use stylelint version 6 until a new, `7.0.0` compatible, version of `stylelinter-loader` is out. I suggest filing a issue downstream.

Or, if you want to use `stylelint@7.0.0` now you could try using[`postcss-loader`](https://github.com/postcss/postcss-loader) and use stylelint [as a PostCSS plugin](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md). 

Or, scrap the loader and use the stylelint CLI via npm-scripts. There willl never be incompatibility issues then.
