### ISSUE TITLE
no-browser-hacks showing $ and !default as errors

### ISSUE THREAD

**Issue by s10wen** [stylelint/stylelint#1710]
Regarding:
https://github.com/stylelint/stylelint/blob/master/src/rules/no-browser-hacks/README.md

I'm getting errors for `$colour-alpha` and `!default` which is valid Sass code.

Appreciate this is a Sass specific question, but wondering if there's a way to whitelist `$` and `!default` for this rule please?

**Comment by evilebottnawi** [comment]
@s10wen 
> stylehacks is only compatible with standard CSS syntax, and does not support nested properties nor custom property sets.
This rule now works only with standard css, not working with `scss`, `less` and etc, maybe in future major release if I have time, maybe I'll think about this decision issue.

**Comment by s10wen** [comment]
Moved over to: https://github.com/kristerkari/stylelint-scss/issues/60
