### ISSUE TITLE
Incorrect behavior if font-family is also a color name

### ISSUE THREAD

**Issue by ViLPy** [stylelint/stylelint#1712]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Incorrect behavior if `font-family` is also a color name and `font-family-name-quotes` enforces using no quotes for font-family. With quoted font-family name (`"font-family-name-quotes": "always-unless-keyword"`) I have no exceptions

> Which rule, if any, is this issue related to?

`color-named` with certain cases of `font-family-name-quotes`

> What CSS is needed to reproduce this issue?

```css
.foo {
  font-family: Brown, sans-serif;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "color-named": "never",
    "font-family-name-quotes": "always-where-recommended"
  }
}
```

> Which version of stylelint are you using?

`7.0.3`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

no color name checks for font-family

> What actually happened (e.g. what warnings or errors you are getting)?

`color-named` rule applied to font-family

```shell
 4:18  ✖  Unexpected named color "Brown"   color-named
```

**Comment by jeddy3** [comment]
@ViLPy Thanks for writing up a detailed report.

We can ignore `font` and `font-family` declarations within `color-named` [just after here](https://github.com/stylelint/stylelint/blob/master/src/rules/color-named/index.js#L39).
