### ISSUE TITLE
Create `hasInterpolation` util

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1716]
Right now this line is being repeated throughout the `isStandardSyntax*` utils: https://github.com/stylelint/stylelint/blob/master/src/utils/isStandardSyntaxSelector.js#L10.

The repetition indicates that that should be taken out into its own util that gets re-used by the others. Additionally, it might be useful on its own. We pretty much always want to ignore interpolated strings, after all.

Open of course to another function name :)

**Comment by sendilkumarn** [comment]
how about `isInterpolation` ?

**Comment by jeddy3** [comment]
`hasInterpolation`? We've [used `has`](https://github.com/stylelint/stylelint/blob/master/src/utils/index.js#L16-L18) in similar contexts before.

**Comment by ntwb** [comment]
Nice, @sendilkumarn as you've done it already except the name change marking this `status: wip`

**Comment by sendilkumarn** [comment]
Thanks @ntwb
