### ISSUE TITLE
colon-space-after

### ISSUE THREAD

**Issue by alan-agius4** [stylelint/stylelint#1721]
Would be nice to have linting on SASS variables as well
example code: 

`$navbar-link-text-color:#f0f !default;
`

Such as: "declaration-colon-space-after": "always-single-line", as at the moment these are not being linted.

Not sure if this is a bug or intended to be liked this.

**Comment by jeddy3** [comment]
> Not sure if this is a bug or intended to be liked this.

It's intended. Non-standard constructs and syntax are ignored in core rules. They can then be targeted in plugins.

Rather serendipitously, the `stylelint-scss` added these exact rules to their plugin pack [two days ago](https://github.com/kristerkari/stylelint-scss/releases/tag/1.3.0).  

In the future, please use the issue template. We deal with quite a few new issue every day and having a consistent format helps us parse through them quicker.

**Comment by alan-agius4** [comment]
thanks
