### ISSUE TITLE
New rule: comment-case

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#174]
Right now #1 suggests 2 options: `"lower"` and `"sentence"`. I'm wondering if there's anything we could meaningfully enforce for `"sentence"`. Presumably we'd look to see that the first character is capitalized. After that, though, we couldn't do much without making assumptions that are probably too general (e.g. after any period the next character should be capitalized). Unless @stylelint/owners have better ideas for what `"sentence"` could mean, I'd suggest we change this rule to `comment-lower-case` and just have it enforce lowercase. (But even with just that, I wonder if the assumption is too broad, since capital letters might come into play even if sentence beginnings, proper nouns, etc. are not capitalized ... e.g. `/* these are the colors of the US flag */` `/* i'm trying to follow SOLID principles */`)

**Comment by MoOx** [comment]
This seems like a weird (useless?) rule. I means, I don't see how this is improving code quality :)

**Comment by jeddy3** [comment]
> This seems like a weird (useless?) rule. I means, I don't see how this is improving code quality :)

Yeap, I'm trying to remember why I added that rule. I'm sure I remember seeing it in some other linter somewhere, but I agree its usefulness might not outweigh its complexity. Perhaps we should focus on an, arguably, more useful rule that lets the user specifiy whether there must or mustn't be a space between the comment markers and the comment itself e.g.:

* `comment-space-inside`: `string` `"always"|"never"`

e.g. `/*never*/` vs `/* always */`

Similar to the [`spaced-line-comment`](http://eslint.org/docs/rules/spaced-line-comment) rule in eslint.

**Comment by MoOx** [comment]
> comment-space-inside

Hell yeah.

**Comment by davidtheclark** [comment]
Let's go with that. I'll close this issue and open one for comment-space-inside.
