### ISSUE TITLE
Add checkPrefixed: true option to property-no-unknown

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1760]
Change the default behaviour to ignore vendor prefixed properties, making the rule:

- Consistent with `at-rule-no-unknown`.
- More permissive (therefore a non-breaking change).

Add `checkPrefixed: true` secondary option to reenabled old behaviour.

**Comment by evilebottnawi** [comment]
@jeddy3 I suggested to do it already :smile: 
sgtm, my opinion is all rules `*-no-unknown` should ignore vendor prefixed by default

**Comment by jeddy3** [comment]
> I suggested to do it already

I know. These new issues as based on your thoughts in https://github.com/stylelint/stylelint/issues/1739.

> my opinion is all rules `*-no-unknown` should ignore vendor prefixed by default

Ok, in addition to `property-no-unknown`, we currently have the following `*-no-unknown` rules:

- `at-rule-no-unknown`
- `selector-pseudo-class-no-unknown`
- `selector-pseudo-element-no-unknown`
- `selector-type-no-unknown`
- `unit-no-unknown`

Seemingly, only `at-rule-no-unknown` currently ignores prefixed things. I can't think of any prefixed *units*, *type selectors* or *pseudo classes*, but there seems to be plenty of prefixed *pseudo elements*. 

I'm happy to see vendor prefixed properties ignored by default in `selector-pseudo-element-no-unknown`.

**Comment by jeddy3** [comment]
> in major? breaking changes

Nope, these changes will make the rules more permissive.

**Comment by davidtheclark** [comment]
SGTM

**Comment by jeddy3** [comment]
It turns out there are [plenty of](https://github.com/postcss/autoprefixer/releases) prefixed pseudo classes too, not just pseudo elements.

I guess me not realising this is testament to autoprefixers usefulness. We don't really have to think about prefixes anymore.

Anyhow, lets ignore prefixes by default for *all* of the `*-no-unknown` rules.

**Comment by gaidarenko** [comment]
Guys let me fix this issue. Assign it to me.

**Comment by evilebottnawi** [comment]
@gaidarenko let's rock

**Comment by jeddy3** [comment]
@gaidarenko Good luck and thanks for helping out. You'll find plenty of information in the [developer guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) to help you get started.

**Comment by jeddy3** [comment]
Done in #1770
