### ISSUE TITLE
Docs: Clarify how to use optional properties?

### ISSUE THREAD

**Issue by jegtnes** [stylelint/stylelint#1776]
Hey there folks,

Thanks for the great tool; discovered it today and I'm loving it. One thing I noticed upon trying to configure it to my project needs is that the docs aren't clear on how to use the optional properties where they exist, so I attempted to use optional rule options as a top-level configuration key-value pair instead of placing it in an object alongside the main rule option in an array.

I think there's scope in the docs for explaining how to use optional properties, possibly in the [About rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md) section to prevent duplication of this information in every rule file with optional properties. If you agree this is a good idea, I'm happy to write up a little section myself; just wanted to check in with the maintainers to find out whether this is something you'd want in stylelint first. 🤘🏻

**Comment by jeddy3** [comment]
@jegtnes Thanks for offering to help.

Did you see the ["Configuration Object" section](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object) of the [User guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide.md)?

By looking into this, I noticed we call them "Secondary" options in the config guide (and within the [developer guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#determine-options)) and "Optional" options within the rule READMEs. Perhaps normalising the naming will help e.g. "Optional secondary options"?
