### ISSUE TITLE
declaration-comma-* flexibility

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#178]
I'm almost finishing plugging in all 60+! rules into the test bed. Everything is remarkably intuitive and almost everything worked first time. This is last of the issues that have popped up.

Given:

```css
a {
  background-image: url("x.jpg"),
    linear-gradient(#f3c, #4ec);
}
```

The indentation of the 2nd value is currently supported (by the `indentation` rule), but we lack a rule to enforce the newline after the comma in the declaration. Currently we have `declaration-comma-space-before|after`. I was going to add `declaration-comma-newline-before|after`, but I realised we might need some flexibility here.

Similarly to `rule-semicolon-newline|space-after|before` rules and their `always-multi|single-line` options, should we offer that for `declaration-comma-newline|space-before|after`? Where the `always-multi|single-line` options refer to multiple or single line value lists.

So, given:

```js
declaration-comma-newline-after: [2, "always-multi-line"]
declaration-comma-space-after: [2, "always-single-line"]
declaration-comma-space-before: [2, "never"]
```

You'd be able to enforce this:

```css
a {
  background-image: url("x.jpg"), url("y.jpg"), 
}

b {
  box-shadow: 1px 1px 1px #000,
    2px 2px 1px 1px #ccc inset,
    2px 2px 1px 2px #ccc inset;
}
```

Perhaps reusing the `always-multi|single-line` options will be confusing. Perhaps something for specific like `always-multi|single-line-values`?

If there is value in this approach, does this then need to be applied to the likes of `media-query-list-comma-*` or are we opening up a can of worms here?

**Comment by davidtheclark** [comment]
`media-query-list-comma-*` already has newline rules, I right?

I wonder if this should be renamed to `property-value-comma-*`. That is more specific and accurate. Then you don't have the ambiguity about whether the declaration is multiline or the value, etc.?????

Seems like good additions to me.

**Comment by jeddy3** [comment]
> media-query-list-comma-* already has newline rules, I right?

Yes, you're right. Forget I mentioned `media-query-list-comma-*` :)

> I wonder if this should be renamed to property-value-comma-*.

Good shout. I think there are two decisions to be made here:

1. Should we be specific and use `property-value-*` or broad and use just `value-*`. At the moment will have a mix-match of both.
2. What's a good name for a list of values.

---

Regarding 1: The crux is that values can *also appear in at rules* ([ref](http://dev.w3.org/csswg/mediaqueries-4/#values)) and I don't think we've taken account of this.

```css
@media only screen and (min-width: 35em) {}
```

Where `35em` is also a value ([vocab ref](http://apps.workflower.fi/vocabs/css/en#value)).

I think we have two options:

1. Make the existing rules more specific e.g. `number-leading-zero` -> `property-number-leading-zero`. And then add new set of rules for at rules e.g. `at-rule-number-leading-zero`.
2. Adapt the existing value rules to also check the values within at rules i.e. we keep the same rules, e.g. `number-no-trailing-zero`, but increase their capabilities. For example, given `number-no-trailing-zero`: `"never"` the follow css would flag up two warnings:

```css
@media only screen and (min-width: 35.0em) {
  a {
    width: 35.0em;
  }
}
```

Two warnings: one for the `35.0em` value in the declaration *and* one for `35.0em` value in the at rule.

I think the latter approach is better as I suspect users will want to enforce the same style on values regardless of whether they appear as property values or as feature values within at rules.

I think only the following number rules will need to be adapted:

* `number-leading-zero`: `"always"|"never"` Require or disallow a leading zero before number
* `number-no-trailing-zeros`: Disallow trailing zeros (e.g. `5.0px`)
* `number-max-precision`: `int` Maximum number of digits after the "." in a number
* `number-zero-length-no-unit`: Disallow units for zero length vaues

I could only find examples of numbers and idents in the [Media Query Spec](http://dev.w3.org/csswg/mediaqueries-4/), so I don't think the `string-*` or `*-url-*` rules need adapting.

Sound good?

Also, the `property-value-no-vendor-prefix` rule would become `value-no-vendor-prefix`. Although, I don't think any change in functionality is required as I can't think of any instances of vendor prefixed *values* in media queries. The name change is, therefore, only for consistency.

However, there are a few vendor prefixed *media feature names* (ref:  https://gist.github.com/marcedwards/3446599). I think it makes sense create a new rule for this and keep it separate from `property-no-vendor-prefix`.

* `media-feature-name-no-vendor-prefix`: `"always"|"never"`

What do you think?

---

Regarding 2.

How about a new *thing* called `value-list`? It is generic enough to capture both "alternative" value lists like font-family (http://www.w3.org/TR/css3-fonts/#font-family-prop) and "multiple" value lists like background-image (http://www.w3.org/TR/css3-background/#layering). The naming is also consistent with `media-query-list-*`.

`value-list-comma-*` would replace `declaration-comma-*`. And, as you pointed out, this name will remove the ambiguity of whether `single-line` and `multi-line` applies to the list of values or the declaration. 

Giving us the following rules:

* `value-list-comma-newline-after``: `"always"|"never"|"always-multi-line"`
* `value-list-comma-newline-before``: `"always"|"never"|"always-multi-line"`
* `value-list-comma-space-after``: `"always"|"never"|"always-single-line"`
* `value-list-comma-space-before``: `"always"|"never"|"always-single-line"`

As example:

So, given:

```js
value-list-comma-newline-after: [2, "always-multi-line"]
value-list-comma-space-after: [2, "always-single-line"]
value-list-comma-space-before: [2, "never"]
```

You'd be able to enforce this css together:

```css
a {
  font-family: sans, serif, monospace /* value-list single-line with space after */
}

b {
  box-shadow: 1px 1px 1px #000, /* value-lust multi-line with newline after... */
    2px 2px 1px 1px #ccc inset,     /* ... */
    2px 2px 1px 2px #ccc inset;     /* ... */
}
```

---

I don't think there is much need to adapt the `number-*` rules before `0.1.0`, but it would be good to get everything named consistently by then so the intent is clear.

What do you think?

**Comment by davidtheclark** [comment]
I agree with everything you said, I think. It would be great if you'd rework the names and #1 and then file issues for those rules that need to be altered before they fit their new name.

**Comment by jeddy3** [comment]
@davidtheclark Renaming done, issues added and #1 updated.
