### ISSUE TITLE
False negatives for some properties in declaration-block-no-redundant-longhand-properties and declaration-block-no-shorthand-property-overrides

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1780]
New shothand:
- `animation`
- `border-block-end`
- `border-block-start`
- `border-image`
- `border-inline-end`
- `border-inline-start`
- `column-rule`
- `columns`
- `flex`
- `flex-flow`
- `grid`
- `grid-area`
- `grid-column`
- `grid-gap`
- `grid-row`
- `grid-template`
- `mask`
- `outline`
- `text-decoration`
- `text-emphasis`
- `transition`

This can do breaking changes.

**Comment by jeddy3** [comment]
Is there a definitive resource where we can be sure we've got these shorthand properties?

What about upcoming specs like grid?

**Comment by evilebottnawi** [comment]
@jeddy3 tomorrow i'll look at all the properties in the specification. Label `need investigation`?

**Comment by evilebottnawi** [comment]
@jeddy3 i refresh all shorthand properties in first message, feel free to edit and discussion.

**Comment by jeddy3** [comment]
Sgtm.

**Comment by ideadapt** [comment]
@jeddy3 I recently found https://drafts.csswg.org/indexes/#properties. Its looks quite interesting too me.
So, I started to scrape that page, see https://github.com/a-axton/css-properties-values/pull/1. In the end you have a list of properties filterable by e.g. css version, css module, name, values etc.

**Comment by jeddy3** [comment]
@evilebottnawi What rules are affected by this change?

**Comment by evilebottnawi** [comment]
@jeddy3 `declaration-block-no-redundant-longhand-properties`, `declaration-block-no-shorthand-property-overrides`

**Comment by evilebottnawi** [comment]
@jeddy3 what about `8.0.0` milestone here?

**Comment by jeddy3** [comment]
Yes. This is a pre-`8.0.0` *major* change. After that it would be *minor*.

**Comment by davidtheclark** [comment]
Closed by #2354.
