### ISSUE TITLE
Add 'never' option to 'block-opening-brace-newline-before' rule

### ISSUE THREAD

**Issue by KatiRasanen** [stylelint/stylelint#1793]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

'Block-opening-brace-newline-before' has option 'always' but not option 'never'. I don't want to have the newline before the opening brace at all, but with current options I need to choose either 'never-single-line' or 'never-multiline'.

Why this rule also effects to whitespace before the opening brace? I'm using 'block-opening-brace-space-before' rule with option 'always' and this is a bit against that.

> Which rule, if any, is this issue related to?

'block-opening-brace-newline-before'

> What CSS is needed to reproduce this issue?

a {
color: pink; 
}

b { color: blue; }

> Which version of stylelint are you using?

7.1.0

**Comment by jeddy3** [comment]
@KatiRasanen Thanks for the report.

>  I'm using 'block-opening-brace-space-before' rule with option 'always' and this is a bit against that.

If you're using `block-opening-brace-space-before: "always"` then you shouldn't use the `block-opening-brace-newline-before` rule.  `block-opening-brace-space-before: "always"` will ensure that there is always a single space before the open brace i.e. it'll disallow multiple spaces and newlines.

There's [a section](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#rules-work-together) in the user guide that explains how these whitespace rules work together. It might seem complicated at first, but it affords flexibility for lots of different code styles.
