### ISSUE TITLE
Unable to load stylelint plugin (eg. stylelint-selector-bem-pattern)

### ISSUE THREAD

**Issue by rgrjoh** [stylelint/stylelint#1796]
I’m running stylelint via the PostCSS plugin and it works fine.

However I am unable to load stylelint plugins. I’m mainly interested in using stylelint-selector-bem-pattern instead of postcss-bem-linter, but when I test another stylelint plugin the same problem occurs so I’m posting this here instead of in the stylelint-selector-bem-pattern repo since the problem doesn’t seem to be specific to that plugin.

I have installed the plugin by adding it to my package.json file and then running npm install. I then updated my .stylelintrc according to https://github.com/davidtheclark/stylelint-selector-bem-pattern:

```
"plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    // ...
    "plugin/selector-bem-pattern": {
      // ...
```

What happens when I run postcss (via grunt, if that matters) is this:

Fatal error: Could not find "stylelint-selector-bem-pattern". Do you need a `configBasedir`?

The only workaround I have been able to come up with is specifying the absolute path to the plugin in .stylelintrc, but that feels like a hack, and doing that is not an option in projects with multiple developers.

I tried adding a configBasedir option with the absolute path to the “node_modules” where the plugin is installed, but that made no difference.

I have not been able to find any information about this problem so it’s quite possible that I’m doing something wrong. What am I missing?

**Comment by davidtheclark** [comment]
@rgrjoh Could you please tell us about your directory structure: where your config is, where your node_modules are, where you run the command from, etc.?

**Comment by m-allanson** [comment]
@rgrjoh A stripped-down example repo that demonstrates the problem could also be useful.

**Comment by rgrjoh** [comment]
See the attached minimised example for the directory structure. I run the grunt commands (in the example ”grunt postcss”) from inside the grunt directory.
[stylelint-selector-bem-pattern-test.zip](https://github.com/stylelint/stylelint/files/417591/stylelint-selector-bem-pattern-test.zip)

**Comment by m-allanson** [comment]
Thanks @rgrjoh, that's useful for investigation. 

As a temporary workaround you should be able to move your `.stylelintrc` into the `grunt` folder, or write it as a `stylelint` property of your `package.json`. The [configuration docs](http://stylelint.io/user-guide/configuration/) have more information.

**Comment by rgrjoh** [comment]
@m-allanson I tried moving things around and it looks like `.stylelintrc` and `node_modules` need to be on the same level or stylelint won’t find its plugins.

I’d rather avoid moving either of them though. Any idea if it’s possible to get the configuration for that right, or does stylelint need changes for that?

**Comment by davidtheclark** [comment]
> it looks like .stylelintrc and node_modules need to be on the same level or stylelint won’t find its plugins

This makes sense. For the same reasons, you couldn't `require('some-module')` from a folder that is a parent to the `node_modules`, right? Because of this, it is common practice to always have `node_modules` at the root of the project. So I do not think this is a problem with stylelint. 

If you can think of a way to improve documentation so others are not confused in the same way in the future, please submit a PR. 

Thanks!

**Comment by m-allanson** [comment]
@davidtheclark This might be a bug with `configBasedir` not being respected.

My understanding is that with a directory stucture of:

```
.stylelintrc
config/
|- node_modules/ 
|- lint.js
|- package.json
```

where `.stylelintrc` is like:

```
{
	"plugins": [
		"./stylelint-selector-bem-pattern"
	],
	"rules": {
		"plugin/selector-bem-pattern": { ... }
	}
}
```

and `lint.js` is like:

```
stylelint.lint({
  configFile: '../.stylelintrc',
  configBasedir: path.join(__dirname, 'node_modules'),
  code: 'a { color: black; }'
})
```

Then stylelint should load the plugin at `config/node_modules/stylelint-selector-bem-pattern`, but that doesn't appear to be happening. I'll open a new issue if I can nail this down with a test or two.

**Comment by rgrjoh** [comment]
@m-allanson Right, that is the feeling I get as well, that changing `configBasedir` doesn’t do anything. Thanks for looking into it.

**Comment by Goldziher** [comment]
This issue is still occuring. 

These are the current packages I have in my project:

```
"stylelint": "^10.1.0",
"stylelint-a11y": "^1.2.1",
"stylelint-config-prettier": "^5.2.0",
"stylelint-config-recess-order": "^2.0.3",
"stylelint-config-recommended-scss": "^3.3.0",
"stylelint-csstree-validator": "^1.5.2",
"stylelint-group-selectors": "^1.0.7",
"stylelint-prettier": "^1.1.1",
"stylelint-scss": "^3.9.4",
```

specifying configBasedir doesn't matter. So the solution I have:

```
const { resolve } = require('path')

const basePath = resolve(__dirname, 'node_modules')
const groupSelectors = `${basePath}/stylelint-group-selectors`
const cssTreeValidator = `${basePath}/stylelint-csstree-validator`

module.exports = {
	plugins: [groupSelectors, cssTreeValidator],
	extends: [
		'stylelint-config-recommended-scss',
		'stylelint-config-recess-order',
		'stylelint-prettier/recommended',
		'stylelint-scss',
		'stylelint-a11y/recommended',
	],
	rules: {
		'no-empty-source': null,
		//check and add avaialble rules here: https://github.com/kristerkari/stylelint-scss
		'scss/selector-no-redundant-nesting-selector': true,
		'plugin/stylelint-group-selectors': true,
		'csstree/validator': true,
	},
}
```
