### ISSUE TITLE
max-nesting-depth: add ignore pseudoclasses, pseudoselectors and pseudoelements

### ISSUE THREAD

**Issue by nicothin** [stylelint/stylelint#1829]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

new option

> Which rule, if any, is this issue related to?

`max-nesting-depth`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  color: pink;
  &:hover {
    .bar {...}
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "rules": {
    "max-nesting-depth": [3, {
      "ignore": ["at-rules-without-declaration-blocks"]
    }],
  }
}
```

> Which version of stylelint are you using?

`7.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `.stylelintrc`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to LESS, SCSS ect.

> What did you expect to happen?

add option for ignore pseudoclasses, pseudoselectors and pseudoelements for calculate level nesting depth.

**Comment by jeddy3** [comment]
@nicothin Thank for your suggestion.

Unlike the [recent addition](https://github.com/stylelint/stylelint/pull/1805/files) of `ignoreAtRules`, where the use case was things like `@print` and `@supports`, this request seems to be more about specificity. As such, I'm closing this in favour of advocating the use of `selector-max-specificity` and/or `selector-max-compound-selectors`.

I think inspecting selector themselves is outside the scope of this rule, as that's a can of worms. I think what you want to achieve can be done with a combination of those aforementioned rules, as both *resolve nested selectors* before checking.

**Comment by nicothin** [comment]
@jeddy3 
use of `selector-max-specificity` and/or `selector-max-compound-selectors` to resolve
```
.block {
  color: pink;
  &__elem {
    &:hover {
      .bar {...}
    }
  }
}
```
but to prohibit the
```
.block {
  color: pink;
  &__elem {
    .bar {...}
  }
}
```
how?

I think this is a job for `max-nesting-depth` )

**Comment by jeddy3** [comment]
I don't understand. If you ignore the pseudo class, isn't the depth of `.bar` the same for those two examples?

**Comment by nicothin** [comment]
@jeddy3 exactly!
I want to calculate the depth of nesting without the influence of pseudoclasses, pseudoselectors and pseudoelements.
In the two examples I would like to have the same count the nesting.

**Comment by inspiratweb** [comment]
I think this is solved here: https://github.com/stylelint/stylelint/pull/3724
You can test it using stylelint: "9.8.0"

**Comment by niksajanjic** [comment]
It is possible to ignore pseudo-classes and blockless-at-rules, but not pseudo-elements for now.
