### ISSUE TITLE
Create CSSLint to styleling migration guide

### ISSUE THREAD

**Issue by ideadapt** [stylelint/stylelint#1834]
Because of https://github.com/CSSLint/csslint/issues/668 I think its best to have a document that explains end users how to migrate. I started with a markdown sketch. Maybe we can create a wiki page based on it, so that we can continuously update it while the [implementation](https://github.com/stylelint/stylelint/milestone/22) is in progress.

What do you think?

Here it goes:

---

# Migrating from CSSLint to stylelint
This page summarizes the outcome of the [initiative to consolidate CSSLint and stylelint](https://github.com/CSSLint/csslint/issues/668).

## CSSLint rules ported to stylelint

| CSSLint | stylelint | changes |
|---|---|---|
| known-properties | property-no-unknown | added checkPrefixed option stylelint/stylelint#1760 |
| disallow-duplicate-properties | declaration-block-no-duplicate-properties | added ignore: ["consecutive-duplicates-with-different-values"] stylelint/stylelint#1759 |

## CSSLint rules not available in stylelint

* [outline-none](https://github.com/CSSLint/csslint/wiki/Disallow-outline%3Anone) (see [issue 1758]( https://github.com/stylelint/stylelint/issues/1758))
* https://github.com/CSSLint/csslint/wiki/Require-standard-property-with-vendor-prefix
* https://github.com/CSSLint/csslint/wiki/Don%27t-use-too-many-web-fonts
* https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors
* https://github.com/CSSLint/csslint/wiki/Disallow-overqualified-elements
* ... list not complete yet!

If any of the above rules should be available in stylelint, they require to be provided via plugin. As of now, there is no such plugin. See [issue 668](https://github.com/CSSLint/csslint/issues/668) for an progress on this subject.

**Comment by jeddy3** [comment]
@ideadapt Thanks for writing this up.

We've already created separated issues [to track](https://github.com/stylelint/stylelint/milestone/22) the changes to core. The rest of the work needs to happened outside of the stylelint org, likely in a plugin called `stylelint-csslint`. I think the migration guide your propose it a great idea and it belongs there.

@ideadapt If you'd like to lead this initiative feel free to create a `stylelint-csslint` repo within your own username to get the ball rolling (the repo can always be moved if a new home is agreed on). I suggest basing the repo on [`stylelint-scss`](https://github.com/kristerkari/stylelint-scss), as it's an example of an excellent plugin *pack*. Feel free to *mention* the relevant people from that repo if you want input on a particular issue.
