### ISSUE TITLE
declaration-block-no-ignored-properties doc typo

### ISSUE THREAD

**Issue by OmgImAlexis** [stylelint/stylelint#1875]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

There's a typo in the docs for `declaration-block-no-ignored-properties`.

Ref: https://github.com/stylelint/stylelint.github.io/pull/6

**Comment by ntwb** [comment]
Thanks @OmgImAlexis, did you want to create a pull request with the fix for this?

**Comment by OmgImAlexis** [comment]
Not entirely sure which file I need to edit but sure.

**Comment by ntwb** [comment]
@OmgImAlexis Awesome, it's in this file: https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-ignored-properties/README.md
