### ISSUE TITLE
API for configuration file

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#1882]
[stylefmt](https://github.com/morishitter/stylefmt) is a tool that automatically formats stylesheets.
[stylefmt](https://github.com/morishitter/stylefmt) can understand the formatting rules specified in your stylelint configuration file (.stylelintrc).
stylelint should provides api to load its configuration (e.g. stylelint.buildConfig).

@morishitter will use this to load configuration.

**Comment by evilebottnawi** [comment]
@gucong3000 why? it is separate tools. All configuration can found in `config`.

**Comment by gucong3000** [comment]
```javascript
function loadStylelintConfig (options) {
  // same as the options in stylelint. see: http://stylelint.io/user-guide/node-api/#options
  try {
    return require('stylelint/dist/buildConfig').default(options).catch(function() {
      return;
    });
  } catch (ex) {
    //
  }
  return cosmiconfig('stylelint', {
    argv: false,
    rcExtensions: true,
    configPath: options.configFile || (typeof options.config === "string" ? options.config : undefined),
  })
}
```

`require('stylelint/dist/buildConfig')` is too dirty.

**Comment by gucong3000** [comment]
@evilebottnawi `stylefmt` has another configuration file loading mode, if stylelint can open API, stylefmt can be simple

**Comment by morishitter** [comment]
@gucong3000 

> stylefmt has another configuration file loading mode

Is this your PR https://github.com/morishitter/stylefmt/pull/192 ? I don't want to have original configuration file in stylefmt.

**Comment by gucong3000** [comment]
@morishitter Yes, it is my PR.
If you don't need original configuration file, I will use it for merge [editorconfig](http://editorconfig.org/) configuration file,

**Comment by evilebottnawi** [comment]
@gucong3000 can you give example usage?

**Comment by Arcanemagus** [comment]
@evilebottnawi This would be somewhat nice in the Atom `linter-stylelint` package. Currently we are also running `cosmiconfig` and then just passing the results into Stylelint.

If Stylelint provided an API to return the configuration for a given path, this would mean that all of the third party utilities that run Stylelint can have a single source of getting a configuration, that is the same source used internally. This means everything using the API can be sure it is starting with the same configuration that Stylelint itself would be using.

I was sure this had been discussed in a different issue, but can't find it at the moment.

**Comment by gucong3000** [comment]
@Arcanemagus 
> If Stylelint provided an API to return the configuration for a given path

Not yet. I'am doing this job.
#1881 #1886

Can you help me to convince @evilebottnawi? English is not my native language.

**Comment by gucong3000** [comment]
@evilebottnawi 
> can you give example usage?

In Atom `linter-stylelint`, we can lookup configuration file like this:
```javascript

stylelint.buildConfig({
	configLookup: dirname(filePath)
})
.then(config => {
	// get config for file in `filePath`
})
```

see #1884

**Comment by davidtheclark** [comment]
This is an interesting discussion. I will be able to think more about it and chime in when I'm back from vacation in a couple of weeks. Sorry for the delay.

**Comment by davidtheclark** [comment]
A few quick words, in case more discussion happens before I check in again:

I agree with @gucong3000 and @Arcanemagus that it would make sense for stylelint to expose a way to lookup the config file that it will use when it runs. This point is especially good:

> This means everything using the API can be sure it is starting with the same configuration that Stylelint itself would be using.

The API that I imagine right off the top of my head is a specialized exposed function, something like `stylelint.lookupConfigFrom(startingPath)`.

**Comment by Arcanemagus** [comment]
That's exactly what I suggested here: https://github.com/stylelint/stylelint/pull/1884#issuecomment-245357293 😛

**Comment by davidtheclark** [comment]
I think this is a good idea that does not need to modify or get in the way of any existing behavior. So I labeled the issue to suggest that it's ready to be worked on.

**Comment by davidtheclark** [comment]
Working on this in PR #1930.
