### ISSUE TITLE
New features: work with `editorconfig`

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#1890]
I usually use `stylelint` and `editorconfig` together, So I need a option property for these rules, let them use configuration of `editorconfig`
- indentation
- no-eol-whitespace
- no-missing-end-of-source-newline

I hope this option property is enabled by default, If configuration property of `editorconfig` is missing, please use the same logic as before.

see https://www.npmjs.com/package/editorconfig

**Comment by evilebottnawi** [comment]
@gucong3000 not related to `stylelint`, you can create own package, which created config file from `editorconfig` to `stylelint` rules.

**Comment by evilebottnawi** [comment]
@gucong3000 also you can created plugin for this

**Comment by gucong3000** [comment]
Stylelint plugin can not get other rules configuration information and modify.
I need a hook to modify configuration object when configuration file load by style file's path.
I need some help.

**Comment by gucong3000** [comment]
I'm trying to on local.
`.stylelintrc.json`:
```json
{
  "extends": "./stylelint-editconfig"
}
```

`stylelint-editconfig.js`:

```javascript
const editorconfig = require("editorconfig")
module.exports = function (config) {
  if (config.sourcePath) {
    return editorconfig.parse(config.sourcePath).then(editorConfig => {
      return {
        rules: {
          "indentation": editorConfig.indent_size,
          "no-eol-whitespace": editorConfig.trim_trailing_whitespace,
          "no-missing-end-of-source-newline": editorConfig.insert_final_newline,
        },
      }
    })
  } else {
    return {}
  }
}
```

It is work well, but I need to modify `buildConfig.js` basis on PR #1888.

```javascript
function stripIgnoreFiles(config) {
  delete config["ignoreFiles"]
  return config
}

function mergeConfigs(a, b, options) {
  if (typeof b === "function") {
    b = b(options)
  }
  return Promise.resolve(b).then(b => {
    const pluginMerger = {}
    if (a.plugins || b.plugins) {
      pluginMerger.plugins = union(a.plugins, b.plugins)
    }
    const rulesMerger = {}
    if (a.rules || b.rules) {
      rulesMerger.rules = assign({}, a.rules, b.rules)
    }
    return assign({}, b, a, pluginMerger, rulesMerger)
  })
}
```

**Comment by gucong3000** [comment]
I can publish a package, the name is called `stylelint-config-editorconfig`, when #1888 is merged.

**Comment by davidtheclark** [comment]
@gucong3000 looks like you've got a good solution for this in your separate package. We'll work on #1888 independently.
