### ISSUE TITLE
Add pull request template?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1891]
On a few occasions we've had Pull requests that should probably be discussed as issues first. Keeping the initial discussions in the issue tracker and the work in the pull request tracker makes it a bit easier to keep track of what's going on.

As such, how do we feel about adding a pull request template to that effect (for non core members)? 

I think doing so will also cut down on the number of times we need to request accompanying documentation changes (especially changelog ones)...

---

Please read the following. Pull requests that do not adhere to these guidelines will be closed.

Each pull request must, with the exception of minor documentation fixes, be associated with an open issue. If a corresponding issue does not exist please stop. Instead, create an issue so we can discuss the change first.

If there is an associated open issue, then the next step is to run through the relevant checklist:

- Adding a rule: https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#write-the-rule
- Adding an option: https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-options-to-existing-rules
- Fixing a bug: https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-bugs

If you've done that, then please continue and create this pull request. Thank you for contributing.

---

**Comment by evilebottnawi** [comment]
@jeddy3 sgtm, we needed template :+1:

**Comment by ntwb** [comment]
SGTM, added a PR per the suggested verbiage to see how it looks and renders.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/issues/1896
