### ISSUE TITLE
False positive for -ms-high-contrast (selector-no-vendor-prefix)

### ISSUE THREAD

**Issue by Nazin** [stylelint/stylelint#1893]
Linter throws an error for the following code:
@media print and (-ms-high-contrast: none), (-ms-high-contrast: active) {

  21:23  error  Vendor prefixes should not be used  no-vendor-prefixes

While it shouldn't. -ms-high-contrast is specific to IE and exists only there.

**Comment by jeddy3** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
