### ISSUE TITLE
New rule: rule-set-no-single-line

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#19]
Disallow single line rule-sets (true/false).

I will work on this soon. For this and #18 I will write a utility function to test whether a block contains any line breaks.

**Comment by davidtheclark** [comment]
Done in a1b9679fb3b423bada679b43f1f69a012093d7d6

**Comment by MoOx** [comment]
Do you know you can close directly issue via commit message/description ?

Example
```
Added: new rule `rule-set-no-single-line`
Closes #19
```

You can use "closes", "close", "fixes" and "fix" to close issues. Only commit messages _in master branch_ might close issue (so on pr, once pr get merged).

**Comment by davidtheclark** [comment]
Yep. Always forget at the crucial moment :)

**Comment by MoOx** [comment]
Np ;)
