### ISSUE TITLE
Integrate stylefmt into stylelint

### ISSUE THREAD

**Issue by gajus** [stylelint/stylelint#1901]
There is no value in asking users to install two separate packages, `stylelint` and `stylefmt`. I would go as far as to say that there is no value to maintain these two as separate projects, but this question is outside of the scope of this issue.

It would be nice if an agreement was made where @stylelint efforts are combined with @morishitter and "stylefmt" became a direct dependency of "stylelint". This would enable fixing and linting using a single tool.

As an example, ESLint program supports [`--fix`](http://eslint.org/docs/user-guide/command-line-interface) option. Using `--fix` option, ESLint fixes and then lints the file.

**Comment by ntwb** [comment]
Paraphrasing:

> _"The stylelint philosophy has been to keep development on stylelint sustainable by putting systems in place that allow the community to extend a robust core, rather than have us bolt more things onto core."_

This still stands true IMHO, _stylelint_ development has been relatively quiet the past couple of weeks as much of the _stylelint_ team have other priorities right now (holidays, new jobs, existing jobs etc). 

Adding another significant facet such as _stylefmt_ to _stylelint_ would add to an already stretched team (in my honest opinion) even more. 

With more people actively contributing to _stylelint_ then for sure _stylelint_ could possibly do more, but taking the recent proposal to merge _CSSLint_ with _stylelint_ as an example, much of that work has been undertaken by the _stylelint_ team and has not bought new _CSSLint_ contributors to contributing to _stylelint_ nor has further work progressed on creating the intermediary _stylelint-csslint_ plugin pack.

_stylelint_ needs to be supportable, maintainable and evolving whilst avoiding team member _burn out_.

**Comment by gajus** [comment]
I agree with everything said by @ntwb. Maintaining a solid core is more important than scaling horizontally.

However, I'd like to just add that the relative size of https://github.com/morishitter/stylefmt is tiny compared to stylelint. Meanwhile, combining the two tools would make this tool vastly more useful and potentially attract more contributors.

**Comment by ntwb** [comment]
Thanks @gajus, for further context see #330 and in particular from this comment https://github.com/stylelint/stylelint/issues/330#issuecomment-189886805

**Comment by davidtheclark** [comment]
> There is no value in asking users to install two separate packages

@gajus It's hardly any trouble to ask users to install two separate packages, though, so that doesn't concern me much. I agree that it would be *nice* if we could support a `--fix` flag like ESLint's, it's not feasible with the amount and style of contribution that we have on this project.

There was some pretty thorough discussion of all this over in https://github.com/stylelint/stylelint/issues/330; and for all the reasons discussed there, I'm not interested in re-opening this possibility unless we have the active contribution to support it.

**Comment by gajus** [comment]
How about at least considering to have a test case that checks compatibility with stylefmt?

**Comment by davidtheclark** [comment]
What are you considering "compatibility with stylefmt"?

**Comment by gajus** [comment]
> What are you considering "compatibility with stylefmt"?

Well, actually these tests would belong in the stylefmt... but basically formatting CSS using a specific rule and then using stylelint to ensure that it is passing the validation.

However, stylelint could do this check too, just to track incompatible rules.

**Comment by davidtheclark** [comment]
@gajus Yeah, it seems like these are just issues for stylefmt. Sounds like stylefmt has a bug about `declaration-block-properties-order`. And stylefmt needs to have tests to ensure that it understands stylelint configuration correctly. I still don't think there's anything to be done in stylelint unless somebody wants to champion (i.e. do a lot of work on) the `--fix` flag cause.
