### ISSUE TITLE
media-feature-no-missing-punctuation broken in SCSS

### ISSUE THREAD

**Issue by tinovyatkin** [stylelint/stylelint#1904]
`media-feature-no-missing-punctuation` seems to not recognize SCSS variables manipulation syntax and erroneously warning on following correct code:
`@media only screen and (max-width: $tablet-width - 1) { .. }`

**Comment by tinovyatkin** [comment]
Sorry, didn't seen it duplicates #1754

**Comment by ntwb** [comment]
Please also remember to use our issue template, issues will be closed if the required information is not included when submitting an issue.
