### ISSUE TITLE
Add curated list of processors to docs

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#1910]
I believe there are 3 processors out there:

- https://github.com/mapbox/stylelint-processor-markdown
- https://github.com/mapbox/stylelint-processor-jekyll
- https://github.com/ccbikai/stylelint-processor-html

Shall we add, like we do for *plugins*, a list of processors within the docs?

**Comment by evilebottnawi** [comment]
@jeddy3 sgtm

**Comment by davidtheclark** [comment]
Yep, sounds good.

The two that I'm working on, though, the mapbox ones, should not be added yet, because they're not quite finished.

**Comment by ntwb** [comment]
sgtm

**Comment by davidtheclark** [comment]
https://github.com/mapbox/stylelint-processor-markdown is ready to be shared, I think.

I depreacted stylelint-processor-jekyll in favor of https://github.com/mapbox/stylelint-processor-arbitrary-tags, which is also ready to be shared now.
