### ISSUE TITLE
table sub-dependency Ajv breaking Stylelint in environments with blocked eval

### ISSUE THREAD

**Issue by Arcanemagus** [stylelint/stylelint#1912]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

It seems that in `table@3.7.10` a dependency on [`ajv`](https://github.com/epoberezkin/ajv) was brought in from https://github.com/gajus/table/pull/16. Unfortunately it seems this library uses `eval` to compile the JSON it is asked to validate. `table@3.7.9` looks like it should still be safe to run in environments where that is blocked like Atom.

There are a few ways to move forward here:

* Have Ajv update to no longer `eval` (unlikely, this looks to be a major part of how it works)
* Have `table` move away from `unsafe-eval` dependencies
* Move away from `table` here in `stylelint`
* Give up on keeping `stylelint` able to run in environments where `eval` is blocked, and have `linter-stylelint` (and any other place that is using `stylelint` in an environment like this) run this package through a wrapper library.

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

`6.0.0` through `7.2.0` (`table` dependency introduced in https://github.com/stylelint/stylelint/commit/06b0fcd8105319870e1e87c990f10c95587bea62)

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

N/A

> What did you expect to happen?

No `unsafe-eval` code being ran.

> What actually happened (e.g. what warnings or errors you are getting)?

The following error is being thrown:

**Stack trace:**
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Ajv.localCompile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:130:26)
    at Ajv.resolve (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/resolve.js:53:19)
    at Object.resolveRef (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:195:21)
    at Object.generate_ref [as code] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/ref.js:22:22)
    at Object.generate_validate [as validate] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/validate.js:157:37)
    at Object.generate_properties [as code] (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/properties.js:198:26)
    at generate_validate (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/dotjs/validate.js:230:37)
    at localCompile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:91:22)
    at Ajv.compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/compile/index.js:59:13)
    at _compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:325:29)
    at getSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:189:51)
    at validate (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:88:11)
    at validateSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:159:19)
    at _addSchema (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:285:7)
    at Ajv.compile (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/ajv.js:110:21)
    at Ajv.addKeyword (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv/lib/keyword.js:46:40)
    at defFunc (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv-keywords/keywords/typeof.js:37:7)
    at defineKeywords (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/ajv-keywords/index.js:20:17)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/validateConfig.js:29:27)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/makeConfig.js:15:23)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/lorisbettazza/.atom/packages/linter-stylelint/node_modules/table/dist/table.js:15:19)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
```

_Note: Originally filed under https://github.com/AtomLinter/linter-stylelint/issues/269._

**Comment by epoberezkin** [comment]
Eval is replaced in Ajv version 4.7.2 (that is within the range) - should be picked up next time you npm install. Please let me know if it's still an issue.

**Comment by Arcanemagus** [comment]
v4.7.2 still has the exact same issue, it looks like you are using `Function()` which still is the same thing as `eval()` on the code, and as such is blocked in environments where that is blocked.

**Comment by epoberezkin** [comment]
How do I reproduce it? npm test seems to run ok.

**Comment by Arcanemagus** [comment]
@epoberezkin You need to be running in an environment where `eval` is prohibited, in this case the way to reproduce that exactly is to install [Atom](https://atom.io/), then install v3.2.1 or below of `linter-stylelint` (`apm install linter-stylelint@3.2.1`, note `apm` not `npm`), and then open any CSS file. Or go into the package directory (`cd ~/.atom/packages/linter-eslint`) and run `apm test`.

**Comment by epoberezkin** [comment]
@Arcanemagus thank you, I understand the issue now.

One of the solutions, in addition to those listed, would be to relax content security policy in Atom to [allow evaluated JavaScript](http://www.html5rocks.com/en/tutorials/security/content-security-policy/#eval-too). Not sure how likely it is to happen, also not sure whether it is intentionally prohibited or it is just so by default. Allowing evaluating JavaScript  from strings may have some benefits, not sure what the risks are. Does Atom allow IO from extensions? I will have a look.

In any case I have a solution - precompile schemas to functions and have them published with table package. I was going to implement it anyway (https://github.com/epoberezkin/ajv/issues/156). So there will be no code evaluation at run time.

**Comment by Arcanemagus** [comment]
`eval` is purposely disabled in Atom by the CSP in place, however if the `stylelint` developers decide it's not worth their development time to keep supporting when dependencies of dependencies run afoul of the policy then there are options such as [atom/loophole](https://github.com/atom/loophole) to work around that. I'd rather not have to use that myself as avoiding `eval` should be done if at all possible in my opinion, but I'm just a consumer of `stylelint` here so it's not up to me 😛.

**Comment by epoberezkin** [comment]
@Arcanemagus thank you, that's one more solution. Works for me ;)

**Comment by Arcanemagus** [comment]
Just to be clear, that's a last resort solution for things that are running in environments where `eval` is blocked, like `linter-stylelint`, and was already mentioned as the 4th option in the issue. It's definitely _not_ something that should be done in Ajv as it will only work in Electron based environments.

**Comment by ntwb** [comment]
Added to 7.3.1 milestone

**Comment by epoberezkin** [comment]
I will resolve the issue in ajv/table, so whether you allow eval is another question...

**Comment by gajus** [comment]
> I'd rather not have to use that myself as avoiding eval should be done if at all possible in my opinion, but I'm just a consumer of stylelint here so it's not up to me 😛.

Does Atom allow to *require* other scripts?

If you look into Node.js source code, you will learn that require is using [vm to run all the code](https://github.com/nodejs/node/blob/e57ff455e25d61555298cacbb0ff964e197ace10/lib/module.js#L532-L536). VM = eval.

I don't see it as an issue to depend on `eval` code.

As a short term solution, just restrict table version to `table@3.7.9` in your package.json.

**Comment by davidtheclark** [comment]
@epoberezkin I'm a little unclear on the direction here: are you going to fix this on the dependency side, or should we still change something about stylelint?

**Comment by epoberezkin** [comment]
I am definitely going to implement pre-compiling schemas into functions - it was an old plan anyway and there are other reasons to do it (browser bundle size, also see epoberezkin/ajv#156). Table package will be able to use precompiled schemas so there will be no dynamic code evaluation there. I will make a PR within 2-4 weeks.

If you want it resolved quicker, using the loophole can be a temporary solution, which later can be reverted, it's up to you. I see no harm in sticking with the previous version of table for this time.

Generally speaking, I think allowing dynamic code evaluation (via Function constructor only) is the right thing - there are quite a few use cases that are difficult/much slower otherwise. That's not my call to estimate which security risks it introduces... Although I think that crippling JavaScript under security pretence is not the right thing. It could have been a bit more granular - for example, they could have crippled generated code instead. Maybe I just like using generated code...

**Comment by Arcanemagus** [comment]
@gajus This isn't really the place to get into the huge philosophical discussion around where and when `eval` might be appropriate. `vm.runInThis Context` isn't exactly the same as `eval` as can be seen in the description of the atom/loophole package [here](https://github.com/atom/loophole#how).

For the moment I've pushed out an update of `linter-stylelint` that lists `table@2.7.9` as a hard dependency, making the resolver use that for the `table` dependency of Stylelint so it's currently not broken (if users are up to date). This isn't a long term solution though. If Ajv is going to be updated to no longer use `eval`, this situation should be fine till then, with the caveat that things will be broken in other environments like that (VSCode? Depending on their CSP).

**Comment by davidtheclark** [comment]
Maybe there is a library simpler than `table` that we can use in stylelint, since we hardly use any of `table`'s real capabilities. I don't think ajv has to be involved to accomplish the simple layout that we need.

**Comment by evilebottnawi** [comment]
@davidtheclark maybe release `7.3.2` with `table@3.7.9` as a hard dependency for avoid this issue (many developers works with `atom`) and before next release explore alternatives and found solution.

**Comment by Arcanemagus** [comment]
@evilebottnawi I've already worked around this in the `linter-stylelint` Atom package, so updates and new installs won't be broken. You might think about that for _other_ environments though, as I don't know all the places Stylelint is integrated and what their CSP policies are.

**Comment by evilebottnawi** [comment]
@Arcanemagus :+1:

**Comment by jeddy3** [comment]
> Maybe there is a library simpler than table that we can use in stylelint, since we hardly use any of table's real capabilities

Sgtm. 

eslint appears to use [text-table](https://github.com/eslint/eslint/blob/master/lib/formatters/stylish.js#L8), which has no dependencies.

Shall we focus (rename and label) this issue to seeing if adopting a similar library for our string reporter is viable?

**Comment by gajus** [comment]
> eslint appears to use text-table, which has no dependencies.

https://github.com/eslint/eslint/blob/0a361387ee180713c6f69adeb86a2a80400de3b5/package.json#L67

**Comment by jeddy3** [comment]
Oh, thanks for the heads up @gajus. 

It looks like they use `table` for the ["table"](http://eslint.org/docs/user-guide/formatters/#table) formatter and `text-table` for the ["stylish"](http://eslint.org/docs/user-guide/formatters/#stylish) formatter.

The stylish formatter output looks most like our "string"  one.

**Comment by jeddy3** [comment]
Lets wait on the outcome of https://github.com/gajus/table/pull/19 before considering an alternative to `table`, as it'll save us having to revisit the `string` formatter.

**Comment by jeddy3** [comment]
Thanks to @epoberezkin and @gajus [recent work on `table`](https://github.com/gajus/table/commit/76290f642c6e7db26eb86a22d0ec7cfc590c15830), I think this can be closed.

Thanks guys for making this change!

**Comment by epoberezkin** [comment]
@jeddy3 just to confirm, it all works now, correct?

**Comment by evilebottnawi** [comment]
@Arcanemagus ping

**Comment by Arcanemagus** [comment]
I'm still seeing this problem with `table@3.8.2`, double checking that it's in `table`.

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/19487451/b7da1e06-9517-11e6-8a22-9b1a0d287b59.png)

It's blowing up on that now, checking out the `table` source to see where that is coming from.

**Comment by epoberezkin** [comment]
Well, the good news is it's not ajv any more :) @gajus is it something babel is doing? I don't see it in the source

**Comment by epoberezkin** [comment]
omg, I think we somehow managed to publish instrumented version of table package... That is good that it was broken at least, or we could have missed it.

**Comment by Arcanemagus** [comment]
Heh, came back here to report that it's the Istanbul Babel plugin, but it looks like you already caught that 😛.

**Comment by Arcanemagus** [comment]
Looks like if `BABEL_ENV` isn't set then it defaults to `development`, which uses the `istanbul` plugin.

**Comment by gajus** [comment]
My mistake, sorry – forgot that `NODE_ENV` defaults to `development`. I have added a [prepublish step](https://github.com/gajus/table/blob/2d1c0d9ebad31f9c76e784e6a88f701de8705005/package.json#L65) that rebuilds the package using `NODE_ENV=production`. [v3.8.3](https://github.com/gajus/table/tree/v3.8.3) has been published.

**Comment by Arcanemagus** [comment]
table v3.8.3 works, thanks! 🎉
