### ISSUE TITLE
Add Webstorm to complementary tools doc

### ISSUE THREAD

**Issue by Nirazul** [stylelint/stylelint#1924]
Just wanted to spread the good news 👍 
Seems that the countless +1 in the jetbrains forum were successful :)

https://blog.jetbrains.com/webstorm/2016/09/webstorm-2016-3-eap-163-4830-stylelint-usages-for-default-exports-and-more/

**Comment by davidtheclark** [comment]
Thanks @Nirazul! I'll transform this issue so it's about adding a note to the documentation at http://stylelint.io/user-guide/complementary-tools/

**Comment by evilebottnawi** [comment]
Wow Finally, I waited for this

**Comment by evilebottnawi** [comment]
Related: https://github.com/stylelint/stylelint/issues/346 (we can close)
I do not know what happens when a problem is closed, which transferred money? :smile:
