### ISSUE TITLE
Rewrite non-rule tests with another test runner

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1947]
While working on #1930 I've become convinced that this project is large enough that we would really benefit from some of the niceties of a more full featured test runner, and that the non-rule tests would be pretty easy to rewrite for another runner. The rule tests are another story.

I'm thinking Mocha or AVA. If somebody really wants to try Jest, I'd be open to that experiment, too. 

@evilebottnawi: I know you've expressed interest in AVA — want to give this a shot? But please wait for me to finish #1930 since I'm making significant changes to those tests in that PR.

**Comment by evilebottnawi** [comment]
@davidtheclark yep. you are good developer, i love you not platonic :smile:

**Comment by jeddy3** [comment]
SGTM. I'll label it up as infrastructure.

**Comment by evilebottnawi** [comment]
@davidtheclark ok, let's wait

**Comment by davidtheclark** [comment]
@evilebottnawi Just merged #1930 so if you'd like to try AVA, the time is ripe.

**Comment by evilebottnawi** [comment]
@davidtheclark let's go, in the near future :smile:

**Comment by davidtheclark** [comment]
@evilebottnawi: Are you going to tackle this? If not, I'm going to look into it soon.

**Comment by evilebottnawi** [comment]
@davidtheclark I have time at the end this week. I you want start now, let's go, sorry

**Comment by davidtheclark** [comment]
I rewrote tests in `src/__tests__/` with AVA and was discouraged by the results. What took 5.5 seconds with `babel-tape-runner` took *37 seconds* with AVA. 

I really like the AVA API, but that huge lag rules it out for me.

Will try again with Jest.

**Comment by evilebottnawi** [comment]
@davidtheclark very strange I used to get different results in other projects, ava worked faster then tap

**Comment by evilebottnawi** [comment]
@davidtheclark let's try jest

**Comment by davidtheclark** [comment]
This is complete.
