### ISSUE TITLE
table update breaks Node 0.12 compatibility

### ISSUE THREAD

**Issue by dryoma** [stylelint/stylelint#1961]
Hey guys!

Starting with 3.8.0 `Table` (a dependency for stylelint) [uses `es2015-node4`](https://github.com/gajus/table/issues/18) preset for building, thus breaking compatibility with 0.12:

I know that you have dropped 0.12 compatibility, yet maybe you would like to consider preserving it for the sake of `stylelint-test-rule-tape`? We use it for running tests in stylelint-scss, and several days ago this thing started to appear on TravisC Node.js 0.12 setup:
```
/home/travis/build/kristerkari/stylelint-scss/node_modules/stylelint-test-rule-tape/node_modules/stylelint/node_modules/table/dist/table.js:112
  let userConfig = arguments.length <= 1 || arguments[1] === undefined ? {} : 
  ^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by evilebottnawi** [comment]
@dryoma format you issue please

**Comment by jeddy3** [comment]
Hi @dryoma 

As stylelint supports Node.js 4 and up, you might want to remove `0.12` from your travis config.

We [decided that](https://github.com/stylelint/stylelint/issues/1580) moving onto Node.js 4 was the best use of our limited time. For example, some of our devDependencies rely on Node.js 4 (e.g. eslint@3), as such testing (and supporting) `0.12` would stop us using features introduced in `eslint@3`. So, we decided to move forward with other tools (and libraries like `table`).

**Comment by dryoma** [comment]
@jeddy3 thanks for clarifying this. Yep, without you supporting 0.12 doing so in a plugin set doesn't do any good anyway :)
