### ISSUE TITLE
Separate core and postcss-api

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1971]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This discussion and proposal. We have a good core with configurations, plugins, processors, support
gitignore and etc. I am sure that in the future we will achieve even greater improvements in it. I recently ran into a problem writing our linters, was not associated with `CSS`, `Less`, `Scss` and etc. His task was to lint our internal configuration files (for build systems). I've been thinking how best to solve this problem, in the end came to the fact that most of the code copied our core (remove postcss-api layout) and finished writing their own rules. It decided our problems. But there are new problems, now we need to keep track of core code and have to spend a lot of time. And in the future expected even writing several linters for such tasks. And the idea came to me that it would be a surprise if there was a package that provides a standard environment for writing linters, which would need to write api and rules, and not to think about the implementation of the standard things (plugins, configurations, cli and etc). By the way, we can draw an analogy with eslint, realized many things from them, as we have implemented. By separating the core from api we can help a lot of people to start a new generation linters. More would not have the same core programming for the implementation of the basic features of modern linters. Perhaps we would support even other projects such as eslint and other linters.
Three things
- `standard-lint` (maybe best name for package), contain all core feature - cli, glob, ignoring, api for configurations, plugins, processors, and agnostic-tester api, and reporting utils and formatters. Maybe I missed something.
- `some-api` - return nodes (ast) based on glob. Each linters can use own parser for this.
- `rules` - Accept nodes and use `report`

I'd add that I want to write for a long time `fslinter` for check on no BOM, filenames and directory patterns and other awesome stuff (Such as https://github.com/schorfES/node-lintspaces now it see as dead repo :sob: ). And I would be glad if you support this idea. We can start a new era of static analyzers :smile: .

> Which rule, if any, is this issue related to?

no matter

> What CSS is needed to reproduce this issue?

no matter

> What stylelint configuration is needed to reproduce this issue?

no matter

> Which version of stylelint are you using?

no matter

> How are you running stylelint: CLI, PostCSS plugin, Node API?

no matter

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no matter

> What did you expect to happen?

no matter

> What actually happened (e.g. what warnings or errors you are getting)?

no matter

**Comment by davidtheclark** [comment]
I think this is a good idea ... but also a huge amount of work. Unfortunately, if it goes well and we convince any other linters to using this core linter API — that would mean even *more* work.

If somebody is interested in creating and maintaining a core linter API like you suggest, they are welcome to use the open-source code here; and if they pull it off we could consider using it. But I don't plan to work on that module myself, at least not in the foreseeable future.

**Comment by evilebottnawi** [comment]
@davidtheclark I think I will have time at the end of this month, I could do this job, to make an experimental branch and see how it will look

**Comment by evilebottnawi** [comment]
@stylelint/core how would you rate the idea?

**Comment by evilebottnawi** [comment]
@eslint/core I would like to hear your opinion on this issue

**Comment by ntwb** [comment]
It sounds like a great idea in theory, but as @davidtheclark noted, a huge amount of work

**Comment by evilebottnawi** [comment]
Just puts '+1' if you think it is a good idea :+1:

**Comment by ntwb** [comment]
> "I'd add that I want to write for a long time fslinter for check on no BOM, filenames and directory patterns and other awesome stuff"

@evilebottnawi I just saw this for the first time :) https://github.com/sahib/rmlint

**Comment by jeddy3** [comment]
> If somebody is interested in creating and maintaining a core linter API like you suggest, they are welcome to use the open-source code here; and if they pull it off we could consider using it. 

Agreed. I think we'd need to assess the level of support the initiative has before adopting it i.e. if there is a dedicated team of contributors then it might alleviate some of our workload. However, if there isn't then it could increase our workload.

> But I don't plan to work on that module myself, at least not in the foreseeable future.

Same here. As such, I'm going to close this issue within the stylelint org. 

@evilebottnawi Feel free to try this initiative outside of the stylelint org. Best of luck :)
