### ISSUE TITLE
Increase Flow coverage

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#1974]
We recently introduced [Flow](http://flowtype.org/) types to some of the files in `src/`. We should try to gradually extend that coverage to more of the app, focusing first on the non-rules code and then seeing how we can start type-checking all the rules, as well.

Anybody who is interested in learning how to use Flow is welcome to submit PR's of any size adding annotations anywhere you feel like poking around :)

**Comment by m-allanson** [comment]
Consider me interested :) Although realistically it'll be about a week until I have a chance to dig in. I'd also be interested to see PRs from anyone else that wants to work on this.

**Comment by ntwb** [comment]
Likewise, very interested, but alas I've not much available time at the moment.

Will look forward to checking out any PRs submitted 😄

**Comment by m-allanson** [comment]
PR #2007 is a useful reference for anyone looking at this issue.
