### ISSUE TITLE
Add testUtil for testing some common patterns found in rule tests.

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#198]
To cover off some `ok()` rules that appear in the majority of rules e.g. empty string, empty rule and blockless statement.

Ref: #196

**Comment by davidtheclark** [comment]
Can I ask why you were thinking we should have regular tests for both `a {}` and `a { }`?

**Comment by jeddy3** [comment]
It wasn't well thought through I'm afraid. I think I based the regular tests on `block-no-empty`, which had `a {}` and `a { }` to be extra sure. Not including `a { }` in the regular tests in super groovy with me.

Thanks again for closing this issue! :)
