### ISSUE TITLE
Stylelint doesn't work on my Sublime Text 3

### ISSUE THREAD

**Issue by wellyshen** [stylelint/stylelint#1980]
Hi I use the "stylelint 7.4.2" with  "Sublinter-contribute-stylelint" but it doesn't work and I receive the following error on the console log of Sublime Text 3 debug mode (here's my [Repo](https://github.com/wellyshen/react-cool-starter)):

> SublimeLinter: stylelint: Home.scss ['/Users/Welly/.nvm/versions/node/v6.7.0/bin/node', '/Users/Welly/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@', '--config', '/Users/Welly/Desktop/react-cool-starter/.stylelintrc'] 
SublimeLinter: stylelint output:
Error: No configuration provided for /var/folders/31/6tnw20657rb5znbqj567_9xm0000gn/T/SublimeLinter3-Welly/Home.scss
    at exports.default (/Users/Welly/Desktop/react-cool-starter/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /Users/Welly/Desktop/react-cool-starter/node_modules/stylelint/dist/getConfigForFile.js:28:43 

Here's my .stylelintrc:
```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "string-quotes": "single",
    "selector-pseudo-class-no-unknown": [
      true,
      {
        "ignorePseudoClasses": [
          "global",
          "local"
        ]
      }
    ]
  }
}
```

**Comment by evilebottnawi** [comment]
@wellyshen first you should format you issue as template

**Comment by jeddy3** [comment]
Closing as this is a sublime plugin issue. Please post in [their issue tracker](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint).

@wellyshen As an aside, I believe they are looking for contributors to help maintain the plugin. As such, please consider helping out them out with a fix and support going forward.
