### ISSUE TITLE
Add option to length-zero-no-unit README

### ISSUE THREAD

**Issue by in-in** [stylelint/stylelint#1982]
http://stylelint.io/user-guide/rules/length-zero-no-unit/

![90cd6](https://cloud.githubusercontent.com/assets/8797432/19329891/c6e8f094-90e3-11e6-9f7c-71fe2934e34a.png)

For example another rule with that option:
http://stylelint.io/user-guide/rules/string-no-newline/

![53a62](https://cloud.githubusercontent.com/assets/8797432/19329935/fe44987c-90e3-11e6-89b9-c164e9470d55.png)

**Comment by jeddy3** [comment]
@in-in Thanks for reporting. Please considering sending a pull request with a fix.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/1983
