### ISSUE TITLE
Path resolution issue with .stylelintrc and Gulp

### ISSUE THREAD

**Issue by ryanheathers** [stylelint/stylelint#1985]
I'm running into an issue where Stylelint is unable to locate the `.stylelintrc` file. I'm running Stylelint as a PostCSS plugin through Gulp.

To repro, I'm using the following folder tree:
```
- utilities
  - .stylelintrc
  - gulpfile.js
  - node_modules
  - package.json
- test
  - test.scss
```

I want to run my `/utilities` gulpfile while I am within my `/test` directory. To do that, I use gulp's `--gulpfile` config option. So for example, my CLI command looks like `gulp util:style:lint --gulpfile ../utilities/gulpfile.js`

Using the `--gulpfile` option in this way changes Node's current working directory to the gulpfile's location while the gulpfile is running i.e. using `process.cwd()` will return the `/utilities` folder. 

This setup works great for all the rest of my gulp tasks. However, stylelint reports `Error: No configuration provided for /test/test.scss`. As a sanity check, I tried moving `.stylelintrc` into the `/test` folder and that change allows the task to complete without error. It only complains when the `.stylelintrc` is in a different directory.

Stylelint's docs mention that it [resolves the location of .stylelintrc](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md) from the **current working directory**. As I mentioned, during the gulp process the Node current working directory **is** the same directory that the `.stylelintrc` is located in. However this doesn't appear to be providing what Stylelint needs.

Can someone shed light on how Stylelint resolves the location of its config file? Or put another way, is there a way to tell Stylelint where to find the config file specifically? Thanks for any insights!

I'm using version `7.4.2` of Stylelint.

**Comment by davidtheclark** [comment]
This may have been introduced with the recent change allowing for a different confit for each file. Probably we need to add another line to lookup config from cwd if none is found relative to the file.

**Comment by ryanheathers** [comment]
👍  Thanks for the fast resolution on this!!
