### ISSUE TITLE
Is this the correct form for the subtitle?

### ISSUE THREAD

**Issue by in-in** [stylelint/stylelint#1986]
http://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties/

![4fb52](https://cloud.githubusercontent.com/assets/8797432/19404349/03201d6a-9276-11e6-8a2f-00af69c60451.png)

According to other rules, the subtitle looks like "_Optional secondary options_".

**Comment by ntwb** [comment]
Right you are @in-in, thanks for creating the issue 👍 

Did you want to submit a pull request to fix this?

Changing `## Options` to `## Optional secondary options` in the rules README [here](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-duplicate-properties/README.md#options-1) is what is needed.

**Comment by davidtheclark** [comment]
Closed by #1988.

**Comment by ntwb** [comment]
Thanks @in-in 👍
