### ISSUE TITLE
stylelint wish list

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#1987]
Over on stylelint-config-wikimedia I [wrote](https://github.com/wikimedia/stylelint-config-wikimedia/issues/3#issuecomment-252401803): 
> There's a neat ESLint plugin, [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules), I'd be cool see a stylelint version of this 😏 

Previously we've removed rules from stylelint and asked the styelint community to help out by creating plugins such as [stylelint-declaration-block-order](https://github.com/hudochenkov/stylelint-declaration-block-order)

So with the above 2 cases it would be nice if we had a little section somewhere in the stylelint docs for a _stylelint wish list_ for plugins, configs, or tools we'd like see or create ourselves if time was not finite, what do you think @stylelint/core ?

**Comment by davidtheclark** [comment]
Sure! It could be a Wiki page on the repo, that way anybody who wanted to could easily add a line.

**Comment by ntwb** [comment]
> Sure! It could be a Wiki page on the repo, that way anybody who wanted to could easily add a line.

Ha... Sometimes the obvious solution is right in front of you 😏 

Oh, looks like the wiki has been turned off again, @jeddy3 what do you think?

**Comment by jeddy3** [comment]
> stylelint wish list for plugins, configs, or tools ... @jeddy3 what do you think?

A wishlist for those things sounds like a great idea to me. I've turned the wiki back on.

**Comment by ntwb** [comment]
Thanks, nothing fancy, but added a section on the wiki home page 👍 

https://github.com/stylelint/stylelint/wiki
