### ISSUE TITLE
New rules: selector-combinator-before and -after

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#20]
I will work on these very soon.

**Comment by jeddy3** [comment]
I'm excited to see this one! Will you build it on top of your [list-selectors](https://github.com/davidtheclark/list-selectors) work?

**Comment by davidtheclark** [comment]
Does anybody anticipate a need to allow for anything other than a single space before or after?

If not, should we change this rule to `selector-combinator-space-before` and `-after` and make it a simple true/false?

I have the same thought about a bunch of other whitespace-related rules, where the suggestion in #1 is that they would be open-ended and users would enter arbitrary characters but the tool and code would be significantly simpler if we just accommodated what *might* be the only actual use-case, which is requiring or rejecting single spaces in those places.

**Comment by davidtheclark** [comment]
Bypass this comment and please read #40 and share you thoughts there.

**Comment by davidtheclark** [comment]
Done in 64f72fe1b73a2a645f6f2e75e9ede4dd90c2bccf as selector-combinator-space
