### ISSUE TITLE
Not supported older Node.js versions

### ISSUE THREAD

**Issue by tgfjt** [stylelint/stylelint#201]
Hi:smile: 
I'm trying out #15  with node@0.10.36.

I got `ReferenceError: Set is not defined`.
https://github.com/stylelint/stylelint/blob/e5abe64667430ec07aece516a0fe6317ad9fcc7c/src/rules/number-zero-length-no-unit/index.js#L20

We need ^0.12?

**Comment by MoOx** [comment]
Supporting 0.10 can be a pain now that more & more people are already using iojs...
0.12 should mandatory imo.

**Comment by MoOx** [comment]
Currently it's tested on 0.12 & iojs 2.x https://github.com/stylelint/stylelint/blob/master/.travis.yml#L4-L6

**Comment by jeddy3** [comment]
Hi @tgfjt 

Thanks for giving us a hand and trying out the linter! :)

Is some external factor involved in you using node@0.10? It would be interesting to know why you're using that version. This might be somewhere where we need to weigh-up the pain of supporting an order version of node vs. reach/compabiltiy of the linter.

It looks like `Set()` [needs](https://babeljs.io/docs/learn-es2015/#map-set-weak-map-weak-set) the [babel polyfil](http://babeljs.io/docs/usage/polyfill/) to work in all environments. Are you able to try running your script using [`babel-node`](https://babeljs.io/docs/usage/cli/#babel-node) to see if that helps?

If that doesn't work, do you have access to node@0.12 or is this issue blocking you getting the linter running?

**Comment by tgfjt** [comment]
It works fine on node@0.12.:smile: 

The reason why I(We) use node@0.10 is just conservative.
It is not easy to upgrade Environment so.

I could understand your pain, and I'd like to use 0.12 or io.js...:trollface: 
You don't need to support 0.10 imo. (Feel free to close this issue:+1: ) 
but would you write about Requirements on README or something doc?

Tomorrow, I'll try more things on io.js.

Thanks!

**Comment by jeddy3** [comment]
> It is not easy to upgrade Environment so.

Yeap, understood.

> but would you write about Requirements on README or something doc?

Good idea.

> Tomorrow, I'll try more things on io.js.

Good stuff. The linter does currently work with `babel-node` on node@0.10.36, so you could use that if pushed. Please don't hesitate to write again if you uncover any more issues :)

**Comment by MoOx** [comment]
:+1:

**Comment by tgfjt** [comment]
node@0.10 with gulp:

```js
gulp.task("css", function () {
  require("babel/register")
  var postcss = require("gulp-postcss")
  var stylelint = require("stylelint")
  var logWarnings = require("postcss-log-warnings")
  return gulp.src("src/**/*.css")
    .pipe(postcss([
      stylelint({
        // config
      }),
      logWarnings()
    ]))
})
```
