### ISSUE TITLE
Deprecate declaration-block-properties-order in favour of more specific community plugins

### ISSUE THREAD

**Issue by Ne-Ne** [stylelint/stylelint#2010]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I want to test my Sass (scss) without having the properties being in a set order.

> Which rule, if any, is this issue related to?

declaration-block-properties-order

> What stylelint configuration is needed to reproduce this issue?

``` json
{
  "rules": {
    "declaration-block-properties-order": [
      {
        order: "flexible",
        properties: [
          "position",
          "top",
          "right",
          "bottom",
          "left"
        ]
      },
      {
        order: "flexible",
        properties: [
          "flex",
          "flex-direction",
          "flex-order",
          "flex-pack",
          "flex-align"
        ]
      },
      {
        order: "flexible",
        properties: [
          "margin",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left"
        ]
      },
      {
        order: "flexible",
        properties: [
          "font",
          "font-family",
          "font-size",
          "font-style",
          "font-weight"
        ]
      },
      {
        order: "flexible",
        properties: [
          "background",
          "background-color",
          "background-image",
          "background-repeat",
          "background-attachment",
          "background-position",
          "background-position-x",
          "background-position-y",
          "background-clip",
          "background-origin",
          "background-size",
        ]
      },
      {
        order: "flexible",
        properties: [
          "transition",
          "transition-delay",
          "transition-timing-function",
          "transition-duration",
          "transition-property",
        ]
      },
      {
        order: "flexible",
        properties: [
          "animation",
          "animation-name",
          "animation-duration",
          "animation-fill-mode",
          "animation-play-state",
          "animation-timing-function",
          "animation-delay",
          "animation-iteration-count",
          "animation-direction"
        ]
      }
    ]
  }
}
```

> Which version of stylelint are you using?

"gulp-stylelint": "3.4.0",

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Nope

> What did you expect to happen?

Code to flag, but with the order in each properties: [...] above (not in the listed order).

> What actually happened (e.g. what warnings or errors you are getting)?

Flags loads of errors, because the code is not written in the order of each block above.
## 

In an ideal world, I want the code to check through and validate the code. However I can't expect all my development team to remember the order.

E.G. must use background before transition but only after the flex code. As an example I don't mind where the flex and positioning are placed however when someone codes positioning. I want it to go:

Pass linting:

``` sass
position: absolute;
top: 0;
right: 0;
bottom:
left: 0;
```

Flag in NPM:

``` sass
right: 0;
top: 0;
bottom:
position: absolute;
left: 0;
```

Many thanks.

**Comment by jeddy3** [comment]
@Ne-Ne Thanks for using the template.

@davidtheclark I think you called it a while back when you said we'd struggle to clearly define this rule's "finished" state. I'm not keen on building this flexibility into this already-complex rule, especially when the majority of the value of this rule is having all your properties in a predictable position. 

I'm wondering whether we use this issue as the catalyst for stripping this rule back even more, to a point where we can clearly draw a line in the sand. Plugins can always be written by the community for specific use-cases e.g. [`stylelint-property-groups-structure`](https://github.com/hudochenkov/stylelint-property-groups-structure). Doing so would allow us and `postcss-sorting`/`stylefmt` teams to standardise on a simpler rule configuration structure (that would work for the majority of users) i.e. a flat array or the "alphabetical" keyword. At the moment there's (flexible) group objects, the expansion of hyphenated properties and de-prefixing of properties, which complicate sharing the stylelint configuration between these tools.

What are your thoughts on stripping back `declaration-block-properties-order` to:

```js
[
  "alphabetical"|["array", "of", "properties"], {
    "unspecified": "top"|"bottom"|"bottomAlphabetical"|"ignore"
  }
]
```

> However I can't expect all my development team to remember the order.

As an aside, I don't think they need to as the linter will inform them of any mistakes. Having said that, I think `alphabetical` ordering works well with big teams... there's nothing for the team to learn as everyone knows the alphabet right? :)

**Comment by Ne-Ne** [comment]
@jeddy3 Thanks for taking the time to reply.

> There's nothing for the team to learn as everyone knows the alphabet right? :)

I feel that if the properties grouped together are far more legible. An example being positioning, the values that affect positioning such as top, left, right and bottom. Should be close proximity, as they can be edited / read both in dev tools and in for production (Some QA and common UI components) much quicker than scrolling or re-checking a class.

While I agree you do have a point :) Quite simply some of the dev's do not know CSS well. Some know more than others. So just try and do a bodge.. Lucky me :) Which is where this possible option comes in.

--

I think it would be cool if the end result was a setup was warnings for a custom order. But failures if properties are not written in a set order. Such as:

```css
position: absolute;
top: 0;
right: 0;
bottom:
left: 0;
```

What do you think @jeddy3 / @davidtheclark ?

**Comment by jeddy3** [comment]
> I think it would be cool if the end result was a setup was warnings for a custom order. But failures if properties are not written in a set order. 

Can you please provide some more (minimal) examples of what you want to happen? e.g. "with the _following config_ `...`, the following CSS `...` would produce the following `...` warnings".

Originally, I thought you were asking for an option that would allow for the _flexible_ ordering of _groups_, but with a _strict_ ordering _within each group_ e.g.

```js
{
  "rules": {
    "declaration-block-properties-order": [[
      {
        order: "strict",
        properties: [
          "position",
          "top",
          "right",
          "bottom",
          "left"
        ]
      },
      {
        order: "strict",
        properties: [
          "flex",
          "flex-direction",
          "flex-order",
          "flex-pack",
          "flex-align"
        ]
      }],
    { group: "flexible" }
  ]}
}
```

With such a config, both the following are valid:

```css
a {
  position: absolute;
  top: 10px;
  flex: 1;
  flex-direction: row;
}
```

```css
a {
  flex: 1;
  flex-direction: row;
  position: absolute;
  top: 10px;
}
```

As the order _of each group_ is flexible, whereas the properties _within each group_ aren't. 

Whereas, the following two examples would return _one_ warning each, but on different lines:

```css
a {
  position: absolute;
  top: 10px;
  flex-direction: row;
  flex: 1;
}
```

```console
5:2 Expected "flex" to come before "flex-direction"
```

And:

```css
a {
  flex-direction: row;
  flex: 1;
  position: absolute;
  top: 10px;
}
```

```console
2:2 Expected "flex" to come before "flex-direction"
```

As the strict order within the "flex group" is being violated.

Is this what you're asking for?. If not, I think some examples would help us better understand what you're requesting.

Once we understand the request we can better judge whether it is inside or outside the scope of this rule.

**Comment by Ne-Ne** [comment]
> Is this what you're asking for?

Sorry was a long day yesterday. That is exactly what I am looking for. You already have support for custom messages.

**Comment by jeddy3** [comment]
> That is exactly what I am looking for.

Ok, thanks for clarifying.

@davidtheclark I think this is plugin territory. What do you think? Also, what do you think about my original proposal to strip this rule back?

**Comment by hudochenkov** [comment]
> However I can't expect all my development team to remember the order.

@Ne-Ne try [postcss-sorting](https://github.com/hudochenkov/postcss-sorting). It sorts rules.

**Comment by davidtheclark** [comment]
I think this illustrates how the rule is trying to do too much.

I agree with @jeddy3's suggestion that we need to get serious about drawing some boundaries. I think the current should be altogether cut, and replaced with specific rules with clear boundaries. @jeddy3's example could be broken down further into two distinct rules:

- `declaration-block-properties-alphabetical-order`
- `declaration-block-properties-specified-order`

I was thinking these rules could live within stylelint core — but then we run into compatibility problems. *I do think this makes the most sense delegated to external plugins*. People should simply pick the plugin that fits their idiosyncratic desire.

This leads me to think we should just *cut the rule from stylelint altogether*.

**Comment by Ne-Ne** [comment]
> @Ne-Ne try postcss-sorting. It sorts rules.

While I could add this plugin, it does not make sense for the extra overhead.. Especially since stylelint team seem to be going in the right direction I want to use the lint tool in.

> People should simply pick the plugin that fits their idiosyncratic desire.

@davidtheclark That makes sense to me!

I think enforcing `declaration-block-properties-order` is overkill. But maintaining properties (margin, padding, border etc..) could keep better housekeeping for other devs.

I like your idea above `declaration-block-properties-specified-order` seems like a direction I would want support you in.

**Comment by jeddy3** [comment]
> This leads me to think we should just _cut the rule from stylelint altogether._

I agree. The upcoming `8.0.0` release seems like the most logical time to do this. As we did with the `7.0.0` release, I suggest we update the ["Release planning"](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md) document to reflect this decision. This will give the community time to help in the transition. 

I'll update the labelling on this issue accordingly.

**Comment by hudochenkov** [comment]
I would like to make these plugins, since it's kinda my thing to make order plugins for stylelint and PostCSS :)

**Comment by davidtheclark** [comment]
Fantastic @hudochenkov!

As mentioned above, I think the way to keep yourself most sane in maintaining them is to limit each plugin's scope to a specific kind of ordering without extra flexibility. If users want another kind of ordering, it could open space for a new plugin.

The sooner we can deprecate that rule and suggest your plugins, instead, the better!

**Comment by hudochenkov** [comment]
To be sure, what I undertand about extracting this rule into plugins:

`stylelint-declaration-block-properties-alphabetical-order`:

Options: `true`.

Specify alphabetical order for properties. Prefixed properties must be placed before unprefixed properties. I want to remove requirement to have prefixed properties in alphabetical order. This is not considered warnings:

```css
a {
	all: initial;
	-webkit-box-shadow: none;
	-moz-box-shadow: none;
	box-shadow: none;
}
```

---

`stylelint-declaration-block-properties-specified-order`:

Options:

```json
[
  ["array", "of", "properties"],
  {
    "unspecified": "top"|"bottom"|"bottomAlphabetical"|"ignore"
  }
]
```

Specify strict order for properties. Prefixed properties treated the same way as in plugin above. This plugin will not support options like this:

```json
[[
	"text-align",
	{
		"properties": [
			"display",
			"position"
		]
	}
]]
```

---

I have doubts what to do with [`stylelint-property-groups-structure`](https://github.com/hudochenkov/stylelint-property-groups-structure), because it's built on top of `declaration-block-properties-order` and its support of objects with group of properties. Now I need to connect two plugins rather core rule and plugin. There are some ideas how to handle deprecation of `declaration-block-properties-order` in this plugin:

1. `property-groups-structure` won't run any rule after it completion. It means that users should have two big lists of properties in their config: one for `property-groups-structure` and another for `declaration-block-properties-specified-order`. This ways config is going to be huge and worse to maintain.
2. In `property-groups-structure` detect if `declaration-block-properties-specified-order` installed and pass option to later plugin if it's true. This way isn't flexible because there are can be other plugins for order.
3. Add an option to `declaration-block-properties-specified-order` like `"from-stylelint-property-groups-structure"`. Properties order plugin will take options from structure plugin and convert to its own config. Also not a good way to have a config converter from property-groups-structure to properties-order in later plugin.

I really confused how to handle deprecation of `declaration-block-properties-order` in `stylelint-property-groups-structure` :(

**Comment by davidtheclark** [comment]
@hudochenkov Your plans for `stylelint-declaration-block-properties-alphabetical-order` and `stylelint-declaration-block-properties-specified-order` look good to me.

I'd recommend against tying `property-groups-structure` to any other plugins or rules. Could `property-groups-structure` implement the same API it currently supports? The other two plugins would support a flat array of property names, but this one would support objects (and only objects) for groups. Each item in the array could be an object with the following properties: 

- emptyLineBefore
- order
- properties

And a secondary option could be `groupOrder` (strict or flexible).

Another idea: You might consider putting these plugins into a single plugin package or using the monorepo approach. I'd guess there's a possibility of having to duplicate code across repos otherwise.

**Comment by hudochenkov** [comment]
> Could property-groups-structure implement the same API it currently supports?

You suggest also to check order in property-groups-structure? Which means code for `declaration-block-properties-specified-order` also will be in `property-groups-structure`?

> You might consider putting these plugins into a single plugin package or using the monorepo approach.

It's an interesting idea. I can create `stylelint-order` plugin pack with these rules:

* [`declaration-block-order`](https://github.com/hudochenkov/stylelint-declaration-block-order)
* [`property-groups-structure`](https://github.com/hudochenkov/stylelint-property-groups-structure)
* `declaration-block-properties-specified-order`
* `declaration-block-properties-alphabetical-order`

**Comment by davidtheclark** [comment]
Yeah, what I'm suggesting is that property-groups-structure checks the order of properties, according to flexible or inflexible groupings, with or without empty lines before. It's true that this means some implementation could might be shared between plugins ... that's what I thought it might be a good idea to maintain them in the same repo.

**Comment by hudochenkov** [comment]
I've combined [`stylelint-declaration-block-order`](https://github.com/hudochenkov/stylelint-declaration-block-order) and [`stylelint-property-groups-structure`](https://github.com/hudochenkov/stylelint-property-groups-structure) into new plugin [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) (published on npm). Also I've added new rule `declaration-block-properties-alphabetical-order` into it.

Going to add `declaration-block-properties-specified-order` rule tomorrow.

Please don't promote this plugin yet (if you wanted to do this :)). I want to add `declaration-block-properties-specified-order` before the public announcement.

---

I need to deprecate my plugins listed above. I've never done this before. What is the best way to do this? Is [`npm deprecate`](https://docs.npmjs.com/cli/deprecate) enough?

**Comment by davidtheclark** [comment]
@hudochenkov What I've seen done that made sense to me, and what I've done myself, is to
- Add a deprecation notice to the README with a link to a good replacement, if there is one.
- `npm deprecate` and include in the deprecation message the name of a good replacement.

**Comment by hudochenkov** [comment]
@davidtheclark thank you! There is a good replacement — stylelint-order, because I've merged code from plugins above into new plugin :)

**Comment by jeddy3** [comment]
@hudochenkov Just a quick message to say `stylelint-order` is looking great!

One thing while it's on my mind, you'll probably want to rename `property-groups-structure` to `declaration-block-property-groups-structure` as, like the `declaration-block-order ` and `declaration-block-properties-alphabetical-order`, it _scoped_ to the declaration block. I'll have a proper poke around the repo soon and add further issues to its issue tracker.

**Comment by hudochenkov** [comment]
@jeddy3 thank you! :)

Good point!

**Comment by hudochenkov** [comment]
I've released [stylelint-order `0.2.0`](https://github.com/hudochenkov/stylelint-order/releases/tag/0.2.0).

* Renamed `property-groups-structure` to `declaration-block-property-groups-structure`
* Added `declaration-block-properties-specified-order` rule

Do you thinks it's ready for a public announcement?

**Comment by jeddy3** [comment]
> Do you thinks it's ready for a public announcement?

Lets:

- [ ] Update the release planning doc.
- [ ] Deprecate `declaration-block-properties-order` with either a simple message within the changelog or by adding a warning to the code (which will be included in the next release). @davidtheclark Which would you prefer?
- [ ] Update the plugins list.

This will give people plenty of time to migrate to `stylelint-order` (and hopefully contribute any additional functionality they want to see) before we remove `declaration-block-properties-order` in `stylelint@8.0.0`

Once these three things are done, I think an announcement via a tweet would be nice :)

**Comment by davidtheclark** [comment]
@jeddy3 I think we should add a warning in the code for the deprecation. Seems like a significant group of people uses this rule, so let's make sure they're informed.

**Comment by jeddy3** [comment]
> I think we should add a warning in the code for the deprecation

Agreed.
