### ISSUE TITLE
ignoreFiles doesn't work with postcss-cli

### ISSUE THREAD

**Issue by ericorruption** [stylelint/stylelint#2014]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

ignoreFiles is not being respected when used inside postcss-cli (and more specifically postcss-partial-import)

> Which rule, if any, is this issue related to?

None

> What CSS is needed to reproduce this issue?

Reduced test case available at https://github.com/ericorruption/stylelint-postcss-cli

> Which version of stylelint are you using?

`7.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Postcss-cli (with stylelint as a plugin)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

No parsing of styles from node_modules files

> What actually happened (e.g. what warnings or errors you are getting)?

Errors on a node_modules file were thrown.

I tried several different syntaxes, even referencing a single file instead of globs, setting a `configBasedir`, and none of that worked.

**Comment by davidtheclark** [comment]
> Errors on a node_modules file were thrown.

What errors?

**Comment by ericorruption** [comment]
Sorry, I meant the usual style warnings of stylelint.

**Comment by evilebottnawi** [comment]
@davidtheclark i am using in some projects `postcss-cli`, i can investigate

**Comment by davidtheclark** [comment]
@ericorruption: After looking at your repo, I believe what's happening is that you're compiling imports *first* and running stylelint *second*. This means that by the time stylelint is looking at your styles, they have been concatenated into one stylesheet. It makes sense that `ignoreFiles` doesn't work to *retroactively* ignore files that you've concatenated together.

We suggest running stylelint *as a separate process*. I think you're probably not gaining anything from using stylelint as a PostCSS plugin via `postcss-cli`: instead, why not run the stylelint CLI on the source files directly?

**Comment by ericorruption** [comment]
@davidtheclark thank you for the support. Indeed putting stylelint as the first plugin on the pipeline worked flawlessly. I was actually following a suggestion of postcss-partial-import when I put it first on the pipeline.

About running stylelint CLI directly, I thought there would be some performance gains by using the postcss pipeline instead. Not benchmarked or anything, just imagined so.
