### ISSUE TITLE
Create case study detailing quantifiable benefits of using stylelint

### ISSUE THREAD

**Issue by ptiswitz** [stylelint/stylelint#2015]
@ai Like we discuss during the CSS meetup Paris, is there is some informations/feedbacks of the community about the implementation of stylelint and its benefits ?

You told me that Facebook wrote an article about stylelint but not really on this subject. ;)

It'll be helpful to have some informations like number of PR reduces or legacy code cleaning, performance etc, to have a clear idea of the gain to use this solution.

**Comment by ai** [comment]
Sure, it was nice idea to have some real numbers from company which started to use Stylelint. I can ask some Russian developers to collect this stats, it will be very good for promotion.

What stats we should collect?

1. Core Review per month.
2. CSS related errors reports per month.
3. What else?

**Comment by davidtheclark** [comment]
Nobody has picked up this idea, and I'm not sure how feasible it is. We'd always love blog posts about stylelint, of course — but I don't think we want to keep stale issues about ideas for them.
