### ISSUE TITLE
Use Jest snapshot testing on a suite of config-stylesheet pairs

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2016]
To protect against regressions, stylelint might benefit from having a collection of config-stylesheet test cases for end-to-end tests. For each test case, the test would be straightforward: Given this config and this stylesheet, what are the stylelint results? We would never be able to make this collection complete and systematic; it will always be a "last line of defense" effort. We'd gradually fill it with any examples we find valuable, especially of regressions that have occurred in the past.

In the past I've considered this idea unrealistic, because it would involve hand-maintaining the stylelint result objects for every test case. Lately, though, I've been using [Jest](https://facebook.github.io/jest/) for React snapshot testing, and have been thinking that snapshot tests might make these end-to-end tests a real possibility. Creating and updating snapshots is very easy.

What would this look like?
- To start with, we'd ask users (and ourselves) to provide us with config-stylesheet pairs that they want to make sure don't regress. We'd be especially interested in config-stylesheet pairs that have suffered regressions in the past. This would be the beginning of the collection.
- From then on, as users run into regressions, _once the bug is fixed_ we can ask for a config-stylesheet pair to add to our suite.

Since the addition of a new test case to the suite would be so painless, we'd have little reason not to pile them up. And the more we have, the more protected we are against regressions, the more certain we are that the code is working as intended.

What do you think?

**Comment by evilebottnawi** [comment]
@davidtheclark sgtm, can you provide first example in PR?

**Comment by ntwb** [comment]
Sgtm, watched the Jest video and peeked at some of [the examples](https://github.com/facebook/jest/tree/master/examples) 👍

**Comment by jeddy3** [comment]
> We'd gradually fill it with any examples we find valuable, especially of regressions that have occurred in the past.

Excellent.

> In the past I've considered this idea unrealistic, because it would involve hand-maintaining the stylelint result objects for every test case.

Agreed.

> We'd be especially interested in config-stylesheet pairs that have suffered regressions in the past. This would be the beginning of the collection.

We'd definitely throw one of the rules that takes an array as a primary option into one of the first config-stylesheet pairs! :)

> From then on, as users run into regressions, once the bug is fixed we can ask for a config-stylesheet pair to add to our suite.

This seems like the most sensible way of building the suite.

> Since the addition of a new test case to the suite would be so painless, we'd have little reason not to pile them up. And the more we have, the more protected we are against regressions, the more certain we are that the code is working as intended.

This is a big plus as, despite our best efforts, quite a few regressions have occurred.

> What do you think?

An excellent initiative. One that we can start small and build on over time.

**Comment by davidtheclark** [comment]
Great! Sometime soon I can start a branch setting up the Jest infrastructure for it, and I'd ask everyone to contribute at least a couple of test cases to get us going.

**Comment by davidtheclark** [comment]
A system is in place and documentation at https://github.com/stylelint/stylelint/blob/master/system-tests/writing-system-tests.md. I will open another issue asking people to contribute cases.
