### ISSUE TITLE
Update Greenkeeper Bot

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2024]
I discovered today that a couple of unrequired branches created by Greenkeeper had not been deleted, i.e The changes were already covered by semantic versioning so a PR was not required.

Two more occurrences of this have since occurred:
• https://github.com/stylelint/stylelint/commit/76645ec20abc91c53c3f1b728ceeaac23a77881e - https://github.com/stylelint/stylelint/compare/greenkeeper-benchmark-2.1.2
• https://github.com/stylelint/stylelint/commit/f9a51ae659c94087435e0f0b212cb40084bc7a13 - https://github.com/stylelint/stylelint/compare/greenkeeper-lodash-4.16.5

I've not deleted these branches yet in case the Greenkeeper team wanted a peak.

I've pinged @greenkeeperio on [Twitter here](https://twitter.com/netweb/status/793005457254121472) in the hope of a reply 😄 

I suspect that part of the reply will be to upgrade to the new _Greenkeeper GitHub Integration_ via https://github.com/integration/greenkeeper which I believe replaces the previous workflow where a repo owner installed and authorised it locally to a centrally managed service on GitHub.

I'll update this issue as I discover more on the new workflow and any reply from @greenkeeperio

**Comment by Arcanemagus** [comment]
Just a note that I see this _all_ the time over on the AtomLinter repos.

**Comment by jeddy3** [comment]
@ntwb Thanks for spoting and looking into this.

> which I believe replaces the previous workflow where a repo owner installed and authorised it locally to a centrally managed service on GitHub.

This was me.

> I suspect that part of the reply will be to upgrade to the new Greenkeeper GitHub Integration

I figured I'd be proactive and migrate to this integration (and, because it's easier to setup, roll it out across the whole stylelint org).

**Comment by ntwb** [comment]
Cool 😎 

I've deleted the two branches I originally mentioned, will close this ticket and we can reopen if branches are still not being deleted using the new and presumably improved Greenkeeper integration.

**Comment by ntwb** [comment]
FYI: I emailed Greenkeeper support yesterday about this ongoing issue.

Currently there are 3 branches for `stylelint-config-standard` which I referenced in my email
• https://github.com/stylelint/stylelint-config-standard/branches

There are currently 4 branches here for `stylelint` that I didn't reference in the email, though I'm going to delete these 4 branches now all the same and just wanted to document them here:
• greenkeeper/jest-17.0.3
• greenkeeper/lodash-4.17.1
• greenkeeper/jest-17.0.2
• greenkeeper/eslint-3.10.1
