### ISSUE TITLE
Deprecate declaration-block-properties-order

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2035]
Ref: https://github.com/stylelint/stylelint/issues/2010

- [ ] Add deprecation warning.
- [ ] Add tests for deprecation warning.
- [ ] Update changelog (post merged) - "Deprecated: `declaration-block-properties-order` rule. Use the community [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) plugin pack instead. See the [release planning](/docs/user-guide/release-planning.md) document for more details."

**Comment by evilebottnawi** [comment]
@jeddy3 what about move `stylelint-order` to `stylelint` org? My opinion was that, the basics rules should be either in the core or in the organization. In life happen different good and bad things and contributor(s) may not have the ability or time to fix something or add or change. This will cause the inability to handle requests from the community associated with sorting features, declaration, etc., which will be negative effects for us. After reviewing the configuration of other organizations, I see that these rules are almost all that once again says that the community needs these rules on the basis of this it seems to me that they belong in the core.

**Comment by ntwb** [comment]
I think it would be worth considering, or at least putting this on the table for discussion in adding a few of the repos to the `stylelint` orginization:

For example, some of the repos that would be up for consideration:
• https://github.com/hudochenkov/stylelint-order
• https://github.com/kristerkari/stylelint-scss
• https://github.com/morishitter/stylefmt

We've discussed this type of proposal numerous times in the past and the one of reasons these plugins and projects are *not* in the stylelint organization is based on the @stylelint/core availability to commit the time required to maintain any extra projects.

If we were to add any project we could add the existing project maintainers as new stylelint organization members groups, e.g. @stylelint/order, @stylelint/scss, @stylelint/stylefmt.

That would then hopefully not change the existing projects in how or by who each of the projects are maintained by or further developed yet it would bring improved "branding" to each of the projects and stylelint as a whole

**Comment by evilebottnawi** [comment]
@ntwb I personally think
- https://github.com/hudochenkov/stylelint-order should move rules in core. Sorting is very popular and good practice. Any alternative linters `csslint`, `scss-lint` and etc have similar rules in core. The transfer of these rules into the core will allow us to quickly fix bugs that have a positive impact on the attitude of the community in the us.
- https://github.com/kristerkari/stylelint-scss should remain as is, separate repo. 
- https://github.com/morishitter/stylefmt should move to `stylelint` org. Almost all of Linter have the opportunity to correct mistakes and it is very convenient, I am sure that over time, the growth of the community, we will continuously receive the same requests for the implementation of this. Transfer to the organization will allow us to meet these demands and to create a positive opinion about us

**Comment by hudochenkov** [comment]
I'm all in to move `stylelint-order` into stylelint organisation or to help integrate rules from this pack to the core.

**Comment by hudochenkov** [comment]
[`stylelint-test-rule-ava`](https://github.com/hudochenkov/stylelint-test-rule-ava) might be also in stylelint organization besides `stylelint-test-rule-tape`.

**Comment by jeddy3** [comment]
> https://github.com/hudochenkov/stylelint-order **should move** rules in core.
> https://github.com/kristerkari/stylelint-scss **should remain** as is, separate repo.

This debating whether a _particular module_ should or shouldn't be in the org is exactly what we've avoided by drawing up our [_clear, unambiguous and communicable_ criteria](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#let-everyone-know). We haven't had to debate things these last few months. Instead, we'd simply refer to the criteria, mark a module accordingly and move on. 

> This will cause the inability to handle requests from the community associated with sorting features, declaration, etc.,

Each of the criteria address problems we're actually faced in the past, rather than some possible future problem we've yet to encounter. For example, only supporting standard syntax and constructs helps core avoid getting snowed under with issue like [this](https://github.com/kristerkari/stylelint-scss/issues/21#issuecomment-232562051).

> the one of reasons these plugins and projects are not in the stylelint organization is based on the @stylelint/core availability to commit the time required to maintain any extra projects.

True, but it's about sustainably maintaining a level of _code quality_ and _interoperability_. Right now, when we release a new version of stylelint (and a compatible stylelint-config-standard, website, demo and rule-tester) we _don't guarantee compatibility with community plugins or tools like stylefmt_. That is the responsibility of those plugins authors to do, and in their own time. This guarantee of compatibility is _clearly communicated_ by the fact stylelint (stylelint-config-standard et al) are within the stylelint org, whereas plugins like `stylefmt` and `postcss-scss` are not. I think if we move away from using this criteria and system, I think things get a murkier and I'm struggling to see the advantages of doing so.

**Comment by davidtheclark** [comment]
Summarizing the above, here are the two main arguments for keeping things out of the org:
- Clear, unambiguous, communicable criteria for what's in the org and what's not.
- Moving things into the org suggests that @stylelint/core is going to take on all or some maintenance burden, and that's not good. The point of the division is to allow @stylelint/core to accept responsibility for some things while handing off responsibility for others. This is necessary. And any of us who want to contribute to non-core projects can still do so.

The only argument I'm hearing in favor of moving things into the org is to boost public opinion of stylelint. Right?

**Comment by ntwb** [comment]
Thanks for the feedback everyone 👍 , both @davidtheclark and @jeddy3 remind me (once again) that any repo that is in or moved to the stylelint organisation will have regardless of how the repo is configured will have an implied status that it is maintained by the stylelint organisation.

> The only argument I'm hearing in favor of moving things into the org is to boost public opinion of stylelint. Right?

Yes, that was where I was coming from

**Comment by evilebottnawi** [comment]
@davidtheclark @jeddy3 https://github.com/hudochenkov/stylelint-order As these rules are used in all other configurations, I think this is the case where we have to take responsibility for these rules, it is important for the community and we should take this into core. I understand the importance of modularity and separation, but this is not the case, this is an important feature of any coding style, and each time we get a negative from the community where they will be something not working

**Comment by evilebottnawi** [comment]
@hudochenkov 
> stylelint-test-rule-ava might be also in stylelint organization besides stylelint-test-rule-tape
I think we should take a decision after the resolution of the issue https://github.com/stylelint/stylelint/issues/1947

**Comment by evilebottnawi** [comment]
@davidtheclark @jeddy3 I'm also of the opinion that we should not reduce the core opportunity in favor of plugins, plugins need to add features (non standard features), but removing a rule, we reduce our capacity. I'm also ready to add from myself that I would be able to base configuration without connecting additional plugins, and as I said earlier, I have sorting properties and declaration is very important feature.

**Comment by jeddy3** [comment]
> but removing a rule, we reduce our capacity

This is what I'm struggling to understand. Surely when added the plugin (and processor) system, and encouraged its use, we _increased_ capacity rather than reduced it? 

By sticking with our current approach (e.g. having plugins as a top level navigation item on the website) we _normalise the use of plugins_, thus empowering us all.

> I think this is the case where we have to take responsibility for these rules, it is *important* for the community

By the same token one could argue that `stylelint-bem-pattern` is the _most_ important rule if you write BEM code, and by this argument we should include it in core. This is what happens when you move from a nonsubjective list of criteria to a subjective one. One person's "important" can be very different from another's, whereas whether a rule targets only standard syntax or not (or if it has a clearly defined finished state) is not subjective.

**Comment by evilebottnawi** [comment]
@jeddy3 
> By sticking with our current approach (e.g. having plugins as a top level navigation item on the website) we normalise the use of plugins, thus empowering us all.

But if but if our CMS (application, site builder) can not do the navigation it will cause a lot of requests from the community to build this functionality. 

> By the same token one could argue that stylelint-bem-pattern is the most important rule if you write BEM code, and by this argument we should include it in core.

To assess this, I do not use what is defined metrics, I just opened all the known configuration and looked well-known code styles of larger and little organizations (we can search this in github), and almost everywhere there is the rule, on this basis, I expect that it is important for our community.

**Comment by evilebottnawi** [comment]
And I can tell you another important argument. I work in many projects we clearly observe the licensing of its violation leads to penalties, I am glad that our project is under MIT license, but we can not answer for the licensed plugins. I would not want to engage in rewriting the rules of the code, when the author decides that he wants to change the license out of it, I have experienced this many times.

**Comment by evilebottnawi** [comment]
Honestly, I think we will be constantly faced with these issues has not yet decided on the point of view of what is important and what is not. Solutions based on the opinion that it makes code easier to contribute, I do not think that is correct. With this view, we can simply place our project with no rules and everything else to make plugins (such as `cssnano`).

**Comment by evilebottnawi** [comment]
In fact, we long to decide what is important and what is not, and everyone will have their own point of view on this issue. I propose to develop a method for determining the importance (or come up with a better name) on the basis of which we make decisions. Part of my configuration rules mood to `null` so I can also be argued that these rules are not important and they should be plugins, but this is the wrong decision, am I not right?

**Comment by davidtheclark** [comment]
@evilebottnawi Users need to feel comfortable using plugins. Period. We need to make it *easy* to use plugins; and users need to accept that that's part of stylelint. Users have completely accepted that plugins are part of ESLint, Babel, PostCSS, etc. It's not unusual at all. The fact that a plugin is popular *does not necessarily mean it should become a core rule*. Instead, it means that the plugin system is working well, and that particular plugin is a good one.

> we will be constantly faced with these issues has not yet decided on the point of view of what is important and what is not

@evilebottnawi You are ignoring the fact that we have already defined some clear criteria for including rules in core: https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#let-everyone-know. The ordering rules violate three of these:

- Has a clear and unambiguous finished state.
- Has a singular purpose.
- Does not contain functionality that overlaps with another rule.

Maybe ordering is popular, but that's only one of the the criteria. Why do we have these criteria? 

Without a clear and unambiguous finished state the rule becomes tangled, confused, overly complex, always dissatisfactory to some base of users; and that confusion takes our time away from projects more essential to the core application. The same applies to rules without a singular purpose. 

It's possible that by splitting up ordering rules we can fix those two criteria. But then we clearly violate the last one. Users will have to know that they can't turn on one ordering rule if another is turned on, or they can but without certain options, etc. Will we write logic to warn them in these situations? Who will they complain to?

So @evilebottnawi, since *we have* already defined criteria for including rules in core, you'll have to argue why these *don't matter* in this case, or are bad criteria.

**Comment by evilebottnawi** [comment]
https://github.com/hudochenkov/stylelint-order/tree/master/rules
> Has a clear and unambiguous finished state.

Exclude `declaration-block-order` with `dollar`, all clean and unambiguous finished state.

> Has a singular purpose.

Each rule have single purpose.

> Does not contain functionality that overlaps with another rule.

After deprecation `declaration-block-properties-order` not contain functionality that overlaps with another rule.

And yes, it is **popular** rule.
I do not see anything disturbing our criteria, maybe I missed something?

**Comment by davidtheclark** [comment]
> all clean and unambiguous finished state

Not convinced. The reason we are where we are is because there is *not* a clean and unambiguous finished state.

> not contain functionality that overlaps with another rule.

The rules in this plugin pack *clearly* overlap with each other.

@evilebottnawi look at https://github.com/mysticatea/eslint-plugin-node. I think those are essential ESLint rules for any node project. It's a mistake not to use them. Does that mean that ESLint should incorporate them into the core set of rules? No, because ESLint has their own criteria for inclusion that I respect, *using a plugin is easy*, and it's even kind of nice to have rules grouped by purpose in this way.

I imagine something like this as a canned response to requests for ordering rules:

> We've found that rules to enforce property order, property groupings, etc., work better as plugins, because there are so many different opinions about what to enforce, and how. When you write or use a plugin, you can make sure to enforce your own particular preferences, exactly; but a rule that tries to address too many divergent use-cases becomes a mess. Plugins are easy to incorporate into your configuration. There are a few excellent ordering plugins that we suggest you look into: ...

**Comment by evilebottnawi** [comment]
@davidtheclark It seemed to me that the main problem was sorted and groups and by expanding the two rules is a problem solved, the more I do not remember what that problems.

> The rules in this plugin pack clearly overlap with each other.

From `eslint`:
> For no-extra-parens, set {nestedBinaryExpressions: false} by default (to avoid conflicting with no-mixed-operators)

Some rules in `eslint` also overlap with other. https://github.com/eslint/eslint/issues/7407#issuecomment-254930694

**Comment by evilebottnawi** [comment]
@davidtheclark https://github.com/mysticatea/eslint-plugin-node separate because `eslint` for ECMA, `eslint-plugin-node` for implementation `ECMA` on `v8` aka `nodejs`.

**Comment by evilebottnawi** [comment]
Using `property-no-vendor-prefix` and `property-blacklist` with `['--webkit-.*']` also `overlap`

**Comment by evilebottnawi** [comment]
> The rules in this plugin pack clearly overlap with each other.

`declaration-block-properties-alphabetical-order` and `declaration-block-properties-specified-order` ? 

Also overlap `selector-no-qualifying-type` and `selector-no-type` on example `a[title='test'] { }` :disappointed:

**Comment by evilebottnawi** [comment]
Rules in any case, sooner or later will overlap on certain sections of code, you can see all the famous linter for example, and in this I do not see anything wrong, bad when two or more rules are responsible for the same purpose

**Comment by davidtheclark** [comment]
You are missing my point about eslint-plugin-node. The point is that *plugins are good for users, good for maintainers, good for the community, and we shouldn't be afraid of them*. Plugins *can and should* provide functionality that some users consider *essential*.

The main force of your argument sounds to me like "I don't want to use plugins. Other users don't want to use plugins. So because we like ordering rules we want those rules in core instead of in plugins." That's not an argument that convinces me. You and other users need to accept plugins.

I still think these ordering rules are more use-case-specific (i.e. users will want all kinds of variations), more messy and open-ended than the other rules we have in core. I think that's a good reason to keep them as plugins.

**Comment by evilebottnawi** [comment]
@davidtheclark well, let's leave it at that then maybe the time to change my opinion, I'm not saying that is bad plugins, I would argue that these rules should be at the core

**Comment by jeddy3** [comment]
> remind me (once again) that any repo that is in or moved to the stylelint organisation will have regardless of how the repo is configured will have an implied status that it is maintained by the stylelint organisation.

> The point is that *plugins are good for users, good for maintainers, good for the community, and we shouldn't be afraid of them*. Plugins *can and should* provide functionality that some users consider *essential*.

I think these two bits come together nicely to summarise the final points.

> well, let's leave it at that then

Good stuff. Thanks for discussion everyone. Lets be sure to keep the key points of this discussion in mind should the issue pop up again.

> We've found that rules to enforce property order, property groupings, etc., work better as plugins, because there are so many different opinions about what to enforce, and how. When you write or use a plugin, you can make sure to enforce your own particular preferences, exactly; but a rule that tries to address too many divergent use-cases becomes a mess. Plugins are easy to incorporate into your configuration.

This is really nice. I suggest we add it to [this entry](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#what-is-the-difference-between-a-plugin-and-a-rule) of the FAQ. Perhaps fleshing out that FAQ entry a little too. I'll create a separate issue for it.

So, back to the issue at hand... I'll probably have time this week to add the code to deprecate `declaration-block-properties-order` if no one beats me to it.

**Comment by xereda** [comment]
For me to be able to use `declaration-block-properties-order` in vscode, how do I do it now?

**Comment by xereda** [comment]
@hudochenkov Tks. It's working for me.
