### ISSUE TITLE
Adapt "multi-line" and "single-line" options rules to be consistent in their naming and behaviour

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#204]
Rename `rule-semicolon-` rules to `declaration-block-:

* [ ] `declaration-block-semicolon-newline-after`:
* [ ] `declaration-block-semicolon-newline-before`
* [ ] `declaration-block-semicolon-space-after`
* [ ] `declaration-block-semicolon-space-before`

Add test to `block-*-brace-*` to ensure "multi-line" and "single" line refers to the just the block and not the whole rule.

* [ ] `block-closing-brace-newline-after`:
* [ ] `block-closing-brace-newline-before`
* [ ] `block-closing-brace-space-after`
* [ ] `block-closing-brace-space-before`

* [ ] `block-opening-brace-newline-after`
* [ ] `block-opening-brace-newline-before`
* [ ] `block-opening-brace-space-after`
* [ ] `block-opening-brace-space-before`

---

Is it possible to add explanations of the terms used in the rules documentation?  

In particular I'm looking at the docs for [rule-semicolon-newline-after](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-semicolon-newline-after/README.md) but I'm not sure exactly what a `rule` is, and the difference between a `rule` and a `multi-line rule`.

Using the definitions from http://apps.workflower.fi/vocabs/css/en, my (potentially incorrect) understanding is that the logic of `rule-semicolon-newline-after` is applied to each declaration in a declaration-block.  And a multi-line rule could be described as a declaration-block containing multiple declarations and at least one newline character.  Would that be an accurate description?

I think I have more questions on the documentation but would like to make sure I understand this bit first :)

**Comment by davidtheclark** [comment]
Your understanding is correct.

**Comment by jeddy3** [comment]
@m-allanson :

> but I'm not sure exactly what a rule is,

A ruleset is a selector and declaration-block together. "Ruleset" can be shorten "rule", which is what we're doing: https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax#CSS_rulesets

Thanks BTW! This is another question subtle question that exposes inconsistencies in rule names and their options.

@davidtheclark Remember how we renamed `declaration-comma-*` to `value-list-comma-*`, over in #178, to remove any ambiguity from whether the `multi-line` and `single-line` options refer to the whole declaration or just the value? I think this issue to related to that.

```js
value-list-comma-*: "always"|"always-multi-line"
      ↑                                 ↑  
// value-list is "the thing"      and "multi-line" (and "single-line") are in reference to it.
```

I think two sets of rules might not (depending on the desired behaviour) align with this convention:

* The `block-*-brace-*` rules.
* The `rule-semicolon-*` rules.

Lets start with the `rule-semicolon-*` rules...

If the following is consider `single-line` (in the context of these rules):

```css
a,
b { color: pink; background:red; }
```

The rules should be renamed to `declaration-block-semicolon-*` to match the convention and *narrow* the scope of the rules to just the declaration block. The `block-*-brace-*` rule names would remain the same.

Whereas if the following is considered `multi-line` (in the context of these rules):

```css
a,
b { color: pink; background:red; }
```

Then I think the `block-*-brace-*` rules should be renamed to `statement-*-brace-*` to match the convention and *broaden* the scope of the rule to the whole statement. The `rule-semicolon-*` rule names would remain the same.

I'm pretty sure it's the former we are after. So, I think it's the `rule-semicolon` rules that should be renamed to remove any ambiguity.

Thoughts?

**Comment by davidtheclark** [comment]
Yep, makes sense to me. Good thinking.

**Comment by m-allanson** [comment]
Yep, this also makes sense to me.
