### ISSUE TITLE
Better test the CLI

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2046]
I do not know of a good way to test the CLI *directly* (maybe others know?); but I do think that we could do more than we are.

What I suggest is that we change `cli.js` such that it passes the `meow` `cli` object to an outside, tested function. That function will be tested against `cli` objects: e.g. what happens if we receive `cli.flags.customReporter`, etc. It should mock `standalone` and just check that `standalone` is called with the expected arguments, and the output is dealt with accordingly.

**Comment by jeddy3** [comment]
> What I suggest is that we change `cli.js` such that it passes the `meow` `cli` object to an outside, tested function. 

This sounds like a good plan to me.

**Comment by jeddy3** [comment]
Closing as stale.
