### ISSUE TITLE
Add a NuGet package & keep it updated?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stylelint/stylelint#2055]
For projects on the MSBuild/NuGet stack, it can be difficult to keep `npm` modules updated. Common ways around it now are:
* Running `npm install`/`yarn install` during builds - either slow, or even undoable on machines without internet access
* Checking the installed module into source control *(yuck!)*

Having something like [tslint-nuget](https://github.com/joshuakgoldberg/tslint-nuget), updated with stylelint's releases, would be helpful.

I'd be willing to make the NuGet package generator, though I don't know how much I can help with the release process beyond suggesting how to publish it.

**Comment by ntwb** [comment]
I'm not at all familiar with MSBuild or Nuget, with that in mind:

From what I see the `tslint-nuget` package is independant of TSLint, I presume when a new release of TSLint is released the `tslint-nuget` maintainer updates and releases that package?

FYI: I don't see the stlyelint organization's role as a maintainer of packages for all the package managers out there either for what it worth.

**Comment by JoshuaKGoldberg** [comment]
> `tslint-nuget` package

Correct. It's just a simple wrapper around a copy of some version of `tslint`. In your case, `stylelint-nuget` would also just be a small wrapper around a copy of `stylelint`. Not to be confused with `S`-etc.

> organization's role

Sure. I like asking, but get that it's not on you.

**Comment by jeddy3** [comment]
> FYI: I don't see the stlyelint organization's role as a maintainer of packages for all the package managers out there either for what it worth.

I understand the intent of the issue, i.e. to help increase adoption of stylelint by those who use MSBuild/NuGet stack, and hopefully someone in the community, who uses stylelint and MSBuild/NuGet, maintains such a package.
