### ISSUE TITLE
Use `husky`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2063]
Ref: https://github.com/typicode/husky

1. Reduce the amount of PR with unclimbed style and tests.
2. Less load on the CI.
3. Very handy tool :smile:

**Comment by davidtheclark** [comment]
I would prefer not to use husky to automate these things that I already do within my own workflow. I'd predict it getting in the way more often than helping out, running tests when I commit after I just ran tests before I committed, etc. Besides that, I don't think it's solving a problem that we have. CI already catches any such mistakes. (And I don't think we're overloading the CI.)

**Comment by evilebottnawi** [comment]
@davidtheclark we can use `prepush` hook, not `precommit`

**Comment by davidtheclark** [comment]
@evilebottnawi But I don't want a prepush hook, either, if I'm already testing what I need to test.

**Comment by evilebottnawi** [comment]
@davidtheclark We just found this tool is convenient for the team, developers sometimes forget to do all the tests and it helps to reduce the load on the CI server and prevents unnecessary incorrect PR, If nobody is interested in this, I closed this issue

**Comment by davidtheclark** [comment]
> We just found this tool is convenient for the team

Totally agree, and I'm glad you introduced me to this tool 👍  I just don't think I myself want it as part of my workflow — it would be more of an obstacle than a help.

**Comment by evilebottnawi** [comment]
@davidtheclark i am close this issue, if someone from @stylelint/core have another opinion you can reopen issue
