### ISSUE TITLE
Feature Request: Support for browserslist file

### ISSUE THREAD

**Issue by npars** [stylelint/stylelint#2068]
Some rules support passing a browserslist string as an argument. Other browserslist utilities ([autoprefixer](https://github.com/postcss/autoprefixer)) support a browserslist file in the current or parent directories. It would be useful for styelint to support this file as well so that the browserslist configuration does not need to be duplicated in many places.

This applies to:
[`no-browser-hacks`](https://github.com/stylelint/stylelint/blob/master/src/rules/no-browser-hacks/README.md), [`no-unsupported-browser-features`](https://github.com/stylelint/stylelint/blob/master/src/rules/no-unsupported-browser-features/README.md)

**Comment by jeddy3** [comment]
@npars Thank you for the suggestion. As with https://github.com/stylelint/stylelint/issues/2054#issuecomment-260601531, I think your issue could be the catalyst for discussing whether these rules belong outside of core as plugins (perhaps within the same pack as they are both focused on checking things specific to the browsers being targetted). As with https://github.com/stylelint/stylelint/issues/2054, I think doing so would be a good thing. For example, it could facilitate experimentation with such a `browserlist` feature. 

@stylelint/core I think we've a better understanding of the division of core rules and plugins now than we had 6 months ago. And I think `8.0.0` is shaping up as our opportunity to further stabilise core, ensuring that _all_ the rules within it adhere to our criteria. What do you think?

As a reminder, both these rules (along with `no-indistinguishable-colors`, which seems mostly applicable to _compiled_ CSS) are wrappers around 3rd party PostCSS plugins.

**Comment by jeddy3** [comment]
Closing in favour of https://github.com/stylelint/stylelint/issues/2079
