### ISSUE TITLE
Feature request: Support for linting CSS inside Markdown files.

### ISSUE THREAD

**Issue by ben-eb** [stylelint/stylelint#2070]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'd like to lint CSS inside Markdown files, so I wrote a small extension to PostCSS that can do this at an abstract level: https://github.com/ben-eb/literate-postcss

This would be a similar thing to https://github.com/eslint/eslint-plugin-markdown but I'm not sure exactly how to do this with Stylelint plugins instead; this functionality operates at the parser level and not the plugin level.

Anyway, I'd like to start a conversation on making an extension to Stylelint that had this behaviour. Thanks!

> Which rule, if any, is this issue related to?

n/a

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

n/a

> Which version of stylelint are you using?

`7.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it relates to parsing CSS inside Markdown files.

> What did you expect to happen?

n/a

> What actually happened (e.g. what warnings or errors you are getting)?

n/a

**Comment by davidtheclark** [comment]
@ben-eb Already exists: https://github.com/mapbox/stylelint-processor-markdown Does that work for you?

**Comment by ben-eb** [comment]
Ah nice, didn't realise it existed already! Thanks.
