### ISSUE TITLE
Cannot override some rules that extend from stylelint-config-*

### ISSUE THREAD

**Issue by morishitter** [stylelint/stylelint#2071]
Some rules e.g. `time-no-imperceptible` have only `true` option, so if these rules are defined in stylelint-cofig-* and extend it, we cannot override its rule.

I want `false` option to resolve that.

```
{
  "extends": "stylelint-config-qiita",
  "rules": {
    "time-no-imperceptible": false
  }
}
```

Thanks! :)

**Comment by ntwb** [comment]
Use `"time-no-imperceptible": null` to overwrite a configuration

See rules configuration docs: http://stylelint.io/user-guide/configuration/#rules

**Comment by morishitter** [comment]
@ntwb Oh, Thank you so much.
