### ISSUE TITLE
Add ignoreFontFamilyName: [] option to font-family-no-duplicate-names

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2086]
Follow up to #1284 

There should be a way to ignore, or optionally ignore duplicate `monospace` font names in `font-family-no-duplicate-names`

Ways to approach this:

1. Ignore `monospace, monospace` by default
2. Add an option to ignore only the `monospace` duplicates, i.e. `monospace, monospace`
3. Add an option to add an array of font names using regex/string to be ignored.

----

For context the above is based on the following comments in #1284:

Over in #1284 @ben-eb made the [following comment](https://github.com/stylelint/stylelint/issues/1284#issuecomment-243898839):
> _"Just FYI, this rule should not affect `monospace, monospace`, as specifying this twice corrects rendering issues across browsers. http://code.stephenmorley.org/html-and-css/fixing-browsers-broken-monospace-font-handling/"_

I added a note [below that](https://github.com/stylelint/stylelint/issues/1284#issuecomment-243936785):
> _"One of the many reasons I dislike SEO and their practices, this said post has no date, no comments and makes it impossible to determine if this was posted 10 years ago or yesterday. Hence I place next to zero value on content of this manner."_

I've still no idea if the above is a legitimate concern for _modern browsers_ but though a rudimentary search of GitHub CSS for `monospace, monospace` returned [1 million plus results](https://github.com/search?p=8&q=%22monospace%2C+monospace%3B%22&ref=searchresults&type=Code&utf8=%E2%9C%93). A high probability that this issue would come up in the future based on those results. The article cites Google Chrome & Safari together, Chrome split from Webkit in Chrome 28 in mid 2013. As such mid 2013 browser versions would be my best guess at trying to guess the versions of browsers that this issue refers to, what has changed in regard to this issue for each browser since then I'm also unaware of /shrug

Thoughts @stylelint/core ?

**Comment by ntwb** [comment]
Some further background on this I just noticed that this was included in `normalize.css`:

• https://github.com/necolas/normalize.css/blob/master/README.md#pre-code-kbd-samp:

> `pre`, `code`, `kbd`, `samp`
> 
> The `font-family: monospace, monospace` hack fixes the inheritance and scaling of font-size for preformatted text. The duplication of monospace is intentional. [Source](https://en.wikipedia.org/wiki/User:Davidgothberg/Test59).

From the source cited above: https://en.wikipedia.org/wiki/User:Davidgothberg/Test59:
> Explanation: Some browsers on some operating systems show `<tt>`, `<code>`, `<pre>` and `<source>` tagged text in a too small font. At the time I write this (21 December 2009) we have applied the code below to MediaWiki:Common.css and MediaWiki:Geshi.css, which seems to fix it for those browsers, and cause no problems in the rest of the browsers. If it works well for the English Wikipedia, then we might deploy the fix for all Wikimedia projects. See discussion at {MediaWiki talk:Common.css#Teletype style fix for Chrome](https://en.wikipedia.org/wiki/MediaWiki_talk:Common.css#Teletype_style_fix_for_Chrome).

**Comment by davidtheclark** [comment]
I think there is no harm in adding an option `ignoreMonospace` for people who want to use this hack.

**Comment by jeddy3** [comment]
Originally I [said](https://github.com/stylelint/stylelint/pull/2020#issuecomment-257599561):

> This is what the disable comment are for i.e. one-off instances (e.g. hacks or workarounds). The ignore option is there for repeating patterns that occur more than once within a codebase.

But I guess you could specify `monospace, monospace` in more than one place in the code and so it is kind of a repeating pattern.

So, I'm easy either way. If we use an option, can we make it one of those more generic ones that accept an array of _user-defined_ options? e.g. `ignoreFontFamilyName: ["monospace"].  It addresses this use-case and, at little cost, adds some flexibility to the rule.

**Comment by davidtheclark** [comment]
^^ 👍

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/issues/2314
