### ISSUE TITLE
Suggestion: Add `files` to configuration

### ISSUE THREAD

**Issue by AntonNiklasson** [stylelint/stylelint#2100]
Add an option for whitelisting files in `.stylelintrc` compared to `ignoreFiles` which is a blacklisting of files.

Could be named `files` or perhaps `includeFiles`.

**Comment by davidtheclark** [comment]
Why?

**Comment by jeddy3** [comment]
@AntonNiklasson Feel free to reopen this issue with a compelling use case that isn't covered by input globs and `ignoreFiles`. Closing for now.
