### ISSUE TITLE
TypeError for unknown unprefixed variants in media-feature-name-no-vendor-prefix

### ISSUE THREAD

**Issue by subzey** [stylelint/stylelint#2109]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug: stylelint crashes.

> Which rule, if any, is this issue related to?

`media-feature-name-no-vendor-prefix`

> What CSS is needed to reproduce this issue?

```css
@media (device-pixel-ratio: 2) {}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "selector-no-vendor-prefix": true,
  }
}
```

> Which version of stylelint are you using?

`7.6.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

Stylelint not to crash

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
TypeError: Cannot read property 'forEach' of null
    at /home/akhlynovskiy/code/tradingview/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:22:14
    at /home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:302:28
    at /home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:148:26
    at Root.each (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:147:21)
    at Root.walkAtRules (/home/akhlynovskiy/code/tradingview/node_modules/postcss/lib/container.js:300:25)
    at /home/akhlynovskiy/code/tradingview/node_modules/stylelint/dist/rules/media-feature-name-no-vendor-prefix/index.js:15:10
    at /home/akhlynovskiy/code/tradingview/node_modules/stylelint/dist/lintSource.js:104:52
```

Proposed fix: https://github.com/subzey/stylelint/commit/c51c8cd8712141d31b9386437e38f063e998cea5

**Comment by evilebottnawi** [comment]
@subzey it is valid `css`? I can try validate in https://jigsaw.w3.org/css-validator/validator and got error

**Comment by subzey** [comment]
@evilebottnawi, it is syntactically valid, the validator only complains about the missing feature. And postcss parses it as well.

(You can place anything inside the `@media` block, if won't affect the crash)

Here's [a little demo](https://jsfiddle.net/fgyjLLm9/) where vendor prefixed versions works fine in both Firefox and Chrome.

**Comment by subzey** [comment]
The `-webkit-device-pixel-ratio: 2` feature indeed doesn't have its unprefixed variant, instead `min-resolution: 2dppx` should be used.

But I'd prefer the linter to yell at me with red colored text, but not to crash with a JS stacktrace.

**Comment by davidtheclark** [comment]
The proposed fix is good. The code should anticipated the possibility that `matches` returns `null`.

@subzey want to submit a PR with tests?

**Comment by subzey** [comment]
Sure

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/2152
