### ISSUE TITLE
Remove rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2124]
- [x] `block-no-single-line` 
- [x] `custom-property-no-outside-root`
- [x] `declaration-block-no-ignored-properties`
- [x] `declaration-block-properties-order`
- [x] `media-feature-no-missing-punctuation`
- [x] `no-browser-hacks`
- [x] `no-indistinguishable-colors`
- [x] `no-unsupported-browser-features`
- [x] `root-no-standard-properties`
- [x] `rule-nested-empty-line-before`
- [x] `rule-non-nested-empty-line-before`
- [x] `selector-no-empty`
- [x] `selector-root-no-composition`
- [x] `stylelint-disable-reason`
- [x] `time-no-imperceptible`

**Comment by m-allanson** [comment]
Refs #2123 and its associated PR.

**Comment by ai** [comment]
@davidtheclark why you want to remove `no-unsupported-browser-features` and `no-indistinguishable-colors`?

People really afraid to use new tools. They will just ignore `doiuse` and other PostCSS based tools.

**Comment by hudochenkov** [comment]
@ai https://github.com/stylelint/stylelint/issues/2222

**Comment by sinedied** [comment]
It would be better to provide an upgrade path for users currently using `no-unsupported-browser-features` in their projects (like mine), like providing a plugin with the same functionality instead of directly removing it, don't you think?

**Comment by hudochenkov** [comment]
@sinedied it would be better. That's why we inform community about these changes and ask them to make a plugin if they still need these rules.

**Comment by sinedied** [comment]
@hudochenkov but since you already have it working in current version, why don't you extract the current code in a plugin already and search for a new maintainer instead of hoping that someone will rewrite the whole thing?

**Comment by hudochenkov** [comment]
@sinedied Courage™! We have reasons to exclude `no-unsupported-browser-features` https://github.com/stylelint/stylelint/issues/2222 We give an opportunity to a brave person in the stylelint community to create a plugin, which helps other people. While we can focus on stylelint to make it better.

**Comment by jeddy3** [comment]
> give an opportunity to a brave person in the stylelint community to create a plugin

@sinedied It sounds like you use the `no-unsupported-browser-features` rule. Would you like to be that person and champion this plugin? As you said, it would just be a case of extracting the rule code [into a plugin](https://stylelint.io/developer-guide/plugins/). As you currently make use of the rule you're an ideal candidate for maintaining it.

**Comment by davidtheclark** [comment]
@sinedied Just to be clear: *anybody* can extract the current code into a plugin — nobody has to rewrite the whole thing or any part if they don't want to. Open source!

**Comment by sinedied** [comment]
Sure, anybody can extract the source, but surely *understanding* it is another matter, I bet someone from the `stylelint` team can pull it out in less time that I would need to just get started with it, that was my point.

**Comment by jeddy3** [comment]
@stylelint/core FYI, @m-allanson and I just brought the `v8` branch up-to-date with `master`. Therefore the issues in the [`8.0` milestone](https://github.com/stylelint/stylelint/milestone/23) are ready to be tackled. Assign yourself and label as `status: wip` if any of them take your fancy :)

**Comment by hudochenkov** [comment]
@m-allanson Would you remove deprecated rules? Or shall I do this?

Unrelated question: is it ok to merge `master` into `v8` without a PR?

**Comment by m-allanson** [comment]
@hudochenkov I will do this soon :)

Yes I think it's ok to merge `master` into `v8` without a PR.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/issues/2422
