### ISSUE TITLE
Deprecate block-no-single-line

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2125]
`block-opening-brace-newline-after` and `block-closing-brace-newline-before` are more flexible and can be used to achieve the same.

Ref: https://github.com/stylelint/stylelint/issues/2079

**Comment by davidtheclark** [comment]
> block-opening-brace-newline-after and block-closing-brace-newline-before are more flexible and can be used to achieve the same.

This isn't self-evident to me. Can you please explain how you'd do this?

**Comment by jeddy3** [comment]
> Can you please explain how you'd do this?

```json
{
  "block-opening-brace-newline-after": ["always"],
  "block-closing-brace-newline-before": ["always"]
}
```

Would allow:

```css
a {
  color: red;
}
```

But not this:

```css
a { color: red;
}
```

This:

```css
a {
color: red; }
```

Or this:

```css
a { color: red; }
```

If you wanted to allow single line blocks then you'd use the `"always-multi-line"` option for both rules.

At moment the following config:

```json
{
  "block-opening-brace-newline-after": ["always"],
  "block-closing-brace-newline-before": ["always"],
  "block-no-single-line": true,
}
```

With:

```css
a { color: red; }
```

Produces:

```shell
1:3 error Unexpected single-line block (block-no-single-line)
1:4 error Expected newline after "{" (block-opening-brace-newline-after)
1:16 error Expected newline before "}" (block-closing-brace-newline-before)
```

Here you can see the redundancy.

**Comment by davidtheclark** [comment]
Hmm ... thanks, I think I'm convinced. Let's see what others have to say.

**Comment by evilebottnawi** [comment]
@jeddy3 @davidtheclark how about add default example (disallow single-line, allow single-line, allow single-line with number of declaration) in docs.

**Comment by davidtheclark** [comment]
@evilebottnawi Yep, I think if we're going to remove `block-no-single-line` we have to provide those examples.

**Comment by evilebottnawi** [comment]
I think we can add note about this in https://github.com/stylelint/stylelint/issues/2123 and deprecate this rule.

**Comment by ntwb** [comment]
SGTM 👍

**Comment by jeddy3** [comment]
Moving to https://github.com/stylelint/stylelint/issues/2123
