### ISSUE TITLE
Deprecate spec validation rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2126]
Spec validation best handled in plugins?

Ref: #2079

**Comment by davidtheclark** [comment]
@jeddy3 I don't know about this ... Are there even any plugins that would handle this kind of validation for most of stylelint's users — or is it still all talk? Unless one of those tools approaches a more finished state (and also devises a method for dealing with non-standard syntax), we might have to start coming to terms with the idea that it just won't happen.

**Comment by jeddy3** [comment]
> I don't know about this ...

I'm unsure too. I figured it was worth using the audit from https://github.com/stylelint/stylelint/issues/2079 try to bring a bit more clarity to what spec-validation rules we do include in core and which we don't.

> (and also devises a method for dealing with non-standard syntax)

This is likely the kicker. 

> we might have to start coming to terms with the idea that it just won't happen.

Agreed. I'll pull the rules that _aren't about spec validation_ out of https://github.com/stylelint/stylelint/issues/2079 and into separate issues (grouped by reason). I suggest we tackle these other rules first and then revisit this one.

**Comment by evilebottnawi** [comment]
@davidtheclark @jeddy3 We can create sepo repo `stylelint-plugin-validation` (maybe best name) for dropped rules, which validate `css` syntax. I could give him some time until we find people interested in the further development. This will free the core from this rules and make it more stable and to avoid problems with the community. Never too late to remove it in the future from our organization to a separate organization.

**Comment by davidtheclark** [comment]
> We can create sepo repo stylelint-plugin-validation (maybe best name) for dropped rules

I'm not sure that we should drop any of these rules, though. Can we discuss specific rules that people think *should* go, and why?

Note that my thinking about "not being a CSS validator" is that we won't be able to know, for example, that in `horse: shoe`, `horse` is not a valid property and `shoe` is not a valid keyword. I don't really think that rules that are more straightforward mistakes, like `no-extra-semicolons` and `color-no-invalid-hex`, fall into the same category.

**Comment by evilebottnawi** [comment]
@davidtheclark 
> no-extra-semicolons
Use https://jigsaw.w3.org/css-validator/#validate_by_input, input:
```css
a {
 color: red;;
}
```
No validation error, and the specification is not considered an error, so I think that this rule should remain in the core

> color-no-invalid-hex

```css
a {
  color: #ffff;
}
```
Error: Value Error : color #ffff is not a valid color 3 or 6 hexadecimals numbers : #ffff and we have allowed hex color form in spec and this should be removed from the core, it is my my opinion.

**Comment by davidtheclark** [comment]
I agree that `no-extra-semicolons` should stay.

I also think that `color-no-invalid-hex` should stay. It's not enforcing anything that is specific to the CSS, or reliant on complex set of possibilities, and therefore kind of unstable and difficulty. Instead, it's fairly simple validation of a value type. For this reason, I would also be interested in rules like `color-no-invalid-rgba` and `color-no-invalid-hsla`.

The real problems with trying to enforce the spec come from situations where we need to check *the validity of a relationship between constructs*. For example, can the property `border-width` have the value `pink`? The amount of complexity in such an assertion is what I think disqualifies it for stylelint core. Meanwhile, we should do everything we can to assert the validity of constructs *on their own* — without the "relationship" aspect that introduces all the complexity.

**Comment by epmatsw** [comment]
Besides agreeing with @davidtheclark's comment above, it feels a bit strange to remove 2 rules that are in `stylelint-config-standard` (which implies to me that everyone should probably have them turned on).

Would the config switch to taking a dependency on `stylelint-plugin-validation` in the future and leave those rules turned on? Or would there be a `stylelint-config-standard-with-validation` that rolled up both sets? Would it actually lower the maintenance burden if there was still a linkage via a stylelint-owned project like that?

**Comment by jeddy3** [comment]
I think we've made good progress on https://github.com/stylelint/stylelint/issues/2079 - we've discussed and agreed on quite a few of the rules highlighted in that issue. It feels like deciding on the spec validation rules is going to be, understandably so, the contentious bit.

To recap, I think these are all the spec validation rules:

- `at-rule-no-unknown`
- `color-no-invalid-hex`
- `function-calc-no-unspaced-operator`
- `media-feature-name-no-unknown`
- `no-invalid-double-slash-comments`
- `property-no-unknown`
- `selector-pseudo-class-no-unknown`
- `selector-pseudo-element-no-unknown`
- `selector-type-no-unknown`
- `string-no-newline`
- `unit-no-unknown`

Proposals:

- `selector-pseudo-element-no-invalid` ([ref](https://github.com/stylelint/stylelint/issues/2155))

Deprecated in https://github.com/stylelint/stylelint/pull/2197:

- `media-feature-no-missing-punctuation`
- `selector-no-empty`

Each of these throws an invalidation warning in the [CSS](https://jigsaw.w3.org/css-validator/#validate_by_input) or [HTML](https://validator.w3.org/nu/#textarea) validators i.e. you can currently catch all-but-one (`selector-type-no-unknown`) of these (and a tonne of other) validator errors by running your processed CSS against [css-validator](https://github.com/twolfson/css-validator).

As we discuss these rules I think it's worth keeping in mind, as outlined in https://github.com/stylelint/stylelint/issues/2079#issue-190470316, there are another 150 rules in stylelint core that:

- Allow, disallow and put limits on constructs and values.
- Spot _valid_ but likely unintentional code.
- Enforce a code style.

For each of these three areas, I think we've created _comprehensive_ rule sets that cover a large number of use cases (across CSS processors and methodologies). That is to say, I don't think there's much left to do in these areas. Also, the ongoing maintenance of these areas feels sustainable as they avoid the complexity of validation.

I think it's also worth keeping in mind that we have a plugin system, which allows users to further tailor the linter to their specific needs; whether that's based on the CSS Processor they use or a particular methodology they adopt.

In contrast with the three areas mentioned above:

- I think that, unless we create a fully-fledged validator (one that checks the validity of the relationships between constructs), we won't be able to cover this area _comprehensively_ within core.
- I think this area feels like it's [in](https://github.com/csstree/csstree/issues/22) [flux](https://github.com/csstree/csstree/issues/23), at least more so than the other three areas.
- I think this is an area of potentially [massive growth](https://github.com/ben-eb/css-values/tree/master/src/validators) e.g. `color-no-invalid-*`, `selector-*-no-invalid`, `at-keyframe-no-invalid` etc.
- I think this area is more prone to compatibility problems across [language](https://github.com/kristerkari/stylelint-scss/issues/86) [extensions](http://lostgrid.org/docs.html#property-options).

Does anyone know if there is a precedence in other tools for both linting and validating source code, or is this distinction not made?

---

I'm not sure what the right way forward is. It sounds like we've a couple of choices moving forward though:

- Continue to grow the validation rules within core with the intent of providing comprehensive coverage.
- Continue to grow the validation rules within core for constructs whose validity can be asserted on their own, and use plugins for checking the validity of the relationships between constructs.
- Freeze the addition of new validation in core. Use plugins for future validation rules. Get `8.0.0` out. See what happens in the world of CSS parsers and validators in the next few months. Assess landscape for `9.0.0`.
- Deprecate all the validation rules. Gauge the communities response to creating a `stylelint-validation` plugin pack in the lead-up to `8.0.0`. Get `8.0.0` out. See what happens in the world of CSS parsers and validators in the next few months. `stylelint-validation` could act as an experimental testing ground for these changes. Assess landscape for `9.0.0`.

Any others?

I think it's worth taking our time to deliberate over this issue. I think the outcome of it will likely set the direction of stylelint development for the current year. As I said before, I don't think there's a clear right answer here. We're looking _to balance_ the sustainability of the project against its usefulness, both in the short and long term.

> Would the config switch to taking a dependency on stylelint-plugin-validation in the future and leave those rules turned on?

No, I don't think so. The `stylelint-config-standard` would just cover the three areas mentioned above. It'd be the responsibility of 3rd parties to put of configs with validation, likely based on CSS Processor being used e.g. the `stylelint-scss` team might have one.

**Comment by davidtheclark** [comment]
@jeddy3 Here are my latest thoughts on this: I don't think we should deprecate these rules until we're ready to funnel users directly into a css-values or csstree plugin. I don't think those libraries are, will be, or *should* be non-standard syntax friendly; so I think we should only deprecate these rules as part of a plan to more or less abandon non-standard syntaxes. For this and other reasons I wrote up #2259.

**Comment by jeddy3** [comment]
> I don't think we should deprecate these rules until we're ready to funnel users directly into a css-values or csstree plugin. I don't think those libraries are, will be, or should be non-standard syntax friendly; so I think we should only deprecate these rules as part of a plan to more or less abandon non-standard syntaxes. 

Agreed.

Do we revert the deprecations of the following (done in https://github.com/stylelint/stylelint/pull/2197)?:

- `media-feature-no-missing-punctuation`
- `selector-no-empty`

Or is `selector-no-empty` still an odd proxy and `media-feature-no-missing-punctuation` still too problematic?

**Comment by davidtheclark** [comment]
I don't thin we should revert those deprecations — I think the justifications for those still stands.

**Comment by jeddy3** [comment]
Agreed. I think we can close this now.
