### ISSUE TITLE
Drop Babel

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2133]
I'm convinced that one of the best things we can do for the overall health and efficiency of this project is to drop Babel. Here are some of the benefits:

- Faster tests, no matter what runner we use
- No polyfill-vs-native confusion
- Fewer dependencies = smaller package, more efficient development & CI
- Faster installation
- Easier debugging for users & devs
- Faster runtime performance

The only non-trivial downside I can think of is that we would not have Flow. But I think we could try to work out something fast and relatively simple with [flow-remove-types](https://github.com/leebyron/flow-remove-types).

Unfortunately, I don't know of a way to drop  Babel more conveniently than manually rewriting ... soooo much. 

I have a couple more experiments in mind to try, but here's the big question: Do others in @stylelint/core think the benefits above would be worth some concerted effort to rewrite code and drop Babel? If it came to manual review of all our files, would others be willing to pitch in on that effort — or do you think it's not worthwhile?

**Comment by davidtheclark** [comment]
FYI: I'm well on my way to making this happen ...

**Comment by evilebottnawi** [comment]
@davidtheclark :+1:

**Comment by nkabardin** [comment]
There are many good things about this idea, and whether will be decided, I'm up for helping with that.

**Comment by evilebottnawi** [comment]
@davidtheclark Perhaps for greater opportunities and less rewriting code should wait for the official dropping `node v4`. If I'm not mistaken it will happen in April next year.

**Comment by m-allanson** [comment]
@evilebottnawi 'Active' support ends in April 2017, 'Maintenance' support in April 2018. I agree it could help reduce the work involved, but it depends on how aggressive stylelint can be in dropping support for older versions of Node.

- [Node LTS schedule](https://github.com/nodejs/LTS)
- [Node ES6 compatibility table](http://node.green/)

**Comment by evilebottnawi** [comment]
@m-allanson In theory you could write a recipe on how to run `stylelint` on `node v4` (maybe throw babel) and exclude `node v4` from our code base

**Comment by TrySound** [comment]
@evilebottnawi Bad UX. People will hate stylelint

**Comment by evilebottnawi** [comment]
@TrySound we can create hook in `npm` `script` section and do it automatically on `node v4`

**Comment by davidtheclark** [comment]
Already made it compatible with Node 4 in https://github.com/stylelint/stylelint/pull/2134. If you'd like to help with this, I'll try to make a list of things to do in that PR.

**Comment by davidtheclark** [comment]
Closed by #2134.
