### ISSUE TITLE
Add system tests for CLI

### ISSUE THREAD

**Issue by nkabardin** [stylelint/stylelint#2142]
After working on https://github.com/stylelint/stylelint/issues/2115 I realized that there are no tests for `cli`.

One system test added [here](https://github.com/stylelint/stylelint/pull/2140/files) to check that cli returns proper exit code, but it's only one case and all other cases should be checked as well.

It should be system tests, but I don't think it's a good idea to just number them the way previous sys tests were numbered. I would rather create a subfolder `/system-tests/cli` for that, what do you think?

Things that needs to be tested:

* That cli prints linting results
* That cli understands and loads configuration (different types) correctly
* That cli returns exit code 0 if everything is correct, and only in this case

**Comment by davidtheclark** [comment]
Thanks @nkabardin! #2046 already exists but only addresses unit tests, I think. So I changed this issue title to reflect its focus on system tests.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2903
