### ISSUE TITLE
Ignoring node_modules when using the PostCSS API

### ISSUE THREAD

**Issue by simonsmith** [stylelint/stylelint#2149]
Hello,

We're using stylelint in the SUIT CSS preprocessor and one issue we have is around [ignoring imports](https://github.com/suitcss/preprocessor/issues/58) that are located in `node_modules`. We're using it like so:

```js
  var processor = postcss();
  if (options.lint) {
    processor.use(stylelint(options.stylelint));
  }
```

From looking round the source I can see the Node API uses globs with a `alwaysIgnoredGlobs` containing `node_modules` but it looks like the PostCSS goes around this check via `lintSource`. I only looked briefly so do correct me if I'm wildly inaccurate :)

Just wondering if `alwaysIgnoredGlobs` should be respected when using stylelint this way?

I can put together an example of the issue if that helps further

Thanks

**Comment by jeddy3** [comment]
> I can put together an example of the issue if that helps further

Any help resolving this more quickly is appreciated @simonsmith as we're pretty stack at the moment with some refactoring and test infrastructure changes.
