### ISSUE TITLE
New rule: media-feature-name-no-vendor-prefix

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#216]
I'm pretty sure that the only vendor prefixes involved here are the ones for resolution. Does anybody disagree? @ai do you know of any others?

If I'm right about that, I'm thinkin the easiest way to handle this rule would just be to look for a specific, small set of strings, instead of trying to mess with the Autoprefixer API.

**Comment by ai** [comment]
I can't remember any other prefixes in media queries. But @yisibl should know better.

**Comment by jeddy3** [comment]
> If I'm right about that, I'm thinkin the easiest way to handle this rule would just be to look for a specific, small set of strings, instead of trying to mess with the Autoprefixer API.

SGTM if resolution are the only ones.
