### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2164]
Via https://travis-ci.org/stylelint/stylelint/jobs/181025542

```shell
...
 PASS  lib/utils/__tests__/report.test.js
(node:2404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: expect(received).toBeTruthy()
Expected value to be truthy, instead received
  false
(node:2404) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  lib/utils/__tests__/isStandardSyntaxRule.test.js
...
```

**Comment by davidtheclark** [comment]
I'm not able to reproduce this locally. Could someone on Node 7 give this a shot?

**Comment by davidtheclark** [comment]
Hm, when we get these tests actually running on Travis, the same error occurs on Node 6 — not seeing on 4. Aha, and I can reproduce that locally. Will investigate.

**Comment by davidtheclark** [comment]
Found the cause for this. There was some buggy promise handling in a few Jest util tests. Will fix.

Worth noting — I didn't know about this until exploring this issue — you can add a listener for unhandled promise rejections and get a better stack trace:

```js
process.on("unhandledRejection", (reason) => {
  console.log(reason)
})
```

**Comment by ntwb** [comment]
Woot 🎉
