### ISSUE TITLE
We are leaking memory

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2168]
Somehow we are leaking memory. I think this is causing the problems that we reported to Jest in https://github.com/facebook/jest/issues/2179.

I think the cause is within the stylelint code, not the Jest test runner, because when I run thousands of Jest tests *without* requiring stylelint, the heap does not grow indefinitely the way it does when I *do* require stylelint.

All it takes to make the heap grow indefinitely is to `require` stylelint from the `jest-setup` file. (If I `require` other libraries, I don't see this happening.)

I don't really know how to debug this, so all help appreciated! I will keep poking around for a little while today.

**Comment by davidtheclark** [comment]
I think I identified one issue, by a process of commenting in-and-out certain `require()` statements: `graceful-fs` in `cosmiconfig` seems to be leaking memory. If I replace that with `fs`, my dummy Jest tests, which use our `jest-setup.js` so require stylelint but *do not run `testRule`*, do not leak memory! However, I'm still seeing a memory leak when I run this modified `cosmiconfig` in actual stylelint tests ...

**Comment by davidtheclark** [comment]
Oh, good news again: I'm not actually seeing leaky memory with the modified `cosmiconfig`. I'm seeing the heap grow, but then it consistently cuts back, instead of accumulating indefinitely. Continuing to investigate ...

**Comment by jeddy3** [comment]
> I don't really know how to debug this, so all help appreciated! 

This is likely new territory for a lot of us!

> Oh, good news again: I'm not actually seeing leaky memory with the modified cosmiconfig. 

Excellent news! Just out of curiosity, what tool are you using to see the heap grow? Is the v8-profiler mentioned in https://github.com/facebook/jest/issues/2179#issuecomment-264661386?

**Comment by davidtheclark** [comment]
@jeddy3 No, I tried that but the snapshots were overwhelming, and I could not find a tutorial that really helped. The tutorials I did find dealt with many, many fewer allocations, so their heuristics for finding leaks just didn't help me. Instead, I'm just Jest with `--logHeapUsage` and seeing how the usage stats change when I make changes to files.

**Comment by jeddy3** [comment]
> and I could not find a tutorial that really helped

Yep, I'm in a similar boat. It's fantastic that you're making progress with `--logHeapUsage` though!

**Comment by davidtheclark** [comment]
I think I tracked down the problem, and just filed an issue with graceful-fs: https://github.com/isaacs/node-graceful-fs/issues/102

If I can get the Travis tests for PR #2158 to pass using `fs` in `cosmiconfig`, I will cut a new release of `cosmiconfig`, include that in the PR, then merge it.

**Comment by davidtheclark** [comment]
Closed by #2158.
