### ISSUE TITLE
Custom rules overrides extended config

### ISSUE THREAD

**Issue by hinok** [stylelint/stylelint#2170]
**Here is repository that reproduce bug described below**
https://github.com/hinok/stylelint-sass-css-modules

I've found the same problem described in another repository
https://github.com/kristerkari/stylelint-scss/issues/86

> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug when you extends a config and try to define custom rules.

> Which rule, if any, is this issue related to?

```
selector-pseudo-class-no-unknown - ignorePseudoClasses
property-no-unknown - ignoreProperties
at-rule-no-unknown - ignoreAtRules
```

> What CSS is needed to reproduce this issue?

I prepared a repository that represents this bug https://github.com/hinok/stylelint-sass-css-modules

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "selector-pseudo-class-no-unknown": [true, {
      "ignorePseudoClasses": [
        "export",
        "import",
        "global",
        "local",
      ]
    }],
    "property-no-unknown": [true, {
      "ignoreProperties": [
        "composes",
      ]
    }],
    "at-rule-no-unknown": [true, {
      "ignoreAtRules": [
        "value",
      ]
    }]
  }
}
```

> Which version of stylelint are you using?

`7.6.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint *.scss --syntax scss`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

Rules defined by extended configuration should be merged with my custom rules.

> What actually happened (e.g. what warnings or errors you are getting)?

My custom rules overrides rules from extended config.

**Comment by davidtheclark** [comment]
@hinok Thanks for opening this. After looking into the linked issue, I realized that there's probably a good solution for stylelint-scss, and [I wrote about it over there](https://github.com/kristerkari/stylelint-scss/issues/86#issuecomment-264737962). Will that solution work for you?

> My custom rules overrides rules from extended config.

I don't understand what this means. In the repo you linked to, I do not see any "custom rules". You are in fact overriding `stylelint-config-standard`.

**Comment by hinok** [comment]
> My custom rules overrides rules from extended config.

Frankly I've thought that it works more like eslint where all rules from

```
"rules": { ... }
```

are merged into configuration defined in

```
"extends": { ... }
```

So if I have defined confiruation like

```
{
  "extends": "stylelint-config-standard"
}
```

and it works with `scss` syntax without any problems so adding new "custom rules" to the `"rules": { ... }` just extends configration not overrides it. So my understanding is that it should still work with `scss` syntax but with new rules like:

```
"rules": {
    "selector-pseudo-class-no-unknown": [true, {
      "ignorePseudoClasses": [
        "export",
        "import",
        "global",
        "local",
      ]
    }],
    "property-no-unknown": [true, {
      "ignoreProperties": [
        "composes",
      ]
    }],
    "at-rule-no-unknown": [true, {
      "ignoreAtRules": [
        "value",
      ]
    }]
  }
```

At the moment it doesn't work like that because I have to redefine `ignoreAtRules` for scss.

PS. I'm not using `stylelint-scss`.

**Comment by jeddy3** [comment]
I'm afraid I'm not understanding your request. Hopefully we can get to the bottom of it though.

>> What actually happened (e.g. what warnings or errors you are getting)?

> My custom rules overrides rules from extended config.

_Overriding_ rules (rather than _merging_ them) is the intended and [documented](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) behaviour. Merging rules (and their options) isn't a viable for the reason outlined in https://github.com/stylelint/stylelint/issues/1646#issuecomment-232779957.

@hinok Does that answer your query?

**Comment by hinok** [comment]
@jeddy3 Aaaaaaaaa got it, #1646 clarifies everything. I'm closing the issue.
What do you think - maybe it's worth to write something about it in README or in guidelines?

**Comment by ntwb** [comment]
> maybe it's worth to write something about it in README or in guidelines?

Yes, for sure, if something isn't clear no doubt I'd expect someone else to get caught out by the same thing in the future. @hinok would you like to open a new pull request for that?

**Comment by hinok** [comment]
@ntwb I will add PR today evening ;)

**Comment by jeddy3** [comment]
> I will add PR today evening ;)

Excellent, thanks. I think adding an FAQ entry will be enough as the actual [`extends` configuration docs within the user guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) mentioned _overrides_ about six times already. 

Perhaps:

### If I extend a configuration, will the options for each rule be merged or overridden?

...

**Comment by hinok** [comment]
@jeddy3 https://github.com/stylelint/stylelint/pull/2178
