### ISSUE TITLE
Expose available formatters in the Node API

### ISSUE THREAD

**Issue by jwilsson** [stylelint/stylelint#2181]
*The template didn't really make sense for this so I skipped it. Hope that's OK.*

Some background: When running the [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) with current `stylelint` `master` it crashes since it tries to load `stylelint/dist/formatters` which doesn't exist anymore. 

Now, what I'd like to propose is a `formatters` property to be exposed on the main `stylelint` Node API object, just like `rules` already is. This would allow plugins and other tools to always get a list of all available formatters without worrying about things moving around (like it just did) and it would be nice to have a proper, documented API for it.

I'd be happy to create a PR for this if accepted and I'll file a corresponding issue on `gulp-stylelint` as well.

**Comment by evilebottnawi** [comment]
@jwilsson thanks for helping, be good if you format issue as template :+1:

**Comment by jeddy3** [comment]
> The template didn't really make sense for this so I skipped it. Hope that's OK.

👍 

> Now, what I'd like to propose is a formatters property to be exposed on the main stylelint Node API object, just like rules already is.

Sounds like a good proposal to me.

> I'd be happy to create a PR for this if accepted and I'll file a corresponding issue on gulp-stylelint as well.

That's fantastic. Thanks for offering to help out. 

Let's wait for the rest of team to add their thoughts.

**Comment by davidtheclark** [comment]
Yep, @jwilsson sounds great!

**Comment by jeddy3** [comment]
@jwilsson Feel free to jump on this on now. Thanks again for offering to help out again. I think we were using jest for just _some_ tests around the time of your [last PR](https://github.com/stylelint/stylelint/pull/2121). Since then we've migrated everything over, and so hopefully the testing experience is now more familiar :)

**Comment by jwilsson** [comment]
Thanks guys!

I'll take a look over the weekend.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2190
