### ISSUE TITLE
Only pass processor functions absolute filepaths

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2195]
I ran into a situation where the `code` processor function's filepath argument was relative, but the `result` processor function's argument was absolute. This makes it hard to associate input and output in the processor code.

We should provide an absolute path to both. We should also document this.

**Comment by kriansa** [comment]
To help debugging, the scenario I ran into was the following:

1. Have `stylelint` installed via `package.json`
2. Have your processors listed on `.stylelintrc.yml`
3. Run it via `node_modules/.bin/stylelint "*.css"`

**Comment by davidtheclark** [comment]
I am working on this in spare time, hope to get a PR in this week.
