### ISSUE TITLE
Ignore certain rules

### ISSUE THREAD

**Issue by AntonNiklasson** [stylelint/stylelint#2216]
My `.stylelintrc` looks like this:

```
{
	"extends": "stylelint-config-standard",
	"rules": {
		"indentation": "tab",
		"color-hex-case": "upper",
		"at-rule-empty-line-before": "always",
		"shorthand-property-no-redundant-values": false
	}
}
```

Is there a way for me to ignore rules that are defined in `stylelint-config-standard`? Looking at this documentation: [at-rule-empty-line-before](http://stylelint.io/user-guide/rules/at-rule-empty-line-before/) I expected there to be something like `ignore` available as an option.

**Comment by m-allanson** [comment]
Use `null`. http://stylelint.io/user-guide/faq/#how-do-i-disable-a-rule
