### ISSUE TITLE
No npm home page defined

### ISSUE THREAD

**Issue by rstacruz** [stylelint/stylelint#2223]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

There's no home page defined in package.json, so npmjs.com defaults to the GitHub repo:

![image](https://cloud.githubusercontent.com/assets/74385/21576505/a18de638-cf6d-11e6-8b91-6506cac49003.png)

> Which rule, if any, is this issue related to?

None.

> What CSS is needed to reproduce this issue?

None; just visit https://www.npmjs.com/package/stylelint.

> What stylelint configuration is needed to reproduce this issue?

None.

> Which version of stylelint are you using?

`7.7.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

All :)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

I expect it to link to http://stylelint.io.

> What actually happened (e.g. what warnings or errors you are getting)?

It links to https://github.com/stylelint/stylelint.

**Comment by ntwb** [comment]
Thanks for creating this issue and follow up pull request and using our templates @rstacruz 👍 

This sounds good to me, we can examine our site stats in a months time and see if there was any impact.

**Comment by rstacruz** [comment]
> we can examine our site stats in a months time

Is this when the new version is scheduled to be released? (package.json changes will need to be `npm publish`ed in a new version.)

**Comment by ntwb** [comment]
There will be a minor release in the next few days, if this is merged and released as part of that then that will occur as part of the publishing the release.

The stats side of things, we have Google Analytics wired up to stylelint.io, so it will be interesting to examine the stats in a months time to see any impact, for better or worse :)

**Comment by jeddy3** [comment]
> Is this when the new version is scheduled to be released?

I'm on the train at the moment but I reckon I'll have time to put out [our pending](https://github.com/stylelint/stylelint/issues/2218) patch before heading out tonight (Happy New Years everyone btw! 🎉 ). 

This release will include this `package.json` change, so we'll be able to check on the stats at the end of Jan.

Closed by https://github.com/stylelint/stylelint/pull/2224
