### ISSUE TITLE
Deprecate root rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2226]
Continuing to split https://github.com/stylelint/stylelint/issues/2079 into separate issues. 

Next up:

- `custom-property-no-outside-root`
- `root-no-standard-properties`
- `selector-root-no-composition`

These three rules have been in since the very beginning. I think it's clear _what_ they do, but I've never really been sure _why_ they would be used.

Am I right in thinking that `custom-property-no-outside-root` is to ensure compatibility with the following limitation of [`postcss-custom-properties`](https://github.com/postcss/postcss-custom-properties#postcss-custom-properties-)?: 

"It currently just aims to provide a future-proof way of using a **limited subset (to :root selector)** of the features provided by native CSS custom properties."

Having custom properties outside of `:root` is [valid](https://drafts.csswg.org/css-variables/#syntax) and a proper use case: 

"Custom properties are ordinary properties, so they can be declared on any element..."

So, in this instance, it looks like we have a rule in core to workaround a limitation of a PostCSS transformation plugin. As full support for custom properties continues to be adopted by browsers, this rule feels like it should be a plugin.

I'm also struggling to find anything in the spec about disallowing composition of the `:root` selector, nor any issue with having standard properties within the `:root` declaration block. The spec simply [says](https://drafts.csswg.org/selectors-4/#the-root-pseudo) that `:root` represents the element that is the root of the document e.g. `html`.

I'd really appreciate someone shedding some light on these three rules.

**Comment by davidtheclark** [comment]
These rules are not to disallow invalid code, but to enforce certain patterns. These rules were [adapted from postcss-bem-linter](https://github.com/postcss/postcss-bem-linter/issues/56). So at the time, at least, SUIT CSS users were interested in them.  I'm not sure if this was only a workaround for the PostCSS plugin or if it was also considered useful. One goal could be to place restrictions on root `:root` and on custom properties, so `:root` alone is the site for declarations of custom properties.

**Comment by jeddy3** [comment]
Thanks. That sheds some light on their origins.

> One goal could be to place restrictions on root `:root` and on custom properties, so `:root` alone is the site for declarations of custom properties.

That makes sense. I guess it now becomes a question of whether these patterns are idiosyncratic or not.

@simonsmith I hope you don't mind me mentioned you, but we're doing an audit of stylelint's rules in preparation for `8.0.0`. There are three rules we're trying to understand:

- [`custom-property-no-outside-root`](https://github.com/stylelint/stylelint/blob/master/lib/rules/custom-property-no-outside-root/README.md)
- [`root-no-standard-properties`](https://github.com/stylelint/stylelint/blob/master/lib/rules/root-no-standard-properties/README.md)
- [`selector-root-no-composition`](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-root-no-composition)

Are you able to shed any light on _why_ these rules might be used within a SUITCSS context?

**Comment by simonsmith** [comment]
@jeddy3 Hey,

I think these rules are mainly to work around the limitations imposed by replicating `root` with a preprocessor but also to ensure styles don't leak out into other components.

**`custom-property-no-outside-root`**: I think this works around the `postcss-custom-properties` limitation that you pointed out already.

**`root-no-standard-properties`**: By forcing use of root it means that all components have to share that global space. If they all set `color` then it would clash. Instead things like `--Component-color` ensures they don't interfere with each other.

**`selector-root-no-composition`**: I'm not too sure on this one. It dates back to when [rework was used for linting](https://github.com/suitcss/rework-suit-conformance). I would assume it ties in with the limitation of replicating custom properties without a DOM.

Interestingly `custom-property-no-outside-root` is not used in the `stylelint-config-suitcss` package.

Out of interest here's what GitHub search yields (under the code tab):

`root-no-standard-properties`: 760
`selector-root-no-composition`: 816
`root-no-standard-properties`: 578

I'm happy to have them moved into a plugin if you'd prefer to remove them from the core.

**Comment by jeddy3** [comment]
@simonsmith Thanks for replying! That continues to shed some more light on things.

> if you'd prefer to remove them from the core.

I think so. They feel quite idiosyncratic and I think better suited as plugins. @stylelint/core Any objections?

**Comment by davidtheclark** [comment]
Sure

**Comment by jeddy3** [comment]
Tracking in https://github.com/stylelint/stylelint/issues/2123

**Comment by simonsmith** [comment]
Where will these rules be moved to? A new `npm` package?

**Comment by jeddy3** [comment]
They'll be deprecated in an upcoming release. The deprecation warning will have a link to http://stylelint.io/user-guide/release-planning/ which will (once [this PR](https://github.com/stylelint/stylelint/pull/2250) is in) ask for the community's help. 

The community will then have time, and if there is the desire, to convert these rules to plugins before they are removed outright in `8.0.0`. We took the [same approach](http://stylelint.io/user-guide/release-planning/#700) with `7.0.0` and it worked well.

More background about this can be found in https://github.com/stylelint/stylelint/issues/2079. In short, it's to keep development of stylelint sustainable by creating and sticking to [a set of criteria](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#criteria-for-inclusion) around what should be a rule and what should be a plugin.

**Comment by simonsmith** [comment]
I see.

Well there is desire to continue using this rules in SUIT CSS. Perhaps when you get round to removing the root ones I could put together a `root` rules plugin.

**Comment by jeddy3** [comment]
> Perhaps when you get round to removing the root ones I could put together a root rules plugin.

That would be super.

> and if there is the desire...

I should have been a bit clearer :) I meant that in the context of browser support for custom properties being [on the horizon](http://caniuse.com/#feat=css-variables), which might make preprocessing the custom properties with SuitCSS unnecessary and, perhaps, these rules redundant. This might not be the case, though. I guess it depends on how things like theming might work when browsers support custom properties.

**Comment by simonsmith** [comment]
I expect IE will hold it back for some :)

But yes, would be ideal to not need them at all!
