### ISSUE TITLE
Is /* stylelint-disable */ working when used in a plugin?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#223]
Flagged in https://github.com/stylelint/stylelint/issues/15#issuecomment-114255674

I also tried:

```css
* stylelint-disable rule-properties-order */`
a { }
```

Both via node API and via gulp, with no dice. Have I got the syntax right?

**Comment by davidtheclark** [comment]
I thought it was working but I guess I was wrong. Will look into it.

**Comment by jeddy3** [comment]
Fixed in #225
