### ISSUE TITLE
Rename ignore: ["at-rules-without-declaration-blocks"] to ["blockless-at-rules"] in max-nesting-depth 

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2231]
https://github.com/stylelint/stylelint/issues/2229 makes me think it's worth being very explicit in our option names. Here we have a rule that targets (nested) rules and might have options that target rules _and at-rules_.

In https://github.com/stylelint/stylelint/pull/2225  I think we're being a bit implicit with the naming of the option `"after-same-name"`.  I think we should be more explicit i.e.:

- `"after-same-name"` becomes `"after-same-name-at-rule"`

In the [deprecations branch](https://github.com/stylelint/stylelint/tree/deprecations/lib/rules/at-rule-empty-line-before#except-inside-block-blockless-after-same-name-blockless-blockless-after-blockless-after-opening-brace) we have `blockless-after-same-name-blockless"` and `"blockless-after-blockless"`. I think we should be more explicit i.e.:

- `"blockless-after-blockless"` becomes `"blockless-at-rule-after-blockless-at-rule"`
- `blockless-after-same-name-blockless"` becomes `blockless-at-rule-after-same-name-blockless-at-rule"`

It's a bit more verbose, but it means that constructs are consistently named across rules and their options e.g. `rule-nested-empty-line-before` has the option `"after-rule"` and, if added, will have the option `"after-at-rule"`.

Lastly, there's an opportunity to standardise on the "blockless-at-rule" name in `max-nesting-depth`:

- [`ignore: ["at-rules-without-declaration-blocks"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/max-nesting-depth/README.md#ignore-at-rules-without-declaration-blocks) becomes `ignore: ["blockless-at-rules"]`.

Thoughts?

**Comment by hudochenkov** [comment]
I think it's unnecessary explicitness, because “scope” of rule and options had already defined in the first part of rule's name.

> `"after-same-name"` becomes `"after-same-name-at-rule"`

There can't be `"after-same-name-custom-property"` or `"after-same-name-declaration"`. Unneeded verbosity.

**Comment by jeddy3** [comment]
> I think this is fine, but let's make sure we have a complete sweep before we release such deprecations & changes, and only do it once.

Agreed.

> They are really only for the benefit of stylelint developers, to avoid confusion and occasional missteps when creating option names — though this hasn't really been a problem in the past, I think

I tend to spend quite a bit of time refamiliarizing myself with all the options when a new one is proposed to ensure it's consistent. Anything to reduce that burden would be helpful.

> I think it's unnecessary explicitness, because “scope” of rule and options had already defined in the first part of rule's name.

Agreed. 

Let's just rename `max-nesting-depth`'s `ignore: ["at-rules-without-declaration-blocks"]` as that's a useful rename to help keep things consistent going forward.

**Comment by davidtheclark** [comment]
Closed by #2275.
