### ISSUE TITLE
Shortcut to format style?

### ISSUE THREAD

**Issue by R083RT2** [stylelint/stylelint#2233]
I was able to create .stylelintrc file and place it in project directory.  The linter highlights errors but not sure how to have it actually apply style/formatting to CSS files.  Didn't see a shortcut for this, is there any?

**Comment by jeddy3** [comment]
[FAQ entry](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-automatically-fix-stylistic-warnings) - use the `stylefmt` tool.
