### ISSUE TITLE
Standardise checks for ignore/except "after-declaration" in declaration-empty-line-before

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2239]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

[`except: ["after-declaration"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-empty-line-before/index.js#L106-L115) checks previous node more accurately than [`ignore: ["after-declaration"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-empty-line-before/index.js#L68-L75). I think `ignore` should check same as `except`.

> Which rule, if any, is this issue related to?

`declaration-empty-line-before`

> Which version of stylelint are you using?

`7.7.1`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

**Comment by jeddy3** [comment]
@hudochenkov Again, thanks for giving the `*-empty-line-before` rules the once over.

> I think `ignore` should check same as `except`

Agreed.

I also think there's an opportunity to extract these conditionals into utililities e.g. `isAfterDeclaration`, `isAfterCustomProperty` etc.

**Comment by davidtheclark** [comment]
Fixed by #2262.
