### ISSUE TITLE
Standardise checks for ignore/except "blockless-group" in at-rule-empty-line-before

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2240]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

[`except: ["blockless-group"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/at-rule-empty-line-before/index.js#L107-L108) checks previous node more accurately than [`ignore: ["blockless-group"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/at-rule-empty-line-before/index.js#L62-L63). I think `ignore` should check same as `except`.

> Which rule, if any, is this issue related to?

`at-rule-empty-line-before`

> Which version of stylelint are you using?

`7.7.1`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

**Comment by jeddy3** [comment]
>  I think ignore should check same as except.

Agreed.

**Comment by davidtheclark** [comment]
Fixed by #2262.
