### ISSUE TITLE
enable all option?

### ISSUE THREAD

**Issue by mockdeep** [stylelint/stylelint#2241]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

It looks like there are no default settings, but one nice option in eslint is the [`eslint:all`](http://eslint.org/docs/user-guide/configuring#using-eslintall) configuration which, like it says, enables all eslint rules. My workflow generally centers around wanting to have all rules enabled and selectively disabling or configuring them to my liking, rather than needing to hunt through the docs for rules that I might like to add.

> Which rule, if any, is this issue related to?

All of them.

**Comment by jeddy3** [comment]
@mockdeep Thanks for the request.

In stylelint [rules are turned on](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#rules) by specifying a _primary option_. There are no default primary options. As such, we supply an [example config](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/example-config.md) that turns on all the boolean rules and lists primary options for each of the non-boolean ones. 

Alternatively, there is [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) which specifies primary options for around 80 of stylelint's rules. It then [provides a list](https://github.com/stylelint/stylelint-config-standard#suggested-additions) of the rule _not used_, so hunting for additional rules is kept to a minimum.

**Comment by jcastrov** [comment]
If you need a quick configuration file with all rules enabled, I created a [gist](https://gist.github.com/jcastrov/6e519be0b085b295f96ba359833787c3). Keep in mind that some no-boolean values are of my own preference (i.e. `function-max-empty-lines`, `indentation`...)
