### ISSUE TITLE
Does styleline support vendor prefix alignment

### ISSUE THREAD

**Issue by lcxfs1991** [stylelint/stylelint#2247]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Maybe a new feature

> indentation

Align these rules with colon `:` will be better.

e.g.

```css
-webkit-transform: translate(-50%, -50%);
             transform: translate(-50%, -50%);
```

**Comment by jeddy3** [comment]
@lcxfs1991 Thanks for the request.

This is quite a specific use case and would, therefore, be a great candidate for a plugin. There is [guide to writing your own plugins](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) within the docs.

FYI, if you use [autoprefixer](https://github.com/postcss/autoprefixer) it's unlikely you'll encounter this pattern in your _source code_.

Ref: https://github.com/stylelint/stylelint/issues/769

**Comment by laukstein** [comment]
@jeddy3 why not to include this in stylelint core? Many already asked about this/similar rule. I'm for it too.

**Comment by laukstein** [comment]
@jeddy3 @lcxfs1991
Any progress (plugin?) for **prefix indentation**?

```
.selector {
    -webkit-user-select: text;
       -moz-user-select: text;
        -ms-user-select: text;
            user-select: text;
}
```
