### ISSUE TITLE
Stylelint doesn't pick up errors when using a star (*) glob pattern

### ISSUE THREAD

**Issue by Pustur** [stylelint/stylelint#2253]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug (i think?) where using a star glob pattern (`*`) doesn't pick up errors in my files.

> Which version of stylelint are you using?

`7.7.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Using Node:  
`node_modules/stylelint/bin/stylelint.js ./src/**/*.css`
`node_modules/stylelint/bin/stylelint.js ./src/**/_typography.css`

the former **doesn't give any output**.
the latter works and gives:
```
src/css/3-base/_typography.css
 38:4  ✖  Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation
```

> What did you expect to happen?

The linter should have picked up the same file (`_typography.css`) even when using the `*` glob pattern.

**Comment by davidtheclark** [comment]
@Pustur What platform are you on, and what happens if you wrap your glob in quotation marks?

**Comment by Pustur** [comment]
@davidtheclark: I tried with the quotation marks and it worked! Thanks!

BTW i'm using
- macOS `10.12.2`
- Node `7.2.0`
