### ISSUE TITLE
Remove ESLint rule for multi-item array bracket spacing

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2260]
Right now we are forced to do `[a]` but `[ a, b ]`. This means we sometimes have to change the spacing around the brackets when we add or remove items from the array — and that is annoying. We should remove this distinction, and stick with no spaces in array brackets always. Hopefully this is automatically fixable.

**Comment by jeddy3** [comment]
SGTM. Tracking in https://github.com/stylelint/eslint-config-stylelint/issues/17
