### ISSUE TITLE
`src/**/*.scss` pattern not matching files in base folder

### ISSUE THREAD

**Issue by sinedied** [stylelint/stylelint#2267]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I have a bug: when I run the command `stylelint src/**/*.scss --syntax scss`, all files located directly in the `src` folder are not processed, as opposed to what's written in the docs.

> Which rule, if any, is this issue related to?

It's related to the CLI not a specific rule

> What CSS is needed to reproduce this issue?

No specific css needs

> What stylelint configuration is needed to reproduce this issue?

No specific conf needed

> Which version of stylelint are you using?

`7.7.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint src/**/*.scss --syntax scss`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes it targets SCSS files

> What did you expect to happen?

All SCSS files contained in `src` folder and subfolders are processed

> What actually happened (e.g. what warnings or errors you are getting)?

Only files in `src` subfolders are processed

**Comment by evilebottnawi** [comment]
@sinedied what shell are use? try `stylelint 'src/**/*.scss' --syntax scss` (with quote)

**Comment by sinedied** [comment]
@evilebottnawi Thanks, it works with quotes I'm silly to have forgotten that! I'm using the OSX standard shell for the record.
