### ISSUE TITLE
Log message is inconsistently formatted for rule no-multiple-empty-lines 

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#227]
It looks like the output from rule `no-multiple-empty-lines` is not formatted the same way as for other rules.  

The rule output looks like this:

`Unexpected empty line at line 18 (no-multiple-empty-lines)`

All the other rules seem to format their output like this:

`49:5	Expected double quotes around url argument (function-url-quotes)`

Is this expected behaviour?

**Comment by davidtheclark** [comment]
Yeah. The reason for that is tied up with #133. PostCSS warnings are attached to nodes, and right now it's the beginning of those nodes that determines the line and column number. But this rule (and some other) actually runs through the whole document so the warning is attached to the root node, which does not get a line and column number (and if it did, they would be `1:1`). So I'm manually checking line number and adding it to the message. Hopefully this will be more consistent when #133 is taken care of.

**Comment by m-allanson** [comment]
Ok that makes sense, thanks.
