### ISSUE TITLE
Implement caching to improve performance

### ISSUE THREAD

**Issue by sergesemashko** [stylelint/stylelint#2270]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request.

I have a project with > 100 .scss files with setup of webpack and stylelint using [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin). Introducing stylelint made builds slower:
```
webpack built 17bce08fdf4ec045935d in 9317ms
```
Initially, I thought that webpack plugin is the source of slowness. But profiling of `./lib/standalone.js` showed that it just takes time to lint the entire style folder:
```
Stylelint time: 6168.771ms
```
I tried to lint only changed files while in development mode and linting time went down to ~100ms (max `170.055ms`). 

I'd like to suggest implementing sort of "good file" caching and lint only failed + changed files. We could borrow caching solution from eslint ([Implement cache in order to only operate on changed files since previous run.](https://github.com/eslint/eslint/pull/3597)). 

In short, they cache files metadata for passed files and exclude them from subsequent lint runs. Cache is persisted to `./node_modules/.eslintcache` by default.

Also, we could learn from the issues they had with cache and avoid them:
- [Do not implicitly cache `package.json`](https://github.com/eslint/eslint/pull/4610)
- [Delete cache only when executing on files](https://github.com/eslint/eslint/pull/6540)
- [Cache is basically not working](https://github.com/eslint/eslint/pull/4019/files)
- [Do not cache `.eslintrc.js`](https://github.com/eslint/eslint/pull/5068)

> What stylelint configuration is needed to reproduce this issue?

Stylelint nodejs api options:

```js
{ 
  formatter: require('stylelint').formatters.string,
  configFile: '.stylelintrc',
  files: [ './src/sass/**/*.s?(c|a)ss' ]
 }
```

.stylelintrc:
```json
{
  "extends": "stylelint-config-standard",
    "rules": {
      "at-rule-no-vendor-prefix": true,
      "color-named": "always-where-possible",
      "media-feature-name-no-vendor-prefix": true,
      "property-no-vendor-prefix": true,
      "selector-no-vendor-prefix": true,
      "selector-no-universal": true,
      "value-no-vendor-prefix": true
    }
}
```

> Which version of stylelint are you using?

`7.7.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API using [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin)

**Comment by davidtheclark** [comment]
When I first read this I wondered why I've never seen my successive ESLint runs go faster — now I see I have to try the `--cache` flag. I'll give it a shot!

@sergesemashko I'm in favor of experimenting with this idea if you'd like to lead the charge. 

@stylelint/core any concerns?

**Comment by sergesemashko** [comment]
@davidtheclark, sure! I'll take a look at this. I'll reach you back when I have any results.

**Comment by jeddy3** [comment]
> @stylelint/core any concerns?

None, as, thanks to @sergesemashko, we've got some great references for lessons learnt in eslint with they implemented the same feature.  

It sounds like a great initiative to me.

**Comment by ntwb** [comment]
Great idea, not that I've looked (on my todo list) but Jest also supports caching

**Comment by sergesemashko** [comment]
I'm  currently working on it and going to submit a PR soon for initial feedback. @jeddy3, @davidtheclark, you can assign the issue to me

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/issues/2293
