### ISSUE TITLE
Call for maintainers dedicated to non-standard syntaxes (SCSS, Less, etc.)!

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2274]
This is a follow-up to #2259. The goal is to bring on more non-standard syntax devotees interested in fixing bugs and refining the tool for their pipeline.

I myself don't use SCSS or Less and probably will not spend any more of my open-source time fixing the bugs that arise for these syntaxes, or coming up with new features that might improve the experience with these syntaxes. The best people to do that kind of work are *actual users of the non-standard syntaxes*.

The more people involved in stylelint, the better it will be. So we'd love your help!

I sent out a plea on Twitter and the following noble souls responded:

- @iamyamakin
- @maraisr
- @sashasushko
- @PhilippeVay

Are you all still interested in spending some time improving stylelint — especially for the syntaxes you use (which do each of you use?)?

If anybody wants to be included as a member of the core team, I'm happy to add you! You don't have to have any mastery of the codebase, just a willingness to spend some time working on issues.

**Comment by evilebottnawi** [comment]
@davidtheclark i have good knowledge about SCSS and Less, most issue with non standard syntax I covered earlier :smile: , can review PR, and of course fix bugs :smile:

**Comment by iamyamakin** [comment]
@davidtheclark yes, i'm still interested. I have experience in Less, Scss, Stylus. I prefer improving Less, because it's used on the project.

**Comment by hudochenkov** [comment]
I'm using bunch of PostCSS plugins, which introduce non-standard syntax. But everything works with default PostCSS parser. I'll keep an eye on related things.

**Comment by maraisr** [comment]
Yes for sure @davidtheclark I can definitely devote about an hour a day! Keen-man! Keen!

**Comment by davidtheclark** [comment]
Excellent to hear from anybody. If you're new to the repo, feel free to pick up issues and offer new ideas! Look forward to working with you.

**Comment by evilebottnawi** [comment]
All who know Less and have time, we should help to resolve problems https://github.com/webschik/postcss-less/issues/60. For more information see https://github.com/stylelint/stylelint/pull/1899. Unfortunately now I do not have time, but if someone will respond and solve the problem it will be just fine :heart:

**Comment by PhilippeVay** [comment]
@davidtheclark I'm still interested in helping maintaining when it comes to Sass and LESS syntaxes. The agency I work for switched from LESS to `*.scss` a while ago so I've worked with both.  
JS is not my _forte_ but I can help debugging existing code.

**Comment by davidtheclark** [comment]
Great @PhilippBaschke! Picking up bugs will be a good way to improve your JS skills.

**Comment by evilebottnawi** [comment]
Who interested to support `less` we need you help, https://github.com/webschik/postcss-less marked as UNMAINTAINED, need maintainers :sos:
