### ISSUE TITLE
PostCSS reports errors as warnings

### ISSUE THREAD

**Issue by vigneshTheDev** [stylelint/stylelint#2294]
Hi,
I'm using `postcss-loader` for `webpack` as a loader for `stylelint`. Here is the config for `postcss`: 

```
module.exports = {
  plugins: [
    require('postcss-reporter')({ clearMessages: true }),
    require('stylelint'),
    require('autoprefixer')
  ]
};
```

Whenever a `stylelint `error occurs, `postcss `reports as a warning. For example, I have this rule:
`"selector-no-type": true`

This is the output from `postcss` when I have a stylelint error:

```
WARNING in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./~/postcss-loader?sourceMap=inline!./www/app/dashboard/dashboard.scss

stylelint: D:\....\www\app\dashboard\dashboard.scss:9:1: Unexpected type selector (selector-no-type)
```

How do I make it to appear as an error?

**Comment by jeddy3** [comment]
> How do I make it to appear as an error?

We recommend using [`stylelint-webpack-plugin`](https://github.com/JaKXz/stylelint-webpack-plugin) for better reporting.
