### ISSUE TITLE
Support for async rules

### ISSUE THREAD

**Issue by ramasilveyra** [stylelint/stylelint#2296]
Hello!

I'm trying to create a plugin with a rule that checks if the absolute urls images of your css exists: https://github.com/auth0/stylelint-images-valid. This rule makes HEAD requests to check if the images exists, everything is asynchronous.

But stylelint doesn't support async rules (postcss plugins with promises).

With a little help on which needs to change maybe I can try to solve it.

**Comment by davidtheclark** [comment]
@ramasilveyra Have a look at https://github.com/stylelint/stylelint/blob/master/lib/lintSource.js#L101. Looks like I already added a comment there that will give you a nice start!

**Comment by davidtheclark** [comment]
Closed by #2351.
