### ISSUE TITLE
Standardise the options of the remaining multi|single-line whitespace rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#231]
* [x] `block-closing-brace-*`
* [x] `block-opening-brace-*`
* [x] `declaration-block-semicolon-*`
* [x] `media-query-list-comma-*`
* [x] `selector-delimiter-*`

To use the following options:

* `*-newline-after`: `"always"|"always-multi-line|"never-multi-line"`
* `*-newline-before`: `"always"|"always-multi-line"|"never-multi-line"`
* `*-space-after`: `"always"|"never"|"always-single-line"|"never-single-line"`
* `*-space-before`: `"always"|"never"|"always-single-line"|"never-single-line"`

Jump in if anyone fancies helping out on this one. The `value-list-comma-*` rules are what they should look like.

**Comment by jeddy3** [comment]
I'm hopefully going to tackle the renaming three tomorrow. I'm half-way through the `media-query-list-comma-*` rules. I haven't started on the `block-*-brace` rules though, so they are up for grabs if anyone fancies it.

**Comment by jeddy3** [comment]
This is proving to be a bit dicey. Each set of `*-newline-*`rules appears to deal with indentation slightly differently. I'm going too take a deeper look into this (and knock out a few tests so we can all see what's going on). Hopefully I'll do this later today, but it might be after the weekend.

**Comment by davidtheclark** [comment]
Ok. Let me know if you have any questions about something you see, or it looks weird/unjustified.

**Comment by jeddy3** [comment]
Closes in #249 etc
