### ISSUE TITLE
Incompatibility with vue-loader and using stylelint as a PostCSS plugin

### ISSUE THREAD

**Issue by juancabrera** [stylelint/stylelint#2316]
It seems there is an issue when linting on Vue components using `vue-loader`'s (webpack) `postcss` plugin.

When I run webpack I got these linting errors even when the code is linted:
```shell
src/Application.vue
29:1	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
33:3	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
33:3	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
35:1	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
```

> Which rule, if any, is this issue related to?

`rule-empty-line-before` and `indentation`

> What CSS is needed to reproduce this issue?

```css
<style>
:root {
  --color-main: green;
}

.my-app {
  background: #eee;
  padding: 10px;

  & .child {
    color: var(--color-main);
  }
}
</style>
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

`7.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Post CSS plugin:
```javascript
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: {
            plugins: [
              require('stylelint')(),
              require('postcss-import')(),
              require('postcss-cssnext')({
                browsers: 'last 2 versions'
              }),
              require("postcss-reporter")({ clearMessages: true }),
            ],
            options: {
              autoprefixer: false
            }
          }
        }
      },
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Noup.

> What did you expect to happen?

Not having those Lint error as code is linted.

> What actually happened (e.g. what warnings or errors you are getting)?

Got the following linting errors:

```shell
src/Application.vue
29:1	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
33:3	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
33:3	⚠  Expected empty line before rule (rule-empty-line-before) [stylelint]
35:1	⚠  Expected indentation of 2 spaces (indentation) [stylelint]
```

**Comment by jeddy3** [comment]
@juancabrera Thank you for the report and for using the template.

Using stylelint in this context, i.e. as a PostCSS plugin, _might be incompatible_ with vue templates as a [processor](https://stylelint.io/user-guide/configuration/#processors) is needed to prepare the source.

There's an approach that uses stylelint as a standalone tool to lint vue files [documented within the vue-loader issue tracker](https://github.com/vuejs/vue-loader/issues/303#issuecomment-259328193).

Unless any of @stylelint/core can think of an alternative, I think this might just need to be documented in the [FAQ](https://stylelint.io/user-guide/faq/).

**Comment by evilebottnawi** [comment]
@jeddy3 :+1:

**Comment by davidtheclark** [comment]
@jeddy3 I'm unclear: what would be the question, and what would be the answer?

**Comment by juancabrera** [comment]
@jeddy3 interesting.

I added `stylelint-processor-html` to `.stylelintrc` and then run: 
```shell
node_modules/stylelint/bin/stylelint.js '**/*.vue'
```
and it work as expected, but when I run it trough `vue-loader` on `webpack.conf` keep getting these warnings. I'm assuming is an issue with `vue-loader` ?

**Comment by jeddy3** [comment]
> I'm unclear: what would be the question, and what would be the answer?

I think we could expand on this [question](https://stylelint.io/user-guide/faq/#how-do-i-lint-styles-within-style-tags) to mention vue files, and provide an example of using the `stylelint-html-processor`.

> and it work as expected, 

Good stuff.

> I'm assuming is an issue with `vue-loader` ?

I think it depends on whether the `vue-loader` team think bundling support for stylelint within the loader is prudent or not. Maybe not, and so I think you're probably best using a [standalone stylelint plugin](https://github.com/JaKXz/stylelint-webpack-plugin) (as you'll get the best formatter options) e.g.

```
var StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports =
  {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          postcss: {
            plugins: [
              require('postcss-import')(),
              require('postcss-cssnext')({
                browsers: 'last 2 versions'
              }),
              require("postcss-reporter")({ clearMessages: true }),
            ],
            options: {
              autoprefixer: false
            }
          }
        }
      },
  plugins: [
    new StyleLintPlugin({
      "files": ['**/*.vue']
  }),
  ],
```

**Comment by juancabrera** [comment]
that worked well, thanks for following this up @jeddy3.

I still [opened an issue](https://github.com/vuejs/vue-loader/issues/627) on `vue-loader` as they might want to get that fixed anyway.
