### ISSUE TITLE
Did depreciations break builds

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2318]
Sorry this is going to be an awkward post because I'm actually on a trip not at my computer ...

I received some messages from coworkers saying that the upgrade is breaking our build with deprecation warnings. We use the CLI. This problem came up before in #869 and maybe elsewhere. But is there a chance it hasn't been fixed? That would be a bummer.

Sorry I don't have more details but as I said I'm not at my machine, and I won't be for the next couple of days. 

If anybody has a minute to look into this and finds there really is a problem, that the deprecation warnings are breaking builds, let's try to get a fixing release out ASAP.

I'll be back in a few days to help out if still needed.

**Comment by hudochenkov** [comment]
Just tested my project with `gulp-stylelint` and `./node_modules/.bin/stylelint`. They both showed warnings in console about deprecated rules. `gulp-stylelint` didn't fail, CLI seems didn't fail either. Then I introduced an error to my styles. Gulp plugin showed an error and failed, because I've enabled `failAfterError`. Can't say whether CLI failed or not, because I don't know where to look :) Output in the console for CLI and gulp plugin was the same.

**Comment by hudochenkov** [comment]
Kind of offtopic. I have in a console:

> Deprecation Warning: 'comment-empty-line-before's' "between-comments" option has been deprecated and in 8.0 will be removed. Instead use the "after-comment" option. See: https://stylelint.io/user-guide/rules/comment-empty-line-before/

Are there correct quotes in `'comment-empty-line-before's'`?

**Comment by davidtheclark** [comment]
The CLI will break builds if it exits with a non-zero code ---- are you sure that didn't happen?

**Comment by hudochenkov** [comment]
Only deprecations, code 0:

![image](https://cloud.githubusercontent.com/assets/654597/22619329/9cc18108-eb03-11e6-8aef-6ea05d885ed2.png)

1 lint error, code 2:

![image](https://cloud.githubusercontent.com/assets/654597/22619332/c8c7d52c-eb03-11e6-9d47-8df9d67e1b26.png)

Looks like everything is working as expected.

**Comment by evilebottnawi** [comment]
@davidtheclark we use and Travis and Gitlab CI, and the update was successful everywhere, no errors.

**Comment by davidtheclark** [comment]
Ok great, and thanks for double checking. Maybe my coworkers had some other problem.

**Comment by jeddy3** [comment]
Phew, I'm glad it wasn't a broken release. I was away over the weekend and so couldn't confirm. @hudochenkov and @evilebottnawi thanks for double checking.
