### ISSUE TITLE
Do not kill declaration-block-properties-order

### ISSUE THREAD

**Issue by in-in** [stylelint/stylelint#2329]
You guys are awesome! In the spring you're going to kill `declaration-block-properties-order`.
I think this is the core feature of _stylelint_.

And you suggest we will use _stylelint-order_, which does not work with _stylefmt_.

Please, do not kill the `declaration-block-properties-order` before the _stylefmt_ will be able to work with plugins. Or help @morishitter finish his _stylefmt_ before you kill `declaration-block-properties-order`.

**Comment by evilebottnawi** [comment]
btw, i am voiting for include `stylelint-order` in `core`, i still believe that such rules should be part of the core :smile:

**Comment by jeddy3** [comment]
`stylelint-order` has already grown to include features that would excluded it from being included in core e.g. support for `dollar-variables` in [declaration-block-order](https://github.com/hudochenkov/stylelint-order/tree/master/rules/declaration-block-order#primary-option) and rules than compose other rules in [declaration-block-property-groups-structure](https://github.com/hudochenkov/stylelint-order/tree/master/rules/declaration-block-property-groups-structure).

These two feature alone highlight why this is an ideal plugin candidate. 

As an aside, I think we should be encouraging the use of plugins. I believe they are what will allow stylelint to avoid becoming burdened with the variety of non-standard syntaxes, constructs and use cases. Thus keeping it agile enough to remain relevant. 

> And you suggest we will use stylelint-order, which does not work with stylefmt.

[`postcss-sorting`](https://github.com/hudochenkov/postcss-sorting) is a great companion to the `stylelint-order`, with an [broad feature list](https://github.com/hudochenkov/postcss-sorting#features).

**Comment by hudochenkov** [comment]
Just for your information: we [have plans](https://github.com/stylelint/stylelint/issues/2259) to add fixing functionality to stylelint. In the meantime, you can use `postcss-sorting` for “fixing” order of properties.

**Comment by in-in** [comment]
>Just for your information: we have plans to add fixing functionality to stylelint.

Yes, it's just plans nothing more for today

But now the autofix works. Guys autofix right now working.
But after a couple of months, you're going to kill autofix without any alternatives. What for?

**Comment by hudochenkov** [comment]
Evolution. We have nothing to do with stylefmt. It's like blaming Microsoft if one of programs for Windows made by non-Microsoft stopped working in the new Windows. You could help community and add support for plugins to stylefmt.

**Comment by in-in** [comment]
Who we are? We are the maintainers
What we do? We don't care about users

@hudochenkov nice answer I like it

**Comment by evilebottnawi** [comment]
@stylelint/core btw, I said that users will respond negatively about removed `declaration-block-properties-order` rule from core, I think it is not the last. We can talk a long time about plugins and how to make good use of them, theoretically we can do to remove all rules from the core in the plugins (it would be ideal :laughing: ). But do not forget about the user experience. All my friends used to sort the properties and they are all similarly negative view to removing this rule without an alternative. 

I've probably all tired of repeating the same thing, but that's just my opinion and I think we should should listen to users, and not impose them his decision, an attempt to idealize the code in spite of the needs of the community to anything good will not.

**Comment by davidtheclark** [comment]
@evilebottnawi: We are not idealizing the codebase, we are not ignoring users, and nothing that is said above seems like a good reason to change our minds. 

@jeddy3 is absolutely right that users need to get used to using plugins. It's not a real burden to them — though, yes, it's easy to complain about if you are looking for things to complain about — and it makes for a better system, which is better for both maintainers and users in the end.

This is open source, unpaid labor, and anybody (like @in-in) who wants something that isn't offered is encouraged to work on it themselves. I will never be convinced by somebody saying "Oh but I really want you to do this thing for free and I don't want to do it so you do it!"

**Comment by in-in** [comment]
@davidtheclark you mention me in your comment so please show me where are I said “I don't want to do it so you do it!”
Can you feel difference between “don't want” and “can't do”?
I do CSS and HTML if you have issues with these technologies glad to help you.
Btw, if I remember correctly I have already fixed your open source documentation because I can do it.
