### ISSUE TITLE
Malformed message in shorthand-property-no-redundant-values

### ISSUE THREAD

**Issue by bedney** [stylelint/stylelint#2330]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This rule produces a malformed fix. See below.

> Which rule, if any, is this issue related to?

`shorthand-property-no-redundant-values`

> What CSS is needed to reproduce this issue?

```css
h1 {
    font-size: 123.1%;
    margin: 1em 0 2em 0;
}

```

> What stylelint configuration is needed to reproduce this issue?

```json
{
    "extends": "stylelint-config-standard",
    "rules": {
        "at-rule-empty-line-before": null,

        "comment-empty-line-before": null,

        "block-no-empty": [true, { "severity": "warning" }],
        "block-opening-brace-newline-after": "always",

        "declaration-empty-line-before": null,

        "indentation": 4,

        "font-family-name-quotes": "always-unless-keyword",

        "function-url-quotes": "always",

        "rule-nested-empty-line-before": null,

        "selector-attribute-quotes": "always",
        "selector-type-no-unknown": null,

        "string-quotes": "double",

        "value-keyword-case": "lower"
    }
}
```

> Which version of stylelint are you using?

`7.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"CLI with `stylelint *.css`"

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

Proper CSS corrective declarations to be emitted.

> What actually happened (e.g. what warnings or errors you are getting)?

The following corrective CSS was produced. Note the weird `0:2em` corrective suggestion:

```shell
 66:5  ✖  Unexpected longhand value '1em 0 2em   shorthand-property-no-redundant-values
          0' instead of '1em 0:2em'
```

Thanks!

**Comment by bedney** [comment]
I'm not an expert on CSS tri-value syntax, but it looks like this might just be a bug where the output is using a colon (':') rather than a space (' ').

**Comment by bedney** [comment]
Further information: it only looks like this is happening when the value that's being 'repeated' and is 'unnecessary' is the value `0`.

**Comment by evilebottnawi** [comment]
@bedney Thanks for feedback. Fell free to send a PR :smile:

**Comment by bedney** [comment]
So I forked and was going to do a PR, but in looking at the rule source, this looks like the bug is possibly in the values parser (`postcss-value-parser`) that you all use. Therefore it is not really a 'beginner-friendly' bug to fix. This will entail either forking `postcss-value-parser`, fixing it there and using the fork or special casing it here. Either way, it wasn't something I felt I could do given that I have no experience with your codebase.

OTOH, this bug could be in some other piece of code and I'm completely wrong here :-).

**Comment by hudochenkov** [comment]
Looks like there an issue with a formatter or something, because warning is correct in our [demo](https://stylelint.io/demo/).

@bedney thank you for starting looking for solution!

**Comment by evilebottnawi** [comment]
@bedney not reproduced, can you create test repo? https://github.com/stylelint/stylelint/pull/2339

**Comment by bedney** [comment]
Guys - thanks for continuing to work this. I'll try to reduce down a test case that shows what I was seeing and why I was seeing it.
