### ISSUE TITLE
Tests complain about \ vs / discrepencies in file paths on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stylelint/stylelint#2357]
Related to #264. On a Windows 10 cmd window with a fresh-from-GitHub install of stylelint, tests are assuming *nix-style file paths.

![image](https://cloud.githubusercontent.com/assets/3335181/22866190/b9771ed8-f126-11e6-8913-7300f48f186c.png)

**Comment by jeddy3** [comment]
@JoshuaKGoldberg Thanks for the report. The snapshots of the results objects were first generated on a *nix system, hence the slash being backwards.  Do you have any experience normalising _the appearance of_ file paths in node? As any help from a windows user would a greatly appreciated!

**Comment by JoshuaKGoldberg** [comment]
You should be able to use [`path.sep`](https://nodejs.org/api/path.html#path_path_sep) to generate file paths that work with the user's system. It's a little annoying to do en masse.

**Comment by davidtheclark** [comment]
Seems that the solution here is probably to iterate through results before taking the snapshot and normalize the path values of the `source` properties.
