### ISSUE TITLE
Run --report-* flags before linting, rather than instead of it

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2369]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Be good can use linting and report needless disables. It is allow reduce unnecessary stylelint disable rules and check on linting error in one command. If you use two scripts (command), then we run twice globby and this increases the load on the file system :disappointed: 

> Which rule, if any, is this issue related to?

No matter

> What CSS is needed to reproduce this issue?

No matter
> What stylelint configuration is needed to reproduce this issue?

e.g.

No matter

> Which version of stylelint are you using?

`7.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No matter

> What did you expect to happen?

Warning and messages about unnecessary stylelint disable comments

> What actually happened (e.g. what warnings or errors you are getting)?

Only two scripts (commands) allow this feature.

**Comment by jeddy3** [comment]
Is the idea here that using the `--report-needless-disables` would run that check first and then run the linter afterwards, rather than _instead of the linter_? 

And I assume the process would exit early if `--report-needless-disables` uncovered any issues?

Can anyone foresee any disadvantages to changing the behaviour?

**Comment by davidtheclark** [comment]
Seems fine to me.

**Comment by jeddy3** [comment]
@evilebottnawi Is this issue something you'll be able to look into for `8.0.0`?

**Comment by evilebottnawi** [comment]
@jeddy3 try to find solution in near future

**Comment by hudochenkov** [comment]
Done in https://github.com/stylelint/stylelint/pull/4151
