### ISSUE TITLE
New rule for shorthand blacklist

### ISSUE THREAD

**Issue by eddiemoore** [stylelint/stylelint#2380]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new rule to have exceptions to the shorthand properties. For example `background` prefer to just use `background-color:` etc. As described by @csswizardry in [this article](https://csswizardry.com/2016/12/css-shorthand-syntax-considered-an-anti-pattern/)
So a rule to only allow `background` when using multiple properties
```css
background: #eee url(image.jpg);
```

> Which rule, if any, is this issue related to?

None at the moment

> What CSS is needed to reproduce this issue?

```css
.foo {
  background: red;
}
```

> What stylelint configuration is needed to reproduce this issue?

None at the moment, but maybe something with a blacklist?
```json
{
  "rules": {
    "shorthand-property-blacklist": ["background"]
  }
}
```

> Which version of stylelint are you using?

`7.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "app/**/*.css"`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Most likely

> What did you expect to happen?

Warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

No warnings flagged

**Comment by jeddy3** [comment]
@eddiemoore Thanks for the suggestion and for using the issue template.

I think this is a good candidate for a plugin. You can [build one](https://stylelint.io/developer-guide/plugins/) and experiment with the practicalities of such a rule. There are edge cases to consider here. For example, when do you trigger a warning? If a shorthand property is missing a _single_ value, and or a configurable amount, and if you can configure it differently for each property. 

If the plugin proves useful and adheres to to [our criteria for inclusion](https://stylelint.io/developer-guide/rules/#criteria-for-inclusion), we can consider moving it to core.

Good luck!

**Comment by eddiemoore** [comment]
@jeddy3 OK. Will have a think about it and see what I can come up with.

**Comment by jeddy3** [comment]
@eddiemoore Good luck. FYI, I thought some more about this last night and one possible approach could a `shorthand-property-min-values: {}` plugin e.g.

```js
"shorthand-property-min-values": {
  "background": 2,
  "font": 3
}
```

You could then use [`postsss-values-parser`](https://github.com/TrySound/postcss-value-parser) to tally the number of _top-level_ `words`, `function` and `strings`. If the tally doesn't meet the [minimum number](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#max-and-min-rules) set for that shorthand property you'd throw a warning.

Perhaps you can get some mileage from that approach.

**Comment by eddiemoore** [comment]
That might be good. I'll give that a try
