### ISSUE TITLE
Add MathML tags to list of known tags in selector-type-no-unknown

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2397]
Ref: https://github.com/stylelint/stylelint/issues/2326#issuecomment-278416740

**Comment by evilebottnawi** [comment]
@jeddy3 sgtm

**Comment by evilebottnawi** [comment]
http://caniuse.com/#search=mathml spec status `recommendation` change labels

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/2478
