### ISSUE TITLE
Potential problem with rejected tests

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2419]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

`line` and `column` for rejected tests can be specified as 0 and it [won't be checked](https://github.com/stylelint/stylelint/blob/16e8cc79f8d08cd9502fd9ab58f9d137c08709b5/jest-setup.js#L51-L54) by Jest. Is it a correct behaviour?

> Which rule, if any, is this issue related to?

`selector-class-pattern` [test](https://github.com/stylelint/stylelint/blob/16e8cc79f8d08cd9502fd9ab58f9d137c08709b5/lib/rules/selector-class-pattern/__tests__/index.js#L68).

**Comment by davidtheclark** [comment]
> Is it a correct behaviour?

No! That's a sloppy conditional. Let's fix it!

**Comment by hudochenkov** [comment]
Is `(testCase.line && testCase.line > 0)` a good fix?

**Comment by davidtheclark** [comment]
I think `(testCase.line !== undefined)` is better. That's really what we're looking for.

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/2420
