### ISSUE TITLE
Rename declaration-empty-line-before to property-empty-line-before

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2423]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I think the name of the rule isn't quite correct. From the rule's name user assumes it targets all declarations:

```css
a {
    --width: 10px;
    $width: 10px;
    width: 10px;
}
```

But it target's only standard syntax declarations and not custom properties or anything else. From example above only `width` is affected by rule.

In fact, there are `custom-property-empty-line-before` and [`scss/dollar-variable-empty-line-before`](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/dollar-variable-empty-line-before/README.md).

I think `property-empty-line-before` is more correct name for this rule.

> Which rule, if any, is this issue related to?

`declaration-empty-line-before`

**Comment by jeddy3** [comment]
> But it target's only standard syntax declarations and not custom properties or anything else.

I think we're OK here. A _declaration_ [is a](https://www.w3.org/TR/css-syntax-3/#syntax-description) standard property followed by a colon and then a value. A _custom property_ [seemingly refers to](https://www.w3.org/TR/css-variables/#defining-variables) to the whole construct i.e. the custom property name, the colon and the custom property value. Or at least the language in the spec makes me think so:

> Unlike other CSS properties, custom property names are case-sensitive.
> The values of custom properties, and the values of var() functions substituted into custom properties

I believe the same is true for _defining_ dollar variables. Say, going forward, new rules are added to `stylelint-scss` for specifically targeting, using heuristics, _maps_ and _lists_. Taking [_map_](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#maps) as an example:

> `$map: (key1: value1, key2: value2, key3: value3);`

The _whole_ construct is called a "map", not just the `$map` bit before the colon.

**Comment by hudochenkov** [comment]
Then I think we should specify at least in rule's README, that the rule targets not all declarations. Because custom properties is a particular case of standard declarations, but they are not targeted by this rule.

**Comment by jeddy3** [comment]
> Because custom properties is a particular case of standard declarations

I'm not sure that's the case. From my reading [of the spec](https://www.w3.org/TR/css-variables/#defining-variables), I think the whole construct is called a _custom property_.  Having said that,  the language is a bit ambiguous. In the past, whenever there seems to be some ambiguity in the wording, we've tended to err on the side of whatever works well for us in the wider stylelint context. And, as the _list_, _map_ and _dollar-variable_ example above hopefully highlights, I think treating the whole construct as a _custom property_ (rather than just the bit before the colon) works better for us.

I'll be glad to change my mind though if you've able to dig up a definitive resource that says the `--name` bit of  `--name: value;` is called a _custom property_, rather than a _custom property name_.

**Comment by hudochenkov** [comment]
I understand, thankfully to your spec link, that custom property it's `--value: key` (full construct).

This is declaration: `prop: value`.
This is declaration, and, more specific, custom property: `--prop: value`.

My point is custom property is a declaration. `declaration-empty-line-before` will ignore it, but based from the rule's name it shouldn't be ignored.

The rule's name stands for both types of declarations `prop: value` and `--prop: value`, but in fact it's only for all declarations except specific kind of declarations — custom properties.

**Comment by jeddy3** [comment]
> This is declaration, and, more specific, custom property: `--prop: value`

This is the bit I'm unsure about. Can you point me at a doc where I can read more about how a _custom property_ is a more specific type of _declaration_?

**Comment by hudochenkov** [comment]
Specifications are hard :(

`--property: value` according to [spec](https://www.w3.org/TR/css-variables/#defining-variables) is `<custom-property-name>: <declaration-value>`.

In [example 6](https://www.w3.org/TR/css-variables/#syntax): “The variable declarations can even be kept in a separate file...”.

_[...20 minutes later...]_

[§ 4. APIs](https://www.w3.org/TR/css-variables/#apis):

> All [custom property](https://www.w3.org/TR/css-variables/#custom-property) [declarations](https://www.w3.org/TR/css-syntax-3/#declaration) have the case-insensitive flag set.

Here it is! `--prop: value` is a _custom property declaration_.

So `--prop: value` is a declaration, but `declaration-empty-line-before` ignores it.

**Comment by jeddy3** [comment]
> Here it is! `--prop: value` is a custom property declaration.

It is a bit confusing, isn't it? Some parts of the spec make me think _custom properties_ are specific types of _declarations_, and other parts make me think they are their own thing entirely.

> Then I think we should specify at least in rule's README, that the rule targets not all declarations.

I think we should just do this. Throughout stylelint we use "declaration" to refer to what, I guess, we can call "standard declarations" i.e. a standard property, followed by a colon and then a value. I believe custom properties, dollar-variables etc are always ignored in `declaration-*` rules. Rather than change that behaviour, let's just add some clarification to this rule's README:

"This rule only applies to standard declarations; custom properties, SCSS variables and LESS variables are ignored."

**Comment by hudochenkov** [comment]
> I believe custom properties, dollar-variables etc are always ignored in declaration-* rules.

No, they aren't.

[`declaration-colon-newline-after`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-colon-newline-after/index.js) works for both `prop: value` and `--prop: value`.
[`declaration-colon-space-after`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-colon-space-after/index.js) works for both `prop: value` and `--prop: value`.
[`declaration-no-important`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-no-important/index.js) doesn't even check if declaration is standard.
[`declaration-empty-line-before`](https://github.com/stylelint/stylelint/blob/5e6d4260cef6e51d898359aed41af1e4c1a61e00/lib/rules/declaration-empty-line-before/index.js#L52-L57) works for `prop: value` only.

[isStandardSyntaxDeclaration.js](https://github.com/stylelint/stylelint/blob/5e6d4260cef6e51d898359aed41af1e4c1a61e00/lib/utils/isStandardSyntaxDeclaration.js) passes for standard and custom properties.

**Comment by jeddy3** [comment]
>> I believe custom properties, dollar-variables etc are always ignored in declaration-* rules.

> No, they aren't.

Ha. I guess I was being overly optimistic in my hope for consistency :)

To be fair, `declaration-no-important ` was written about 2 years ago and before the likes of custom properties and non-standard syntax support came on the scene.

I still think we can resolve this with documentation though by being pragmatic (and a little loose) with our definition of a declaration.

- `declaration-colon-*-*`: let's continue to check both `prop: value` and `--prop: value` as it seems pretty unlikely people would want differing conventions between standard declarations and custom properties. In these instances `declaration` refers to both standard declarations and custom properties. If they do want differing conventions, we can always create a bunch of `custom-property-colon-*` rules later down the line.
- `declaration-no-important`: we've generally only excluded non-standard syntax when it causes a problem. As no one has complained about `!important` with non-standard syntax or custom properties yet, I think we can leave it as is.
- `declaration-empty-line-before`: let's document that it's applicable to only standard declarations _as there's a specific rule_ for controlling the empty lines before custom properties.

**Comment by hudochenkov** [comment]
Done in https://github.com/stylelint/stylelint/pull/2434
