### ISSUE TITLE
No way to disable hardcoded ignore of node_modules folder

### ISSUE THREAD

**Issue by TheXardas** [stylelint/stylelint#2436]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where there is no way to disable hardcoded ignore of node_modules folder.

> Which rule, if any, is this issue related to?

No specific rule

> What CSS is needed to reproduce this issue?

No specific css required to reproduce.

> What stylelint configuration is needed to reproduce this issue?

No specific configuration required to reproduce

> Which version of stylelint are you using?

7.9.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

running stylelint with CLI `stylelint /Users/xardas/PhpstormProjects/project1/src/node_modules/Roboto.css` 

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

To lint file correctly, and to not throw any errors.

> What actually happened (e.g. what warnings or errors you are getting)?

stylelint failed to match file, because it is in the node_modules directory.
And then, stylelint throws this error:
```
Error: Files glob patterns specified did not match any files
    at globby.then.filePaths
```

We use "node_modules" folder in our repository for a more comfortable way to import components, shared between few projects, with absolute path.
So, files in certain "node_modules" folder should be checked, but should be ignored in another "node_modules", which we could specify. But there is no way to disable hardcoded "node_modules" check.

**Comment by evilebottnawi** [comment]
@TheXardas seems duplicate https://github.com/stylelint/stylelint/pull/2382

**Comment by TheXardas** [comment]
@evilebottnawi yeah, seems so.

**Comment by jeddy3** [comment]
@TheXardas FYI, there's a [pending PR](https://github.com/stylelint/stylelint/pull/2382) for it... it's just a bit tricky.
