### ISSUE TITLE
config with extends.

### ISSUE THREAD

**Issue by alan-agius4** [stylelint/stylelint#2439]
just a question, when using `config` rather than `configFile` does `extends` still work?

**Comment by jeddy3** [comment]
Yes, it does as `config` [excepts a complete _configuration object_](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#config).

However, you might need to [set `configBaseDir`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#configbasedir) if your `extends` uses _relative_ paths.
