### ISSUE TITLE
Add Support for TypeScript

### ISSUE THREAD

**Issue by alan-agius4** [stylelint/stylelint#2444]
Hi,

Are you willing to accept TypeScript typings within the repo itself?

This will make it more convenient for typescript users (and [suggested by typescript](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)) to provide typings with the repository itself, rather than another repo (such as [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)).

Are you willing to have a pull request for this?

I will be happy to create typing for this library myself if you agree.

Thanks!

**Comment by davidtheclark** [comment]
Nope. I do not want to mess with Typescript. If you have any other less intrusive ideas for making package consumption easier for Typescript users, let us know.

**Comment by alan-agius4** [comment]
The least intrusive ideas would be to have typings as a seperate file. Example /typings/index.d.ts. 

Your code won't change a bit. You'll code the way u do now. 

Basicilly the change would be to include this file within you library 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/stylelint/index.d.ts

**Comment by evilebottnawi** [comment]
@alan-agius4 can you do PR with sample example?

**Comment by alan-agius4** [comment]
Yeah surly I can do it tmr or the day after

**Comment by Arcanemagus** [comment]
The problem I see here is that as the API changes the authors here will need to keep that maintained, when this is something that isn't desired in the first place it will likely to be forgotten and become out of date.

**Comment by alan-agius4** [comment]
In case the API is updated at the moment at the moment is harder to maintain as 3rd party users will have to go and update https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stylelint and keep it maintained.

**Comment by jeddy3** [comment]
> The problem I see here is that as the API changes the authors here will need to keep that maintained

I agree.

> 3rd party users will have to go and update https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/stylelint and keep it maintained.

I think having it maintained by a 3rd party in the DefinitelyTyped repo correctly signals that the stylelint org isn't responsible for keeping it up to date i.e. the org puts out a release (with a change of API) and then a 3rd party can update the definitions on DefinitelyTyped _after the fact_, rather than the stylelint org being responsible for updating the definitions _before_ the release.

**Comment by alan-agius4** [comment]
Okay, thanks for the feedback and interest anyways.

**Comment by davidtheclark** [comment]
> I think having it maintained by a 3rd party in the DefinitelyTyped repo correctly signals that the stylelint org isn't responsible for keeping it up to date

@jeddy3's point is exactly right.

**Comment by davidmaxwaterman** [comment]
From README
> CSS-in-JS object & template literals

I wonder if stylelint is supposed to work with style in template literals in typescript? Since it worked in template literals in JavaScript, I imagined it would work similarly in template literals in TypeScript, but it seems not to. Am I missing something?
