### ISSUE TITLE
Loading modules via the custom-formatter CLI flag

### ISSUE THREAD

**Issue by ccbikai** [stylelint/stylelint#2449]
I write a formatter like:

![image](https://cloud.githubusercontent.com/assets/2959393/24393553/275001e2-13cb-11e7-83b4-5d555c6392f2.png)

I want use `stylelint --syntax scss --config .stylelintrc --custom-formatter stylelint-formatter-table public/scss/*.css` run it, but fail.

I can only use `stylelint --syntax scss --config .stylelintrc --custom-formatter /Users/ccbikai/code/node/stylelint-formatter-table/index.js public/scss/*.css`.

code: https://github.com/ccbikai/stylelint-formatter-table

**Comment by jeddy3** [comment]
@ccbikai Thanks for the report.

The code to load custom formatters via the CLI is [here](https://github.com/stylelint/stylelint/blob/master/lib/cli.js#L152-L155). Would you like to investigate what is happening and maybe submit a Pull Request to resolve the issue?

**Comment by jeddy3** [comment]
Closing. Feel free to reopen if any further investigation uncovers something.
