### ISSUE TITLE
No elegant way to have a global config?

### ISSUE THREAD

**Issue by SidFerreira** [stylelint/stylelint#2479]
I'm new using stylelint, just started testing it, and I was wondering how to set a global rule.
I was expecting that stylelint would check the `process.env.HOME` for a file, but I'm reading the source and seem that's not the case.

Of course, this isn't an issue for developers that has their projects inside their home dir, but that's not my case.

Seem to me that adding 
```
  }).then(config => {
    // If no config was found, try looking from user's HOME
    if (!config) return stylelint._fullExplorer.load(require('os').homedir())
return config
```
at https://github.com/stylelint/stylelint/blob/master/lib/getConfigForFile.js#L36 would to the trick.

ps: I didn't wrote a PR because I wasn't sure it would help with the goals for the tool

**Comment by hudochenkov** [comment]
It searches for config in home dir. [Loading the configuration object](https://stylelint.io/user-guide/configuration/#loading-the-configuration-object).

[cosmiconfig readme](https://github.com/davidtheclark/cosmiconfig):
> cosmiconfig continues to search in these places all the way down the file tree until it finds acceptable configuration (or hits the home directory).

Just put your `.stylelintrc` in your home dir.

**Comment by SidFerreira** [comment]
If this is the case, seem that cosmiconfig has something wrong. I'll debug it a bit and ping you back

**Comment by SidFerreira** [comment]
@hudochenkov I checked cosmiconfig and happens that they just assume that the project is inside the home path, as you can see at https://github.com/davidtheclark/cosmiconfig/blob/master/lib/createExplorer.js#L80 and https://github.com/davidtheclark/cosmiconfig/blob/master/index.js#L18.

Maybe we can suggest this change to `cosmiconfig` project.

**Comment by davidtheclark** [comment]
> they just assume that the project is inside the home path

@SidFerreira: cosmiconfig starts from the specified starting point and then continues down the tree until it reaches either home or the specified `stopDir`. It should find configuration in your home path. I tried it out again this morning, and it worked just fine. So I think something is different about your particular situation.

**Comment by SidFerreira** [comment]
@davidtheclark maybe the issue is in my local instal... But to be sure: have you tried to run the command on a removeable media for example? Something that isn't mounted inside the `/Users/myuser` / `/home/myuser`?

**Comment by davidtheclark** [comment]
@SidFerreira: That's different, right? The "home" directory is not the *root*. Have you tried using `stopDir` to specify that you want it to search all the way down to the root? Also, there'd have to be a direct path from the file you're linting to the config — it's not going to look from one drive into another.

**Comment by SidFerreira** [comment]
@davidtheclark Well, we finally found the point here :) I personally think that, in a last case scenario, makes sense to check on user's home folder, even if we aren't on the same path/drive. I think that placing it on my computer's root or `/Volumes` isn't a logical decision for a starter user, that's why I suggested the change. It's a suggestion but I feel it doesn't meed the goals for Stylelint it self. 

Still, thanks for your time talking about it. It's a great tool I hope to help in the near future 😄

**Comment by davidtheclark** [comment]
> I personally think that, in a last case scenario, makes sense to check on user's home folder, even if we aren't on the same path/drive.

Sure, this sounds reasonable. If you'd like to open and issue or PR in cosmiconfig, we could look into  the idea further.
