### ISSUE TITLE
Document recommend secondary option for disabling fix in plugins

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2499]
stylelint plugins could have autofixing. I'll start with `stylelint-order` as an example.

I would like to use `postcss-sorting` inside `stylelint-order` for autofixing. `stylelint-order` works great, it checks only things user specified to check. But `postcss-sorting` makes assumptions about other things which might be related to specified things. It [glued comments to nodes](https://github.com/hudochenkov/postcss-sorting#handling-comments) they can belong. It works that way because it most likely what people will do with manual sorting. So if `stylelint-order`'s autofixing will use `postcss-sorting`, it might not be what user expects.

I think we should add ability to disable autofixing for specified plugins or rules. If linting and fixing logic in plugin is slightly different, and fixing isn't working as it should, but user still wants to lint.

One way we can do this is by adding `disableFixing` secondary option:

```json
{
	"order/properties-alphabetical-order": [true, {
		"disableFixing": true
	}]
}
```

And while I've been writing this issue I came up with idea, that stylelint shouldn't do anything. stylelint plugin's author could add this option by herself, if she knows fixing is different from linting in her plugin. But we should add some guidelines for plugin authors about this situation.

What do you think?

**Comment by jeddy3** [comment]
> And while I've been writing this issue I came up with idea, that stylelint shouldn't do anything. stylelint plugin's author could add this option by herself

That SGTM. 

> But we should add some guidelines for plugin authors about this situation.

Agreed. Let's go with `disableFix` in the docs for parity with the `--fix` option.

**Comment by davidtheclark** [comment]
👍

**Comment by hudochenkov** [comment]
Done in #2517
