### ISSUE TITLE
Add support for asynchronous processors

### ISSUE THREAD

**Issue by ismay** [stylelint/stylelint#2502]
I'm in the middle of writing [a stylelint-processor for glamorous](https://github.com/ismay/stylelint-processor-glamorous), but it needs [postcss-js](https://github.com/postcss/postcss-js) to parse the css-in-js, which works async. So I can't return a result synchronously. The docs only show a sync example, so my question is if there is a way to define an async processor.

**Comment by davidtheclark** [comment]
@ismay: Probably not. Didn't think of that. We can build it in as a new feature — it's a good idea.

**Comment by jeddy3** [comment]
@ismay Feel free to help contribute this feature. Support for async _plugins_ was [recently added](https://github.com/stylelint/stylelint/pull/2351/files#diff-5ad37590092c2098f0fb6d72557720dd), and might be useful as a reference.

**Comment by ismay** [comment]
Cool, I'll look into it if I have the time!

**Comment by jeddy3** [comment]
Closing as processors are discouraged in favour of custom syntaxes.
