### ISSUE TITLE
Can i use my own plugin or extend with CodeClimate?

### ISSUE THREAD

**Issue by konstantin24121** [stylelint/stylelint#2505]
In my stylelintrc.js 
```
module.exports = {
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-css-modules",
  ],
  "plugins": [
    "stylelint-performance-animation",
  ],
...
```
In codeclimat.yaml i turn on stylelint engine and take this error on codeclimete

•• Timing: .engineConfig: 0.049s
Error: Could not find "stylelint-config-css-modules". Do you need a `configBasedir`?
See our documentation at https://docs.codeclimate.com/docs/stylelint for more information.

Can somebody explain me how enable plugins ands extends if it posible?

**Comment by evilebottnawi** [comment]
@konstantin24121 please use issue's template and also it is seems as question not related to `stylelint` directly, for this better use `stackoverflow` or create issue in https://github.com/codeclimate/codeclimate.

**Comment by konstantin24121** [comment]
@evilebottnawi ok, thanks
