### ISSUE TITLE
Deprecate `function-url-data-uris` in favor of `function-url-scheme-blacklist`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2513]
- [x] Create `function-url-scheme-blacklist`
- [x] Deprecate `function-url-data-uris`

> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Deprecated `function-url-data-uris` in favor `function-url-scheme-blacklist`.

> Which rule, if any, is this issue related to?

If i enable `function-url-data-uris` it is disable use `data` in url, but i can use `function-url-scheme-whitelist` without allowed `data` scheme and get two errors (intersection of rules). I think more right deprecated `function-url-data-uris` and add `function-url-scheme-blacklist` where i can disable `data` and maybe other scheme like as `ftp`, `file` and etc.

In now only `function-url-scheme-whitelist` don't have pair and it is should be `function-url-scheme-blacklist`.

> What CSS is needed to reproduce this issue?

no matter

> What stylelint configuration is needed to reproduce this issue?

no matter

> Which version of stylelint are you using?

latest

> How are you running stylelint: CLI, PostCSS plugin, Node API?

no matter

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no matter

> What did you expect to happen?

no matter

> What actually happened (e.g. what warnings or errors you are getting)?

no matter

/cc @stylelint/core

**Comment by davidtheclark** [comment]
Sounds correct to me! 👩‍🚀

**Comment by hudochenkov** [comment]
Sounds right.

**Comment by jeddy3** [comment]
Agreed. I was sure we were done with deprecations before `8.0.0`, but it seems there will be a few more (e.g. the `selector-max-*` rules replacing the `selector-no-*` ones). As such, let's make sure we do this deprecation in a new `deprecations-round-2` branch so that we can bundle them all into the same release to minimise inconvenience to the user.

**Comment by jeddy3** [comment]
FYI, I'm WIP on deprecating the old `function-url-data-uris` rule.
