### ISSUE TITLE
Show the linting status after linting is done

### ISSUE THREAD

**Issue by anshulguleria** [stylelint/stylelint#2514]
A feature to show status of linting after its done, similar to what eslint does.

e.g.
✖ 61 problems (2 errors, 59 warnings)

This is printed after i run `eslint` but in case of `stylelint` it only shows me the errors in lines not the total status at the bottom. 

```bash
stylelint -v # 7.10.1
```

**Comment by evilebottnawi** [comment]
@anshulguleria please use issue's template,

**Comment by jeddy3** [comment]
@anshulguleria `stylelint "**/*.css" --formatter verbose`

Use `stylelint --help` to see the CLI options.
