### ISSUE TITLE
Remove Sinon stubs in favor of Jest mocks

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2519]
Since we are using Jest now, we should be able to remove our Sinon dependency.

This will also eliminate the warning we're getting: `sinon.stub(obj, 'meth', fn) is deprecated and will be removed from the public API in a future version of sinon.`

**Comment by jeddy3** [comment]
SGTM.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/issues/2559
