### ISSUE TITLE
Deprecate selector-no-* rules in favour of selector-max-*

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2528]
Ref: https://github.com/stylelint/stylelint/pull/2474

I did an audit of the 50 or so `-no-` rules. The good news is that it is only some the `selector-no-*` rules that are applying a limit and would be better suited as `-max-` rules.

I believe these are:

Create new rules:

- [x] `selector-no-attribute` -> `selector-max-attribute` ("attribute" is shorthand for _attribute selector**s**_)
- [x] `selector-no-combinator` -> `selector-max-combinators` (pural as not shorthand)
- [x] `selector-no-id` -> `selector-max-id`
- [x] `selector-no-type`  -> `selector-max-type`
- [x] `selector-no-universal`  -> `selector-max-universal`

Deprecate old rules:

- [x] `selector-no-attribute`
- [x] `selector-no-combinator`
- [x] `selector-no-id`
- [x] `selector-no-type`
- [x] `selector-no-universal`

(Additionally, there's scope for a new rule within this system - `selector-list-max-selectors`, but that's for another time).

I think we'll want to make these deprecations at the same time as https://github.com/stylelint/stylelint/issues/2513 - and we'd remove the rules in `8.0.0`.

@stylelint/core Thoughts?

@jimbo Would you be willing to help out with these rules? I believe you're in an ideal position after your work on `selector-max-class`.

**Comment by evilebottnawi** [comment]
@jeddy3 sgtm

**Comment by davidtheclark** [comment]
👌

**Comment by jimbo** [comment]
@jeddy3 Certainly. I'll be traveling for most of May, but I'll have time here and there to work on them, and the new rules will probably be very similar to `selector-max-class` anyway.

**Comment by jeddy3** [comment]
Excellent. I've labelled as `status: help wanted`. 

I'll also add `beginner friendly` as contributing to this issue would be a good my-first-pr.

Anyone feel free to jump in. Just drop a note here about which rule you're working on so that effort is not duplicated.

**Comment by evilebottnawi** [comment]
`selector-max-attribute` wip

**Comment by evilebottnawi** [comment]
`selector-max-universal` wip

**Comment by evilebottnawi** [comment]
`selector-max-combinators` wip

**Comment by evilebottnawi** [comment]
:tada: `selector-no-type` wip

**Comment by evilebottnawi** [comment]
@stylelint/core before close this issue, after all will be merged, please twice check code, docs and tests, I did it quickly and we could have missed something

**Comment by jeddy3** [comment]
> selector-no-type wip

Good stuff.

Remember that `selector-no-type` has, unlike the other `selector-no-*` rules, [optional secondary options](https://github.com/stylelint/stylelint/tree/c85372c07239e2d0688abcda1eb1b390e649bfba/lib/rules/selector-no-type#optional-secondary-options). If these options are set then the corresponding type selector _should not be included in the count_.

**Comment by evilebottnawi** [comment]
@jeddy3 also we should improve perf new rules, i known how it do, let's do it after merge.

**Comment by jeddy3** [comment]
> also we should improve perf new rules, i known how it do, let's do it after merge.

Good idea. Let's create a separate issue for that. Unlike deprecating the old rules, it's no neccesary for the `7.12` release.

**Comment by jeddy3** [comment]
FYI, I'm WIP on deprecating the old `no` rules.
