### ISSUE TITLE
Deprecate `postcss-less` support

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2533]
Now `postcss-less` parser is don't maintenance and we asked the community for support and looked for contributors, but no one was found, apparently this is not particularly necessary to anyone.

Also I want to add about the future `postcss-sass`, we should surely make sure that he has at least one permanent contributor, otherwise everything will happen the same with `postcss-less`.

/cc @stylelint/core @AleshaOleg @ai

**Comment by hudochenkov** [comment]
Related discussion in PR https://github.com/stylelint/stylelint/pull/1899.

Also there was related discussion in https://github.com/stylelint/stylelint/pull/2438. /cc @edg2s

**Comment by evilebottnawi** [comment]
@hudochenkov let's give last chance community to see this, i something to do :smile:

**Comment by AleshaOleg** [comment]
@evilebottnawi I will support `postcss-sass`, but first I need to finish it a bit more. More details: #2486. Next release, I planned in two weeks. I hope after all the tests will pass, except one which is associated with the [gpa](https://github.com/tonyganch/gonzales-pe) parser. Issue [there](https://github.com/tonyganch/gonzales-pe/issues/264). So, this problem still will not allow to run `postcss-sass`

**Comment by ai** [comment]
I posted, but nobody answered 😕

I will try to post it again tomorrow

**Comment by TrySound** [comment]
I vote for splitting parsers from core. This will let to use whatever parsers users want. Same as babel-eslint.

**Comment by evilebottnawi** [comment]
@TrySound problems not in `splitting`, problems that many rules before linting use `isStandard*`and skip lint if it is not standard construction, and each new `parser` for non-standard syntax have unique specific syntactic overlay (nested declaration as example) and it is requires add new check in `isStandard`, we can't take into account all these features for all possible non standard syntax. 

Maybe if all parses have flag `compatibility: true` (compatibility with standard css) for each node, we will can solve this problem globally, but it is in theory and a lot of work :sob: . I think it is question more related to @ai .

**Comment by Nikolay-Govorov** [comment]
Hi!

I am ready to take this project under my care.

**Comment by evilebottnawi** [comment]
@Nikolay-Govorov it is good, source repo https://github.com/webschik/postcss-less, also your can try to linking with @webschik and help with this :+1: or create fork and starting resolve issues

**Comment by shellscape** [comment]
I've reached out to @webschik via email and linkedin to see if there's any possibility of transferring repo and npm ownership. The [Lesshint](https://github.com/lesshint/lesshint/issues/380) project has a vested interest in the module seeing continued development, as it's core to the project.

Should we not hear back from the owner... The project has two pending PRs which are rather urgent, and 5 probably-valid issues. I don't see a fork on Nikolay's profile, so I'll volunteer to fork, cherry pick the two PRs, attempt to resolve the pending issues, and publish to npm under a new name - if that's something you folks are interested in using.

**Comment by evilebottnawi** [comment]
@shellscape it great! Keep us informed as soon as you decide on the issues into https://github.com/lesshint/lesshint/issues/380. I will help your with this and integrate fork with `stylelint` :+1:

**Comment by evilebottnawi** [comment]
@shellscape also we can investigate about migrate `stylelint-less` (we have good core api and many good features - cache, globing, ignoring and etc).

**Comment by shellscape** [comment]
@Nikolay-Govorov I'm not sure what you mean. I don't see you listed on the contributors here: https://github.com/webschik/postcss-less/graphs/contributors. Do you mean that you were added to the repo as a collaborator? If so, what are your plans for updating the project? I'd like to make sure it doesn't fall into a state of neglect again :)

**Comment by Nikolay-Govorov** [comment]
@shellscape yes, I mean, thah me added to the repo as a collaborator :) I intend to close the current issue, and then do the work with the new version of postcss. If you have any tips on how best to proceed, I'm open to suggestions.

**Comment by shellscape** [comment]
@Nikolay-Govorov that's wonderful, congrats!

**Comment by shellscape** [comment]
some good news. I spoke with webschik and he's transferred the repo, for which I'll be able to dedicate time.

while I don't feel that this project should deprecate LESS support, it does raise a tangential question about the version of node the code in postcss-less targets, which is currently node 4x, same as styelint. I jumped into the convo on #2497 a bit late, but I'd like to move postcss-less into the present, using the best parts of node 6x. However, that might have an impact on stylelint using it, and for users stuck on old node. Does anyone have suggestions about how to get around these limitations?

**Comment by evilebottnawi** [comment]
@shellscape i think it is normal and breaking changes, just add note about this in `CHANGELOG`?

**Comment by Arcanemagus** [comment]
@evilebottnawi He means that `postcss-less` would no longer be compatible with the minimum version of Node.js that `stylelint` supports... meaning it couldn't be used here unless there is a way to get around those limitations.

@shellscape Have you looked into using `babel`? You could write all the code in ES6+ and have `babel` transpile it down to something usable in the ancient Node.js v4.

**Comment by evilebottnawi** [comment]
@Arcanemagus in theory we can add caveat about this

**Comment by shellscape** [comment]
@Arcanemagus postcss-less presently uses babel. There's so little reason to use babel anymore other than ES6 module support, and that's dropping in Node v8 (V8 already has support for it hidden behind flags, so it's coming soon). Babel had it's place before Node started catching up - I'm not a fan of transpiling, but do it when I have to.

**Comment by Arcanemagus** [comment]
> I'm not a fan of transpiling, but do it when I have to.

Very much with you there, it's the only method I know to write good code and still have it run in terrible environments which is why I suggested it 😉

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/stylelint/stylelint/pull/2547, `less` still alive :smile:
