### ISSUE TITLE
Add rule for blacklisting class names

### ISSUE THREAD

**Issue by ryanve** [stylelint/stylelint#2535]
[I have a situation where having a rule to blacklist classes as an array would be useful](http://stackoverflow.com/q/43641059/770127). Is there a way to do this currently? Would it be possible to add such a rule?

**Comment by evilebottnawi** [comment]
@ryanve please use template, we already have rule for this https://stylelint.io/user-guide/rules/selector-class-pattern/

**Comment by ryanve** [comment]
In that case how bout https://github.com/stylelint/stylelint/issues/2541
