### ISSUE TITLE
SugarSS not supported by stylelint-config-standard

### ISSUE THREAD

**Issue by FezVrasta** [stylelint/stylelint#2537]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I have some SugarSS files I want to lint, as soon I enable stylelint with the following `.stylelintrc`:

```
{
  "extends": "stylelint-config-standard"
}
```

I get a ton of errors.

```
  3:5   ✖  Expected single space before "{"                    block-opening-brace-space-before
 10:22  ✖  Unexpected leading zero                             number-leading-zero
 13:16  ✖  Expected single space before "{"                    block-opening-brace-space-before
 14:33  ✖  Expected a trailing semicolon                       declaration-block-trailing-semicolon
 15:2   ✖  Expected newline before "}" of a multi-line block   block-closing-brace-newline-before
 16:10  ✖  Expected single space before "{"                    block-opening-brace-space-before
 28:17  ✖  Expected single space before "{"                    block-opening-brace-space-before
 29:19  ✖  Expected a trailing semicolon                       declaration-block-trailing-semicolon
 30:4   ✖  Expected newline before "}" of a multi-line block   block-closing-brace-newline-before
 31:13  ✖  Expected single space before "{"                    block-opening-brace-space-before
 45:16  ✖  Expected single space before "{"                    block-opening-brace-space-before
 46:23  ✖  Expected a trailing semicolon                       declaration-block-trailing-semicolon
 47:6   ✖  Expected newline before "}" of a multi-line block   block-closing-brace-newline-before
 49:53  ✖  Expected single space after ":"                     media-feature-colon-space-after
 49:86  ✖  Expected single space before "{"                    block-opening-brace-space-before
```

etc

> Which rule, if any, is this issue related to?

I don't think it's a rule problem but more a bug with the way SugarSS (.sss) files are parsed..

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo
  color: pink
  color: red
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

`7.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

```bash
▶ echo ".foo\n  color: pink\n  color: red" | stylelint --syntax sugarss

<input css 1>
 1:4   ✖  Expected single space before "{"                    block-opening-brace-space-before
 3:12  ✖  Expected a trailing semicolon                       declaration-block-trailing-semicolon
 3:13  ✖  Expected newline before "}" of a multi-line block   block-closing-brace-newline-before
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

SugarSSS + postcss-nested

> What did you expect to happen?

No errors to be flagged

> What actually happened (e.g. what warnings or errors you are getting)?

See log above.

**Comment by jeddy3** [comment]
@FezVrasta Thanks for using the template.

You'll need to turn off the punctuation rules that aren't applicable to SugarSS. This is [documented in the `stylelint-config-standard` README](https://github.com/stylelint/stylelint-config-standard#using-the-config-with-sugarss-syntax).

**Comment by FezVrasta** [comment]
I see, thank you and sorry for the issue then.
