### ISSUE TITLE
Let selector-class-pattern accept a function

### ISSUE THREAD

**Issue by ryanve** [stylelint/stylelint#2541]
It'd be useful if [selector-class-pattern](https://stylelint.io/user-guide/rules/selector-class-pattern/) could accept a function for custom checking. [Regex gets complicated](http://stackoverflow.com/q/43641351/770127). Being able to supply a function allows for more readable and capable checking.

```
module.exports = {
  rules: {
    "selector-class-pattern": function(className) {
      var allowed = /^[a-z0-9-]+$/ 
      var blacklist = ['red', 'blue']
      return allowed.test(className) && blacklist.indexOf(className) === -1
    }
  }
};
```

**Comment by jeddy3** [comment]
Thanks for the suggestion. For instances where regex isn't enough then we recommend writing a plugin specific to your needs. Plugins are the go-to feature for extending stylelint. There's a [guide in the docs](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) on how to do this. For the sake of consistency, rule configuration objects are compatible with JSON and YAML.

**Comment by ryanve** [comment]
@jeddy3 Thanks—I just might make a plugin for this :)
