### ISSUE TITLE
The node_modules directory isn't ignored

### ISSUE THREAD

**Issue by vadim-chernev8** [stylelint/stylelint#2543]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'm using Ionic2 with PostCss plugin stylelint the problem is with ignore path in stylelint options 

> What stylelint configuration is needed to reproduce this issue?

{
  "extends": "stylelint-config-sass-guidelines",
  "plugins": [
    "stylelint-scss",
    "stylelint-order"
  ],
  "rules": {
    "scss/dollar-variable-pattern": "[A-Z][a-z]*([A-Z][a-z]*)*",
    "scss/selector-no-redundant-nesting-selector": true,
    "order/properties-alphabetical-order": null,
    "max-nesting-depth": 3,
    "string-quotes": "double",
    "color-hex-length": "long"
  }
}

My ignore file 

node_modules/
tmp/
temp/
hooks/
platforms/
plugins/
www/

> Which version of stylelint are you using?
"stylelint": "7.10.1"

> How are you running stylelint: CLI, PostCSS plugin, Node API?

{
   postCssPlugins: [
     require('stylelint')({
       configFile: '.stylelintrc',
       ignorePath: '.stylelintignore'
     })
   ],
 }

> What did you expect to happen?

No warnings in console

> What actually happened (e.g. what warnings or errors you are getting)?

it's steel not excluding node_modules

**Comment by jeddy3** [comment]
In `stylelint@7.10.1` the `node_modules` directory is ignored by default, regardless of what's in your `.stylelintignore` file. So, it should be ignored.

Can you try using stylelint via the CLI - do you experience the same behaviour?

Can you please also create reproducible test repo to help us help you?

**Comment by jeddy3** [comment]
Closing. Feel free to reopen if you're able to create a reproducible test repo for us.
