### ISSUE TITLE
Advocate support through opencollective rather than bountysource

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#2544]
I think we should try, many people are interested in helping open source software. As my practice showed with `webpack` it really works and people ready to help. Due to small financing, we can make our product better.

It will also be good to add this information to the `README` in a visible place and on the site so that more people know that they can help.

/cc @stylelint/core

**Comment by jeddy3** [comment]
LGTM.

**Comment by evilebottnawi** [comment]
@jeddy3 It is required to be `owner`, can your found time for this (registration and adding infromation to README and on site)

**Comment by jeddy3** [comment]
I've applied for opencollective. If we are accepted I'll update the `README.md`.

**Comment by BannerCoe** [comment]
Hello I'm beginner. I want to contribute this project. But I don't know where to start. Please help me.

**Comment by evilebottnawi** [comment]
@BannerCoe It is great! Thanks! In near future we will complete integration with `opencollective` and update `README.md`. Thanks again!

**Comment by jeddy3** [comment]
> I want to contribute this project. But I don't know where to start.

@BannerCoe Thanks for offering to help. There is a [list of things](https://github.com/stylelint/stylelint/blob/master/README.md#help-out) you can help with. Some issues are labelled as ["beginner friendly"](https://github.com/stylelint/stylelint/issues?q=is%3Aissue+is%3Aopen+label%3Abeginner-friendly) - addressing one of these would be a good first contribution. Lastly, [here is a guide](https://opensource.guide/how-to-contribute/) to contributing to a open source project. Good luck!

**Comment by BannerCoe** [comment]
Thanks @jeddy3 and @evilebottnawi

**Comment by renatinhotsw** [comment]
Hi, I'm a beginner. I want to contribute with this project. But I do not know where to start. Please help me.

**Comment by ntwb** [comment]
Open Collective was added in #2955
