### ISSUE TITLE
Add `block-closing-brace-empty-line-after`

### ISSUE THREAD

**Issue by wouter-muller** [stylelint/stylelint#2560]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature request

> Which rule, if any, is this issue related to?

`block-closing-brace-empty-line-before`

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

any

> Which version of stylelint are you using?

`7.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --config .stylelintrc "src/css/**/*.scss"`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

Is it an idea to add a `block-closing-brace-empty-line-after` so i can structure my CSS like this:
```
.selector {
  width: 100%;
}
     <--- this empty line
selector2 {
  width: 100%;
}
```
Or is there another way to do this?

I did not find anything about this, except http://stackoverflow.com/questions/40593334/stylelint-force-empty-line-at-bottom-of-nested-block

**Comment by jeddy3** [comment]
@wouter-muller Thanks for the request and for using the issue template.

I answered [your question in stylelint-scss](https://github.com/kristerkari/stylelint-scss/issues/118#issuecomment-299859239) just before I saw this issue. The same advice applies here. Only in this case, you'll want to use `rule-empty-line-before: "always"`.

**Comment by wouter-muller** [comment]
Thanks @jeddy3!
