### ISSUE TITLE
Add stylelint-no-unsupported-browser-features to Plugins page

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#2578]
Let’s add [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features) to [Plugins](https://stylelint.io/user-guide/plugins/).

**Comment by hudochenkov** [comment]
It's already there https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md Website updates when we release new version, because info came from stylelint package. We'll release new version soon.
