### ISSUE TITLE
Two exceptions cancel each other out

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#258]
Given this config:

```js
    'at-rule-empty-line-before': [2, 'always', {
      except: ['blockless-group', 'all-nested'],
    }],
```

and this CSS:

```css
.ht-Input {
  @mixin input-base;
  @mixin input-skin;
}
```

We have a problem. This is a nested blockless group -- so it matches two exceptions --- so those exceptions actually cancel each other out and I get a warning here.

I'm thinking that the workable solution probably is to only attend to one matched exception at a time. So if one exception matches the context and the expectation is reversed, we don't pay attention to other exceptions. Do @stylelint/owners think that's the right fix?

**Comment by jeddy3** [comment]
Just to double check, you're saying that *primary* expectation is reverse if *any* of the except conditions are met.

If so, that SGTM.

**Comment by jeddy3** [comment]
Oops. Just saw your PR. That's exactly what you're saying, so ignore the above comment :)

**Comment by davidtheclark** [comment]
Yes. You can see the file change in the PR making this happen --- combining all the exception checks into *one* exception check, really, that can only reverse the primary expectation *once*.

**Comment by davidtheclark** [comment]
Sweet. Thanks. After merging this the whole stylesheet setup at my job runs through clean! So I'm looking forward to implementing 0.1.0 when I get back from this little trip.

**Comment by jeddy3** [comment]
That's awesome!

Enjoy your trip and we'll cut a release when you're back! :)
