### ISSUE TITLE
Invalid CssSyntaxError for expressions followed by non unit nor ;

### ISSUE THREAD

**Issue by soswow** [stylelint/stylelint#2584]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where an expression is followed by non-unit or semicolon.

> Which rule, if any, is this issue related to?

This is CssSyntaxError.

> What CSS is needed to reproduce this issue?

This causing me a problem and I can't find a workaround for it.
```css
&:focus {
    box-shadow: 0 0 0 ${width} ${color};
    outline: none;
  }
```

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

7.10.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `node_modules/.bin/stylelint <my file>`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS expression. Also we use `stylelint-processor-styled-components` and example above is inside this function:
```js
const createFocusRing = (color = defaultColor, width = '2px') => css`
  &:focus {
    box-shadow: 0 0 0 ${width} ${color};
    outline: none;
  }
`;
```

> What did you expect to happen?

No exception.

> What actually happened (e.g. what warnings or errors you are getting)?

The following exception:

```shell
<my file>
 4:23  ✖  Missed semicolon   CssSyntaxError
```

**Comment by soswow** [comment]
Most likely a duplicate of https://github.com/styled-components/stylelint-processor-styled-components/issues/20 Please confirm and close if so.

**Comment by hudochenkov** [comment]
@soswow Thanks for using issue template!

I'm sure it's a problem with `stylelint-processor-styled-components`. We don't support JavaScript interpolation in style sheets, so I suppose `stylelint-processor-styled-components` handle this and provide something supported to stylelint. This code doesn't throw any errors in stylelint.

```css
&:focus {
    box-shadow: 0 0 0 2px red;
    outline: none;
}
```

**Comment by evilebottnawi** [comment]
@stylelint/core I think more and more often that perhaps we should take the often used and important parts of our ecosystem. I understand that this will take even more time, but we can try to look for additional contributors. It's sad, but it often happens that people can not configure something and stop using the project.
