### ISSUE TITLE
Feature request: --watch mode

### ISSUE THREAD

**Issue by chrisregner-com** [stylelint/stylelint#2585]
I think it would be nice (and common to packages like this) to have stylelint run upon file change.

**Comment by evilebottnawi** [comment]
@chrisregner-com hm, what your use case, many build and bundler system have watch mode (webpack, grunt, gulp and etc.)

**Comment by chrisregner-com** [comment]
I intend to separate my lint commands (currently eslint and stylelint) from build command (with webpack) so that I could get away with commenting some stuff out without cluttering my console, and have a separate console that is concerned only with linting.

**Comment by evilebottnawi** [comment]
@chrisregner-com seems `eslint` also not support `watch` mode and have separate package for this https://github.com/rizowski/eslint-watch

**Comment by chrisregner-com** [comment]
Hmm, you're right. Do you know by any change a similar package that does the same thing for stylelint?

**Comment by evilebottnawi** [comment]
@chrisregner-com in theory your can use `stylelint` as `postcss` plugin and use `postcss-cli` in `watch` mode https://www.npmjs.com/package/postcss-cli

**Comment by chrisregner-com** [comment]
Great! Didn't think of using `postcss` that way. I suppose you have no plan of implementing this feature, may I know why?

**Comment by evilebottnawi** [comment]
@chrisregner-com Label is discussion :smile: I would like to hear other members about this

**Comment by davidtheclark** [comment]
I think it should be a separate tool. This separate tool can then handle whatever complexities watching entails, while stylelint can focus on the linting.

**Comment by hudochenkov** [comment]
I don't see a need for watch mode in the stylelint core because most users already have it when using their build tools or in code editors.

**Comment by jeddy3** [comment]
@chrisregner-com Thanks for the suggestion. 

It looks like the team is in agreement with David's sentiment:
 
> I think it should be a separate tool. This separate tool can then handle whatever complexities watching entails, while stylelint can focus on the linting.

Feel free to create a separate tool and add it to the list of [complementary tools](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md).
