### ISSUE TITLE
Add default support for HTML, Markdown, Vue component

### ISSUE THREAD

**Issue by gucong3000** [stylelint/stylelint#2592]
The existing [processors API](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/processors.md) is not compatible with __autofixes__.

I suggest to use [opts.syntax](http://api.postcss.org/global.html#syntax)

**Comment by sergesemashko** [comment]
@gucong3000, [processors API](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/processors.md) doesn't mean to be compatible with postCSS syntax api, as per documentation:

> Processors can enable stylelint to lint the CSS within non-stylesheet files. For example, let's say you want to lint the CSS within `<style>` tags in HTML. If you just feed stylelint your HTML code, you'll run into problems, because PostCSS does not parse HTML. Instead, you can create a processor that does the following:
> 
> -   In the `code` processor function, extract CSS from the `<style>` tags in the HTML code. Return a CSS string containing all that extracted CSS, which is what stylelint will inspect.
> -   Build a sourcemap while performing the extraction, so warning positions can be tailored to match the original source HTML.
> -   In the `result` processor function, modify the line/column position of each warning using your sourcemap.

I'm curious, tho, what are the use cases and why is it necessary? To introduce a breaking change there should be cases and benefits that worth it.

**Comment by sergesemashko** [comment]
It looks like this issue is not going to be resolved, let's let it sit in the issue queue for maybe couple of days, and if there are no additional clarifications, we'll close it.

**Comment by gucong3000** [comment]
In #2596, I use postcss syntax `postcss-html` to support `*.md`, `*.vue`, It is compatible with autofixes.

**Comment by xx999** [comment]
Hi @gucong3000,
 is it supported for now in *.vue files ?

**Comment by gucong3000** [comment]
@xx999 Not yet. But you can use cli arguments

```shell
stylelint "**/*.vue" --custom-syntax postcss-html
```

**Comment by abdonrd** [comment]
@gucong3000 and how to use it in HTML files? Thanks in advance!

**Comment by gucong3000** [comment]
@abdonrd 
```shell
stylelint "**/*.{vue,html.htm}" --custom-syntax postcss-html
```

**Comment by abdonrd** [comment]
@gucong3000 When I run:

`stylelint "**/*.{css,html}" --custom-syntax postcss-html`

I get:

`Error: Could not find "postcss-html". Do you need a `configBasedir`?`

But the `postcss-html` is on the devDependencies:

https://github.com/stylelint/stylelint/blob/0c27c3ba92bf1b34d9e50af497ad4efa654f5a67/package.json#L95

I should add the `postcss-html` to my devDependencies?

**Comment by gucong3000** [comment]
> I should add the `postcss-html` to my devDependencies?

Yes. `npm i --save-dev postcss-html`

> The number reference lines are wrong.

I'd like to know the content of HTML.

> The `--fix` command breaks the `.html` files.

What kind of breaks?
 
> Only maintains the CSS code.

Don't you think it's should to be like that?

**Comment by abdonrd** [comment]
Thanks @gucong3000!

Example about the number lines:
https://gist.github.com/abdonrd/13589481a848f9bca50e41e950b0e8f1

<img width="670" alt="screen shot 2017-10-10 at 11 15 29" src="https://user-images.githubusercontent.com/1007051/31378686-6450b0ac-adac-11e7-878d-77d183dd8bb9.png">

Example about the `--fix` output:

<img width="664" alt="screen shot 2017-10-10 at 11 18 58" src="https://user-images.githubusercontent.com/1007051/31378855-da94fa70-adac-11e7-943e-07a043f31567.png">

**Comment by pateroski** [comment]
![captura de pantalla 2017-10-10 a las 14 38 02](https://user-images.githubusercontent.com/14295682/31386970-01ad7576-adc9-11e7-8429-4c2bf8561c03.png)
@abdonrd @gucong3000 Actually i've found that only where file contains only ```<style>``` tags detects correctly the line where it takes the error: 
![captura de pantalla 2017-10-10 a las 14 37 39](https://user-images.githubusercontent.com/14295682/31386963-f966bcf6-adc8-11e7-8fcf-7fd757d75aa9.png)

**Comment by gucong3000** [comment]
@abdonrd Is there something unusual in the config file?

**Comment by abdonrd** [comment]
@gucong3000 oh! I forget remove the processor:

```json
"processors": ["stylelint-processor-html"],
```

Now the number lines and the `--fix` works! 🎉 

In a near future the `postcss-html` will be integrated in stylelint? It would be great!

<hr>

But I have one issue with the `--fix`: It doesn't respect the indentation:

<img width="686" alt="screen shot 2017-10-11 at 09 58 16" src="https://user-images.githubusercontent.com/1007051/31428342-bdeb4c80-ae6a-11e7-92f1-35620737c101.png">

**Comment by abdonrd** [comment]
Thanks!

Now with the `v8.3.0` it works only with the `package.json` as:

```json
{
  "devDependencies": {
    "stylelint": "^8.3.0"
  },
  "scripts": {
    "lint:stylelint": "stylelint **/*.{css,html} --ignore-path .gitignore",
  }
}
```

And run:

```
npm run lint:stylelint
```

Any news about the identation issue?

**Comment by gucong3000** [comment]
@abdonrd
> it works only with the `package.json`

I don't quite understand, do you mean there are other way that can't work?

> Any news about the identation issue?

#3043

**Comment by abdonrd** [comment]
@gucong3000 I was just summarizing that now it's very simple! 👏 

Thanks for the issue! 👍
