### ISSUE TITLE
Allow `false` for some rules as an override for extended rulesets

### ISSUE THREAD

**Issue by TrevorSayre** [stylelint/stylelint#2594]
https://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values/

In our project we are using `stylelint-config-standard` but would like to override one of the rules.

The rule `shorthand-property-no-redundant-values` only has an option for `true`.

Since there is no option for `false`, we cannot override the rule.

The following `.stylelintrc` will throw an error.

```JSON
{
  "extends": "stylelint-config-standard",
  "rules": {
    "shorthand-property-no-redundant-values": false
  }
}
```

**Comment by jeddy3** [comment]
Are you trying to _enforce_ redundant values? That's a use case we've not accounted for. What's your reasoning, so we can better consider the request?

If you just want to turn off the rule,  [use `null`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-disable-a-rule).

**Comment by TrevorSayre** [comment]
We're trying to allow redundant, not enforce. Using `null` solves our problem, thank you :)
