### ISSUE TITLE
What is the difference between Head and 7.10.1

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2599]
Head https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#head
7.10.1 https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#7101

**Comment by evilebottnawi** [comment]
@jitendravyas This is what will be in the next version

**Comment by ntwb** [comment]
Indeed, most of what is in HEAD will be released as part of stylelint 7.11.0
