### ISSUE TITLE
Cannot run in gulp

### ISSUE THREAD

**Issue by morishitter** [stylelint/stylelint#260]
Hi, I tried to use stylelint, but could not run in gulp.

This is the task code:

```js
gulp.task('postcss', function () {
  var postcss = require('gulp-postcss');
  var autoprefixer = require('autoprefixer-core');
  var stylelint = require('stylelint');
  var reporter = require('postcss-reporter');

  var processors = [
    autoprefixer({
      browsers: [
      'ios >= 6',
      'android >= 2.3'
      ]
    }),
    stylelint(),
    reporter({
      clearMessages: true,
    })
  ];

  return gulp.src('sample.css')
    .pipe(postcss(processors))
    .pipe(gulp.dest('build/'));
});
```

Is this a bug?

Thanks.

**Comment by tgfjt** [comment]
is it stylelint@`0.0.0`?

**Comment by morishitter** [comment]
@tgfjt Yes.

**Comment by tgfjt** [comment]
@morishitter 
`0.0.0` is just empty module. :sob: 

We can install from master:
`$ npm install stylelint/stylelint && cd node_modules/stylelint && npm i && cd ../..`

**Comment by morishitter** [comment]
@tgfjt Oh... thanks :D

**Comment by jeddy3** [comment]
@tgfjt Thanks for answering this!

@morishitter We're hoping to release `0.1.0` really soon. Just a few of us have been testing `master` for the last couple of weeks. So if you run into any more issues just let us know and we'll help out as best we can, as we're keen to iron out all the bugs before `0.1.0` :)

One thing I noticed is that you'll need to add a config to your setup and it might be best to run stylelint before autoprefixer i.e.:

```js
gulp.task('postcss', function () {
  var postcss = require('gulp-postcss');
  var autoprefixer = require('autoprefixer-core');
  var stylelint = require('stylelint');
  var reporter = require('postcss-reporter');

  var processors = [
    stylelint({  // use stylelint before autoprefixer
      "rules": { // your config goes here
        "number-trailing-zero": 2
      }
    }),
    autoprefixer({
      browsers: [
      'ios >= 6',
      'android >= 2.3'
      ]
    }),
    reporter({
      clearMessages: true,
    })
  ];

  return gulp.src('sample.css')
    .pipe(postcss(processors))
    .pipe(gulp.dest('build/'));
});
```

If you don't want to hand-craft your own config you can use our first [shareable config](https://github.com/stylelint/stylelint#shareable-configs), which checks against the [suitcss styleguide](https://github.com/suitcss/suit/blob/master/doc/STYLE.md) e.g.

```js
gulp.task('postcss', function () {
  var postcss = require('gulp-postcss');
  var autoprefixer = require('autoprefixer-core');
  var stylelint = require('stylelint');
  var configSuitcss = require("stylelint-config-suitcss"); // require config
  var reporter = require('postcss-reporter');

  var processors = [
    stylelint(configSuitcss), // use suitcss config
    autoprefixer({
      browsers: [
      'ios >= 6',
      'android >= 2.3'
      ]
    }),
    reporter({
      clearMessages: true,
    })
  ];

  return gulp.src('sample.css')
    .pipe(postcss(processors))
    .pipe(gulp.dest('build/'));
});
```

As with `stylelint` you'll need to install the config from `master` until we release `0.1.0` i.e.

```console
npm install stylelint/stylelint-config-suitcss
```

Please don't hesitate to give us a shout if you run into anymore issues using the linter :)

**Comment by morishitter** [comment]
@jeddy3 I was sure that `0.1.0` was released. I will try to use it. Thanks :D

**Comment by davidtheclark** [comment]
@morishitter I'm running it via `gulp-postcss` and it's been working swell :)

**Comment by morishitter** [comment]
BTW, Why are flags to configure rules `0` and `2`?
`true` and `false` or `0` and `1` feel better for me :)

**Comment by davidtheclark** [comment]
In the future we plan to make 0 = ignore, 1 = warning, 2 = error, just like http://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by morishitter** [comment]
@davidtheclark I see. Thanks :)
