### ISSUE TITLE
Postcss + TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mdavidmorton** [stylelint/stylelint#2603]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

TypeError thrown when using stylelint with postcss (and Gulp)

> What stylelint configuration is needed to reproduce this issue?

```js
const precss    = require('precss');
const postcss   = require('gulp-postcss');
const reporter  = require('postcss-reporter');
const stylelint = require('stylelint');

// Other plugins and config ...

gulp.task('css', () => {
  let plugins = [
    precss,
    cssnext({warnForDuplicates: false}),
    autoprefixer,
    cssnano({filterPlugins: false}),
    stylelint(),
    reporter({clearMessages: true}),
  ];

  return gulp.src(config.postcss.src)
    .pipe(postcss(plugins))
    .pipe(gulp.dest(config.postcss.dest));
});
```

> Which version of stylelint are you using?

`7.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

As a postcss plugin via gulp task. See above configuration

> What did you expect to happen?

No exceptions. Reporter should have identified any style issues.

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
events.js:160
  throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'length' of undefined
  at module.exports (/Users/davidmorton/dev/pattern-library/node_modules/stylelint/lib/utils/declarationValueIndex.js:9:41)
  at /Users/davidmorton/dev/pattern-library/node_modules/stylelint/lib/rules/declarationBangSpaceChecker.js:9:25
  at /Users/davidmorton/dev/pattern-library/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:192:28
  at /Users/davidmorton/dev/pattern-library/node_modules/postcss-partial-import/node_modules/postcss/lib/container.js:148:26
  at Rule.each (/Users/davidmorton/dev/pattern-library/node_modules/postcss-partial-import/node_modules/postcss/lib/container.js:114:22)
  at Rule.walk (/Users/davidmorton/dev/pattern-library/node_modules/postcss-partial-import/node_modules/postcss/lib/container.js:147:21)
  at /Users/davidmorton/dev/pattern-library/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:150:32
  at Root.each (/Users/davidmorton/dev/pattern-library/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:114:22)
  at Root.walk (/Users/davidmorton/dev/pattern-library/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:147:21)
  at Root.walkDecls (/Users/davidmorton/dev/pattern-library/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:190:25)
```

Other issues (e.g. #1914) suggest using previous versions of stylelint. Those versions gave me the same error as that above. 

However, moving stylelint to the top of my postcss plugin list fixed the problem:

```js
let plugins = [
  stylelint(),
  precss,
  // ... other postcss plugins
];
```

**Comment by jeddy3** [comment]
> However, moving stylelint to the top of my postcss plugin list fixed the problem:

We recommend having stylelint as the first plugin in the PostCSS pipeline, otherwise stylelint is linting the output of the transformation plugins rather than your actual source code.

As an aside, it looks like either `precss`, `cssnext`, `autoprefixer` or `cssnano` is transforming your CSS code into something that breaks stylelint. It would be useful to investigate what that might be. Are you able to provide a _small snippet_ of CSS that triggers the error?

**Comment by mdavidmorton** [comment]
@jeddy3 I initially glossed over the documentation's reference to [plugin order](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#usage-examples). I submitted this issue at the request of @hudochenkov.

The problem appears to stem from the postcss-import module. This CSS will throw the error **if** the plugin order is wrong:

```css
@import 'partial';
```

And in _partial.css:

```css
body {
  font-size: 18px;
}
```

**Comment by jeddy3** [comment]
> The problem appears to stem from the postcss-import module. 

Thanks for digging deeper! 

It's good to know it's related to `postcss-import`, as I think we've [already address that](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#example-b) in the docs. In the example, we recommend using `postcss-imports`'s [plugins option](https://github.com/postcss/postcss-import#plugins). As such, I think we can close this issue.

> I initially glossed over the documentation's reference to plugin order. 

No worries :) You've a choice of either putting stylelint first in the pipeline or use `postcss-import`'s `plugins` option. Both are valid.

**Comment by hudochenkov** [comment]
Also we recommend use [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) for better reporting instead of using stylelint as PostCSS plugin.
