### ISSUE TITLE
Fix errors when running flow on stylelint as a dependency

### ISSUE THREAD

**Issue by lukedar** [stylelint/stylelint#2608]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where running flow against version 7.10.1 causes 40 errors.

> What stylelint configuration is needed to reproduce this issue?

install 'flow-bin' and run npm run flow without excluding node_module

> Which version of stylelint are you using?

7.10.1 

> What actually happened (e.g. what warnings or errors you are getting)?

```
node_modules/stylelint/lib/utils/hasEmptyBlock.js:11
 11:   statement/*: postcss$rule | postcss$atRule*/
                    ^^^^^^^^^^^^ identifier `postcss$rule`. Could not resolve name

node_modules/stylelint/lib/utils/hasEmptyBlock.js:11
 11:   statement/*: postcss$rule | postcss$atRule*/
                                   ^^^^^^^^^^^^^^ identifier `postcss$atRule`. Could not resolve name

node_modules/stylelint/lib/utils/isKeyframeRule.js:7
  7: module.exports = function (rule/*: postcss$rule*/)/*: boolean*/ {
                                        ^^^^^^^^^^^^ identifier `postcss$rule`. Could not resolve name

node_modules/stylelint/lib/utils/isStandardSyntaxAtRule.js:10
 10: module.exports = function (atRule/*: postcss$atRule*/)/*: boolean*/ {
                                          ^^^^^^^^^^^^^^ identifier `postcss$atRule`. Could not resolve name
```

I have added stylelint under [ignore] in .flowconfig but projects should not have to exclude node modules if not when imports of modules need to be stubbed,

**Comment by jeddy3** [comment]
@lukedar Thanks for the report and for using the template.

Can you try `master`, i.e. `npm i stylelint/stylelint`, and see you still get the same errors?

**Comment by lukedar** [comment]
@jeddy3 Thanks for your response. Unfortunately the same errors output with master.
Ive attached all the errors.

[errors.txt](https://github.com/stylelint/stylelint/files/1060957/errors.txt)

**Comment by irina-paxlife** [comment]
Hi all, I have the same issue on stylelint 7.12.0 and flow-bin 0.49.1. The errors are the same.
[stylelint errors.txt](https://github.com/stylelint/stylelint/files/1131223/stylelint.errors.txt)

**Comment by jeddy3** [comment]
@lukedar & @irina-paxlife This this still a problem with `master` and `flowbin@0.53.0`?

**Comment by jeddy3** [comment]
Should no longer be an issue with `stylelint@8.1.1`. Feel free to open a new issue (and hopefully a companion PR!) if that's not the case.

**Comment by jackwilsdon** [comment]
I'm still having this exact issue, checking out `stylelint` (master) into it's own folder and running `flow` on it is fine, it just seems to have issues when it's installed via `npm`. I tried installing both the master branch and 8.1.1 via `npm` but still had the issues with `flow`.

**Comment by jeddy3** [comment]
@jackwilsdon Thanks for the update. I'll reopen this. The flow stuff in stylelint has been getting a bit of love lately, so hopefully this can be resolved.

**Comment by jeddy3** [comment]
@jackwilsdon Also labelling as `help wanted`, so feel free to jump in a help out if can.

**Comment by CAYdenberg** [comment]
Reproduced with flow-bin@0.49.1, but errors disappear with flow-bin@0.53.0. Seems like we can safely close :balloon:

**Comment by jeddy3** [comment]
@CAYdenberg Thanks for digging into this! Good to see this resolved with flow-bin@0.53.0

**Comment by ivanzusko** [comment]
Have the same issue...
```
stylelint: 9.2.0,
flow-bin: ^0.70.0
```

**Comment by ivanzusko** [comment]
Looks like that when we run `flow` in our project - it can't find declarations in stylelint.

I've tried to add next to `.flowconfig`:
```
[libs]
./node_modules/stylelint/lib
```

This removed previous errors, but brought new ones. The first one was:

```
Library type error:
node_modules/stylelint/lib/dynamicRequire.js:5
  5:   return require(name);
              ^^^^^^^^^^^^^ The parameter passed to require() must be a literal string.
```

It's easy to fix with editing `.flowconfig`:
```
[options]
module.ignore_non_literal_requires=true
```

So, the `The parameter passed to require() must be a literal string.` error disappear.

But there still lots of another. For example, one of those:
```
Library type error:
node_modules/stylelint/lib/formatters/stringFormatter.js:88
 88:   const columnWidths = { 0: 1, 1: 1, 2: 1, 3: 1, 4: 1 };
                              ^^^^ non-string literal property keys not supported
```
and, as far as I can understand, it's not gonna be fixed by _flow_ devs very soon... [Source](https://github.com/facebook/flow/issues/380)

**CC** @jeddy3

**Comment by ivanzusko** [comment]
Changing `./node_modules/stylelint/lib` on `./node_modules/stylelint/decls` (in the `[libs]` section) resolved my issue.
Final `.flowconfig` looks like this:

```
[ignore]

[include]

[libs]
./node_modules/stylelint/decls

[options]
module.ignore_non_literal_requires=true

[lints]
```

**Comment by ntwb** [comment]
@ivanzusko Apologies for missing the above, could you create a new issue please.

We can then track the issue and the upstream issue you linked to.

If you have a fix an accompanying pull request would also be fantastic 😄
