### ISSUE TITLE
support for stylelint in package.json [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [stylelint/stylelint#2609]
`stylelint` supports the property in package.json but the loader is not reading from it. :)

**Comment by evilebottnawi** [comment]
@damianobarbati not related to `stylelint`, seems `loader` don't support configuration for stylelint

**Comment by damianobarbati** [comment]
Yes I noticed! `the loader is not reading from it`
Any plan to support this?

**Comment by sergesemashko** [comment]
@damianobarbati, seems like [stylelint-loader](https://www.npmjs.com/package/stylelint-loader) is deprecated, you might want to check out [https://github.com/JaKXz/stylelint-webpack-plugin](stylelint-webpack-plugin)

**Comment by damianobarbati** [comment]
no wait: I'm not using the loader but postcss plugin:

```
    loader: 'postcss-loader',
    options: {
        plugins: [
            autoprefixer({ browsers: config.browserslist }),
            styleLint({
                extends: 'stylelint-config-standard',
                plugins: ['stylelint-scss'],
            }),
        ],
        sourceMap: true,

```

**Comment by sergesemashko** [comment]
most likely `postcss-loader` is not reading the properties from package.json. As it was mentioned above, this is not related to `stylelint`

**Comment by jeddy3** [comment]
> you might want to check out [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin)

👍
