### ISSUE TITLE
"off" to turn off rule [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [stylelint/stylelint#2611]
Please add an option to disable a rule, like:
```
    "stylelint": {
        "extends": [
            "stylelint-config-standard",
            "stylelint-config-sass-guidelines"
        ],
        "rules": {
            "selector-list-comma-newline-after": false
        }
    },

```
This way we can have defaults but override (or better remove) rules which we don't want to apply at all (when no available option match the needs).

**Comment by evilebottnawi** [comment]
@damianobarbati use `null` for this purpose

**Comment by damianobarbati** [comment]
doh! I did try `false`... thanks!

**Comment by jitendravyas** [comment]
@evilebottnawi like this?

`"selector-list-comma-newline-after": null`

**Comment by hudochenkov** [comment]
@jitendravyas yes.

**Comment by timbru31** [comment]
What about supporting `false` for boolean rules, too? It's not obvious to use `null` over `false` for  a simple toggle on/off rule. Yes the documentation states that null turns off a rule, but I find it confusing.

**Comment by hudochenkov** [comment]
I found only [this explanation](https://github.com/stylelint/stylelint/issues/1922#issuecomment-249160716), why there is no support for `false`.

@stylelint/core as I remember no core rule has `false` as primary option. What do you think? Maybe it's time reconsider. We could add `false` to disable a rule in the next major version, as it is breaking change. `false` indeed is a more intuitive way to disable a rule.

**Comment by evilebottnawi** [comment]
@hudochenkov `false` is semantic value, example:
- `space-before-something`: `true` - mean your should add space before something
- `space-before-something`: `false` - mean your should not add space before something

**Comment by m-allanson** [comment]
@stylelint/core This is probably the most common support request on stylelint. Maybe we could add something to `validateOptions()` that detects people using `false` and advises them to use `null` instead? e.g.

```
false is an invalid option for rule "${ruleName}". If you'd like to disable this rule, use 'null'.
```

This would not be a breaking change, and still leaves us open to using `false` is a primary option if we really want.

**Comment by evilebottnawi** [comment]
@m-allanson sounds good

**Comment by hudochenkov** [comment]
@m-allanson good idea! But how to do it? We have to add this check and message for every rule?

**Comment by m-allanson** [comment]
@hudochenkov I think we can add it to [lib/utils/validateOptions.js](https://github.com/stylelint/stylelint/blob/d229a67723d7dfda0ca1ad605d43b92eadb62c77/lib/utils/validateOptions.js)?

**Comment by hudochenkov** [comment]
@m-allanson if we will show message for every rule, that has `false` option, how rule accept it without showing a message?

**Comment by jeddy3** [comment]
I think we can be more explicit in what we pass into the `validateOption` function from each of the `no-` rules i.e. they only accept a boolean value _set to true_. Plugins, or a future rule, might accept a boolean set to false or true, and it should be explicit about that.

**Comment by evanjmg** [comment]
this doesn't work for unknown rules, which is really annoying
