### ISSUE TITLE
stylelint + postcss running on processed css instead of original .scss

### ISSUE THREAD

**Issue by damianobarbati** [stylelint/stylelint#2612]
How can we have `stylelint` lint just original sources in webpack? Because processing the final output throws every error possible of course! 
Also: it's processing files multiple times, how come?

```
const extractCssLoaders = [{
    loader: 'css-loader',
    options: {
        modules: true,
        importLoaders: 2,
        camelCase: true,
        localIdentName: '[name]-[local]',
        minimize: process.env.NODE_ENV === 'development' ? false : { presets: 'default' },
        sourceMap: true,
    },
},{
    loader: 'postcss-loader',
    options: {
        plugins: [
            autoprefixer({ browsers: config.browserslist }),
            styleLint(config.stylelint),
            postcssReporter({
                clearReportedMessages: true,
                throwError: true,
            }),
        ],
        sourceMap: true,
    },
},{
    loader: 'sass-loader',
    options: {
        sourceMap: true,
    },
}];
```

**Comment by evilebottnawi** [comment]
@damianobarbati use plugin for webpack https://github.com/JaKXz/stylelint-webpack-plugin or move `stylelint` on top of postcss plugins

**Comment by damianobarbati** [comment]
- I tried to move stylelint on tops of plugins but same errors, same file processing multiple times and errors on processed files
- I tried using stylelint-webpack-plugin, no errors but it's still processing multiple times css!
- I'd really rather use the postcss plugins method for sake of consistence

Here a repro => https://github.com/damianobarbati/react-simple-app

@evilebottnawi thanks so much for helping <3

**Comment by damianobarbati** [comment]
@evilebottnawi with top you mean first or last? just to be sure, not working either way.. :(

**Comment by evilebottnawi** [comment]
@damianobarbati I am not familiar with linting on loaders and plugins. I don't use `lint` in `webpack` assembly, on large project it is very increases assembly time. For linting i use `npm` commands and `lint-staged`.

**Comment by ntwb** [comment]
Here's a couple of links to what's mentioned above:
https://github.com/okonet/lint-staged
https://github.com/awebdeveloper/pre-commit-stylelint

**Comment by jeddy3** [comment]
> For linting i use npm commands and lint-staged.

Also, this and [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin) allow you to use stylelint's [built-in](https://github.com/stylelint/stylelint/tree/master/lib/formatters) formatter.

Closing as I believe this is a toolchain issue, rather than a stylelint core one.
