### ISSUE TITLE
Add processors support to autofix 

### ISSUE THREAD

**Issue by abdonrd** [stylelint/stylelint#2617]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When I run `stylelint '**/*.{css,html}' --fix`, all the .html files are emptied (if the `.html` file doesn't have CSS) or only with the CSS code (if the `.html` file has CSS in a <style> tag).

> What CSS is needed to reproduce this issue?

Any CSS code in a `.html` file.

> What stylelint configuration is needed to reproduce this issue?

 The [stylelint-processor-html](https://github.com/ccbikai/stylelint-processor-html) without plugins.

> Which version of stylelint are you using?

`7.11.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint '**/*.{css,html}' --fix`.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

Keep the HTML code intact, only change the CSS code.

> What actually happened (e.g. what warnings or errors you are getting)?

All the .html files are emptied (if the `.html` file doesn't have CSS) or only with the CSS code (if the `.html` file has CSS in a <style> tag).

**Comment by hudochenkov** [comment]
Thank you for reporting! What stylelint configuration (config, plugins, processors) is needed to reproduce this issue?

**Comment by abdonrd** [comment]
Oops! Sorry, the https://github.com/ccbikai/stylelint-processor-html without plugins.

(when I get home, I add the config)

**Comment by hudochenkov** [comment]
As autofixing is experimental feature, we haven't investigated extra configurations. We need to make further investigation about using autofixing with processors.

Is it possible at all to use autofixing with them? If it is, then do we need to make changes to stylelint core or changes should be made to processors themselves.

For now you can only use autofixing only if you don't use any processors (non-standard syntaxes is supported, though).

**Comment by hudochenkov** [comment]
There is also an [issue](https://github.com/stylelint/stylelint/issues/2592) and [PR](https://github.com/stylelint/stylelint/pull/2596) on this topic.

**Comment by abdonrd** [comment]
Got it, thanks @hudochenkov!

**Comment by jeddy3** [comment]
Closing in favour of https://github.com/stylelint/stylelint/issues/2592
