### ISSUE TITLE
LESS's `extend` is not ignored in 7.11

### ISSUE THREAD

**Issue by ShayDavidson** [stylelint/stylelint#2618]
I've upgrade to 7.11 and suddenly I get this error in my LESS files:
`Unexpected unknown pseudo-class selector ":extend"`.

It happens for this declaration.
```css
.checkbox {
  &:extend(.external_checkbox all);
}
```

On 7.10.x it simply worked.

**Comment by hudochenkov** [comment]
Thank you for reporting! What your configuration?

**Comment by ShayDavidson** [comment]
That's what I run: `'stylelint \'./client/**/*.less\' --syntax less'`

**Comment by hudochenkov** [comment]
What is your config?

**Comment by ShayDavidson** [comment]
```
{
	"extends": [
		"stylelint-config-standard",
		"stylelint-config-css-modules"
	],
	"rules": {
		"indentation": "tab",
		"at-rule-no-unknown": null,
		"declaration-empty-line-before": [ "never", {
			"ignore": [
				"after-declaration",
				"after-comment",
				"inside-single-line-block"
			]
		}]
	}
}
```

**Comment by hudochenkov** [comment]
@evilebottnawi could you look into this issue, please? This commit caused regression https://github.com/stylelint/stylelint/commit/669ca6b69c7c13aecccec5e489d2301bfaa17ce1. 

Is it possible to put back:

```js
if (!isStandardSyntaxRule(rule)) {
  return
}
```

**Comment by evilebottnawi** [comment]
@hudochenkov `Unexpected unknown pseudo-class selector ":extend"` related to `selector-pseudo-class-no-unknown` rule and other

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/2625
