### ISSUE TITLE
Autofix strips semicolons from mixins

### ISSUE THREAD

**Issue by ShayDavidson** [stylelint/stylelint#2619]
I've run this command: `stylelint \'./client/**/*.less\' --fix --syntax less`, and stylelint ended up stripping all semicolons from my mixins.

For example:
`alert-help();` became `alert-help()` without the semicolon.

**Comment by hudochenkov** [comment]
Thank you for reporting!

It's probably we're using old and unstable Less parser. Related to https://github.com/stylelint/stylelint/pull/2547

**Comment by ShayDavidson** [comment]
Thanks - I'll ignore the problem for now with `disable-line` :)

**Comment by jwilsson** [comment]
I just tested this on the `v8` branch and it's working properly now (i.e. the semicolon is still there).
