### ISSUE TITLE
[FR?]Override rules of stylelint in file

### ISSUE THREAD

**Issue by uharbachou** [stylelint/stylelint#2621]
Hello,
i think it more feature request

For example i have two scss/less files. And its common practice to write brand colors in separate files. In one file i want all colors will be written as hex variables, but for other files support only variables. SCSS is more comfortable for that. btw i want for file variables turned on options for hex variables and for others turned off.

I have trying researching solutions and can't find. 
Thanks

PS: I know this is not place for questions but as i see it can be FR.

**Comment by jeddy3** [comment]
Stylelint is configurable with [configuration objects](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md). I suggest creating separate configurations objects/files for each of your use cases, then run stylelint for each use case, update your input glob accordingly `stylelint "*.less" --config stylelint-config-mylessone`. Use [`"extends"`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) to remove any duplication within them.

**Comment by uharbachou** [comment]
Great, thanks
