### ISSUE TITLE
How the team is deciding that which rules should gets auto-fix --fix first?

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2623]
As a request, I would like if this can be taken as priority https://stylelint.io/user-guide/rules/selector-pseudo-element-colon-notation/

**Comment by evilebottnawi** [comment]
@jitendravyas We do not have a specific list, but if your can help us with this, it will be just fine

**Comment by jeddy3** [comment]
It's an open source project. So, I believe it'll be whatever rules scratch our own personal itches.

@jitendravyas If `selector-pseudo-element-colon-notation` is your itch, then please consider contributing a PR for it.

**Comment by ntwb** [comment]
I've spent the past few days adding stylelint to an existing project, I've got a ~20,000 line patch in progress, I've been saving all the regex's I used so I'm hoping these will help me to create _fixes_ for the rules I found the most annoying to have to update manually, scratching an itch as @jeddy3 said
