### ISSUE TITLE
TypeError: Cannot read property 'syntax' of undefined with --fix

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2624]
```

❯ stylelint "app/styles/**/*.scss" --syntax scss --fix
TypeError: Cannot read property 'syntax' of undefined
    at stylelint._lintSource.then.postcssResult (/Users/jitendravyas/.nvm/versions/node/v6.10.0/lib/node_modules/stylelint/lib/standalone.js:156:74)
```

```

❯ stylelint "app/styles/**/*.scss" --fix
TypeError: Cannot read property 'syntax' of undefined
    at stylelint._lintSource.then.postcssResult (/Users/jitendravyas/.nvm/versions/node/v6.10.0/lib/node_modules/stylelint/lib/standalone.js:156:74)
```

Latest Stylelint `7.11.0` on Latest OSX and node/v6.10.0

**Comment by evilebottnawi** [comment]
@jitendravyas can your provide minimal reproducible test repo?

**Comment by jitendravyas** [comment]
I'm just using CLI to auto-fix .scss files

**Comment by jeddy3** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
