### ISSUE TITLE
is there any way to provide a processor via command line?

### ISSUE THREAD

**Issue by mmase** [stylelint/stylelint#2639]
I am interested in using stylelint with both `.scss` files and `.vue` files. I am able to get `.vue` to work nicely with `stylelint-processor-html`, but then the `.scss` files don't wory.

Is there a way to provide a separate processor for only `.vue` files or would this require entirely separate configs?

**Comment by jeddy3** [comment]
>  I am able to get .vue to work nicely with stylelint-processor-html, but then the .scss files don't wory.

Can you please clarify in what way it doesn't work? Do you get an error etc? 

> Is there a way to provide a separate processor for only .vue files or would this require entirely separate configs?

Not currently. You can use [`extends`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) to make using separate configs pretty effortless:

```js
// stylelint-config-mybase
{
  "rules" : { .. }
}
```

```js
// stylelint-config-mybasevue
{
  "extends": ["stylelint-config-mybase"],
  "processors": ["stylelint-processor-html"]
}
```

```console
stylelint "*.scss" --config stylelint-config-mybase
stylelint "*.vue" --config stylelint-config-mybasevue
```

**Comment by jeddy3** [comment]
Closing for now. Feel free to reopen with a clarification if using two configs isn't an acceptable solution.
