### ISSUE TITLE
Error: Cannot find module 'table'

### ISSUE THREAD

**Issue by bardware** [stylelint/stylelint#2640]
I use stylelint on the command line; Windows 10 box; Node 8.1.1. 
I call `node_modules\.bin\stylelint my.scss --fix` and get error `Error: Cannot find module 'table'`.
I manually install `npm i table -D`, call my command again and the error is gone.

**Comment by evilebottnawi** [comment]
@bardware your use `npm@5`? If yes, please don't use in production and in work, now they are very unstable

**Comment by ntwb** [comment]
Our Travis CI test suite is passing 100% perfect with Node.js 8.x and npm 5.x

Via https://travis-ci.org/stylelint/stylelint/jobs/242710531
```
$ node --version
v8.1.1
$ npm --version
5.0.3
```

I've also just tested this locally and I don't get any errors.

@bardware If you've just recently switched to Node.js 8 & npm 5 I'd suggest cleaning your npm cache via `npm cache clean --force` and removing your `node_modules` folder and reinstalling via `npm install`

**Comment by bardware** [comment]
> If you've just recently switched

I actually like to believe I did the first `npm install` on that project using node 8, but I would not want to vow.
I have no problem trusting your tests.
