### ISSUE TITLE
Poor linting of `@if` in SCSS

### ISSUE THREAD

**Issue by clarcharr** [stylelint/stylelint#2641]
The code:

```
@if $cond {
  // ...
} @else {
  // ...
}
```

Gets linted such that it should be changed to this:

```
@if $cond {
  // ...
}

@else {
  // ...
}
```

This seems like a poor suggestion IMO.

**Comment by ntwb** [comment]
You'll need to use [stylelint-scss](https://github.com/kristerkari/stylelint-scss)

Also GitHub issues are for stylelint bugs and enhancements, if you're looking for help or support with stylelint then stackoverflow is our preferred question and answer forum - http://stackoverflow.com/questions/tagged/stylelint
