### ISSUE TITLE
Case of line should be respected by `ignorePattern` in max-line-length

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2647]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where trying to ignore multiple patterns using `ignorePattern` in the `max-line-length` rule

This is a follow up to #2630

> Which rule, if any, is this issue related to?

`max-line-length`

> What CSS is needed to reproduce this issue?

```css
/*
Theme Name: Twenty Eleven
Theme URI: Theme URI: https://wordpress.org/themes/twentyeleven/styles/css/url/path/longer/than/80/chars
Author: the WordPress team
Author URI: https://wordpress.org/
Description: The 2011 theme for WordPress is sophisticated, lightweight, and adaptable.
Version: 2.6
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: blog, one-column, two-columns, left-sidebar, right-sidebar, custom-background.
Text Domain: twentyeleven
*/
```

> What stylelint configuration is needed to reproduce this issue?

```js
   "max-line-length": [ 80, {
      "ignore": "non-comments",
      ignorePattern: ["/(https?:\/\/[0-9,a-z]*.*)|(Description\:.+)|(Tags\:.+)/"],
    } ],
```

> Which version of stylelint are you using?

`7.11.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI via `stylelint test.css --config index.js`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

No warnings to be flagged on lines 3, 6, and 10

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
test.css
  3:106  ✖  Expected line length to be no more than 80 characters   max-line-length
  6:87   ✖  Expected line length to be no more than 80 characters   max-line-length
 10:84   ✖  Expected line length to be no more than 80 characters   max-line-length
```

Here's what a test of this I think should look like:
```js
testRule(rule, {
  ruleName,
  config: [ 20, { ignorePattern: "/(multiple\:.+)|(should\:.+)" } ],

  accept: [{
    code: "/*\n multiple lines in multiline comments\n should be able to be ignored\n*/",
  }],

})
```

I've tried various regex `g` and `m` modifiers in `ignorePattern` such as these with no luck:
• `  ignorePattern: ["/(https?:\/\/[0-9,a-z]*.*)|(Description\:.+)|(Tags\:.+)/gm"],`
• `  ignorePattern: ["/(https?:\/\/[0-9,a-z]*.*)|(Description\:.+)|(Tags\:.+)/g"],`
• `  ignorePattern: ["/(https?:\/\/[0-9,a-z]*.*)|(Description\:.+)|(Tags\:.+)/m"],`

**Comment by jeddy3** [comment]
Use `/(https?:\/\/[0-9,a-z]*.*)|(description\\:.+)|(tags\\:.+)/`. The line is lowercased before checking. We should change that behaviour in `8.0.0`

**Comment by jeddy3** [comment]
Done in #2683
