### ISSUE TITLE
Add --max-warnings <number> flag

### ISSUE THREAD

**Issue by alexilyaev** [stylelint/stylelint#2651]
A common use case among teams I've worked with is to show warnings in development, but fail the build if there are leftovers.

This was essential since minor stylistic glitches in code happen all the time and having them as errors really blocks the flow of the developer.  
Now with `defaultSeverity` we can set everything to `warning` and the devs are happy, dealing with them when they're comfortable.

But... if they forget, someone gotta fix those warnings, so we expect the build to fail (in CI, locally, etc.).

In ESLInt there is `--max-warnings <number>` CLI flag which works well for this scenario.  
Was wondering if we can have such a flag for Stylelint?

**Comment by jeddy3** [comment]
Sounds like a valid use case to me, and one that we could accept a PR for.

**Comment by alexilyaev** [comment]
@jeddy3 Can you direct me to which files should be changed and maybe suggest a way to implement? :-)

**Comment by jeddy3** [comment]
@alexilyaev Try [`/lib/cli.js`](https://github.com/stylelint/stylelint/blob/master/lib/cli.js#L243-L259). Here's how [eslint does it](https://github.com/eslint/eslint/blob/master/lib/cli.js#L182-L189).

**Comment by jeddy3** [comment]
Tracking in https://github.com/stylelint/stylelint/issues/2651
