### ISSUE TITLE
Ensure consistent case sensitivity across *-list rules and ignore* options

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2660]
Ref: https://github.com/stylelint/stylelint/pull/2626#issuecomment-309861380

**Comment by evilebottnawi** [comment]
@jeddy3 i think it should be case insensitivity, because protocol scheme case insensitivity https://tools.ietf.org/html/rfc3986#section-3.1.

**Comment by hudochenkov** [comment]
It isn't clear what this issue about. Would you mind adding more description, please?

**Comment by jeddy3** [comment]
Currently, all `*-*list` rules require their primary options to be lowercase. All the rules are case-insensitive when checking _for matches_, though. For example, `function-url-scheme-blacklist: "http"` will disallow both `http://g.co/x.jpg` and `HTTP://g.co/x.jpg`.

We can either document this limitation or address it.

I suggest we address it as `function-blacklist` currently requires lowercase function names, even though some functions are camelcase. For example, `function-blacklist: "translateX"` will never match anything. It currently needs to be configured as `function-blacklist: "translatex"`.

**Comment by evilebottnawi** [comment]
@jeddy3 Am i right what `function-blacklist` and other case sensitivity rules should have documentation about this (also be good add tests), other case insensitivity rules (like `function-url-scheme-blacklist`) should be documented too and have tests?

**Comment by jeddy3** [comment]
As we have the `*-case`rules, e.g. [`function-name-case`](https://github.com/stylelint/stylelint/tree/master/lib/rules/function-name-case) I think it'll be fine to standardise on case insensitive _primary options_ across all the `*-list*` rules.

For example, the any of the following configurations would all disallow `a { transform: translateX(10px); }`:

- `function-blacklist: "translateX"`
- `function-blacklist: "translatex"`
- `function-blacklist: "TRANSLATEX"`

Same with `function-url-scheme-blacklist`, either of the following configurations would disallow `http://g.co/x.jpg` and `HTTP://g.co/x.jpg`: 

- `function-url-scheme-blacklist: "http"`
- `function-url-scheme-blacklist: "HTTP"`

**Comment by evilebottnawi** [comment]
@jeddy3 all css functions case insensitivity, hist try in browser `transform: TRANSLATEX(20px);`

**Comment by jeddy3** [comment]
Good stuff, thanks for checking that. It [supports my proposal](https://github.com/stylelint/stylelint/issues/2660#issuecomment-309911294) to have case insensitive primary options.

**Comment by evilebottnawi** [comment]
@jeddy3 good, let's do this

**Comment by jeddy3** [comment]
On further my investigation, I believe my [initial suggestion](https://github.com/stylelint/stylelint/issues/2660#issuecomment-309911294) was wrong. Having whitelist, blacklists and `ignore*: []` secondary options be case insensitive by default is too much magic. It leads to problems like https://github.com/stylelint/stylelint/issues/2647. Users should _explicitly_ opt into case insensitivity by using regular expressions and the `i` flag.  This approach works well because we have all the `*-case` rules. It also means the behaviour of whitelist and blacklists and `ignore: []` is consistent across all rules, including `max-line-length` and `comment-word-blacklist`.

This PR enables the use of the `i` flag in regular expressions, and updates the code, tests and docs of the `*-whitelist` and `*-blacklist` rules, and any rules that have an `ignore*: []` secondary option.

This also fixes the current incorrect behaviour where users are forced to use lowercase values in black/whitelists e.g. a user no longer needs to use `function-whitelist: ["translatex"]`, they can now use the more intuitive `function-whitelist: ["translateX"]`.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2709
