### ISSUE TITLE
Improve docs navigation

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2668]
I'm not sure if this issue should be open here or in stylelint.io repository.

Our docs are huge and thorough, but they are hard to navigate and search. Even for experienced users. I suggest adding Table of Content (ToC) at the beginning of every page (maybe except every rule page). It would immediately tell a user what content this page has, what might be enough for a user to decide if a page contains what she needs.

It might be overwhelming to support ToC manually in markdown files, so we might add autogenerated ToC on our site when it generated.

**Comment by jeddy3** [comment]
> It might be overwhelming to support ToC manually in markdown files

I think so. Let's open up an issue in stylelint.io instead. We might be able to make use of something like [remark-toc](https://github.com/wooorm/remark-toc) to autogenerate.
