### ISSUE TITLE
How to use two stylelint config an and used them different folders in same project?

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2692]
How to use two stylelint configs an and used them different folders in the same project?

In a project, I have two kinds of CSS

1) CSS files are written from scratch by our developers.
2) Third party CSS files which are slightly modified by our developer

I can't use same stylelint config for both because some part of third party code I won't be able to change. But I want to use few rules on third party edited files in this case.

Is it possible to have two `.stylelintrc` in same repo and use them on two different paths?

**Comment by jeddy3** [comment]
See: [Loading the configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#loading-the-configuration-object).

> Is it possible to have two .stylelintrc in same repo and use them on two different paths?

"Once one of these is found [a config file] and parsed, the _search will stop and that object will be used_.

> How to use two stylelint configs an and used them different folders in the same project?

"The configuration search can be short-circuited by using either the config or configFile options".

Have two configs, and use `--config`. Run stylelint twice.

**Comment by ntwb** [comment]
The above is how I've got stylelint setup to lint CSS with one config, and SCSS with another 👍 

On a related subject, ESLint just added _"glob based configuration" for overriding files, interesting concept that I've not fully explored yet, still think it's neat all the same 👌 
> http://eslint.org/blog/2017/06/eslint-v4.1.0-released#glob-based-configuration

**Comment by jitendravyas** [comment]
@ntwb do you lint css and scss in same project? Would like to know, why are linting css too while you use scss

**Comment by ntwb** [comment]
The project I use that in includes some external SCSS assets that I lint as a safeguard "just in case", the rest of the project is written in pure CSS.

**Comment by evilebottnawi** [comment]
@ntwb we can solve this more easier, when i use `stylelint.config.js` and return function, just pass file path. Example:
```js
"use strict";

const path = require('path');

module.exports = (filePath) => {
    const extension = path.extension(filePath);
    let config = null;   
 
   switch (extension) {
       case '.css':
           config = {}; // css configuration
           break; 
       case '.scss':
           config = {}; // scss configuration
           break; 
   }

    return config;
};

```

**Comment by evilebottnawi** [comment]
@stylelint/core what do your about example above?

**Comment by ntwb** [comment]
That's one way sure 👍 

The repo I'm using for this particular configuration uses Grunt, so a condensed version is roughly:

```js
		configCss    = require('stylelint-config-wordpress/index.js'),
		configScss   = require('stylelint-config-wordpress/scss.js');

...

		stylelint: {
			css: {
				options: {
					config: configCss,
					format: 'css'
				},
				src: [ '**/*.css' ]
			},
			scss: {
				options: {
					config: configScss,
					format: 'scss'
				},
				src: [ '**/*.scss' ]
			}
		},
```
