### ISSUE TITLE
Cannot find module 'postcss-scss'

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2694]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Not sure

> Which rule, if any, is this issue related to?

Not rule specific I guess
> What CSS is needed to reproduce this issue?

NA

> What stylelint configuration is needed to reproduce this issue?

NA

> Which version of stylelint are you using?

7.11.0 and I use stylelint-scss plugin too

> How are you running stylelint: CLI, PostCSS plugin, Node API?

on CLI with lint-staged as a pre-commit hook

```
  "lint-staged": {
    "*.scss": [
      "stylelint --syntax=scss",
      "prettier --parser postcss --use-tabs --write",
      "git add"
    ],
    "*.js": [
      "prettier --use-tabs --single-quote --write",
      "git add"
    ]
  },
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

NA

> What did you expect to happen?

No error

> What actually happened (e.g. what warnings or errors you are getting)?

![2017-06-30 03-18-29](https://user-images.githubusercontent.com/77309/27712188-7c18e286-5d43-11e7-96fe-7743006cc236.jpg)

**Comment by evilebottnawi** [comment]
@jitendravyas which npm version your use?

**Comment by jitendravyas** [comment]
@evilebottnawi npm `5.0.4` and node `6.10.0`

**Comment by jitendravyas** [comment]
After i installed https://www.npmjs.com/package/postcss-scss this error is gone

**Comment by hudochenkov** [comment]
@jitendravyas it might be a problem with npm@5: npm install sometimes fails to install some dependencies on a fresh install (npm/npm#16902).

**Comment by ntwb** [comment]
I'm finding lots of issues with updating dependencies with npm 5, my workaround:

• Delete `package-lock.json`
• Delete `node_modules`
• Run `npm install`

😢

**Comment by jeddy3** [comment]
Closing as this is unlikely a problem with stylelint itself

**Comment by svapreddy** [comment]
I am also facing this issue. But with `postcss-html` dependency package. The error message is `postcss-html@0.15.0 requires a peer of postcss@>=5.0.0 but none is installed. You must install peer dependencies yourself.` Why this is happening with only Stylelint package.
