### ISSUE TITLE
v0.1.1 maybe

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#271]
We've merged code that should
- Fix how newlines are handled for Windows
- Allow a couple of rules that broke with nesting to understand nesting

In my mind that could warrant a patch release. Anybody object?

**Comment by jeddy3** [comment]
Nope. Sounds good to me.

**Comment by MoOx** [comment]
I like to ship release as often as possible. So one fix in a stable master = one patch released :)

**Comment by davidtheclark** [comment]
Great: I think the same way. I will try to use your release script later today.

**Comment by davidtheclark** [comment]
Published v0.1.1.
