### ISSUE TITLE
Added non-file inputs support to autofix

### ISSUE THREAD

**Issue by olegskl** [stylelint/stylelint#2710]
Feature request: return autofixed code in stylelint results.

Currently it seems that only configurations containing `files` option are autofixed because of early return in [standalone.js#L76](https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L76).

> Which rule, if any, is this issue related to?

All autofixable rules.

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  color: #FFF;
}
```

> What stylelint configuration is needed to reproduce this issue?

e.g.

```json
{
  "config": {
    "rules": {
      "color-hex-case": "lower"
    }
  },
  "fix": true
}
```

> Which version of stylelint are you using?

e.g. `7.12.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

I expect stylelint to return a string containing autofixed code.

> What actually happened (e.g. what warnings or errors you are getting)?

The `fix` option is noop.

**Comment by jeddy3** [comment]
@olegskl Thanks for the report and for using the template. I'm going to label this as "help wanted". It's early days for the autofix feature, and any help shoring it up would be much appreciated.

**Comment by modosc** [comment]
this should be fixed in `master` now.
