### ISSUE TITLE
Fix missing closing brace in example inside max-nesting-depth documentation

### ISSUE THREAD

**Issue by gamtiq** [stylelint/stylelint#2718]
A closing brace is missing in the first example inside [max-nesting-depth documentation](https://github.com/stylelint/stylelint/blob/master/lib/rules/max-nesting-depth/README.md):
```css
a { & > b { top: 0; }
```

**Comment by jeddy3** [comment]
Thanks for spotting this.

Feel free to submit PRs directly for small documentation fixes like this. No need to create an issue :)
