### ISSUE TITLE
Add `ignorePath` as a config option

### ISSUE THREAD

**Issue by Hypnosphi** [stylelint/stylelint#2724]
My usecase is to use `.eslintignore` for ignoring paths that shouldn't be linted by either stylelint or eslint. Now i have to pass `--ignore-path .eslintignore` everywhere I use stylelint

**Comment by jeddy3** [comment]
I'm not sure this use case warrants an additional config option. Adding `--ignore-path .eslintignore` is a minor inconvenience and is explicit.

**Comment by jeddy3** [comment]
Closing for now. We can always reopen if there are further requests for such a feature.
