### ISSUE TITLE
Add Greenkeeper support for package-lock.json

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2766]
It looks like we need to add a GitHub token to the repo for Greenkeeper to be able to push to branches from within Travis CI

https://github.com/greenkeeperio/greenkeeper-lockfile#setup

Noticed as part of #2765: https://travis-ci.org/stylelint/stylelint/jobs/255347993#L1879
```shell
0.86s$ greenkeeper-lockfile-update
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please, commit your changes or stash them before you can merge.
Aborting
child_process.js:631
    throw err;
    ^
Error: Command failed: git revert -n HEAD
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please, commit your changes or stash them before you can merge.
Aborting
```

**Comment by hudochenkov** [comment]
@ntwb can you take care of this problem, please? You're the best of us who understand in npm@5 and Greenkeeper things. We've already missed some dependencies updates, which breaks stylelint for npm <5 users.

https://github.com/stylelint/stylelint/issues/2775
https://github.com/stylelint/stylelint/issues/2768

**Comment by ntwb** [comment]
@jeddy3 Now that you're back from 🏖  (which I hope was awesome) could you take a look at this please? 😄 

Following the details here: https://github.com/greenkeeperio/greenkeeper-lockfile#setup

1. We need a GitHub token created for each the stylelint repos that use Greenkeeper
2. For each repo the token added as environment variable `GH_TOKEN` to e.g https://travis-ci.org/stylelint/stylelint/settings 

After that I can then create the PRs for each repo to implement the required changes 🤖

**Comment by jeddy3** [comment]
> Now that you're back from 🏖 (which I hope was awesome)

Thanks :)

> could you take a look at this please? 

I've created a token and added it as the `GH_TOKEN` environment variable on Travis to:

- `stylelint`
- `stylelint-demo`
- `stylelint-config-standard`
- `stylelint-config-standard`
- `eslint-config-stylelint`

Anything else to do?

**Comment by ntwb** [comment]
- `stylelint` Changes required added previously ✅ 
- `stylelint-demo` Changes required added previously ✅ 
- `stylelint-config-recommended` https://github.com/stylelint/stylelint-config-recommended/pull/8
- `stylelint-config-standard` https://github.com/stylelint/stylelint-config-standard/pull/91
- `eslint-config-stylelint` https://github.com/stylelint/eslint-config-stylelint/pull/33

Thanks @jeddy3 The above 3 PRs should finalise anything outstanding for this 👍

**Comment by ntwb** [comment]
I would have expected the fresh PR #2844 to have worked per what has already been implemented here, sadly that's not the case 😞 

All 4 jobs of the build fail with the same error:
```shell
$ greenkeeper-lockfile-update
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please, commit your changes or stash them before you can merge.
Aborting
child_process.js:511
    throw err;
    ^
Error: Command failed: git revert -n HEAD
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please, commit your changes or stash them before you can merge.
Aborting
    at checkExecSyncError (child_process.js:468:13)
    at execSync (child_process.js:508:13)
    at updateLockfile (/home/travis/.nvm/versions/node/v4.8.4/lib/node_modules/greenkeeper-lockfile/lib/update-lockfile.js:30:5)
    at Module.update [as exports] (/home/travis/.nvm/versions/node/v4.8.4/lib/node_modules/greenkeeper-lockfile/update.js:60:3)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v4.8.4/lib/node_modules/greenkeeper-lockfile/update.js:68:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
The command "greenkeeper-lockfile-update" failed and exited with 1 during .
Your build has been stopped.
```

Per the docs at https://github.com/greenkeeperio/greenkeeper-lockfile#testing-multiple-node-versions this should fail at best for only one job and not all 4 😞 

Friday night here, I'm out for the night but will investigate further tomorrow 🥃

**Comment by hudochenkov** [comment]
@ntwb Flow is weird. It fails on current master https://travis-ci.org/stylelint/stylelint/builds/271133000

**Comment by ntwb** [comment]
@hudochenkov The Flow error is caused by npm 5.4.0, I've _pinned_ npm 5.3.0 for Travis CI for now, see #2849 for more details and links 😄

**Comment by jeddy3** [comment]
@ntwb Can this be closed?

**Comment by ntwb** [comment]
> @ntwb Can this be closed now that the npm issue is resolved?

Let's wait for the next Greenkeeper PR, I still don't believe Greenkeeper is working as is expected

**Comment by jeddy3** [comment]
> Let's wait for the next Greenkeeper PR, I still don't believe Greenkeeper is working as is expected

Am I right in thinking that the last couple of Greenkeeper PRs failed? Is there anything I can do to help resolve this?

**Comment by ntwb** [comment]
Indeed they continue to fail, will need to investigate further.

I believe we have implemented everything correctly we need to per the docs FWIW:
> https://github.com/greenkeeperio/greenkeeper-lockfile#greenkeeper-lockfile

**Comment by hudochenkov** [comment]
We should address this problem with priority. @ntwb spends quite a lot of his time doing [manual work](https://github.com/stylelint/stylelint/pull/2922#issuecomment-331683749) which should be automated. From what I see, Greenkeeper and `package-lock.json` give us more problems (no problems, but unneeded manual work), than help.

**Comment by jeddy3** [comment]
> We should address this problem with priority.

I went through the checklist again and we appear to be doing everything right.

>  From what I see, Greenkeeper and package-lock.json give us more problems (no problems, but unneeded manual work), than help.

Agreed. Shall we disable `package-lock.json` for now, until the processes (and tooling) around its use is more mature?

I believe the simple addition of a `.npmrc` with the contents of `package-lock=false` will do this.

**Comment by ntwb** [comment]
I'll double check a couple of things over the next couple of hours...

If no reply, or whatever I suggest doesn't work then feel free to make the `.npmrc` change disabling `package-lock.json` and add it to `.gitignore`

**Comment by ntwb** [comment]
Here's a few suggestions:

- Greenkeeper is not currently enabled for `stylelint-config-recommended`, maybe try enabling it there to see if it works, maybe when we set everything up there was a bug that's now been resolved...

- Maybe try _turning it off and on again_, by way of disabling Greenkeeper for `stylelint` and then enabling it once again.
  - To this the following is how Greenkeeper document this:
  - Remove the repo from the Greenkeeper integration in the app installation settings on GitHub and save.
  - On the same page, add the repo again, and save.

- Greenkeeper repo status for stylelint repos can be seen at [greenkeeper.io/account/stylelint](https://account.greenkeeper.io/account/stylelint)

**Comment by jeddy3** [comment]
> Here's a few suggestions:

Thanks for writing this up. I nuked greenkeeper on all the repos and enabled them again on a clean slate. Hopefully, that'll work (fingers crossed). Otherwise, let's go down the `.npmrc` route.

**Comment by hudochenkov** [comment]
It didn't work out :( https://github.com/stylelint/stylelint/pull/2928

**Comment by jeddy3** [comment]
> It didn't work out :( #2928

Shame. Oh well, let's go down the `.npmrc` route for now and we can revisit this in a couple of months.

**Comment by brunocodutra** [comment]
FYI I struggled with this very same issue for a while until I decided to manually implement the logic myself. 

It turns out to be quite simple in fact: https://github.com/brunocodutra/steady/blob/ddb5ea0c9a534713c26b85ad9cc76259eba32c05/.travis.yml#L44
