### ISSUE TITLE
Add autofixing for end-of-source newlines

### ISSUE THREAD

**Issue by imrekoszo** [stylelint/stylelint#2771]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

In a codebase I'm working on right now, this is one of the most common errors. It would be very helpful if stylelint could append newlines to source files that don't have a trailing one. I will create a pull request as it appears this would be a simple code change.

> Which rule, if any, is this issue related to?

`no-missing-end-of-source-newline`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  color: pink;
}
```

> Expected fix

e.g.

```css
.foo {
  color: pink;
}
\n
```

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

yarn stylelint ...

**Comment by ntwb** [comment]
Fixed via #2772
