### ISSUE TITLE
Stylelint with postcss-scss

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#2776]
I'm not even sure this is an issue with stylelint itself so please bear with me.

So, I'm using gulp-postcss with stylelint and postcss-scss like this:

```js
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var stylelint = require('stylelint');
var reporter = require('postcss-reporter');
var scssParser = require('postcss-scss');
var config = require('../../config').stylelint;
var options = config.options;

gulp.task('lint:styles', function() {
    var plugins = [
        stylelint(options.configFile),
        reporter(options.reporter)
    ];

    return gulp.src(config.src)
        .pipe(postcss(plugins, { syntax: scssParser }));
});
```

My `.stylelintrc`:

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "block-closing-brace-empty-line-before": null,
    "block-opening-brace-space-before": "always",
    "color-hex-length": "long",
    "color-named": "never",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "always",
    "indentation": 4,
    "max-empty-lines": 2,
    "media-query-list-comma-space-after": "always",
    "rule-empty-line-before": ["always", {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    }],
    "value-list-comma-newline-after": "never-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always"
  }
}
```

Now this works fine with stylelint v7.x, but with v8.0.0 it's like Sass is no longer recognized. For example I'm getting:

```
sass/layout/_footer.scss
20:13   ‼  Unexpected unknown at-rule "@include" (at-rule-no-unknown) [stylelint]
```

I'm using node.js v8.2.1 on Windows 7 64-bit. If it's a config issue please point me to the right direction.

Thanks!

**Comment by ntwb** [comment]
Ensure you've using the latest `stylelint-config-standard`, there was some shuffling around of some rules in stylelint v8 including `at-rule-no-unknown` and I think that might be what's tripping you up here.

Aside 1: You might also want to consider including the new [stylelint-config-recommended-scss](https://github.com/kristerkari/stylelint-config-recommended-scss) in addition to `stylelint-config-standard` as this config adds a new SCSS specific `scss/at-rule-no-unknown` and turns off the `at-rule-no-unknown` rule from `stylelint-config-standard`

Aside 2: You don't need to use `gulp-postcss` and `postcss-reporter` any longer, you should switch to [gulp-stylelint](https://github.com/olegskl/gulp-stylelint) which supports the built in stylelint reporters

**Comment by XhmikosR** [comment]
Thanks for the reply!

1. I made sure all deps are up to date, nothing changes
2. I added `stylelint-config-recommended-scss` but I can't make stylelint to pick it up.

```json
"extends": ["stylelint-config-standard", "stylelint-config-recommended-scss"],
```

```
C:\Users\xmr\Desktop\foobar>gulp lint:styles
[07:53:32] Using gulpfile ~\Desktop\foobar\gulpfile.js
[07:53:32] Starting 'lint:styles'...
[07:53:32] 'lint:styles' errored after 50 ms
[07:53:32] Error in plugin 'gulp-postcss'
Message:
    Could not find "stylelint-scss". Do you need a `configBasedir`?
Details:
    code: 78
    fileName: C:\Users\xmr\Desktop\foobar\sass\main.scss
Stack:
Error: Could not find "stylelint-scss". Do you need a `configBasedir`?
    at module.exports (C:\Users\xmr\Desktop\foobar\node_modules\stylelint\lib\utils\configurationError.js:8:28)
    at module.exports (C:\Users\xmr\Desktop\foobar\node_modules\stylelint\lib\utils\getModulePath.js:18:11)
    at config.plugins.concat.map.lookup (C:\Users\xmr\Desktop\foobar\node_modules\stylelint\lib\augmentConfig.js:119:14)
    at Array.map (native)
    at absolutizePaths (C:\Users\xmr\Desktop\foobar\node_modules\stylelint\lib\augmentConfig.js:118:48)
    at Promise.resolve.then.then.then.augmentedConfig (C:\Users\xmr\Desktop\foobar\node_modules\stylelint\lib\augmentConfig.js:30:14)
    at <anonymous>
```

I'll look into gulp-stylelint later, thanks. The reason I didn't want to use it is because I'm trying to depend to as few as possible third-party stuff and use the libraries directly.

**Comment by XhmikosR** [comment]
So that scss config is broken with Node.js v8.x; it doesn't install `stylelint-scss`. It's probably the peerDependencies they have. IMO they should drop those since they are obsolete.

What works for me is explicitly disabling at rules `"at-rule-no-unknown": null,` but that beats the point :/

**Comment by XhmikosR** [comment]
Ah, nvm, the problem with `stylelint-scss` is that they have it specified it in devDependencies and not dependencies.

**Comment by XhmikosR** [comment]
Closing this since I managed to get things working.

Thanks for the help!

**Comment by niftylettuce** [comment]
@XhmikosR just an FYI you don't need both extends, as the latter includes the former, see <https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js#L4>
