### ISSUE TITLE
Special indentation for related selectors

### ISSUE THREAD

**Issue by magsout** [stylelint/stylelint#278]
I use BEM methodology and indentation for block element like: https://gist.github.com/magsout/a0a2b7f95fd9b912e21f

I don't know how to solve this problem without disabling the rule (ìndentation`). Perhaps add an exception to test if the indentation is always space or tab, but allow a higher indentation for at-rule? Or there is no way ..

**Comment by jeddy3** [comment]
@davidtheclark Would adding `ignore: ["statement"]` option to the `indentation` rule work here?

I think that would allow @magsout to indent his *statements* as he see fit, while still enforcing indentation for *blocks* and *value lists*.

I guess the tricky one here is *nested statements* i.e. rules within *at-rules blocks*...

Any ideas?

**Comment by MoOx** [comment]
Maybe we can consider a new indentation level is valid if a selector starts with the previous one ?

**Comment by davidtheclark** [comment]
@magsout : Is this something you think is unique to your stylesheets or a common practice?

If it's unique to your stylesheets, I'd think we should go with @jeddy3's suggestion of adding an `ignore: ["statement"]` option. Other people might have other idiosyncratic indentation practices, and we certainly can't address them all.

If this particular pattern is common practice for BEM users, then we should consider turning @MoOx's idea on as an option.

Those are my opinions.

**Comment by MoOx** [comment]
I know some others people like @magsout and myself that indent their BEM stylesheets ;)

My suggestion might works for non bem code too:

```css

.test {}

  .test .child{} // indexOf(previous selector) === 0
```

**Comment by davidtheclark** [comment]
Ok. Maybe we should do both ... `ignore: ['statement']` for people who do something idiosyncratic and don't want statements checked; and @MoOx's suggestion as a special option.

**Comment by MoOx** [comment]
Do you think we can consider both those case valid _by default_:

```css
.test {}

.test .child {} /* valid */
  .test .child {} /* valid too ?!*/
```

Well while I am writing this, it might make no sense to support both at the same time. So an option sounds like a good plan (even if an autodetection on first rules might make sense too, but it will be a bit more complicated to implement)

**Comment by davidtheclark** [comment]
@MoOx and @magsout : Can you think of any option name that would describe this pattern in a way people would understand?

**Comment by MoOx** [comment]
something like "indent-children-selectors" maybe?

**Comment by magsout** [comment]
I think, more like : `indent-adjacent-selectors` ? (like selectors spec name ;) ) http://www.w3.org/TR/REC-CSS2/selector.html#adjacent-selectors

**Comment by MoOx** [comment]
adjacent selectors are selectors separated by `+`.

**Comment by magsout** [comment]
so Same thing here  ? 
```
.test {}

.test .child {} /* valid */
  .test .child {} /* valid too ?!*/
```

css : 
```
.test + .test {

}
```

**Comment by magsout** [comment]
forget my last comment. After a discussion with @MoOx, I agree with him on `indent-children-selectors`

**Comment by jeddy3** [comment]
I'm wondering whether this is a good candidate for a custom *[runtime rule](http://eslint.org/docs/developer-guide/working-with-rules#runtime-rules)*. We briefly discussed this before [here](https://github.com/stylelint/stylelint/issues/77#issuecomment-103924979).

Currently the `indentation` rule just iterates through all the nodes making sure each nested node is indented by one further indent. In #280 we're proposing to add the simple option of excluding nodes of chosen types from this rule.

I think what we're proposing in this issue is more complicated, as it involves enforcing a nesting level based on the comparison of the selectors of two rules.

What do you all think? If you think this makes a good candidate to experimenting with making the linter capable of handling *runtime rules*, what are the steps needed to make this happen?

**Comment by jeddy3** [comment]
> I think what we're proposing in this issue is more complicated, as it involves enforcing a nesting level based on the comparison of the selectors of two rules.

Just it clarify this. In @magsout original gist he's indenting based on the name of the class e.g. `.cs-Navbar` and `.cs-Navbar-item` rather than any descendant or adjacent-sibling relationship.

**Comment by MoOx** [comment]
I understand your point. That might be doable easily.

Note:  `".cs-Navbar-item".indexOf(".cs-Navbar") === ".test .child".indexOf(".test") === 0`

**Comment by jeddy3** [comment]
I think the advantage of the custom runtime rules is that we can keep the core `indentation` rule simple and supporting the majority of the use-cases, while the authors of custom indentation rule is free enforce any convention he or she wishes to code up; be it conventions based on BEM naming or selector combinators.

**Comment by MoOx** [comment]
I get it, your call.

indentation is always a tricky stuff https://github.com/eslint/eslint/blob/master/lib/rules/indent.js

**Comment by jeddy3** [comment]
> indentation is always a tricky stuff https://github.com/eslint/eslint/blob/master/lib/rules/indent.js

Yikes, that *is* tricky!

> Note: ".cs-Navbar-item".indexOf(".cs-Navbar") === ".test .child".indexOf(".test") === 0

I might not be seeing this clearly, so bare with me, but where would`".cs-Navbar"` and `".test"` come from? Would they be the selector of a previous rule in the stylesheet? 

> I get it, your call.

Perhaps we should get #280 in first, as that'll make `indentation` partly useful for this type of indentation convention. After that, perhaps we should wait until we have a couple more candidates for custom rules, to better assess if it's worth our time implementing that functionality?

What are everyone's thoughts on that? If it sounds like a plan I can create a new issue accordingly.

**Comment by MoOx** [comment]
> I might not be seeing this clearly, so bare with me, but where would".cs-Navbar" and ".test" come from?

Just the previous selector (from previous node, if any).

**Comment by davidtheclark** [comment]
Let's plan to make a pluggable custom rule for this (https://github.com/stylelint/stylelint/issues/295).

**Comment by davidtheclark** [comment]
I changed my mind on this one, because the indentation rule is a fairly complex one so it would probably be much easier to just incorporate this functionality as an option. I'm working on a PR to demonstrate.
