### ISSUE TITLE
Add autofixing for color-hex-length

### ISSUE THREAD

**Issue by imrekoszo** [stylelint/stylelint#2780]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

In a codebase I'm working on right now, this is one of the most common errors. It would be very helpful if stylelint could autofix them. I will create a pull request as it appears this would be a simple code change.

> Which rule, if any, is this issue related to?

`color-hex-length`

> What CSS is needed to reproduce this issue?

e.g.

```css
a { color: #FFF; }
b { color: #FFFFFF; }
```

> What stylelint configuration is needed to reproduce this issue?

n/a

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

yarn stylelint...

**Comment by ntwb** [comment]
Fixed via #2781
