### ISSUE TITLE
Add 'peerDependencies' guideline to plugin writing documentation

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#2812]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I propose to add guideline which plugin authors should declare *stylelint* as `peerDependencies`
to [stylelint plugin writing documentation](https://stylelint.io/developer-guide/plugins/) such as [ESLint](http://eslint.org).

[ESLint documentation](http://eslint.org/docs/developer-guide/working-with-plugins#peer-dependency) says:

> To make clear that the plugin requires ESLint to work correctly you have to declare ESLint as a peerDependency in your package.json.
> The plugin support was introduced in ESLint version 0.8.0. Ensure the peerDependency points to ESLint 0.8.0 or later.

And [npm documentation](https://docs.npmjs.com/files/package.json#peerdependencies) says:

> In some cases, you want to express the compatibility of your package with a host tool or library,
> while not necessarily doing a require of this host. This is usually referred to as a plugin.

This proposal reason is that different versions of *stylelint* can be installed **unexpectedly** at same time,
if you will install some plugins depending on different versions of *stylelint*.

For example:

`stylelint-plugin-a` depends to `stylelint@^7.0.0`.

```json
{
  "name": "stylelint-plugin-a",
  "version": "1.0.0",
  "dependencies": {
    "stylelint": "^7.0.0"
  }
}
```

On the other hand, `stylelint-plugin-b` depends to `stylelint@^8.0.0` as `peerDependencies`.

```json
{
  "name": "stylelint-plugin-b",
  "version": "1.0.0",
  "peerDependencies": {
    "stylelint": "^8.0.0"
  }
}
```

Then if installing these plugins, warning about `peerDependencies` will be output.

```shellsession
$ npm install ../stylelint-plugin-a ../stylelint-plugin-b
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN stylelint-plugin-b@1.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
npm WARN using-stylelint-plugins@1.0.0 No description
npm WARN using-stylelint-plugins@1.0.0 No repository field.
npm WARN using-stylelint-plugins@1.0.0 No license field.

+ stylelint-plugin-a@1.0.0
+ stylelint-plugin-b@1.0.0
added 2 packages in 0.981s

$ npm ls | grep stylelint
using-stylelint-plugins@1.0.0 /tmp/using-stylelint-plugins
├── UNMET PEER DEPENDENCY stylelint@^8.0.0
├─┬ stylelint-plugin-a@1.0.0 -> /tmp/stylelint-plugin-a
│ └─┬ stylelint@7.13.0
└── stylelint-plugin-b@1.0.0 -> /tmp/stylelint-plugin-b
npm ERR! peer dep missing: stylelint@^8.0.0, required by stylelint-plugin-b@1.0.0
npm ERR! extraneous: ansi-styles@3.2.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/ansi-styles
npm ERR! extraneous: is-fullwidth-code-point@2.0.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/is-fullwidth-code-point
npm ERR! extraneous: strip-ansi@4.0.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/strip-ansi
```

```json
{
  "name": "using-stylelint-plugins",
  "version": "1.0.0",
  "dependencies": {
    "stylelint-plugin-a": "file:../stylelint-plugin-a",
    "stylelint-plugin-b": "file:../stylelint-plugin-b"
  }
}
```

Or if installing also `stylelint`, warning will not be output but different versions of `stylelint`
will be installed.
**This may cause unexpected behavior or increase of install time**.

```shellsession
$ npm install ../stylelint-plugin-a ../stylelint-plugin-b stylelint@^8.0.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN using-stylelint-plugins@1.0.0 No description
npm WARN using-stylelint-plugins@1.0.0 No repository field.
npm WARN using-stylelint-plugins@1.0.0 No license field.

+ stylelint-plugin-a@1.0.0
+ stylelint-plugin-b@1.0.0
+ stylelint@8.0.0
added 200 packages in 6.333s

$ npm ls | grep stylelint
using-stylelint-plugins@1.0.0 /tmp/using-stylelint-plugins
├─┬ stylelint@8.0.0
├─┬ stylelint-plugin-a@1.0.0 -> /tmp/stylelint-plugin-a
│ └─┬ stylelint@7.13.0
└── stylelint-plugin-b@1.0.0 -> /tmp/stylelint-plugin-b
npm ERR! extraneous: ansi-styles@3.2.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/ansi-styles
npm ERR! extraneous: is-fullwidth-code-point@2.0.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/is-fullwidth-code-point
npm ERR! extraneous: strip-ansi@4.0.0 /tmp/using-stylelint-plugins/node_modules/stylelint-plugin-a/node_modules/strip-ansi
```

```json
{
  "name": "using-stylelint-plugins",
  "version": "1.0.0",
  "dependencies": {
    "stylelint": "^8.0.0",
    "stylelint-plugin-a": "file:../stylelint-plugin-a",
    "stylelint-plugin-b": "file:../stylelint-plugin-b"
  }
}
```

Example environments:
- OS: Mac OS X 10.12.6 16G29
- Node: 8.3.0
- npm: 5.3.0

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

N/A

> How are you running stylelint: CLI, PostCSS plugin, Node API?

N/A

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

N/A

> What did you expect to happen?

N/A

> What actually happened (e.g. what warnings or errors you are getting)?

N/A

**Comment by jeddy3** [comment]
@ybiquitous Thanks for writing this up.

> This proposal reason is that different versions of stylelint can be installed unexpectedly at same time, if you will install some plugins depending on different versions of stylelint.

Doing as [eslint does](https://github.com/yannickcr/eslint-plugin-react/blob/master/package.json#L39-L41) here SGTM. It would address this issue.

**Comment by ybiquitous** [comment]
@jeddy3 Can I write documentation?

Or should core committers write documentation about this?
(Because the documentation may be important on the `stylelint` community)

**Comment by ntwb** [comment]
@ybiquitous That would be fantastic if you could please 😄

**Comment by ybiquitous** [comment]
@ntwb Thanks a lot! Anyway I will try 😉

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2850
