### ISSUE TITLE
CLI not exiting with non-zero error code

### ISSUE THREAD

**Issue by jamiedust** [stylelint/stylelint#2817]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

When running stylelint via the CLI errors do not cause the process to exit with a non-zero error code, this is required for adding to pipelines.

> Which rule, if any, is this issue related to?

n/a

> What CSS is needed to reproduce this issue?

```css
.foo {
  color: #xyz;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "color-no-invalid-hex": [ true, { severity: "error" } ]
  }
}
```

> Which version of stylelint are you using?

8.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

./node_modules/stylelint/bin/stylelint.js /path/to/css.less

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

It is not related to syntax.

> What did you expect to happen?

When an error is found or a syntax error the process should exit with a non-zero exit code.

> What actually happened (e.g. what warnings or errors you are getting)?

The process does not exit with a non-zero code.

**Comment by evilebottnawi** [comment]
@jamiedust don't reproduce, can your try to reinstall `node_modules`, if error still exists please create minimum reproducible test repo, thanks!

**Comment by jamiedust** [comment]
My mistake, on further investigation I see that it is indeed returning a non-zero exit code. I am used to seeing eslint throw an error on failures but have realised that this was npm throwing the error.
