### ISSUE TITLE
By default, all node_modules and bower_components are ignored?

### ISSUE THREAD

**Issue by syakuis** [stylelint/stylelint#2825]
By default, all node_modules and bower_components are ignored?

![2017-08-21 10 48 27](https://user-images.githubusercontent.com/6147878/29500763-8a99b094-865e-11e7-82b3-43a26a9bab5c.png)

.stylelintrc

```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "at-rule-empty-line-before": null
  }
}
```

.stylelintignore

```
node_modules/
bower_components/
dist/
```

Why is this? :(  sorry, I speak a little English.

**Comment by jeddy3** [comment]
> By default, all node_modules and bower_components are ignored?

Yes. However, the [`ignoreFiles` option](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#ignorefiles) can be used to change this behaviour.

**Comment by asumaran** [comment]
@jeddy3 `node_modules` not being ignored for me as well.

Here's the output after running stylelint

```
mighty-client - as-prettier-scss! ❯ ./node_modules/.bin/stylelint "./**/*.scss"  --config .stylelintrc                                                                                             [system]

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_modals.scss
 36:49  ✖  Unexpected whitespace before ";"   at-rule-semicolon-space-before

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_theme.scss
 217:3  ✖  Unexpected whitespace before ";"   at-rule-semicolon-space-before

node_modules/bootstrap-sass/assets/stylesheets/bootstrap/mixins/_image.scss
 23:8   ✖  Expected single space after at-rule name "@media"   at-rule-name-space-after
 24:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 25:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 25:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 26:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 26:56  ✖  Expected single space after ","                     media-query-list-comma-space-after
 27:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 27:54  ✖  Expected single space after ","                     media-query-list-comma-space-after
 28:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
 28:59  ✖  Expected single space after ","                     media-query-list-comma-space-after
 29:20  ✖  Unexpected whitespace after "("                     media-feature-parentheses-space-inside
```


My config file is

```
{
  "extends": [
    "stylelint-config-prettier"
  ],
  "syntax": "scss"
}
```

If I add `"ignoreFiles": ["./node_modules/**"]`  it works well though, what I'm doing wrong?

**Comment by jeddy3** [comment]
@asumaran Please create a new issue (using the template) so we can better help you. Preferably, please create a reproducible test repo to accompany your new issue.

Incidentally, there is no such `"syntax": "scss"` property and value within [the configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object). I've seen this a few times now... it'll be interesting to know where it first came from so we can address it at the source.

**Comment by asumaran** [comment]
@jeddy3 I've created an issue for that. Here it is https://github.com/stylelint/stylelint/issues/3005 Thanks!
