### ISSUE TITLE
Unexpected unknown animation name with `no-unknown-animations: true`

### ISSUE THREAD

**Issue by chhavi-khandelwal** [stylelint/stylelint#2831]
On running `grunt stylelint` task with rule no-unknown-animations: true, it gives an error:
**Unexpected unknown animation name "modal-slide"   no-unknown-animations**

SCSS Code:
```
$anim-prefix: 'anim-';

@mixin keyframe ($animation-name){
    @keyframes #{$animation-name}{
        @content;
    }
}

.#{$anim-prefix}modal-slide {
     animation: modal-slide ease-in-out .2s;
     animation-fill-mode: forwards;
}

@include keyframe('modal-slide') {
     0% {
          opacity: 0;
	  transform: translateY(10px);
      }
      100% {
	  opacity: 1;
	  transform: translateY(0);
	}
}
```

Stylelint version **8.0.0**

Can't figure out what is wrong with the code?

**Comment by ntwb** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.

**Comment by jeddy3** [comment]
`no-unknown-animations`, like all of the built-in rules within stylelint, only understands standard CSS syntax e.g.

```css
@keyframes modal-slide { .. }
.modal-slide {
  animation: modal-slide ease-in-out .2s;
}
```

In your code snippet you are _defining_ the keyframe using SCSS constructs like variables and mixins. As such, the rule can not determine that the `modal-slide` animation exists.

Either use standard constructs and continue using the `no-unknown-animations` rule, or turn off the `no-unknown-animations` rule.
