### ISSUE TITLE
Add ability for --fix to output results to STDOUT

### ISSUE THREAD

**Issue by chaucerbao** [stylelint/stylelint#2840]
Just wanted to see what you thought about adding an option for `--fix` to output the results to STDOUT.  It would allow integration into an IDE.

**Comment by ntwb** [comment]
Sounds like a great idea, looping @Arcanemagus in as the maintainer of [AtomLinter/linter-stylelint/](https://github.com/AtomLinter/linter-stylelint/) I'm sure he's thought about supporting fixable rules in Atom 😄

**Comment by jeddy3** [comment]
Is this a dupe of https://github.com/stylelint/stylelint/issues/2710?

**Comment by jeddy3** [comment]
Closing for now as I think its a dupe. @chaucerbao autofix is a new feature that needs contribution to improve. Please consider helping out with https://github.com/stylelint/stylelint/issues/2710 and bringing autofix to non-files.
