### ISSUE TITLE
path with mask works inconsistent

### ISSUE THREAD

**Issue by TrejGun** [stylelint/stylelint#2859]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

i'm trying to run same command from npm scripts 
```json
{
  "scripts": {
    "stylelint": "stylelint client/**/*.less --syntax less"
  }
}
```
and directly from command line
```sh
node_modules/.bin/stylelint client/**/*.less --syntax less
```

it works perfect from command line but skips all files in subfolders when invoked from npm 

> Which version of stylelint are you using?

8.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI, config is in .stylelintrc

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

all files from all subfolder are checked in both cases

> What actually happened (e.g. what warnings or errors you are getting)?

no warnings or errors

**Comment by evilebottnawi** [comment]
@TrejGun `stylelint "client/**/*.less" --syntax less` (use quotes around glob), thanks!

**Comment by TrejGun** [comment]
thanks

**Comment by RinatMullayanov** [comment]
@evilebottnawi I use stylelint like npm scripts:
```sh
csslint: "stylelint \"Content/**/*.css\""
```
on Windows 10: double escaped quotes works, but single quotes doesn't work.
What are difference between double and single quotes?

**Comment by evilebottnawi** [comment]
@RinatMullayanov 
```
csslint: "stylelint 'Content/**/*.css'"
```
?

**Comment by RinatMullayanov** [comment]
@evilebottnawi 

just package.json
```json
  "scripts": {
    "csslint": "stylelint 'Content/**/*.css'"
  }
```

I seem I have found an explanation:
https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

**Comment by pke** [comment]
Still does not work with this syntax:
`"lint:css": "stylelint '{src,products}/**/*.css'",`
