### ISSUE TITLE
styelint-config-cssrecipes 

### ISSUE THREAD

**Issue by magsout** [stylelint/stylelint#286]
I am trying to create a stylelint's config for cssrecipes https://github.com/cssrecipes . 
Just one question,  Do you want to host configurations in the org stylelint or not?

**Comment by MoOx** [comment]
I think it can be a good idea to have some, and since I am the creator of cssrecipes, I think it's a good idea. That said, I will let @davidtheclark and @jeddy3 have the final words on this.

**Comment by jeddy3** [comment]
I'm all for more configs :)

**Comment by davidtheclark** [comment]
Same here.

**Comment by MoOx** [comment]
💥 https://github.com/stylelint/styelint-config-cssrecipes
