### ISSUE TITLE
Add ignore values in declaration-property-unit-blacklist

### ISSUE THREAD

**Issue by klimashkin** [stylelint/stylelint#2860]
**Feature request**

In our project we follow [Fluid Typography](https://css-tricks.com/snippets/css/fluid-typography/) pattern, thus we don't use `px` in font-size, margins, padding etc. Instead we have bunch of variables that contain `rem` unit for specific viewport width.

For instance,
```css
  --2px: 0.14285714rem;
  --3px: 0.21428571rem;
  --4px: 0.28571429rem;
  --5px: 0.35714286rem;
  --6px: 0.42857143rem;
  --7px: 0.5rem;
  --8px: 0.57142857rem;
  --9px: 0.64285714rem;
  --10px: 0.71428571rem;
  --11px: 0.78571429rem;
  --12px: 0.85714286rem;
  --13px: 0.92857143rem;
  --14px: 1rem;
  --15px: 1.07142857rem;
  --16px: 1.14285714rem;
... and so on
```
And use this variables, so font/margin/padding grow/shrink when window size changes.

`declaration-property-unit-blacklist` rule fits perfectly for our needs:
```javascript
'declaration-property-unit-blacklist': {
  // We use pixel variables instead of real pixels
  '/margin|padding/': ['px'],
  '/^(top|right|bottom|left|font|font-size|line-height)$/': ['px'],
},
```

But in many cases we still need 1px offset for element regardless of viewport width, for instance, gap between flex elements, and 1px should remain 1px since browsers can't really interpolate it if it was rem value.

Would be nice to have exceptions in `declaration-property-unit-blacklist` for such cases. Or separate rule, like
```javascript
'declaration-property-unit-blacklist-ignore-values': {
  '/margin|padding/': ['1px'],
}
```

**Comment by jeddy3** [comment]
@klimashkin Thanks for the request and suggestion. The plugin system was designed for such specific use cases. [You could build your own plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) for this functionality (by converting the existing `declaration-property-unit-blacklist` rule to a plugin and building on it).
