### ISSUE TITLE
Any exit code generate a npm error message using npm run

### ISSUE THREAD

**Issue by aviram83** [stylelint/stylelint#2863]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

setting script line in package.json and then run it will generate error list and in the end it will also generate a npm error

> Which rule, if any, is this issue related to?

none

> What CSS is needed to reproduce this issue?

```css
.white-color {
  color: #ffffff;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
    "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

8.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

inside package.json
```json
{
  "scripts": {    
    "stylelint": "stylelint src/**/*.less"
  }
}
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

no npm error

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
src/TestComponent.less
 20:10  ✖  Expected "#ffffff" to be "#fff"   color-hex-length


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\avirams\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "stylelint"
npm ERR! node v7.7.3
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! frontend@0.0.1 stylelint: `stylelint public/src/apps/**/*.less`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the frontend@0.0.1 stylelint script 'stylelint public/src/apps/**/*.less'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     stylelint public/src/apps/**/*.less
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\projects\frontend-reference\npm-debug.log

```

**Comment by gucong3000** [comment]
@aviram83 It is not a bug. See:
https://stylelint.io/user-guide/cli/#exit-codes

**Comment by gucong3000** [comment]
if you actually exit code 0, you can config inside package.json
{
  "scripts": {    
    "stylelint": "stylelint src/**/*.less || echo \"lint faild for some file(s).\""
  }
}

**Comment by aviram83** [comment]
Your answer is great solution, maybe it's should be documented

**Comment by gucong3000** [comment]
> maybe it's should be documented
Already in the document, the link I'm giving you is.

**Comment by aviram83** [comment]
your solution I mean, I have saw the error list before but didn't how to get rid of the npm error  message

**Comment by gucong3000** [comment]
I understand now.

**Comment by jeddy3** [comment]
@gucong3000 Thanks for helping with this.

The solution is applicable to all npm run-scripts, rather than stylelint itself and so I don't think we need to document it here. If it comes up again though we can consider adding it to the FAQ.

**Comment by pthurmond** [comment]
So I am actually going to call out this as a big problem because it refuses to run "--fix" with these errors. How do you fix an error with "--fix" if it just won't get past the find portion without exiting???

**Comment by hudochenkov** [comment]
@pthurmond if you experience any problem, create a new issue, please.
