### ISSUE TITLE
Fix false positives for spaceless multiplication in calc functions in unit-*

### ISSUE THREAD

**Issue by CAYdenberg** [stylelint/stylelint#2875]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Bug, although corner-case. In `calc` functions, multiplication (and division) operations can be spaceless e.g. `calc(2px*3)`. postcss-value-parser however doesn't recognise `*` as a divider so it would assess the units as `px*3`. This is a problem for all `unit-*` rules.

> Which rule, if any, is this issue related to?

It was fixed in the case of `unit-no-unknown` in #2848. So unit-blacklist, unit-whitelist and unit-case. There may be others?

You can see #2551 for details - it is functionally the same.

I'm able to handle this one too as the fix is simple - but I'll leave this open for awhile first for discussion.

**Comment by jeddy3** [comment]
SGTM.

**Comment by CAYdenberg** [comment]
This was, afaik, handled in #2948
