### ISSUE TITLE
Direct nodejs api + cli

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#288]
What do you think about reusing some work made on cssnext, which share the same thing:

+ initiate the module with a config
+ execute on some css

---

- do this via a cli or a nodejs api
- config in a js/json/yml .rc file (will do in https://github.com/cssnext/cssnext/issues/73)
- possibly a watcher for the cli (single file, multiple files) (will do multiples files in https://github.com/cssnext/cssnext/issues/93)

I can probably make a postcss abstraction module in order to easily generate a cli and a nodejs api from a postcss module.

**Comment by davidtheclark** [comment]
Yep, if you want to make a module to help with that, that go for it.

**Comment by MoOx** [comment]
What do you think about a module named `postcss-as-tool`? poke @ai

**Comment by ai** [comment]
Some common codebase for making tools is good idea.
What API it will have? For example, stylelint is a few plugins.

**Comment by davidtheclark** [comment]
`as-tool` is ambiguous to me. But I can't think of anything better right now.

**Comment by MoOx** [comment]
@ai the tool should consume a postcss instance, we might allow a callback or something. I think I will see when I will work on it since stylelint and cssnext have some differences.

**Comment by ai** [comment]
Technically we has postcss-cli with config, etc right now.
But I think you suggest some different workflow.

**Comment by MoOx** [comment]
Yeah, something where the end user doesn't care about PostCSS.

**Comment by MoOx** [comment]
That might interest @ben-eb and @jonathantneal.
I am also thinking that we should provide postcss-* version of our tool as a simple plugin + mix the wrapper I will work on that integrate the plugin as the * tool.

**Comment by ben-eb** [comment]
How about `postcss-standalone-tool`?

**Comment by davidtheclark** [comment]
Yes, I think the word "standalone" is a good addition.

**Comment by MoOx** [comment]
postcss-* looks like a plugin...

`postcss-unpluginifier` ? :D

**Comment by ben-eb** [comment]
> postcss-* looks like a plugin...

> What do you think about a module named `postcss-as-tool`?

:wink:

**Comment by MoOx** [comment]
yeah yeah I know... ^^

I tried something that looks weird on purpose...

**Comment by MoOx** [comment]
`unpostcssifier` ?

**Comment by MoOx** [comment]
I will handle that in the next couple of days.

Recap of my naming ideas (please vote):

- postcss-as-tool
- postcss-standalonifier
- postcss-toolifier
- postcss-unpluginifier
- postcssifier
- unpostcssifier
- postcss-plugin-on-steroid
- postcss-plugin-enhancer

"ifer" can be replace by "ify" but I don't really like it for those examples.

**Comment by ben-eb** [comment]
I like postcss-toolify or failing that postcss-toolifier. :smile:

**Comment by davidtheclark** [comment]
I vote postcss-standalonifier or postcss-toolifier or postcss-standalonetoolifier.

**Comment by jonathantneal** [comment]
`postcss-clify`

**Comment by MoOx** [comment]
Nice idea but this will be a bit more than just "cli" (config file for example)

**Comment by jonathantneal** [comment]
IMHO, it still works since many CLI accept config files. However, with that in mind, I might also suggest: `postcss-silo`, `postcss-depot` because I like short names.

**Comment by magsout** [comment]
`postcss-toolifier` or `postcss-plugin-as-tool`

**Comment by TrySound** [comment]
+postcss-clify

**Comment by ben-eb** [comment]
I changed my mind. Modules that end in `ify` is a browserify convention, so it would be good to avoid that suffix. So I vote `postcss-toolifier`.

**Comment by TrySound** [comment]
postcss-clifier

**Comment by MoOx** [comment]
I have made some reseach this morning to avoid reinventing the weel.
I found a nice "rc" loader: https://www.npmjs.com/package/rc and a cool abstration on top of it (that "just" add YAML support) https://www.npmjs.com/package/rc-yaml so for the RC, I will go with this if you are ok.

I didn't find any magic shit for the CLI part so I will make it as a simple module that allow to execute some code with input (stdin, file or glob + watcher). I will call the module `easy-cli` (since `cli` is taken by a non automatically tested module).

It won't be focused on postcss but with those 2 packages, I guess making a "postcss-toolifier" will be like 5 lines of code ^^.

**Comment by MoOx** [comment]
I just found that a package is already using easy-cli (but I don't like it), so I will go for something like "cli-for-files" if I (or you) don't get a better idea before publising.

**Comment by jeddy3** [comment]
`rc-yaml` looks great.

Is something like https://github.com/sindresorhus/meow of any use here?

**Comment by MoOx** [comment]
I am using commander atm, but I will take a look to meow (even if it seems very light according to the codebase ^^)

**Comment by jeddy3** [comment]
Cool beans. I've not written a cli tool before so I'm very interested to see how all the bits go together :)

**Comment by MoOx** [comment]
This will probably be something really similar to this https://github.com/cssnext/cssnext/blob/master/src/bin.js ;)

**Comment by jeddy3** [comment]
Looks great!

**Comment by davidtheclark** [comment]
Great!

The `rc` part makes sense to me. Good find. At first I wasn't not sure what you're looking for for the "magic shit for the CLI part" -- that commander or minimist don't offer (argument organization and defaults) ---- but I think now I understand: it's about being able to handle multiple input formats (stdin, filename, glob) and also watching --- right?

**Comment by MoOx** [comment]
Yeap!

**Comment by TrySound** [comment]
[rc-yaml](https://github.com/digsjs/rc-yaml) uses [yaml-js](https://github.com/connec/yaml-js) which is less popular than [js-yaml](https://github.com/nodeca/js-yaml)

**Comment by MoOx** [comment]
I just published https://github.com/MoOx/rc-loader which handle YAML (via js-yaml), JSON or JS config, based on `rc` (I just overrode the parser).
I will continue on the cli things tomorrow.

**Comment by TrySound** [comment]
Nice!

**Comment by t32k** [comment]
:+1:

**Comment by davidtheclark** [comment]
@MoOx: Any estimate on when this might be ready? If you are too busy these days I could look into it: I should have some good quantities of time in the next couple of weeks.

**Comment by MoOx** [comment]
I've locally a wip almost ready. I will try to stabilize things tomorrow and will push the wip so you can help if you want.

**Comment by MoOx** [comment]
@davidtheclark here is the start https://github.com/MoOx/cli-for-files (name subject to change if, like me, you find this one shitty and have a better idea).
I added you as a collab

I extract what I did for cssnext and looked at some others tools like babel. I started to create an simple API to apply a transformation easily on any input. I just ensured a simple test pass for now (file input > file output). I hope README example is clear enough to show what users will be able to do with this module (or maybe for now, HOW).

Let me know using issue if you are going to handle something, there is some `// TODO` in the codebase. 
I don't have a lot of time indeed (like 1h everyday at max), but I will do my best to finish what I started :)
That said, any help is welcome via issue/PR.

**Comment by davidtheclark** [comment]
@MoOx Ok, I will probably be able to take a look sometime this weekend and see if there's anything I can do. Thanks.

**Comment by davidtheclark** [comment]
> I will do my best to finish what I started

@MoOx If that means you aren't super interested in working on the project, you certainly don't have to finish. I can just work on a solution that works for stylelint specifically. Let me know what you think.

**Comment by MoOx** [comment]
@davidtheclark For personal reasons, I am focusing myself currently on some other stuff that css atm (I am not saying that I using inline styles & shit ^^). I am just not as active as I was for postcss/cssnext...
But I think the module I started to work on is a good candidate for stylelint and postcss too, and probably for other modules.

Since I don't really work on stylelint, feel free to do whatever you want. I just think using a module to handle those stuff (cli input) that some others might need too is a good idea.

If you create something specific, you will end up by doing pretty much the same the module will do (except maybe the output part, but this part should be totally disabled/enabled by an option).

**Comment by davidtheclark** [comment]
@MoOx I think stylelint will need a small subset of what you have planned for cli-for-files (which I think are good plans). stylelint won't need output or watching, for example, just file reading.  So I think that I'm going to see if it won't be pretty quick to implement what stylelint needs on its own; and if I do write that we'll just integrate a more generic module whenever it's ready.

**Comment by MoOx** [comment]
ok

**Comment by davidtheclark** [comment]
Done in https://github.com/stylelint/stylelint/pull/380
