### ISSUE TITLE
Investigate alternative code coverage analysis suite

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2880]
![screen shot 2017-09-12 at 3 38 04 pm 2](https://user-images.githubusercontent.com/1016458/30310059-d7483242-97d1-11e7-8fd2-841a71b6a4ac.png)

The above screenshot shows the code coverage report differences between local code coverage reporting and that of our current analysis tool Coveralls.

• `https://coveralls.io/builds/13227720/source?filename=lib%2Futils%2FisCustomElement.js`
• `file:///dev/stylelint/stylelint/.coverage/lcov-report/lib/utils/isCustomElement.js.html`

The local coverage checkout shows the `I` (Yellow with Black background) which when hovered over states `if path not taken` signalling that the `if` path has not been tested ([ref](https://stackoverflow.com/questions/26618243/how-do-i-read-an-istanbul-coverage-report#36697606))

It's a shame this can't be seen on the Coveralls report, I'm wondering if switching to another code coverage reporting tool such as [Codecov](https://codecov.io/) (which is the only alternative I know of) would improve code coverage reporting for stylelint? 🤔 

I'd hoped a refactor if the test layout might have helped in #2879 but it didn't ;)

Anyone know of other alternatives and/or have views on Codecov vs Coveralls?

**Comment by gucong3000** [comment]
[codecov](https://codecov.io/) is support for appveyor,

**Comment by gucong3000** [comment]
> Anyone know of other alternatives and/or have views on Codecov vs Coveralls?
https://sonarcloud.io/

**Comment by jeddy3** [comment]
> It's a shame this can't be seen on the Coveralls report, I'm wondering if switching to another code coverage reporting tool such as Codecov (which is the only alternative I know of) would improve code coverage reporting for stylelint?

SGTM. You're closest to the infrastructure stuff, and I trust your judgment. If you find a suitable alternative then let's give it a go.

**Comment by gucong3000** [comment]
Command failed `npm run jest -- --runInBand --coverage --testPathPattern \lib` on appveyor.
```shell
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
- [log - node 8.4.0 (x64)](https://ci.appveyor.com/project/stylelint/stylelint/build/4808#L113)
- [log - node 8.4.0 (x86)](https://ci.appveyor.com/project/stylelint/stylelint/build/4806#L111)

Does anyone know why?

**Comment by gucong3000** [comment]
https://codecov.io/gh/stylelint/stylelint/branch/codecov-test
Everything looks normal except for Appveyor.

**Comment by jeddy3** [comment]
> Does anyone know why?

It runs out of memory. I believe there's a bit more memory to play with on travis, which is why we currently only run coverage there. @ntwb Is that right?

**Comment by gucong3000** [comment]
```shell
 RUNS  lib/rules/font-weight-notation/__tests__/index.js

<--- Last few GCs --->

[6380:0000017B1C937110]   225281 ms: Mark-sweep 1400.8 (1482.2) -> 1400.8 (1482.2) MB, 2182.4 / 0.1 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001EB4F61CEA9 <JSObject>
    2: /* anonymous */ [E:\work\stylelint\node_modules\lodash\lodash.js:16843] [bytecode=00000024CD1678B9 offset=33](this=000002162CA7F8D1 <JSGlobal Object>,methodName=00000024CD118C59 <Strin
g[4]: take>,index=1)
    3: arguments adaptor frame: 3->2
    5: arrayEach [E:\work\stylelint\node_modules\lodash\lodash.js:537] [bytecode=00000024CD15E0F1 offset=46](this=000002162CA7F8D1 <JSGlobal Object...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
The same thing happened to me locally.

**Comment by jeddy3** [comment]
> The same thing happened to me locally.

In [the past](https://github.com/stylelint/stylelint/issues/2168), we had a memory leak. Perhaps we've sprung another. Debugging memory leaks is likely new territory for some of us, and so any help investigating this would be fantastic!

**Comment by ntwb** [comment]
Unfortunately Codecov also misses the same info that Coveralls misses

https://codecov.io/gh/stylelint/stylelint/src/67cdcec5b8d59c8d9d059e138688d4be46a95d39/lib/utils/isCustomElement.js
![screen shot 2017-09-22 at 12 54 47 pm](https://user-images.githubusercontent.com/1016458/30727554-4d789b30-9f95-11e7-98c9-64f77198be9e.png)

I'll close this issue and the #2890 PR, if someone happens upon another code coverage tool that improves on Codecov and Coveralls please open up a new issue and we'll take a look 👍 

p.s. AppVeyor historically have assigned small amounts of RAM for open source projects, we've had the stylelint org bumped up plans directly by AppVeyor numerous times, there's a possibility that that has been changed again though it's pure speculation. For now let's leave things as they are as debugging those memory leaks last time was quite complex and time consuming, let's see how AppVeyor performs for the next few weeks and revisit if needed in a new issue.

**Comment by gucong3000** [comment]
I forgot to mention
`codecov` will report the diff coverage in PRs.
![image](https://user-images.githubusercontent.com/1171691/30728244-2d3484b2-9f89-11e7-8d1d-da38c61e184e.png)
