### ISSUE TITLE
Is Stylint capable of doing CSS quality analysis?

### ISSUE THREAD

**Issue by gkatsanos** [stylelint/stylelint#2884]
Some examples : code duplication? 
So essentially going a bit further than just coding style.
(if not, are there any tools which do that?)

**Comment by jeddy3** [comment]
Yes. The [list of rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md) is broken down into three categories:

-   [Possible errors](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors).
-   [Limit language features](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#limit-language-features).
-   [Stylistic issues](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#stylistic-issues).

Where stylistic issues are, arguably, the least important category for code quality.

Within the "possible errors" category, there are a number of `no-duplicate` rules. As well as rules for managing specificity, and checking for overrides etc.

The "limit language features" rules allow a team to specify exactly what features of CSS a team can and can't use within a project e.g. what units are allowed etc. For me personally, I use this category extensively on projects as I believe it brings consistency to the code base.

Additionally, check out the [VISION.md](https://github.com/stylelint/stylelint/blob/master/VISION.md) if you're interested in an overview of stylelint.

**Comment by evilebottnawi** [comment]
@gkatsanos if you have idea about new quality analysis rules, you can create new issue with description this rule (one issue on one new rule):+1:
