### ISSUE TITLE
CLI displaying a summary of warnings/errors

### ISSUE THREAD

**Issue by gkatsanos** [stylelint/stylelint#2885]
Is there a plugin or an option to display a summary of warnings/errors just at the end of the errors output?

**Comment by jeddy3** [comment]
Use the [verbose formatter](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md#formatter).

```
stylelint "**/*.scss" --formatter verbose
```

Also, use the `stylelint --help` command for a list of CLI options. The [Node API documentation](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md) within the [User Guide](https://github.com/stylelint/stylelint/tree/master/docs/user-guide) contains more details about what these options are.

**Comment by gkatsanos** [comment]
God I love this tool.

**Comment by ntwb** [comment]
Thank YOU @gkatsanos, a very gracious gesture, thanks on behalf of the entire stylelint team ❤️
