### ISSUE TITLE
lets discuss prettier-stylelint :)  

### ISSUE THREAD

**Issue by hugomrdias** [stylelint/stylelint#2898]
hi guys so i made [prettier-stylelint](https://github.com/hugomrdias/prettier-stylelint) hope you like it.
First would love some feedback on it!

Second some topics to discuss

- disabling config, can you guys review this [file](https://github.com/hugomrdias/prettier-stylelint/blob/master/config.js) to double check if i missed anything. Basically this file has all the rules that conflict with prettier or should be handled by it.
-  as stylelint adds more fixable rules we should remove those rules from the disabling config and let stylelint fix after prettier. do you agree ?
- can you confirm that using the api, stylelint still uses node-ignore to ignore `.stylelintignore` ? should i also ignore on my side .gitignore and .prettierignore?
- now the hacks :) 

```
const linterAPI = stylelint.createLinter();
linterAPI._fullExplorer
        .load(file)
        .then(({ config }) => resolve(config));
```

i need to do this to get all the final config extended and merged to infer prettier options, do you consider this ok or should we add a proper method to the stylelint public api?

```
const tempPath = tempWrite.sync(
    prettier.format(text, prettierConfig), 'fix-stylelint' + path.extname(filePath)
);
```

and finally when using fix === true the fixed code isn't returned in the PostCSS result, so i need to use the files options and get the code from a temp file. There are already several issues opened related to this.

**Comment by Arcanemagus** [comment]
@hugomrdias You can use `linterAPI.getConfigForFile(filePath)` to get the config using the actual API 😉.

There is also `linterAPI.isPathIgnored(filePath)`.

**Comment by hugomrdias** [comment]
which is the exactly the same thing several levels deeper in the code. I was looking for something simpler without calling createLinter(), more like `stylelint.resolveConfig()` that only returns the rules extended or if it returns everything to have a way to avoid doing the same thing here https://github.com/stylelint/stylelint/blob/5b730f88ec4ce2f97356d05e2b51982e335d245e/lib/lintSource.js#L62

**Comment by lydell** [comment]
@hugomrdias So prettier-stylelint is inspired by [prettier-eslint](https://github.com/prettier/prettier-eslint). Are you aware that [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) exists as well?

- prettier-eslint: New tool. Use when you disagree with Prettier's output and want `eslint --fix` to fix that for you.
- eslint-plugin-prettier: Runs inside ESLint (it's just a plugin). When you agree with Prettier's output and don't want a new tool.

Since you didn't create stylelint-plugin-prettier I am curious what you don't like about Prettier's CSS formatting and that `stylelint --fix` can fix? I have contributed a bit to Prettier's CSS handling, and I would find this to be good feedback :)

**Comment by ntwb** [comment]
We've a pretty long previous discussion on Prettier and stylelint in #2532 

Starting around this comment https://github.com/stylelint/stylelint/issues/2532#issuecomment-301328771 is where the stylelint team started to nail down what we think Prettier for stylelint would be from an architectural point of view.

We'll need to all probably take a bit of re-read of that now that 8.0.0 is out to refresh our memory!

**Comment by hugomrdias** [comment]
@lydell i created a prettier issue to keep this one stylelint specific

**Comment by iki** [comment]
@hugomrdias Thanks for the effort to integrate Stylelint and Prettier!

Can be [prettier](https://github.com/prettier/prettier) used not as a dependency of [prettier-stylelint](), but a separate package (called externally), so user has control over prettier version?

Or, what about reimplementation rather as a [stylelint plug-in](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md)?

Similar approach is useful for TypeScript, where we have [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier) to disable tslint-* rules conflicting with prettier, and [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier) to check formatting with prettier.

Actually, there already exists [stylelint-config-prettier](https://github.com/shannonmoeller/stylelint-config-prettier), so only `stylelint-plugin-prettier` is needed.

It would imo also make sense also from user perspective to use common `stylelint` or `stylelint --fix` commands.

How does it fit your needs?

**Comment by hugomrdias** [comment]
prettier as separate package, how would that work ? file relative imports are already in place so you can control the version for specific files and folder.

prettier-stylelint was created for the same reasons prettier-eslint was, basically if the user doesn't like something in the prettier formatting use the next tool to fix it. 

Also a stylelint config is included no need to add yet another package and as stylelint adds more fixable rules that config will become smaller and smaller until we can run prettier and stylelint without exceptions. 

Regarding the use of common commands i agreed that adding another middle man tool isn't optimal but the only other way i see is to include integration onto prettier itself. We did that with the vscode prettier extension, the user can just activate prettier-stylelint or prettier-eslint in the options no need to install a different extension.

Please feel free to open an issue with any suggestions.

**Comment by jeddy3** [comment]
Closing this issue here. Users looking to discuss further can do so in the prettier-stylelint repo.

@hugomrdias Thanks again for your work on prettier-stylelint. It looks like a look of people find it very useful :)
