### ISSUE TITLE
Increase flow coverage

### ISSUE THREAD

**Issue by CAYdenberg** [stylelint/stylelint#2935]
A few places we could gain some ground adding Flow annotations, without diving into the rules.

- [x] lib/utils/getCacheFile
- [x] lib/utils/hash.js
- [x] lib/utils/isAfterSingleLineComment.js
- [x] lib/utils/whitespaceChecker.js
- [x] lib/formatters/needlessDisablesStringFormatter.js
- [ ] lib/formatters/stringFormatter.js
- [x] lib/formatters/verboseFormatter.js

**Comment by jeddy3** [comment]
SGTM

**Comment by glen-84** [comment]
Should this be closed now? (see #4451)

**Comment by jeddy3** [comment]
Yep. `stringFormatter` [has types now](https://github.com/stylelint/stylelint/blob/master/lib/formatters/stringFormatter.js) too.
