### ISSUE TITLE
postcss ignores .stylelintignore

### ISSUE THREAD

**Issue by BamaBoy** [stylelint/stylelint#2949]
Here's my webpack snippet:
```
    {
        test: /\.css$/,
        use: [
          require.resolve('style-loader'),
          {
            loader: require.resolve('css-loader'),
            options: {
              importLoaders: 1
            },
          },
          {
            loader: require.resolve('postcss-loader'),
            options: {
              plugins: () => [
                require('postcss-import'),
                require('stylelint')(),
                require("postcss-reporter")(),
              ]
            },
          },
        ],
      },
```

I have `.stylelintignore` located next to `package.json`. 
CLI rescpects `.stylelintignore` ( command `stylelint "**/*.css"`), but postss ignores it.
Is this my mistake or is this a bug?

**Comment by jeddy3** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
