### ISSUE TITLE
Pluggable custom rules

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#295]
We already have a few ideas for custom rules:

- Nesting depth (#291)
- Special indentation for related selectors (#278)

So I thought I'd open this issue for building out and documenting the functionality needed for people to easily create custom rules.

**Comment by ai** [comment]
What will be best way to distribute plugin specific linters? Put them into plugin? Or make some `stylelint-precss` linters set?

**Comment by davidtheclark** [comment]
I thought about this a little today and wanted to run an API possibility by everybody.

Here's the idea:

We add a `plugins` property to the config. It expects an object. For each property of the object, if its value is a function, that function is added to the rule definitions, named according to its key; and if the value is another object, it is recursively treated the same way.

So you could do the following:

```js
module.exports = {
  plugins: {
    foo: function(options) { .. },
    bar: function(options) { .. },
    baz: {
      bazFoo: function(options) { .. },
      bazBar: function(options) { .. }
    }
  },
  rules: [ .. ]
}
```

In the above example, `foo` and `bar` are individual linting rules, while `baz` is a *set* of linting rules (e.g. `stylelint-precss`).

Each plugin-rule would have the same signature as our rules: 

```js
function(expectation, options) {
  return function(root, result) { .. }
}
```

What do you think? Would this work?

**Comment by jeddy3** [comment]
Sgtm. Although I'm the least experienced of us all when it comes to plugin architecture. The `plugin` property in the config makes a lot of sense though.

**Comment by davidtheclark** [comment]
This is presuming that the configuration is an actual JS object, instead of JSON or YML. Does anybody see a problem with that?
