### ISSUE TITLE
False negative when using tab indentation and declaration-colon-newline-after

### ISSUE THREAD

**Issue by BillyBlaze** [stylelint/stylelint#2951]
Edit:
Sorry, totally invalid bug. closing this. sorry for the created issue.

**Comment by oyeanuj** [comment]
@BillyBlaze I think I am running into this as well - wondering why was this invalid? Did you solve it somehow?

**Comment by BillyBlaze** [comment]
@oyeanuj 

Sorry I am on vacation and I cannot look at the code base for a while.
From the top of my mind: I think I had the indentation with the config `except: ["value"]`. After removing this, everything worked fine.
