### ISSUE TITLE
Add no-duplicate-at-import-rules

### ISSUE THREAD

**Issue by s10wen** [stylelint/stylelint#2954]
Hi, wondering if there's a rule that could warn for the following issues please?

Same path imported:
```
@import "test/test";
…
@import "test/test";
```

Same variable declared:
```
$test: #f00;
…
$test: #b00;
```

**Comment by evilebottnawi** [comment]
maybe no `at-rule-no-duplicate-import`?

**Comment by s10wen** [comment]
@evilebottnawi had a search at https://stylelint.io/user-guide/rules/ but couldn't find that one. Is it in the code base, but no docs? Can you link to me to any further info please?

**Comment by s10wen** [comment]
A mate of mine wrote the following `bash` for this if it's useful to handle the `import` issue.

```
function findDuplicateSassImports() {
    find $ELYSIUM_DIR/src/main/webapp -type f -name '*.scss' | while read filepath; do
        grep -Pzo '(?s)(@import .+;).*\1' $filepath | head -n1 | while read x; do
            echo "$filepath : $x";
        done
    done
}
```

**Comment by jeddy3** [comment]
> maybe no at-rule-import-no-duplicate?

Yes, such a rule would be in line with the existing `no-duplicate-*` rules. They check code that, despite being _valid_, is probably a mistake.

Calling the rule `no-duplicate-at-imports` would follow the [naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md#about-rule-names) as it's [scoped to the source](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#general--sheet), like the existing `no-duplicate-selectors` rule.

> Is it in the code base, but no docs? Can you link to me to any further info please?

I think @evilebottnawi is suggesting it as a new rule.

@stylelint/core If there aren't any objections, I'll label this as a new rules and help wanted.

> Same variable declared:

Yes, a separate rule/plugin could also be built for that too. The built-in stylelint rules only check standard CSS syntax. As dollar variables are non-standard constructs, this would be best suited as a plugin. In fact, I think it'd be a perfect fit for [stylelint-scss plugin pack](https://github.com/kristerkari/stylelint-scss). Have a chat to the guys over there about it. They might welcome the contribution of that plugin.

**Comment by evilebottnawi** [comment]
@jeddy3 agree new rule

**Comment by s10wen** [comment]
Thanks for clarifying, I'll head over to https://github.com/kristerkari/stylelint-scss and discuss from there.

**Comment by evilebottnawi** [comment]
I think `no-duplicate-at-import-rules` should be in `core` rules, @jeddy3 what do you think?

**Comment by jeddy3** [comment]
Yeap, that's what I mean above.

- `no-duplicate-at-import-rules` - built-in rule as for standard construct (`@import`).
- `no-duplicate-dollar-variables` - plugin in the stylelint-scss plugin pack as for non-standard construct (dollar variables).

**Comment by jeddy3** [comment]
As no objections yet, I'm going to label this up as ready to go.

- Name: `no-duplicate-at-import-rules`
- Description: Disallow duplicate `@import` rules within a stylesheet.
- Primary option: `true`
- Secondary options: none
- Message: "Unexpected duplicate `@import` rule "${atImport}"
- Section: "Possible errors -> General / Sheet"

Remember to test [urls, string and media query lists](https://drafts.csswg.org/css-cascade-3/#at-import).

@s10wen Feel free to [contribute](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#creating-a-new-rule) this rule if you'd like to see it built-in to stylelint. There's prior art in [`no-duplicate-selectors`](https://github.com/stylelint/stylelint/tree/master/lib/rules/no-duplicate-selectors) and [`declaration-block-no-duplicate-properties`](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-no-duplicate-properties), but this rule should be simplier.

**Comment by agatac** [comment]
Hi, I'd like to give it a try (first time contributor).

**Comment by jeddy3** [comment]
> Hi, I'd like to give it a try (first time contributor).

Excellent. The ["Working on rules" section](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) of the Developer Guide has plenty of useful information to help you get started. Good luck and feel free to ask questions here.

**Comment by agatac** [comment]
Hi, I could use some help. Could you walk me through the process of testing the rule? Can I test a single rule instead of all of them?

**Comment by agatac** [comment]
Hi, I started here #2963. Could you point me in the right direction?

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/2963

**Comment by kristerkari** [comment]
@s10wen @jeddy3 @evilebottnawi  I have implemented `no-duplicate-dollar-variables` in a PR over at https://github.com/kristerkari/stylelint-scss/pull/239. 

Maybe you could have a look at the PR and let me know if there are some obvious things or edge cases that I'm missing from the rule?
