### ISSUE TITLE
Rename stylelint repo labels to aid new contributors

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#2969]
![screen shot 2017-10-16 at 2 07 08 pm](https://user-images.githubusercontent.com/1016458/31593622-1f6eb8be-b273-11e7-804a-2df15780d0e6.png)

I've just seen the displayed here on the stylelint repo here.

@stylelint/core should we change these labels to match this new GitHub feature?

https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

We'd need to change the following two statuses:

 • From [status: help wanted](https://github.com/stylelint/stylelint/labels/status%3A%20help%20wanted) to [help wanted](https://github.com/stylelint/stylelint/labels/help%20wanted)
 • From [beginner friendly](https://github.com/stylelint/stylelint/labels/beginner%20friendly) to [good first issue](https://github.com/stylelint/stylelint/labels/good%20first%20issue)

p.s. I think we should definitely do this, I created the issue rather than just doing it as heads up, I expect most, if not all repos across GitHub will make changes to standardise on these labels.

**Comment by jeddy3** [comment]
SGTM.

We've had quite a few first-time contributors in the last couple of weeks. It's been nice experience :) So, anything to encourage more of that is a good thing.

**Comment by ntwb** [comment]
Cool, looks like someone has already done the rename, closing.
