### ISSUE TITLE
\u doesn't support 10000+

### ISSUE THREAD

**Issue by Aladdin-ADD** [stylelint/stylelint#2974]
https://github.com/stylelint/stylelint/blob/adb9158b9d928017a4c5ae92b367482f0a72b026/lib/rules/font-family-name-quotes/index.js#L40

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.

**Comment by Aladdin-ADD** [comment]
aha, not a English speaker~(✿◕‿◕✿)

in short, `\u` doesn't support 10000+, so I guess here is a bug.
![image](https://user-images.githubusercontent.com/13050025/31741746-f3221bea-b487-11e7-8039-3812f6729e0b.png)

refs:

**Comment by Aladdin-ADD** [comment]
not a English speaker d=====(￣▽￣*)b
in short `\u` doesn't support 10000+, so I guess here is a bug..

![image](https://user-images.githubusercontent.com/13050025/31741899-85a06f9e-b488-11e7-9018-597ccd6dd70d.png)

**Comment by jeddy3** [comment]
@Aladdin-ADD Can you submit a Pull Request with failing tests, please?

This might help us overcome the language barrier.
