### ISSUE TITLE
How can I configure stylelint to accept styles from react-native?

### ISSUE THREAD

**Issue by sibelius** [stylelint/stylelint#2987]
Based on this https://github.com/styled-components/stylelint-processor-styled-components/issues/134

I'm receiving this following error when runnnig the lint based on styled-components preprocessor

24:3   ✖  Unexpected unknown property "padding-horizontal"   property-no-unknown
 25:3   ✖  Unexpected unknown property "padding-vertical"     property-no-unknown

How can I write a custom rule/plugin/processor to handle this case for React Native projects?

**Comment by jeddy3** [comment]
Either [configure the rule to ignore these non-standard properties](https://github.com/stylelint/stylelint/blob/master/lib/rules/property-no-unknown/README.md#ignoreproperties-regex-string) or [don't turn the rule on](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#rules).

**Comment by sibelius** [comment]
fixed with this .stylelintrc

```jsx
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss",
  "rules": {
    "block-no-empty": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "block-closing-brace-newline-before": null,
    "indentation": null,
    "property-no-unknown": [ true, {
      "ignoreProperties": [
        "padding-vertical",
        "padding-horizontal",
        "shadow-color",
        "shadow-offset",
        "shadow-radius",
        "shadow-opacity"
      ]
    }
    ]
  }
}
```

tks
