### ISSUE TITLE
Atom editor auto fixer support?

### ISSUE THREAD

**Issue by Vertigoooo** [stylelint/stylelint#2994]
Hi I am using the atom editor, and the atom package for linter-stylelint:
https://atom.io/packages/linter-stylelint
I saw there is an auto fix option, I am currently using stylefmt (and didn't really understand how to configure it to use stylelint)
 but I would like to use the available tool is there any option to add that ?

**Comment by hudochenkov** [comment]
Please, create an issue in https://github.com/AtomLinter/linter-stylelint repository.
