### ISSUE TITLE
Drop Node.js 4 support

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2996]
Shall we drop Node.js 4 support in the next major version?

Today [Node.js 8 moved to LTS](https://medium.com/the-node-js-collection/news-node-js-8-moves-into-long-term-support-and-node-js-9-becomes-the-new-current-release-line-74cf754a10a0) (i. e. it's now production ready). Node.js 4 became more legacy and outdated. It's in maintenance mode [since April 2017](https://github.com/nodejs/Release), which will end in April 2018.

It will give our codebase and us a breath of fresh air. There are a bunch of awesome stuff starting Node.js 6, which are missing in Node.js 4: default function parameters, rest parameters, spread operator, destructuring, no need for `'use strict'` to use `let, const`. Currently, we have to use “old” methods to do what these ES6 features do, which leads to more code.

Also, we'll have lower test time in CI (if we won't add Node.js 9 :)).

---

Not related: we've just passed 4000 stars :)

**Comment by jeddy3** [comment]
> Currently, we have to use “old” methods to do what these ES6 features do, which leads to more code.

Anything that helps to reduce the burden of maintenance gets a thumbs up from me! 

(FYI, I recently started a new contract and so I will be balancing my time on stylelint with that over the next few of months.)

> Not related: we've just passed 4000 stars :)

🎉  Congrats everyone :)

**Comment by CAYdenberg** [comment]
👍

**Comment by ntwb** [comment]
So that's 3 thumbs up from me 👍 👍 👍 
• 👍  Drop Node.js 4.x 
• 👍  4000 stars
• 👍  @jeddy3 new contract

**Comment by ntwb** [comment]
I've created #3075, it bumps the minimum Node.js version to `6` in `package.json` and rmoves the Travis CI 4.x job from `.travis.yml`

Feel free to submit pull requests for Node.js 6.x enhancements 🎉
