### ISSUE TITLE
TypeError: "Expected `moduleId` to be of type `string`, got `function`" in Node.js 9.0.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [stylelint/stylelint#2998]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where stylelint crashes with a TypeError.

> Which rule, if any, is this issue related to?

Not related to any particular rule.

> What CSS is needed to reproduce this issue?

Any CSS.

> What stylelint configuration is needed to reproduce this issue?

```json
{"extends": "stylelint-config-standard"}
```

> Which version of stylelint are you using?

`8.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API with

```js
stylelint.lint({
    code: "",
    codeFilename: undefined,
    config: {extends: require.resolve("stylelint-config-standard")}
});
```

I am using `require.resolve()` here as a workaround for this issue: https://github.com/stylelint/stylelint/issues/1973

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

No crashing.

> What actually happened (e.g. what warnings or errors you are getting)?

A TypeError is thrown:

```text
Expected `moduleId` to be of type `string`, got `function`
          ---
          stack: >
            resolveFrom (node_modules/stylelint/node_modules/resolve-from/index.js:11:9)
          
            Function.module.exports.silent
            (node_modules/stylelint/node_modules/resolve-from/index.js:35:48)
          
            module.exports (node_modules/stylelint/lib/utils/getModulePath.js:13:26)
          
            loadExtendedConfig (node_modules/stylelint/lib/augmentConfig.js:188:22)
          
            resultPromise.then.resultConfig
            (node_modules/stylelint/lib/augmentConfig.js:163:16)
          
            <anonymous>
          at:
            line: 11
            column: 9
            file: node_modules/stylelint/node_modules/resolve-from/index.js
            function: resolveFrom
          type: TypeError
          test: stylelint
          source: >
            throw new TypeError(`Expected \`moduleId\` to be of type \`string\`, got
            \`${typeof moduleId}\``);
```

**This bug is present only in Node.js 9.0.0.**

**Comment by hudochenkov** [comment]
Thank you for reporting and for using a template. Currently, Node.js 9 is unstable. Even latest `npm` doesn't work with it https://github.com/nodejs/node/issues/16649 Also, we can't use Travis to test in Node.js 9 https://github.com/stylelint/stylelint/pull/2999

We'll hold our forces to dig into this problem for now.

**Comment by EvgenyOrekhov** [comment]
@hudochenkov Somehow npm 5.5.1 works fine with Node.js 9.0.0 in my Travis builds: https://travis-ci.org/EvgenyOrekhov/lints/jobs/295689025#L445-L448

**Comment by hudochenkov** [comment]
@EvgenyOrekhov we explicitly install the latest npm: https://github.com/stylelint/stylelint/blob/38d23e035287dac95c28729d4bd45ef5a9c4f885/.travis.yml#L35-L36

npm shipped with Node.js 9 works (which you use), but npm installed from npm — doesn't.

**Comment by ntwb** [comment]
Agreed, let's wait for npm and node to release some updates before investigating further 😄

**Comment by EvgenyOrekhov** [comment]
Closing since this bug is not related to stylelint, it is related to the bug in Node.js and the way I used `require.resolve()`.

See https://github.com/nodejs/node/issues/16687.
