### ISSUE TITLE
Fix autofix writing to files that aren't changed

### ISSUE THREAD

**Issue by edi9999** [stylelint/stylelint#3003]
This is a **bug**. 

When running stylelint --fix, stylelint will do a file write to the file even if the file did not change at all.
This makes webpack (or other file watchers) trigger a new build for nothing.

> What CSS is needed to reproduce this issue?

any css wil do the trick
any stylelintrc too

You can verify that there was a write with these commands : 

```
strace -f -yy -ttt 2>/tmp/straced ./node_modules/stylelint/bin/stylelint.js css/_unity.scss  --fix
grep --color -E  write </tmp/straced | grep --color -E scss
```

As you can see, there was a write to 

```
[pid  1714] 1509729135.599998 pwrite64(12</var/www/lib/ui/css/_unity.scss>, "[class^=\"unity_\"], [class*=\" uni"..., 73, 0) = 73
```

**Comment by jeddy3** [comment]
@edi9999 Thanks for the report.

This was first raised in https://github.com/stylelint/stylelint/issues/2991#issuecomment-339988328, but it's better to have a separate issue for it. This was considered an optimisation in the other issue, but I think you're right that this is a bug because tools like webpack will not be expecting this behaviour.

Labeling as bug and help wanted. @edi9999 Feel free to jump into the code if you'd like to see this fixed.

**Comment by edi9999** [comment]
Before getting started I just wanted to know how I could implement it. Should I verify that the contents of the file differs from the new file content, or should I use a flag that is set in the `fixer` that would be set to true once a fix was applied to the file?

**Comment by jeddy3** [comment]
Is there an established best practise for this kind of thing?

It feels like setting a flag and then only working on the flagged files sounds like the most performant way to go about this.

**Comment by edi9999** [comment]
I think the best practrice would be to use a flag indeed.

That is what they do in eslint I think :  

```
    if (fixedResult.fixed) {
        result.output = fixedResult.output;
    }
```
https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L199

```
    static outputFixes(report) {
        report.results.filter(result => result.hasOwnProperty("output")).forEach(result => {
            fs.writeFileSync(result.filePath, result.output);
        });
    }
```
https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L451

So it makes sense do to the same in stylelint

**Comment by jeddy3** [comment]
> So it makes sense do to the same in stylelint

Agreed.

**Comment by edi9999** [comment]
I will try to give it a shot for the end of this week.
