### ISSUE TITLE
Add ignoreProperties: [] to property-no-vendor-prefix

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3007]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I use Stylelint with an Electron app where I have to use a few vendor prefixed properties.

> Which rule, if any, is this issue related to?

`property-no-vendor-prefix` and `value-no-vendor-prefix`

> What CSS is needed to reproduce this issue?

e.g.

```css
div {
	-webkit-app-region: drag;
	cursor: -webkit-grab;
}
```

I'm aware I could run Autoprefixer, but that's a waste for only two properties. And it's annoying to have to add a lot of inline ignore comments.

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "property-no-vendor-prefix": true,
    "value-no-vendor-prefix": true
  }
}
```

> Which version of stylelint are you using?

`8.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint --config myconfig *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

I expected these rules to have an `ignore` option like many other rules have.

> What actually happened (e.g. what warnings or errors you are getting)?

The vendor prefixes got reported.

**Comment by jeddy3** [comment]
The use case makes sense.

> `property-no-vendor-prefix` and `value-no-vendor-prefix`

I'll break this issue into two separate ones. This one can be for adding a `ignoreProperties: []` optional secondary option to `property-no-vendor-prefix`.

There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to add options if someone would like to pick this up.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/3089
