### ISSUE TITLE
Support regex literals in all options that accept regexes

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3008]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Many of the Stylelint rule options supports regexes, but they require having the regexes in a string. For JS based configs, it would be much nicer to specify them as regex literals. Some rules supports this already, like the `selector-class-pattern` and `selector-id-pattern` rules, while the `declaration-property-value-blacklist` rule does not and require string `'/thin/'`.

> Which rule, if any, is this issue related to?

`declaration-property-value-blacklist`, but really any rule that supports regexes, should also support regex literals.

> What CSS is needed to reproduce this issue?

Does not apply.

> What stylelint configuration is needed to reproduce this issue?

Does not apply.

> Which version of stylelint are you using?

`8.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`stylelint --config myconfig *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

I expected to be able to use regex literals in options.

> What actually happened (e.g. what warnings or errors you are getting)?

It didn't work.

**Comment by jeddy3** [comment]
Sounds good.

I suspect these inconsistencies crept in as new rules were added with this feature, but the feature wasn't backported to the older rules.

Labelling as enhancement and help wanted.

**Comment by kevva** [comment]
I think https://github.com/stylelint/stylelint/blob/master/lib/utils/matchesStringOrRegExp.js should be updated instead of the rules themselves. You could use https://github.com/sindresorhus/is-regexp to check if it's a regex.

**Comment by ntwb** [comment]
Hey, @kevva Did you take a look at this? If not would you be interested still?

**Comment by jeddy3** [comment]
> I think https://github.com/stylelint/stylelint/blob/master/lib/utils/matchesStringOrRegExp.js should be updated

This was done as part of https://github.com/stylelint/stylelint/pull/3087.

> instead of the rules themselves

I believe that all there is left to do is update the options validator config in each applicable rule so that RegExp are accepted. We'd also want to update/add some appropriate tests. Examples of both can be found in https://github.com/stylelint/stylelint/pull/3087.

**Comment by CAYdenberg** [comment]
This is a bit of a chore but here is everything that I think needs to be updated. I got tired of checking the code when I got into the secondary options, so it's possible some of those are already covered - just check the box or comment in thread if so.

- [x] selector-class-pattern
- [x] selector-id-pattern
- [x] selector-pseudo-element-*list
- [x] keyframes-name-pattern
- [x] custom-media-pattern
- [x] custom-property-pattern
- [x] selector-nested-pattern
- [ ] function-linear-gradient-no-nonstandard-direction
- [ ] comment-word-blacklist
- [ ] function-*list
- [ ] function-url-scheme-*list
- [ ] function-name-case (ignoreFunctions)
- [ ] media-feature-name-*list
- [ ] media-feature-name-value-*list
- [ ] property-*list
- [ ] selector-pseudo-class-*list (primary + selectorPseudoClasses)
- [ ] unit-*list (ignoreProperties, ignoreMediaFeatureNames)
- [ ] unit-no-unknown (ignoreUnits)
- [ ] value-keyword-case (ignoreKeywords, ignoreProperties)
- [ ] declaration-property-value-*list 
- [ ] at-rule-no-unknown (ignoreAtRules)
- [ ] selector-type-no-unknown (ignoreNamespace, ignoreTypes)
- [ ] number-max-precision (ignoreUnits)
- [ ] property-no-vendor-prefix (ignoreProperties)
- [ ] media-feature-name-no-unknown (ignoreMediaFeatureNames)
- [ ] declaration-block-no-duplicate-properties (ignoreProperties)
- [ ] block-*-brace-space-before (ignoreAtRules)
- [ ] max-line-length (ignorePattern)
- [ ] color-named (ignoreProperties)
- [ ] font-family-no-duplicate-names (ignoreFontFamilyNames)
- [ ] selector-max-attribute (ignoreAttributes)
- [ ] selector-max-specificity (ignoreSelectors)
- [ ] property-no-unknown (ignoreProperties)
- [ ] selector-max-type (ignoreTypes)
- [ ] max-nesting-depth (ignoreAtRules)
- [ ] declaration-block-no-redundant-longhand-properties (ignoreShorthands)
