### ISSUE TITLE
Add ignoreValues: [] to value-no-vendor-prefix

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3009]
Ref: https://github.com/stylelint/stylelint/issues/3007

There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to add options if someone would like to pick this up.

**Comment by Bebersohl** [comment]
I'll do this one
