### ISSUE TITLE
Disallow using /deep/, >>> and ::shadow

### ISSUE THREAD

**Issue by morriq** [stylelint/stylelint#3010]
Since it's depracated I want to disallow using /deep/, >>> and ::shadow. Could you tell me please how can I achieve that?

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.

**Comment by jeddy3** [comment]
@hudochenkov was right to request more information via the issue template. However, I had a personal curiosity about `/deep/`, `>>>` and `::shadow` as I've been poking around with Web Components (and the Shadow DOM). Incidentally, fascinating stuff!

I'm a great personal advocate of the [rules that limit language features](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#limit-language-features) (as I think they really help make a code base consistent) and this issue has highlighted two gaps in our coverage of `*-blacklist` and `*-whitelist` rules: [combinators](https://drafts.csswg.org/selectors-4/#combinators) and [pseudo-elements](https://drafts.csswg.org/selectors-4/#pseudo-elements). These could be used to disallow `>>>` (the [_shadow-piercing descendant combinator_](https://drafts.csswg.org/css-scoping/#deep-combinator))  and `::shadow`, respectively.

There is prior-art for these rules in [`selector-pseudo-class-whitelist`](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-pseudo-class-whitelist
) and [`selector-pseudo-class-blacklist`](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-pseudo-class-blacklist
). So, creating these new rules should just be about the legwork. They would make ideal first issues for someone, and I'll create now. 

I believe [`/deep/`](https://www.w3.org/TR/2014/WD-css-scoping-1-20140403/#deep-combinator) is a so-called [_reference combinator_](https://www.w3.org/TR/selectors4/#idref-combinators). I think we should restrict the `selector-combinator-*list` rules to non-reference combinators, and reference combinators should be covered by community plugins: `selector-reference-combinator-blacklist` and `selector-reference-combinator-whitelist`. 

When the four new rules and two community plugins are finished, a complete config could look like.

```json
{
  "rules": {
    "plugin/selector-reference-combinator-blacklist": ["deep"],
    "selector-combinator-blacklist": [">>>"],
    "selector-pseudo-element-blacklist": ["shadow"]
  }
}
```

@morriq Please [consider authoring](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) the `selector-reference-combinator-*list` plugins. FYI, references combinators, like `/deep/`, are parsed as a `tag` selector by [postcss-selector-parser](https://www.npmjs.com/package/postcss-selector-parser), so checking for them should be trival (if counter-intuitive).
