### ISSUE TITLE
feature request: use cosmiconfig for configuration file support

### ISSUE THREAD

**Issue by zyy7259** [stylelint/stylelint#3028]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

a feature request, use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for configuration file support

**Comment by Arcanemagus** [comment]
`cosmicconfig` is _already_ used here, in fact it was written inside `stylelint` and only split out to a separate module later 😕.
