### ISSUE TITLE
postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0

### ISSUE THREAD

**Issue by nikolay-borzov** [stylelint/stylelint#3035]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Looks like `postcss-html` got new peer dependency that isn't a `stylelint` dependency

> Which version of stylelint are you using?

 `8.3.0`

> What did you expect to happen?

Probably `postcss-sass` should be installed w/ stylelint

> What actually happened (e.g. what warnings or errors you are getting)?

Warning about unmet peer dependency

```shell
npm i stylelint -D
...
npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jeddy3** [comment]
@gucong3000 Thoughts?

**Comment by modosc** [comment]
fwiw we already have all the other `peerDeps` from `postcss-html@0.11.0` listed in `dependencies`

**Comment by gucong3000** [comment]
We can add `postcss-sass` to `dependencies` when finish #2503

**Comment by billyjanitsch** [comment]
@gucong3000 why does `postcss-html` have a peer dependency on `postcss-sass` at all? It doesn't seem like the former references the latter anywhere in its source.

**Comment by hudochenkov** [comment]
@billyjanitsch https://github.com/gucong3000/postcss-html/blob/6f252374c8ff0d10dc8317b76b5515add1d2397f/lib/get-syntax.js#L11-L12

**Comment by billyjanitsch** [comment]
Ah, thanks for the pointer @hudochenkov! That explains why it didn't turn up in a search.

**Comment by hudochenkov** [comment]
Done in https://github.com/stylelint/stylelint/pull/3040
