### ISSUE TITLE
Add autofix support for no-descending-specificity

### ISSUE THREAD

**Issue by modosc** [stylelint/stylelint#3036]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

since `no-descending-specificity` was just added to the recommended config i'm getting tons of errors in my work codebase. it would be nice to automatically fix these.

> Which rule, if any, is this issue related to?

`no-descending-specificity`

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

`stylelint-config-recommended`

> Which version of stylelint are you using?

e.g. `8.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

node api

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no
> What did you expect to happen?

n/a

> What actually happened (e.g. what warnings or errors you are getting)?

n/a

**Comment by jeddy3** [comment]
@modosc This would be amazing. I guess the first step would be to assess how viable this is as specificity and shifting around rules (especially nested one) are tricky.

**Comment by modosc** [comment]
@jeddy3 i see what you mean - since we're comparing the collapsed versions via `postcss-resolve-nested-selector` we don't have the original sass structure so it's hard to tell what we're reordering. 

and we don't want to normalize everything since deeply nested sass can cause other issues (and may violate `max-nesting-depth`. ugh.

**Comment by hudochenkov** [comment]
I don't believe it's possible to make autofix for this rule. Reordering rules is very error-prone. Autofix will most likely create other errors, and more frustration for a user. It's not safe manipulation.

Someone could prove me wrong and create a plugin for stylelint, which will utilize `no-descending-specificity` and add autofix.

**Comment by jeddy3** [comment]
> Someone could prove me wrong and create a plugin for stylelint, which will utilize no-descending-specificity and add autofix.

Experimental plugin SGTM.
