### ISSUE TITLE
--fix option mangles .vue files.

### ISSUE THREAD

**Issue by Gingernaut** [stylelint/stylelint#3049]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

BUG: Running style lint with the `--fix` parameter removes all non-scss from all vue files (all html, javascript, etc.)

Example file before running stylelint:
```javascript
<template>
  <div id="app">
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return { }
  }
}
</script>

<style lang="scss">
#app {
    background-color: red;
    color: #2c3e50;
}
</style>
```

after
```
#app {
    background-color: red;
    color: #2c3e50;
}
```

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

Any css/scss in vue files. Vue files without any styling are emptied.

> What stylelint configuration is needed to reproduce this issue?

in my `package.json`:
```json
{
"stylelint": {
    "plugins": [
      "stylelint-scss"
    ],
    "processors": [
      "stylelint-processor-html"
    ],
    "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null
    }
  },
}
```
I have the following stylelint `devDependencies`:
```json
{
    "stylelint": "^8.3.1",
    "stylelint-config-standard": "^18.0.0",
    "stylelint-processor-html": "^1.0.0",
    "stylelint-scss": "^2.1.0",
    "stylelint-webpack-plugin": "^0.9.0"
}
```

> Which version of stylelint are you using?

e.g. `^8.3.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

In my `package.json` scripts with  `stylelint '**/*.{vue,scss}' --syntax scss --fix`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

This issue occurs regardless of css or scss.

> What did you expect to happen?

To have the css/scss between `<style></style>` tags in `.vue` files to be linted and fixed.

** Reproduction

`mkdir vueBug && cd vueBug`
`vue init webpack-simple` (with yes for sass)

Add the following to your package.json
```json
"scripts": {
   "lint": "stylelint '**/*.{vue,scss}' --syntax scss --fix"
  },

"stylelint": {
    "plugins": [
      "stylelint-scss"
    ],
    "processors": [
      "stylelint-processor-html"
    ],
    "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null
    }
  },
"devDependencies": {
    "stylelint": "^8.3.1",
    "stylelint-config-standard": "^18.0.0",
    "stylelint-processor-html": "^1.0.0",
    "stylelint-scss": "^2.1.0",
    "stylelint-webpack-plugin": "^0.9.0"
  }
```
`npm install`
`npm run lint` <- This destroys the `.vue` files.

**Comment by gucong3000** [comment]
@Gingernaut 
There is an error in the configuration:
 ```diff
{
"stylelint": {
    "plugins": [
      "stylelint-scss"
    ],
-    "processors": [
-      "stylelint-processor-html"
-    ],
    "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null
    }
  },
}
```
Please delete these 3 lines.

**Comment by stavros-liaskos** [comment]
Note that `--syntax scss` might throw `Unknown word CssSyntaxError` as in #3633

**Comment by stavros-liaskos** [comment]
Note that `--syntax scss` might throw `Unknown word CssSyntaxError` as in #3633
