### ISSUE TITLE
Allow processors to handle PostCSS errors

### ISSUE THREAD

**Issue by chinesedfan** [stylelint/stylelint#3050]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Feature.

> Which rule, if any, is this issue related to?

Not related to a certain rule.

> What CSS is needed to reproduce this issue?

Not related to CSS codes.

> What stylelint configuration is needed to reproduce this issue?

The default configuration is enough.

> Which version of stylelint are you using?

8.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Node API.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

Even if `postcss` errors were caught, give processors a chance to handle it, or by another configurable way.

For example, `styled-components/stylelint-processor-styled-components` normally extracts styles from React components, passes to `stylelint` to lint, and recovers lint results with right line numbers. But if an error happened, line numbers can not be recovered any more.

> What actually happened (e.g. what warnings or errors you are getting)?

The program falls from [_lintSource](https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L216) into [handleError](https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L242) directly, skipping [_createStylelintResult](https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L239). So that [processors](https://github.com/stylelint/stylelint/blob/master/lib/createStylelintResult.js#L142) have no chance to be called.

**Comment by jeddy3** [comment]
@chinesedfan Thanks for the suggestion. 

It'd be great to have this as [being extensible](https://github.com/stylelint/stylelint/blob/master/VISION.md#extensible) is one of the goals of stylelint. @stylelint/core Unless anyone can foresee a problem with this, then I think this contribution would be very welcomed.

**Comment by emilgoldsmith** [comment]
I'm taking this on :). I'm one of the main maintainers of `stylelint-processor-styled-components` and it would greatly improve the UX of our processor since if users make a css syntax error at this moment, source maps aren't applied so they can't see where the error occured.

I should have a PR ready within the next few days :)

**Comment by ntwb** [comment]
It looks like there is a WIP branch of this here: https://github.com/stylelint/stylelint/compare/issue-3050

**Comment by emilgoldsmith** [comment]
Yep see #3063 for more information about the branch. I'll finish this up in the near future as I was just enjoying Christmas/New Year holiday, but getting ready to get back to being productive now :)

**Comment by ntwb** [comment]
No rush @emilgoldsmith 😄 I just wanted to add reference the branch against this issue as there wasn't a reference previously, just helps with maintaining branches 🎉
