### ISSUE TITLE
Smacss for stylelint

### ISSUE THREAD

**Issue by dzhytomyrsky** [stylelint/stylelint#3055]
Can you add smacss properties sort order to 
"rule-properties-order"?

It will be really useful!

**Comment by hudochenkov** [comment]
There is no “rule-properties-order” rule in stylelint. Therefore there is a plugin [stylelint-order](https://github.com/hudochenkov/stylelint-order), which has rule `properties-order` for checking properties order. But this plugin doesn't have predefined orders, i. e. SMACSS. However there is a shareable config [stylelint-config-property-sort-order-smacss](https://www.npmjs.com/package/stylelint-config-property-sort-order-smacss), which has configuration for `stylelint-order` with SMACSS properties order.
