### ISSUE TITLE
(npm) Consider extending dependencies to fulfill `postcss-html` needs.

### ISSUE THREAD

**Issue by falsyvalues** [stylelint/stylelint#3058]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Stylelint `package.json` contains direct dependency to `postcss-html` which requires `postcss-sass` as a peer dependency. `npm i stylelint` will warn as below, which is kinda wired since we don't directly deepend on `postcss-html`.
To sum up please consider adding `postcss-sass` as a dependency.

> What stylelint configuration is needed to reproduce this issue?

`"stylelint": "^8.3.1",`
`"stylelint-config-standard": "^18.0.0",`

> Which version of stylelint are you using?

`8.3.1`

> What did you expect to happen?

No npm warnings to be shown during install.

> What actually happened (e.g. what warnings or errors you are getting)?

npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none is installed. You must install peer dependencies yourself.

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

It's already fixed in https://github.com/stylelint/stylelint/issues/3035, but not released yet.

**Comment by falsyvalues** [comment]
@hudochenkov Somehow I missed this, thanks!
