### ISSUE TITLE
It doesn't work with postcss plugin

### ISSUE THREAD

**Issue by taven-liu** [stylelint/stylelint#3065]
there is no error when i used stylelint cli, but it doesn't work normally in postcss plugin.
```
require('style-lint')()
```
and i also try to add `configFile` 
```
require('style-lint')({
  configFile: './.stylelintrc'
})
```
but it also have errors

my `.stylelintrc`
```
{
  "extends": "stylelint-config-standard"
}
```

**Comment by evilebottnawi** [comment]
`require('style-lint')` => `require('stylelint')`

**Comment by jeddy3** [comment]
Closing. @taven-liu Feel free to reopen if the above suggestion doesn't resolve the issue for you.

**Comment by taven-liu** [comment]
it's a clerical error, i use `require('stylelint')` in my project

**Comment by taven-liu** [comment]
it's a clerical error, and i use `require('stylelint')` in my project, lots of warnings about stylelint rules
