### ISSUE TITLE
Add autofix to case-*

### ISSUE THREAD

**Issue by luoxlgh** [stylelint/stylelint#3068]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

feature request

> Which rule, if any, is this issue related to?

selector-attribute-quotes
declaration-block-no-redundant-longhand-properties
shorthand-property-no-redundant-values
font-family-no-duplicate-names
value-no-vendor-prefix
number-no-trailing-zeros
number-leading-zero
function-calc-no-unspaced-operator
block-opening-brace-space-before
selector-attribute-brackets-space-inside
selector-attribute-operator-space-after
selector-attribute-operator-space-before
selector-pseudo-class-parentheses-space-inside
selector-combinator-space-after
property-case
unit-case
value-keyword-case
selector-pseudo-element-case
selector-pseudo-class-case
selector-type-case
no-extra-semicolons
declaration-block-single-line-max-declarations
selector-pseudo-element-colon-notation

> Which version of stylelint are you using?

e.g. `8.2.0`

> What did you expect to happen?

Rules mentioned above seems easy to support auto fix but they dont, and it makes using stylelint in big project hard.

**Comment by evilebottnawi** [comment]
@luoxlgh PR welcome, we don't have many time for implement fix in many rules :disappointed:

**Comment by jeddy3** [comment]
> Rules mentioned above seems easy to support auto fix but they dont, and it makes using stylelint in big project hard.

@luoxlgh Firstly, thanks for [the PR](https://github.com/stylelint/stylelint/pull/3080) contributing autofix to the `case-*` rules.

As @evilebottnawi mentioned, it's simply a matter of a lack of time to why these haven't already been added.

Let's just make this issue about the `case-*` rules. We can create a separate issue (or issues) for the other rules. From what I can tell, the following rules aren't covered by this issue or https://github.com/stylelint/stylelint/issues/2829 and https://github.com/stylelint/stylelint/pull/2565:

- selector-attribute-quotes
- declaration-block-no-redundant-longhand-properties
- font-family-no-duplicate-names
- function-calc-no-unspaced-operator
- selector-attribute-brackets-space-inside
- selector-attribute-operator-space-after
- selector-attribute-operator-space-before
- selector-pseudo-class-parentheses-space-inside
- no-extra-semicolons
- declaration-block-single-line-max-declarations
- selector-pseudo-element-colon-notation

**Comment by jeddy3** [comment]
Closing as per https://github.com/stylelint/stylelint/issues/3511#issuecomment-413500637. Let's create separate issues for each rule going forward.
