### ISSUE TITLE
Fix --fix exiting with code 2 when all errors were fixed

### ISSUE THREAD

**Issue by l5x** [stylelint/stylelint#3077]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

`cat file.scss | stylelint --fix` always exits with error code 2

> Which rule, if any, is this issue related to?

e.g. `number-leading-zero`

> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  color: pink;
}
```

> What stylelint configuration is needed to reproduce this issue?

`stylelint-config-standard`

> Which version of stylelint are you using?

`8.4.0`

> What did you expect to happen?

exit with 0

> What actually happened (e.g. what warnings or errors you are getting)?

exit with 2

**Comment by jeddy3** [comment]
@epiloque Thanks for the report and for using the template.

Yes, it sounds sensible to only return with a non-zero code when there are unfixable errors.

Please consider contributing a fix for this as the core team is a bit stretched at the moment.

**Comment by farhadniaz** [comment]
I have the same issue. 
"stylelint": "^8.4.0",
"stylelint-config-standard": "^18.0.0",
"stylelint-order": "^0.8.0"
yarn stylelint  "Layout.css " --fix
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ybiquitous** [comment]
Is this problem still occurring?

I try the following test script on terminal, but I can't see this problem. 🤔 

```sh
# Setup
mkdir stylelint-3077
cd stylelint-3077
npm init -y
npm i stylelint stylelint-config-standard
echo '{"extends":"stylelint-config-standard"}' > .styelintrc.json
echo '.foo{color:pink}' > foo.css

# Test
./node_modules/.bin/stylelint --fix foo.css
echo $? #=> 0
cat foo.css #=> ".foo { color: pink; }"
```

**Comment by jeddy3** [comment]
@ybiquitous  Thanks for looking into this! Let's close this issue if you can reproduce it.

**Comment by Avivhdr** [comment]
I also have this problem.
It doesn't occur when I use `npm` instead of `yarn`.
