### ISSUE TITLE
It doesn't work with postcss plugin

### ISSUE THREAD

**Issue by taven-liu** [stylelint/stylelint#3078]
there is no error when i used stylelint cli, but it doesn't work normally in postcss plugin.
```
require('stylelint')()
```
and i also try to add configFile
```
require('stylelint')({
  configFile: './.stylelintrc'
})
```
but it also have errors

my` .stylelintrc`
```
{
  "extends": "stylelint-config-standard"
}
```

**Comment by CAYdenberg** [comment]
Please use issue template.

**Comment by taven-liu** [comment]
it work normally when i use the `stylelint` in front of other plugins 
```
require('stylelint')(),
require('postcss-import')()
...
```

**Comment by ntwb** [comment]
@taven-liu Thanks for creating this issue but we closed it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
