### ISSUE TITLE
Linting happens after PostCSS autoprefixing

### ISSUE THREAD

**Issue by nobleach** [stylelint/stylelint#3083]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I can't call this a "bug", as I'm probably doing something wrong. I'd like to run Stylelint on my untransformed `*.less` files. I can do this from the command line just fine using stylelint-cli. When attempting to do this via PostCSS's webpack loader, all transformed CSS is also linted. This leads to a ton of issues with un-alphabetized properties.

> Which rule, if any, is this issue related to?

This is unrelated to any rule specifically

> What CSS is needed to reproduce this issue?

As a webpack build is necessary to reproduce this issue, I can provide the relevant loader config:
```javascript
                    {
                        loader: 'postcss-loader',
                        options: {
                            sourceMap: true,
                            plugins: function(webpack) {
                                return [
                                    require("stylelint")(),
                                    require("postcss-import")(
                                        { addDependencyTo: webpack }
                                    ),
                                    require("postcss-url")(),
                                    require("postcss-cssnext")(),
                                    // add our "plugins" here
                                    // and if we want to compress,
                                    // just use css-loader option that already use cssnano under the hood
                                    require("postcss-browser-reporter")(),
                                    require("postcss-reporter")()
                                ]
                            }
                        }
                    },
```

> What stylelint configuration is needed to reproduce this issue?

I'm currently just using an order plugin:
```json
{
    "plugins": [
        "stylelint-order"
    ],
    "rules": {
        "order/order": [
            "custom-properties",
            "declarations"
        ],
        "order/properties-alphabetical-order": true
    }
}

```

> Which version of stylelint are you using?

8.2.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin as noted above. I have also tried adding another loader directive with just PostCSS and stylelint.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

I don't think so, but it's entirely possible. I am using Less.

> What did you expect to happen?

I expected the output to match the output from the command line - only reporting actual errors that occur in my source file format, not the transformed output.

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Have you tried to use [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin)? It might fix all the problem.

**Comment by nobleach** [comment]
I did. I didn't see any output at all. I'm willing to try it again though if you think it will be a better option.

**Comment by jeddy3** [comment]
> I'm willing to try it again though if you think it will be a better option.

Yes, [it's recommended](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-lint-using-my-task-runner-of-choice) to use a dedicated stylelint task-runner plugin rather than use stylelint as a PostCSS plugin.

@nobleach I'm going to close this issue for now, but feel to reopen it if `stylelint-webpack-plugin` (and/or just using stylelint via the CLI) doesn't work out for you.

---

Incidentally, if you wish to peruse using stylelint as a PostCSS plugin via webpack then it might be worth double checking your loader config e.g. the order of your loaders (is the less-loader coming before or after the postcss-loader?) and are [you correctly setting](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#example-a) the PostCSS syntax options.

**Comment by nobleach** [comment]
Thank you for the information. I have implemented a standalone task for this. I did try all the options, but in the end, the CLI was the only option that completely worked. I am noticing that using node to run the CLI isn't exiting properly, but that is another issue altogether.
