### ISSUE TITLE
Related: airbnb shareable config for stylelint

### ISSUE THREAD

**Issue by tony** [stylelint/stylelint#3091]
Sorry for posting an issue not related to development of stylelint itself.

There is a pull request open for creating a shareable config for the popular airbnb css specification: https://github.com/airbnb/css, and I wanted to draw attention to it since shareable configs are a big piece of stylelint.

The PR is at https://github.com/airbnb/css/pull/56.

It would be great to have some testers and feedback on it.

In the same spirit of [ESLint having an airbnb config](https://www.npmjs.com/package/eslint-config-airbnb), I think the stylelint having an airbnb config (whether or not it's official) is something that'll be welcomed by stylelint users.

There is a potential snag though: Apparently airbnb doesn't use stylelint (https://github.com/airbnb/css/issues/45). So if this PR doesn't work out, there's still a chance to fork the shareable config into a separate repo. Which means it'd need maintainers to step forward.

**Comment by ntwb** [comment]
Thanks @tony, I was the one who created that original PR, everything is fine in regard to the current status of Airbnb PR and can be discussed in the issues and PRs there (I'm subscribed to them all)

I'm closing this issue here as it is not required.
