### ISSUE TITLE
Add ignore: ["first-nested"] to declaration-empty-line-before

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3101]
This option would be useful for when using prettier and stylelint side-by-side (see: https://github.com/prettier/prettier/issues/2621)

**Comment by hudochenkov** [comment]
I don't see how it's related to Prettier issue? That issue is empty lines between rules.

**Comment by jeddy3** [comment]
The same is true for empty lines between declarations. However, prettier will remove any empty lines before the first nested node. This option will allow a user to configure stylelint to ignore first nested declarations and, instead, let handle prettier handle those.

**Comment by ntwb** [comment]
I really should take Prettier and stylelint for a spin, I've yet to try it with CSS or SCSS...
