### ISSUE TITLE
Use lebab to add modern syntax sugar to code

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3112]
Since stylelint [will only support node@6+](https://github.com/stylelint/stylelint/pull/3075) going forward, there are a few syntax sugar features of ES6 that we can now use.

node@4 supported a lot of ES6 features and we already make use of them in the code e.g.:

- `const` and `let`
- arrow functions
- object shorthand
- `Map` and `Set`
- template literals
- etc.

There are a few transforms within [lebab](https://github.com/lebab/lebab), that I can see off-hand, that we could make use of:

- "arg-rest"
- "arg-spread"
- "default-param"
- "destruct-param"

We could also run the transforms of features we already use to ensure we use them consistently when they can be used:

- "arrow"
- "for-each"
- "obj-shorthand"
- "let"
- "template"

I figured it was best to keep this issue focused just on syntax sugar. If anyone has thoughts on how other ES6 features can be used to refactor, in minor or major ways, other parts of the system then please create new issues.  The goals being:

- Improve ease of maintenance via understandability of code
- Improve performance (as I believe quite a few ES6 features are optimised for)

**Comment by hudochenkov** [comment]
Great idea!

We could also remove `"use strict";` as it, I believe, was used only to be able to use `const` and `let` in Node.js 4.

**Comment by Arcanemagus** [comment]
@hudochenkov [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) does quite a bit more than just that, those are just nice side effects that are enabled due to the constraints of strict mode 😉.

Until the code is refactored as ES6 modules which enforces that mode for you automatically (which Node.js doesn't yet support), `'use strict'` should still be in the files.

**Comment by jeddy3** [comment]
Sounds like there aren't any objections to this, so going to label up.

**Comment by ntwb** [comment]
FYI: I was just checking out the `arrow` Labeb _transform_, it appears to have conflicts with Flow/Prettier:

• `lebab --replace lib/utils/report.js  --transform arrow`
```diff
diff --git lib/utils/report.js lib/utils/report.js
index 04ca8d4c..ee6518b3 100644
--- lib/utils/report.js
+++ lib/utils/report.js
@@ -15,17 +15,15 @@ const _ = require("lodash");
  *
  * You *must* pass *either* a node or a line number.
  */
-module.exports = function(
-  violation /*: {
-  ruleName: string,
-  result: Object,
-  message: string,
-  node: Object,
-  index?: number,
-  word?: string,
-  line?: number
-}*/
-) {
+module.exports = violation /*: {
+ruleName: string,
+result: Object,
+message: string,
+node: Object,
+index?: number,
+word?: string,
+line?: number
+}*/ => {
   const ruleName = violation.ruleName;
   const result = violation.result;
   const message = violation.message;
```

When committing: 
```shell
git commit -m "test"
husky > npm run -s precommit (node v9.3.0)

 ❯ Running tasks for *.js
   ✖ prettier --write
     → [error]   29 |   const message = violation.message;
     git add
✖ prettier --write found some errors. Please fix them and try committing again.


[error] lib/utils/report.js: SyntaxError: Unexpected token (26:5)
[error]   24 | word?: string,
[error]   25 | line?: number
[error] > 26 | }*/ => {
[error]      |     ^
[error]   27 |   const ruleName = violation.ruleName;
[error]   28 |   const result = violation.result;
[error]   29 |   const message = violation.message;

husky > pre-commit hook failed (add --no-verify to bypass)
```

Will dig around and read some more over the weekend, thought I'd mention it as a heads up for anyone exploring Lebab 😄

**Comment by CAYdenberg** [comment]
Just to push back a little bit, I found it really tough while trying to debug the .stylelintignore problems (so far unsuccessfully) that the Prettier transform modified basically every file and most lines of code in stylelint. It really messes with understanding the diff and history. It's nice to have everything written in a consistent style, but it's also OK to just update to ES6 features when refactoring a file or piece of code. Just my $0.02.

**Comment by ntwb** [comment]
I hear you loud and clear @CAYdenberg 👍 

This might be of help but in a Prettier world it might not, Prettier doesn't make a separate commit for its changes, they're just merged with the primary commit 🤔 

https://github.com/blog/2304-navigate-file-history-faster-with-improved-blame-view

**Comment by hudochenkov** [comment]
Closing this as we're doing this with ESLint instead.
