### ISSUE TITLE
Add linebreaks

### ISSUE THREAD

**Issue by bcullman** [stylelint/stylelint#3114]
Request new rule, similar to https://eslint.org/docs/rules/linebreak-style, `CRLF` or `LF` (aka windows, or unix). I believe this would fall under `https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#general--sheet-2`

> Which version of stylelint are you using?

`^8.0.0`

> How are you running stylelint: 

"CLI with `stylelint './less/**/*.less'`"

> What did you expect to happen?

Would like to throw errors if a line ending style other than what is specified in the `.stylelintrc` is used.

**Comment by jeddy3** [comment]
@bcullman Thanks for the request.

I'm surprised this hasn't come up before. @stylelint/core Any objections to such a rule? 

`"linebreaks":  "unix"|"windows"`?

**Comment by ntwb** [comment]
No objections here, what I will say is that we should include similar notes to that of which ESlint include on setting this using VCS https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems.

**Comment by jeddy3** [comment]
As there no objections, I'll label this issue up accordingly.

@bcullman Feel free to [contribute](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#creating-a-new-rule) this rule.

- Name: `linebreaks`
- Primary option: `"unix"|"windows"`
- Secondary options: none
- Message: "Expected linebreak to be ${linebreak}"
- Section: "Stylistic -> General"

**Comment by saulotoledo** [comment]
Hi. If no one is working on this one, I will do do the job.

**Comment by bcullman** [comment]
hi @saulotoledo - nope have not had time to look into how to implement. feel free to take

**Comment by saulotoledo** [comment]
Thanks @bcullman! I will work on it then.

**Comment by saulotoledo** [comment]
Hi @jeddy3. I have a first version of the rule. It still needs some work and new test cases (as looking for newlines in the end of the file, for example). I plan to work on it this weekend (or before, if possible), but I would like you or the community to take a look if possible. May I open the MR as a WIP?

**Comment by saulotoledo** [comment]
Please take a look at https://github.com/stylelint/stylelint/pull/3289 when possible. It still needs some work. I will work on it as soon as possible, but please let me know if you have comments.
