### ISSUE TITLE
onlyOneChar works the other way around

### ISSUE THREAD

**Issue by MartijnCuppens** [stylelint/stylelint#3118]
In `lib/utils/whiteSpaceChecker.js`:
```
   * @param {boolean} [args.onlyOneChar=false] - Only check *one* character before.
   *   By default, "always-*" checks will look for the `targetWhitespace` one
   *   before and then ensure there is no whitespace two before. This option
   *   bypasses that second check.
```
Shouldn't this be `true` by default?

**Comment by Arcanemagus** [comment]
@MartijnCuppens Can you please refile this using the template and explain your reasoning behind why you think it should be `true` by default?

Note when refiling it that [embedded code snippets](https://github.com/blog/2415-introducing-embedded-code-snippets) make it _far_ more readable 😉.
