### ISSUE TITLE
Add --print-config flag

### ISSUE THREAD

**Issue by mcdado** [stylelint/stylelint#3127]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A nice feature of eslint's CLI is the option `--print-config` that will [log to the console the parsed configuration object](https://github.com/eslint/eslint/blob/b8aa0718c88774f7ef59b5b1ca22e1478a09b1e6/lib/cli.js#L167) for a given configuration file, including all the extended rules. It's awesome for debugging configuration files.

> Which rule, if any, is this issue related to?

n/a

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

n/a

> Which version of stylelint are you using?

e.g. `8.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --config .stylelintrc.js *.scss`"

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Not necessarily

> What did you expect to happen?

To have the configuration printed in the console

> What actually happened (e.g. what warnings or errors you are getting)?

The option is not there

**Comment by jeddy3** [comment]
@mcdado Thanks for the request and for using the template.

> It's awesome for debugging configuration files.

Sounds like a solid use case to me. @stylelint/core Any objections to `--print-config` flag?

**Comment by Arcanemagus** [comment]
None here, sounds like it's just exposing the same functionality as `getConfigForFile`.

**Comment by jeddy3** [comment]
> None here, 

Labelling up accordingly. @mcdado Feel free to contribute this feature.

**Comment by mcdado** [comment]
I was motivated to do so and tried to do it as I created the issue, but I couldn't get it to work… I'm not really sure how to implement it, since I couldn't get a configuration object from the file

**Comment by thibaudcolas** [comment]
Having this functionality would make my life much easier while creating configurations, so I've given it a shot over at #3532. Feedback welcome!
