### ISSUE TITLE
Move Jest and Lodash flow-typed definitions to ./flow-typed/npm/

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#3143]
Via @matteocng in https://github.com/stylelint/stylelint/issues/2322#issuecomment-282648773
> I noticed that `decls` contains declarations for `jest` and `lodash` coming from `flow-typed`. Maybe those two should/could be moved to another folder i.e `'./flow-typed/npm/'` (the default folder when you run `flow-typed install`), included and used internally but not shipped?

This would allow the hack `flow-defs` npm script in #3142 to become less hacky 😏 

I think it would also help devs consuming stylelint and using Flow.

That all said and done though, this will need some testing so if you're familiar with Flow and could help guide me and the stylelint team in the best way forward that would be great.

**Comment by jeddy3** [comment]
SGTM

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/3164
