### ISSUE TITLE
Using --fix on embedded SCSS, such as a vue component removes all but the SCSS

### ISSUE THREAD

**Issue by lee-chase** [stylelint/stylelint#3148]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug which occurs when using --fix option on a file with embedded scss.

> Which rule, if any, is this issue related to?

No particular rule affects --fix

> What CSS is needed to reproduce this issue?
A vue component file e.g.

```  component.vue
<template>
  <div class="div">
    I get deleted
  </div>
</template>

<script>
  let a = 'I get deleted';
  console.log(a);
</script>

<style lang="scss">
.div {
  border: 0;
}
</style>
```

The command: stylelint -s scss --fix component.vue

> What stylelint configuration is needed to reproduce this issue?

default / any

> Which version of stylelint are you using?

Version 8.4.

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Command line and Webpack

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

The SCSS to be fixed where possible with the rest of the file left intact.

> What actually happened (e.g. what warnings or errors you are getting)?

The file is reduced to just SCSS

```

.div {
  border: 0;
}
```

**Comment by CAYdenberg** [comment]
@gucong3000 Anything simple come to mind as to why this would be the case?

**Comment by gucong3000** [comment]
@lee-chase,
Sorry for the late reply.
Please remove `stylelint-processor-html` from stylelint config. It is incompatible with `--fix`.

**Comment by lee-chase** [comment]
@gucong3000 are there any processors out there compatible with --fix? stylelint-processor-arbitrary-tags produces the same result.

**Comment by gucong3000** [comment]
@lee-chase The latest version of the `stylelint` has built-in support vue format. do not need any processors.

**Comment by lee-chase** [comment]
@gucong3000 thankyou. 

NOTE: For anyone reading this you may also need to remove '-syntax scss'

See https://github.com/stylelint/stylelint/pull/2975
