### ISSUE TITLE
0.4.0 exposure of ruleTester = big mistake

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#315]
I forgot that we shouldn't even *expose* the ruleTester without making tape/postcss dependencies, or npm installs will screw up. I will backout of this and make a separate module, maybe.

**Comment by jeddy3** [comment]
Eeek. 

> I will backout of this and make a separate module, maybe.

You mean similar to how eslint does it with their [eslint-tester](https://github.com/eslint/eslint-tester)?
