### ISSUE TITLE
Add block-opening-brace-empty-line-before

### ISSUE THREAD

**Issue by kellyselden** [stylelint/stylelint#3154]
This seems like the natural analog to [block-closing-brace-empty-line-before](https://stylelint.io/user-guide/rules/block-closing-brace-empty-line-before/), but seems missing.

**Comment by jeddy3** [comment]
Thanks for the request. Yes, I can see the use-case if a users were to use it in conjunction with `"block-opening-brace-newline-before": "always"` e.g.

```json
{
  "block-opening-brace-empty-line-before": 0,
  "block-opening-brace-newline-before": "always",
}
```

Would produce one violation for:

```css
a

{
  property: value;
}
```

And zero violations for:

```css
a
{
  value: property
}
```

@kellyselden Please consider [contributing a this rule](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) if you need it.

**Comment by jeddy3** [comment]
Closing [as stylistic rules are frozen](https://github.com/stylelint/stylelint/issues/5674). The community is welcome to create the rule [as a plugin](https://stylelint.io/developer-guide/plugins).
