### ISSUE TITLE
Add never to declaration-block-semicolon-newline-before

### ISSUE THREAD

**Issue by kellyselden** [stylelint/stylelint#3155]
https://stylelint.io/user-guide/rules/declaration-block-semicolon-newline-before/

It seems like "never-multi-line" will essentially get me what I want, but I have other rules which enforce multiline only. Seems like "never" as an option would make more sense in this case.

**Comment by jeddy3** [comment]
@kellyselden Can you expand on your use case with examples, please? Some examples of your code style would be very helpful in determining whether your conventions can be enforced with the existing primary options or not.

**Comment by jeddy3** [comment]
Closing for now. Feel free to reopen with clarification.
