### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#3175]
I just discovered https://github.com/stylelint/stylelint/community

We've 5 out of 6 in the list checked off:
✅- Description
✅- README
❌- Code of conduct - What is a code of conduct?
✅- Contributing
✅- License
✅- Issue template and pull request template

There are two automated options to implement a Code of Conduct
• Contributor Covenant
or
• Citizen Code of Conduct

**Comment by evilebottnawi** [comment]
We use https://github.com/sindresorhus/conduct
