### ISSUE TITLE
`npm install` spam

### ISSUE THREAD

**Issue by shannonmoeller** [stylelint/stylelint#3182]
Please stop. I love your project. I don't love spam.

![image](https://user-images.githubusercontent.com/155164/36446316-2af03878-163e-11e8-9494-dacfb4a6a6f1.png)

**Comment by m-allanson** [comment]
Hi @shannonmoeller 👋 This will be removed in the next release of stylelint, due in the next day or two. See https://github.com/stylelint/stylelint/pull/3180 and https://github.com/stylelint/stylelint/issues/3181.

**Comment by shannonmoeller** [comment]
Thank you!! ❤️❤️❤️

**Comment by m-allanson** [comment]
No problem!
