### ISSUE TITLE
No `context` 3rd parameter provided to plugin for autofixing

### ISSUE THREAD

**Issue by rhumaric** [stylelint/stylelint#3192]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

More of  a bit of guidance, but maybe an underlying issue. I'm trying to create a Stylelint plugin to integrate Prettier and can't figure how to test the autofixing nor enable it in the rule. I've added a 3rd parameter to the plugin function and have both the `fix: true` and `fixed: <expected fixed CSS>` properties in the tests. I don't see what I'm doing differently than other plugins with autofixing (went to have a look in stylelint-order for example), so would appreciate a bit of help there.

> Which rule, if any, is this issue related to?

Not really a rule, more autofixing and creating a plugin that supports it.

> What CSS is needed to reproduce this issue?

No specific CSS but the code for the plugin is [public](https://github.com/rhumaric/stylelint-plugin-prettier).

> What stylelint configuration is needed to reproduce this issue?

No specific configuation.

> Which version of stylelint are you using?

9.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

For now, just tests, created with stylelint/stylelint-test-rule-tape (0.2.0)

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Nope

> What did you expect to happen?

Errors for properties not being fixed properly (atm) and access to the 3rd `context` argument for the plugin function. Plugin is in `index.js` and tests in `test/index.js`.

> What actually happened (e.g. what warnings or errors you are getting)?

No 3rd argument when the plugin is called, and tests failing when `fixed` is present but no fixing happens.

**Comment by jeddy3** [comment]
@rhumaric Thanks for starting this plugin. 

I'm not sure I'll be able to supply much help, other than reassure you that looking at `stylelint-order` is a good approach as it is written by one of stylelint's core contributors. My only suggestion is to adopt Jest as your test running, like [`stylelint-order` has done](https://github.com/hudochenkov/stylelint-order/blob/master/jest-setup.js). I believe the tape runner was written before stylelint could autofix.

[Work is being done](https://github.com/stylelint/stylelint/issues/3206#issuecomment-371769453) to make it easier for plugin authors to use Jest, but at the moment it's just the case of copying and pasting.

I'm going to close the issue for now as I'm conducting a triage clean-up, but feel free to continue commenting if adopting the jest approach doesn't work out for you.

**Comment by rhumaric** [comment]
Thanks. I went ahead and used the `jest-setup.js` from that repo (forgot to come back here to mention that when I did, sorry) and it worked much better. 

Looking forward to having some testing utilities to help validate plugins. For now, I can get back to fixing my failing tests ;) 

Might be a minor need regarding testing, but I found that as prettier works on whole files, it was easier to read accept/reject/fixed values from actual files than set them up with CSS. Would be great to have some utilities regarding that too. Maybe a `testFolder()` function that would accept the path to a folder laid out as so:

```
config.json // The configuration for the plugin that's being tested
accept // Accept cases
  |-- a.css
  |-- b.css
reject // Reject cases
  |-- c.css
  |-- d.css
fixed // Fixes for rejected files that can be fixed
  |-- d.css
```

I was also imagining the reject files could have a front-matter to define expected line, message...But it might well all be overkill.

**Comment by jeddy3** [comment]
>  Would be great to have some utilities regarding that too. Maybe a testFolder() function that would accept the path to a folder laid out as so:

Sounds great. It'd be fab if you could experiment with building something like this, within your plugin repo, to satisfying your own user needs. It can then be rolled into `stylelint-scripts` if it looks like it'll be useful to other plugin authors.

**Comment by rhumaric** [comment]
Sounds a good plan! I'm trying things out for it at the moment on the `stylelint-plugin-prettier` plugin, but running into issues of tests needing to be created synchronously and the node fs API not being super fast when using the sync functions (which sounds like a bad plan anyways). I'll see if I can find a better way.
