### ISSUE TITLE
Fix file path not being considered when CSS has a syntax error

### ISSUE THREAD

**Issue by shinnn** [stylelint/stylelint#3204]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug related to the path resolution of stylelint configuration files.

> Which rule, if any, is this issue related to?

No rules are related.

> What CSS is needed to reproduce this issue?

Any CSS resulting in `CssSyntaxError`, for example `}}}}}broken css`.

> Which version of stylelint are you using?

`9.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

### Project structure

```
/Users/shinnn/sample/
└─┬ stylelint
  ├── run.js 
  ├── package.json 
  ├── node_modules/
  └─┬ fixtures/
    ├── fixture.css
    └── stylelint.config.js
```

#### package.json

```json
{
  "name": "sample",
  "private": true,
  "devDependencies": {
    "stylelint": "9.1.1"
  }
}
```

#### run.js

```javascript
'use strict';

const {lint} = require('stylelint');

(async () => {
  // process.cwd() === '/Users/shinnn/sample'

  try {
    const {results} = await lint({
      files: '/Users/shinnn/sample/fixtures/style.css'
    });

    console.log(results[0].warnings);
  } catch (err) {
    console.error(err.stack);
  }
})();
```

#### fixtures/fixture.css

```css
}
```

#### fixtures/stylelint.config.js

```js
module.exports = {
  rules: {
    'length-zero-no-unit': true
  }
};
```

### Node.js version

```console
$ node --version
> v9.7.1
```

### How to run

Run

```console
node ./run.js
```

in the `/Users/shinnn/sample/` directory.

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

As `fixtures/fixture.css` is not a valid CSS (`}`), I expect `stylelint.lint()` resolves a result object containing `CssSyntaxError`:

```js
console.error(results[0].warnings);
/* => [ { line: 1,
    column: 1,
    rule: 'CssSyntaxError',
    severity: 'error',
    text: 'Unexpected } (CssSyntaxError)' } ] */
```  

> What actually happened (e.g. what warnings or errors you are getting)?

`stylelint.lint()` doesn't resolve, but rejects with the following error:

```
Error: No configuration provided for /Users/shinnn/sample
    at module.exports (/Users/shinnn/sample/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at stylelint._fullExplorer.load.then.then.config (/Users/shinnn/sample/node_modules/stylelint/lib/getConfigForFile.js:46:15)
    at <anonymous>
```

I first thought stylelint doesn't take the target path into consideration while resolving configuration files. However, when I update `fixtures/fixture.css` to a valid CSS, for exmaple `a { font: 0px }`,

```js
const {results} = await lint({
  files: '/Users/shinnn/sample/fixtures/style.css' // a { font: 0px }
});

console.error(results[0].warnings);
/*=> [ { line: 1,
    column: 12,
    rule: 'length-zero-no-unit',
    severity: 'error',
    text: 'Unexpected unit (length-zero-no-unit)' } ] */
```

As you can see, `stylelint.lint()` enables `length-zero-no-unit` rule by loading `fixtures/stylelint.config.js` and resolves a correct result.

Here is my assumption: only when the CSS has a syntax error, stylelint omits to refer the path of CSS file.

**Comment by shinnn** [comment]
What is interesting is, when I add a debug message `console.log('Config loaded.')` to the top of `fixtures/stylelint.config.js` and run `node ./run.js`, it prints

```
Config loaded.
Error: No configuration provided for /Users/shinnn/sample
    at module.exports (/Users/shinnn/sample/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at stylelint._fullExplorer.load.then.then.config (/Users/shinnn/sample/node_modules/stylelint/lib/getConfigForFile.js:46:15)
    at <anonymous>
```

Yes, `Config loaded.` is printed *before* the error.

So, contrary to `No configuration provided` error message, stylelint successfully finds `fixtures/stylelint.config.js` even if the CSS is broken, but it doesn't seem to actually use it.

**Comment by jeddy3** [comment]
@shinnn Thanks for the very detailed report and for using the template.

I'm labelling this up directly as a bug as the report is thorough. @shinnn is also the author of the popular VSCode stylelint plugin, and thus very familiar with stylelint as a consumer.

@stylelint/core Does anyone have any ideas on how to resolve this or time to look into it?
