### ISSUE TITLE
Publish jest-setup as npm package

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3206]
Should we, and is it even possible to, publish [`jest-setup.js`](https://github.com/stylelint/stylelint/blob/master/jest-setup.js) as an npm package so that it can be used by plugin authors:

Refs:
- https://github.com/kristerkari/stylelint-z-index-value-constraint/blob/master/jest-setup.js
- https://github.com/stylelint/stylelint/pull/3201

**Comment by ntwb** [comment]
Yes, we should, I'd planned on adding to https://github.com/stylelint/stylelint-scripts, though originally I hadn't thought of publishing it as a stand-alone package, I'd planned on including it as "configuration" option of the scripts.

The inspiration of this new stylelint repo comes from these two packages:
• https://github.com/facebook/create-react-app/tree/master/packages/react-scripts
• https://github.com/kentcdodds/kcd-scripts

Which in turn has led us at WordPress to publish this package:
• https://github.com/WordPress/packages/tree/master/packages/scripts/

Each of the above packages expose various levels of Jest integration, some just a shared config, others more of a _setup_ like our own `jest-setup.js`

Over the weekend I'll push up my progress to stylelint/stylelint-scripts 🎉

**Comment by jeddy3** [comment]
Awesome. I'm looking forward to seeing this!

**Comment by kristerkari** [comment]
Having jest-setup.js as an npm package would be great! Any of the stylelint utils that can be useful for plugins would be nice to have as a separate npm package.

**Comment by jeddy3** [comment]
I think we can close this as there's a [now a repo](https://github.com/stylelint/stylelint-scripts) for tracking the scripts progress.
