### ISSUE TITLE
using --fix in a plugin with respect to indentation

### ISSUE THREAD

**Issue by OriR** [stylelint/stylelint#3210]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Question/Feature.

I'm not sure if this was already discussed or not but, in a plugin I'd like to support the `--fix` flag with respect to the `indentation` rule value.
Is there a way to get a hold of this value in a plugin?

> Which rule, if any, is this issue related to?

`indentation`, `scss/dollar-variable-colon-newline-after` (I know the latter is not part of the core rules, I'm only using it to demonstrate my use case)

> What CSS is needed to reproduce this issue?

```scss
$var: 10px;
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "indentation": [2, {
      "except": ["value"]
    }],
    "scss/dollar-variable-colon-newline-after" : "always"
  }
}
```

> Which version of stylelint are you using?

`9.1.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI (using node scripts and `.stylelintrc`) with `stylelint path/to/scss/files/**/*.scss`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Technically yes, it's related to SCSS, but this could apply to any plugin/internal rule.

> What did you expect to happen?

Have the option to use the `indentation` value 

> What actually happened (e.g. what warnings or errors you are getting)?

The output of the above style snippet, ideally would be
```scss
$var:
  10px;
```
but I can only do
```scss
$var:
10px;
```
because I can't assume any value of the indentation when fixing my own rule.

**Comment by jeddy3** [comment]
td;dr Your best way forward, for now, is to assume that any indentation violations will be fixed outside your plugin. 

> Is there a way to get a hold of this value in a plugin?

Every rule is standalone and independent of other rules. So, a rule should just fix problems to make itself valid, and not worry about introducing violations for other rules e.g.

`"dollar-variable-colon-newline-after": "always"` should just add a newline after the colon of the dollar variable. The `indentation` rule then handles any indentation violations that might be introduced. I believe this is how [stylelint-order](https://github.com/hudochenkov/stylelint-order) works.

Having said that, this is all still up in the air. The "standalone and independent" approach was chosen when stylelint was just a linter, rather than a linter _and a fixer_. This change in purpose has introduced [issues that aren't resolved yet](https://github.com/stylelint/stylelint/issues/2532#issuecomment-302109499) e.g. does stylelint need to do multiple fixing runs or do dependencies between rules need to be explicitly defined.

**Comment by OriR** [comment]
Thanks for the detailed response!
I started reading the discussion and quickly realized that it contains several months of comments 😅 

One question that came me to after skimming through it though, does this affect the plugin ecosystem in anyway?
I saw that there's an intention to create `stylelint-plugin-prettier`, so my "fear" is that we'll need some kind of [recommended configuration](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration), otherwise a plugin might flag something as an error even though it's fixed in prettier.

**Comment by jeddy3** [comment]
> One question that came me to after skimming through it though, does this affect the plugin ecosystem in anyway?

Only that, at the moment, users need to place any plugins at the top of the rules list within their configuration object, so that built-in rules like `indentation` rule run last.

> otherwise a plugin might flag something as an error even though it's fixed in prettier.

I don't quite understand this bit. Can you elaborate a little, please?

**Comment by jeddy3** [comment]
Closing this as I think the original question is answered, but feel free to continue the conversation.

**Comment by OriR** [comment]
Sorry for the delay

> > otherwise a plugin might flag something as an error even though it's fixed in prettier.

> I don't quite understand this bit. Can you elaborate a little, please?

What I meant is that if a you have a formatting rule defined in a plugin, let's say spacing related.
In a problematic code section, the plugin will flag it as an error but, it's something prettier will probably fix, so on the one hand a plugin will exit `stylelint` with an error exit code because of the bad formatting, but later prettier will fix that so it's a non-issue.
I _think_ that's the reason for the recommended configuration for `eslint-plugin-prettier`.

It might be solved if prettier will run prior to `stylelint` but that's just a guess.


> users need to place any plugins at the top of the rules list within their configuration object

What happens when you `extend` a configuration? what's the order the rules run in?

**Comment by jeddy3** [comment]
> so on the one hand a plugin will exit stylelint with an error exit code because of the bad formatting, but later prettier will fix that so it's a non-issue.

Thanks for the further explanation. I don't think much work has been done exploring how (the fixing part of) stylelint and prettier would work together. Perhaps reaching for [`prettier-stylelint`](https://github.com/hugomrdias/prettier-stylelint) would do it (so long as the indentation options match for the two tools)?

> What happens when you extend a configuration? what's the order the rules run in?

It's a good question, and I'm afraid I don't know off-hand. Do you want to dig into the code a little to find out? Any help with understanding and improving the linting engine would be appreciated.

**Comment by OriR** [comment]
From what I could gather it looks like this is how the rules are merged between a config and its extensions:
https://github.com/stylelint/stylelint/blob/f6fbad37e1ffa84aed4a996b3829b4275e7320c5/lib/augmentConfig.js#L229-L231
(Where `a` is the base config and `b` is the extending config)

And this is how they're being iterated over:
https://github.com/stylelint/stylelint/blob/f6fbad37e1ffa84aed4a996b3829b4275e7320c5/lib/lintSource.js#L127

This means that it's similar to this scenario:
```js
const x = {d: 1, h:2, m:3};
const y = {a: 3, k:4, t: 5};
const keys = Object.keys(Object.assign({}, x, y)); // ['d', 'h', 'm', 'a', 'k', 't']
```
This keeps the order which the objects were merged by - back to our case - it means that the order where rules are run in `extend` are: first the rules that come from the base config and only then the  rules coming from the extending config.

This also applies to nested `extend` directives as well as seen here:
https://github.com/stylelint/stylelint/blob/f6fbad37e1ffa84aed4a996b3829b4275e7320c5/lib/augmentConfig.js#L149-L180

So if a base config declares an `indentation` rule, this rule is going to be evaluated before any rule in the custom config a project is declaring and all the plugins it uses.

This means that in order to make sure a fixable rule you're inheriting is doing its job at the right time you have to declare it your config even if it's coming from an extended config, right?

**Comment by jeddy3** [comment]
> So if a base config declares an `indentation rule`, this rule is going to be evaluated before any rule in the custom config a project is declaring and all the plugins it uses.

Thanks for digging deeper into this.

> This means that in order to make sure a fixable rule you're inheriting is doing its job at the right time you have to declare it your config even if it's coming from an extended config, right?

That does appear to be the case. It's definitely not optimal. Any ideas what can be done about it? Could we, as a temporary workaround, patch the merging process so that `indentation` and the `*-empty-line-before` run last? That's a bit of a stop gap and it would be ideal to resolve this is a more robust way.

**Comment by OriR** [comment]
Here are some of the things I thought about - 
**General Solutions**
1. The best solution IMO for this case would be to have a topological sort of the fixable rules, that way we can get the rule dependency graph and run the lint in that order. But that's in a perfect world and probably hard to implement at this point, unless you know of something that I'm not familiar in `stylelint` that would help us achieve that.

2. Implement a multiple passes/dirty check of sorts solution, that way we can avoid trying to know the dependencies and just run everything until it's "clean", but here we're risking an infinite loop and an overall longer run time of the linter.

These would work regardless of rules order/plugins/config extensions.

**Specific Solutions**
1. As you suggested pluck the `indentation` so it'll always run last. This assumes that it depends on no other rule when it's fixing. It's not that bad except that it's an implementation detail that now plugin authors _can_ rely on but, it won't cause a major version bump if later decided to drop it.

2. Allow to access the indentation value in plugins, just like we can access the new line value of the system using the `context` parameter. It raises some questions though, what happens if the user doesn't set the `indentation` rule? how plugins would then fix themselves? what happens if there's gonna be a need for another type of value from another rule to be accessed like this?

So I think the best course of action would be to do some digging and see if the topological sort solution is feasible or not. if not then pluck `indentation` and run it last (assuming it has no other dependencies).

WDYT?

**Comment by jeddy3** [comment]
Thanks for giving this some thought.

> So I think the best course of action would be to do some digging and see if the topological sort solution is feasible or not. if not then pluck `indentation` and run it last (assuming it has no other dependencies).

SGTM. ESLint must have encountered this same problem. Do we know if they opted for a topological sort approach?

> unless you know of something that I'm not familiar in stylelint that would help us achieve that.

Nothing springs to mind I'm afraid.
