### ISSUE TITLE
Disable --fix while using a processor and display message

### ISSUE THREAD

**Issue by emilgoldsmith** [stylelint/stylelint#3223]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Minor feature request, I'm thinking this could be a `good first issue`. Just thought of this as I was tending to [this sad user of the Styled Components processor](https://github.com/styled-components/styled-components-website/pull/247), the simplest way I can think of avoiding future issues is to just disable `--fix` when a processor is present in the configuration as it is not currently supported (and since a processor being able to use `--fix` would require the processor to always output the same css input it got, the only type of processor I can think of that could use this is one that only changes the stylelint screen output / maybe doing some statistics), if you think that could be a problem an option could be to add (and of course inform the user what happened and the possibilities when `--fix` fails) a `--fix-processor` option or something of the like that overrides the disable.

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

N/A

> How are you running stylelint: CLI, PostCSS plugin, Node API?

N/A

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Using processors

> What did you expect to happen?

N/A

> What actually happened (e.g. what warnings or errors you are getting)?

N/A

**Comment by jeddy3** [comment]
@emilgoldsmith Thanks for the request and for using the template.

> Minor feature request, I'm thinking this could be a `good first issue`

It seems like a sensible idea. I'll label this up accordingly. 

Let's see if we can disable `--fix` when a processor is present _and_ display an (info level) message to that affect.

**Comment by mackelito** [comment]
Any updates on this one? would really love to get it running in vscode :)

**Comment by emilgoldsmith** [comment]
As I said it should be a pretty easy implement, so feel free to take it on

**Comment by Regaddi** [comment]
Just to make sure I understood correctly:

Fixing this issue requires a check for configuration options and command-line arguments.
If the `processor` configuration option is present (and not empty) and the `--fix` cmd flag is present, the `--fix` flag should be omitted (deactivate fixing) and an info text should be printed to the console.

Correct? @emilgoldsmith @jeddy3

**Comment by emilgoldsmith** [comment]
Sounds right to me @Regaddi !

**Comment by Regaddi** [comment]
So after having my first dive in to the codebase I am unsure where to put this check.
Technically I would check for existence of the `processor` array, its length and if the `fix` flag is true. In that case the information is printed to the console and the fix flag deactivated for the running stylelint instance.

This raises some questions, that I am currently not able to answer for myself, so I'd be more than happy, if someone could help me out here:

1. Where is the best place to do this check (filename & approximate line of code)?
2. How can I access the currently used configuration for that instance?
3. How can I unset the `fix` flag, if its set?

I stumbled across these lines, where a stylelint instance is created (maybe this already answers question 1).
https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L85-L95

**Comment by Regaddi** [comment]
Ideas or hints? @jeddy3 @emilgoldsmith

**Comment by emilgoldsmith** [comment]
I'm not very familiar with the codebase myself I'm afraid, I've only ever contributed a small feature. So I'm afraid I can't be of much help!

**Comment by jeddy3** [comment]
@Regaddi Thanks for looking into this. I'd suggest holding off doing any more digging until we know [a little more about the role of processors](https://github.com/stylelint/stylelint/issues/3264) going forward.

**Comment by BPScott** [comment]
It sounds like [processors are going to be deprecated eventually](https://github.com/stylelint/stylelint/issues/3408) but won't be removed until the syntax ecosystem matches the current processor system.

I'd imagine that'll take some time, so giving users information on potentially destructive option combinations still seems like a worthwhile thing to do, as processors won't be going away in the immediate future.

**Comment by jeddy3** [comment]
> I'd imagine that'll take some time, so giving users information on potentially destructive option combinations still seems like a worthwhile thing to do

Agreed. Let's keep this issue open and labelled as "help wanted".
