### ISSUE TITLE
Feature Request: Add CLI flag to display full list of rules being enforced

### ISSUE THREAD

**Issue by JSMike** [stylelint/stylelint#3235]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

Since stylelint config can extend other configs it can be difficult to understand all of the rules that are being enforced. I don't see a CLI flag to output the full set of rules/flags being enforced. This would be useful for integration with other CI/CD tools, and for overall documentation of a project. 

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

`9.1.3`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

N/A

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

N/A

> What did you expect to happen?

Display all rules being enforced

> What actually happened (e.g. what warnings or errors you are getting)?

N/A

**Comment by jeddy3** [comment]
@JSMike Thanks for the request and for using the template. Do you know if other linters offer this flag? It'd be good to know if there's a common name for such a flag.

**Comment by hudochenkov** [comment]
@jeddy3 ESLint: [`--print-config file.ext`](https://eslint.org/docs/user-guide/command-line-interface#--print-config).

**Comment by jeddy3** [comment]
@hudochenkov Thanks! Such a flag SGTM. Unless there any objections, I'll label this up as "help wanted".

**Comment by jeddy3** [comment]
Oops, I didn't spot the dupe... https://github.com/stylelint/stylelint/issues/3127. 

@JSMike Please consider contributing the option (via https://github.com/stylelint/stylelint/issues/3127) if you'd like to see it added to stylelint.

**Comment by JSMike** [comment]
@jeddy3 Thank you, tried to search first but didn't find the dupe.
