### ISSUE TITLE
Add rule (plugin?) to limit z-index to variable/functions

### ISSUE THREAD

**Issue by netta-s** [stylelint/stylelint#3247]
I've been thinking of a new rule (maybe more suitable as a plugin) to limit `z-index` use to variables and functions such as `map-get`. I really like the method of handling `z-index` props using lists in projects I've been working on, and I think it would be useful to use a rule for that.

**Comment by jeddy3** [comment]
I believe the [`stylelint-declaration-use-variable](https://github.com/sh-waqar/stylelint-declaration-use-variable) plugin will be suitable for your needs. If not, feel free to create another plugin and add it to the list.
