### ISSUE TITLE
Reduce install size

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3248]
Ref: https://github.com/stylelint/stylelint/issues/3236

The size of the install has increased significantly (and the number of packages has nearly doubled) between `8.4.0` and `9.2.0`. I believe partly because `postcss-html` [bundles a couple of parsers](https://github.com/gucong3000/postcss-html/blob/10b59ccd92d1c16ca0c06e455074200784e44334/package.json#L48-L53): 

Difference between `8.4.0` and `9.2.0`:
```
+ stylelint@8.4.0
added 260 packages in 12.919s
jeddy3:stylelint-test jeddy3$ du -sh node_modules
 24M    node_modules
```

```
+ stylelint@9.2.0
added 418 packages in 22.232s
jeddy3:stylelint-test jeddy3$ du -sh node_modules
 33M    node_modules
```

For comparsion, here's ESLint:

```
+ eslint@4.19.1
added 141 packages in 8.82s
jeddy3:stylelint-test jeddy3$ du -sh node_modules
 19M	node_modules
```

Is there anything we can do about this? @gucong3000 Is it worth optimising `postcss-html` for `<style>` tags and then making markdown and template literal parsing opt-ins? Am I right in thinking it's just the parsing of `<style>` which is most useful for Vue and Web Component authors?

**Comment by gucong3000** [comment]
With the development of `postcss-html`, I changed its original design. Maybe I should find the right time to change its name. I used `postcss-html` for split file (not just html) for `postcss` syntax parsing

**Comment by jeddy3** [comment]
@gucong3000 Thanks for splitting the syntaxes into separate packages.

Once `9.2.1` is released, we can assess the new install size of stylelint. We can then discuss:

1. which syntaxes we should bundle with stylelint _by default_
2. which syntaxes should be used via the `--custom-syntax` flag

for `stylelint@10.0`.

**Comment by jeddy3** [comment]
> I created a new package to solve: postcss-syntax (No dependencies)

I'll close this issue then.

We can move the discussion what about should be included by default to https://github.com/stylelint/stylelint/issues/3264
