### ISSUE TITLE
Invalid Option: Invalid value "composes" for option "except" of rule "indentation"

### ISSUE THREAD

**Issue by wkentdag** [stylelint/stylelint#3257]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug. I'm attempting to override my indentation rules for `composes` declarations only, and `stylelint` chokes when it encounters `composes` in my `.stylelintrc`, labeling it an invalid value:

`Invalid Option: Invalid value "composes" for option "except" of rule "indentation"`

> Which rule, if any, is this issue related to?

No specific rule - if I try to use `composes`-specific overrides in any rule in my config, it errors with an "invalid value".

> What CSS is needed to reproduce this issue?

```css
.name {
	composes:
		global(heading)
		global(heading-l);
	padding-top: 8px;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
      "indentation": [
         "tab", {
          "except": ["composes"]
        }
      ],
  }
}
```

or 

```json
  "rules": {
      "declaration-colon-space-after": [
       "always", {
        "except": ["composes"]
      }
    ],
  }
}

```

> Which version of stylelint are you using?

`9.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint ./src/**/**/*.css` and `./stylelintrc` in project root

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to CSS Modules

> What did you expect to happen?

The linter to run without throwing configuration errors.

> What actually happened (e.g. what warnings or errors you are getting)?

Encountered the following configuration error upon running `stylelint ./src/**/**/*.css`:
```shell
Invalid Option: Invalid value "composes" for option "except" of rule "indentation"
```

Note: I am happy to submit a PR for this if it's an issue that needs patching! I couldn't find any similar bugs out there but I'd be surprised if I was the first person to run into this :)

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

`compose` is not a valid option. There is only 3 valid options for [`except`](https://stylelint.io/user-guide/rules/indentation/#except-block-param-value): `"block"`, `"param"`, `"value"`.

**Comment by jeddy3** [comment]
Nor is `composes` a valid option for `declaration-colon-space-after`.

However, the following is a code style easily _enforced_ with stylelint:

```css
.name {
  composes:
    global(heading)
    global(heading-l);
  padding-top: 8px;
}
```

With the following config:

```json
{
  "rules": {
    "indentation": "tab",
    "declaration-colon-newline-after": "always-multi-line",
    "declaration-colon-space-after": "always-single-line"
   }
}
```

If however, you'd like to enforce a more idiosyncratic code style of aligning the properties values by more than one indent, then you'll need to create [a custom plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) for that. If you don't want to _enforce_ a indent value of properties, then another option is to use [`"ignore:["value"]`](https://github.com/stylelint/stylelint/blob/master/lib/rules/indentation/README.md#value) option which means you can have any indentation for the value of properties.

**Comment by wkentdag** [comment]
@jeddy3 that does the trick. Thank you both for your super quick responses.
