### ISSUE TITLE
Add autofix to color-no-hex

### ISSUE THREAD

**Issue by filipekiss** [stylelint/stylelint#3291]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

`stylelint --fix` should convert hex colors to either rgb or hsl

> Which rule, if any, is this issue related to?

color-no-hex

> What CSS is needed to reproduce this issue?

Input
```css
.foo {
  color: #FFFFFF;
}
```
Output
```css
.foo {
  color: rgb(255,255,255);
}
```

> What stylelint configuration is needed to reproduce this issue?

Since it's a new option, I propose the following:
```json
{
  "rules": {
	"color-no-hex": "rgb"
  }
}
```

The option would accept `rgb`, `hsl`, `rgba`, `hsla` and `true`. True would error but wouldn't try to fix anything.

> Which version of stylelint are you using?

9.2.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

This should work despite the method chose to run stylelint

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

I expected `stylelint --fix` to convert hex color to rgb (which is the most popular) and was disappointed when I couldn't do it.

> What actually happened (e.g. what warnings or errors you are getting)?

Just errors, no fixes.

I already have a branch in my fork where this is working, but I haven't written the tests yet. If people are interested, I'll update the branch and open the pull-request.

**Comment by jeddy3** [comment]
Plugin written: [`stylelint-color-format`](https://github.com/filipekiss/stylelint-color-format).
