### ISSUE TITLE
yarn warning incorrect peer dependency "postcss-syntax@^0.10.0"

### ISSUE THREAD

**Issue by brneto** [stylelint/stylelint#3318]
When after I removed the `yarn.lock` and then I execute `yarn`, it keep giving me the following warning:
```
"stylelint > postcss-html@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
"stylelint > postcss-markdown@0.23.7" has incorrect peer dependency "postcss-syntax@^0.10.0".
```
Environment:
```
"stylelint": "^9.2.1",
"stylelint-config-standard": "^18.2.0",
"stylelint-order": "^0.8.1",
"stylelint-scss": "^3.1.0",
"stylelint-selector-bem-pattern": "^2.0.0",
"stylelint-webpack-plugin": "^0.10.5",
"postcss-flexbugs-fixes": "^3.3.1",
"postcss-loader": "^2.1.5",
```

**Comment by brneto** [comment]
My `yarn.lock` **stylelint** section:
```
stylelint@>=3.0.2, stylelint@^9.2.1:
  version "9.2.1"
  resolved "https://registry.yarnpkg.com/stylelint/-/stylelint-9.2.1.tgz#fe63c169f6cd3bc81e77f0e3c6443df3267ec211"
  dependencies:
    autoprefixer "^8.0.0"
    balanced-match "^1.0.0"
    chalk "^2.4.1"
    cosmiconfig "^5.0.0"
    debug "^3.0.0"
    execall "^1.0.0"
    file-entry-cache "^2.0.0"
    get-stdin "^6.0.0"
    globby "^8.0.0"
    globjoin "^0.1.4"
    html-tags "^2.0.0"
    ignore "^3.3.3"
    import-lazy "^3.1.0"
    imurmurhash "^0.1.4"
    known-css-properties "^0.6.0"
    lodash "^4.17.4"
    log-symbols "^2.0.0"
    mathml-tag-names "^2.0.1"
    meow "^5.0.0"
    micromatch "^2.3.11"
    normalize-selector "^0.2.0"
    pify "^3.0.0"
    postcss "^6.0.16"
    postcss-html "^0.23.6"
    postcss-less "^1.1.5"
    postcss-markdown "^0.23.6"
    postcss-media-query-parser "^0.2.3"
    postcss-reporter "^5.0.0"
    postcss-resolve-nested-selector "^0.1.1"
    postcss-safe-parser "^3.0.1"
    postcss-sass "^0.3.0"
    postcss-scss "^1.0.2"
    postcss-selector-parser "^3.1.0"
    postcss-syntax "^0.9.0"
    postcss-value-parser "^3.3.0"
    resolve-from "^4.0.0"
    signal-exit "^3.0.2"
    specificity "^0.3.1"
    string-width "^2.1.0"
    style-search "^0.1.0"
    sugarss "^1.0.0"
    svg-tags "^1.0.0"
    table "^4.0.1"
```

My `yarn.lock` **postcss-syntax** section: 
```
postcss-syntax@^0.9.0:
  version "0.9.1"
  resolved "https://registry.yarnpkg.com/postcss-syntax/-/postcss-syntax-0.9.1.tgz#5dbd90af1631ab8805b8f594bef2c2e8002d3758"
```
As you can see stylelint is requiring the right version, so why `yarn` keep saying `has incorrect peer dependency "postcss-syntax@^0.10.0"`? No one int `yarn.lock` is asking by `postcss-syntax@^0.10.0`

**Comment by brneto** [comment]
Investigating deeper I've taken a look at `package.json` from `node_modules/stylelint/node_modules/postcss-html` and `node_modules/stylelint/node_modules/postcss-markdown`.  Doing so I've found out that in `devDependencies` section there's a reference to `"postcss-syntax": "^0.10.0"`.  I think maybe that is the cause of the `yarn` warning because while the `stylelint` `yarn` registry is saying that `stylint` depends on:
```
postcss-html "^0.23.6"
postcss-markdown "^0.23.6"
postcss-syntax "^0.9.0"
```

The `package.json` of `node_modules/stylelint/node_modules/postcss-html` and `node_modules/stylelint/node_modules/postcss-markdown` is saying that they depends on:

`"postcss-syntax": "^0.10.0"`

Some tips how I could fix that? If you all agree I can create a PR to fix that!

**Comment by brneto** [comment]
What’s your plans about the date for that new version come out?

**Comment by brneto** [comment]
How about remove from the `stylelint` the direct dependency to `postcss-syntax` as `postcss-html` and `postcss-markdown` already does that?

**Comment by hudochenkov** [comment]
@brneto we [did](https://github.com/stylelint/stylelint/pull/3261) quite opposite recently :)

**Comment by brneto** [comment]
Did you have problems doing that way? What kind of problems did you have?

**Comment by hudochenkov** [comment]
All these packages do different things. We need them all.

postcss-html did many things before. Recently postcss-syntax was extracted from it. postcss-syntax detects syntax from a file extensions and apply correct parser. postcss-html parse HTML-like files.

**Comment by hudochenkov** [comment]
Closing this issue, because it was fixed in https://github.com/stylelint/stylelint/pull/3316
