### ISSUE TITLE
Release 9.3

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#3319]
Shall we release 9.2.2? There are few issue with out dependencies https://github.com/stylelint/stylelint/issues/3318 and https://github.com/stylelint/stylelint/issues/3315. The former is already fixed. The later [will be fixed soon](https://github.com/davidtheclark/cosmiconfig/pull/145) in cosmiconfig, or we can temporary configure cosmiconfig in our repository.

- [ ] stylelint release
- [ ] stylelint-demo update
- [ ] stylelint.io update
- [ ] tweet

cc @stylelint/core

**Comment by hudochenkov** [comment]
#3315 is fixed.

**Comment by ntwb** [comment]
I can take a look at possibly making a release in ~6 hours

We should be able to also include #3321

**Comment by MatthiasKunnen** [comment]
@ntwb, what about #3320?

**Comment by ntwb** [comment]
@MatthiasKunnen Thanks, I'll review that also, sorry about the delay

**Comment by ntwb** [comment]
@gucong3000 Can you add a summary of the postcss-* fixes for the changelog please.

**Comment by gucong3000** [comment]
- postcss-syntax:
  - Add support for syntax name mapping. (https://github.com/stylelint/stylelint/issues/3325)
- postcss-html:
  - add support for vue (and quick app) template value (https://github.com/gucong3000/postcss-html/issues/58)
  - add support for vue src imports (https://github.com/stylelint/stylelint/issues/3314)
- postcss-markdown:
  - just update `postcss-*`.

**Comment by gucong3000** [comment]
# 9.2.2
-   Fixed: throws error when .vue files have `<style lang="stylus">` ([#3331](https://github.com/stylelint/stylelint/pull/3258))
-   Fixed: `no-empty-source` false positives on vue external source `<style src="*">` tag ([#3331](https://github.com/stylelint/stylelint/pull/3258))

**Comment by evilebottnawi** [comment]
@hudochenkov i think we can merge https://github.com/stylelint/stylelint/pull/3321 and release `9.3.0`

**Comment by evilebottnawi** [comment]
@gucong3000 i try to integrate linting markdown and have interesting problem around `max-line-length`:
https://github.com/stylelint/stylelint/blob/master/lib/rules/max-line-length/index.js#L42.
Just create:
```md
very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-very-long-line
```

And it is reported as problem.

//cc @stylelint/contributors any ideas how we can solve this problem?

**Comment by gucong3000** [comment]
> any ideas how we can solve this problem?

we can run `stylelint` in this way, to solve this problem?
```javascript
const postcss = require('gulp-html-postcss');
const postcss = require('stylelint');
const gulp = require('gulp');

gulp.task('css', () => (
    gulp.src('./src/*.html')
        .pipe(postcss([
            stylelint()
        ]))
        .pipe(gulp.dest('./dest'))
));
```

**Comment by evilebottnawi** [comment]
@gucong3000 we should search way how it is solve not running through `postcss`

**Comment by jeddy3** [comment]
> we have many PR, somebody have time to review their?

I'm working on them now (after a couple of weeks offline). I've 58 unread stylelint notifications... it looks likes there's been a lot of productivity these last couple of weeks :)

After I've reviewed and merged what I can, I'm happy to do the release if no one beats me to it. Is there anything (or any pending PRs) blocking the release or are we good to go?

**Comment by evilebottnawi** [comment]
@jeddy3 let's fix https://github.com/stylelint/stylelint/issues/3365 before release

**Comment by jeddy3** [comment]
Are we good to release after https://github.com/stylelint/stylelint/pull/3320, https://github.com/stylelint/stylelint/pull/3363 and https://github.com/stylelint/stylelint/pull/3376 are in?

**Comment by evilebottnawi** [comment]
@jeddy3 i think yes, let's finish their and release new version, a lot of fixes in this version :1st_place_medal:

**Comment by jeddy3** [comment]
I don't think it's essential we wait on https://github.com/stylelint/stylelint/pull/3320 as it can come in 9.4.

Unless there are any objections, I'll attempt a release this evening.

**Comment by jeddy3** [comment]
Just waiting on https://github.com/stylelint/stylelint/pull/3381 to be reviewed, and then I'll release.

**Comment by jeddy3** [comment]
Done 🎉 

Thanks to all the new contributors! New rules and options were added by them in this release.

Thanks, as always, to the long-standing contributors for squashing bugs and adding features!
