### ISSUE TITLE
npmignore

### ISSUE THREAD

**Issue by TrySound** [stylelint/stylelint#332]
Do we need es6 sources? If you will add it to npmignore, package will be 0.5mb smaller.

**Comment by MoOx** [comment]
If for some reason people want to build from master, it's mandatory... Is there still __tests__ folders ?

**Comment by TrySound** [comment]
`__tests__` are there.

**Comment by TrySound** [comment]
Without tests (in both `dist` and `src`) we will save 550kb

**Comment by jeddy3** [comment]
Can confirm. That's odd considering `__tests__` has been in the .npmignore file since the beginning...

**Comment by MoOx** [comment]
Yeah that why I mentionned them. They should be ignored.

**Comment by TrySound** [comment]
@jeddy3 Maybe better `**/__tests__` or I'm wrong?

**Comment by TrySound** [comment]
Or maybe it overrides with package.json `files` field?

**Comment by TrySound** [comment]
@jeddy3 Yes, I tried to remove package files and it works!

**Comment by jeddy3** [comment]
@TrySound Thanks for looking into this! Yeap, it looks like the `files` array in `package.json` and `.npmignore` don't seem to play well together. I've got a pending PR which cleans things up and removes the extra 550kb from the package.

**Comment by TrySound** [comment]
@jeddy3 Thank you very much!

**Comment by TrySound** [comment]
Do we need readme in sources? Will be saved 90kb more :)

**Comment by MoOx** [comment]
Readme is automatic. And doc is always nice for offline use.

**Comment by davidtheclark** [comment]
Yes, I like having READMEs installed, as well.
