### ISSUE TITLE
Stylelint cannot parse nested font properties

### ISSUE THREAD

**Issue by alexmiddeleer** [stylelint/stylelint#3324]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I think this is a bug. Stylelint cannot seem to parse nested font props as described here: https://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_properties:

> Which rule, if any, is this issue related to?

None

> What CSS is needed to reproduce this issue?

```css
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```

> What stylelint configuration is needed to reproduce this issue?

```
{
  extends: ".../node_modules/stylelint-config-recommended-scss",

  rules: {
    "block-opening-brace-space-before": "always",
    "declaration-colon-space-after": "always",
    "selector-list-comma-space-after": "never-single-line",
    "max-empty-lines": 1,
    length-zero-no-unit: true
  }
}
```

> Which version of stylelint are you using?

`8.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint foo.scss`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

Yes, it's related to SCSS nesting and namespacing.

> What did you expect to happen?

Successful parse.

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
foo.scss
2:5  ✖  Cannot parse selector   parseError
```

I looked for duplicate issues but didn't find any. Thanks to everyone working on stylelint :)

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Please, install latest stylelint and see if it fixes an error.

**Comment by alexmiddeleer** [comment]
Oops, I just realized the latest version is 9. That fixed my issue. Sorry for wasting your time!
