### ISSUE TITLE
VSCode Stylelint Extension: Cannot find module 'postcss-xml'

### ISSUE THREAD

**Issue by beastdestroyer** [stylelint/stylelint#3328]
This is a bug which popped up for me when I created a new XML file. A notification popped up stating that the 'postcss-xml' module cannot be found. the error doesn't seem to originate from any stylelint rules either, nor does it need CSS or anything, creating an XML file made it pop-out

The configuation i was using at the time was stylelint-config-recommended-scss, running version 9.2.1, extension version 0.36.2. Upon creating the XML file, I expected nothing to happen, especially since I don't use CSS with XML , but instead one did.

Using:
Windows 10 version 1803, Build: 17134
VSCode Insiders for 1.24

**Comment by evilebottnawi** [comment]
@beastdestroyer please use issue template

**Comment by Arcanemagus** [comment]
I'm guessing this is the same issue discussed in https://github.com/stylelint/stylelint/issues/3323.

**Comment by evilebottnawi** [comment]
@Arcanemagus yes :+1: 
@beastdestroyer looks like we already solve and will be release in `9.2.2`. Let's close this issue, feel free to reopen or recreate if problem still exists after update to `9.2.2`. Thanks

**Comment by shinnn** [comment]
> looks like we already solve and will be release in `9.2.2`

No.

```js
'use strict';

const {lint} = require('stylelint'); // current latest `master` (d3d4bfc9566cfbaa4cec1ebdf978d9e5108da9fd)

lint({
  code: '<xml/>',
  codeFilename: 'example.xml',
  config: {
    rules: {}
  }
}).catch(console.error);
```

```console
$ node example.js
{ Error: Cannot find module 'postcss-xml'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireSyntax (/Users/example/test/node_modules/postcss-syntax/get-syntax.js:31:19)
    at getSyntax (/Users/example/test/node_modules/postcss-syntax/get-syntax.js:50:10)
    at parser (/Users/example/test/node_modules/postcss-syntax/parser.js:37:17)
    at Object.parse (/Users/example/test/node_modules/postcss-syntax/parse.js:19:43)
    at new LazyResult (/Users/example/test/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/example/test/node_modules/postcss/lib/processor.js:117:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by evilebottnawi** [comment]
@shinnn hm, interesting how css can be used in `xml`?
/cc @gucong3000

**Comment by gucong3000** [comment]
@NikosK72 
> hm, interesting how css can be used in xml?

And I have the same doubts.

**Comment by hudochenkov** [comment]
I don't know how plugins work in VS Code, or stylelint plugin specifically. But it feels like the plugin or VS Code tries to lint everything and relies on stylelint to determine if it should be linted or not. I think it's plugins job to filter what's goes into stylelint for linting.

**Comment by evilebottnawi** [comment]
Looks yes https://www.w3.org/Style/styling-XML.html#Embedded :smile:

**Comment by NikosK72** [comment]
@gucong3000 
Well it gets invoked by itself while working with these files.

**Comment by evilebottnawi** [comment]
@NikosK72 can you provide stylelint configuration for VS?

**Comment by evilebottnawi** [comment]
@shinnn expected error, because we can't have `postcss-xml` right now
/cc @gucong3000 Can we throw better error when people try to lint syntax what we don't support, looks it will be easy

**Comment by gucong3000** [comment]
@NikosK72
> Looks yes https://www.w3.org/Style/styling-XML.html#Embedded 😄

Does your XML file conform to this syntax?

**Comment by hudochenkov** [comment]
@gucong3000 it's not a standard. Also, this issue is not about XML, but about trying to lint things, that should not be linted.

**Comment by hudochenkov** [comment]
vscode-stylelint tries to lint styles in [XML files by default](https://github.com/shinnn/vscode-stylelint/blob/0843c4fa22c0319f5b099bd9ca4b0fd08f0cc109/package.json#L48). Stylelint doesn't support styles linting in XML (it's not even in web standards). I'm closing this issue as it's not relevant to stylelint itselft, but to vscode-stylelint.

@beastdestroyer you can exclude .xml files from plugin configuration (https://github.com/shinnn/vscode-stylelint/issues/148#issuecomment-370976249).

**Comment by beastdestroyer** [comment]
@hudochenkov Thanks for the help!

**Comment by shinnn** [comment]
Again, how do you "already solve and will be release in `9.2.2`" ?

**Comment by NikosK72** [comment]
@gucong3000 , yes 100% well formed and valid XML. It has suddenly started to happen with the latest update. Never had issues before.

**Comment by gucong3000** [comment]
@NikosK72 @shinnn 
I think `*.xml` should not apply to `stylelint`.
I don't understand why vscode stylelint extension do that.

> Again, how do you "already solve and will be release in 9.2.2" [sic] ?

No, XML format is still not supported in `stylelint@9.2.2`,

**Comment by NikosK72** [comment]
@gucong3000 Is there a way of disabling that extension for xmls. That error gets launched all by itself when opening whatever xml. I had the suspicion that it could be some sort of conflict with another extension, but it happens even with it being the only available extension in VS code.

**Comment by gucong3000** [comment]
> Is there a way of disabling that extension for xmls. 

Maybe @shinnn can help you.

**Comment by brunocalou** [comment]
I had the same issue with .svg files. I solved adding `"ignoreFiles": ["**/**.svg", "**/**.xml"]` to .stylelintrc

**Comment by gucong3000** [comment]
> I had the same issue with .svg files. I solved adding "ignoreFiles": ["**/**.svg", "**/**.xml"] to .stylelintrc

@shinnn I think we should check the file name extension before applying XML files to `stylelint`, only
