### ISSUE TITLE
text-stroke

### ISSUE THREAD

**Issue by strarsis** [stylelint/stylelint#3330]
**Is your feature request related to a problem? Please describe.**
[`text-stroke`](https://caniuse.com/#feat=text-stroke) is well supported now (albeit with `-webkit-` prefix). I want to use `text-stroke` without prefix in styles because I am using an autoprefixer and browsers will probably support it without prefixes in near future.

**Describe the solution you'd like**
Add `text-stroke` as valid CSS property.

**Describe alternatives you've considered**
The alternative would be using `text-stroke` with `-webkit-` prefix: `-webkit-text-stroke`, 
but this would lock into the `-webkit-` prefix.

**Comment by hudochenkov** [comment]
It's not clear what problem your experience. Perhaps, [bug report](https://github.com/stylelint/stylelint/issues/new?template=Bug_report.md) issue template is the correct issue template to use to describe a problem you're facing.

**Comment by evilebottnawi** [comment]
@strarsis friendly ping

**Comment by strarsis** [comment]
@hudochenkov, @evilebottnawi: `text-stroke` is not available yet, only `-webkit-text-stroke`, hence it doesn't make sense yet to add `text-stroke` as supported CSS property.
