### ISSUE TITLE
Catch invalid 'property: value' combinations

### ISSUE THREAD

**Issue by mvasin** [stylelint/stylelint#3343]
**Is your feature request related to a problem? Please describe.**
I spent an hour pursuing a bug before I finally noticed `display: fixed`.

**Describe the solution you'd like**
Check properties for invalid values. Like `color: wite`, `display: fixed` etc. All that stuff that's silently ignored by browsers, something that's terrifically hard to spot sometimes.

**Describe alternatives you've considered**
I'd love to encounter a Chrome plugin or some secret browser console tab that shows ignored CSS rules, but I couldn't.

**Additional context**
I use stylelint for linting [styled components](https://www.styled-components.com/docs/basics). Here's my [post](https://spectrum.chat/thread/31cb00f5-31e4-4c6e-8ea1-55decfa2da2a) about the problem on the styled-components forum.

I'd be happy to learn that stylelint already does that and it's [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) fault that doesn't include some linting rules, but seems like it's not the case.

**Comment by jeddy3** [comment]
@mvasin Thanks for the report and for using a template.

You're looking for a specification _validator_. [csstree](https://github.com/csstree/validator) is an up-and-coming one that has a [stylelint plugin](https://github.com/csstree/stylelint-validator).

**Comment by DanielBiskup** [comment]
This is so useful. What do you think about adding this sentence to your "Getting started" or documentation?

**Comment by ybiquitous** [comment]
FYI: The following page describes `csstree`:
https://stylelint.io/about/linting#validators
