### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined error

### ISSUE THREAD

**Issue by mdesantis** [stylelint/stylelint#3351]
**Describe the bug? (A clear and concise description of what the bug is)**

Hello, I'm new to stylelint. I added it to my experimental project, but I can't make it work properly. My project is public on GitHub, you can access to the full code related to this issue [here](https://github.com/mdesantis/stimulus_demo/tree/stylelint).

When I run `stylelint` it raises the error `TypeError: Cannot read property 'type' of undefined`. More details below.

**Which rule, if any, is this issue related to?**

No particular rules are set

**What CSS is needed to reproduce this issue?**

Any, I want to lint .sass files in my project, if it is relevant somehow

**What stylelint configuration is needed to reproduce this issue?**

This is the one I'm trying now:

```yml
extends: stylelint-config-sass-guidelines
```

Extension used: `"stylelint-config-sass-guidelines": "^5.0.0"`

But I had the same error with

```yml
extends: stylelint-config-standard
```

Extension used: `"stylelint-config-standard": "^18.2.0"`

**Which version of stylelint are you using?**

`9.2.1`

**How are you running stylelint: CLI, PostCSS plugin, Node API?**

CLI with `node_modules/stylelint/bin/stylelint.js '**/*.sass'`

**Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?**

I don't know, I'm using Sass files, but it doesn't seem related to me

**What did you expect to happen?**

No error to be raised, .sass files to be properly linted and result output to be printed

**What actually happened (e.g. what warnings or errors you are getting)?**

The following error was raised:

```
> node_modules/stylelint/bin/stylelint.js '**/*.sass'
TypeError: Cannot read property 'type' of undefined
    at indentationLevel (/home/maurizio/Sviluppo/stimulus_demo/node_modules/stylelint/lib/rules/indentation/index.js:152:23)
    at root.walk.node (/home/maurizio/Sviluppo/stimulus_demo/node_modules/stylelint/lib/rules/indentation/index.js:54:25)
    at /home/maurizio/Sviluppo/stimulus_demo/node_modules/postcss-sass/node_modules/postcss/lib/container.js:144:26
    at Root.each (/home/maurizio/Sviluppo/stimulus_demo/node_modules/postcss-sass/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/home/maurizio/Sviluppo/stimulus_demo/node_modules/postcss-sass/node_modules/postcss/lib/container.js:143:21)
    at /home/maurizio/Sviluppo/stimulus_demo/node_modules/stylelint/lib/rules/indentation/index.js:53:10
    at Promise.resolve.then (/home/maurizio/Sviluppo/stimulus_demo/node_modules/stylelint/lib/lintSource.js:221:9)
    at <anonymous>
```

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/stylelint/stylelint/issues/3244

**Comment by mdesantis** [comment]
Oh, sorry @evilebottnawi, I searched for duplicates but coudln't find it
