### ISSUE TITLE
Document use of globby rather than node-glob

### ISSUE THREAD

**Issue by shellscape** [stylelint/stylelint#3352]
**Describe the bug? (A clear and concise description of what the bug is)**

There's no issue template for documentation or metadata issues, so I'm putting this one here.

Searching the repo reveals several mentions of `node-glob` https://github.com/stylelint/stylelint/search?q=node-glob&unscoped_q=node-glob. However, this package uses `globby` as of 775926504f39468ed18efa20b40f408f8affe985. The documentation should be updated to reflect the correct glob package in use.

**Which rule, if any, is this issue related to?**

n/a

**What CSS is needed to reproduce this issue?**

n/a

**What stylelint configuration is needed to reproduce this issue?**

n/a

**Which version of stylelint are you using?**

github

**How are you running stylelint: CLI, PostCSS plugin, Node API?**

n/a

**Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?**

No

**What did you expect to happen?**

Docs reflect accurate package name.

**What actually happened (e.g. what warnings or errors you are getting)?**

Docs claim different package is in use

**Comment by jeddy3** [comment]
> There's no issue template for documentation or metadata issues, so I'm putting this one here.

Thanks for the heads up. I'm going to cross reference to https://github.com/stylelint/stylelint/issues/3313 so we can resolve this there.

> The documentation should be updated to reflect the correct glob package in use.

Yep agreed.
