### ISSUE TITLE
[Rule]: Using :focus with :hover

### ISSUE THREAD

**Issue by YozhikM** [stylelint/stylelint#3354]
**Is your feature request related to a problem? Please describe.**
To improve the availability of sites. To remind developers of this important pseudo-class.

**Describe the solution you'd like**
Adding a new rule.

**Describe alternatives you've considered**
Include this in other selector rules.

**Additional context**
...

**Comment by jeddy3** [comment]
Done in a plugin in https://github.com/stylelint/stylelint/pull/3364
