### ISSUE TITLE
[Rule]: prefers-reduced-motion

### ISSUE THREAD

**Issue by YozhikM** [stylelint/stylelint#3356]
**Is your feature request related to a problem? Please describe.**
Solves the problem of the availability of sites for people who have the disabled animation for health reasons, for example.

It is a non-vendor-prefixed declaration that allows developers to “create styles that avoid large areas of motion for users that specify a preference for reduced motion in System Preferences.”

[webkit.org](https://webkit.org/blog/7551/responsive-design-for-motion/)
[css-tricks.org](https://css-tricks.com/introduction-reduced-motion-media-query/)

**Describe the solution you'd like**
Adding a new rule.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by jeddy3** [comment]
Done in a plugin in https://github.com/stylelint/stylelint/pull/3364
