### ISSUE TITLE
Root node type of `atrule` not detected

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#336]
`rule-no-duplicate-properties` and `rule-properties-order` won't run when the root node is an at-rule. Based on the [PostCSS docs](https://github.com/postcss/postcss/blob/master/docs/api.md#nodetype) it looks like this is due to a simple typo.  

This PR should detect and fix the problem: https://github.com/stylelint/stylelint/pull/337

**Comment by jeddy3** [comment]
Published to npm
