### ISSUE TITLE
stylelint-a11y

### ISSUE THREAD

**Issue by YozhikM** [stylelint/stylelint#3361]
Created the [plugin](https://github.com/YozhikM/stylelint-a11y). It would be very cool if you looked and checked it.
What will happen to the previous issues and PRs?
@jeddy3 @evilebottnawi @hudochenkov can you help me, please?

**Comment by evilebottnawi** [comment]
What do you think about create this plugin under `stylelint` orgs? 

Why?
- It is allow fix critical problems asap 
- Ensures that somebody always have access to repo/npm
- Same style for code and tools.

**Comment by YozhikM** [comment]
@evilebottnawi Okay, I agree, it sounds cool.

**Comment by hudochenkov** [comment]
> What do you think about create this plugin under stylelint org?
> It is allow fix critical problems asap
> Ensures that somebody always have access to repo/npm

Our biggest plugin packs not under organization (e.g. `stylelint-scss`, `styelint-order`), exactly for the opposite reasons. Tools under `stylelint` organization imply that stylelint/core members will support them. I'm afraid, we don't have the capacity to maintain more tools.

**Comment by jeddy3** [comment]
> Created the plugin.

@YozhikM Holy smokes, that was fast. Good job!

> It would be very cool if you looked and checked it.

It looks great to me. Two minor suggestions:

* [this deps](https://github.com/YozhikM/stylelint-a11y/blob/master/package.json#L63) looks redundant
* the "Contribute to stylelint" bullet on the homepage feels a little at odds with the other bullets

> What will happen to the previous issues and PRs?

I'll close them.

> Our biggest plugin packs not under organization (e.g. stylelint-scss, styelint-order), exactly for the opposite reasons.

Agreed. This has been discussed on a few occasions in the past. I don't believe anything has changed.

What we can do is a better job promoting plugins within the stylelint documentation. We can create a separate issue for that.

> Ensures that somebody always have access to repo/npm

@evilebottnawi I'm sure @YozhikM would be grateful for any help and would happily add you to the repo and npm package as a contributor.

---

@YozhikM Do you want to publish the package? Then send a PR updating the [list of plugins](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md).

I'll create that separate issue for us all to discuss how we can best tweak the stylelint documentation to better promote plugins.

**Comment by ntwb** [comment]
Woot, thanks @YozhikM, I've also sent you an invite to join the @stylelint/contributors team 😄

**Comment by YozhikM** [comment]
@ntwb Wohoo, thank you, I will be happy to help. Now I will transfer the repo to the organization

**Comment by YozhikM** [comment]
@evilebottnawi @hudochenkov  @jeddy3  @ntwb  And since I do not have the rights to create a repo, I gave you access to my own.

**Comment by ntwb** [comment]
@YozhikM Let's hold off on transferring the repo as @hudochenkov pointed out above:

> _Tools under `stylelint` organization imply that @stylelint/core members will support them. I'm afraid, we don't have the capacity to maintain more tools._

We've only recently decided to actively grow the `stylelint` org team, once this growth experiment settles down a little this may allow the `stylelint` org to maintain more tools.

**Comment by YozhikM** [comment]
@ntwb Well understood you.

**Comment by ntwb** [comment]
p.s. This process will soon be automated and anyone who contributes to stylelint that has a pull request merged will be invited to join the `stylelint` organisation.

~Until I've sorted that automation~, I've manually invited more recent contributors to the `stylelint` organisation and @stylelint/contributors team

Hey @stylelint/contributors I've just enabled the app https://github.com/apps/invite-contributors/
> invite-contributors is a GitHub App built with probot that automatically invites new contributors to your repository's organization once they get a Pull Request merged.

**Comment by evilebottnawi** [comment]
@YozhikM can you send invite to me in plugin, to allow fast critical fixes and do not lost control if you will be unavailable?

**Comment by evilebottnawi** [comment]
@YozhikM and npm access :+1: Thanks!

**Comment by ntwb** [comment]
Welcome to stylelint @filipekiss 🎉

**Comment by jeddy3** [comment]
We can continue the discussion about how best to promote this plugin and the plugin system itself in https://github.com/stylelint/stylelint/issues/3362.
