### ISSUE TITLE
Better promote the plugin system

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#3362]
Ref: https://github.com/stylelint/stylelint/pull/3355#issuecomment-394426248 & https://github.com/stylelint/stylelint/issues/3361#issuecomment-394548640

There are some excellent stylelint plugins. We could do a better job of promoting them and the plugin system itself.

Currently, we:

* give plugins a top-level navigation item on the website
* mention the plugin system within the list of features in the README
* mention and link to the list of plugins from the list of the rules page

A couple of ideas... we could:

1. Move "Support for plugins" up the features list and embellish it with examples e.g. **Support for plugins**: It's easy to create your own rules and add them to the linter, or make use of plugins written by the community. For example, there are plugin packs for [Scss](..), [a11y](..) and [ordering of things]() you can use.
2. Create a "Highlighted plugins" list on the plugins page. We could flesh out the descriptions of each of these plugins.
3. Look to embellish the existing mentions of the plugins system in the docs.
3. Look for other places in the docs where a mention of the plugin system would be appropriate.

Any others?

**Comment by filipekiss** [comment]
I guess we could scrape the project issues to see what people ask the most and that could be solved by plugins and create a few "recipes" to tackle those common issues, showing how powerful stylelint can get exactly because of plugins.
