### ISSUE TITLE
Add autofix to declaration-block-trailing-semicolon

### ISSUE THREAD

**Issue by trollepierre** [stylelint/stylelint#3369]
**Is your feature request related to a problem? Please describe.**
Sometimes we forget to add trailing semicolon

**Describe the solution you'd like**
I wish stylelint would add directly the missing trailing semicolon

**Comment by jeddy3** [comment]
@trollepierre Thanks for the request and for using the template. The issue is labelled as "help wanted", so please consider contributing the feature if you'd like to see it added to stylelint.

**Comment by YozhikM** [comment]
WIP

**Comment by hudochenkov** [comment]
Done in #3382.
