### ISSUE TITLE
Fix module resolution issue due to transitive dependency of micromatch

### ISSUE THREAD

**Issue by onlywei** [stylelint/stylelint#3370]
**Describe the bug? (A clear and concise description of what the bug is)**
A transitive dependency has failed to properly declare its dependencies in its `package.json`. This causes failure when installed & run using a strict client such as [pnpm](https://pnpm.js.org/).

**Which rule, if any, is this issue related to?**
N/A

**What CSS is needed to reproduce this issue?**
N/A

**What stylelint configuration is needed to reproduce this issue?**
N/A

**Which version of stylelint are you using?**
`9.1.3`

**How are you running stylelint: CLI, PostCSS plugin, Node API?**

CLI with:
```stylelint client/src/**/*.pcss```

**Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?**

No

**What did you expect to happen?**

No module resolution issues to happen.

**What actually happened (e.g. what warnings or errors you are getting)?**

I get this module resolution error:

```shell
module.js:549
    throw err;
    ^

Error: Cannot find module 'arr-flatten'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/node_modules/arr-diff/2.0.0/node_modules/arr-diff/index.js:10:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by ntwb** [comment]
Thanks for creating the issue @onlywei, and using our issue template 😄 

We've not yet updated to Micromatch 3.x as we have not been able to resolve the Windows issues it introduces.

Please see also #2888 and the bunch or previous references linked in that issue.

**Comment by jeddy3** [comment]
Labelling as "help wanted". Any help getting PR https://github.com/stylelint/stylelint/pull/2888 resolved would be greatly appreciated.

**Comment by hudochenkov** [comment]
We have micromatch updated to v4. This issue was probably resolved.
