### ISSUE TITLE
Handling of PostCSS syntax errors

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#34]
We need some elegant handling of PostCSS syntax errors -- especially considering that it's kind of the first line of linting (will find errors in people's code even if they have not turned on any rules).

**Comment by MoOx** [comment]
Currently postcss will automatically throw error before calling any plugins, so not sure how we can handle that while we are only offering a plugin :/

**Comment by davidtheclark** [comment]
Well, maybe we don't need to, then. We just trust whatever runner to handle errors, accomplishing that first layer of linting; and when the time comes that stylelint has its own runner, we start thinking about this. Should we close this issue then?

**Comment by MoOx** [comment]
I think we can for now.
