### ISSUE TITLE
no-missing-end-of-source-newline with style

### ISSUE THREAD

**Issue by codepandy** [stylelint/stylelint#3406]
```
  <div
    style={{
      margin: '-24px -24px 0',
    /*show error*/}}
    className={wrapperClassName}
  >
```
the style show `[stylelint] Unexpected missing end-of-source newline (no-missing-end-of-source-newline)` at the last brace.

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.
