### ISSUE TITLE
Add autofix to selector-list-comma-newline-after

### ISSUE THREAD

**Issue by trollepierre** [stylelint/stylelint#3409]
> What is the problem you're trying to solve?

stylelint --fix should add newline after comma selector list

> What solution would you like to see?

selector-list-comma-newline-after autofix

**Comment by jeddy3** [comment]
@trollepierre Thanks for the request and for using the template.

As the issue has been labelled "help wanted", please consider [contributing the feature](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-autofixing).
