### ISSUE TITLE
Unhandled 'error' event when using less comments

### ISSUE THREAD

**Issue by saviomd** [stylelint/stylelint#341]
__/* lorem ipsum */__ comments always works
__// lorem ipsum__ comments only works if it's the only thing in the line

```
/* this works */
// this works
.selector {
  margin: 10px; /* this works */
  padding: 10px; // this doesn't work, says that have a "Unknown word" in this line
}
```

**Comment by MoOx** [comment]
It's a postcss parser issue, please open it on postcss repo.

**Comment by MoOx** [comment]
https://github.com/postcss/postcss/issues/new ;)

**Comment by saviomd** [comment]
Ok, sorry and thanks! :)
