### ISSUE TITLE
declaration-colon-space-after throws lint error, doesn't autofix

### ISSUE THREAD

**Issue by NZI** [stylelint/stylelint#3422]
> Clearly describe the bug

Running `./node_modules/.bin/stylelint "my/scss/**/*.scss" --fix` produces errors instead of auto fixing

> Which rule, if any, is the bug related to?

This is related to: declaration-colon-space-after

> What CSS is needed to reproduce the bug?

```css
body {
  font-size:  1px;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
  "stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "at-rule-no-unknown": [
        true,
        {
          "ignoreAtRules": [
            "function",
            "if",
            "each",
            "include",
            "mixin"
          ]
        }
      ],
      "no-descending-specificity": null
    }
  }
```

> Which version of stylelint are you using?

`9.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

 - CLI with `./node_modules/.bin/stylelint "my/scss/**/*.scss" --fix`
 - Gulp with `require('gulp-run')('./node_modules/.bin/stylelint "' + SCSS_SOURCE +'" --fix').exec()`
 - Also an issue with `gulp-stylelint`:
```javascript
gulp.task('stylelint:fix', () => {
  return gulp.src(SCSS_SOURCE)
    .pipe(gulpStylelint({
      fix: true
    }))
    .pipe(gulp.dest(SCSS_DIR))
})
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, it doesn't seem to be related.

> What did you expect to happen?

No errors flagged, and spaces trimmed to 1 space after colon.

> What actually happened (e.g. what warnings or errors did you get)?

declaration-colon-space-after error displayed, scss remained the same

```shell
my/scss/test.scss
 2:13  ✖  Expected single space after ":" with a single-line declaration   declaration-colon-space-after
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

This rule doesn't support autofix. Consider [contributing](https://stylelint.io/developer-guide/rules/#adding-autofixing) this feature.
