### ISSUE TITLE
Add ignoreFunctions: [] to unit-no-unknown

### ISSUE THREAD

**Issue by minorgod** [stylelint/stylelint#3424]
> What is the problem you're trying to solve?

Ignore an unknown unit format based on the entire value of the attribute rather than just the unit. I find this useful specifically in cases of using background-image: image-set with units such as 1x, 2x, 3x, etc. For example: 

```css
div {
  background-image: image-set(
	     '/images/some-image-1x.jpg' 1x,
	     '/images/some-image-2x.jpg' 2x,
	     '/images/some-image-3x.jpg' 3x,
	);
}
```
Yes, we could simply use the ignoreUnits secondary option with "x" as a string literal or regex, but this is too broad as it will allow values such as 20x or 200x, which are likely typos where "px" was the intended unit. Since image-set units will likely only ever be single digit values, I only want to allow "x" as a unit in situations where the value is between 1x and 4x. If we had another secondary option such as "ignoreValue" it would solve this problem as I could create a regex matching rule such as ["/[1-4]x/"] which would cover those specific cases. 

> What solution would you like to see?

A new secondary option called "ignoreValue" which takes exactly the same parameter format as the existing ignoreUnits secondary option, but instead of comparing it with the units, it would compare it with the valueNode.value. 

I suspect my use case is achievable via another rule such as declaration-property-value-whitelist, however in the case of an image-set, given the variability of the filenames and the format of background-image: image-set syntax, the regex that would need to be created seems rather complicated compared to how easy it is to create a regex for just a unit value. Also, adding an "ignoreValue" secondary option is a very trivial code and documentation change. In fact..

I have created a fork/branch and implemented this feature (including documentation) here:
https://github.com/minorgod/stylelint/tree/unit-no-unknown_ignoreFormat/lib/rules/unit-no-unknown

The existing "ignoreUnits" secondary option implementation could be modified so that it compares both the units and the value, but this could potentially break the expected behavior of some people's configuration, so it would probably be better just to add an new "ignoreValue" secondary option. 

If this feature is approved I'll be happy to submit a pull request. If there's another way to easily achieve what I'm trying to do via an existing stylelint rule please advise.

**Comment by jeddy3** [comment]
@minorgod Thanks for the report and for using the template.

Is `image-set` in the specs? If it's only in a draft one then we should probably treat this as a bug as `x` doesn't seem like an _unit_ to me. If it's in the spec then let's ignore `x` inside `image-set` functions in this rule.

@minorgod Can you dig up a little more information about the `image-set` feature for us, please?

**Comment by hudochenkov** [comment]
There [was](https://github.com/stylelint/stylelint/issues/3026) discussion about this unit. `image-set` is [a draft spec](https://drafts.csswg.org/css-images-4/#image-set-notation), and it's in negotiation (i. e. might change or be removed). `x` unit is a [draft spec](https://drafts.csswg.org/css-values-4/#x).

I would stick with my previous suggestion:

> `x` unit is only in Editor's Draft, i. e. not ready to use. Also, adding `x` as a supported unit will make `unit-no-unknown` less useful, as `x` is most likely a typo for `px` these days.
>
> Users of currently non-standard syntax could use the [`ignoreUnits` secondary option](https://github.com/stylelint/stylelint/blob/master/lib/rules/unit-no-unknown/README.md#ignoreunits-regex-string) of the rule.

**Comment by jeddy3** [comment]
@hudochenkov Makes sense.

I think a compromise between just using the current `ignoreUnits` option and @minorgod's proposed `ignoreValues` option is an `ignoreFunctions` option.

It feels a bit more in line with how [other `ignore*` options](https://github.com/stylelint/stylelint/tree/master/lib/rules/function-name-case#ignorefunctions-regex-non-regex) work i.e. the `ignore*` options target [CSS constructs](http://apps.workflower.fi/vocabs/css/en) (e.g. a [value](http://apps.workflower.fi/vocabs/css/en#value) of a [declaration](http://apps.workflower.fi/vocabs/css/en#declaration)), whereas @minorgod's fork is targetting an artefact of the values parser. For anyone interested... we do this to hide parser implementation details from the user and only expose them to _familar_ CSS constructs and vocab in the API. 

So, for example, `ignoreFunctions: ["image-set"]` would keep `unit-no-unknown` useful as it would still catch instances of `x` outside of the `image-set` function. 

Sound good? 

I'll label this issue up as a new option (`ignoreFunctions: [string, regex]`). @minorgod Feel free to contribute this option. There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to get started.... it should just be a minor tweak to your fork i.e. checking that the "value" node is of type `function` before comparing it.

**Comment by minorgod** [comment]
@jeddy3 Thanks for your consideration! I'm a bit busy, but I'll try to make your suggested change in the next day or two and submit a pull request.

**Comment by evilebottnawi** [comment]
Just information, we can improve `unit-no-unknown` check `x` unit only for `image-set` function, in other places it will be a error

**Comment by evilebottnawi** [comment]
To be precise, only where it is possible to use `<resolution>`, it is not hard

**Comment by hudochenkov** [comment]
@evilebottnawi I think this is a good idea! Do you mind creating an issue, please?

**Comment by evilebottnawi** [comment]
@hudochenkov done https://github.com/stylelint/stylelint/issues/3770
