### ISSUE TITLE
Plugins in vscode

### ISSUE THREAD

**Issue by xereda** [stylelint/stylelint#3426]
How do I use a plugin in a setting in the vscode editor? I'm using the "vscode-stylelint" extension in vscode.
I need to validate `declaration-block-properties-order`, but as it was deprecated in favor of a plugin, I do not know how to apply it in vscode.

Can you help me?

**Comment by jeddy3** [comment]
The VSCode extension respects your [stylelint configuration object](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md).

Follow the [plugin instructions](https://github.com/hudochenkov/stylelint-order#installation) to add the plugin to your configuration object. 

Please use stackoverflow for future support.
