### ISSUE TITLE
SublimeLinter-contrib-stylelint editor plugin

### ISSUE THREAD

**Issue by kungfusheep** [stylelint/stylelint#345]
Hi Guys

Just a quick note on this sublime plugin. It's currently looking for a `.stylelintrc` file in the format of the current configuration object. I know there's not been a consensus on the format of this file so when there is I'll reflect it in the plugin. 

Cheers!

**Comment by ntwb** [comment]
This is being looked at in https://github.com/stylelint/stylelint/issues/288

**Comment by jeddy3** [comment]
There's more discussion in https://github.com/postcss/postcss/issues/477 too, if you're interested.

**Comment by davidtheclark** [comment]
@kungfusheep : Thought you might have input on this question as it relates to the Sublime Text plugin: https://github.com/stylelint/stylelint/pull/380#issuecomment-139892268

> Would there be any real downside to only allowing CommonJS configuration files?

**Comment by davidtheclark** [comment]
@kungfusheep Can you verify that the `js-api` branch will work for your plugin? It introduces the `.stylelintc` file (in JSON format), the CLI, the JS API, and extends. I think that ensuring that it works with editor plugins is vital.

**Comment by kungfusheep** [comment]
@davidtheclark I'll take a look. Unless the interface has changed it *should* be okay, i've probably just jinxed that though.

**Comment by kungfusheep** [comment]
@davidtheclark Okay, the good news is this new codebase is fully backward-compatible as far as the plugin is concerned. I'm going to need to make a change to support plugins, but that's just to set the correct current working directory.

**Comment by davidtheclark** [comment]
Awesome, thanks for checking it out!

**Comment by davidtheclark** [comment]
@kungfusheep : Now that we have the CLI/API out (in 2.0.0) with `.stylelintrc` support, should we close this issue?

**Comment by kungfusheep** [comment]
Absolutely!
