### ISSUE TITLE
Stylelint does not ignore disable command after postcss-import

### ISSUE THREAD

**Issue by sibicode** [stylelint/stylelint#3452]
> Clearly describe the documentation issue

Stylelint does not ignore the file postcss-import

**index.css:**
```
@import "foo.css"

/* stylelint-disable */
@import "../../node_modules/slick-carousel/slick/slick.css";
/* stylelint-enable */

@import "bar.css"
```
**postcss.config:**

```
require('postcss-import'),
require('stylelint')({
  reporters: [
    {formatter: 'string', console: true}
  ]
}),
require('lost'),
require('postcss-preset-env')({
  stage: 1,
  features: {
    'custom-properties': {
      preserve: false
    },
    'nesting-rules': true
  }
}),
require('autoprefixer')
```

**package.json:**

```
    "autoprefixer": "^8.6.4",
    "gulp-postcss": "^7.0.1",
    "stylelint": "^9.3.0",
    "lost": "^8.3.0",
    "postcss-import": "^11.1.0",
    "postcss-preset-env": "^5.2.1",
```
after import comments are stay, but Stylelint ignore it, why ?

**Comment by jeddy3** [comment]
From [the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#usage-examples):

> We recommend you lint your CSS before applying any transformations.

So, either put stylelint as the first plugin in your PostCSS pipeline or use postcss-import's `plugin` option.

Alternatively, you can use [stylelint-webpack-plugin](https://github.com/webpack-contrib/stylelint-webpack-plugin).
