### ISSUE TITLE
no-descending-specificity with interpolation

### ISSUE THREAD

**Issue by in19farkt** [stylelint/stylelint#3455]
> Clearly describe the bug

Interpolation in the selector results in an error `Expected selector "#{$r}_modifier .block__element" to come before selector ".block__element" (no-descending-specificity)`.

> Which rule, if any, is the bug related to?

`no-descending-specificity`

> What CSS is needed to reproduce the bug?

```sass
.block {
  $r: &;

  &__element {
    color: white;

    #{$r}_modifier & {
      color: black;
    }
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard",
  ],
  "plugins": [
    "stylelint-order",
    "stylelint-scss"
  ],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/dollar-variable-empty-line-before": [
      "always",
      {
        "except": [
          "first-nested",
          "after-comment",
          "after-dollar-variable"
        ],
      }
    ],
    "scss/dollar-variable-colon-newline-after": "always-multi-line",
    "scss/dollar-variable-colon-space-after": "always-single-line",
    "scss/dollar-variable-colon-space-before": "never",
    "order/order": [
      "dollar-variables",
      "at-rules",
      "declarations",
      {
        "type": "at-rule",
        "name": "keyframes",
      },
      {
        "type": "at-rule",
        "name": "media",
      },
      "rules",
    ],
  }
}
```

> Which version of stylelint are you using?

`9.3.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin and [VSCode extension](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint)

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS selectors interpolation

> What did you expect to happen?

No error for this case.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
Expected selector "#{$r}_modifier .block__element" to come before selector ".block__element" (no-descending-specificity)
```

**Comment by jeddy3** [comment]
@in19farkt Thanks for the report and for using the template.

You'll be pleased to hear that this has [already been fixed](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#head) in `master` and will be in the next release.
