### ISSUE TITLE
Create IntelliJ IDEA editor plugin

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#346]
If we accumulate ***300$*** here,  then i will learn Java and SDK for creating plugins for IntelliJ IDEA, and i will write this plugin. Let's rock :smile: [Click here!](https://www.bountysource.com/issues/25758168-intellij-idea-editor-plugin?utm_campaign=plugin&utm_content=tracker%2F9282518&utm_medium=issues&utm_source=github)
---
Good news guys. In `2016.3` we have support `postcss`, perhaps this will help us :smile: 
---
To vote for the plugin please visit https://youtrack.jetbrains.com/issue/WEB-19737 and click `Vote` in right panel. Thanks to everyone for their help in the voting!

**Comment by jeddy3** [comment]
Hello @evilebottnawi. Is this something you can help with?

**Comment by evilebottnawi** [comment]
@jeddy3, soon I start writing a plugin if needed will return here Pomozov

**Comment by davidtheclark** [comment]
@evilebottnawi : With 2.0.0 we've introduced a CLI, Node API, and support for external JSON config files  --- so I think that should help a lot in creating an editor plugin. Let us know if there's anything else that would help!

**Comment by evilebottnawi** [comment]
@davidtheclark it is good, thanks

**Comment by jeddy3** [comment]
@davidtheclark Shall we nuke this issue? If someone has the need to build it, it'll happen outside this repo.

**Comment by evilebottnawi** [comment]
@jeddy3 this issue for information and docs, in the near future I'm going to start writing a plugin, if somebody is willing to help in this I will be happy

**Comment by davidtheclark** [comment]
I'm ok keeping it open as an ecosystem issue while @evilebottnawi has plans to work on it.

**Comment by jeddy3** [comment]
Ok with me :)

> if somebody is willing to help in this I will be happy

There are [3 existing](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#editor-plugins) editor plugins you could use for inspiration. Am I right in thinking that an _IntelliJ IDEA plugin_ is written in Java? I've not written much Java since my uni days, and so can't directly help you out with it. Good luck though :)

**Comment by evilebottnawi** [comment]
@jeddy3 Yes, it is Java :(

**Comment by evilebottnawi** [comment]
https://youtrack.jetbrains.com/issue/WEB-19737
All those interested please vote (right side `Votes` click). This is speed up the development.

**Comment by evilebottnawi** [comment]
Manual before plugin not created.
There can be used with the error output to the IDE console.
1. Install stylelint globally (`npm -g install stylelint`).
1. Install plugin `File Watchers` from plugins repository.
2. After install restart IntelliJ IDEA.
3. Go to `File - Settings - Tools - File Watchers`.
4. Click `Add` (`+`). And select `CSSO CSS Optimizer` (for `.css`) or SCSS (for `.scss`)
5. Set up `Name:` to `Stylelint`. Set `Immediate file synchronization` (if need run immediate after change) and `Show console` to `Error`. Set `Program:` to `/usr/bin/stylelint` (path maybe other, depending on your npm settings). Set `Arguments:` to `$FilePath$ --config $ProjectFileDir$/.stylelintrc`, if need scss add argument `-s scss`. Set `Working directory:` to `$ProjectFileDir$`.
6. Click `OK` and `OK`
7. Change your `.css` or `.scss` file.
8. Profit! You look error in IDE console.

**Comment by deepfriedmind** [comment]
@evilebottnawi Just wanted to let you know that a JetBrains plugin for stylelint would be greatly appreciated. :+1: I use PhpStorm personally, but I guess the plugin architecture is universal for all their IDE's?

Also, I've tried adding a File Watcher like you explained but it refuses to run on any other file than my "root" .scss file, even though I have `Track only root files` unchecked. I.e. it activates properly when I make changes to any .scss file in the project, but in the console output I see that only the path of the root file is passed to the stylelint CLI. Very strange.

**Comment by evilebottnawi** [comment]
@deepfriedmind almost all plugins are universal. With `scss` and watcher strange behavior appears. In older versions works fine, in new versions they have changed the processing logic and the decision to  unfortunately not work. You can configure stylelint as external tools, but it is extremely convenient. We need plugins, but i don't know java and their sdk.

**Comment by evilebottnawi** [comment]
@deepfriedmind we can only vote and hopes :(

**Comment by deepfriedmind** [comment]
For anyone confused on how to vote up the issue (at https://youtrack.jetbrains.com/issue/WEB-19737), you need to be logged in with your JetBrains account and the voting symbol will appear under the info table to the right.

**Comment by evilebottnawi** [comment]
@deepfriedmind Probably to try to go to the channels in gitter about java and ask for help.

**Comment by cbrwizard** [comment]
I would love to have it too

**Comment by davidtheclark** [comment]
@evilebottnawi Is there any reason to leave this issue open? Or is it entirely in the hands of JetBrains?

**Comment by evilebottnawi** [comment]
@davidtheclark New users can start creating related issues. I think we can close, after we get the plugin, as there are references to vote for implementation.

**Comment by dan-gamble** [comment]
https://blog.jetbrains.com/webstorm/2016/09/webstorm-2016-3-eap-163-4830-stylelint-usages-for-default-exports-and-more/

Thank you can mark this as closed now :)

**Comment by evilebottnawi** [comment]
@dan-gamble waiting for release, because it is EAP, they can do anything (example delete this feature :smile: )

**Comment by dan-gamble** [comment]
That's a fair point, just got a bit giddy they finally release PyCharm EAP so i can utilise it :D

**Comment by ntwb** [comment]
Also https://github.com/Jardinero/stylelint-plugin

**Comment by evilebottnawi** [comment]
@ntwb awesome, wait some times to release and close this issue :smile:

**Comment by davidtheclark** [comment]
https://github.com/Jardinero/stylelint-plugin already exists, so I'll close this.

**Comment by niutech** [comment]
Stylelint plugin is now in the [Jetbrains Plugin Repository](https://plugins.jetbrains.com/plugin/9276)!

**Comment by danez** [comment]
Stylelint is also natively supported now in version 2016.3 without any additional plugin.

**Comment by niutech** [comment]
Yes, but only for CSS files, not SCSS or LESS. That plugin works for
all of these.

**Comment by danez** [comment]
Works also fine for scss files here.

**Comment by folmert** [comment]
Not in PhpStorm. For me it [throws an error](https://github.com/Jardinero/stylelint-plugin/issues/4) and I can see highlighted errors only in CSS files.

**Comment by evilebottnawi** [comment]
@folmert in new versions `IntelliJ Idea`(`2016.3`) `stylelint` build-in IDE, i think also this present in `WebStorm` new version, `PhpStorm` based on `WebStorm` and also should have build-in `stylelint`.

**Comment by folmert** [comment]
A lot of things "should" work the same way in WebStorm as in PhpStorm, but I've learned the hard way that it's just a theory ;) especially when it comes down to custom plugins.

**Comment by evilebottnawi** [comment]
@folmert you can use `IntelliJ Idea` and install `php` plugin, there is usually everything works and quickly fixed

**Comment by emileber** [comment]
It should be made clear that Intellij natively supports Stylelint in the [Editor plugins section](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#editor-plugins) of the doc.
