### ISSUE TITLE
Use spec and common spelling of “ID” (not “id”)

### ISSUE THREAD

**Issue by j9t** [stylelint/stylelint#3476]
When referring to unique identifiers, the stylelint docs speak of “ids”, not “IDs”. While this seems like a minor thing, both related specs (like [CSS](https://www.w3.org/TR/CSS22/selector.html#id-selectors)) and the common spelling of the term (cf. [Wikipedia’s entry on identifiers](https://en.wikipedia.org/wiki/Identifier)) suggest the spelling “ID”—strongly so, in my view.

I’d be happy to update the docs if it sounds reasonable to use the same spelling as both specs and common writing.

**Comment by jeddy3** [comment]
> I’d be happy to update the docs if it sounds reasonable

It does sound reasonable. Thank you, any help polishing the docs into shape is appreciated :)

**Comment by j9t** [comment]
:) I won’t get to it right now but will take care of it.

**Comment by j9t** [comment]
Submitted PR https://github.com/stylelint/stylelint/pull/3486.
