### ISSUE TITLE
Bump postcss syntaxes packages

### ISSUE THREAD

**Issue by kaisermann** [stylelint/stylelint#3482]
> What is the problem you're trying to solve?

There are some really useful changes in `postcss-syntax`, `postcss-html`, etc which provide a better support for linting styles in most template languages)

> What solution would you like to see?

Update the `postcss-syntax`, `postcss-html`, `postcss-markdown` from `0.28.0` to `0.31.0` (latest version). 

(all tests continue to pass)

![image](https://user-images.githubusercontent.com/12702016/42949444-29b52d86-8b48-11e8-9107-abf564d3a842.png)

**Comment by evilebottnawi** [comment]
@kaisermann PR welcome :+1:

**Comment by jeddy3** [comment]
@kaisermann Thanks for the request and using the template. This is already being worked on in https://github.com/stylelint/stylelint/pull/3405 as part of https://github.com/stylelint/stylelint/issues/3264.

The PR is very close to being merged. We're just waiting on @gucong3000 to shift a few tests around.
