### ISSUE TITLE
Selector Requires ID

### ISSUE THREAD

**Issue by northernseagull** [stylelint/stylelint#3519]
Either a new rule or an option/update to 'selector-id-pattern' to ensure that selectors have an id. This is to allow instances where css wants to enforce an id being used.

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using the template.
