### ISSUE TITLE
Add unix-style formatter

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#3522]
> What is the problem you're trying to solve?

For some unix tools (e.g. Emacs), I think that unix-style formatter is very useful, which is similar to [ESLint's unix formatter](https://eslint.org/docs/user-guide/formatters/#unix).

See also:
- https://github.com/eslint/eslint/issues/2991
- https://github.com/eslint/eslint/blob/137140f737d720fa93a4ac06ce79a86b523327f7/lib/formatters/unix.js#L1

> What solution would you like to see?

e.g. 

```
$ stylelint --formatter=unix foo.css
/Users/ybiquitous/foo.css:1:26: Unexpected empty block (block-no-empty) [error]

1 problem
```

```
$ stylelint --formatter=unix bar.css
/Users/ybiquitous/bar.css:1:26: Unexpected empty block (block-no-empty) [error]
/Users/ybiquitous/bar.css:10:26: Unexpected empty block (block-no-empty) [error]

2 problems
```

**Comment by jeddy3** [comment]
@ybiquitous Thanks for the request. Is this different from the `compact` formatter?

(Thanks for the fix in https://github.com/stylelint/stylelint/pull/3521 btw!).

**Comment by ybiquitous** [comment]
> Is this different from the compact formatter?

Yes. The format `FILE:LINE:COLUM: MESSAGE` such as `/Users/ybiquitous/bar.css:1:26: message...` makes `grep` easier!

FYI, ESLint also offers both [`compact`](https://eslint.org/docs/user-guide/formatters/#compact) and [`unix`](https://eslint.org/docs/user-guide/formatters/#unix) formatters.

**Comment by ybiquitous** [comment]
Now I try writing code, so I can open new pull request soon when you allow this issue. 💪

**Comment by jeddy3** [comment]
> FYI, ESLint also offers both compact and unix formatters.

Good to know. I don't think they'll be any opposition to adding this formatter then.

> so I can open new pull request soon

Fantastic. Please do.

**Comment by ybiquitous** [comment]
Thanks! I will open a new pull request within a few days. 👍
