### ISSUE TITLE
`selector-combinator-space-after always` and `selector-list-comma-space-before always`  could colide

### ISSUE THREAD

**Issue by mbehzad** [stylelint/stylelint#3525]
> Clearly describe the bug

Using `selector-combinator-space-after always` and `selector-list-comma-space-before always` rule together would lead to nonfixable lint issue.
either the missing space (after the combinator) will trigger an error. or the present of the space (before the comma) will trigger another error.

> Which rule, if any, is the bug related to?

`selector-combinator-space-after` && `selector-list-comma-space-before`

> What CSS is needed to reproduce the bug?

```scss
.foo ~,
.bar ~ {
  .bam {
    width: 100%;
  }
}
```
or add space after the `,` on the first line. which will still have the error (the other one)
```scss
.foo ~ ,
.bar ~ {
  .bam {
    width: 100%;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "selector-combinator-space-after": "always",
    "selector-list-comma-space-before": "never",
  }
}
```

> Which version of stylelint are you using?

`9.4.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

e.g. "CLI with `stylelint "**/*.css" --config myconfig.json`"
can also be reproduced on the [https://stylelint.io/demo/](https://stylelint.io/demo/)

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"Yes, it's related to SCSS nested properties."

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

` error Expected single space after "~`

Thank you very much

**Comment by jeddy3** [comment]
@mbehzad Thanks for the report and using the template.

As the built-in rules focus on (up-to editor draft) standard syntax, I think it's unlikely these rules will be adapted to deal with this use case. However, I think you have two options:

1. Write your nested CSS inline with the editor's draft e.g.

```css
.foo,
.bar {
  & ~ .bam {
    width: 100%;
  }
}
```

(which is, arguably, more readable too)

2. If you wish to continue with the idiosyncratic style, you can create [plugin versions](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) of the two rules and adapt them to cope with this use case. The plugin system was designed for this type of use case in mind.

**Comment by evilebottnawi** [comment]
@jeddy3 it should be easy to fix in `selector-combinator-space-after`

**Comment by jeddy3** [comment]
> it should be easy to fix in selector-combinator-space-after

Can it be done in a way that doesn't add code specific to this non-standard construct e.g. via a generic option?

**Comment by evilebottnawi** [comment]
@jeddy3 yep

**Comment by jeddy3** [comment]
@evilebottnawi  How's about an `exceptNextChars: []` secondary option on `selector-combinator-space-after`? e.g.

```js
{
  "rules": {
     "selector-combinator-space-after": ["always", { "exceptNextChars": [","] }]
  }
}
```

This would invert the primary option if they next char is one of the chars in the array.

**Comment by jeddy3** [comment]
Triage... 

Closing as the following is the more idiomatic way of writing this code:

```
.foo,
.bar {
  & ~ .bam {
    width: 100%;
  }
}
```
