### ISSUE TITLE
Add autofix to declaration-block-semicolon-newline-after

### ISSUE THREAD

**Issue by ota-meshi** [stylelint/stylelint#3544]
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [declaration-block-semicolon-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-semicolon-newline-after)

**Comment by ota-meshi** [comment]
@jeddy3  Thank you for the information!
I did not know about the status. I will manage the status from the next task.

**Comment by jeddy3** [comment]
> Thank you for the information!

No worries :)

As you have the most experience with adding autofix to these stylistic rules, feel free to use your judgement and add an additional `good first issue` label to any of the issues you think could be tackled by a new contributor i.e. ones that you think are relatively simple or don't require much knowledge of stylelint itself.
