### ISSUE TITLE
Add autofix to declaration-block-semicolon-space-after

### ISSUE THREAD

**Issue by ota-meshi** [stylelint/stylelint#3553]
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [declaration-block-semicolon-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-semicolon-space-after)

**Comment by noamyogev84** [comment]
Hi @ota-meshi . this sounds fun. Can you share some code pointers?

**Comment by jeddy3** [comment]
> Can you share some code pointers?

@noamyogev84 Here's a PR, https://github.com/stylelint/stylelint/pull/3554/, for the very similar `declaration-block-semicolon-space-before` rule.

Good luck!

**Comment by noamyogev84** [comment]
Thanks @jeddy3
