### ISSUE TITLE
add ignore: ["after-comment"] for "at-rule-empty-line-before"

### ISSUE THREAD

**Issue by onigoetz** [stylelint/stylelint#357]
Hi,
I'm starting to use stylelint on a few projects, and spotted a few things that might be improved, I will create one issue per rule.

If I find some time, I will try to create a few pull requests, but I can't guarantee anything.

Now to my request, the rules `rule-nested-empty-line-before` and `rule-non-nested-empty-line-before` both have a `ignore: ["after-comment"]` option.

Can we add the same option for `at-rule-empty-line-before` ?

Thanks in advance, keep up the good work :D

**Comment by jeddy3** [comment]
Hi there.

> I'm starting to use stylelint on a few projects

Good stuff. Give us a holler if you've any questions about anything :)

> Can we add the same option for at-rule-empty-line-before ?

Yeap, that makes sense. It's a quick enhancement and something I should be able to look into this evening.

**Comment by davidtheclark** [comment]
I think you already solved this, @jeddy3, for https://github.com/stylelint/stylelint/issues/350

**Comment by davidtheclark** [comment]
https://github.com/stylelint/stylelint/commit/d132c0a15a11a692fb2694b19656a4df4895aba6

**Comment by davidtheclark** [comment]
Looks like we didn't release it, though. Now's our big chance.

**Comment by jeddy3** [comment]
> I think you already solved this, @jeddy3, for #350

Ha, oops :)

> Now's our big chance.

I've merged in your `indentation` PR. Do you want to cut the release?

**Comment by jeddy3** [comment]
@davidtheclark I've updated the changelog.

**Comment by jeddy3** [comment]
Released :)

@onigoetz Your three issues are addressed in `0.8.0`.

**Comment by onigoetz** [comment]
Wow, this was quick :D thanks a lot guys !
