### ISSUE TITLE
Rule 'no-empty-source' fails on 'null' and doesn't accept 'false'

### ISSUE THREAD

**Issue by PMK** [stylelint/stylelint#3587]
I want to use stylelint to lint inside Vue files. When adding Vue files to be linted, I get this error:

```
src/layouts/default.vue
 12:24  ✖  Missed semicolon   CssSyntaxError
```

I need to install processor [@mapbox/stylelint-processor-arbitrary-tags](https://github.com/mapbox/stylelint-processor-arbitrary-tags) (because stylelint-preprocessor-html is deprecated). And when using this, their readme says to disable the rule [no-empty-source](https://stylelint.io/user-guide/rules/no-empty-source/).

I am extending [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) in my config, and I must overwrite the rule `no-empty-source` to turn it off.

When setting `'no-empty-source': null` in the config, stylelint will return no exit code and all linting will succeed (but it should fail when there are lint-errors).
When setting `'no-empty-source': false` in the config, stylelint returns an error: `Invalid Option: Unexpected option value "false" for rule "no-empty-source"`.

I expect to use `false` if the input is of type Boolean, or using `null` to reset to the default. To set to false or null, I can use the processor to use stylelint in style tags in Vue files.

Configuration file:

```js
module.exports = {
  processors: ['@mapbox/stylelint-processor-arbitrary-tags'],
  extends: ['stylelint-config-standard'],
  rules: {
    'no-empty-source': null
  }
}
```

Stylelint version: `9.5.0`, is also not working in `9.4.0`

CLI: `$ ./node_modules/.bin/stylelint --config ./config/stylelint.config.js --syntax scss ./src/{assets/styles/{,*/}*.scss,**/*.vue}`

To test this, make sure to let your example code fail when using the 'stylelint-config-recommended' rules, then update your configuration to enable the processor and add the rule 'no-empty-source'.

**Comment by jeddy3** [comment]
> I need to install processor @mapbox/stylelint-processor-arbitrary-tags (because stylelint-preprocessor-html is deprecated).

stylelint has built-in support for extracting styles from `.vue` files. You shouldn't need to use a processor.

Can you share the contents of your `src/layouts/default.vue` file with us so we can help determine where the syntax error is occuring?

**Comment by PMK** [comment]
I'm using Nuxt as the framework and Nuxt uses Vue. The declaration of a Vue instance is not needed.

Please see this repo: https://github.com/PMK/stylelint-bug-3587
And update `config/stylelint.config.js` to see the effect.

**Comment by ota-meshi** [comment]
It may work if you remove `--syntax scss`.

**Comment by jeddy3** [comment]
> It may work if you remove --syntax scss.

Good suggestion. The `--syntax` flag forces the syntax to be SCSS, whereas you'll want to rely on the built-in switcher to select the most appropriate parser _for each file type_ e.g. the Scss parser for `*.scss` files and HTML parser for `*.vue` files.

@PMK Can you try that?

**Comment by PMK** [comment]
I don't see any change with or without using `--syntax scss`. I am using the first example in the config. All other examples in the config have the same effect.

If I split these tasks the same stuff happens too:
```
"lint:scss": "./node_modules/.bin/stylelint --config ./config/stylelint.config.js --syntax scss ./src/assets/styles/{,*/}*.scss",
"lint:style-in-vue": "./node_modules/.bin/stylelint --config ./config/stylelint.config.js ./src/{pages,layouts}/*.vue",
"lint": "npm run lint:scss && npm run lint:style-in-vue"
```

Console:

```
$ npm run lint

> stylelint-test@1.0.0 lint ./
> npm run lint:scss && npm run lint:style-in-vue


> stylelint-test@1.0.0 lint:scss ./
> stylelint --config ./config/stylelint.config.js --syntax scss ./src/assets/styles/{,*/}*.scss


> stylelint-test@1.0.0 lint:style-in-vue ./
> stylelint --config ./config/stylelint.config.js ./src/{pages,layouts}/*.vue

$
```

So I think the issue is not per se the scss files with the vue files. It seems more the effect of the setting in the config, right?

**Comment by ota-meshi** [comment]
I think your setting is working properly. Nothing is output to the console because I think that your CSS has no lint error.

**Comment by PMK** [comment]
@ota-meshi You're totally right. This was very confusing me... Actually, now if I add the `--syntax scss` again, it gives different results. So to solve it, I need to remove the `--syntax scss`.

Thanks for the help all!

**Comment by jeddy3** [comment]
> This was very confusing me... So to solve it, I need to remove the --syntax scss and removing processor stylelint-processor-arbitrary-tags.

I've been [working on a PR](https://github.com/stylelint/stylelint/pull/3591) to deemphasize processors and the `--syntax` option in the docs. This will hopefully make it less confusing for other users.

stylelint can now automatically:

- infer the syntax in lots of cases
- extract styles from lots of places

As such, I've deemphasized processors and the `--syntax` option in the docs as their use is more of an edge case than the norm now. 

> Thanks for the help all!

@PMK I'm glad you were able to resolve the issue :)
