### ISSUE TITLE
Add autofix to max-empty-lines

### ISSUE THREAD

**Issue by ota-meshi** [stylelint/stylelint#3612]
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [max-empty-lines](https://github.com/stylelint/stylelint/tree/master/lib/rules/max-empty-lines)

**Comment by EliazTray** [comment]
WIP

**Comment by ota-meshi** [comment]
I’m looking forward to PR!

**Comment by EliazTray** [comment]
When i run  scripts “ npm run watch” for “max-empty-lines”

There is a case which i think it could be correct, but it reports error. i think i need a help.

when i debug , in last step,  i find [this](https://github.com/stylelint/stylelint/blob/master/jest-setup.js#L130) will return a warning caused by  [no absoluteFileName](https://github.com/stylelint/stylelint/blob/master/lib/standalone.js#L112).

**Comment by ota-meshi** [comment]
Are you asking why following error happens?

```diff
 FAILlib/rules/max-empty-lines/__tests__/index.js
●max-empty-lines › reject › [1] › "<div>\n<style>\n/* horse */\n\n\n</style>\n</div>" › no description
expect(received).toEqual(expected)
    Expected value to equal:
[]
    Received:
[{"column": 1, "line": 5, "rule": "max-empty-lines", "severity": "error", "text": "Expected no more than 1 empty line (max-empty-lines)"}]
    Difference:
- Expected
+ Received
- Array []
+ Array [
+   Object {
+     "column": 1
+     "line": 5
+     "rule": "max-empty-lines"
+     "severity": "error"
+     "text": "Expected no more than 1 empty line (max-empty-lines)"
+   }
+ ]
 128 |                    })
 129 |.then(({ output warnings })=> {
> 130 |                      expect(output.results[0].warnings).toEqual(warnings);
     |^
 131 |                      expect(output.results[0].parseErrors).toEqual([]);
 132 |                    });
 133 |                });
```

If so,
[This test case](https://github.com/stylelint/stylelint/blob/master/jest-setup.js#L130) checks that no errors remain in the fixed CSS.

Looking at [this](https://github.com/stylelint/stylelint/blob/6084f30ae8d23d57167a2a714042308a7aaded8d/lib/rules/max-empty-lines/__tests__/index.js#L159), perhaps, I think that `</style>` is judged to be eof and an error has been reported.

```html
<div>
<style>
/* horse */

</style>
</div>
```

**Comment by EliazTray** [comment]
@ota-meshi 

In this case, I think the following should be correct.

```html
<div>
<style>
/* horse */

</style>
</div>
```

But in [test](https://github.com/stylelint/stylelint/blob/6084f30ae8d23d57167a2a714042308a7aaded8d/lib/rules/max-empty-lines/__tests__/index.js#L138), i add the new empty line, it reports error. Is this expected behavior?
I'm comfused .

```js

// max-empty-lines/__tests__/index.js

···

testRule(rule, {
  ruleName,
  config: [1],
  syntax: "html",

  accept: [
    {
      code: `<div>




<style>
/* horse */

</style>



</div>`
    }
  ],
);
```

**Comment by ota-meshi** [comment]
@EliazTray 
> In this case, I think the following should be correct.

I think so, too.

This is a different issue from autofix, so I would like you to open up a new issue.

**Comment by mpelzsherman** [comment]
How is this coming along?

**Comment by lfender6445** [comment]
For anyone wondering how they might script something like this with the command line, you could do 

```bash
sed -i '' '/^$/{N;/^\n$/d;}' src/ui/theme/large/components/_someStyle.scss
```
