### ISSUE TITLE
Add support for stylelintIgnore package.json property

### ISSUE THREAD

**Issue by theahmadzai** [stylelint/stylelint#3627]
> What is the problem you're trying to solve?

To be consistent stylelint must recognize ignored files from Package.json like eslint does,  it prevents file pollution in a project, adding a file for ignoring one directory doesn't seem good to me, it is a good idea to keep both eslint and stylelint ignored file patterns and browser list supports in package.json so can be changed easily when wanted.

> What solution would you like to see?

I forked the repository but I'm having a little bit hard time to make changes and test code but I'm sure this might work in `isPathIgnored` file.

```js
const ignoreFiles = require(path.resolve(process.cwd(),'package.json'));
  if(ignoreFiles.hasOwnProperty('stylelintignore')) {
    filePath = ignoreFiles.stylelintignore;
  }
```

In Package.json
```json
"stylelintIgnore: [
  "file1",
  "file2"
]
```

Thank you

**Comment by jeddy3** [comment]
@theahmadzai Thanks for the request.

For those interested, the relevant documentation for this feature in ESLint is [here](https://eslint.org/docs/user-guide/configuring#using-eslintignore-in-packagejson).

@theahmadzai Feel free to contribute this feature.

**Comment by jasalt** [comment]
I was looking for this feature and found this open issue, however according to https://stylelint.io/user-guide/ignore-code/ you can add an `ignoreFiles` property within your configuration object, which in case of `package.json` looks like this and which works:

```
  "stylelint": { 
    "extends": "@wordpress/stylelint-config/scss",
    "ignoreFiles": ["testing.css", "build/"]
  },
```

Is this issue relevant anymore at this point, or did I get something wrong?

**Comment by jeddy3** [comment]
Thanks for pointing that out. Closing.
