### ISSUE TITLE
Unknown word  CssSyntaxError Vue

### ISSUE THREAD

**Issue by stavros-liaskos** [stylelint/stylelint#3633]
> Clearly describe the bug

Stylelint throws "Unknown word  CssSyntaxError" in valid .vue files

> Which rule, if any, is the bug related to?

Any, as long as there is more than one. Tested with  
 `"no-empty-source": null` and/or   
`  "extends": "stylelint-config-standard",
`

> What CSS is needed to reproduce the bug?

Start a new project with vue-cli v3 and make sure you enable SCSS:
```bash
vue create vue-bug
cd vue-bug/
```
Default `HelloWorld.vue` throws the error above:

```css
<style scoped lang="scss">
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "plugins": [
    "stylelint-scss"
  ],
  "extends": "stylelint-config-standard",
  "rules": {
    "no-empty-source": null
  }
}

```

> Which version of stylelint are you using?

```json

    "stylelint": "^9.5.0",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-scss": "^3.3.0",
    "stylelint-webpack-plugin": "^0.10.5",
```

> How are you running stylelint: CLI, PostCSS plugin, Node API?

From `package.json`:
```bash
    "lint:css": "stylelint '**/*.vue' --syntax scss"
or
    "lint:css": "stylelint --fix '**/*.vue' --syntax scss"

```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

The error persists with both `<style scoped>` and `<style scoped lang="scss">`. Styles are in standard syntax

> What did you expect to happen?

Actual stylelint errors emerge. Note that in the editor (PhpStorm with Stylelint enabled), the correct errors are shown (rule-empty-line-before x3) 

> What actually happened (e.g. what warnings or errors did you get)?

Unknown word  CssSyntaxError

```shell
src/components/HelloWorld.vue
 3:12  ✖  Unknown word   CssSyntaxError
```

I was using the config from #3049 because of the mangling files issue and then this happened.

**Comment by ota-meshi** [comment]
Hello.
I think that removing `--syntax scss` works well.

https://github.com/stylelint/stylelint/issues/3587#issuecomment-414625015

**Comment by stavros-liaskos** [comment]
@ota-meshi True. It's working. Thanks

**Comment by Liujiang-keep** [comment]
hh

**Comment by heyakyra** [comment]
Commenting here to help anyone coming from search engines. I hit this in a stupid way for an unrelated plugin (`unplugin-vue`) which is that VSCode was inserting `// …` for CSS/SCSS/SASS comments in SFC files instead of `/* … */` which I only discovered due to adding more unwittingly-invalid "comments" and seeing the number of errors keep rising.
