### ISSUE TITLE
Add autofix to function-name-case

### ISSUE THREAD

**Issue by ota-meshi** [stylelint/stylelint#3658]
> What is the problem you're trying to solve?

Adds autofix of rules [defined in `stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) so that everyone can start using [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) easily.

> What solution would you like to see?

Add autofix to [function-name-case](https://github.com/stylelint/stylelint/tree/master/lib/rules/function-name-case)

**Comment by bcowgill** [comment]
I think I've found a bug in this.  

With .stylelintrc function-name-case: lower

If you have a /* stylelint-disable-next-line function-name-case */
or /* stylelint-disable function-name-case */
present before an uppercase function name

Then running stylelint correctly ignores that uppercase function
but stylelint --fix . incorrectly converts that uppercase function to lower case.

**Comment by evilebottnawi** [comment]
@bcowgill please create new issue
