### ISSUE TITLE
[stylelint] Unknown word (CssSyntaxError) with .scss variables

### ISSUE THREAD

**Issue by BiosBoy** [stylelint/stylelint#3669]
> Clearly describe the bug

I'm using the stylelint package to lint my .scss files, but for some reason it does not work with the variables in it. So, even when I try to use my $cs vatiable in animation anim effect - I gets an error - [stylelint] Unknown word (CssSyntaxError)

> Which rule, if any, is the bug related to?

Do not know. Probably - `CssSyntaxError`

> What CSS is needed to reproduce the bug?
```
@mixin addRowAnimation($color) {
  $cs: str-slice(inspect($color), 2);
  animation: fadeIn-#{$cs} 3s cubic-bezier(0.55, 0.055, 0.675, 0.19);
} 

// in "fadeIn-#{$cs}" part -> $cs - [stylelint] Unknown word (CssSyntaxError)
```

> What stylelint configuration is needed to reproduce the bug?

```
{
    "extends": "stylelint-config-standard",
    "plugins": [
        "stylelint-no-unsupported-browser-features",
        "stylelint-order"
    ],
    "ignoreFiles": ["**/*.js"],
    "rules": {
        "declaration-block-no-redundant-longhand-properties": [
          true,
          {
            "ignoreShorthands": ["flex-flow"]
          }
        ],
       .........
       .....
```

Gist:
https://gist.github.com/BiosBoy/1d7ba251f0c2e054b2e950bd6473d156

> Which version of stylelint are you using?

"stylelint": "^9.4.0"

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"stylelint --fix --formatter=verbose" from CLI via yarn

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS nested properties.

> What did you expect to happen?

No warnings to be flagged.

**Comment by evilebottnawi** [comment]
@BiosBoy please provide full stack error

**Comment by BiosBoy** [comment]
@evilebottnawi 
 - what I gets in console -> ` 2:3   ✖  Cannot parse selector`
-  what I gets when puts my mouse on the highlighted part -> `[stylelint] Unknown word (CssSyntaxError)
`
There is no any huge stack error as you probably imagine about my case.

**Comment by BiosBoy** [comment]
There is a lot of other errors, if you what to know, but they probably do not related to this issue:
```
$success: #effdd6;
$error: #fff9db;
$warning: #fff9f7;

$successText: #85b200;
$errorText: #fab005;
$warningText: #ff3f00;

@mixin addAnimation($color) {
  $cs: str-slice(inspect($color), 2);
  animation: fadeIn-#{$cs} 3s cubic-bezier(0.55, 0.055, 0.675, 0.19);
}
```

Stack trace:
```
  2:1   ✖  Expected $ variable name to match specified patte
rn
                                scss/dollar-variable-pattern

  3:1   ✖  Expected $ variable name to match specified pattern                                scss/dollar-variable-pattern
  4:1   ✖  Expected $ variable name to match specified pattern                                scss/dollar-variable-pattern
  6:1   ✖  Expected $ variable name to match specified pattern                                scss/dollar-variable-pattern
  7:1   ✖  Expected $ variable name to match specified pattern                                scss/dollar-variable-pattern
  8:1   ✖  Expected $ variable name to match specified pattern                                scss/dollar-variable-pattern
 10:1   ✖  Expected @mixin name to match specified pattern                                scss/at-mixin-pattern
 12:3   ✖  Cannot parse selector                                parseError
```

**Comment by evilebottnawi** [comment]
Maybe problem in `stylint-scs`. Can you disable disable plugin and test again?

**Comment by BiosBoy** [comment]
Still a lot of same errors: 
```
 10:1   ✖  Unexpected unknown at-rule "@mixin"   at-rule-no-unknown
 12:3   ✖  Cannot parse selector     parseError
 12:3   ✖  Cannot parse selector     parseError
 12:3   ✖  Cannot parse selector     parseError
 12:3   ✖  Cannot parse selector     parseError
```

Also I added my `.stylelint` config to the issue post

**Comment by ota-meshi** [comment]
What is the extension of the file where the error is reported?

**Comment by BiosBoy** [comment]
@ota-meshi Hi,
I used the non-standart file extension for `scss` syntax files with css-module included - like `*.cssmodule`. So, I understand, my problem is located in file extension. Any solutions how to bring `stylelint` work normally with with non-standart file extensions?

**Comment by ota-meshi** [comment]
`--syntax scss` may be available, but other files may be affected.
but it may be worth a try.

https://stylelint.io/user-guide/css-processors/#parsing-non-standard-syntax

**Comment by BiosBoy** [comment]
@ota-meshi thank you. But is these some way to put this rule inside `.stylelintrc` config file, instead of cli usage?

**Comment by ota-meshi** [comment]
Sorry. I don't know that...

**Comment by jeddy3** [comment]
> But is these some way to put this rule inside .stylelintrc config file, instead of cli usage?

There isn't.

I think stylelint can automatically infer Scss syntax if you use the `module.scss` naming convention e.g. `button.module.scss`, otherwise you'll need to force the syntax with the `--syntax` CLI flag.
