### ISSUE TITLE
New rule:Disallow Trailing comma in Selectors list

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#3730]
> What is the problem you're trying to solve?

e.g. "The trailing comma in the selectors leads to a parse error and style in that block will not be applied"

> What solution would you like to see?

A new rule that prevents trailing comma in the selectors.
ex : 
span,{
color:red;
}
here this style won't apply to any span tag.

**Comment by jeddy3** [comment]
@ssivanatarajan Thanks for the suggestion.

See https://github.com/stylelint/stylelint/issues/3053#issuecomment-349561036

Feel free to create the `stylelint-selector-no-empty` plugin and share it with the community or use `csstree` in conjunction with stylelint to validate against the spec.

**Comment by ssivanatarajan** [comment]
@jeddy3 . created a new repository for stylelint-selector-no-empty rule. 
repo url:https://github.com/ssivanatarajan/stylelint-selector-no-empty. how to publish this stylelint plugin.
