### ISSUE TITLE
Add ignoreTypes: [] to selector-type-case

### ISSUE THREAD

**Issue by niksajanjic** [stylelint/stylelint#3739]
> What is the problem you're trying to solve?

It's a very rare use case and it might not be the most reasonable reason to add this option, but here it goes. I'm using mixins (which are not standard) and with them, I have the ability to apply custom properties as selectors, like this (I'm using SugarSS syntax):

```sss
@define-mixin focus $parentClass, $element
    $parentClass > $element
      color: red
```

This code works great, but I have a problem with `$parentClass` property, which is camel case. Therefore I get an error of `selector-type-case`.

I had to add `ignoreTypes: ['/\$\w*/']` to `selector-type-no-unknown` to make sure I prevent those errors so I would like to be able to apply same ignore logic here.

> What solution would you like to see?

I would like to add an ignore option as an array where you can pass regExp or string with selectors to ignore. It would be similar to `ignoreTypes` in `selector-type-no-unknown` rule.

Currently, I use comments to disable this eslint rule which is fine, but it would be easier to have ignore option. If this request sounds reasonable I could come up with some PR.

**Comment by jeddy3** [comment]
@niksajanjic Thanks for the suggestion and for using the template.

Even though your use case if for a non-standard language extension, I think a new option will be fine as these type of options rarely add much complexity. I agree with your suggestion of an `addTypes` option as it'll be consistent with the one in `selector-type-no-unknown`.

Feel free to [add the option](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule), you can probably pull most of the code and tests from the `selector-type-no-unknown`
