### ISSUE TITLE
Grouping Selectors with same set of properties and values

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#3740]
> What is the problem you're trying to solve?

"By grouping selectors with same properties and values we can reduce the files"

> What solution would you like to see?

 "A new rule that identifies the selectors which are having the same set of properties and values"
example: ``` .a{
color:red;
padding:10px;
}
.b{
padding:5px;
}
.c{
color:red;
padding:10px;
}```
here we can group ".a" and ".c" .

**Comment by jeddy3** [comment]
@ssivanatarajan Thanks for the suggestion.

I think this is an [ideal candidate for a plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#criteria-for-inclusion) as not all users will see the value in grouping sets together, some prefer to duplicate declarations and have one-rule-per-part approach e.g.

```
.Block {
  color: red;
  padding: 10px;
}

.Block-element {
  padding: 5px;
}

.Block-otherElement {
  color: red;
  padding: 10px;
}
```

And then rely on tools, like [cssnano](https://cssnano.co/), to handle any duplication in production.

**Comment by ssivanatarajan** [comment]
@jeddy3 ,Please verify [stylelint-group-selectors](https://github.com/ssivanatarajan/stylelint-group-selectors/blob/master/README.md).

**Comment by jeddy3** [comment]
I'm afraid I won't have time to review plugins. As long as it serves your purpose then you're all good.
