### ISSUE TITLE
Add ignore: ["next-sibling"] to selector-max-type

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#3757]
> What is the problem you're trying to solve?

Need Combinators as ignore option for "selector-max-type" rule.

> What solution would you like to see?

A new  option should ignore "Subsequent-sibling combinator " and "Next-sibling combinator"
 in "selector-max-type" rule.

The rule should ignore below css
``` #userSelVal + span{}```
``` #userSelVal > span{}```

**Comment by jeddy3** [comment]
@ssivanatarajan Thanks for the suggestion.

> #userSelVal + span{}

Yes, an `ignore: ["next-sibling"]` option will work here ([ref](https://www.w3.org/TR/selectors-4/#adjacent-sibling-combinators)).

Please consider contributing this option. There's [a section in the Developer Guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#adding-an-option-to-an-existing-rule) on how to get started.

> #userSelVal > span{}

You can use the exisiting [`ignore: ["child"]` secondary option](https://stylelint.io/user-guide/rules/selector-max-type/#child) for this.

If you also need an option for subsequent-sibling combinator (aka `~`), please create a separate issue.
