### ISSUE TITLE
Fix CssSyntaxError for functions in template literals

### ISSUE THREAD

**Issue by mbrowne** [stylelint/stylelint#3766]
Functions not preceded by property names inside template literals cause an "Unknown word" error in some cases, for example:

```js
const MyComponent = styled.div`
    margin-top: 10px;
    ${p => (p.showBottomBorder ? '' : 'border-bottom: 0;')};
`
```

> Unknown word   CssSyntaxError

Direct function calls cause the same error:

```js
const MyComponent = styled.div`
    margin-top: 10px;
    ${foo()};
`
```

A more realistic example: we have a function called `visibleScrollbarOnWebkit()` that includes multiple rules. So in those cases, refactoring to include a CSS property name before the function isn't a practical option.

> Which rule, if any, is the bug related to?

It's a general issue (not rule-specific) but it doesn't always happen. For example, if the function isn't the last rule and doesn't have a semicolon after it, it will work:

```css
  ${p => (p.showBottomBorder ? '' : 'border-bottom: 0;')}
  margin-top: 10px;
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

> Which version of stylelint are you using?

9.7.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

`yarn stylelint src`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

No errors

> What actually happened (e.g. what warnings or errors did you get)?

    Unknown word   CssSyntaxError

**Comment by jeddy3** [comment]
@mbrowne Thank you for the report and for the clear write-up.

This looks to be a bug in the `postcss-styled` parser. /cc @gucong3000

**Comment by pietrofxq** [comment]
I'm having the same issue; is there any updates?

![image](https://user-images.githubusercontent.com/6238029/48943768-9015a980-ef24-11e8-892a-f9a822142033.png)

**Comment by mbrowne** [comment]
@pietrofxq In the meantime you could use https://github.com/styled-components/stylelint-processor-styled-components. My team is still using it because of this issue (although we'd prefer to use stylelint directly so we can use autofixing).

BTW, the `css` helper isn't actually necessary in your example...you could just use a regular string or template literal there if you wanted.

**Comment by gucong3000** [comment]
If there is no objection, I will replace `postcss-styled` with `postcss-jsx`.
They have one two two differences:
- `postcss-jsx` depends on `Babel`, so it's **larger size**.
- `postcss-jsx` supports **both** object & template literals.

**Comment by gucong3000** [comment]
I'm going to fix this next week.

**Comment by jeddy3** [comment]
Fixed in https://github.com/stylelint/stylelint/pull/3869
