### ISSUE TITLE
CSS @apply Rule

### ISSUE THREAD

**Issue by JosefJezek** [stylelint/stylelint#378]
Please add CSS `@apply` Rule. We need for Polymer Theme.

- http://tabatkins.github.io/specs/css-apply-rule/
- https://github.com/StartPolymer/polymer-starter-kit-plus

**Comment by davidtheclark** [comment]
Is there some particular rule that does not understand `@apply` and is causing you trouble? I'm not sure what this feature request is right now.

**Comment by JosefJezek** [comment]
We need for Polymer projects

https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

**Comment by davidtheclark** [comment]
@JosefJezek : Sorry, but I guess I still don't understand what you're requesting. Can you please clarify?

**Comment by JosefJezek** [comment]
I am sorry, apply rule is ok.
