### ISSUE TITLE
Stylinter stopped working with stylelint-config-airbnb

### ISSUE THREAD

**Issue by ArtemBernatskyy** [stylelint/stylelint#3784]
> Clearly describe the bug

Stylinter not working with stylelint-config-airbnb

> Which rule, if any, is the bug related to?

stylelint-config-airbnb

> What CSS is needed to reproduce the bug?

`git clone https://github.com/ArtemBernatskyy/MuzicBox.git .`
`cd front_end && npm install (dep and devDep)`

> What stylelint configuration is needed to reproduce the bug?

https://github.com/ArtemBernatskyy/MuzicBox/blob/master/front_end/.stylelintrc

> Which version of stylelint are you using?

`9.7.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with ` cat src/components/song/song.css | /Users/artem/Desktop/MuzicBox/src/front_end/node_modules/.bin/stylelint --formatter json --stdin-filename /Users/artem/Desktop/MuzicBox/src/front_end/src/components/song/song.css
`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, pure CSS related bug

> What did you expect to happen?

Lots of warnings

> What actually happened (e.g. what warnings or errors did you get)?

No warnings at all

**Comment by hudochenkov** [comment]
If I understand correctly, you have problems in your code, and linter does its job to report them.

**Comment by ArtemBernatskyy** [comment]
I've intentionally made error in my code in order to test `stylelint-config-airbnb`.

So to summarize `stylelint-config-standard` shows errors
`stylelint-config-airbnb` doesn't show errors at all !

Thx !

**Comment by hudochenkov** [comment]
Please, update your issue using [issue template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md).

**Comment by hudochenkov** [comment]
First of all, I would advise you not to use this config. It's not an official one. It installs `ava` testing framework and `editorconfig-tools`. They should not be installed for a user. Looks very bad.

Also, it has very few rules enabled, you can see it if you go to your `node_modules/stylelint-config-airbnb/index.js`. I think, your code just doesn't violate according to that config.

I would suggest using [`stylelint-config-recommended`](https://github.com/stylelint/stylelint-config-recommended) or [`stylelint-config-standard`](https://github.com/stylelint/stylelint-config-standard) instead.

**Comment by ArtemBernatskyy** [comment]
Thx @hudochenkov
I was confused , i thought that `stylelint-config-airbnb` will be as good as `eslint-config-airbnb`. Now i understand that i was wrong )
