### ISSUE TITLE
boolean options: true/false vs always/never vs only true

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#38]
We have a mistmatch in how booleans are used for options in the drafts in #1.

Case #1:
color-hex-shorthand: bool
- true - hex colors must be shorthand
- false - hex colors must not be shorthand

Case #2:
color-no-named: bool Disallow named colors
- true: named colors must not be used for colors
- false: named colors can be used for colors

The key is that sometimes false = "must not" and sometimes false = "can".

I can think of a couple of possible ways to clarify this:

1. Make `false` always mean "must not" as in Case #1; so in Case #2 `false` just wouldn't be a possibility --- if the user wants to *not* disallow named colors the user should turn the rule off, not leave it on and pass false.

2. Use `always` and `never` instead of `true` and `false` in cases like Case #1. That would not clarify Case #2, though.

(This applies to the existing `declaration-no-important` as well as a bunch of other ones.)

**Comment by MoOx** [comment]
> if the user wants to not disallow named colors the user should turn the rule off, not leave it on and pass false.

Completely agree. We should document that.

> Use always and never instead of true and false in cases like Case #1. That would not clarify Case #2, though.

Yes !

**Comment by davidtheclark** [comment]
I think this one is tied up in the severity question, as well. For instance, ESLint doesn't have the ambiguity because every rule gets a 0-1-2 that designates whether it's "on" or "off". If we do the same, we'd never have to use true/false simply to determine whether a rule like `declaration-no-important` is on/off.

**Comment by jeddy3** [comment]
Yeap, I think you're right about that.

**Comment by davidtheclark** [comment]
Since we're in agreement on using 0-1-2 and "always"/"never", we're sort of nullifying this issue by avoiding booleans.
