### ISSUE TITLE
Rule for detecting unused selectors

### ISSUE THREAD

**Issue by avrelaun** [stylelint/stylelint#3805]
We have a large codebase at Beekast, including some global dedicated scss files but also scss style inside Vue components. After multiple refactors, the scss in components is sometimes left behind with dead style for removed selectors. 

> What solution would you like to see?

It would be awesome to have stylelint warn about style selectors that are not used anywhere.

**Comment by avrelaun** [comment]
Good question, in vue html template via the class attribute, in vue script I guess this is much harde since selector names can be generated via javascript.

**Comment by evilebottnawi** [comment]
@avrelaun sounds good for plugin, not core rule

**Comment by jeddy3** [comment]
@avrelaun Yep, this would make a great [plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md). It could even be a simple plugin that wraps an existing tool like [uncss](https://github.com/uncss/uncss). [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features) is a great example of an existing plugin that does with (with the doiuse tool).
