### ISSUE TITLE
Add JSDoc comments to utilities

### ISSUE THREAD

**Issue by vankop** [stylelint/stylelint#3836]
> What is the problem you're trying to solve?

Add documentation to `~/lib/roles/*.js`. It will help contributors to understand how write rules better.

> What solution would you like to see?

It looks like there is already `flow` in `~/utils/*.js` so we can support it as well or just use `esdocs`.

**Comment by vankop** [comment]
@yepninja

**Comment by jeddy3** [comment]
I think there's definitely scope to improve the comments within the utilities to help contributors. there are some good comments, for example with the [`validateOptions` util](https://github.com/stylelint/stylelint/blob/master/lib/utils/validateOptions.js#L8-L27) that we use as exemplars. A lot of other utils lack these JSDoc comments.

**Comment by hudochenkov** [comment]
As part of migration to TypeScript we added JSDoc with parameters and return values to every util. Does this mean we can close this issue?

**Comment by vankop** [comment]
I think yes
