### ISSUE TITLE
function-name-case rule does not work correctly with --fix

### ISSUE THREAD

**Issue by bcowgill** [stylelint/stylelint#3837]
With .stylelintrc function-name-case: lower

If you have a /* stylelint-disable-next-line function-name-case */
or /* stylelint-disable function-name-case */
present before an uppercase function name

Then running stylelint correctly ignores that uppercase function
but stylelint --fix . incorrectly converts that uppercase function to lower case.

stylelint --version
9.9.0

_Originally posted by @bcowgill in https://github.com/stylelint/stylelint/issue_comments#issuecomment-444119466_

**Comment by evilebottnawi** [comment]
@bcowgill please use issue template

**Comment by hudochenkov** [comment]
Unfortunately, it works as intended. From [docs](https://stylelint.io/user-guide/cli/#autofixing-errors):

> **Note:** It's an _experimental_ feature. It currently does not respect special comments for disabling stylelint within sources (e. g. `/* stylelint-disable */`). Autofixing will be applied regardless of these comments.
