### ISSUE TITLE
Disallow "transition: all"

### ISSUE THREAD

**Issue by zlepper** [stylelint/stylelint#3838]
> What is the problem you're trying to solve?

Designers on my team likes to use "transition: all", when they just want one property to animate, which has a tendency to cause some odd, and probably unwanted transitions. 

> What solution would you like to see?
A new rule that disallows "transition: all"

This should watch out for both the shorthand transition, and `transition-property: all`

**Comment by jeddy3** [comment]
@zlepper Thanks for the suggestion and for using the template.

You can use the [`declaration-property-value-blacklist`](https://github.com/stylelint/stylelint/blob/master/lib/rules/declaration-property-value-blacklist/README.md) rule to achieve this.

As per the [VISION](https://github.com/stylelint/stylelint/blob/master/VISION.md#limit-language-features):

> **Limit language features**
> Provide rules to limit what language features can be used, including:
> - Enforcing best practices at _the configuration level_ e.g. disallowing the all keyword for transitions as it is not performant.

You can enforce these kind of best practises at the configuration level. If these [language limiting rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#limit-language-features) aren't enough for your needs (e.g. you want custom violations messages) you can [create a bespoke plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) to meet them.
