### ISSUE TITLE
Fix autofix for within comments in no-eol-whitespace

### ISSUE THREAD

**Issue by axten** [stylelint/stylelint#3842]
> Clearly describe the bug

autofix not working

> Which rule, if any, is the bug related to?

`no-eol-whitespace`

> What CSS is needed to reproduce the bug?

```css
// 
// sample comment with trailing spaces 
// 
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-eol-whitespace": [true, { ignore: ["empty-lines"] }]
  }
}
```

> Which version of stylelint are you using?

`9.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"CLI with `stylelint "**/*.scss" --config myconfig.json`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"Yes, it's related to SCSS"

> What did you expect to happen?

this should be autofixed

> What actually happened (e.g. what warnings or errors did you get)?

**Comment by jeddy3** [comment]
@axten Thanks for the report.

I can reproduce this bug for both single line comments and normal CSS comments e.g.

```
/* comment - this line is not fixed
  */ - this line is fixed

// this line is not fixed 
```

As the issue has been labelled "help wanted", please consider [contributing a fix](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).

**Comment by stephenliu1944** [comment]
still won't fix this bug.

**Comment by fliang-solielcom** [comment]
please review again.
