### ISSUE TITLE
how to use globally installed stylelint plugins  in stylelint CLI 

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#3844]
Want to use globally installed plugins in the cli , how to refer those global plugins in .stylelintrc file

**Comment by evilebottnawi** [comment]
@ssivanatarajan please use issue template, otherwise issue will be closed without reply

**Comment by ssivanatarajan** [comment]
@evilebottnawi issue template is not loading.

**Comment by ssivanatarajan** [comment]
can I use node modules path of those plugins like this in config?
"plugins": [
        "/usr/local/node_modules/stylelint-selector-no-empty"
]

**Comment by jeddy3** [comment]
I believe you can just reference them as you would a locally installed npm module, like so:

```
"plugins": [
"stylelint-selector-no-empty"
]
```

See [this part of the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#extends) about "locators".

If the above doesn't work, then please raise [a new bug issue](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md).

_Background... plugins are [found using `getModulePath`](https://github.com/stylelint/stylelint/blob/master/lib/augmentConfig.js#L121-L125) and, [as of `9.7.0`](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#970), this checks the global npm folder._
