### ISSUE TITLE
Fix autofix for single-line comment within maps in value-keyword-case

### ISSUE THREAD

**Issue by vkrol** [stylelint/stylelint#3847]
> Clearly describe the bug

Single-line comment is replaced with the multi-line. There is the bug in the `value-keyword-case` auto-fixing functionality. This bug was introduced in this PR https://github.com/stylelint/stylelint/pull/3775.

Repository for reproducing: https://github.com/vkrol/stylelint-scss-single-line-comment-bug.

> Which rule, if any, is the bug related to?

`value-keyword-case`

> What CSS is needed to reproduce the bug?

```scss
$map: (
	key: 0, // some single-line comment
);

```

> What stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
	rules: {
		"value-keyword-case": "lower",
	},
};

```

> Which version of stylelint are you using?

e.g. `9.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint \"**/*.scss\" --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS maps.

> What did you expect to happen?

No changes.

> What actually happened (e.g. what warnings or errors did you get)?

Single-line comment is replaced with the multi-line.

/cc @nazarov-nikita

**Comment by jeddy3** [comment]
@vkrol Thanks for the report and for the reproducible repo.

**Comment by alexander-schranz** [comment]
Tried to fix it but could not get it work the problem seems to be that the `stringify` function converts `//` comments into `/*`
