### ISSUE TITLE
--fix is partial when used on package.json scripts chaining after prettier --write

### ISSUE THREAD

**Issue by avrelaun** [stylelint/stylelint#3856]
We have a package.json script at work called "fix" which runs prettier write && eslint --fix && stylelint --fix. Works pretty well, but the stylelint --fix output varies based on whether or not prettier as the --write option. Cannot seem to figure out why.

Here's a repo containing minimal code to test:

https://github.com/avrelaun/prettier-stylelint-conflict

Expected behavior:

When running "yarn run fix" in the repo, the files should be edited like when running "yarn run fix2" (where prettier does not --write)

Actual behavior:

Some stylelint --fix does not pass (although some does, you can check by adding some other css/scss stylelint rule error)

**Comment by avrelaun** [comment]
Based on diagnostics made on the issue referenced above, apparently this is ane issue of stylelint --fix stabitlity/consistency: when the command is called twice it fixes it.

This is still a bug though.

**Comment by hudochenkov** [comment]
Please, describe your issue using [issue template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md). It's not clear what problem you're experiencing with stylelint.

**Comment by avrelaun** [comment]
Rewritten here: https://github.com/stylelint/stylelint/issues/3857
