### ISSUE TITLE
Add support for reportNeedlessDisables to the configuration object

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3858]
> What is the problem you're trying to solve?

I always want to use the `--report-needless-disables` flag, but it's a chore having to use it for every `$ stylelint` invocation.

> What solution would you like to see?

I would like the ability to specify the CLI flag as a setting in the Stylelint config. That way I can put it in my shareable config and I don't have to specify it each time. The setting could be named `reportNeedlessDisables`.

**Comment by evilebottnawi** [comment]
@sindresorhus good idea, i have some problem, all my projects have `--report-needless-disables` and it is not look good :+1:

**Comment by jeddy3** [comment]
Sounds good to me.

**Comment by fanich37** [comment]
Since #3859 is under discussion this issue is also should be.
