### ISSUE TITLE
Add support for fix to the configuration object

### ISSUE THREAD

**Issue by sindresorhus** [stylelint/stylelint#3859]
> What is the problem you're trying to solve?

I always want to use the `--fix` flag, but it's a chore having to use it for every `$ stylelint` invocation.

> What solution would you like to see?

I would like the ability to specify the CLI flag as a setting in the Stylelint config. That way I can put it in my shareable config and I don't have to specify it each time. The setting could be named `fix`.

---

Related to #3858

**Comment by jeddy3** [comment]
> That way I can put it in my shareable config and I don't have to specify it each time. 

Sounds like a valid use case to me.

**Comment by hudochenkov** [comment]
I'm not sure this is a good idea to put CLI flags into config. Seems weird. ESLint doesn't have such thing and it's used by far bigger user base.
