### ISSUE TITLE
Fix CSSSyntaxError for paired quotes in single-line comments

### ISSUE THREAD

**Issue by johnwest80** [stylelint/stylelint#3882]
> Description

Two apostrophes in comment lines cause cssSyntaxErrors

> Which rule, if any, is the bug related to?

cssSyntaxError

> What CSS is needed to reproduce the bug?

```less
// apostrophe's
// apostrophe's
// more
```

However, one apostrophe doesn't fail:

```less
// apostrophe's
// apostrophes
// more
```

> Which version of stylelint are you using?

9.9.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

node_modules/stylelint/bin/stylelint.js test.less

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

less

> What did you expect to happen?

No error

> What actually happened (e.g. what warnings or errors did you get)?

Error

**Comment by johnwest80** [comment]
great.  glad i could help, and i look forward to a fix.

**Comment by jwilsson** [comment]
We have an [open issue](https://github.com/shellscape/postcss-less/issues/130) for this over at `postcss-less`. Any help with that would be greatly appreciated!

**Comment by jwilsson** [comment]
This issue has been fixes upstream, a fresh install of stylelint should solve this issue.

**Comment by jeddy3** [comment]
> This issue has been fixed upstream, a fresh install of stylelint should solve it.

That's great!

I followed the conversation about exposing the position of the current tokenizer in PostCSS to enable this fix. Fascinating stuff! It's also humbling to see the number of moving parts and effort that goes into the upstream libraries. stylelint would not be possible without!
