### ISSUE TITLE
Fix TypeError on CWD=Undefined when run as npm-run-script

### ISSUE THREAD

**Issue by klh** [stylelint/stylelint#3896]
> Clearly describe the bug

when running stylelint from package.json via `npm run task` opt.cwd is undefined and causes globby to barf a TypeError

> Which version of stylelint are you using?

9.10.0
node 11.6.0
npm 6.5.0-next.0

works:
CLI with: `stylelint  "{src, sass }/**/*.scss" --fix` 

does not work:
```package.json
{
  "scripts": {
    "lint": "stylelint \"{src, sass }/**/*.scss\" --fix"
}
}
```

`npm run lint` -> TypeError cwd undefined.

possible solution:
you've already added GlobOptions to the API in previous commits, make the default cwd = baseDir or process.cwd()

**Comment by hudochenkov** [comment]
I can't reproduce the issue. @klh do you still experience an issue.
