### ISSUE TITLE
Why rule-set-body-selector-background-property?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#39]
I don't understand this one. Am I right that it's trying to force the user to *at some point* use a background property on `body`? If that's the intention, I don't think this will accomplish that. If the uses the `body` selector twice in legitimate ways and only applies a background once, this will needlessly. Also, the user could *never* use the `body` selector and thus bypass the intention without getting warned. (Or maybe there's another reason behind this rule?)

**Comment by MoOx** [comment]
> Am I right that it's trying to force the user to at some point use a background property on body?

Reference: http://nota-bene.org/Background-and-foreground-colours

I think a global check if "there is a background prop in all selectors that might affect body" is fine. That said, this rule is tricky since some use (like me) will use a class for body.

This rule is totally low priority.

**Comment by jeddy3** [comment]
Yeap, I wasn't quite sure where to place this rule when I was regrouping things. 

Agreed it's a low priority. Shall we park it for now?

**Comment by MoOx** [comment]
What do you mean by "park" ? Close ? If so I think we can. I just added the link to this issue in #1.

**Comment by jeddy3** [comment]
Park it for now = not deal with it for now, but later.

So, yeap, adding a link to this issue in #1 and closing this issue is perfect :)
