### ISSUE TITLE
Downgrade `postcss-markdown` to 0.34 or increase the mayor version.

### ISSUE THREAD

**Issue by artberri** [stylelint/stylelint#3907]
There are compilation errors when using stylelint in projects that uses Typescript < 3.0.0. Some dependencies are using now the new Typescript type "unknown", which is not compatible with versions lower than 3.

This problem has been introduced with the upgrade of the `postcss-markdown` library (https://github.com/stylelint/stylelint/pull/3871). This commit upgraded the library from 0.34 to 0.36, which is the one introducing this breaking change. I understand that is difficult to see it because the mayor version number of that library has not been increased, and this is why I've opened another issue in their library suggesting them to increase the mayor version number: https://github.com/gucong3000/postcss-markdown/issues/30.

In order to avoid this issue in other projects I suggest you to downgrade  `postcss-markdown` to 0.34 or to increase the stylelint mayor version.

What do you think?

**Comment by hudochenkov** [comment]
Neither of this project, `postcss-markdown`, or `remark` uses TypeScript. All these projects use JavaScript. Could you explain how it's all related?

**Comment by artberri** [comment]
Thanks for your quick answer, and sorry because my previous explanation was quite bad. Apart from that, I'm realizing that probably this is not the repo where I should open the issue. Let me explain it again, and give me your opinion if you don't mind.

First I'll start with the chain of dependencies:

- `postcss-markdown@0.36` depends on `remark@^10.0.1`  
https://github.com/gucong3000/postcss-markdown/blob/v0.36.0/package.json
- `remark@^10.0.1` depends on `unified@^7.0.0`  
https://github.com/remarkjs/remark/blob/10.0.1/packages/remark/package.json

[Unified](https://github.com/unifiedjs/unified) is probably where I should open the issue because they introduced a new dependency in the 7.1.0 version: https://github.com/unifiedjs/unified/pull/43.

- `unified@^7.0.0` __does not depend on__ `@types/vfile@^3.0.0`    
https://github.com/unifiedjs/unified/blob/7.0.0/package.json
- `unified@^7.1.0` __depends on__ `@types/vfile@^3.0.0`  
https://github.com/unifiedjs/unified/blob/7.1.0/package.json

This typing package does not depend directly on typescript >=3.0.0 but it contains types of that version, so, if you have a typescript project which uses for example `stylelint` it will include also the  `@types/vfile` package because of dependencies, and your project will fail compiling unless you add `skipLibCheck: true` to your compiler options.

Another option to avoid the error is by adding unified as a direct dependency and forcing it to a >=7.0.0 <7.1.0 version in the project which is requiring stylelint, so, right now, I think that I shouldn't open this issue. Sorry for the inconveniences.

I'll close it, but anyway, it would be nice to read your opinion on this.

**Comment by hudochenkov** [comment]
I have no experience with TypeScript. But I can understand that issue like this gives you problems from nowhere. I hope you'll find an acceptable solution.

**Comment by otakustay** [comment]
This is an issued originally caused by https://github.com/gucong3000/postcss-markdown/pull/33, stylelint is unable to do anything about it, only to wait `postcss-markdown` to publish a new version
