### ISSUE TITLE
Reduce package size after ballooning to 171MB in 9.10.0

### ISSUE THREAD

**Issue by billyjanitsch** [stylelint/stylelint#3913]
> Clearly describe the bug

The rule introduced in #3833 is neat, but depending on `jison-gho` brings in ~140MB of additional dependencies, bringing the install size of stylelint from 31MB (9.9.0) to 171MB (9.10.0). 😕 Is a ~6X increase in install size justifiable for a single rule?

Would you consider using Jison as a dev dependency and using it to generate a parser as a JS file at build time, rather than using it as a dependency and generating the parser at runtime? And perhaps reverting this rule until then?

> Which rule, if any, is the bug related to?

`function-calc-no-invalid`

> Which version of stylelint are you using?

`9.10.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

You can compare the install sizes like this:

```
mkdir old && cd old && npm i stylelint@9.9.0 && du -sh node_modules
mkdir new && cd new && npm i stylelint@9.10.0 && du -sh node_modules
```

**Comment by jeddy3** [comment]
@billyjanitsch Thanks for the report.

> Is a ~6X increase in install size justifiable for a single rule?

No, it's not. 

> Would you consider using Jison as a dev dependency and using it to generate a parser as a JS file at build time

Thanks for the suggestion of a solution.

---

Let's try to get [size-limit](https://www.npmjs.com/package/size-limit) added to the PR that fixes this, so we can stop this from happening again.
