### ISSUE TITLE
Support style tag inside template literal

### ISSUE THREAD

**Issue by Draccoz** [stylelint/stylelint#3928]
> What is the problem you're trying to solve?

Linting styles inside `<style>` tags inside template literals does not work. Would be useful to be able to lint them.

> What solution would you like to see?

Handling such use cases (popular with web components).

Brief summary:
Linting css inside html files (in `<style>` tags) works. Linting css in tagged templates work. Would be helpful if the following worked as well:
```
export const template = html`
  <style>selector { attribue: value; }</style>
  <div>Rest of the template</div>
`;
```

**Comment by gucong3000** [comment]
@Draccoz 
```console
stylelint --syntax html **/*.js
```

Maybe this command will make it work.

**Comment by Draccoz** [comment]
@gucong3000 it does work, thanks! If it goes about my use case, I consider this issue fixed. It still wouldn't work if one had both css in tagged templates and css in `<style>` in tagged templates, but am not sure if that kind of mix exists in bigger projects.
Will you want to improve the support for the above edge case, or should I close the issue?

**Comment by jeddy3** [comment]
> Will you want to improve the support for the above edge case

@gucong3000 Would it be possible to handle this use case in `postcss-syntax`?

**Comment by gucong3000** [comment]
> Would it be possible to handle this use case in postcss-syntax?

OK. I will start this work after the Spring Festival holiday.

**Comment by rubixibuc** [comment]
> @Draccoz
> 
> ```
> stylelint --syntax html **/*.js
> ```
> 
> Maybe this command will make it work.

I have tried this and it breaks for certain use cases. It will break at times when using string interpolation in the <style> tag. it also breaks at times when using interpolation in style="" attributes.
