### ISSUE TITLE
Nested sort order to enforce new line above specified properties

### ISSUE THREAD

**Issue by DanGamble89** [stylelint/stylelint#393]
Would it also be able to implement nested arrays like CSSComb's sort order as my code style tends to be like:

```
"sort-order": [
        [
             "prop1",
             "prop2",
             "prop3",
        ],
             "prop4",
             "prop5",
             "prop6",
        ]
]
```

```
  display: block;
  padding-top: 6px;
  padding-right: 10px;
  padding-bottom: 6px;
  padding-left: 10px;
  width: 100%;

  line-height: inherit;

  appearance: none;
  border: 1px solid transparent;
  color: map-get($colors, text);
```

**Comment by jeddy3** [comment]
This is a valid suggestion. @DanGamble89 Feel free to contribute this. Although, I suggesting holding off until the other `rule-properties-order` enhancements are in: #392 and #391

**Comment by jeddy3** [comment]
@DanGamble89 Both #392 and #391 are now in `master` :) So feel free, if you like, to contribute this functionality.

**Comment by davidtheclark** [comment]
There are a fair number of special cases to consider. @DanGamble89 maybe you can help clarify user expectations based at least in part on what CSSComb does?

Here are some questions I thought up -- given an order array like this: `[ [ A, B, C ], [ D, E, F ] ]`:
- `rule-properties-order` currently ignores properties that are not specified in a custom order array. If user inserts G between C and D, what line breaks are expected? If user inserts G after F, should there be a newline above it?
- If user wants unspecified properties to be declared at the bottom of the block, should they be separated by a newline from any explicitly grouped properties above? (Kind of the same as the second question above.)
- Same question but for the top of the block, e.g. if user inserts G *before* A.
- Am I right that any rule A from any group should be separated with a newline from any other rule B in another group, regardless of rule A's position within its group? So if my actual order were A, B, C, (newline) E, D, F, I would only get *one* warning, complaining that D should come before E -- not another complain that D should have a newline before it? And if I have B, F, there should be a newline before F?

Can anybody think of any other weird annoying details like this?

**Comment by DanGamble89** [comment]
Hey sorry i didn't realise there was activity in here. I'll look back at all my mentions and write up things i can help with at some point today or tomorrow :)

**Comment by DanGamble89** [comment]
@davidtheclark 

1. CSSComb adds a spread like property (`"..."`):

    ```
    ["$variable"],
    ["position"],
    ["..."],
    ["border"],
    ["$include"],
    ["font"]
    ```

    This specifies where any rules that you haven't specified will get spat out.

2. I'd say yes i'd just treat the spread operator like any other declaration, if it's in it's own array it should have line breaks above or below it, if it's inside another array then the breaks should match what the config shows.

3. That sounds right to me. Maybe it should only complain about there being no line separating properties if they are all in the correct order to begin with as the new line thing should be hit far fewer times than property order.

4. Yes if you have B, F there should be a new line before F.

Hope this clears some of this up :)

**Comment by davidtheclark** [comment]
Done in #470.
