### ISSUE TITLE
Expose HTML style node to rules

### ISSUE THREAD

**Issue by romulof** [stylelint/stylelint#3937]
> What is the problem you're trying to solve?

I'm working with `.vue` files and writing a rule to do some very specific checks for styles that are not `scoped`.

> What solution would you like to see?

Internally you are using _postcss-html_, which uses _htmlparser2_ to deal with HTML-like structure. Keeping the parsed node information and exposing it to the rule would not only solve my problem, but allow more flexibility. Something like this:

```js
function rule(primary, secondary, context) {
    return (root, result) => {
        if (root.styleTag && root.styleTag.hasAttribute('scoped') {
            // Has scoped style tag -> Ignore this rule
            return;
        }
        // Normal rule checks ...
    };
}
```

**Comment by jeddy3** [comment]
@romulof Thanks for the request and for using the template.

> I'm working with .vue files and writing a rule to do some very specific checks for styles that are not scoped.

That's an interesting use case! 

Some of the built-in rules now rely on node information from non-standard syntax parsers. For example:

https://github.com/stylelint/stylelint/blob/afb1c394ccb26a8969bf9fd05cd9d303976a67cb/lib/rules/max-empty-lines/index.js#L104-L126

So, there is a precedent for this.

> Keeping the parsed node information and exposing it to the rule

@gucong3000 As the maintainer of postcss-html, do you think is this viable?

**Comment by romulof** [comment]
Right now I'm doing this:

```js
const stylelint = require('stylelint');
const get = require('lodash/get');

const styleTagRegex = /<style(\s+[^>]+)*\s*>/g;
const scopedAttrRegex = /\sscoped[\s>]/;

module.exports = stylelint.createPlugin(ruleName, (primaryOption, secondaryOptionObject) => {
    return (postcssRoot, postcssResult) => {
        const beforeStyle = get(postcssResult, 'root.nodes[0].raws.beforeStart', '');
        const styleTagMatches = beforeStyle.match(styleTagRegex);

        if (styleTagMatches && styleTagMatches.length === 1 && styleTagMatches[0].match(scopedAttrRegex)) {
            // Has scoped style tag -> Ignore this rule
            return;
        }

        postcssRoot.walkRules(node => {
            ...
        });
    };
});
```

I know that that those regular expressions are not 100% compliant, but I didn't want to add an HTML parser here (I have some restrictions about adding packages), also this solution does not support scripts added this way:

```html
<style lang="scss" scoped src="./somefile.scss" />
```

**Comment by romulof** [comment]
Any news?

**Comment by hudochenkov** [comment]
I'm afraid there are no news. @gucong3000, author of `postcss-html`, is not active on Github currently.

**Comment by jeddy3** [comment]
Closing as related to external custom syntaxes.
