### ISSUE TITLE
Is there a way to get this to play a bit nicer with Sass?

### ISSUE THREAD

**Issue by DanGamble89** [stylelint/stylelint#394]
This seems like an awesome project for PostCSS and i'd love to use that more but for reasons i can't fully jump into it and i'm still left using Sass. Since Sass gets compiled it does certain things like always adding the final semi colon regardless of whether it's there in the `.scss` or not.

I'd like to use Stylelint to enforce style in my `.scss` files as well. Is there a way to get this to iterate over the `.scss` files before being piped through `node-sass` or do i just have to try and do my best with what compiled css i get after?

**Comment by davidtheclark** [comment]
Have you tried using https://github.com/postcss/postcss-scss to run your `.scss` files directly through PostCSS plugins? I believe that's what it was made to enable.

**Comment by DanGamble89** [comment]
I haven't, that looks like it could work :). Do you know if anyone has tried it with Stylelint before?

**Comment by ntwb** [comment]
I am, it works great :)

**Comment by DanGamble89** [comment]
@ntwb Awesome! Is it really just as simple as piping through the `.scss` files instead of adding it to my current `.scss -> .css` gulp task?

**Comment by davidtheclark** [comment]
@DanGamble89 Did you get this sorted out?

@jeddy3, @ntwb : Maybe we should add some documentation explaining how to do this, because I'm sure it won't be uncommon.

**Comment by DanGamble89** [comment]
I didn't unfortunately. Still quite new to Javascript so do struggle with things like this. Would love some documentation on it :)

**Comment by ntwb** [comment]
> Still quite new to Javascript so do struggle with things like this.

Me too :smirk:

I'll try to whip something up, some docs, and an example later today :)

**Comment by DanGamble89** [comment]
Would love to see it if you do :)

**Comment by DanGamble89** [comment]
Hey @ntwb did you whip anything up? :)

**Comment by ntwb** [comment]
@DanGamble89 Sorry, haven't had time, and as I stated above I'm also pretty new to JavaScript so not the simplest of things for me either :smirk: 

That said this happened today, I think the example given is what you'll need: https://github.com/postcss/postcss-scss/issues/10

There's also GitHub search which is amazing, you should use it to search for code examples:
Theres not many people using PostCSS-SCSS yet but the following two I found via [this search](https://github.com/search?p=2&q=gulp+require%28%27postcss-scss%27%29&type=Code&utf8=%E2%9C%93)

• https://github.com/wellington/realbench/blob/master/gulpfile.js
• https://github.com/dustindowell22/buckle/blob/master/gulpfile.coffee

**Comment by DanGamble89** [comment]
I struggle to go beyond basics with the Github search but i'm sure you've given me a nice foundation to work with. Will return if i construct anything useful. Thanks :)

**Comment by jeddy3** [comment]
> Maybe we should add some documentation explaining how to do this, because I'm sure it won't be uncommon.

SGTM. 

@DanGamble89 Let us know how you get on with either @ntwb suggestion of https://github.com/postcss/postcss-scss/issues/10 (if you're using gulp) or https://github.com/postcss/postcss-scss#scss-transformations (if you're using the JS API), and we'll incorporate something into the README to help other users who also use scss.

**Comment by TrySound** [comment]
@jeddy3 Can be closed I think
https://github.com/postcss/gulp-postcss/commit/1e684db776df2f27bb047cf6b87a5b99e68903b1

**Comment by jeddy3** [comment]
@TrySound Thanks for the heads up.

@davidtheclark Question for when you get back. Do we need to account for this in the new API/CLI? If not, I'll close the issue.

**Comment by davidtheclark** [comment]
Yes, I think we need to provide an option in the API/CLI to use alternate SCSS syntax. I will make a more focused issue for that.
