### ISSUE TITLE
Fix false negatives for nested at-rules in selector-max-*

### ISSUE THREAD

**Issue by ccabrales** [stylelint/stylelint#3947]
> Clearly describe the bug

There are false negatives for `selector-max-type` and `selector-max-combinators` when using SCSS @include in the block.

> Which rule, if any, is the bug related to?

`selector-max-type`, `selector-max-combinators`

> What CSS is needed to reproduce the bug?

```scss
.a-selector {
  div {
    @include test-mixin {
      background-color: orange;
    }
    overflow: hidden;
  }
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
 "extends": "stylelint-config-standard",
 "plugins": ["stylelint-scss"],
  "rules": {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "selector-max-type": 0,
    "selector-max-combinators": 0
  }
}
```

> Which version of stylelint are you using?

`9.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint --config stylelint.config.js "src/**/*.scss" -f verbose`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS mixins and `@include`.

> What did you expect to happen?

Errors on the `div` for both `selector-max-type` and `selector-max-combinators`.

> What actually happened (e.g. what warnings or errors did you get)?

There were no errors reported on the `div`.

**Comment by jeddy3** [comment]
@ccabrales Thanks for the report and for using the template.

I can reproduce this.

The built-in rules are geared towards standards-compliant CSS. For example, the following are correctly flagged:

```css
/* nested rule within at-rule */
@media (min-width: 10rem) { 
  div {} 
}
```

```css
/* nested rules within nested at-rule */
@supports (display: grid) {
  @media (min-width: 10rem) { 
    div {} 
  }
}
```

```css
/* nested rule (using the nesting selector) within a rule */
.class
  & div {} 
}
```

_At-rules nested within rules_ are not standards-compliant and are currently ignored by these `selector-max-*` rules. However, if you can add support for nested at-rules _without adding too much complexity_ then I think we can patch the rules. Otherwise, a plugin (say within `stylelint-scss`) might be a better option. A guide to working with rules can be find [in the developer guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).

**Comment by ccabrales** [comment]
I think I understand. I'll take a look and see what I can do.

But I'm not able to install packages using `yarn` or `npm`...yarn fails on a checksum mismatch and npm fails with a 404 when trying to install the package `@iamstarkov/listr-update-renderer@0.4.1`. Looks like that package dropped the namespace. Is this a known issue that installing dependencies on a clean project fails?

**Comment by jeddy3** [comment]
> I'll take a look and see what I can do.

Excellent.

> Is this a known issue that installing dependencies on a clean project fails?

Nope, it should install fine. I just tried it myself with after deleting my `node_modules` directory and it worked. 

```
jeddy3:stylelint jeddy3$ node --version
v10.15.1
jeddy3:stylelint jeddy3$ npm --version
6.8.0
jeddy3:stylelint jeddy3$ npm install
> fsevents@1.2.7 install /Users/jeddy3/Projects/stylelint/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/jeddy3/Projects/stylelint/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> husky@1.3.1 install /Users/jeddy3/Projects/stylelint/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done
added 1233 packages from 590 contributors and audited 24818 packages in 38.224s
found 0 vulnerabilities
```

Are you using the latest version of `npm`?

**Comment by ccabrales** [comment]
Yes, I'm using the latest version of `npm`. The more specific error is below.

```shell
stylelint$ nvm use node
Now using node v11.10.0 (npm v6.7.0)
stylelint$ npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@iamstarkov%2flistr-update-renderer - User not found
npm ERR! 404 
npm ERR! 404  '@iamstarkov/listr-update-renderer@0.4.1' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 It was specified as a dependency of 'lint-staged'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by ccabrales** [comment]
Figured out the issue after banging my head against the wall for a while. I guess you have to `npm login` before it will let you download scoped packages.
https://github.com/npm/npm/issues/18569#issuecomment-370888479

I'll try to take a look at updating the rule now. Not sure on a timeline though.

**Comment by jeddy3** [comment]
> Figured out the issue after banging my head against the wall for a while.

Thanks for digging deeper. That's a strange npm issue.
