### ISSUE TITLE
I need help  regarding stylelint install ways.

### ISSUE THREAD

**Issue by syedsimanta03** [stylelint/stylelint#3948]
I installed stylelint globally via NPM and have my .stylelintrc file setup for project. Do I still need the vs code stylelint plugin?

**Comment by jeddy3** [comment]
If you want stylelint violations to show in the _editor panel_ of VS Code you will need to install the VS code extension.

You can also use stylelint via the CLI, which you can run via the VS Code _integrated terminal_.

A complete list of how to use stylelint is [available in the docs](https://github.com/stylelint/stylelint#getting-started).
