### ISSUE TITLE
Fix false positives for prefers-color-scheme in media-feature-name-no-unknown

### ISSUE THREAD

**Issue by vinkla** [stylelint/stylelint#3950]
> What is the problem you're trying to solve?

The `media-feature-name-no-unknown` rule doesn't allow the new [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query feature. This is a new media query added to CSS Media Queries Level 5 to utilize the dark mode preference operating systems provide. This new media query is [implemented in Safari Technology Preview](https://trac.webkit.org/changeset/237156/webkit) and [currently in development for Chrome and Firefox](https://www.chromestatus.com/feature/5109758977638400).

> What solution would you like to see?

The media query `prefers-color-scheme` to be allowed by `media-feature-name-no-unknown` rule.

I could open a pull request to add this but I'm not comfortable enough within the stylelint codebase to get started. If someone could point me in the right direction?

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Please, consider a contribution by updating [the list of known media queries](https://github.com/stylelint/stylelint/blob/d78ea0131e14de2414d44eccfc996461b4de4eb6/lib/reference/keywordSets.js#L564).

**Comment by vinkla** [comment]
Thanks @hudochenkov! I've opened a pull request: #3951
