### ISSUE TITLE
custom property issue

### ISSUE THREAD

**Issue by syedsimanta03** [stylelint/stylelint#3960]
Hi please check the image and I want to keep the custom variables like that way, but itz show custom-property-empty-line-before error. Can you please set rules. I don't need any empty line rule here.

https://imgur.com/a/EI7gkVw

**Comment by evilebottnawi** [comment]
Please use issue template

**Comment by evilebottnawi** [comment]
Before makr question, please read docs, it is bug tracker, not QA service, for questions you can use `stackoverflow`/`gitter`/ other services
