### ISSUE TITLE
custom property space issue 

### ISSUE THREAD

**Issue by syedsimanta03** [stylelint/stylelint#3961]
Hi please check the image and I want to keep the custom variables like that way, but itz show custom-property-empty-line-before error. Can you please set rules. I don't need any empty line rule here.

https://imgur.com/a/EI7gkVw

**Comment by evilebottnawi** [comment]
Please read https://github.com/stylelint/stylelint/issues/3960

**Comment by evilebottnawi** [comment]
ok, it's useless

**Comment by evilebottnawi** [comment]
@syedsimanta03 please provide you stylelint configuration

**Comment by syedsimanta03** [comment]
@evilebottnawi 
{
  "plugins": [
    "stylelint-scss"
  ],

  "extends": [
    "stylelint-config-standard",
    "stylelint-config-prettier"
  ],
  

  "rules": {
    
    "scss/dollar-variable-pattern": "^foo",
    "scss/selector-no-redundant-nesting-selector": true,

    "block-no-empty": null,
    "length-zero-no-unit": null,
    "color-no-invalid-hex": true,
    "comment-empty-line-before": [
      "always",
      {
        "ignore": [
          "stylelint-commands",
          "after-comment"
        ]
      }
    ],

    "declaration-colon-space-after": "always",
    "declaration-property-value-whitelist": {
      "line-height": [
        "/.*em$/"
      ]
    },

    "max-empty-lines": 7,

    "rule-empty-line-before": [
      "always",
      {
        "except": [
          "first-nested"
        ],
        "ignore": [
          "after-comment"
        ]
      }
    ],

    "unit-whitelist": [
      "em",
      "rem",
      "%",
      "s",
      "px",
      "vh",
      "deg",
      "vw"
    ]
  }
}

**Comment by syedsimanta03** [comment]
@evilebottnawi evilebottnawi  any update?

**Comment by jeddy3** [comment]
> I want to keep the custom variables like that way, but itz show custom-property-empty-line-before error.

There is no way to enforce that style with a linter because the positions of the empty lines are arbitrary (or tightly coupled to the pattern of the custom property name). You can either [turn off the rule](https://stylelint.io/user-guide/configuration/#turning-rules-off-from-within-your-css) or use comments above each block, like so:

```css
:root {
  --primary-1: 0;
  --primary-2: 0;

  /* greys */
  --grey-1: 0;
  --grey-2: 0;
  --grey-3: 0;

  /* shadow */
  --shadow: 0;
}
```

@syedsimanta03 In the future, please posts questions to slackoverflow and not the issue tracker.

**Comment by syedsimanta03** [comment]
@jeddy3 how to turn off? I used  null which didn't work

**Comment by hudochenkov** [comment]
@syedsimanta03 
<img width="1120" alt="screenshot 2019-02-22 at 08 30 02" src="https://user-images.githubusercontent.com/654597/53226714-4734d480-367c-11e9-9c47-82a52a588595.png">

I'm locking this conversation because it's not a support forum. All information is accessible on the main site.
