### ISSUE TITLE
There is no option to fix line-height error

### ISSUE THREAD

**Issue by syedsimanta03** [stylelint/stylelint#3963]
"declaration-property-value-whitelist": {
      "line-height": [
        "/.*em$/"
      ]
    },

I am using the above rule which shows error when I am not using rem or em for line-height. I removed the rule still same error for line-height : 1;

There should be no error for line-height : 1; without unit. there is no rule in your docs

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using the template.
