### ISSUE TITLE
line-height error - unitless

### ISSUE THREAD

**Issue by syedsimanta03** [stylelint/stylelint#3964]
declaration-property-value-whitelist": {
"line-height": [
"/.*em$/"
]
},

I am using the above rule which shows error when I am not using rem or em for line-height. I removed the rule still same error for line-height : 1;

There should be no error for line-height : 1; without unit. there is no rule in your docs

**Comment by jeddy3** [comment]
This query has been answered before: https://github.com/stylelint/stylelint/issues/3932#issuecomment-458254366
