### ISSUE TITLE
Update known-css-properties to the latest version (0.12.0)

### ISSUE THREAD

**Issue by pathmapper** [stylelint/stylelint#3973]
For `known-css-properties` the release `0.12.0` is available:

https://github.com/known-css/known-css-properties/releases

**Comment by evilebottnawi** [comment]
Don't need create issue, we use `greenkeeper` bot, he automatically create PR with updated dep and we merge this for next release, anyway you can manually update your deps and/or lock file (just run `npm update`/`yarn upgrade`)
