### ISSUE TITLE
feature-request: selector-min-class

### ISSUE THREAD

**Issue by clshortfuse** [stylelint/stylelint#3974]
> What is the problem you're trying to solve?

Prevent rules being defined without any classes either intentionally or accidentally. For example, we wouldn't want to allow this

````
.myclass {
  &[red] {
    color: red;
  }
  [green] {
   color: green
  }
  :last-of-type {
    margin: 4px;
  }
}

````

In the second example, it's likely that an `&` was omitted mistakenly for `[green]`. It would become:

````
.myclass[red] {
  color: red;
}

.myclass *[green] {
  color: green;
}

.myclass *:last-of-type {
  margin: 4px;
}
````

Which makes an unintentional universal selector. I would like to be able to avoid that.

> What solution would you like to see?

A new rule where you specify a minimum number of classes, perhaps called: `selector-min-class`, where I could set the number to 1.

**Comment by jeddy3** [comment]
@clshortfuse Thanks for the suggestion and for using the template.

This is an interesting one.

I'm not sure a `selector-min-class` rule would work in this instance as the `selector-*` rules resolve _nested selectors_ before tallying up the number of _selectors_. Each of the _unresolved selectors_ in your example above has one _class selector_.

Would enforcing the explicit use of the _nesting selector (`&`)_ resolve the issue for you? You can do this with the [`selector-nested-pattern` rule](https://stylelint.io/user-guide/rules/selector-nested-pattern/):

```json
{
  "selector-nested-pattern": "^&"
}
```

**Comment by clshortfuse** [comment]
@jeddy3 Thanks for getting back to me so soon. I messed around a bit and found some success with:

`^(\s+|((:root|&|[a-z0-9A-Z._])[^\s>~+]*)|&::?|[&+~>])*$`

Basically, these would fail:

````
:bad()
:first-of-type
bad [attr]
:first-child
[attr]
.test>:not(good)
&input .test~:bad
````
It considers spaces between `&+~>`

I hadn't considered  the `selector-nested-pattern` rule initially because I found the need for this type rule to avoid using global selectors because it trashed IE performance. I would like to avoid something like this in the future:

````
[bold-text] {
  font-weight: bold;
}
[light-text] {
  font-weight: light;
}
````

Instead, it would be better to do

````
.custom-text {
  &[bold-text] {
    font-weight: bold;
  }
  &[light-text] {
    font-weight: light;
  }
}
````

I figured a `selector-min-class` would be a simple variation of the `selector-max-class`. At least I can solve the issue with nested rules, but I would still need something for top-level rules, even if it's a regex.

**Comment by jeddy3** [comment]
Thanks for the further explanation.

> I figured a selector-min-class would be a simple variation of the selector-max-class.

I'm not sure a `selector-min-class` rule would be generally useful to users and therefore wouldn't meet the [criteria for inclusion](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#criteria-for-inclusion).

> I found the need for this type rule to avoid using global selectors because it trashed IE performance

Fortunately, we have the plugin system for just this type of use case. So, you can craft a
[plugin](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md) to check for exactly this and in a way that works best for your code base.

(Issue triage: closing as best suited as plugin)

**Comment by vvanpo** [comment]
@jeddy3 I have been looking for a rule like this, because my project uses CSS modules in Vue components, but developers occasionally do not understand the limitations of CSS modules and will write bare element selectors like `button { ... }`. What I need is a rule that enforces that all selectors have at least one class in them, regardless of nesting or how complex the selectors are. A rule like `selector-min-class` would solve this for me.

Does this sound like it meets the criteria for inclusion? I imagine this rule would be useful to any project, Vue-based or not, that uses CSS modules.

**Comment by jeddy3** [comment]
I'd say write it as a plugin first. It's easier to port plugins into stylelint than it is to move rules out.
