### ISSUE TITLE
Update inconsistencies in docs/sources & types

### ISSUE THREAD

**Issue by 43081j** [stylelint/stylelint#3976]
I'm currently fixing up the `@types` package for stylelint.

I ran into the following issues if you wouldn't mind explaining each one:

* Your docs claim there's a [`postcssResults`](https://stylelint.io/user-guide/node-api/#postcssresults) in the lint result, however there is no such thing in your sources anywhere. Have I somehow missed it or have you forgotten to update your docs after removing it?
* Your [docs claim](https://stylelint.io/developer-guide/plugins/#the-anatomy-of-a-plugin) a rule function is given a `LazyResult` as the second parameter, but every rule you have uses this result in the `report(...)` util which internally calls `warn(...)`. LazyResults **do not have a warn method**, so surely this means a rule function is in fact given a `Result`, _not_ a `LazyResult`?
* Your [`ruleMessages` docs](https://stylelint.io/developer-guide/plugins/#stylelintutilsrulemessages) don't explain anything at all, it would be nice to see the usage (the interface, not an example) without having to look in the source, so we know what it accepts
* Again, [`validateOptions` has no docs apparently](https://stylelint.io/developer-guide/plugins/#stylelintutilsvalidateoptions)
* Your flow types are dated (e.g. [syntax](https://github.com/stylelint/stylelint/blob/7452f9fbfc43c2ca3cb4f2c723cf16ddc93e6784/flow-typed/stylelint.js#L30) values)

**Comment by jeddy3** [comment]
> I'm currently fixing up the @types package for stylelint.

Thank you!

> Have I somehow missed it or have you forgotten to update your docs after removing it?

I suspect we've forgotten to update the docs. I think this is going to be the answer to all your questions. The docs and the flow types are likely out of date or missing in all of the instances.

As mentioned in #3982, any help filling in these holes would be greatly appreciated. Feel free to submit a PR if you've time.

**Comment by jeddy3** [comment]
Closing as types now published.
