### ISSUE TITLE
Ignore or warn undefined rule

### ISSUE THREAD

**Issue by keenwon** [stylelint/stylelint#3984]
> What is the problem you're trying to solve?

I use stylelint and stylelint-config-xo

- stylelint: v9.6.0
- stylelint-config-xo: v0.13.0

and then throw "undefined rule function-calc-no-invalid".

> What solution would you like to see?

for "undefined rule", maybe it’s better to ignore(warn) than to report an error.

**Comment by evilebottnawi** [comment]
@keenwon please update stylelint, looks you use outdated version of stylelint

**Comment by keenwon** [comment]
@evilebottnawi 
I know, I just suggested that for "undefined rules", ignoring or warning may be better than reporting errors.

**Comment by jeddy3** [comment]
I don't think there's a need to change this behaviour. It's been this way since the beginning.

I'll close this issue for now, but it's still open for comments and we can always revisit if more people request this behaviour change.
