### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by js2me** [stylelint/stylelint#3993]
Hello!

I've got a problem with using this wonderful linter!
Commnd `stylelint .` executed without any exceptions I see own scss errors/warning.
But when I use `stylelint . --fix` then I see this error:
![image](https://user-images.githubusercontent.com/16340911/54695024-4dfb1e00-4b3a-11e9-8f7d-af42d9d9ea4b.png)

node version: `v10.15.1`
npm version: `6.4.1`
stylelint version: `9.10.1`

stylelint config: 
```
{
  "extends": ["stylelint-config-standard", "stylelint-config-recommended", "stylelint-config-recommended-scss"],
  "plugins": ["stylelint-scss", "stylelint-prettier"],
  "rules": {},
  "ignoreFiles": ["node_modules/**", "src/style/fonts/**"]
}

```
Also without extensions and plugins I catched the same error in output

Thanks!

**Comment by evilebottnawi** [comment]
Something wrong in css, can you create minimum reproducible test repo? Also please use issue template for future issues

**Comment by js2me** [comment]
@evilebottnawi I solved that problem and I'm closing that issue.

Solved using the 
```
"ignoreFiles": ["node_modules/**", "src/style/fonts/**", "**/*.json","**/*.svg","**/*.{and another unneeded types}",]
```
This error occured when it trying to parse files like `package.json` :-D

Thanks for your answer!
