### ISSUE TITLE
Drop support for Node.js 6.x

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#4000]
Drop support for Node.js 6.x

• Node.js 6.x LTS entered maintenance mode 30 April 2018
• Node.js 6.x becomes end-of-life 30 April 2019

https://github.com/nodejs/Release#release-schedule

Previously: #2996 Drop Node.js 4 support 

As noted in #3991 we are starting to find modules stylelint use are starting to require Node.js 8.x

This will be a breaking change and will require to be shipped in a _major_ version of stylelint, e.g. 10.0

**Comment by hudochenkov** [comment]
Agreed.

**Comment by jeddy3** [comment]
SGTM.

**Comment by hudochenkov** [comment]
Node.js 8 will reach end-of-life pretty soon as well — end of this year. What if minimum support version for stylelint 10 will be Node.js 10? :)

stylelint will most likely work on Node.js 8 as well for a long time, because we almost don't use language feature from Node.js older than 6. And most likely we won't use them. I don't even know what new in Node.js 8 and 10 except `async`/`await` ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯

What are you thoughts?

**Comment by ntwb** [comment]
• Node.js 8.x LTS entered maintenance mode 1 January 2019
• Node.js 8.x becomes end-of-life December 2019
(1: The 8.x Maintenance LTS cycle is currently scheduled to expire early on December 31, 2019 to align with the scheduled End-of-Life of OpenSSL-1.0.2.)

I think with [919,893 weekly downloads](https://www.npmjs.com/package/stylelint) we should urge on the side of caution and not remove Node.js 8.x yet, let's wait until later in the year, November or December to drop Node.js 8.x

**Comment by tim-soft** [comment]
How did you guys arrive at a minimum node version of 8.15.1? I'm realizing now that AWS Lambda only supports 8.10, which means many serverless hosting services will not work with StyleLint v10

**Comment by hudochenkov** [comment]
@tim-soft 8.15.1 is the latest 8.x release at the time of release. I believe stylelint 10 will work with Node.js 8.10 without any problems.

**Comment by tim-soft** [comment]
@hudochenkov building for node 8.10 will cause problems with yarn

```bash
error stylelint@10.0.0: The engine "node" is incompatible with this module. Expected version ">=8.15.1". Got "8.10.0"
```

**Comment by hudochenkov** [comment]
I think it's pretty reasonable to require the most secure version of a specific Node.js branch. I wouldn't encourage to use outdated version of Node.js. This is strange why AWS ignoring security issues and using old Node.js version.

Also, npm doesn't have problems installing stylelint 10 even on Node.js 8.4. Looks like third-party packet manager more strict.

We can lower version in `engine` in `package.json`, but we don't know what version is really the minimum which won't break. We know for sure, that latest Node.js 8.x version will work. We don't have resources to investigate every possible 8.x release to find the minimum version, and keep checking it with every PR. While Amazon have more than enough resources to update their products.

Possible solution is to use [`yarn install --ignore-engines`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) or `npm install`.

**Comment by tim-soft** [comment]
I completely agree on the point of AWS supporting newer versions of node...

But I also think setting the minimum node version as the latest minor release is kind of arbitrary
