### ISSUE TITLE
--fix-dry-run option

### ISSUE THREAD

**Issue by seyedi** [stylelint/stylelint#4005]
Can we have an option like eslint that automatically fixes problems without saving the changes to the file system?

**Comment by hudochenkov** [comment]
What is use case for it?

**Comment by seyedi** [comment]
Sorry guys, I had an infinite loop in my workflow and I thought it came from autosave option which then I realized that wasn't the case, so for now I don't have a use case for this. Gonna close this issue.
thanks for this great tool!
