### ISSUE TITLE
Remove deprecated syntax options

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4007]
Options `styled`, and `jsx` for `syntax` were replaced with `css-in-js` in https://github.com/stylelint/stylelint/pull/3872.

We should remove them in the next major release.

We didn't show any deprecation notice. We can't release release new patch version with deprecation notice without making a special branch for release. Because `master` has breaking changes already.

It's should be fine. We'll address this change in release notes.

**Comment by jeddy3** [comment]
> We'll address this change in release notes.

SGTM. I think we can just remove the old `styled` and `jsx` options for 10.0.0.

**Comment by ntwb** [comment]
Changelog: https://github.com/stylelint/stylelint/commit/bfbf4629a1b7ed5d1ce6819a41cb32fca123bade
> Removed: styled and jsx syntax options that were replaced with css-in-js in v9.10.0 (#4007).
