### ISSUE TITLE
Improve publish and release process

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#401]
See https://github.com/stylelint/stylelint/issues/15#issuecomment-145299563

**Comment by jeddy3** [comment]
I need to get a new version of `stylelint-config-suitcss` out for the changes in `v3`. Should I try this release process over there and, if it works, migrate it her for `3.0.0`?

**Comment by TrySound** [comment]
@jeddy3 I like this
```
npm version patch
git push --follow-tags && npm publish
```
Nothing more :)

**Comment by MoOx** [comment]
It is clearly not enough. You need to run tests withn a fresh node_mosules folder and generate github release (nice to notify watchers about a release). That is why I created this commands.

**Comment by TrySound** [comment]
prepublish npm hook for tests. And releases do not need on every project. But maybe here.

**Comment by davidtheclark** [comment]
I'm open to whatever you all agree upon.

**Comment by jeddy3** [comment]
Done in #618
