### ISSUE TITLE
Enforce no end-of-source newline

### ISSUE THREAD

**Issue by kdex** [stylelint/stylelint#4011]
> What is the problem you're trying to solve?

I'm trying to lint end-of-source newlines; our team's policy is to strip them away. As far as I can tell, `stylelint` doesn't support this configuration. Instead, currently only the opposite is possible via `no-missing-end-of-source-newline` whose only option is `true`.

> What solution would you like to see?

Like with ESLint, the rule `no-missing-end-of-source-newline` should really offer both preferences and not assume that the final EOL is missing. Unfortunately, adding the options `always`/`never` leads to a double negative (`no-missing-end-of-source-newline`, `never`), which is a little awkward.

For clarity, this rule should be renamed to something along the lines of `end-of-source-newline` and offer the options `always` and `never`.

**Comment by jeddy3** [comment]
@kdex Thanks for the suggestion and for using the template.

> Like with ESLint, the rule no-missing-end-of-source-newline should really offer both preferences and not assume that the final EOL is missing

I think you're probably right and the rule should have been built this way.

> For clarity, this rule should be renamed to something along the lines of end-of-source-newline and offer the options always and never.

However, the rule is a few years old now and there are at least a few hundred public configs using it. We decided to minimise rule name changes around the time version 7 came out as not to inconvenience the majority of users.

As this is the first request for this code style in as many years I'm wondering if [a plugin](https://stylelint.io/developer-guide/plugins/) is the best way forward. Alternatively, we could consider adding a `false` primary option to the rule. I'm personally leaning towards to the former, but l'll label the issue up for discussion should anyone else like to chime in.

**Comment by kdex** [comment]
@jeddy3 Thank you for getting back to me so quickly.

> However, the rule is a few years old now and there are at least a few hundred public configs using it. We decided to minimise rule name changes around the time version 7 came out as not to inconvenience the majority of users.

I do get that, and it makes sense not to break configurations if it can be avoided. Though, I'm a little confused about two things:

- Like in this case, avoiding to change a rule may lead to a bogged set of rules over time. Yes, `false` may work in theory, but, like I think we both feel about this, makes the rule harder to grasp due to the double negative.
- I'm having a little trouble understanding why a plugin could avoid this breakage in the long run. Assuming the rule had been a plugin to begin with, then the plugin would have had the bogged API. I'm sure this is not the way things should be seen, but this makes it seem as if it weren't okay for `stylelint` to break things, but A-OK if its plugins do.

IMHO, remodeling mistakes from the past is a necessity for a good user experience. :smile_cat: The way I see it, the best way out of such problems is semantic versioning. If the major version number increments, users are supposed to acknowledge breakage. And if package authors are extra fancy, they even issue warnings if the user attempts to use an API that has been deprecated.

**Comment by evilebottnawi** [comment]
@jeddy3  What about implement new rule for `10` release with `true`/`false` and leave the old rule with deprecation message and remove this in `11`?

**Comment by jeddy3** [comment]
Closing [as stylistic rules are frozen](https://github.com/stylelint/stylelint/issues/5674). The community is welcome to migrate the rule [to a plugin](https://stylelint.io/developer-guide/plugins).
