### ISSUE TITLE
Fix autofix for !important annotation in declaration-block-semicolon-space-before

### ISSUE THREAD

**Issue by lennontu** [stylelint/stylelint#4016]
> Clearly describe the bug

'declaration-block-semicolon-space-before': 'never' autofix failed

> Which rule, if any, is the bug related to?

declaration-block-semicolon-space-before

> What CSS is needed to reproduce the bug?

```css
div {
  width: 50% !important   ;
}

```

> What stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  'rules': {
     'declaration-block-semicolon-space-before': 'never',
  }
}
```

> Which version of stylelint are you using?

 `9.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"CLI with `stylelint --fix "**/*.css" --config myconfig.json`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"No"

> What did you expect to happen?

"autofix success, `width: 50% !important   ;` => `width: 50% !important;`"

> What actually happened (e.g. what warnings or errors did you get)?

"autofix failed, `width: 50% !important   ;`  not change"

**Comment by jeddy3** [comment]
@lennontu Thanks for the report and for using the template.

I can reproduce this. It appears to be related to the `!important` annotation and unrelated to the primary option i.e. `"always"` or `"never"`.

As the issue has been labelled "help wanted", please consider [contributing a fix](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).
