### ISSUE TITLE
how to prevent "PX" or "Px" to be converted to  lower case

### ISSUE THREAD

**Issue by xsteadybcgo** [stylelint/stylelint#4047]
in my project , i use the postcss-plugin -- "postcss-pxtorem". This plugin will convert my css unit value 'px' to 'rem', and when you do not want this convertion , you should use "PX" or "Px" instead of "px".

eg 

`
// input less file  
  .mybox {width: 75px; border: 1PX solid #333;}  
// output less file  
 .mybox {width: 1rem; border: 1PX solid #333;}  
`

when intergrating with  stylelintint  , I don't want this tool to fix it as i hope my "px" coexit with "PX" or "Px" unit.

I have tried the options , for example:  "unit-case" , but it does not have the ignore unit option as a second option. The "white-blacklist" does not support regexp expresion but only string or []string.

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using the template.
