### ISSUE TITLE
Question - Ignore code inside simbols <% %>

### ISSUE THREAD

**Issue by jose-decima** [stylelint/stylelint#4053]
I try to ignore some lines in the CSS, but I want to maintain the line position if one error appears 
I am using EJS and pass these variables in the CSS code, but I then render in the HTML this CSS code

example :
```
/* HEADER BASE CSS */
<%
  const css = vars.css;
%>

html,
body {
  font: 9px/16px <%- css.fonts.sansSerif %>;
  margin: 10px;
  padding: 10px;
  background-color: <%- css.colors.base.red %>;
  }
```

**Comment by hudochenkov** [comment]
Stylelint doesn't support such syntaxes.

You can try to use [special comments](https://stylelint.io/user-guide/configuration/#turning-rules-off-from-within-your-css).
