### ISSUE TITLE
Add import-notation

### ISSUE THREAD

**Issue by andyearnshaw** [stylelint/stylelint#4055]
> What is the problem you're trying to solve?

We're creating web components using Shadow DOM. In many situations, the structure and style creation of our components is done off-tree and then the component is appended to the DOM. At this point, the stylesheets are parsed and the component is rendered.

If, when the component is appended to the DOM, one of the stylesheets contains an `@import url(...);` rule, parsing the remaining stylesheet is blocked until the import is completed. Therefore, we'd like to disallow `@import url()`, but allow `@import './otherfile.scss'`, which doesn't seem possible (or at least the docs doesn't make it clear how this can be done).

An emerging standard for Constructable Stylesheets also sees the introduction of a new function called `replaceSync(cssText)`, which will throw if any `@import` rules are encountered when parsing the rules.  Having a linting rule for this would mean that anyone trying to import stylesheets from a URL would be made aware at dev time rather than run time.

> What solution would you like to see?

A new rule that disables `@import url()`.  My suggestion for the name is `no-async`, both as a future proof rule name and as a nod to the `replaceSync()` method.

**Comment by hudochenkov** [comment]
According to specs:

<img width="824" alt="" src="https://user-images.githubusercontent.com/654597/56772695-5d195f80-67bb-11e9-9eaa-468ca22cbee4.png">

I guess, we can have a rule to enforce `@import` path to be `<url>` or `<string>`.

@stylelint/contributors what do you think?

* [Importing Style Sheets: the @import rule — CSS Cascading and Inheritance Level 3](https://drafts.csswg.org/css-cascade-3/#at-import)
* [Importing Style Sheets: the @import rule — CSS Cascading and Inheritance Level 4](https://drafts.csswg.org/css-cascade-4/#at-import)

**Comment by andyearnshaw** [comment]
I totally forgot that was valid in CSS, I've used `url()` exclusively for
those kinds of import for so long!

**Comment by Grawl** [comment]
Do you want to disallow any `@import`'s that will download external resource? Like `http://` or `ftp://`. If so, you need to parse import string and disallow anything that looks like an external link.

**Comment by andyearnshaw** [comment]
Yeah I think that would be the simplest solution.

**Comment by j9t** [comment]
Just for understanding, is this just for performance reasons?

**Comment by ntwb** [comment]
No objections here, I'll mark it up as _help wanted_

**Comment by andyearnshaw** [comment]
@j9t 

> Just for understanding, is this just for performance, or is there some other problem this tries to address? (Just cautious around bans, and there may be alternatives.)

Performance is part of the problem, as we were hitting flashes of unstyled content when the stylesheet for the shadow tree contained imports. I evaluated a bunch of potential alternatives, such as hiding the host until styles are loaded, but I didn't think this approach acceptable. The only thing we were waiting on was a font from typekit, it didn't make sense to hold up the rendering of the component.

Importantly, though, this rule will be useful for when `replaceSync()` reaches a later stage of adoption, as it will throw an error at runtime if asynchronous imports are used. By banning asynchronous imports in the linting stage, a developer will be warned before they attempt to run the code.

**Comment by hudochenkov** [comment]
It's not clear what was decided here.

1. Create a rule to enforce `@import url("styles.css")` or `@import "styles.css"`?
2. Create a rule to forbid external imports like `@import url("http://example.com/styles.css")`, but allow `@import url("/styles.css")`?

**Comment by andyearnshaw** [comment]
In plain CSS, both `@import url(...)` and `@import '...'` are synonymous and always asynchronous, so a new `no-async` rule would ban either forms for `.css` files.  In Sass, the following are compiled into plain (asynchronous) CSS imports, and Stylelint could ban all of these with a `no-async` rule:

- Imports where the URL ends with .css.
- Imports where the URL begins http:// or https://.
- Imports where the URL is written as a url().
- Imports that have media queries.

https://sass-lang.com/documentation/at-rules/import#plain-css-imports

**Comment by j9t** [comment]
Looks okay to me if nowhere on by default—to turn it on in the sample configs it seems too restrictive given how many good and valid use cases there are for any form of CSS import (no matter the drawbacks).

**Comment by andyearnshaw** [comment]
Of course, it would be silly to turn it on by default, it targets a very specific paradigm for shadow DOM and constructable stylesheets.

**Comment by andyearnshaw** [comment]
Are there any other use cases to warrant separating out the behaviour into separate rules? If you think of asynchronous imports as a single thing that you want to avoid, then a single `no-async-imports` rule to block it makes sense, as multiple rules to block a single thing means more chance of things slipping through.

**Comment by evilebottnawi** [comment]
@andyearnshaw it is bad idea union difference rules in one

**Comment by andyearnshaw** [comment]
@evilebottnawi I can't say that I agree, given that there are no concrete use cases for keeping them separate and a single configuration rule is much more user friendly. However, it's not a hill that I would die on and I probably haven't been using stylelint to dictate how it should be designed, and I'd be happy enough with a set of rules that achieve what I need.

**Comment by evilebottnawi** [comment]
@andyearnshaw 
> at-rule-import-whilelist-extensions/at-rule-import-whilelist-blacklist

Allow to ensure all import have right extensions, you can do typo like `@import './style.csss'` and we catch this.

> at-rule-import-no-url-function

Allow to ensure all `@import` without `url`, maybe best name `at-rule-import-notation: 'url' | 'no-url'`. Consistent `@import` at-rule style for developers.

And more.

**Comment by andyearnshaw** [comment]
Fair enough, if you think these are important use cases. FWIW, a single rule is still preferable from my point of view if I want to disable all asynchronous imports because I could potentially miss one out or misconfigure one without realising. Again, though, this isn't something I feel strongly enough about and would be happy to see this capability, so I'll say no more about it.
