### ISSUE TITLE
Breaking SCSS mixins that have maps as parameters

### ISSUE THREAD

**Issue by joneslloyd** [stylelint/stylelint#4058]
**Summary:**

SCSS mixins that have map parameters are being broken across multiple lines, seemingly regardless of settings, which results in compile errors.

**Detail:**

I have a SCSS mixin called `responsive-properties` (to help with media queries) :
https://gist.github.com/joneslloyd/17ddf3c372627e2cfdd81eca8eefe79b

When stylelint is run on an SCSS file containing this mixin, the code containing the mixin call is changed from (for example) this:
```
@include responsive-properties(((padding-left, (v: $spacer-x, v-md-up: 0)), (padding-right, (v: $spacer-x, v-md-up: 0)), (margin-left, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)), (margin-right, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)),));
```

To this:
```
@include responsive-properties(
    (
      (padding-left, (v: $spacer-x, v-md-up: 0)),
      (padding-right, (v: $spacer-x, v-md-up: 0)),
      (
        margin-left,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      ),
      (
        margin-right,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      )
    )
  );
```

And it will no longer compile. I get the error:
```
ERROR in ./styles/main.scss
Module build failed: ModuleBuildError: Module build failed:
    @if (map-has-key($attribute, v) and (index($actual-media-queries, v) == null)) {
        ^
      Argument `$map` of `map-has-key($map, $key)` must be a map
```

To be clear: It does compile perfectly without the reformatting that stylelint applies.

> Which rule, if any, is the bug related to?

I'm actually not sure.

> What CSS is needed to reproduce the bug?

Any mixin with nested map parameters:

```
@include responsive-properties(((padding-left, (v: $spacer-x, v-md-up: 0)), (padding-right, (v: $spacer-x, v-md-up: 0)), (margin-left, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)), (margin-right, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)),));
```

> What stylelint configuration is needed to reproduce the bug?

This:

```
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null,
      "at-rule-empty-line-before": null,
      "indentation": [
        2
      ]
    }
  },
```

Or this:

```
"stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "no-empty-source": null,
      "at-rule-empty-line-before": null,
      "indentation": [
        2,
        {
          "indentInsideParens": "once-at-root-twice-in-block",
          "ignore": [
            "inside-parens",
            "param"
          ]
        }
      ]
    }
  },
```

> Which version of stylelint are you using?

7.12

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

I'm running stylelint via [Vscode's Prettier extension](https://github.com/prettier/prettier-vscode)

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS nested map parameters in a mixin

> What did you expect to happen?

The mixin to remain on a single line and the code to compile.

> What actually happened (e.g. what warnings or errors did you get)?

The mixin was broken onto multiple lines and indented, and the SCSS will no longer compile:

```
ERROR in ./styles/main.scss
Module build failed: ModuleBuildError: Module build failed:
    @if (map-has-key($attribute, v) and (index($actual-media-queries, v) == null)) {
        ^
      Argument `$map` of `map-has-key($map, $key)` must be a map
```

**Comment by evilebottnawi** [comment]
As i said in previously issue, problem not in mixin, problem in other place. Please provide example with `@if` directive as you can see in error

**Comment by joneslloyd** [comment]
The example with the `@if` directive is included at the top of this issue and the other issue.

Here it is again:
https://gist.github.com/joneslloyd/17ddf3c372627e2cfdd81eca8eefe79b

(Line 5)

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by joneslloyd** [comment]
No problem!

**Comment by hudochenkov** [comment]
Because you use Prettier before stylelint, example you provided it's not what stylelint receives. What code stylelint receives after Prettier?

**Comment by joneslloyd** [comment]
Prettier does not do anything here (or at least it shouldn't), because I have directed it to rely on stylelint.

Here is my `settings.json` file:
```
{
  "atomKeymap.promptV3Features": true,
  "editor.colorDecorators": false,
  "editor.fontFamily": "'Input Mono'",
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.insertSpaces": true,
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.tabSize": 4,
  "emmet.includeLanguages": {
    "blade": "html"
  },
  "emmet.triggerExpansionOnTab": true,
  "eslint.autoFixOnSave": false,
  "eslint.alwaysShowStatus": true,
  "files.autoSave": "off",
  "files.trimTrailingWhitespace": true,
  "php.validate.enable": false,
  "php-cs-fixer.executablePath": "/usr/local/bin/php-cs-fixer",
  "php-cs-fixer.onsave": true,
  "php-cs-fixer.rules": "@PSR2",
  "php-cs-fixer.autoFixByBracket": true,
  "php-cs-fixer.autoFixBySemicolon": true,
  "php-cs-fixer.formatHtml": true,
  "php-cs-fixer.documentFormattingProvider": true,
  "prettier.eslintIntegration": true,
  "prettier.stylelintIntegration": true,
  "prettier.tabWidth": 2,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/dist/**": true,
    "**/.cache-loader/**": true
  },
  "stylelint.enable": true,
  "css.validate": false,
  "scss.validate": false,
  "workbench.colorTheme": "Cobalt2",
  "workbench.iconTheme": "vscode-great-icons",
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 0,
  "explorer.confirmDelete": false
}
```

Notice this line: `"prettier.stylelintIntegration": true` which should mean that Prettier is delegating this task to stylelint?

**Comment by hudochenkov** [comment]
This is incorrect understanding.

https://github.com/prettier/prettier-vscode:

> prettier.stylelintIntegration (default: false) - CSS, SCSS and LESS only
> Use prettier-stylelint instead of prettier.

https://github.com/hugomrdias/prettier-stylelint:

> code > prettier > stylelint > formatted code
>
> prettier-stylelint attempts to create a prettier config based on the stylelint config, then format with prettier followed by stylelint --fix.

[This is how](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgCc4BnAB2hMwDc4BaMwiMuQmTUgCgBJHnX2pAJT5gAHQL5uAQzAwArtIA2ddHAAmmaXQCO81hxJJ8ABgA0pi+cs3rdqw9uP7pgNwSJ+fKjiyAFlJ8LGwAnhYyMDCEmABG8vD4eIFMwYIkop5e3pgAZvic6NJkdH7SJHQA1nAhPNKR0XHwFtQi0lDq+XjqcNi1cooqapraegakzSIAvJP4UPJKSkIi4pJZUrIKyqoaWrr60aTGxGRKsvSwfn2bgzsj+4YWAIwT7qv4AL4eb6i5+YXFpXKVRqESisXicGadGwJFa7U67R6VwG22GezGJChMKmMzmCyWGTeXhk-S2Q12owORiIcBOZzoF2RZNu6KpFgATFjYa81p8oJkvD88gUiiUypVqrV6uCmvhqHQSOg6OoIAB3KBwjqcLpIknXVEU+7jOUKpUq9U42bzRbLAVZPUo8l3DFHWmnMDnGCXB3MtGUh74ADMUMVyrVGp5WT5dqFf1FgIlILqYMakJNofkZE1CO6vR9Nz9Rsx6aVmcteJthLWxI2jpZ-sONLpHoZXqZBcNGIsABYQ6Ws5GvNHvr8RQDxcCpSmIX3s9rEXna77O2yS+XrQSVtX1qSO86qa7m57vUu96yAwBWWeDj5fNaxsdioGS0ENGcm9DqMMW-BtLU6xddwNfcA3lT9vw1fBpitfFbSJHd9Sdc9G2Od1j3bYDkOLAA2KFwPNCM7WHe9R3+J9EynN9ZTAr8y1-eF51zDCkIbYsaLoOjoIrTc7RrICWKLQ80NbE9+PrIsLAAdjw2iByIu8sgfMiE0nV8ZTTGi5wA5jxK7D91HXWCq2rfNMNYoT6UZUyBL0gAOGShBvYjFNI+MJxfZMqI0uglAAcwgrSFx0ws9PlPyAqg3ENzg7drN0g8m2EqzTzMiT8AATihcKCMc+T+RHYVlPcpNpVTLL-Lov8c11FKbNXMKKqzSKYMrLcTNq+LDAsltkrEkLV0eawGo4uS3mcwVXPHZ8SunaifN8wKmLi-rQPmwzWt4hC6xWlC3UsttlpXANHmeE0-NysaFImwq3Omyj1KxFRKoY7TDpA415WwJ6mq46LjLWN6sO69DAdYp5ORNL6Rou3kruyG6pootSyshlQcvo-8gtBtLPrR8N1p4+DsZdRL9tExDOuNR5g1RgKnLhpTbqRzyHtRxaar6o6PuhRZmu4mL2s597qVQsngq54tHl7Nn6fykiEfI1SWZRz6oeezGlo6na2OhNWfqioy2oBrWJeBkTxeFp4r0hvWYajBnJsVjzSvfVW8Z-KrGI5intaxKH0d+w3NuJhLRZ6g6Tct-BHlwm33cIy7JGcnx-CkOqQkSAgQ8Mf74fybh0+alpc8FXwwACXgUgEMJ1hdhIkkr-g2Bzo3qwAYmARvUhCd5jDI3y4Bge6Vbt2HE5jUcC-ijPoM+2ES+yKAwCUeRunwJCYmIaQKgoPAYAgzhsQX0vU676vwmViFM+SJu0mPrIO7P0Je-X0UB6H5HXehblNqHTa+THhPYUU9+ozxmPKUM6NW4TSXivNeG8t47wgHvA+ioBbbhTuXG+3cL51zgNfJ+d9oHt07kEauL9+6D2Hl-SB+Mbxj23AA+2csXLAMLrPU00MF4-FgavfBCDfBIJQZmTgaD76YIrmQ0IuDZr4IblIohv8H6kKrs-Pub8qGfzmhmUa24-7wSYfooB+d2HgNNOglyvD4Esk3oI3esA6DQCUDUMRxCT5YMITXLRcis4KJbkorwj8FE93UcUd+1DtHoFHtWQxzDAEFRMdPIuqgvxQM2jw5efD142MQfY-eBECgGXEWXSRqiYBeMvvXXxZT-HwTWEEspITX5hM0ZU7y+E6FKNifo+J8tEmgOSeBOixCMlwP4TkuxyCHEiM-BY+8JTsHn1rrIghfjSD30CSo2+TTKEfzaTJaG9C4kxLysYngpj9JzMXpk6xaJbHbzyY4qAzjClXPcaU7ZMivKrJqestxyjPEUI0XsvBDkjk9JOePBJ5ykkcOyvjbheAbnjLubkqZ+TwycHOsU0+wSvnqR+bfWpeiAXBKBS0kFsjyp0y6f-U50KQErjAWdRqVzRlZIEQ89FI0sULRxR4vFyzvnyN+ekf5mzAWhLoOE7x1KyzgtvAY+lfSYUDLhXykZSKxnZNRZMlBTiajYv+RIxZ0ihUEpFUSv5AT8ANO2eS6VrTQUsuiQwyFvTWH9KZck-2CLNVWJRbse5QiHEFK+m87wCzPH4tTIS1IxKSW2q2d3B1Mr9m0xygq7piqPXXS9fuZluMuH+uRTqoNaLhFkEPrzY1UbBXeLjQIBNJK7UpqlWm51Rb5W0qVVClVjKC0+prekrVHKJlcv1c8mo4b+UfJwea2Nlr43WrqaSxpqanVUplj2xhyrPWqu9Rw7Avqfwlu1ZykNGL1SHxnbW3FjSY1XyXU2ldiak2SuaY6ylXk-bx1dcct1RiGUXLdsWkdAay3aGDY8kRx7h2rpNdGhdT7qlWrFTa1t5D22bp-XHQ5O73XHL5O8EAZgQDMHYJQZAoBpCECYKqAACrRhAJBkAgGkNQZB6hSMgE3rIKoMAADKZBZB4F8sgKI+gyN+BgOgJQAB1PwmB4DkDOIJljymaDKZCGxsAJBWNkbwCQAQDHCDSF8oUZAORlDGbIwAKxINgAAQmZsAAnBPSDUAAGTwHAKzNnIQgAc9gQTYmlBwAAIryAgPAfzShbMgBE4QYzhA2MkD0wZxL0RYDycwOoL0yBbLmCyxAYz8mzNkDY4wUgrBaA8b0DFuApnmCsZQOKKAcANAaB48QPQmBiCmfM5ZpA1n4uBeM1gCThApMgCoFAXy4WouNbiwlmA0gYi5fy34ZAnIQBRGkJgJQYmADCEB0DDZAFAaAfmyPyGMwAFXW610bxn3jvCAA) your mixin looks like after Prettier alone (if I configured Prettier correctly according to your config).

I would suggest to investigate what happens yo your code during prettier-stylelint cycle.

1. How the code look like after Prettier? Is it still vaild SCSS?
2. Does stylelint 10.0.1 (the latest stylelint) breakes the code it receives.

As it stylelint repository, we're not going to investigate it as it related to other tool, which we don't develop. If you investigate it, we can look into the problem, if it's stylelint's problem. For now your original mixin code doesn't show any warnings with your config.

**Comment by joneslloyd** [comment]
Thanks for getting back to me.

I think there may have been some mis-understandings though:

1) The problem is not with the formatting of my mixin, but where the mixin is called
2) My mixin actually looks [the same as your code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgCc4BnAB2hMwDc4BaMwiMuQmTUgCgBJHnX2pAJT5gAHQL5uAQzAwArtIA2ddHAAmmaXQCO81hxJJ8ABgA0pi+cs3rdqw9uP7pgNwSJ+fKjiyAFlJ8LGwAnhYyMDCEmABG8vD4eIFMwYIkop5e3pgAZvic6NJkdH7SJHQA1nAhPNKR0XHwFtQi0lDq+XjqcNi1cooqapraegakzSIAvJP4UPJKSkIi4pJZUrIKyqoaWrr60aTGxGRKsvSwfn2bgzsj+4YWAIwT7qv4AL4eb6i5+YXFpXKVRqESisXicGadGwJFa7U67R6VwG22GezGJChMKmMzmCyWGTeXhk-S2Q12owORiIcBOZzoF2RZNu6KpFgATFjYa81p8oJkvD88gUiiUypVqrV6uCmvhqHQSOg6OoIAB3KBwjqcLpIknXVEU+7jOUKpUq9U42bzRbLAVZPUo8l3DFHWmnMDnGCXB3MtGUh74ADMUMVyrVGp5WT5dqFf1FgIlILqYMakJNofkZE1CO6vR9Nz9Rsx6aVmcteJthLWxI2jpZ-sONLpHoZXqZBcNGIsABYQ6Ws5GvNHvr8RQDxcCpSmIX3s9rEXna77O2yS+XrQSVtX1qSO86qa7m57vUu96yAwBWWeDj5fNaxsdioGS0ENGcm9DqMMW-BtLU6xddwNfcA3lT9vw1fBpitfFbSJHd9Sdc9G2Od1j3bYDkOLAA2KFwPNCM7WHe9R3+J9EynN9ZTAr8y1-eF51zDCkIbYsaLoOjoIrTc7RrICWKLQ80NbE9+PrIsLAAdjw2iByIu8sgfMiE0nV8ZTTGi5wA5jxK7D91HXWCq2rfNMNYoT6UZUyBL0gAOGShBvYjFNI+MJxfZMqI0uglAAcwgrSFx0ws9PlPyAqg3ENzg7drN0g8m2EqzTzMiT8AATihcKCMc+T+RHYVlPcpNpVTLL-Lov8c11FKbNXMKKqzSKYMrLcTNq+LDAsltkrEkLV0eawGo4uS3mcwVXPHZ8SunaifN8wKmLi-rQPmwzWt4hC6xWlC3UsttlpXANHmeE0-NysaFImwq3Omyj1KxFRKoY7TDpA415WwJ6mq46LjLWN6sO69DAdYp5ORNL6Rou3kruyG6pootSyshlQcvo-8gtBtLPrR8N1p4+DsZdRL9tExDOuNR5g1RgKnLhpTbqRzyHtRxaar6o6PuhRZmu4mL2s597qVQsngq54tHl7Nn6fykiEfI1SWZRz6oeezGlo6na2OhNWfqioy2oBrWJeBkTxeFp4r0hvWYajBnJsVjzSvfVW8Z-KrGI5intaxKH0d+w3NuJhLRZ6g6Tct-BHlwm33cIy7JGcnx-CkOqQkSAgQ8Mf74fybh0+alpc8FXwwACXgUgEMJ1hdhIkkr-g2Bzo3qwAYmARvUhCd5jDI3y4Bge6Vbt2HE5jUcC-ijPoM+2ES+yKAwCUeRunwJCYmIaQKgoPAYAgzhsQX0vU676vwmViFM+SJu0mPrIO7P0Je-X0UB6H5HXehblNqHTa+THhPYUU9+ozxmPKUM6NW4TSXivNeG8t47wgHvA+ioBbbhTuXG+3cL51zgNfJ+d9oHt07kEauL9+6D2Hl-SB+Mbxj23AA+2csXLAMLrPU00MF4-FgavfBCDfBIJQZmTgaD76YIrmQ0IuDZr4IblIohv8H6kKrs-Pub8qGfzmhmUa24-7wSYfooB+d2HgNNOglyvD4Esk3oI3esA6DQCUDUMRxCT5YMITXLRcis4KJbkorwj8FE93UcUd+1DtHoFHtWQxzDAEFRMdPIuqgvxQM2jw5efD142MQfY-eBECgGXEWXSRqiYBeMvvXXxZT-HwTWEEspITX5hM0ZU7y+E6FKNifo+J8tEmgOSeBOixCMlwP4TkuxyCHEiM-BY+8JTsHn1rrIghfjSD30CSo2+TTKEfzaTJaG9C4kxLysYngpj9JzMXpk6xaJbHbzyY4qAzjClXPcaU7ZMivKrJqestxyjPEUI0XsvBDkjk9JOePBJ5ykkcOyvjbheAbnjLubkqZ+TwycHOsU0+wSvnqR+bfWpeiAXBKBS0kFsjyp0y6f-U50KQErjAWdRqVzRlZIEQ89FI0sULRxR4vFyzvnyN+ekf5mzAWhLoOE7x1KyzgtvAY+lfSYUDLhXykZSKxnZNRZMlBTiajYv+RIxZ0ihUEpFUSv5AT8ANO2eS6VrTQUsuiQwyFvTWH9KZck-2CLNVWJRbse5QiHEFK+m87wCzPH4tTIS1IxKSW2q2d3B1Mr9m0xygq7piqPXXS9fuZluMuH+uRTqoNaLhFkEPrzY1UbBXeLjQIBNJK7UpqlWm51Rb5W0qVVClVjKC0+prekrVHKJlcv1c8mo4b+UfJwea2Nlr43WrqaSxpqanVUplj2xhyrPWqu9Rw7Avqfwlu1ZykNGL1SHxnbW3FjSY1XyXU2ldiak2SuaY6ylXk-bx1dcct1RiGUXLdsWkdAay3aGDY8kRx7h2rpNdGhdT7qlWrFTa1t5D22bp-XHQ5O73XHL5O8EAZgQDMHYJQZAoBpCECYKqAACrRhAJBkAgGkNQZB6hSMgE3rIKoMAADKZBZB4F8sgKI+gyN+BgOgJQAB1PwmB4DkDOIJljymaDKZCGxsAJBWNkbwCQAQDHCDSF8oUZAORlDGbIwAKxINgAAQmZsAAnBPSDUAAGTwHAKzNnIQgAc9gQTYmlBwAAIryAgPAfzShbMgBE4QYzhA2MkD0wZxL0RYDycwOoL0yBbLmCyxAYz8mzNkDY4wUgrBaA8b0DFuApnmCsZQOKKAcANAaB48QPQmBiCmfM5ZpA1n4uBeM1gCThApMgCoFAXy4WouNbiwlmA0gYi5fy34ZAnIQBRGkJgJQYmADCEB0DDZAFAaAfmyPyGMwAFXW610bxn3jvCAA) when I format it with Prettier and Prettier Stylelint. The issue is that the calls to my mixin like this:
```
@include responsive-properties(((padding-left, (v: $spacer-x, v-md-up: 0)), (padding-right, (v: $spacer-x, v-md-up: 0)), (margin-left, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)), (margin-right, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)),));
```
...are messed up and changed to this:
```
@include responsive-properties(
    (
      (padding-left, (v: $spacer-x, v-md-up: 0)),
      (padding-right, (v: $spacer-x, v-md-up: 0)),
      (
        margin-left,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      ),
      (
        margin-right,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      )
    )
  );
```
...and it won't compile.

**Comment by hudochenkov** [comment]
Looks like it's still [prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAllMAbArgEzgAIAnOAZwAdpz0A3OAWkpIkrhJnQoAo-KAhvnyYA5o2xwAZjAA0RHnSREAJFQFgOjAB7y6jALb5GuSsoAMASkvyeg4WMYl0ogBZyFS1es0kdew2NTC2tbAwESUUwJaQ9FZR4VUWdjUVwYeD8Ad3R8GFciAHoiRgBGGyJ9cgMTMwUklMY0jK0cvILixgAmCv0jWpCKnnDI6Oc3OK9E5Nym9MzGNvyikvKA6oH6mdT51tzlzp6A-uCiKxtrAG4QWRA2LhpkUAjWLIAFCIRyZBABOghcjcQAAjEgaADWcBgAGVBGAxMgYCRcHBbu4DNgAOqudDwHxwaFfXH0XEATx+YHI31umHIHBgbzBonCyCkAmwdNuACtyNoAEJgsCQmECAxwAAymDgrPZnJAPO00LEkgAirgIPAZRzUSBBCQ6SQfuRKdTdc5YJj9q5kAAOcy3FgQOmYsGUH4sCgcBhAgCO6vgjLY3xQAnIjCgcDghHwQLIfvQZEZAmZAi1crpBnQiOROtoUFEqv90qQbO1txgAmBlvayC65bB6GwYgAwhADCyUFBoNLbrg6QAVSvB0t0gC+o6AA) messing.

**Comment by joneslloyd** [comment]
Do you mean the problem is with Prettier, not stylelint?

**Comment by hudochenkov** [comment]
I think so, you can [see yourself](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAllMAbArgEzgAIAnOAZwAdpz0A3OAWkpIkrhJnQoAo-KAhvnyYA5o2xwAZjAA0RHnSREAJFQFgOjAB7y6jALb5GuSsoAMASkvyeg4WMYl0ogBZyFS1es0kdew2NTC2tbAwESUUwJaQ9FZR4VUWdjUVwYeD8Ad3R8GFciAHoiRgBGGyJ9cgMTMwUklMY0jK0cvILixgAmCv0jWpCKnnDI6Oc3OK9E5Nym9MzGNvyikvKA6oH6mdT51tzlzp6A-uCiKxtrAG4QWRA2LhpkUAjWLIAFCIRyZBABOghcjcQAAjEgaADWcBgAGVBGAxMgYCRcHBbu4DNgAOqudDwHxwaFfXH0XEATx+YHI31umHIHBgbzBonCyCkAmwdNuACtyNoAEJgsCQmECAxwAAymDgrPZnJAPO00LEkgAirgIPAZRzUSBBCQ6SQfuRKdTdc5YJj9q5kAAOcy3FgQOmYsGUH4sCgcBhAgCO6vgjLY3xQAnIjCgcDghHwQLIfvQZEZAmZAi1crpBnQiOROtoUFEqv90qQbO1txgAmBlvayC65bB6GwYgAwhADCyUFBoNLbrg6QAVSvB0t0gC+o6AA). This code then goes to stylelint.

**Comment by joneslloyd** [comment]
Thanks for confirming – It does seem that you're right. Thanks! – I'll open an issue with Prettier.
