### ISSUE TITLE
Is there a rule for commas in import statements? URLs should not have spaces...

### ISSUE THREAD

**Issue by pixelmord** [stylelint/stylelint#407]
I get an error linting the following:
@import url(https://fonts.googleapis.com/css?family=Open+Sans:700,700italic,600,600italic|Roboto);

The error is:
7:66	⚠  Expected single space after "," (media-query-list-comma-space-after) [stylelint]
7:76	⚠  Expected single space after "," (media-query-list-comma-space-after) [stylelint]
7:80	⚠  Expected single space after "," (media-query-list-comma-space-after) [stylelint]

Could a rule like this help?
        'import-comma-space-before': ['never'],
        'import-comma-space-after': ['never'],

**Comment by TrySound** [comment]
these rules shouldn't work in `url` function

**Comment by jeddy3** [comment]
@pixelmord Thanks for reporting!

@TrySound Yep, they shouldn't. They seem to be erroneously checking all at-rules rather than just at-media ones. Hopefully tightening it up we fix this. I'll try to quash it this afternoon.

**Comment by jeddy3** [comment]
@pixelmord Fixed in `1.2.1`. Do you want to see how you get on with that release?
