### ISSUE TITLE
Wrong example cli except files

### ISSUE THREAD

**Issue by dartess** [stylelint/stylelint#4077]
> Clearly describe the documentation issue

https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md wrong example except files?

> What solution would you like to see?

stylelint 10.0.1:
```
stylelint "**/*.css, !**/docker/**"
```
Error: No files matching the pattern <...> were found.
```
stylelint "**/*.css" "!**/docker/**"
```
Works correct

**Comment by hudochenkov** [comment]
Thank you for spotting this! Would you mind [sending a PR with the fix](https://github.com/stylelint/stylelint/edit/master/docs/user-guide/cli.md)?
