### ISSUE TITLE
Declare seperate rules for different filetypes in 1 .stylelintrc

### ISSUE THREAD

**Issue by DavidVaness** [stylelint/stylelint#4079]
Hey guys, first of all thank you for creating this valuable tool.

> What is the problem you're trying to solve?

I would like to be able to have 1 .stylelintrc in my project and declare a specific set of rules for each filetype. e.g.: a ruleset for scss files and a specific ruleset for .vue files.

I know it is possible to have 2 seperete .stylelintrcs and declare different filetypes for each and run them with seperate cli commands. However in my specific project is a lot of legacy code and the .stylelintrc provides the developers with valuable inline help (PHPStorm). So being able to set up which rules apply to which filetype in only 1 .stylelintrc would be very valuable to me. Am I missing some way to set this up?

> What solution would you like to see?

Not sure what the best approach to implement this would be. I am totally open to suggestions and my colleagues and I could set some time aside to implement this.

Best regards
David

**Comment by hudochenkov** [comment]
This is a good idea! Solution for it is described in https://github.com/stylelint/stylelint/issues/3128 but it's not implemented yet.
