### ISSUE TITLE
Rules to avoid using overflow scroll but auto 

### ISSUE THREAD

**Issue by dbendaou** [stylelint/stylelint#4084]
> What is the problem you're trying to solve?

I would like to avoid using `overflow: scroll` as it cause the scroll bar to appear on Microsoft even if there's nothing to scroll.

> What solution would you like to see?

I would like to have a rule who will forbidden the usage of `overflow: scroll` in favor of `overflow: auto` as auto doesn't show any scroll bar if there's nothing to scroll.

**Comment by evilebottnawi** [comment]
https://stylelint.io/user-guide/rules/declaration-property-value-blacklist/ ?

**Comment by dbendaou** [comment]
Well, that's exactly what I was looking for ! Thanks and sorry for the noise 🙈
