### ISSUE TITLE
Sponsor button

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#4087]
No template :smile: 

Add `Sponsor` button https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository.

Don't have rights on this.

**Comment by hudochenkov** [comment]
I've created https://github.com/stylelint/.github/blob/master/FUNDING.yml which will be used for every repository automatically, when sponsorship is enabled.

I enabled it for:

- [stylelint](https://github.com/stylelint/stylelint)
- [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)
- [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended)
- [stylelint.io](https://github.com/stylelint/stylelint.io)
- [stylelint-demo](https://github.com/stylelint/stylelint-demo)

**Comment by ntwb** [comment]
Nice, thanks Aleks 💯
