### ISSUE TITLE
Add description for every CLI argument

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4094]
> Clearly describe the documentation issue

All CLI arguments descriptions are scattered all over documentation. There is no single place to find them.

> What solution would you like to see?

Add description of every CLI argument similar to what `stylelint --help` does.

**Comment by ntwb** [comment]
Sounds good to me, I got caught out by this recently looking for a CLI reference, it was due to a v10 feature that I was looking for in a v9 install.

Having this centrally documented would indeed be great IMHO
