### ISSUE TITLE
Add support for SCSS syntax to API/CLI

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#410]
Re: https://github.com/stylelint/stylelint/issues/394#issuecomment-144731465

**Comment by davidtheclark** [comment]
@jeddy3 : I would like to resolve this before we release, because I think I'll have it done within the day or tomorrow. That ok?

**Comment by davidtheclark** [comment]
I'm wondering if we should change the `css` option name in the standalone API, because it might not always be CSS once we introduce this change. Anybody have any other ideas?

**Comment by jeddy3** [comment]
>  I would like to resolve this before we release, because I think I'll have it done within the day or tomorrow. That ok?

Groovy with me.

> I'm wondering if we should change the css option name in the standalone API

Good point. `input` or maybe `string`...?
