### ISSUE TITLE
Can't get --fix working for indentation

### ISSUE THREAD

**Issue by Troncoso** [stylelint/stylelint#4106]
> Clearly describe the bug

I'm attempting to integrate stylelint with a vue project. I would like to use the --fix flag to auto address anything fixable. I know that this list is limited, but I know for sure that the indent rule is supported, but it is not getting fixed.

> Which rule, if any, is the bug related to?

indentation

> What CSS is needed to reproduce the bug?

```scss
.testclass {
  background-color: blue;
}
```

> What stylelint configuration is needed to reproduce the bug?

```javascript
module.exports = {
    processors: ['stylelint-processor-html'],
    extends: 'stylelint-config-standard',
    rules: {
        'indentation': 4
    }
};
```

> Which version of stylelint are you using?

`^10.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

My initial script in my package.json looks like this:

`vue-cli-service lint && stylelint --fix **/*.{vue,scss} --syntax scss`

In order to try and isolate the issue, I tried this as well:

`npx stylelint **/*.{vue,scss} --syntax scss --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No. While I am testing with an scss file, the content is pure CSS

> What did you expect to happen?

Expected rules to be fixed automatically

> What actually happened (e.g. what warnings or errors did you get)?

The errors are simply reported in the console

```shell
src/assets/styles/app.scss
 2:3  ×  Expected indentation of 4 spaces   indentation
```

**Comment by Troncoso** [comment]
I apologize. With all the input on the screen, I missed this message:
`Autofix is incompatible with processors and will be disabled. Are you sure you need a processor?`

Since I would like to use this for .vue files, is there anyway around needing the stylelint-processor-html processor?

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Remove ` --syntax scss` from npm scripts, and `processors: ['stylelint-processor-html'],` from config. stylelint automatically detects syntax. Also it supports Vue components out of the box.

**Comment by Troncoso** [comment]
Thank you very much! That worked as expected

**Comment by Liusq-Cindy** [comment]
> Thanks for the report and for using the template.
> 
> Remove ` --syntax scss` from npm scripts, and `processors: ['stylelint-processor-html'],` from config. stylelint automatically detects syntax. Also it supports Vue components out of the box.

I remove the processors: ['stylelint-processor-html'],` from config. stylelint, it really can automatically detects ayntax, but another question shows: when i "npm run dev"， the project faild to compile, it show "Unknown word   CssSyntaxError" in .vue files.
