### ISSUE TITLE
Document and finish testing CLI & API

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#411]
re: https://github.com/stylelint/stylelint/pull/380

**Comment by davidtheclark** [comment]
@jeddy3 : I have a decent start on splitting this stuff up that I'll try to submit as a PR before work this morning.

**Comment by jeddy3** [comment]
Oh good stuff. I was going to make a start on this myself today, but you beat me too it :)

**Comment by davidtheclark** [comment]
Feel free to build on what's there if you like the start: I might not be able to work on this again until after Wednesday.

**Comment by jeddy3** [comment]
Done in #412
