### ISSUE TITLE
Not working: "block-closing-brace-empty-line-before": ["never", { except: ["after-closing-brace"] }]

### ISSUE THREAD

**Issue by rosinfotech** [stylelint/stylelint#4112]
.stylelintrc:

{
…
   "rules": {
…
      "block-closing-brace-empty-line-before": ["never", { except: ["after-closing-brace"] }],
…
}

and my less:

@front: #fafafa;
@background: #e339a4;

li {
   background: @background;
   border: 1px solid darken(@background, 25%);
   color: @front;
   display: inline-block;
   min-width: 200px;
   padding: 10px;
   > a {
      color: @front;
   }}

and this result of --fix using:

@front: #fafafa;
@background: #e339a4;

li {
   background: @background;
   border: 1px solid darken(@background, 25%);
   color: @front;
   display: inline-block;
   min-width: 200px;
   padding: 10px;

   > a {
      color: @front;
   }<<< EXPECT AN EMPTY LINE HERE
}

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using the template.
