### ISSUE TITLE
--fix removes all media queries despite no errors?

### ISSUE THREAD

**Issue by Meekohi** [stylelint/stylelint#4115]
I might be just super lost but... example file:

```
// test.sass
.test
  display: flex

  @media (max-width: 800px)
    border: 0
```

`stylelint --syntax sass "test.sass"` -- no output.
`stylelint --syntax sass "test.sass" --fix` edits the file anyway:

```
// *test.sass
.test
  display: flex
```

am I missing something?

**Comment by Meekohi** [comment]
```
$ stylelint -v
10.1.0
```

**Comment by Meekohi** [comment]
```
$ cat .stylelintrc 
{
  "rules": {
    "color-no-invalid-hex": true,
    "declaration-colon-space-after": "always",
    "color-hex-case": "lower",
    "no-eol-whitespace": true,
  }
}
```

**Comment by Meekohi** [comment]
Doesn't seem like it depends on the `.stylelintrc` -- does `--fix` try to fix things that aren't in `.stylelintrc`?
```
{
  "rules": {
    "color-no-invalid-hex": true,
  }
}
```

**Comment by Meekohi** [comment]
Maybe related to https://github.com/stylelint/stylelint/issues/3274?

**Comment by hudochenkov** [comment]
Thank you for the report!

I can reproduce this bug. Even with no rules applied. Looks like it's a problem with [postcss-sass](https://github.com/AleshaOleg/postcss-sass) parser we use to work with .sass files. It ignores nested `@media` rules.

cc @AleshaOleg

**Comment by AleshaOleg** [comment]
I implemented basic support for media rules - https://github.com/AleshaOleg/postcss-sass/pull/98
Will write more tests, and will release new `postcss-sass` version
