### ISSUE TITLE
Migrate Travis CI to `.com` from `.org`

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#4116]
This issue is for tracking the migration from Travis CI `.org` to `.com`

More details: https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

The following stylelint repos require migration:

- [x] stylelint
- [x] stylelint-demo
- [x] stylelint.io
- [x] stylelint-config-recommended
- [x] stylelint-config-standard
- [x] eslint-config-stylelint
- [x] jest-preset-stylelint 

(Sucessfully migrated repos will have a checkmark added)

**Comment by ntwb** [comment]
All repos have now been migrated to Travis CI `.com`

All repos are passing ✅

They can be seen at https://travis-ci.com/stylelint/

**Comment by hudochenkov** [comment]
We probably need to remove Travis service at the bottom of the https://github.com/stylelint/stylelint/settings/installations

**Comment by ntwb** [comment]
Done, removed from all affected repos
