### ISSUE TITLE
Document Custom Syntax API

### ISSUE THREAD

**Issue by brandonkal** [stylelint/stylelint#4118]
> Clearly describe the documentation issue

The custom syntax API such as "css-in-js" is not documented.

> What solution would you like to see?

I see in another issue that there is talk of depreciating the custom processor API. That cannot take place until the new API is documented on the website.

**Comment by hudochenkov** [comment]
What exactly is the problem you're facing? stylelint automatically detects syntax, so `--syntax` option is the last resort. `css-in-js` supported out of the box.

**Comment by brandonkal** [comment]
@hudochenkov 

The problem I am seeing is that the out of the box "css-in-js" support does not appear to understand interpolations. See [my comment here](https://github.com/callstack/linaria/issues/440#issuecomment-502822722). From what I can tell, getting things to work properly would require either fixing postcss-jsx or writing another syntax processor.

For instance, I am looking into a modifier syntax such as this:
```js
const Button = styled.div`
  ${[props.primary && props.disabled]} {
       /* styles */
  }
`
```
The babel rewrites that condition inside an array literal as a classname selector. Stylelint would need some way of knowing this. This is currently handled by the processor, but as the syntax option now preferred to allow `--fix`, I would need documentation on how to write such a syntax.

**Comment by hudochenkov** [comment]
> The problem I am seeing is that the out of the box "css-in-js" support does not appear to understand interpolations. See [my comment here](https://github.com/callstack/linaria/issues/440#issuecomment-502822722).

It does understand them. I'll response on this topic in mentioned issue.

> From what I can tell, getting things to work properly would require either fixing postcss-jsx or writing another syntax processor.

> I would need documentation on how to write such a syntax

Stylelint could use any PostCSS syntax. Here is the documentation how to [make one](https://github.com/postcss/postcss/blob/master/docs/syntax.md). But it's better to improve current [CSS-in-JS syntax](https://github.com/gucong3000/postcss-jsx), instead of creating a new one.

> For instance, I am looking into a modifier syntax such as this:

I don't see any problem with this code. You can try it in demo. E. g. for the following it correctly reports unknown property:

```js
const Button = styled.div`
&${[props.primary && props.disabled]} {
  asdf: none;
}
`;
```

**Comment by brandonkal** [comment]
Thanks for the link to the PostCSS syntax documentation! That was what I was looking for. So this issue could be resolved with a link to that documentation in the [Stylelint Ecosystem Guides](https://stylelint.io/developer-guide/#ecosystem-guides).

Improving the current CSS-in-JS syntax is preferred but pre-evaluation would only make sense for linaria currently.

> I don't see any problem with this code.

This is interesting. So it looks like the postcss-jsx syntax is including interpolations when they appear as a selector, property, or value in a declaration, but ignoring them otherwise.

**Comment by hudochenkov** [comment]
@brandonkal Would you mind contributing a fix, please?
