### ISSUE TITLE
prevent non css syntax in pure css file

### ISSUE THREAD

**Issue by Airkro** [stylelint/stylelint#4122]
> What is the problem you're trying to solve?

strict syntax check for scss/sass/less/css

> What solution would you like to see?

when using scss/sass/less syntax in a '.*css' file, stylelint should report error

**Comment by evilebottnawi** [comment]
Out of scope for stylelint you can create own rule for this

**Comment by Airkro** [comment]
I don't this can be solved by a rule. It might be a doomsday breaking change.

Stylelint is powerful, but as a linter, why stylelint allow non-css syntax in a pure css file?

![image](https://user-images.githubusercontent.com/12206891/59896587-b7314c80-941b-11e9-8426-f007ae2fdcfd.png)

**Comment by evilebottnawi** [comment]
Can you provide example of problem, can't understand you

**Comment by hudochenkov** [comment]
Stylelint doesn't validate syntax. We can't know if syntax incorrect or now based on content of a file and extension. I'm afraid you have to verify yourself that files are named correctly.

**Comment by sebastian-nowak** [comment]
If that's the case, what's the purpose of the `--syntax scss` CLI switch?

**Comment by Airkro** [comment]
@sebastian-nowak In fact, I didn't use that for a long time

**Comment by Airkro** [comment]
@hudochenkov

The file extension is not the point(but we do need overrides by file extension).

I mean `eslint` doing great because everything not in Specification will not pass unless we allow it. It can make sure the code is browser-ready.
