### ISSUE TITLE
Rule Idea: Option for rule-empty-line-before

### ISSUE THREAD

**Issue by stevefulghum** [stylelint/stylelint#4123]
> What is the problem you're trying to solve?

I have a rule with many properties, followed by a number of sub-rules. For better legibility, and to see where the properties end and the sub-rules begin, I'd like to require a line of white space.

I have "rule-empty-line-before" set to "never-multi-line", so adding an empty line between the properties and my first nested selector throws an error.

While there are a few options through "except" and "ignore" for rule-empty-line-before, they don't do _quite_ what I need it to do, and I expect other users may have this issue.

"except" and "inside-block-and-after-rule" work, but require empty lines before _every_ sub-rule. I'm just trying to focus on the first sub-rule after properties.

"except" and "first-nested" only works if the nested rule is the first child of the parent, and I have properties that come before it.

"ignore" and "inside-block" works, and does provide a good, temporary solution, but I'd still like to enforce "never-multi-line" for subsequent nested rules.

> What solution would you like to see?

I'd like to have a new exception option for "rule-empty-line-before", and I suggest "inside-block-and-after-property".

Therefore, given the sytlelint option and classes below, there would be no errors thrown for the white space between "color: chartreuse" and ".a-sub-class":

```
// .stylelintrc
"rule-empty-line-before": [
  "never-multi-line",
  {
    "except": [
      "inside-block-after-property"
    ]
  }
]

// style.scss

.some-other-class {
  font-weight: bold;
}
.my-important-class {
  display: grid;
  position: relative;
  font-family: comic-sans;
  color: chartreuse
  
 .a-sub-class {

  }
}
.another-example-class {
  display: none;
}
```

**Comment by hudochenkov** [comment]
Try the following:

```
'rule-empty-line-before': ['always', {
    except: ['first-nested', 'after-rule'],
    ignore: ['after-comment'],
}],
```

**Comment by hudochenkov** [comment]
I'm closing the issue because of inactivity. Feel free to comment to continue discussion.
