### ISSUE TITLE
Support schema.json for better editor support

### ISSUE THREAD

**Issue by snebjorn** [stylelint/stylelint#4138]
> What is the problem you're trying to solve?

[Schema.json](https://json-schema.org/) will give editors auto-completion and schema validation support in .stylelintrc.json.

> What solution would you like to see?

A schema.json file distributed with the npm package.

Then inside .stylelintrc.json it'll look like this

```json
{
  "$schema": "./node_modules/stylelint/config/schema.json",
  "extends": "stylelint-config-standard",
  "rules": {
    // your overrides or custom rules here
  }
}
```

**Comment by evilebottnawi** [comment]
We don't disturb json schema, please open issue in your IDE

**Comment by snebjorn** [comment]
Distributing the schema for a stylelint config with an IDE/plugin for IDE isn't the right solution.

For example Angular does it. So inside angular.json you have:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
   ...
}
```

**Comment by evilebottnawi** [comment]
> Distributing the schema for a stylelint config with an IDE/plugin for IDE isn't the right solution.

We don't disturb json schema

**Comment by snebjorn** [comment]
If others are looking for this. There's one available here: http://json.schemastore.org/stylelintrc.json
