### ISSUE TITLE
How am I supposed to make the linter locate this mistake ?

### ISSUE THREAD

**Issue by Spanoudakhs** [stylelint/stylelint#4145]
![Screenshot from 2019-07-03 12-39-09](https://user-images.githubusercontent.com/45520375/60581690-02d6e500-9d90-11e9-9559-4a6369e1daa1.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use this plugin https://github.com/csstree/stylelint-validator
