### ISSUE TITLE
Support turn off rules with /*! comment

### ISSUE THREAD

**Issue by BoruiGu** [stylelint/stylelint#4152]
> What is the problem you're trying to solve?

We have multiple `scss` files that will be compiled into a single `css` file, and we'd like to run stylelint on both `scss` files and the compiled `css` file. 

There're some places in the `scss` files that we turn off rules with `/* stylelint-disable */` comment and it works. However in the compiled `css` file, the comments are gone since we use `compressed` style, and the compiled `css` file will fail linting

> What solution would you like to see?

since the `/*!` comments are preserved in compiled css, I would like stylelint to be able to recoginize comments like

`/*! stylelint-disable */` `/*! stylelint-disable-line */` etc.

so that we can scan both `scss` files and the compiled `css` files

**Comment by hudochenkov** [comment]
I'm afraid it won't be implemented. We're aim to create functionality which is generally useful and mostly target standard CSS. Your case is quite specific for your team needs.

I would recommend to [write a PostCSS plugin](https://github.com/postcss/postcss/blob/master/docs/writing-a-plugin.md) which will be run before SCSS compilation. It will replace `/* stylelint-disable` to `/*! stylelint-disable`.

You can start with this:

```js
var postcss = require('postcss')

module.exports = postcss.plugin('PLUGIN_NAME', function () {
  return function (root) {
	root.walkComments(comment => {
		// Transform each comment here
	});
  }
})
```
