### ISSUE TITLE
Quick fix feature is not working in VS Code

### ISSUE THREAD

**Issue by pavlyukpetr** [stylelint/stylelint#4170]
Hello, the Quick Fix feature is not working for me.
![2019-07-25_13-08-27](https://user-images.githubusercontent.com/11602610/61866456-d66d3f00-aedd-11e9-8d90-d5ae5016054d.jpg)
It says "No code actions available".

Can you, please, tell me maybe there is a way to add the code actions?

Thank you.

**Comment by hudochenkov** [comment]
Please open issue in your editors plugin repository: https://github.com/shinnn/vscode-stylelint.
