### ISSUE TITLE
Add support to test for several warnings

### ISSUE THREAD

**Issue by vankop** [stylelint/stylelint#4172]
> What is the problem you're trying to solve?

Currently it not possible to detect several warnings in tests, see
https://github.com/stylelint/stylelint/blob/master/jest-setup.js#L92

However, sometimes it is necessary for tests to detect such cases, see https://github.com/stylelint/stylelint/issues/4113

> What solution would you like to see?

My suggestion is to rework reject object syntax.

Typescript defintion:
```
type WarningDescription = {
    message: string,
    line?: number,
    column?: number,
    fixed?: string
};

type Reject = {code: string, warnings?: Array<WarningDescription>} & WarningDescription;
```

**Comment by vankop** [comment]
cc @stylelint/contributors

**Comment by evilebottnawi** [comment]
I have nothing against it :+1:

**Comment by vankop** [comment]
I think this discussion is mostly about API since it important to support current behavior + Will we enable strict warnings array length check? or we will check it length only when warnings descriptions presented as array

**Comment by jeddy3** [comment]
What is the complexity overhead of this feature? I ask as because #4113 was the first time we've needed the feature. If it's a lot then it might not be worth it. If it's not much though, then I suggest we go ahead.

> Will we enable strict warnings array length check? or we will check it length only when warnings descriptions presented as array

Am I right in thinking that the latter would support the current behaviour? If so, I suggest we take that approach if we added the feature.

**Comment by vankop** [comment]
> What is the complexity overhead of this feature?

decided to create a draft ☝



> Am I right in thinking that the latter would support the current behaviour? If so, I suggest we take that approach if we added the feature.

Yes

**Comment by vankop** [comment]
If enable strict warnings count check, getting result of:
`132 failed, 14747 passed`

errors in:
```
selector-pseudo-class-blacklist
selector-pseudo-class-no-unknown
selector-pseudo-element-colon-notation
number-max-precision
number-leading-zero
number-no-trailing-zeros
media-feature-colon-space-after
media-feature-colon-space-before
media-feature-range-operator-space-after
media-feature-range-operator-space-before
selector-max-universal
selector-max-pseudo-class
selector-max-combinators
selector-max-compound-selectors
selector-max-id
value-list-max-empty-lines
selector-list-comma-newline-before
selector-list-comma-space-after
indentation
```
and more..

Obviously, most warnings are expected, but I think we need to cover this cases as well

**Comment by hudochenkov** [comment]
We should not break tests for now. I propose to create a new issue when related PR is merged to track tests which need to be improved (add all missed warnings). When all tests are improved we could enable strict check for warnings count.
