### ISSUE TITLE
Missing typescript version

### ISSUE THREAD

**Issue by irstavr** [stylelint/stylelint#4192]
The description of the `pre-requisites` does not mention the compatiblity with Typescript version. 
We installed the latest `stylelint` with typescript `2.7.2` and brought many typescript build errors. Upgrading typescript to `3.5.3` solved everything. 
But, instead we decided to downgrade `stylelint` to 8.2.0 to fix our issues.

I suggest rewriting the documentation with referring the compatible typescript version for every version of `stylelint` as well.

**Comment by evilebottnawi** [comment]
@irstavr stylelint doesn't have types in repo, you should open issue in `typed` repo
