### ISSUE TITLE
stylelint property in package.json not working

### ISSUE THREAD

**Issue by Svish** [stylelint/stylelint#4195]
With a `stylelint` configuration file named `.stylelintrc.json` next to my `package.json` the following command works:
```cmd
> npx stylelint --print-config .
{
  ...
}
```

But if I add `"stylelint": "./.stylelintrc.json"` to my `package.json` I get the following:
```cmd
> npx stylelint --print-config .
Error: No rules found within configuration. Have you provided a "rules" property?
    at module.exports (C:\dev\projects\stylelint-config-opf\node_modules\stylelint\lib\utils\configurationError.js:8:28)
    at C:\dev\projects\stylelint-config-opf\node_modules\stylelint\lib\augmentConfig.js:89:15
```

Similar setup worked fine for prettier, so figured it would work here too (`"prettier": "./myconfig.json"`), but, seems like it doesn't...? 😕

**Version:** `10.1.0`
**Via:** `CLI`

**Comment by hudochenkov** [comment]
This is correct. We don't support `"stylelint": "./.stylelintrc.json"` in package.json. There is no need, because `.stylelintrc.json` picked up automatically.

**Comment by Svish** [comment]
Well, in this project yes, but the goal was to publish this as a package to use for shared stylelint configuration. And the hope was to then be able to refer to it in other packages using `"stylelint": "@company/stylelint-config"` in `package.json` for less file clutter.

Seems I can add a `.stylelintrc.js` with `module.exports = require('@company/stylelint-config');`, but would really like to not have that unnecessary file there.

Would it be difficult to add support for referring to a file/package using the `"stylelint"` key in `package.json`, like you can with `prettier` and (I think) `eslint`?

**Comment by hudochenkov** [comment]
You can use [`extends`](https://stylelint.io/user-guide/configuration#extends).

```js
// package.json
{
    "stylelint": {
        "extends": "@company/stylelint-config"
    }
}
```

**Comment by Svish** [comment]
Ah, cool, that works, thanks 🙂👍
