### ISSUE TITLE
Handling warnings or errors

### ISSUE THREAD

**Issue by tgfjt** [stylelint/stylelint#42]
Can we result unsuccessfully with errors?(and successfully with warnings as well)
Do you have a plan to be the build to fail on errors?

I mean:

```js
if (options === '2') {
  result.error(
      messages.unexpected,
      { node: decl }
    )
  })
} else if (options === '1') {
  result.warn(
      messages.unexpected,
      { node: decl }
    )
  })
}
```
https://github.com/CSSLint/csslint/blob/master/src/core/CSSLint.js#L89

**Comment by MoOx** [comment]
We do not plan to throw exception for now. We might handle log/error levels later.

**Comment by MoOx** [comment]
See https://github.com/stylelint/stylelint/issues/26

**Comment by tgfjt** [comment]
I see. Thank you. :+1:
