### ISSUE TITLE
New rule/options: newline support for *media-query-parentheses-*-inside`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#422]
I'm flagging this one up for discussion as, unlike the `function-*` equivalent, the use case for this one is pretty murky.

It [looks like](http://www.w3.org/TR/mediaqueries-4/#mq-syntax) parentheses are used for two purposes inside media queries:

* For containing individual _media features_.
* For _operator precedence_ when using _media conditions_.

To be honest, I'm not 100% sure my understanding of the latter one is correct as the spec is making my head hurt.

So, the use-case is pretty edgy here as I can't think why you'd want a newline inside a _media feature_ like `(max-width: 100px)` and I can't actually think of media query complex enough that you'll have to use brackets to control the precedence. I'm sure one exists though, but it's got to be rare and I'm wondering whether this rule is worth our time because of that. Well, at least until someone stumbles into it in the real world.

What do you think?

**Comment by davidtheclark** [comment]
Yes, I'd prefer not to work on this until somebody requests it.
