### ISSUE TITLE
security: potential redos

### ISSUE THREAD

**Issue by aladdin-add** [stylelint/stylelint#4221]
https://github.com/stylelint/stylelint/blob/f8d7865eae73af0ecb7a21002e6bd5ef5b01fcfe/lib/rules/max-line-length/index.js#L13-L14

please do not use this kind of regex -- it can cause potential redos!
refs: https://en.wikipedia.org/wiki/ReDoS

btw, is there a better way to report security issues?(I don't think it's good to use GitHub for filing security issues.)

**Comment by hudochenkov** [comment]
Thank you! We have a fix https://github.com/stylelint/stylelint/pull/4213.

> is there a better way to report security issues?

You can email to one of maintainers. I have email in my profile.

**Comment by aladdin-add** [comment]
closing, as it has been fixed by #4213
