### ISSUE TITLE
Add daemon support

### ISSUE THREAD

**Issue by MeisterTea** [stylelint/stylelint#4226]
Stylelint takes around 1 second to parse a css file.
It can be quite heavy when you are using it frequently to lint your files

The same happens with eslint.
Eslint_d fixes this issue. Could the same be done with stylelint ?

This projects aims to fix that but is not maintained anymore
https://github.com/jo-sm/stylelint_d

**Comment by hudochenkov** [comment]
This won't be part of stylelint core. Same as eslint_d is not part of ESLint. It's open source, so you can maintain repository you mentioned.
