### ISSUE TITLE
Fix autofix stripping BOM

### ISSUE THREAD

**Issue by vkrol** [stylelint/stylelint#4228]
> Clearly describe the bug

Autofix strips BOM

> Which rule, if any, is the bug related to?

N/A.

> What CSS is needed to reproduce the bug?

N/A.

> What stylelint configuration is needed to reproduce the bug?

N/A.

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.css" --fix`.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

The BOM must remain in place.

> What actually happened (e.g. what warnings or errors did you get)?

N/A.

Minimal reproducible example: https://github.com/vkrol/stylelint-fix-bom-bug.
This is related to https://github.com/stylelint/stylelint/issues/3792 and https://github.com/stylelint/stylelint/pull/4225.

**Comment by vkrol** [comment]
@jeddy3 `status: wip` is most likely confusing because I was only writing the test, but I am not fixing this bug at the moment.

**Comment by evilebottnawi** [comment]
I think we need option in postcss for this, becaue previously postcss always add BOM if it is exists in source file

**Comment by ybiquitous** [comment]
The `unicode-bom` rule is now deprecated and will be removed in the future. See below:

https://github.com/stylelint/stylelint/blob/74d8da444d500ba69b15801c9165d32af54192f1/lib/rules/unicode-bom/README.md?plain=1#L3
