### ISSUE TITLE
at-rule-property-blacklist and whitelist

### ISSUE THREAD

**Issue by paradox460** [stylelint/stylelint#4235]
> What is the problem you're trying to solve?
Inefficient properties in keyframe animations cause jank and reflow.

Use of properties in keyframe animations, such as `top` and `width` can seriously impact CSS animation performance

https://css-tricks.com/tale-of-animation-performance/

> What solution would you like to see?

A new set of rules for defining property blacklists (and whitelists) for defining what set of properties can be used within an at-rule. There is already the `at-rule-property-requirelist` rule, which takes a map of `atrule-type: [property]`, to define which properties _must_ be present in a matching at-rule.

**Comment by hudochenkov** [comment]
You might find this useful https://github.com/kristerkari/stylelint-high-performance-animation

**Comment by paradox460** [comment]
Thanks! That does the trick perfectly.

**Comment by vankop** [comment]
> You might find this useful https://github.com/kristerkari/stylelint-high-performance-animation

@ntwb could we add this plugin to [stylelint-awesome](https://github.com/ntwb/awesome-stylelint) ?

**Comment by jeddy3** [comment]
Closing for now as the current use case is best addressed with the available plugin. We can reopen this if other uses cases for built-in `at-rule-property-white/blacklist` rules come to light.
