### ISSUE TITLE
Compatible Indentation Rules to Prettier

### ISSUE THREAD

**Issue by Chaoste** [stylelint/stylelint#4238]
Hi all,

> Clearly describe the bug

I am using stylelint and eslint with prettier. All configs are set to 2 spaces indentation. However, they appear to have different rules for template literals. In one of my styled-components, prettier uses the indentation similar to functions with parameters covering multiple lines:
The parameters are indented by four spaces while the function body is indented by two spaces.

> Which rule, if any, is the bug related to?

`indentation`

> What CSS/JS is needed to reproduce the bug?

Indentation as preferred by stylelint:
```js
export const MyComponent = styled.div`
  width: ${theme.sizes.tool};
  padding: calc(
    ${({ isMobile }) =>
      isMobile ? GeneralStyles.padding.small : GeneralStyles.padding.medium} +
    ${theme.sizes.tool} + ${OVERLAP}
  );
`;
```

Preferred by prettier:
```js
export const MyComponent = styled.div`
  width: ${theme.sizes.tool};
  padding: calc(
    ${({ isMobile }) =>
        isMobile ? GeneralStyles.padding.small : GeneralStyles.padding.medium} +
      ${theme.sizes.tool} + ${OVERLAP}
  );
`;
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": "2"
  }
}
```

> Which version of stylelint are you using?

`9.9.0`

Prettier Version: `1.18.2`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.js" "**/*.jsx" --config myconfig.json`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to template literals which are required for usage with styled-components.

> What did you expect to happen?

Compatible behavior to prettier

> What actually happened (e.g. what warnings or errors did you get)?

While prettier preferred one indentation, stylelint preferred the other way.

```shell
packages/Nexboard/src/components/menus/interactionMenu/ToolColorSelector.jsx
 41:7  ✖  Expected indentation of 4 spaces   indentation
```

**Comment by evilebottnawi** [comment]
We should skip check `indentation` for `${}`, maybe hard to implement

**Comment by evilebottnawi** [comment]
Also we strongly recommend disable all stylistics rules when you use prettier

**Comment by hudochenkov** [comment]
The best solution is to disable this rule. stylelint and Prettier will rarely match. That's why indentation rules disabled both in [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier/blob/80a0b3fcf50c96c78c139774e6bbdf14dcd2c07d/src/index.js#L5) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier/blob/793aa76f9045a1aa9237558c343e64e957b56984/index.js#L38).

**Comment by ntwb** [comment]
Agreed, ensure you're Prettier config sets the tab-width

https://prettier.io/docs/en/options.html#tab-width
