### ISSUE TITLE
New rule: color-no-named

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#424]
Disallow named colors

**Comment by davidtheclark** [comment]
Waiting on https://github.com/TrySound/postcss-value-parser/issues/12

**Comment by jeddy3** [comment]
Yep, nearly all the outstanding rules will be.

I think the `selector-no-qualified`, `function-parentheses-*-inside`, `selector-pattern`, `comment-*-inside` and 'max-line-length` are the only ones that aren't.

**Comment by TrySound** [comment]
@jeddy3 https://github.com/TrySound/postcss-value-parser/issues/12#issuecomment-149153638

**Comment by jeddy3** [comment]
[is-named-css-color](https://www.npmjs.com/package/is-named-css-color) might be useful here.

**Comment by jeddy3** [comment]
Done in #443
