### ISSUE TITLE
Replace Greenkeeper

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4244]
Greenkeeper sends a lot of messages and PR. Most of the time they are not really usefull. There is no real need to update every single dependency to it's every version. Greenkeeper open new PRs even for minor versions, and creates more distraction, rather real help.

I propose to reconsider our choice and choose different tool for updating dependencies.

What I think are good features:

1. Create PRs for major versions and 0.x versions. Because versions could have breaking changes. And breaking changes are easier to fix as soon as possible, rather postpone.
2. Create PRs for vulnerabilities.
3. Don't create PRs for version withing semver range specified in package.json. Or at least create PRs not as soon as possible, but on a schedule, like once per month.
4. Notify if dependency withing semver range breaks our build.
5. Nice to have: able to ignore packages. E. g. Flow is the most annoying. They update way to often, and because they still on 0.x versioning, every version considered a major (could have breaking changes).

We could try https://dependabot.com/ (which is bought by Github). These features could cover Greenkeeper's shortcomings:

* [`ignored_updates`](https://dependabot.com/docs/config-file/#ignored_updates)
* [`version_requirement_updates: widen_ranges`](https://dependabot.com/docs/config-file/#version_requirement_updates) or `increase_versions_if_necessary`

Also, very nice feature is [`automerged_updates`](https://dependabot.com/docs/config-file/#automerged_updates).

And we could manually check/update dependencies before releases. We don't release that often, so shouldn't be a burden.

**Comment by jeddy3** [comment]
> We could try https://dependabot.com/ (which is bought by Github).

SGTM

**Comment by ntwb** [comment]
Likewise, SGTM, happy to give Depanabot a try.

Greenkeeper creates a new branch for each package release, it runs the CI tests and if the CI fails it creates a PR, or creates a PR if it is not covered by the SemVer range, otherwise it then deletes the branch.

I think we've been caught a little of guard recently by the above type PRs because for example the `flow-bin` PRs had not been resolved Greenkeeper would continue commenting on existing PRs and sometimes creating new PRs, which is noisy as noted.

Being able to _ignore updates_ would be nice for issues where we have less experience to address some of these _flow_ or _Windows glob_ issues.

**Comment by hudochenkov** [comment]
Dependabot is cool. I closed PR and it [reacted](https://github.com/stylelint/stylelint/pull/4251#issuecomment-528267042):

> OK, I won't notify you again about this release, but will get in touch when a new version is available. If you'd rather skip all updates until the next major or minor version, let me know by commenting `@dependabot ignore this major version` or `@dependabot ignore this minor version`.
> 
> If you change your mind, just re-open this PR and I'll resolve any conflicts on it.

**Comment by hudochenkov** [comment]
I uninstalled Greenkeeper and enabled Dependabot for the following repositories:

- eslint-config-stylelint
- stylelint
- stylelint-config-recommended
- stylelint-config-standard
- stylelint-demo
- stylelint.io

We'll get bunch of PR to all repos initially, but after that we should receive PR every month. Security updates will be instant.

**Comment by hudochenkov** [comment]
One more nice feature. I was merging PRs Dependabot created, and after one merge I saw this in other PRs:

<img width="769" alt="Screenshot 2019-09-05 at 13 21 17" src="https://user-images.githubusercontent.com/654597/64337724-388e8900-cfe0-11e9-91e3-336e4acc8d5f.png">

**Comment by hudochenkov** [comment]
It's configured for all mentioned above repositories.
