### ISSUE TITLE
Replace Flow with TypeScript JSDoc

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4245]
In https://github.com/stylelint/stylelint/issues/4244#issue-489022754 @hudochenkov mentioned how looking after Flow is a bit of a pain.

I wonder whether it's worth investigating how much effort is involved in migrating away from Flow to [TypeScript JSDocs](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc). Does anyone have experience with this? I believe we'd be able to keep the codebase free of a compile step with this approach. A little more about the JSDoc style can be [found here](https://fettblog.eu/typescript-jsdoc-superpowers/), and there's a [(relatively old) discussion](https://github.com/postcss/postcss/issues/1221) about taking this approach in PostCSS.

Labeling as a discussion so people can add their thoughts on the pros and cons of such a replacement.

**Comment by ntwb** [comment]
I'd be interested in taking a closer look at this, I try to grok Flow but it just doesn't come easy to me, one of the projects I'm involved with [Gutenberg](https://github.com/wordpress/gutenberg) has recently started doing the same, switching to TypeScript JSDocs.

As for time to do it, I'll be quote limited, starting a new job next week 🎉

Nevertheless I like the sounds of this idea and thanks for raising the discussion @jeddy3 💯

**Comment by hudochenkov** [comment]
I think it's a good idea. TypeScript is more reliable and future-proof.

Here is one more article on this topic https://ricostacruz.com/til/typescript-jsdoc

**Comment by evilebottnawi** [comment]
:+1: For typescript-jsdoc

**Comment by vankop** [comment]
Typescript jsdoc is pain =) anyway it is better, then Flow (de facto TypeScript is only one optimal solution for types in JS, Flow was better for js before babel team implemented plugin for typescript)

Problem with `typescript-jsdoc` is that it is different from TypeScript in `ts` files and less documented.

Some guys in TypeScript gitter suggested me look on jsdoc tests to find usage example =(

**Comment by vankop** [comment]
Maybe we could find (or write) babel plugin to easy migrate on TypeScript

**Comment by vankop** [comment]
should be closed after: 
https://github.com/stylelint/stylelint/issues/2935

**Comment by hudochenkov** [comment]
[A sandbox project to testing VS Code and JavaScript + JSDoc type checking.](https://github.com/patoi/ultima-thule)

**Comment by hudochenkov** [comment]
We have 123 files with Flow types. Not going to be easy to migrate.

The hardest part that almost no one has experience with Flow 🙈

I think we can start with small files (all `lib/utils`), and migrate tests last.

- Doesn't anyone has idea how to migrate it piece by piece without the need change everything in on go?
- Can we run Flow and TypeScript temporarily together?
- Could we replace Flow with JSDoc in one file without breaking the rest of Flow type-checking?

Some functions has JSDoc already. E. g. [`whitespaceChecker.js`](https://github.com/stylelint/stylelint/blob/master/lib/utils/whitespaceChecker.js).

<details>
<summary>List of files</summary>

```
lib/assignDisabledRanges.js
lib/augmentConfig.js
lib/cli.js
lib/createPlugin.js
lib/createStylelint.js
lib/createStylelintResult.js
lib/getConfigForFile.js
lib/getPostcssResult.js
lib/invalidScopeDisables.js
lib/isPathIgnored.js
lib/lintSource.js
lib/needlessDisables.js
lib/normalizeRuleSettings.js
lib/postcssPlugin.js
lib/printConfig.js
lib/standalone.js
lib/writeOutputFile.js
lib/formatters/disableOptionsReportStringFormatter.js
lib/formatters/index.js
lib/utils/addEmptyLineAfter.js
lib/utils/addEmptyLineBefore.js
lib/utils/atRuleParamIndex.js
lib/utils/beforeBlockString.js
lib/utils/blockString.js
lib/utils/blurComments.js
lib/utils/blurFunctionArguments.js
lib/utils/blurInterpolation.js
lib/utils/checkAgainstRule.js
lib/utils/checkInvalidCLIOptions.js
lib/utils/configurationError.js
lib/utils/containsString.js
lib/utils/declarationValueIndex.js
lib/utils/FileCache.js
lib/utils/findAnimationName.js
lib/utils/findAtRuleContext.js
lib/utils/findFontFamily.js
lib/utils/findListStyleType.js
lib/utils/functionArgumentsSearch.js
lib/utils/getCacheFile.js
lib/utils/getFormatterOptionsText.js
lib/utils/getModulePath.js
lib/utils/getNextNonSharedLineCommentNode.js
lib/utils/getOsEol.js
lib/utils/getPreviousNonSharedLineCommentNode.js
lib/utils/getSchemeFromUrl.js
lib/utils/getUnitFromValueNode.js
lib/utils/hasBlock.js
lib/utils/hasEmptyBlock.js
lib/utils/hasEmptyLine.js
lib/utils/hash.js
lib/utils/hasInterpolation.js
lib/utils/hasLessInterpolation.js
lib/utils/hasPsvInterpolation.js
lib/utils/hasScssInterpolation.js
lib/utils/hasTplInterpolation.js
lib/utils/hasUnresolvedNestedSelector.js
lib/utils/isAfterComment.js
lib/utils/isAfterSingleLineComment.js
lib/utils/isAfterStandardPropertyDeclaration.js
lib/utils/isAutoprefixable.js
lib/utils/isBlocklessAtRuleAfterBlocklessAtRule.js
lib/utils/isBlocklessAtRuleAfterSameNameBlocklessAtRule.js
lib/utils/isCounterIncrementCustomIdentValue.js
lib/utils/isCounterResetCustomIdentValue.js
lib/utils/isCustomElement.js
lib/utils/isCustomMediaQuery.js
lib/utils/isCustomProperty.js
lib/utils/isCustomPropertySet.js
lib/utils/isCustomSelector.js
lib/utils/isFirstNested.js
lib/utils/isFirstNodeOfRoot.js
lib/utils/isKeyframeRule.js
lib/utils/isKeyframeSelector.js
lib/utils/isLogicalCombination.js
lib/utils/isMathFunction.js
lib/utils/isOnlyWhitespace.js
lib/utils/isRangeContextMediaFeature.js
lib/utils/isSharedLineComment.js
lib/utils/isSingleLineString.js
lib/utils/isStandardSyntaxAtRule.js
lib/utils/isStandardSyntaxCombinator.js
lib/utils/isStandardSyntaxDeclaration.js
lib/utils/isStandardSyntaxFunction.js
lib/utils/isStandardSyntaxMediaFeature.js
lib/utils/isStandardSyntaxMediaFeatureName.js
lib/utils/isStandardSyntaxProperty.js
lib/utils/isStandardSyntaxRule.js
lib/utils/isStandardSyntaxSelector.js
lib/utils/isStandardSyntaxTypeSelector.js
lib/utils/isStandardSyntaxUrl.js
lib/utils/isStandardSyntaxValue.js
lib/utils/isValidFontSize.js
lib/utils/isValidHex.js
lib/utils/isVariable.js
lib/utils/isWhitespace.js
lib/utils/levenshteinDistance.js
lib/utils/matchesStringOrRegExp.js
lib/utils/nextNonCommentNode.js
lib/utils/optionsMatches.js
lib/utils/parseSelector.js
lib/utils/rawNodeString.js
lib/utils/removeEmptyLinesAfter.js
lib/utils/removeEmptyLinesBefore.js
lib/utils/report.js
lib/utils/ruleMessages.js
lib/utils/transformSelector.js
lib/utils/validateObjectWithArrayProps.js
lib/utils/validateObjectWithStringArrayProps.js
lib/utils/validateOptions.js
lib/utils/whitespaceChecker.js
lib/utils/__tests__/checkAgainstRule.test.js
lib/utils/__tests__/getNextNonSharedLineCommentNode.test.js
lib/utils/__tests__/getPreviousNonSharedLineCommentNode.test.js
lib/utils/__tests__/isBlocklessAtRuleAfterBlocklessAtRule.test.js
lib/utils/__tests__/isBlocklessAtRuleAfterSameNameBlocklessAtRule.test.js
lib/utils/__tests__/isFirstNested.test.js
lib/utils/__tests__/isSharedLineComment.test.js
system-tests/001/001.test.js
system-tests/002/002.test.js
system-tests/003/003.test.js
system-tests/004/004.test.js
system-tests/005/005.test.js
system-tests/ignoreFile/ignoreFile.test.js
```
</details>

**Comment by vankop** [comment]
I will take a look on automation this) I think we can use something lie https://github.com/bcherny/flow-to-typescript

**Comment by ntwb** [comment]
Nice, there's also https://www.npmjs.com/package/flow-to-ts

**Comment by hudochenkov** [comment]
I'm afraid these tools doesn't support Flow comments and TypeScript JSDoc.

**Comment by vankop** [comment]
looks like @hudochenkov https://github.com/bcherny/flow-to-typescript uses babylon, so I think it will not with comments

**Comment by vankop** [comment]
As I see all `utils` types depends on types in 
```
lib/assignDisabledRanges.js
lib/augmentConfig.js
lib/cli.js
lib/createPlugin.js
lib/createStylelint.js
lib/createStylelintResult.js
lib/getConfigForFile.js
lib/getPostcssResult.js
lib/invalidScopeDisables.js
lib/isPathIgnored.js
lib/lintSource.js
lib/needlessDisables.js
lib/normalizeRuleSettings.js
lib/postcssPlugin.js
lib/printConfig.js
lib/standalone.js
lib/writeOutputFile.js
```

So moving this files to correct ts types will allow us to use typescript. Then we need just move all `utils` to types(as I see mostly all utils are independent functions). In this case types coverage will decrease, but it will easy migration

**Comment by vankop** [comment]
All welcome to participate on this ☝️

**Comment by G-Rath** [comment]
> The hardest part that almost no one has experience with Flow 🙈

I've got a lot of exp w/ TypeScript, and Flow. I'd be happy to spearhead a conversion to pure TypeScript, but moving to JSDoc is a good middle ground. (I recently handled converting `eslint-plugin-jest` to TypeScript).

Since you've already gotten underway, and I have a bit on my plate, I won't try to dive in along side, but you're more than welcome to @ me w/ any questions, and I'm happy to review PRs.

I'm also on the TypeScript gitter under the same handle, so you can @ me there too if you'd like to chat in real time :)

**Comment by hudochenkov** [comment]
@vankop I want to try to add more types. If you didn't start yet, I'm going to add types to everything in [`lib/utils`](https://github.com/stylelint/stylelint/tree/master/lib/utils) tomorrow (Monday).

**Comment by vankop** [comment]
No, I did not start this work, help always welcome 🙂

**Comment by vankop** [comment]
@hudochenkov so I will take a look on removing flow then =)

**Comment by hudochenkov** [comment]
@vankop don't do actual removing yet. Because we'll have many conflicts. But you could figure out the strategy.

Maybe a little Babel plugin which will remove all comment which starts with `/*: `?

**Comment by vankop** [comment]
@hudochenkov I want to try https://flow.org/en/docs/tools/flow-remove-types/

**Comment by hudochenkov** [comment]
@vankop what next? Is it time to remove Flow? Do we need to add more types before removing Flow?

**Comment by vankop** [comment]
> Is it time to remove Flow?

we can remove it and add `// @ts-nocheck` to /rules/* . I did not find best solution to remove it.

> Maybe a little Babel plugin which will remove all comment which starts with /*: ?

I think running https://flow.org/en/docs/tools/flow-remove-types/ first and then running this plugin should be enough

> Do we need to add more types before removing Flow?

It will be great to fix `TODO TYPES` =)

**Comment by hudochenkov** [comment]
I tried `flow-remove-types` and it doesn't work good. It remove content of some comments, but not comments themselves:

```diff
module.exports = function(
	stylelint /*: stylelint$internalApi*/,
-	searchPath /*:: ?: string*/,
+	searchPath /*::          */,
) /*: configPromise*/ {
	searchPath = searchPath || process.cwd();
```

We'll have to write Babel plugin which will remove comments:

* which starts with `/*: ` (note space at the end)
* which starts with `/*:: ` (note space at the end)
* `/* @flow */`

**Comment by vankop** [comment]
I think this can be closed

**Comment by hudochenkov** [comment]
Could you create issues for things that we need to do? Like remove `@ts-ignore`.

Then we can close this issue.

**Comment by joe223** [comment]
I think this babel plugin would be useful https://www.npmjs.com/package/@zxbodya/babel-plugin-flow-to-typescript
