### ISSUE TITLE
Reconfigure Prettier and use tabs for indentation

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4246]
I would like to reconfigure Prettier. Main goals are increase readability, and cleaner diffs.

Proposed changes:

* [`printWidth: 100`](https://prettier.io/docs/en/options.html#print-width). We're dealing with a lot of nesting and long variables names. 80 symbols is too small, and often single expression is broken into multiple lines which leads to worse readability. I don't have an example on hand, though.
* [`singleQuote: true`](https://prettier.io/docs/en/options.html#quotes). I think it's a pretty common thing. Airbnb config and StandardJS uses this.
* [`trailingComma: "es5"`](https://prettier.io/docs/en/options.html#trailing-commas) (or "all"). Cleaner diffs, and no need to add this comma every time we need to add something to the end of list.
* [`arrowParens: "always"`](). Just to remove annoyance when we need to add a parameter to a function, and have to wrap the first parameter first. Or when we need to remove single parameter and put parenthesis instead. Current usage in our code base:
	* With parenthesis: 2294 functions.
	* No parenthesis: 1059 functions.

---

[`useTabs: true`](https://prettier.io/docs/en/options.html#tabs). This is a huge one. Many people consider pro of spaces to keep code looks the same in any environment. But on the other side it's the main con of spaces. People have different vision. Using spaces disables some people to see indentation comfortable. Here are very good reason and example: https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/

I personally struggle to read code indented with two spaces. I'm not visually impaired but for me is very hard to see nesting, when indentation is too small (2 spaces). With 4 spaces width I can clearly see it. When code base uses tabs everyone could adjust their indentation level for their liking. It's exactly the same as everyone using their preferred font size, and color scheme. Every editor support setting tab width from the dawn of times.

For Github it's a little bit trickier, but possible.

If you want tab size to be 4 spaces the easies solution is to use [Tab Size on GitHub](https://github.com/sindresorhus/tab-size-on-github) extension. I use it for many years.

If you want 2 spaces or use Firefox or Opera, then use [Stylus](https://add0n.com/stylus.html) extension with [styles](https://github.com/sindresorhus/tab-size-on-github/blob/master/content.css) copied from extension above and adjusted for your liking.

As a bonus you will have nice indentation in all other repositories using tabs on Github :)

After reddit post above I could finally convince my 2-space-fan colleague to switch our codebase to tabs. He configured his VS Code and browser for 2 spaces width, and I configured to 4 spaces width. Now we all happy and can see how we like to see :)

Let's increase accessibility of our code base!

**Comment by evilebottnawi** [comment]
Prettier has problem with ternary and literal templates when you use tabs, it is very ugly in many cases

**Comment by ntwb** [comment]
I'm fine with the first 4, even `trailingComma: "all"` if you'd like.

I'm also fine switching to _tabs_, they've been my personal preference ever since I started programming...

<img src="https://www.hanselman.com/blog/content/binary/tabsvsspaces.gif">

**Comment by ntwb** [comment]
I've just read the Reddit post and it's not entirely accurate IMHO, using an `.editorconfig` file and your Editor/IDE settings you can set the same _view_ of 2 or 4 characters


### Indent 2 Characters

#### Spaces

`.editorconfig` file:
```
indent_style = space
indent_size = 2
```

#### Tabs

`.editorconfig` file:
```
indent_style = tab
```

Editor/IDE "Tab Size" to `2` for example for VS Code: `"editor.tabSize": 2`

### Indent 4 Characters

#### Spaces

`.editorconfig` file:
```
indent_style = space
indent_size = 4
```

#### Tabs

`.editorconfig` file:
```
indent_style = tab
```

Editor/IDE "Tab Size" to `4` for example for VS Code: `"editor.tabSize": 4`


----

Typically an `.editorconfig` file is committed to a repo, but if you omit the `indent_size` from the `.editorconfig` file it becomes "user choice" on how many characters to indent with, a user could choose `2`, `4`, or even `8` in their Editor/IDE settings without affecting other developers and the `.editorconfig` file can be set to use tabs or spaces.

For the _large font_ scenario cited:

### Indent 1 Characters

#### Spaces

`.editorconfig` file:
```
indent_style = space
```

#### Tabs

`.editorconfig` file:
```
indent_style = tab
```

Editor/IDE "Tab Size" to `1` for example for VS Code: `"editor.tabSize": 1`


For the wide screen_ scenario cited:

### Indent 8 Characters

#### Spaces

`.editorconfig` file:
```
indent_style = space
```

#### Tabs

`.editorconfig` file:
```
indent_style = tab
```

Editor/IDE "Tab Size" to `8` for example for VS Code: `"editor.tabSize": 8`

----

Or finally for stylelint, we could remove a single line from the `.editorconfig`:
https://github.com/stylelint/stylelint/blob/master/.editorconfig#L7

And let developers set their own setting in their Editor/IDE of choice the _indent width_ which for example VS Code is `"editor.tabSize":x` where `x` is the desired width of the dev.

**Comment by hudochenkov** [comment]
@ntwb Correct, to have advantages of tabs we need to set `indent_style = tab`, remove `indent_size` and convert whole code base to tabs.

**Comment by hudochenkov** [comment]
@evilebottnawi After formatting our codebase I see few weird places, when part of ternary has nesting (function or objects):

```js
functionCommaSpaceChecker({
	root,
	result,
	locationChecker: checker.afterOneOnly,
	checkedRuleName: ruleName,
	fix: context.fix
		? (div, index, nodes) => {
				return fixer({
					div,
					index,
					nodes,
					expectation,
					position: 'after',
					symb: context.newline,
				});
		  }
		: null,
});

const { attrBefore, setAttrBefore } = rawAttrBefore
	? {
			attrBefore: rawAttrBefore,
			setAttrBefore(fixed) {
				attributeNode.raws.spaces.attribute.before = fixed;
			},
	  }
	: {
			attrBefore: _.get(attributeNode, 'spaces.attribute.before', ''),
			setAttrBefore(fixed) {
				_.set(attributeNode, 'spaces.attribute.before', fixed);
			},
	  };
```

These are related Prettier issues:

https://github.com/prettier/prettier/issues/5811
https://github.com/prettier/prettier/issues/5184

Doesn't look good. But it a small sacrifice to make the rest of the code look readable for more folks.

**Comment by ntwb** [comment]
And now after reading all the comments in the Reddit thread:

4 comments correctly cite that with a modern Editor/IDE it should not matter
![Screen Shot 2019-09-04 at 9 37 21 pm](https://user-images.githubusercontent.com/1016458/64251610-4a2e4d00-cf5c-11e9-991c-7f15f7873550.png)

In VS Code the setting is `"editor.detectIndentation": true`, or `false` to disable:

<img width="782" alt="Screen Shot 2019-09-04 at 9 39 07 pm" src="https://user-images.githubusercontent.com/1016458/64251749-8eb9e880-cf5c-11e9-9c22-fa091933e485.png">

Add to that setting your _preferred_ width of 1, 2, 4 , or 8 and your all set, tabs vs spaces does not matter 🎉

**Comment by ntwb** [comment]
> ... to have advantages of tabs we need to set `indent_style = tab`, remove `indent_size` and convert whole code base to tabs.

Technically it doesn't, I think if you remove `indent_size` from the `.editorconfig` file @hudochenkov and change the Editor/IDE setting for tab width, which if you use VS Code that would be `"editor.tabSize": 4` you will see the results your expecting.

Granted, I think it is probably easier to change Prettier and Editorconfig to explicitly note the use of _tabs_ it shouldn't matter to a modern Editor/IDE

**Comment by hudochenkov** [comment]
I removed both `indent_` options from editor config. I have `"editor.tabSize": 4`. Tried both `"editor.detectIndentation": true` and `false`. No luck to change visual appearance.

With `detectIndentation: false` it renders two spaces as two spaces, but on Tab key inserts tab symbol. With `detectIndentation: true` two spaces are inserted on Tab press.

I don't think it's possible to render two space indent as four space indent width.

**Comment by hudochenkov** [comment]
Just for fun: origin of 80 characters line limit https://softwareengineering.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width/148678#148678

**Comment by hudochenkov** [comment]
Thank you, everyone, for supporting (or being tolerant) these changes.

<img width="184" alt="Screenshot 2019-09-15 at 23 05 40" src="https://user-images.githubusercontent.com/654597/64927623-7b850380-d80d-11e9-8db1-2a5537a2b24e.png">

I don't like that it resulted in a little mess. But I believe it will lead to better future :)

After sometime we could apply same settings to the rest of repositories. Want to have some time with new configuration to avoid things like https://github.com/stylelint/stylelint/pull/4280 (forgot something) to do in every repository.
