### ISSUE TITLE
New rule: color-no-hex

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#425]
Disallow hex colors

**Comment by davidtheclark** [comment]
Seems that if we have this one we should also make color-no-rgb, right?

**Comment by jeddy3** [comment]
I think that'll be handled by `function-blacklist/whitelist`. 

Hex colours and named colours don't fit the blacklist/whitelist mould (i.e. of simple string comparisons), so I broke them out into their own rules.

Sound groovy, or am I missing a beat here?

**Comment by davidtheclark** [comment]
Oh, ok. Makes sense.

**Comment by davidtheclark** [comment]
Done in #440.
