### ISSUE TITLE
calc needs its own parentheses spacing control

### ISSUE THREAD

**Issue by hanakin** [stylelint/stylelint#4261]
The current implementation of function-parentheses-space-inside is a catch all. Meaning all uses of () can or can not have spaces based on the settings. Our devs would like to have the ability to specify this independently for the calc(). For example urls and colors should not have spaces, but calc should allow for spaces to make it easier to read complex math formulas or match it to the scss settings for the same type of operations.

> What solution would you like to see?

A new rule for calc that checks spaces and ignores the global function-parentheses-space-inside. or however is easiest to implement the functionality

**Comment by hudochenkov** [comment]
I'm afraid it won't be implemented. Because it doesn't pass our [criteria for inclusion](https://stylelint.io/developer-guide/rules#criteria-for-inclusion):

> Generally useful; not tied to idiosyncratic patterns.

You could create a [plugin](https://stylelint.io/developer-guide/plugins) for your needs.
