### ISSUE TITLE
dollar-variable-empty-line-after AND dollar-variable-first-in-block

### ISSUE THREAD

**Issue by larsmunkholm** [stylelint/stylelint#4287]
Hi! I would like to have a new rule added :)

`dollar-variable-empty-line-after` ... to make sure there's always (or never) an empty line after variables.

`dollar-variable-first-in-block` ... to make sure variables are always written first in blocks.

**Comment by hudochenkov** [comment]
I think you wanted to open an issue in https://github.com/kristerkari/stylelint-scss

**Comment by larsmunkholm** [comment]
sorry, you're right

**Comment by jeddy3** [comment]
@larsmunkholm You can achieve this already with existing rules and plugins.

> to make sure there's always (or never) an empty line after variables.

From [the docs](https://stylelint.io/user-guide/about-rules#empty-line-before-and-max-empty-lines-rules):

> Each thing is responsible for pushing itself away from the preceding thing, rather than pushing the subsequent thing away. This consistency is to avoid conflicts, and is why there aren't any `*-empty-line-after` rules in stylelint.

Target the subsequent thing (likely a declaration) to ensure there's an empty line between it and the dollar variable like so:

```json

{
  "rules": {
    "custom-property-empty-line-before": [
      "always",
      {
        "except": ["after-custom-property", "first-nested"]
      }
    ],
    "declaration-empty-line-before": [
      "always",
      {
        "except": ["after-declaration", "first-nested"]
      }
    ]
  }
}
```

> to make sure variables are always written first in blocks.

You can use @hudochenkov's [stylelint-order/order](https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md) plugin to do this.
