### ISSUE TITLE
new rule filename-case

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#4306]
> What is the problem you're trying to solve?

Enforces all linted files to have their names in a certain case style.

> What solution would you like to see?

New rule, maybe better name

with option kebabCase, camelCase, snakeCase, pascalCase and custom regexp

Why not plugin? Because all projects try to use the same case style for files so this rule will be useful for everyone

Example rule for eslint https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md

**Comment by evilebottnawi** [comment]
I think better name `filename-pattern` as we do for other rules in stylelint

**Comment by ntwb** [comment]
> with option kebabCase, camelCase, snakeCase, pascalCase and custom regexp

kebab-case, camelCase, snake_case, PascalCase 😏

**Comment by ntwb** [comment]
BTW, this was previously discussed in https://github.com/stylelint/stylelint/issues/1485, it was closed as it was determined that this should really be a "file linting" solution as it has nothing to do with CSS

**Comment by hudochenkov** [comment]
It doesn't fit to our [vision areas](https://stylelint.io/vision#complete), because it has nothing to do with styles.

**Comment by evilebottnawi** [comment]
@hudochenkov hm, waht is problem, looks it is good rule for `Stylistic issues`, many style guides have recommendation for naming files

**Comment by hudochenkov** [comment]
It's about code style, not about file structure.

**Comment by evilebottnawi** [comment]
@hudochenkov for BEM (not only) file naming is part of code style, also this rule not for file structure, it is file naming

**Comment by joe223** [comment]
I agree with hudochenkov.

File name is not about code style, it's more like a `project architecture` style.

**Comment by evilebottnawi** [comment]
@joe223 in theory you can have difference naming for difference files, but it is ok to close for me if other developers things what it is unnecessary rule

**Comment by joe223** [comment]
@evilebottnawi 😂 Surly we can define a rule about how to write a file name. And I absolutely agree that developers should follow the same rule for keeping project consistent. But, I mean, it is a little bit **exceed** the obligation of `stylelint`.

**Comment by vankop** [comment]
I agree with @evilebottnawi that this type of linting could be useful for some methodologies (e.g. BEM) . However, it is not a part of **CSS lint** (read as `stylelint` 😂) . If `stylelint` as tool can solve this problem, someone can create plugin for this. 

On the other hand I can suggest to support this ability from stylelint side, so community can create plugins for specific methodologies =)
