### ISSUE TITLE
New API for applying fixes, to support comments disabling rules

### ISSUE THREAD

**Issue by stof** [stylelint/stylelint#4307]
> What is the problem you're trying to solve?

Comments disabling rules are processed after the rules have been applied (skipping the reporting of the error). But as rules are responsible for applying fixes themselves instead of reporting the error, they will fix things even in places where they were disabled, making the fixing mode unsuitable if there was a valid reason to disable the rule (for instance disabling a rule forcing to write `0` without unit due to the Flex bug of IE).

> What solution would you like to see?

A solution could be to change the rule API to look similar to the API of ESLint: instead of expecting rules to mutate the AST themselves at the time they run, the reporting API would accept a `fix` callback performing the mutation. And the main runner would call this callback when needed, i.e. when fixing mode is enabled and the rule is not ignored (and would then skip the reporting as it would have fixed it already).

An alternative solution would be to expose a method in the context to let the rule know whether it is ignored or no at a given position, so that it can skip fixing. But this would require rule authors to take care of this feature all the time, which is more demanding on them.

**Comment by hudochenkov** [comment]
Thank you for a suggestion. We can continue discussion in https://github.com/stylelint/stylelint/issues/2643.

Closing this one as a duplicate.
