### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by vankop** [stylelint/stylelint#4308]
As I understand stylelint participated in 2018 hacktoberfest. New one is starting, see https://hacktoberfest.digitalocean.com/

**Comment by hudochenkov** [comment]
I don't recall if we had any new contributors, to be honest. But it's still nice to label all of “help wanted” issues for hacktoberfest.

**Comment by ntwb** [comment]
Issues labeled `Good First Issue` will be available to Hacktoberfest participants

We first participated in 2017 via #2913

**Comment by vankop** [comment]
@ntwb looks like only `Hacktoberfest` label counts, see 2nd question in [faq](https://hacktoberfest.digitalocean.com/faq)

**Comment by hudochenkov** [comment]
I labeled every “good first issue” and “help wanted” with “Hacktoberfest”.
