### ISSUE TITLE
Output-File option is missing from CLI docs

### ISSUE THREAD

**Issue by mastacheata** [stylelint/stylelint#4319]
> Clearly describe the documentation issue

The docs are missing the --output-file / -o option added in #4085 / #3586 

> What solution would you like to see?

I suggest adding an explanation of that option to the docs and the README.md

**Comment by hudochenkov** [comment]
Thank you for the report!

I would say it's relevant to https://github.com/stylelint/stylelint/issues/4094.

**Comment by mastacheata** [comment]
Wow, that was quick.
Thanks a lot.
