### ISSUE TITLE
Windows Prettier Glob Error

### ISSUE THREAD

**Issue by bkinnamon** [stylelint/stylelint#4322]
> Clearly describe the bug

Windows 10 requires double quotes around the glob patterns in the prettier command line.

https://github.com/prettier/prettier/issues/4804

> Which rule, if any, is the bug related to?

No rule

> What CSS is needed to reproduce the bug?

None

> What stylelint configuration is needed to reproduce the bug?

None

> Which version of stylelint are you using?

11.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

I am not running stylelint. I am running tests on the stylelint repo.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

prettier to check/fix the **/*.js files

> What actually happened (e.g. what warnings or errors did you get)?

[error] No matching files. Patterns tried: '**/*.js' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

**Comment by evilebottnawi** [comment]
Why it is created here? Use `"` quotes, what is problem?

**Comment by bkinnamon** [comment]
The package.json for stylelint keeps erroring out when I try to run tests (`npm test`).

I just submitted the PR that fixes it.

Should I have just submitted a PR without an issue?
