### ISSUE TITLE
Fix clarity of CLI Docs

### ISSUE THREAD

**Issue by orionrush** [stylelint/stylelint#4324]
> Clearly describe the documentation issue

The [CLI Docs](https://stylelint.io/user-guide/cli) instructs users to install stylelint with `npm install stylelint --save-dev`, and then suggests that, as a `devDependancy`, `stylelint --help` could be run. 

Unless there's something wrong with my environment which is preventing the intended behaviour, I believe that for the CLI to work, users would either have to install stylelint with the `--global` flag, or use the full path like so: `./node_modules/.bin/stylelint --help`. 
The use of `npm link` being yet another option....

> What solution would you like to see?

Clarification on intended behaviour and more granular troubleshooting instructions if user runs into a problem. See also #4094.

**Comment by orionrush** [comment]
I take your point that Stylelint's CLI can be invoked in a few different contexts. But when I read the [CLI documentation page](https://stylelint.io/user-guide/cli), it seems to imply that installing stylelint as a `devDependancy` would symlink the 'bare' `stylelint` command so it was available within the project directory. 

I opened this issue because I couldn't tell if I was misunderstanding the intended behaviour (I was), or if my environment was somehow broken (yay its not!). I believe a bit more clarity on this doc page, would be really helpful, especially for onboarding folks that are a bit new to npm.

How about something like the following?

> ### Installation
> 
> Stylelint is an npm package, which can be installed globally using:
> 
> `npm install stylelint --global`
> 
> To install as a dependancy of project, `cd` into the same directory as your package.json and run:
> 
> `npm install stylelint --save-dev`
> 
> ### Usage
> 
> When installed globally, Stylelint's CLI can be invoked as follows:
> 
> `stylelint --help` This will print out stylelint's docs. 
> 
> When used as a project dependency, the Stylelint's CLI can be invoked by providing the full path to the local `.node_modules` directory:
> 
> `./node_modules/.bin/stylelint --help` 
> 
> ### Output
>
> The CLI outputs formatted results into process.stdout, .... _the rest of the docs_

**Comment by hudochenkov** [comment]
Installing stylelint globally (or any other linter) is considered a bad practice. Because different projects could require different linter version installed.

I understand you confusion. I'm afraid teaching how to use npm is outside of scope of stylelint docs. Therefore, we could improve docs to avoid confusion for people new to tooling. For example, we could add a paragraph about `npx` and using it when running locally installed stylelint from Terminal.

**Comment by orionrush** [comment]
Agreed, the docs shouldn't become a tutorial on npm. Arguably though, the page already starts down that path by saying:

> stylelint is an npm package. Install it using:

`npx` would be a great inclusion. 
Would something like the following split the difference?

> ### Installation
> Stylelint is an npm package. To  install it as a dependency of your project using:
> 
> `npm install stylelint --save-dev`
> 
> ### Usage
> Stylelint's CLI can then be invoked as follows:
> 
> `./node_modules/.bin/stylelint --help` prints the stylelint documentation.
> 
> #### Terminal
> In your terminal you can use `npx` to invoke the CLI without having to specify the full path to the local `.node_modules` directory:
> 
> `npx stylelint --help` 
> 
> ### Output
> The CLI outputs formatted results into process.stdout, .... the rest of the docs

**Comment by erasmuswill** [comment]
I'll take a shot at rewording this!
