### ISSUE TITLE
Funky syntax highlighting on website

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#433]
I was reading http://stylelint.io/?http%3A%2F%2Fcdn.rawgit.com%2Fstylelint%2Fstylelint%2F2.0.0%2F%2Fdocs%2Fuser-guide%2Fnode-api.md and noticed some really weird looking syntax highlighting. It's probably more confusing than helpful if we can't get something more accurate going.

**Comment by jeddy3** [comment]
This was an odd one to track down. I don't know how, but using a web font inside the `<pre>` tags was causing the quotes to change to stylistic ones, and thus breaking the highlighter. Anyway, I've stripped it out and it's a bit better now.

Also, I slightly shortened those horrific urls. 

http://localhost:3003/?%2Fdocs%2Fuser-guide%2Fnode-api.md

I'm looking forward to the new website for sure :)
