### ISSUE TITLE
Fix autofix for max-empty-lines

### ISSUE THREAD

**Issue by gxmzjxk** [stylelint/stylelint#4330]
> Clearly describe the bug

When I run `stylelint src/**/*.less`，I got the follow error:
```
 13:1  ✖  Expected no more than 1 empty line   max-empty-lines
 34:1  ✖  Expected no more than 1 empty line   max-empty-lines
```
After I run `stylelint src/**/*.less --fix`，then I run `stylelint src/**/*.less`，I still got the above error.

> Which rule, if any, is the bug related to?

https://github.com/stylelint/stylelint/issues/4232

> What CSS is needed to reproduce the bug?
```less
// 红色
@red-1: #ffd1d1;
@red-3: #ff8585;
@red-5: #f04142;


// 法式-洋红
@magenta-5: #f2c8fa;
@magenta-5: #e26bfa;
@magenta-5: #db24ff;
```

> What stylelint configuration is needed to reproduce the bug?
```json
{
    extends: [
        'stylelint-config-standard'
    ],
    rules: {
        // 缩进 4 个空格
        indentation: 4
    },
    ignoreFiles: [
        '**/*.png|eot|ttf|woff',
        '**/*.js|jsx|ts|tsx',
        'docs/**',
        'scripts/**'
    ]
}
```

> Which version of stylelint are you using?

11.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint src/style/variables/private_colors.less --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

none

> What did you expect to happen?

After run stylelint --fix，stylelint can pass.

> What actually happened (e.g. what warnings or errors did you get)?
The following warnings were flagged:
```shell
src/style/variables/private_colors.less
 13:1  ✖  Expected no more than 1 empty line   max-empty-lines
 34:1  ✖  Expected no more than 1 empty line   max-empty-lines
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

Marking as “help wanted”, consider contributing a fix.

**Comment by ybiquitous** [comment]
via #5507
