### ISSUE TITLE
Sass @use support in Stylelint

### ISSUE THREAD

**Issue by selcet** [stylelint/stylelint#4349]
> Clearly describe the bug

Key changes [in the Sass](https://sass-lang.com/documentation/at-rules/use) - [`@use`](http://sass.logdown.com/posts/7858341-the-module-system-is-launched) has been [released in **Dart Sass 1.23.0**](https://github.com/sass/dart-sass/releases/tag/1.23.0).
I try to configure stylelintrc to handle this feature in manual mode, by adding `@use` into  `at-rule-no-unknown`

> Which rule, if any, is the bug related to?

`at-rule-no-unknown`

> What CSS is needed to reproduce the bug?

```css
@use '<some-file-url>';
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "at-rule-no-unknown": [ true, {
        "ignoreAtRules": ["use"]
      }],
  }
}
```

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Node.js API

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS new feature

> What did you expect to happen?

no errors when using in project Sass `@use`

![Screen+Shot+2019-10-12+19-48-22](https://user-images.githubusercontent.com/6522667/66704943-6ffffc00-ed29-11e9-9579-73b3669befd2.png)

**Comment by hudochenkov** [comment]
I can't reproduce it. https://stylelint.io/demo#N4Igxg9gJgpiBcIACBXAzjABAHRADwDow01cBubAOyoENNhIAbCAJ3kwGIAxHszAXyogANCDQBPSgBcaeBGOJoR4CJQBmASwDm84FUw4QLFIxikE9fQcM0pAWmOm7lCHZSUA1i4Du1CwG1MKWMYYUtKa0jDbRcWGABBKQAlEzNcdn9cdBhcAF0rSP58iIEqfhB+IA

**Comment by evilebottnawi** [comment]
Better open issue in stylelint-sass https://github.com/kristerkari/stylelint-scss/tree/master/src/rules/at-rule-no-unknown

**Comment by hudochenkov** [comment]
Correct, better to use `scss/at-rule-no-unknown`. This rule doesn't have support for `@use` yet, but it's a matter of time when it supported.

**Comment by amk221** [comment]
I think there are a few other rules that don’t work with the `scope.member` syntax.

I’m sure if this is due to stylelint not supporting `use` at a fundamental level, or if it is a per-rule thing.

...in which case I will have to raise an issue for each rule it doesn’t work with.

Can anybody confirm?

**Comment by hudochenkov** [comment]
@amk221 check if rule you're using doesn't have equivalent in `stylelint-scss` plugin. E. g. `scss/at-rule-no-unknown` should be used instead of `at-rule-no-unknown`. If it doesn't sovle the problem create new issue per rule with example made in https://stylelint.io/demo

**Comment by evilebottnawi** [comment]
@hudochenkov i think we can close issue in favor `scss/at-rule-no-unknown`, it have support new at-rules already

**Comment by nikoladev** [comment]
For anyone from the future looking for how to ignore warnings for `@use` in their SCSS files without using the `stylelint-scss` plugin, you can add this to your Stylelint config file:

```json
{
  "rules": {
    "at-rule-no-unknown": [
      true,
      { "ignoreAtRules": [ "use" ] }
    ]
  }
}
```

This works for me with `stylelint@13.9.0`.
