### ISSUE TITLE
sass-lint declarations-before-nesting equivalent 

### ISSUE THREAD

**Issue by lambert-velir** [stylelint/stylelint#4359]
> What is the problem you're trying to solve?

I'm migrating from sass-lint, and there is a rule that I want to enforce using stylelint: https://github.com/sasstools/sass-lint/blob/master/docs/rules/declarations-before-nesting.md
Does this already exist somehow?

> What solution would you like to see?

A new rule that mimics https://github.com/sasstools/sass-lint/blob/master/docs/rules/declarations-before-nesting.md

**Comment by hudochenkov** [comment]
You can use [stylelint-order](https://github.com/hudochenkov/stylelint-order) plugin.
