### ISSUE TITLE
Add `selector-class-pattern-blacklist` rule

### ISSUE THREAD

**Issue by joyzhong** [stylelint/stylelint#4362]
> What is the problem you're trying to solve?

My team maintains a common component library within Google. Our components' classes are all prefixed with `mdc-`, and ideally only our CSS would style elements with these classes. 

We would like to ban `mdc-` class selector usages outside of our code in order to prevent client teams from styling internal elements (and thus making it more difficult for us to roll out core updates in the monorepo). 

> What solution would you like to see?

Currently the selector-class-pattern (https://stylelint.io/user-guide/rules/selector-class-pattern) only allows for specifying an allowed pattern.

It would be great to have a `selector-class-pattern-blacklist` that allows for blacklisting a specific pattern.

**Comment by hudochenkov** [comment]
I believe you can use negative match to target everything except `mdc-`. Similar to https://www.regextester.com/15

**Comment by joyzhong** [comment]
Thanks! Using the negative lookahead regex `^(?!mdc-)` works.

I would still prefer a `selector-class-pattern-blacklist` for ease of use (easier to parse a blacklist pattern than a negative regex). Otherwise, this works well for us.

**Comment by jeddy3** [comment]
Thanks for the suggestion.

I'm in favour of sticking with just `selector-class-pattern`.

The rules follow [a strict set of naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md). Similar rules accept the same options. For example, all `*-pattern` rules accept a single regex whereas all `*-blacklist` rules except a regex, a string or an array of regexes and strings. This consistency helps users when configuring rules.  I'm concerned that the introduction of a `*-pattern-blacklist` rule adds inconsistency as it will accept a regex or an array of regexes which I don't believe is a pattern found in any other rule.

However, I am in favour of updating [this section of the FAQ](https://stylelint.io/user-guide/faq#how-do-i-configure-the--pattern-rules-for-common-css-naming-conventions-like-kebab-case) to include an example of negative match. Labeling as "documentation" and "help wanted".

**Comment by jeddy3** [comment]
> However, I am in favour of updating this section of the FAQ to include an example of negative match. Labeling as "documentation" and "help wanted".

FAQs [are problematic](https://alistapart.com/article/no-more-faqs-create-purposeful-information-for-a-more-effective-user-experi/). We added a new section about [using regexes in rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules/regex.md) to the user guide, which we link to from the [SUPPORT.md](https://github.com/stylelint/stylelint/blob/master/SUPPORT.md) instead.
