### ISSUE TITLE
no-duplicate-selectors

### ISSUE THREAD

**Issue by makotot** [stylelint/stylelint#437]
Like [scss-lint's mrgeable selector](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#mergeableselector), disallow to define same selector more than once.

**Comment by jeddy3** [comment]
Thanks for the suggestion @makotot!

@davidtheclark Seems like a worthwhile one. What do you think? 

I think it'll need to be called `no-duplicate-selectors` to match the conventions. And I think it should compare the whole selector, whether it be a _simple_, _compound_ or _complex. 

If we do add it, I believe this will be first non-whitespace rule whose _thing_ is the `sheet` itself.  More on that in #436...

**Comment by davidtheclark** [comment]
Addressing users of postcss-import will be tricky but I have an idea (look at the rule nodes for the selectors and compare the `source`s).

Also have to make sure not to break when media queries include selectors duplicated outside the query.

Yes, I think this is worthwhile.

**Comment by jeddy3** [comment]
> Addressing users of postcss-import will be tricky but I have an idea

Agreed.  And your idea sounds good :)

> Also have to make sure not to break when media queries include selectors duplicated outside the query.

Good point. I suggest we approach this rule cautiously as it'll likely not play well with CSS Processors, especially those supporting nesting.

**Comment by davidtheclark** [comment]
Would all the problems with this rule be solved if we just requested in the docs that if you use some kind of fancy selector processing (nesting, variables-in-selectors, etc.), that needs to happen *before* stylelint runs? I can't think of any other way this rule would work -- but that way seems fine to me.

**Comment by makotot** [comment]
> Would all the problems with this rule be solved if we just requested in the docs that if you use some kind of fancy selector processing (nesting, variables-in-selectors, etc.), that needs to happen before stylelint runs?

I agree with you. I think guide in docs is enough.

**Comment by jeddy3** [comment]
Ditto.
