### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined for Sass for insude Vue

### ISSUE THREAD

**Issue by akoidan** [stylelint/stylelint#4373]
> Clearly describe the bug

The sass loops inside of **VUE** files cause linter to crash

> Which rule, if any, is the bug related to?

not related to any rule

> What CSS is needed to reproduce the bug?

Any rule that has `@for` loop in sass

```sass
  $class-slug: for !default

  @for $i from 1 through 4
    .#{$class-slug}-#{$i}
      width: 60px + $i
      color: black
```

> What stylelint configuration is needed to reproduce the bug?

Any rule, is not rule specific. Put something to tigger the linter.

```json
{
  "rules": {
    "color-named": "never"
  }
}
```

> Which version of stylelint are you using?

 11.1.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?
 
  `./node_modules/.bin/stylelint Sass.vue`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

 Yes, it's related to SASS loops

> What did you expect to happen?

 stylelint would work instead of failing with an error 

> What actually happened (e.g. what warnings or errors did you get)?

An error occured

```text
TypeError: Cannot read property 'start' of undefined
    at LocalFixer.node (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:35:27)
    at /home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:41:9
    at /home/andrew/sass-for/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/andrew/sass-for/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/andrew/sass-for/node_modules/postcss/lib/container.js:131:17)
    at LocalFixer.root (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:40:8)
    at LocalFixer.parse (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:69:9)
    at parseStyle (/home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:88:39)
    at /home/andrew/sass-for/node_modules/postcss-syntax/parse-style.js:103:17
    at Array.forEach (<anonymous>)
```

To reproduce the issue:
 - git clone https://github.com/akoidan/style-sass-for-issue
 - cd style-sass-for-issue
 - yarn install
 - yarn run works
 - yarn run fails

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

It's a problem with `postcss-sass` parser. Here the [demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIAkYA2BDAzpgtJ1ArgObwAEAZhAE6kCEs56BqALgDoB2nAApTUgEsKVCAFtSARlIsAFiOIzSAFk6lSAOgDEwFBmx5CRAL45tgo6rWkA7gKiyyANgAMABwAepANSlBltZCo1GQARhhgANYgADQgmACeHCzo7ghxWJgx4BAc5AJEacCWbCBUzDCYJWRFHFakJegsOGWoMDgcEDgEHBEd1lwI0mUw0f71IGEQke2dMKKuLPFVQwQjYyWB1DM4AhwAbuiodjgyMO7LLMOjtVYbYqIwSdtzC0uDl6vXdSWwaOhUjQEORwk2mHRwUAIriOYEabVcIlcMCoLAEFWWAG0xmoPmsbnUanVviB8h0qDBMdiiXcOJgYGACKi9m1IdCBLCWBUcLZZBCBORyMjHk0DoR0SAqWoALpUiz40hSr63EC-DAA1HA0ERbaYGTUWToDhQHAIiBIlHxHAQZlUKh2cVkXFKtQlShPRiiASoS3g1kwuHtdAPSrvK7rEBupoer0+zqe7C7Ig4IiPZHsnDR704CIweLWahQC5h+Wu7pgDUcHCw1Bgba7UV2IufcPkMsVquHWvg7qYVzoMAwY1m5GNahNvHE1scctAytHDgwf7JgFQNFPcEdWnJI3-Y2r8kznLj53jHPxcgAh4Q+lqwHA8ECeb6w3sUPNksgB6r9AZxcsAjkoGV7dj0fQDI6xbEr6FQDkaiZ4EiYD8uyAiLMe4a+lC-qcjgjQ7E+KLNOUIYQe+UGdH67IBnSrTltQJErBOyrgi8ix4BAAEDuhH4se4lw-nSnqbLS3HkTs+yHMcUAcWEbT4FgMhVvcwoMU64amuabEgb0ED9KJyo0fSLBbK4dIENJVZ6Lg2lgfpLpxDAtHGVQJpmRZjlzMK2zdDpelvkx9mGXRLmLEi3mgbp4GMSeJSYJc8EbjA1jzhS-kxSA3SoeFvlRWpH54S0bSsZaKUgjAfCpWQWLyvZhzWOg8QhieaiEkS9lnAOCyUjV1ITEEkStPo6DkJyLmYEGbQcBNIL9REg1NZKyp5FQcXtBUnKFhKPXSs1yqktQlWkNVbXEsNo1KaIDxJCUi0yj1cp1Iq4YFeUQFtLCdLLCUQTWMiJTpS9rRvQh-ZtGdf2DA0qD1Y1eCJkDKX-c9TSFXgczshAQSVguyW7GDI0Q2QUMwwtH5apZECYPBIQAgOODFTgpUhOVB1fSAC42kjZOzRTVMcEmNOg2tuMLrhBNUGzdUNaTxLk2glPU7Tk1JUzLPkpL0PSzgojMKijN41zss8-LfMC0rIN08zFUayTcP8wjBsxOG5PDhwitCzjpXgxLkMgFLsM66wAj6wuhvKi7SJu-zILm72QvezbWumw7odO9zUzaq77t03Hltq4dxPS2H9mbC5pzuB2n2+z9EPpaXJxnIzjxELIbO6vqxfjJAl1eQzqvW4Mx29f7MtEq1bUlB1MBdYPi32ctq0LnFg43dtCq7fZ+3q7Pa+BYsrTzk03eiIaUAhrdspjE9H7H151gyKhFR9nTuxU7AieNZ3GwEHFYgmoiyI2J9zxmVAeVUqSF0-mnNq49epTxnuA3e4xvZVh-sZUQ-9hwWk7hPCMAgVpNCXhtVeJ116LRKFvQ6Q9SENHFhdK6r4N57VpPaO2RAU5tC1CQk6d02oPSsNfYkqp-h3krCEQ0SZc741GmzDmtdwzCPVLOEEEiLacPzh-Ue9lFGiJmhnNGQlMb3hViAhOvsR7a11sHRG0DlQ6PbOTQSGMsZqLFjI8xmtYbJzaDY9K9jlGOPRsJVxVtWa+zkT7PxN4REOJ5t4kObQT4V38TkBiEgol-CUZqHm-EvTwSccJTRX8VTRKyZWYJntTHi00ZYoOCTikpPKUYysUi3GE2QZ43A8TfEKNKbo4JrTQnbyJuzGAnNbHaL6e2YBoshlUIgX7TpODSCwOJPA18iDSG1ToY05Zk58GL3WivLapDBEnQoUQMk8ykG0POrfa6EzzkkhYbANhHC9GRG4W1XhRJ+E7RbG2ZRx8fyVNFmYkZFjA56x6R+Kch4mmXQEs-aR7TIFdPhj4x26U4XtmBSEjR4SxnyNhYC4EST6bzDYilBizhsWkuxtND6BcQA10iQC6c7Y+zkiSKcOk1kTGi1fvaGpULrFYvZfCk0-xhS8q5K0oV79CU2jeZi1OdKOXKPvo-Vp4KOkk2KbsWASRRHLAAEzpVaPzXkAAvZEnQQKoTsuMclMyHSSHSl+AQP5BSNAAu9ZprjdVouKZ671f4-VKRcYMglIyIkhsHF638vrAJTSvEytmrL43fiTf+QCXKZUVDlci8Sb9mVxseSUUNOaI0An5m0LBo4xrFqDYs-VFbPwJrDcmtotaUxWnNI2-FYC9VF3bVWgAjqsKgJUBCrTxaClFPsIWdNqdC8VH4J1TpnXO+4SL47VI8bbbp67iSbuRNuo+u6h1hNjUStlPFZiY25A-TkUinUlHBPGU29MjRWnIOxTiysRaHTylBAgohmYuVaOgVc0dbUiCKe2jg4HIPbFyfOJM8HKbvpABpQBlp03V10sS4kqNXWgJvUdBZkKrH1MeS1chIB1ndS2eMBehCjmbVukwi5VyWNbNuciehwovlEh+XUP5ZCPxBWcrhFg8UQiMk4bTHMLAunFoVWWu9xSZNbEaAppT-aRyyZ1Qe294z0q6Zcvpu0imcINpM8WuZsjtPtqsxdEIuxB2mfccuttlmPLBQ815xzQtnOHtHQFpyWxYCYFglAF8wWpqyY3MCN9aVwzuaODuxFwsvZmZHVAqLRktjZcvbl6Nw6P2ueK0Fl1lKZ1L2WLSzLgXZOmRgOZTofx9CEZGZmtzbWTJuW61ZKV3LZCFvU0LTTLmLOteiy5DrXX6atAYZXZlA3avtZG6tzyTwKkQGSBWNm0kCCyR00NkK8Qwp9fGFt8MmUj5YE28R+9xJRSrH1jlk+eWqm+cK7gUVdH0qfcxT9vddMW0WOPWq8MYPvvld+5Vyj1X5sfgR2V7WKQKWvASTSywcojAgCMEAA) with Sass syntax failing.

Please, open an issue in [postcss-sass](https://github.com/AleshaOleg/postcss-sass).

**Comment by akoidan** [comment]
Forwaded to https://github.com/AleshaOleg/postcss-sass/issues/120
