### ISSUE TITLE
plan cosmiconfig v6 to next future-major

### ISSUE THREAD

**Issue by vankop** [stylelint/stylelint#4386]
> What is the problem you're trying to solve?

add `cosmiconfig@6` to next major

https://github.com/davidtheclark/cosmiconfig/pull/216

**Comment by hudochenkov** [comment]
It was released https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md

**Comment by vankop** [comment]
So I think this can be closed
