### ISSUE TITLE
Include a sample .stylelintrc file and document the .stylelintrc format

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#439]
- [x] Include a sample .stylelintrc file
- [x] Document the .stylelintrc format

**Comment by jeddy3** [comment]
The configuration object is described in the [configuration part of the user guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md).

And there are examples for `rules`, `extends` and `plugins`.

Is that you're after @ntwb, or are you referring to something else? 

Either way, perhaps we need to sign-post this part of the _user guide_ better?

**Comment by ntwb** [comment]
> The configuration object is described in the configuration part of the user guide.
> Either way, perhaps we need to sign-post this part of the user guide better?

Yeah, I missed this doc shuffle and didn't see the sign posts :smirk:

**Comment by jeddy3** [comment]
No problemo :)

Do you think we need to do more than signpost it in the [Quick start](https://github.com/stylelint/stylelint#quick-start) of the main readme?

> 3. Create your [configuration](/docs/user-guide/configuration.md), probably as a `.stylelintrc` file.

Or is that enough?

**Comment by ntwb** [comment]
That's fine, my eyesight not so much ¯\_(ツ)_/¯
