### ISSUE TITLE
Enforce empty lines before and/or after multi-line declarations

### ISSUE THREAD

**Issue by alexhribsek** [stylelint/stylelint#4390]
> What is the problem you're trying to solve?

I think it would be neat to have a rule that can enforce empty lines before and/or after multi-line declarations (e.g. complex mixins).

E.g.:

```
rule {
    singleLineDeclaration;
    singleLineDeclaration;
    singleLineDeclaration;

    multiLineDeclaration((
        ...
    ));

    singleLineDeclaration;
    singleLineDeclaration;
    singleLineDeclaration;
}
```

> What solution would you like to see?

E.g.:

```
...
"declaration-empty-line-before": [
    "multi-line",
    {
        "except": [
            "first-nested"
        ]
    }
],
"declaration-empty-line-after": [
    "multi-line",
    {
        "except": [
            "last-nested"
        ]
    }
],
...
```

**Comment by evilebottnawi** [comment]
> complex mixins 
?

**Comment by alexhribsek** [comment]
I have lots of custom mixins that receive a complex map as an argument. For example:
```
@include myCustomMixin((
    argument1: ...
    argument2: ...
    argument3: ...
    ...
    argumentX: ...
));
```

For readability sake it makes sense to wrap this mixin call with newlines so they're easily distinguishable compared to single-line declarations.

**Comment by evilebottnawi** [comment]
@alexhribsek out of scope stylelint, please open issue in `stylelint-scss`
