### ISSUE TITLE
Add missing documetation for some rules

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#44]
- [x]  block-opening-brace-space
- [x]  block-opening-brace-newline
- [x] declaration-bang-space
- [x] declaration-block-trailing-semicolon
- [x] declaration-comma-space
- [x] function-comma-space
- [x] number-leading-zero
- [x] rule-set-no-single-line
- [x] selector-combinator-space

**Comment by jeddy3** [comment]
I can do this one.

**Comment by jeddy3** [comment]
Done in #75
