### ISSUE TITLE
Stage 2 decorators cannot be used to decorate parameters

### ISSUE THREAD

**Issue by Gil707** [stylelint/stylelint#4402]
In Nest.js we use decorators outside functions and inside function parameters,
for example

```
@Controller('test')
@UseInterceptors(TestInterceptor)
export class TestController {
    @Get()
	getTest(@Req() request: ExperimentsRequest) {
		return request.test
	}
}
```
And stylelint shows error on **@Req() request: ExperimentsRequest**
`21:2  ✖  Stage 2 decorators cannot be used to decorate parameters (21:2)`

How I can ignore this? Now I'm exclude this folder (./server) but may be there is some parameter preventing this error?

Here is `.stylelintrc`
```
{
	"processors": ["stylelint-processor-styled-components"],
	"extends": [
		"stylelint-config-styled-components"
	],
	"ignoreFiles": [
		"./src/server/**"
	],
	"syntax": "css-in-js"
}
```
stylelint `11.1.1`

**Comment by evilebottnawi** [comment]
Do not use `stylelint-processor-styled-components`, it is outdated, stylelint support CSS-in-JS out of box

**Comment by Gil707** [comment]
Thank's

**Comment by evilebottnawi** [comment]
@Gil707 Can we close issue?

**Comment by Gil707** [comment]
> @Gil707 Can we close issue?

Yes, everything ok without stylelint-processor
