### ISSUE TITLE
Fix line numbering for quotes in single line comments

### ISSUE THREAD

**Issue by Zae** [stylelint/stylelint#4411]
Hi,

I noticed that stylelint does not handle single quotes in // comments well. I found bug #547 and 3882 that is basically the same error however it seems that this bug might have only been fixed for scss and not for less.

I can sort of reproduce it in the demo environment, but not really. Locally the quote causes the linenumbers to start at 0 at the quote again, so errors following the quote will have incorrect linenumbers.

In the demo the duplicate selector isn't found by styleline, but only if the quote if on the end of the line, locally it doesn't matter where the quote is in the comment.

/* */ comments work fine btw.

Version: 9.10.1 and 11.1.1 (did not test any other versions)

~~~
a {
  color: #FFF;
}

p {
  color: #ASDASD;
  // Dont do this it breaks'
}

a {
  color:#BROKEN;
}
~~~

**Comment by evilebottnawi** [comment]
Please report issue here https://github.com/shellscape/postcss-less

**Comment by jeddy3** [comment]
Help was requested upstream, so labeling this as "help wanted".

**Comment by jeddy3** [comment]
The [`syntax` option was removed](https://github.com/stylelint/stylelint/issues/5289) for the [14.0.0 release](https://github.com/stylelint/stylelint/issues/5205). (See the [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md#syntax-option-and-automatic-inferral-of-syntax).)

Closing in favour of the the upstream issue as the syntax is no longer bundled by Stylelint.
