### ISSUE TITLE
Replace `indexOf` with `includes`

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4414]
IMHO this makes it clearer. I have a WIP branch, which actually breaks one of the tests so I think something flaky is going there :)

https://github.com/stylelint/stylelint/blob/7d56168ee3c99d3073be312d293675ec9061689d/lib/utils/containsString.js#L37

`value` can be a regex in one of the tests and with this patch this is revealed.

https://github.com/stylelint/stylelint/compare/master...XhmikosR:includes

Let me know if you want me to proceed with a PR.

**Comment by hudochenkov** [comment]
Go for it!
