### ISSUE TITLE
Use `startsWith`/`endsWith` when possible

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4415]
This makes things more clear IMHO.

I have a WIP branch: https://github.com/stylelint/stylelint/compare/master...XhmikosR:starts-ends-with

I didn't change all the instances on purpose; in some cases we check the second character too, so I kept it as it was.

Let me know what you think and if I should make it into a PR.

**Comment by hudochenkov** [comment]
Go for it!
