### ISSUE TITLE
Support loading config from package.json

### ISSUE THREAD

**Issue by keithamus** [stylelint/stylelint#442]
Just like eslint does, stylelint should support loading its config from the package.json.

Eslint reads an `eslint` field in the package.json, for example:

```json
{
  "name": "my-super-awesome-project",
  "eslint": {
    "extends": ["..."],
    "rules": {
      "...": "..."
    }
  },
  "dependencies": {
    "eslint": "^1.7.2",
  }
}
```

It'd be great if I could do exactly the same with stylelint:

```json
{
  "name": "my-super-awesome-project",
  "stylelint": {
    "extends": ["..."],
    "rules": {
      "...": "..."
    }
  },
  "dependencies": {
    "stylelint": "^2.1.0",
  }
}
```

**Comment by davidtheclark** [comment]
@keithamus : Absolutely. Thanks for the issue.

I wonder if you could answer a question for me about ESLint's use of package.json: Do you have to make sure to run the ESLint CLI from the project root, the place with package.json, in order for that way of loading config to work? Or can you run from anywhere in the project and it will check up the file tree for package.jsons to read?

**Comment by keithamus** [comment]
It does indeed check up the file tree. The logic for finding both `.eslintrc` and `package.json` is driven by [file-finder.js](https://github.com/eslint/eslint/blob/master/lib/file-finder.js) which is called by [`Config.prototype.findLocalConfigFiles`](https://github.com/eslint/eslint/blob/master/lib/config.js#L467-L478)

**Comment by davidtheclark** [comment]
@keithamus : If there's both a `.stylelintrc` file *and* a `stylelint` property in `package.json`, which should take priority (override)?

**Comment by keithamus** [comment]
I think eslint will read from both, mering the configs. I presue .eslinrtc takes precedent. Here's the debug output that eslint provides:

```js
eslint:config Using .eslintrc and package.json files +1ms
eslint:config Loading /Users/<snip>/package.json +2ms
eslint:config Loading /Users/<snip>/.eslintrc +7ms
eslint:config Merging command line environment settings +1ms
```

If you read through http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy, the documentation suggests that any `.eslintrc` files in lower directories will be merged with `pacakge.json#eslintConfig`, where `.eslintrc` overrides any option within `pacakge.json#eslintConfig`. 

The typical usage pattern I have is: `pacakge.json#eslintConfig` has the main project config, and sometimes I'll have a `test/.eslintrc` to override a couple of rules for writing tests easier. Although for `stylelint` I'd probably just use the one config inside `package.json`.

**Comment by davidtheclark** [comment]
I think we might have to tackle this one and #418 at the same time by writing our own configuration loader instead of just using rc. We can use rc itself, eslint, jscs, and probably some other projects (babel?) as examples to work from.

(Unless ... @MoOx, any chance you know an existing project that extends rc to load config from `[projectname]Config` properties in `package.json` files found via the same file-finding function?)

**Comment by MoOx** [comment]
I have to admit that a package that can handle the following could be great:
- custom config file provided by hand (-c or via node api) (that can support commonjs by providing a .js file)
- package.json [projectName] section (I don't see the need of `[projectName]Config`, since package.json is a config file already...
- .[projectName]rc (yaml/json) in the tree hierarchy.
but I don't know a module that does that.

**Comment by MoOx** [comment]
rc can be used for the .rc thing, maybe a module can use it in addition to the others options (custom config file + package.json section). That could help for https://github.com/postcss/postcss/issues/477

**Comment by davidtheclark** [comment]
Anybody here have an opinion about stylelint *not* automatically merging all the `.stylelintrc` files it finds? Instead, it would just use the first configuration it finds. And if you wanted to extend another config, you would do so deliberately with `extends`. I was thinking about that change here: https://github.com/dominictarr/rc/issues/64#issuecomment-153207916 I thought that maybe the auto-merging that rc enables would actually cause more confusion than good for our type of tool.

**Comment by MoOx** [comment]
I think indeed the same thing: we don't really need rc.
If you want, we can use "rc-loader" (rewrite it) to support the following:

- try package.json "projectname" section from process.cwd() (or parent folder until one is found),
- try process.cwd() (or parent) for ".{projectname}rc" or "{projectname}(.config?).js" (to support commonjs)

**Comment by jeddy3** [comment]
> I thought that maybe the auto-merging that rc enables would actually cause more confusion than good for our type of tool.

Agreed.

**Comment by keithamus** [comment]
> Anybody here have an opinion about stylelint not automatically merging all the .stylelintrc files it finds? Instead, it would just use the first configuration it finds.

For my use case this is fine - I use one canonical config via package.json. However, users coming from eslint - with the expectation that it merges config - might be surprised to see that this project doesn't behave similarly. I think you mentioned a valid use case in https://github.com/dominictarr/rc/issues/64#issuecomment-153202399:

> You might also have a user-configuration for your linter at e.g. ~/.stylelintrc, just to help you write code the way you like to write it even when a specific project doesn't itself enforce conventions

**Comment by davidtheclark** [comment]
@keithamus: That user I mentioned would still be able to use their `~/.stylelintrc` file *as long as there was no other configuration between that and the project. So in most cases if the project does not contain a configuration of its own, stylelint will find the user's config in their home dir.

**Comment by davidtheclark** [comment]
@TrySound: Sounds like you think we should write our own loader instead of using rc -- https://github.com/stylelint/stylelint/issues/481#issuecomment-153766108. I'm not sure our loader wouldn't also be sync, though ... but we could certainly try to make useful error messages.

**Comment by TrySound** [comment]
@davidtheclark PostCSS can be async, so why not?

**Comment by davidtheclark** [comment]
Just not making guarantees until I actually write code. I can think of some challenges --- but who knows, just got to get into the code. For example, if the could *could* have a config file either at (a) `./.stylelintrc` or (b) `../.stylelintrc` or (c) `../../.stylelintrc` or (d) `../../../.stylelintrc` --- then how would I know that I should look for (b) until I have already tried and failed with (a)? I wouldn't want to async search for *all* of them initially, right? I don't know.

**Comment by TrySound** [comment]
@davidtheclark We can separate .stylelintrc looking (in series) and package.json looking and pass them in Promise.all. Then just read both and get result.

**Comment by davidtheclark** [comment]
@stylelint/owners : Is anybody opposed to writing our own config loader and dropping rc? Here's what I think the requirements would be (integrating with @MoOx said above):

- Look for `.stylelintrc`, `stylelint.config.js`, and `stylelint` properties in `package.json` files.
- Starting from `process.cwd()`, look for these files in `./ ../ ../../ ../../../` etc., all the way to `~` (user home directory), checking first for `stylelint` in `package.json`, second for `.stylelintrc`, third for `stylelint.config.js`.
- *Stop looking at the first one that is found*, and use that one as the config.
- Build in YAML support for `.stylelintrc`.

Does that sound good to everyone? 

Also @MoOx, if we made that do you think it would suit the other projects you had in mind?

**Comment by TrySound** [comment]
I can help with rc-loader

**Comment by MoOx** [comment]
Sounds really good.
I think we should use the exact same convention for postcss for #https://github.com/postcss/postcss/issues/477 (@ai does the rules above look good to you too?)

@davidtheclark that would be nice to have this logic under rc-loader. I am adding you and @TrySound as collab, feel free to add more people if relevant. Also adding you as an npm owner.

**Comment by davidtheclark** [comment]
If we try to do the above as a generic project, rc-loader, do you think it would be worthwhile to try including the `extends` logic that stylelint supports? To clarify:

- The config can have an `extends` property, whose value is a single string or an array of strings. Each string must be *a lookup that `require()` would understand*, so either:
  - A npm module name
  - An absolute path
  - A relative path, relative to the config file that is extending
- If config A extends config B, the result is config A's properties merged into config B, with config A taking priority.

**Comment by davidtheclark** [comment]
Also: Do any of you know how to write effective unit tests for a project like this? Know of a good package that mocks a file system, or something like that? Of would we stub `fs` functions?

**Comment by ai** [comment]
@MoOx yeap, seems good :)

**Comment by MoOx** [comment]
Not sure about the extends part, but that can definitely be an option in this package.
I think you should split the logic in multiple parts in order to avoid testing the fs. This logic need a tree and a method to read parent of a tree if needed. Then you can write the merging part.
Not sure what is the best way to test indeed.
You can easily define a "root" in the method (that will by default use process.cwd() for real world usage) and a "stop" (by default [user home](https://www.npmjs.com/package/user-home)), so you can easily test in a fixture folder with any tree.

**Comment by davidtheclark** [comment]
Thanks for all the input everyone. Sounds like the rc-loader project is the way to go. I'm going to close this to create a more focused issue.
