### ISSUE TITLE
Use a Set for unique collections

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4422]
Wouldn't it make more sense if we use a real Set in

https://github.com/stylelint/stylelint/blob/9071fdd4ef8e2bba78c22fdec54b96f143faed79/lib/rules/length-zero-no-unit/index.js#L38

There might be more places we could do the same, I just noticed this one.

**Comment by vankop** [comment]
here it used with correct purpose, we need to ignore some values, e.g math functions:

Sample 1:
`calc(10px + 10%) 10px` here we need to ignore `calc(10px + 10%)` so we create an array of all indexes and walk AST node by node, so when we found a function node `calc`  with string value `calc(10px + 10%)`  we mark all indexes in source string as `true` starting from `c` index to `)` + 1 index.

Sample 2:
`calc(myfunction(3px) + 10px) + 5`

1. we found function node `calc` and mark all indexes in source string as `true` starting from `c` index to last `)` + 1 index.
2. we found function node `myfunction` and mark all indexes in source string as `false` starting from `m` index to first `)` + 1 index

So in sample 2 we don't ignore `myfunction`

**Comment by XhmikosR** [comment]
Ah, then I guess the comment confused me :)

https://github.com/stylelint/stylelint/blob/9071fdd4ef8e2bba78c22fdec54b96f143faed79/lib/rules/length-zero-no-unit/index.js#L102-L103

That being said, it would be nice if someone could check the codebase if there are cases Set could be used. If not, feel free to close the issue.

**Comment by hudochenkov** [comment]
I don't see value converting stuff to Sets.

**Comment by hudochenkov** [comment]
I don't think it's worth it to convert to Sets just for the sake of using them.

**Comment by XhmikosR** [comment]
I only suggested it in cases it makes sense only, i.e. we need a unique collection of data. If we don't have any such cases, we can close this issue.

**Comment by jeddy3** [comment]
> __I only suggested it in cases it makes sense only, i.e. we need a unique collection of data.__ If we don't have any such cases, we can close this issue.

SGTM. Labeling as "help wanted".

**Comment by ybiquitous** [comment]
I'm closing this issue because we've actively used `Set` as possible, for example:

https://github.com/stylelint/stylelint/blob/16754b1dab7590238f9b842ebd25678f8204ae9d/lib/reference/functions.js#L3

If you find a code where we can use `Set` for refactoring, please directly open a pull request.
