### ISSUE TITLE
Using '--fix' results in "TypeError: Cannot read property 'search' of undefined" exception

### ISSUE THREAD

**Issue by MichaelKaaden** [stylelint/stylelint#4424]
> Clearly describe the bug

Running `npx stylelint --fix foo.scss` results in

```
TypeError: Cannot read property 'search' of undefined
    ...
```

`npx stylelint foo.scss` results in a perfecty reasonable

```shell
foo.scss
 1:3  ⚠  Expected img is used with @media                         a11y/media-prefers-reduced-motion
         (prefers-reduced-motion)                                                                  
 5:3  ✖  Unexpected empty line before declaration                 declaration-empty-line-before

```

A repo to reproduce is error is available at [https://github.com/MichaelKaaden/stylelint-issue.git](https://github.com/MichaelKaaden/stylelint-issue.git).
Please use `npm install`, followed by `npm run lint` to see the exception.

> Which rule, if any, is the bug related to?

The exception happens inside `block-closing-brace-newline-after`.

> What SCSS is needed to reproduce the bug?

```scss
img {
  max-width: 100%;
  max-height: 600px;

  transition: max-height 0.3s ease;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-standard-scss",
  "plugins": [
    "stylelint-scss",
    "stylelint-a11y"
  ],
  "rules": {
    "a11y/media-prefers-reduced-motion": [
      true,
      {
        "severity": "warning"
      }
    ]
  }
}
```

> Which version of stylelint are you using?

`12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint --fix foo.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Nope, don't think so.

> What did you expect to happen?

It should remove the empty line.

> What actually happened (e.g. what warnings or errors did you get)?

It threw the following exception:

```shell
TypeError: Cannot read property 'search' of undefined
    at <input css 1>:1:1
    at Object.err (/private/tmp/issue/node_modules/stylelint/lib/rules/block-closing-brace-newline-after/index.js:105:46)
    at expectAfter (/private/tmp/issue/node_modules/stylelint/lib/utils/whitespaceChecker.js:303:14)
    at after (/private/tmp/issue/node_modules/stylelint/lib/utils/whitespaceChecker.js:154:5)
    at Object.afterOneOnly (/private/tmp/issue/node_modules/stylelint/lib/utils/whitespaceChecker.js:265:3)
    at check (/private/tmp/issue/node_modules/stylelint/lib/rules/block-closing-brace-newline-after/index.js:95:12)
    at /private/tmp/issue/node_modules/postcss/lib/container.js:295:18
    at /private/tmp/issue/node_modules/postcss/lib/container.js:135:18
    at Root.each (/private/tmp/issue/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/private/tmp/issue/node_modules/postcss/lib/container.js:131:17)
    at Root.walkAtRules (/private/tmp/issue/node_modules/postcss/lib/container.js:293:19)
```

The object the code stumbles upon is

   ```json
   {
     "raws": {
       "between": " ",
       "semicolon": true,
       "after": "\n"
     },
     "type": "rule"
     // ...
   }
   ```

Obviously, no "before" property here.

**Comment by hudochenkov** [comment]
I tried this config (disabled stylelint rule that caused error):

```json
{
  "extends": "stylelint-config-standard-scss",
  "plugins": [
    "stylelint-scss",
    "stylelint-a11y"
  ],
  "rules": {
    "a11y/media-prefers-reduced-motion": [
      true,
      {
        "severity": "warning"
      }
    ],
    "block-closing-brace-newline-after": null
  }
}
```

And got this is output:

```scss
@media screen and (prefers-reduced-motion: reduce) {
  img {
    max-width: 100%;
    max-height: 600px;
    transition: none;
  }
}

undefinedimg {
  max-width: 100%;
  max-height: 600px;
  transition: max-height 0.3s ease;
}
```

It might be that some combination of rules causes wrong PostCSS AST. But I think that the problem in `a11y/media-prefers-reduced-motion` rule. The way [how it creates `@media`](https://github.com/YozhikM/stylelint-a11y/blob/1c522f677e1bd68420cc47a935e9865dd797159a/src/rules/media-prefers-reduced-motion/index.js#L129-L132) looks weird. That's probably the issue, because node created without PostCSS API, and node doesn't have every property it would have if it parsed or created with PostCSS API.

**Comment by hudochenkov** [comment]
You can report my findings to `stylelint-a11y` repository. Plugins should not break PostCSS AST.

**Comment by MichaelKaaden** [comment]
Thanks a lot for your effort. I created https://github.com/YozhikM/stylelint-a11y/issues/49 as follow-up to this bug report.
