### ISSUE TITLE
add stylelint.config.mjs and stylelint.config.cjs file for esm and commonjs

### ISSUE THREAD

**Issue by xiaoxiangmoe** [stylelint/stylelint#4447]
add `stylelint.config.mjs` and `stylelint.config.cjs` file for esm and commonjs.

> This comes from Node.js finally unflagging ESM (ie --experimental-modules).
> 
> The Node.js Modules team took time to explore matters of source disambiguation where unlike browsers that only ever deal with text/javascript files based on clear intent of loading, tooling and Node.js itself cannot always assume the format of .js files.
>
> Package authors can indicate that .js is either ESM of CommonJS using the package.type field — and so to close the gap for tools expecting CommonJS configuration in a package.type = "module" (ie ESM) the .cjs extension may be necessary when relying on require(configuration) in their implementation.
>
> The reverse can be accomplished with .mjs.

https://github.com/prettier/prettier/issues/7049#issuecomment-558109668

**Comment by ntwb** [comment]
I think we should rely on cosmiconfig for this, just as @evilebottnawi has create an issue already:

> Done davidtheclark/cosmiconfig#224

**Comment by hudochenkov** [comment]
Correct. This is something to `cosmiconfig` to implement. We use `cosmiconfig` to find configs, and to support different config formats.

**Comment by rifler** [comment]
> Correct. This is something for `cosmiconfig` to implement. We use `cosmiconfig` to find configs, and to support different config formats.

cosmiconfig release 7.x version with cjs support
