### ISSUE TITLE
Autofix changes files without offenses

### ISSUE THREAD

**Issue by dreyks** [stylelint/stylelint#4449]
> Clearly describe the bug

when running with `--fix` stylelint generates the output that is not equal to the input even when no changes where made

> Which rule, if any, is the bug related to?

generating output with postcss

> What CSS is needed to reproduce the bug?

```js
import React from 'react'

export default () => {
  const left = 0
  const top = 0

  return (
    <div
      style={{ top, left }}
    >
      Test
    </div>
  )
}

```
> What stylelint configuration is needed to reproduce the bug?

empty config

```json
{
  "rules": {
  }
}
```

> Which version of stylelint are you using?

`stylelint@12.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `--fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, CSS-in-JS

> What did you expect to happen?

the file is not changed

> What actually happened (e.g. what warnings or errors did you get)?

```js
import React from 'react'

export default () => {
  const left = 0
  const top = 0

  return (
    <div
      style={{ top:top, left:left }}
    >
      Test
    </div>
  )
}
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by fanich37** [comment]
Seems that it's not `stylelint` issue. I tried to run standalone with `postcss-jsx` parser w/o `--fix` and it returned the same result as you provided.

```js
it('standalone shouldn`t change `jsx` file if no `fix` were applied', () => {
	const config = {
		rules: {},
	}

	return standalone({
		config,
		syntax: 'css-in-js',
		customSyntax: `${fixturesPath}/css-in-js-syntax`,
		code: 'return (<div style={{ top, left }}>Test</div>);',
		formatter: stringFormatter,
	}).then((linted) => {
		const results = linted.results;

		console.log(results) // eslint-disable-line no-console
	})
});
/*
[ { source: '<input css 9>',
        deprecations: [],
        invalidOptionWarnings: [],
        parseErrors: [],
        errored: false,
        warnings: [],
        ignored: undefined,
        _postcssResult:
         Result {
           processor: [Processor],
           messages: [],
           root: [Document],
           opts: [Object],
           css: 'return (<div style={{ top:top, left:left }}>Test</div>);',
           map: undefined,
           stylelint: [Object] } } ]
*/

**Comment by evilebottnawi** [comment]
Yes, it is problem postcss-jsx :disappointed:

**Comment by dreyks** [comment]
should i report this issue there?

**Comment by BPScott** [comment]
I've just found a fix for this and have opened a PR upstream: https://github.com/gucong3000/postcss-jsx/pull/67

**Comment by BPScott** [comment]
Reopening this, a fix gas been merged upstream but it still needs to be released and stylelint still needs to pull in that new version of postcss-jsx
