### ISSUE TITLE
Enable caching for GitHub Actions

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4454]
This was recently made available https://github.com/actions/cache

I started playing with it and works good enough. I haven't made the switch yet myself because I need to tweak it more. For reference https://github.com/twbs/bootstrap/pull/29765

I don't expect this to save a lot since `npm ci` is pretty fast already, but I guess if it doesn't cause any issues (which it shouldn't if we do it properly), every little bit helps.

**Comment by jeddy3** [comment]
SGTM. Labeling accordingly.

**Comment by hudochenkov** [comment]
What exactly we would cache?

**Comment by jeddy3** [comment]
I (perhaps incorrectly) assumed it was `node_modules`.

**Comment by hudochenkov** [comment]
Cache for `node_modules` is useless with `npm ci`:

> If a `node_modules` is already present, it will be automatically removed before `npm ci` begins its install.

https://docs.npmjs.com/cli/ci.html

**Comment by jeddy3** [comment]
>>  What exactly we would cache?

> Cache for node_modules is useless with npm ci:

Oh, then probably nothing :)

**Comment by XhmikosR** [comment]
The global npm folder

**Comment by XhmikosR** [comment]
Alright, I tested with cache enabled, but I'm not sure how PRs vs branches are handled. That being said I see this:

1. on Windows cache isn't saved in the PR
2. on macOS the cache is 1115 MB!
3. with the above 2 things, it seems caching doesn't help

I say we close this and revisit later if needed
