### ISSUE TITLE
Add flexible groupings to `rule-properties-order`

### ISSUE THREAD

**Issue by MadLittleMods** [stylelint/stylelint#447]
Add flexible groupings to [`rule-properties-order`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-properties-order/README.md).

We already support flexible grouping for long-hand `border-*`, `margin-*`, `padding-*`, etc if you define the shorthand in the order, see https://github.com/stylelint/stylelint/issues/373#issuecomment-141811077

For these new flexible groups, there would be two types which can be nested. We probably need a better syntax because this is very verbose.

 - `group`: *could be `unordered`*
 - `order`: ordered

```json
"rule-properties-order": [2, [
	"position",
	{
		"type": "group",
		"properties": [
			"top",
			"left",
			"right",
			"bottom"
		]
	},

	{
		"type": "group",
		"properties": [
			{
				"type": "order",
				"properties": [
					"foo",
					"bar",
					"baz",
				]
			},
			{
				"type": "order",
				"properties": [
					"qux",
					"quux",
					"norf",
				]
			}
		]
	}
]]
```

---

While agreeing on a strict order would be ideal, in a team environment this is not as easy. This kind of flexibility for any grouping of properties would ease the inconsistencies in opinions.

Here are some actual use case flexible property groups that we want to use: https://gist.github.com/anonymous/75e94d6f6e3f41392b89

---

I can see this being pushed to a plugin in which case we can use a simpler syntax; arrays for unordered and object for ordered with nesting on object via the `properties` key.

---

A bit related to https://github.com/stylelint/stylelint/issues/393

**Comment by mjschlot** [comment]
:+1:

**Comment by dmschlot** [comment]
:+:

**Comment by dmschlot** [comment]
:+1:

**Comment by davidtheclark** [comment]
@MadLittleMods : Are there supposed to be newlines between those groups or not? Just wondering how much this relates to https://github.com/stylelint/stylelint/issues/393.

**Comment by MadLittleMods** [comment]
@davidtheclark nope.

While it would be cool to enforce at a certain point, number of decls in group to force a newline, this issue is not concerned with it.

**Comment by MadLittleMods** [comment]
> To expand on the flexible groupings and nested idea, [here is a full use-case](https://gist.github.com/MadLittleMods/929bcdefb2b29c9b97c3#file-stylelint-rule-properties-order-example-json) and [overview proposal of the syntax](https://gist.github.com/MadLittleMods/929bcdefb2b29c9b97c3#file-stylelint-rule-properties-order-use-case-syntax-overview-md)
> https://github.com/stylelint/stylelint/pull/470#issuecomment-153144327

**Comment by davidtheclark** [comment]
Done in #470.
