### ISSUE TITLE
Missing VSCode Extension

### ISSUE THREAD

**Issue by yangmingshan** [stylelint/stylelint#4477]
The original VSCode extension is buggy, and [seem to be missing](https://marketplace.visualstudio.com/search?term=stylelint&target=VSCode&category=All%20categories&sortBy=Relevance). Any plans?

**Comment by hudochenkov** [comment]
We're working on bringing the old extension back. At the moment you can use https://marketplace.visualstudio.com/items?itemName=thibaudcolas.stylelint, which is exact version of previously available extension made by @shinnn.

**Comment by yangmingshan** [comment]
@hudochenkov As it stands I don't think this issue should be close, others may have the same question. We should have an issue to track this problem.

Ref: https://github.com/stylelint/stylelint/pull/4438

**Comment by ntwb** [comment]
We've moved the extension from @thibaudcolas repo to the stylelint org

https://github.com/stylelint/vscode-stylelint

I'll get this published to the VS Code marketplace later today

Thanks again for kicking this off @thibaudcolas 💯

**Comment by thibaudcolas** [comment]
🎉 pretty cool to see this under https://github.com/stylelint

**Comment by ntwb** [comment]
VS Code - stylelint v0.60.0 published

https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint
