### ISSUE TITLE
 TypeError: Cannot read property 'stringify' of null

### ISSUE THREAD

**Issue by russel-yang** [stylelint/stylelint#4481]
` TypeError: Cannot read property 'stringify' of null
    at Root.toString (/Users/urs/mywork//node_modules/postcss/lib/node.js:193:21)
    at /Users/user/mywork/node_modules/stylelint/lib/standalone.js:257:44
    at async Promise.all (index 0)`

when you run stylelint --fix "filename"
rollback to 11.1.1 the problem go away.

**Comment by hudochenkov** [comment]
Please, use issue template, otherwise we can't help you.

**Comment by adascal** [comment]
Same problem. Running `stylelint --fix` fail with error:

```
stylelint 'src/**/*.ts?(x)' --fix
[1] Autofix is incompatible with processors and will be disabled. Are you sure you need a processor?
[1] TypeError: Cannot read property 'stringify' of null
[1]     at Root.toString (/home/project/node_modules/postcss/lib/node.js:193:21)
[1]     at stylelint._lintSource.then (/home/project/node_modules/stylelint/lib/standalone.js:256:44)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

used packages:
```
"stylelint": "12.0.0",
"stylelint-config-recommended": "3.0.0",
"stylelint-config-styled-components": "0.1.1",
"stylelint-processor-styled-components": "1.9.0",
```

**Comment by evilebottnawi** [comment]
Do not use `stylelint-processor-styled-components`, it is deprecated

**Comment by evilebottnawi** [comment]
@hudochenkov any ideas about it, maybe we should add FAQ?

**Comment by adascal** [comment]
@evilebottnawi any replacement? I don't see deprecation warning on their page https://github.com/styled-components/stylelint-processor-styled-components

**Comment by evilebottnawi** [comment]
@adascal stylelint support css-in-js out of box, you don't need processor

**Comment by evilebottnawi** [comment]
https://github.com/styled-components/stylelint-processor-styled-components/issues/278

**Comment by adascal** [comment]
Feels like it's working with issues

```
[1]  26:3  ✖  Cannot parse selector   parseError
[1]  26:3  ✖  Cannot parse selector   parseError
[1]  26:3  ✖  Cannot parse selector   parseError
[1]  26:3  ✖  Cannot parse selector   parseError
[1]  26:3  ✖  Cannot parse selector   parseError
[1]  26:3  ✖  Cannot parse selector   parseError
```

For construction like:

```
# Line 24
const globalStyles = css`
  ${config.IS_DEVELOPMENT &&
    css`
      html {
        font-size: 12px;
      }

      body {
        @import url('https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700&subset=latin,cyrillic&display=swap');
        font-family: 'Ubuntu', sans-serif;
        margin: 0;
      }
    `}

  #__next {
    background: var(--white);
  }
`;
# Line 43
```

**Comment by evilebottnawi** [comment]
Need fix problem in https://github.com/gucong3000/postcss-jsx Can you open issues?

**Comment by hudochenkov** [comment]
@evilebottnawi it's open https://github.com/gucong3000/postcss-jsx/issues/53

**Comment by evilebottnawi** [comment]
@hudochenkov Sometimes it seems to me that postcss-syntax and postcss-jsx are abandoned and in near future we will clone them in stylelint org and fix errors yourself

**Comment by jeddy3** [comment]
> Sometimes it seems to me that postcss-syntax and postcss-jsx are abandoned

Yes, that does sadly seem to be the case.

> and in near future we will clone them in stylelint org 

The postcss org seems like a better home for these parsers as they are compatible with all postcss plugin.

**Comment by stephenkoo** [comment]
Could I re-open this issue since it isn't solved?

Removing `stylelint-processor-styled-components` produces the following type of error for all plugins: `Could not find "stylelint-config-standard". Do you need a configBasedir?`

Using `stylelint-processor-styled-components` produces the above TypeError.

@evilebottnawi do you have a recommendation on what to do to use stylelint with styled components properly?

**Comment by mkotsollaris** [comment]
Do we have any updates on this? Older versions of `stylelint` contain vulnerabilities, so rollback is not an option here :/

**Comment by morewings** [comment]
In case it helps anyone. I resolved the same problem by installing `"postcss": "^8.4.17",` as a direct dependency.
