### ISSUE TITLE
Rules removed in v8.0.0 are still gives error when  we updated on v12.0.0

### ISSUE THREAD

**Issue by Bhushankumar-pawar** [stylelint/stylelint#4486]
Removed Rules in v8.0.0 showing up in v12.0.0

Below rules removed in v8.0.0 and still gives me error when I am on v12.0.0
**src/form/date/css/date-time-range-picker.qcss**
 ```
1:1  ×  Unknown rule media-feature-no-missing-punctuation                             media-feature-no-missing-punctuation
 1:1  ×  Unknown rule media-query-parentheses-space-inside. Did you mean               media-query-parentheses-space-inside
         media-feature-parentheses-space-inside?
 1:1  ×  Unknown rule no-missing-eof-newline                                           no-missing-eof-newline
 1:1  ×  Unknown rule rule-non-nested-empty-line-before                                rule-non-nested-empty-line-before
 1:1  ×  Unknown rule declaration-block-no-ignored-properties                          declaration-block-no-ignored-properties
```

**date-time-range-picker.qcss**All errors for 1st line 
```
@value toolbarColorDisabled, containerBackgroundColor, dateTimeRangeBorderColor from "../../../css/default-theme.qcss";

.container {
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.2), 0 1px 1px 0 rgba(0, 0, 0, 0.14), 0 2px 1px -1px rgba(0, 0, 0, 0.12);
  background-color: containerBackgroundColor;
  box-sizing: border-box;
  white-space: nowrap;
  display: inline-flex;
  flex-direction: row;
}
```

**default-theme.qcss**

```
@import "./qualys.qcss";
@value toolbarColorDisabled: grey-lighten-50;
@value containerBackgroundColor: q-empty-background;
@value dateTimeRangeBorderColor: q-gray-c3;
```

> What stylelint configuration is needed to reproduce the bug?
**.stylelintrc**
`
{
  "extends": "stylelint-config-standard",
  "rules": {
    "at-rule-no-unknown": [ true, {
       "ignoreAtRules": [ "value", "apply" ]
     }],
    "at-rule-empty-line-before": [ "always" , {
      except: ["after-same-name", "inside-block", "blockless-after-same-name-blockless", "blockless-after-blockless", "first-nested"]
    }],
    "no-missing-end-of-source-newline":false
  }
}`

> version of stylelint ?
 `12.0.0`

> running stylelint: Using CLI,
"CLI with `stylelint \"src/**/*.qcss\" --config ./.stylelintrc`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

e.g. "No, it's related to removed rules which getting fired in the latest version."

> What did you expect to happen?
e.g. "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?
 "The following warnings were flagged:"
 ```
1:1  ×  Unknown rule media-feature-no-missing-punctuation                             media-feature-no-missing-punctuation
 1:1  ×  Unknown rule media-query-parentheses-space-inside. Did you mean               media-query-parentheses-space-inside
         media-feature-parentheses-space-inside?
 1:1  ×  Unknown rule no-missing-eof-newline                                           no-missing-eof-newline
 1:1  ×  Unknown rule rule-non-nested-empty-line-before                                rule-non-nested-empty-line-before
 1:1  ×  Unknown rule declaration-block-no-ignored-properties                          declaration-block-no-ignored-properties
```

**Comment by hudochenkov** [comment]
You need to update all your configs, so they don't have these rules.
