### ISSUE TITLE
'string-no-newline' freezes for template inside css

### ISSUE THREAD

**Issue by vilchik-elena** [stylelint/stylelint#4489]
When the following file is analyzed by `stylelint` with the rule `string-no-newline`, `stylelint` freezes:
https://github.com/rubocop-hq/rubocop/blob/master/assets/output.html.erb

Smaller reproducer, given:
the file `config.json`
```json
{"rules": {"string-no-newline": true}}
```
the file `file.css`
```css
<% COLORS.each do |color| %>
a { }
<% end %>
a { }
```
the following command freezes:
```sh
stylelint --config config.json file.css
```

Stylelint version 10.1.0

**Comment by evilebottnawi** [comment]
It is expected, we doesn't support non standard CSS, you need custom parser

**Comment by vilchik-elena** [comment]
How about failing with parsing error?
I'm not sure that's the reason but https://stylelint.io/demo is down since I tried this code there.

**Comment by evilebottnawi** [comment]
I think parser is not failed here, a problem what we use regexp in the `string-no-newline` rule and some nonstandard constitutions potentially cause this behavior, I think we should still figure it out

**Comment by vankop** [comment]
> I'm not sure that's the reason but https://stylelint.io/demo is down since I tried this code there.

Damn.. we need to fix this since this is kind of vulnerability..

**Comment by hudochenkov** [comment]
Initial investigation shows that it's `postcss-selector-parser`, who gets consuming more and more resources. We pass following "selector" to it `<% COLORS.each do |color| %>\na` based on provided example.

https://github.com/stylelint/stylelint/blob/77b02fa29118ab17249ce7f520ebe23fb90d8a6e/lib/rules/string-no-newline/index.js#L46

[`isStandardSyntaxSelector`](https://github.com/stylelint/stylelint/blob/77b02fa29118ab17249ce7f520ebe23fb90d8a6e/lib/utils/isStandardSyntaxSelector.js) doesn't help.

**Comment by vankop** [comment]
@hudochenkov please redeploy demo, it is stucked

**Comment by vankop** [comment]
In application I can suggest to spawn lint in separate process and have something like job queue:
```js
const linkQueue = ...;

class LintJob extends EventEmitter {
  constructor(opts: Linting options) { this.opts = opts;}
   start() {
       ...spawn node js process here using provided options..
      this.pid = ...;
      this.timeout = setTimeout(() => this.emit('timeout', this.pid), LINTING_TIMEOUT);
   }

   done() {
        clearTimeout(this.timeout);
       this.emit('done');
   }

   onTimeout() {
       process.kill(this.pid, 'SIGHTERM');
       this.emit('timeout');
   }
}

...

onRequest(req, res) {
  const opts = req.opts;
  new Promise((resolve, reject) => {
         const job = new LintJob(opts);
         
        job.on('done', resolve);
        job.on('timeout', reject);
        lintQueue.add(job);
   })
    .then((...) => res.send(...))
    .catch(() => res.send(500));
}
```

I can take a look on this issue later

**Comment by hudochenkov** [comment]
I redeployed Demo. Please, don't test this case there :)

**Comment by hudochenkov** [comment]
Released in `12.0.1`. Thanks for the report, @vilchik-elena!

**Comment by vilchik-elena** [comment]
@hudochenkov Could you share when next version will be released? it will be great for us to use the version [with fixed `no-descending-specificity`](https://github.com/stylelint/stylelint/pull/4491#issuecomment-569124366).

**Comment by hudochenkov** [comment]
Will try to do this weekend.
