### ISSUE TITLE
Fix all types problems

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#4496]
During migration from Flow to TypeScript (https://github.com/stylelint/stylelint/issues/4245) we marked many places with `@ts-ignore` comments. We need to remove all these comments and fix types problems, which were suppressed by these comments.

**Comment by ybiquitous** [comment]
Now I'm addressing a new type package `@types/postcss-less`. If you are interested, please take a look: 😉 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46235

If `@types/postcss-less` is published, we can fix the following declaration and some `@ts-ignore` comments:

https://github.com/stylelint/stylelint/blob/cecacb9d4fe3b5bae5f264efa6e60c414a0f4946/types/global.d.ts#L5

https://github.com/stylelint/stylelint/blob/cecacb9d4fe3b5bae5f264efa6e60c414a0f4946/lib/utils/isLessVariable.js#L10-L11

**Comment by ybiquitous** [comment]
Here is a list of rules using the `// @ts-nocheck` comment.

- [ ] `lib/rules/index.js`
- [ ] `lib/rules/no-descending-specificity/index.js`
- [ ] `lib/rules/no-duplicate-at-import-rules/index.js`
- [ ] `lib/rules/no-duplicate-selectors/index.js`
- [ ] `lib/rules/no-empty-first-line/index.js`
- [ ] `lib/rules/no-empty-source/index.js`
- [ ] `lib/rules/no-eol-whitespace/index.js`
- [ ] `lib/rules/no-extra-semicolons/index.js`
- [ ] `lib/rules/no-invalid-double-slash-comments/index.js`
- [ ] `lib/rules/no-invalid-position-at-import-rule/index.js`
- [ ] `lib/rules/no-irregular-whitespace/index.js`
- [ ] `lib/rules/no-missing-end-of-source-newline/index.js`
- [ ] `lib/rules/no-unknown-animations/index.js`
- [ ] `lib/rules/number-leading-zero/index.js`
- [ ] `lib/rules/number-max-precision/index.js`
- [ ] `lib/rules/number-no-trailing-zeros/index.js`
- [ ] `lib/rules/property-allowed-list/index.js`
- [ ] `lib/rules/property-case/index.js`
- [ ] `lib/rules/property-disallowed-list/index.js`
- [ ] `lib/rules/property-no-unknown/index.js`
- [ ] `lib/rules/property-no-vendor-prefix/index.js`
- [ ] `lib/rules/rule-empty-line-before/index.js`
- [ ] `lib/rules/selector-attribute-brackets-space-inside/index.js`
- [ ] `lib/rules/selector-attribute-name-disallowed-list/index.js`
- [ ] `lib/rules/selector-attribute-operator-allowed-list/index.js`
- [ ] `lib/rules/selector-attribute-operator-disallowed-list/index.js`
- [ ] `lib/rules/selector-attribute-operator-space-after/index.js`
- [ ] `lib/rules/selector-attribute-operator-space-before/index.js`
- [ ] `lib/rules/selector-attribute-quotes/index.js`
- [ ] `lib/rules/selector-class-pattern/index.js`
- [ ] `lib/rules/selector-combinator-allowed-list/index.js`
- [ ] `lib/rules/selector-combinator-disallowed-list/index.js`
- [ ] `lib/rules/selector-combinator-space-after/index.js`
- [ ] `lib/rules/selector-combinator-space-before/index.js`
- [ ] `lib/rules/selector-descendant-combinator-no-non-space/index.js`
- [ ] `lib/rules/selector-disallowed-list/index.js`
- [ ] `lib/rules/selector-id-pattern/index.js`
- [ ] `lib/rules/selector-list-comma-newline-after/index.js`
- [ ] `lib/rules/selector-list-comma-newline-before/index.js`
- [ ] `lib/rules/selector-list-comma-space-after/index.js`
- [ ] `lib/rules/selector-list-comma-space-before/index.js`
- [ ] `lib/rules/selector-max-attribute/index.js`
- [ ] `lib/rules/selector-max-class/index.js`
- [ ] `lib/rules/selector-max-combinators/index.js`
- [ ] `lib/rules/selector-max-compound-selectors/index.js`
- [ ] `lib/rules/selector-max-empty-lines/index.js`
- [ ] `lib/rules/selector-max-id/index.js`
- [ ] `lib/rules/selector-max-pseudo-class/index.js`
- [ ] `lib/rules/selector-max-specificity/index.js`
- [ ] `lib/rules/selector-max-type/index.js`
- [ ] `lib/rules/selector-max-universal/index.js`
- [ ] `lib/rules/selector-nested-pattern/index.js`
- [ ] `lib/rules/selector-no-qualifying-type/index.js`
- [ ] `lib/rules/selector-no-vendor-prefix/index.js`
- [ ] `lib/rules/selector-pseudo-class-allowed-list/index.js`
- [ ] `lib/rules/selector-pseudo-class-case/index.js`
- [ ] `lib/rules/selector-pseudo-class-disallowed-list/index.js`
- [ ] `lib/rules/selector-pseudo-class-no-unknown/index.js`
- [ ] `lib/rules/selector-pseudo-class-parentheses-space-inside/index.js`
- [ ] `lib/rules/selector-pseudo-element-allowed-list/index.js`
- [ ] `lib/rules/selector-pseudo-element-case/index.js`
- [ ] `lib/rules/selector-pseudo-element-colon-notation/index.js`
- [ ] `lib/rules/selector-pseudo-element-disallowed-list/index.js`
- [ ] `lib/rules/selector-pseudo-element-no-unknown/index.js`
- [ ] `lib/rules/selector-type-case/index.js`
- [ ] `lib/rules/selector-type-no-unknown/index.js`
- [ ] `lib/rules/selectorAttributeOperatorSpaceChecker.js`
- [ ] `lib/rules/selectorCombinatorSpaceChecker.js`
- [ ] `lib/rules/selectorListCommaWhitespaceChecker.js`
- [ ] `lib/rules/shorthand-property-no-redundant-values/index.js`
- [ ] `lib/rules/string-no-newline/index.js`
- [ ] `lib/rules/string-quotes/index.js`
- [ ] `lib/rules/time-min-milliseconds/index.js`
- [ ] `lib/rules/unicode-bom/index.js`
- [ ] `lib/rules/unit-allowed-list/index.js`
- [ ] `lib/rules/unit-case/index.js`
- [ ] `lib/rules/unit-disallowed-list/index.js`
- [ ] `lib/rules/unit-no-unknown/index.js`
- [ ] `lib/rules/value-keyword-case/index.js`
- [ ] `lib/rules/value-list-comma-newline-after/index.js`
- [ ] `lib/rules/value-list-comma-newline-before/index.js`
- [ ] `lib/rules/value-list-comma-space-after/index.js`
- [ ] `lib/rules/value-list-comma-space-before/index.js`
- [ ] `lib/rules/value-list-max-empty-lines/index.js`
- [ ] `lib/rules/value-no-vendor-prefix/index.js`
- [ ] `lib/rules/valueListCommaWhitespaceChecker.js`

---

This is created by the following command:

```shell
git grep -l '@ts-nocheck' | sed -r 's/^(.+)/- [ ] `\1`/'
```

**Comment by jeddy3** [comment]
You've made an amazing amount of progress improving the type coverage over the last couple of months!

**Comment by ybiquitous** [comment]
#5878 is the last one PR!

**Comment by jeddy3** [comment]
@ybiquitous Many thanks again for completing this huge endeavour!

**Comment by ybiquitous** [comment]
@jeddy3 Without your support, I wouldn't have been able to stay motivated. 😄
