### ISSUE TITLE
doesn't work with pathname contains square brackets

### ISSUE THREAD

**Issue by BananaWanted** [stylelint/stylelint#4515]
> Clearly describe the bug

`stylelint` currently doesn't work with pathname contains square brackets '[]'

these commends won't work:
```
> touch '[abcd].js'

> stylelint '[abcd].js'
Error: No files matching the pattern "[abcd].js" were found.
    at /Users/tzhang/workspace/appannie/aa-react/node_modules/stylelint/lib/standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

> stylelint '\[abcd\].js'
Error: No files matching the pattern "\[abcd\].js" were found.
    at /Users/tzhang/workspace/appannie/aa-react/node_modules/stylelint/lib/standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The reason we're using `[]` in paths is `next.js` decides to use those characters for dynamic routing. Various tools are broken because of this. While most of them can be fixed by quote or escape the path, `stylelint` just doesn't work no matter how the input paths are escaped, so need to be fixed in the package directly.

Related discisson: https://github.com/okonet/lint-staged/issues/676

> Which rule, if any, is the bug related to?
N/A

> What CSS is needed to reproduce the bug?
N/A

> What stylelint configuration is needed to reproduce the bug?
N/A

> Which version of stylelint are you using?

12.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI command ran by `lint-staged`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?
N/A

> What did you expect to happen?

can check files with `[]` chars in their path.

> What actually happened (e.g. what warnings or errors did you get)?
Error thrown as listed above

**Comment by hudochenkov** [comment]
It's a known issue https://github.com/stylelint/stylelint/issues/4388#issuecomment-569013742. No one is working on a solution yet.

**Comment by jeddy3** [comment]
Thanks for the report. Closing as duplicate.
