### ISSUE TITLE
Please upgrade postcss-markdown dependency version

### ISSUE THREAD

**Issue by alejandroclaro** [stylelint/stylelint#4518]
postcss-markdown version 0.36 produces some warning in audit tools due to deprecation of @types/vfile and @types/vfile-message packages required by old versions of the 'unified' package.

**Comment by ntwb** [comment]
v0.36.0 is the latest release https://github.com/gucong3000/postcss-markdown/releases

They are also only _warnings_ that can be ignored.

If you like you can head over that repo and create an issue and or pull request to update the dependencies
