### ISSUE TITLE
How to define .stylelintrc with Grunt plugin ?

### ISSUE THREAD

**Issue by ethyde** [stylelint/stylelint#452]
Hi,

I use Grunt to process my files, i put my ```.stylelintrc``` in a ```etc``` folder to have something like ```etc/.stylelintrc```.

In my package.json : 
```
"postcss": "^5.0.10",
"grunt-postcss": "^0.7.0",
"stylelint": "^2.0.0"
```
My Grunt task : 
```
postcss: {
    lint: {
        options: {
            map: false,
            processors: [
                require( 'stylelint' )()
            ]
        },
        src: [ "dev/css/**/*.css" ]
    }
}
```
I Have try (with differente relative path): 
```
require( 'stylelint' )({
    config: "etc/.stylelintrc"
})
```
Or
```
require( 'stylelint' )({
    config: ".stylelintrc",
    configBasedir: "etc/"
})
```
And finaly, for test, i put ```.stylelintrc``` file on root, and it's work ! But it's impossible to me to let it here.

Can you help me ?

ps : sorry for my bad english.

**Comment by davidtheclark** [comment]
Try this:

```js
var stylelintConfig = require('/etc/.stylelintrc'); 
/* ... */
processors: [
  require('stylelint')(stylelintConfig)
]
```

How does that go for you?

**Comment by ethyde** [comment]
I have try this workaround with different path, and i have two type of answer :
```>> Error: Cannot find module '/etc/.stylelintrc'``` or ```>> SyntaxError: Unexpected token :```

**Comment by davidtheclark** [comment]
Change `var stylelintConfig = require('/etc/.stylelintrc'); ` so that it points to your `.stylelintrc` file. I don't know the directory structure of your project so can't be more precise. (If you need help tell me about your files.)

**Comment by ethyde** [comment]
Hum ok i explain more :)

My current folder structure are something like that : 
```
ROOT
    |_ app
    |_ dist
    |_ etc
        |_.stylelintrc
    gruntfile.js
```
So, with ```var stylelintConfig = require('./etc/.stylelintrc');``` grunt prompt ```>> SyntaxError: Unexpected token :```, with any other path, grunt prompt ```>> Error: Cannot find module ...```
My .stylelintrc file : 
```
{
  "rules": {
    "color-no-invalid-hex": 2,
    "declaration-colon-space-after": [1, "always"],
    "indentation": [2, "tab", {
      "except": ["value"]
    }]
  }
}
```

**Comment by davidtheclark** [comment]
Change the filename to something like `/etc/stylelintConfig.json`. There is a problem trying to `require()` a file without a `.js` or `.json` extension (even if it is valid JSON). With that change I was able to get your setup working.
