### ISSUE TITLE
 "Browserslist: caniuse-lite" is outdated warning

### ISSUE THREAD

**Issue by smlombardi** [stylelint/stylelint#4520]
> Clearly describe the bug

When running my Angular app with `npm start`, the project builds and runs ut there is a warning in the Terminal that was not there  before:

```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```

After Googling this error and finding [this thread](https://github.com/postcss/autoprefixer/issues/1184), I performed the suggested command `npm ls browserslist` and it yields:

```
ng-starter-app@2.0.0 /Users/st016lo/github/ng-starter-app
└─┬ stylelint@12.0.1
  └─┬ autoprefixer@9.7.3
    └── browserslist@4.8.3 
```

So, it would seem the version of caniuselite inside this package is out of date?

> Which version of stylelint are you using?

`12.0.1`

**Comment by ntwb** [comment]
Autoprefixer latest update is v9.7.3, of which browserslist and caniuse-lite are subpackages of.

Stylelint cannot help in this regard if caniuse-lite is out of date, did you try running the command it suggested `npm update`?

You could try removing the `node_modules` folder and running `npm install` again

Aside from the above options there is nothing else stylelint can do until a new Autoprefixer release is released if the above options do not work for you

**Comment by hudochenkov** [comment]
I did new install of stylelint and no such warning is present. So it's specific install `node_modules`/`package-lock.json` problem.

**Comment by smlombardi** [comment]
I deleted package-lock.json and node_modules, did npm install.  Problem persists.

**Comment by hudochenkov** [comment]
What `npm ls caniuse-lite` says? It might be other dependency requires lower version and it within range that our dependencies require. In any case, it's not stylelint specific problem.

We're going to release new version soon, all direct dependencies would be up to date, so it might solve your problem as well.

**Comment by smlombardi** [comment]
```
st016lo:~/github/ng-starter-app (develop) $ npm ls caniuse-lite
ng-starter-app@2.0.0 /Users/st016lo/github/ng-starter-app
└── (empty)
```

**Comment by hudochenkov** [comment]
¯\_(ツ)_/¯ you have the latest browserslist, and somehow no `caniuse-lite`.

**Comment by smlombardi** [comment]
Sorry, I forgot I had reverted the project to before doing updates.  The correct output is:
```
ng-starter-app@2.0.0 /Users/st016lo/github/ng-starter-app
└─┬ stylelint@12.0.1
  └─┬ autoprefixer@9.7.3
    ├─┬ browserslist@4.8.3
    │ └── caniuse-lite@1.0.30001020  deduped
    └── caniuse-lite@1.0.30001020 
```

**Comment by hudochenkov** [comment]
I don't know, you have the latest versions or everything 🤷‍♂️
