### ISSUE TITLE
Improve documentation structure

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4543]
I'm looking at the documentation with fresh eyes after a hiatus and I think we could improve the overall structure. It hasn't changed much since the beginning, but things have changed around it:

- awesome lists appeared (like [awesome-stylelint](https://github.com/ntwb/awesome-stylelint))
- evidence that FAQs [are problematic](https://alistapart.com/article/no-more-faqs-create-purposeful-information-for-a-more-effective-user-experi/) appeared
- pretty printers (like [prettier](https://prettier.io/)) and validators (like [csstree-validator](https://github.com/csstree/validator)) appeared
- we use Docusaurus for the website now, which has a sidebar
- we have more contributors than ever managing issues, pull requests and releases
- we have backers and sponsors now

I've been looking at other documentation sites, e.g. Prettier's, Jest's, ESLint's, Docusaurus' etc., to try to identify better structures.

I propose the following structure:

- Home ([1](https://github.com/stylelint/stylelint/blob/master/README.md#features), [2](https://github.com/stylelint/stylelint/blob/master/README.md/#contributors))
   - User guide
      - Get started ([1](https://github.com/stylelint/stylelint/blob/master/README.md#getting-started))
      - Configuration
         - Configuration object ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#the-configuration-object))
         - Rules ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md))
            - `at-rule-blacklist` ([1](https://github.com/stylelint/stylelint/blob/master/lib/rules/at-rule-blacklist/README.md))
             - ...
         - Conventions ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/about-rules.md))
         - Example config ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/example-config.md))
      - Usage
         - CLI ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md))
         - Node.js API ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/node-api.md))
         - PostCSS plugin [discouraged] ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md))
      - Ignore code ([1](https://stylelint.io/user-guide/configuration#turning-rules-off-from-within-your-css), [2](https://stylelint.io/user-guide/configuration#stylelintignore))
   - Developer guide
      -  Rules ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md))
      -  Plugins ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/plugins.md))
      -  Formatters ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/formatters.md))
      -  Processors [discouraged] ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/processors.md))
   - Maintainer guide
      - Issues ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/issues.md))
      - Pull requests ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/pull-requests.md))
      - Releases ([1](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/releases.md))
   - About
      - Linting  ([1](https://github.com/stylelint/stylelint/blob/master/VISION.md#possible-errors), [2](https://github.com/stylelint/stylelint/blob/master/VISION.md#stylistic-issues)) 
      - Vision ([1](https://github.com/stylelint/stylelint/blob/master/VISION.md), [2](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/css-processors.md#css-processors)) 
      - Semantic versioning ([1](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/semantic-versioning-policy.md))

I've linked (in brackets) to the various bits of existing content to give you a feel about what will be housed in each section.

Notable differences to the existing structure:

1. FAQ is gone - we'd integrate each FAQ item into the most appropriate content section to maintain context.
2. Complementary tools, articles, plugins and processors are gone - we'd highlight the best of each within appropriate content sections and then link off to [awesome-stylelint](https://github.com/ntwb/awesome-stylelint).
3. New About linting section - we'd address the relationship between linters, validators and pretty printers there.
4. New Maintainer guide for managing issues, pull requests and releases 
5. New Ignoring code section within the User guide.

Additionally:

1. We should improve the [contributing document](https://github.com/stylelint/stylelint/blob/master/CONTRIBUTING.md) so that it caters to users writing their first stylelint issue or submitting their first stylelint pull request as GitHub directs users to this document.
2. We should direct new members to the Maintainer guide (as part of the invitation process).
3. We should embrace the sidebar and reduce the header navigation to "Docs" and "Demo" on the left-hand side and "Twitter" and "GitHub" on the right.

I'm happy to put the majority of the legwork into this.

Thoughts?

**Comment by hudochenkov** [comment]
I love it!

Our documentation has almost every question asked covered, but to find needed info is usually problematic. Even I struggle sometimes to find something.

There is another thing, that there is too much text and very little navigation. E. g. https://stylelint.io/user-guide/configuration it has so much information, but many headers not even in the right sidebar. Also, we should leverage lists (ordered and unordered) to allow faster skimming through docs to find needed info.

Not sure if we need to remove editor and build tools plugins. They usually part of stylelint experience. I would keep “Complimentary tools” page, maybe we should rename it to “Integrations”, like [ESLint has](https://eslint.org/docs/user-guide/integrations).

**Comment by jeddy3** [comment]
> Our documentation has almost every question asked covered, but to find needed info is usually problematic. Even I struggle sometimes to find something.

Ditto! Our documentation is pretty comprehensive, but I get lost in it too.

> There is another thing, that there is too much text and very little navigation.

I agree. For example, that configuration page became a jumble by explaining the configuration object _and_ things like how to ignore code. Hopefully pulling these out into new sections will, with the help of better navigation, improve matters.

> Also, we should leverage lists (ordered and unordered) to allow faster skimming through docs to find needed info.

I agree. Lists help a lot.

> Not sure if we need to remove editor and build tools plugins. [..] maybe we should rename it to “Integrations”,

I agree.

**Comment by ybiquitous** [comment]
@jeddy3 I think the following transformation script should be changed to fit this issue until the next release.

https://github.com/stylelint/stylelint.io/blob/43507db8b0c954c48caf728f9cd7def5614214c7/scripts/generate-stylelint-docs.js

**Comment by jeddy3** [comment]
I agree. I've created an issue: https://github.com/stylelint/stylelint.io/issues/128.

**Comment by ybiquitous** [comment]
Thanks! 😊 👍
