### ISSUE TITLE
Fix RangeError in indentation

### ISSUE THREAD

**Issue by whatisaphone** [stylelint/stylelint#4551]
> Clearly describe the bug

Certain input (see below) causes a crash in the `indentation` rule. I can repro locally, and also on the online demo page.

> Which rule, if any, is the bug related to?

`indentation`

> What CSS is needed to reproduce the bug?

```css
:not(.enabled
) {
  color: gray;
}

```

> What stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  rules: {
    'indentation': 2,
  },
};

```

> Which version of stylelint are you using?

`13.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `yarn stylelint **/*.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

Rule does not crash.

> What actually happened (e.g. what warnings or errors did you get)?

Rule crashes with the following exception and stack trace:

```text
RangeError: Invalid count value
    at /workdir/client/redacted/file.scss:161:5
    at String.repeat (<anonymous>)
    at /workdir/client/node_modules/stylelint/lib/rules/indentation/index.js:316:45
    at handleMatch (/workdir/client/node_modules/style-search/index.js:201:5)
    at module.exports (/workdir/client/node_modules/style-search/index.js:189:5)
    at checkMultilineBit (/workdir/client/node_modules/stylelint/lib/rules/indentation/index.js:222:4)
    at checkSelector (/workdir/client/node_modules/stylelint/lib/rules/indentation/index.js:190:4)
    at /workdir/client/node_modules/stylelint/lib/rules/indentation/index.js:132:5
    at /workdir/client/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/workdir/client/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/workdir/client/node_modules/postcss/lib/container.js:131:17)
```

**Comment by jeddy3** [comment]
@whatisaphone Thanks for the report. I can reproduce this locally.

This is a regression as stylelint does not error with `12.0.1`. Only [refactoring and dependencies changes](https://github.com/stylelint/stylelint/commits/master/lib/rules/indentation/index.js) have happened to this rule since `12.0.1`, so I assume one of those two is causing this.

As the issue has been labelled "status: ready to implement", please consider [contributing a fix](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#fixing-a-bug-in-an-existing-rule).

**Comment by XhmikosR** [comment]
@whatisaphone @jeddy3 can you confirm if #4564 fixes the issue for you?

**Comment by jeddy3** [comment]
I tested it locally with your `master-xmr-indent` branch and the error still occurs.

**Comment by XhmikosR** [comment]
Hmm, then this is another regression :/

**Comment by jeddy3** [comment]
Yes. I suspect it was caused by https://github.com/stylelint/stylelint/pull/4413 and the [replacement of lodash's `repeat` with the native one](https://github.com/stylelint/stylelint/pull/4413/files#diff-04ee6cd1e55e4be0983ed5a4fcea5e50).

```
RangeError: Invalid count value
    at /workdir/client/redacted/file.scss:161:5
    at String.repeat (<anonymous>)
```

**Comment by XhmikosR** [comment]
Sounds quite possible judging from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

> RangeError: repeat count must be non-negative.
> RangeError: repeat count must be less than infinity and not overflow maximum string size.

**Comment by XhmikosR** [comment]
Here's a quick patch https://github.com/stylelint/stylelint/compare/master-xmr-indent-2?

I'm hesitant to keep the native repeat, unless we go though all the other instances and make sure we are not passing any negative values.

**Comment by XhmikosR** [comment]
Alright, I double checked all `repeat` cases and AFAICT there's only one that might be negative but I haven't evaluated it yet:

https://github.com/stylelint/stylelint/blob/9e605552778f149324e1795783e46ad7c0b32d4b/lib/utils/blurFunctionArguments.js#L42

In all other cases the count seems to be > 0 so we should be OK.

BTW I'm not 100% sure [my patch](https://github.com/stylelint/stylelint/compare/master-xmr-indent-2) covers all cases, so I could use another pair of eyes :)

**Comment by jeddy3** [comment]
> BTW I'm not 100% sure my patch covers all cases, 

That's OK as we can address any other problems when they're reported.

**Comment by jeddy3** [comment]
> https://github.com/stylelint/stylelint/compare/master-xmr-indent-2?

Do you want to make a PR for your branch?
