### ISSUE TITLE
Fix autofix transforming media queries when no errors

### ISSUE THREAD

**Issue by UltraTempest** [stylelint/stylelint#4560]
Simillar to https://github.com/stylelint/stylelint/issues/4115 so could be related:

// test.jsx
```
const style = {
  maxWidth: 10,
  '@media(max-width:930px)': {
    width: '64%',
  },
}
```

stylelint --syntax sass "test.jsx" -- no output.
stylelint --syntax sass "test.jsx" --fix edits the file anyway:

// *test.jsx
```
const style = {
   maxWidth: 10,
  '@media(maxWidth:930px)': {
    width: '64%',
  },
}
```

am I missing something?

> Which rule, if any, is the bug related to?

No rule

> What CSS is needed to reproduce the bug?
```
const style = {
   maxWidth: 10,
  '@media(max-width:930px)': {
    width: '64%',
  },
}
```
in a js or jsx file

> What stylelint configuration is needed to reproduce the bug?

```
module.exports = {
  extends: ['stylelint-config-recommended', 'stylelint-config-rational-order'],
  ignoreFiles: ['**/storybook-static/**'],
  rules: {
    'at-rule-no-unknown': null,
    'plugin/rational-order': [
      true,
      {
        'border-in-box-model': true,
        'empty-line-between-groups': false,
      },
    ],
  },
};

```

> Which version of stylelint are you using?

`13.0.0`

> How are you running stylelint: CLI?

 "CLI with `stylelint **/*.{html,jsx} "--fix"`"

> Does the bug relate to non-standard syntax?

Yes, it's related to JSX nested properties.

> What did you expect to happen?

max-width in media query string not to be transformed since it can't be camelCase in order to work for css-in-js with emotion.

> What actually happened (e.g. what warnings or errors did you get)?

No warnings flagged but the media query no longer works

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed

**Comment by UltraTempest** [comment]
Done

**Comment by jeddy3** [comment]
@UltraTempest Thanks for the report and for using the template.

To clarify, which command are you running?

- `stylelint --syntax sass "test.jsx" --fix`
- or `stylelint **/*.{html,jsx} --fix`

The first command forces the syntax to be SASS, which won't be able to parse a `.jsx` file.

If it's the second command, can you share a typical snippet of the styling code within one of your `.html` files, please? This will help us understand your use case. We can then advise you on what action to take.

**Comment by UltraTempest** [comment]
Hi @jeddy3 ,

```
stylelint **/*.{html,jsx} --fix
```
is the command being run.


However the majority of files in my codebase are jsx. I can provide you with a typical snippet of styling in a jsx file.

```
import React from 'react';

const style = theme => ({
  maxWidth: 10,
  '@media(max-width:930px)': {
    width: '64%',
  },
});

const style2 = {
  maxWidth: 10,
  '@media(max-width:930px)': {
    width: '64%',
  },
};

const Component = () => (
    <div css={style}>
      some other text
     <span css={style2}>Hello</span>
    </div>);
```

I use React & the css prop with emotion & emotion-theming.

**Comment by UltraTempest** [comment]
The html files are working just fine with stylelint, the jsx files are the problem. Specifically the media queries

**Comment by jeddy3** [comment]
Thanks for the extra information. I'm struggling to reproduce this, though. It would help us if you created a reproducible test repository.

I suspect your issue may be related to https://github.com/stylelint/stylelint/issues/4449, which is fixed in the next release of stylelint.

**Comment by UltraTempest** [comment]
https://github.com/UltraTempest/stylelint-jsx-bug is the reproducible test repository :)

emotion requires the styles in the media query to be kebab case & not camelCase like Stylelint is transforming it to.

Hope this repo clarifies everything for you!

**Comment by jeddy3** [comment]
@UltraTempest Thank you for taking the time to create the reproducible test. I was able to reproduce the issue locally using it (and the `master` branch of stylelint).

It's likely a problem with the [CSS-in-JS parser](https://github.com/gucong3000/postcss-jsx) that stylelint uses. I'm going to label this issue up accordingly.

There are quite a few open issues in stylelint related to this parser. As such, we've decided to:

- fork it into the stylelint organisation
- create an umbrella issue for those associated with this parser
- try to drum up support from the community to help maintain it 

I'll drop an update here when we've done the first two. After that, if you have time and would like to help out, you're welcome to contribute a fix.

**Comment by jeddy3** [comment]
We've forked the parser we use for CSS-in-JS [into stylelint organisation](https://github.com/stylelint/postcss-css-in-js), and we're looking for help to fix our fork to close this issue.

See https://github.com/stylelint/stylelint/issues/4574.

**Comment by jeddy3** [comment]
In addition to the actions listed in https://github.com/stylelint/stylelint/issues/4560#issuecomment-578907499, we started to improve our documentation around syntaxes:

- [about/syntaxes](https://stylelint.io/about/syntaxes)
- [developer-guide/syntax](https://stylelint.io/developer-guide/syntaxes)

In [`13.2.0`](https://stylelint.io/changelog#1320), we also released a system to temporarily workaround these autofix issues. If you're unable to contribute to the syntax, please consider [contributing](https://stylelint.io/contributing) a [workaround to stylelint itself](https://stylelint.io/developer-guide/syntaxes#add-a-workaround) so that it won't attempt to autofix sources that contain `@media` within JavaScript object properties.
