### ISSUE TITLE
Use Jest's V8 code-coverage feature

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4562]
Jest@25 includes a new [experimental code-coverage feature using V8](https://jestjs.io/blog/2020/01/21/jest-25#v8-code-coverage). We should look into the performance gains for us.

We may need to wait until it's no longer experimental if [the stability can't be guaranteed](https://github.com/stylelint/stylelint/pull/4557#issuecomment-578489915).

Ref: https://github.com/stylelint/stylelint/pull/4557#issuecomment-578398303.

**Comment by Mouvedia** [comment]
unblocked since 8192fe43d54ee8a425e8d5c1a734b47ccbb7833f
see facebook/jest@469f3a5088bc2523dbaf7dfd5b70122246a8ee43
