### ISSUE TITLE
Release 13.1.0

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4569]
- [x] stylelint release
- [x] stylelint-config-recommended update/release
- [x] stylelint-config-standard update/release
- [x] stylelint-demo update
- [x] stylelint.io update
- [x] tweet

cc @stylelint/core

I think we need to release v13.0.1 ASAP after the following:

- [x] Merge the dependabot PRs
  - [x] #4579
  - [x] #4578
  - [x] #4577
  - [x] #4568
  - [x] #4567
  - [x] #4566
  - [x] #4565
  - [x] #4557
  - [x] #4554
- [x] Redo #4559 and merge it
- [ ] ~~#4564~~
- [x] #4572
- [x] #4576
- [x] Merge #4561

Feel free to add any other TODOs. Also I'm not sure who can make new releases

**Comment by jeddy3** [comment]
I can do a release today (or when we merge these). I believe stylelint/owners can release and that includes @ntwb, @hudochenkov and myself.

Yep, it'll be great to get https://github.com/stylelint/stylelint/pull/4561 in. It doesn't need a thorough review as it's a documentation change, i.e. not code that could break someone's build. We can think of as an incremental improvement.

**Comment by jeddy3** [comment]
I'm available this weekend to do a release if we're able to get the last remaining PRs reviewed and merged.

**Comment by XhmikosR** [comment]
I'm also available and I will do #4559 before the release

**Comment by jeddy3** [comment]
I believe https://github.com/stylelint/stylelint/pull/4561 is the only outstanding pull request from the original list. It requires one more approval.

It would be nice to see https://github.com/stylelint/stylelint/pull/4581 (waiting on review) and https://github.com/stylelint/stylelint/pull/4573 (waiting on revision). I think these can wait until the next patch release if they're not merged by the weekend.

**Comment by jeddy3** [comment]
The release will be `13.1.0` due to [our policy on minor releases](https://github.com/stylelint/stylelint/blob/master/docs/about/semantic-versioning.md#minor-release):

> a bug fix in a rule that results in stylelint reporting more errors

Introduced in https://github.com/stylelint/stylelint/pull/4581.

**Comment by jeddy3** [comment]
I need two approvals on https://github.com/stylelint/stylelint-config-standard/pull/136 to release `stylelint-config-standard@20.0.0`.

**Comment by jeddy3** [comment]
I've got as far as I can through the process. I:

- released 13.1.0. 
- updated [stylelint.io](https://stylelint.io) website (it features the overhauled documentation)
- updated [stylelint.io/demo](https://stylelint.io/demo)

I added some [last-minute redirects](https://github.com/stylelint/stylelint.io/commit/0cd87bcd5f0c556b74cd9419a8a6ace036e24acc) to the website so that existing links don't break.

Once https://github.com/stylelint/stylelint-config-standard/pull/136 is approved and merged, I will:

- release stylelint-config-standard@20.0.0
- tweet

**Comment by jeddy3** [comment]
All done 🎉 

Thanks to everyone who contributed to this release!
