### ISSUE TITLE
Improve errors and warnings docs

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4585]
We have a [new section in the docs for errors and warnings](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/errors.md) like:

- Css Syntax Error
- Parse Error
- Invalid options Error

We should expand this section to include hints on how to resolve the errors as we frequently post these as comments within issues. For example:

"A parse error is often caused by a malformed selector. You should check your selectors for unclosed quotes or brackets."

Follows: https://github.com/stylelint/stylelint/pull/4561 & https://github.com/stylelint/stylelint/issues/4227

**Comment by Catalyst497** [comment]
I am willing to solve this issue. Could you assign it to me and show me how or where to get the hints?

**Comment by Yaswanth820** [comment]
Hey @jeddy3. I would like to work on this issue. Can I get started?

**Comment by jeddy3** [comment]
@Yaswanth820 That'd be great, thank you.

**Comment by Supriya-48** [comment]
Hi @jeddy3 I would like to work on this issue, can you assign me on this,

**Comment by ybiquitous** [comment]
@Supriya-48 Yes, please feel free to open a pull request. Nobody works on this issue now.

**Comment by Supriya-48** [comment]
Thank you will do

**Comment by Supriya-48** [comment]
@ybiquitous I am participating for the first time in hacktoberfest 
![Screenshot (58)](https://user-images.githubusercontent.com/48731097/197333732-f392171f-8f0d-499a-84b5-cbd962cdd447.png)
, wanted to cross check whether I am going on a right path, is this the same what you are expecting?

**Comment by jeddy3** [comment]
@Supriya-48 Thank you for working on the issue. Yes, you're on the right path. I suggest opening a pull request so that we can feedback on what you have so far.
