### ISSUE TITLE
Fix open handle in tests

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4596]
I got this while running our tests:

```shell
Running coverage on untested files...A worker process has failed to exit gracefully and has been force exited. 
This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```

And the following:

```shell
npm run jest -- --runInBand --detectOpenHandles

```

Returns:

```shell
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TTYWRAP

      14 | 
      15 |      beforeAll(() => {
    > 16 |              processRestore = { ...process };
         |              ^
      17 |              logRestore = { ...console };
      18 |              process.exit = (exitCode) => (process.exitCode = exitCode);
      19 |      });

      at Object.<anonymous> (system-tests/cli/cli.test.js:16:3)
```

**Comment by exoer** [comment]
> I got this while running our tests:
> 
> ```shell
> Running coverage on untested files...A worker process has failed to exit gracefully and has been force exited. 
> This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
> ```
> 
> And the following:
> 
> ```shell
> npm run jest -- --runInBand --detectOpenHandles
> ```
> 
> Returns:
> 
> ```shell
> Jest has detected the following 1 open handle potentially keeping Jest from exiting:
> 
>   ●  TTYWRAP
> 
>       14 | 
>       15 |      beforeAll(() => {
>     > 16 |              processRestore = { ...process };
>          |              ^
>       17 |              logRestore = { ...console };
>       18 |              process.exit = (exitCode) => (process.exitCode = exitCode);
>       19 |      });
> 
>       at Object.<anonymous> (system-tests/cli/cli.test.js:16:3)
> ```

@jeddy3 You might want to try something like this 
```
afterAll(()=>{
   processRestore = null
    ...
})
```

**Comment by jeddy3** [comment]
@exoer Thanks for the suggestion. @hudochenkov refactored these tests in https://github.com/stylelint/stylelint/pull/4601 and I believe the issue was resolved.
