### ISSUE TITLE
Add equivalent of --color / --no-color CLI flags to standalone

### ISSUE THREAD

**Issue by jdforrester** [stylelint/stylelint#4603]
> What is the problem you're trying to solve?

I maintain [grunt-stylelint](https://github.com/wikimedia/grunt-stylelint). In porting our repo over from Travis to GitHub Actions, our quick integration test stopped working, presumably because  `supports-color` doesn't detect GitHub's virtual terminal as ANSI-capable. The unit test was expecting ANSI colours in the output, but stylelint standalone was providing none.

The proper solution to this is to run the test in `--no-color` mode, but passing that in doesn't work because (AFAICT from reading the stylelint codebase) the stripping code is only activatable via cli.js, not the standalone version.

I've hacked around it with [a quick `stripANSI` feature](https://github.com/wikimedia/grunt-stylelint/pull/86/commits/0ae3cbddaa8a595748df9dae04a7ba17aa825771) but this is ugly on several levels.

> What solution would you like to see?

Providing a `colorOutput` flag in the standalone tool with `true`/`false`/`'auto'` options or whatever. Or, even better, for you to point out that I'm totally wrong and that there is already a flag, and I should use that!

**Comment by jeddy3** [comment]
@jdforrester Thanks for the request and for using the template.

Would [using an environmental variable](https://www.npmjs.com/package/supports-color#info) work in your case:

> For situations where using `--color` is not possible, use the environment variable `FORCE_COLOR=1` (level 1), `FORCE_COLOR=2` (level 2), or `FORCE_COLOR=3` (level 3) to forcefully enable color, or `FORCE_COLOR=0` to forcefully disable. The use of `FORCE_COLOR` overrides all other color support checks.

**Comment by jdforrester** [comment]
Thank you! That works well enough for my use case. Will keep this in mind to expose through flags if users ask for the feature. Thanks again.
