### ISSUE TITLE
Version 13.2.0 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by johnhunter** [stylelint/stylelint#4607]
> Clearly describe the bug

Running stylelint results in a CLI error

`TypeError: Cannot read property 'length' of undefined`

> Which rule, if any, is the bug related to?

Any.

> What CSS is needed to reproduce the bug?

```css
.foo {
  color: red;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-standard"
}
```
with stylelint-config-standard@20.0.0 

> Which version of stylelint are you using?

`13.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with NPN task: `stylelint 'src/sass/test.css'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

no, see example above

> What did you expect to happen?

npm task should complete normally with no errors

> What actually happened (e.g. what warnings or errors did you get)?

Running the npm task results in the following error

```shell
> stylelint 'src/sass/test.css'

TypeError: Cannot read property 'length' of undefined
    at Object.getPatternParts ([...]/node_modules/fast-glob/out/utils/pattern.js:94:20)
    at PartialMatcher._getPatternSegments ([...]/node_modules/fast-glob/out/providers/matchers/matcher.js:30:37)
    at PartialMatcher._fillStorage ([...]/node_modules/fast-glob/out/providers/matchers/matcher.js:19:35)
    at new Matcher ([...]/node_modules/fast-glob/out/providers/matchers/matcher.js:10:14)
    at new PartialMatcher ([...]/node_modules/fast-glob/out/providers/matchers/partial.js:4:1)
    at DeepFilter._getMatcher ([...]/node_modules/fast-glob/out/providers/filters/deep.js:16:16)
    at DeepFilter.getFilter ([...]/node_modules/fast-glob/out/providers/filters/deep.js:11:30)
    at ProviderAsync._getReaderOptions ([...]/node_modules/fast-glob/out/providers/provider.js:25:41)
    at ProviderAsync.read ([...]/node_modules/fast-glob/out/providers/async.js:12:30)
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clementine@0.0.0 lint:test: `stylelint 'src/sass/test.css'`
npm ERR! Exit status 1
```

**Comment by ybiquitous** [comment]
Hi @jhwohlgemuth 
I also got this error today, but this does not seem an issue of stylelint.
https://github.com/mrmlnc/fast-glob/issues/253

I've resolved this issue via the following command to update `picomatch` as sub-dependency:

```
npm update picomatch --depth=5
```

`--depth=5` is dependent on each environment.

**Comment by johnhunter** [comment]
Thanks @ybiquitous. I get a 403 error on running `npm update picomatch --depth=5` So' i'll pin to 13.1.0 until the issues with fast-glob are resolved.

**Comment by rchl** [comment]
You can try `npm un stylelint && npm I stylelint` to re-install it, together with all sub-dependencies.

**Comment by johnhunter** [comment]
Good idea, thanks. In the end I used @ybiquitous suggestion to update `picomatch` - it turned out my 403 issue was an npm availability problem.

**Comment by jeddy3** [comment]
I can no longer reproduce this with a fresh install of stylelint using npm. Is it still an issue for yarn users, or can we close this?

**Comment by evilebottnawi** [comment]
@jeddy3 https://github.com/mrmlnc/fast-glob/issues/253#issuecomment-586914257

**Comment by ybiquitous** [comment]
It seems this issue has resolved! 🎉 

https://github.com/mrmlnc/fast-glob/issues/253#issuecomment-589248324

**Comment by jeddy3** [comment]
Can we close this or is this dependent on us putting out a new release of stylelint?

**Comment by evilebottnawi** [comment]
@jeddy3 I think we can close it, the original issue was resolved and we don't have `fast-glob` in our deps (it is a transitive dep)

**Comment by ybiquitous** [comment]
I also agree with @evilebottnawi 👍

**Comment by johnhunter** [comment]
Agreed.
