### ISSUE TITLE
Difference in Styelint results between Windows and Mac?

### ISSUE THREAD

**Issue by gntsketches** [stylelint/stylelint#4609]
I work on Windows 10 and am consistently getting stylelint errors that another developer on my team who uses Mac does not (I mean, for the same blocks of code.)

I'm not sure whether to report this as a bug, as it seems as likely to have to do with Windows as with Styleline. I'm wondering if this has been reported before and if so what a proper workaround might be (if there is one other than disabling those rules.)

So far all the errors are of these types:
- Expected selector ".selector227 img" to come before selector ".selector226 > .stat > img"   no-descending-specificity
- Unexpected duplicate "margin-bottom" declaration-block-no-duplicate-properties

**Comment by ntwb** [comment]
That's a strange case, primarily issues seen between the different OSs have to do with line endings between the two platforms.

If you had of used the template provided when you created the issue you could have included the sample CSS that would have helped us identify the issue, as such I'm closing this issue as we cannot diagnose this issue as it stands, please create a new issue using the issue template to include the information that we ask, stylelint version, how you are using stylelint, the rules you are using, and example CSS code.
