### ISSUE TITLE
Please support JSF EL tokens when parsing

### ISSUE THREAD

**Issue by Vampire** [stylelint/stylelint#4621]
> What is the problem you're trying to solve?

We use SonarQube with its CSS plugin to check our CSS files.
Our CSS files have JSF EL tokens in them like for example `font-family: #{appearanceBean.fontFamily};` or `font-family: ${appearanceBean.fontFamily};`. (https://docs.oracle.com/javaee/7/tutorial/jsf-el.htm)
When using JSF this should be quite common.
When the SonarQube CSS plugin parses the CSS files that contain those tokens, the parsing fails with error message `Unknown word` for the files where JSF EL is used on the first occurrence of such a token.
SonarSource said they cannot do anything on this, as the use Stylelint under the hood and it cannot parse those files.

> What solution would you like to see?

Parsing should work poperly if a JSF EL token is encountered, any code inspecting this should assume there is a valid value used.

**Comment by evilebottnawi** [comment]
You need custom parser for this

**Comment by jeddy3** [comment]
@Vampire Thanks for the request and for using the template.

As @evilebottnawi said, you can [write a custom PostCSS syntax](https://github.com/postcss/postcss/blob/master/docs/syntax.md) and then use stylelint [customSyntax](https://stylelint.io/user-guide/usage/options#customsyntax) option to achieve this.

> When using JSF this should be quite common.

If there is community support for creating and maintaining the custom syntax, we can consider bundling it into stylelint [like we do with other popular syntaxes](https://stylelint.io/about/syntaxes).
