### ISSUE TITLE
npm run stylelint failed:This is probably not a problem with npm. There is likely additional logging output above

### ISSUE THREAD

**Issue by jiameiw** [stylelint/stylelint#4641]
npm run stylelint & "stylelint": "stylelint 'src/**/*.css' 'src/**/*.less'" in package.json failed

No files matching the pattern "'src/**/*.css', 'src/**/*.less'" were found
This is probably not a problem with npm. There is likely additional logging output above
but it works on macOS

**Comment by hudochenkov** [comment]
You probably want your npm script looks like this:

```
"stylelint": "stylelint 'src/**/*.css' 'src/**/*.less'"
```

Next time use issue template, please, if you want us to help.

**Comment by jeddy3** [comment]
If that doesn't work, you might need to use escaped backslashes:

```
"stylelint": "stylelint \"src/**/*.css\" \"src/**/*.less\""
```

As an aside, this isn't an issue with stylelint its just how [npm run-scripts](https://docs.npmjs.com/cli/run-script) work.
