### ISSUE TITLE
stylelint installation fails: have broken dep for babel/runtime

### ISSUE THREAD

**Issue by neffets** [stylelint/stylelint#4643]
> Clearly describe the bug

`npm install stylelint`
fails,
because the dependency to "babel/runtime" is not longer available at github.com
can be that the dep come from another dep "yaml"

> Which rule, if any, is the bug related to?

no rule. Installation fails.

> What code is needed to reproduce the bug?

`npm install stylelint`

> What stylelint configuration is needed to reproduce the bug?

none

> Which version of stylelint are you using?

13.2.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`npm install stylelint`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

no

> What did you expect to happen?

it should install.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
npm install stylelint
loadDep:write-file-atomic ▀ ╢███████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-88-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "stylelint"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log
```
I'm running on Ubuntu 18.04LTS with npm in version 3.5.2 and node 8.10.0

**Comment by neffets** [comment]
[npm-debug.log](https://github.com/stylelint/stylelint/files/4320098/npm-debug.log)

**Comment by evilebottnawi** [comment]
Seems problem on npm side, npm 3.5.2 is deprecated, we can't help with it, sorry, update your npm version

**Comment by neffets** [comment]
Yes old npm has problem to resolve the right version of "yaml"

> npm install yaml@1.8.2
fails with the github not found repo for babel/runtime

> npm install yaml@1.7.2
the version originally requested by stylelint, is OK

WORKAROUND for older npm:
```shell
npm install yaml@1.7.2 stylelint
```
