### ISSUE TITLE
Configure postcss-syntax to use forked syntaxes

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#4645]
When we publish [`@stylelint/postcss-css-in-js`](https://github.com/stylelint/postcss-css-in-js) we'll need to configure postcss-syntax to use it rather `postcss-jsx`.

I've labelled as ready to implement as we could do with investigating and proving, sooner rather than later, that this is possible.

**Comment by hudochenkov** [comment]
We would also need to do the same for `@stylelint/postcss-markdown`.

**Comment by ntwb** [comment]
I don’t believe we can publish packages under the `@stylelint` scope on npm without first converting the the npm `stylelint` user to an npm organisation account, this will involve a bit of juggling to process all this in my mind (2FA, organisation members etc)

I’m a little behind in my emails, but if this has been discussed else where please let me know

**Comment by jeddy3** [comment]
> I’m a little behind in my emails, but if this has been discussed else where please let me know

Nope, I don't think we had considered it. I can look into it today.

**Comment by jeddy3** [comment]
> the the npm stylelint user to an npm organisation account

Apparently I did this 3 years ago...

I've sent you both invites to the npm org.

**Comment by hudochenkov** [comment]
Thanks!

npm organisation account info is mission in our password manager. Could you add it there, please?

**Comment by jeddy3** [comment]
> Could you add it there, please?

Done.

I also converted you to an owner of the npm org. We'll do the same for @ntwb once he's added.

**Comment by ntwb** [comment]
Thanks org Invite accepted
