### ISSUE TITLE
Document how to lint multiple extension using the CLI

### ISSUE THREAD

**Issue by stephenliu1944** [stylelint/stylelint#4661]
> Clearly describe the bug
Is there a way to lint multiple ext type by CLI, like:
```
stylelint src/**/*.(css|scss|sass)
// or
stylelint src/**/*.{css,scss,sass}
// or like eslint
stylelint src/ --ext css,scss,sass
```
I just use:
```
stylelint src/**/*.css src/**/*.scss src/**/*.sass
```
to do that, but not looks well.

**Comment by jeddy3** [comment]
> `stylelint src/**/*.{css,scss,sass}`

This is correct. However, you'll want to quote your glob, like so:

```
stylelint "src/**/*.{css,scss,sass}"
```

I'm labelling this as a documentation issue as I suspect more newcomers will now be using stylelint to lint multiple styling languages and containers.

I suggest we add one more [usage example to the list](https://stylelint.io/user-guide/usage/cli#usage-examples):

---

## Example B - multiple file extensions

Linting all `.css`, `.scss` and `.sass` files:

```
stylelint "**/*.{css,scss,sass}"
```

---

FYI, you can use [globtester](https://globster.xyz/) to test your globs.

@stephenliu1944 I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) this documentation amend if you have time.

**Comment by malsf21** [comment]
Hey, if this is a quick doc fix I don't mind implementing it - do y'all mind?
