### ISSUE TITLE
Autofix not working for declaration-block-trailing-semicolon

### ISSUE THREAD

**Issue by hornta** [stylelint/stylelint#4738]
> Clearly describe the bug

The autofix isn't working for declaration-block-trailing-semicolon

> Which rule, if any, is the bug related to?

declaration-block-trailing-semicolon

> What code is needed to reproduce the bug?

e.g.

```css
.foo {
  margin-top: 3
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "declaration-block-trailing-semicolon": "always"
  }
}
```

> Which version of stylelint are you using?

13.3.3

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.less" --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

The autofix to have been applied.

> What actually happened (e.g. what warnings or errors did you get)?

No autofix were applied.

```shell
test.css
2:14    Expected a trailing semicolon (declaration-block-trailing-semicolon)
```

**Comment by jeddy3** [comment]
@hornta Thanks for using the template.

I can't reproduce this locally.

See https://github.com/stylelint/stylelint/issues/4736.

**Comment by hornta** [comment]
I've updated this with a working code example now.
