### ISSUE TITLE
Autofix not working for block-closing-brace-empty-line-before

### ISSUE THREAD

**Issue by hornta** [stylelint/stylelint#4739]
> Clearly describe the bug

The autofix isn't applied for reports of `block-closing-brace-empty-line-before`

> Which rule, if any, is the bug related to?

block-closing-brace-empty-line-before

> What code is needed to reproduce the bug?

e.g.

```css
.foo {
  .bar {
    color: pink;

  }
}
```

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "rules": {
    "block-closing-brace-empty-line-before": "never"
  }
}
```

> Which version of stylelint are you using?

13.3.3

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint "**/*.less" --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Maybe it's related to Less nested rules.

> What did you expect to happen?

The autofix to have been applied.

> What actually happened (e.g. what warnings or errors did you get)?

Nothing

```shell
test.css
4:2    Unexpected empty line before closing brace (block-closing-brace-empty-line-before)
```

**Comment by jeddy3** [comment]
I can't reproduce this locally.

See https://github.com/stylelint/stylelint/issues/4736#issuecomment-624749470.

You're welcome to reopen with a reproducible repo.

**Comment by hornta** [comment]
Ok it was like I suspected related to other code. I've updated the code examples now.
