### ISSUE TITLE
Add configFile option to plugin options

### ISSUE THREAD

**Issue by saviomd** [stylelint/stylelint#475]
With eslint, I can do this:
```
.pipe(eslint({configFile: '.eslintrc'}))
.pipe(eslint.format())
```

But with gulp I don't know what to do.
The only way I managed to do it, is giving a .json extension to the file and using require. But I would like to have the file without an extension, what can I do?
(if the file doesn't have an extension, the require function breaks..)
this works:
```
.pipe(postcss([
	stylelint(require('./stylelint.json'))
]))
```
this does not:
```
.pipe(postcss([
	stylelint(require('./stylelint'))
]))
```
neither this:
```
.pipe(postcss([
	stylelint({config: 'stylelint'))
]))
```

**Comment by davidtheclark** [comment]
How about

```js
var fs = require('fs');
var myConfig = fs.readFileSync('/path/to/myConfig.json');
..
.pipe(postcss([
  stylelint(myConfig)
]))
```

??

**Comment by jeddy3** [comment]
You can also try it without any config specified in the options. It should then look for the .`stylelintrc` file behind-the-scenes. e.g.

```js
var gulp = require('gulp')
var postcss = require('gulp-postcss')
var stylelint = require('stylelint')

gulp.task('lint', function () {
    var processors = [
        stylelint()
    ]
    return gulp.src('css/*.css')
        .pipe(postcss(processors))
})
```

**Comment by luisfmsouza** [comment]
#watching

**Comment by saviomd** [comment]
@davidtheclark I didn't know about filesync! I will try that out, thank you

@jeddy3 yes, i know and this is something I've already started to think about. Rename/reorganize all my config files so they have the default name and path, so I don't have to set them up anymore. Thanks for the suggestion

**Comment by saviomd** [comment]
But I think that it would be a good idea to have a option to setup the path/name of the config file anyway.
Eslint has it (called "configFile"), so probably I'm not the only that needs it :)

**Comment by davidtheclark** [comment]
Sure, it could be added without too much trouble, probably. @jeddy3 any opposition?

**Comment by jeddy3** [comment]
> @jeddy3 any opposition?

None. :)
