### ISSUE TITLE
stylelint不能格式化嵌套在vue组件文件里的sass代码

### ISSUE THREAD

**Issue by qianluoluo** [stylelint/stylelint#4757]
> Clearly describe the bug

stylelint不能格式化嵌套在vue组件文件里的sass代码

> Which rule, if any, is the bug related to?

报错：TypeError: Cannot read property 'search' of undefined

> What code is needed to reproduce the bug?

```css
.org-container
  display: flex
  position: relative
  width: 212px
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
 rules: {
    'at-rule-no-unknown': [true, {
      ignoreAtRules: [
        'mixin', 'extend', 'content',
      ],
    }],
    'selector-pseudo-element-no-unknown': [true, {
      ignorePseudoElements: ['v-deep'],
    }],
    'selector-max-id': null,
  },
}
```

> Which version of stylelint are you using?

`^13.3.3`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

 "CLI with `stylelint "src/**" --fix`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"SASS"

> What did you expect to happen?

 "No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

```shell
TypeError: Cannot read property 'search' of undefined
    at /Users/eleme/project/family/src/components/org/xxx.vue:130:1
```

**Comment by hudochenkov** [comment]
Please, use English language. We can't help you otherwise.

**Comment by jeddy3** [comment]
I'm unable to [reproduce this using the demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIB0EBOBzAtJAdgFwEMBLHGVAHRwAIqoiBnABwBsCBPeKgM2ZgA9KNRhHpE8RCDk6oYrcQDcYgqgHciUPAAtOAJgCMOxgJwgANCHpt8BPggsF69M+Elci6O8Erk85EKgBXXno-Ti8cH0iQAjxMQN5MHAhMAJwAaySVCIQqAG1vX0K8QJhTAsi8cIrqkHckmQBBPAAlIJgQnPyQAFsiPhI-Uyo-fjwYHChB4Zd8cd8QAF1ywoBfZYWyiMK-elkYMDw0TEZdgKhkve65xOTUjIgs0Lzln2KA0pfKz6i6tBgABVO5wAorwrvgOpwuvJMLAYIw-EsthU1si8BsXhY9gcjt0bJh1E8cEFmAVUSsQCsgA).

Closing for now, but you can reopen with a reproducible demo or repo.
