### ISSUE TITLE
No files matching only Windows

### ISSUE THREAD

**Issue by maystrenkoYurii** [stylelint/stylelint#4772]
![Снимок](https://user-images.githubusercontent.com/23016311/81979909-654a7400-9636-11ea-9cd3-d4cf8f2550d2.PNG)

**Comment by hudochenkov** [comment]
Please use issue template if you want us to help you.

**Comment by jeddy3** [comment]
Closing as there's not enough actionable information.

Issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
