### ISSUE TITLE
Add --list-rules CLI arg

### ISSUE THREAD

**Issue by ThiefMaster** [stylelint/stylelint#4774]
I would like to have a command line arg indicating which rules are available (including those from plugins!) and whether they have any non-default config (ideally even showing from which `extends` they are coming).

This would be helpful in seeing whether there are any other rules I may want to enable, besides the defaults provided by the presets I'm using.

**Comment by jeddy3** [comment]
@ThiefMaster Thanks for the request and for using the template.

I believe this can be done, including listing unused rules from plugins, with the [stylelint-find-new-rules](https://github.com/Donov4n/stylelint-find-new-rules) tool.

```
npx stylelint-find-new-rules
```

I'm not sure we'll want to bake this functionality into stylelint itself, but I've leave the issue open for discussion.

As an aside, I've created [a pull request](https://github.com/stylelint/awesome-stylelint/pull/19) to add it to [awesome stylelint](https://github.com/stylelint/awesome-stylelint).

**Comment by jeddy3** [comment]
Closing for now. We can reopen if there are more thumbs-up for the feature.
