### ISSUE TITLE
no-extra-and for less

### ISSUE THREAD

**Issue by kaysonwu** [stylelint/stylelint#4786]
> What is the problem you're trying to solve?

Can you remind me to delete the extra '&'？

> What solution would you like to see?

```less
&-parent {
 // For less, the `&` is extra
 & > .children {
  }
}
```

**Comment by jeddy3** [comment]
@kaysonwu Thank you for the request.

The built-in rules are geared towards standard CSS, where the _nesting selector_ (`&`) is required.

Fortunately, Less and Sass syntax overlap when it comes to the nesting selector and there's the [`selector-no-redundant-nesting-selector` rule](https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/selector-no-redundant-nesting-selector/README.md) in the [`stylelint-scss` plugin](https://github.com/kristerkari/stylelint-scss) that does what you want.

As an aside, the explicitness of the nesting selector can be useful so I'd question whether you'd want to turn on that rule or not, but it's there if you want to.

**Comment by kaysonwu** [comment]
Thanks, let me try. It's just that the naming of the plugin made me ignore it!

**Comment by jeddy3** [comment]
Yes, the plugin name can be a little misleading.

The [README tries to clarify](https://github.com/kristerkari/stylelint-scss#purpose), though:

> stylelint-scss introduces rules specific to SCSS syntax. That said, the rules from this plugin can be used with other syntaxes, like Less or some PostCSS syntaxes. That's why the rules' names are not tied to SCSS only (`at-function-pattern` instead of `scss-function-pattern`).

I hope it works for you.

**Comment by kaysonwu** [comment]
Thanks,  I'm already using it and promoting it in less applications.
