### ISSUE TITLE
unit-whitelist exceptions based selectors

### ISSUE THREAD

**Issue by alejandroclaro** [stylelint/stylelint#4789]
> What is the problem you're trying to solve?

Define unit-whitelist or blocklist based on selector or other criteria. I want to restrict the use of absolute units but use them for the base cases. I have a case like this:

``` scss
$breakpoints: (
  "extra-small": ("width": 800px, "height": 600px),
  "small": ("width": 1024px, "height": 800px),
  "medium": ("width": 1024px, "height": 1280px),
  "large": ("width": 1280px, "height": 1024px)
);
```

I would like to add an exception to these breakpoints without disabling the rule with a comment in these lines. I can add an exception for property 'width', but that will affect all the occurrences of 'width' property, and that's not what I want. I just want to allow the use of absolute units in the properties inside the definition of '$breakpoint'.

> What solution would you like to see?

Add a mechanism to add exception based on the "selector" where the exception must be applied.

**Comment by jeddy3** [comment]
@alejandroclaro Thanks for the request and for using the template.

The built-in rules [are geared towards standard CSS](https://stylelint.io/user-guide/rules/about). The comprehensive [`stylelint-scss` plugin](https://github.com/kristerkari/stylelint-scss/) is your best place to request the feature of limiting units in [a Sass map](https://sass-lang.com/documentation/values/maps) value based on key or parent key.

> I would like to add an exception to these breakpoints without disabling the rule with a comment in these lines.

As an aside, disabling the `unit-whitelist` rule with a comment is perfectly valid. It's a great example of why the comment system exists. I recommend designing your configuration object to cover _the usual_, and then use comments to disable rules for one-off occasions of code.

The explicitness of comments can also help communicate intent to other team members in-situ. For example, by adding `/*stylelint-disable unit-whitelist*/` to this bit of code you're saying that that you're allowing the use of a unit (for this snippet of code only) that you wouldn't _normally_ allow.

**Comment by alejandroclaro** [comment]
Thanks @jeddy3 

I will try to ask for this in stylelint-scss plugin project.

I fully understand your comment and I agree. However, we work in projects with strict coding standards and audit processes conducted by third parties, and most of the time it's not acceptable to them silent rule validations. They look for these comments and report them as a violation of the established rules. They prefer those exceptions to be documented in the definition of the rules and, if possible, handled by tools rather than by comments in code.
