### ISSUE TITLE
Fix up rule list in #1 to accord with whitespace conventions

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#48]
Lots of `something-before` and `-after` will need to be revised to `something-space`.

**Comment by jeddy3** [comment]
Yeap. I can do this, if you like?

**Comment by davidtheclark** [comment]
That would be swell. I like that you're taking charge of the documentation and ensuring it is accurate and consistent.

**Comment by jeddy3** [comment]
I like accurate and consistent documentation :)

**Comment by davidtheclark** [comment]
As any decent person should.

**Comment by jeddy3** [comment]
:)

**Comment by MoOx** [comment]
❤️

**Comment by jeddy3** [comment]
Done.
