### ISSUE TITLE
How do we use `selector-pseudo-element-whitelist` with `selector-pseudo-element-no-unknown`?

### ISSUE THREAD

**Issue by IAMtheIAM** [stylelint/stylelint#4807]
> Clearly describe the documentation issue

If I disbable unknown pseudo elements, then try to add back specific elements to the whitelist, it does not respect the white list.

```
        "selector-pseudo-element-whitelist": ["/^ng-deep/"],
        "selector-pseudo-element-no-unknown": true,
```
> What solution would you like to see?
Whitelist should override `no-unknown` list.

**Comment by hudochenkov** [comment]
Use `null` to [turn off a rule](https://stylelint.io/user-guide/configure#rules).
