### ISSUE TITLE
SyntaxError: Unexpected token i

### ISSUE THREAD

**Issue by ahmedelgabri** [stylelint/stylelint#481]
I'm trying to integrate stylelint in a project that uses `.scss` using gulp and here is the minimal task that I created 

```js
var postcss      = require('gulp-postcss');
var stylelint      = require('stylelint');
var srcFiles   = '<path to scss files>/**/*.scss';
gulp.task('foo', function() {
    return gulp.src(srcFiles)
            .pipe(postcss([
                stylelint()
            ], { parser: require('postcss-scss') })).on('error', function(err) { console.log(err.stack) })
});
```

and this is the output
```sh
[15:53:48] Using gulpfile ~/Sites/dev/foo-project/gulpfile.js
[15:53:48] Starting 'foo'...
SyntaxError: Unexpected token i
    at Object.parse (native)
    at exports.parse (/Users/Gabri/Sites/dev/foo-project/node_modules/stylelint/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Users/Gabri/Sites/dev/foo-project/node_modules/stylelint/node_modules/rc/index.js:31:20)
    at module.exports (/Users/Gabri/Sites/dev/foo-project/node_modules/stylelint/node_modules/rc/index.js:45:3)
    at /Users/Gabri/Sites/dev/foo-project/node_modules/stylelint/dist/plugin.js:48:43
    at LazyResult.run (/Users/Gabri/Sites/dev/foo-project/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Users/Gabri/Sites/dev/foo-project/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Users/Gabri/Sites/dev/foo-project/node_modules/postcss/lib/lazy-result.js:129:15)
    at processing.Promise.then._this2.processed (/Users/Gabri/Sites/dev/foo-project/node_modules/postcss/lib/lazy-result.js:155:20)
    at LazyResult.async (/Users/Gabri/Sites/dev/foo-project/node_modules/postcss/lib/lazy-result.js:152:27)
[15:53:48] 'foo' errored after 32 ms
[15:53:48] SyntaxError in plugin 'gulp-postcss'
Message:
    Unexpected token i
```

I even tried with a dummy `.scss` file, still got the same error.
```scss
// SCSS Comment
.foo {
    color: red;
}
```

Even tried using NodeAPI directly, still getting the same error.

So I can't really find what is the problem or what am I doing wrong, I'm using the latest versions of `gulp-postcss`, `postcss-scss` and `stylelint`.

**Comment by TrySound** [comment]
@ahmedelgabri Show your `.stylelintrc`

**Comment by ahmedelgabri** [comment]
@TrySound 

I tried with this only, and also failed.

```json
{
    "rules": {
        "string-quotes": [2, "double"],
    }
}
```

Here is the full one

```json
{
    "rules": {
        "string-quotes": [2, "double"],
        "color-hex-case": [2, "lower"],
        "color-no-invalid-hex": 2,
        "number-leading-zero": [1, "never"],
        "number-max-precision": [2, 3],
        "number-no-trailing-zeros": 2,
        "number-zero-length-no-unit": 2,
        "function-calc-no-unspaced-operator": 2,
        "function-blacklist": [],
        "function-comma-newline-after": [2, "always-multi-line"],
        "function-comma-space-after": [2, "always"],
        "function-comma-space-before": [2, "never"],
        "function-linear-gradient-no-nonstandard-direction": 2,
        "function-space-after": [2, "always"],
        "function-url-quotes": [2, "none"],
        "value-no-vendor-prefix": 2,
        "value-list-comma-newline-after": [2, "never-multi-line"],
        "value-list-comma-newline-before": [2, "never-multi-line"],
        "value-list-comma-space-after": [2, "always"],
        "value-list-comma-space-before": [2, "never"],
        "property-blacklist": ["height"],
        "property-no-vendor-prefix": 2,
        "property-unit-blacklist": [2, {
            "font-size": ["px"],
            "width": ["px"],
            "height": ["px"]
        }],
        "custom-property-no-outside-root": 2,
        "declaration-bang-space-after": [2, "never"],
        "declaration-bang-space-before": [2, "always"],
        "declaration-colon-space-after": [2, "always"],
        "declaration-colon-space-before": [2, "never"],
        "declaration-no-important": 1,
        "declaration-block-semicolon-newline-after": [2, "always"],
        "declaration-block-semicolon-newline-before": [2, "never"],
        "block-closing-brace-newline-after": [2, "always"],
        "block-closing-brace-newline-before": [2, "never"],
        "block-no-empty": 2,
        "block-opening-brace-newline-after": [2, "always"],
        "block-opening-brace-newline-before": [2, "never"],
        "selector-combinator-space-after": [2, "always"],
        "selector-combinator-space-before": [2, "always"],
        "selector-no-id": 2,
        "selector-no-type": 1,
        "selector-no-universal": 2,
        "selector-no-vendor-prefix": 2,
        "selector-pseudo-element-colon-notation": [1, "double"],
        "selector-root-no-composition": 2,
        "selector-list-comma-newline-after": [2, "always"],
        "selector-list-comma-newline-before": [2, "never"],
        "selector-list-comma-space-after": [2, "always"],
        "selector-list-comma-space-before": [2, "never"],
        "rule-nested-empty-line-before": [2, "always"],
        "rule-no-duplicate-properties": 2,
        "rule-no-shorthand-property-overrides": 2,
        "rule-non-nested-empty-line-before": [2, "always", {
            ignore: ["after-comment"]
        }],
        "rule-single-line-max-declarations": [2, 1],
        "rule-trailing-semicolon": [2, "always"],
        "root-no-standard-properties": 2,
        "media-feature-colon-space-after": [2, "always"],
        "media-feature-colon-space-before": [2, "never"],
        "media-feature-name-no-vendor-prefix": 2,
        "media-query-list-comma-newline-after": [2, "always"],
        "media-query-list-comma-newline-before": [2, "never"],
        "media-query-list-comma-space-after": [2, "always"],
        "media-query-list-comma-space-before": [2, "before"],
        "at-rule-empty-line-before": [2, "always"],
        "at-rule-no-vendor-prefix": 2,
        "comment-empty-line-before": [2, "always"],
        "comment-space-inside": [2, "always"],
        "no-eol-whitespace": 2
    },
    "plugins": {
        "statement-max-nesting-depth": [2, 2, { atRulesDontCount: true }]
    }
}
```

**Comment by TrySound** [comment]
@ahmedelgabri In your short example json can't have last comma, your second example shows error own :)

**Comment by ahmedelgabri** [comment]
@TrySound the short example is just a typo copying and pasting it here, fixed. 

Regarding the second example... I'm speechless :disappointed_relieved:

But shouldn't the error message be more descriptive than this? Like _Your config file has an error_ or something.

But thanks and sorry for silly mistake!

**Comment by TrySound** [comment]
@ahmedelgabri I think about decision

**Comment by ahmedelgabri** [comment]
Cool, thanks :+1:

**Comment by TrySound** [comment]
@davidtheclark `rc` Sucks. It's sync. And it passes only content without filepath for good error message. Also `jsYaml.safeLoad` parses even non-strict json like example above. Need to change something.

**Comment by jeddy3** [comment]
@TrySound Thanks for diagnosing this one :)

You also get `SyntaxError: Unexpected token i` with the CLI and standalone API. @davidtheclark Are we expecting at least the CLI to [exit with 78 code](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md#exit-codes) in this instance?

@ahmedelgabri You'll also need to configure your plugin [differently](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#plugins) i.e. 

```json
{
  "plugins": {
    "statement-max-nesting-depth": "statement-max-nesting-depth",
  },
  "rules": {
    "statement-max-nesting-depth": [2, 2, { "atRulesDontCount": true }]
  }
}
```

Assuming you've just `npm install`ed `statement-max-nesting-depth` and it's in your `node_modules` directory.

Please let us know if you run into any issues with the plugin system. We've only just gotten started with it and you'll likely to be one of the first few people to be using it. Thanks :)

@davidtheclark Do you think I should comb through the docs making sure we have used json for all the config examples?

**Comment by jeddy3** [comment]
@ahmedelgabri One more thing... are you using `master` or `2.0.0`? I only ask as you're configuring the `property-unit-blacklist` rule in your config i.e.:

```json
"property-unit-blacklist": [2, {
  "font-size": ["px"],
  "width": ["px"],
  "height": ["px"]
}],
```

That rule is hot-off-the-press and was only added a couple of days ago (courtesy of @makotot).

So you might be running into an "invalid rule" error if you're not using `master`. 

I think we were planning on releasing `2.1.0` today anyhow. So if you do run into that error... either use `master` or wait a little where until we get the release out :)

@davidtheclark Shall I release?

**Comment by jeddy3** [comment]
@davidtheclark FYI, I'm just double checking and bringing the CHANGELOG up-to-date. In case you were thinking of doing the same.

**Comment by ahmedelgabri** [comment]
@jeddy3 yes I noticed a couple of more stuff that I needed to change. The plugin config and the `property-unit-blacklist` and maybe a couple of more rules. 

I assume I'm using `master` because I just did simple `npm install` I'm not on my laptop now to check. But will check later and let you know.

**Comment by jeddy3** [comment]
@ahmedelgabri FYI, `npm install` installs the latest _published to npm_ version i.e. our latest [release](https://github.com/stylelint/stylelint/releases) and which is usually a little behind `master`. `master` is the git branch where we push our latest features in preparation for bundling them into the next release.

Don't worry though as we just released, and published to npm, version `2.1.0`... which contains all the new rules. You'll just need to do an `npm install stylelint@latest --save-dev` to get it :)

**Comment by ahmedelgabri** [comment]
@jeddy3 thanks, updated it and everything is working now :+1:

**Comment by jeddy3** [comment]
Glad to hear :)

**Comment by ahmedelgabri** [comment]
One minor issue thought :sweat: when I fixed the plugin configuration I'm getting this now. Shouldn't it be picked from `node_modules` without configuration?

```
Error: Could not find "statement-max-nesting-depth". Do you need a `configBasedir`?
```

**Comment by jeddy3** [comment]
Oops, my bad... your config needs to be:

```json
{
  "plugins": {
    "statement-max-nesting-depth": "stylelint-statement-max-nesting-depth"
  },
  "rules": {
    "statement-max-nesting-depth": [2, 2, {
        "atRulesDontCount": true
      }
    ]
  }
}
```

Note the name of the module is `stylelint-statement-max-nesting-depth`. The key of the object is what you want to call the rule and the value is the "locator", which, in your instance, is the full name of the module.

I've just run it myself and it works fine. Although, you will get a couple of deprecation warnings if you're using PostCSS 5+ as the plugin is using some PostCSS 4 API calls. I'll raise another issue to address that.

**Comment by ahmedelgabri** [comment]
> The key of the object is what you want to call the rule and the value is the "locator", which, in your instance, is the full name of the module.

I guess mentioning this in the docs can be helpful too :)

Thanks a lot!

**Comment by jeddy3** [comment]
[Is it](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#plugins). I just forgot to double check the docs when I wrote the first example :)

Anyhow. Glad it working for you now :)
