### ISSUE TITLE
property-no-unknown to check for valid values

### ISSUE THREAD

**Issue by jkevingutierrez** [stylelint/stylelint#4827]
> What is the problem you're trying to solve?

It would be great to have the ability to check property values to check if they are valid values.

CSS lint have a similar rule [known-properties](https://github.com/CSSLint/csslint/wiki/Require-use-of-known-properties):

_In addition to checking the property name, this rule also checks the property value against the property name to ensure proper values are being supplied. Not all properties are supported yet, but a large number are._

![image](https://user-images.githubusercontent.com/6220055/84405025-325fb580-abcd-11ea-96b0-5fc8ed305f1c.png)

> What solution would you like to see?

The validation could be added to the `property-no-unknown` or it could also be a new rule that could check property values, like `property-no-unknown-values`

**Comment by jeddy3** [comment]
@jkevingutierrez Thanks for the request and for using the template.

You can use the [stylelint-csstree-validator plugin](https://www.npmjs.com/package/stylelint-csstree-validator) to do this. CSSTree is doing the heavy-lifting here, like the parser behind CSSLint does in their [`known-properties` rule](https://github.com/CSSLint/csslint/blob/master/src/rules/known-properties.js#L22)

**Comment by Mouvedia** [comment]
#6511
