### ISSUE TITLE
Add customSyntax option to configuration object

### ISSUE THREAD

**Issue by DimaNazdratenko** [stylelint/stylelint#4843]
It's resolve the problem with integrate stylelint with different languages (for example like Stylus) with many IDEs like WebStorm. 

For example in VS Code there is an option for custom syntax option for stylelint, but in another like WebStorm - NO.

**Comment by jeddy3** [comment]
@DimaNazdratenko Thanks for the request and for using the template.

I thought the same thing when I first encountered @ota-meshi's stylus plugin. 

I can't remember the historical reasons why some things live inside the configuration object, others in options and others as CLI flags. However, I think we should make it consistent i.e. everything that can live in the configuration object should and CLI flags can be used to augment this object. I believe this is how [Jest works](https://jestjs.io/docs/en/jest-object). Eventually, we'd then be able to remove options, which will simplify both the experience for the user and the stylelint codebase.

This would close:

- https://github.com/stylelint/stylelint/issues/3860
- https://github.com/stylelint/stylelint/issues/3859
- https://github.com/stylelint/stylelint/issues/3858

I help us achieve https://github.com/stylelint/stylelint/issues/3128.

Adding `customSyntax` to the configuration object would be part of that work.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
