### ISSUE TITLE
Does not work rules from config files!

### ISSUE THREAD

**Issue by MoskalenkoM** [stylelint/stylelint#4847]
module.exports = {
  extends: 'stylelint-config-standard',
  rules: {
    'property-no-unknown': [true, { ignoreProperties: ['appearance'] }],
    'at-rule-no-unknown': [
      true,
      {
        "ignoreAtRules": ['@custom-media']
      }
    ],
	}
};

Below go wrong in stylelint!

@custom-media --mobile_screen (min-width: 320px) and (max-width: 399px);
@custom-media --tablet_screen (min-width: 400px) and (max-width: 700px);

Below go warning in stylelint!

appearance: none;

What is going on?

**Comment by hudochenkov** [comment]
We can't help you if you don't use issue template, as your comment miss a lot of information.

**Comment by jeddy3** [comment]
Please can recreate your issue using [this template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md). In particular, please answer the questions on what you expected to happen and what actually happened.
