### ISSUE TITLE
Add autofix to *-no-vendor-prefix rules

### ISSUE THREAD

**Issue by yepninja** [stylelint/stylelint#4856]
## Rules
- value-no-vendor-prefix
- property-no-vendor-prefix
- selector-no-vendor-prefix
- media-feature-name-no-vendor-prefix
- at-rule-no-vendor-prefix

## Implementation
Autoprefixer already has method for unprefixing https://github.com/postcss/autoprefixer/blob/d2ce094d39224d0faf219d0b2bca4490e024e704/lib/prefixes.js#L284
Also there is postcss method https://api.postcss.org/vendor.html#.unprefixed

**Comment by hudochenkov** [comment]
We had a PR for this https://github.com/stylelint/stylelint/pull/2565

`postcss.vendor` is removed in the upcoming PostCSS 8 https://github.com/postcss/postcss/issues/1372

**Comment by yepninja** [comment]
I think it is not a problem to implement unprefixing within with issue
