### ISSUE TITLE
Fix inconsistent trailing newlines in CLI errors 

### ISSUE THREAD

**Issue by getsnoopy** [stylelint/stylelint#4862]
> Clearly describe the bug

When the CLI (`stylelint`) fails because of some error (particularly when an exception that's thrown), it prints the message with stack trace and exits the process, but the stack trace doesn't have a trailing newline, so the CLI prompt ends up on the same line as the error message.

> Which rule, if any, is the bug related to?

None.

> What code is needed to reproduce the bug?

Run the CLI in a directory that doesn't have any files that match the glob, for example:

```bash
npx stylelint "**/*.sass"
```

> What stylelint configuration is needed to reproduce the bug?

Any one.

> Which version of stylelint are you using?

`13.6.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint "**/*.sass"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

There should be a trailing newline after the stack trace.

> What actually happened (e.g. what warnings or errors did you get)?

There was no trailing newline stack trace. This happens because [`handleError`](https://github.com/stylelint/stylelint/blob/master/lib/cli.js#L537) in `lib/cli.js` uses `process.stderr.write` instead of `console.error` to write the stack trace. Seeing as `console.error` maps to `STDERR` by default, the latter should be used instead so that the trailing newline is appended to the message.

**Comment by malsf21** [comment]
Hm, I remember us explicitly moving from `console.error` to `process.stderr.write` the last time this file was touched. You can see the accompanying review [here](https://github.com/stylelint/stylelint/pull/4799/files#r434512187).

@m-allanson , are you able to comment? The way I see it, we could either manually add the newline, wrap it in some sort of utility function, or switch to using `console.error`. Not sure what the best approach is here.

**Comment by m-allanson** [comment]
The files should use either `console` or `process.x.write` functions consistently. I don't have a strong opinion on which approach is best.

However, some of the messages already contain ending newlines (e.g. `checkInvalidCLIOptions()` returns a string with ending newlines). So in this case the simplest change is to manually add newlines. I think that should be good enough for now.
