### ISSUE TITLE
Add autofix to function-calc-no-unspaced-operator

### ISSUE THREAD

**Issue by privatenumber** [stylelint/stylelint#4866]
> What is the problem you're trying to solve?

Finding a lot of stylelint errors in my team's codebase about spaces and seems automatable.

```
577:21  ⚠  Expected single space after "*" operator   function-calc-no-unspaced-operator
```
> What solution would you like to see?

`function-calc-no-unspaced-operator` with autofix

**Comment by malsf21** [comment]
Hey @privatenumber,

Thank you for submitting this issue! This seems like a reasonable request to me, though a second opinion from @stylelint/core would be great.

In the meantime, I'll label this as ready to implement. If you have the time, it'd be great if you could contribute the fix yourself! You can find out more about working on rules and creating an autofix [on the stylelint developer guide](https://stylelint.io/developer-guide/rules#add-autofix).

**Comment by jeddy3** [comment]
> This seems like a reasonable request to me, though a second opinion from @stylelint/core would be great.

Sounds good to me.

@privatenumber Please consider [contributing](https://stylelint.io/contributing) if you have time.
