### ISSUE TITLE
Add reportDescriptionlessDisables option

### ISSUE THREAD

**Issue by nex3** [stylelint/stylelint#4868]
> What is the problem you're trying to solve?

Within Google, we want to require that all exceptions to stylelint rules are documented.

> What solution would you like to see?

As I understand it, `stylelint-disable-reason` (#2227) was deprecated because there was no inherent connection between a comment existing immediately before a `/* stylelint-disable */` tag and that comment actually providing a *reason* for the disabled lint. Now that #4840 is implemented, there's a more explicit way to provide a description for a disable tag, but there's still no way to enforce it.

Judging by issues like #2292, it seems like the best way to model this would be as a flag rather than as a rule. So I propose a `reportDisablesWithoutDescriptions` flag that flags any disable tag that doesn't have an associated reason as a violation.

If this is something you'd be amenable to, my team can probably implement it.

**Comment by malsf21** [comment]
Hey @nex3, thank you for using the issue template! 

Overall, I agree, I think this is a good feature to add, and a flag seems like the appropriate way to add it. I'm still pretty new to the project, so would like to defer to someone on @stylelint/core for a second look-over!

**Comment by jeddy3** [comment]
@nex3 Thanks for the request. Sound good to me.

Let's go with a `reportDescriptionlessDisables` option. It'll be similar to the existing [`reportNeedlessDisables` one](https://stylelint.io/user-guide/usage/options#reportneedlessdisables).

---

CLI flags: --report-descriptionless-disables, --rdd

Produce a report of the stylelint-disable comments that are without descriptions.

If needless disables are found, the:
- CLI process exits with code `2`
- Node.js API adds a `descriptionlessDisables` property to the returned data

---

> If this is something you'd be amenable to, my team can probably implement it.

That would be fantastic!
