### ISSUE TITLE
Unit rules in documentation link to a 404 page

### ISSUE THREAD

**Issue by Xaviju** [stylelint/stylelint#487]
Link: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#unit

How to reproduce:
1. Click on the links at the rules options > Units.
2. See 404 not found.

Links are:
unit-blacklist: Specify a blacklist of disallowed units.
unit-whitelist: Specify a whitelist of allowed units.

**Comment by jeddy3** [comment]
@Xaviju Thanks for letting us know :)

Fixed now.

**Comment by Xaviju** [comment]
Question (not sure if this is the right place) on rules: if I do not apply a rule:option in my _.stylelintrc_ there are default values applied? If yes, which ones?

**Comment by jeddy3** [comment]
No rules are turned on by default, so you only have to learn about the rules you want to enforce; and you can start small, growing your config over time as you have a chance to explore more of the rules.

**Comment by Xaviju** [comment]
Thanks :+1:

**Comment by jeddy3** [comment]
Nor are there default values, so you'll need to explicitly configure each of the rules you want to use :)

**Comment by talgautb** [comment]
@jeddy3 the same problem on site :( http://stylelint.io/?/docs/user-guide/rules.md

**Comment by jeddy3** [comment]
@talgautb My bad. I forgot to update the version of stylelint for the website. 

Done now :)
