### ISSUE TITLE
Use fastest-levenshtein instead of leven

### ISSUE THREAD

**Issue by ka-weihe** [stylelint/stylelint#4873]
`fastest-levenshtein` is much faster than `leven`. Please consider using it instead. If you don't believe the benchmark you can run it yourself and see [here](https://github.com/ka-weihe/fastest-levenshtein). I've opened a PR (#4874) for this change.

### Benchmarks
N = length of strings
Numbers are in ops/sec
Higher is better.
| Test Target               | N=4   | N=8   | N=16  | N=32 | N=64  | N=128 | N=256 | N=512 | N=1024 |
|---------------------------|-------|-------|-------|------|-------|-------|-------|-------|--------|
| fastest-levenshtein       | 44423 | 23702 | 10764 | 4595 | 1049  | 291.5 | 86.64 | 22.24 | 5.473  |
| leven                     | 19688 | 6884  | 1606  | 436  | 117   | 30.34 | 7.604 | 1.929 | 0.478  |

**Comment by jeddy3** [comment]
Thank you for the issue. 

I suggest we stick with `leven` for now as it's more popular, even if it's slower.

**Comment by ka-weihe** [comment]
Hmmmm, `fast_levenshtein` is the most popular levenshtein package (14.3 million weekly downloads) and it now uses `fastest-levenshtein` under the hood.  Have a look https://www.npmjs.com/package/fast-levenshtein. The benchmarks in the `leven`-readme are extremely deceiving - `leven` is not even in the top 3 of the fastest levenshtein packages, but people keep using it despite that.
