### ISSUE TITLE
Fix tests that use callbacks

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#4881]
> Clearly describe the bug

I found a bug in the following test code using a callback:

https://github.com/stylelint/stylelint/blob/9f93d1f25ab6c8f8142817269243848fb1bec22a/lib/utils/__tests__/isStandardSyntaxRule.test.js#L58-L62

When I add `done()` to the test as follows, this test fails.

```diff
--- a/lib/utils/__tests__/isStandardSyntaxRule.test.js
+++ b/lib/utils/__tests__/isStandardSyntaxRule.test.js
@@ -55,9 +55,10 @@ describe('isStandardSyntaxRule', () => {
 			expect(isStandardSyntaxRule(rule)).toBeFalsy();
 		});
 	});
-	it('called Less class parametric mixin', () => {
+	it('called Less class parametric mixin', (done) => {
 		lessRules('.mixin-name(@var);', (rule) => {
 			expect(isStandardSyntaxRule(rule)).toBeFalsy();
+			done();
 		});
 	});
 	it('non-outputting parametric Less class mixin definition', () => {
```

```console
$ npx jest --silent lib/utils/__tests__/isStandardSyntaxRule.test.js
 FAIL  lib/utils/__tests__/isStandardSyntaxRule.test.js (5.515 s)
  ● isStandardSyntaxRule › called Less class parametric mixin

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      56 | 		});
      57 | 	});
    > 58 | 	it('called Less class parametric mixin', (done) => {
         | 	^
      59 | 		lessRules('.mixin-name(@var);', (rule) => {
      60 | 			expect(isStandardSyntaxRule(rule)).toBeFalsy();
      61 | 			done();

      at lib/utils/__tests__/isStandardSyntaxRule.test.js:58:2
      at Object.<anonymous> (lib/utils/__tests__/isStandardSyntaxRule.test.js:7:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 30 passed, 31 total
Snapshots:   0 total
Time:        5.544 s, estimated 6 s
```

Because this Less node `.mixin-name(@var);` is an `AtRule` (not `Rule`), and thus `expect()` is not called in the callback passed to `lessRules()`.

When I rewrite the test without a callback as follows, the test fails still, though.
However, the failure is due to passing an `AtRule` to `isStandardSyntaxRule()`, and I believe there is no such a case actually.
(Perhaps, we can fix the failure by returning `false` if `rule.type !== 'rule'`.)

```diff
--- a/lib/utils/__tests__/isStandardSyntaxRule.test.js
+++ b/lib/utils/__tests__/isStandardSyntaxRule.test.js
@@ -56,9 +56,8 @@ describe('isStandardSyntaxRule', () => {
 		});
 	});
 	it('called Less class parametric mixin', () => {
-		lessRules('.mixin-name(@var);', (rule) => {
-			expect(isStandardSyntaxRule(rule)).toBeFalsy();
-		});
+		const rule = less.parse('.mixin-name(@var);').first;
+		expect(isStandardSyntaxRule(rule)).toBeFalsy();
 	});
 	it('non-outputting parametric Less class mixin definition', () => {
 		lessRules('.mixin-name() {}', (rule) => {
```

```console
$ npx jest --silent lib/utils/__tests__/isStandardSyntaxRule.test.js
 FAIL  lib/utils/__tests__/isStandardSyntaxRule.test.js
  ● isStandardSyntaxRule › called Less class parametric mixin

    TypeError: Cannot read property 'startsWith' of undefined

      16 |
      17 | 	// SCSS placeholder selectors
    > 18 | 	if (selector.startsWith('%')) {
         | 	             ^
      19 | 		return false;
      20 | 	}
      21 |

      at isStandardSyntaxSelector (lib/utils/isStandardSyntaxSelector.js:18:15)
      at isStandardSyntaxRule (lib/utils/isStandardSyntaxRule.js:17:7)
      at Object.<anonymous> (lib/utils/__tests__/isStandardSyntaxRule.test.js:60:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 30 passed, 31 total
Snapshots:   0 total
Time:        0.567 s, estimated 1 s
```

There are such invalid test codes using a callback in the other test files, e.g.:

https://github.com/stylelint/stylelint/blob/9f93d1f25ab6c8f8142817269243848fb1bec22a/lib/utils/__tests__/isStandardSyntaxAtRule.test.js#L10-L14

Sadly, the ESLint `jest/no-test-callback` rule cannot detect such problematic code patterns... 😢 
(see https://github.com/jest-community/eslint-plugin-jest/blob/v23.18.2/docs/rules/no-test-callback.md)

> Which rule, if any, is the bug related to?

None.

> What code is needed to reproduce the bug?

See the description above about the reproduction. 

> What stylelint configuration is needed to reproduce the bug?

None.

> Which version of stylelint are you using?

The HEAD version.

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Via Jest, e.g. `npx jest lib/utils/__tests__/isStandardSyntaxRule.test.js`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

I think we should not use a callback in the test code as possible.
Or, if a callback is needed, we should wrap the callback with `return new Promise(done => {})`

> What actually happened (e.g. what warnings or errors did you get)?

Some tests do not work correctly.

**Comment by jeddy3** [comment]
> I think we should not use a callback in the test code as possible.
> Or, if a callback is needed, we should wrap the callback with return new Promise(done => {})

SGTM.

**Comment by ybiquitous** [comment]
I find 2 issues discussing similar problems to this issue:

- https://github.com/facebook/jest/issues/2209
- https://github.com/facebook/jest/issues/5196

Unfortunately, it seems there is not an easy way. 😓

**Comment by ybiquitous** [comment]
FYI. If this ESLint rule (maybe [`jest/prefer-expect-resolves`](https://github.com/jest-community/eslint-plugin-jest/issues/803)) would be implemented, this task might be easier.

**Comment by ybiquitous** [comment]
Progress report (**25** files left):

```console
$ git grep -l -E '\.(then|catch|finally)' '**/*.test.js'
lib/__tests__/extends.test.js
lib/__tests__/ignore.test.js
lib/__tests__/ignoreDisables.test.js
lib/__tests__/integration.test.js
lib/__tests__/invalidScopeDisables.test.js
lib/__tests__/message.test.js
lib/__tests__/needlessDisables.test.js
lib/__tests__/normalizeRuleSettings-integration.test.js
lib/__tests__/plugins.test.js
lib/__tests__/postcssPlugin.test.js
lib/__tests__/printConfig.test.js
lib/__tests__/processors.test.js
lib/__tests__/reportDisables.test.js
lib/__tests__/reportUnknownRuleNames.test.js
lib/__tests__/standalone-cache.test.js
lib/__tests__/standalone-deprecations.test.js
lib/__tests__/standalone-fix.test.js
lib/__tests__/standalone-formatter.test.js
lib/__tests__/standalone-maxWarnings.test.js
lib/__tests__/standalone-quiet.test.js
lib/__tests__/standalone-syntax.test.js
lib/__tests__/standalone.test.js
lib/__tests__/stylelintignore-test/stylelintignore.test.js
lib/rules/linebreaks/__tests__/integration.test.js
lib/utils/__tests__/nodeContextLookup.test.js
```

**Comment by G-Rath** [comment]
I wonder if it could be valuable for `eslint-plugin-jest` to ship something like `no-expects-in-callback` that could take an allowlist to provide a hyper-aggressive way of detecting this 🤔 

> Unfortunately, it seems there is not an easy way. 😓

@ybiquitous you should be able to create a file like [this](https://github.com/G-Rath/audit-app/blob/main/test/setupExpectEachTestHasAssertions.ts) that calls `expect.hasAssertions` before every test.

That won't work if you have tests that don't use `expect`, but depending on what those tests are (and how many there are) there are ways around that - i.e converting test logic into a custom matcher on `expect`, or adding "fake" (or less useful) `expect` calls to those tests to ensure you've got at least one `expect`.

**Comment by ybiquitous** [comment]
> @ybiquitous you should be able to create a file like [this](https://github.com/G-Rath/audit-app/blob/main/test/setupExpectEachTestHasAssertions.ts?rgh-link-date=2021-04-10T22%3A15%3A35Z) that calls `expect.hasAssertions` before every test.

@G-Rath Thank you for the advice! That’s also a nice idea (I didn't know such a way). 😄 

But, I’m a bit concerned about the way that at least one `expect()` may be required would make some developers confusing, since it would introduce an explicit context (maybe as you also pointed). 🤔 

So, I think it best if we can check them via ESLint.
Again, thank you so much for your feedback! 🙌
