### ISSUE TITLE
Add comment-pattern

### ISSUE THREAD

**Issue by ericcornelissen** [stylelint/stylelint#4887]
> What is the problem you're trying to solve?

Linting is used to enforce a common style in code. I want to enforce a (somewhat) common style in comments as well. In particular I would like to enforce all comments to start with a lowercase letter.

> What solution would you like to see?

Either:

1. A specific new rule to enforce comments to start with a lowercase/uppercase letter, e.g. `comment-first-letter: "lowercase"`. Or,
2. A slightly more general rule to enforce comments to adhere to a specific style (with more options then just lowercase/uppercase first letter), e.g. `comment-style: "proper-sentence"` which would require starting with a capital letter and ending with a dot. Or,
3. A general rule that can be used to specify a regular expression that all comments must match. For example, to enforce comments to start with a lowercase letter one could configure: `comment-format: "^[a-z].*$"`

The first two are a little bit easier to use because it doesn't involve coming up with a regular expression that matches your style. The third option is very general and would be useful in many more scenarios then just mine (some of which I probably can't even think of). The advantage of the first one over the second one is that it is more straightforward and doesn't "open the floodgates" on comment styles that _should_ be supported.

I would be in support of both the first and third option, but between those two I don't know which one the maintainers would prefer.

**Comment by jeddy3** [comment]
@ericcornelissen Thanks for the report, using the template and proposing three different solutions.

The third option sounds good to me, i.e. a `comment-pattern` rule.

I'll label up a needing discussion to see if there are any objections. Meanwhile, you're welcome to rustle it up [as a plugin](https://stylelint.io/developer-guide/plugins) to trial the rule in your own projects.

**Comment by jeddy3** [comment]
As there are no objections to this, I'll label the rule as ready to implement:

- Name: `comment-pattern`
- Primary option: `regex`
- Secondary options: None
- Autofixable: No
- Message: "Expected comment to match specified pattern"
- Description: "Specify a pattern for comments."
- Section: "Limit language features" -> "Comment"

@ericcornelissen I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new rule](https://stylelint.io/developer-guide/rules#add-a-rule) in the Developer guide.

You'll likely want to use the [`custom-property-pattern` rule](https://github.com/stylelint/stylelint/tree/master/lib/rules/custom-property-pattern) as a blueprint. You'll want to include some `// comment` tests too.
