### ISSUE TITLE
Remove DisableReportRange.unusedRule

### ISSUE THREAD

**Issue by nex3** [stylelint/stylelint#4899]
(Added by request in https://github.com/stylelint/stylelint/pull/4897/files#r470950362)

#4897 renames the `DisableReportRange.unusedRule` field to `.rule`, since it's used to refer to rules in multiple contexts (rather than just when they're unused). We're keeping the old field name around for the time being to ensure backwards-compatibility, but in the next major version release the old name should be removed entirely.

**Comment by ota-meshi** [comment]
Note that vscode-stylelint also uses that `unusedRule` field.
https://github.com/stylelint/vscode-stylelint

**Comment by jeddy3** [comment]
>  but in the next major version release the old name should be removed entirely.

SGTM. I'll set the milestone to future-major.

**Comment by ybiquitous** [comment]
Closed via #5345
