### ISSUE TITLE
Performance benchmarks (consider lodash)

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#49]
Followup to discussion here: https://github.com/stylelint/stylelint/commit/64f72fe1b73a2a645f6f2e75e9ede4dd90c2bccf#commitcomment-11168302

Currently we are leaving lodash out because we don't want to include unnecessary dependencies, which is a good approach.

lodash author John-David Dalton says there should be perf benefits to using lodash even within Node.js or io.js: https://twitter.com/jdalton/status/598511373849530368?cn=cmVwbHk%3D&refsrc=email

Because we are going to be running lots and lots of checks on sometimes lots and lots of lines of CSS, I'd say that performance is a major priority, and we should seriously consider any perf benefits we can get.

I'm opening this issue so that somebody at some point might run some benchmarks and compare some of the native looping, mapping, reducing, etc. that we are already doing against the same procedures with lodash functions. If lodash performance beats out the (babel-compiled) native code, then that (on top of other things I like about lodash) should incline us to use it.

**Comment by MoOx** [comment]
Good initiative :)

**Comment by jeddy3** [comment]
Agreed :)

**Comment by jeddy3** [comment]
> I'm opening this issue so that somebody at some point might run some benchmarks and compare some of the native looping, mapping, reducing, etc

I've updated the title and added the `status: pr welcome` label to reflect this.

**Comment by davidtheclark** [comment]
I'd say we got a good first draft of benchmarks in #1000. At least enough for us to measure individual rules experiment with performance-improving refactoring. So I'm gonna close.
