### ISSUE TITLE
New configuration loader

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#490]
Here's the spec:

- Look for `.stylelintrc`, `stylelint.config.js`, and `stylelint` properties in `package.json` files.
- Starting from `process.cwd()`, look for these files in `./ ../ ../../ ../../../` etc., all the way to `~` (user home directory), checking first for `stylelint` in `package.json`, second for `.stylelintrc`, third for `stylelint.config.js`.
- *Stop looking at the first one that is found*, and use that one as the config.
- Built-in YAML support for `.stylelintrc`.
- The config can have an extends property, whose value is a single string or an array of strings. Each string must be a lookup that require() would understand, so either:
  - A npm module name
  - An absolute path
  - A relative path, relative to the config file that is extending
- If config A extends config B, the result is config A's properties merged into config B, with config A taking priority.

The plan right now is to build these features into a standalone module and integrate that module into stylelint.

cc/ #442, #418

**Comment by davidtheclark** [comment]
This will cause a pretty low-impact breaking change, because the search-and-merge feature of rc will no longer be supported.

**Comment by davidtheclark** [comment]
Started https://github.com/davidtheclark/load-multiconfig

**Comment by davidtheclark** [comment]
Mission accomplished in #503

**Comment by jeddy3** [comment]
:tada: :)

**Comment by keithamus** [comment]
@davidtheclark awesome work on this! Thanks so much! Is it ready to use (released) yet? I'd love to take it for a spin!

**Comment by davidtheclark** [comment]
@keithamus You can try the `v3` branch. Let us know if you find problems!

**Comment by davidtheclark** [comment]
@keithamus v3 is now released.

**Comment by keithamus** [comment]
:tada: I've been working with it a bit - sadly atom-stylelint hasn't yet been updated but my package.json works well. Thanks for all of your efforts @davidtheclark :beers:
