### ISSUE TITLE
Add allowEmptyInput configuration object property

### ISSUE THREAD

**Issue by AkhmerovM** [stylelint/stylelint#4900]
> What is the problem you're trying to solve?

I think that write this flag in every command is not convenient.

> What solution would you like to see?

To fix this problem i recommend to create new rule.

**Comment by jeddy3** [comment]
@AkhmerovM Thanks for the request.

I believe this would fit into https://github.com/stylelint/stylelint/issues/4843#issuecomment-650137005, and would make sense alongside https://github.com/stylelint/stylelint/issues/3860.
