### ISSUE TITLE
Prettier 2.1 is confilct with stylelint

### ISSUE THREAD

**Issue by Mister-Hope** [stylelint/stylelint#4909]
Just see https://github.com/prettier/prettier/pull/8013. (And my issue https://github.com/prettier/prettier/issues/9101)

Prettier is moving the trailing semi of a style tag placing in a single line, and it causes conflict with the rule [declaration-block-trailing-semicolon](https://stylelint.io/user-guide/rules/declaration-block-trailing-semicolon#declaration-block-trailing-semicolon)

I am not sure whether removing it is better (My opinion is keeping it). But I am now failing linter CI.

Just hope that you can have a discussion and reach an agreement.

**Comment by ybiquitous** [comment]
@Mister-Hope Can you use [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier) to avoid the conflict?

**Comment by evilebottnawi** [comment]
You should disable stylelint stylistics rules if you want to use `prettier`, answer above
