### ISSUE TITLE
Add ignoreAtRules: [] to property-no-unknown

### ISSUE THREAD

**Issue by anneke** [stylelint/stylelint#4928]
> What is the problem you're trying to solve?

I would like me and my colleagues to be able to use edge-of-your-seat new features to CSS. Sometimes features are not known to Stylelint yet and it would be nice if developers wouldn't have to disable linting for a few lines in the meantime.

> What solution would you like to see?

I was thinking it might be useful to by default disable `property-no-unknown` linting within `@supports` blocks within the scss. Seeing as this marks a point where someone intends to progressive enhance their site with new features, I think it might be redundant to check it and have the developer disable bits of code manually. 

See for [explanation on `@supports` MDN website](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports)

**Comment by jeddy3** [comment]
@anneke Thanks for the request and for using the template.

> I was thinking it might be useful to by default disable property-no-unknown linting within `@supports` blocks

Rules are [strict by default, but can be made more permissive with options](https://stylelint.io/developer-guide/rules#write-the-rule). I think we'd want to maintain that convention here as the main purpose of this rule is the catch spelling mistakes.

For example, `displa` would be a violation in:

```
@supports (display: grid) {
  div {
    displa: grid;
  }
}
```

However, we can add an `ignoreAtRules` secondary option for users who want to change this behaviour.

I've labelled the issue as ready to implement. @anneke Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

I suggest using the existing [`ignoreSelectors` option](https://stylelint.io/user-guide/rules/property-no-unknown#ignoreselectors-regex-regex-string) as a blueprint.

**Comment by anneke** [comment]
Thanks Jeddy! I will definately look at this to see if I can contribute. Would be cool 💪
