### ISSUE TITLE
Fix `syntax` argument in CLI

### ISSUE THREAD

**Issue by karolis-adapt** [stylelint/stylelint#493]
`stylelint -s scss` works as expected, yet `stylelint --syntax scss` or `stylelint --syntax=scss` gets ignored and fails.

```
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
```
and
```
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
```
with
```
$ node_modules/stylelint/dist/cli.js --version
2.1.0
```

**Comment by davidtheclark** [comment]
It was a dumb bug. Thanks for bringing it to my attention! Should be fixed in 2.2.0, which I just released.
