### ISSUE TITLE
Stylelint not working for css-template

### ISSUE THREAD

**Issue by nsisodiya** [stylelint/stylelint#4951]
Stylelint is working fine for styled-components but not for css-template
how to quick fix? please help.
![image](https://user-images.githubusercontent.com/333455/94110611-8763c680-fe60-11ea-96b8-1c9a7cae45b2.png)
check Image above
Here is the source code.

```js
import React from 'react';
import css from 'css-template';
import styled from 'styled-components';

const Container = styled.div`
  position: relative;
  height: 50px;
  color: #ffffff;
  background: #282e40;
  display: flex;
  flex-direction: row;
  align-items: center;
`;

const styles = {
  container: css`
    position: relative;
    height: 50px;
    color: #ffffff;
    background: #282e40;
    display: flex;
    flex-direction: row;
    align-items: center;
  `
};
```

**Comment by jeddy3** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
