### ISSUE TITLE
Except empty line before pseudo classes and/or pseudo elements

### ISSUE THREAD

**Issue by AdrianFahrbach** [stylelint/stylelint#4952]
> What is the problem you're trying to solve?

The basic idea behind what I'm trying to achieve is having empty lines between single elements / logical blocks. If you got a CSS file with an headline, text-block and button, then I would like to have three blocks with empty lines between them. hover effects, after elements and slight variations on first/last children are part of that block and should't have empty lines before and after them.

> What solution would you like to see?

I want this to be illegal...

```
.headline {
    [...]
}

.text-block {
    [...]
}

.btn {
    margin: 1rem 0;
    [...]

    &:first-child {
        margin-top: 0;
        [...]
    }

    &:hover {
        [...]
    }
}
```

...and this to be legal, so that the button itself is one single block:

```
.headline {
    [...]
}

.text-block {
    [...]
}

.btn {
    margin: 1rem 0;
    [...]
    &:first-child {
        margin-top: 0;
        [...]
    }
    &:hover {
        [...]
    }
}
```

As far is I know, there is no way to do this, since in this case stylelint always wants empty lines before the pseudo classes.

**Comment by jeddy3** [comment]
You can use the [`except: ["inside-block"]`](https://stylelint.io/user-guide/rules/rule-empty-line-before#inside-block) secondary option to enforce:

```css
a {
}

b {
}

c {
    margin: 1rem 0;  
    &:first-child {
      margin-top: 0;
    }
    &:hover {
    }
}
```

[Demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYAdAdgXy1gRmlrplmEZilSgLZIBOA5gJabwoCM9MNKADAG4qWaigBk8AGbN6AZwAuAWjAALZgBsoFUVTpNWi+RAAO7QSOolRElRABuMetsvEQAGhCyAnpnlIAHgjgsrLu4BCY0oxBGJQo6CD0AK7qMLIJ7LGiCcmpijzG8l6K6qwwivgwkhDcGSgA2hbZyOoA7khesoo0KfLMJWUJbk3UWTrCIDD+YDCFdY1x4xPSckqYafIwUEMj4wmsssywFeoQYADWCbvUALrDizr7jJg1MPPXzUiSm-TKEDQ0GC+K4PUQ3a5WW4WEjYEDYIA).

This will apply to all nested rules regardless of the selector. If you want to change the behaviour depending on the selector, you'll need to [write a plugin](https://stylelint.io/developer-guide/plugins). With the plugin system you can enforce any  idiosyncratic pattern.
