### ISSUE TITLE
Nesting depth rule?

### ISSUE THREAD

**Issue by bjankord** [stylelint/stylelint#496]
Are any rules in stylelint that [warn against nesting selectors too deep](http://www.sitepoint.com/beware-selector-nesting-sass/)? Looking something similar to [scss-lint's nesting depth rules](https://github.com/brigade/scss-lint/blob/50dbcaf0119c1edde250c292c5717551f725fb23/lib/scss_lint/linter/nesting_depth.rb).

**Comment by davidtheclark** [comment]
Here you are: https://github.com/davidtheclark/stylelint-statement-max-nesting-depth

**Comment by bjankord** [comment]
Thanks David!
