### ISSUE TITLE
Migrate from dependabot-preview

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#4968]
We can now migrate from dependabot-preview, so we can experience the better integration between Dependabot and GitHub.
(we have migrated in the `stylelint/eslint-config-stylelint` repository. See stylelint/eslint-config-stylelint#90)

I think the following steps:

1. Click **Create config file** button on [dependabot.com](https://dependabot.com/) to create a migrate PR.
2. Edit the PR.
   - Delete [`.dependabot/config.yml`](https://github.com/stylelint/stylelint/blob/69d4896829be3f0acaa1aa4185a9c8f5a10484c6/.dependabot/config.yml)
   - Configure the settings.
   - See also [`.github/dependabot.yml`](https://github.com/stylelint/eslint-config-stylelint/blob/398de43a26cfefab51baf6f0cfe293767e1a9729/.github/dependabot.yml) in `eslint-config-stylelint`.
3. Merge the PR.
4. We will be able to view Dependabot logs or run updates manually on the [/network/updates](https://github.com/stylelint/stylelint/network/updates) page.

See also:
- https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
- https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-github-dependabot-version-updates

/cc @stylelint/owners

**Comment by hudochenkov** [comment]
Go ahead!

**Comment by ybiquitous** [comment]
@hudochenkov Thanks for the response. Now, PR #4969 is ready to review. 😃

**Comment by hudochenkov** [comment]
![Screen Shot 2020-10-10 at 20 20 45](https://user-images.githubusercontent.com/654597/95662286-15fd6680-0b36-11eb-949a-036d49062d3d.png)
