### ISSUE TITLE
Change plugins from object to array

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#497]
The intention behind having an object instead of an array was that you could then give whatever rule name you want to the function exported by the plugin. But that doesn't really work. The system expects the rule name in the config to match the rule name that is sent along with `report()` when there's a problem. So each plugin really should inform the user of what its rule name is --- which means we may as well have an array instead of an object.

Additionally, if we have an array and let each plugin tell its users about its name, we open the door to the possibility of loading plugin packs as single entries, e.g. `plugins: [ 'stylelint-sass-attack' ]` -- as long as that pack told the user all of the rules it exposes (just like ESLint plugins, I guess).

Any objections?

**Comment by jeddy3** [comment]
> Any objections?

None from me. Makes sense.
