### ISSUE TITLE
Remove nesting-block-opening-brace-newline/space-before?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#498]
Ref: https://github.com/stylelint/stylelint/issues/489#issuecomment-155576063

> Current nesting block rules look as if a curly brace is required, which is not in the spec…

The spec has moved on. Shall we remove these rules in `3.0.0`?

**Comment by davidtheclark** [comment]
Huh, interesting. Yes I'm fine with removing them.
