### ISSUE TITLE
Can update Stylelint recognize some CSS properties ?

### ISSUE THREAD

**Issue by dnknn** [stylelint/stylelint#5001]
`Stylelint` cannot recognize the following CSS properties:

### `overscroll-behavior:contain`
https://developers.google.com/web/updates/2017/11/overscroll-behavior
https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior
https://caniuse.com/#search=overscroll-behavior

<details>
<summary>Details</summary>

![208_08002557](https://user-images.githubusercontent.com/10995302/89666905-c28c5380-d90d-11ea-805d-ba64d95a1120.png)

</details>

---

- `CSS Scroll Snap` :  
　　https://caniuse.com/?search=CSS%20Scroll%20Snap
　　https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap
![2010_22225644](https://user-images.githubusercontent.com/10995302/96890118-e8aba380-14b9-11eb-8a85-fc8278311298.png)

 
 Containers Properties |   |    Children Properties
:---: |--- |--- |
`scroll-snap-type:`(supported) |  | `scroll-snap-align:`(supported)
` scroll-padding:` |  | ` scroll-margin:`
`scroll-padding-*:` |  | `scroll-margin-*:`
`scroll-snap-stop:` (Can used, but no effect)|  | 

<details>
<summary>details</summary>

The most commonly used example:
```
ul { scroll-snap-type: x | y | both  [ mandatory ]? ; }   /* `proximity` is default*/
li { scroll-snap-align: start | end | center ; }

　　/* or add snap offset */
ul {scroll-padding:5px; | scroll-padding-*: 5px }
li {scroll-margin:5px;  | scroll-margin-*: px }
```

about `scroll-snap-type:  proximity | mandatory ;`

![123](https://user-images.githubusercontent.com/10995302/95659052-2e2eaf00-0b51-11eb-9d50-7af2fdf69a25.gif)

about `scroll-snap-align: start | end | center ;`
![scroll-snap-align](https://user-images.githubusercontent.com/10995302/95658986-e576f600-0b50-11eb-89bf-32fa3bc4cf7b.gif)

</details>

Thanks!

**Comment by tophf** [comment]
@dnknn, this property is already supported in Stylelint long time ago. This issue is invalid, please close and delete it.

**Comment by dnknn** [comment]
I'm very sorry for causing trouble .... very sorry!
