### ISSUE TITLE
Add .scssm extension support for SCSS syntax

### ISSUE THREAD

**Issue by matthewwithanm** [stylelint/stylelint#5011]
> What is the problem you're trying to solve?

I'm working in a project that uses the extension "scssm" for scss modules. Because of that, stylelint is unable to infer the correct syntax and uses the default, which causes false errors and bad fixes. There doesn't seem to be any way to specify a custom syntax in the stylelintrc file to address this. Everything works fine from the CLI with `--syntax scss`, but this means that we need special configuration for IDE plugins.

> What solution would you like to see?

A way to map extensions to syntaxes in the stylelintrc file would solve this problem. #3128 seems like it would address the issue too but is a much broader scope.

Alternatively, the syntax "guessing" could be made looser so that "scssm" files used the scss syntax.

**Comment by jeddy3** [comment]
Thanks for the request and for using the template.

> #3128 seems like it would address the issue too but is a much broader scope.

Yes it would. There's also the [piece of work](https://github.com/stylelint/stylelint/issues/4843#issuecomment-650137005) to bring more options into the configuration object, including `syntax`. This is a narrower in scope and the precursor to #3128, but there's been no movement on it yet.

> Alternatively, the syntax "guessing" could be made looser so that "scssm" files used the scss syntax.

That'll be the quickest way. The change will need to made [upstream in our fork of postcss-syntax](https://github.com/stylelint/postcss-syntax/blob/0bca5a408f12891a622fd6149d8f23d3bd98df86/get-lang.js#L6).

**Comment by jeddy3** [comment]
Fixed by `overrides` and `customSyntax` options.
