### ISSUE TITLE
 scrapy and twisted installation problem on pycharm (python 3.9)

### ISSUE THREAD

**Issue by tamtam0280** [stylelint/stylelint#5021]
hello, I tried to install the scrapy package for python, you must first download twysted
however it returns me this error (of which I put only the end which seems important to me, the whole is in attachment)

I work on python 3.9
I don't understand the solution

I previously downloaded visual C ++

Can you help me please.

[Collecting Twisted.pdf](https://github.com/stylelint/stylelint/files/5483069/Collecting.Twisted.pdf)
    src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(8437): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\tamtam\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tamtam\\AppData\\Local\\Temp\\pycharm-packaging\\twisted\\setup.py'"'"'; __file__='"'"'C:\\Users\\tamtam\\AppData\\Local\\Temp\\pycharm-packaging\\twisted\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tamtam\AppData\Local\Temp\pip-record-9nu9h_21\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\tamtam\AppData\Local\Programs\Python\Python39\Include\Twisted' Check the logs for full command output.

**Comment by hudochenkov** [comment]
Wrong repository.
