### ISSUE TITLE
Disabling comments with descriptions don't disable the rule

### ISSUE THREAD

**Issue by geebru** [stylelint/stylelint#5033]
> Clearly describe the bug

While updating our shared monorepo with new stylelint rules and doing some fixes, I added a requirement to add descriptions to any disabling rules. The disabling itself works great in loud vs. silent styles, and in our SCSS files, but when I add a description to the disabling line, the disable stops working.

In searching I found a variety of bugs related to odd behaviors with single vs. multi line disables, certain rules not working, but no issue where the disabling straight up broke when a description was added.

> Which rule, if any, is the bug related to?

Not so much a rule as a feature - https://stylelint.io/user-guide/ignore-code

> What code is needed to reproduce the bug?

```scss
.rule-1 {
  color: #eee;
  background: #ddd;
}

.rule-2 {
  border-color: #FA0;
}

.rule-3 {
  // stylelint-disable-next-line
  color: #B4D;
}

.rule-4 {
  //stylelint-disable-next-line -- This one is okay.
  color: #E9E;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "color-hex-case": "lower"
  }
}
```

*The issue is not this specific rule. Any / all rule will do for this bug.*

> Which version of stylelint are you using?

13.7.2

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

VSC extension -  https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

Also confirmed via CLI: `stylelint -f verbose --rdd "disable-test.scss"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Used within SCSS files but the same issue exists if I switch the file to CSS.

> What did you expect to happen?

1. CLI should flag the disables without descriptions
2. Disables with _and_ without descriptions should both disable the rule, regardless

> What actually happened (e.g. what warnings or errors did you get)?

The reporter correctly flags those disables missing descriptions, but when a description is added, the disabling breaks.

```terminal
~/Desktop/quick-test
➜ stylelint -f verbose --rdd "disable-test.scss"

disable-test.scss
descriptionless disable: all, start line: 12, end line: 12

disable-test.scss
 7:17  ✖  Expected "#FA0" to be "#fa0"   color-hex-case

1 source checked
 C:\Users\gregb\Desktop\quick-test\disable-test.scss

1 problem found
 severity level "error": 1
  color-hex-case: 1
```

A potentially related / weird thing in the CLI output - the _line_ it's listing is the line from `.rule-4` but the actual SCSS it's talking about is from `.rule-2`. I would also expect the CLI output (based on the VSC extension) to list both issues in `.rule-2 and `.rule-4` but the CLI seems to be combining them into a singular failure somehow.

**Comment by jeddy3** [comment]
@geebru Thanks for the clear write-up and for using the template.

I'm unable to replicate this [using the demo](https://stylelint.io/demo#N4Igxg9gJgpiBcIB0AnArgGxgWgIwAJgAdAO330gwhXnwGIZGBuUgX1NNUxwCZDTylarToAxAIIAGFiXYlO6LNgDM-MvgD0G-AGcALgE8sGAJYk92KCZ0BDAEZKSMAB4XTTgRQhUa9AEIALAAiMnIK3NgBauRa+kYw7hZWtg44Tq7Y7jD42Nj4ACoAFtb4EE74JRAA1jYGSJ5CvnQAogCczaEgADQgOgbmNs4IvWA6Ot3gZQBmJgDmw8TqRCCKMDrLtIvk5MuN2IUu2GA2OjAb+MtUAO4wKMuecqwgrEA) or locally (using the VSCode extension and the CLI).

Unless I've misunderstood, it looks like the output is correct in your example:

```
7:17  ✖  Expected "#FA0" to be "#fa0"   color-hex-case
```

Which refers to this:

```scss
.rule-2 {
  border-color: #FA0;
}
```

Which is an uppercase hex colour without a disable comment.

Neither the following are producing violations:

```scss
.rule-3 {
  // stylelint-disable-next-line
  color: #B4D;
}

.rule-4 {
  //stylelint-disable-next-line -- This one is okay.
  color: #E9E;
}
```

I get the same result locally using `13.8.0`:

```
jeddy3@mac stylelint-test % npx stylelint "sources/scss/disabled.scss" -f verbose --rdd --config configs/disabled.json

sources/scss/disabled.scss
  7:17  ✖  Expected "#FA0" to be "#fa0"                color-hex-case                   
 11:3   ✖  Disable for "all" is missing a description  --report-descriptionless-disables

1 source checked
 /Users/jeddy3/Projects/stylelint-test/sources/scss/disabled.scss

2 problems found
 severity level "error": 2
  color-hex-case: 1
  --report-descriptionless-disables: 1
```

**Comment by geebru** [comment]
@jeddy3 I just gave it another test in my demo as well as in my actual project and now it's not happening for me either.

Maybe VSC got stuck in a weird intermediary version or conflict between the CLI version and my extension? Either way, it works in both places now (VSC/CLI) so I can close this one out. Sorry about that!
