### ISSUE TITLE
"stylelint **/*.{css,scss,less}" run failed when has 'global.scss' file

### ISSUE THREAD

**Issue by fyangstudio** [stylelint/stylelint#5039]
![image](https://user-images.githubusercontent.com/9896768/99224743-df47f980-2821-11eb-888d-cd29a33829c2.png)

> Clearly describe the bug

We use `npm run stylelint` check style files, the script is "stylelint **/*.{css,scss,less}".

When our project has `src/global.scss` things got strange, no scss file be found.

`**/*.{css,scss,less}` will become:
[ '`**/*.css`', '`**/*.scss`', '`**/*.less`' ]

when has `src/global.scss` became:
[ '`**/*.css`', '`src/global.scss`', '`**/*.less`' ]

> What stylelint configuration is needed to reproduce the bug?

e.g.

```js
// .stylelintrc.js
const { getStylelintConfig } = require('@iceworks/spec');

module.exports = getStylelintConfig('react');
```

> Which version of stylelint are you using?

e.g. `13.7.2`

**Comment by hudochenkov** [comment]
You need to put globs in quotes:

```
"stylelint": "stylelint \"**/*.css,**/*.scss,**/*.less\""
```

**Comment by fyangstudio** [comment]
Why this happen? 

-----
We use npm run stylelint check style files, the script is "stylelint **/*.{css,scss,less}".

When our project has src/global.scss things got strange, no scss file be found.

**/*.{css,scss,less} will become:
[ '**/*.css', '**/*.scss', '**/*.less' ]

when has src/global.scss became:
[ '**/*.css', 'src/global.scss', '**/*.less' ]

----

Don't you think this is a bug?  Some project runs well, some not。

**Comment by hudochenkov** [comment]
If you don't use quotes around glob, then your operating system takes care of glob parsing and resolution. If you use quotes, as I showed in previous message, then stylelint parses the glob. Try it, please.
