### ISSUE TITLE
Add the ability to ignore code to the validation

### ISSUE THREAD

**Issue by raynor85** [stylelint/stylelint#504]
Sometimes it is useful to ignore certain snippet of css from the validation, for example when you import a third part css into your main.css file.
I would suggest a syntax similar to jshint, someting like that:

/* jshint ignore:start */
/* jshint ignore:end */

**Comment by jeddy3** [comment]
Hello raynor. You can do this already. See [here](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#configuring-rules)

**Comment by raynor85** [comment]
Hi Richard. Thank you for the link, but it doesn't seem to work, and I know
why.

main.css

@import '../../bower_components/normalize.css/normalize.css';

If I put the code inside normalize.css it works, but if I put the code
inside main.css in this way


/* stylelint-disable */
@import '../../bower_components/normalize.css/normalize.css';
/* stylelint-enable */

It doesnt.

Any idea why?

Ruben

**Comment by jeddy3** [comment]
I'm not 100% sure what you're trying to achieve. Are you trying to lint normalise.css for some reason?

Are you using the CLI, the node API or the plugin API? If it's one of the latter two, can you paste your script for us to see please?

**Comment by raynor85** [comment]
I am using grunt.js, and main.scss is the entry point of all the postcss of
my application.

You can find my partial gruntfile attached (the one used for postcss which
loads stylelint) and you can also find main.scss.

Unluckily the gruntfile is only a partial, but it gives you the idea.

Ruben

**Comment by jeddy3** [comment]
You'll need to paste your grunt file, rather than attach it.

**Comment by raynor85** [comment]
/*global console */
var preprocessorsBeforeSprites = [
    require('postcss-import'),
    require('stylelint'),
    require('postcss-mixins'), // Must be set *before* simple-vars and
nested
    require('postcss-simple-vars'),
    require('postcss-color-function'),
    require('postcss-calc'),
    require('postcss-nested'),
    //require('postcss-simple-extend'), // Must be set *after* nested
    require('postcss-media-minmax'),
];

var preprocessorsAfterSprites = [
    require('postcss-pseudoelements'),
    require('postcss-focus'),
    require('postcss-fakeid'),
    //require('postcss-at2x'), // Not needed if using sprites
    require('autoprefixer')({browsers: 'last 2 versions, ie 8'}),
    require('css-mqpacker'),
    require('csswring'),
    require('postcss-reporter'),
    require('postcss-media-legacy')
];

var postCssSprites = require('postcss-sprites');

function getPostCssPreprocessors(name) {
    var spriteProcessor = postCssSprites({
        stylesheetPath: 'public/pcss/' + name,
        spritePath: 'public/images/' + name + '/sprite.png',
        retina: true, // also search for @2x filenames
        filterBy: function (image) {
            return !/\.svg$/gi.test(image.url);
        }
    });

    return
preprocessorsBeforeSprites.concat(spriteProcessor).concat(preprocessorsAfterSprites);
}

module.exports = {
    options: {
        map: {inline: false},
        failOnError: true
    },
    golden: {
        src: '<%= dirs.pcss %>/golden/main.scss',
        dest: '<%= dirs.css %>/golden.css',
        options: {
            processors: getPostCssPreprocessors('golden')
        }
    },
    parkers: {
        src: '<%= dirs.pcss %>/parkers/main.scss',
        dest: '<%= dirs.css %>/parkers.css',
        options: {
            processors: getPostCssPreprocessors('parkers')
        }
    },
    gumtree: {
        src: '<%= dirs.pcss %>/gumtree/main.scss',
        dest: '<%= dirs.css %>/gumtree.css',
        options: {
            processors: getPostCssPreprocessors('gumtree')
        }
    },
    confused: {
        src: '<%= dirs.pcss %>/confused/main.scss',
        dest: '<%= dirs.css %>/confused.css',
        options: {
            processors: getPostCssPreprocessors('confused')
        }
    },
    aa: {
        src: '<%= dirs.pcss %>/aa/main.scss',
        dest: '<%= dirs.css %>/aa.css',
        options: {
            processors: getPostCssPreprocessors('aa')
        }
    }
};

**Comment by jeddy3** [comment]
@davidtheclark Is the recommendation here to create a separate lint task, that would run against just his source files rather than anything in `node_modules`?

**Comment by jeddy3** [comment]
And avoid using `postcss-import` in that lint task.

**Comment by davidtheclark** [comment]
> Is the recommendation here to create a separate lint task, that would run against just his source files rather than anything in node_modules?

Yes, absolutely. 

I guess we could also create an `ignore` property in config where you could pass a glob ...

**Comment by raynor85** [comment]
Thanks good idea, i will do so.

Ruben

**Comment by jeddy3** [comment]
> I guess we could also create an ignore property in config where you could pass a glob ...

Cool. Shall we keep that in mind if more requests similar to this come up? Probably no need to implement it until then though :) As it really only as issue with `postcss-import`, right?, as won't `globby`'s negation, or gulp/grunt's glob's negation, help out normally?

> Thanks good idea, i will do so.

Good luck. Let us know if that doesn't work out for you.

**Comment by raynor85** [comment]
It works, thank you.

I have still two problems though. I
set "rule-non-nested-empty-line-before": [2, "always"] which works fine but:

1. I always get an error for the first line of my css (because there is no
space at the beginning of the rule at the start of the file). Is there a
way to avoid that?

/* it lint this line even if it is the start of the document */
foo1 { }
/* it works for this empty line */
foo2 { }


2. I doesn't apply to nested rules. For example in my post css:

.foo1 {
    .bar1 { }
     /* it doesn't lint this line */
     bar2 { }
}
/* it works for this empty line */
.foo2 {
    .bar1 { }
     /* it doesn't lint this line */
     bar2 { }
}

**Comment by jeddy3** [comment]
1. Separate issue here: https://github.com/stylelint/stylelint/issues/507
2. There's another rule for that:  https://github.com/stylelint/stylelint/blob/master/src/rules/rule-nested-empty-line-before/README.md
