### ISSUE TITLE
Attribute style in JSX leads to TypeError

### ISSUE THREAD

**Issue by SetRedEyes** [stylelint/stylelint#5057]
![TypeError](https://user-images.githubusercontent.com/43894497/100008719-7854b280-2dd6-11eb-8acc-20f8afb95362.png)

**Comment by jeddy3** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
