### ISSUE TITLE
Outputting a JSON report to an output file also makes the console output unredable

### ISSUE THREAD

**Issue by slikts** [stylelint/stylelint#5070]
stylelint version: 11.1.1

I'd like to use the `--formatter json` option together with `--output-file` while still preserving human readability for the console output. Currently, generating a JSON report means that it's not possible to understand the output just from the console, e.g., in a pipeline job.

**Comment by slikts** [comment]
A similar issue for ESLint: https://github.com/eslint/eslint/issues/10707

**Comment by jeddy3** [comment]
Thanks for the request. 

I'm closing, as with the ESLint issue, due to lack of interest. 

We can always revisit the issue if it receives more thumbs up.
