### ISSUE TITLE
CRLF linebreak where LF is expected

### ISSUE THREAD

**Issue by cotneit** [stylelint/stylelint#5087]
> Clearly describe the bug

Within a file without linebreaks (a file with a single @import rule for example) during autofix stylelint appends a CRLF linebreak instead of LF, even if `linebreaks: 'unix'` rule is set. 
Running `stylelint --fix` once more converts said line ending to LF, but only if `linebreaks: 'unix'` is set.

> Which rule, if any, is the bug related to?

`no-missing-end-of-source-newline`
`linebreaks`

> What code is needed to reproduce the bug?

```scss
@import 'module'
```

or any other one-line stylesheet:

```css
a { color: red; }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": ["stylelint-config-standard"],
}
```

> Which version of stylelint are you using?

13.8.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `npx stylelint src/scss/** --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, it does not. Works the same with all one-line css/scss stylesheets.

> What did you expect to happen?

I expected the linebreak to be LF instead of CRLF, especially if `linebreaks: 'unix'` is set.

> What actually happened (e.g. what warnings or errors did you get)?

I got CRLF linebreak.

**Comment by hudochenkov** [comment]
Are you using Windows?

This is my assumption: rule [`block-closing-brace-newline-after`](https://stylelint.io/user-guide/rules/block-closing-brace-newline-after) is [set to `always`](https://github.com/stylelint/stylelint-config-standard/blob/b6417ecef11196901f549856af8efb2ce3333a6f/index.js#L17) in `stylelint-config-standard`. In your example new line should be added. Stylelint uses the same line endings as the file or [fallbacks](https://github.com/stylelint/stylelint/blob/5601902f0d630d8b8f65e842445a678e9d95bebb/lib/lintPostcssResult.js#L38) to operating system line ending, which is CRLF for Windows. However, `linebreaks` rule should fix wrong line ending. Unfortunately, we run only one pass of fixes. So if `linebreaks` rule was run before `block-closing-brace-newline-after`, we would get situation you're describing. I think we have somewhere open ticket to make stylelint run multiple passes, but I can't find it.

**Comment by cotneit** [comment]
Yes, I'm using Windows. That's exactly what happens.

**Comment by ybiquitous** [comment]
Since the reported rules are a part of *stylistic* rules and deprecated, we will no longer fix them. See below:

- https://github.com/stylelint/stylelint/blob/16754b1dab7590238f9b842ebd25678f8204ae9d/docs/user-guide/rules.md#deprecated
- https://github.com/stylelint/stylelint/blob/16754b1dab7590238f9b842ebd25678f8204ae9d/docs/migration-guide/to-15.md#deprecated-stylistic-rules
