### ISSUE TITLE
Fix syntax inference with processors

### ISSUE THREAD

**Issue by yaymukund** [stylelint/stylelint#5117]
> Clearly describe the bug

If your config contains a processor, stylelint no longer uses `postcss-syntax` to infer the syntax and defaults to the css parser. The change appeared in version 13.4.0. It's not clear to me if it was an oversight or an intended change in behavior, but here's the relevant line:

 https://github.com/stylelint/stylelint/pull/4729/files#diff-5383a0a864da5a5ad24b4bae8f44c5574601bd4d145999b1ddc211d3900dd68bL89

I know that there's [discussion of deprecating the `processor` option](https://github.com/stylelint/stylelint/issues/3408), but in the meantime I think this could be better documented. I'm happy to submit a docs PR if that sounds good.

> Which rule, if any, is the bug related to?

Not related to a specific rule.

> What code is needed to reproduce the bug?

```scss
// In an scss file, add double slash comments.
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "processors": ["stylelint-processor-styled-components", {}]
}
```

> Which version of stylelint are you using?

13.4.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?
```bash
$ stylelint "**/*.scss" --config myconfig.json
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to scss syntax in my case, but in theory would apply to any syntax that a CSS parser would reject.

> What did you expect to happen?

Expected no warnings.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
Error: Unexpected '/'. Escaping special characters with \ may help.
  at ...styles.scss
```

Thank you for taking a look :)

**Comment by jeddy3** [comment]
@yaymukund Thanks for the clear report and for using the template.

I've dug into this and it looks like an oversight on my behalf in https://github.com/stylelint/stylelint/pull/4729/.

It's only autofix that is incompatible with processors, not custom syntaxes outright. We already have a check for that:

https://github.com/stylelint/stylelint/blob/a9db12a5f68c4351166cf80dfc7e6369cd2b8901/lib/getPostcssResult.js#L86-L97

I've labelled the issue as a bug and ready to implement.

**Comment by eMerzh** [comment]
hello @jeddy3 ...i just notice this issue too while willing to upgrade to v15 ...

is there some work around ? or plan?  

thanks a lot :)

**Comment by jeddy3** [comment]
@eMerzh You should use a custom syntax rather than processor. See [the migration guide](https://stylelint.io/migration-guide/to-15#removed-processors-configuration-property).

Thanks for drawing my attention to this issue. I'll close it as it's no longer relevant since we removed processors in `15.0.0`.
