### ISSUE TITLE
css color value invalid no rule

### ISSUE THREAD

**Issue by dengshenkk** [stylelint/stylelint#5120]
> Clearly describe the bug

Verify invalid value

> Which rule, if any, is the bug related to?

maybe color-no-invalid-hex

> What code is needed to reproduce the bug?

```css
a {
  color: 1;
}
```

> What stylelint configuration is needed to reproduce the bug?

```js
 stylelint.config.js
module.exports = {
  defaultSeverity: 'error',
  extends: 'stylelint-config-sass-guidelines', // 官方推荐
  rules: {
    'max-nesting-depth': 4,
    'color-no-invalid-hex': true, // 禁止使用无效的十六进制颜色
    'no-duplicate-selectors': true, // 禁止在声明块中使用重复的属性
    'property-no-unknown': true, // 禁止未知属性
    'unit-no-unknown': true, // 禁止未知属性
    'declaration-block-no-duplicate-properties': true, // 禁止在声明块中使用重复的属性。
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep']
      }
    ],
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['mixin', 'each', 'extend', 'content', 'include', 'for', 'function', 'return']
      }
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['export']
      }
    ],
    // 'scss/dollar-variable-pattern': /^\$([a-z])([a-z0-9])/
    'scss/dollar-variable-pattern': /\w/
  }
}

```

> Which version of stylelint are you using?
```json
 "stylelint": "^13.9.0",
 "stylelint-config-sass-guidelines": "^7.1.0"
```

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint "**/*.scss" --config stylelint.config.js`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

SCSS

> What did you expect to happen?

throw error

> What actually happened (e.g. what warnings or errors did you get)?

no error , no warning

**Comment by dengshenkk** [comment]
live demo https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYLIBsICd4oEYAmAZgG4UBfAHQDsQAaEAZwE9aAXJADwRbGbNG4CLQBmASwDmfYHRQpqIHAFdMMZkvxzaChUqQcAtKvVHaEIytoBrCwHdaWlB1UwG8vUoBG2MDfNLGABbAAcOVmdXFXdPfRFsHECjCVoANyRMCSgjAAsYbii3D10vEWDgmE5kkPDIhBdiuMUQWDBMJBxDCVEjXwh-ZKgVUKywQxgjUJwIUJgcDgkNZwBtZoVo2NK9NHWy6QscGFW9naVIWmYYMBVFtMnh0Ylxjg0jewkOXKMoCTExeZVYwZTAxTQgU4oAC6exo22hJTOrWuHS6i16-UGFiMzFyuC+SFoOWms3mESMEHuOBw2WWDU2iLKYlExjESGCEkwrCGIzGE3M7Lp+AZzSUzOqbI5XOSHMEqSkRikVXmzyMks53JsMFY9lwUCKMUZ8TE1jA6NoRnGmDAyVSIOyBq2SJNtDNPQtVpt2OszFCSDAMBypLRuEdRpaLrdvSytBgnUVXV+QOSFkuXCJnRyvyOUac9Ka8KUWtYYi6lR+KM63V62IkYXxhI4YdFIEqvyQarjHBURwF5e9tgceeFBaR2NgzADRPlOLmYD+z0+9RHhpb495z35hhS9YWJjUQsaq8LIHXTxekyu6jNuHBK6dZWxtXJzAgPYDzZPT+4rg7Vw5WCiHeR4PvEtbpJk2Q-G+viXh0uKWhAFRAsBIoniScwLNyA52BAjifkiV7XBwuBTFcKhQJY7RIIIyTWLh+H5sehEwNeJFJKE5GUUYrEhMmOFDgRZRETeSQRHMdGDnhw4geGSjMK4M7YrG9gxscTGgS01ifJJDEyWhSLbqYkzPtyal9DAzJHCc8LxJk9hIKw4LhgoOg7EiBQBuENnue5Ph+DY6i0UgYivEkzCCn2kyYoFGjOZCxoSDgCnmBorz6hCtl6FCLn7FIhzqfgaxZYZoXzIhyGcEokIwllcI7DlLZGQeUWWjRhUtNg9jzEocnIMYxmtb6-qTCFYXOAYmAOU5OLymYam9U1A0tf+zwQNgFoqeZY09Q0k3TfFJ4xZa2DMDO3hdAGPFhOS5neJZuAdUosZUotR0BSdEBnbQCoXSNqWqako1lTgE3IFNjmHUix3tF952XZMW1AxZVlPeDB1GMEaiLEYC2MC2MOnfD-3DVd92o2D9mQ7NP3zUDb3Qx9pK0MTV1I7GRg7aDe3o9TWOYDjeN9cdzOs5efpXVzlMQzN31SHTsYM2UItzCzP19Ajs7-eTj3SwdSvxIBST5NwbVXGDXW7X1Rt5AUuNVFIXxg7i+IGy0kCVcYpm48jOvWQ0xW+ftkNu65kJKJ5MDeQHCURklKWxgpgbVSVCLhyABy6zHqfxAprDqDGxge8EhJQOCNWws0jUnsXyb2LknwaBLkypGdsB6yH+M1yoClIVMMyYeS3t3Q9-tFXswdOaHuypxH3BeU22e+aVYWWj3JHBP3wYRNPzrx8YifpSny9p7PGf5Vn485y0XMVZUVVdyf8St7SNPy5Md0Bcfy+1b59XZX1NoqJqwWm8ISBUpNgbjR5i9K2LYgFVnNH0cBWsyajzRlTKej8ygILRO6PoH1VqAU2jAQGHMpY80wcwTG2MJA+0Vtg+IuCQEEIGAEIh61eiQM5iDDuss5of3powlozCkHHQ4RtVB0V0Fg1gdzQBlY8EYkIQI+hkwS6m1Ee6YCBAFHUSUaAj6v5OQzgkaIPhUMcGKJYcQgG21eGUJltQ-mgshF6OAUg2x3CKH4EntQuWCt1LuMQfgrxzcUaXxaHIt2SgtG9GHr7GRS8-K8ywblNyy854Lx8k-AwIMKz6JAbvJk+9UpJwyjVXKz8L5jxQIHXJyB8m1wflU-YlxX4BMERzGK39fK-3cv-BQ1dnSmk8UhEudjkY+Jvk4mhAs6FCxbJGMZFQ-zhOmX4t+gSYkgGWaE8ZaztZJN8aeGAr1hFilGfgjR106hqOAgABj6nsmskVxjmx5pbeRSyrm9D9EcTg+QrjUPZi3dp7dHEYxcQstxPzXRIP+UCIFbxuEvwhScuRWyulBLhbmd4DdXjeIcScqhOzUiwE4EUhoRA+rqB+l8IwAAveYlgByfCEvEG5CTE7OF0S2NsEgOwAkMD2SYYT-obNSZYzlgZBWdhFb2cVaCKYwLOXAk8AqhVdlFa1d5aMvk7M1fK7svZEWAo0Ci8JaK0bRIua2WVWqFWTC6D9SYwZDCkSJdAklTjDUOuNTql1SoKSYQ9eFcJfsMG+rtUagAjjEHAZkJApWLh2UFPDvUzKhbQtRfr2xGHjfMJNKaDlSIzbtH1GNOm5pjf6wtiafYltWWWyNsi1XfK-EEda+LG6QI5VEywso5Y8SJBSMQOI3w4DZqQvG94+q0BUMEe6SR1BIF+OrZlMwLE7IXUu8q2JjExgVJur6-alAYTJNyPVFs8LqqRINbl0iVVXyDlKuZriGHpPTpHaOL6GmSGSgfNKydMon2GZk8+BUcknzyavZpi8K51Srn1ES7FOYcEUt4W40VLpag4P4q14KbXtp2ah0ihhMPYZDfMMNZbJW2pQ7xUS6HKOvGoyGcNRzn1RJI3asjSQPbeFSLRr1Fas2d0Y2xUignhNoe4a2yFEmWz8YrJOKoUBGwVSE7QWjykuHNzPSwJjaGshNomemyVpK+PGdIqZoupb5PHJ4+cyTxFSJcpukmnlDQnnKZsxxLiVF4LUOvZ829HaWJSYCzACiQWaLULNV8C1BH-rWrbS5vzUWyIxe4rxe+Rd2o3u6hF4S-nsuxZ4uofLiFJEWC4OaMGlEVCwVI2V8SYrCtheKzs7SBWPknINXakEMQjDFl1DgHIoWBvhZ2cNwRZm00zqmcS8TM1oU1r6nNxt9nm2ie5pW6m1bFkni23Zu+hzlWROerxzbmQRtnY83ctSjzPBwkoCASgQA

**Comment by jeddy3** [comment]
@dengshenkk Thanks for the report and for using the template.

The `color-no-invalid-hex` will catch:

```css
a {
  color: #1;
}
```

But not:

```css
a {
  color: 1;
}
```

You'll need to use the [`stylelint-csstree-validator` plugin](https://github.com/csstree/stylelint-validator) to do that as colours [can be a lot of things](https://csstree.github.io/docs/syntax/#Type:color) in CSS.
