### ISSUE TITLE
Apply .scss linting rules to .css files

### ISSUE THREAD

**Issue by yusuphgammut** [stylelint/stylelint#5121]
Hi people. I'm using postcss in my next.js project and decided to use [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) plugin to add a little more felxibility to my workflow. I also installed [stylelint-config-sass-guidelines](https://github.com/bjankord/stylelint-config-sass-guidelines) to add support for that scss-like syntax.

However, the linter is still highlighting the `$var` variables as errors. If I change the extension of my files from `.css` to `.scss` the error highlighting goes away. I found in [this issue](https://github.com/kristerkari/stylelint-scss/issues/352) that the [stylelint-scss](https://github.com/kristerkari/stylelint-scss) plugin doesn't control to which files its syntax rules are applied, but Stylelint does.

My question is: is there a way to tell Stylelint to apply sass rules to css? or could this be related more to the vscode plugin than to styleint itself? I have no problem moving to scss but I would like to know the answer to those questions if possible.

My current `.stylelintrc.js` file contains this:

```
module.exports = {
    extends: [
        'stylelint-config-standard',
        'stylelint-config-sass-guidelines',
    ],
    plugins: [
        'stylelint-order',
    ],
    rules: {
        'indentation': 'tab',
    },
};
```

Thanks in advance.

**Comment by jeddy3** [comment]
> However, the linter is still highlighting the $var variables as errors.

What's the error?

The `$var`s added by the postcss-simple-vars plugin can be understood by the default CSS parser. You shouldn't need to change the extension to `.scss`.

**Comment by yusuphgammut** [comment]
These are the errors:

<img width="689" alt="Screen Shot 2021-02-01 at 13 14 21" src="https://user-images.githubusercontent.com/12637787/106500148-79b5f180-648f-11eb-9876-3890303cc79b.png">
<img width="804" alt="Screen Shot 2021-02-01 at 13 14 37" src="https://user-images.githubusercontent.com/12637787/106500153-7b7fb500-648f-11eb-803a-1f518587ed83.png">

I'm using Neovim with coc.nvim and coc-stylelint.

**Comment by jeddy3** [comment]
Those errors don't look like they are related to stylelint. It could be the CSS linter built into your editor. You'll probably want to turn that off if your using stylelint.

You can run stylelint on the CLI to check that isn't stylelint.

```console
npx stylelint "**/*.css"
```

---

Two FYIs:

1. All the PostCSS plugins are compatible with the standard CSS parser, so you can use them with stylelint using a `.css` extension.
2. You'll probably want to use [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) rather than introduce non-standard dollar variables if you're writing CSS.

**Comment by yusuphgammut** [comment]
Thanks @jeddy3, you were right. I added the following code to my `coc-settings.json` file as recommended in the [vscode-stylint page](https://github.com/stylelint/vscode-stylelint) (coc.vim is a port of vscode language servers to Vim), and that did the trick.

```
"css.validate": false,
"less.validate": false,
"scss.validate": false
```

I'll consider only using custom properties only. I wanted to try simple variables use then inside `@media` declarations, which is not supported by custom properties yet.

**Comment by jeddy3** [comment]
> I added the following code to my coc-settings.json file as recommended in the vscode-stylelint page (coc.vim is a port of vscode language servers to Vim), and that did the trick.

Good stuff.

> I wanted to try simple variables inside `@media` declarations, which is not supported by custom properties yet.

You may want to look into the [postcss custom media plugin](https://github.com/postcss/postcss-custom-media). Using dollar variables generally make things harder, as you saw with it tripping up the linter built into VS Code, so you're best avoiding them if you can.
