### ISSUE TITLE
Typescript template literal types break stylelint

### ISSUE THREAD

**Issue by mrThomasTeller** [stylelint/stylelint#5134]
Given such typescript (typescript version 4.1.2) code:

```typescript
export const strConcat = <A extends string, B extends string>(a: A, b: B) => (a + b) as `${A}${B}`;
```

Try to lint this file and you will get the error:

`Unexpected token`

It seems that stylelint doesn't work with new "Typescript template literal types" feature (https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)

**Comment by mrThomasTeller** [comment]
As a temporary workaround, I added the file which caused such error to the ignoreFiles section of .stylelintrc

**Comment by jeddy3** [comment]
@mrThomasTeller Thanks for the report.

I'm unable to replicate this [using the demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICWBbADhATgFwAQGdsBPAGxilwDNMIVcAdEQ08gWknQgDsYvt9GAbnpcRMAB4YcuSF0IFsmAMLcwAQzwBeXAB4AgrgnZeUfAsxIuAcwA0uAEKHxxrqfOWrAPgAUa+Lj07ACN-ewBKXE1PXF9cAGpcIIi1MwADABJgPQBfTPts1MEQGyYiPjVxBHB8fFZLVgArfGLwbkokKyrgEVwGEEwAVzIBBFxurl7exg1WQbJWLghWAa4Aa0WAd1FRxQGYGx7JxiCSCDBVhaWYdGJGf139w6nW08xLuq4ANzUSJChWAAWEjuuAeBwmR1aKBQvGw72uaFuO0Gjwhz1gYBIakwGiQ3FYJzOF0WrCgAzQv3UxlYaBoaBgOCQMBG-gA2k9JmCOb1xpM+X0OotMDAQey0fznrJ8DAwANsEhPjBSeTKRpmawNkhsADSUhKJQGbDWN8SHsRtzJgBdC3ZDmW8F8xgYrE4+X4wnnd74AFYbVqVw0ukM4isCCKzAWWAs0Eoh2QyjcOGUNQoJAkIjvMkUpBUpVcFPMkFc8WMBN8VjJ1Pp96pmoeVhWXgMnMVlNpjOrGBEDZYKBF2Mc0srMBurjsH5gd6WE1-ft7OPPSjD0fjkiTkkrfBoNRgNgQemurBz1GOkBLrgjvFj348bENnFQJnlkmLOTYf1QbH-R-Cy-cY8Ln0nZENQBakjKLq4viJKoFI758ABg4gDCj5qBWMAaAMwoLGBG5rJs2z3AOJYgCSUa7q49ZbjKeo5lqRCISRZEqjmaqsDMsG+rMQyFsi85Icx2a5qw0pkCOWDRsWp4kgiIb4BAWG7ox0lXM4OIidcOYQKccjKZCMFfD8fykgpJxKvgWLeuwtAwnwknEaetL7sGGZ4esEBbHpzyiTK2BYDS0oDFASyYiktRuQRXl9D54lvGggXBawMBkLZcIRR5hExvxJExX5bzEPS7wrO5nl8SekKEBY1jvDwGw3iKZWAYwKxakV+EZVF0xwnMSqyRm9UEjACbCqKFrTCQGxqEQIyATyFrPBIu6IqN4oSscpznMMtRqJQxhvPguFgR6qxbYws38qWSCYIQCzMsYfYgPNuD2k9jCClgDVsk9zw7Xt1nQrCjBPdaq24La4ovSRMw9ThMLjtKIKMKcGwMmdSHQzxsPmduu7sbtqOjONk3TSJHjzPVaNQ91mPSqmkA6bddWWEqv0E-4RNTTNSHHewpz4PWQQ4rjfWsANQRDR9iOkTA4aU6ePOYhA-PVYLO55jATM8Hje1Sz8xNcyRCt8wLQvq5rSri8Nn19HrnOsCgQzyqLzNy5CRtKybasiTjFsSyNhMgLbJPK1Y5Mu8U3MbRczlcJ7uO1QNrOYLrE12w7JBOxTEeG1Hob0rHKum97XtJyn+uk9YYc8K7zw8zHcfY17luSwHQcG6e9P+UC4jw9bSMeQTTUvF3Eii7wVjalL3q+jXfQcKlSU3P1zODVbK1rYHqfTbPc2gwt4hLdg68SvGV03TwhDkEDe-Pedzzvf7X0395xBkDecLzx+5o3yDErg3ykMO42SNBsAEWpmQ+w+PzWAZdOaz0YLKQgtBAzORwBmEWYs-bWzFBvNuO8xivRAItGAy1Rg4JPj9fGbxEF+RQCgg8SI76n2umlO6V9Ho-yYW9KwQpsHfRtlQ-6qV8GnksNA8yZMlRiyjtfChv9+T-ytEPZ02IoJjiCP6KwxdcalwDjwWW2dTwqNdFeAkmjtG+zXq3Le7dITGLUQSXOtMtIMwTivXR7NN7l3TpncOyiIKqJXDzZxncxxbhLlQ2BwdJHO2roYuxASTHuicZpUJFjV4t08foweSF7FBKcTEgaKAKjgVCkk3SowACM-iykOJ5ooNQaYqKpO0v+ax+t4EgDyaYtJbitYeJtjY+2jskCxIajUyCK40nhJ0ZE9pdsQ5V3GbkxJDjpmQObo-Po2Tk7xPRKslcGCV6bL4aDDm289mTF5CfRgxDSFPwoZQv63S2lMMXGfVhl8HrAy4cgHhmTcDkIodMQR89AaXI3mIv4EjK5SOOTIjhcibR2iHueP8Y5P6M0TnMzxbdhkZ1GVnVFy4ek2TQjMlmOLBnl0WXCuJxKLxTLJekk5UsdmdLRSuYpPcjkXxBAABgZeirGvcpbIxySRTlpjtzCj4ECaU4UNYDShTA+ZJMfGEr8UhKV+IZWwnleqClUDoVsplgyCuoc6XLMlSS-EoDwFGoGec2x99XCwjUSCAATEPMg1htSsAAF4MiWHhLUnVkIlN5bxfw1SkIoSQGhA0mFsLrIiTrNVLq+jxsTRhbAWElSptxqyvRZrdlD2zehZNeYwLqARgHcVZa43kATZWvN2E9VyuZIayBKq+7SwMeW5tOaq2zE0UqVBGh-KOqpc6zpFak1tqVDiaw46DyTv2hsrBUTM2MArQARz2JgZeN1MV9Mpem3FQyNVjLnUO1gB6GTHo-sy6dF7qULMKVqki+7D1PqEeSzdVismls6TJbSGowHGApeGkktYQ5JQDBASgIkFKYHjkq8ORFsrSQGCgcWbwyBqEfNVINNBt2gdw-h94DSmkkeDfZbDkInIMIzLWvtDbOkwyjRkrZQLIR4uvUSi01yN53KPmQ-hl0WG3S+bIk+gCbl-N4cfYFgdQXAIQoi+TyKIZD1yv5DQigkBBDlBbIWnZ+DpN7aagdSF9NvEMxYEz1IJ15XSU6-tErTz2fYtgIzznV0MnXSyrdJbbM5WSr5fyHAgiWGC6+tm76Ll6ci7Ff6sX8xuaNcWy9HTLmMB8+REw-pn14bi25l8+JoONTs6ltzvwT3MrPdrRLs78tMDq-5BrpXikhaA9skD7WfPcsXoiZefLRiCtq2JNz8UYBBRCpZWobGxUD0bRFmb-k5sLd5mFGk2J9VdtqEa6zYWvMVU63FBKVwUpGhW-WtbnSfPbcSpFhevSIDvlHFLYKAwzJPcu6wAqBaUjsce+1lqH9QerZRut08Jo9isGAj2TA-x7ueI4+1hHcLGvQjQs1jzAmRk3qxz8RH3X-3uZnV4j9sKSdD2x87XHvXsuheA+F+HZOcdwhG1G6M-LDjg2yCAbIQA).

Please can you create a new issue using the [bug template](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REPORT_A_BUG.md), and reference a reproducible repo or demo.

Having all the details in the bug template will help us clearly understand the issue and help you.
