### ISSUE TITLE
Add certain CLI options to .stylelintrc.json

### ISSUE THREAD

**Issue by thernstig** [stylelint/stylelint#5141]
> What is the problem you're trying to solve?

The developers on my team use different editors. There are some options that can be run with the CLI like `--report-needless-disables` (https://stylelint.io/user-guide/usage/options#reportneedlessdisables).

> Produce a report to clean up your codebase, keeping only the `stylelint-disable` comments that serve a purpose.

But editors such as VS Code cannot report these errors as there is no configuration for them. We don't run the CLI during development, only during CI. This means users can accidentally add comments without descriptions without it being reported as a failure in their editor. This is problematic as we lose time as developers only first find these errors in CI where we use `--report-needless-disables`.

> What solution would you like to see?

I would like to enforce this at config level i.e. in `.stylelintrc.json`. Same goes for options `reportInvalidScopeDisables` and `reportDescriptionlessDisables`.

**Comment by hudochenkov** [comment]
You're not going to believe. In the next stylelint release: https://github.com/stylelint/stylelint/blame/bcc4f9cb775c40b852051e8a7e1c8456c85f268a/CHANGELOG.md#L7

**Comment by jeddy3** [comment]
@thernstig Thanks for the request and for using the template.

As @hudochenkov said, this is coming in the next release. The plan is to move all the options to the configuration object. I think I'll create an umbrella issue for that so it's more visible.
