### ISSUE TITLE
Possible Errors Link etc on Getting Started Page does not bring the topic into view.

### ISSUE THREAD

**Issue by bcowgill** [stylelint/stylelint#5174]
> Clearly describe the documentation issue

The link to Possible Errors (and possibly others) is incorrect on the Getting Started Page
It takes you to the page but does not bring the section heading into view.

> What solution would you like to see?

On this page:
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/get-started.md
The Possible Errors link:
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules/list.md#possible-errors
Looks like it should be:
https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules/list.md#user-content-possible-errors

And should probably test all the other links on the page for the same problem.

**Comment by jeddy3** [comment]
@bcowgill Thanks for the report and for using the template.

That's strange. I can't reproduce this. The anchors are just the content of the heading turned into slugs, which are then checked by [remark](https://github.com/remarkjs/remark-validate-links). I'm not sure where the `user-content` part of the anchor may be coming from.

Do you experience the same issue on the stylelint website?:
https://stylelint.io/user-guide/get-started

**Comment by bcowgill** [comment]
I do not experience the same problem using the links on the website https://stylelint.io/user-guide/get-started only when I go from the github page with the readme on it.

**Comment by jeddy3** [comment]
Thanks for letting us know. GitHub is maybe rolling something out where they append `user-content` to anchors within markdown files. I suggest we wait to see what happens, as this currently breaks existing anchors on GitHub. If anyone else encounters this issue, please thumb up the top post so we can track how prevalent it is.
