### ISSUE TITLE
Add support for dependencies to custom formatter flag

### ISSUE THREAD

**Issue by ThornWalli** [stylelint/stylelint#5192]
Current implementation, although using `require`, only provides relative or absolute file path.

https://github.com/stylelint/stylelint/blob/16ae9e4537975d1d755e430a813a74ddfb681cde/lib/cli.js#L348-L354

So it is not possible to import a formatter as dependency correctly.

**Not Correct** `stylelint "src/**/*.css" --custom-formatter node_modules/dependency/index.js`

**Correct** `stylelint "src/**/*.css" --custom-formatter dependency`

Topic was already mentioned here in the past. https://github.com/stylelint/stylelint/issues/2449

PR: #5193

**Comment by ybiquitous** [comment]
I forgot about this issue, but this has been implemented with PR #7343 unintentionally.

### Confirmation

Using [`stylelint-codeframe-formatter`](https://www.npmjs.com/package/stylelint-codeframe-formatter).

`package.json`:

```json
{
  "type": "module",
  "dependencies": {
    "stylelint": "^16.2.0",
    "stylelint-codeframe-formatter": "^1.2.0"
  }
}
```

`stylelint.config.js`:

```js
export default {
	rules: {
		'block-no-empty': true
	}
};
```

`test.css`:

```css
a {}
```

Run:

```sh-session
$ npm i

$ npx stylelint "*.css" --custom-formatter=stylelint-codeframe-formatter
  test.css

  ✖ Unexpected empty block (block-no-empty) at test.css:1:3
> 1 | a {}
    |   ^^
  2 |

  1 error
```

**Comment by Mouvedia** [comment]
We will have to edit the CHANGELOG retroactively to add that enhancement.

**Comment by ybiquitous** [comment]
> We will have to edit the CHANGELOG retroactively to add that enhancement.

We had it already:
https://github.com/stylelint/stylelint/blob/34cdc97149234063c94301cd64ceb378b20a07bf/CHANGELOG.md?plain=1#L47

**Comment by Mouvedia** [comment]
I meant a separate line that states that we now support the package name as an argument to `--custom-formatter`.

**Comment by ybiquitous** [comment]
Ah, do you mean we should add an entry to the previous version (16.0.0) in CHANGELOG.md?
https://github.com/stylelint/stylelint/blob/34cdc97149234063c94301cd64ceb378b20a07bf/CHANGELOG.md?plain=1#L31

**Comment by Mouvedia** [comment]
Yes that's what I meant by "retroactively".
