### ISSUE TITLE
Clarify "never" option for whitespace rules

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#52]
Given a rule like `declaration-bang-space` --- so far I've been treating "never" to mean: "*no* whitespace in front of the bang". Because I'm thinking that if you want there to be *no* space in front of the !, you're also not going to want there to be a tab or newline or some other whitespace.

One implication of that treatment that I wanted to run by everybody is that "never" means the same, then, whether it's for a space rule or a newline rule. I was working on `block-opening-brace-newline`, and realized that the tests for its "never" would be the same as for `block-opening-brace-space`.

So does it seem that that's the right approach to everybody? Or should we instead make "never" mean "not *this particular* whitespace --- but other whitespaces we don't know.*

**Comment by davidtheclark** [comment]
The more I think about it, the more I believe that are current approach is probably fine. After all, what reasonable situation might arise that a person *wouldn't* be able to support? If user wants space before and newline after, that's possible by passing `{ before: "always" }` to the `-space` rule (leaving out `after` option) and `{ after: "always" }` to `-newline` (leaving out the `before` option). If weird user wants a tab before and newline after, that's possible by just leaving out the `before` option for `-newline`.

Anybody see any problems I'm missing?

**Comment by jeddy3** [comment]
> Anybody see any problems I'm missing?

Nothing springs to mind, but it's a tough one to think through. I also think, like you, we should carry on implementing the current approach and deal then with any hurdles if they come.

**Comment by MoOx** [comment]
> So does it seem that that's the right approach to everybody?

Works for me.

**Comment by davidtheclark** [comment]
Great.
