### ISSUE TITLE
Add maxWarnings as a configuration option

### ISSUE THREAD

**Issue by thernstig** [stylelint/stylelint#5208]
> What is the problem you're trying to solve?

I want all warnings to be considered errors when using editors such as VS Code. Errors in editors are often handled differently than warnings. There is no way for me to enforce all warnings to be considered errors as the only flag today is the one that we can use via CLI i.e. `maxWarnings`.

> What solution would you like to see?

A new configuration option for `maxWarnings` which today only exists as [an option](https://stylelint.io/user-guide/usage/options#maxwarnings). if I could add it to the stylelint config file it could be enforced better for all situations.

**Comment by jeddy3** [comment]
@thernstig Thanks for the request and for using the template.

We should make the option available in the configuration. I've added the issue to https://github.com/stylelint/stylelint/issues/5142.

However, I'm not sure that's what you want. The `maxWarning` option [simply sets the CLI exit code to 2 if the quantity is exceeded](https://stylelint.io/user-guide/usage/options#maxwarnings). I don't think this has any effect in an editor like Vs Code.

Errors are errors and warnings are warnings, i.e. warnings can't be considered errors. You'll need to use the [`severity`](https://stylelint.io/user-guide/configure#severity) and [`defaultSeverity`](https://stylelint.io/user-guide/configure#defaultseverity) configuration options if you want rules to report their violations as errors.

**Comment by thernstig** [comment]
@jeddy3 that is a valid point regarding the exit code. I think `defaultSeverity` is maybe what I want then. I want all `warnings` to be considered `errors` by stylelint. Then editors (e.g. VS Code) might highligh errors differently than warnings.

Since we do not allow any warnings at all, there is no point to have the level of `warning`. I.e. in CI we do use the  `maxWarnings=0` which in effect to me means it is better to flag them as errors also e.g. when editing code.

**Comment by jeddy3** [comment]
>  I want all warnings to be considered errors by stylelint. Then editors (e.g. VS Code) might highligh errors differently than warnings.

The rules in stylelint report _violations_. These _violations_ can either have the severity of _warning_ or _error_. So yes, you'll need to set the `severity to `error` if you want VS Code to treat all violations consistently as errors.

**Comment by thernstig** [comment]
That means I have to do that per rule right? So if I extend a common config, it means I have to override all the rules in there?

But if it was possible to force all _violations_ to have severity _error_ without override per rule, I would use it. I suppose this is not a huge deal, and I am thus closing this. Thanks for the support @jeddy3 !
