### ISSUE TITLE
Add autofix to selector-attribute-quotes

### ISSUE THREAD

**Issue by ProtonGravity** [stylelint/stylelint#5211]
I have tried to fix some issues in CSS file together with option --fix, but it don't fix problems only reports about errors.

> Clearly describe the bug

For Example: 

I have the simplest rule file:

{
  "rules": {
"selector-attribute-quotes": "always",
"string-quotes": "double"
  }
}

and run this in the terminal:

stylelint "**/*.css" --fix

and receive this:

 72:12  ×  Expected quotes around "text"   selector-attribute-quotes

but this not fix anything

> Which rule, if any, is the bug related to?

e.g. selector-attribute-quotes

> Which version of stylelint are you using?

13.12.0

OS : WINDOWS 10

> What did you expect to happen?

I expected to fix this and of course inform about a problem in the terminal (what it does).

Please inform me if I am doing something wrongly ?

I also must say that sometimes stylelint fix problems, for example with 
plugin stylelint-order it is working.

**Comment by jeddy3** [comment]
@ProtonGravity Thanks for the report and for using the template.

The `selector-attribute-quotes` isn't autofixable yet. Autofixable rules are labelled with "(Autofixable)" in [the list of rules](https://stylelint.io/user-guide/rules/list).

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add autofix to a rule](https://stylelint.io/developer-guide/rules#add-autofix) in the Developer guide.

Let's autofix with double quotes. The `string-quotes` rule can then switch them to single if neccessary.
