### ISSUE TITLE
Invalid Option Error thrown with "no-duplicate-selectors" rule.

### ISSUE THREAD

**Issue by james0r** [stylelint/stylelint#5221]
> Clearly describe the bug

Invalid Option Error thrown when using `"no-duplicate-selectors": false` rule even though the rule seems to take effect on my SCSS with stylelint-scss plugin added.

> Which rule, if any, is the bug related to?

no-duplicate-selectors

> What code is needed to reproduce the bug?

```module.exports = {
  extends: "stylelint-config-recommended",
  plugins: [
    /**
     * add plugins
     * docs: https://stylelint.io/user-guide/configure#plugins
     */
    'stylelint-scss'
  ],
  ignoreFiles: [
    /**
     * ignore certain files
     * docs: https://stylelint.io/user-guide/configure#ignorefiles
     */
    // 'my-file.css',
    // '**/my-directory/*.css'
  ],
  rules: {
    /**
     * add custom rules
     * docs: https://stylelint.io/user-guide/rules/list
     */
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    "no-empty-source": false,
    "no-descending-specificity": null,
    "no-duplicate-selectors": false
  },
};

```

> What stylelint configuration is needed to reproduce the bug?

See above.

> Which version of stylelint are you using?

13.10.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

Webpack plugin

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, SCSS

> What did you expect to happen?

Duplicate selectors are ignored and no errors to stdout.

> What actually happened (e.g. what warnings or errors did you get)?

```ERROR in Invalid Option: Unexpected option value "false" for rule "no-duplicate-selectors"
Invalid Option: Unexpected option value "false" for rule "no-empty-source"
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

To [disable a rule](https://stylelint.io/user-guide/configure#disable-errors) use `null`, and not `false`.

**Comment by james0r** [comment]
Thanks for your reply.

This would be a helpful addition to the detail page for this rule and perhaps others.

https://stylelint.io/user-guide/rules/no-duplicate-selectors

I do not see the null value indicated anywhere there.

To add to the confusion the nested option takes 'false'.
