### ISSUE TITLE
Fix false positives for attrs in property-no-unknown

### ISSUE THREAD

**Issue by kyleknighted** [stylelint/stylelint#5235]
> Clearly describe the bug

Seemingly related to #3710

`Unexpected unknown property "***" (property-no-unknown)` while using `attrs()` from styled-components

> Which rule, if any, is the bug related to?

`property-no-unknown`

> What code is needed to reproduce the bug?

[Stylelint Demo Page Reproduction](https://stylelint.io/demo#N4Igxg9gJgpiBc4IDsDOAXABAFQgczwBsZMBeTDAT2KgDoBDB9dAJ1QApgAdZTTACxYwAZvEwByAMTiANDwC+ASnadM6fjAC2JJWQB8mMKlQADHnwBk8ePWHoYLTN159MUAJaoADoXqUxAEaEEGAA1gDc5q6QyPaxYlwgmImRLnzCwfToYizuePzoqa6YAO7uUOpiAAxFrhp5BdW1fAEQLLAsALSQwSxirPRoXvRCsc2Yre0OnVTEYqgQhOXjkx2dZRX8YgCsXgAemFWYuwcnK21rxHbdi21iACTA6lowtD1tqLR4LH4A2gAcVQAuvJxpoRnh3MhOugIF4dvswRCoZ1cvlsphOgBGKqIqLyHgmRThEAyECoSixeh7BDgYydFEAK1QpKQyGEeVpzi46ESLAArsRUIkxNzebyQFlUYKYJ1kBBOvzkKF5SVkCK1AKYHJ1eLEkEQqE5QqtF50JQNax+dqeDy7UhesaGcgAG70JZQToaPaWrU6u0SyCabSxJ2m82+63+vUgWBgXw-dDuFCdA1hJ1Qfk+dxgLKysD8jAQTSdLwsOEOJMwYUITVR20xuMJrLJ6Fpo3yzqZ7O5+yl8teSvuasa34NgNWm26gNigP2vLyoSj8d6mMxVAwAtJl2y7tLXvV9budRd9zCYQOGCht2Ea01lcBoEP9AE6foIHR+1NkYtlPtp2oPwbTqIMnplhWLDmp0EA7iwuSwDW-R+g+IDCCg6CdMI9CaO4hCUBmWb7nmcrYSOtaTp+EpoaGWE4XhTo4cYUJ4J0eBXg4OaYdhuH4aEMCUCUFyRlOc6oUqYBJimuaEGATpQje5TCZRiTCOJknQtJsmdkq3j0GAMCehBWRtEpKGqcgEmtp0SzIDAIysT8HhXhhnbymg6CgSMnoeEIlkoKZb6JHxlDCD82hdpuzbqXJmheMBgwSkh9aBSA2gePQmF2eg-JCCR4XacqqrquRyEpcgpGet85SdCMdmoHJrruopJXJaJnZ7jmxFSu4sXAdKQoBW1CodQeMwwMQEkfINMadjAewDGNOHvGg032p28lNd5ED8kEsqoL4gE3MGzmIXWIkxuBg6QfhBUqhAaqrRKG4TbCXReBu-JQAq8b0PSt1FY9iTPZur2lh9X2dONLyhv993FUl532sDk1dOag5Okqd0PS1iNPawzFOrZJQ2TAgMgEqx4Y4VcNk1KArEJDsVQSTqYiG0pO1mOgUSu6JR+DWynoLOq6JHN+lmsu3Oie2Qr1bY9hdKgpF5bKMvVgLz6iRybAudW9hQIkmvvoL854IuHNiFzc4i5KdjTEGIYSkbT7c6+j7KZKGH07K5XhbmG4aokwQlA4iQe3TMoqzMwz6TVdssIHkqEHzlD1agzEMyTYcoRHDMbkttzQkTLPy6HtaJLz-PZyl-7xhA6fICxAQ-LH4b4SzARs0u5cgLZsHV9LwTpnXDdNy3PswMTUKyqXCc95XqcDzGtfBKPqbj3Kk8d13FvJEnKf1ZogpJtZ09L-aK-1wTzd6XtMeqzvicL2nGeylnpIof+FbINfG-F9PccFZP2TvzToR9CAn3fh7L+g4f6N3XrfaOiDZ7AIPjMV+p9bLnwlDAq8v9EG6Vjp3NC3cEj7yrh-FK7wujem6L9XeQd7plw9tQr0c1rJXjwOoROgFgLYMSA7ZyjMzTtwAcQ9mktrYVxAYvSh1thaiTFjACWnMjb2m1hgTeGADKGylsbNRIAFwSNUXopG5piA2Qwg7UC949Eu2tm7cUH4UKCNDCUfgx5qz32dOnWAqCKEsMLLCEsl1Kz4Tbpgh+JDd5Wxts-fhQsDFKJUZbNRPN47dCCcWfsEEIxyJFjGDRuttEGxAM7E2EojGkMwLEqR6SFZHUdgk0SUJfF7QwR3IeoRdF1PsauRxPJnEpW-ImKyARBgsUITPeOic+7MJQiM38bYJlIKIY-eeMiNbDMij+aK-5845kLpvKetlAFlzIc-MBx93CRP4bGHZoy-xdMWoc4I0IplnLnhczZ6DG6ZzPvkr8DylmpmeQc5aqyonGLIXMueHtFl7LBR0gB4I9gRR+o8latYsTwuBdFCFHzxHVMSLCu55k-IaWLOCY5JcZkbLQeAyBAKPbkvxVSjKHyUH0tAaPf5WDAVUTUlZaxkLWbRNmTAfuAqVJCpTKi4RzNp6nSqCy2V0JhijGeBueq-9TmtPKAw8hqcrkQJuVAsyarSy1ViBobVor9V+J7rC35RA37MpQlCWAVJ1IagAEwe2II3E8AAvBwCoCrHjJvKiJJNTo4pQmldwGULxZByvmI5nK6XfIPncxNyaspppuG80VRLDWkulalAySbMqptyr7fM9DE7B3mSlPNNbsq5Q1c5W1h4PkOrLZKltok20po7bKH4jdZRGVBpmoB3LZEexHQW3KE62LQSusZRW3jS3+IXQmqtGUACO1oWCiM0SK3V0y53ZtAYys17rW0Hs6MehwZ6rHstFVym9xreVuv5Yup9L7T2n3PR+wl6yYWDrhShZA-JNCdy6MQegHh4GhvLLurZbU4MIadAMXCBM0P1zJqE66dCA492bdBlK3sFWiNOTukxUijWH2ubc6ViTTEgGSYlGpaSVLuB1lo-WPSClDLqYkKpMS+O2waa4p2djnwDP0SlZGoMsj4wCPyPsN8wgwHQGnbx-aJVSo9qptoNVmC5E032ad5nZ3nL3uW0zUMUYWY01pqdG6Z3bog45qDdyzNdCDAEKEm7P1Zr3vEitgWjohfKt5xBDHv2YZjDFhC+lkBQASrF0LoNXIpimWTGLSxQPBgypez5GGAsudBiV99ZWS2+ZJf56LNXzPRqZnRsi1RnMvXM+9GAn1voHXqv7Q1lHqt9beuDYbv16pdptdWXthm0AGuM0O1LbXpuDYhlDR2ZHxtMKo6JGLA2huQ2IPtiF8oPI+p7l9HaxBJsg3M2jBt5GyETYrRTKxjaKNHbuTea0IH6vUoq1+yLPy71sY9kDt1pXqX2a+ZDtBv6YcoThyDxpHKfPiqdS13FGKQX-jwzZSZWhXn+XnSloFRO2XFvBxF2DhBCCE6isKjN3iIfSJzRWhFVkY1iN88z1nFqLLRXrQdjUIvVXi6su4zxSPpeClF2VYa1YMsocmYOMAZ4czHgtLWGXMGTSdZmNtFg+llcs49rNRY6wPH2EK4x1cFFnwKJjJJyRBT7SC9srY3pimVxiZmgqRia8ryGWEObnKsdL3W9V6JEjUFOw7ky-1oQHIfQu4nKVeRBjJMAAUBxDm67x0xEoqqenLCUGnPuQBV6LXBrFFT7SN5r80mMjeejN5E9bPpAYlMh-tJj1PkeM8iHcNn1J3M3fcw96bc2AA1d0d5vfiYb-BTv85kAsyr331cA-xRD9h6v2UwVBLtCl0blXDZXzyBAPIIAA)

**Comment by jeddy3** [comment]
@kyleknighted Thanks for the report and for the demo.

It's likely a problem with [the parser](https://github.com/stylelint/postcss-css-in-js) stylelint uses [to support CSS-in-JS](https://stylelint.io/about/syntaxes). I've added this issue to https://github.com/stylelint/stylelint/issues/4574, which is a list of the problems with the syntax that we need help to fix.

Please consider [contributing to the parser](https://stylelint.io/developer-guide/syntaxes) if you have time.

**Comment by jeddy3** [comment]
Closing as the [`syntax` option was removed](https://github.com/stylelint/stylelint/issues/5289) for the [14.0.0 release](https://github.com/stylelint/stylelint/issues/5205). (See the [migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md#syntax-option-and-automatic-inferral-of-syntax).)

We'll also [be deprecating](https://github.com/stylelint/postcss-css-in-js/issues/225) our [forked CSS-in-JS package](https://github.com/stylelint/postcss-css-in-js), in favour of leaner custom syntaxes.

Please consider [writing a custom syntax](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/syntaxes.md) specific to the CSS-in-JS library in this issue and fixing the bug there.
