### ISSUE TITLE
Add rules to stylelint via .stylelintrc file when using the stylelint PostCSS plugin

### ISSUE THREAD

**Issue by tiloyi** [stylelint/stylelint#5247]
> Clearly describe the bug

Hello,
I would like to know if it is possible to add rules to stylelint via a configuration file, when using the stylelint PostCSS plugin?

Currently, I am working on a project that builds CSS with PostCSS.
The PostCSS configuration (that implement stylelint) is provided to me by an external library, so I can't change it.

However, I would like to be able to add additional rules to Stylelint, so that it does not mention certain "errors" that I have in my code.

So I create a `.stylelintrc` file, but it doesn't seem to be read in the stylelint PostCSS plugin during the build.

> What code is needed to reproduce the bug?

1. The PostCSS configuration is the following:
_(this configuration is provided by an external library)_
_(I remove other elements that were not useful for understanding the problem, but the configuration is much more extensive than that.)_

```js
const autoprefixer = require('autoprefixer')
const sass = require('@csstools/postcss-sass')
const stylelint = require('stylelint')
const reporter = require('postcss-reporter')
const styleLintConfig = {
  extends: ['stylelint-config-standard'],
  plugins: ['stylelint-scss'],
  rules: {
    'at-rule-no-unknown': null,
    'max-empty-lines': null,
  },
}

module.exports = {
  plugins: [
    stylelint({ config: styleLintConfig }),
    reporter({ clearReportedMessages: true }),
    sass({
      outputStyle: 'expanded',
    }),
    autoprefixer(),
  ],
};
```

2. I want to add new rules for stylelint, so I create a `.stylelintrc` file, that contain: 
```json
{
  "rules": {
    "selector-pseudo-element-no-unknown": [
      true,
      {
        "ignorePseudoElements": ["v-deep"]
      }
    ]
  }
}
```

> Which version of stylelint are you using?

stylelint@13.12.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

With PostCSS plugin

> What did you expect to happen?

I want the rule I add to the `.stylelintrc` file to be taken into account during the build by the stylelint PostCSS plugin

> What actually happened (e.g. what warnings or errors did you get)?

The rule in the  `.stylelintrc` file is not taken into account

```shell
src/bundle.scss
17:4    ⚠  Unexpected unknown pseudo-element selector "::v-deep" (selector-pseudo-element-no-unknown) [stylelint]
```

Thank you for your help

**Comment by jeddy3** [comment]
It's not possible to use both the `config` option and a `.stylelintrc` file.

From [the docs](https://stylelint.io/user-guide/usage/node-api#config):

> __config__
> A configuration object.
> stylelint does not bother looking for a .stylelintrc file if you use this option.

I suggest calling stylelint without any options and moving all the configuration object into your `.stylelintrc` file:

```
module.exports = {
  plugins: [
    stylelint(),
    reporter({ clearReportedMessages: true }),
    sass({
      outputStyle: 'expanded',
    }),
    autoprefixer(),
  ],
};
```

**Comment by tiloyi** [comment]
Hi @jeddy3 ,
Thanks for your feedback.
I will try to follow your recommendation.
