### ISSUE TITLE
Add ignoreFiles property to config

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#530]
We could add an `ignoreFiles` property to the config object. Users can already ignore specific files using negative glob patterns; but there are two shortcomings of that:

- It's not super straightforward and easy for some users
- Clients that do not care about file globs won't pick it up; e.g. you won't be able to tell a stylelint editor plugin to a ignore certain files

I think the simplest approach for us is to add a `ignoreFiles` property to config, which accepts a glob pattern.

Any thoughts?

**Comment by jeddy3** [comment]
> Any thoughts?

Sounds like the simplest approach to address those two issue to me too.

**Comment by davidtheclark** [comment]
I've been working on this and of course ran into the complications caused by extends.

I was thinking: Would it be reasonable to just ignore any `ignoreFiles` in extended configs? I'm not sure there's a great way to make the globs of an `ignoreFiles` option make sense except in the root config.

**Comment by jeddy3** [comment]
> Would it be reasonable to just ignore any ignoreFiles in extended configs?

Yes, this sounds reasonable to me.

**Comment by davidtheclark** [comment]
Closed by #545 .
