### ISSUE TITLE
Improve migration experience to customSyntax

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#5301]
Ref: https://github.com/stylelint/stylelint/issues/5289#issuecomment-841048285

We'll need to:

- write a migration guide and changelog
- update the user guide to reflect this change

**Comment by hudochenkov** [comment]
Also we would need to:

- if `--syntax` passed provide helpful message for each syntax with some guidance to resolve an issue.
- if file extension is not `.css`, `.pcss`, `.postcss`, and `customSyntax` is not specified show similar guidance for known syntaxes.

**Comment by jeddy3** [comment]
I was going to create a new issue for that, but it makes sense to do the code messaging documentation together.
