### ISSUE TITLE
Fix npm vulnerabilities from postcss

### ISSUE THREAD

**Issue by SergKozyrev** [stylelint/stylelint#5318]
> What is the problem you're trying to solve?

I want to fix npm vulnerabilities from postcss.

> What solution would you like to see?

```
"dependencies": {
    ...
    "postcss": "^8.2.15",
    ...
}
```

**Comment by hudochenkov** [comment]
Will be fixed with https://github.com/stylelint/stylelint/issues/4942.

**Comment by jeddy3** [comment]
@SergKozyrev releasing `14.0.0` requires a fair amount of work (see https://github.com/stylelint/stylelint/issues/5205#issue-837034702). Please consider [contributing](https://stylelint.io/contributing) if you have time to speed up the release.
