### ISSUE TITLE
comment-space-inside

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#532]
I have some comments with `/*!` for copyright, may be add option to ignore space in comments(regexp option), example 
```json
{
    "comment-space-inside": [
        2,
        "always",
        {
            "ignore" : "^[/* ] Copyright"
        }
    ],
}
```
Also source map generated code in css:
```css
/*# sourceMappingURL=bootstrap.css.map */
```
And it make error

**Comment by jeddy3** [comment]
Makes sense to me.

@davidtheclark What do you think about having the regex in the optional option object? I believe we've used an array of keyword strings for `ignore` everywhere else. The regex seems like a eloquent solution of these two edge cases though.

**Comment by davidtheclark** [comment]
The regexp ignore seems find to me. But are those conventions pretty widespread, pretty standard (`/*!` for copyright and `/*#` for source maps)? If so, I'm thinking we should just ignore them by default.

**Comment by jeddy3** [comment]
> But are those conventions pretty widespread, pretty standard (/*! for copyright and /*# for source maps)

They seem to be. `/*#` is in the [sourcemap spec](https://developers.google.com/web/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed?hl=en) and `/*!` looks to be historically from [YUI Compressor](http://yui.github.io/yuicompressor/css.html#special-comments), but continues to [be supported by the likes of cssnano](http://cssnano.co/optimisations/#removal-of-comments).

Should we include the trailing space in `/*# `, as not to accidentally ignore comments like `/*#some-id comment goes here */`?

> If so, I'm thinking we should just ignore them by default.

Agreed :)

**Comment by davidtheclark** [comment]
Ok. I agree that we should expect the space after `/*#` or `/*!`.
