### ISSUE TITLE
Unexpected unknown at-rule "@use"

### ISSUE THREAD

**Issue by strarsis** [stylelint/stylelint#5340]
> Clearly describe the bug

`stylelint` doesn't know the `@use` [`at-rule`](https://sass-lang.com/documentation/at-rules/use), available with `dart-sass`.

> Which rule, if any, is the bug related to?

`at-rule-no-unknown`

> What code is needed to reproduce the bug?

```scss
@use "sass:math";
```

> What stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  'extends': 'stylelint-config-standard',
  'rules': {
    'no-empty-source': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'string-quotes': 'double',
    'at-rule-no-unknown': [
      true,
      {
        'ignoreAtRules': [
          'extend',
          'at-root',
          'debug',
          'warn',
          'error',
          'if',
          'else',
          'for',
          'each',
          'while',
          'mixin',
          'include',
          'content',
          'return',
          'function',
          'tailwind',
          'apply',
          'responsive',
          'variants',
          'screen',
        ],
      },
    ],
  },
};

```

> Which version of stylelint are you using?

`13.13.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`webpack`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS stylesheets.

> What did you expect to happen?

No lint error from rule `at-rule-no-unknown` for `@use` rule.

> What actually happened (e.g. what warnings or errors did you get)?

````
Unexpected unknown at-rule "@use"
````

**Comment by jeddy3** [comment]
Thanks for the report and for using the template.

The rule is behaving [as documented](https://stylelint.io/user-guide/rules/list/at-rule-no-unknown/):

> This rule considers at-rules defined in the CSS Specifications, up to and including Editor's Drafts, to be known.

You'll want to use [`at-rule-no-unknown` rule](https://github.com/kristerkari/stylelint-scss/tree/master/src/rules/at-rule-no-unknown) from the [`stylelint-scss` plugin](https://github.com/kristerkari/stylelint-scss/) if you're writing SCSS.

In the next major release of stylelint, it'll be clearer that a plugin should be used when writing a styling language other than CSS. See https://github.com/stylelint/stylelint/issues/5289#issuecomment-840772900.

**Comment by strarsis** [comment]
@jeddy3: So currently I am using `stylelint-config-standard`. Does this mean this ruleset is less suited than `stylelint-scss` when I am linting SCSS with it? Is `stylelint-scss` also a ruleset like `stylelint-config-standard`, but for SCSS, or is it something different?

**Comment by jeddy3** [comment]
> Is `stylelint-scss` also a ruleset like `stylelint-config-standard`, but for SCSS, or is it something different?

- `stylelint-scss` is a _plugin pack_ of custom rules designed for SCSS-like syntax
- `stylelint-config-standard` is a _shared config_ that turns on and configures the stylistic rules built-in to stylelint

A _shared config_ can bundle _plugins / plugin packs_ within them.

> Does this mean this ruleset is less suited than stylelint-scss when I am linting SCSS with it?

They are different and can be used together. 

I suspect as we move towards releasing `14.0.0`, the SCSS community will release a `stylelint-config-scss-standard` _shared config_ which will:

- bundle `stylelint-scss` and the `postcss-syntax` syntax
- turn on and configure the stylistic rules from `stylelint-scss`

Then you'll just need to install that to get:
- comprehensive linting
- the built-in rules configured for SCSS

Until then, I suggest continuing to use `stylelint-config-standard` and adding `stylelint-scss` on top, e.g.

```js
module.exports = {
  'plugins': 'stylelint-scss',
  'extends': 'stylelint-config-standard',
  'rules': {
    "at-rule-no-unknown": null,
    "scss/at-rule-no-unknown": true,
    // turn on all the other stylelint-scss rules you want
    // https://github.com/kristerkari/stylelint-scss#list-of-rules
  },
};
