### ISSUE TITLE
custom fix

### ISSUE THREAD

**Issue by YeomanYe** [stylelint/stylelint#5342]
> What is the problem you're trying to solve?

I set color type limits.The autofix tool cannot automatically convert colors.

> What solution would you like to see?

I want stylelint to call the custom fix-tool to fix it.

**Comment by jeddy3** [comment]
Thank you for your suggestion. I think this is best-suited as a [plugin](https://stylelint.io/developer-guide/plugins).

The existing [`stylelint-color-format` plugin](https://github.com/filipekiss/stylelint-color-format) may be want you need, otherwise you'll want to craft you own.

**Comment by YeomanYe** [comment]
> Thank you for your suggestion. I think this is best-suited as a [plugin](https://stylelint.io/developer-guide/plugins).
> 
> The existing [`stylelint-color-format` plugin](https://github.com/filipekiss/stylelint-color-format) may be what you need, otherwise you'll want to craft your own.

Thank you very much for solving my problem
