### ISSUE TITLE
Rule to prevnet list of vendor prefixed properties

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#5343]
> What is the problem you're trying to solve?

In modern browsers, most of the properties(animation, transition) are not required with vendor prefixes.  So need to prevent some properties with vendor prefixes alone, the property without vendor prefix should be allowed

> What solution would you like to see?

A new rule or an option in property-disallowed-list to disallow the list of vendor-prefixed properties.

**Comment by hudochenkov** [comment]
You want this rule https://stylelint.io/user-guide/rules/list/property-no-vendor-prefix? :)

**Comment by ssivanatarajan** [comment]
yes , Thanks @hudochenkov

**Comment by ssivanatarajan** [comment]
Sorry mistakenly closed. Actually, I need to prevent vendor prefixes for specific properties, not all vendor prefixes. And also it is not possible to give all other properties in the ignored-properties option in property-no-vendor-prefix . it would be good if we have an option to give a set of properties to prevent

**Comment by jeddy3** [comment]
For such a specific use case, a custom [plugin](https://stylelint.io/developer-guide/plugins) is best.

The built-in rules are for the common use cases of:

- `property-disallowed-list` working on unprefixed properties
- `property-no-vendor-prefix` disallowing vendor prefixes that are handled by Autoprefixer.

**Comment by ssivanatarajan** [comment]
@jeddy3 created a plugin to fix this issue https://github.com/ssivanatarajan/stylelint-disallow-vendor-prefix
