### ISSUE TITLE
Any rule to mandate a space between keywords in media query

### ISSUE THREAD

**Issue by ssivanatarajan** [stylelint/stylelint#5344]
> What is the problem you're trying to solve?

if there is no space between media keywords in the media query it won't work. example below code snippet

`@media only screen and(max-width: 600px) {
  body {
    background-color: lightblue;
  }
}`

the above block won't work because there is  no space between 'and' & (max-width .
> What solution would you like to see?

A new rule that  mandate the space between the keywords in media query.

**Comment by mattxwang** [comment]
This is not exactly the fix you're looking for, but a bandaid fix could involve using [`function-disallowed-list`](https://stylelint.io/user-guide/rules/list/function-disallowed-list/) and slapping in `and` as a disallowed pattern.

I may also be missing a different rule that better fits what you're looking for!

**Comment by jeddy3** [comment]
Thanks for the request and for using the template.

I think validating media queries is out of scope. This may change if we ever migrate to a stricter parser, though.

You can either use a dedicated tool like [CSSTree validator](https://github.com/csstree/validator) (test it [here](https://csstree.github.io/docs/validator.html)) or write a [plugin](https://stylelint.io/developer-guide/plugins) that to disallow this. As @mattxwang suggestion hints at, the PostCSS value parser will parse this as a `function` node so you can write your plugin to work with this behaviour.
