### ISSUE TITLE
no-multiple-empty-lines option count empty lines

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#537]
Add options for setup how many empty lines throw warning or error

**Comment by jeddy3** [comment]
Sgtm.

Perhaps a choice of solution here:

1. This will be another `*-no-*` rule, after #533, with an optional options object e.g. `"no-multiple-empty-lines": [ true, { max: 3 } ]`
2. Add a new rule inline with the `*-max-*` conventions e.g. `max-empty-lines: int`

The former is probably best... what do you guys think?

**Comment by evilebottnawi** [comment]
@jeddy3 i think it is good solution

**Comment by davidtheclark** [comment]
I actually like the `max-empty-lines: int` approach better. More concise and simple.

**Comment by jeddy3** [comment]
> I actually like the max-empty-lines: int approach better. More concise and simple.

Agreed.

So, shall we replace `no-multiple-empty-lines` with `max-empty-lines: int` in `3.0.0`?

**Comment by davidtheclark** [comment]
Yeah, now's our big chance.

**Comment by davidtheclark** [comment]
Closed by #563.

@jeddy3 : With this issue out of the way, are we ready to release v3?

**Comment by jeddy3** [comment]
> With this issue out of the way, are we ready to release v3?

I believe so :)

**Comment by jeddy3** [comment]
@davidtheclark Shall I do the release?

**Comment by davidtheclark** [comment]
Sure, if you'd like. Rebasing v3 onto master might be kind of a pain, so I
was going to give it a shot tonight; but if you're interested, feel free.

**Comment by jeddy3** [comment]
> Rebasing v3 onto master might be kind of a pain, so I
was going to give it a shot tonight; 

Ooo. Of course. I'll leave it to you, if that's OK, as I've a family meal this evening. I'll make time to push out `3.0`-compatible version of `config-suitcss` and `config-wordpress` when you're done though.
