### ISSUE TITLE
Document pre-commit framework integration

### ISSUE THREAD

**Issue by AleksaC** [stylelint/stylelint#5373]
> What is the problem you're trying to solve?

I want to be able to use stylelint with [pre-commit framework](https://pre-commit.com). The biggest selling point of pre-commit is that in addition to managing git hooks it also installs them in isolated environments making configuration as simple as specifying them in a single yaml file. It is especially good for projects that use multiple languages as it supports hooks in [over a dozen languages](https://pre-commit.com/#supported-languages).

I saw that [docs](https://github.com/stylelint/stylelint/blob/403248c5586d6015127b5f98cf93442efc7c2547/docs/user-guide/integrations/other.md) currently mention this [repo](https://github.com/awebdeveloper/pre-commit-stylelint). However the solution has no benefits over just using [`repo: local`](https://pre-commit.com/#repository-local-hooks) and since it doesn't mirror stylelint releases it is actually worse than using local repo. One of the downsides of using solutions like that is that the hooks can't be updated using pre-commit's autoupdate command and need to be updated manually. Also I think that they make less use of pre-commit's cache if they are used across many repositories.

> What solution would you like to see?

To be able to use this repo, pre-commit needs a little bit of metadata that needs to be put inside `.pre-commit-hooks.yaml` file. This is a simple config that shouldn't change much over time and therefore would require little to no maintenance. 

While writing this issue I came across a [comment](https://github.com/pre-commit/pre-commit/issues/1768#issuecomment-765551051) where the author of pre-commit suggests adding pre-commit support to this repo as a preferred solution for using stylelint with pre-commit.

**Comment by jeddy3** [comment]
@AleksaC Thanks for the request and for using the template.

I suspect we'll want to avoid including config files for third party tooling in the stylelint repo. I think the mirror approach would be best.  I'll label the issue as discussion in case any other contributors have thoughts on this. If no one adds anything, assume that the config won't be added and that the mirror approach is best.

I'll also close the open pull request, so that any discussion happens in one place.

**Comment by thibaudcolas** [comment]
I’m interested in this as well. We could learn from the example of Prettier, which [originally had support within the `prettier/prettier` repository](https://github.com/prettier/prettier/issues/8925), then made a [prettier/pre-commit mirror](https://github.com/prettier/pre-commit), which then got replaced by [pre-commit/mirrors-prettier](https://github.com/pre-commit/mirrors-prettier) (see [prettier#8937](https://github.com/prettier/prettier/pull/8937)).

From what I understand of this latest iteration, the mirroring is fully automated. According to [prettier#8925](https://github.com/prettier/prettier/issues/8925), it also comes with performance advantages.

**Comment by thibaudcolas** [comment]
I wanted to see what the steps involved would be, so went ahead and made [thibaudcolas/mirrors-stylelint](https://github.com/thibaudcolas/mirrors-stylelint). This is based on the example I shared above, as well as the existing [awebdeveloper/pre-commit-stylelint](https://github.com/awebdeveloper/pre-commit-stylelint) to make it as simple as possible to migrate.

This should be very low-maintenance – the way stylelint works is very compatible with pre-commit as it is, so the hook should be able to support all versions of stylelint and all versions of pre-commit for the foreseeable future. The only regular change will be to mirror stylelint releases as tags, and that’s automated.

If we’ll have it, I’d love to have this moved to the stylelint organisation (as `stylelint/pre-commit`?).

**Comment by AleksaC** [comment]
Looks good to me. The only thing I'd add is the releases section on the repo page since that's where I go to find the release I want to use and I'm probably not the only one.

**Comment by jeddy3** [comment]
@thibaudcolas Thanks for looking into this some more. The mirror looks good!

> If we’ll have it, I’d love to have this moved to the stylelint organisation (as stylelint/pre-commit?).

We are moving stuff out of the Stylelint organisation at the moment, e.g. custom syntaxes. I suggest we update [our integration docs](https://stylelint.io/user-guide/integrations/other) to point to your repo rather than move the repo in the org.

I'll label as a documentation issue.

**Comment by thibaudcolas** [comment]
@jeddy3 @AleksaC if you could have a look at recent comments on https://github.com/pre-commit/pre-commit/issues/1768 between me and the maintainer of pre-commit, I’d appreciate an extra 👍  to confirm we do want to proceed with the new mirror as we’ve discussed, before I go on to make further changes. The caveats mentioned make sense to me, and personally I’d still prefer the mirror approach.

**Comment by thibaudcolas** [comment]
Here we are, I believe this should be it: https://github.com/stylelint/stylelint/pull/5898

**Comment by thibaudcolas** [comment]
Just in case anyone here finds this interesting – I wrote a quick report on how the mirror has been working over the last year and a half: https://github.com/thibaudcolas/pre-commit-stylelint/discussions/1. I’m planning to introduce Stylelint on a major project so had to take a look at this again.
