### ISSUE TITLE
Bump autoprefixer to v10

### ISSUE THREAD

**Issue by LeoniePhiline** [stylelint/stylelint#5380]
> What is the problem you're trying to solve?

I want to use `@supports selector(:pseudo-selector)` in my CSS.

> What solution would you like to see?

It is solved in autoprefixer 10: https://github.com/postcss/autoprefixer/issues/1391

stylelint uses autoprefixer 9. Bumping the dependency to v1would help me use `@supports selector(:focus-visible)`.

**Comment by jeddy3** [comment]
@LeoniePhiline Thanks for the request and for using the template.

Autoprefixer will be removed in the next major release ([14.0.0](https://github.com/stylelint/stylelint/issues/5205)).

**Comment by LeoniePhiline** [comment]
Thanks @jeddy3 !

Do you have a rough ETA? The release seems to be a bigger project.

**Comment by jeddy3** [comment]
> Do you have a rough ETA?

No, I'm afraid not. We had some momentum but then I and the other volunteers got busy. If you'd like to help get the release finished, the https://github.com/stylelint/stylelint/issues/4843 is the next issue to pick up.
