### ISSUE TITLE
Reasons why we can't use Stylelint

### ISSUE THREAD

**Issue by Bazeloth** [stylelint/stylelint#5383]
Not necessarily a bug report, so i'm just throwing this out there for you guys to improve upon:

**Integration**
We have to seperately install Stylelint as a global executable instead of being able to integrate it into our development pipeline in order to use the `--fix` parameter. We were able to get it working with postcss with Visual Studio, but this doesnt include the functionality to automatically fix certain errors (the `--fix` option for the CLI version). For that we need the CLI version which isn't available as a nuget package. We do the same thing to cleanup our code using the resharper CLI by including https://www.nuget.org/packages/JetBrains.ReSharper.CommandLineTools/2021.2.0-eap04 by referencing the package in our csproj and executing a command line. We can't do this with Stylelint as it's not available as an official nuget package.

By simply specifying a target in the .csproj file we are able to call this by the specified `Name` attribure from our compiled dll:
![image](https://user-images.githubusercontent.com/19928782/123769126-42763000-d8c9-11eb-8a24-7bdf7c55d3c2.png)

We'd like to do a similar thing for Stylelint, but again: there is no nuget package to reference so its a hassle to setup. It _has_ to be installed as a global executable which defeats the whole purpose of automation and pipeline integration.

**Encoding**
In our `.csproj` file we have a whole list of files set to use a specific encoding. `.json` files for example are encoded as UTF8 BOM, which isnt supported to be loaded as a config file:
![image](https://user-images.githubusercontent.com/19928782/123768503-ac420a00-d8c8-11eb-8eb4-3df7255778d7.png)

A similar issue is reported here and people have been asking for an update, but there hasnt been any activity/reply to this comment: https://github.com/SonarSource/sonar-css/issues/161#issuecomment-731218011

Besides that we use a bunch of partial .scss files to create a bundle file. We'd like to see a default encoding option in the Stylelint config instead of having to decorate every file with an @charset "UTF-8 BOM". By the way: only @charset "UTF-8" seems to be working. I can't find the correct string for UTF8-BOM.

I hope this feedback helps to improve the product.

**Comment by jeddy3** [comment]
Thanks for the suggestions. It'd be good to do what we can to improve the editor integration.

> there is no nuget package to reference

Is this something a 3rd party can publish from our npm package? If so, would you like to go ahead and do that? If not, can you please create a [new feature request issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REQUEST_A_FEATURE.md) for it.

> We'd like to see a default encoding option in the Stylelint config instead of having to decorate every file with an `@charset` "UTF-8 BOM".

Can you please create a [new feature request issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REQUEST_A_FEATURE.md) for this too, please? It'll help us triage and discuss it.
