### ISSUE TITLE
Fix false positives for @counter-style and related properties in property-no-unknown

### ISSUE THREAD

**Issue by amire80** [stylelint/stylelint#5385]
> What is the problem you're trying to solve?

Both Firefox and Chrome now support the @counter-style feature, which is described at https://www.w3.org/TR/css-counter-styles-3/

stylelint doesn't seem to support it yet, and fails with property-no-unknown.

The necessary properties are:
* system
* negative
* prefix
* suffix
* range
* pad
* fallback
* symbols
* additive-symbols
* speak-as

Many code examples can be found at https://www.w3.org/TR/predefined-counter-styles/ . They were checked by W3C and are supposed to be valid.

This feature is used on Wikipedia in some languages, such as Santali (sat.wikipedia.org) and Meetei (mni.wikipedia.org), and Wikimedia's code is checked using stylelint, so it would be nice to support it properly without stylelint-disable.

> What solution would you like to see?

Support the feature and the necessary properties and values.

**Comment by jeddy3** [comment]
@amire80 Thanks for the report and for using the template.

We use the [`known-css-properties` package](https://github.com/known-css/known-css-properties) to get the list of known properties. It looks like properties related to the `@counter-style` feature were recently added to it. We'll just need to update our dependencies.

We're currently working on [a major release](https://github.com/stylelint/stylelint/issues/5205) and we'll roll this update in to that.

**Comment by amire80** [comment]
Great to hear! Thanks :)

**Comment by jeddy3** [comment]
Closing [as fixed](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYAdAdilBnAnrgC4wC28KAxAGa0DcWOmMA5kkQJYBuMFN9jFAAcATjGocAHn1rUG2PAFdaUmQIUikmFryqz5OIUihq5g6kgA2lgEZIwAa1MG8+UjYiXczwcagdOHgBaAndPbz11HFwhGCQHIKQI-jNMAF8sEAAaEAJMIiRJBHBcXGzwCEwJFmKMBXQQEUVLGFwGijqcHAatTAgCzkqgvqDFTAc+gHdMdpQiJpgswW7kIiCmluGIUfGpmYQ5haWFFZtLCEctoLIhInxZ+cVF5ZQGyHORK45MLisOKCCAAsYJIHkcXm8IKRSDB8lcbncwU9jl1XuBFMQoUFRBBYiI7ldSBxSt8WEFfp9qGMwIN9hRHs8TmjYGBLEhNLSgmcLgkRlBFEJLBwwOwYEEwBiiFicXjOK0kYzUQ0WWyORwhtzLnyBUKRSRsSJcTB8Rx5QcANovHAMlGotBWroNDgsPpiWaWpl2tGQTC4GASwJi-mC4Wi3BBSYBQFBfy0Y2wta-SxPNogB04AC6DoyTIztpWKvZ7HVmC55y121wgIg+MBWgBMuNBIgPBEIn+Zvp4KZDWolTWFiJlnwV2DutFwyQMNTXeREJAfbhg44w8JxNwpKCOmY7bAQWXq4cMHwkxrUAV+bRVMwNJL4qse5GYxi9hgAKNHJrF-n19vQyFzDslumj+AmVx9L6BSYFA7IAv4Yh-nShxzj2C7UpyT67BA0zfqhR74NQmgwmWPKjjqob6n6LQ0jWM7IYqjogPhhFTkG-qqsWQwjBwpBCDWUFELhSogDC-hIPucREIoYiTsRmETNhSE2vOmCsQCLDtgC7JxOG3E-H854HMpqF8q0YCwv42ghLEYAcBItmIkZ3bCdqIZ6mK7BBDxfH4uszSdvRl4NK546UTA1FSiIdHGS52wIiOuAQNJ5lCYxIwgvM4l+kS7yVNFzlpds3xJv8MZJWcYq4GyVbilCML5PlKGxV5+lCg2EAbpynnefxfktKlKzcW2rDNEBkyAgErRGClTlNYxjb4iO8l7ANaJUf6kXYn6ihQNsrJJLp2xjApOGzQxKzrTRnxCNtu3XC09VrMtimrQ0l2bXcsRXMdK0Wg6MV2p0Xpos6rowO66aMRKmKkPdZAJqmkNZp6KA5qiebzsQ7ZWSMzCTAB4NnUFIBjAE31Yads7nWiVhCHW5JWE8WwDCWEMow0eLmfkSA6A0l44EDXoNCC5m3AACoasqmnRHrA4xuL2AE9zZJDKwSNYQQKw5yv83avbnNAmvTUrfOq2tUpCEbiuObrwlYxAR5W9rDRI9mLwY6hnkbGK8VBATXLiDWhMULLevIJYkxIIQpso4LYcizAtxs3Lpzlg4LSlIk1AkJ8uCsbJYqaunrSprbjESFFT2tCQhlI2XToukHycpz02fGrV0IJi7KOZm7ubE17-kF-efqzA05yTMaMfCYPmyqcRL7mVnOdj+HkeECEpKbAT0+MbPYojDw0E1ga4hSK9qx9ZVZDCp4XEwPj3weW3Iir1Y6+l-ORfiucG5WTYmgl6+39jYQOboDjBRgK2XeqdSKsg6puABr5hgP39kgF+b8I5R0-qhb+8C-5kiQUvPGICwHBxplgjepBmicD9k-GBaI8G-0QYAyq01C5kMwR-Te2ht70JVrgtORtYQsOQSQp+y8p4QLXtgoI1DLC0J3gI4S38jSYFEUvRez8V7SPfrIghfDmAMIaKo2I6j-6sOssg0BfZwEUB6JQnBwlcqUnQnePoLNKir1INAY0+xiYuKBCCEe5Dx7YSkQEu+nxgSSD9rCFgRBASryrPxYxFRO5wmARImxTc-rsxkdHZRgNIbC0kKLQSeSU5Xg4JXFBxA3zdzlh7OWDcwbNxabkO4LQAJrEgNCesiMe4oGRl6NGXRmlQzqmBcak0tEtQ3LALh2C0nQylLDBaBIsnMADrY8hocZ6OIYQLEpIAE5J0qS3ZAL9xSSmlJLJsOsza9hqcQOpNdGnAwmULEAoNckhyeVcnOHdHpHLDt8BZlUt5ihAWnD5XoRl2jGZmAJtzYaiQ4OJIwRAc5IX2YxAAegACnNOJAAXhmElQRSUAAYggAE4MwACoACUhKgiUppfSjMABqZljKAAkoK47CWnHnXm0iACikgbI1xQKsqEKB0WoAAI5PBEPgFA88YBzAgCgUBKAjx2BsCEuFXQkXDJRTDA0H4CRYpxe0glxKyUUrJbShlLK2UcrdTyvlgqimomFYxUVPNQkgClTKt8crUXCHuYtTVrEdV6u1YapAxqRSjzTCjc1XzmTsSLJyOwVk5noJ0fYkAzBoH+tzftNUGotBkjmTkuxFCP5pMLLW0s39sq33OKWcR2yS1SLLXoqhNCOB0KMVW5UeaO0kUuN23KpZi0YN0Y4nhLBDGE2Ju2zinahELrvku9hOy-logrRE+cO6C37qhROsUpBCgxhnbuuiABGbdz7r2kUyiuTcB7e1LMKR+mtu6528m2GIfk0EtBrF7SwOs0FrVSwCgDAsn67yLpQY-AdK7h1rvkYo-hwGOKckw8u0tLb9G3qUcR-NGHD1WKXk20N57X5TpAFeu8WyOG7IdSsEdTjilDNKeUvjYdB2fE414qt3yK6vOYPU2uQyc3CV+c2vF3yJPAq7jJsFvoOzrs3WB016M+7o2JouAcU4VxLXzqq-oAUHHcPGvGdY-opnQQaex38pG6riX7doodlHR0KPHTRn8bihh9IfYxwLbG8PcIMdCojEWby+f6bFk9zbIGVos5F0sD7YncbotSvLaX3H53TaGieF7UI+bvEYMQ+RgR+l0qgiR4KOyAfDARsLKW6v5exNpZrrRWiZc64s6RrHDPJcnWVxCowRCWCCPZkgdEnPLO84NmZa3j0Se62kwETNYAaRgAffou6368K3fOHqvkPGXekVjUkaTviwG5rSWYAAmYmzEiLXwiifB7n3pGcwTCGnYGdwyRkSd8II+FTwiHfJgVcRc0l-dYrpfOdq-FiYaESjlLqqXeo9ey11XLeUCqFSc4N4qy3ho2pGjHMJ40s6lEmg1MAjUmszaM92xMWjaESVS402xMIBAvoV64vECQEzfcTKX-tBcJKSQcV9X3SvziVRJdg0kxRkb27h4LgmVja+oJJPXtVe2ZeY6vVjaSzcW5klqnnZaatsYV2+DFOupLO-zofCyJ9RBn1BETLXXvxLm91zJRrCYWtjbmRNljUDasiojz7y3mhtBig-OwE+5GgsbaA+HsSGeZJZ50MIz8udj229Xa29j2vVXGhHEKV50X-PtZwxRovPWx13od+n5v6q6Ht785l-b9eqPXYH43ofarW-El6ePxtnCpsp49ypOKMuRxydg-wqmxN0qeAjBNXbr4L4jCJCSKyFlNbUBCElEQxCu-kNQ2exQ7h24tGMJuUlouDt2NMBP9QFPgpdg9bINxpMKAAAWI-EA9uEYH9ACMkf-Q0RqamDmWNAkKrVed3NJDZJabYI+Xaa6MQCQUPQ-ecb2aXW4RfbZOvf5fJATORfvcLWOE5M5CpJgqpZ5WpBTd5XnT5euH5RudTAFLTaLHTV2LNfnTGcKDaE+dgeYDgGwRQfUIhI8IgcMRPfTSbMte3djd6JQ7FdsNQ-UXPTaAveLM9DfNJYwz4ZQsw9QnPPEPPGvaxNfAwuwowhQq6RIUw1QlwlbRQBzdbApE3NaPwzafaTOHHEQXFB0fHJ1KlInTld1VlMnYnCnX1anYTESEuENVeBnGkSNWI3APAaImsRNfVFNNNJIQmMzcZYmBwjuGwb4dwifI3Xvewqoz4Ppdo1SKw2vLw43XowHSTMyCyGDNojozaXGIYLRC+Vo0qeIxI-JAnZ1L1LlUnbYhlSnP1XWQNU3QounNEEo2Vf4SoiYmo5NLnVNHnJo5FeQiY0fZfDLALSRGwno3w14tvd4mLVfXjdfXLF4xQsAx9YrWYTXVCVogPY+MgkPZYvo5mZmR7MtPpQUEEcY8EraGAHaPaaqcMXA6RfA343Em6fEu6coobJrRJUbHQ49JPO3HwlolEykgkuGR6V3NEMktk14jku6BQ7kzDYHVmaRXaRQCqHE-wz6fXBovA8JTfWE6sWsesJDB5K4SDMYGCOEJMFMZYlQqyVbRzDjcqfqdjUmXpBU0kpUtJfUsUBHM8HksJSeZU4SB0t44FTvbDOLbrVg0LWfYmT0-470ronvCImbIM+cEMpfMMoE09HLVPRiWM15KXKEg4GEj0xmc7ckQPREighUQQHMNIEANIIAA).
