### ISSUE TITLE
How to disable no-invalid-position-at-import-rule globally in .stylelintrc

### ISSUE THREAD

**Issue by oller** [stylelint/stylelint#5387]
> Clearly describe the documentation issue

I'm trying to disable `no-invalid-position-at-import-rule` globally in .stylelintrc but the only documented option is `true`.  I've tried `false`, `"never"` etc.  Presumably this is supported, are the docs just missing here?

> What solution would you like to see?

Clear instructions and an example of how to disable this rule.

**Comment by ybiquitous** [comment]
@oller You can set `null` to disable a rule. See <https://stylelint.io/user-guide/configure#rules> 😉

**Comment by oller** [comment]
Ahh perfect. Thank you!
