### ISSUE TITLE
Add disableFix secondary option to configuration object

### ISSUE THREAD

**Issue by kuangrs** [stylelint/stylelint#5431]
> What is the problem you're trying to solve?

Sometimes we need find error which should not be automatically fixed, or it was automatically fixed by mistake, instead, we want to fix it manually.  So if closing autofix by passing property like disableFix in secondaryOptions will be very helpful

> What solution would you like to see?

Add support for closing autofix by passing property like `disableFix` in secondaryOptions

in file lib/lintPostcssResult.js (stylelint version 13.13.1), line 105 
https://github.com/stylelint/stylelint/blob/403248c5586d6015127b5f98cf93442efc7c2547/lib/lintPostcssResult.js#L104-L108 change like this 

```javascript
ruleFunction(primaryOption, secondaryOptions, {
  fix:
      // Add support for closing autofix by passing property like `disableFix` in secondaryOptions
      !secondaryOptions.disableFix && 
      stylelintOptions.fix &&
      // Next two conditionals are temporary measures until #2643 is resolved
      isFileFixCompatible &&
      !postcssResult.stylelint.disabledRanges[ruleName],
   newline,
})(postcssRoot, postcssResult),
```

**Comment by jeddy3** [comment]
@kuangrs Thanks for the request and for using the template.

Just to confirm, you'd like to disable autofix _on a per rule basis_, like the [`severity` secondary option](https://stylelint.io/user-guide/configure#severity)? If so, sounds good to me. We even [suggest plugin authors do it.](https://stylelint.io/developer-guide/plugins#the-anatomy-of-a-plugin)

**Comment by kuangrs** [comment]
> @kuangrs Thanks for the request and for using the template.
> 
> Just to confirm, you'd like to disable autofix _on a per rule basis_, like the [`severity` secondary option](https://stylelint.io/user-guide/configure#severity)? If so, sounds good to me. We even [suggest plugin authors do it.](https://stylelint.io/developer-guide/plugins#the-anatomy-of-a-plugin)

yes, I'd like to use it like `serverity`.

**Comment by jeddy3** [comment]
Thanks for confirming.

A new `disableFix` secondary option SGTM. 

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

Please branch off `v14` rather than `master`.
