### ISSUE TITLE
Project-oriented local rule plugin doesn't work properly

### ISSUE THREAD

**Issue by japboy** [stylelint/stylelint#5479]
I don't know if this is the right place to post this, but hopefully someone could help me.

Currently trying to write some project-oriented stylelint rules for my own, just like [ESLint provides an plugin which allows us to create our own project-oriented local rules](https://github.com/not-an-aardvark/eslint-plugin-rulesdir)

However somehow the custom rule plugin doesn't work properly. The minimum reproduction codes are below:

`stylelint.config.js`:

```js
module.exports = {
  plugins: ['./stylelint/rulesdir.js'],
  rules: {
    'rulesdir/no-no': [1],
  },
}
```

`stylelint/rulesdir.js`:

```js
const fs = require('fs')
const path = require('path')

const stylelint = require('stylelint')

const filenames = fs.readdirSync(__dirname)
const rules = filenames
  .filter(
    (filename) => !filename.endsWith('rulesdir.js') && filename.endsWith('.js'),
  )
  .map((filename) => {
    const modulename = path.resolve(__dirname, filename)
    const rule = require(modulename)
    return stylelint.createPlugin(`rulesdir/${rule.ruleName}`, rule)
  })

module.exports = rules
```

`stylelint/no-no.js`:

```js
const stylelint = require('stylelint')

const ruleName = 'no-no'
const messages = stylelint.utils.ruleMessages(ruleName, {
  rejected() {
    return 'Just a test error...'
  },
})

function rule(primaryOption, options = {}) {
  return function (root, result) {
    const validOptions = stylelint.utils.validateOptions(
      result,
      ruleName,
      {
        actual: primaryOption,
        possible() {
          return true
        },
      },
      {
        actual: options,
        possible() {
          return true
        },
        optional: true,
      },
    )

    if (!validOptions) {
      return
    }

    root.walk((node) => {
      stylelint.utils.report({
        ruleName,
        result,
        message: messages.rejected(),
        node,
      })
    })
  }
}

rule.messages = messages
rule.ruleName = ruleName

module.exports = rule
```

This should just shows  `Just a test error...` errors if I run `yarn stylelint ./**/*.{css,vue}`. However the output is strange:

![image](https://user-images.githubusercontent.com/84360/129310699-3aab42b7-5588-4b27-a6a7-4f44f88e66cb.png)

Also vscode-stylelint shows an error when I open an file which should be checked by the stylelint:

![image](https://user-images.githubusercontent.com/84360/129311014-9125486b-cb40-4673-b7ba-d5a74d987e59.png)

Am I missing something? Thanks for reading!

**Comment by jeddy3** [comment]
> Currently trying to write some project-oriented stylelint rules for my own

Good on you. Project-oriented plugins are a great way of enforcing consistency, and give you the most control over things like messages.

> Am I missing something?

For some reason, the `severity` property isn't being set. It's `undefined`, which shows up in both the VSCode error and within the CLI output (wrapped and stacked vertically, which is why it looks weird).

I don't have time to debug why this is happening, but I suspect it's something to do with exports. However, you can fix the issue by creating the plugins within their own files rather than within `rulesdir.js`, like so:

```js
const fs = require("fs");
const path = require("path");

const stylelint = require("stylelint");

const filenames = fs.readdirSync(__dirname);
const rules = filenames
  .filter(
    (filename) => !filename.endsWith("rulesdir.js") && filename.endsWith(".js")
  )
  .map((filename) => {
    const modulename = path.resolve(__dirname, filename);
    return require(modulename);
  });

module.exports = rules;
```

```js
const stylelint = require("stylelint");

const ruleName = "plugin/no-no";
const messages = stylelint.utils.ruleMessages(ruleName, {
  rejected() {
    return "Just a test error...";
  },
});

module.exports = stylelint.createPlugin(
  ruleName,
  function (primaryOption, options = {}) {
    return function (root, result) {
      const validOptions = stylelint.utils.validateOptions(
        result,
        ruleName,
        {
          actual: primaryOption,
          possible() {
            return true;
          },
        },
        {
          actual: options,
          possible() {
            return true;
          },
          optional: true,
        }
      );

      if (!validOptions) {
        return;
      }

      root.walk((node) => {
        stylelint.utils.report({
          ruleName,
          result,
          message: messages.rejected(),
          node,
        });
      });
    };
  }
);

module.exports.messages = messages;
module.exports.ruleName = ruleName;
```

**Comment by japboy** [comment]
@jeddy3 thx for quick reply and im gonna try that code. thank you~
