### ISSUE TITLE
Non-consistent rule names for `@keyframes`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#5493]
> Clearly describe the bug

The [naming convention of rules](https://github.com/stylelint/stylelint/blob/v14/docs/user-guide/rules/about.md#names) says:

> The first part describes what thing the rule applies to.

But, I think that the first part of the [`keyframes-name-pattern`](https://github.com/stylelint/stylelint/blob/v14/lib/rules/keyframes-name-pattern) and [`keyframe-declaration-no-important`](https://github.com/stylelint/stylelint/tree/v14/lib/rules/keyframe-declaration-no-important) rules is not consitent: `keyframes-` and `keyframe-`. Is this intentional?

> Which rule, if any, is the bug related to?

- `keyframes-name-pattern`
- `keyframe-declaration-no-important`

> What code is needed to reproduce the bug?

None.

> What stylelint configuration is needed to reproduce the bug?

None.

> Which version of stylelint are you using?

`13.13.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

N/A

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

N/A

> What did you expect to happen?

A consistent naming: `keyframes-*` or `keyframe-*`.

> What actually happened (e.g. what warnings or errors did you get)?

A non-consistent naming.

**Comment by jeddy3** [comment]
> Is this intentional?

Possibly, I can't remember :)

I think what we have is OK though, if we think of `keyframe` as shorthand for `keyframe-block` and `declaration` as the thing within it. Or put another way, `keyframes-name-pattern` is scoped to the entire keyframes at-rule whereas `keyframe-declaration-no-important` is scoped to the declarations within each `keyframe[-block]`.

See: https://www.w3.org/TR/css-animations-1/#keyframes

**Comment by ybiquitous** [comment]
@jeddy3 I see, that makes sense. Thanks for explaining it. 👍🏼
