### ISSUE TITLE
Upgrading from PostCSS 7 to PostCSS 8

### ISSUE THREAD

**Issue by TropicalRaisel** [stylelint/stylelint#5506]
Many libraries I'm using now support PostCSS 8, and some say there are a variety of issues using PostCSS 7 & 8 alongside each other even if they are not interrelated directly.

Knowing that [this project uses PostCSS 7](https://github.com/stylelint/stylelint/blob/master/package.json#L138), are there any plans to use PostCSS 8?

**Comment by jeddy3** [comment]
Thanks for your question.

Yes, updating to PostCSS 8 is part of our [`14.0.0`](https://github.com/stylelint/stylelint/issues/5205). There's more to do before we can release, though. So please consider helping out with the outstanding tasks in that issue, if you have time.
