### ISSUE TITLE
Weird Text in License

### ISSUE THREAD

**Issue by kaaax0815** [stylelint/stylelint#5518]
Issue Type: <b>Bug</b>

I created a LICENSE File with MIT License Content. After "SOFTWARE." Pressing CTRL + S adds weird Text to the License
```json
// .vscode/settings.json
"editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.fixAll": true
}
```

Extension version: 0.86.0
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.09GB free)|
|Process Argv|D:\\Bernd\\BerndPC\\Documents\\Github\\Typescript\\caprover-api --crash-reporter-id a4187d8f-07e6-4b5e-8d0b-eb0da148d534|
|Screen Reader|no|
|VM|0%|

**Comment by jeddy3** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
