### ISSUE TITLE
Remove `configOverrides` option

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#5522]
[`configOverrides`](https://stylelint.io/user-guide/usage/node-api/#configoverrides) in Node.js API would be quite confusing with [`overrides`](https://github.com/stylelint/stylelint/issues/3128) in config.

I propose to remove it in v14.

**Comment by jeddy3** [comment]
I agree.

**Comment by hudochenkov** [comment]
I can look into it as soon https://github.com/stylelint/stylelint/pull/5521 merged.

**Comment by hudochenkov** [comment]
Code is ready. Waiting for #5521 to be merged. Then I could send a PR.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/5530
