### ISSUE TITLE
Use dashed idents in our examples of custom constructs

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#5523]
> Clearly describe the documentation issue

We should use dashed idents in our examples of custom constructs to [align with the specs](https://www.w3.org/TR/css-values-4/#dashed-idents) (see example 7), e.g. `@--custom` rather than `@custom`.

This is in line with Stylelint's emphasis on standard CSS in our rules and docs.

Ref: https://github.com/stylelint/stylelint/pull/5520#issuecomment-917625540

- [x] At-rules
- [x] Functions
- [x] Units
- [x] Selectors

**Comment by sylwia-lask** [comment]
Hi @jeddy3, I think I can do that next week, but please tell me should I branch off v14 or master?

**Comment by hudochenkov** [comment]
Use v14, please.

**Comment by ybiquitous** [comment]
I believe we've rewritten all the examples. If there is what we missed, please let us know or open a pull request.
