### ISSUE TITLE
Online linter on website

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#556]
Example for csslint: http://csslint.net/
What do you thinks?

**Comment by davidtheclark** [comment]
Yes that would be fabulous, just fabulous.

**Comment by evilebottnawi** [comment]
@davidtheclark i think need start repo for this :)

**Comment by evilebottnawi** [comment]
@davidtheclark maybe place this issue in https://github.com/stylelint/stylelint.github.io

**Comment by jeddy3** [comment]
Spring cleaning the issues...

Closing this in favour of merging into #6, which in turn will point to https://github.com/stylelint/stylelint.github.io/issues
