### ISSUE TITLE
font-family-name-quotes

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#557]
http://www.w3.org/TR/CSS2/fonts.html#font-family-prop
I think 3 options:
always, never, whereRequired.

**Comment by davidtheclark** [comment]
Sure.

It is never required, I believe, (except in the crazy situation of using a font-family with the same name as a font keyword, which I don't think we could check) -- though (from the spec) "it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens".  So how about renaming the third option?

**Comment by evilebottnawi** [comment]
@davidtheclark third option - need quotes only for font-family value contain white space, digits, or punctuation characters other than hyphens. Plus it will provide an opportunity to bring to a common type of `font-family`, better code style.

**Comment by jeddy3** [comment]
I think David means the spec uses the word "recommended", as the digital and punctuation characters etc can be escaped, and so I think the options for this rule should be:

`"single"|"double"|"none"|"single-where-recommended"|"double-where-recommended"`.

This brings the options inline with the likes of `function-url-quotes`, and the use of hyphens to separate the words within the _keywords_ matches likes of `"always-single-line` seen the `-after/before` rules.

Also, I think the rule should be named `font-family-name-quotes` for consistency with the other `*-quote` rules.

**Comment by davidtheclark** [comment]
I agree with @jeddy3's comments.

**Comment by davidtheclark** [comment]
[I read (here)] that quoting generic family keyword fallbacks (e.g. `serif`) is almost always a mistake, causing the stylesheet to look for a font by that name instead of using the generic one.
