### ISSUE TITLE
bountysource integration

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#560]
https://www.bountysource.com/
What do you think?

**Comment by davidtheclark** [comment]
Is there something we need to do to allow people to post bounties for issues?

**Comment by evilebottnawi** [comment]
@davidtheclark I think it is never superfluous, and provides an incentive to work and the emergence of new contributions.

**Comment by davidtheclark** [comment]
I agree that it's a fine idea. I just don't understand the request: is there something that the project needs to do in order to allow bountysource to be used? Can't people already post bounties if they want to?

**Comment by evilebottnawi** [comment]
@danieldiekmeier https://www.bountysource.com/tools

**Comment by danieldiekmeier** [comment]
@evilebottnawi Can you please stop mentioning me?

**Comment by evilebottnawi** [comment]
@danieldiekmeier sorry man, I try.

**Comment by davidtheclark** [comment]
Ok, I believe the repo is bounty-source-ready.
