### ISSUE TITLE
Fix false positives for dynamic-range keywords in media-feature-name-no-unknown

### ISSUE THREAD

**Issue by willcassella** [stylelint/stylelint#5612]
> What is the problem you're trying to solve?

CSS Media Queries level 5 introduced the [dynamic-range and video-dynamic-range media queries](https://www.w3.org/TR/mediaqueries-5/#dynamic-range). This has been (partially) implemented in Safari, implemented behind a feature-flag in Chrome, and is considered ["worth prototyping" in Firefox](https://github.com/mozilla/standards-positions/issues/584). Since this library is used as part of of Chromium's devtools frontend, we'd like to make sure this is supported fully.

> What solution would you like to see?

"dynamic-range" and "video-dynamic-range" should be added to the set of media query feature names in this library. I've created a commit which does just that, and I'd be willing to turn it into a pull request if you'd like to accept it:
https://github.com/willcassella/stylelint/commit/612a70889260e30fde026ce7910cce747d44abc9

**Comment by jeddy3** [comment]
@willcassella Thanks for the report.

> I'd be willing to turn it into a pull request

Yes, please. Can you branch off `v14` rather than `master` and I'll slip it into the [`14.0.0` release](https://github.com/stylelint/stylelint/issues/5205).
