### ISSUE TITLE
WTF is wrong with v3?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#566]
So I published v3, with all its tests passing ... but apparently it doesn't work??

If I try to run it I get these errors:

```
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

with absolutely no helpful stack track.

Is this happening to others? Does anybody have any what is going wrong and how to fix it?

**Comment by frederickfogerty** [comment]
Getting the same error, only with glob patterns tho. Quotes don't help

**Comment by frederickfogerty** [comment]
Also I'd probably change the title, it's not very respectful to the library authors @davidtheclark

**Comment by davidtheclark** [comment]
@frederickfogerty I am the library author, and I'm frustrated with myself!

**Comment by frederickfogerty** [comment]
Hahhahahahahah I only just realised after I checked the contributors, sorry @davidtheclark

**Comment by davidtheclark** [comment]
Thanks for sticking up for me, but I'm just so annoyed by me right now that I'm not willing to listen to reason.

**Comment by davidtheclark** [comment]
Whew ... figured out the problem, and fixed in v3.0.2.

**Comment by frederickfogerty** [comment]
:+1: cheers.

**Comment by charlieschwabacher** [comment]
@davidtheclark I am running into the same issue w/ stylelint 7.3.1

```
> stylelint ./packages/**/*.css

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

**Comment by evilebottnawi** [comment]
@charlieschwabacher you have folder with `*.css` (example animated.css)
