### ISSUE TITLE
Webstrom use Stylelint 14 show error :The "syntax" option is no longer available. You should install an appropriate syntax, e.g. postcss-scss, and use the "customSyntax" option

### ISSUE THREAD

**Issue by zw-slime** [stylelint/stylelint#5662]
# my project stylelintrc :
<img width="1130" alt="企业微信截图_a421c02e-2cf4-468a-8958-ac73517aa51d" src="https://user-images.githubusercontent.com/18528957/139179888-29d20364-958d-4ab5-8105-6c3e552872f5.png">

exec ` npx stylelint "**/*.scss" ` work  well.

# but webstrom show errors:
<img width="1305" alt="企业微信截图_c1322ba5-3d5d-48df-8ab6-b89255ec8bfd" src="https://user-images.githubusercontent.com/18528957/139179818-36d6acf3-951a-4a2b-abe5-d7c2337c80c6.png">

so how to slove this problems?

**Comment by aituanyuan** [comment]
how did you reslove it

**Comment by Kramgres** [comment]
update WebStorm to the new version
