### ISSUE TITLE
stylelint for less - The "syntax" option is no longer available

### ISSUE THREAD

**Issue by PlayApple** [stylelint/stylelint#5663]
stylelint --fix "src/**/*.less" --syntax less
Error: The "syntax" option is no longer available. You should install an appropriate syntax, e.g. postcss-scss, and use the "customSyntax" option

`"lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",`

How to use customSyntax to fixed it? Thanks

**Comment by meatnordrink** [comment]
For anyone that encounters this later, the solution is

`npm i --save-dev postcss@8`

https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/5#issuecomment-961709882
