### ISSUE TITLE
Add `validateTypes` to `stylelint.utils.*`

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#5669]
It would probably make sense if the validateTypes were exposed for downstream packages to consume.

Refs https://github.com/stylelint-scss/stylelint-scss/pull/554

EDIT: looking at stylelint-scss code, it seems they duplicate a lot more utils.

**Comment by jeddy3** [comment]
> There are other utils that are stable in responsibility, e.g. the `isStandardSyntax*` ones...

[Example of the `isStandardSyntax*` being used in the wild](https://github.com/csstree/stylelint-validator/commit/bcf1382571e15ce392f5f484db5f7bcac16a3c76). 

(As an aside, it looks like a new version of the validator is going to land soon with support for at-rules!)

**Comment by ybiquitous** [comment]
> [Example of the `isStandardSyntax*` being used in the wild](https://github.com/csstree/stylelint-validator/commit/bcf1382571e15ce392f5f484db5f7bcac16a3c76).

Interesting. Exposing such helper functions may be valuable...?

> (As an aside, it looks like a new version of the validator is going to land soon with support for at-rules!)

This is very promising! 🙌🏼

**Comment by jeddy3** [comment]
Let's expose `validateTypes` util for now as it's complementary to the already exposed `stylelint.utils.validateOptions`.

We can revisit the `isStandardSyntax*` utils (in a separate issue) when get around to https://github.com/stylelint/stylelint/issues/5291 and bundle.

**Comment by ybiquitous** [comment]
I'm reconsidering this issue inspired by #6151. What if starting with the following changes?

- Expose only `is*()` functions. Because I'm still not confident with `assert*()` interfaces, but `is*()` interfaces seem more stable.
- Expose functions as flat forms, e.g.
    ```js
    // A bit verbose
    stylelint.utils.validateTypes.isBoolean(value);

    // Simpler
    stylelint.utils.isBoolean(value);
    ```

**Comment by jeddy3** [comment]
Adding only the `is*()` functions to the public API sounds good to me as they're the most commonly used alongside [`stylelint.utils.validateOptions`](https://stylelint.io/developer-guide/plugins#stylelintutilsvalidateoptions).

Having said that, I'm not 100% sure of the value of exposing these compared to the reference data which will change over time whereas the type checks won't. A person can, if they wish, copy and paste them into their plugin confident that they are unlikely to change.

**Comment by jeddy3** [comment]
Closing in favour of broader discussion issue https://github.com/stylelint/stylelint/issues/6866
