### ISSUE TITLE
Document freezing of stylistic rules

### ISSUE THREAD

**Issue by alexander-akait** [stylelint/stylelint#5674]
My proposal may seem too loud to someone, but it is discussion. 

Our main problem is that we can never satisfy stylistic preferences. There will always be someone who wants an extra space or line break. Stylistic rules grow endlessly and create more and more problems. It's getting harder and harder to maintain. 

Eslint has https://eslint.org/blog/2020/05/changes-to-rules-policies and says:

> Stylistic rules are frozen - we won't be adding any more options to stylistic rules. We've learned that there's no way to satisfy everyone's personal preferences, and most of the rules already have a lot of difficult-to-understand options. Stylistic rules are those related to spacing, conventions, and generally anything that does not highlight an error or a better way to do something. Update 2021-01-29: We clarified in the README that we will still support newly-added ECMAScript features.

Honestly, I think we should do the same. 

Currently [`prettier`](https://github.com/prettier/prettier) do good job. I see no reason not to use `prettier`. And most developers have long seen the benefits of using formatters.

Yes, some stylistic rules can still be helpful - order of properties (we have a plugin for this), force using newlines in some places (we can reduce them to a minimum options). I think we can put together a list of style rules here and discuss them.

My opinion has always been:  want your preferred formatting - write your rule/plugin. 

I don't think we should bear the burden of maintaining due to some developers who want to have an extra space. I don't want to show disrespect for someone's preferences. 

I think it's time to say that stylistics rules are outdated. They were all created when we didn't have good formatters. Enough time has passed since that time and a lot has changed.

My proposal:

- Collect stylistics rules here and discussion them, maybe divide them on two sides - can be solved formatter and can't be not solved formatter.
- Create/update documentation about rules police about stylistics rules.
- Freeze stylistics rules.
- Close all issues related to stylistics rules.

@stylelint/contributors

**Comment by nosilleg** [comment]
I'm in favour of this.  I'm also in favour of using [Prettier](https://prettier.io/) as the formatter to base decisions on / push requests for stuff not already included there.

I've taken the 88 rules listed as [Stylistic issues](https://github.com/stylelint/stylelint/blob/main/docs/user-guide/rules/list.md#stylistic-issues) and made a quick, first iteration, table to keep track of the decision process.

Feel free to move this somewhere more appropriate.

Category | Rule | Done by Prittier | Freeze | Description
-- | -- | -- | -- | --
At-rule | at-rule-empty-line-before | ❓ | ❓ | Require or disallow an empty line before at-rules (Autofixable).
At-rule | at-rule-name-case | ❓ | ❓ | Specify lowercase or uppercase for at-rules names (Autofixable).
At-rule | at-rule-name-newline-after | ❓ | ❓ | Require a newline after at-rule names.
At-rule | at-rule-name-space-after | ❓ | ❓ | Require a single space after at-rule names (Autofixable).
At-rule | at-rule-semicolon-newline-after | ❓ | ❓ | Require a newline after the semicolon of at-rules (Autofixable).
At-rule | at-rule-semicolon-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the semicolons of at-rules.
Block | block-closing-brace-empty-line-before | ❓ | ❓ | Require or disallow an empty line before the closing brace of blocks (Autofixable).
Block | block-closing-brace-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the closing brace of blocks (Autofixable).
Block | block-closing-brace-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the closing brace of blocks (Autofixable).
Block | block-closing-brace-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the closing brace of blocks.
Block | block-closing-brace-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the closing brace of blocks (Autofixable).
Block | block-opening-brace-newline-after | ❓ | ❓ | Require a newline after the opening brace of blocks (Autofixable).
Block | block-opening-brace-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the opening brace of blocks (Autofixable).
Block | block-opening-brace-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the opening brace of blocks (Autofixable).
Block | block-opening-brace-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the opening brace of blocks (Autofixable).
Color | color-hex-case | ❓ | ❓ | Specify lowercase or uppercase for hex colors (Autofixable).
Color | color-hex-length | ❓ | ❓ | Specify short or long notation for hex colors (Autofixable).
Comment | comment-empty-line-before | ❓ | ❓ | Require or disallow an empty line before comments (Autofixable).
Comment | comment-whitespace-inside | ❓ | ❓ | Require or disallow whitespace on the inside of comment markers (Autofixable).
Custom property | custom-property-empty-line-before | ❓ | ❓ | Require or disallow an empty line before custom properties (Autofixable).
Declaration | declaration-bang-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the bang of declarations (Autofixable).
Declaration | declaration-bang-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the bang of declarations (Autofixable).
Declaration | declaration-colon-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the colon of declarations (Autofixable).
Declaration | declaration-colon-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the colon of declarations (Autofixable).
Declaration | declaration-colon-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the colon of declarations (Autofixable).
Declaration | declaration-empty-line-before | ❓ | ❓ | Require or disallow an empty line before declarations (Autofixable).
Declaration block | declaration-block-semicolon-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the semicolons of declaration blocks (Autofixable).
Declaration block | declaration-block-semicolon-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the semicolons of declaration blocks.
Declaration block | declaration-block-semicolon-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the semicolons of declaration blocks (Autofixable).
Declaration block | declaration-block-semicolon-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the semicolons of declaration blocks (Autofixable).
Declaration block | declaration-block-trailing-semicolon | ❓ | ❓ | Require or disallow a trailing semicolon within declaration blocks (Autofixable).
Font family | font-family-name-quotes | ❓ | ❓ | Specify whether or not quotation marks should be used around font family names.
Function | function-comma-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the commas of functions (Autofixable).
Function | function-comma-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the commas of functions (Autofixable).
Function | function-comma-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the commas of functions (Autofixable).
Function | function-comma-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the commas of functions (Autofixable).
Function | function-max-empty-lines | ❓ | ❓ | Limit the number of adjacent empty lines within functions (Autofixable).
Function | function-name-case | ❓ | ❓ | Specify lowercase or uppercase for function names (Autofixable).
Function | function-parentheses-newline-inside | ❓ | ❓ | Require a newline or disallow whitespace on the inside of the parentheses of functions (Autofixable).
Function | function-parentheses-space-inside | ❓ | ❓ | Require a single space or disallow whitespace on the inside of the parentheses of functions (Autofixable).
Function | function-url-quotes | ❓ | ❓ | Require or disallow quotes for urls.
Function | function-whitespace-after | ❓ | ❓ | Require or disallow whitespace after functions (Autofixable).
General / Sheet | indentation | ❓ | ❓ | Specify indentation (Autofixable).
General / Sheet | linebreaks | ❓ | ❓ | Specify unix or windows linebreaks (Autofixable).
General / Sheet | max-empty-lines | ❓ | ❓ | Limit the number of adjacent empty lines (Autofixable).
General / Sheet | max-line-length | ❓ | ❓ | Limit the length of a line.
General / Sheet | no-eol-whitespace | ❓ | ❓ | Disallow end-of-line whitespace (Autofixable).
General / Sheet | no-missing-end-of-source-newline | ❓ | ❓ | Disallow missing end-of-source newlines (Autofixable).
General / Sheet | no-empty-first-line | ❓ | ❓ | Disallow empty first lines (Autofixable).
General / Sheet | unicode-bom | ❓ | ❓ | Require or disallow Unicode BOM.
General / Sheet | no-irregular-whitespace | ❓ | ❓ | Disallow irregular whitespace.
Media feature | media-feature-colon-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the colon in media features (Autofixable).
Media feature | media-feature-colon-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the colon in media features (Autofixable).
Media feature | media-feature-name-case | ❓ | ❓ | Specify lowercase or uppercase for media feature names (Autofixable).
Media feature | media-feature-parentheses-space-inside | ❓ | ❓ | Require a single space or disallow whitespace on the inside of the parentheses within media features (Autofixable).
Media feature | media-feature-range-operator-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the range operator in media features (Autofixable).
Media feature | media-feature-range-operator-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the range operator in media features (Autofixable).
Media query list | media-query-list-comma-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the commas of media query lists (Autofixable).
Media query list | media-query-list-comma-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the commas of media query lists.
Media query list | media-query-list-comma-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the commas of media query lists (Autofixable).
Media query list | media-query-list-comma-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the commas of media query lists (Autofixable).
Number | number-leading-zero | ❓ | ❓ | Require or disallow a leading zero for fractional numbers less than 1 (Autofixable).
Number | number-no-trailing-zeros | ❓ | ❓ | Disallow trailing zeros in numbers (Autofixable).
Property | property-case | ❓ | ❓ | Specify lowercase or uppercase for properties (Autofixable).
Rule | rule-empty-line-before | ❓ | ❓ | Require or disallow an empty line before rules (Autofixable).
Selector | selector-attribute-brackets-space-inside | ❓ | ❓ | Require a single space or disallow whitespace on the inside of the brackets within attribute selectors (Autofixable).
Selector | selector-attribute-operator-space-after | ❓ | ❓ | Require a single space or disallow whitespace after operators within attribute selectors (Autofixable).
Selector | selector-attribute-operator-space-before | ❓ | ❓ | Require a single space or disallow whitespace before operators within attribute selectors (Autofixable).
Selector | selector-attribute-quotes | ❓ | ❓ | Require or disallow quotes for attribute values.
Selector | selector-combinator-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the combinators of selectors (Autofixable).
Selector | selector-combinator-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the combinators of selectors (Autofixable).
Selector | selector-descendant-combinator-no-non-space | ❓ | ❓ | Disallow non-space characters for descendant combinators of selectors (Autofixable).
Selector | selector-pseudo-class-case | ❓ | ❓ | Specify lowercase or uppercase for pseudo-class selectors (Autofixable).
Selector | selector-pseudo-class-parentheses-space-inside | ❓ | ❓ | Require a single space or disallow whitespace on the inside of the parentheses within pseudo-class selectors (Autofixable).
Selector | selector-pseudo-element-case | ❓ | ❓ | Specify lowercase or uppercase for pseudo-element selectors (Autofixable).
Selector | selector-type-case | ❓ | ❓ | Specify lowercase or uppercase for type selectors (Autofixable).
Selector list | selector-list-comma-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the commas of selector lists (Autofixable).
Selector list | selector-list-comma-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the commas of selector lists (Autofixable).
Selector list | selector-list-comma-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the commas of selector lists (Autofixable).
Selector list | selector-list-comma-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the commas of selector lists (Autofixable).
String | string-quotes | ❓ | ❓ | Specify single or double quotes around strings (Autofixable).
Unit | unit-case | ❓ | ❓ | Specify lowercase or uppercase for units (Autofixable).
Value | value-keyword-case | ❓ | ❓ | Specify lowercase or uppercase for keywords values (Autofixable).
Value list | value-list-comma-newline-after | ❓ | ❓ | Require a newline or disallow whitespace after the commas of value lists (Autofixable).
Value list | value-list-comma-newline-before | ❓ | ❓ | Require a newline or disallow whitespace before the commas of value lists.
Value list | value-list-comma-space-after | ❓ | ❓ | Require a single space or disallow whitespace after the commas of value lists (Autofixable).
Value list | value-list-comma-space-before | ❓ | ❓ | Require a single space or disallow whitespace before the commas of value lists (Autofixable).
Value list | value-list-max-empty-lines | ❓ | ❓ | Limit the number of adjacent empty lines within value lists (Autofixable).

**Comment by ybiquitous** [comment]
@nosilleg Thanks for the list-up!

In addition, [the `stylelint-config-prettier` implementation](https://github.com/prettier/stylelint-config-prettier/blob/2e7704ddec015bb113b645ef50f613b92b34f6fe/src/index.js) also may be helpful.

**Comment by ota-meshi** [comment]
I think it might be better to exclude the `no-irregular-whitespace` rule from the stylistic rule classification.

**Comment by Maxim-Mazurok** [comment]
> I think it might be better to exclude the `no-irregular-whitespace` rule from the stylistic rule classification.

as well as `unicode-bom`, I think

**Comment by alexander-akait** [comment]
I think we should keep:
- `color-hex-length`
- `font-family-name-quotes`, not related to formating
- `function-url-quotes`, prettier print and `<url-token>` and `<fn-token>`, it is different things in CSS spec
- `no-irregular-whitespace`
- `unicode-bom`

Maybe:
- `comment-whitespace-inside`, prettier format comments as is

**Comment by nosilleg** [comment]
@ota-meshi @Maxim-Mazurok @alexander-akait 

So we can audit/explain this, what are the reasons for not relaying on how Prettier deals with the suggested rules that mean that we should retain them here?

@ybiquitous 

I'll merge those rules into my list.

**Comment by nosilleg** [comment]
`stylelint-config-prettier` resets have these differences:

Does not reset any rules in these categories:
 * Comment
 * Custom Property
 * Font family
 * Value

Does not reset these specific rules:
 * declaration-empty-line-before
 * function-name-case
 * no-irregular-whitespace
 * media-feature-range-operator-space-after
 * media-feature-range-operator-space-before
 * rule-empty-line-before
 * selector-type-case

Does reset these rules not listed in 'Stylistic issues':
 * selector-max-empty-lines

**Comment by hudochenkov** [comment]
I struggle to find what “frozen” mean. Maybe we should clarify that term. If I understand correctly bug fixes won't happen in stylistic rules. Shall we document this?

By the way, ESLint [keep stylistic rule rules](https://github.com/eslint/eslint#stylistic-rule-updates) in core and fixes bugs in them, but not adding new options or rules.

**Comment by alexander-akait** [comment]
@hudochenkov Yes, but unfortunately we don't fix many stylistics issues many years (some of them due bugs in parser, some of them are very hard to fix, some of them have very low usage), so I suggest going ahead and doing a total freeze

**Comment by jeddy3** [comment]
I take it to mean that the stylistic rules won't be touched (including bug fixes), will be deprecated and then eventually removed. People can always migrate a rule to a plugin to fix bugs or add options. Better to have a clean slate down the line, than some halfway house (i.e. some stylistic rules, but not for new language features) as we're a smaller project than ESLint with limited resources.

> Shall we document this?

Good idea. I can open a pull request.

**Comment by danielocdh** [comment]
but it is in the name... STYLElint
