### ISSUE TITLE
Fix TypeError for `baseIndentLevel: 1` option and vue file in indentation

### ISSUE THREAD

**Issue by caioferrarezi** [stylelint/stylelint#5677]
Hey, guys! I'm sorry if it is a repetition of another issue, but I couldn't anything related to the problem I'm facing.

> Clearly describe the bug

I got a javascript error when trying to use `stylelint` and `postcss-html` to lint `.vue` files (I believe this might happens on html files too) with the `indentation` rule configured to have a `baseIndentLevel: 1`.

> Which rule, if any, is the bug related to?
```json
"indentation": [2, {
  "baseIndentLevel": 1
}]
```

> What code is needed to reproduce the bug?

A simple single file component is enough to see the bug happening.

```html
<template>
  <div id="app">
    hi!
  </div>
</template>

<style lang="scss">
  #app {
    font: var(--type-body1-400);
  }
</style>
```

> What Stylelint configuration is needed to reproduce the bug?

```json
{
  "plugins": [
    "stylelint-scss",
    "stylelint-order"
  ],
  "ignoreFiles": ["**/dist/**/*"],
  "overrides": [{
    "files": ["*.scss", "**/*.scss"],
    "customSyntax": "postcss-scss",
    "ignoreFiles": ["**/_normalize.scss"]
  }, {
    "files": ["*.vue", "**/*.vue"],
    "customSyntax": "postcss-html",
    "rules": {
      "indentation": [2, {
        "baseIndentLevel": 1
      }]
    }
  }],
  "rules": { ... }
}
```

> Which version of Stylelint are you using?

```json
{
  "postcss": "^8.3.11",
  "postcss-html": "^1.2.0",
  "postcss-scss": "^4.0.2",
  "stylelint": "^14.0.1",
  "stylelint-order": "^5.0.0",
  "stylelint-scss": "^4.0.0"
}
```

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `./node_modules/.bin/stylelint **/*.{vue,css,scss}`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to CSS/SCSS inside HTML syntax.

> What did you expect to happen?

I was expecting the normal validation with a stylelint error when the root css code was in the same indentation level as the style tag.

> What actually happened (e.g. what warnings or errors did you get)?

I got this error:

```
./node_modules/.bin/stylelint **/*.{vue,css,scss}
TypeError: Cannot read property 'match' of undefined
    at /home/enguser/Documents/enjoei/ui/packages/vue-ui/sandbox/app.vue:18:3
    at inferRootIndentLevel (/home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/rules/indentation/index.js:682:25)
    at getRootBaseIndentLevel (/home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/rules/indentation/index.js:487:25)
    at indentationLevel (/home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/rules/indentation/index.js:170:20)
    at /home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/rules/indentation/index.js:71:22
    at /home/enguser/Documents/enjoei/ui/node_modules/postcss/lib/container.js:55:18
    at Root.each (/home/enguser/Documents/enjoei/ui/node_modules/postcss/lib/container.js:41:16)
    at Root.walk (/home/enguser/Documents/enjoei/ui/node_modules/postcss/lib/container.js:52:17)
    at /home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/rules/indentation/index.js:65:8
    at /home/enguser/Documents/enjoei/ui/node_modules/stylelint/lib/lintPostcssResult.js:112:8
    at Array.map (<anonymous>)
```

**Comment by jeddy3** [comment]
@caioferrarezi Thanks for the report and for using the template.

> I'm sorry if it is a repetition of another issue,

You're all good, it hasn't be raised as an issue yet but the good news is that'll it'll be fixed by https://github.com/stylelint/stylelint/pull/5657.

I'll mark this is a bug and wip.
