### ISSUE TITLE
Can´t make lint less pls help

### ISSUE THREAD

**Issue by pajinev** [stylelint/stylelint#5686]
After update to 14.0.0 cant run stylelint in less files...
i don´t understand how to use postcss-less...
pls help someone

**Comment by jeddy3** [comment]
See the [migration guide](https://stylelint.io/migration-guide/to-14).

Applied to Less...

First, install the postcss-less syntax as a dependency:

```
npm install --save-dev postcss-less
```

Then, update your configuration object to use it:

```
{
  "customSyntax": "postcss-less",
  "rules": {
    ..
  }
}
```

**Comment by nebirhos** [comment]
@jeddy3 Thanks for posting the correct configuration.

I updated to v14 following the guide and got stuck for a while on this error:

```
> stylelint 'src/**/*.less'

TypeError: Cannot read property 'stringify' of undefined
    at LazyResult.stringify ([...]/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:274:13)
    at LazyResult.runAsync ([...]/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:441:17)
    at LazyResult.async ([...]/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then ([...]/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:206:17)
```

The error message is not very clear... turns out I have to set `customSyntax` to `postcss-less` instead of `less`:

```diff
module.exports = {
  'extends': 'stylelint-config-standard',
-  customSyntax: 'postcss-less'
+  customSyntax: 'less'
}
```

I think this should be added to the migration guide.

**Comment by pajinev** [comment]
Not work for me.
Installed postcss-less
add do .stylelintrc this
{
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-rational-order"

  ],
  "customSyntax": "postcss-less",
  "rules": {
    "plugin/rational-order": [true, {
      "border-in-box-model": false,
      "empty-line-between-groups": true
    }],
 "comment-whitespace-inside": null,
    "at-rule-empty-line-before": null,
    "at-rule-name-space-after": null,
    "at-rule-no-unknown": null,
    "no-missing-end-of-source-newline": null,
//and more rules
}
and have still error syntax is no longer available. :(

**Comment by zheeeng** [comment]
@jeddy3  I searched many issues and tested these configs, them all failed.

reports `this.getPosition is not a function` by postcss-less

**Comment by ohhoney1** [comment]
@zheeeng postcss is outdated， needs 8.x  

or install postcss-less@^4.0.1

**Comment by kiccer** [comment]
> @zheeeng postcss is outdated， needs 8.x
> 
> or install postcss-less@^4.0.1

I also reported this error. My postcss-less is 6.0.0.
