### ISSUE TITLE
Add '--absolute-config' for an absolute config path

### ISSUE THREAD

**Issue by JacobTravers** [stylelint/stylelint#5692]
### What is the problem you're trying to solve?

`--config` seems to always use a relative path for the config file, so if you want to do something like `--config='~/.config/.stylintrc'` you will get an error because the file `currentWorkingDirectory/~/.config/.stylintrc` could not be found.

### What solution would you like to see?

I want to be able to use a an absolute path for the config file from the cli with `--absolute-config='~/.config/.stylintrc'`

**Comment by alexander-akait** [comment]
I don't think we need this, something wrong in your environments, `--config` works fine with relative and absolute configurations

**Comment by JacobTravers** [comment]
Here is an example of the command I'm running and the output:
```sh
~/m/p/project on  development is 📦 v1.0.0 via  v16.11.1
❯ echo public/css/slider.css | stylelint --fix --config='/home/user/.config/.stylelintrc'  --stdin-filename='public/css/slider.css'
Error: ENOENT: no such file or directory, open '/home/user/project/home/user/.config/.stylelintrc'
```

**Comment by JacobTravers** [comment]
would this be linked to #4521 ?

**Comment by ybiquitous** [comment]
@JacobTravers I am wondering if your reproduction code should be the following: 🤔 

- `echo` → `cat`
- Needless `--fix`
- Missing `--stdin`
- `~/` is a shell feature, so split `--config` and `~/.config/.stylintrc` with a whitespace

```shell
cat public/css/slider.css | stylelint --config ~/.config/.stylintrc --stdin --stdin-filename public/css/slider.css
```

**Comment by JacobTravers** [comment]
Sorry my mistake, I was using `cat` but accidentally wrote `echo` when I tested it outside of my editor config in the shell. However I ran the script exactly as you wrote it, and it broke exactly in the way I described before, I also tried replacing `~` with `$HOME` and `/home/user`. I am on Arch Linux using fish-shell, but I tested the script in bash, and sh as well with the same results.
```bash
$ cat public/css/slider.css | stylelint --config ~/.config/.stylintrc --stdin --stdin-filename public/css/slider.css
Error: ENOENT: no such file or directory, open '/home/user/project/home/user/.config/.stylintrc'
```

**Comment by ybiquitous** [comment]
@JacobTravers  Umm..., I cannot reproduce the error still. 🤔 

My code:

```console
$ node_modules/.bin/stylelint --version
14.0.1

$ cat /tmp/a.css
a{}

$ cat ~/.config/.stylelintrc
rules:
  block-no-empty: true

$ cat /tmp/a.css | node_modules/.bin/stylelint --config ~/.config/.stylelintrc --stdin --stdin-filename a.c
ss

a.css
 1:2  ✖  Unexpected empty block  block-no-empty
```

- Node.js v17.0.1
- macOS Big Sur

**Comment by JacobTravers** [comment]
sorry i'm dislexic, it looks like the command i was using this whole time had `.stylintrc` in the same way you had it here  https://github.com/stylelint/stylelint/issues/5692#issuecomment-962563117, it looks to be working now, closing this issue
