### ISSUE TITLE
Why is numbered severities (0, 1, 2) have been deprecated?

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#571]
As I now indicate that is a error, and that warning, or now it is considered to be unnecessary and superfluous?

**Comment by TrySound** [comment]
@davidtheclark Didn't you make option to toggle notation?

**Comment by evilebottnawi** [comment]
Also may be add feature if rule have value false, not use this rule. Why? Because I try to keep all of its setting rules linters to when a new version does not miss and do not forget. And when I point out false at a certain rule, I understand clearly put others who will be looking to the configuration file that the rule is turned off, not because you have forgotten to bring it.

**Comment by davidtheclark** [comment]
I'm sorry, I don't think the documentation was as updated as it needed to be. Here is the relevant excerpt that I just updated:

### `rules`

[Rules](/docs/user-guide/rules.md) determine what the linter looks for and complains about.
*No rules are turned on by default*, so this is where you turn on everything you want to check.

**The `rules` property is an object whose keys are rule names and values are rule configurations.**
Each rule configuration fits one of the following formats:

- a single value (the primary option)
- an array with two values (`[primary option, secondary options]`)
- `null` (to turn the rule off)

```json
{
  "rules": {
    "color-no-invalid-hex": true,
    "declaration-colon-space-after": "always",
    "max-empty-lines": 2,
    "indentation": ["tab", {
      "except": ["value"]
    }]
  }
}
```

#### Severities: error & warning

By default, all rules have an "error"-level severity. To downgrade any rule to "warning"-level severity,
pass a secondary option `"warn": true`.

```js
// error-level severity examples
{ "indentation": 2 }
{ "indentation": [2] }

// warning-level severity examples
{ "indentation": [2, { "warn": true } ] }
{ "indentation": [2, {
    "except": ["value"],
    "warn": true
  }]
}
```

Different reporters may use these severity levels in different way, e.g. display them differently, or exit the process differently.

**Comment by davidtheclark** [comment]
@TrySound In v3 any given configuration file can use either format. In v4 we're going to just use the non-numbered format.

@evilebottnawi Let me know if this excerpt doesn't answer all your questions.

**Comment by evilebottnawi** [comment]
@danieldiekmeier how about my feature above? Rules with false value ignored?

**Comment by davidtheclark** [comment]
(You are pinging the wrong person, BTW.)

`null` ignores the rule. `false` is reserved for rules that might have a boolean as their primary option.

**Comment by evilebottnawi** [comment]
@davidtheclark null not work with
```json
"function-whitelist": null,
"property-blacklist": null,
"property-unit-blacklist": null,
"property-unit-whitelist": null,
"property-whitelist": null
```

**Comment by davidtheclark** [comment]
That's a bug. I'll open a new issue for it.
