### ISSUE TITLE
function-calc-no-invalid was removed and replacement is non-existent or  undocumented

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#5713]
### What steps are needed to reproduce the bug?

Have a stylelint config with `function-calc-no-invalid` in it.

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": { "function-calc-no-invalid": "<any value>" }
}
```

### How did you run Stylelint?

Any method

### Which version of Stylelint are you using?

^14

### What did you expect to happen?

No errors or documentation on where to find a replacement

### What actually happened?

Unknown rule function-calc-no-invalid  function-calc-no-invalid

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Write migration/deprecation docs.

--------

This issue discusses moving it to a separate plugin : https://github.com/stylelint/stylelint/issues/4731#issuecomment-623440469

But I can't find it anywhere.

The PR specifically mentions not doing any kind of deprecation cycle : https://github.com/stylelint/stylelint/pull/5296#issuecomment-839734268

This issue just mentions updating a standards config : 
https://github.com/stylelint/stylelint/issues/5653

But it does not explain why this would help or any hint of a replacement.

------------

Can this be rectified?
I understand that some people had strong feelings about removing this rule but guiding the community is important here.

Open questions I have?

- why is running in the browser and performance there even a factor ?!?
- is there a replacement?

**Comment by ybiquitous** [comment]
@romainmenke Thank you for using a template! As far as I know, there seem to be no replacements. 😞 

We have discussed performance and browser support for a long time (see #2454 and #3935).
Also, the `function-calc-no-invalid` rue had a problem with maintainability.

**Comment by jeddy3** [comment]
> Also, the function-calc-no-invalid rue had a problem with maintainability

This was the main reason for its removal. It had a security vulnerability.

> is there a replacement?

As @ybiquitous said, there is no replacement. Stylelint may, in the future, offer more validation if we [migrate some rules to a different parser](https://github.com/stylelint/stylelint/issues/5586). 

I'm going to close the issue as the [migration guide says to remove the rule from your config](https://stylelint.io/migration-guide/to-14#function-calc-no-invalid-rule) and that's all we can suggest at the moment.
