### ISSUE TITLE
stylelint ignoreFiles does not work as expected

### ISSUE THREAD

**Issue by amedee** [stylelint/stylelint#5715]
Please ignore, invalid bug report.

**Comment by zuoxiaobai** [comment]
If it‘s an "No files matching the pattern xx were found" error under lint-staged , you can use "stylelint --allow-empty-input" to fix it, refer to #4712. 

stylelint --fix  'ignoreFiles' will thrown error in current version.

**Comment by amedee** [comment]
Thank you!
