### ISSUE TITLE
"property-unit-blacklist" bug

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#572]
With empty array
```json
{
    "property-unit-blacklist": []
}
```
And not empty array
```json
"property-unit-blacklist": [
            {
                "font-size": ["em", "px"],
                "animation": ["s"]
            }
        ]
```
throw
```bash
[19:13:53] TypeError in plugin 'gulp-postcss'
Message:
    propBlacklist.indexOf is not a function

```

**Comment by davidtheclark** [comment]
What is your version number? Have you tried this in v3.1.0? --- because it sounds like a bug that release fixes.

**Comment by evilebottnawi** [comment]
@danieldiekmeier 3.1.0

**Comment by davidtheclark** [comment]
Oops, sorry. I just noticed that your rule's config is the incorrect structure. It should be an object, not an array. http://stylelint.io/?/src/rules/property-unit-blacklist/README.md
