### ISSUE TITLE
Add `cwd` option to API

### ISSUE THREAD

**Issue by adalinesimonian** [stylelint/stylelint#5720]
Related to #2833, Resolves stylelint/vscode-stylelint#155

### What is the problem you're trying to solve?

Currently, Stylelint resolves paths for certain files it looks for, e.g. `.stylelintignore`, by looking in `process.cwd()`. However, there will be cases such as in `vscode-stylelint` where Stylelint isn't being run in the same working directory as it effectively "should" be, i.e. the directory in which the command would be run if it were being run from the CLI. 

As a result, users of the API need to manually specify the `ignorePath`, which is prohibitive because it means we can't rely on the resolution logic inside Stylelint to locate the path for us.

### What solution would you like to see?

ESLint resolves this very same issue by having a [`cwd` option in the API](https://eslint.org/docs/developer-guide/nodejs-api#parameters). I think we should do the same.

**Comment by ybiquitous** [comment]
The addition looks nice to me. 👍🏼

**Comment by jeddy3** [comment]
SGTM.
