### ISSUE TITLE
I used styledlint to format styled components, but it didn't work

### ISSUE THREAD

**Issue by CGSimplePeople** [stylelint/stylelint#5726]
### What steps are needed to reproduce the bug?

I used styledlint to format styled components, it didn't work, but .less can be formatted

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": ["stylelint-config-standard", "stylelint-config-rational-order", "stylelint-config-prettier"],
  "plugins": ["stylelint-order"],
  "rules": {
    "font-family-no-missing-generic-family-keyword": null,
    "value-keyword-case": null,
    "no-descending-specificity": null,
    "no-empty-source": null,
    "declaration-bang-space-before": null,
    "declaration-block-trailing-semicolon": null,
    "declaration-block-semicolon-newline-after": "always",
    "block-opening-brace-newline-after": "always"
  }
}

### How did you run Stylelint?

.stylelintrc.json

### Which version of Stylelint are you using?

14.0.1

### What did you expect to happen?

formatted styled-components

### What actually happened?

styled-components cannot be formatted, but .less can be formatted

**Comment by jeddy3** [comment]
You'll need to use custom syntaxes to support CSS-in-JS libraries.

See the [migration guide](https://stylelint.io/migration-guide/to-14/#syntax-option-and-automatic-inferral-of-syntax).

**Comment by CGSimplePeople** [comment]
> You'll need to use custom syntaxes to support CSS-in-JS libraries.
> 
> See the [migration guide](https://stylelint.io/migration-guide/to-14/#syntax-option-and-automatic-inferral-of-syntax).

I updated my configuration, but I still can't

 "extends": ["stylelint-config-standard", "stylelint-config-rational-order", "stylelint-config-prettier"],
  "overrides": [
    {
      "files": ["**/*.scss"],
      "customSyntax": "postcss-scss",
      "rules": {
        "at-rule-no-unknown": null
      }
    },
    {
      "files": ["**/*.{js,tsx}"],
      "customSyntax": "@stylelint/postcss-css-in-js",
      "rules": {
        "at-rule-no-unknown": null,
        "block-opening-brace-newline-after": "always"
      }
    }
  ],
  "plugins": ["stylelint-order"],
  "rules": {
    "font-family-no-missing-generic-family-keyword": null,
    "value-keyword-case": null,
    "no-descending-specificity": null,
    "no-empty-source": null,
    "declaration-bang-space-before": null,
    "declaration-block-trailing-semicolon": null,
    "declaration-block-semicolon-newline-after": "always",
    "block-opening-brace-newline-after": "always"
  },
