### ISSUE TITLE
Need report error by `selector-combinator-space-after`.

### ISSUE THREAD

**Issue by NWYLZW** [stylelint/stylelint#5727]
### What steps are needed to reproduce the bug?

dependencies
```
"postcss": "^8.3.11",
"postcss-scss": "^4.0.2",
"stylelint": "^14.1.0",
```
code
```scss
// selector-combinator-space-after error
a>b {}
// selector-combinator-space-after no error
a {
  >b {}
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-combinator-space-after": ["always"]
  }
}
```

### How did you run Stylelint?

stylelint src/**/*.{html,vue,css,sass,scss,less}

### Which version of Stylelint are you using?

16.13

### What did you expect to happen?

I think here should also check.
```scss
// selector-combinator-space-after no error
a {
  >b {}
}
```

### What actually happened?

no report error, need report error.

### Does the bug relate to non-standard syntax?

Yes, it's related to scss nested properties.

**Comment by jeddy3** [comment]
Thanks for the report.

The built-in rules are designed for CSS, and the following isn't valid CSS.

```scss
a {
  >b {}
}
````

You'll need to use an explicit _nesting selector_ (`&`) for it to be valid, like so:

```css
a {
  & >b {}
}
```

[See demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYAdAdilAyFAfAEZoC+W5mIANCAM4CemALkgB4Lh103gSYAzAJYBzThmwp0IAE4BXADYw60+Giw4c0pMwC08pbswRdczAGtjAd0yqUzeTGobN0ogohhzRkzAC2AA7MDHYOck4uWnweMj66QpgAbkgKQlC6ABYwbKGOzpJRkH5+MCxx-kEhCPZ5kVLgcnTMEH66ATIQATAywXF+QtwJIrrJsQJmYMxC-Lnh+Zr1sGAKSDI605i67p7exrpQcgGpYDowumCNza3tnd1TyrMRBYswy6vr-FseXnEHR0InZhnG5dHpCB7VADadRwYSeCxwEgRrhAomMMhgdmhz2R0kgmDorzkU0SZz+x1OdF0ViEzAy+yEAgE3VKemSCnCKhAMM0AF0eZQFrz5iilis1lNPtsfns6BkID0MkhMOkQXcGLoIKSZDI0hC1HCRVEBPw9AIkP0FBq9uSAacjBb9TU5nVpCayubLdaTP1BphhiJSt0AbpPUIrbpzDAGFYFVBHkb6uNMJMNucUmA4mY6AEkGAYOlbhKFQnXSBk6nPqlMDBVroRGsoOCyntjATWCrVukmxjK7Zqoay1GGAI1iV9q9xR9NnshIEFR3mKXntISk2kKHa8w5BiHeO9mZLBAbMuFtJMI70g20rpVrWqbOkik0qeUTblPmVUNdDnXoyAbSVQGrUK4gDahwUkCt56HOAQLvoihOoOoHgf8gJnISSiTAqXLAS6KG+IEvR0BAO75q+UR7NkDgboS-SQB4BIUfUj7sjeUCke4GErHK5wtCULC4c68JviYCRsaqEB0LSaY6PE849AhSjMeeYk6jAIiKHWVgZLSyi5uRA4gWeIBqj03qmBY1j9nhIlRJhrzNLEASEnIHHnDxD4mIe1kqfQMBYU5bSue5AX+KyWZWceNnCYm0gOdhsTBF0kVHieUI8shyJIsi9RogqmIZTiCJ4pcLS6GFAnMFyPI4PyxWCnycX0A436tjAVjVoVtnNWYtKpb5Rn4SZKQBEqIwpOEPisJKMXYripndJ+rCBtIiaIrV9TZPmQQAAodKC9xCfNuVRJ0eaAdIm31cijV1c1ckGGcFS9F1WwwCaGJYjy2gKFYSAMFy63qMVUTbTAQTfaDKLSuYSjcLeAhArEdCOnuZyw-DQObcaQgyE0RjKEC8bctDwqbdI+VfUVp1REgSPdHxxSsldZMCnU5OgY9iHo+mhJ2NIHhWN0a1ltzhgXuOOZ5mc9PIwLyB-QDVLSf6hhdaLXN6E9cSkiqCptBiwg5ENdn1OLGH+ACECMYTnUJLLDMyArKT-YDmsmbDHlSd+RBrPmFVERqb1EB9BUKzW2oezD3zeMsPv+ls-tnDW9s1oj8vVL9bvY6BXvx6rwx+zLdsh2H1NqNnyu6H4ihTLoGs0GW+ceIXScl9LAeh593Xm0rgM-kM6sO9HURe7cmC+8npcOxnItZ4rOc13XQgNyPTd57HmpdJPifFwHneO5nleL9XhfDzWo-1OPO9Tx3BkY+XvdV+7G8mQxBsVrN03TgrfjQN0fszUP6xCyGwPmz8QBC3nsAm2BswEN1KCIOkCs5QLivnifiEUXrB1nt3cONMSqn1fsDHKC1waQ0IadN0eMCY1iaAWVmp1ObUNRCIdEvcTqsKaAwJQ1Y9BFD8MqKANU2YNQ5rA5mZQdJ6UPvEAkeoXb91zu-Mq1wDrqkDpUNe6d8EVxQFwlErtlZXw2tDaQFClxUNytoJ25w1GGyLMEUxRDhD4z0PQ4mTDcosJsWwjhUNabmzsYIlmb9aaUwUbAQeaszgh1jt45EN0ER3RQL4woDi1xCA3LmZgyM5o-RAAAPQABSQg3AAL15OU3QFSAAMugACcvIABUABKEpugan1KabyAA1G0lpAASFxZCiElG4EgVaC8ACibAuiTALCgC4TQWgoCyagAAjuEGQDAUCSxgPYCAKBQ4oCjEQJARAIGJM0Kk9J9QVlXEcYdDUuT8mBKIaU7p1TKkNOae0zp3S-n9MGSM8JCwxkmQmajaZJ85kLOJsstRKAzLBH2Y6I5JzDnnMudc0mt0JFljFO8b+FzE5yLlvPE+kcYFEsnCStMZLhhyL0ZA4xJC6VvAlIyredFra21Tm9SlzsF7sqpLXBQ9dG7NWJdyqUvKrYf02BSp2Sil7nzievGV9K5WbC9nypVP4H7vR7hHGAUdwUvC5dOL4OwYkiAvmcIR4DZXTiEgARm1da0lW8aLhm-AauBMUX4qNFDqm1Xs9gYgOJ2MojERBKhVM8u44IhJZTDd6tMhrBWz2FWq6uEqpVas5VOb+hqVXHz7uqoemrL6WukK6stQajUl1ZWai1XrS1phwTox+prrF02UaMimIBLEfNYcKicmaZiWoWm4uhRNGH4p8cDKIVNOE42CcjJmVUXEmQSNJaJGre22q8DcoU7Nnj3LdKaUMFpwzWjRtsiAQIhIhupFkXcvYsEqiXc1L+Wb+IbhzenPNorlHL0lavaVZYAOfEEbRY1YGT5ivtY6jB5YJhNuKIh1tT9220tAnBzYzqtGvQdkJOp-6sNpgOXik+0CRXUZTN-XMGIWBZEJA+Dqb0D2KPA0vQt0Hi1EZo58NjrJOPKBbQHPjsACMoxrb2jDxHTAyAULoZ9r780ctEyxtMMjX1IdVQJkx9aQAZCmrABsMAU4vt-qK2JGGEiwBYA5tQAAmZqw5RyOgfGjN5gDx0oi+ZUn5tTgUAq6b83pAzhnDvMSAaFUzIHwscksnzY5DkHMxacnFVyTj82XQsO5zUlD+jpLU7oJgDyTysT1MspGe1dQ9c1Ujb1yvIIyHYd1HmqONYLNkzcOgdxnHLcZytIaMMbOG9uXc428P9upeawjULBsbmZCN3cdHCuQMY9N9bs3Ru8z2HrDizkjZCBNg10CM3NtzeBHeDjyhpNyLk5AmlTGBvriO1+5UgZt7dB0AbCtVKq1mba4d+7x21j+jOEWYHKNjVttM7ptbP3tndFwQTBDM9QMmZQxBoTynzMzcx7steOOgMyaPmD99x6YO3cO+T7HAjqcsvwwvT7GGqJB1DLQvQjcbsmSojbD9siH5+T2L6NupRCwCB-KRGQAcQO93TZROQfhQ6xCUEgJsicKnVZ06GjXWvGakfaH+aSM61AABZmqYE19ruIfrqzDENx0NNxkUSoo1LthW+3zO+91nLg2lvjZ+R1s1vBnO1CGMHYJleJPSEjrHQO1xAvCYMJJtdVdeV2EELj5u2x27QksHPXyS9QpmoJSCjoVqRBiQY39lGaqNP5GHo+ytr7oFa8G3r7qRvUEEdBVByK5bHayx99iAPoQQ-4egkR+3lHE-Vsomn9BBvTfNNyBfU6Kb5mN9vARoFmQBTirSFC7U8LPT-kdOixF2LoKEusOS7C+oaXFlQGWZ5FA0-cvYowAXIFZIBFZV5NRT5hSJRMxEAJBL5j7G4YZH4tCwEXij7I6x7g5o7r5QFBSwB0CfhQDKhs5a5wFBStifCHx+Qb43in7n4LRX5VJAq9JRbMHNJxZgop6JZv6pbzLpbf5pB-64EKgAFnJAG4r+7Fa3KEq97CE64DAkFCJ4607j5YEm71Ab6pBU44bL6YHnjd5IFyE1zsBka4L0J2D9ayGBQGynah4XYfRXbUFGEuQwBuQmDH5UiSEMbHhr72TOEhTuGeRtBPZ0gvYqzGrvYKaGHWHOQBEVRKBVT0b1CB417+GuGhQJERTZr2azQKwcRyBcTRGOQGzJRjagF7Y+E94mRoKKjCLJrmRxDRpmBEFlDsicjUGtSJxab74gD5GFHmZ9QCLlEB6VEYZtFnDDixgyDpBeHJGjHmbjGU6KHAY8a5oE5qGQZFp1rNSLFaHLHt7IYbEM4iYmS7EKE7q4Zdx6FgQGELGTSaoExNZ84tYWE7H3Eh76z2ER6mwuCUCkAgCkBAA).

Stylelint can be extended to support non-CSS constructs using plugins, though.

You can raise an issue in [the stylelint-scss plugin](https://github.com/stylelint-scss/stylelint-scss) to see if they'll support implicit nesting for this type of rule.

**Comment by NWYLZW** [comment]
> Thanks for the report.
> 
> The built-in rules are designed for CSS, and the following isn't CSS.
> 
> ```css-scss
> a {
>   >b {}
> }
> ```
> 
> You'll need to use an explicit _nesting selector_ (`&`) for it to be CSS, like so:
> 
> ```css
> a {
>   & >b {}
> }
> ```
> 
> [See demo](https://stylelint.io/demo#N4Igxg9gJgpiBcICGACYAdAdilAyFAfAEZoC+W5mIANCAM4CemALkgB4Lh103gSYAzAJYBzThmwp0IAE4BXADYw60+Giw4c0pMwC08pbswRdczAGtjAd0yqUzeTGobN0ogohhzRkzAC2AA7MDHYOck4uWnweMj66QpgAbkgKQlC6ABYwbKGOzpJRkH5+MCxx-kEhCPZ5kVLgcnTMEH66ATIQATAywXF+QtwJIrrJsQJmYMxC-Lnh+Zr1sGAKSDI605i67p7exrpQcgGpYDowumCNza3tnd1TyrMRBYswy6vr-FseXnEHR0InZhnG5dHpCB7VADadRwYSeCxwEgRrhAomMMhgdmhz2R0kgmDorzkU0SZz+x1OdF0ViEzAy+yEAgE3VKemSCnCKhAMM0AF0eZQFrz5iilis1lNPtsfns6BkID0MkhMOkQXcGLoIKSZDI0hC1HCRVEBPw9AIkP0FBq9uSAacjBb9TU5nVpCayubLdaTP1BphhiJSt0AbpPUIrbpzDAGFYFVBHkb6uNMJMNucUmA4mY6AEkGAYOlbhKFQnXSBk6nPqlMDBVroRGsoOCyntjATWCrVukmxjK7Zqoay1GGAI1iV9q9xR9NnshIEFR3mKXntISk2kKHa8w5BiHeO9mZLBAbMuFtJMI70g20rpVrWqbOkik0qeUTblPmVUNdDnXoyAbSVQGrUK4gDahwUkCt56HOAQLvoihOoOoHgf8gJnISSiTAqXLAS6KG+IEvR0BAO75q+UR7NkDgboS-SQB4BIUfUj7sjeUCke4GErHK5wtCULC4c68JviYCRsaqEB0LSaY6PE849AhSjMeeYk6jAIiKHWVgZLSyi5uRA4gWeIBqj03qmBY1j9nhIlRJhrzNLEASEnIHHnDxD4mIe1kqfQMBYU5bSue5AX+KyWZWceNnCYm0gOdhsTBF0kVHieUI8shyJIsi9RogqmIZTiCJ4pcLS6GFAnMFyPI4PyxWCnycX0A436tjAVjVoVtnNWYtKpb5Rn4SZKQBEqIwpOEPisJKMXYripndJ+rCBtIiaIrV9TZPmQQAAodKC9xCfNuVRJ0eaAdIm31cijV1c1ckGGcFS9F1WwwCaGJYjy2gKFYSAMFy63qMVUTbTAQTfaDKLSuYSjcLeAhArEdCOnuZyw-DQObcaQgyE0RjKEC8bctDwqbdI+VfUVp1REgSPdHxxSsldZMCnU5OgY9iHo+mhJ2NIHhWN0a1ltzhgXuOOZ5mc9PIwLyB-QDVLSf6hhdaLXN6E9cSkiqCptBiwg5ENdn1OLGH+ACECMYTnUJLLDMyArKT-YDmsmbDHlSd+RBrPmFVERqb1EB9BUKzW2oezD3zeMsPv+ls-tnDW9s1oj8vVL9bvY6BXvx6rwx+zLdsh2H1NqNnyu6H4ihTLoGs0GW+ceIXScl9LAeh593Xm0rgM-kM6sO9HURe7cmC+8npcOxnItZ4rOc13XQgNyPTd57HmpdJPifFwHneO5nleL9XhfDzWo-1OPO9Tx3BkY+XvdV+7G8mQxBsVrN03TgrfjQN0fszUP6xCyGwPmz8QBC3nsAm2BswEN1KCIOkCs5QLivnifiEUXrB1nt3cONMSqn1fsDHKC1waQ0IadN0eMCY1iaAWVmp1ObUNRCIdEvcTqsKaAwJQ1Y9BFD8MqKANU2YNQ5rA5mZQdJ6UPvEAkeoXb91zu-Mq1wDrqkDpUNe6d8EVxQFwlErtlZXw2tDaQFClxUNytoJ25w1GGyLMEUxRDhD4z0PQ4mTDcosJsWwjhUNabmzsYIlmb9aaUwUbAQeaszgh1jt45EN0ER3RQL4woDi1xCA3LmZgyM5o-RAAAPQABSQg3AAL15OU3QFSAAMugACcvIABUABKEpugan1KabyAA1G0lpAASFxZCiElG4EgVaC8ACibAuiTALCgC4TQWgoCyagAAjuEGQDAUCSxgPYCAKBQ4oCjEQJARAIGJM0Kk9J9QVlXEcYdDUuT8mBKIaU7p1TKkNOae0zp3S-n9MGSM8JCwxkmQmajaZJ85kLOJsstRKAzLBH2Y6I5JzDnnMudc0mt0JFljFO8b+FzE5yLlvPE+kcYFEsnCStMZLhhyL0ZA4xJC6VvAlIyredFra21Tm9SlzsF7sqpLXBQ9dG7NWJdyqUvKrYf02BSp2Sil7nzievGV9K5WbC9nypVP4H7vR7hHGAUdwUvC5dOL4OwYkiAvmcIR4DZXTiEgARm1da0lW8aLhm-AauBMUX4qNFDqm1Xs9gYgOJ2MojERBKhVM8u44IhJZTDd6tMhrBWz2FWq6uEqpVas5VOb+hqVXHz7uqoemrL6WukK6stQajUl1ZWai1XrS1phwTox+prrF02UaMimIBLEfNYcKicmaZiWoWm4uhRNGH4p8cDKIVNOE42CcjJmVUXEmQSNJaJGre22q8DcoU7Nnj3LdKaUMFpwzWjRtsiAQIhIhupFkXcvYsEqiXc1L+Wb+IbhzenPNorlHL0lavaVZYAOfEEbRY1YGT5ivtY6jB5YJhNuKIh1tT9220tAnBzYzqtGvQdkJOp-6sNpgOXik+0CRXUZTN-XMGIWBZEJA+Dqb0D2KPA0vQt0Hi1EZo58NjrJOPKBbQHPjsACMoxrb2jDxHTAyAULoZ9r780ctEyxtMMjX1IdVQJkx9aQAZCmrABsMAU4vt-qK2JGGEiwBYA5tQAAmZqw5RyOgfGjN5gDx0oi+ZUn5tTgUAq6b83pAzhnDvMSAaFUzIHwscksnzY5DkHMxacnFVyTj82XQsO5zUlD+jpLU7oJgDyTysT1MspGe1dQ9c1Ujb1yvIIyHYd1HmqONYLNkzcOgdxnHLcZytIaMMbOG9uXc428P9upeawjULBsbmZCN3cdHCuQMY9N9bs3Ru8z2HrDizkjZCBNg10CM3NtzeBHeDjyhpNyLk5AmlTGBvriO1+5UgZt7dB0AbCtVKq1mba4d+7x21j+jOEWYHKNjVttM7ptbP3tndFwQTBDM9QMmZQxBoTynzMzcx7steOOgMyaPmD99x6YO3cO+T7HAjqcsvwwvT7GGqJB1DLQvQjcbsmSojbD9siH5+T2L6NupRCwCB-KRGQAcQO93TZROQfhQ6xCUEgJsicKnVZ06GjXWvGakfaH+aSM61AABZmqYE19ruIfrqzDENx0NNxkUSoo1LthW+3zO+91nLg2lvjZ+R1s1vBnO1CGMHYJleJPSEjrHQO1xAvCYMJJtdVdeV2EELj5u2x27QksHPXyS9QpmoJSCjoVqRBiQY39lGaqNP5GHo+ytr7oFa8G3r7qRvUEEdBVByK5bHayx99iAPoQQ-4egkR+3lHE-Vsomn9BBvTfNNyBfU6Kb5mN9vARoFmQBTirSFC7U8LPT-kdOixF2LoKEusOS7C+oaXFlQGWZ5FA0-cvYowAXIFZIBFZV5NRT5hSJRMxEAJBL5j7G4YZH4tCwEXij7I6x7g5o7r5QFBSwB0CfhQDKhs5a5wFBStifCHx+Qb43in7n4LRX5VJAq9JRbMHNJxZgop6JZv6pbzLpbf5pB-64EKgAFnJAG4r+7Fa3KEq97CE64DAkFCJ4607j5YEm71Ab6pBU44bL6YHnjd5IFyE1zsBka4L0J2D9ayGBQGynah4XYfRXbUFGEuQwBuQmDH5UiSEMbHhr72TOEhTuGeRtBPZ0gvYqzGrvYKaGHWHOQBEVRKBVT0b1CB417+GuGhQJERTZr2azQKwcRyBcTRGOQGzJRjagF7Y+E94mRoKKjCLJrmRxDRpmBEFlDsicjUGtSJxab74gD5GFHmZ9QCLlEB6VEYZtFnDDixgyDpBeHJGjHmbjGU6KHAY8a5oE5qGQZFp1rNSLFaHLHt7IYbEM4iYmS7EKE7q4Zdx6FgQGELGTSaoExNZ84tYWE7H3Eh76z2ER6mwuCUCkAgCkBAA).
> 
> Stylelint can be extended to support non-CSS syntax using 3rd party plugins, though.
> 
> You can raise an issue in [the stylelint-scss plugin](https://github.com/stylelint-scss/stylelint-scss) to see if they'll support implicit nesting for this type of rule.

ok, thx

**Comment by NWYLZW** [comment]
I fixed it.
[Nest css in scss `selector-combinator-space-after`](https://gist.github.com/NWYLZW/a0fc792fc5c3e0c6a43a69d9a35acf43)
