### ISSUE TITLE
Add support for shorthands in `extends` and `plugins`

### ISSUE THREAD

**Issue by fsmaia** [stylelint/stylelint#5745]
### What is the problem you're trying to solve?

Currently, we have to repeat the `stylelint-config-` prefix over and over in the `extends` field, the same for `stylelint-plugin` in the `plugins` field.

Similarly to ESLint, it would be nice to support the absence of the prefix, as in the following example:

Before:
```js
module.exports = {
  extends: ['stylelint-config-recommended', 'stylelint-config-prettier', 'stylelint-config-rational-order', @myorg/stylelint-config]
};
```

After:
```js
module.exports = {
  extends: ['recommended', 'prettier', 'rational-order', '@myorg'],
};
```

Not only this makes the config file more declarative, but it also encourages the community to publish their configs/plugins with the canonical name, and then this will leverage their packages (and the whole stylelint ecosystem) popularity.

### What solution would you like to see?

I would like to see support for the following shorthands, adding a `require.resolve` chain:

`extends`:
1. `stylelint-config-{config}`
2. `{org}/stylelint-config`
3. `{config}`
4. 
`plugins`:
1. `stylelint-plugin-{plugin}`
2. `{org}/stylelint-plugin`
3. `{plugin}`

I have implemented this same feature in [Docusaurus](https://github.com/facebook/docusaurus/pull/5930), and I would be glad to port it to this repository too.

**Comment by jeddy3** [comment]
@fsmaia Thanks for the request and for using the template.

This has come up before and we decided to not add this feature, preferring to keep the logic simple and explicit.

However, I'll label as a discussion to see if the sentiment has changed since then.

**Comment by fsmaia** [comment]
Okay! I'll wait for more inputs then.

I really see a huge advantage in this, the whole ecosystem grows as more and more packages are published with the correct name, in the convention-over-configuration flavor.

From the point of view of implementation, it's simple too, we would run a `map()` inside the `getModulePath` to get the first successful resolution. As we use `resolve-from`, there is no need to wrap the resolve inside a `try`/`catch`.

From the point of view of implicitness, the only downside/caveat/possible ambiguity is when the project has both the package with and without the alias, ex.: `moment` and `stylelint-config-moment`. Is this the major problem or is it the "magic" resolution?

**Comment by jeddy3** [comment]
As there are no objections to this proposal, I'll label as ready to implement so that we align with the behaviour of tools like ESLint and Docusaurus.

> I have implemented this same feature in https://github.com/facebook/docusaurus/pull/5930, and I would be glad to port it to this repository too.

@fsmaia That would be fantastic!

**Comment by ybiquitous** [comment]
When I've finished reading ESLint's [blog post](https://eslint.org/blog/2022/08/new-config-system-part-1/) about its new config system, I start doubting if this issue's flexible shorthand feature is really necessary. Because it seems to me that the increased complexity of our code base will be worse than improved usability through the new shorthand support.

What do you think regarding this opinion?

**Comment by jeddy3** [comment]
That's blog post is a great read.

>  I start doubting if this issue's flexible shorthand feature is really necessary

It's not, especially if we hope to migrate to a similar flat config system in the future.

As an aside, we're close to a flat config system as an early design decision was not to implement cascading configs. I'm glad we made this decision. 

[From the blog post](https://eslint.org/blog/2022/08/new-config-system-part-1/#the-extends-key):

> In hindsight, if we had thought things through a little more, we would have removed the configuration cascade at this point. Introducing extends enabled a lot of the same use cases as the cascade, and keeping both turned out to be a mess that we would spend years trying to fix.
As an aside,

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the response. I agree. 👍🏼
