### ISSUE TITLE
Use codecov for coverage

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#5748]
## What is a problem

Builds on Coveralls have not worked for a while:
https://coveralls.io/github/stylelint/stylelint

Even when seeing the log of GitHub Actions, we cannot know anything... 🤷🏼 
https://github.com/stylelint/stylelint/runs/4336137130?check_suite_focus=true#step:8:8

I've resynced with the GitHub repository on the Coveralls repo settings, but errors still occur:
https://github.com/stylelint/stylelint/pull/5743#issuecomment-980070312

## How to solve

So, I think there are the following options:
1. Stop using Coveralls
2. Migrate to another service

For example, [Codecov](https://codecov.io/) is an option. When I've tried my forked repository, it works:
- https://codecov.io/gh/ybiquitous/stylelint/tree/401071d44695a610413a926fef873916ab66c102
- https://github.com/ybiquitous/stylelint/runs/4346303358?check_suite_focus=true#step:8:32
- https://github.com/ybiquitous/stylelint/pull/2

Does anyone have thoughts?

**Comment by jeddy3** [comment]
Let's give Codecov a whirl.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the response. I've created PR #5749!

**Comment by ybiquitous** [comment]
Done! 🎉 

https://app.codecov.io/gh/stylelint/stylelint
