### ISSUE TITLE
I don't understand what having the number  2 as the first config means in rule-properties-order

### ISSUE THREAD

**Issue by onlywei** [stylelint/stylelint#575]
In this doc page, near the bottom there is a section about "unspecified":
http://stylelint.io/?/src/rules/rule-properties-order/README.md

It gives the configuration example: `[2, ["color", "background"], { unspecified: "ignore" }]`.

However, I don't understand what the first element in that array means. It's just a 2. It makes sense to me for the indentation rule, but I don't know what it means here. Is it supposed to behave like eslint?

**Comment by jeddy3** [comment]
@onlywei Thanks for reporting. That's a mistake in the documentation, which is being addressed in the referenced PR.

> Is it supposed to behave like eslint?

FYI, in versions prior to `3.0.0` the configuration syntax behaved like eslint. In `3.0.0` the configuration syntax changed, but I accidentally missed this bit of documentation when updating the examples. Sorry about the confusion.
