### ISSUE TITLE
Add option to force no empty-lines between rule-properties-order groups

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#578]
Responsible for setting newline between groups of properties. 
Options: `always`, `never`. For value `null` that means it does not matter.
We work as a team and some members of the team put the newline between the groups, some are not, so code losing the general code style. I would like to be able to verify and control over put of new lines between groups of properties.

**Comment by davidtheclark** [comment]
Does the existing method of grouping and using `emptyLineBefore` not work for you?

**Comment by evilebottnawi** [comment]
@davidtheclark emptyLineBefore `If true, this group must be separated from other properties by an empty newline.`, but does not prohibit the line bet. Maybe modify behaviour this options on `always`, `never`, `null`? For lint empty line before between group.

**Comment by davidtheclark** [comment]
OK. I changed the title to reflect the request. Ideally we could do this without a breaking change, but if a breaking change is the way to go, we'd want to keep the existing functionality alongside the new with a deprecation warning until the next major release.

**Comment by dan-gamble** [comment]
@davidtheclark or @jeddy3 would i be able to get some feedback RE: https://github.com/dan-gamble/stylelint/commit/871a99f8d9ed27a3422d0475d1d36568d7ba51dd#diff-0236e9e46bfa4cab2f1c2d280a77996cR113

**Comment by dan-gamble** [comment]
I've opened a PR for this here: https://github.com/stylelint/stylelint/pull/809

**Comment by jeddy3** [comment]
Done in #809
