### ISSUE TITLE
Class extends value undefined is not a constructor or null at Object.

### ISSUE THREAD

**Issue by jiaxun-yang** [stylelint/stylelint#5791]
### What steps are needed to reproduce the bug?

When I update stylelint from 13.13.1 to 14.1.0, stylelint-scss 3.20.1 to 4.0.1.
Whether it is running the git commit command，or open less file in vscode，always show error
`TypeError: Class extends value undefined is not a constructor or null at Object.<anonymous> (/Users/jiaxun_yang/projects/optimix-opx_compose/solution/optimix-opx_frontend/node_modules/postcss-scss/lib/nested-declaration.js:3:33) at Module._compile (internal/modules/cjs/loader.js:1125:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10) at Module.load (internal/modules/cjs/loader.js:982:32) at Module._load (internal/modules/cjs/loader.js:823:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12913) at Module.require (internal/modules/cjs/loader.js:1006:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/Users/jiaxun_yang/projects/optimix-opx_compose/solution/optimix-opx_frontend/node_modules/postcss-scss/lib/scss-parser.js:4:25) at Module._compile (internal/modules/cjs/loader.js:1125:30)`
and this is my lint-staged
```
"lint-staged": {
    "packages/**/*.{ts,tsx,js,jsx}": [
      "eslint --fix"
    ],
    "packages/**/*.{md,json}": [
      "prettier --write"
    ],
    "packages/**/*.{scss,sass}": [
      "stylelint --syntax=scss",
      "prettier --parser scss --write"
    ],
    "packages/**/*.less": [
      "stylelint --syntax=less",
      "prettier --parser less --write"
    ]
  },
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "plugins": [
    "stylelint-scss"
  ],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss"
  ]
}
```

### How did you run Stylelint?

git commit or open less file in vscode

### Which version of Stylelint are you using?

14.1.0

### What did you expect to happen?

no error

### What actually happened?

```
TypeError: Class extends value undefined is not a constructor or null at Object.<anonymous> (/Users/jiaxun_yang/projects/optimix-opx_compose/solution/optimix-opx_frontend/node_modules/postcss-scss/lib/nested-declaration.js:3:33) at Module._compile (internal/modules/cjs/loader.js:1125:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10) at Module.load (internal/modules/cjs/loader.js:982:32) at Module._load (internal/modules/cjs/loader.js:823:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12913) at Module.require (internal/modules/cjs/loader.js:1006:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/Users/jiaxun_yang/projects/optimix-opx_compose/solution/optimix-opx_frontend/node_modules/postcss-scss/lib/scss-parser.js:4:25) at Module._compile (internal/modules/cjs/loader.js:1125:30)
```

### Proposal to fix the bug

When I search this question in internet, I tried remove node_modules and run npm i again，but error stilly exist

**Comment by jeddy3** [comment]
Thanks for using the template.

The `syntax` option has [been removed](https://stylelint.io/migration-guide/to-14). Used the `overrides` and `customSyntax` [configuration properties](https://stylelint.io/user-guide/configure) instead.

Try:

```json
{ 
  "lint-staged": {
    "packages/**/*.{ts,tsx,js,jsx}": [
      "eslint --fix"
    ],
    "packages/**/*.{md,json}": [
      "prettier --write"
    ],
    "packages/**/*.{scss,sass,less}": [
      "stylelint --fix",
      "prettier --write"
    ]
  }
}
```

And:

```json
{
  "extends": ["stylelint-config-standard-scss"],
   "overrides": [{
      "files": "**/*.sass",
      "customSyntax": "postcss-sass"
    }, {
      "files": "**/*.less"
      "customSyntax": "postcss-less"
  }]
}
```

You'll need to install stylelint-config-standard-scss, postcss-sass and postcss-less.
