### ISSUE TITLE
Support autofix for `font-family-name-quotes` rule

### ISSUE THREAD

**Issue by MrBrN197** [stylelint/stylelint#5805]
### What steps are needed to reproduce the bug?

create a css file with
```css
body {
  margin: 0;
  font-family: "Roboto", sans-serif;
}
```
enable rule `'font-family-name-quotes': 'always-where-recommended'`

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "font-family-name-quotes": "always-where-recommended"
  }
}
```

### How did you run Stylelint?

`stylelint index.css --fix`

### Which version of Stylelint are you using?

`14.2.0`

### What did you expect to happen?

`"Roboto"` should be converted to `Roboto` after `--fix` flag.

### What actually happened?

`--fix` does not automatically fix the problem.

### Proposal to fix the bug

I have a hunch that this was working in `stylelint@13` but I'm not sure. either way shouldn't this be an automatically fixable problem by removing the quotes on font family names that don't have spaces or misc symbols.

**Comment by ybiquitous** [comment]
@MrBrN197 Thanks for using the template and reporting the issue!
Currenty, the [`font-family-name-quotes`](https://stylelint.io/user-guide/rules/list/font-family-name-quotes/) rule doesn't have an *autofix* option.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add an *autofix* option](https://stylelint.io/developer-guide/rules#add-autofix) in the Developer guide.

Also, we're discussing freezing all stylistic rules (including `font-family-name-quotes`) with #5674, but I think it's acceptable to add an *autofix* option to an existing rule for now.

**Comment by MrBrN197** [comment]
@ybiquitous Hi, I took some time to look at the code and see what I could figure out. I've created a PR for it. There is some information on the PR description that I'd like clarification on if you can.
