### ISSUE TITLE
Look for eslint like config file names such as .stylelintrc.json

### ISSUE THREAD

**Issue by mickvangelderen** [stylelint/stylelint#583]
Eslint recommends using a file extension that conveys the format: http://eslint.org/docs/user-guide/configuring#configuration-file-formats

I like this change because it is clearer, future proof and allows generic tools to analyze the files properly. Highlighting by editors for example becomes more reliable. 

Could stylelint be updated to look for .stylelintrc.json and .stylelintrc.yaml?

**Comment by davidtheclark** [comment]
Yep. We are loading the configs via cosmiconfig, and I have an issue open over there to do just this: https://github.com/davidtheclark/cosmiconfig/issues/18

**Comment by mickvangelderen** [comment]
Good to hear :+1:
