### ISSUE TITLE
Add support for meta.url to enable links in terminal

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#5842]
### What is the problem you're trying to solve?

As discussed with #2622, I think it is very useful if stylelint rules (including plugins) could have metadata with doc URL, deprecated, etc. [like ESLint](https://eslint.org/docs/developer-guide/working-with-rules#rule-basics).

For example, use cases:

- Tools or plugins like [stylelint-find-rules](https://github.com/alexilyaev/stylelint-find-rules)
- Create rule links on a terminal (see #5835)
- Generate a simple document for rules
- and so on...

Actually, we had metadata with the `deprecated` property:

https://github.com/stylelint/stylelint/blob/16b4595496f54fa52182fafe9d75e78691b38261/lib/rules/at-rule-blacklist/index.js#L62

Also, the Stylelint document below has described rule metadata:

https://github.com/stylelint/stylelint/blob/9e75552d5da4f4448208a65b0c6f876ef9a0feb0/docs/developer-guide/rules.md#L198

### What solution would you like to see?

I propose to define a metadata schema via the document and type definitions (TypeScript).

For example of a rule with metadata:

```js
// lib/rules/color-no-invalid-hex/index.js
rule.ruleName = ruleName;
rule.messages = messages;

rule.meta = {
  type: 'problem', // or 'convention' etc.
  docs: {
    description: 'Disallow invalid hex colors.',
    url: 'https://stylelint.io/user-guide/rules/list/color-no-invalid-hex',
  },
  deprecated: false,
  fixable: true,
  schema: [
    { type: 'boolean' }, // primary
  ],
};

module.exports = rule;
```

For the `Rule` type of the TypeScript definitions, we would add a `meta` property:

https://github.com/stylelint/stylelint/blob/9e75552d5da4f4448208a65b0c6f876ef9a0feb0/types/stylelint/index.d.ts#L154-L164

**Comment by jeddy3** [comment]
SGTM. I suggest we start with `meta.url` so that plugins can opt into the terminal links. We can open up follow up issues for other properties as we need them / want to work on them.

Should we explicitly define the URL for the built-in rules or continue to build it from the rule name?

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the feedback!

I agree with the small start to add `meta.url`. 👍🏼 

And, I think it better to "explicitly define the URL for the built-in rules" like [ESLint does](https://github.com/eslint/eslint/blob/670f48113708b556e8ba870607766cb4707791cf/lib/rules/no-console.js#L26). It is straightforward and doesn't require any extra build steps.

**Comment by jeddy3** [comment]
Labelled as ready.

Let's include updating the plugin docs as part of the pull request.
