### ISSUE TITLE
Add function-no-unknown

### ISSUE THREAD

**Issue by gnuletik** [stylelint/stylelint#5853]
### What is the problem you're trying to solve?

I'm looking for a list of known CSS functions in order to catch typo errors.

see https://github.com/stylelint-scss/stylelint-scss/issues/581#issuecomment-1017484418

### What solution would you like to see?

1. Stylelint could export a list of known CSS functions that could be imported inside stylelint.config.js
2. Stylelint could provide a rule `function-no-unknown` which throws errors for unknown functions

**Comment by jeddy3** [comment]
@gnuletik Thanks for the request.

The [`stylelint-csstree-validator`](https://github.com/csstree/stylelint-validator) plugin will catch this for you.

Having said that, spotting unknown functions is a simple use case that users [who don't wish to use the CSSTree validator would benefit from](https://stylelint.io/about/linting#validators). There is also a lot of innovation happening in the CSS parser world and [we may use a different parser (or a combination of parsers) in the future](https://github.com/stylelint/stylelint/issues/5586), which may have better syntax validation. While we wait for the dust to settle on those innovations, we can add a `function-no-unknown` rule.

We can use the [`css-functions-list`](https://www.npmjs.com/package/css-functions-list) package.

The rule should ignore doubled dashed custom functions by default, e.g. `--custom-function()`.

What does everyone think?

**Comment by ybiquitous** [comment]
Using the `css-functions-list` package for a new `function-no-unknow` rule sounds good to me. 👍🏼

**Comment by gnuletik** [comment]
Thanks for the quick answer!

`stylelint-csstree-validator` is exactly what I was looking for!

Also, having a `function-no-unknown` rule would also be a great solution for simple use cases.

**Comment by jeddy3** [comment]
> stylelint-csstree-validator is exactly what I was looking for!

Yeah, that plugin is amazing. It has full syntax validation for declaration property/value pairs and at-rules. You may find you need to turn off most of Stylelint's built-in `*-no-unknown` rules when using it.

> Using the css-functions-list package for a new function-no-unknown rule sounds good to me. 👍🏼

Okay, let's go with:


- Name: `function-no-unknown`
- Primary option: `true`
- Secondary options: None
- Autofixable: No
- Message: `Unexpected unknown function "${function}"`
- Description: "Disallow unknown properties."
- Section: "Avoid errors" -> "Functions"
- Extended description: 

"This rule considers functions defined in the CSS Specificationsto be known.

This rule ignores double-dashed custom functions, e.g. `--custom-function()`"

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new rule](https://stylelint.io/developer-guide/rules#add-a-rule) in the Developer guide.

**Comment by mizozobu** [comment]
It would be nice to have a feature to ignore certain functions just like [at-rule-no-unknown](https://stylelint.io/user-guide/rules/list/at-rule-no-unknown). I'm having a trouble with tailwindcss [theme](https://tailwindcss.com/docs/functions-and-directives#theme) function.

**Comment by jeddy3** [comment]
@mizozobu Sounds good, but please [open a request issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REQUEST_A_FEATURE.yml) so that we can track it.

**Comment by mizozobu** [comment]
created https://github.com/stylelint/stylelint/issues/5900

**Comment by ZanMarolt** [comment]
This is now throwing false positives for calculations, for example: `-(@variable / 2)` -> `48:13  ✖  Unexpected unknown function "-"      function-no-unknown`

and math functions for example: `floor(@variable)` -> `77:12  ✖  Unexpected unknown function "floor"  function-no-unknown`

Should those default sass functions be added to the `"ignoreFunctions"` array? 🤔

**Comment by ybiquitous** [comment]
@ZanMarolt Please see https://github.com/stylelint-scss/stylelint-scss/issues/581

**Comment by ZanMarolt** [comment]
The version we are using is `14.5.0`, so the solution is to add the scss functions to `"ignoreFunctions"` array? 🤔

**Comment by ybiquitous** [comment]
Yes, for example, see the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYLIBsICd4oDNtcAKAAQDckcBLJAI0xgEoUBfAHQDsQAaEAM4BPLgBckADwTgBAvuAhcCNAObTg3FCg4gcAVyYCd+DVy1adBPVzCiaigLRcID6wGtnAdy7GUAbVF9GF40HVVnHBgAMWtbey4jBH9LYhwdAF02dM12bjYQNiA).

**Comment by alexander-akait** [comment]
I think we should ignore non standard CSS syntax

**Comment by ZanMarolt** [comment]
Should we consider extending this lint rule to be able to include all `sass` [functions](https://www.tutorialsteacher.com/sass/sass-functions) as well? 🤔

**Comment by ybiquitous** [comment]
Yes, like `scss/at-rule-no-unknown`. Please see also https://github.com/stylelint-scss/stylelint-scss/issues/581

**Comment by ZanMarolt** [comment]
Perfect, sounds great!
