### ISSUE TITLE
Stylelint: Unknown word (CssSyntaxError)

### ISSUE THREAD

**Issue by ofirrifo** [stylelint/stylelint#5864]
### What steps are needed to reproduce the bug?

I just upgrade stylelint from version 13.13.1 to 14.2.0 and I start to get this error `Stylelint: Unknown word (CssSyntaxError)` on ts files.

I read this migration doc  https://stylelint.io/migration-guide/to-14 but it not helped me.

and here is my relevant `devDependencies` I'm using

```
    "stylelint": "^14.2.0",
    "stylelint-config-sass-guidelines": "^9.0.1",
    "stylelint-config-standard": "^24.0.0",
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-sass-guidelines",
  "rules": {
    "length-zero-no-unit": true,
    "unit-no-unknown": true,
    "property-no-unknown": true,
    "color-no-invalid-hex": true,
    "color-no-hex": true,
    "function-disallowed-list": ["/^rgb/", "/^hsl/"],
    "color-named": "never",
    "declaration-block-no-duplicate-properties": true,
    "selector-pseudo-element-no-unknown": [true, { "ignorePseudoElements": ["ng-deep"] }],
    "media-feature-name-no-unknown": true,
    "at-rule-no-unknown": null,
    "comment-no-empty": true,
    "no-duplicate-at-import-rules": true,
    "no-extra-semicolons": true,
    "no-invalid-double-slash-comments": true,
    "shorthand-property-no-redundant-values": true,
    "value-keyword-case": "lower",
    "max-nesting-depth": null,
    "selector-no-qualifying-type": null,
    "selector-class-pattern": "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^noUi-|calenderMatMenu",
    "selector-max-compound-selectors": null,
    "scss/dollar-variable-pattern": null,
    "order/properties-alphabetical-order": null
  }
}
```

### How did you run Stylelint?

stylelint '**/*.scss' --fix

### Which version of Stylelint are you using?

`^14.2.0`

### What did you expect to happen?

Not to show me an un relevant error: `Stylelint: Unknown word (CssSyntaxError)`

### What actually happened?

I see error on ts files with Stylelint: Unknown word (CssSyntaxError)
on js import 
for example
```ts
import { DAY_DROPDOWN_ITEMS, getCorrectDayObjByValue, getDaysDropdownItems } from './day-dropdown-items.const';
```

### Does the bug relate to non-standard syntax?

NO

**Comment by jeddy3** [comment]
Thanks for using the template.

> Not to show me an un relevant error: `Stylelint: Unknown word (CssSyntaxError)`

This error occurs in version 14 when trying to lint something other than CSS without specifying a [`customSyntax`](https://stylelint.io/user-guide/usage/options#customsyntax).

[This is the relevant part of the migration guide](https://stylelint.io/migration-guide/to-14/#syntax-option-and-automatic-inferral-of-syntax).

We suggesting extending the [`stylelint-config-standard-scss`](https://www.npmjs.com/package/stylelint-config-standard-scss) shared config as it configures Stylelint for SCSS:

```json
{
  "extends": "stylelint-config-standard-scss",
  "rules": {
    "function-disallowed-list": ["/^rgb/", "/^hsl/"],
    "color-named": "never",
    "selector-pseudo-element-no-unknown": [true, { "ignorePseudoElements": ["ng-deep"] }],
    "selector-class-pattern": "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^noUi-|calenderMatMenu",
  }
}
```

```console
stylelint '**/*.scss' --fix
```

This will not lint JavaScript files.

If the error occurs in VS Code, make sure you're [using the latest version of the official extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint).

**Comment by ofirrifo** [comment]
@jeddy3  this error occurs in Webstorm and not as part of execute `stylelint '**/*.scss' --fix`
in this case when I will replace the extends to `stylelint-config-standard-scss` it should fix the issue ?

**Comment by jeddy3** [comment]
> this error occurs in Webstorm

It's a problem with Webstorm then. Either a bug or it's been configured to lint JavaScript files with Stylelint when it shouldn't.

> when I will replace the extends to stylelint-config-standard-scss it should fix the issue ?

No. The issue appears to be with Webstorm.

I dug into the config your extending ([stylelint-config-sass-guidelines](https://github.com/bjankord/stylelint-config-sass-guidelines#stylelint-config-sass-guidelines)) and it does the same as `stylelint-config-standard-scss`, i.e. configures Stylelint for SCSS by using postcss-scss and stylelint-scss. Changing to stylelint-config-standard-scss won't make a difference.

**Comment by ofirrifo** [comment]
@jeddy3 Thanks!
I just find how to solve my issue in the configuration of Webstorm.
Preferences -> Languages & Frameworks-> Style Sheets -> Stylelint
Now unselect the Process JS Files checkbox

Solve my issue

**Comment by GitHubJackson** [comment]
```
module.exports = {
  customSyntax: 'postcss-less',
  extends: [
    'stylelint-config-html',
    'stylelint-config-recommended-vue',
    'stylelint-config-prettier',
  ],
};
```
this is my config,but there is some errors like this
```
yarn run v1.22.18
$ stylelint src/**/*.{vue,css,less}

src/App.vue
 23:1  ✖  Unknown word  CssSyntaxError

src/components/Counter.vue
 4:13  ✖  Unknown word  CssSyntaxError
```
the file like this
```
<style lang="less"><style>
```
how can i solve it?
it's a vue3 project, stylelint v14.8.5
