### ISSUE TITLE
Document `overrides` and `customSyntax` working together

### ISSUE THREAD

**Issue by lz000** [stylelint/stylelint#5872]
### What is the problem you're trying to solve?

My project has both less and styled-components. I want to use stylelint to lint both. For styled-components, I use `"customSyntax": "postcss-jsx"` in the .stylelintrc. For less, I use` "customSyntax": "postcss-less"`. This works well for the corresponding file type. But I can't have stylelint to lint both file types since I can only specify one value for `customSyntax`.

### What solution would you like to see?

perhaps allow specifying an array of `customSyntax` so that stylint can use different library to parse corresponding type?

**Comment by jeddy3** [comment]
Thanks for the request and for using the template.

You should use the [`overrides`](https://stylelint.io/user-guide/configure#overrides) configuration property. See https://github.com/stylelint/stylelint/issues/5777.

I'll label the issue as documentation as this is the 2nd query about it recently. We can:

- show `customSyntax` being used in the `overrides` example
- reference `overrides` in the `customSyntax` documentation section
