### ISSUE TITLE
Rules block being ignored

### ISSUE THREAD

**Issue by JamesJosephFinn** [stylelint/stylelint#589]
Looks like the `rules` block in `.stylelintrc` is being ignored when extended:
```json
{
    "extends": "stylelint-config-suitcss",
    "rules": {
        "indentation": 4,
        "max-empty-lines": 4,
    }
}
```
But, the reporter prints out:
```bash
===> stylelint test.css 

>> Deprecation Warning: Numbered severities (0, 1, 2) have been deprecated, and in 4.0 they will be disabled.  See: http://stylelint.io/?/docs/user-guide/configuration.md

test.css
1:21	Expected single space before "{" (block-opening-brace-space-before)
2:1	Expected indentation of 2 spaces (indentation)
2:10	Expected a trailing semicolon (rule-trailing-semicolon)
3:2	Unexpected empty line (max-empty-lines)
4:1	Unexpected empty line (max-empty-lines)
5:1	Unexpected empty line (max-empty-lines)
8:21	Expected single space before "{" (block-opening-brace-space-before)
9:1	Expected indentation of 2 spaces (indentation)
9:10	Expected a trailing semicolon (rule-trailing-semicolon)
```
As an aside, I'm assuming the deprecation warning is getting printed every time the program runs.

**Comment by davidtheclark** [comment]
I believe this is a duplicate of https://github.com/stylelint/stylelint/issues/585. We'll confirm when a fix is up.

**Comment by davidtheclark** [comment]
@JamesJosephFinn : Can you please run your code against `master` now, and see if the problem is solved?

**Comment by JamesJosephFinn** [comment]
I upgraded to `3.2.0` both globally and locally (in my `package.json`), and now the reporter prints:
```bash
===> stylelint test.css 

>> Deprecation Warning: Numbered severities (0, 1, 2) have been deprecated, and in 4.0 they will be disabled.  See: http://stylelint.io/?/docs/user-guide/configuration.md

test.css
Expected option value for rule "indentation"
Expected option value for rule "max-empty-lines"
```
* My `.stylelintrc` remains unchanged (as above). The syntax is correct as per the docs.
* To test config, my `test.css` has indentation and empty-line errors, but as you can see, they are not being reported.

Thanks! This tool has great promise, it's "the way of the future".

**Comment by davidtheclark** [comment]
Docs now have this section that I think applies to your situation:

>Before v3, configuration involved a system of numbered severities, like ESLint's. Numbered severities have been deprecated (and will be removed in v4), but can still be used for the time being — just expect a deprecation warning whenever stylelint runs.

> stylelint should be able to figure out whether you're using legacy numbered severities as opposed to the more recent standard. But there is one situation in which auto-detection won't work: if your config only contains rules with integers as their primary option (e.g. indentation and max-empty-lines), auto-detection will assume you're using numbered severities, even if you're not. If this exception applies to you, you can explicitly force standard (non-numbered) severities by adding legacyNumberedSeverities: false to your config.

Can you try using `legacyNumberedSeverities: false` and see how it goes?

**Comment by JamesJosephFinn** [comment]
Brilliant! I guess I should learn to read. That one slipped right by me. Props to you, open source work aint easy. Happy New Year!
