### ISSUE TITLE
Add `ignoreFunctions: []` to function-no-unknown

### ISSUE THREAD

**Issue by mizozobu** [stylelint/stylelint#5900]
### What is the problem you're trying to solve?

[function-no-unknown](https://stylelint.io/user-guide/rules/list/function-no-unknown) throws an error when using non-standard funcitons such as tailwindcss [theme](https://tailwindcss.com/docs/functions-and-directives#theme) function.

### What solution would you like to see?

It would be nice to have a feature to ignore certain functions just like `ignoreAtRules` of [at-rule-no-unknown](https://stylelint.io/user-guide/rules/list/at-rule-no-unknown).

**Comment by jeddy3** [comment]
@mizozobu Thanks for the request and for using the template.

Sounds good to me.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

Out of curiosity, does Tailwind have an [dashed ident](https://www.w3.org/TR/css-values-4/#dashed-idents) alias for `theme()`, e.g. `--tailwind-theme()`, that you can use?

**Comment by ybiquitous** [comment]
@mizozobu Thanks for the suggestion. I've opened a pull request #5901.

**Comment by mizozobu** [comment]
@jeddy3 
> Out of curiosity, does Tailwind have an [dashed ident](https://www.w3.org/TR/css-values-4/#dashed-idents) alias for theme(), e.g. --tailwind-theme(), that you can use?

Not that I know of, or at least it's not documented. I've tried `--tailwind-theme()` and `--tw-theme()`, but no luck. My best guess is that tailwindcss performs some transformation with postcss instead of exposing their functions.

https://github.com/tailwindlabs/tailwindcss/blob/5ea67b0a86be1df2a2392dd17468de61e5b4b6f7/tests/evaluateTailwindFunctions.test.js#L9-L32

**Comment by jeddy3** [comment]
Thanks for trying them out. Maybe they'll add them in the future.

**Comment by jeddy3** [comment]
Released in `14.5.0`.
