### ISSUE TITLE
Fix TypeError [ERR_INVALID_URL_SCHEME] in function-no-unknown

### ISSUE THREAD

**Issue by kliehm** [stylelint/stylelint#5918]
### What steps are needed to reproduce the bug?

I think there's a bug in 14.5.0. If I use
```
@use "sass:color"
@use "~mypackage"
```

Then I get an error
```
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at \node_modules\stylelint\lib\rules\function-no-unknown\index.js:48:39  
```

### What Stylelint configuration is needed to reproduce the bug?

any

### How did you run Stylelint?

stylelint './src/**/*.scss' --fix

### Which version of Stylelint are you using?

14.5.0

### What did you expect to happen?

No script error

### What actually happened?

```
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at \node_modules\stylelint\lib\rules\function-no-unknown\index.js:48:39  
```

### Proposal to fix the bug

Compare with 14.4.0, it only occurs in 14.5.0

**Comment by danielweck** [comment]
FYI I am experiencing the same CI failure.

**Comment by danielweck** [comment]
Error, only on Windows (via GitHub Actions CI builds):

Stylelint `14.5.0`

```
TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at D:\a\project\node_modules\stylelint\lib\rules\function-no-unknown\index.js:48:39
    at D:\a\project\node_modules\stylelint\lib\lintPostcssResult.js:113:8
    at Array.map (<anonymous>)
    at lintPostcssResult (D:\a\project\node_modules\stylelint\lib\lintPostcssResult.js:104:18)
    at lintSource (D:\a\project\node_modules\stylelint\lib\lintSource.js:91:8)
    at async D:\a\project\node_modules\stylelint\lib\standalone.js:227:27
    at async Promise.all (index 0)
    at async standalone (D:\a\project\node_modules\stylelint\lib\standalone.js:266:22)
Error: Process completed with exit code 1.
```

Configuration:

```
{
    "extends": "stylelint-config-standard",
    "rules": {
        "declaration-block-no-redundant-longhand-properties": null,
        "shorthand-property-no-redundant-values": null,
        "selector-class-pattern": null,
        "custom-property-pattern": null,
        "selector-id-pattern": null,
        "keyframes-name-pattern": null,
        "property-no-vendor-prefix": null,
        "value-no-vendor-prefix": null,
        "number-max-precision": null,
        "color-function-notation": null,
        "alpha-value-notation": null,
        "string-quotes": null,
        "selector-attribute-quotes": null,
        "function-url-quotes": null,
        "font-family-name-quotes": null,
        "no-descending-specificity": null,
        "at-rule-no-unknown": [
            true,
            {
                "ignoreAtRules": ["define-mixin", "mixin", "include"]
            }
        ],
        "selector-pseudo-class-no-unknown": [
            true,
            {
                "ignorePseudoClasses": ["global"]
            }
        ]
    }
}
```

**Comment by danielweck** [comment]
The only notable change in my `package-lock.json` is `css-functions-list`, see changelog:
https://github.com/niksy/css-functions-list/releases/tag/v3.0.1

> Use fileURLToPath for location resolve

**Comment by danielweck** [comment]
Ah yes, I see @niksy the author of `css-functions-list` has already chimed in here, in the PR:
https://github.com/stylelint/stylelint/pull/5916#issuecomment-1039362738
#:+1:

**Comment by BePo65** [comment]
Just a short question: should the problem now be solved (without a new release)?

In my program I removed the package-lock,json and the node_modules folder and reinstalled all packages (including stylelint-config-standard@25.0.0), but the error ("TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file") is still there.

In my package-lock.json I see "css-functions-list@3.0.1" (so the correct version of "css-functions-list" seems to be installed).

Is there something i must do besides reinstalling my packages?

**Comment by kliehm** [comment]
> Is there something i must do besides reinstalling my packages?

I see it's scheduled for release 14.5.1, which isn't available on github yet. In the meantime you can set `"function-no-unknown": null` in your `.stylelintrc.js` file to avoid the error.

**Comment by danielweck** [comment]
I have updaated all my NPM packages, unfortunately the regression bug remains. In fact, I believe the bug was introduced by `css-functions-list` version `3.0.1`, see my original report (3 comments in a row):

https://github.com/stylelint/stylelint/issues/5918#issuecomment-1040200040

...let me try to pin `css-functions-list` to version `3.0.0`, just to see what happens.

**Comment by ybiquitous** [comment]
@danielweck Have you tried [`stylelint@14.5.1`](https://github.com/stylelint/stylelint/releases/tag/14.5.1)?

**Comment by danielweck** [comment]
> Have you tried [`stylelint@14.5.1`](https://github.com/stylelint/stylelint/releases/tag/14.5.1)?

Ah, I see it has just been published ... will try now :)

https://www.npmjs.com/package/stylelint/v/14.5.1

**Comment by danielweck** [comment]
> ...let me try to pin `css-functions-list` to version `3.0.0`, just to see what happens.

Confirmed that this works. However, I am going to try https://www.npmjs.com/package/stylelint/v/14.5.1 now.

**Comment by danielweck** [comment]
> > Have you tried [`stylelint@14.5.1`](https://github.com/stylelint/stylelint/releases/tag/14.5.1)?
> 
> Ah, I see it has just been published ... will try now :)
> 
> https://www.npmjs.com/package/stylelint/v/14.5.1

Yep, all fixed now :)
Thanks 👍

**Comment by niksy** [comment]
Thanks everyone for bug report, glad that we could get this resolved, and sorry for this little hiccup!
