### ISSUE TITLE
Unexpected unknown function "nth"

### ISSUE THREAD

**Issue by andriusign** [stylelint/stylelint#5931]
### What steps are needed to reproduce the bug?

Create SCSS file with content:
```
@mixin respond-from($media) {
  @each $breakpoint in $breakpoints {
    @if $media == nth($breakpoint, 1) {
      @media (min-width: #{nth($breakpoint, 2)}) {
        @content;
      }
    }
  }
}
```

Run stylelint: `npx stylelint`

### What Stylelint configuration is needed to reproduce the bug?

```
{
  "extends": ["stylelint-config-standard", "stylelint-config-sass-guidelines", "stylelint-prettier/recommended"],
  "plugins": ["stylelint-declaration-strict-value", "stylelint-prettier", "stylelint-order"],
  "ignoreFiles": ["**/src/scss/vendor/**/*.scss"],
  "rules": {
    "at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": [
          "extends",
          "ignores",
          "include",
          "mixin",
          "extend",
          "if",
          "else",
          "each",
          "warn",
          "function",
          "return",
          "for"
        ]
      }
    ],
    "scale-unlimited/declaration-strict-value": [
      ["color", "fill", "font-family", "z-index"],
      { "ignoreValues": ["transparent", "inherit", "/rgba(.*)/"] }
    ],
    "color-function-notation": ["legacy"],
    "selector-pseudo-element-no-unknown": [
      true,
      {
        "ignorePseudoElements": ["ng-deep"]
      }
    ],
    "selector-class-pattern": "[a-zA-Z0-9]+",
    "declaration-block-no-duplicate-properties": [
      true,
      {
        "ignore": ["consecutive-duplicates-with-different-values"]
      }
    ],
    "max-nesting-depth": 3,
    "order/order": ["custom-properties", "declarations"],
    "order/properties-alphabetical-order": true,
    "no-descending-specificity": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "rule-empty-line-before": [
      "always-multi-line",
      {
        "except": ["first-nested"],
        "ignore": ["after-comment"]
      }
    ],
    "prettier/prettier": true
  }
}

```

### How did you run Stylelint?

npx stylelint

### Which version of Stylelint are you using?

14.5.1

### What did you expect to happen?

Stylelint pass without errors like in version 14.0.1

### What actually happened?

Unexpected unknown function "nth"  function-no-unknown

### Does the bug relate to non-standard syntax?

SCSS

### Proposal to fix the bug

Was working fine in version 14.0.1.

**Comment by alexander-akait** [comment]
Please open an issue in `stylelint-scss`, `nth` is unknown function in CSS, also you can ignore this function if you want to skip it

**Comment by jeddy3** [comment]
Thanks for the report.

As @alexander-akait said, the rule is working as intended as `nth` is not a standard CSS function.

`stylelint-scss` may add a new rule soon that includes functions for SCSS. See https://github.com/stylelint-scss/stylelint-scss/pull/591

In the meantime you can ignore function using the [`ignoreFunctions`](https://stylelint.io/user-guide/rules/list/function-no-unknown#ignorefunctions-regex-regex-non-regex) secondary option.

**Comment by andriusign** [comment]
OK, thanks a lot for the tips. Will do.
