### ISSUE TITLE
font-weight-notation

### ISSUE THREAD

**Issue by dan-gamble** [stylelint/stylelint#595]
i.e `700` > `bold`

**Comment by danielgamble** [comment]
Gonna take a crack at this one myself, sure it's very trivial :)

**Comment by danielgamble** [comment]
Got most of the way through it, it's basically based on: `color-no-named`

One thing i'm not sure how to pass or see how it's done in that rule is have it not fail when something named appears in a Sass/CSS variable, animation or url. https://github.com/danielgamble/stylelint/blob/master/src/rules/color-no-named/index.js

**Comment by davidtheclark** [comment]
Maybe it would work if you make sure that the *entire* value of the node is `bold` or `semibold` etc. -- in which case there rule complains. If the value of the node is some custom word like `maybe-boldish` or `$bold`, which contains `bold` but is also more, then the rule ignores it. Does that seem like it might work?

**Comment by danielgamble** [comment]
Ahh gotcha i thought you might check the rules i.e `color:` or `background-color`. Will look into learning regex as well while i'm at it :). Do you think hardcoding a set of accepted values is okay in this instance as there are only 9 or so and unlikely to change in the future?

**Comment by davidtheclark** [comment]
Yes, I think hardcoding the accepted values is fine.

For me the key to learning about regular expressions is to use a tool like [regexr](http://www.regexr.com/) that gives you super fast feedback.

**Comment by jeddy3** [comment]
@danielgamble I'm a bit late to party, and so I'm just catching up on issues... 

This rule sounds great to me. I have some input on the naming and options though.

Perhaps we should, for consistency with other style-based rules like `color-hex-case`, not have this as a `no-*` rule, but rather one with options e.g.

`font-weight-style: "numeric"|"named"`

I'm not sure if you were planning this already, but I also think this rule should look for font weight values across the board: `font-weight` props within rules, `font-weight` props within `@font-face` at-rules, and font weight values within the `font` shorthand props. 

How does that sound?

**Comment by danielgamble** [comment]
That seems to cover a lot more bases than i had originally though :)

I again did try and give it a pop but so far have failed quite miserably!

**Comment by jeddy3** [comment]
> I again did try and give it a pop but so far have failed quite miserably!

Ha, I know how that feels. I cut my node teeth on some of the earlier stylelint rules, but only with the help of David and Maxime.

You were right to look to `color-no-named` for inspiration. `color-hex-case` would be another good rule to harvest bits from. 

I'm not sure if it's of any help to you, but the rule logic could go something like:

1. For the [each declaration filtered by](https://github.com/postcss/postcss/blob/master/docs/api.md#containerwalkdeclspropfilter-callback) the `font-weight` property, check and then flag a warning if the whole `node.value` is either one of the numeric values (for the `"named"` keyword), or one of the named values (for the `"numeric"` keyword).

2. For each declaration filtered by the `font` property, [jump through](https://github.com/TrySound/postcss-value-parser) trying to decipher which value is the font weight, and then check that value as above. You can probably use the description of `font` on [devdocs](http://devdocs.io/css/font) to help you decipher things i.e. it looks like you can check all the values if the option is `"numeric"` as the _named_ values won't appear anywhere else. The `"named"` option is a little tricker as you could have a line height value of `100` etc, but it looks like line height must always be preceeded with a `/` divider, and so you can use that info to ignore line height values.

Good luck and don't hesitate to push up a PR with your code for us to help you with, if you'd prefer to do that :)
