### ISSUE TITLE
Ban certain font-weight values

### ISSUE THREAD

**Issue by C0ZEN** [stylelint/stylelint#5950]
### What is the problem you're trying to solve?

I use some fonts that do not cover certain font-weight.
To avoid mistakes, I would like to be able to ban those unsupported font-weight from my code.

### What solution would you like to see?

Add a new rule that disallow the usage of certain values used for the font-weight.

**Comment by jeddy3** [comment]
@C0ZEN Thanks for the request and for using the template.

You can use the [stylelint-scales plugin](https://github.com/signal-noise/stylelint-scales) to do this.

---

See also https://github.com/stylelint/stylelint/issues/4593. One day these rules may be ported in to core, but at the moment all the built-in rules only target constructs:

> The existing `*-disallowed-list` and `*-allowed-list` rules target [syntactical constructs](http://apps.workflower.fi/vocabs/css/en) available in the AST like at-rules, functions, declarations, values and properties, whereas these new rules will need a finer-grained understanding of the values within these constructs.

**Comment by jeddy3** [comment]
@C0ZEN I forgot to mention that if don't use the `font` shorthand property (which you can disallow using the [`property-disallowed-list`](https://stylelint.io/user-guide/rules/list/property-disallowed-list/) rule), you can use the built-in [`declaration-property-value-disallowed-list`](https://stylelint.io/user-guide/rules/list/declaration-property-value-disallowed-list) rule to disallow certain values for the `font-weight` property.

The scales plugin:
- assumes you'll be using numeric weights (as it's the future with variables fonts on the horizon)
- can autofix values onto the scale

Whereas the built-in rules:
- can't autofix
- but can be used with keyword weights like `bold`
