### ISSUE TITLE
time-no-imperceptible

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#597]
What about adding rule, which will test `transition` and `animation` duration. Many new developers write `100ms` animations, but human eye can see only >150ms moves.

**Comment by davidtheclark** [comment]
Cool, thanks.

**Comment by jeddy3** [comment]
Sgtm.

To fit this inline with the naming conventions, I think this should be named `time-no-imperceptible`. As [time](https://drafts.csswg.org/css-values-3/#time) is a type like `color` and `number`, which are _things_ we've attached other rules to.

The rule will need to decipher `animation/transition-duration` from the likes of `animation/transition-delay`, and also check the shorthand `animation` and `transition` declarations.

**Comment by davidtheclark** [comment]
@ai: Do you have any article or post pointing to this 150ms number?

**Comment by ai** [comment]
Old movies uses 24 frammes per second. It is about 40 ms for every frame. So any animation less than 100 ms will be visiblle as 2 frames. And 2 frames is not a animtion :).
