### ISSUE TITLE
Add selector-not-notation

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#5974]
check https://github.com/stylelint/stylelint/issues/5974#issuecomment-1072255775

<hr />

### What is the problem you're trying to solve?

- reject mistakes for `::slotted()` e.g. `::slotted(div a) {}` 
  - see #5575
- reject mistakes for `:not()` ([**level 3**](https://www.w3.org/TR/selectors-3/#negation)) using an option on the rule e.g. `:not(div, .foo)` or `:not(a.b[c])`
  - see https://caniuse.com/css-not-sel-list

prompted by https://github.com/stylelint/stylelint/issues/5575#issuecomment-1071317122

### What solution would you like to see?

One rule that fix it for `::slotted()` which would have one option for `:not()` (disabled by default*).
Someone will have to check whether there are other functions that require simple selectors.

<sub>\* because the level 4 `:not()` is not affected</sub>

**Comment by jeddy3** [comment]
Thanks for opening a new issue.

Am I right in thinking that `::slotted` can _only_ accept simple selectors, whereas `:not()` can accept a simple selector _or_ s selector list depending on what browsers a user is targeting?

If so, we can add a rule to our [enforce conventions](https://stylelint.io/user-guide/rules/list#enforce-conventions) category that'll let the user enforce their preference. It would be similar to the [`selector-pseudo-element-colon-notation`](https://stylelint.io/user-guide/rules/list/selector-pseudo-element-colon-notation) rule, e.g. `selector-not-notation: "simple"|"list"`.

Where `"simple"` will warn for:

```css
:not(div, .foo) {}
```

And accept:

```css
:not(div):not(.foo) {}
```

And `"list"` would do the opposite.

**Comment by Mouvedia** [comment]
> whereas :not() can accept a simple selector or s selector list depending on what browsers a user is targeting?

Like I said in the other issue, I think that this is too niche to warrant its own rule.
Here's the demographic for the option on the rule: developers that care about using a cross-browser `:not()`.
It's similar to developers that enforce using `:before` instead of `::before`.
Since we should prioritize recent specifications (level 4 wins over level 3) it should be disabled by default.

> `selector-not-notation: "simple"|"list"`

If you still insist that it should be its own separate rule, I guess I don't mind.
Would `"simple"` reject `:not(a.b[c])` as well?
If `"simple"` corresponds to level 3 then it should.

**Comment by Mouvedia** [comment]
Here's the demographic for the option on the proposed rule: developers that care about using a cross-browser `:not()`.
It's akin to developers that enforce using `:before` instead of `::before`.
Since we should prioritize recent specifications the option ought to be `false` by default.

> Am I right…

You are.

> we can add a rule to our [enforce conventions](https://stylelint.io/user-guide/rules/list#enforce-conventions) category that'll let the user enforce their preference

If you think that it should be its own separate rule, Ill comply.
Feel free to rename this issue's title.

> `selector-not-notation: "simple"|"list"`

1. Would `"simple"` reject `:not(a.b[c])` as well? If `"simple"` corresponds to level 3 then it should.
2. Is `a.b[c]` considered a list?

I think `"simple"|"complex"` would be better.
ref https://developer.mozilla.org/en-US/docs/Web/CSS/:not#syntax (uses complex)

**Comment by jeddy3** [comment]
> I think `"simple"|"complex"` would be better.

SGTM.

- Name: `selector-not-notation`
- Primary option: `"simple"|"complex"`
- Secondary options: None
- Autofixable: Yes, but only for `"complex"` (see [color-function-notation](https://stylelint.io/user-guide/rules/list/color-function-notation) for precedence)
- Message: `Expected ${primary} :not() pseudo-class notation"`
- Description: "Specify complex or simple notation for the `:not()` pseudo-class"
- Extended description: (Something about level 3 vs level 4, and fix option. Also see [color-function-notation](https://stylelint.io/user-guide/rules/list/color-function-notation))
- Section: "Enforce conventions" -> "Selectors"

**Comment by Mouvedia** [comment]
> Autofixable: Yes

It's my first rule, I don't plan to make it fixable in that PR.

> but only for "complex" (see [color-function-notation](https://stylelint.io/user-guide/rules/list/color-function-notation) for precedence)

check #5975
there's one test that I considered unfixable for `"simple"`
the rest is doable

> Description
> Extended description

Ill need help for that.

**Comment by jeddy3** [comment]
> It's my first rule, I don't plan to make it fixable in that PR.

That's fine, we can open a follow-up issue.

> Ill need help for that.

Sure thing. I'll add something to the pull request.

**Comment by jeddy3** [comment]
Added in https://github.com/stylelint/stylelint/pull/5975

**Comment by carlosjeurissen** [comment]
The fix method is a non-safe method as it changes specificity. So not sure including this in the general fix method is a good idea.

**Comment by jeddy3** [comment]
@carlosjeurissen Can you [open a documentation issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&template=REPORT_A_DOCS_ISSUE.yml), please? We can add a note to [rule's README](https://stylelint.io/user-guide/rules/list/selector-not-notation) that the fix may change the specificity. 

> So not sure including this in the general fix method is a good idea.

Rules can be turned on and off individually. Quite a few other rules come with caveats regarding their autofix.
