### ISSUE TITLE
Add support for vendor prefixes in `﻿property-*-list`

### ISSUE THREAD

**Issue by keganlance** [stylelint/stylelint#5981]
Currently `property-disallowed-list` is configured to ignore vendor prefixes to make sure when defining `animation`, also `-webkit-animation` is disallowed.

However, when actually specifying a vendor-prefix within `property-disallowed-list`, it seems stylelint should respect that and only block that specific vendor prefix. For example when trying to disallow `-webkit-text-stroke`.

**Comment by jeddy3** [comment]
Makes sense. It should be trivial to implement.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
