### ISSUE TITLE
Fix incorrect column position with autofix in max-line-length

### ISSUE THREAD

**Issue by afdev82** [stylelint/stylelint#5984]
### What steps are needed to reproduce the bug?

I found already a fixed issue for this problem: https://github.com/stylelint/stylelint/issues/2266, but this time it happens only if the check is using the `--fix` option.
To reproduce the problem it's enough to use the `bug.scss` file provided [here](https://github.com/stylelint/stylelint/files/712500/linter-stylelint_GH307.zip) and run stylelint with the `--fix` option.

### What Stylelint configuration is needed to reproduce the bug?

module.exports = {
  "rules": {
    "max-line-length": 130
  },
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss"
  ]
}

### How did you run Stylelint?

`yarn run stylelint --fix bug.scss`

### Which version of Stylelint are you using?

14.6.0

### What did you expect to happen?

```
2:269  ✖  Expected line length to be no more than 130 characters  max-line-length
```

### What actually happened?

The first time I get:

```
2:271  ✖  Expected line length to be no more than 130 characters  max-line-length
```

That is wrong, it should be column 269.
The second time I get 269 because the indentation gets fixed, but it should be 267.

### Does the bug relate to non-standard syntax?

It happens with a scss, I don't know if it's the same with other formats

### Proposal to fix the bug

I don't know how to fix the bug, but if I could help in some way just let me know.
Thank you!

**Comment by jeddy3** [comment]
@afdev82 Thanks for the report and for using the template. The stylistic rules are frozen. We [now recommend using Stylelint alongside a pretty-printer like Prettier](https://stylelint.io/#how-itll-help-you) to enforce stylistic consistency like max line lengths. I'll label as discussion in case any of the other contributors have anything to add, but the last time around we decided to avoid any changes to the stylistic rules, including bug fixes.

**Comment by ybiquitous** [comment]
> the last time around we decided to avoid any changes to the stylistic rules, including bug fixes.

I agree with the decision. 👍🏼

**Comment by afdev82** [comment]
Ok,

so this means I have to disable the rule, otherwise the autofix will always complain about that.
I'll have a look at Prettier.
Thank you!

**Comment by afdev82** [comment]
In fact, I don't have to manually disable the rules, it's already done by [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier), nice!

**Comment by jeddy3** [comment]
> In fact, I don't have to manually disable the rules, it's already done by [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier), nice!

Yeap, that's the [recommended set up now](https://stylelint.io/user-guide/get-started#linting-css-files) so that we can focus on rules that [avoid errors](https://stylelint.io/user-guide/rules/list/#avoid-errors) and [enforce _non-stylistic_ conventions](https://stylelint.io/user-guide/rules/list/#enforce-conventions).

> I agree with the decision. 👍🏼

Good stuff. I'll close the issue then.
