### ISSUE TITLE
ESM releated bug

### ISSUE THREAD

**Issue by Lijiaoa** [stylelint/stylelint#5998]
### What steps are needed to reproduce the bug?

1. my package.json: 
 
![image](https://user-images.githubusercontent.com/61399850/160574398-750f94b4-05a2-40ab-9a8a-e58d54ba7eb2.png)

when I check the style, will use `yarn stylelint` and `yarn stylelint --fix`
![image](https://user-images.githubusercontent.com/61399850/160574531-2c063259-5d24-4a6a-97c2-c3da28eca22e.png)

2. and now, i found that error when i run `yarn stylelint`, my node version is `16.4.0`

![image](https://user-images.githubusercontent.com/61399850/160574850-2a131a68-3e80-4bee-ae1d-b6bd4f0f2234.png)

### What Stylelint configuration is needed to reproduce the bug?

I think it doesn't matter.

### How did you run Stylelint?

had told that in first block

### Which version of Stylelint are you using?

14.0.0

### What did you expect to happen?

could run normally

### What actually happened?

had bug

**Comment by ybiquitous** [comment]
@Lijiaoa Thank you for using the template.

When seeing the error stack trace, your `package.json` seems to install [`meow@10`](https://github.com/sindresorhus/meow/releases/tag/v10.0.0) (which is a pure ESM package).
We have not supported ESM dependencies yet (see #5291).

https://github.com/stylelint/stylelint/blob/ac200dcb12507b72873b0280f3497469470a49e9/package.json#L131

Could you confirm the `meow` version, please?

**Comment by jeddy3** [comment]
> Could you confirm the meow version, please?

You can use `npm ls meow` to do this.

**Comment by Lijiaoa** [comment]
sorry for late reply, its version `9.0.0`  @ybiquitous @jeddy3 
![image](https://user-images.githubusercontent.com/61399850/160741257-96ea39c4-9b37-4310-baf1-84633088291a.png)

**Comment by ybiquitous** [comment]
Umm..., what if `npm ls trim-newlines`? [`trim-newlines@4`](https://github.com/sindresorhus/trim-newlines/releases/tag/v4.0.0) is also a pure ESM.

**Comment by Lijiaoa** [comment]
![image](https://user-images.githubusercontent.com/61399850/160742270-d430fb9f-ad88-4ce5-a596-95bb62ae2170.png)

**Comment by ybiquitous** [comment]
Thanks. `meow@9` should depend on `trim-newlines@3`:
https://github.com/sindresorhus/meow/blob/v9.0.0/package.json#L52

If you can fix the invalid dependency tree, it seems the Stylelint error should be resolved.

**Comment by Lijiaoa** [comment]
ok, thank you! I will try to fix that.
