### ISSUE TITLE
New rule: set minimum `z-index` value

### ISSUE THREAD

**Issue by niksy** [stylelint/stylelint#602]
I’ll let this quote from [CSS Tricks article](https://css-tricks.com/handling-z-index/) explain the reasoning behind this:

> It's fairly common to see people number in the hundreds with z-index in web design too. The idea being that you could slip something in between later if need be, which you couldn't if you did 1, 2, 3, etc, because z-index doesn't support decimals.

So, with this rule you could set values to be minimum of, let’s say, `10`, and everything lower than that, *except `auto` and `-1`*, is reported back.

Is this valid enough to be in the core?

**Comment by davidtheclark** [comment]
Interesting idea. Maybe I'm missing something, though, because I do not understand why it would help to set a minimum. Aren't you just offsetting the problem by 10? Because devs could just use 10, 11, 12, 13, and hit the same issue.

**Comment by niksy** [comment]
Huh, didn’t think about that. I guess then it’s kind of complicated to cater to this issue in this form. What about setting increment value? If you set it to `2`, developer should always use values like `10`, `12`, `14`, etc. but if you want to slip something between, you should use `stylelint-disable` comment to temporarily disable this rule. It looks nasty, but it will force you to reconsider what you’re doing and refactor your code.

**Comment by davidtheclark** [comment]
Yeah, incrementing and forcing a disable comment is the only way I can think of. Because that's an unusual approach (forcing disable comments), I'd say this is better fitted to a plugin, at least for initial experimentation. Let us know how it goes!
