### ISSUE TITLE
The "max-empty-lines" rule with an integer always produces an error

### ISSUE THREAD

**Issue by benfrain** [stylelint/stylelint#603]
Running 3.2.0 and when I have `"max-empty-lines": 2` in my .stylelintrc I get this error for every file:

`⚠  Invalid option value "true" for rule "max-empty-lines"`

I'm running via gulp-postcss.

**Comment by davidtheclark** [comment]
Is this a duplicate of https://github.com/stylelint/stylelint/issues/585?

**Comment by benfrain** [comment]
Apologies, I have literally no clue how I just managed to screw up my .stylelintrc so badly. I'd somehow reverted to a version that used the numbered severities. Switched to my correct config object and all is well. Move along. Nothing to see here! [Sorry!]

**Comment by davidtheclark** [comment]
:)
