### ISSUE TITLE
Ignore files from node_modules, is it possible?

### ISSUE THREAD

**Issue by leandrogrillo** [stylelint/stylelint#604]
Here is my case:

I'm importing vendors css using `postcss-import` but i don't want to lint them. I tried to add a glob in  `.stylelintrc` to `node_modules`:

```json
"ignoreFiles": "node_modules/**/*.css"
```

and it didn't work. i tried to add file path in `ignoreFiles`:
```json
"ignoreFiles": "node_modules/path-to-file/file.css"
```
 but still linting.

Also tried to add in option in gulp, but got same thing:

```js
.pipe(postcss([
  stylelint({ ignoreFiles: 'node_modules/**/*.css' })
]))
```

and the worst thing:

```css
/* sylelint-disable */
@import "pkg-name/file.css"
/* sylelint-enable */
```

don't work D:

if it helps, this the branch that i was working https://github.com/leroy-merlin-br/garden/tree/fix/css-lint

Is right to use stylelint in postcss pipeline?

**Comment by davidtheclark** [comment]
I find that it's almost always better to run stylelint either before other processors or as a separate task. If you do that, do you get the intended results?

**Comment by TrySound** [comment]
@leandrogrillo My example
https://github.com/TrySound/case/blob/master/gulpfile.js#L51-L91

**Comment by davidtheclark** [comment]
Another idea: Maybe it will work if you use an absolute path for your `ignoreFiles` value? Give that a try.

Closing the issue because I don't think it's pointing at a bug.

**Comment by leandrogrillo** [comment]
@davidtheclark can you show an example?

ty @TrySound ! :) 

i removed stylelint from postcss pipe as you guys suggested and create a separated task to lint. 

It works because don't pass through `postcss-import`, it make sense.

**Comment by davidtheclark** [comment]
```js
.pipe(postcss([
  stylelint({ ignoreFiles: path.dirname(__dirname, 'node_modules/**/*.css') })
]))
```

... if your node_modules dir is in the same places as gulpfile.

**Comment by leandrogrillo** [comment]
even in my separated task, still linting my file, here is what i'm using:

```js
return gulp.src([paths.src.css.glob, paths.docs.css.glob])
    .pipe(stylelint({
      ignoreFiles: path.dirname(__dirname, 'path-to-file/**/*.css'),
      reporters: [
        reporter()
      ]
    }));
```

and just to remind, i can't get this working:

```css
/* sylelint-disable */
.container {
  color: #fff;
}
/* sylelint-enable */
```
Using  enable/disable comments, it's still linting.

![img](http://puu.sh/mmTvp/4012a104ac.png)

**Comment by jeddy3** [comment]
> It works because don't pass through postcss-import, it make sense.

Yep, that's the recommended way to go about it.

> and just to remind, i can't get this working:

Is that example taken straight from your source? As you've misspelt `stylelint`... it should be `stylelint-disable` and not `sylelint-disable`(where you're missing the `t`).

**Comment by leandrogrillo** [comment]
@jeddy3 ops! :B sorry about that. :)

**Comment by jeddy3** [comment]
np :)

**Comment by jeddy3** [comment]
@leandrogrillo Just to double check, everything is working for you now and this issue can remained closed?

**Comment by pahiggins** [comment]
I got around this using the ignoreFiles property in the stylelint configuration object (source: stylelint.config.js), e.g.

`
{
ignoreFiles: ['./node_modules/**/*.js.css'],
}
`

More info: https://stylelint.io/user-guide/configure#ignorefiles

**Comment by amarg26** [comment]
My setup for React.js
-------------------------------------------------------------
Install the below packages for your Project
-------------------------------------------------------------
npm install -g stylelint
npm i -D stylelint 
npm i -D stylelint-config-standard
npm i -D stylelint-no-browser-hacks
-------------------------------------------------------------
Install **StyleLint** in VS code from the extension panel
-------------------------------------------------------------
Create the new files as below in the project root folder
-------------------------------------------------------------
**.stylelintrc.json**
`{
  "extends": ["stylelint-config-standard", "stylelint-config-prettier"]
}
`
**.stylelintignore**
`node_modules/
build/
coverage/`
--------------------------------------------------------------
Make the below changes in the VS code **settings.json** file
**settings.json**
`  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
  "css.validate": false,
  "scss.validate": false,
  "stylelint.validate": ["css", "scss"]
`
--------------------------------------------------------------
Make the command below in the **package.json**
--------------------------------------------------------------
    "csslint": "stylelint **/*.{css,sass,scss}"
--------------------------------------------------------------
Run the command as:
--------------------------------------------------------------
npm run csslint
--------------------------------------------------------------
Open the files which is to be fixed and do Ctrl+s 
--------------------------------------------------------------
Hurray 👯‍♂️
