### ISSUE TITLE
Fix memory leak with `function-calc-no-unspaced-operator` and `--fix`

### ISSUE THREAD

**Issue by dmarov** [stylelint/stylelint#6044]
### What steps are needed to reproduce the bug?

Minimal example https://github.com/dmarov/stylelint-bug
Such syntax as
```
calc(100%/var(--row-items))
```
causes memory leak when used with --fix option

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": "stylelint-config-standard-scss"
}

### How did you run Stylelint?

stylelint style.scss --fix

### Which version of Stylelint are you using?

14.8.0

### What did you expect to happen?

Memory leak should not occur

### What actually happened?

command crashes with error

```
<--- Last few GCs --->

[8224:000001E2E2084530]    76754 ms: Scavenge (reduce) 4094.4 (4099.8) -> 4093.4 (4100.8) MB, 4.5 / 0.0 ms  (average mu = 0.251, current mu = 0.214) allocation failure
[8224:000001E2E2084530]    76764 ms: Scavenge (reduce) 4094.8 (4100.0) -> 4093.8 (4101.0) MB, 4.5 / 0.0 ms  (average mu = 0.251, current mu = 0.214) allocation failure

...
```

### Does the bug relate to non-standard syntax?

No

**Comment by ybiquitous** [comment]
@dmarov Thank you for opening the issue and using the template. And more thanks for providing the reproduction repository.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

I also will investigate this soon.

**Comment by ybiquitous** [comment]
I found that the memory leak occurs with the `function-calc-no-unspaced-operator` rule and standard CSS code.

Here is a reproduction ⬇️ 

Config:

```json
{
  "rules": {
    "function-calc-no-unspaced-operator": true
  }
}
```

CSS:

```css
a {
  width: calc(100%/var(--foo));
}
```

Run without `--fix` (no problems):

```console
$ ./node_modules/.bin/stylelint *.css

a.css
 2:19  ✖  Expected single space after "/" operator  function-calc-no-unspaced-operator
```

Run with `--fix` (**memory leak**):

```console
$ ./node_modules/.bin/stylelint *.css --fix

<--- Last few GCs --->

[79625:0x148008000]    46036 ms: Mark-sweep 4080.6 (4143.1) -> 4079.5 (4143.1) MB, 2602.4 / 0.0 ms  (average mu = 0.216, current mu = 0.067) allocation failure; scavenge might not succeed
[79625:0x148008000]    48974 ms: Mark-sweep 4081.1 (4143.6) -> 4079.9 (4143.6) MB, 2934.9 / 0.0 ms  (average mu = 0.125, current mu = 0.001) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
...
```

Environment:

```console
$ npm version
{
  npm: '8.8.0',
  node: '18.0.0',
  v8: '10.1.124.8-node.13',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.2+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by ybiquitous** [comment]
And, when there are whitespaces between the `/` operator, the memory leak never occurs:

```diff
 a {
-  width: calc(100%/var(--foo));
+  width: calc(100% / var(--foo));
 }
```

**Comment by ybiquitous** [comment]
The cause is an infinite-loop by calling `Array.prototype.splice()` in `for...of`:

https://github.com/stylelint/stylelint/blob/0364db13241d25f3859cf4f56c8c69f6b0a85093/lib/rules/function-calc-no-unspaced-operator/index.js#L310

https://github.com/stylelint/stylelint/blob/0364db13241d25f3859cf4f56c8c69f6b0a85093/lib/rules/function-calc-no-unspaced-operator/index.js#L146-L151

Here is a pseudo code:

```js
valueParser(value).walk((rootNode) => {
  for (const [index, node] of rootNode.nodes.entries()) {
    // Mutate the array inside a loop of itself.
    rootNode.nodes.splice(index, 0, { type: 'space', value: ' ' })
  }
});
```

**Comment by ybiquitous** [comment]
This memory leak occurs only for the `*` and `/` operators, whereas it doesn't occur for `+` and `-`.
So, fixing the false positives reported in #5695 may fix also the memory leak.
