### ISSUE TITLE
Paths separated by '\' are not supported

### ISSUE THREAD

**Issue by southorange1228** [stylelint/stylelint#6070]
### What steps are needed to reproduce the bug?

<img width="781" alt="image" src="https://user-images.githubusercontent.com/32590310/167236385-2d15134f-1716-40bb-8b98-112897a8ee83.png">

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-css-modules',
    'stylelint-config-rational-order',
    'stylelint-config-prettier',
  ],
  plugins: ['stylelint-order', 'stylelint-declaration-block-no-ignored-properties'],
  rules: {
    'declaration-empty-line-before': null,
    'no-descending-specificity': null,
    'selector-pseudo-class-no-unknown': null,
    'selector-pseudo-element-colon-notation': null,
    'order/properties-order': null,
    'font-family-no-missing-generic-family-keyword': null,
    'property-no-unknown': [
      true,
      {
        ignoreProperties: ['line-width'],
      },
    ],
    'block-closing-brace-empty-line-before': 'never',
  },
};

```

### How did you run Stylelint?

 npx stylelint .\src\style\asset.less --fix

### Which version of Stylelint are you using?

`14.17.6`

### What did you expect to happen?

stylelint can run and fix errors.

### What actually happened?

When i use `file watcher` to fix style error in webstorm. I try to set `file watcher` to this.
<img width="445" alt="image" src="https://user-images.githubusercontent.com/32590310/167236598-079de7c8-31a1-4e3d-af10-b2ad243489dd.png">

But i get paths that separated by '\' .
And now, i get some error.
```log
 No files matching the pattern ".\src\style\asset.less" were found
```

**Comment by ybiquitous** [comment]
@southorange1228 Thanks for using the template. Could you provide a reproduction repository so that we can investigate it?

For example, I tried a reproduction on the following repository, but back-slashed paths seem to be working fine:
https://github.com/ybiquitous/foo/runs/6332921659?check_suite_focus=true#step:5:1

<img width="552" alt="image" src="https://user-images.githubusercontent.com/473530/167243306-6c86a390-5413-49b7-a82a-4d454b2db0f4.png">

**Comment by southorange1228** [comment]
@ybiquitous
I think the reason almost be this.
When i use `unix-liked` ternimal client on windows,for example `git bash`, then it can be reproduction.But if i use `powershell`, back-slashed paths seem to be working fine.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/32590310/167245938-45ea8993-fda0-4e36-8e62-d1da45c2a3b9.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/32590310/167245958-d78b23b9-f8c7-40c8-97de-949d309e2515.png">


I'm sorry that i don't know how to change default ternimal client with github action.Can you try it?

**Comment by ybiquitous** [comment]
@southorange1228 Using Bash:

https://github.com/ybiquitous/foo/runs/6333342188?check_suite_focus=true#step:5:1

<img width="634" alt="image" src="https://user-images.githubusercontent.com/473530/167246473-726c0e94-faf4-4abb-9c0d-8b44844d43f3.png">

**Comment by southorange1228** [comment]
Amazing! So if i use `unix-liked` ternimal and  i must use quotes. And Webstorm's setting may have some error .Thanks a lot
