### ISSUE TITLE
Fix false positives for display-mode in media-feature-name-no-unknown

### ISSUE THREAD

**Issue by andreypelykh** [stylelint/stylelint#6071]
> What is the problem you're trying to solve?

The media-feature-name-no-unknown rule doesn't allow the new [display-mode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/display-mode) media query feature. 

> What solution would you like to see?

The media query display-mode to be allowed by the media-feature-name-no-unknown rule.

**Comment by ybiquitous** [comment]
@andreypelykh Thanks for opening the issue and creating the pull request.

I can reproduce the bug on the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBbGUCWBDABFgNvngHZQ4AUmAzgA75YCeAtCtDPDgGYCuhVYAJxgxiAShzAAOsRw4ARtAYTps2SiwCA5hmIcADAG4VqhQNgCOAVhoAPHFQj4MZOfTABrIzJwBfaX+IQABoQKgZiABcsGwRwKipg8AhiTgxNWKlvSRABXhgqbI5M1RxstEwsJk4YLAjuISZiLDRGiCZuYndiCAB3YkKcCNyYYwCfEB8gA):

<img width="950" alt="image" src="https://user-images.githubusercontent.com/473530/167321218-c13a5ea9-187e-48f0-b7bb-34ea89a20559.png">
