### ISSUE TITLE
Add rule metadata to public API

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#6082]
### What is the problem you're trying to solve?

I want to write a [custom formatter](https://stylelint.io/developer-guide/formatters) with rule metadata (e.g. rule doc URL), but now there is no way to use easily rule metadata.

For example, the built-in `verbose` formatter uses an internal API (`_postcssResult`):

https://github.com/stylelint/stylelint/blob/ece68bced0ec04221bc03d0a9d9c60ba03aa2276/lib/formatters/verboseFormatter.js#L109-L119

I want to use a public API for this purpose.

### What solution would you like to see?

I think that the simplest way is to add a property for rule metadata to `LinterResult` (used as the second argument of `Formatter`). See the relevant type definitions:

`Formatter`:

https://github.com/stylelint/stylelint/blob/ece68bced0ec04221bc03d0a9d9c60ba03aa2276/types/stylelint/index.d.ts#L129

*NOTE: It looks possible to change `returnValue?: LinterResult` (optional) to `returnValue: LinterResult` (required).*

`LinterResult`:

https://github.com/stylelint/stylelint/blob/ece68bced0ec04221bc03d0a9d9c60ba03aa2276/types/stylelint/index.d.ts#L311-L328

The use of `LinterResult` on the public API:

https://github.com/stylelint/stylelint/blob/ece68bced0ec04221bc03d0a9d9c60ba03aa2276/types/stylelint/index.d.ts#L367-L372

If you know of a better way, please let me know.

**Comment by jeddy3** [comment]
> I think that the simplest way is to add a property for rule metadata to LinterResult (used as the second argument of Formatter).

SGTM. Labelled as ready to implement.
