### ISSUE TITLE
Add support for PnP as linked customFormatters

### ISSUE THREAD

**Issue by meriouma** [stylelint/stylelint#6100]
### What steps are needed to reproduce the bug?

Run `yarn stylelint --custom-formatter mypackage/stylelint-formatter ...`

### What Stylelint configuration is needed to reproduce the bug?

```
{
  "extends": ["@equisoft/stylelint-config"]
}
```

### How did you run Stylelint?

CLI with `stylelint --custom-formatter mypackage/stylelint-formatter src/browser/**/*.{css,scss,js,jsx,ts,tsx}` 

### Which version of Stylelint are you using?

14.8.2

### What did you expect to happen?

The formatter is loaded from the dependency.

### What actually happened?

stylelint prepends `process.cwd()` to the provided custom-formatter option

### Does the bug relate to non-standard syntax?

No

**Comment by ybiquitous** [comment]
@meriouma Thanks for using the template.

Currently, a custom formatter can be loaded only from an absolute or relative file path:

https://github.com/stylelint/stylelint/blob/23dfa32e1c19930c2f3eec0cb27b276d3deb6ac8/lib/cli.js#L340-L342

Can you use a relative path instead of a dependency path?

**Comment by meriouma** [comment]
Not really. The goal is to reuse a custom formatter we created in multiple projects, without the need to copy it around. It works with the `node_modules` linker, as you can have an absolute path, but when using PnP it can't.

**Comment by ybiquitous** [comment]
@meriouma Thanks for the explanation. I understand the goal. Loading a custom formatter as a sharable package sounds good to me. 👍🏼 

Can we realize this by changing the current algorithm without breaking changes?

```js
function resolveCustomFormatter(formatterPath) {
	if (path.isAbsolute(formatterPath)) {
		return formatterPath;
	}
	const relativePath = path.join(process.cwd(), formatterPath);
	if (fs.existsSync(relativePath)) {
		return relativePath;
	}
	return formatterPath; // as a package path like `your-stylelint-custom-formatter`
}
```

Will this also work with Yarn PnP? Or, are there more considerations?

**Comment by meriouma** [comment]
I believe this should work with PnP without breaking the current behavior.

**Comment by jeddy3** [comment]
I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
