### ISSUE TITLE
Add `--globby-options` flag

### ISSUE THREAD

**Issue by silversonicaxel** [stylelint/stylelint#6109]
### What steps are needed to reproduce the bug?

Create a folder beginning with a dot, and set a css or scss file and run a `stylelint --fix` command. It won't work.
I'm experiencing this problem with `.storybook` folder.

### What Stylelint configuration is needed to reproduce the bug?

any configuration would be enough

### How did you run Stylelint?

stylelint --fix '**/*.css

### Which version of Stylelint are you using?

13.13.1

### What did you expect to happen?

The lint fixes also files present in hidden folders

### What actually happened?

Hidden folders files are ignored

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

Read also hidden folders

**Comment by alexander-akait** [comment]
@ybiquitous We should not lint `.` files, they are hidden files and it is good by default avoid to lint them (that is why glob by default doesn't collect `.` files too), so using `'.*/**/*.scss'` is a valid solution. Even more linux (and more) don't show `.` files in your file exporer, I strongly reccomend don't use `.` directories (if you really don't want to hide something), it can be a problem for developers on other platforms/os

**Comment by silversonicaxel** [comment]
My folder is `.storybook`, obviously it is considered hidden and I strongly believe I can't rename it. Inside that folder I've also some custom css, that I desire to lint. 

So I also understand @alexander-akait point of view. In my opinion this should be also a config parameter, so users can decide their preferences. 

What do you think?

**Comment by silversonicaxel** [comment]
For the `.git` we could eventually use stylelintignore file @ybiquitous

**Comment by alexander-akait** [comment]
I am fine with an additional option

**Comment by silversonicaxel** [comment]
Who's going to be in charge of this implementation? How does it work?

**Comment by ybiquitous** [comment]
@alexander-akait @silversonicaxel
Thanks for the feedback. I also agree with ignoring dotfiles by default (the same as always).

So, it seems we need to consider a new CLI option to pass `{ dot: true }` to `globby` to address the following use-cases:

```console
$ tree .foo
.foo/
├── .bar/
│   └── a.css
└── a.css

1 directory, 2 files

$ npx stylelint '.foo/**/*.css'

.foo/a.css
 1:12  ✖  Unexpected unit  length-zero-no-unit
```

In the example above, we should want to check not only `.foo/a.css` but also `./foo/.bar/a.css`.

Decisions required for the new option if needed:

- name (e.g. `--dot`)
- argument (e.g. `--dot=true`, `--dot=false`, or disallows an argument?)
- default value (e.g. `[default: false]`)

```console
$ stylelint '.foo/**/*.css' --dot
# should match `.foo/a.css` and `.foo/.bar/a.css`

$ stylelint '.foo/**/*.css' --dot --ignore-pattern '.git/**'
# should be useful with `.stylelintignore` or `--ignore-pattern`
```

Any thoughts?

**Comment by silversonicaxel** [comment]
I would like to have this command in my script

```
stylelint '**/*.css' --dot
# should match `.foo/a.css` and `.foo/.bar/a.css`
```

and regarding this 
```
stylelint '**/*.css' --dot --ignore-pattern '.git/**'
```
could also live in `.stylelintignore` as

```
node_modules
dist
.git
.vscode
```

but then it is up to the consumers who are into hidden folders to set them in the ignore list

to me looks good like this!

**Comment by ybiquitous** [comment]
Considering consistency with the Node.js API, `--globby-options` is also a good option. 👍🏼

**Comment by jeddy3** [comment]
Let's an `--globby-options` flag.

> I could potentially help... Who's going to be in charge of this implementation? How does it work?

It's great you want to help a new feature is generally implemented by the person who requested it or by someone who also needs it. The team working on Stylelint have time to review pull requests, but not time to implement features like this unless they need it themselves.

@silversonicaxel I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by sidverma32** [comment]
@jeddy3 @ybiquitous  is this done or shall i pick this up?

**Comment by ybiquitous** [comment]
@sidverma32 Thank you! Nobody currently works on this issue, so please feel free to create a pull request.

**Comment by sidverma32** [comment]
Can you guide me which file to refer to add this `option` support? @ybiquitous 

Also i can see this `dot` support present in code repo, would like to know if we have the support for `dot` but not utilising it properly or is this `dot` referring to some other functionality? 

<img width="1130" alt="Screenshot 2022-10-29 at 12 25 18 PM" src="https://user-images.githubusercontent.com/10995431/198818559-d556bc70-5e97-49b8-b3c9-223303c4346c.png">

**Comment by silversonicaxel** [comment]
thanks, I also had issues to implement myself this interesting feature. kudos to volounteers!

**Comment by ybiquitous** [comment]
@sidverma32 To support the `--globby-options` CLI flag, we need to change `lib/cli.js` and pass the new flag value to `standalone()`:

https://github.com/stylelint/stylelint/blob/7fbf2972a3c0d3d0d837fe2ba7964478fc323b7a/lib/cli.js#L506

`lib/standalone.js` has allowed the `globbyOptions` option:

https://github.com/stylelint/stylelint/blob/7fbf2972a3c0d3d0d837fe2ba7964478fc323b7a/lib/standalone.js#L52

**Comment by sidverma32** [comment]
> @sidverma32 To support the `--globby-options` CLI flag, we need to change `lib/cli.js` and pass the new flag value to `standalone()`:

By new `flag` value you mean something like this :
`return standalone(options, newFlag) `

or something like this:
```
if(cli.flags.globbyOptions){
  optionBase.globbyOptions = cli.flags.globbyOptions;
}

```

**Comment by ybiquitous** [comment]
I mean:

```js
if (cli.flags.globbyOptions) {
  optionBase.globbyOptions = cli.flags.globbyOptions;
}
```

**Comment by sidverma32** [comment]
> I mean:
> 
> ```js
> if (cli.flags.globbyOptions) {
>   optionBase.globbyOptions = cli.flags.globbyOptions;
> }
> ```

Thanks for clarification! Please have a look over the raised PR and let me know if i missed any detail.

**Comment by silversonicaxel** [comment]
I tried the upgraded version of stylelint

https://github.com/stylelint/stylelint/pull/6437#issuecomment-1314063407

but I still have the same issue and I wanted to share it again here.
