### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/array-union/index.js from /node_modules/globby/index.js not supported.

### ISSUE THREAD

**Issue by avinashs2401** [stylelint/stylelint#6117]
### What steps are needed to reproduce the bug?

Run `stylelint "src/**/*.scss" --fix`
Angular Version: 13
Node Version: 16.13.1

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-recommended-scss"
  ],
  "rules": {
    "font-family-name-quotes": "always-where-recommended",
    "function-url-quotes": [
      "always",
      {
        "except": ["empty"]
      }
    ],
    "selector-attribute-quotes": "always",
    "string-quotes": "single",
    "max-nesting-depth": 3,
    "selector-max-compound-selectors": 3,
    "selector-max-specificity": "0,3,2",
    "declaration-no-important": true,
    "at-rule-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "property-no-vendor-prefix": true,
    "selector-no-vendor-prefix": true,
    "value-no-vendor-prefix": true,
    "no-empty-source": null,
    "selector-class-pattern": "[a-z-]+",
    "selector-id-pattern": "[a-z-]+",
    "selector-max-id": 0,
    "selector-no-qualifying-type": true,
    "selector-max-universal": 0,
    "selector-pseudo-element-no-unknown": [
      true,
      {
        "ignorePseudoElements": ["ng-deep"]
      }
    ],
    "unit-whitelist": ["px", "%", "em", "rem", "vw", "vh", "deg", "s"],
    "max-empty-lines": 2,
    "max-line-length": 125
  }
}
```

### How did you run Stylelint?

stylelint "src/**/*.scss" --fix

### Which version of Stylelint are you using?

14.8.5

### What did you expect to happen?

Linting should have happened without any issues

### What actually happened?

Error [ERR_REQUIRE_ESM]: require() of ES Module xxx/node_modules/array-union/index.js from xxx/node_modules/stylelint/node_modules/globby/index.js not supported.
Instead change the require of xxx/node_modules/array-union/index.js in xxx/node_modules/stylelint/node_modules/globby/index.js to a dynamic import() which is available in all CommonJS modules.
    at require (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (xxx/node_modules/stylelint/node_modules/globby/index.js:3:20)
    at Module._compile (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at require (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (xxx/node_modules/stylelint/lib/printConfig.js:4:16)
    at Module._compile (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at require (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (xxx/node_modules/stylelint/lib/cli.js:10:21)
    at Module._compile (xxx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.<anonymous> (xxx/node_modules/stylelint/bin/stylelint.js:8:1) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by ybiquitous** [comment]
@avinashs2401 Thanks for writing the report and using the template.

It seems the error is caused by pure ESM dependencies. Stylelint hasn't supported ESM yet (see #5291).

When seeing the stack trace, `globby` or some dependencies in your project may be pure ESM. `globby` has been pure ESM since [v12.0.0](https://github.com/sindresorhus/globby/releases/tag/v12.0.0), while Stylelint uses v11:

https://github.com/stylelint/stylelint/blob/35d29d72e2d462412940084b9b28025f618cf731/package.json#L122

Could you please confirm such dependencies' version?

**Comment by avinashs2401** [comment]
@ybiquitous I haven't installed the `globby` explicitly and looking at `package_lock.json`, globby is present in some places with version 12

**Comment by ybiquitous** [comment]
@avinashs2401 Could you provide some reproduction code (e.g. a repository or gist), please?
