### ISSUE TITLE
Add autofix to declaration-block-no-duplicate-properties

### ISSUE THREAD

**Issue by amarg26** [stylelint/stylelint#6119]
### What is the problem you're trying to solve?

I have set the Stylelint config to remove duplicate CSS properties and values as below. 

```
        "declaration-block-no-duplicate-properties": [
            true,
            {
                "ignore": ["consecutive-duplicates-with-different-values"]
            }
        ],
```
I want to remove the duplicate property values like on the fix lint command or on Ctrl+S but this is not happening at all.
Example as below.

```
.full-screen {
    align-items: center;
    align-items: center;

    //you need to setup file-loader in webpack before you can use images
    background-position: center;
    bottom: 0;
    display: flex;
    display: flex;
    flex-direction: column;

    //_ works with row or column_

    flex-direction: column;
    height: 100%;
    justify-content: center;
    justify-content: center;
    left: 0;
    position: fixed;
    right: 0;
    text-align: center;
    top: 0;
    width: 100%;
}
```

Please let me know how I can achieve this?the 

### What solution would you like to see?

I want to remove the duplicate property values like on the fix lint command and using Ctrl+S

**Comment by ybiquitous** [comment]
@amarg26 Thanks for using the template.

The [`declaration-block-no-duplicate-properties`](https://stylelint.io/user-guide/rules/list/declaration-block-no-duplicate-properties/) rule doesn't provide the *autofix* feature, but do you want autofix?

**Comment by jeddy3** [comment]
Do we want to add autofix to a rule like this? I guess it'd be useful in combination with the autofix in the `no-vendor-prefix` rules.

**Comment by ybiquitous** [comment]
We can fix the following case easily, and it seems useful to me:

```css
a {
  color: pink;
  color: pink; /* should be removed */
}
```

But, can we fix the following case? Which should be removed: `pink` or `organge`?

```css
a {
  color: pink;
  color: orange;
}
```

**Comment by jeddy3** [comment]
> But, can we fix the following case? Which should be removed: pink or orange?

Unless the `"ignore": ["consecutive-duplicates-with-different-values"]` option is set, I think we should fix this case so that the fix behaviour is complete.

We should keep the last option and remove all previous duplicates as that's how the browser is going to interpret it most of the time, e.g.

```css
a {
  color: red; /* remove */
  color: pink; /* remove */
  color: orange;
}
```

**Comment by ybiquitous** [comment]
Thanks for the explanation. That makes sense. 👍🏼

**Comment by amarg26** [comment]
> @amarg26 I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

@jeddy3 Sure, Please let me know in what way I can contribute.

**Comment by ybiquitous** [comment]
@amarg26 No one has touched this issue yet. PR welcome. 😃 

If you could implement the auto-fix and it would be merged, the next minor version would include it.

**Comment by carlosjeurissen** [comment]
Let's make sure fallback logic is not affected by this autofix. For example:
```
a {
  color: orange; /* remove */
  color: purple; /* should not be removed, as rebeccapurple is not supported in all browsers */
  color: rebeccapurple;
}
```

Same goes for calc, variables, and others:
```
div {
  width: 20px; /* remove */
  width: 8px; /* should not be removed, is fallback to calc */
  width: calc(100% - 100px);
}
```

**Comment by ybiquitous** [comment]
@carlosjeurissen Thank you. That's a good point. 👍🏼 

Indeed, can we easily distinguish if fallback or not...? 🤔

**Comment by jeddy3** [comment]
@ybiquitous That's correct. Adding autofix to a rule doesn't change what problems a rule detects, it just autofixes them rather than reporting them. 

> It may be good to note fallbacks in the rule doc when adding autofix.

[We already do that for the consecutive option.](
https://stylelint.io/user-guide/rules/list/declaration-block-no-duplicate-properties/#ignore-consecutive-duplicates)

**Comment by Mouvedia** [comment]
> and remove all previous duplicates as that's how the browser is going to interpret it most of the time

I disagree. There are many cases where a value is ignored because it's not supported and it default to the last valid—in that browser—value. Hence it's very common to have the same property duplicated 2 or 3 times but with different values to cater for the different browsers. A fix that removes these would actually break many websites.
The fix needs to adapt to the different secondary options.
