### ISSUE TITLE
Stylelint doesn't work inside vue custom blocks

### ISSUE THREAD

**Issue by webistomin** [stylelint/stylelint#6125]
### What is the problem you're trying to solve?

Hi! I use [custom blocks](https://vue-loader.vuejs.org/guide/custom-blocks.html#example) in vue, but stylelint doesn't work in them. Is there some way to make this work? Thanks.

### What solution would you like to see?

**Works fine**

![image](https://user-images.githubusercontent.com/30475699/171119541-ca2549c6-e814-44f4-8e05-4add941e4209.png)

**Doesn't work**

![image](https://user-images.githubusercontent.com/30475699/171119673-130b5760-3d3a-4d29-b74a-275f6c37eb85.png)

**Comment by ybiquitous** [comment]
@webistomin Thanks for using the template.

I'm not familiar with Vue, but it seems related to `postcss-html`. The following code in `postcss-html` seems to support only `<style>` tags.

https://github.com/ota-meshi/postcss-html/blob/10539de0cc8ebf5469bd0938842a1cd695b20728/lib/html/extract-styles.js#L39-L42

**Comment by webistomin** [comment]
@ybiquitous thanks for the answer. I'll create an issue there. In the meantime, I tried using [patch-package](https://www.npmjs.com/package/patch-package). Everything works as it should.
