### ISSUE TITLE
Fix TypeError regression for nth-child in selector-max-specificity

### ISSUE THREAD

**Issue by Hypnosphi** [stylelint/stylelint#6139]
### What steps are needed to reproduce the bug?

Reproduction repo: https://github.com/Hypnosphi/stylelint-nth-child

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
    rules: {
        'selector-max-specificity': ['0,2,0'],
    }
}
```

### How did you run Stylelint?

stylelint index.css

### Which version of Stylelint are you using?

`14.9.0`

### What did you expect to happen?

No errors

### What actually happened?

```
index.css
 1:1  ✖  Cannot parse selector (TypeError: Cannot read property 'nodes' of undefined)  parseError
```

**Comment by ybiquitous** [comment]
@Hypnosphi @reintroducing Thanks for opening the issue and using the template. And thank you so much for providing the reproduction repository and demo.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

I will also try to fix the regression soon.

**Comment by ybiquitous** [comment]
Maybe PR #6131 seems to be a cause.

**Comment by ybiquitous** [comment]
I find the error occurs in the [`@csstools/selector-specificity`](https://www.npmjs.com/package/@csstools/selector-specificity) code:

https://github.com/csstools/postcss-plugins/blob/b755ca7806b52d86276d825968832e957c5c2e8a/packages/selector-specificity/src/index.ts#L74

Reproduction:

```js
const parser = require('postcss-selector-parser');
const { selectorSpecificity } = require('@csstools/selector-specificity');

console.log(selectorSpecificity(parser().astSync(':is')));
//=> { a: 0, b: 0, c: 0 }

console.log(selectorSpecificity(parser().astSync(':nth-child')));
//=> TypeError: Cannot read properties of undefined (reading 'nodes')
//=> should be { a: 0, b: 1, c: 0 } ???
```

I'll open an issue for `@csstools/selector-specificity` about the behavior.

**Comment by ybiquitous** [comment]
`@csstools/selector-specificity@2.0.1` has been released 🎉 

I believe it should mitigate the problem.

**Comment by reintroducing** [comment]
Awesome @ybiquitous, thank you for fixing this so quickly. When is the next planned release of Stylelint with this update?

**Comment by ybiquitous** [comment]
@reintroducing I'll release the next patch version tomorrow (#6146). 😃

**Comment by reintroducing** [comment]
great, thank you @ybiquitous!

**Comment by ybiquitous** [comment]
14.9.1 is out! 🎉 
https://github.com/stylelint/stylelint/releases/tag/14.9.1

**Comment by reintroducing** [comment]
@ybiquitous confirmed this is working as expected now, thank you very much for the quick turn around on this.
