### ISSUE TITLE
sassdoc file level annotations are parsed

### ISSUE THREAD

**Issue by davidosomething** [stylelint/stylelint#616]
got
```
Message:
    /home/davidosomething/projects/16.davidosomething.com/assets/scss/global.scss:1:1: Unknown word
////
```

from 
```
////
/// global.scss
//
/// Global styles for davidosomething.com
///
/// @author David O'Trakoun <me@davidosomething.com>
////
```

also, unclosed quote from the apostrophe in the @author line

to fix, probably need to loosen regex on comment indicator to any number of `/[/+]`

http://sassdoc.com/file-level-annotations/

**Comment by jeddy3** [comment]
Hi @davidosomething 

Can you confirm you're using the `scss` `syntax` option? e.g. [like so](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/css-processors.md#parsing-scss) if you're using the Node API or CLI, or [as the second example here](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#usage-examples) if you're using the PostCSS plugin.

If you are then this might be an issue with `postcss-scss`. What do you think @davidtheclark

**Comment by davidtheclark** [comment]
Agreed: Those errors sounds like PostCSS parsing errors, so this would be an issue with postcss-scss.

**Comment by davidtheclark** [comment]
Please re-open if it turns out that I'm wrong.
