### ISSUE TITLE
Add cacheStrategy option

### ISSUE THREAD

**Issue by kaorun343** [stylelint/stylelint#6170]
### What is the problem you're trying to solve?

It seems the current cache strategy of Stylelint is the same with ESLint and Prettier's `metadata` strategy. When running on CI, each file metadata can change at every single CI execution.

### What solution would you like to see?

ESLint and Prettier supports `content` cache strategy. This strategy doesn't depends on metadata but depends on each file's content, so it is very useful when running them at CI.

- https://eslint.org/docs/user-guide/command-line-interface#--cache-strategy
- https://prettier.io/docs/en/cli.html#--cache-strategy

**Comment by jeddy3** [comment]
@kaorun343 Thanks for the request and for using the template.

A new `cacheStrategy` [option](https://stylelint.io/user-guide/usage/options) (being `metadata` (default) or `content`) that is available via the [Node.js API](https://stylelint.io/user-guide/usage/node-api) and the [CLI](https://stylelint.io/user-guide/usage/cli) sounds good to me. 

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
