### ISSUE TITLE
Disallow relative imports

### ISSUE THREAD

**Issue by TD-DO** [stylelint/stylelint#6171]
### What is the problem you're trying to solve?

Everything should be relative to src. For example, when I want something from Users/user/documents/code/project/src/components/A.js to be imported into Users/user/documents/code/project/src/components/B.js it should say 'import {something} from 'components/A' ' instead of 'import {something} from './A' '.

### What solution would you like to see?

It would be nice to have an option to flag everything in a specific folder (or be able to exclude folders) where they have './' or '../' as part of their import string

**Comment by alexander-akait** [comment]
It is CSS linter, we don't handle `import { ... } from "..."l`
