### ISSUE TITLE
Upgrade cosmiconfig and add rc extensions

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#620]
With cosmiconfig 1.1.0, we can add [rcExtensions](https://github.com/davidtheclark/cosmiconfig#rcextensions).

**Comment by TrySound** [comment]
@davidtheclark `^1.0.0` includes `1.1.0`

**Comment by davidtheclark** [comment]
Yeah, but we'd have to change the documentation to inform users of this difference, and change the dependency to ^1.1.0 so all users would definitely get the new feature. Right?

**Comment by TrySound** [comment]
Okay :)
