### ISSUE TITLE
Invalid option value "i" for rule "string-quotes"

### ISSUE THREAD

**Issue by danielgamble** [stylelint/stylelint#621]
Started by seeing my projects seemingly ignoring the `string-quotes` rule and managed to get it down tot his: https://github.com/danielgamble/styletest

Can just `git clone` then `npm i && npm run lint`

**Comment by davidtheclark** [comment]
It must have something to do with the attempt to figure out whether this
config has legacy numbered severities or not. That's all I can guess
without digging in later.

**Comment by davidtheclark** [comment]
You need to upgrade to v3.

**Comment by davidtheclark** [comment]
The config *without numbered severities* only works in v3+.

**Comment by danielgamble** [comment]
Hmm could've swore i had this, if a local `stylelint` is `2.x` but the global is `3.x` which one gets used?

**Comment by davidtheclark** [comment]
If you just type `stylelint something` in the command line, the global will get used. But if you use an npm script, as in the example repo, the *local* one will get used.

**Comment by danielgamble** [comment]
Swore the global + local was failing but i just tested it again with a local `3.x` and it's working. I promise i thought i checked this :D Thanks for the quick fix :)

**Comment by davidtheclark** [comment]
I understand the confusion.

**Comment by jeddy3** [comment]
Oh my... I feel like quite the nincompoop for not seeing version 2 in the `package.json` when I looked into this.
