### ISSUE TITLE
When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-less", and use the "customSyntax" option

### ISSUE THREAD

**Issue by Chen-913** [stylelint/stylelint#6210]
### What steps are needed to reproduce the bug?

package.json：
```json
{
  "name": "123",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "postcss": "^8.4.14",
    "postcss-html": "^1.5.0",
    "postcss-less": "^6.0.0",
    "stylelint": "^14.9.1",
    "stylelint-config-recess-order": "^3.0.0",
    "stylelint-config-recommended-vue": "^1.4.0",
    "stylelint-config-standard": "^26.0.0"
  }
}
```

color.less：
```less
@primary:   #03b9f3;
@base-text-color:   #E7F9FF;
```

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  root: true,
  extends: [
    'stylelint-config-standard',
    'stylelint-config-recess-order',
    'stylelint-config-recommended-vue',
  ],
  overrides: [
    {
      files: '**/*.less',
      customSyntax: 'postcss-less',
    },
    {
      files: '**/*.vue',
      customSyntax: 'postcss-html',
    },
  ],
  rules: {
    indentation: 2,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['mixin', 'extend', 'content', 'include'],
      },
    ],
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['deep'],
      },
    ],
    'function-no-unknown': [true, {
      ignoreFunctions: ['if'],
    }],
  },
};
```

### How did you run Stylelint?

Use vscode plug-in or run scripts to format

### Which version of Stylelint are you using?

14.19.1

### What did you expect to happen?

There are no warnings and the code is formatted normally

### What actually happened?

Whenever I tried to save and format, he warned me

![image](https://user-images.githubusercontent.com/72293244/180108998-941a7cf7-5eab-4725-87c7-d7a316033fc8.png)

### Does the bug relate to non-standard syntax?

Less

**Comment by ybiquitous** [comment]
@Chen-913 Thanks for using the template.

Unfortunately, I cannot reproduce the error by the codes you provide.
Could you please provide a minimal reproduction repository or something?

**Comment by Chen-913** [comment]
@ybiquitous I'd be happy to provide you with an example. Here's the code repository I just created:
https://github.com/Chen-913/bug-demo.git
By the way, the Stylelint plugin I have in VSCode is currently version `1.2.2`

I recorded a `GIF` of my process, thought it might be helpful for you to judge
![Animation](https://user-images.githubusercontent.com/72293244/180174185-7e132084-9cbd-4f13-b257-1c2d7753a6ae.gif)

**Comment by ybiquitous** [comment]
@Chen-913 Thanks for providing the reproduction repository. But I cannot reproduce the error still. See below:

```console
$ npx ci

$ npx stylelint "**/*.{less,vue}" -f verbose

src/components/HelloWorld.vue
 48:3  ✖  Expected "padding" to come before "background-color"  order/properties-order
 50:3  ✖  Expected "color" to come before "border-radius"       order/properties-order

3 sources checked
 /Users/koba/tmp/bug-demo/src/App.vue
 /Users/koba/tmp/bug-demo/src/components/HelloWorld.vue
 /Users/koba/tmp/bug-demo/src/styles/demo.less

2 problems found
 severity level "error": 2
  order/properties-order: 2
```

**Comment by ybiquitous** [comment]
> By the way, the Stylelint plugin I have in VSCode is currently version `1.2.2`
> And I want Stylelint to check both LESS and vue files
> But in the vue file, the same type of warning appears when formatting with Stylelint

Sorry, I'm unfamiliar with VSCode and Vue. If it's a problem with the VSCode plugin, I recommend filing an issue on the [stylelint/vscode-stylelint](https://github.com/stylelint/vscode-stylelint) repository instead of here.

Also, we will not support stylistic rules in the future, so we recommend migration to a pretty printer like Prettier for code-formatting. Please see also our [document](https://stylelint.io/user-guide/rules/list#stylistic-issues).

**Comment by Chen-913** [comment]
@ybiquitous Thank you very much for your suggestions. I prefer the customization of stylelint's personalized rules, which is much freer than Prettier

Should I close this issue?

**Comment by JounQin** [comment]
The should be related to vscode-stylelint does not support pnpm well, you can try to use `public-hoist-pattern[]=*stylelint*` in you project level `.npmrc` and run `pnpm install` to install, then reload vscode.

**Comment by zqy233** [comment]
> By the way, the Stylelint plugin I have in VSCode is currently version `1.2.2`
> And I want Stylelint to check both LESS and vue files
> But in the vue file, the same type of warning appears when formatting with Stylelint

您好，请问下，这个行内的红色报错是怎么做到的，插件还是配置

**Comment by Chen-913** [comment]
> > By the way, the Stylelint plugin I have in VSCode is currently version `1.2.2`
> > And I want Stylelint to check both LESS and vue files
> > But in the vue file, the same type of warning appears when formatting with Stylelint
> 
> 您好，请问下，这个行内的红色报错是怎么做到的，插件还是配置

一个插件：usernamehw.errorlens
