### ISSUE TITLE
Core support for "wrapping" or "extending" rules

### ISSUE THREAD

**Issue by mattxwang** [stylelint/stylelint#6211]
### What is the problem you're trying to solve?

This issue continues [a conversation in the stylelint/contributors team](https://github.com/orgs/stylelint/teams/contributors/discussions/9/comments/4). In particular, there are several accessibility-focused rules that could be defined *based on other rules*. I'll copy what @thibaudcolas had written in the thread as motivation:

> Something else that I think would help is better support for defining rules based on other rules. Take for example my [font-size-relative](https://github.com/thibaudcolas/stylelint-accessible/blob/e38ad48c46933bc02d9937b0d1da1df368810c3a/lib/rules/font-size-relative/index.js#L21-L40) rule – it’s just a wrapper around declaration-property-unit-allowed-list using stylelint’s checkAgainstRule API with a preset list of units.
> 
> It would be perfectly possible for someone to use declaration-property-unit-allowed-list directly like @jeddy3 shows, however declaration-property-unit-allowed-list can only be configured once for a given stylelint configuration – so if your project extends an accessibility-focused config, you’d run the risk of mistakenly disabling those checks if your config separately sets this rule for unrelated reasons. Creating a new rule that "wraps" another solves this quite neatly (as well as the custom error messages problem)

In addition, @jeddy3 also wrote a blueprint for a potential rule, `media-feature-name-unit-allowed-list`, which allows users to only allow a certain list of units *within* the values of media query declarations/names - something which, in theory, could be a "wrapper" around `media-feature-name-allowed-list`. Consider @jeddy3's current mock solution:

```js
{
  "rules": {
     "media-feature-name-value-allowed-list": {
      "/^((min|max)-)?(width|height$)/": ["/[0-9]em$/"]
    }
  }
}
```

I'm sure that beyond these two examples, there are other rule ideas that wrap existing rules. Many of them seem like rules related to accessibility (for example, extending `at-rule-property-required-list` *could* be a strategy for #6202; `declaration-property-value-allowed-list` could be easily extended to only allow logical values for `text-align`, and the disallowed-list could disallow `text-align: justify`, `text-overflow: ellipsis`, and other examples).

### What solution would you like to see?

I'm hesitant to define exactly what my solution is, given my comparative lack of experience in developing for Stylelint. It seems like there are several desired features of wrapping/extending a rule:

- using the logic for another rule, i.e. calling into it
- changing or adding on the error message for an existing rule
- independent configuration, i.e. the configs for wrapped and wrapping rules are defined separately

I'm also not sure if the current plugin system already provides most of these benefits (and I'm just not aware of them), or if instead extra improvements to the plugin system are what we need. It would be great if @thibaudcolas could chime in as well with extra context.

I may also be missing existing ways to do this (maybe there's some way we can just export the rule function, or maybe this is already done). Any thoughts are appreciated!

cc: 

- @thibaudcolas, who originally wrote about this in-thread
- @alexander-akait, who encouraged the writing of this issue
- @jeddy3 for providing a motivating example

**Comment by thibaudcolas** [comment]
@mattxwang 🤘on the three points you want to see:

> using the logic for another rule, i.e. calling into it

That’s already supported! With the [`stylelint.utils.checkAgainstRule`](https://stylelint.io/developer-guide/plugins/#stylelintutilscheckagainstrule) API.

> changing or adding on the error message for an existing rule

Not supported but people have already made the case for this in the past: #4117, #5170.

> independent configuration, i.e. the configs for wrapped and wrapping rules are defined separately

To me that would warrant either a higher-level API in Stylelint, or a separate package that makes this kind of rule wrapping straightforward.

---

Here’s another practical example illustrating all three points:

```js
'property-disallowed-list': [
    // Disallow positioning with physical properties. Use logical ones instead.
    '/(left|right)/',
    // Avoid order – we always want the visual order of elements to match the DOM, for keyboard and screen reader users.
    'order',
    // We prefer to avoid UPPERCASE SHOUTING TEXT.
    'text-transform',
],
```

The first disallowed pattern is to enforce using logical properties and values for RTL support. The second pattern is for keyboard and screen reader users’ experience. The third one is stylistic. They all warrant a custom message as it’s not obvious what the issue might be with the styles this flags. And they all should ideally be override-able by projects reusing this config, without altering the checking of the other conventions

**Comment by jeddy3** [comment]
@mattxwang Thanks for pulling out this part of the discussion too.

As @thibaudcolas said, we already have an API for using the logic of another rule and there are existing issues to improve messaging. It'd be great to complete those issues as we should do what we can to enable plugin authors.

> independent configuration, i.e. the configs for wrapped and wrapping rules are defined separately

I haven't quite grokked what you mean by this. Can you expand on it, please?

**Comment by mattxwang** [comment]
Realizing that this discussion was inadvertently wrapped up elsewhere (within the stylelint team, other PRs/issues, etc.). Going to close since I think it's stale!
