### ISSUE TITLE
Bringing accessibility rules into the core organization/repository

### ISSUE THREAD

**Issue by mattxwang** [stylelint/stylelint#6212]
### What is the problem you're trying to solve?

Following up on [a thread in the stylelint/contributors](https://github.com/orgs/stylelint/teams/contributors/discussions/9/comments/7) team.

There are several different plugins (with varying levels of maintenance) that focus on accessibility:

- https://github.com/YozhikM/stylelint-a11y
- https://github.com/ronilaukkarinen/stylelint-a11y
- https://github.com/thibaudcolas/stylelint-accessible

Overall, I agree that there's a limited niche for Stylelint in the world of accessibility, especially as many accessibility concerns involve context (which linters and other static analysis tools can miss). I do think it's great if we can play a small part in this larger ecosystem.

However, @alexander-akait has mentioned that the importance of accessibility could warrant bringing some of these projects into the core organization. This could help with unifying/deduplicating work, and also improve maintenance of important libraries. That being said, I know the value of these plugins is less clear-cut, and additional maintenance burden is surely nontrivial (we already do a lot)!

## Specific rules

@thibaudcolas has also written up some rule ideas; for posterity's sake (since the thread is private), I'll copy-paste them here:

> So far I’ve focused on rules that are broadly applicable to a lot of different styling methodologies, with few false positives. And in particular rules that can either be implemented "as a config" only / by wrapping existing rules. I was hoping to build all of those myself but would happily see other people take a stab too / instead.
> 
> - RTL support – generally I’d argue multilingual support is an accessibility consideration. So checking for:
>   - Systematic usage of logical properties and values, never physical ones.
>   - Never using `float`. As browser support for flow-relative logical values is very poor.
>   - Only logical values for `text-align`.
> - forced colors / Windows high contrast mode / contrast themes
>   - Never using legacy IE-only media queries
>   - Only using valid system color keywords (no typos, no vendor-specific keywords)
> - General best practices
>   - No `text-align: justify`. Makes it harder to read text.
>   - No `text-overflow: ellipsis` as it hides text
>   - Only relative units for font size
>   - Only em units for media queries
> 
> And finally there are rules that could likely help but aren’t as generally applicable, or would risk creating a lot of false positives. I could see myself wanting to build and enforce those to help on projects with very strict accessibility goals, but they would likely be hard to apply on lots of projects:
> 
> - Correct usage of `prefers-reduced-motion`
> - No `forced-color-adjust: none`
> - No `text-transform: uppercase`. Creates problems when screen readers interpret "ADD" as an acronym
> - No icon fonts – they can create issues for screen reader users if implemented poorly.
> - No background images – as they don’t work in high contrast mode
> - No `position: absolute`. Makes it very hard to create RTL layouts, and also can cause trouble when resizing text

### What solution would you like to see?

I'm thinking that this is less of a "solution to see" and more of a discussion issue: what is the future of these projects, and is this something that we should adopt (similar to the postcss plugins that we now have in our namespace). 

Since I have comparatively little experience in developing for and maintaining Stylelint, I think having seasoned contributors offer their perspective would be very helpful. In addition, having the plugin authors (such as @thibaudcolas, who has been active) chime in would be great!

If we think this is the wrong avenue to have this discussion, feel free to close/move elsewhere!

**Comment by thibaudcolas** [comment]
To give a bit more context about my work-in-progress – it’s an attempt at replacing `stylelint-a11y` since it has become [unmaintained](https://github.com/YozhikM/stylelint-a11y/pull/66). I’m focusing on replacing the parts of that plugin that I think are the most useful, and adding more rules that are straightforward to reason about and maintain.

If we were bringing some of those rules into Stylelint itself, I think it’d make sense to consider #6211 further, as the majority of the rules are just specific configurations and messages for existing rules.

**Comment by ybiquitous** [comment]
As an intermediate idea, what if creating a plugin for such a common a11y ruleset under the [github.com/stylelint](https://github.com) organization? (for example, `stylelint/stylelint-a11y` or `stylelint/stylelint-accessibility` etc.)

I don't think fatting the core more is a good idea.

It would be great if some people interested in a11y could maintain that plugin repository with ownership.

Of course, if there are a11y rules with fewer false positives, I think bringing the rules into the core is worth considering.

**Comment by jeddy3** [comment]
@mattxwang Thanks for pulling the bits together and creating the issue.

I think a plugin pack (like stylelint-accessible) is best. We shouldn't shy away from the plugin system. We created it for precisely this type of problem; i.e. volatile rules that:

- try to align to shifting best practices (introducing breaking changes to a plugin is far easier than to the built-in rules)
- may trigger false positives and negatives (none of the built-in rules trigger false positives or negatives, this is an established user expectation now)

The discussion in https://github.com/stylelint/stylelint/issues/6202 illustrates both of these.

If the community creates a useful accessibility plugin, we can direct people to it in our docs.

> I'm thinking that this is less of a "solution to see" and more of a discussion issue: what is the future of these projects, and is this something that we should adopt (similar to the postcss plugins that we now have in our namespace).

Like all community plugins, it'd live outside of the Stylelint organisation. This rule keeps things clear for our users and us. There are no blessed plugins; each plugin lives and dies by the community they build.

(We eventually intend to remove the postcss-css-in-js package from the Stylelint org once/if the community creates packages to replace it.)

**Comment by jeddy3** [comment]
We should enable plugin authors by adding:

- built-in rules that enable enforcing best-practise on the plugin and/or configuration level (so long as they meet our [criteria for inclusion](https://stylelint.io/user-guide/rules/about)), e.g. `media-feature-name-unit-allowed-list`
- options to the built-in rules to improve the usefulness of the [`stylelint.utils.checkAgainstRule`](https://stylelint.io/developer-guide/plugins#stylelintutilscheckagainstrule), e.g. we often add `ignore*` option to help the stylelint-scss plugin pack authors
- other useful APIs like custom messaging

**Comment by mattxwang** [comment]
Thanks @jeddy3 especially for the context around Stylelint - it's definitely something I lack for this project. A plugin pack + better support for APIs that plugin authors use (ex custom messaging) seems like a great option to me.

@thibaudcolas, perhaps we should reach out to @[ronilaukkarinen](https://github.com/ronilaukkarinen) and try to unify all of the plugins then? And perhaps we can point users to it in the docs in the meantime. Happy to help with any of the logistics (ex if we want to make a new org, documentation, etc.) if that's helpful!

**Comment by Mouvedia** [comment]
> No `position: absolute`
> No background images

That seems really extreme to me.

**Comment by thibaudcolas** [comment]
Those are indeed extreme! I’d expect discussion and research about those rules to be commensurate with how drastic the rules are.

@mattxwang I @-mentioned him on the relevant threads on `stylelint-a11y`. I’d be up for a `stylelint-accessible` org or similar, and either transfer my WIP plugin, or start with a clone of `stylelint-a11y`, or start over completely.

It doesn’t seem like there is another way than issues like this to have (public) discussions about Stylelint and its ecosystem, so I think it’d be nice to keep this issue open and visible a bit longer.

**Comment by ronilaukkarinen** [comment]
While I agree that accessibility should always be default, in CSS it's really hard to automate. Most of the accessibility is achieved only with real testing rather than automation. That being said, we simply cannot disable some rules like display: none; or small font sizes since they may be perfectly fine especially in the use cases where arias are used and/or JavaScript does the heavy lifting or whatever. This is why there should not be any defaults in stylelint either.

However, stylelint-a11y for instance is used for simple "reminders". If a developer uses display: none; accidentally to hide content simply because of laziness or forgets to use proper font-size, it's good to have stylelint to warn about these situations. This is why it would be beneficial to have them as underlying options by default in stylelint package. This is something that I agree on.

Accessibility features should not be a "plugin" to enable "when needed". Accessibility is always needed.

**Comment by gaurav5430** [comment]
What is the current understanding on this, is there a way to use these rules from stylelint core already or should we be using the individual (possibly unmaintained) libraries for now ?

**Comment by jeddy3** [comment]
> What is the current understanding on this

Probably https://github.com/stylelint/stylelint/issues/6212#issuecomment-1192616384 & https://github.com/stylelint/stylelint/issues/6212#issuecomment-1192621791

i.e., it's best that interested parties create an `stylelint-accessible` organisation where they can discuss and implement these rules within a plugin pack as they are likely to have false positives (unlike all the built-in rules). A plugin pack is also ideal as it's easier to iterate, experiment and introduce breaking changes to plugins than it is to the built-in rules.

The org can publish a plugin pack (`stylelint-accessible`) and a shared configuration (`stylelint-config-accessible`) that makes use of the plugin pack. The authors can make judgement calls on whether a rule in the config should be a warning (e.g. acting as "reminders") or an error depending on how likely are false positives.

Once the plugin pack and config are created, we can include a link to them in our docs.

I think we can close this issue now. If there are any features that we can to Stylelint itself to help plugin authors, then we can open new issues for those.

**Comment by mattxwang** [comment]
Yup, agreed with @jeddy3's summary! Apologies for not driving more of this conversation, ended up having less "free time" in the internship to work on Stylelint than I thought 😓 .

It seems like @thibaudcolas knows quite a few of the people in the intersection of Stylelint users and accessibility plugin developers / consumers, so maybe in conjunction with him we'll try to make an organization and consolidate these plugins! Hopefully life will be a little less busy for me soon, and I can take more time doing this.

Going to close this issue (since I originally opened it), appreciate everyone's discussion!

P.S. @jeddy3 did you want me to submit an issue / implement the `media-feature-name-unit-allowed-list`? I can certainly do that, I know I promised it earlier!

**Comment by jeddy3** [comment]
> P.S. @jeddy3 did you want me to submit an issue / implement the media-feature-name-unit-allowed-list? I can certainly do that, I know I promised it earlier!

Yes, please. It'd be useful in its own right but also as a rule that the accessible plugin could use.

**Comment by mattxwang** [comment]
Ah! I never submitted the issue (just going through my GitHub notifs). Just saw that you opened #6509. Happy to take that up!

I'll knock out a few of the other actionables over the rest of this break!

**Comment by schalkneethling** [comment]
Hey folks! Thank you @ybiquitous for pointing me to this issue.

My company, Mechanical Ink, takes accessibility very seriously, and we have always found the `stylelint-a11y` package very useful. It was unfortunate when we realized that the package seemed no longer maintained and was considered foreign and taking over maintenance.

Before doing so, we tried to contact the original author to understand the status. Unfortunately, we were unsuccessful, and when looking into the repository status again, we came across this issue. https://github.com/YozhikM/stylelint-a11y/issues/69

We have now forked the project here (https://github.com/mechanical-ink/stylelint-a11y) to take over maintenance. We plan to publish this on NPM using the `@accessibility` namespace along with other tools, web components, etc., that we are developing at the moment. From what I can tell from reading the thread here, taking over maintenance is a community decision and will not need to be OK'ed by the largest `stylelint` project.

It sounds like having this as a plugin is a better fit than attempting to integrate the rules into Stylelint itself. Unless there are strong opinions or suggestions against this route, we will then continue to address the current problems that are preventing this package from working with the latest version of `stylelint` and then publish this as `@accessibility/stylelint-a11y` on NPM.

Here is an issue to kick off the transition and work. https://github.com/mechanical-ink/stylelint-a11y/issues/1

**Comment by ybiquitous** [comment]
@schalkneethling I'm so glad to hear this big news! I believe it's an excellent decision for many people who are interested in accessibility. 👍🏼

**Comment by schalkneethling** [comment]
> @schalkneethling I'm so glad to hear this big news! I believe it's an excellent decision for many people who are interested in accessibility. 👍🏼

Glad to hear that! Thank you for the support!

**Comment by ronilaukkarinen** [comment]
> Hey folks! Thank you @ybiquitous for pointing me to this issue.
> 
> My company, Mechanical Ink, takes accessibility very seriously, and we have always found the `stylelint-a11y` package very useful. It was unfortunate when we realized that the package seemed no longer maintained and was considered foreign and taking over maintenance.
> 
> Before doing so, we tried to contact the original author to understand the status. Unfortunately, we were unsuccessful, and when looking into the repository status again, we came across this issue. [YozhikM/stylelint-a11y#69](https://github.com/YozhikM/stylelint-a11y/issues/69)
> 
> We have now forked the project here (https://github.com/mechanical-ink/stylelint-a11y) to take over maintenance. We plan to publish this on NPM using the `@accessibility` namespace along with other tools, web components, etc., that we are developing at the moment. From what I can tell from reading the thread here, taking over maintenance is a community decision and will not need to be OK'ed by the largest `stylelint` project.
> 
> It sounds like having this as a plugin is a better fit than attempting to integrate the rules into Stylelint itself. Unless there are strong opinions or suggestions against this route, we will then continue to address the current problems that are preventing this package from working with the latest version of `stylelint` and then publish this as `@accessibility/stylelint-a11y` on NPM.
> 
> Here is an issue to kick off the transition and work. [mechanical-ink/stylelint-a11y#1](https://github.com/mechanical-ink/stylelint-a11y/issues/1)

Maintainer of [@ronilaukkarinen/stylelint-a11y](https://github.com/ronilaukkarinen/stylelint-a11y) fork speaking 👋  As stated [here](https://github.com/ronilaukkarinen/stylelint-a11y/issues/2#issuecomment-1866348056) this could have been my comment from word to word. We've gone through your path as well here at [Dude](https://github.com/digitoimistodude) and I decided to fork the repo couple of years ago because of this very reason. I wanted it so that the repo would not be owned by my company but myself, to underline the fact it was started by a person.

Our approach is to just maintain [the fork](https://github.com/ronilaukkarinen/stylelint-a11y) it as-is, because we used it in [dozens of projects](https://github.com/digitoimistodude/devpackages/blob/700f926e30cee894d41f465274c5108c7a5b74ca/package.json#L13) in our company. Maybe we can co-exist somehow.

This comment is related to issues [#2](https://github.com/ronilaukkarinen/stylelint-a11y/issues/2), [#69](https://github.com/YozhikM/stylelint-a11y/issues/69) and [#1](https://github.com/mechanical-ink/stylelint-a11y/issues/1).

**Comment by schalkneethling** [comment]
> > Hey folks! Thank you @ybiquitous for pointing me to this issue.
> > My company, Mechanical Ink, takes accessibility very seriously, and we have always found the `stylelint-a11y` package very useful. It was unfortunate when we realized that the package seemed no longer maintained and was considered foreign and taking over maintenance.
> > Before doing so, we tried to contact the original author to understand the status. Unfortunately, we were unsuccessful, and when looking into the repository status again, we came across this issue. [YozhikM/stylelint-a11y#69](https://github.com/YozhikM/stylelint-a11y/issues/69)
> > We have now forked the project here (https://github.com/mechanical-ink/stylelint-a11y) to take over maintenance. We plan to publish this on NPM using the `@accessibility` namespace along with other tools, web components, etc., that we are developing at the moment. From what I can tell from reading the thread here, taking over maintenance is a community decision and will not need to be OK'ed by the largest `stylelint` project.
> > It sounds like having this as a plugin is a better fit than attempting to integrate the rules into Stylelint itself. Unless there are strong opinions or suggestions against this route, we will then continue to address the current problems that are preventing this package from working with the latest version of `stylelint` and then publish this as `@accessibility/stylelint-a11y` on NPM.
> > Here is an issue to kick off the transition and work. [mechanical-ink/stylelint-a11y#1](https://github.com/mechanical-ink/stylelint-a11y/issues/1)
> 
> Maintainer of [@ronilaukkarinen/stylelint-a11y](https://github.com/ronilaukkarinen/stylelint-a11y) fork speaking 👋 As stated [here](https://github.com/ronilaukkarinen/stylelint-a11y/issues/2#issuecomment-1866348056) this could have been my comment from word to word. We've gone through your path as well here at [Dude](https://github.com/digitoimistodude) and I decided to fork the repo couple of years ago because of this very reason. I wanted it so that the repo would not be owned by my company but myself, to underline the fact it was started by a person.
> 
> Our approach is to just maintain [the fork](https://github.com/ronilaukkarinen/stylelint-a11y) it as-is, because we used it in [dozens of projects](https://github.com/digitoimistodude/devpackages/blob/700f926e30cee894d41f465274c5108c7a5b74ca/package.json#L13) in our company. Maybe we can co-exist somehow.
> 
> This comment is related to issues [#2](https://github.com/ronilaukkarinen/stylelint-a11y/issues/2), [#69](https://github.com/YozhikM/stylelint-a11y/issues/69) and [#1](https://github.com/mechanical-ink/stylelint-a11y/issues/1).

Heya! I would 100% be in favor of collaborating. How about we start an accessibility-devtools org here on GitHub and use ti to house all the things starting with stylelint-a11y?

**Comment by Mouvedia** [comment]
see also https://github.com/double-great/stylelint-a11y
