### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#622]
I'm tired of dealing with these issues about the two severity sets. Want to release a breaking change?

I think we should also include the cosmiconfig upgrade in this change.

Regarding the other issues: are any of those important enough that we should add them to the milestone and make sure they're done before the next release? I can probably knock a few out if needed.

**Comment by jeddy3** [comment]
> Want to release a breaking change?

Yes please :)

> Regarding the other issues: are any of those important enough that we should add them to the milestone and make sure they're done before the next release?

They're all either new rules, new options , or more tests. There doesn't seem to be any breaking ones. So I think we can slip out, without any fanfare, `v4` once the docs are updated with the cosmiconfig change. Unless you've got a hankering to knock a few out?

**Comment by davidtheclark** [comment]
> Unless you've got a hankering to knock a few out?

We will see. Let's try to get out v4 by the end of the weekend. If anybody, myself included, has time and energy to pitch in and close out some of those issues, by all means go for it.

**Comment by davidtheclark** [comment]
@jeddy3: Are we ready for the v4 release, or was there anything else you want to get in there?

**Comment by jeddy3** [comment]
@davidtheclark Yep, I think we're good to go. All the other issues are now just new rules, new options, more tests or performance related.

Changelog looks good to go too.

**Comment by jeddy3** [comment]
Done :)

:tada:

**Comment by ntwb** [comment]
![Happy Dance](https://i.cloudup.com/QnoqCxHSdL.gif)

**Comment by davidtheclark** [comment]
![celebration-dance](https://cloud.githubusercontent.com/assets/628431/12449709/716af42e-bf3c-11e5-81d0-f1e77d7dff88.gif)
