### ISSUE TITLE
color-function-notation does not flag typos in color notation

### ISSUE THREAD

**Issue by fwraymond** [stylelint/stylelint#6240]
### What steps are needed to reproduce the bug?

Run the rule against this css (note the missing / before 70%)

`.foo { background: rgb(67 67 67 70% );}`

### What Stylelint configuration is needed to reproduce the bug?

any config with color-function-notation enabled

### How did you run Stylelint?

stylelint --fix --allow-empty-input

### Which version of Stylelint are you using?

14.7.1

### What did you expect to happen?

Stylelint would flag the missing slash (/) accordingly

### What actually happened?

stylelint did NOT flag the missing slash (/)

**Comment by ybiquitous** [comment]
@fwraymond Thanks for filing the issue and using the template. We can reproduce the problem on the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AzCEAEwMCMCGYA1gOYBOEArgHZTwanE4AUAbAOwbucdsAMApBgCUAbgC+AHSogANCADOATyoAXPAA8E4efNngIVFAEtiW4FIwYJIUhQA2Medbrmqly9ch2IpALQpqMBUjA18qCDVgg2crEABbaBhSKmsLDEkqMRAxIA).

Unfortunately, the [`color-function-notation`](https://stylelint.io/user-guide/rules/list/color-function-notation) has been designed about the use of function notations like `rgb` or `rgba`, so the rule cannot check the validity of a function notation's arguments.

If you want to validate more, we recommend using a plugin like [stylelint-csstree-validator](https://www.npmjs.com/package/stylelint-csstree-validator) as [our document describes](https://stylelint.io/user-guide/get-started/#your-configuration).

**Comment by jeddy3** [comment]
As @ybiquitous said, you'll want to use a validator alongside (or inside Stylelint via the csstree validator plugin) for this. The [CSSTree validator will catch this](https://csstree.github.io/docs/validator.html).
