### ISSUE TITLE
Fix URL metadata for plugins

### ISSUE THREAD

**Issue by Reda011** [stylelint/stylelint#6245]
### What steps are needed to reproduce the bug?

I  reproduced the question in many Plugins Libraries, such as `stylelint-z-index-value-constraint`、`stylelint-scss` and so on.

Next, take `stylelint-scss` as an example：

step1: 
`npm i stylelint-scss` in my project;

step2: 
creat an test file called `test.less`;

fill it with：(from `stylelint-scss/ selector-no-redundant-nesting-selector`'s testFile)
`
called test.less
`
step3: 
`.stylelintrc.js`

`
module.exports = {
  plugins: [
    "stylelint-scss",
  ],
  rules: {
    "scss/selector-no-redundant-nesting-selector": true,
  },
};
`
step4:
it give me error tips: 'Unnecessary nesting selector (&) (scss/selector-no-redundant-nesting-selector)Stylelint(scss/selector-no-redundant-nesting-selector)'

But,  `Stylelint(scss/selector-no-redundant-nesting-selector)` had no url.

### What Stylelint configuration is needed to reproduce the bug?

module.exports = {
  plugins: [
    "stylelint-scss",
  ],
  rules: {
    "scss/selector-no-redundant-nesting-selector": true,
  },
};

### How did you run Stylelint?

cli

### Which version of Stylelint are you using?

 "stylelint": "^14.9.1","stylelint-scss": "^4.3.0"

### What did you expect to happen?

I click the error tips "...Stylelint(scss/selector-no-redundant-nesting-selector)"

and I can open the web URL which was set in the library.

### What actually happened?

I clicked and I can‘t open the web Url which was set in the library.

**Comment by ybiquitous** [comment]
@Reda011 Thanks for opening the issue and using the template.

This behavior seems to be due to the mismatch between our doc and code on exporting rules.

The doc instructs using multiple `module.exports`,

https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/docs/developer-guide/plugins.md?plain=1#L53-L55

but the built-in rules are using a single `module.exports`:

https://github.com/stylelint/stylelint/blob/e424be5eca77c5532b13147c4a7dad14085a4276/lib/rules/alpha-value-notation/index.js#L203-L206

I think we should make it work in both cases. Maybe, we may need to fix the following code:

https://github.com/stylelint/stylelint/blob/b013ac0827fede2547ba478e920956ff5739af8e/lib/lintPostcssResult.js#L100

---

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by Reda011** [comment]
I checked these Plugins' Libraries, but it doesn't work even using a single module.exports:

[stylelint-scss/selector-no-redundant-nesting-selector](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/selector-no-redundant-nesting-selector/index.js#L88-L90)

Is there any other possibility?

**Comment by ybiquitous** [comment]
@Reda011 Umm..., it seems the `stylelint-scss` plugin works 🤔 
(`verbose` formatter can show a link to `meta.url`)

```console
$ cat package.json
{
  "dependencies": {
    "stylelint": "14.9.1",
    "stylelint-config-recommended-scss": "7.0.0"
  },
  "stylelint": {
    "extends": "stylelint-config-recommended-scss"
  },
  "scripts": {
    "test": "stylelint \"*.{css,scss}\" -f verbose"
  }
}

$ cat a.scss
@foo{}

$ npm it
...
a.scss
 1:1  ✖  Unexpected unknown at-rule "@foo"  scss/at-rule-no-unknown
 1:5  ✖  Unexpected empty block             block-no-empty

1 source checked
 /Users/koba/tmp/foo/a.scss

2 problems found
 severity level "error": 2
  scss/at-rule-no-unknown: 1
  block-no-empty: 1
...
```

<img width="528" alt="image" src="https://user-images.githubusercontent.com/473530/183327448-139bb3c1-c8f5-497d-add1-66d95ed78ac5.png">

**Comment by Reda011** [comment]
uh, I created a new project to test this, looks like it still doesn't work: 

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/21105303/183369984-0eb275da-2de2-4daa-afe5-1a3ae9f2f611.png">

Is it related to my environment?

**Comment by ybiquitous** [comment]
Maybe, some IDEs like VSCode may not support terminal links. See the code of the `verbose` formatter:

https://github.com/stylelint/stylelint/blob/0bd6976fea7fa2a07c47672de424194716d31164/lib/formatters/verboseFormatter.js#L138-L144

https://github.com/stylelint/stylelint/blob/0bd6976fea7fa2a07c47672de424194716d31164/lib/formatters/terminalLink.js#L8-L15

See also [Hyperlinks in Terminal Emulators](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)

**Comment by Reda011** [comment]
Look this, I got these messages without terminal command but automatic verification：

[block-no-empty](https://stylelint.docschina.org/user-guide/rules/block-no-empty/) is a rule, it worked;

[selector-no-redundant-nesting-selector](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/selector-no-redundant-nesting-selector/index.js) and [at-rule-no-unknown](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/at-rule-no-unknown/index.js) are plugins of [stylelint-scss](https://github.com/stylelint-scss/stylelint-scss), they didn't work.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/21105303/183376575-ac83760a-dfae-4988-81ff-4ab714ba1153.png">

**Comment by ybiquitous** [comment]
I'm not sure, but it seems a problem with the VSCode extension... 🤔 

https://github.com/stylelint/vscode-stylelint/blob/d38b5db38debc59e4a00fdb73716202b4b43e38b/src/utils/stylelint/warning-to-diagnostic.ts#L51

**Comment by jeddy3** [comment]
We only recently added the capability for plugins to include optional metadata and none of the ones listed above uses it, including the stylelint-scss plugin pack. 

However, I locally tested a plugin that does and I saw the same behaviour. We will need to look into this more, perhaps adding the fix suggested in https://github.com/stylelint/stylelint/issues/6245#issuecomment-1207515758.

**Comment by Reda011** [comment]
@jeddy3 Ok, thanks!

**Comment by ybiquitous** [comment]
@Reda011 I've opened PR #6264 to fix the plugin document. I think the document is incorrect, not the code.

Maybe, the new doc way as below should work for your plugin: 👇🏼 

https://github.com/stylelint/stylelint/blob/121a34f8e9990ecde7202b4b44a7b30309855169/docs/developer-guide/plugins.md?plain=1#L16-L55

**Comment by jeddy3** [comment]
> We only recently added the capability for plugins to include optional metadata and none of the ones listed above uses it, including the stylelint-scss plugin pack.

My bad. I was looking at a local version of stylelint-scss that was out of date. I hadn't realised @ybiquitous [added URL metadata to the SCSS plugin back in May](https://github.com/stylelint-scss/stylelint-scss/pull/602). 

> Maybe, the new doc way as below should work for your plugin:

I tried this way, but still no success. It may just be a local issue for me. 

> https://github.com/stylelint/stylelint/issues/6245#issuecomment-1207852687

Shall we transfer this issue to the VS Code extension repo? (although it's currently unmaintained)

**Comment by ybiquitous** [comment]
> Shall we transfer this issue to the VS Code extension repo? (although it's currently unmaintained)

Sounds good. 👍🏼 

I previously changed the VSCode extension to use the rule metadata (https://github.com/stylelint/vscode-stylelint/pull/375), but it might be insufficient.

**Comment by ybiquitous** [comment]
I've opened the issue stylelint/vscode-stylelint#415.

**Comment by jeddy3** [comment]
@Reda011 Resolved in latest version of the VS Code extension: https://github.com/stylelint/vscode-stylelint/pull/416

**Comment by Reda011** [comment]
> stylelint/vscode-stylelint#416

Ok, I'll try it, thanks.

**Comment by Reda011** [comment]
I updated stylelint's version to 14.10.0, and it worked in my custom plugins library.

Thank you(@ybiquitous @jeddy3 ).
