### ISSUE TITLE
Use automation for a changelog and release management

### ISSUE THREAD

**Issue by JounQin** [stylelint/stylelint#6253]
### Describe the documentation issue

With https://github.com/changesets/changesets/tree/main/packages/changelog-github, we'll have `thanks` mentions for contributors in our changelog and releases.

### What solution would you like to see?

Enable [`changesets`](https://github.com/changesets/changesets)

---

Alternative, manage `thanks` mentions manually.

**Comment by ybiquitous** [comment]
@JounQin Thanks for the proposal. I have some questions.

1. We have the following workflow already for updating the `CHANGELOG.md` file, but will your proposed tool replace with it?

https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/docs/maintainer-guide/pull-requests.md?plain=1#L27-L32

2. Can we keep the existing CHANGELOG format with this tool? Because the format change may affect the [CHANGELOG page](https://stylelint.io/CHANGELOG) in our website (will permalinks be retained?).

3. Will this tool affect the existing release workflow with `np`?

https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/docs/maintainer-guide/releases.md?plain=1#L7-L17

If a new tool could reduce the tedious work (e.g. updating the changelog file), that would be great!

**Comment by JounQin** [comment]
> We have the following workflow already for updating the CHANGELOG.md file, but will your proposed tool replace with it?

It will.

> Can we keep the existing CHANGELOG format with this tool? Because the format change may affect the [CHANGELOG page](https://stylelint.io/CHANGELOG) in our website (will permalinks be retained?).

Sure, we can define our own changelog format while keeping previous history changelog unmodified.

> Will this tool affect the existing release workflow with np?

We only need to merge a PR like https://github.com/un-ts/prettier/pull/213 for releasing.

**Comment by ybiquitous** [comment]
@JounQin Thanks for the answers. Sounds good to me. 👍🏼

**Comment by hudochenkov** [comment]
We need to consider quality of a changelog before adding any automated tool.

Changelog is one of the most important parts of documentation of any open source project. As I consumer of many open source packages, I've seen lots of changelogs. In my experience automated changelogs usually provide not enough information to the user. Or changelog items are confusing and only make sense to package developers. Or include information, which is not needed to the users (for example dev dependencies updates).

We need to make sure that our changelog provides only needed information and in a good way.

**Comment by JounQin** [comment]
@hudochenkov 

changesets uses user defined changelog, not automated.

And its content can always be changed before releasing.

**Comment by hudochenkov** [comment]
@JounQin Do you want to add `changesets` only for thank you notes?

**Comment by JounQin** [comment]
> @JounQin Do you want to add `changesets` only for thank you notes?

Not at all, It's just a smallest feature of changesets, with changesets we're going maintain CHANGELOG and releasing much easier.

**Comment by hudochenkov** [comment]
Could you write down what do you want to use `changesets` for?

How it will change current [release flow](https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/docs/maintainer-guide/releases.md?plain=1#L7-L17)?

It is important for us to understand everything before time is spent on setting up and configuring new tool.

**Comment by JounQin** [comment]
@hudochenkov OK, let me explain in details.

1. We'll need to install https://github.com/apps/changeset-bot
2. We'll need to add https://github.com/changesets/action like https://github.com/un-ts/prettier/blob/master/.github/workflows/release.yml
3. `changesets` will handle all CHANGELOG and release related tasks
4. For instance, a user or maintainer can add a changeset for CHANGELOG via `changeset add` command, or via GitHub UI like https://github.com/un-ts/prettier/pull/212#issuecomment-1199300439
5. If changesets files exist, a PR would be created by GitHub Actions automatically like https://github.com/un-ts/prettier/pull/213
6. We'll need to decide whether to release on CI or manually.

    - If we do release on CI, then we'll need to provide a `publish` input at https://github.com/un-ts/prettier/blob/master/.github/workflows/release.yml#L43 and a `NPM_TOKEN` secret at https://github.com/un-ts/prettier/blob/master/.github/workflows/release.yml#L46, when we're ready for releasing, we'll only need to merge that PR
    - Otherwise, we just don't provide the `publush` input and `NPM_TOKEN` secret, and we run `npm run release` manually, and then copy the correct part of CHANGELOG to draft a GitHub release, see also https://github.com/changesets/changesets/issues/885

HDYT?

**Comment by hudochenkov** [comment]
Thank you for an explanation!

It might be something interesting to explore. Since I didn't only few releases in the past, I would like to hear from people, who did the most releases: @jeddy3 and @ybiquitous.

**Comment by ybiquitous** [comment]
@JounQin @hudochenkov Thanks for clearing the details!

It seems good to start at a minimum to evaluate the new workflow:

- Install https://github.com/apps/changeset-bot
- Add https://github.com/changesets/action

We can update `CHANGELOG.md` automatically via the two things above, right? Additionally, do we need to write a custom formatter to keep the existing `CHANGELOG.md` format?

If auto-updating `CHANGELOG.md` will be successful, I think we can move on to further automation.

**Comment by JounQin** [comment]
@ybiquitous 

Let's make it work! Feel free to notice me when the GitHub App ready, and then I'm going to raise a PR to enable it in our workflow.

**Comment by jeddy3** [comment]
> It seems good to start at a minimum to evaluate the new workflow:

There's no harm in evaluating a new workflow. Considering we need to be in the terminal for the stylelint-demo and stylelint.io updates anyway, it may prove troublesome to have a different means for releasing Stylelint (and I assume the official configs, and possible all the other packages in the Stylelint org?).

@ybiquitous If you're in favour of evaluating of this workflow then I'm happy to give it ago as you've been doing lots of the releases recently.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the feedback. First, I'll try only the changelog automation. Then, if it doesn't fit, let's revert it.

@JounQin I've installed [changeset-bot](https://github.com/apps/changeset-bot). Could you please open a pull request if you have time?

**Comment by JounQin** [comment]
@ybiquitous I'll raise a PR ASAP.

**Comment by ybiquitous** [comment]
Since there are some problems found in PR #6282, let's try the new workflow in the next iteration (after [14.11.0](https://github.com/stylelint/stylelint/issues/6280))!

**Comment by ybiquitous** [comment]
[14.12.0](https://github.com/stylelint/stylelint/releases/tag/14.12.0) is the first version using the changelog generation! We evaluate that it is easier to update the changelog than before.

But, we encounter a small problem with GitHub Releases. For details, see https://github.com/stylelint/stylelint/issues/6343#issuecomment-1250353973

**Comment by ybiquitous** [comment]
It seems we can now evaluate the new changelog automation workflow. What do you think?

If no objections, we should update the following parts in the maintainer guide:

https://github.com/stylelint/stylelint/blob/e3421aa7d9465f2f5272191d2036b0fd44d14145/docs/maintainer-guide/pull-requests.md?plain=1#L27-L32

https://github.com/stylelint/stylelint/blob/e3421aa7d9465f2f5272191d2036b0fd44d14145/docs/maintainer-guide/releases.md?plain=1#L8-L12

**Comment by JounQin** [comment]
> If auto-updating CHANGELOG.md will be successful, I think we can move on to further automation.
> - @ybiquitous 

@jeddy3 

Do we want `changesets` to replace `np` for releasing further on CI? The downside may be mess due to permission of merge/release. Or maybe we just keep it as-is.

**Comment by ybiquitous** [comment]
@JounQin Please let me ask a few questions.

1. If we publish on CI, will the following 3 to 5 steps no longer be needed?
   https://github.com/stylelint/stylelint/blob/eee9deb35190f46c5f964769d521fef5d7d1d7a8/docs/maintainer-guide/releases.md?plain=1#L13-L15
2. Will changes for the releasing workflow be as follows? (`npm run release` should run `changeset publish`, and we should generate a new npm token for publishing)
   https://github.com/stylelint/stylelint/blob/eee9deb35190f46c5f964769d521fef5d7d1d7a8/.github/workflows/releasing.yml#L46-L48
   ```diff
     version: npm run version
   + publish: npm run release
   env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   + NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
   ```
3. What will publishing via `changeset` do? Pushing a Git tag, publishing a new version to the npm registry, and more? (e.g., generating a GitHub release)

**Comment by JounQin** [comment]
@ybiquitous 

1. Yes, all will be done on CI automatically
2. Yes
3. It will push tag, publish npm version and generate GitHub release (But the release content could be different with our format)

**Comment by ybiquitous** [comment]
@JounQin Thanks for the answer.

> generate GitHub release (But the release content could be different with our format)

Regarding this, it seems possible to prevent generating a GitHub release via the [`createGithubReleases: false` option of `changesets/action`](https://github.com/changesets/action#inputs).

It sounds good to me to publish on CI for easier workflow, but perhaps it may be tough to recover if a publishing CI job would fail. As of now, we don't have a problem with continuing to use `np` manually.

**Comment by JounQin** [comment]
> it seems possible to prevent generating a GitHub release

Glad to hear

> but perhaps it may be tough to recover if a publishing CI job would fail

I'm not sure to understand this part, if the CI job fails, we can just retry it and when the npm version is not published, `changesets` will still recognize it and try to release again

> As of now, we don't have a problem with continuing to use np manually.

Sure, I also don't have a strong opinion on this neither, it just could be a bit redundant to have two release tools while `changesets` can handle it alone.

**Comment by ybiquitous** [comment]
> I'm not sure to understand this part, if the CI job fails, we can just retry it and when the npm version is not published, `changesets` will still recognize it and try to release again

I'm worried about a situation where tagging is successful but publishing is failed. In such a case, it seems harder to recover than manually releasing. Although, it should be rare.

**Comment by JounQin** [comment]
The order is releasing npm version first, then tag and GitHub release, so I don't think the case would be possible. And also, create/delete a tag/release on GitHub UI is very easy.

**Comment by ybiquitous** [comment]
@JounQin Thanks for the explanation. I understand well. 👍🏼 

I'd like to hear @jeddy3's idea.

**Comment by jeddy3** [comment]
> Do we want changesets to replace np for releasing further on CI? The downside may be mess due to permission of merge/release. Or maybe we just keep it as-is.

I think we should keep it as-is as:

- during a release, we're in the terminal anyway to perform other updates (e.g. to the website and demo)
- our other npm package repos use `np`

**Comment by ybiquitous** [comment]
> * during a release, we're in the terminal anyway to perform other updates (e.g., to the website and demo)

That makes sense. I have no objections. 👍🏼
