### ISSUE TITLE
getUnitFromValueNode removed in v14 - no alternative documented

### ISSUE THREAD

**Issue by atomicrobokid** [stylelint/stylelint#6256]
### Describe the documentation issue

Hi,

I have recently moved from v13 to v14, and I had a custom stylelint rule that was checking the values of a particular selector.

It essentially did this:

`const unit = getUnitFromValueNode(node);`

However I can see in v14 `stylelint/lib/utils/getUnitFromValueNode` does not exist

### What solution would you like to see?

There docs that give a clear alternative. How can I do the same as above but in v14? What other functions have been removed?

**Comment by JounQin** [comment]
`stylelint/lib/utils/*` seems not a public API at all. Should we use `exports` field in `package.json` to forbid this usage on `v15`? cc @ybiquitous

**Comment by ybiquitous** [comment]
@atomicrobokid Thanks for using the template.

Unfortunately, we don't support using private implementation like `require ('stylelint/lib/utils/...')`. Generally, please use the exposed API of [`stylelint.utils.*`](https://stylelint.io/developer-guide/plugins#stylelintutils).

If there are many needs for an internal utility, we'll consider exposing it as a public API. But then, please open an issue like #5669.

Of course, you can use private utilities at your own risk. `getUnitFromValueNode()` was changed to [`getDimension()`](https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/lib/utils/getDimension.js#L15) with refactorings through PR #6169, so `getDimension()` may help you instead.

---

> `stylelint/lib/utils/*` seems not a public API at all. Should we use the `exports` field in `package.json` to forbid this usage on `v15`?

@JounQin IMO, forbidding the internal API seems a bit too strict, but I think we can discuss it toward the next major version (v15).

**Comment by atomicrobokid** [comment]
@ybiquitous thanks that did the trick!

One final question while i've got you, i'm trying to report the error for both the value with the unit, but i'm only getting the error under the value itself:

My rule looks like:
<img width="385" alt="Screenshot 2022-08-13 at 17 26 50" src="https://user-images.githubusercontent.com/72664200/184502715-f99f0f03-1f24-40a3-9bba-cfcdb4121502.png">

But i only get the value erroring:
<img width="172" alt="Screenshot 2022-08-13 at 17 27 15" src="https://user-images.githubusercontent.com/72664200/184502723-a9f2f706-3775-4622-bd90-fb24dad7e5ad.png">

Probably me missing something obvious, but I can only seem to ever get the "margin-right" selector to show the error, of the value, in this case 1, without the unit. 

Thanks for your help

**Comment by ybiquitous** [comment]
@atomicrobokid Do you mean you want to show an error position like this?

```css
a {
  margin-right: 1px;
/*              ~~~
                ↑ Here is an error position.
 */
}
```

If so, the following code may help you; specifying not only `index` but also `endIndex` to `report()` ⬇️ 

https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/lib/rules/declaration-property-value-allowed-list/index.js#L51-L61

**Comment by jeddy3** [comment]
I think we can close this issue was resolved by https://github.com/stylelint/stylelint/issues/6256#issuecomment-1213549891

**Comment by atomicrobokid** [comment]
> @atomicrobokid Do you mean you want to show an error position like this?
> 
> ```css
> a {
>   margin-right: 1px;
> /*              ~~~
>                 ↑ Here is an error position.
>  */
> }
> ```
> 
> If so, the following code may help you; specifying not only `index` but also `endIndex` to `report()` ⬇️
> 
> https://github.com/stylelint/stylelint/blob/4772851c0a1745db03f149ac35a2de6fe375c369/lib/rules/declaration-property-value-allowed-list/index.js#L51-L61

Hmmm, no joy on that, still only highlights the number, checked my versions of `postcss-value-parser` and `stylelint` to make sure they're up to date and they are.

Even took the above code as a base for my rule, would you mind seeing if you can spot anything obvious in the code?
[https://gist.github.com/atomicrobokid/7e8fc4e714a28ae6ad81ef81e0c1ea38](https://gist.github.com/atomicrobokid/7e8fc4e714a28ae6ad81ef81e0c1ea38)

The rule itself is configured like this:
```
"rules": {
    "enforce-grid-base-unit": [
      true,
      {
        "unitVariable": "$grid-base-unit",
        "unitValue": 8,
        "unitThreshold": 64
      }
    ],
}
```

Thanks again!

**Comment by ybiquitous** [comment]
@atomicrobokid Can you confirm if `endLine` and `endColumn` are correctly output via the CLI command with the JSON formatter like this?

```console
$ stylelint -f json '*.css' | jq .
...
      {
        "line": 2,
        "column": 12,
        "endLine": 2,
        "endColumn": 15,
        "rule": "length-zero-no-unit",
        "severity": "error",
        "text": "Unexpected unit (length-zero-no-unit)"
      }
...
```

If you cannot see the incorrect end positions only with VSCode, it may be a problem of the VSCode extension (see https://github.com/stylelint/vscode-stylelint/issues/336).

**Comment by atomicrobokid** [comment]
Hi @ybiquitous - I can see `column` and `endColumn` are different values in terminal:

```
 {
        "line": 8,
        "column": 19,
        "endLine": 8,
        "endColumn": 22,
        "rule": "enforce-grid-base-unit",
        "severity": "error",
        "text": "Unexpected unit \"px\" for property \"margin-right\""
      }
```

This is using Webstorm, and from what I can see this doesn't use a plugin, it uses the `node_modules` stylelint package

**Comment by atomicrobokid** [comment]
So are we thinking from the above output that's an issue with, Stylelint, or my code itself @ybiquitous ??

**Comment by jeddy3** [comment]
@atomicrobokid It looks like the JSON output is showing that your plugin is working correctly (as the `column` and `endColumn` values look correct). We only recently added end positions to Stylelint ([as of version `14.7.0`](https://stylelint.io/CHANGELOG#1470)), so the Webstorm integration may not support them yet. I suggest opening an issue in their issue tracker.

**Comment by atomicrobokid** [comment]
Perfect @jeddy3 thank you for the response. I've raised it with them so i'll report back if they have any questions or they resolve the issue.

Thank you all again :)
