### ISSUE TITLE
Use `exports` field in `package.json` to forbid unexpected API usage

### ISSUE THREAD

**Issue by JounQin** [stylelint/stylelint#6258]
`stylelint/lib/utils/*` seems not a public API at all. Should we use `exports` field in `package.json` to forbid this usage on `v15`? cc @ybiquitous

_Originally posted by @JounQin in https://github.com/stylelint/stylelint/issues/6256#issuecomment-1213537779_

**Comment by ybiquitous** [comment]
Help from @regseb on <https://github.com/stylelint/stylelint/pull/7159/files#r1318318623>.

```json
{
  "exports": {
    ".": {
      "import": "./lib/index.mjs",
      "require": "./lib/index.cjs"
    },
    "./package.json": "./package.json"
  }
}
```

Exporting also `package.json` may be better. See https://github.com/depcheck/depcheck/issues/754#issuecomment-1582636531

**Comment by Mouvedia** [comment]
https://github.com/stylelint/stylelint/commit/310c9ad39add73c7d9af0f5c6d0a1832a272aa4d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R31
