### ISSUE TITLE
New rule: function-operator-space

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#63]
Typical whitespace --- but this one in combination with `function-comma-space` makes me think I should write a general utility for finding things in values that are inside of (or outside of) functions.

**Comment by davidtheclark** [comment]
Does anybody know about operators other than `+` `-` `*` and `/` that we'd need to check?

**Comment by MoOx** [comment]
Not sure there is others. (Not for calc() at least)

**Comment by jeddy3** [comment]
Same, don't know of any others. http://www.w3.org/TR/css3-values/#calc

**Comment by davidtheclark** [comment]
@MoOx raised a point here: https://github.com/stylelint/stylelint/issues/62#issuecomment-102247076

> But for function-operator-space it's a bit more tricky since you can have +10% value (see color function spec).

Yeah, so the whitespace is significant *to the language* not just the style around `+` and `-`, cf. http://www.w3.org/TR/css3-values/#calc-syntax. Does that mean we should restrict this rule to `calc()` only? `calc-operator-space`?

**Comment by MoOx** [comment]
`calc-operator-space` looks like an edge case, maybe we can postpone that.

**Comment by davidtheclark** [comment]
Unsure where this conversation left off. Let's clarify: Do we want `calc-operator-space`? It seems like the only situation we're aware of where function-operator-space would actually apply.

I use `calc()` enough in my stylesheets that I think that would be a valuable rule.

**Comment by MoOx** [comment]
If you want to do it, go :)
I was just thinking it can be low priority. Do whatever you need ;)

**Comment by davidtheclark** [comment]
OK, got it.
