### ISSUE TITLE
Fix false positives for container queries in `*-no-unknown`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#6304]
### What is the problem you're trying to solve?

CSS Container Queries will be shipped on Chrome 105 soon. See [Can I use](https://caniuse.com/css-container-query-units):

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/473530/186792292-da88abb2-71fe-41a6-9006-1598b829fca0.png">

However, the `at-rule-no-unknown` rule doesn't support the new at-rule `@container` from the spec. See the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACkB2AXAhgS1TATgAQAUAtrgLQDu2U6AFvIQOwAMrADgB4CUwAOqkKEAdGEz4ohAUOGEo2AM4cANpgCeTAOb5aAbkFzCO2hXQxSqzOYqQVAV1KpFTAEwAzIgEZPB2QF9BQNQQABoQRXUMTC4EcEVFMPAIVHdsLTiZYX4QfHsVGEUcpiy5HOsKPIKKVAgKe1QAa1qqVGLCdDyYQ0Jg-xB-IA):

<img width="500" alt="image" src="https://user-images.githubusercontent.com/473530/186792390-e0505dd6-9500-4c36-b32e-0a2eb01cbf20.png">

Ref:

- [CSS Containment Module Level 3](https://drafts.csswg.org/css-contain-3/)
- [CSS Container Queries - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries)
- [@container and :has(): two powerful new responsive APIs landing in Chromium 105 - Chrome Developers](https://developer.chrome.com/en/blog/has-with-cq-m105/)

### What solution would you like to see?

It seems to me that we can support the new at-rule by adding `container` to the at-rule list. See the related code:

- https://github.com/stylelint/stylelint/blob/cde3a14ebf8e28f4a21e9ebc0c5e1a98bbffcd0f/lib/rules/at-rule-no-unknown/index.js#L54
- https://github.com/stylelint/stylelint/blob/cde3a14ebf8e28f4a21e9ebc0c5e1a98bbffcd0f/lib/reference/atKeywords.js#L26

**Comment by fpetrakov** [comment]
LGTM🗿

**Comment by ybiquitous** [comment]
I would like to move this issue "ready to implement" if there are no objections.

Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by ybiquitous** [comment]
FYI, Firefox seems to be in the process of [implementing CSS container queries](https://bugzilla.mozilla.org/show_bug.cgi?id=1744221).
