### ISSUE TITLE
Add no-at-import or prefer-at-use

### ISSUE THREAD

**Issue by ericghpham** [stylelint/stylelint#6313]
### What is the problem you're trying to solve?

https://sass-lang.com/documentation/at-rules/import

The Sass team discourages the continued use of the `@import` rule. Sass will [gradually phase it out](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline) over the next few years, and eventually remove it from the language entirely. Prefer the [@use rule](https://sass-lang.com/documentation/at-rules/use) instead. (Note that only Dart Sass currently supports `@use`. Users of other implementations must use the @import rule instead.)

### What solution would you like to see?

A new rule that encourages use of `@use` in place of `@import`

**Comment by ybiquitous** [comment]
@ericghpham Thanks for using the template.

A rule you suggest is related to the [`stylelint-scss`](https://github.com/stylelint-scss/stylelint-scss) plugin and should not be included in the Stylelint built-in rules, according to the [rule criteria](https://stylelint.io/user-guide/rules/about/).

Please consider opening a feature request issue to the `stylelint-scss` repository instead.

By the way, the [`at-rule-disallowed-list`](https://stylelint.io/user-guide/rules/list/at-rule-disallowed-list) rule may meet your needs; for example, in this [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACBLAtgBwgJwC4AIAdEAMwgmIG4QAaEAZwE8A7XAQwA8EGx77bwEZiRQBzbsELN8RENgCuAGxj1i8fJOkzZbXAFoFyvVBT02ixRADuMKHsWnca-AG0p27cXRY8xGu48NAMDZNBUzURhnYgAFbBgSGGwiQmIkeXoo1JB8CAA3JJS07xwnbOJg7QBfSoBdAJrmKpAqoA).
