### ISSUE TITLE
Add function-calc-no-redundant-parentheses rule

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#632]
```css
h1 {
    height: calc((10) + (10));
}
```
We don't need extra parens. What do you think?

**Comment by jeddy3** [comment]
I think I'd be more than happy to accept a PR for this.

We'll need to decide on the scope of the rule though. Perhaps it's best to keep this laser-focused on `calc` functions to begin with. We can always add more rules down the line for other contexts.

As such, we'd probably want to name this: `function-calc-no-superfluous-parentheses`... although, there might be a better/more-common alternative word than `superfluous` that we can use.

@davidtheclark What do you think?

**Comment by davidtheclark** [comment]
Where might this even apply other than calc?

How about supernumerary-parentheses? :)

Or "extra" or "redundant"?

**Comment by evilebottnawi** [comment]
@davidtheclark sass, less and other. I think this rule don't break compatibility if i use not pure css.

**Comment by davidtheclark** [comment]
@evilebottnawi: You're talking about calculations outside of an actual function invocation, right?

If someone can pull off a PR doing that, I'd consider (would also make a great plugin); but it sounds kind of nightmarish so I don't plan to work on that myself.

**Comment by evilebottnawi** [comment]
@davidtheclark I think rule need lint only `calc`, but not break if i use sass, less and etc. For sass, less and etc exist custom rules and this do not treat this issue.

**Comment by davidtheclark** [comment]
Cool.

**Comment by jeddy3** [comment]
> How about supernumerary-parentheses? :)

That's another one of your words I had to look up :)

Shall we go with "redundant" as, I think, that's quite a familiar term to developers (whether their first language is English or not)?

**Comment by davidtheclark** [comment]
Sure. @evilebottnawi sound good to you?

**Comment by evilebottnawi** [comment]
@davidtheclark yes

**Comment by davidtheclark** [comment]
What determines redundant parentheses? Just if there is no operator inside them that is not within another nested parentheses-pair?

**Comment by jeddy3** [comment]
This could get [quite involved](http://stackoverflow.com/questions/18400741/remove-redundant-parentheses-from-an-arithmetic-expression). 

> Just if there is no operator inside them that is not within another nested parentheses-pair?

Perhaps we should just go with that?

**Comment by davidtheclark** [comment]
Then again, if we don't follow all that logic this rule hardly does what it promises.

**Comment by jeddy3** [comment]
Good point.

**Comment by evilebottnawi** [comment]
It may be to help https://gist.github.com/nderkach/d59ab888c99bf511f74c (python)

**Comment by jeddy3** [comment]
Looks good. It feels like such a thing would make a good independent npm module e.g. `reduce-parentheses`?

**Comment by evilebottnawi** [comment]
@jeddy3 yep on next week i create

**Comment by jeddy3** [comment]
Excellent :)

**Comment by davidtheclark** [comment]
I'm going to close this one, for a few reasons:

- There hasn't been any action here for a good long while. 
- I can't find any existing npm modules implementing the algorithm we'd need to do this accurately.
- Following the above, ESLint doesn't do this.
- This rule will stumble a lot around people's personal preferences about adding extra parentheses to improve legibility.

**Comment by evilebottnawi** [comment]
@davidtheclark yep
