### ISSUE TITLE
Specific file not capturing linting

### ISSUE THREAD

**Issue by calebepaglioza** [stylelint/stylelint#6324]
### What steps are needed to reproduce the bug?

Hello,

This looks like a very specific issue I've been experiencing where just one specific CSS file (apparently) out of a whole repo doesn't capture stylelint alerts in VS Code.

**First issue (my be related to the second)**
1. Run `npx stylelint path/to/file/src/style_1.css` or `stylelint path/to/file/src/style_1.css`
2. Get this output on VS Code terminal: `Error: All input files were ignored because of the ignore pattern. Either change your input, ignore pattern or use "--allow-empty-input" to allow no inputs
    at standalone (/home/epglclb/cda-web/web/node_modules/stylelint/lib/standalone.js:272:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Second issue**
When running stylelint command for style_2.css in the same folder where style_1.css is located, **it works**. It's noticeable also that stylelint VS Code extension doesn't work for style_1.css, however it does for style_2.css (considering again that they're in the same folder).

How to solve that?

### What Stylelint configuration is needed to reproduce the bug?

```
{
  "reportNeedlessDisables": true,
  "reportInvalidScopeDisables": true,
  "reportDescriptionlessDisables": true,
  "plugins": ["stylelint-order"],
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-hudochenkov/order",
    "stylelint-config-prettier",
    "stylelint-config-recommended"
  ],
  "rules": {
    "selector-type-no-unknown": [true, { "ignore": ["custom-elements"] }],
    "font-family-no-missing-generic-family-keyword": [
      true,
      { "ignoreFontFamilies": ["Ericsson Icons"] }
    ]
  },
  "ignoreFiles": ["**/*.js", "**/*.md", "**/*.json", "**/*.html"]
}
```

### How did you run Stylelint?

`npx stylelint path/to/file/src/style_1.css`

### Which version of Stylelint are you using?

`14.11.0`

### What did you expect to happen?

I expect stylelint to lint any CSS file in my repo.

### What actually happened?

The following happens when trying to lint a specific CSS file inside the same folder that stylelint lints a second CSS file as it's supposed to:

Here's an example of the repo folder structure we use:

```
repo
  client
    components
      component-1
        src
          <JS files...>
          style_1.css
          style_2.css
  .stylelintrc
  package.json
  ...
```

### Does the bug relate to non-standard syntax?

No

**Comment by ybiquitous** [comment]
@calebepaglioza Thanks for using the template. Can you please provide a minimal reproduction repository so that we can look into the problem?

Also, can you reproduce it on the command-line, or only on VSCode?

**Comment by calebepaglioza** [comment]
Hi @ybiquitous, thank you for responding.

Please, let me know if the screenshot below is enough to reproduce the error (I can't provide any zipped repo since it's too sensitive):
![image](https://user-images.githubusercontent.com/6879705/188636805-46cc5c15-141f-4f1f-9198-b9ec0ef5329a.png)

I can reproduce the same error on both the command-line and VSCode.

Also it might be good to know that I'm using VSCode Remote on Windows 10 Enterprise. The repo is based on Linux Ubuntu 20.04.2 LTS virtual machine.

**Comment by ybiquitous** [comment]
I'm afraid that I cannot reproduce the error. Can you reproduce and share it in your personal and public repository, including minimum dependencies and source files?

**Comment by jeddy3** [comment]
Closing as stale. Feel free to reopen with a reproducible repo.
