### ISSUE TITLE
Incorrect autofix for Sass indented mixins

### ISSUE THREAD

**Issue by bartoszmaka** [stylelint/stylelint#6325]
### What steps are needed to reproduce the bug?

1. Run stylelint on file containing mixin.
2. The mixin line is gone

Sample file:
``` sass
// assets/stylesheets/components/alerts.sass
.alert__undo
  background: #33343A !important
  height: 80px

.error-alert
  +box-shadow($box-shadow)
  border-color: $error-darker
  margin: $m-sm auto
  width: 50%

  span
    color: $error-darker
    display: flex
    font-weight: 500
    justify-content: space-between
    line-height: $m-base
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-prettier",
    "stylelint-config-recommended-scss",
    "stylelint-config-standard",
  ],
  "customSyntax": "postcss-sass",
  "plugins": [
    "stylelint-order",
    "stylelint-scss"
  ],
  "rules": {
    "indentation": 2,
    "order/properties-alphabetical-order": true
  }
}
```

### How did you run Stylelint?

`yarn stylelint 'assets/stylesheets/*.sass' --fix --custom-syntax`

### Which version of Stylelint are you using?

`^14.11.0`

### What did you expect to happen?

I expect the file to keep the `+box-shadow($box-shadow)` line after stylelint is run

### What actually happened?

The mentioned line is removed from the file.

### Does the bug relate to non-standard syntax?

SASS

**Comment by ybiquitous** [comment]
@bartoszmaka Thanks for opening the issue and using the template.

We can reproduce the bug in the following minimal example:

`package.json`:

```json
{
  "dependencies": {
    "postcss-sass": "0.5.0",
    "stylelint": "14.11.0"
  },
  "stylelint": {
    "customSyntax": "postcss-sass",
    "rules": {}
  }
}
```

`test.sass`:

```sass
.foo
  +some-mixin($bar)
```

Run:

```console
$ npm install
...

$ npx stylelint *.sass
(no output)

$ npx stylelint *.sass --fix
(no output)
```

Output:

```diff
-.foo
-  +some-mixin($bar)
```

---

I'm not sure about a cause, but perhaps `postcss-sass` may be related.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by ybiquitous** [comment]
As I said, it seems to be a `postcss-sass` problem. There is a similar report on the `postcss-sass` repo: https://github.com/AleshaOleg/postcss-sass/issues/175

**Comment by ybiquitous** [comment]
Unfortunately, [`postcss-sass`](https://github.com/AleshaOleg/postcss-sass) and [`gonzales-pe`](https://github.com/tonyganch/gonzales-pe) internally used by `postcss-sass` seems not to be actively maintained. 😓
