### ISSUE TITLE
Fix incorrect URL hashes in documents

### ISSUE THREAD

**Issue by kimulaco** [stylelint/stylelint#6346]
### Describe the documentation issue

If the document's URL hash is camel case, the scroll position does not match.
Because the Docusaurus is to convert the id from camel case to lower case.

**Example:** 
The "More info" hash in the [Command Line Interface (CLI)](https://stylelint.io/user-guide/usage/cli) is a camel case.
https://github.com/stylelint/stylelint/blob/main/docs/user-guide/usage/cli.md?plain=1#L17

However, the actual id set is lower case.
https://stylelint.io/user-guide/usage/options/#allowemptyinput

Other pages may have the same problem.

### What solution would you like to see?

I think it is one of the following.

- Change hash to lower case.
- Specify the id in the camel case heading.
    - e.g. ``## `allowEmptyInput` {#allowEmptyInput}``
    - https://docusaurus.io/docs/next/markdown-features/toc#heading-ids

I prefer the latter because it is more readable.

I can send a PR.

**Comment by ybiquitous** [comment]
@kimulaco Thanks for the report.

I think the following suggestion is better:

> Change hash to lower case.

because the markdown documents can also be read on GitHub.com or in other ways. I think it preferable to follow the standard Markdown syntax as possible.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by ybiquitous** [comment]
By the way, I wonder [`remark-lint` doesn't seem to support a rule](https://github.com/remarkjs/remark-lint#rules) what we want here. I wish to check by [`@stylelint/remark-preset`](https://github.com/stylelint/remark-preset) if possible.

**Comment by kimulaco** [comment]
> because the markdown documents can also be read on GitHub.com or in other ways. I think it preferable to follow the standard Markdown syntax as possible.

I agree to this reason. Sure, it is better not to depend on tools.
I will send a PR of fix the hash to lower case.
