### ISSUE TITLE
Can rule function-no-unknown support to recognize function such as fade that defined in non-standard synctax ?

### ISSUE THREAD

**Issue by Laffery** [stylelint/stylelint#6360]
### What steps are needed to reproduce the bug?

In fact, creating any simple project which uses `less` can easily reproduce this problem.

for example

```sh
npm init @vitejs/app
npm create vite demo -- --template react-ts

npm i stylelint -D
npm i less postcss-less
```

create a `src/test.less` with style as follows: (function `fade` is defined in less, rather than CSS)

```less
.test {
	background-color: fade(hsl(50%, 50%, 50%), 0.1);
}
```

then run stylelint CLI

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "customSyntax": "postcss-less",
  "rules": {
    "function-no-unknown": [true]
  }
}
```

### How did you run Stylelint?

npx stylelint **/*.less

### Which version of Stylelint are you using?

`14.12.1`

### What did you expect to happen?

expect stylelint to recognize functions that are defined in a non-standard syntax such as Less

### What actually happened?

![image](https://user-images.githubusercontent.com/49607541/192215756-995f9daa-1550-4a14-842d-a258ebf0399a.png)

### Does the bug relate to non-standard syntax?

Less

**Comment by JounQin** [comment]
https://github.com/stylelint/stylelint/blob/main/lib/rules/function-no-unknown/README.md#optional-secondary-options

You can already do this with the second options `ignoreFunctions`.

**Comment by jeddy3** [comment]
@Laffery Thanks for the report.

From the [rule's README](https://stylelint.io/user-guide/rules/list/function-no-unknown):

> This rule considers functions defined in the CSS Specifications to be known.
> This rule ignores double-dashed custom functions, e.g. `--custom-function()`.


Stylelint and the built-in rules are geared towards standard CSS syntax as non-standard language extensions come and go. For example, the Less community doesn't appear to be very active these days and only a few Stylelint plugins have been written for it. You're also welcome to [write and publish your own plugin](https://stylelint.io/developer-guide/plugins) that is geared towards non-standard Less functions. The SCSS community [does still already](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/function-no-unknown/README.md) within their [stylelint-scss plugin pack](https://github.com/stylelint-scss/stylelint-scss/). As @JounQin said, you can make use of the `ignoreFunctions` secondary option in your plugin or within your config.
