### ISSUE TITLE
Update number of rules in README

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#639]
https://github.com/stylelint/stylelint/blob/master/README.md#features currently states:
• `Nearly a hundred rules:`

Stylelint currently has exactly 100 rules, we should update the docs to reflect this as part 4.0

**Comment by jeddy3** [comment]
> Stylelint currently has exactly 100 rules

That's worth celebrating :) :tada: 

> we should update the docs to reflect this as part 4.0

Sgtm
