### ISSUE TITLE
New rule: number-trailing-zero

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#64]
Do we think it's reasonable that a person might want to *require* trailing zeros?

If not, maybe this should be `number-no-trailing-zero`.

**Comment by MoOx** [comment]
> Do we think it's reasonable that a person might want to require trailing zeros?

We never know what people might want to do :/

`number-no-trailing-zero` lgtm anyway.

**Comment by jeddy3** [comment]
> We never know what people might want to do :/

Ha, indeed.

> If not, maybe this should be number-no-trailing-zero.

Yeah, I wasn't sure when I converted it to the `number-trailing-zero` format as it was originally as `*-no-*` rule. I think I did it for:

a. Consistency with the other number rules.
b. To give the user the choice (as @MoOx pointed out).

If it's no more work to support `number-trailing-zero` than `number-no-trailing-zero`,  then I think it's worth doing. But if it's more work than `number-no-trailing-zero`, then I don't think it's worth it for now.

I'm easy either way :)

**Comment by davidtheclark** [comment]
Well, it's only a little more work; but it is more code & tests to maintain in the long run. Also it's a representative problem: we can't enforce all possible rules, so we have to practice drawing the line (which can always be revised based on user requests). I think we should leave it as `*-no-*` until somebody requests otherwise, because I'm having a really hard time imagining that somebody would want to insist trailing zeros everywhere.

**Comment by jeddy3** [comment]
Agreed. Seems like a good one to draw the line with.
