### ISSUE TITLE
no-unsupported-browser-features

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#644]
https://github.com/anandthakker/doiuse already knows how to do it. It would have been insanely convenient and usually would when writing code does not lose sight of the browser support. Analogues of such a rule, I have not seen anywhere else. What do you think guys?

**Comment by davidtheclark** [comment]
This might be same situation as with postcss-bem-linter: the tool itself (in this case doiuse) already exists, but you want to integrate it into stylelint's API for the reporting, text editor linting, etc. —— which is a perfect case for a plugin, right?

**Comment by jeddy3** [comment]
I was just about the say the same thing. I think [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern) would be a great example to follow here if you want to give it a go @evilebottnawi .

**Comment by evilebottnawi** [comment]
@davidtheclark @jeddy3 Do you think it is not necessary to make this rule into the core? It's true it would be very cool, and I think be allocated against other linters.

**Comment by jeddy3** [comment]
I think this is exactly the type of functionality the plugin system was originally built for. Feel free to have a go at creating it, I think it'll end up being a great plugin :)

**Comment by davidtheclark** [comment]
As discussed in #781, let's see how this goes as a core rule. I think it needs a better name. 

`browser-support`?

**Comment by jeddy3** [comment]
>  I think it needs a better name.

Agreed. 

What we're doing here is disallowing the use of features unsupported by a user's target browser. I also think this should be a `no` rule as it doesn’t make sense to enforce the opposite i.e. requiring the user to only use unsupported features. 

Therefore, how about: `no-unsupported-browser-features`

**Comment by davidtheclark** [comment]
Great. I'll change the issue title.
