### ISSUE TITLE
stylelint can't automatically format on save

### ISSUE THREAD

**Issue by W-Ace** [stylelint/stylelint#6441]
### What steps are needed to reproduce the bug?

When I was using stylelint 13, it was working fine, but for some reason after I upgraded to version 14, the fix on save function didn't work, but stylelint has correctly marked the error.

### What Stylelint configuration is needed to reproduce the bug?

```js
  // stylelint.config.cjs

  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-recommended-vue',
  ],
  customSyntax: 'postcss-html',
  overrides: [
    {
      files: ['**/*.{scss,css,sass}'],
      customSyntax: 'postcss-scss',
    },
  ],
  plugins: [
    'stylelint-scss',
    'stylelint-order',
  ],
```

```json
  // package.json

  "devDependencies": {
    "@babel/core": "^7.19.6",
    "@babel/eslint-parser": "^7.19.1",
    "@types/node": "^18.11.8",
    "@vitejs/plugin-vue": "^3.2.0",
    "eslint": "^8.26.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-sort": "^2.4.0",
    "eslint-plugin-vue": "^9.7.0",
    "postcss": "^8.4.18",
    "postcss-html": "^1.5.0",
    "postcss-scss": "^4.0.5",
    "prettier": "^2.6.0",
    "prettier-plugin-tailwindcss": "^0.1.11",
    "sass": "^1.55.0",
    "stylelint": "^14.14.0",
    "stylelint-config-recommended-vue": "^1.4.0",
    "stylelint-config-standard-scss": "^6.0.0",
    "stylelint-order": "^5.0.0",
    "stylelint-scss": "^4.3.0",
    "typescript": "^4.6.4",
    "vite": "^3.2.0",
    "vite-plugin-pages": "^0.27.1",
    "vue-tsc": "^1.0.9"
  }
```

```json
  // setting.json
  
  {
  "files.associations": {
    "*.vue": "vue"
  },
  "editor.formatOnSave": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.tslint": true,
    "source.fixAll.stylelint": true,
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "editor.cursorSmoothCaretAnimation": true,
  "files.eol": "\n",
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.quickSuggestions": {
    "strings": true
  },
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "files.autoSaveDelay": 500,
  "prettier.singleQuote": true,
  "emmet.triggerExpansionOnTab": true,
  "editor.snippetSuggestions": "top",
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "stylelint.snippet": [
    "css",
    "less",
    "postcss",
    "scss"
  ],
  "stylelint.validate": [
    "css",
    "less",
    "postcss",
    "scss",
    "html",
    "javascript",
    "vue-html",
    "vue-postcss",
    "sass",
    "markdown",
    "vue",
  ],
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
   "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "bracketPairColorizer.depreciation-notice": false,
  "i18n-ally.localesPaths": [
    "src/locales/lang",
    "lang",
    "src/locales",
    "src/lang",
  ],
  "i18n-ally.enabledParsers": ["js", "json"],
  "i18n-ally.displayLanguage": "zh_cn",
  "html.autoClosingTags": false,
}
```

### How did you run Stylelint?

Just save code

### Which version of Stylelint are you using?

14.14.0

### What did you expect to happen?

I expect it would format the code automatically

### What actually happened?

It didn't format the code automatically

**Comment by ybiquitous** [comment]
@W-Ace Thanks for using the template. I have the following questions:

- Could you please provide a minimal reproduction repository or a [demo](https://stylelint.io/demo/)?
- What editor are you using? If VS Code, it may be a problem with our [VS Code extension](https://github.com/stylelint/vscode-stylelint).

**Comment by ybiquitous** [comment]
@W-Ace Thanks for providing the reproduction repository. Which files do you expect to format? `.vue` or `.scss`?

**Comment by W-Ace** [comment]
Thanks for your mail.

I expect both of them do.

Masafumi Koba ***@***.***>於 2022年11月2日 週三，12:12寫道：

**Comment by ybiquitous** [comment]
I've locally tried auto-fixing via the following command on the repository:

```shell
npx stylelint "**/*.{scss,vue}" --fix
```

Then, I've got the change:

```diff
diff --git a/src/App.vue b/src/App.vue
index 55cb0bb..b2f5533 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -8,6 +8,7 @@
   padding: 1.5em;
   will-change: filter;
 }
+
 .logo:hover {
   filter: drop-shadow(0 0 2em #646cffaa);
 }
diff --git a/src/style.scss b/src/style.scss
index 3678134..45a6959 100644
--- a/src/style.scss
+++ b/src/style.scss
@@ -1,21 +1,21 @@
 :root {
+  color: rgb(255 255 255 / 87%);
   font-weight: 400;
-  color-scheme: light dark;
-  color: rgba(255, 255, 255, 0.87);
-  line-height: 24px;
   font-size: 16px;
   font-family: Inter, Avenir, Helvetica, Arial, sans-serif;
+  line-height: 24px;
   background-color: #242424;
-  -webkit-text-size-adjust: 100%;
+  color-scheme: light dark;
+  text-size-adjust: 100%;
   -webkit-font-smoothing: antialiased;
-  text-rendering: optimizeLegibility;
+  text-rendering: optimizelegibility;
   -moz-osx-font-smoothing: grayscale;
   font-synthesis: none;
 }
 
 a {
-  font-weight: 500;
   color: #646cff;
+  font-weight: 500;
   text-decoration: inherit;
 }
 
diff --git a/src/views/index.vue b/src/views/index.vue
index d20c0a6..3927918 100644
--- a/src/views/index.vue
+++ b/src/views/index.vue
@@ -5,7 +5,7 @@
 </template>
 <style lang="postcss" scoped>
 .a {
-  height: 200px;
   width: 100px;
+  height: 200px;
 }
 </style>
```

Is this what you expected?

**Comment by W-Ace** [comment]
Thank you for such a quick reply！

I know it can be formatted via command,but I hope it can format instantly
via VSCODE extension and following settings

｛
     “eslint.validate: ［
        source.fixAll.stylelint: true
      ］
   ｝

Or is this supposed to be VSCODE extension problem?

But it work fine when I use stylelint below version 13.

I appricate your kind assistance.

Masafumi Koba ***@***.***>於 2022年11月2日 週三，12:47寫道：

**Comment by ybiquitous** [comment]
If VS Code only causes the issue instead of CLI, there may be a cause in the VS Code extension. It may not be related to this repository.

Also, according to the [vscode-stylelint doc](https://github.com/stylelint/vscode-stylelint#editorcodeactionsonsave), the following settings seem to be correct instead of your settings:

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.stylelint": true
  }
}
```

**Comment by W-Ace** [comment]
Oh. I made a typo, my setting is the same as yours.

OK, I get it, I’ll find out what the problem is,

Sorry and Thanks for your help.

Masafumi Koba ***@***.***>於 2022年11月2日 週三，13:44寫道：

**Comment by ybiquitous** [comment]
I'm closing this issue. Please feel free to reopen it if you find a problem.

**Comment by skylite21** [comment]
I am experiencing the same issue but it does not work even if I run stylelint from the cli. 
Example repo: https://github.com/skylite21/stylelint_demo
`npm run stylelint` but even ` npx stylelint "**/*.{css,scss}" --fix` does not do anything on the file, only outputs the correct errors.  For css files it works correctly.

**Comment by jeddy3** [comment]
@skylite21 It outputs an `CssSyntaxError` that can't be fixed automatically. You'll need to fix it manually.

```console
 2:12  ✖  Missed semicolon  CssSyntaxError
```

>  For css files it works correctly.

When linting CSS files, Stylelint automatically fixes these syntax errors using [postcss-safe-parser](https://www.npmjs.com/package/postcss-safe-parser). This isn't possible for non-standard syntaxes like SCSS, which need their own [custom syntaxes](https://stylelint.io/user-guide/usage/options#customsyntax), e.g. [postcss-scss](https://github.com/postcss/postcss-scss)
