### ISSUE TITLE
weird behavior with (comment-empty-line-before)

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#645]
```
11:5	Expected empty line before comment (comment-empty-line-before)
```

```
09 @media (width > 50em) {
10   .logo {
11     /*max-width: 40%;*/
12  }
13 }
```

Maybe this rule should have some exception or something? Because in this case it sounds weird to ask for a new line.

(Note: I get that rule from the stylelint-config-standard)

**Comment by davidtheclark** [comment]
You should be able to do it with `except: ["first-nested"]`. @jeddy3, want to add that to stylelint-config-standard?

**Comment by jeddy3** [comment]
> @jeddy3, want to add that to stylelint-config-standard?

Sounds like a plan. @davidtheclark Perhaps we should also add the [`ignore-stylelint-commands`](https://github.com/stylelint/stylelint/blob/master/src/rules/comment-empty-line-before/README.md#ignore-stylelint-commands) option if we're going for permissive?

**Comment by davidtheclark** [comment]
Yep I think so. Closing this as it's an issue with the standard, not stylelint.

**Comment by jeddy3** [comment]
FYI, released in `stylelint-config-standard`.
