### ISSUE TITLE
Add message arguments to `function-disallowed-list`

### ISSUE THREAD

**Issue by glen-84** [stylelint/stylelint#6455]
### What is the problem you're trying to solve?

Setting a custom message for the `function-disallowed-list` rule.

### What solution would you like to see?

```js
"function-disallowed-list": [
    ["rgb", "rgba"],
    {
        message: (functionNameOrRegex) => {
            switch (functionNameOrRegex) {
                case "rgb":
                case "rgba":
                    return "Use HSL colours";
            }
        }
    }
]
```

**Comment by ybiquitous** [comment]
@glen-84  Thanks for the proposal. See also <https://github.com/stylelint/stylelint/issues/6453#issuecomment-1304954997>.

I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
