### ISSUE TITLE
Create the 8-rules plugin (for the ones not yet handled by Prettier)

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#6483]
### What is the problem you're trying to solve?

Not having ppl stuck on 14.x.x if they depend on the dropped rules.

### What solution would you like to see?

Create a repository and the corresponding npm package for the plugin.

see
- https://github.com/stylelint/stylelint/issues/6311#issuecomment-1239342078
- https://github.com/stylelint/stylelint/issues/6311#issuecomment-1320081715

followup: find an official maintainer (optional)

**Comment by Mouvedia** [comment]
Also we need to review whether the options of the other stylistic rules are properly covered by Prettier.
If not we either open PRs on Prettier side or just add more rules to the plugin.

**Comment by ybiquitous** [comment]
Considering our maintainers' fewer resources, I believe it's better to avoid maintaining the plugin repository as possible — for example, archive the repo to prevent issue triage, etc.

**Comment by Mouvedia** [comment]
Here's how I would recommend to do it:

1. review options
2. create github repo under @stylelint (without issues)
3. release as β on npm
4. find a maintainer for the plugin
5. transfer the repo to the maintainer
6. release 1.0.0 on npm on the maintainer scope

1 to 3 are our responsibility; I am not sure whether 4 is ours.

**Comment by ybiquitous** [comment]
Sounds good. If a maintainer cannot be found, the plugin will remain β, right?

**Comment by Mouvedia** [comment]
> If a maintainer cannot be found, the plugin will remain β, right?

I guess? It's just my recommandation.
If you put a disclaimer in the README you will find a maintainer in no time.
The priority is parity for now.
