### ISSUE TITLE
[Feature request] Vanilla-extract build-time css-in-js integration?

### ISSUE THREAD

**Issue by rc-glean** [stylelint/stylelint#6489]
### What is the problem you're trying to solve?

x-posting this vanilla-extract feature request https://github.com/vanilla-extract-css/vanilla-extract/discussions/858

I'm unsure whether there's a canonical way to get stylelinting into css.ts css-generator files

### What solution would you like to see?

Ideally, the react object props fed to `style` (https://vanilla-extract.style/documentation/api/style/) can receive stylelints, but precommits against generated css files might suffice too

**Comment by ybiquitous** [comment]
@rc-glean Thanks for using the template.

You need to write a custom PostCSS syntax to support a specific CSS-in-JS syntax. This repository (Stylelint core) doesn't handle extended CSS-like syntaxes like SCSS or CSS-in-JS.

For details, please see <https://github.com/stylelint/postcss-css-in-js/issues/225>.

**Comment by jeddy3** [comment]
> You need to write a custom PostCSS syntax to support a specific CSS-in-JS syntax

@ybiquitous is correct. You'll find more info about custom syntaxes in our [developer guide](https://stylelint.io/developer-guide/syntaxes) and [user guide](https://stylelint.io/user-guide/usage/options#customsyntax).

As far as I'm aware, no one has written a dedicated PostCSS syntax for an _object-based_ CSS-in-JS library yet. Vanilla-extract is a great first candidate as it's:

- a popular and nextgen zero-runtime library
- compatible with many of our rules\* 

\* Especially those that [avoid errors](https://stylelint.io/user-guide/rules#avoid-errors) and [enforce non-stylistic conventions](https://stylelint.io/user-guide/rules#enforce-non-stylistic-conventions), e.g. disallow specific units [etc](https://stylelint.io/#how-itll-help-you).

In terms of implementation, you can look at the following for inspiration:

- JavaScript object to PostCSS AST in [postcss-js](https://github.com/postcss/postcss-js)
- `Document` node usage in [postcss-lit](https://github.com/43081j/postcss-lit) and [postcss-linaria](https://github.com/callstack/linaria/tree/master/packages/postcss-linaria)
- Object extraction in the `object-*` files of the deprecated [postcss-css-in-js](https://github.com/stylelint/postcss-css-in-js)

If you do create the syntax, please open a pull request here to add it to the list in our docs.

**Comment by osdiab** [comment]
@rc-glean did you ever find a way to instrument this in a way that worked well?

**Comment by osdiab** [comment]
@rc-glean did you ever find a way to instrument this in a way that worked well?
