### ISSUE TITLE
CLI should ignore node_modules by default

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#649]
I am trying to reproduce something I like from eslint:

```
$ eslint .
```

By default, eslint will add "**/*.js" if you provide a directory, and exclude `node_modules` (nobody wants to lint external modules).
That would be an easy and nice enhancement, don't you think? Well, 2.

**Comment by MoOx** [comment]
I am trying stuff like `stylelint '!(node_modules)/**/*.css'` but no "luck".

**Comment by davidtheclark** [comment]
Seems like a fine enhancement to me.

For now I think this should work, right? `stylelint '**/*.css' '!node_modules/**/*.css'??

**Comment by MoOx** [comment]
It's not :(

```
CssSyntaxError: .../node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown word
```

I am using `stylelint '**/web_modules/**/*.css'` but it's slow, since it's still looking in node_modules.

**Comment by davidtheclark** [comment]
Huh, maybe I don't quite understand the negation syntax the way I thought I
did. Anyway, I'll look into it sometime soon. @jeddy3 do you agree with
adopting the same defaults ESLint had that @MoOx mentioned?

**Comment by ntwb** [comment]
I use [Ag](https://github.com/ggreer/the_silver_searcher) rather than Grep or ACK, one of the cool things I like about is it ignores file patterns from your `.gitignore` file, so if stylelint was linting its own CSS files based on its [.gitignore](https://github.com/stylelint/stylelint/blob/master/.gitignore) it would ignore both `node_modules` and `dist` folders

**Comment by jeddy3** [comment]
> @jeddy3 do you agree with adopting the same defaults ESLint had that @MoOx mentioned?

Sgtm. Excluding `node_modules` has popped up before.

**Comment by MoOx** [comment]
Also, stuff like `stylelint '**/web_modules/**/*.css'` don't work the same on windows...
 
```
Error: Files glob patterns specified did not match any files`
```

**Comment by davidtheclark** [comment]
We're simply using [globby](https://github.com/sindresorhus/globby), so I'm surprised there's any issue with the globs. But will check it out.

**Comment by MoOx** [comment]
https://ci.appveyor.com/project/MoOx/statinamic/build/job/fpw4d3dafisam1o2

**Comment by davidtheclark** [comment]
@MoOx: I can confirm that when I pass `'**/web_modules/**/*.css'` to the CLI, `standalone.js` is passing `[ '**/web_modules/**/*.css' ]` directly to [globby](https://github.com/sindresorhus/globby) and relying on that module's output. If you could put together some details and file an issue there, that would be swell.

**Comment by MoOx** [comment]
Does globby transform windows path? I don't have much to add that the failure on appveyor I posted earlier :/

**Comment by davidtheclark** [comment]
@MoOx globby extends https://github.com/isaacs/node-glob, which is supposed to be consistent cross-platform.

**Comment by davidtheclark** [comment]
@MoOx is it possible you need to use double quotation marks on windows?

**Comment by MoOx** [comment]
Seems to be ok with double quotes. Thanks ! https://ci.appveyor.com/project/MoOx/statinamic/build/200/job/p2l5a18tp5ybwr4v#L634
