### ISSUE TITLE
Reorganize public type definitions

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#6508]
Because it is unclear whether a type definition is public or internal and so available from Stylelint plugin packages, there is a problem in that we cannot safely refactor type definitions. 

There are a few ways to limit the publicity of type definitions:

1. Add the `@internal` JSDoc annotation and a warning message like this:
    https://github.com/stylelint/stylelint/blob/11acf312191e5097692f7428f13977bd1fd12cd4/types/stylelint/index.d.ts#L539-L544
2. Add a `_` prefix to types or type members like this:
    https://github.com/stylelint/stylelint/blob/11acf312191e5097692f7428f13977bd1fd12cd4/types/stylelint/index.d.ts#L544-L550
3. Remove `export` from internal types as possible. This way is smarter, but it may need to remove `namespace`:
    https://github.com/stylelint/stylelint/blob/11acf312191e5097692f7428f13977bd1fd12cd4/types/stylelint/index.d.ts#L6

I believe we need to reorganize type definitions by combining such ways well.
I'm happy to hear any feedback.

Ref:
- https://github.com/stylelint/stylelint/pull/6415#issuecomment-1337682121
- https://github.com/stylelint/stylelint/pull/6503#discussion_r1039551312
- [The TypeScript Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

**Comment by jeddy3** [comment]
You're probably the most familiar with our types than anyone else 😄  Do you have a preference for how to combine the approaches? We can roll into v15 so that it can be a breaking change.

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/6510
