### ISSUE TITLE
`indentation` rule needs multiple passes and never stabilize

### ISSUE THREAD

**Issue by mvorisek** [stylelint/stylelint#6514]
### What steps are needed to reproduce the bug?

1. checkout https://github.com/fomantic/Fomantic-UI/tree/5e12443467d77a71628731900d8fb27bffcb6739
2. run `yarn install`
3. run `npx stylelint "**/*.{css,less}" --fix`

### What Stylelint configuration is needed to reproduce the bug?

only 1 rule `indentation: 4`

for complete config/packages, see https://github.com/fomantic/Fomantic-UI/commit/5e12443467d77a71628731900d8fb27bffcb6739 commit

### How did you run Stylelint?

`npx stylelint "**/*.{css,less}" --fix`

### Which version of Stylelint are you using?

latest / 14.16.0

### What did you expect to happen?

indentation files in all files to 4 spaces and when stylelint is run for 2nd time, no file changes

### What actually happened?

stylelint currently fixes one file line when in `each` block per `--fix` run (for example in `src/definitions/collections/form.less` file)

and in some files like `src/definitions/collections/message.less` it does add more spaces in each run even wrongly:

![image](https://user-images.githubusercontent.com/2228672/206748461-b030b808-e5d5-44cf-b3ae-75af501486c7.png)

### Does the bug relate to non-standard syntax?

yes, with LESS

**Comment by jeddy3** [comment]
@mvorisek Thanks for the report and for using the template.

> indentation rule needs multiple passes and never stabilize

This is [one of the reasons](https://github.com/stylelint/stylelint/pull/6504#discussion_r1039819747) we'll be [deprecating this rule](https://github.com/stylelint/stylelint/pull/6504) in the next major release.

I recommend following the [WIP migration guide](https://github.com/stylelint/stylelint/blob/v15/docs/migration-guide/to-15.md), i.e. adopt Prettier alongside Stylelint. Stylelint will [help you avoid errors and enforce (non-whitespace) conventions](https://github.com/stylelint/stylelint/blob/v15/README.md#how-itll-help-you) while Prettier will pretty-print the whitespace from the AST based on the length of each line.

Alternatively, if you want to continue using Stylelint for whitespace you can [port the rule to the plugin](https://stylelint.io/developer-guide/plugins) and fix the bug there.

**Comment by mvorisek** [comment]
One question - the `src/definitions/collections/message.less` problem I touched above turned out to be a bug corrupting the code.

see https://github.com/fomantic/Fomantic-UI/pull/2592/commits commits, /wo the 2nd commit when stylelint is run with `--fix`, the stylelint `indentation` rule was removing a colon

the fix on our side was to ignore the problematic line with `stylelint-disable-line` comment like https://github.com/fomantic/Fomantic-UI/pull/2592/commits/c59da089320af6198177746aff2bd62eac6f946b#diff-bfa7b5eb95ceab9fa6ad897327d60daffa9ec42c14dfef4e62022933809a9a7aR38

can this issue receive an official bugfix?

**Comment by jeddy3** [comment]
> can this issue receive an official bugfix?

We're frozen the deprecated rules so that we can focus on standard CSS and modernising our codebase.  The interplay between the `indentation` rule and the PostCSS Less custom syntax is non-trivial. You can [port the rule to the plugin](https://stylelint.io/developer-guide/plugins) and try fixing the bug there, though.
