### ISSUE TITLE
`no-extra-semicolons` is reporting wrong line

### ISSUE THREAD

**Issue by mvorisek** [stylelint/stylelint#6515]
### What steps are needed to reproduce the bug?

checkout https://github.com/fomantic/Fomantic-UI/blob/28f6f64f8956599b96f8bd0d9c16e50571cb37b7/src/themes/default/globals/colors.less#L616 and run stylelint

### What Stylelint configuration is needed to reproduce the bug?

`stylelint-config-standard` ruleset

complete config: https://github.com/fomantic/Fomantic-UI/blob/28f6f64f8956599b96f8bd0d9c16e50571cb37b7/.stylelintrc.js

### How did you run Stylelint?

`npx stylelint "**/*.{css,less}" --fix`

### Which version of Stylelint are you using?

latest / 14.16.0

### What did you expect to happen?

I would expect line 619 reported.

### What actually happened?

Line 616 is reported and the (intended) `stylelint-disable-line no-extra-semicolons` needs to be placed currently at an unrelated line.

### Does the bug relate to non-standard syntax?

LESS

**Comment by jeddy3** [comment]
@mvorisek Thanks for another report.

See https://github.com/stylelint/stylelint/issues/6514#issuecomment-1345202892
