### ISSUE TITLE
Autofix is broken, files with the same name (and different extension) are not checked/fixed at all

### ISSUE THREAD

**Issue by mvorisek** [stylelint/stylelint#6516]
### What steps are needed to reproduce the bug?

checkout https://github.com/mvorisek/Fomantic-UI/commit/5d4093916f2f60121d286e21461e0d1a70cdcc26

and notice `npx stylelint "**/*.{css,less,overrides,variables}" --fix` does not fix anything nor emit any error

`stylelint "**/*.{css,less,overrides,variables}"` (the same command /wo `--fix`) list the error correctly

I belive the problem is that some internal map is built /wo the extensions thus 2 files with the same name but different extension are added/processed for 1 file only.

### Which version of Stylelint are you using?

latest / 14.16.0

**Comment by mvorisek** [comment]
for repro please checkout the repo I posted and run stylelint with and without `--fix`

**Comment by ybiquitous** [comment]
I can confirm the `indentation` rule autofix doesn't work by following your instruction:

```console
$ npx stylelint src/themes/amazon/elements/button.variables

src/themes/amazon/elements/button.variables
 14:4  ✖  Expected indentation of 4 spaces  indentation

1 problem (1 error, 0 warnings)
```

However, I'm afraid we won't fix bugs for the stylistic rules handled by Prettier, including the `indentation` rule. Please see [our document](https://stylelint.io/user-guide/rules#enforce-stylistic-conventions) and the relevant issue #6342, and please consider using Prettier.

For example, Prettier can fix indentations via the following command:

```shell
npx prettier src/themes/amazon/elements/button.variables --write --parser=less --tab-width=4
```

**Comment by mvorisek** [comment]
very weird issue, how is it related with stylistict rules only?

**Comment by ybiquitous** [comment]
When running `npx stylelint "**/*.{css,less,overrides,variables}"` on the reproduction repository, we can get the following output:

```console
$ npx stylelint "**/*.{css,less,overrides,variables}"

src/themes/amazon/elements/button.variables
 14:4  ✖  Expected indentation of 4 spaces  indentation

src/themes/default/globals/colors.less
 484:32  ✖  Needless disable for "no-extra-semicolons"  --report-needless-disables
 616:17  ✖  Needless disable for "no-extra-semicolons"  --report-needless-disables

3 problems (3 errors, 0 warnings)

$ npx stylelint "**/*.{css,less,overrides,variables}" --fix

src/themes/default/globals/colors.less
 484:32  ✖  Needless disable for "no-extra-semicolons"  --report-needless-disables
 616:17  ✖  Needless disable for "no-extra-semicolons"  --report-needless-disables

2 problems (2 errors, 0 warnings)
```

The `indentation` rule is reported on the output above, and the rule is categorized as a stylistic rule handled by Pretty printers. See the [doc](https://stylelint.io/user-guide/rules/#general--sheet).

**Comment by mvorisek** [comment]
I replaced all files with 1 `number-leading-zero` issue per file and I can confirm this is not a stylelint global problem, but instead specific, possibly only frozen stylystic rules, rule problem.
