### ISSUE TITLE
Front-end Stylelint (BROWSER EDITITON)

### ISSUE THREAD

**Issue by ExtravagantBoost** [stylelint/stylelint#6522]
### What is the problem you're trying to solve?

I see that there is no availability for only browser ENV, only NodeJS
Recently i’ve got a version of Stylelint onto a single JS file,
one problem is that i could not get one of the rules to work while testing it, it is a permanent bug that spawned when transferring from Node:URL to Browser:URL
at rule `function-no-unknown` when set to true
### What solution would you like to see?

check out this Repo:
[ExtravagantBoost/Stylelintfront](https://github.com/ExtravagantBoost/Stylelintfront)
i have a demo for the repo above, i wish to see for you to find a way to implement it
[ExtravagantBoost/Stylelintfront - demo](https://ExtravagantBoost.github.io/Stylelintfront)

**Comment by ybiquitous** [comment]
@ExtravagantBoost Thanks for using the template. This issue seems duplicate to #3935. 

Yes, there are still problems with running Stylelint on a browser. Please check out #3935 for details.
