### ISSUE TITLE
Unexpected Node API output when any rule contains `disableFix: true`

### ISSUE THREAD

**Issue by adrianjost** [stylelint/stylelint#6542]
### What steps are needed to reproduce the bug?

`disableFix: true` in any stylelint rule breaks the `output` of the node api if the `fix: true` option is set. 
If this configuration is provided for any rule, instead of containing the fixed code, the regular output that would have been shown without the `fix: true` flag is returned.
A symptom of this issue is that the VSCode eidtor integration can not autofix any issues.

Example Script
```ts
import * as stylelint from "stylelint";

async function lint(cssContent: string): Promise<void> {
  try {
    const lintResult = await stylelint.lint({
      code: cssContent,
      fix: true,
    });
    console.log(lintResult.output);
  } catch (error) {
    console.error(error);
  }
}
lint(`.border-top-default {
  border-top: 1px solid red;
  margin: 0;
}`);
```
And configuration:
Example stylelint config:
used packages: stylelint-order, stylelint-scss, stylelint-declaration-strict-value.
```js
module.exports = {
  customSyntax: "postcss-scss",
  plugins: ["stylelint-declaration-strict-value", "stylelint-order"],
  rules: {
    "order/properties-order": [["margin", "border"], { unspecified: "bottom" }],
    "scale-unlimited/declaration-strict-value": [
      "/border/",
      { disableFix: true }, // this one breaks the autofix
    ],
  },
};
```

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  plugins: ["stylelint-declaration-strict-value", "stylelint-order"],
  rules: {
    "order/properties-order": [["margin", "border"], { unspecified: "bottom" }],
    "scale-unlimited/declaration-strict-value": [
      "/border/",
      { disableFix: true }, // this one breaks the autofix
    ],
  },
};
```

### How did you run Stylelint?

NodeJS script, provided in steps to reproduce bug

### Which version of Stylelint are you using?

14.15.0

### What did you expect to happen?

I expect the `intResult.output` to contain the fixed CSS
```css
.border-top-default {
  margin: 0;
  border-top: : 1px solid red;
}
```

### What actually happened?

But as soon as `disableFix: true` is set, I get the following result:
```json
[{
  "source": "<input css rPadxH>",
  "deprecations": [],
  "invalidOptionWarnings": [],
  "parseErrors": [],
  "errored": false,
  "warnings": []
}]
```
which is similar to the result that I get when I remvoe the `fix: true` option from the node script.
```json
[{
  "source": "<input css qETqql>",
  "deprecations": [],
  "invalidOptionWarnings": [],
  "parseErrors": [],
  "errored": true,
  "warnings": [
    {
      "line": 3,
      "column": 5,
      "endLine": 3,
      "endColumn": 15,
      "rule": "order/properties-order",
      "severity": "error",
      "text": "Expected \"margin\" to come before \"border-top\" (order/properties-order)"
    }
  ]
}]
```

### Does the bug relate to non-standard syntax?

I don't think so

### Proposal to fix the bug

Not yet, will try to look into it.

**Comment by adrianjost** [comment]
Related Issue in the VSCode editor plugin: https://github.com/stylelint/vscode-stylelint/issues/369

**Comment by adrianjost** [comment]
I suspect it is because of https://github.com/stylelint/stylelint/blob/main/lib/standalone.js#L146

**Comment by ybiquitous** [comment]
@adrianjost Thanks for firing the detailed report and creating the pull request. I can reproduce the bug. 👍🏼
