### ISSUE TITLE
Refactor `declaration-block-no-duplicate-properties`

### ISSUE THREAD

**Issue by fpetrakov** [stylelint/stylelint#6544]
Hi there. While reading the code I noticed that the declaration-block-no-duplicate-properties rule has a quite deep nesting. I think the rule could be refactored a bit so the code become more readable. What do you think? If you agree, I can take care of it.

**Comment by jeddy3** [comment]
@fpetrakov Thank you. We welcome any contribution to make the code more readable. Refactoring to reduce the nesting depth would be great.
