### ISSUE TITLE
`--quiet` does not work when `-o` is specified

### ISSUE THREAD

**Issue by kuoruan** [stylelint/stylelint#6557]
### What steps are needed to reproduce the bug?

Use `-q` option with `-o`.

### What Stylelint configuration is needed to reproduce the bug?

Any config is OK.

### How did you run Stylelint?

`stylelint -f json -o stylelint-report.json --quiet '**/*.{css,scss,sass}'`

### Which version of Stylelint are you using?

`14.16.1`

### What did you expect to happen?

Do not output to stdout when `-q` and `-o` specified.

### What actually happened?

The content output to the console.

### Does the bug relate to non-standard syntax?

No

**Comment by ybiquitous** [comment]
@kuoruan Thanks for using the template. The [`quiet`](https://stylelint.io/user-guide/usage/options/#quiet) option does not control output to stdout/stderr, but control problems report about severities.

> Only register problems for rules with an "error"-level severity (ignore "warning"-level).

You can use another way like `> /dev/null` redirecting to suppress output to stdout.

**Comment by kuoruan** [comment]
@ybiquitous OK, thank you for the reply.
