### ISSUE TITLE
Warning when propriety unknown

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [stylelint/stylelint#6576]
### What is the problem you're trying to solve?

How can i have a linting when it's unknown propriety. I tried all plugins no one give me a warning i those cases

` display: inl-flex;`
`justify-content: cent`

### What solution would you like to see?

` display: inline-flex;`

**Comment by jeddy3** [comment]
A rule to do this may land in `stylelint@15.0.0` - See https://github.com/stylelint/stylelint/pull/6511

In the meantime, you can use the [`stylelint-csstree-validator`](https://www.npmjs.com/package/stylelint-csstree-validator) plugin.
