### ISSUE TITLE
Allow per-declaration(?) override of rules, or at least the indentation rule

### ISSUE THREAD

**Issue by mirabilos** [stylelint/stylelint#6581]
### What is the problem you're trying to solve?

My “house style” uses tabs for indentation but indents top/bottom/left/right after position one extra tab:

```
#loadingelt {
	z-index:16383;
	position:fixed;
		top:0px;
		left:0px;
	width:100%;
	height:100%;   
	background:rgba(0, 0, 0, 0.666);
}
```

The `indentation` rule currently has no way of managing this.

To add to the problem, I’m only invoking stylelint from the GitHub Action codacy, which does not allow for plugins, so this must be in core.

### What solution would you like to see?

Ideally, an option to do just that, to require top/bottom/left/right to appear only/directly after position and to indent it extra.

More realistically, something like “indent with one tab, except if the thing is top/bottom/left/right, then indent it with two tabs”, which looks very doable to me having looked at `indentation/index.js` for quite a bit, using the second configuration parameter object for such a thing.

It might make sense to do this globally, so people can apply different rule configurations depending on the… declaration? thing. Another candidate for this would be:

```
  "rules": {
    "alpha-value-notation": [
      "number",
      {
        "different-per-declaration": [
          [["opacity"], "percent"]
        ]
      }
    ]
  }
```

The idea here, which could be applied to others, is:

`different-per-declaration` is an Array of two- or three-value Arrays, whose first respective element is an Array of declarations it applies to (here only one), the second and optional third correspond to the two configuration settings for the rule.

With this syntax, I could have:

```
  "rules": {
    "indentation": [
      "tab",
      {
        "different-per-declaration": [
          [["top", "bottom", "left", "right"], "tab", {
            "baseIndentLevel": 1
          }]
        ]
      }
    ]
  }
```

Or something.

**Comment by jeddy3** [comment]
@mirabilos Thanks for the thoroughly-written issue.

We've [frozen the stylistic rules](https://stylelint.io/user-guide/rules#enforce-stylistic-conventions), including `indentation` and we'll be [deprecating them in the next major release](https://github.com/stylelint/stylelint/blob/2e49275d0147a702607feba0b1a96993f607551b/docs/migration-guide/to-15.md).

We now recommend using a pretty-printer (like Prettier) alongside Stylelint. Linters and pretty printers are complementary tools that work together to help you write consistent and error-free code.

Use Stylelint to:

- [avoid errors](https://stylelint.io/user-guide/rules#avoid-errors)
- [enforce (non-stylistic conventions)](https://stylelint.io/user-guide/rules#enforce-non-stylistic-conventions)

Use a pretty printer to format stylistic things like whitespace to an optimal line length.

> I’m only invoking stylelint from the GitHub Action codacy, which does not allow for plugins, so this must be in core.

Only generally applicable rules are built-in. Plugins are a better fit for bespoke conventions, and hopefully codacy soon resolves the limitation on using them. You could try writing a Prettier plugin for your whitespace conventions.

> It might make sense to do this globally, so people can apply different rule configurations depending on the… declaration? thing.

Thank you for this suggestion. We have the [`except(*)` secondary option](https://stylelint.io/developer-guide/rules#keyword-ignore-and-except) that we add on a rule-by-rule basis. It inverts the primary option for a given pattern. 

For example, we have [`exceptProperties: []`](https://stylelint.io/user-guide/rules/alpha-value-notation/#exceptproperties-regex-regex-string) for the `alpha-value-notation` rule:

```json
{ 
 "rules": {
    "alpha-value-notation": ["number", { "exceptProperties": ["opacity"] }]
  }
}
```

**Comment by mirabilos** [comment]
Richard Hallows dixit:

>We now recommend using a pretty-printer (like Prettier) alongside

I see. I don’t want anything to format the code automatically though,
just check it.

>For example, we have [`exceptProperties: []`](https://stylelint.io/user-guide/rules/alpha-value-notation/#exceptproperties-regex-regex-string) for the `alpha-value-notation` rule:

Ooooh, that’s good. No solution for indentation though, but I guess
I could just disable that if anything else checks it.

Thanks for the response,
//mirabilos
-- 
Infrastrukturexperte • tarent solutions GmbH
Am Dickobskreuz 10, D-53121 Bonn • http://www.tarent.de/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 5168 • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
