### ISSUE TITLE
Document how `--cache` handles plugin and Stylelint versions

### ISSUE THREAD

**Issue by thernstig** [stylelint/stylelint#6590]
### Describe the documentation issue

https://stylelint.io/user-guide/usage/options/#cache has no explanation of if plugin versions and implementations are used, nor has it information about if the Stylelint version, config etc. is used.

### What solution would you like to see?

Prettier adds more verbose information on what is cached, see https://prettier.io/docs/en/cli.html#--cache

The ideal solution would however be for the caching to be able to handle the Prettier version, Prettier config as well as plugin versions and implementations. The rationale for this is that unless it is done, caching in CI is going to be impossible to use since the cache will not be correct, potentially missing new faults introduced in CI.

**Comment by jeddy3** [comment]
@thernstig Thanks for the report and for using the template.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by thernstig** [comment]
Bump
