### ISSUE TITLE
New rule: number-no-trailing-zeros

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#66]
To replace `number-trailing-zero`, as discussed in #64.

**Comment by jeddy3** [comment]
I just noticed that scsslint [has two rules](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#trailingzero) for this, with slightly different purposes:

Trailing Zeros is for when there is a faction with extra zeros at the end e.g. `5.55500000px` and Unnecessary Mantissa is for when an integer has a unnecessary faction after it e.g. `5.0px`.

Is there value in us being this specific? I guess they are kind of different things. Thoughts? Should we go with?:

* [ ] `number-no-trailing-zeros`: Disallow trailing zeros (e.g. `5.55000px`)
* [ ] `number-no-unnecessary-mantissa`: Disallow unnecessary mantissa (e.g. `5.0px`)

**Comment by MoOx** [comment]
I found this overkill. 5.55000px is just useless like 5.0px. Looks the same to me.

**Comment by davidtheclark** [comment]
Yeah, I sort of think that distinction only happened because somebody with a math background new what "mantissa" is? I don't about the use-case. Did you search the issues to see if there was some justification for it?

**Comment by jeddy3** [comment]
> Did you search the issues to see if there was some justification for it?

Yeap, but I couldn't find anything. 

Sounds like we're agreed it's overkill anyway.

Shall we call our one rule `number-no-trailing-zeros` (note the s at the end) as then it makes it a little clearer that it'll flag up 1 *or more* trailing zeros i.e. both `5.55000px` and `5.0px`?

**Comment by MoOx** [comment]
why not

**Comment by davidtheclark** [comment]
sure
