### ISSUE TITLE
Make the behaviour and names of rule-*, block-* and declaration-block-* rules consistent

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#664]
- [x] `rule-trailing-semicolon` → `declaration-block-trailing-semicolon`
- [x] `declaration-block-no-single-line` → `block-no-single-line`
- [x] `rule-no-duplicate-properties` → `declaration-block-no-duplicate-properties`
- [x] `rule-no-shorthand-property-overrides` → `declaration-block-no-shorthand-property-overrides`
- [x] `rule-properties-order` → `declaration-block-properties-order`

Ref: https://github.com/stylelint/stylelint/issues/648#issuecomment-174229082

I think there is some inconsistency in the grouping of the `rule-*`, `block-*` and `declaration-block-*` rules that could, perhaps, be address in `5.0.0`.

Firstly...

* `rule-trailing-semicolon` → `declaration-block-trailing-semicolon`

Historically we created the `rule-trailing-semicolon` rule first and it was named based on the PostCSS node tree, which doesn't go into the specifics of declaration blocks. We have since gone on to create the `declaration-block-semicolon-newline/space-before/after` rules, which are consistent with the _scoping_ naming conventions and [aligned with the specs](https://www.w3.org/TR/CSS2/syndata.html#rule-sets). Perhaps we should rename the `rule-trailing-semicolon` rule so that all the semicolon rules match?

Secondly... 

* `declaration-block-no-single-line` → `block-no-single-line`

The distinction between _blocks_ and _declaration blocks_ seems solid. _block_ being the more generic _[thing](http://apps.workflower.fi/vocabs/css/en)_ that incorporates both _declaration blocks_ and those belonging to at-rules. Hence the generic `block-closing/opening-*` rules look good to me. We also have the `block-no-empty` rule which, again, makes sense to be generic. However, we have the specific `declaration-block-no-single-line` rule which is only applied to _declaration blocks_. Perhaps we should change its behaviour to align it with the `block-no-empty` rule and make it generic to all blocks. As an aside: I think the `declaration-block-single-line-max-declarations` rule should remain as is, as _the number of declarations_ is specific to declaration blocks.

Lastly (and these might seem like a bit of a stretch, but hopefully I'll give some sound reasons)...

* `rule-no-duplicate-properties` → `declaration-block-no-duplicate-properties`
* `rule-no-shorthand-property-overrides` → `declaration-block-no-shorthand-property-overrides`
* `rule-properties-order` → `declaration-block-properties-order`

1. Each of these rules, like `declaration-block-single-line-max-declarations`, are specific to _declaration blocks_. 
2. If the [intent](https://github.com/stylelint/stylelint/issues/653) is to support non-standard nested at-rules, then I think renaming these rules better reflects that behaviour i.e. regardless of whether a _declaration block_ belongs to rule or a non-standard nested at-rule it will be checked in isolation.
3. By reducing the `rule-*` rules down to just empty line rules, it'll bring consistency between the [`at-rule-*`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#at-rule) and remaining `rule-*` rules.

@davidtheclark What do you think? I remember you saying the naming of the `declaration-block-semicolon-*` rules irked you a little. Is that because we thought semicolons didn't belong to _declaration blocks_ or because of the inconsistency in the naming of the `trailing-semicolon` rule? If it was the latter, then hopefully these changes are the final hurdle towards totally consistent rule names. I know such a thing would please me :)

**Comment by davidtheclark** [comment]
> Perhaps we should rename the rule-trailing-semicolon rule so that all the semicolon rules match?

Sure.

> Perhaps we should change its behaviour to align it with the block-no-empty rule and make it generic to all blocks.

Agreed.

> Lastly (and these might seem like a bit of a stretch, but hopefully I'll give some sound reasons)

All of those rule => declaration-block changes are fine by me.

> I remember you saying the naming of the declaration-block-semicolon-* rules irked you a little.

I think it's fine.

All these name changes are fine by me. I'd really like to limit them in the future, though, because they really are relatively unimportant and force users to make a change. So before releasing 5.0, whenever that is going to happen, let's make sure to really wrack our brains to make sure we're happy with the naming that exists and have no plans to perform any more name-changes down the line.

**Comment by jeddy3** [comment]
> All these name changes are fine by me.

Good stuff :)

> I'd really like to limit them in the future

Defo! 

> let's make sure to really wrack our brains to make sure we're happy

Yep. I'll really wrack it. I'm pretty pleased with the consistency we've achieved across the vast majority of the rules. I think we've been good at deliberating over the naming of new rule names. Consistency has been a priority for me, as it seems to make the new user experience that little bit nicer. But, like you said, this will be our last chance (if only because as the user base grows name changes negatively impact more existing users) and so I'll double down on the wracking :)

**Comment by davidtheclark** [comment]
And I just looked it up --- and see that "rack" is the more widely accepted usage, rather than "wrack", but both are common. Language nerdery.

**Comment by jeddy3** [comment]
Ha, when articles about wrack and rack start with "The relationship between the forms rack and wrack is complicated"... you know you're in for a good read :)

**Comment by jeddy3** [comment]
I'm going to hold off on renaming `rule-properties-order` (and checking the rule-set and `@rule` is behaviour is consistent) until @dan-gamble is done with https://github.com/stylelint/stylelint/issues/752 and https://github.com/stylelint/stylelint/issues/578
