### ISSUE TITLE
Document migrating deprecated rules to a plugin in the migration guide

### ISSUE THREAD

**Issue by bitstarr** [stylelint/stylelint#6668]
### Describe the documentation issue

In https://stylelint.io/migration-guide/to-15 you tell people that you will no longer handle stylistic rules but do not provide an appropriate replacement. You only recommend Prettier which is problematic since it's heavily opinionated to a grade that's very patronising and insufficiently configurable.

Rules like `indentation`, `number-no-trailing-zeros`, `number-leading-zero`, or `declaration-colon-space-after` are things I care about (and maybe others that didn't realized already this is coming).

### What solution would you like to see?

As a front-of-the-frontend developer (not regularry using node, or some js frameworks) I want to make sure my CSS is working and written in a consisten style. If you decide to drop these rules, please provide clear and helpful information how to move to another tool and recommend useful alternatives.

**Comment by bitstarr** [comment]
Please reopen this issue until there is a real solution. Waiting for a messiah to write a plugin in a far future is not an appropriate solution.

**Comment by privatenumber** [comment]
I agree this should be re-opened. The migration guide is not helpful if a clear alternative is not offered.

If prettier is the recommended alternative, that should be made clearer. And perhaps there should be a link or section on how to achieve similar results.

If stylelint is seeking a maintainer for stylistic rules via separate plugin, there should be an Issue for "help wanted".
