### ISSUE TITLE
Add `--quiet-deprecation-warnings` flag

### ISSUE THREAD

**Issue by peteduel** [stylelint/stylelint#6677]
### What is the problem you're trying to solve?

A page of deprecation warnings on v15.x

### What solution would you like to see?

The quiet flag (or some other means) to opt-out of the warnings

**Comment by Mouvedia** [comment]
related discussion: https://github.com/stylelint/stylelint/pull/6561#discussion_r1070291263

**Comment by ybiquitous** [comment]
@peteduel @Mouvedia Thanks for the report and for sharing the related discussion.

The current [`quiet`](https://stylelint.io/user-guide/options#quiet) option handles only *linting* problems with a severity (`error` or `warning`). On the other hand, deprecation warnings are *not* linting problems, so expanding the current option semantics may break something.

If we want to avoid such a breaking possibility, we may need to add a new option to suppress deprecation warnings.

What do you think? @jeddy3

**Comment by jeddy3** [comment]
> If we want to avoid such a breaking possibility, we may need to add a new option to suppress deprecation warnings.

We could accept a PR for a `--quiet-deprecation-warnings` flag. It's explicit and clear.

**Comment by Mouvedia** [comment]
IMHO `SKIP_WARNINGS` environment variable should hide them as well.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the answer. Yes, adding a new flag may be safe. 👍🏼 

@Mouvedia Where does that environment variable come from? I believe we have not used any environment variables in Stylelint... 🤔

**Comment by Mouvedia** [comment]
@ybiquitous you are right.
I misread https://github.com/stylelint/stylelint/blob/c1223a430a4ea9afeb89218449ecf0393436fdfe/docs/developer-guide/formatters.md?plain=1#L71

**Comment by jeddy3** [comment]
I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
