### ISSUE TITLE
Option to always require !important

### ISSUE THREAD

**Issue by silverwind** [stylelint/stylelint#669]
In a userstyle, it is best practice to append `!important` to all values.

Maybe [`declaration-no-important`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-no-important/README.md) could be renamed to `declaration-important` (so the rule name is unbiased) and gain `always|never` options?

**Comment by jeddy3** [comment]
> In a userstyle, it is best practice to append !important to all values.

Oh wow, this use case never even occurred to us. It's a totally valid one though.

> Maybe declaration-no-important could be renamed to declaration-important

Yep, that seems like correct thing to do.

@davidtheclark Do you agree, and shall we at it to the `5.0.0` milestone?

**Comment by TrySound** [comment]
@silverwind I'm sure using important is always bad practice. But you can use some processors after linter like https://github.com/crimx/postcss-safe-important

**Comment by silverwind** [comment]
> I'm sure using important is always bad practice

I agree totally for regular site CSS, but a userstyle has to make sure to override a page's rules consistently, see [this section](https://github.com/JasonBarnabe/stylish/wiki/Overwriting-page-styles#recommendations) of the userstyle guide.

**Comment by TrySound** [comment]
@silverwind I mean using that plugin you can prevent repeating !important again and again. And add comment where you don't want to add it. I wouldn't like to change no-important option for such specific case whih can be handled more powerful than just linting.

**Comment by silverwind** [comment]
@TrySound Yeah, I think that solution should work for my case and I prefer auto-fixing over warnings anyways. This issue is merely about a possible use-case you might have missed, but if it's to much pain to change a rule name, leave it as is, as it would only help a very small subsection of users :wink:

**Comment by jeddy3** [comment]
@TrySound Thanks, I didn't know about `postcss-safe-important`.

Over in https://github.com/stylelint/stylelint/issues/664 we've decided to going ahead with a behaviour and name change to `declaration-block-no-single-line` for `5.0.0` (and bundle a few other name changes along with it). So, I think it's worth thrashing this issue out as `5.0.0` is the best, and likely the last, opportunity we'll get to change the behaviour and name of `declaration-no-important`.

I think there is a valid use case here i.e. a userstyle author might not want to use a processor to build their stylesheet e.g. they might just want to use `stylelint` on the command line to check their hand-authored CSS meets their specific criteria.

So, despite `declaration-no-important` with `postcss-safe-important` providing nice solution, it might still be worth considering this change.

It'll be slightly more involved than just name change though, as there's a few [gotchas](https://github.com/crimx/postcss-safe-important#safe) to supporting `"declaration-important": "always"` i.e. adding the code and tests to ignore `@font-face` and `@keyframes` declarations by default.

What do you think @silverwind, is this something you could find time for?

If so, I'll be inclined to accept this change into `5.0.0`.

What do you guys think? A good idea considering the larger context, or shall we close the issue?

**Comment by davidtheclark** [comment]
Fine by me.

**Comment by davidtheclark** [comment]
@silverwind: So is your intention to run two separate stylelint process, one with this rule on for the user stylesheets and one with it off for your other stylesheet? I'm just having a hard time envisioning this rule being used unless people setup dual processes like that, which is kind of awkward ... 

The more I think about it the less enthusiastic I am, just because of the apparent absurdity of setting `declaration-important: "always"`. I wonder if the one use-case for it might be better served just by `stylelint-disable declaration-no-important` ...

**Comment by silverwind** [comment]
My use case is [this userstyle](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css). We often forget to add `!important`. It is usually is not an issue as If I understand it correctly, a user/agent style of the same specificity wins over an author style, but we have been bitten by missing `!important` in the past.

**Comment by davidtheclark** [comment]
Huh. Well, ok :)

**Comment by davidtheclark** [comment]
@jeddy3 : What would you say to creating `declaration-important` with `always|never` options as soon as someone gets around to it, and adding a deprecation notice on `declaration-no-important`; then removing `declaration-no-important` in v5?

**Comment by jeddy3** [comment]
I think that's the way to go. We should probably do the same for the changes in https://github.com/stylelint/stylelint/issues/664

**Comment by jeddy3** [comment]
Revisiting this... I think @TrySound's [point](https://github.com/stylelint/stylelint/issues/669#issuecomment-177134494) is strong.

It also feels wasteful to duplicate (and maintain) [`postcss-safe-important`](https://github.com/crimx/postcss-safe-important) [safe](https://github.com/crimx/postcss-safe-important#safe) logic here.

I think we should not create `declaration-important` and instead add a note to the `declaration-no-important` README. One that points users to [`postcss-safe-important`](https://github.com/crimx/postcss-safe-important) if they wish to add `!important` to every declaration in a sheet.

@davidtheclark What do you think?

**Comment by davidtheclark** [comment]
Closing.
