### ISSUE TITLE
Add `-c` alias for `--config` 

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#6690]
requested by @ybiquitous in https://github.com/stylelint/stylelint/pull/6617#discussion_r1121431016

see https://github.com/stylelint/stylelint/blob/4835d16d08fd91ff9e0ab47c1f7adbcf73fb0342/lib/cli.js#L261

**Comment by jeddy3** [comment]
SGTM.

**Comment by sidverma32** [comment]
@ybiquitous  can u raise PR for this?

**Comment by ybiquitous** [comment]
@sidverma32 Yes, of course!

**Comment by sidverma32** [comment]
<img width="624" alt="Screenshot 2023-03-20 at 1 20 50 PM" src="https://user-images.githubusercontent.com/10995431/226278019-d2277442-8c3e-409e-b7f1-f7a43a2fd9c4.png">

@ybiquitous  why getting this error while running `npm run lint` command in `main` branch?

**Comment by ybiquitous** [comment]
@sidverma32 I'm not sure but your local Node.js version seems old... 🤔 

https://github.com/stylelint/stylelint/blob/eabe85d443e104394865cce9a24095be5fb59620/package.json#L203-L205
