### ISSUE TITLE
Return stylistic rules

### ISSUE THREAD

**Issue by taras-turchenko-moc** [stylelint/stylelint#6693]
### What is the problem you're trying to solve?

In the latest major release stylelint removed all stylistic rules in favor of prettier usage but the fact is not all projects use prettier because it brings complexity with other linters such as eslint or stylelint

It's hard to configure prettier and other linters in big projects without any conflicts and strange formatting behavior

### What solution would you like to see?

If you don't want to keep it in the stylelint library we can move it to a new library

**Comment by jeddy3** [comment]
> we can move it to a new library

@taras-turchenko-moc That would be fantastic, thank you! There are are instructions in the [migration guide](https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules) on how to migrate the stylistic rules to a plugin. Once you've published the new plugin pack, we can update the migration guide to include a link so others can find it. People can then choose to use Prettier or the stylistic plugin pack for Stylelint.

**Comment by Arkellys** [comment]
Duplicate/related to #6657
