### ISSUE TITLE
Error when formatting styled-components with stylelint

### ISSUE THREAD

**Issue by CGSimplePeople** [stylelint/stylelint#6700]
### What steps are needed to reproduce the bug?

Use stylelint to format styled-components
At that time, the style was written in the tsx file. Just after writing const, an error message of stylelint will appear immediately.

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": ["stylelint-config-rational-order", "stylelint-config-standard"],
  "plugins": ["stylelint-order"],
  "customSyntax": "postcss-styled-components"
}

### How did you run Stylelint?

vscode-stylelint

### Which version of Stylelint are you using?

15.2.0

### What did you expect to happen?

I hope that when I write styles in my tsx file, there will be no error message when I just finished writing const

### What actually happened?

SyntaxError: Unexpected keyword 'function'. (10:0) at instantiate (E:\GProjects\UI\node_modules.pnpm@babel+parser@7.21.2\node_modules@babel\parser\lib\index.js:64:32) at constructor

[Error - 13:09:56] [language-server] Error running lint | uri: "file:///e%3A/GProjects/UI/src/App.tsx" error: {"code":"BABEL_PARSER_SYNTAX_ERROR","reasonCode":"UnexpectedKeyword","loc":{"line":10,"column":0,"index":157},"pos":157,"name":"SyntaxError","message":"Unexpected keyword 'function'. (10:0)","stack":"SyntaxError: Unexpected keyword 'function'. (10:0)\n at instantiate (E:\GProjects\UI\node_modules\.pnpm\https://github.com/babel+parser@7.21.2\node_modules\https://github.com/babel\parser\lib\index.js:64:32)\n at constructor

### Does the bug relate to non-standard syntax?

styled-components

**Comment by jeddy3** [comment]
@CGSimplePeople Thanks for the report. However, please raise this [in the custom syntax issue tracker](https://github.com/hudochenkov/postcss-styled-syntax) rather than in the Stylelint one.

**Comment by CGSimplePeople** [comment]
> @CGSimplePeople感谢您的报告。[但是，请在自定义语法问题跟踪器中](https://github.com/hudochenkov/postcss-styled-syntax)而不是在 Stylelint 中提出这个问题。

Thank you for your reply, can you simply recommend the configuration of styled-components? I tried many ways but still can't solve my problem
