### ISSUE TITLE
stylelint:fix failed without output (ENOENT)

### ISSUE THREAD

**Issue by TemurbekRuziyev** [stylelint/stylelint#6709]
### What steps are needed to reproduce the bug?

I am trying to use styelint with lint-staged in project.
But when I run **npx lint-staged**, styelint is giving such an error
<img width="611" alt="Screenshot 2023-03-13 at 12 07 16" src="https://user-images.githubusercontent.com/68279922/224631011-e8ecf345-49d4-4572-8d67-fa400a5b9684.png">

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-config-recommended",
    "stylelint-config-prettier",
    "stylelint-config-prettier-scss"
  ]
}

### How did you run Stylelint?

"stylelint:fix": "stylelint \"src/**/*.+(css|scss|sass)\" --fix --ignore-path .gitignore"

### Which version of Stylelint are you using?

15.2.0

### What did you expect to happen?

To run without breaking

### What actually happened?

It's Stylelint's turn to be broken

**Comment by ybiquitous** [comment]
@TemurbekRuziyev Thanks for using the template. Unfortunately, we cannot reproduce the problem with the provided information. Could you give us a minimal repository so that we can identify the problem?

**Comment by jeddy3** [comment]
@TemurbekRuziyev You're welcome to reopen the issue with a minimal reproducible repository.
