### ISSUE TITLE
CssSyntaxError Unknown word

### ISSUE THREAD

**Issue by MiloszKuznia** [stylelint/stylelint#6714]
### What steps are needed to reproduce the bug?

Hi, i have Unknown word CssSyntaxError in my scss files in place were i have // comment. I added stylelint-scss plugins and postcss syntax scss and still have this error ... need help :D

### What Stylelint configuration is needed to reproduce the bug?

//.stylelintrc.json file 
{
  "plugins": ["stylelint-scss", "stylelint-prettier"],
  "extends": ["stylelint-config-outside-in-order"],
  "rules": {
      "prettier/prettier": true,
      "order/order": [
        "custom-properties",
        "declarations"
      ],
      "order/properties-order": [
        "width",
        "height"
      ]
  }
}

### How did you run Stylelint?

 npx stylelint "**/*.scss"

### Which version of Stylelint are you using?

15.2.0

### What did you expect to happen?

I want to //coments be allowed to use in my files

### What actually happened?

 2:4  ✖  Unknown word  CssSyntaxError

### Does the bug relate to non-standard syntax?

Yes

**Comment by victorcngo** [comment]
hi! did you find a solution for this?
