### ISSUE TITLE
Handling CSS Variables from Frameworks with Non-Compliant Naming Conventions in Stylelint

### ISSUE THREAD

**Issue by Falven** [stylelint/stylelint#6732]
I am working on a large monorepo project that enforces kebab-casing.
MUI now offers [CSS theme variables](https://mui.com/material-ui/experimental-api/css-theme-variables/overview/)
On generation they look like:
```css
--mui-transitions-easing-easeInOut: cubic-bezier(0.4, 0, 0.2, 1);
--mui-zIndex-speedDial: 1050;
```
And do not follow `kebab-casing`.  It's too tedious to add `/* stylelint-disable */` for every line in which you are using these CSS variables (most lines do).
I thought about writing a rule: `ignore-mui-properties`, but the [Stylelint rules documentation](https://stylelint.io/developer-guide/rules#define-the-rule) essentially state that this is a one-off pattern and writing a rule is not really appropriate in this case.
So how does Stylelint officially recommend handling the case where you're using frameworks that do not adhere to your general project rules?

**Comment by Falven** [comment]
Here's what I ended up doing, hope this helps someone in the future:
in my .stylelintrc.js
```js
'use strict';

module.exports = {
  extends: ['stylelint-config-standard-scss', 'stylelint-config-css-modules'],
  rules: {
    'custom-property-pattern': [
      '^mui-.*$|^([a-z][a-z0-9]*)(-[a-z0-9]+)*$',
      {
        message: (name) => `Expected custom property name "${name}" to be kebab-case`,
      },
    ],
  },
};
```
Overwrote the custom-property-pattern rule with my own that defines a regex that will match css variables begining with `mui-` or kebab-case. This seems to work for now.

**Comment by ybiquitous** [comment]
@Falven It's a nice way to configure `custom-property-pattern` with your specific regex pattern. 👍🏼 

A regex becomes more complex, but it's unavoidable. Tools like [regex101](https://regex101.com/) may help debug a regex.

**Comment by ybiquitous** [comment]
@Falven Have you resolved your problem? Can we close this issue?
