### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix with basic keywords

### ISSUE THREAD

**Issue by LeonardDrs** [stylelint/stylelint#6738]
### What steps are needed to reproduce the bug?

Hi!

Following https://github.com/stylelint/stylelint/pull/6699, `stylelint` now fixes
```css
	bottom: initial;
	left: 16px;
	right: 16px;
	top: 16px;
```
in
```css
	inset: 16px 16px initial;
```
which is incorrect, as `inset` does not support the `initial` value when position values are specified. As such, the property is ignored by browsers.

**Edit:**
I've check and it also happens with `padding-*` and `margin-*` which accept `initial` as a value but not `padding` or `margin`. Edited the title accordingly but not whole description

**Note**

:spiral_notepad:  Also, question that should maybe be a separate issue, shouldn't `*-no-redundant-*` rule not trigger on `inset` if there is a `browserlistrc` specifiying a version of browser which does not support `inset`?

### What Stylelint configuration is needed to reproduce the bug?

```json
{
	"extends": "stylelint-config-standard"
}
```

### How did you run Stylelint?

`stylelint '**/*.css'`

### Which version of Stylelint are you using?

`15.3.0`

### What did you expect to happen?

Stylelint rule should either not trigger or should fix with
```css
	inset: 16px 16px;
	bottom: initial;
```
Same for properties `margin-*`, `padding-*` and more

### What actually happened?

Stylelint fixes with unsupported values

```css
	inset: 16px 16px initial;
```

### Does the bug relate to non-standard syntax?

Nope

### Alternative fix

In `.stylelintrc`, use 
```json
"rules": {
	"declaration-block-no-redundant-longhand-properties": [
		true,
		{
			"ignoreShorthands" : ["inset"]
		}
	]
}
```

_Also fixes and answer my question :spiral_notepad:_

**Comment by ybiquitous** [comment]
@LeonardDrs Thanks for reporting the issue with the detailed reproduction. We can reproduce the problem [with the demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgIwhxwgFt4UBLTCnCpAGwG4td6YAzHcgRgDYAHAB7NsOAE4UA5gAsuKPkJG5i-HgOEscJJGMlUAtASKlyVGnSabtug205rFVnXsz6JMuQo2jrL-SodvAF8sEAAaEHYKNgA5JBI4RBhBeP42ADowAGcs8PAITCjJBBAMTBQUdBBknBhMKCyq8gBtLAqKqqycAE82eiocfUhCqX0upHqdKCq2lABdLCC84aKAMQgxbRwSgCssgrzYflzEMo6QLt6YfswcJsqQeiRarqqw2c6evoGhgqKxnATKBTe5VJ4vO4gRYgIJAA).

Excluding `initial` sounds good to me. 👍🏼 

> 🗒️ Also, question that should maybe be a separate issue, shouldn't `*-no-redundant-*` rule not trigger on `inset` if there is a `browserlistrc` specifiying a version of browser which does not support `inset`?

Stylelint core does not check supported browsers strictly, while some plugins do that, e.g. [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features). You can find such a plugin in [awesome-stylelint](https://github.com/stylelint/awesome-stylelint).

I think no problem to support `inset` because most modern browsers already support it ([caniuse](https://caniuse.com/mdn-css_properties_inset)).

Just to confirm, does you mean to fix only [declaration-block-no-redundant-longhand-properties](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties/) and not for [shorthand-property-no-redundant-values](https://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values), doesn't it?

**Comment by LeonardDrs** [comment]
> I think no problem to support inset because most modern browsers already support it ([caniuse](https://caniuse.com/mdn-css_properties_inset)).

As long as some plugins do that, this in not an issue indeed. Plus, we can edit the configuration to omit `inset` from the rule if needed so that's OK. I only asked this because my .browserlistrc targeted a safari < 14.

> not for [shorthand-property-no-redundant-values](https://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values), doesn't it?

Indeed, the `shorthand-property-no-redundant-values` does not need fixing. I was quick to c/p another issue title :sweat_smile:

**Comment by romainmenke** [comment]
I think this applies to more keywords : `revert`, `revert-layer`, `inherit`, ...

**Comment by ybiquitous** [comment]
@LeonardDrs Thanks, I just updated this issue title.

@romainmenke Good catch. We can use the following constant to exclude that keywords:

https://github.com/stylelint/stylelint/blob/fe4a86f8e341ef9f50dd6163f312da73f004ea02/lib/reference/keywords.js#L5

---

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by mattxwang** [comment]
Agh, another autofix issue 😅  that's on me! I'm happy to take this up as well.

I'll do a bit of searching in the CSS spec to see if there's a consistent rule on what's not allowed to be used in these shorthands (is it just basic keywords?). I may be able to catch some other issues that could have been introduced by the new autofix.

**Comment by romainmenke** [comment]
These are the CSS-wide keywords : https://drafts.csswg.org/css-values-4/#common-keywords

I don't think there is a single place where they are all defined together.
But rather they are defined in individual specifications. (e.g. `revert-layer` was added in [`css-cascade-5`](https://drafts.csswg.org/css-cascade-5/#revert-layer))

Unless I am mistaken these keywords can never be mixed with other keywords or values on a single declaration. (`!important` is not a keyword in this context)

correct :

```css
.foo {
  margin-inline: unset;
}

.foo {
  margin-left: 10px;
  margin-right: unset;
}
```

invalid :

```css
.foo {
  margin-inline: unset 10px;
}

.foo {
  margin-inline: unset inherit;
}
```

**Comment by mattxwang** [comment]
Thanks for the quick response @romainmenke, appreciate it! Your intuition is correct; these keywords cannot be mixed with other keywords/values in a single declaration. [Spec ref](https://w3c.github.io/csswg-drafts/css-cascade-4/#shorthand-property):

> If a [shorthand](https://w3c.github.io/csswg-drafts/css-cascade-4/#shorthand-property) is specified as one of the [CSS-wide keywords](https://www.w3.org/TR/css-values/#common-keywords) [[css-values-3]](https://w3c.github.io/csswg-drafts/css-cascade-4/#biblio-css-values-3), it sets all of its [sub-properties](https://w3c.github.io/csswg-drafts/css-cascade-4/#longhand) to that keyword, including any that are [reset-only sub-properties](https://w3c.github.io/csswg-drafts/css-cascade-4/#reset-only-sub-property). (Note that these keywords cannot be combined with other values in a single [declaration](https://w3c.github.io/csswg-drafts/css-syntax-3/#declaration), not even in a shorthand.)

Also, I've now opened #6748.
