### ISSUE TITLE
Using ! in react JSX gets marked incorrectly as an annotation

### ISSUE THREAD

**Issue by Kristaphonie** [stylelint/stylelint#6749]
### What steps are needed to reproduce the bug?

React element with configurable style:

`<div style={{ background: !expectedBoolean ? "red" : "blue" }}></div>`

This will throw:
Unexpected unknown annotation "!expectedBoolean"  annotation-no-unknown

because of this line of [code](https://github.com/stylelint/stylelint/blob/02f1f98064f6c3e505b261be2eaf22612356daea/lib/rules/annotation-no-unknown/index.js#L81-L83).

It checks if something starts with an exclamation point without verifying if the word is actually an actual annotation.

### What Stylelint configuration is needed to reproduce the bug?

Any configuration

### How did you run Stylelint?

CLI

### Which version of Stylelint are you using?

15.3.0

### What did you expect to happen?

I expected it to verify the word following the exclamation

### What actually happened?

It returned the exception `annotation-no-unknown`

**Comment by ybiquitous** [comment]
@Kristaphonie Thanks for the report using the template. But we would like more info to reproduce your problem. Could you provide a *minimal* reproduction repository or [demo](https://stylelint.io/demo/)?

**Comment by jeddy3** [comment]
Closing as stale. You're welcome to reopen with a reproducible example.
