### ISSUE TITLE
where is my npx syntax wrong

### ISSUE THREAD

**Issue by caochithuong270400** [stylelint/stylelint#6776]
### Describe the documentation issue

I tried to run the following npx command but still got the syntax error
![image](https://user-images.githubusercontent.com/46454286/231115340-108e61e2-5629-4e7a-8151-94c0e0636da0.png)
please help me find my syntax error and how to fix it

**Comment by ybiquitous** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
