### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by vyorkin** [stylelint/stylelint#678]
I may be wrong, not 100% sure this is related to stylelint.
Full stack trace: https://travis-ci.org/vyorkin-personal/erlyeditor#L1342

**Comment by ntwb** [comment]
I think you'll find this is a duplicate of #654 

Via "Usage Examples" in http://stylelint.io/?/docs/user-guide/postcss-plugin.md
> "We recommend you lint your CSS before applying any transformations."

**Comment by vyorkin** [comment]
@ntwb Thanks, it helps! Closing this
