### ISSUE TITLE
stylelint command broken as peer dependency

### ISSUE THREAD

**Issue by Josehower** [stylelint/stylelint#6781]
### What steps are needed to reproduce the bug?

https://stackblitz.com/edit/nextjs-gjbzy2?file=package.json

go to the stackblitz reproduction app.

1. stop the server from the terminal
2. run `pnpm run ls-stylelint`
3. verify stylelint is indeed in node_modules 
```
~/projects/nextjs-gjbzy2 4s
❯ 
pnpm run ls-stylelint

> next-app@0.1.0 ls-stylelint /home/projects/nextjs-gjbzy2
> ls /home/projects/nextjs-gjbzy2/node_modules/.pnpm/stylelint@15.4.0

node_modules 
```
4. run `pnpm stylelint "**/*.css"` 
```
~/projects/nextjs-gjbzy2
❯ pnpm stylelint "**/*.css"
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: stylelint
spawn stylelint ENOENT
```

### What Stylelint configuration is needed to reproduce the bug?

```js
/** @type { import('stylelint').Config } */
const config = {
  extends: ['stylelint-config-recommended'],
  rules: {
    'no-descending-specificity': null,
    // Allow files without any styles
    'no-empty-source': null,
  },
  overrides: [
    {
      files: ['**/*.css', '**/*.scss', '**/*.sass', '**/*.less'],
      extends: ['stylelint-config-recommended-scss'],
      rules: {
        'scss/at-rule-no-unknown': [
          true,
          {
            ignoreAtRules: ['tailwind'],
          },
        ],
      },
    },
    {
      files: ['**/*.module.css', '**/*.module.scss', '**/*.module.sass'],
      extends: ['stylelint-config-css-modules'],
    },
    {
      files: [
        '**/*.js',
        '**/*.cjs',
        '**/*.mjs',
        '**/*.jsx',
        '**/*.ts',
        '**/*.tsx',
      ],
      customSyntax: 'postcss-styled-syntax',
    },
  ],
};

module.exports = config;
```

### How did you run Stylelint?

pnpm stylelint "**/*.css"

### Which version of Stylelint are you using?

stylelint@15.4.0

### What did you expect to happen?

before npm v7+ and pnpm v8+ devDependencies must be listed as devDependencies otherwise, they will not be installed at all.

This is not the case anymore since now NPM v7+ installs peerDependencies [by default](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md), making the package.json files easier to read and understand.

stylelint should be able to be recognized when installed as peer dependency

### What actually happened?

stylelint behaves as if it would be uninstalled

**Comment by ybiquitous** [comment]
@Josehower Thanks for the report with the reproduction demo. I confirmed the behavior on the demo (stackblitz).

I'm unfamiliar with `pnpm`, but this seems a problem `pnpm` instead of `stylelint` to me. 🤔 
When I try the `package.json` locally with `npm@9.6.4`, `stylelint` works expectedly.

Does anyone help?

**Comment by Josehower** [comment]
@ybiquitous, thanks for the response

unfortunately i can't make it work either with npm

I created a reproduction with `npm` https://stackblitz.com/edit/nextjs-mdeinv?file=package-lock.json,package.json

to reproduce:

1. stop the server from the terminal
2. run `npm stylelint "**/*.css"`

```
~/projects/nextjs-mdeinv 9s
❯ npm stylelint "**/*.css"
ERR!: Unknown command `stylelint`

Try this: turbo --help

error Command failed with exit code 1
```

**Comment by Josehower** [comment]
I can confirm the behavior you exposed in npm

```
➜  test-json  ls
index.css  package.json  stylelint.config.js
➜  test-json cat package.json
{
  "dependencies": {
    "stylelint-config-upleveled": "0.0.5"
  },
  "scripts": {
    "test": "stylelint \"**/*.css\""
  }
}
➜  test-json npm t

> test
> stylelint "**/*.css"

sh: 1: stylelint: not found
npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.6.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.4
npm notice Run npm install -g npm@9.6.4 to update!
npm notice 
➜  test-json  npm i

added 184 packages, and audited 185 packages in 9s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.6.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.4
npm notice Run npm install -g npm@9.6.4 to update!
npm notice 
➜  test-json npm t

> test
> stylelint "**/*.css"


index.css
 1:1  ✖  Unexpected unknown type selector "lol"  selector-type-no-unknown
 1:5  ✖  Unexpected empty block                  block-no-empty

2 problems (2 errors, 0 warnings)

npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.6.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.4
npm notice Run npm install -g npm@9.6.4 to update!
npm notice 
➜  test-json  node -v
v18.15.0
➜  test-json npm -v
8.19.4
➜  test-json

```

but still, I am not 100% sure if this is a pnpm problem indeed because, as I showed in the reproduction example, the peerDependency is installed by pnpm.

It can't be stylelint can't resolve the peerDependencies when installed by pnpm?
maybe can't find the location since pnpm since to install peer-dependencies under `node_modules/.pnpm/stylelint@15.4.0`

**Comment by Josehower** [comment]
i also create a report in `pnPm` https://github.com/pnpm/pnpm/issues/6392

**Comment by ybiquitous** [comment]
The problem seems to be due to the difference between `npm` and `pnpm` around peer deps: does it create an executable of peer deps in `node_modules/.bin`?

- `npm`: yes
- `pnpm`: no

I don't know if this difference is intended by `pnpm` though. 🤷🏼‍♂️ 

To be honest, I believe it's safer to explicitly add `stylelint` as an executable to `package.json`, so that we can avoid such problems.

**Comment by ybiquitous** [comment]
I closed this issue because not Stylelint but package managers have this behavior and we cannot deal with it.

Please reopen it if you have additional information. Thank you.

**Comment by powerfulyang** [comment]
> https://pnpm.io/npmrc#resolution-mode
# .npmrc
resolution-mode=highest
