### ISSUE TITLE
Fix `declaration-block-no-duplicate-properties` autofix for 3 or more duplicates

### ISSUE THREAD

**Issue by cakkypamucm** [stylelint/stylelint#6784]
### What steps are needed to reproduce the bug?

- create style.css with rule
```
.test {
    // count is 4
    display: flex;
    display: flex;
    display: flex;
    display: flex;
}
```
- execute `stylelint --fix` with config above

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-duplicate-properties": [true]
  }
}
```
or
```json
{
  "rules": {
    "declaration-block-no-duplicate-properties": [
            true,
            {
                "ignore": ["consecutive-duplicates-with-different-values"]
            }
        ]
  }
}
```

### How did you run Stylelint?

CLI with `stylelint --fix`

### Which version of Stylelint are you using?

`15.4.0`, `14.16.1`

### What did you expect to happen?

I expect removing of all duplicate identical properties:
```
.test {
    // count is 1
    display: flex;
}
```

### What actually happened?

```
.test {
    // count is 3
    display: flex;
    display: flex;
    display: flex;
}
```

### Does the bug relate to non-standard syntax?

No, it's not related

### Proposal to fix the bug

I don't know

_Maybe related with [this issue](https://github.com/stylelint/stylelint/issues/6119)_

**Comment by ybiquitous** [comment]
@cakkypamucm Thanks for the report with the reproduction. We can reproduce it with the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilUCWAzgA4A2SAnvCgGYkwAeA3FugC77FmU11MvuFSFKrQbNMAXywgANCGp46AOSQBbOIgZrSMAHRgCBWeAiYFAcwQgM2FOhANWMTFAL2qAbSw4c9gq3I6EjxMVgBaSDM8czD-JBckACcoe28UAF0sCWNIiwAxCETVJFYrACsCU2NYIiNEG18Qf0CYYND3OxAyJ397GTS-AKCQ8Nzo2NZ4qCSUhE7umF6QLJAJIA).

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.
