### ISSUE TITLE
Lint run fails with an error message `isFullwidthCodePoint is not a function`

### ISSUE THREAD

**Issue by HarelM** [stylelint/stylelint#6793]
### What steps are needed to reproduce the bug?

Run lint with the common library

### What Stylelint configuration is needed to reproduce the bug?

[See: https://github.com/maplibre/maplibre-gl-js/blob/main/.stylelintrc](https://github.com/maplibre/maplibre-gl-js/blob/4bfc527f3e33ba616cc3e8ac03175d82803422ab/.stylelintrc)

### How did you run Stylelint?

stylelint src/css/maplibre-gl.css

### Which version of Stylelint are you using?

15.5.0

### What did you expect to happen?

Lint should pass

### What actually happened?

`TypeError: isFullwidthCodePoint is not a function`
The library can be found in the link below, we basically run styleling on a single css file, nothing too comlicated:
https://github.com/maplibre/maplibre-gl-js/pull/2406
![image](https://user-images.githubusercontent.com/3269297/232466527-45282bc0-a17f-4335-9ea1-110813756097.png)

### Does the bug relate to non-standard syntax?

I don't think so...

### Proposal to fix the bug

No, clue, I just upgraded from version 15.2 to version 15.4 and 15.5 and it started failing.

**Comment by ybiquitous** [comment]
@HarelM Can you try reinstallation like this? I can fix it locally.

```console
$ npm rm stylelint stylelint-config-standard

$ npm i -D stylelint stylelint-config-standard
```

**Comment by HarelM** [comment]
This seemed to have solve the issue, thanks!!
