### ISSUE TITLE
Fix `function-url-quotes` autofix for comments in SCSS function

### ISSUE THREAD

**Issue by kerryj89** [stylelint/stylelint#6799]
### What steps are needed to reproduce the bug?

After upgrading to v15+ of Stylelint, some of my SCSS comments are changing into CSS comments.

I know Stylelint deals with CSS, but since Stylelint was the only piece that changed I feel like it's either an issue that stems from Stylelint or a change that SCSS config maintainers need to be aware of (and I'll file a ticket there if you can let me know what needs to be changed).

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": [
    "stylelint-config-standard-scss"
  ],
  "rules": {
    "color-function-notation": false,
    "scss/at-function-parentheses-space-before": false
  }
}

### How did you run Stylelint?

See [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEARGAHGA7WuYAnqgJYDOq5MALqjRKgG4CMArGbvQBYWqwBbCADoAOrhSoAyjSIAbGHNK46rACyoA1jGyUAhnLn8IAVwBGCqnL3luMcuMkB3UjW79SAM08wATnjpyMHJKSFxPUgBzcnhHNGA41CTREHJZBSUVFPhUFIA9dWEABmKUgBpE5NT0xWUaAFowiMj6tL18PV8oVuCHBFyQAoB2YtKQRIBfcXFhGns6BNxRGkkAFV5KNNJDVCcIX01KZWZ2aZpIOX2cgGIi7wBucSml3AABAVIAD2PyCAEYeofb64AAUAEpUIskkk1htUAZfrt9odOCc2ABqcTQ1AAMng8HqThgZk0rh6vgghjMnXqNF8ejAmng3H2pAAXhAVAYKlxofjCcTSQ0ghSqTS6QymSzfOzOTQDJCsdjodTGZEKSZ8DlMjAaeq9FBSAEQQxUGYIDQGAIyqh-FAbRYTDAwY9ecqzZL1aZ8PUsBByK5SJycv4BI0DGAQUMsJ8IUVXe6kqrNF7Nd1-Dg9DQcrgIPUM7qaAnE8nUz6A2yYDkwBGQSwikUAKSoeqoa7AUPhuSRlhqGNgiYQ+tN4tJZ7PcTvL4-MCiuStbgGiBOcj1CBMPyeS5OEEAEmUYDkJlg9U+9T03xiqE8CJgNv3hCPJ6I58vOTpTvvB6fAM6FJXOQ3nI1AQlCKqehqWpKom0JeHu37HgCL4XhQPIwTBILQehMGwnwYCLrgkT2KirAYlh2Hujqer0oaxpMJ0IL1PUZiRPe5pQC+LEQgAzE2Nq+JE1IggATGwbA2qJ4moJJNpNmCYJoRRMFUb49T6rRKgggJQkydJYkSfpqByTa9G+IxzGsagu7sZxkQQkMxnkRRClOdhuAmIYLluuhcEPoeiGnq+qGuehmHeUp2K4aEBFEUcXCkei9AQBAIVKSpak0UammmjKkTcDQJkMUxLE2tc3ieDxfG2oJegiYZum6XJXkRYm6XqVlNAmowuX5fxNV1VJDWGcZzBFRZpXlfZjnhc5ikte5nmjqg66btuOQrb41hEK6E4vK8niamANBBlwyhYCYDT4TAjLmmemV5gIehYKgYXYtZkQ5C17q7ldN0QHdBpBuNWG7hEhifV9SQ-XYf0A4aeZg3Ic3KpIwi-Zot3wAyx0bkgwj3VjR2kBuIW7tjxMAixEMUdD10Y-9+aA3m5MbsDM1QyzAKI9TMG07DjPw+eROs4jyORWgaMw-TnzwJ4EBgCY5B4wTcsKw47NWarisWTz2F89LAtA1rq4laTxv1NzEX67dhsI-L2uiyFqPo5jLIbr4ytM8yG2k27fg6191sM-d9R+6ppsa7uYcW9sci64mQdw0D0eOxrztS5j6MwFAnvw-AWdQKTBcB1bLvB0zjRS9nbO88Xls02XSd5nXsdi9C6d05jhrkHoFjZ7nQbwN3vcKIXkfD333RU6XGfl4LE+jzXCcL9X9foYntv1Cv3Sp6BWGvP4NAmL4XCvSWH2Q8q71t0ka+Q6Drepe3EuN4TOMwAPEBvxTT9JJzJdKTJsLSmrFf7wmATHcGgD-6pyUh3WGst7ZK3xl7Y2YDzbTxaqDJBS9sLmzvuvfBj8NYoxfrPGWYdP7e3dmA6OmCrZ0NASQ6EKdY7x2+qwwwN9SGoElp3f6+cq45xQXnAuYDi70IbkI3B6EW5QKkXTVexC4FkP4TLbeVDt5gO3gAvWOiI5KR0QQ76RjlHQjBE8EAZQQBgxgAAOT0P8BAIAYCfEcVgBQwggghCseATkzRnFgRSK4uY+A+g5AANpYRSGkeQtQVCNH8VEVo8oOhdB6CEFISoAC6ikUi+A8vYbIipvIpAuPsC2h1jqcnqLmeU1Slj9CAtQZGMTehICzJUwgDTfSdACHYagq5yBYAZJTGAct-DFOaTAJU45fFNCiAAMX2I9GgziABWvxcC+NgFgcggSlQxJqJkGgxSUjWDmGkcohzqhxJOYk8IyS2hpO6N48JAwLnzCybgCYIAJhAA)

### Which version of Stylelint are you using?

15.5.0

### What did you expect to happen?

Keep double slashes like in v14 of Stylelint

### What actually happened?

Valid double slash comments inside properties or arguments turn into CSS comments.

### Does the bug relate to non-standard syntax?

SCSS

**Comment by kerryj89** [comment]
I tried having using Stylelint's ignore feature around the SCSS comments via

```
/* stylelint-disable */
// This changes in v15+
/* stylelint-enable */
```

and

```
/* stylelint-disable-next-line
// This changes in v15+
```

but it seems to be changing into CSS comments still.

**Comment by ybiquitous** [comment]
@kerryj89 Thanks for the report with the reproducible demo! I can produce the same problem with  [this smaller demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAzArgOzAFwJYQwAIUIIAKAHQwuwHpbDIBbJmDbKgSkOAF8QANCBS4ANjAByAQ1YIQMAB4yADuIB0AZzAaNg8AREBzOcCqFCFcGg3YITAMoBPdlIWX4FkMog3tGgLRaOpYCZp4ATmjiGu48YeaW6Fh4BP5o4aL+AI5oENgwMQieUqIA7lKOhWG8VPxCkBhGAGIQ4UxS2HIAVhoEerDKuoimRJ42juKiuOyxlqIdBRyCYZbevjqBfrMg8-k2lrUgvEA), which identifies this is a problem of the [`function-url-quotes`](https://stylelint.io/user-guide/rules/function-url-quotes/) rule.

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by ybiquitous** [comment]
I can identify the cause and am preparing for PR.
