### ISSUE TITLE
Try Online! feature on the website

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#680]
It'd be pretty neat if you could try out stylelint with a dropdown of the official linters.

This would have to be built after https://github.com/stylelint/stylelint/issues/330 is addressed but in the meantime maybe we could add some simple examples with a dropdown to the website?

http://codepen.io/corysimmons/pen/eJjave?editors=1100 (note: dropdown buttons don't actually work)

**Comment by davidtheclark** [comment]
Yep, it is a good idea. Already addressed as part of #6.
