### ISSUE TITLE
Fix `selector-pseudo-class-no-unknown` false positive for `:modal`

### ISSUE THREAD

**Issue by jbvolvo** [stylelint/stylelint#6809]
### What is the problem you're trying to solve?

I'm writing CSS for only modal dialogs (not vanilla dialogs). The web spec allows `:modal` to target such cases. But with stylelint I get an error.

`Unexpected unknown pseudo-class selector ":modal" (selector-pseudo-class-no-unknown)`

### What solution would you like to see?

Would like to see a warning instead of an error due to low range of browser support perhaps?

**Comment by ybiquitous** [comment]
@jbvolvo Thanks for the report. I can reproduce the problem with [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcCC20CGAbABMAOgO00yVQCcBzASz3kwEYSYkBufAXxABoQAzC9GAHKokcRDAAewgA78AdGADOCzuAh5eZBCFwFMOEBIAuMPFAX6aAbXyFC+hYYCe-dFUMBaSOopl3D1KakUPo2mAC6bCpeGgBiECTEhloAVgpqKrBSyog6diAOzjCueIYWeiDoqMYO+hyh9k4ubp5qGn6GAVBBZfqV1aUgkaxAA). As you commented, the `:modal` pseudo-class is in the [Selectors Level 4 spec](https://w3c.github.io/csswg-drafts/selectors/#modal-state).

Probably, we need to just add `modal` to the following list `pseudoClasses`:

https://github.com/stylelint/stylelint/blob/380e92053f3441cd318e4d6c2acba887ea12f700/lib/reference/selectors.js#L245

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.
