### ISSUE TITLE
bug: Atom Linter - Column start greater than line length

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#681]
![image](https://cloud.githubusercontent.com/assets/224636/12773742/969c59ec-ca0c-11e5-8dcd-007bb59b622e.png)

WordPress standard selected in Atom Linter > stylelint options.

Just opened a fresh .scss

**Comment by davidtheclark** [comment]
If the bug only happens when using linter-stylelint, please file the issue there: https://github.com/AtomLinter/linter-stylelint
