### ISSUE TITLE
Update vulnerable `yaml` package

### ISSUE THREAD

**Issue by TannerS** [stylelint/stylelint#6813]
Looks like  `cosmiconfig@7.1.0` has a vuln a level deep with yaml https://security.snyk.io/package/npm/yaml thats popping up in our scans, i did open issue with them https://github.com/cosmiconfig/cosmiconfig/issues/303 to add a fix to v7 but just in case wanted to report here. this issue doesnt seem to exist in v8

**Comment by d-fischer** [comment]
You're probably just not up to date since [stylelint already uses v8](https://github.com/stylelint/stylelint/blob/main/package.json#L121).

**Comment by ybiquitous** [comment]
Thanks for the information. I just opened PR #6814 to fix the vulnerable `yaml` version.
