### ISSUE TITLE
Anyone have a bunch of different stylesheet examples?

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#683]
It'd be nice if we had a ton of stylesheet (and preprocessor sheet) examples to test our configs out on.

Or heck, just one that tests every single rule in the rules.

Just curious if anyone has such a thing laying around anywhere. =)

**Comment by davidtheclark** [comment]
If you or anyone else wants to work on something it would be very useful for #569

**Comment by corysimmons** [comment]
Okay, I'll add it to me todo list. :+1:

**Comment by jeddy3** [comment]
Closing this in favour of tracking in #569
