### ISSUE TITLE
Make `ignoreFiles` behave like `.stylelintignore`

### ISSUE THREAD

**Issue by segevfiner** [stylelint/stylelint#6830]
### What is the problem you're trying to solve?

It seems `ignoreFiles` uses a different glob syntax than `.stylelintignore`.

### What solution would you like to see?

They should behave the same. Both should just use `node-ignore`. That's how it works in ESLint AFAIK.

**Comment by ybiquitous** [comment]
@segevfiner Thanks for the report and sorry for the late response. This issue is related to:

- #5804

We need to discuss `ignoreFiles` comprehensively.

**Comment by jeddy3** [comment]
Closing in favour of a single discussion in https://github.com/stylelint/stylelint/issues/5804
