### ISSUE TITLE
Add `insideFunctions: {"function": number}` to `number-max-precision`

### ISSUE THREAD

**Issue by firefoxic** [stylelint/stylelint#6856]
### What is the problem you're trying to solve?

It is very rare to find a need for precision values greater than 2 decimal places. Therefore, the `number-max-precision' rule almost always specifies `2'.

But the `chroma` component of the `oklch()` color function is special in this sense. Even in the `rec2020` color space, the highest value of `chroma` does not exceed `0.5`, and values from `0` to `0.3` are mostly used. With such a short range, even 3 decimal places are not enough, it is desirable to use at least 4.

At the same time, I would not want to completely ignore this component, because automatic converters and generators often produce more than 10 digits, which is not necessary at all.

### What solution would you like to see?

I would like `number-max-precision` to have an additional option, something like `oklchChroma` (suggest a more appropriate name), which takes an integer like the main value of the rule, but does not depend on it.

Example:
```json
{
	"rules": {
		"number-max-precision": [
			2,
			{
				"oklchChroma": 4
			}
		]
	}
}
```

**Comment by ybiquitous** [comment]
@firefoxic Thanks for the proposal. It's an interesting case. So, could you provide CSS code examples so that we can easily understand your problem?

For example, when the following config is given,

```json
{
	"rules": {
		"number-max-precision": [
			2,
			{
				"oklchChroma": 4
			}
		]
	}
}
```

CSS code:

```css
a {
	/* bad */
	background-color: oklch(...);

	/* good */
	background-color: oklch(...);
}
```

**Comment by firefoxic** [comment]
When the following config is given:
```json
{
	"rules": {
		"number-max-precision": [
			2,
			{
				"oklchChroma": 4
			}
		]
	}
}
```

```css
a {
	/* bad, every number */
	color: oklch(75.323% 0.24546 45.234);
	transition: color 0.315s;

	/* good */
	color: oklch(75.32% 0.2455 45.23);
	transition: color 0.32s;
}
```

**Comment by firefoxic** [comment]
But when the following config is given:
```json
{
	"rules": {
		"number-max-precision": 2
	}
}
```
CSS code:
```css
a {
	/* bad, every number */
	color: oklch(75.32% 0.2455 45.23);
	transition: color 0.315s;

	/* good */
	color: oklch(75.32% 0.25 45.23);
	transition: color 0.32s;
}
```
And the approximate correspondence of these colors is:
`oklch(75.32% 0.2455 45.23)` → `#ff6800`
`oklch(75.32% 0.25 45.23)` → `#ff6600`
Whereas even the second decimal place of the other components (`lightness` and `hue`), has almost no effect.

**Comment by ybiquitous** [comment]
@firefoxic Thank you for providing the examples. We can see them also with the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgegCoUAjJKAGhRgDcYAnATxUwFcBbY+lAvLXSADYQ68FBADWAsAAsAFAHYArADoAzACZVAUhQAGZeoAsiwwDYUxg6sMBKANx8cOOkkwBnAJY4PETKMHCemoAjIpuDtjY+EQA5hDQ3LxRASJikjIKKho6+kaKihYqmvaOzq6e3r7+EEJ0QRrhWAC+fJiEALydPK2oGFGEJGSUNPRMrBxc3ck1wqISUnJKauo5BsYFlsURuGXuXj5+KCn1oY2RuANxCVP8M6nzGUvZQeobRaolUbsVB9W19eozk0QOQQAAzDwCGAAOSQbDgiBgAA84QAHKHKMBuNwg8C+CExBAgPooFDoEB0FhQtzk0Qk0lkkDjTh0AC0bCQSNZqLoMDAHk8vlpKHUWFJLUwwNBkEwBIAYsIOTgiQArNy+XGwVE4xD08luHAMKECDyYHDC8mhZSmAzk5ogJpAA):

<img width="401" alt="image" src="https://github.com/stylelint/stylelint/assets/473530/2e607e67-5979-4be1-8678-50d14ccbf34d">

**Comment by ybiquitous** [comment]
I now understand your problem.

But the [`number-max-precision`](https://stylelint.io/user-guide/rules/number-max-precision/) rule currently has the `ignoreProperties` and `ignoreUnits` options, so I think we should provide a more generic way to ignore such a case than `oklchChroma` (too specific).

Please see also [our criteria for built-in rules](https://stylelint.io/developer-guide/rules#define-the-rule):

> A rule must be:
> - ...
> - generally useful; not tied to idiosyncratic patterns

For example,

```json
{
  "number-max-precision": [
    2,
    {"ignoreFunctions": ["oklch"]}
  ]
}
```

**Comment by firefoxic** [comment]
I thought about it, that's why I said it above:
> At the same time, I would not want to completely ignore this component, because automatic converters and generators often produce more than 10 digits, which is not necessary at all.

**Comment by ybiquitous** [comment]
Providing an option that ignores only a specific argument in an arbitrary function might be difficult... 🤔

I don't find a good way for now. 😓

**Comment by firefoxic** [comment]
How about the whole function instead of a specific argument?
```json
{
	"rules": {
		"number-max-precision": [
			2,
			{
				"insideFunction": [
					{
						"oklch": 4
					}
				]
			}
		]
	}
}
```
🤔

**Comment by ybiquitous** [comment]
`insideFunctions` sounds good! Supporting regex may be also nice:

```json
{
	"number-max-precision": [
		2,
		{
			"insideFunctions": {
				"oklch": 4,
				"/^foo/": 1
			}
		}
	]
}
```

**Comment by ybiquitous** [comment]
Blueprint:

- Rule: [`number-max-precision`](https://stylelint.io/user-guide/rules/number-max-precision/)
- New secondary option: `insideFunctions: { "function": number }`
  - `"function"` supports a regex, e.g., `{ "/^foo/": 1 }`
- Description: the `insideFunctions` option can change a primary option value for specified functions.

What do you think?

**Comment by firefoxic** [comment]
> What do you think?

It's awesome 😊

**Comment by ybiquitous** [comment]
OK, let's go on.

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to add a new option](https://stylelint.io/developer-guide/rules#add-an-option-to-a-rule) in the Developer guide.

Feel free to comment if having any concerns.

**Comment by romainmenke** [comment]
For reference : 

https://drafts.csswg.org/css-color-4/#serializing-oklab-oklch

> The precision with which [oklab()](https://drafts.csswg.org/css-color-4/#funcdef-oklab) component values are retained, and thus the number of significant figures in the serialized value, is not defined in this specification, but due to the wide gamut must be sufficient to round-trip L values between 0 and 1 (0% and 100%), and a and b values between ±0.5, with at least sixteen bit precision; this will result in at least five decimal places unless trailing zeroes have been omitted. (half float or float, is recommended for internal storage). Values must be [rounded towards +∞](https://drafts.csswg.org/css-values-4/#combine-integers), not truncated.

All the new color functions have support for much higher precision. But `oklch`, `oklab` and `color` also have value ranges between `0` and `1` or even a fraction of `1`.

The specification also advices that tools emit values at high precision so that values can round trip.

So the result is almost always more than 2 decimal places :)

------

How does `insideFunctions` work with `calc`? 

```css
.foo {
  color: oklch(from pink 75.323% 0.24546 calc(0.00001deg + h));
}
```

I would assume that the closest matching ancestor function determines the limit, not the immediate parent.

thoughts?

**Comment by ybiquitous** [comment]
@romainmenke Thanks for providing the insights! 😄 

---

> Also `lightness` is allowed to be a number between `0` and `1`

We should handle such a case with another rule; a new general-purpose built-in rule or a dedicated plugin. Personally, a plugin might be preferable here.

I believe a rule to detect invalid ranges in color functions should be so useful, but unfortunately, it should be out of the scope of `number-max-precision`.

---

> How does `insideFunctions` work with `calc`?

Good point. I missed the case. 👍🏼 
To simply implement the option, `insideFunctions` should be applied also to nested functions like `calc`. For example:

```json
{
	"number-max-precision": [
		2,
		{"insideFunctions": {"oklch": 4}}
	]
}
```

```css
.foo {
  color: oklch(from pink 75.323% 0.24546 calc(0.00001deg + h));
/*                               ^^^^^^^      ^^^^^^^
 */
}
```

@firefoxic Any thoughts?

**Comment by firefoxic** [comment]
> The specification also advices that tools emit values at high precision so that values can round trip.

@romainmenke So you suggest `ignoreFunctions` instead of `insideFunctions`? 🤔

I think it would be even easier to implement. Including the case with `calc()`.

> Please consider contributing if you have time.

@ybiquitous Yes, although I don't have much experience, I will try to do it. But it seems we have to choose an option. Maybe I really wanted too much control?

**Comment by romainmenke** [comment]
> The specification also advices that tools emit values at high precision so that values can round trip.

> So you suggest ignoreFunctions instead of insideFunctions?

No, I only wanted to provide context on why specifically these values always have so many decimal places. 🙂

`insideFunctions` can work as `ignoreFunctions` by setting a very large value for the allowed decimal places. So `insideFunctions` is the more powerful (better?) feature.

**Comment by ybiquitous** [comment]
> Yes, although I don't have much experience, I will try to do it.

Glad to hear. PR #6773 recently added a new secondary option, which could help.

**Comment by Mouvedia** [comment]
I don't really like the name `insideFunctions` but I don't have anything to propose either.
