### ISSUE TITLE
Stylelint CLI results in `command not found` error

### ISSUE THREAD

**Issue by benfrain** [stylelint/stylelint#687]
Running stylelint v4.2.0 via Gulp works as expected.

However,  Running it via CLI e.g. `stylelint /thing/*.css` results in `command not found: stylelint`. Likely my ineptitude with CLI!

Equally, running `which stylelint` results in `stylelint not found` whereas `which node` gives me: `usr/local/bin/node`

Does anyone else have this issue? Even tried installing stylelint globally `sudo npm install stylelint -g` but the same issue.

**Comment by davidtheclark** [comment]
I have had no trouble installing stylelint globally myself, and haven't heard any complaints like this yet, so I'm thinking there must be something going on in your setup.

Are you able to successfully install *other* npm modules globally? If so ... weird. If not, then I'm afraid something has gone bonkers with your node/npm setup.

**Comment by benfrain** [comment]
Thanks David. :+1:

**Comment by davidtheclark** [comment]
@benfrain Did you figure it out?

**Comment by benfrain** [comment]
No but just tried a colleagues machine and it installs as expected. I'll update this thread when I get to the bottom of it but closed as it's clearly not something particular to stylelint :)

**Comment by benfrain** [comment]
Updated node to 4.2.6 (was 4.1.2) and re-ran `sudo npm install stylelint -g` again and all is well - no idea what had gone wrong!
