### ISSUE TITLE
Throwing errors at impossible places

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#688]
https://github.com/atom-community/linter/issues/1069#issuecomment-180000798

I don't know if this is a problem with stylelint or Atom's stylelint linter.

**Comment by davidtheclark** [comment]
Can you provide details about which rule caused this problem?

**Comment by corysimmons** [comment]
No, I'm sorry. I closed the errors after filing the issue and began coding again and they didn't popup again.

It's happened a few times so I'll try to keep an eye on it and replicate steps the next time it comes up.

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12865157/07f3e476-cc73-11e5-85b9-7f0762c5228a.png)

Happening when I'm working in a .md file.

![image](https://cloud.githubusercontent.com/assets/224636/12865160/21a23bf2-cc73-11e5-80d0-c40192be39a0.png)

Doesn't lead me to believe stylelint should be activated on all filetypes.

Is this a problem with stylelint itself or the Atom stylelint Linter? I'm leaning towards the latter...

**Comment by davidtheclark** [comment]
Sounds like linter-stylelint.

If you can't reproduce it in another settings (CLI, postcss plugin, Node API) then please file the issue with linter-stylelint.
