### ISSUE TITLE
Set a timeout for GitHub Workflows

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#6880]
see : https://github.com/stylelint/stylelint/actions/runs/5136149333/jobs/9242517643?pr=6879

This workflow job ran for 6 hours.
99% sure this was a glitch unrelated to the actual change.

Setting a maximum duration for workflow jobs should help with cases like these.
Preventing accidental usage of resources is good for the environment :)

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

**Comment by ybiquitous** [comment]
@romainmenke Nice catch! Please feel free to open a pull request. 😄
