### ISSUE TITLE
Fix `unit-no-unknown` false positives for `unicode-range` descriptors

### ISSUE THREAD

**Issue by Mister-Hope** [stylelint/stylelint#6891]
## Reproduction

https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqABAGwIYBcCWAdgLQwAeOaKSAOgQAIBmEBORDWYMawtaaTLIgHcYeAOYALHPDQAWAAzyA3L37NWAZxwBPDDBl4cWDHjAqCfAa3YBbPBm0yAMrgjm+GgE5gZGCGGMACmoQFxwINABJIxMwEIBKABpMfyCQsIgiaONTBMTVPgBXTwxgkCkcAAcNeCQkKw0AOjEtXFNGyBskDSRscKQANwBGAHYkAGUANkKADiFZACEAWQBVABUABQAJACtSDQBBFbwiAEcAKQBhAE1GoQgGBgAmBIK+NU8bXDL7x5eQeLmVSFAimaAwIieLAEMT6NArADU8iGiiI8iesgAYslEeiAKwAThxCKGAFFUWTMdj4Qinuj5MS6Qd5EQmQt8hZ3oimQARVnyS7U7lDIYAZkZl0mLKelxGQoRBxGdKIiqp5gAvrQQIkQAx7DAAHJYGxwRBkY2VPQdDQabXgZh6sQIEA8TkhMg4GAEKAaEIyADabxCWl0MBMgkgBEdRFa3qwnigIVUAF1aOq7ZHHZiIJ9cM6dhpmHbYNVna6+MGdHpwzg-WgQn0YFoQhyKyAQ9XCKxM+IY0Y4wm6w3cE3ayA0yB1UA

### Which version of Stylelint or dependencies are you using?

15.6.3

### What did you expect to happen?

No problem

### What actually happened?

error

### Does the bug relate to non-standard syntax?

no

**Comment by Mister-Hope** [comment]
Probably caused by https://github.com/stylelint/stylelint/commit/7206cfc12e61d5f3af9308ad960844655b01f666

**Comment by romainmenke** [comment]
Thank you for reporting this @Mister-Hope 

I can confirm the issue.

**Comment by ybiquitous** [comment]
@Mister-Hope @romainmenke Thanks for the report and the quick-fix!
