### ISSUE TITLE
rule-properties-order: Add an empty line before unspecified properties

### ISSUE THREAD

**Issue by alienlebarge** [stylelint/stylelint#690]
Hi,

Is there a way to add an empty line before unspecified properties via `rule-properties-order` ?

Something like:
```
"rule-properties-order": [
    ["color", "background"],
    {
        unspecified: "bottom",
        emptyLineBefore: true
    }
]
```

**Comment by ntwb** [comment]
@alienlebarge This is currently being discussed in #578, I'm pretty sure that include coverage for new lines before `unspecified` properties.

**Comment by alienlebarge** [comment]
@ntwb thanks, I will take a look
