### ISSUE TITLE
Fix `allowEmptyInput` in configuration files

### ISSUE THREAD

**Issue by astorije** [stylelint/stylelint#6926]
### What steps are needed to reproduce the bug?

I made a reproduction repo at https://github.com/astorije/stylelint-allowEmptyInput-issue-repro. Or follow steps in this issue instead.

### What Stylelint configuration is needed to reproduce the bug?

```yaml
extends: stylelint-config-standard

allowEmptyInput: true
```

### How did you run Stylelint?

Use the following `package.json`:

```json
{
  "private": true,
  "scripts": {
    "pass": "stylelint \"**/*.css\" --allow-empty-input",
    "fail": "stylelint \"**/*.css\""
  },
  "devDependencies": {
    "stylelint": "15.7.0",
    "stylelint-config-standard": "33.0.0"
  }
}
```

Make sure to have no CSS file in the folder.

Run:
- `yarn pass` works as expected
- `yarn fail` should also work but instead the `allowEmptyInput` configuration is ignored.

### Which version of Stylelint or dependencies are you using?

- `stylelint`: 15.7.0
- `stylelint-config-standard`: 33.0.0

### What did you expect to happen?

Both ways of using the `allowEmptyInput` / `--allow-empty-input` options should produce the same results.

### What actually happened?

```
$ stylelint "**/*.css"
Error: No files matching the pattern "**/*.css" were found.
    at standalone (/[...]node_modules/stylelint/lib/standalone.js:260:43)
```

(In case it might be related: https://github.com/stylelint/stylelint/issues/5142)

**Comment by ybiquitous** [comment]
@astorije Thanks for the report with the reproduction!

Indeed, this is a bug, and we should fix the following logic: 

https://github.com/stylelint/stylelint/blob/1c44f18c7322449990f790e92ae4a50188a3dac8/lib/standalone.js#L254-L255

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by astorije** [comment]
> Please consider [contributing](https://stylelint.io/contributing) if you have time.

You went faster than I could react :D
Next time!

Thank you so much for fixing this, works like a charm :)

**Comment by ybiquitous** [comment]
Ya, I created a PR since I found the cause immediately. 😄 
I'd expect your next time contribution!
