### ISSUE TITLE
Remove deprecated rules

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#6961]
As of v15.0.0, we have deprecated many stylistic rules. And, as we announced when the v15.0.0 release, we will remove these rules in the next major version (maybe v16.0.0).

Additionally, as #6753 introduced, the Stylelint community has provided 3rd-party plugins as an alternative, e.g.

- https://github.com/elirasza/stylelint-stylistic

So, I think we can perform this removal without a big confusion.

See also:

- https://github.com/stylelint/stylelint/blob/e56fc6cfdd7c9dab342a1289ab5a596b29c7be57/docs/migration-guide/to-15.md?plain=1#L12-L14
- https://github.com/stylelint/stylelint/blob/e56fc6cfdd7c9dab342a1289ab5a596b29c7be57/docs/user-guide/rules.md?plain=1#L334-L336

**Comment by jeddy3** [comment]
Done in https://github.com/stylelint/stylelint/pull/6979

**Comment by aiddroid** [comment]
If you deperacated the `indentation` rule, Can you tell the user what the alternatives are?
