### ISSUE TITLE
`declaration-block-no-redundant-longhand-properties`: support collapsing and new properties

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#6984]
### Reason

see https://github.com/stylelint/stylelint/pull/6958#discussion_r1240996956

### Collapsing

fixes for these properties:

- [ ] padding
- [ ] margin
- [ ] border-radius
- [ ] border-width

e.g. for `border-radius`

```css
border-top-left-radius: 1px;
border-top-right-radius: 4px;
border-bottom-right-radius: 2px;
border-bottom-left-radius: 4px;

/* gets fixed to */

border-radius: 1px 4px 2px;
```

```css
border-radius: 1px 4px 2px 4px;

/* this fix would be a bonus targetted to previous versions of stylelint */

border-radius: 1px 4px 2px;
```

### New properties

support:

- [ ] overflow
- [ ] background-position
- [ ] border-image-width
- [ ] border-inline-width
- [ ] border-block-width
- [ ] offset-position
- [ ] overscroll-behavior

**These lists are not exhaustive and may be expanded by the PR submitter(s) if need be.**
Id recommend to handle it in several separate PRs.

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for opening the discussion.

Just to confirm, should we provide this feature as an opt-in or not? I'm a bit concerned if there are any cases where people want to avoid shorthand with fewer values than 4, like `border-radius: 1px 4px 2px`.

**Comment by Mouvedia** [comment]
> I'm a bit concerned if there are any cases where people want to avoid shorthand with fewer values than 4

The only reasons I can come up with would apply to 4 values as well.
i.e. being explicit, easier to maintain

> should we provide this feature as an opt-in or not?

I think it should be automatic if it's easy to implement.
i.e. the logic needs to be shared for all properties supporting 3 values

**Comment by ybiquitous** [comment]
Okay, I agree with supporting the collapsing without any option. 👍🏼

**Comment by jeddy3** [comment]
I believe you're describing our [`shorthand-property-no-redundant-values`](https://stylelint.io/user-guide/rules/shorthand-property-no-redundant-values) rule.

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYKA6A7DAXARhAE6xEC0uEADmQDYwBmuZRSUAlgK4DO8KAjFQAeAbmwoUhEjHKUaRdgHMAFs1YcefACzCxWCVNJlCuSgFsWS1SzZdeKAEy7xk4kZPm6jNbc0odotgAviAANCAM7PQAckhmcIgwQnFU9AB0YNzcYeAQWJGKCCDALhggRJz03GV8JfoSmCCwYLRIrLjseca0EGAA1mRYECwwUJxYUEhYzD1YKlNQZFRE1DIdMNUIKLgVMKEuEmXcysS4ygtLK1RrAJ6Dw0Sj45PTZABuSLScGzXbuy5BYI5SD5JQAMWIZiQuCKACtuHkcrAqNlEHVDiBuLgbvRaOxpr8yq1cBtcGV9vUjtjcfjmCCCmQsQs2lBCSBiaSykCgkA)

---

When opening issues, please:

- use the appropriate [template](https://github.com/stylelint/stylelint/issues/new/choose)
- limit the issue to one problem
- follow our conventions for [label](https://stylelint.io/maintainer-guide/issues#labels)
- follow our conventions for [titles](https://stylelint.io/maintainer-guide/issues#titles) 

As these help us all out.

**Comment by ybiquitous** [comment]
Sorry, I missed the existing rule `shorthand-property-no-redundant-values`. 😓

**Comment by jeddy3** [comment]
We've a lot of rules and we can't be expected to remember them all 😄

**Comment by Mouvedia** [comment]
@jeddy3 so the second part—new properties—is dismissed as well?

**Comment by jeddy3** [comment]
Please open a dedicated new false negatives [bug report issue](https://github.com/stylelint/stylelint/issues/new?assignees=&labels=&projects=&template=REPORT_A_BUG.yml) following our conventions for titles and labels.
