### ISSUE TITLE
`declaration-block-no-redundant-longhand-properties` should honor my `browserslist` config

### ISSUE THREAD

**Issue by lianzhao** [stylelint/stylelint#6989]
### What steps are needed to reproduce the bug?

```css
.my-element {
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  rules: {
    'declaration-block-no-redundant-longhand-properties': true,
  },
};

```

### How did you run Stylelint?

```shell
styelint
```

### Which version of Stylelint or dependencies are you using?

15.8.0

### What did you expect to happen?

my `.browserslistrc`:
```
chrome 76
```

no stylelint error expected.

### What actually happened?

stylelint error: `Expected shorthand property "inset" (declaration-block-no-redundant-longhand-properties)`

### Does the bug relate to non-standard syntax?

No.

### Proposal to fix the bug

Expect stylelint to honor my `browserslist` config. `inset` was not supported in my config (chrome 76). See https://caniuse.com/?search=inset

**Comment by lianzhao** [comment]
I understand that I can ignore `inset` with
```
module.exports = {
  rules: {
    'declaration-block-no-redundant-longhand-properties': [true, { ignoreShorthands: 'inset' }],
  },
};
```

**Comment by jeddy3** [comment]
@lianzhao Thanks for the report and for using the template.

You can configure the rule it ignore the `inset` property:

```json
{
  "extends": [
    "stylelint-config-standard"
  ],
  "rules": {
    "declaration-block-no-redundant-longhand-properties": [true, { "ignoreShorthands": ["inset"]}]
  }
}
```

See [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0BbAngWhgGximAdgC4AEwAOgSSURAA7wkAMA3JdQE4CWA5gBZFGrdiQBGEIrRRC2VErgBmg5rIC+IADQgFXXADkAhvgQgYADyN1cSMAGdbm8BAI6eJinPKmzRQlFtejADaItRetkRouNhcxBiQLrwYEQYEUAYcUF4iALoaIl4cAK64AQhkoSResGDYGQZEXM4YotgQYADWGAQQGBwwUEVpqUQYbQT8qVAYdBz0MByNMGXBRMUwGmRVILw9-QDKfBCLfFMrJCE7BLYwRF45qjkiqpTqWgmuAGLHKA0mAFa2ZyOWB0ByIDxhEARKI4WJ3cpeOq+CJefKeaGRaLw+LOVzJIhTDJZREgZHLBGvECqIA).

Stylelint doesn't include browserslist. It did a few years ago, but we took it out for performance reasons.

**Comment by ybiquitous** [comment]
@lianzhao Do you find the following plugin? It uses the caniuse database.
https://github.com/ismay/stylelint-no-unsupported-browser-features

Note: the plugin is present on [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint#plugins).

**Comment by lianzhao** [comment]
@jeddy3 Thanks for the reply. I understand that I can ignore `inset ` with `ignoreShorthands`. But when I update my `.browserslistrc`, I must update my `stylelint.config.js` as well. 😂

**Comment by lianzhao** [comment]
@ybiquitous Yes I'm using `stylelint-no-unsupported-browser-features`.

**Comment by jeddy3** [comment]
> But when I update my .browserslistrc, I must update my stylelint.config.js as well.

That's the compromise we had to make when balancing competing needs. You're welcome to [port the rule to a plugin](https://stylelint.io/developer-guide/plugins) and adapt it to use `browserslist` like the [`stylelint-no-unsupported-browser-features`](https://github.com/ismay/stylelint-no-unsupported-browser-features) plugin did with one of our older built-in rules.

**Comment by lianzhao** [comment]
> That's the compromise we had to make when balancing competing needs. You're welcome to [port the rule to a plugin](https://stylelint.io/developer-guide/plugins) and adapt it to use `browserslist` like the [`stylelint-no-unsupported-browser-features`](https://github.com/ismay/stylelint-no-unsupported-browser-features) plugin did with one of our older built-in rules.

Got it. Thank you for you help.

**Comment by lianzhao** [comment]
BTW, `doiuse` (used by [`stylelint-no-unsupported-browser-features`](https://github.com/ismay/stylelint-no-unsupported-browser-features)) is not working with `. browserslistrc` currently. Please refer to https://github.com/anandthakker/doiuse/issues/63
