### ISSUE TITLE
Bring stylelint-rule-tester back into the fold

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#702]
Now that we are exposing utilities that plugin developers might want to use --- such that both of the plugins I've made use stylelint as a dependency --- I think there's not a great reason to have stylelint-rule-tester as its own repo, instead of just keeping it in here and exposing it just like other utilities.

Any disagreement?

**Comment by corysimmons** [comment]
:+1:

**Comment by jeddy3** [comment]
Sgtm.
