### ISSUE TITLE
Add --verbose option to CLI

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#703]
I can't tell if it's running or not. I saw someone suggest this somewhere else but didn't find it in issues here.

**Comment by jeddy3** [comment]
Would this be the responsibility of the formatter? [This one](https://github.com/jeddy3/stylelint-formatter-yhw) outputs a success message. You can use the `--custom-formatter` option of the CLI to use it.

**Comment by davidtheclark** [comment]
Silent success is deliberately following the unix philosophy's Rule of Silence: https://en.wikipedia.org/wiki/Unix_philosophy. It is a very common convention among CLIs to output nothing on success.

So, yes, I think that if you want success messages you could use a custom formatter.

Another possibility is that we add a `--verbose` option, and if that's on print a success message. In addition, probably, to a complete list of the files that were checked.

**Comment by corysimmons** [comment]
Why not enable it by default and add a `--silent` option? It'd confuse less newbs like myself.

All in all, I don't particularly care, I was just surprised.

**Comment by davidtheclark** [comment]
Nah, I don't think I'm going to vary from that pattern that is very well established across CLI tools.

But I do think a verbose option would be good, and I'll change this issue title to reflect that enhancement.

**Comment by corysimmons** [comment]
Sounds good, thanks @davidtheclark :+1:

**Comment by davidtheclark** [comment]
Suggestions for verbose reporter:

- List every file linted.
- List number of number of errors found total and for each rule (#659).

Anybody have any other suggestions?

**Comment by jeddy3** [comment]
> Anybody have any other suggestions?

Nope, both those sound good to me.

**Comment by davidtheclark** [comment]
First of all, in working on this I realized that we should have a better output for invalid option warnings. So I built that into the regular string formatter. Then I worked out the verbose output, appending it to the end of the regular output. Here's what I have (I screwed up the config on my large project and ran this, adding ellipses to abbreviate): what do you think?

```
>> Invalid Option: Invalid option value "never-multi-line" for rule "declaration-colon-newline-after"
>> Invalid Option: Invalid option value "always-single-line" for rule "function-comma-newline-after"

src/main/ui/connect/apps/connect-refauth/css/RefAuthPage.css
1:27	Unexpected empty line (max-empty-lines)
3:16	Unexpected whitespace before "{" (block-opening-brace-space-before)

...

src/main/ui/themes/p7777/smartui/p7777-Shell.css
1:21	Unexpected empty line (max-empty-lines)
3:10	Unexpected whitespace before "{" (block-opening-brace-space-before)
7:2	Unexpected empty line (max-empty-lines)
9:18	Unexpected whitespace before "{" (block-opening-brace-space-before)
14:2	Unexpected empty line (max-empty-lines)
16:23	Unexpected whitespace before "{" (block-opening-brace-space-before)
22:2	Unexpected empty line (max-empty-lines)
24:15	Unexpected whitespace before "{" (block-opening-brace-space-before)

550 sources checked

/Users/davidclark/dev/healthtrio-workspaces/smartseries/connect/connect-htcweb/src/main/ui/connect/apps/connect-refauth/css/RefAuthPage.css
/Users/davidclark/dev/healthtrio-workspaces/smartseries/connect/connect-htcweb/src/main/ui/core/apps/core-claimsException/css/CoreClaimsException.css
/Users/davidclark/dev/healthtrio-workspaces/smartseries/connect/connect-htcweb/src/main/ui/core/apps/core-claimsException/css/ExceptionClaimsList.css
...
/Users/davidclark/dev/healthtrio-workspaces/smartseries/connect/connect-htcweb/src/main/ui/themes/p7777/smartui/p7777-Shell.css

5137 problems found

Severity level "error": 2713
- block-opening-brace-space-before: 2267
- at-rule-empty-line-before: 217
- media-query-parentheses-space-inside: 54
- selector-combinator-space-after: 82
- function-comma-space-after: 92
- media-feature-colon-space-after: 1

Severity level "warning": 2424
- max-empty-lines: 2332
- function-comma-space-before: 92

```

**Comment by davidtheclark** [comment]
`>> Invalid Option` is bold and red

`550 sources checked` and `5137 problems found` are bold, cyan, underlined

`Severity level ..." are bold

**Comment by davidtheclark** [comment]
cc/ @s10wen and @bluetidepro because you expressed interest in #659 in more verbose output.

**Comment by jeddy3** [comment]
Looking very good. Thanks for starting this!

I had one suggestion. Would merging the warnings and list of sources be beneficial e.g. 

```shell
src/main/ui/connect/apps/connect-refauth/css/RefAuthPage.css
1:27    Unexpected empty line (max-empty-lines)
3:16    Unexpected whitespace before "{" (block-opening-brace-space-before)

src/main/ui/core/apps/core-claimsException/css/CoreClaimsException.css
 - Passed
src/main/ui/core/apps/core-claimsException/css/ExceptionClaimsList.css
 - Passed

...

src/main/ui/themes/p7777/smartui/p7777-Shell.css
1:21    Unexpected empty line (max-empty-lines)
3:10    Unexpected whitespace before "{" (block-opening-brace-space-before)
7:2 Unexpected empty line (max-empty-lines)
9:18    Unexpected whitespace before "{" (block-opening-brace-space-before)
14:2    Unexpected empty line (max-empty-lines)
16:23   Unexpected whitespace before "{" (block-opening-brace-space-before)
22:2    Unexpected empty line (max-empty-lines)
24:15   Unexpected whitespace before "{" (block-opening-brace-space-before)

550 sources checked

5137 problems found

Severity level "error": 2713
- block-opening-brace-space-before: 2267
- at-rule-empty-line-before: 217
- media-query-parentheses-space-inside: 54
- selector-combinator-space-after: 82
- function-comma-space-after: 92
- media-feature-colon-space-after: 1

Severity level "warning": 2424
- max-empty-lines: 2332
- function-comma-space-before: 92
```

Whether you need the "Passed" label is debatable. Perhaps just colour the passing files in green?

**Comment by davidtheclark** [comment]
Ok will give it a shot.

**Comment by davidtheclark** [comment]
Actually, that's a big pain because then we couldn't just use the string formatter and append to the end of it.

**Comment by davidtheclark** [comment]
I could color files green and red, though, based on whether they passed.

**Comment by jeddy3** [comment]
> I could color files green and red, though, based on whether they passed.

I think that'll be perfect.

**Comment by tdmalone** [comment]
For others coming across this now, `--verbose` was changed to `--formatter verbose` in [7.0.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#700).
