### ISSUE TITLE
Document check of configs in release process

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7045]
Ref: https://github.com/stylelint/stylelint/pull/7044

We have a chicken and egg problem. Our test in this repo will fail if we mark a rule as included in the standard config before releasing it. If we wait until after realising the config then the tests on `main` will fail.

We also have to mark it as included before releasing the config as we use a tarball version of this package for the website.

Any ideas on how to resolve this or do we need to remove this test?

**Comment by ybiquitous** [comment]
Oh, I didn't realize that problem. 😓 

How about skipping the problematic case by default and running it as needed by a temporary manual change? It's not smart, though...

**Comment by jeddy3** [comment]
> How about skipping the problematic case by default and running it as needed by a temporary manual change? 

SGTM.

> We also have to mark it as included before releasing the config as we use a tarball version of this package for the website.

I'll open a PR to document this.
