### ISSUE TITLE
Give property order violation priority over emptyLineBefore in declaration-block-properties-order

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#705]
![image](https://cloud.githubusercontent.com/assets/224636/12878306/63416730-cdf0-11e5-9759-794a369a7c3c.png)

![image](https://cloud.githubusercontent.com/assets/224636/12878310/7152fd48-cdf0-11e5-8570-cc2f0d761a93.png)

![image](https://cloud.githubusercontent.com/assets/224636/12878312/804c5e34-cdf0-11e5-9af1-046f998baba5.png)

![image](https://cloud.githubusercontent.com/assets/224636/12878315/8890d71e-cdf0-11e5-81ee-b30ee60b0ab2.png)

![image](https://cloud.githubusercontent.com/assets/224636/12878318/924c66e2-cdf0-11e5-8be9-b882d9b9d741.png)

4 steps to fix that, versus 2 if property order takes priority. I've noticed a few places where property order taking priority would reduce the number of steps needed to fix something.

**Comment by jeddy3** [comment]
See: https://github.com/stylelint/stylelint/issues/1308
