### ISSUE TITLE
Add support for multiple messages

### ISSUE THREAD

**Issue by clshortfuse** [stylelint/stylelint#7053]
### What is the problem you're trying to solve?

I have two `rule-selector-property-disallowed-list` entries that each need their own different reasonings, justifying a message for each. As of now, all rules much share the same message.

````json
"rule-selector-property-disallowed-list": [
      { 
        "/^(?!:host)[^[]+\\[/": "/^--/",
        "/^(?!:host).+/": "/^overflow/"
      },
      { "message": "Avoid using CSS variables for state since they will traverse down the entire tree"},
      { "message": "Avoid constructing containers on shadowed elements since they will not be exposed to children as their offsetParent"}
    ],
````

### What solution would you like to see?

It would nice is one of these trees were supported:

Option 1:

````json
"rule-selector-property-disallowed-list": [
      { "/^(?!:host)[^[]+\\[/": "/^--/" },
      { "message": "Avoid using CSS variables for state since they will traverse down the entire tree"},
      { "/^(?!:host).+/": "/^overflow/" },
      { "message": "Avoid constructing containers on shadowed elements since they will not be exposed to children their offsetParent"}
    ],
````

Option 2:
````json
    "rule-selector-property-disallowed-list": [
      {
        "/^(?!:host)[^[]+\\[/": "/^--/",
        "/^(?!:host).+/": "/^overflow/"
      },
      {
        "messages": [
          "Avoid using CSS variables for state since they will traverse down the entire tree",
          "Avoid constructing containers on shadowed elements since they will not be exposed to children their offsetParent"
        ]
      }
    ],
````

Option 3:
````json
    "rule-selector-property-disallowed-list": [
      {
        "/^(?!:host)[^[]+\\[/": "/^--/",
        "/^(?!:host).+/": "/^overflow/"
      },
      { "message": "Avoid using CSS variables for state since they will traverse down the entire tree" },
      { "message": "Avoid constructing containers on shadowed elements since they will not be exposed to children their offsetParent" }
    ],
````

I believe Option 3 is the most backwards compatible. Basically, something like

````js
const messages = ruleArray.filter((entry) => 'message' in entry)
function getMessageForRule(ruleIndex) {
  return messages[Math.min(ruleIndex, messages.length - 1)].message;
}
````

It'll repeat the last message if the author has only scripted one message, which is how it already works.

**Comment by ybiquitous** [comment]
@clshortfuse Thanks for using the template. How about using the existing feature [`message` function](https://stylelint.io/user-guide/configure/#message) if you can switch to a JS config file?

```js
module.exports = {
  rules: {
    "rule-selector-property-disallowed-list": [
      {
        "a": ["color", "/margin/"],
        "/foo/": "/size/"
      },
      {
        message: (selector, prop) => {
          // your custom logic
          return `...`;
        }
      }
    ]
  }
};
```


For example, see this [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLpANhAE7wpExQDcWuAtkkQOYCWmAtDhAA6kAMXAD2qYAvlhAAaEADNm+GADkktOIhgDlXeQDowAZz2TwETLMYIQtaAFcd6rsRx6UAXjRYUZWzD2kMmT090ECJvNj0YeTBOIjYuIm4YIhwATzYoZj0kfEIAdwo2fEycYNIAbQ9Az38qquCkUpQKgNq640IiYIlK1qCQAHp6JlZ+4J7agF1ultbg-ukICFGEFDm9ZgAvGGXxzxFp1prelQMkRhhSAAoIqJiJFHjuAEpXAD53Gd7+-pQUiGsiCgwNY9JxaChCCwwLtauQcACAgADbQoxHCXooMSfPbjCaVLEiYRGSCmZiMABixHoOAsACtDFJYFxDIgjsFQSl5EVMCUVsF8EgcD5eVgRCAREA).

**Comment by clshortfuse** [comment]
@ybiquitous Yes, that should work, though I was hoping for a way to do it over JSON.

I took a look at the source and was thinking of this tweak:

````js
type RuleMessage = string | Record<string, string> | RuleMessageFunc;
````

and rewriting [function buildWarningMessage(message, messageArgs) { ](https://github.com/stylelint/stylelint/blob/c1aefb4d5c3c15d035a658a8e6f53be2fd5de283/lib/utils/report.js#L127) as

````js
function buildWarningMessage(message, messageArgs) {
	const args = messageArgs || [];

	if (typeof message === 'string') {
		return printfLike(message, ...args);
	}

	if (typeof message === 'function') {
		return message(...args);
	}

	const [arg0] = args;
	const entries = Object.entries(message);
	let entry = entries.find(([key]) => key === arg0) ?? entries[0];
	
	return printfLike(entry[1], ...args)
}
````

The JSON would be: 
````json
"rule-selector-property-disallowed-list": [
  {
    "/^(?!:host)[^[]+\\[/": "/^--/",
    "/^(?!:host).+/": "/^overflow/"
  },
  {
    "message": {
      "/^(?!:host)[^[]+\\[/": "Avoid using CSS variables for state since they will traverse down the entire tree",
      "/^(?!:host).+/": "Avoid constructing containers on shadowed elements since they will not be exposed to children as their offsetParent"
    }
  }
],
````

This would likely work for `rule-selector-property-disallowed-list` since `messageArgs` has the selector itself as arg0, but YMMV for other rules.

**Comment by ybiquitous** [comment]
@clshortfuse Yes, your request seems to be satisfied by adding a logic to `buildWarningMessage()`, but I want to know why you stick to JSON, not JS.

I'm worried the requested feature makes our code and people's usage more complex than needed.

**Comment by jeddy3** [comment]
Closing as the existing `message` feature points towards a possible [flat config future](https://github.com/stylelint/stylelint/issues/7408).
