### ISSUE TITLE
min-device-pixel-ratio getting caught by media-feature-name-no-vendor-prefix

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#706]
![image](https://cloud.githubusercontent.com/assets/224636/12878455/3e084c74-cdf3-11e5-846d-d3fba0484d93.png)

There's not a vendor prefix on it.

**Comment by davidtheclark** [comment]
I believe there is no `min-device-pixel-ratio`, and you should be using `min-resolution`, which autoprefixer converts to all the vendor prefixed `min-device-pixel-ratio`s. cf: https://github.com/postcss/autoprefixer/issues/122

**Comment by corysimmons** [comment]
Ah very cool, thanks

**Comment by jitendravyas** [comment]
Do you mean 	
`screen and (min-device-pixel-ratio: 2),` 
should be
 `screen and (min-resolution: 2),` ?
