### ISSUE TITLE
Document how to write plugins using TypeScript

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7072]
### Describe the documentation issue

I'd like to know how to write and publish plugins using TypeScript.

It seems worthwhile, especially as we:

- publish our types, which can be consumed by plugin authors
- are moving to ESM, which may change how plugins are authored

Ref: https://github.com/stylelint/stylelint/issues/7017#issuecomment-1628823202

### What solution would you like to see?

Improvements to our [writing plugins](https://stylelint.io/developer-guide/rules) documentation, perhaps as a new section,

**Comment by jeddy3** [comment]
I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if anyone has time.

**Comment by ybiquitous** [comment]
@0scvr Yes. There are very few changes, even on the `v16` branch.

```shell
git diff main...v16 -- docs/developer-guide/rules.md
```

```diff
diff --git a/docs/developer-guide/rules.md b/docs/developer-guide/rules.md
index 33297b25b..ff33bb27d 100644
--- a/docs/developer-guide/rules.md
+++ b/docs/developer-guide/rules.md
@@ -258,7 +258,7 @@ Look at the READMEs of other rules to glean more conventional patterns.
 
 The final step is to add references to the new rule in the following places:
 
-- [The rules `index.js` file](../../lib/rules/index.js)
+- [The rules `index.mjs` file](../../lib/rules/index.mjs)
 - [The list of rules](../user-guide/rules.md)
 
 ## Add an option to a rule
```
