### ISSUE TITLE
Add tests with at-rule nesting to block-closing-brace-*

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#71]
I realize that I forgot about those when writing the tests.

**Comment by davidtheclark** [comment]
I realize a problem here ...

Let's say we're testing `block-closing-brace-space`. Because of the possibility of nesting you can run into contradictions.

If the options are `{ before: "never", after: "always" }`, those requirements will conflict when there's a rule inside a media query, e.g. `@media print { a { color: pink; } }`. The rule's `after` will conflict with the at-rule's `before`; nothing will be acceptable.

Right now the only fix I can think of that still enforces *something* (as opposed to just ignoring that situation) would be to make one style of enforcement trump the other. I was thinking "always" could trump "never".  If that were the case, with those same options the following would pass: `@media print { a { color: pink;} }`.

Thoughts?

**Comment by davidtheclark** [comment]
I guess another possibility would be to ignore `after` enforcement for a nested rule and instead let the spacing be enforced by the parent's `before` enforcement ...

In that case, `@media print { a { color: pink;} }` would be an error because the last closing brace should never have a space before. We'd expect `@media print { a { color: pink;}}`

**Comment by MoOx** [comment]
There is not only media queries. We should consider any children. We can have `@page` or even futur nesting ! http://tabatkins.github.io/specs/css-nesting/

**Comment by davidtheclark** [comment]
Yeah, changed the name to at-rules generally.

**Comment by MoOx** [comment]
(It's even more than at rules but I get it)

**Comment by davidtheclark** [comment]
But for now we can only test at-rules, right? Or should we test using `postcss-nested` also?

**Comment by MoOx** [comment]
> Or should we test using postcss-nested also?

Noooo https://github.com/cssnext/cssnext/issues/80#issuecomment-96497760

:D

**Comment by davidtheclark** [comment]
> another possibility would be to ignore after enforcement for a nested rule

Do @stylelint/owners think this would be the right approach?

**Comment by MoOx** [comment]
No sure what you mean. Can you try to explain me in another way ?

**Comment by davidtheclark** [comment]
Ok, so problem is this: If the options are `{ before: "never", after: "always" }`, those requirements will conflict when there's a rule inside a media query, e.g. `@media print { a { color: pink; } }`. See how the rule's `"after"` expectation (to have a space) will conflict with the at-rule's `"before"` expectation (not to have a space). Because of this conflict, nothing would work. 

- `@media print { a { color: pink;}}` would error because of `after: "always"`
- `@media print { a { color: pink;} }` would error because of `before: "never"`

This problem will only arise, though, when we have two successive closing braces like that, `} }`. So I'm wondering if the way out would be to *ignore the "after" expectation if the next non-whitespace character is `}`* (meaning the the block is the last nested block within a larger block). If we did that, `@media print { a { color: pink;}}` *would* work because the "after" rule that would have complained is being ignored.

It's kind of convoluted, I know ... but does that help?

**Comment by MoOx** [comment]
> So I'm wondering if the way out would be to ignore the "after" expectation if the next non-whitespace character is }

Make sense, I can't see any other solution.

**Comment by jeddy3** [comment]
Well explained. 

I also agree we should go with ignore the "after" expectation for now.

Perhaps, later down the line and only if needed, there's scope for a "nested" variant (or option) e.g. "always-single", "always-nested".

**Comment by davidtheclark** [comment]
Luckily, it looks like the current code already does this :)

I will just add some tests.
