### ISSUE TITLE
color-named

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#710]
Like `#fff` would throw a warning that it should be converted to `white`. I prefer named colors because they're more explicit.

**Comment by davidtheclark** [comment]
Sgtm. Maybe `color-prefer-named`? @jeddy3, what do you think?

**Comment by jeddy3** [comment]
> Maybe `color-prefer-named`

This would be the first rule, that's not a `-no-` one, to take a boolean primary option. This got my thinking.

Perhaps we should combine this functionality with `color-no-named`, to bring it inline with all the other rules that use explicit options e.g. `font-family-name-quotes` and `color-hex-length`, and have the singular `"color-named": "never"|"always-where-possible"`?

@davidtheclark What do you think?

> I prefer named colors because they're more explicit.

There are [quite a few](https://drafts.csswg.org/css-color-4/#named-colors) named colours and I think we'll need check for the different representations of those colors. I suggest (pre)calculating the `hex`, `rgb()`, `rgba()` `hsl()`, `hsla()`, `hwb()` [3 and 4 arguments], `device-cmyk()` and, if applicable, `gray()` representations for each of the named colours. Does that sound about right?

This could be a good rule to cut your stylelint teeth on @corysimmons :) You can repurpose a lot from [color-no-named](https://github.com/stylelint/stylelint/blob/master/src/rules/color-no-named/index.js) and [function-blacklist](https://github.com/stylelint/stylelint/blob/master/src/rules/function-blacklist/index.js) to get it done, and [color](https://www.npmjs.com/package/color) will help you calculate the various representations of the named colours.

**Comment by davidtheclark** [comment]
@jeddy3: Yeah, agreed. It makes more sense to create a `color-named` (or `color-keyword`?) rule.

**Comment by jeddy3** [comment]
Lets go with `color-named` over `color-keyword` as it matches the _type_ [in the spec](https://drafts.csswg.org/css-color-4/#named-colors).

How does all this sound to you @corysimmons, something you'd like to contribute?

**Comment by corysimmons** [comment]
Sounds good. I suck at JS or I would. I'm just here to pester you smart people into doing stuff.

**Comment by ntwb** [comment]
I've just [created an upstream](https://github.com/dustinspecker/is-css-color-name/issues/28) for `is-css-color-name` issue to potentially switch the color-name library, the change if it was to be accepted would change the number of named colors from ~150 to ~2300.

**Comment by jeddy3** [comment]
I'm not sure the colours listed in `color-name` are actual color idents. Chrome doesn't seem to recognise the few I tried. Doesn't the [spec you reference](https://drafts.csswg.org/css-color-4/#valdef-color-green) in the upstream issue contain the list of valid color idents?

**Comment by davidtheclark** [comment]
The spec you reference does have a list of color names and it only has 148. So it seems like that's actually the more accurate number, right?

**Comment by jeddy3** [comment]
> So it seems like that's actually the more accurate number, right?

I think so.

**Comment by ntwb** [comment]
Right, I've dug around some more and indeed only those 148 named colors are in the spec :smirk:
