### ISSUE TITLE
Possible to set a parser in config?

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint#713]
I was experiencing a problem with `@include my_mixin();` being interpreted as an at-rule and needing a newline above it. I don't think `@include` is technically an at rule.

Is there a way to set SCSS as the parser or something via config? Didn't find anything in docs but I know you can do it via the CLI.

**Comment by davidtheclark** [comment]
`@include` is an at-rule, so any rules you apply to at-rules will apply to it.

If what you mean is that you want to compile SCSS before stylelint runs, you just need to do that in your build. If you want stylelint to parse SCSS, there are options for that in the CLI and the Node API, and if you use it as a PostCSS plugin just set the parser via your PostCSS runner.

**Comment by corysimmons** [comment]
Okay I see what you're saying, but maybe being able to set some sort of per-project config for it is a good idea?

**Comment by davidtheclark** [comment]
This would seem fine to me for CLI and Node users; but what about users you include stylelint as a PostCSS plugin along with others? In that situation, stylelint doesn't get to pick its parser.

**Comment by corysimmons** [comment]
Without a config option for it, it will always be an error in editors (which is exactly my problem and it's making my .scss look goofy).

![image](https://cloud.githubusercontent.com/assets/224636/12920818/335f87e4-cf18-11e5-89c9-2f37b6c148b2.png)

This is a problem even with larger rulesets. This `@include` should not be considered an @ rule and if we have the ability to ignore it via the CLI with the syntax option, why not add that ability into the config so we don't end up with stuff like this:

```scss
.foo {

  @include button(red);
  background: rgba(red, .75);
  font-family: sans-serif;
  color: blue;
}
```

**Comment by davidtheclark** [comment]
> This @include should not be considered an @ rule and if we have the ability to ignore it via the CLI with the syntax option

You do not have the ability to ignore it with the syntax option. It is still treated as an at-rule. 

Are you sure one of the options for `at-rule-empty-line-before` won't do what you want? https://github.com/stylelint/stylelint/tree/master/src/rules/at-rule-empty-line-before#optional-options

**Comment by corysimmons** [comment]
I'll have another look over them.
