### ISSUE TITLE
New repo for Sass specific linting rules?

### ISSUE THREAD

**Issue by kristerkari** [stylelint/stylelint#716]
I have some ideas for new rules that would lint against Sass syntax. I can see that stylelint's primary job is to lint CSS, but many of the rules support SCSS too.

Would it make sense to create a new repo that would only contain rules for Sass syntax as stylelint plugins?

**Comment by davidtheclark** [comment]
Yes, @kristerkari, I think it would be a great idea to accumulate a bunch of plugin rules that target Sass specifically.

**Comment by jeddy3** [comment]
I also think it's a great idea :)

**Comment by kristerkari** [comment]
I think that it might be easier to start with a single repo and then later see if it makes sense to create multiple repos or not.

**Comment by jeddy3** [comment]
Sounds good to me :)

Once you've got something up and running, feel free to fire over a PR with a link to the repo on the [plugins page](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/plugins.md) of the docs.

**Comment by kristerkari** [comment]
Yeah I will, but it might be that I don't have time for that before weekend, because I was planning on doing some bugfixes to CSSfmt.

**Comment by kristerkari** [comment]
I created a new repo called [stylelint-scss](https://github.com/kristerkari/stylelint-scss). I chose that name because it was short and descriptive, but let me know if you have other plans for that name :)

There isn't anything ready yet, but I started writing down some rule ideas (only 2 now, but more coming). It would be nice to get some feedback about them and also new ideas for rules.  

I'm probably going to collect a few more rules before starting to code anything.

**Comment by jeddy3** [comment]
> I created a new repo called stylelint-scss.

Sounds great to me!

**Comment by davidtheclark** [comment]
Since this repo has been created should we close the issue?

**Comment by jeddy3** [comment]
Yes please.
