### ISSUE TITLE
`at-rule-empty-line-before` interferes with prettier

### ISSUE THREAD

**Issue by alexthemark** [stylelint/stylelint#7161]
### What minimal example or steps are needed to reproduce the bug?

```scss
.header {
    @include at-media('600px') {
      color: red 
    }
}
```
in a `.scss` file

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": ["stylelint-config-standard-scss"]
}
```

### How did you run Stylelint?

`npx stylelint src/**/*.scss`

### Which Stylelint-related dependencies are you using?

"stylelint-config-standard-scss"@10.0.0

### What did you expect to happen?

I expected prettier and stylelint with the standard `scss` config to work together without additional configuration.

### What actually happened?

Prettier would remove the space prior to the at-rule, then stylelint would want to add it back. I resolved my issue by disabling `at-rule-empty-line-before`, but I would have expected prettier to disable that rule with stylelint 15 -- which is supposed to work with prettier. 

This had been discussed in https://github.com/stylelint/stylelint/issues/6619#issuecomment-1444075732 (the suggestion was to break it into a separate issue but I don't think that happened -- so here it is). 

Additionally, the rule was previously disabled by the (now deprecated due to stylelint 15) stylelint-config-prettier config at https://github.com/prettier/stylelint-config-prettier/blob/master/src/index.js#L8

### Do you have a proposal to fix the bug?

I propose deprecating the rule similar to other styling rules and removing the rule with stylelint 16. I'd also propose not including it in the [config-standard](https://github.com/stylelint/stylelint-config-standard/blob/main/index.js#L18C3-L18C3) since it interferes with prettier + scss.

**Comment by ybiquitous** [comment]
@alexthemark Thanks for opening the issue by using the template.

> Prettier would remove the space prior to the at-rule, then stylelint would want to add it back.

[at-rule-empty-line-before](https://stylelint.io/user-guide/rules/at-rule-empty-line-before) is  related to *empty lines* before at-rules, not *whitespaces*. I checked your code, but it seems Prettier and Stylelint work well together.

Here's my code:

`package.json`:

```json
{
  "dependencies": {
    "prettier": "^3.0.2",
    "stylelint": "^15.10.3",
    "stylelint-config-standard-scss": "^10.0.0"
  },
  "stylelint": {
    "extends": [
      "stylelint-config-standard-scss"
    ]
  }
}
```

Prettier fixes your SCSS code like this:

```diff
--- a/test.scss
+++ b/test.scss
@@ -1,5 +1,5 @@
 .header {
-    @include at-media('600px') {
-      color: red
-    }
+  @include at-media("600px") {
+    color: red;
+  }
 }
```

Then run Stylelint and Prettier. Both exit normally:

```console
$ npx stylelint *.scss

$ npx prettier *.scss --check
Checking formatting...
All matched files use Prettier code style!
```

What I miss something?

**Comment by alexthemark** [comment]
My apologies -- I pasted an incomplete example and made an error! so sorry. 

Here's the more full example (I hadn't realized that it was actually my second selector making the error)
```
.header {
  @include at-media("600px") {
    color: red;
  }
  @include at-media("900px") {
    color: blue;
  }
}
```

errors as expected: 
```
src/test.module.scss
 5:3  ✖  Expected empty line before at-rule  at-rule-empty-line-before`
```
And if I then go add an empty line at line 5, prettier preserves that empty line and the `stylelint` error goes away. 

I don't think there's a conflict, so I'm happy to close out (and hopefully the next person who comes across that comment in #6619 can learn from my mistakes.
