### ISSUE TITLE
It doesnt work for me

### ISSUE THREAD

**Issue by vladimirov-s** [stylelint/stylelint#7168]
### What minimal example or steps are needed to reproduce the bug?

style.sass:
```
@font-face {
  font-family: 'roboto';
  src: url('../../assets/fonts/Roboto-Thin.ttf');
}
```
or 
```
$SecondShadow: 0 0 3px 1px #33333366;
```
sass autocompiller reports about some problem. Your extension must recognize and fix it. Why it doesnt work??

### What minimal configuration is needed to reproduce the bug?

by default- nothing

### How did you run Stylelint?

press key ctrl+s

### Which Stylelint-related dependencies are you using?

eslint

### What did you expect to happen?

Problem must recognise

### What actually happened?

Recognised nothing. Even if I try so:
```
@font-face {
  font-family: 'roboto';
  src: url('../../assets/fonts/Roboto-Thin.ttf');
}}}
```

**Comment by ybiquitous** [comment]
@vladimirov-s Can you provide a minimal reproduction, for example, by using a [demo](https://stylelint.io/demo/)?

**Comment by Mouvedia** [comment]
After more than a month without any responses to @ybiquitous's inquiry, I am closing this issue.
