### ISSUE TITLE
Error with imbricated media query

### ISSUE THREAD

**Issue by georges-g** [stylelint/stylelint#7169]
### What minimal example or steps are needed to reproduce the bug?

```sass
.text-page
    margin: 4rem auto

    @media(max-width: 40rem)
        margin: 2rem auto
```

### What minimal configuration is needed to reproduce the bug?

```json
{
    "extends": "stylelint-config-standard",
    "customSyntax": "postcss-sass"
}
```

### How did you run Stylelint?

```shell
npx stylelint -f verbose "**/*.sass"
```

### Which Stylelint-related dependencies are you using?

```json
{
    "postcss-sass": "0.5.0",
    "stylelint": "15.10.3",
    "stylelint-config-standard": "34.0.0"
}
```

### What did you expect to happen?

No problem to be reported

### What actually happened?

The following error happened:
```
Error: The node source must be present
    at Object.getContext (/home/georges/data/tmp/dev/stylelint-bug/node_modules/stylelint/lib/utils/nodeContextLookup.js:23:28)
    at /home/georges/data/tmp/dev/stylelint-bug/node_modules/stylelint/lib/rules/no-descending-specificity/index.js:73:52
    at /home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:379:18
    at /home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:307:18
    at Rule.each (/home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:53:16)
    at Rule.walk (/home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:304:17)
    at /home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:312:24
    at Root.each (/home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:53:16)
    at Root.walk (/home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:304:17)
    at Root.walkRules (/home/georges/data/tmp/dev/stylelint-bug/node_modules/postcss/lib/container.js:377:19)
```

### Do you have a proposal to fix the bug?

Not sure if it is a stylelint issue or a postcss-sass issue

**Comment by ybiquitous** [comment]
@georges-g Thanks for the report with the reproduction info. I confirmed the reproduction with the [minimal demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AXGAPFBaADgQwHMYAdAOwAJLyBbPAJwIEtT5yAWOma8vAVxQhkyVcgAFqMKIzwAKWuiwB3RlBQALVmwAMnagEphIqrQbNWAJl09+EEABoQAM0YAbGADk8EhCAxecbkgAznhBQfbgEKTOBD7AhsTgvEEC1ADKAJ6kKHjoiayJOBApYGFYIWGJdgkgdLxuQfnk8RRUiaQQWLBBYDCkUqQE5TgwYIzOYygZTSh1JK0AvmQLEZDRjAQAYhB0tCg+AFZBURGwOOGILZSFxSilQeWhjQjkiVpIAKxIWlU1KRluFzMFBNRIARi+YPeAGZEssQAsgA).

The location where the error occurs:

https://github.com/stylelint/stylelint/blob/0b686f289ab436eac64aaa78eb1646d38a153294/lib/utils/nodeContextLookup.js#L23

> Not sure if it is a stylelint issue or a postcss-sass issue

I guess this is a `postcss-sass` issue because the AST is invalid. Unfortunately, the [AleshaOleg/postcss-sass](https://github.com/AleshaOleg/postcss-sass) repo seems to be unmaintained, so this error won't likely resolved.

If possible, I recommend switching to `postcss-scss` that is officially maintained by the PostCSS org (https://github.com/postcss/postcss-scss).

**Comment by georges-g** [comment]
Thanks for the reply @ybiquitous.

I would rather stick to sass for the moment and unfortunately disable stylelint.

When you are 100% sure it comes from postcss-sass, would you be OK with posting an issue there? Who knows, the contributors there might wake up.

**Comment by ybiquitous** [comment]
Please see the following experiment: ⬇️ 

```console
> require('postcss-sass').parse('@media(max-width: 40rem)\n  color: red').nodes[0].source
undefined
> require('postcss-scss').parse('@media(max-width: 40rem) { color: red }').nodes[0].source
{
  input: Input {
    css: '@media(max-width: 40rem) { color: red }',
    hasBOM: false,
    id: '<input css FGAgvV>',
    [Symbol(fromOffsetCache)]: [ 0 ]
  },
  start: { column: 1, line: 1, offset: 0 },
  end: { column: 39, line: 1, offset: 38 }
}
```

`postcss-sass` fails to set the `source` property when parsing `@media`, while `postcss-scss` succeeds in it. So I'm 100% sure that this is a bug of `postcss-sass`.

> would you be OK with posting an issue there? 

I'm sorry, but I'm not strongly interested in the `sass` syntax (non-standard), and I have no time. Can you file an issue by yourself, please? If no reaction in `postcss-sass`, you might need some fork of `postcss-sass`.

**Comment by georges-g** [comment]
Alright, I just opened [an issue there](https://github.com/AleshaOleg/postcss-sass/issues/179).

I also noticed there is a another postcss-sass plugin: [csstools/postcss-sass](https://github.com/csstools/postcss-sass). Is there a way to make it work with stylelint?

I tried this configuration:
```
    "customSyntax": "@csstools/postcss-sass",
    "overrides": [
        {
            "files": ["*.sass"],
            "customSyntax": "@csstools/postcss-sass"
        }
    ],
```

But it doesn't work:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at MapGenerator.clearAnnotation (/home/georges/dev/cdm/main-front/node_modules/postcss/lib/map-generator.js:65:36)
```

**Comment by ybiquitous** [comment]
I'm unsure about `@csstools/postcss-sass`, but the cause seems that `@csstools/postcss-sass` doesn't have the `parse()` function:

```console
> require('@csstools/postcss-sass').parse
undefined
```

Also, `@csstools/postcss-sass` seems unmaintained.

**Comment by georges-g** [comment]
OK, I will close this issue then and keep the issue in postcss-sass open.
I might work on postcss-sass if I have some time in the future.

Thanks for the discussion @ybiquitous.
