### ISSUE TITLE
Ways for maintainers to communicate with each other (re: expiring 1Password)

### ISSUE THREAD

**Issue by mattxwang** [stylelint/stylelint#7174]
Now that GitHub's team discussions have been sunsetted, what is the correct way for us to get in touch with each other (preferably somewhat privately)? 

(for context, we just got an email that our internal 1Password trial is about to expire. I'm happy to do whatever work we'd like -- either getting a new PW manager, reaching out to them to see if we can get a free plan, or using our sponsor money -- but want to get others' opinion and make sure I understand the context)

**Comment by ybiquitous** [comment]
@mattxwang Unfortunately, it seems we cannot make a discussion private, so we should find an alternative. 😢 
https://github.com/orgs/community/discussions/2829

Also, I didn't realize 1Password expiration. Does anyone know about it? @stylelint/owners

**Comment by mattxwang** [comment]
Gotcha - I'll keep to only publicly available info for now!

I'm not sure what the past precedent has been for using OpenCollective/GitHub Sponsors money has been (it seems like [mostly for domain renewals](https://opencollective.com/stylelint#category-BUDGET)), but I think this would be a reasonable use-case since it enables secure development? The [Teams Starter Pack](https://1password.com/business-pricing) for 1Password is $20/mo for 10 users, which fits well within the monthly contributions we get from various sponsors (ex Sentry). The per-user pricing for business is $8/user/mo, which is quite a bit higher but not unreasonable (ex with 11 owners, that would be $88/mo -> 1056/yr - a bit under how much we get from one OpenCollective "Sponsor" tier).

If we did want something cheaper, [Bitwarden](https://bitwarden.com/pricing/business/) is one option I've heard of that's $3/mo/user.

That being said, I'm a relatively new maintainer, so don't want to buck the trend in terms of how project funding is used - I don't have a strong opinion either way!

**Comment by m-allanson** [comment]
Looking at https://github.com/1Password/1password-teams-open-source it says the following:

> Your membership does not expire. If you signed up before November 26, 2021, please contact [opensource@1password.com](mailto:opensource@1password.com) to convert your two-year membership into one that doesn't need to be renewed.

@mattxwang if you’re happy to contact them, that should hopefully be enough to resolve the 1Password issue.

**Comment by mattxwang** [comment]
Ah! So sorry, I must have missed that. I'll shoot them an email now, thanks @m-allanson!

**Comment by mattxwang** [comment]
Okay, 1Password has gotten back to us and provided a free indefinite account (thanks 1Password!). Since the immediate issue is cleared, I'll close this issue; however, I do wonder if we'll need other private communication methods in the future.

**Comment by ybiquitous** [comment]
@mattxwang Thanks for your work! It's valuable to keep this open until we find a private communication way.

**Comment by ybiquitous** [comment]
How about Discord? The ESLint team seems to use it: https://eslint.org/chat

**Comment by hudochenkov** [comment]
I think we could explore Organization Discussion.

[Announcement blog post](https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/)
[Docs](https://docs.github.com/en/organizations/managing-organization-settings/enabling-or-disabling-github-discussions-for-an-organization)

If I understood correctly we could create a **private** repo, and have discussions enabled there. Whoever have **write** access to that repo, could see discussions. Node.js team [went this way](https://github.com/nodejs/TSC/issues/1340). But we need to really test this out, if we could setup it up private for owners only.

**Comment by ybiquitous** [comment]
Looks good. I'll try to create a repo.

**Comment by ybiquitous** [comment]
Created: https://github.com/stylelint/owners/discussions

**Comment by ybiquitous** [comment]
I guess the stylelint org members can access the repo 🤔 
<img width="274" alt="image" src="https://github.com/stylelint/stylelint/assets/473530/148af613-d40d-4250-8fb1-f856dc69c985">

**Comment by hudochenkov** [comment]
Yeah, this confuses me too.

> **Only those with access** to this repository can view it.
> **All 110 members can access** this repository.
> **0 teams or members have access** to this repository. Only [Owners](https://github.com/orgs/stylelint/people?query=role%3Aowner) can contribute to this repository.

<img width="790" alt="CleanShot 2023-09-13 at 01 18 59" src="https://github.com/stylelint/stylelint/assets/654597/9f557caa-5d9a-4d91-8de5-1e0eebf447f9">

How can we verify that only Owners could see https://github.com/stylelint/owners/discussions?

**Comment by hudochenkov** [comment]
I guess we have to change Organization [Base permissions](https://github.com/organizations/stylelint/settings/member_privileges) from “Write” to “No permission”, then go to each public repository and add all teams with “Write” permissions. Quite a hustle to manage this. Luckily we have only three teams. And “Owners” team might not need any additional permission, since the permission level of people inside it.

<img width="981" alt="CleanShot 2023-09-13 at 01 29 30" src="https://github.com/stylelint/stylelint/assets/654597/dc667389-9841-41a4-9086-d70747d3bbdd">

**Comment by ybiquitous** [comment]
Thanks for the investigation. Let's try changing "Base permissions". Then, to verify members cannot access stylelint/owners, could you temporarily change my role to Member? @hudochenkov

**Comment by ybiquitous** [comment]
I've updated "Base permissions" to "No permission". I'll double check each repo's settings.

**Comment by ybiquitous** [comment]
Updating settings is done. No big changes since we owners can access any repositories without extra settings.

**Comment by hudochenkov** [comment]
@ybiquitous I've temporary changed your role to Member and removed from Owners team. Could you check if you have access to https://github.com/stylelint/owners/discussions and https://github.com/stylelint/owners/discussions/1

**Comment by ybiquitous** [comment]
@hudochenkov Thanks. I cannot access either 👍🏼

**Comment by hudochenkov** [comment]
@ybiquitous thank you for verifying. I've reverted all your role and added back to Owners team.

I guess we found our solution for discussion. We probably need to tag `@stylelint/owners` in each discussion there to have people notified because not everyone could be watching the repo.

**Comment by ybiquitous** [comment]
Thank you so much! I've updated https://github.com/stylelint/owners#readme to add your idea. 👍🏼
