### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by arantebw** [stylelint/stylelint#7185]
### What minimal example or steps are needed to reproduce the bug?

```bash
yarn lint
```

### What minimal configuration is needed to reproduce the bug?

Using:
- yarn 1.22.19
- node 18.16.0

### How did you run Stylelint?

```json
    "lint": "yarn prettier --check && yarn eslint && yarn stylelint && yarn markdownlint",
```

### Which Stylelint-related dependencies are you using?

```json
    "stylelint": "^15.10.3",
```

### What did you expect to happen?

Lint won't return a runtime error.

### What actually happened?

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/user1/Projects/project1/node_modules/string-width/index.js from /Users/user1/Projects/project1/node_modules/stylelint/lib/formatters/stringFormatter.js not supported.
Instead change the require of index.js in /Users/user1/Projects/project1/node_modules/stylelint/lib/formatters/stringFormatter.js to a dynamic import() which is available in all CommonJS modules.
```

### Do you have a proposal to fix the bug?

Upgrade `string-width` to its latest version.

Currently used by `stylelint`:
![Screenshot 2023-09-14 at 14 13 26](https://github.com/stylelint/stylelint/assets/8081121/fd24aeaa-d146-4e7c-bbdb-f397a650a105)

Latest version available:
<img width="87" alt="Screenshot 2023-09-14 at 14 13 52" src="https://github.com/stylelint/stylelint/assets/8081121/b6d24c28-b7b6-41a9-b324-8bba8b12324e">

**Comment by ybiquitous** [comment]
@arantebw Thanks for opening the issue using the template. I'm afraid that Stylelint v15 doesn't support ESM yet, so `stylelint@15.10.3` needs to use older versions of `string-width`. See also the dependencies restriction below: 

```console
$ npm v stylelint@15.10.3 'dependencies.string-width'
^4.2.3
```

But we are moving to ESM (#5291) and will support ESM in the next major version (v16.0.0).

**Comment by arantebw** [comment]
I appreciate the reply and the info. Thanks! 🙏🏼
