### ISSUE TITLE
 ✖ stylelint --fix [SIGSEGV]  ✖ stylelint --fix failed without output (SIGSEGV).

### ISSUE THREAD

**Issue by yuzihan30** [stylelint/stylelint#7186]
### What minimal example or steps are needed to reproduce the bug?

How to solve this stylelint error, no error detail, I cant fix this bug

git commit -m "feat: 测试styleLint" 

> investbank-web@0.1.4 lint:lint-staged
> lint-staged

✔ Preparing lint-staged...
❯ Running tasks for staged files...
  ❯ package.json — 5 files
    ✔ *.{js,jsx,ts,tsx} — 1 file
    ↓ {!(package)*.json,*.code-snippets,.!(browserslist)*rc} — no files [SKIPPED]
    ↓ package.json — no files [SKIPPED]
    ❯ *.vue — 3 files
      ✔ eslint --fix
      ✔ prettier --write
      ✖ stylelint --fix [SIGSEGV]
    ↓ *.{scss,less,styl,html} — no files [SKIPPED]
    ↓ *.md — no files [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ stylelint --fix failed without output (SIGSEGV).
husky - pre-commit hook exited with code 1 (error)

### What minimal configuration is needed to reproduce the bug?

module.exports = {
  root: true,
  plugins: ['stylelint-order'],
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  customSyntax: 'postcss-html',
  rules: {
    'function-no-unknown': null,
    'selector-class-pattern': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global'],
      },
    ],
    'selector-pseudo-element-no-unknown': [
      true,
      {
        ignorePseudoElements: ['v-deep'],
      },
    ],
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['tailwind', 'apply', 'variants', 'responsive', 'screen', 'function', 'if', 'each', 'include', 'mixin'],
      },
    ],
    'no-empty-source': null,
    'string-quotes': null,
    'named-grid-areas-no-invalid': null,
    'unicode-bom': 'never',
    'no-descending-specificity': null,
    'font-family-no-missing-generic-family-keyword': null,
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    // 'declaration-block-trailing-semicolon': 'always',
    'rule-empty-line-before': [
      'always',
      {
        ignore: ['after-comment', 'first-nested'],
      },
    ],
    'unit-no-unknown': [true, { ignoreUnits: ['rpx'] }],
    'order/order': [
      [
        'dollar-variables',
        'custom-properties',
        'at-rules',
        'declarations',
        {
          type: 'at-rule',
          name: 'supports',
        },
        {
          type: 'at-rule',
          name: 'media',
        },
        'rules',
      ],
      { severity: 'warning' },
    ],
  },
  ignoreFiles: ['**/*.js', '**/*.jsx', '**/*.tsx', '**/*.ts'],
  overrides: [
    {
      files: ['*.vue', '**/*.vue', '*.html', '**/*.html'],
      extends: ['stylelint-config-recommended'],
      rules: {
        'keyframes-name-pattern': null,
        'selector-pseudo-class-no-unknown': [
          true,
          {
            ignorePseudoClasses: ['deep', 'global'],
          },
        ],
        'selector-pseudo-element-no-unknown': [
          true,
          {
            ignorePseudoElements: ['v-deep', 'v-global', 'v-slotted'],
          },
        ],
      },
    },
    {
      files: ['*.less', '**/*.less'],
      customSyntax: 'postcss-less',
      extends: ['stylelint-config-standard', 'stylelint-config-recommended-vue'],
    },
  ],
};

### How did you run Stylelint?

    "lint:stylelint": "stylelint --cache --fix \"**/*.{vue,less,postcss,css,scss}\" --cache --cache-location node_modules/.cache/stylelint/",

### Which Stylelint-related dependencies are you using?

    "stylelint": "^15.4.0",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-recommended": "^11.0.0",
    "stylelint-config-recommended-vue": "^1.4.0",
    "stylelint-config-standard": "^32.0.0",
    "stylelint-order": "^6.0.3",

### What did you expect to happen?

stylelint error with detail

### What actually happened?

stylelint error without detail

**Comment by ybiquitous** [comment]
@yuzihan30 Thanks for the report by using the template. Can you provide a minimal reproducible repository for our deeper investigation?

**Comment by Mouvedia** [comment]
Without any response to @ybiquitous's inquiry for more than a week, I am closing this issue.

**Comment by Mouvedia** [comment]
Without any response to @ybiquitous's inquiry for more than a week, I am closing this issue.
