### ISSUE TITLE
Block rules need to contend with single-multi line distinction

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#72]
I'm pretty sure that's not being considered yet.

**Comment by davidtheclark** [comment]
Agh. This runs single/multi-line stuff is running into some complications.

1. For each relevant what we'll have to define what determines that it's "single" or "multi". For example, is this `a\n{ color: pink; }` a single- or a multi-line block? How about this `a {\n  color:pink; background: orange;\n}`?

2. Then, we will run into the situation where certain permutations of standard options don't make sense. `block-opening-brace-newline`, for instance --- does it just not accept the single-line options for "after", because anytime a newline is present within the braces the block is multi-line? (Dependent on #1)

**Comment by MoOx** [comment]
From what I know about eslint, single line is when the entire block (for eslint: object) on a single line: `{ ... }`. As soon as there is a newline somewhere, we should switch to multilines.
I have to admit that the case of the selector is kind of tricky. I think we should only consider single/multi for the block it self (braces + content inside).

**Comment by davidtheclark** [comment]
Yeah, I was thinking that, too. So we're in agreement about #1.

After #73 changes are implemented I think that #2 has a straightforward solution: the `block-opening-brace-newline-after` simply doesn't accept `*-single-line` or `*-multi-line` keywords, only accepts `always|never`.

**Comment by MoOx** [comment]
lgtm

**Comment by jeddy3** [comment]
The solutions to 1 and 2 both LGTM :)

**Comment by davidtheclark** [comment]
As of bbea328ab8769f380467e77818157e8f229a5834 this is finished for `block-opening-brace-space-*`.
