### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` false negatives for `*-block` and `*-inline` logical properties

### ISSUE THREAD

**Issue by smfaramarzirad** [stylelint/stylelint#7200]
### What steps are needed to reproduce the bug?

  margin-block-start: 2px;
  margin-block-end: 2px;
  margin-inline-start: 2px;
  margin-inline-end: 2px;

### What did you expect to happen?

  margin-block: 2px;
  margin-inline: 2px;

### What actually happened?

  margin-block-start: 2px;
  margin-block-end: 2px;
  margin-inline-start: 2px;
  margin-inline-end: 2px;

**Comment by ybiquitous** [comment]
CanIuse stats:

- [`margin-block`](https://caniuse.com/mdn-css_properties_margin-block) - 90.69%
- [`margin-inline`](https://caniuse.com/mdn-css_properties_margin-inline) - 90.69%

I think they have enough usage to be supported.

FYI. [`inset`](https://caniuse.com/mdn-css_properties_inset) also has the usage rate (90.69%).

---

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

@mattxwang Feel free to comment if you have any help.

**Comment by Mouvedia** [comment]
There's also

- overflow
- background-position
- border-image-width
- border-inline-width
- border-block-width
- offset-position
- overscroll-behavior

see https://github.com/stylelint/stylelint/issues/6984#issuecomment-1609370641

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for the info. All of the properties except `offset-position` have enough usage stats.

For `offset-position`, it may be better to avoid implementing it since the property is still experimental. See the [CanIuse stats](https://caniuse.com/mdn-css_properties_offset-position).

It's no problem to include also the additional properties in one PR. 👍🏼

**Comment by smfaramarzirad** [comment]
> CanIuse stats:
> 
>     * [`margin-block`](https://caniuse.com/mdn-css_properties_margin-block) - 90.69%
> 
>     * [`margin-inline`](https://caniuse.com/mdn-css_properties_margin-inline) - 90.69%
> 
> 
> I think they have enough usage to be supported.
> 
> FYI. [`inset`](https://caniuse.com/mdn-css_properties_inset) also has the usage rate (90.69%).
> 
> I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.
> 
> There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.
> 
> @mattxwang Feel free to comment if you have any help.

In my country (Iran), more than 95% of browsers support margin-block.

The issue is not only margin-inline and margin-block. There are other logical features such as:

border-block, border-inline, 
border-inline-color, border-inline-style, border-inline-width, padding-block, padding-inline, inset-block, inset-inline, scroll-margin-block, scroll-margin-inline, scroll-padding-block, scroll-padding-inline.

**Comment by mattxwang** [comment]
Thanks for tagging me in! Course prep has been unfortunately busier than I thought, but if nobody else is interested in this PR, I can certainly add it to my own backlog. I can be conservative for now in the properties we support.

I've also been meaning to resolve some of the longstanding issues with the autofix - I suspect there are still a few incorrect behaviours (e.g. with `grid`) that nobody has reported since having *all* of the longhand properties is somewhat unlikely. I'll try to also balance that with the `messageArgs` work!

**Comment by mattxwang** [comment]
@Mouvedia I'm going through the list you had earlier, and wanted to ask:

- for `background-position`: is this a shorthand? I see how we *could* translate `background-position-x` and `-y` into the "shorthand" version, but it doesn't seem to indicate that this is a true shorthand property in the [spec (draft)](https://drafts.csswg.org/css-backgrounds/#background-position)
- for border-image-width`: what would this be a shorthand for? I don't see any candidate longhand properties / anything in the spec, but perhaps I'm missing something

(MDN also has a [handly list](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties#see_also) that I'm using, though it is incomplete)

**Comment by Mouvedia** [comment]
> true shorthand property

I don't know what you mean by _true_ though.
If 2, or more, declarations can be converted to less—currently only one—declaration, I consider it warrants to be added.

> for `border-image-width`: what would this be a shorthand for? I don't see any candidate longhand properties / anything in the spec, but perhaps I'm missing something

I am not sure, I can't remember; I may have made a mistake. Ill remove it from the list.

**Comment by mattxwang** [comment]
> > true shorthand property
> 
> I don't know what you mean by _true_ though. If 2, or more, declarations can be converted to less—currently only one—declarations, I consider it warrants to be added.

Two things on my mind:

- the word "shorthand" doesn't appear anywhere in the spec for `background-position`; usually, in other shorthand a line like "This property is a [shorthand property](https://drafts.csswg.org/css-cascade-5/#shorthand-property) that" exists
- the draft spec seems to still be a work in progress:
> [This section is still being worked out. The tricky thing is making all the start/end keywords work sanely.](https://drafts.csswg.org/css-backgrounds-4/#issue-67389536)

**Comment by Mouvedia** [comment]
> it's also not straightforward

Not always indeed; it doesn't have to. We are not in a hurry to support all shorthands.
Let's resolve the easy ones first and then decide whether the harder ones are still in scope for the rule.
I would say the only reason Id be against it, is if it had a substantial effect on performance.
