### ISSUE TITLE
Error linting SASS files

### ISSUE THREAD

**Issue by zdllucky** [stylelint/stylelint#7216]
### What minimal example or steps are needed to reproduce the bug?

On some _.sass files

```sass
.mb-2-ng
  // -->> Stylelint: Unknown word (CssSyntaxError)
  margin-bottom: -.25rem !important
  ^^^^^^^^^^^^^
```

```sass
html.theme-dark
  // -->> Stylelint: Unknown word (CssSyntaxError)
  filter: hue-rotate(180deg) invert(1) contrast(.8)
  ^^^^^^
  img, video, svg
    filter: contrast(1.2) invert(1) hue-rotate(-180deg)
```

### What minimal configuration is needed to reproduce the bug?

Basic .stylelintrc.json
```json
{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-recommended-scss",
    "stylelint-config-twbs-bootstrap",
    "stylelint-config-sass-guidelines"
  ],
  "plugins": ["stylelint-scss"],
  "parser": "stylelint-scss",
  "reportInvalidScopeDisables": true,
  "reportNeedlessDisables": true,
  "overrides": [
    {
      "files": "./src/client/src/**/*.sass",
      "rules": {
        "scss/selector-no-union-class-name": true
      }
    }
  ]
}
```

### How did you run Stylelint?

It fires error both with IntelliJ IDEA built-in plugin:

![Снимок экрана 2023-10-07 в 16 14 10](https://github.com/stylelint/stylelint/assets/20101012/f4059993-55e5-4fbb-8444-1e5a7c2ee1fc)
![Снимок экрана 2023-10-07 в 16 14 38](https://github.com/stylelint/stylelint/assets/20101012/a5e33742-9eb1-471a-86c6-96cc0343694e)

And via running it as independent npm script in CLI:
![Снимок экрана 2023-10-07 в 16 15 27](https://github.com/stylelint/stylelint/assets/20101012/8a783a20-cf00-4422-9092-baff6c387c78)

```json
{
  "scripts": {
    "lint:styles": "stylelint \"src/client/src/**/*.{css,sass,scss}\" --fix",
  }
}
```
### Which Stylelint-related dependencies are you using?
```json
{
  "devDependencies": {
    "stylelint": "^15.10.3",
    "stylelint-config-sass-guidelines": "^10.0.0",
    "stylelint-config-twbs-bootstrap": "^11.0.1",
    "stylelint-scss": "^5.2.1",
    "postcss-scss": "^4.0.9",
  }
}
```
### What did you expect to happen?

No error linting

### What actually happened?

Error linting

### Do you have a proposal to fix the bug?

It looks like it only takes very first word for first class in file and then fails

**Comment by ybiquitous** [comment]
@zdllucky Can you try [`postcss-sass`](https://github.com/AleshaOleg/postcss-sass)? For example, see this [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0BbARgWgEwYHYHMAdXAAhJQEMAnfAS1wzQgBdmIV4SMksBWKmChIBCWigAOEKswq5mxEABoQAM1oAbGADkKKOIhgAPXeM1IAzhXPml4CLjX4EIYMTKFwAV3NsUAZQBPOQpDD04PSR8wawxLaw9FNxIPKk9NczCSV1IyZJBYMHVqCmZaezwIDDFJaVl5BBJmVJgkgF9iVttIB1p8ADEpSmZnACtze1tYcRtEbPcQSOZo81irDIaPAAYkXiRNhKSPHwDNdXp68JAARl2r7YBmDw6QVqA).

**Comment by zdllucky** [comment]
First of all, thank you for reply,

I did it after some more digging, but it still has weird behavior, althouth it lints correctly now it drops all import lines on fix... so I just dropped this stylelint from lintstaged :) now I do use it manually only.

btw, the root cause of error was "stylelint-config-twbs-bootstrap" dep, once dropped it most error dropped except one described above.

```json
{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-recommended-scss",
    "stylelint-config-sass-guidelines"
  ],
  "parser": "stylelint-scss",
  "customSyntax": "postcss-sass",
  "reportInvalidScopeDisables": true,
  "reportNeedlessDisables": true,
  "plugins": ["stylelint-scss", "stylelint-no-unsupported-browser-features"],
  "rules": {
    "plugin/no-unsupported-browser-features": [
      true,
      {
        "severity": "warning",
        "browsers": ["iOS >= 12", "Android >= 6"],
        "ignorePartialSupport": true,
        "ignore": ["css-filters", "rem", "css-nesting", "@import"]
      }
    ],
    "no-empty-source": null,
    "selector-no-qualifying-type": null
  }
}
```

The unexpected behavior still exists, I don't know should I close this issue or not.

**Comment by ybiquitous** [comment]
@zdllucky I'm unsure about your situation, but mixing `scss` and `sass` in your Stylelint config seems problematic.

I recommend `scss` configs/plugins because `postcss-sass` seems unmaintained.

**Comment by jeddy3** [comment]
Closing as the issue seems related to custom syntax rather than Stylelint itself.
