### ISSUE TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-template` with `repeat()`

### ISSUE THREAD

**Issue by paceaux** [stylelint/stylelint#7228]
### What minimal example or steps are needed to reproduce the bug?

I've provided a [demo](https://github.com/paceaux/stylelint-template-repeat-bug) of the bug. 

1. Create a CSS ruleset containing these properties

```css
  grid-template-columns: repeat(3, 1fr);
  grid-template-rows: auto;
  grid-template-areas: "left center right";
```

2. Using stylelint, apply the `--fix` parameter and observe that it produces this

```css
    grid-template: "left center center right" auto / repeat(3, 1fr);


```

3. Observe the modified CSS in the browser, specifically that it is invalid.

### What minimal configuration is needed to reproduce the bug?

```json
{
    "extends": [
      "stylelint-config-standard"
    ],
    "configBasedir": [
        "./"
    ],
    "ignoreFiles": [
      "node_modules/**/*",
      "dist/**/*.scss"
    ],
    "rules": {
      "indentation": 2
    }
  }
```

### How did you run Stylelint?
See the [demo](https://github.com/paceaux/stylelint-template-repeat-bug)

I've run the command

```bash
stylelint 'styles/**/*' --config .stylelintrc.json --fix
``` 

as an npm script

### Which Stylelint-related dependencies are you using?

* stylelint-config-standard
* stylelint 15.10.3

### What did you expect to happen?

autofix would produce valid syntax. [According the the CSS specifications](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template#values), MDN states that

> The [repeat()](https://developer.mozilla.org/en-US/docs/Web/CSS/repeat) function isn't allowed in these track listings, as the tracks are intended to visually line up one-to-one with the rows/columns in the "ASCII art".

So this expected output should not be a duplication from `grid-template-columns` but an _interpretation_ of `repeat()` for each column: (interpretation? extraction? parsing? IDK)

```css
grid-template-areas: "left center right" auto / 1fr 1fr 1fr;
```

### What actually happened?

The autofixed output copied the property from `grid-template-columns`, which, in the _specific_ case of having `repeat()`, is invalid:

```css
    grid-template: "left center center right" auto / repeat(3, 1fr);
```

### Do you have a proposal to fix the bug?

Honestly I think the smartest thing to do is to skip grid-template with this rule because you're going to get some crazy use-cases. 

In lieu of that, you'll need to place a trailing `/` and then "unravel/parse/apply" the `repeat` into an appropriate number of units, which doesn't sound fun at all.

**Comment by ybiquitous** [comment]
@paceaux Thanks for the report with a reproducible demo repository! I confirmed the repo, and we can also reproduce the bug with our [live demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilBzATgJZQC0ALjALYAOANkhSZLQK6WYDO8K+M1MDABQBmADQoAjADN8ASgDcWHAWLkqdBjBL4IAdy4okLMhEXY8RUhRr1GSXkgPoQtGFLIowMTBXw9CuAAWZM5mAL4goiBShK4AckiUcIgwAB6JdDAAdGAcHJHgEJgxuAggGObO+CyuHM7cFTg4zrBg9PgMhEUkAEa0EGAA1iSYENowUCyYUEg+JP2YQbOk1Dr8+GSEMHUIKGTVMEooYVgRUZDFAQBiEPiUDGUAVhxFBbDU+YiNKM4cZACerlohB89R+IAkAFYshIAAxZYTOU4gMJAA).

As MDN says ([the spec too](https://drafts.csswg.org/css-grid/#explicit-grid-shorthand)), we should add an exception for `repeat()` to the following implementation: ⬇️ 

https://github.com/stylelint/stylelint/blob/2a1fc6dbcfc1f245a4f75e83d8d8048c098614c4/lib/rules/declaration-block-no-redundant-longhand-properties/index.js#L91-L109

I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by mattxwang** [comment]
Thanks for the detailed issue! I hadn't realized that the behavior of `repeat` was so complicated (I'm browsing the [syntax in the spec](https://drafts.csswg.org/css-grid/#repeat-notation), and it doesn't seem like a trivial fix). For now, I'll submit a PR to mark this as unfixable, but I think it'd be nice to eventually be able to deal with this properly (which would involve some more parsing work).

**Comment by paceaux** [comment]
@mattxwang  I'm glad my advice to skip this is being taken seriously. 

1. `repeat()` has very complex behavior
2. The syntax for `grid-template` itself is _also_ extremely complex 

Honestly, I think the best thing is that `declaration-block-no-redundant-longhand-properties` actually ignores `grid-template` and compatriots because condensing these `grid-template` properties into their shorthand will reduce legibility substantially. 

I gave you a watered down use-case, but I discovered this on a `grid-template-columns` that was using **twelve columns**. 
If Stylelint did this "properly", the output would've been this:

```css
  grid-template: 
    "sidebar sidebar sidebar main main main main main main main main main"
    "footer footer footer footer footer footer footer footer footer footer footer footer" / auto / 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
```

I don't think Stylelint wants to lay claim that the above is actually better than
```css
  grid-template-columns: repeat(12, 1fr);
  grid-template-rows: auto;
  grid-template-areas: 
    "sidebar sidebar sidebar main main main main main main main main main"
    "footer footer footer footer footer footer footer footer footer footer footer footer";
```

**Comment by paceaux** [comment]
@mattxwang Another alternative would just be to look to see if there's a `repeat()` in any of the `grid-template` values, and simply conclude, "nope, this rule should be ignore under these circumstances" If you do that you save yourself the problem of accidentally producing broken code.

**Comment by mattxwang** [comment]
> @mattxwang Another alternative would just be to look to see if there's a `repeat()` in any of the `grid-template` values, and simply conclude, "nope, this rule should be ignore under these circumstances" If you do that you save yourself the problem of accidentally producing broken code. 

Yup, I gave that a spin in the PR I just submitted for this issue. The proposal to skip `grid-template` is interesting - any thoughts from others? It's not hard to do from a code perspective, but does have downstream impacts. The alternative is to disable the rule for that shorthand (which is doable now).

**Comment by ybiquitous** [comment]
Thanks for the interesting discussion. If supporting `grid-template` has a problem, then how about ignoring `grid-template` in `stylelint-config-standard` like this, instead of ignoring `grid-template` in the rule? If doing so, users can have a more flexible option.

```diff
- 'declaration-block-no-redundant-longhand-properties': true,
+ 'declaration-block-no-redundant-longhand-properties': [true, {ignoreShorthands: ['grid-template']}],
```

https://github.com/stylelint/stylelint-config-standard/blob/3fe435b1b931e534610da4ffb58fbc1f744d3dd7/index.js#L55

Of course, I think it should be best to avoid such ignorance even in the sharable config as possible, though.
