### ISSUE TITLE
`string-quotes`: fix @charset quotes

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7233]
### Rationale

https://github.com/stylelint/stylelint/pull/2959#discussion_r145541376
#7060

### What minimal example or steps are needed to reproduce the bug?

```css
@charset 'utf-8';
```

### What minimal configuration is needed to reproduce the bug?

```jsonc
{
  "fix": true,
  "rules": {
    "string-quotes": "single" // or "double"
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo

### What did you expect to happen?

after `--fix`

```css
@charset "utf-8";
```

### What actually happened?

after `--fix`

```css
@charset 'utf-8';
```

**Comment by ybiquitous** [comment]
@Mouvedia `string-quotes` will be removed in v16.

**Comment by Mouvedia** [comment]
elirasza/stylelint-stylistic#16
