### ISSUE TITLE
Support custom formatter for ESM

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7267]
### What is the problem you're trying to solve?

Currently, we support only a custom formatter written in CommonJS (CJS). But, it would be useful if people could also specify a custom formatter in ESM.

https://github.com/stylelint/stylelint/blob/958bf369127f867747c613ec9c7025344e220eed/lib/cli.mjs#L396-L400

Related to #6930

### What solution would you like to see?

I suggest supporting a custom formatter written in ESM. This means we need to change the current *requiring* logic.

**Comment by mattxwang** [comment]
This seems like a reasonable idea to me! From my understanding, it wouldn't be too complicated right (?) - as we can synchronously load CJS from ESM code? 

(perhaps we could also look to the community and see which formatters are popular, which could help us guide the API)

**Comment by ybiquitous** [comment]
I guess we could use *dynamic import* (aka `import()`), which is available both ESM and CJS modules as the [Node.js document](https://nodejs.org/api/esm.html#import-expressions) says:

> [Dynamic `import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) is supported in both CommonJS and ES modules. In CommonJS modules it can be used to load ES modules.

We must change the code using `Promise` when adopting this approach since `import()` returns a `Promise`. But this should not be problematic because the `cli.mjs`'s main function is already an *async* function.
