### ISSUE TITLE
Support custom syntax for ESM

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7269]
### What is the problem you're trying to solve?

Currently, we support a custom syntax module only for CommonJS (CJS). It would be useful if we could support ESM as well.

https://github.com/stylelint/stylelint/blob/958bf369127f867747c613ec9c7025344e220eed/lib/getPostcssResult.js#L74

Related to #6930, #7267

### What solution would you like to see?

I suggest supporting a custom syntax written in ESM. This means we need to change the current requiring logic.

**Comment by mattxwang** [comment]
Basically parroting my comment in https://github.com/stylelint/stylelint/issues/7267#issuecomment-1776292737:

> This seems like a reasonable idea to me! From my understanding, it wouldn't be too complicated right (?) - as we can synchronously load CJS from ESM code? 
> 
> (perhaps we could also look to the community and see which ~~formatters~~ syntaxes are popular, which could help us guide the API)

I imagine the SCSS/SASS and LESS custom syntaxes are the most common, though I recall seeing some issues related to Vue, etc.
