### ISSUE TITLE
Improve organization of non-rule tests

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#727]
Right now the organization isn't always phenomenal. Like, the testing of `ignoreFiles` all happens in `standalone-test`, but the actual implementation is not part of the standalone API: it's part of the PostCSS plugin. This and other stuff could be cleaned up.

**Comment by jeddy3** [comment]
> This and other stuff could be cleaned up.

Is there a list of misplaced things you could possibly knock-up offhand? If so, I'm happy to do the shifting around.

**Comment by davidtheclark** [comment]
Within standalone's tests there are several themes that could be broken out into their own test files:

- extends
- non-standard syntax
- ignoring files

Maybe that's it.

**Comment by jeddy3** [comment]
Thanks, now I see what you mean.

I've got a pending PR for this.

**Comment by davidtheclark** [comment]
Done in #1546
