### ISSUE TITLE
stylelint does not search in /usr/lib64 for the node_modules directory in case of a global installation

### ISSUE THREAD

**Issue by sedimentation-fault** [stylelint/stylelint#7297]
### What minimal example or steps are needed to reproduce the bug?

1. Start with no `stylelint` whatsoever, neither locally, nor globally.
2. Install globally with
    `npm install -g stylelint stylelint-config-standard`
4. Create a configuration file in the root of your project.
     Name it `.stylelintrc`:
 
    ```
    {
    "extends": "stylelint-config-standard"
    }
    ```
    
5.  Try to check a CSS outside your project, say, one dir up:
    `stylelint ../some-path-to-a-css`
    

### What minimal configuration is needed to reproduce the bug?

This is not the _minimal_ configuration, but the configuration of the system:

- Linux, kernel 5.4.196
- npm 9.6.7
- node.js 18.7.1

### How did you run Stylelint?

See above.

### Which Stylelint-related dependencies are you using?

No package.json. This is a global installation.

### What did you expect to happen?

Check messages as in the case of a normal operation.

### What actually happened?

 First error:
 `Error: EACCES: permission denied, open '/.config/stylelintrc'`
 
 I copied the local `.stylelintrc` to `/.config/stylelintrc`, which indeed did not exist, just to see what happens further. It still complained with the same error. I had to change the permissions of

-  `/.config/stylelintrc` to 644
-  `/.config` to 755

 to make the whole path readable to all. The error went away, but another one popped up:
 
 ```
 Error: Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?
 at configurationError (/usr/lib64/node_modules/stylelint/lib/utils/configurationError.js:12:49)
 at getModulePath (/usr/lib64/node_modules/stylelint/lib/utils/getModulePath.js:28:9)
 at loadExtendedConfig (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:216:21)
 at extendConfig (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:184:25)
 at augmentConfigBasic (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:57:26)
 at augmentConfigFull (/usr/lib64/node_modules/stylelint/lib/augmentConfig.js:111:30)
 at Object.transform (/usr/lib64/node_modules/stylelint/lib/getConfigForFile.js:51:37)
 at search (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:47:54)
 at async search (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:64:28)
 at async search (/usr/lib64/node_modules/stylelint/node_modules/cosmiconfig/dist/Explorer.js:64:28)
 ```

This was a very nasty one to resolve...

### Do you have a proposal to fix the bug?

At first I thought the advice of the error message was pointing me to the right direction (it was _not_...:disappointed:), so I thought my global config file at `/.config/stylelintrc` was missing the `"configBasedir"` line, like this:

```
"stylelint": {
  "extends": "stylelint-config-standard",
  "configBasedir": "full-path-to-the-directory-of-globally-installed-stylelint-config-standard"
}
```

which in my case meant I should add the line:

  `"configBasedir": "/usr/lib64/node_modules"`

However, no matter what I entered as a path there, the error remained - _very_ frustrating! :unamused:

### Reason

At the end I decided to use `strace`:

`strace stylelint ../some-path-to-a-css`

This pointed me to the _cause of the problem_:

**`stylelint` simply cannot find my global `node_modules` directory:**

```
statx(AT_FDCWD, "/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/XXX/.node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/XXX/.node_libraries", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/lib/node", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/usr/lib", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=12288, ...}) = 0
statx(AT_FDCWD, "/usr/lib/node_modules", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, 0x7ffcc3d7c160) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/lib/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/node_modules", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffcc3d7be70) = -1 ENOENT (No such file or directory)
```

It searches for it all over the place, BUT NOT AT

`/usr/lib64/node_modules`

where my node modules are installed globally...

### Conclusion

To summarize, there are multiple problems here, but they can be easily fixed:

- There are no instructions for a global installation in the User Guide.
- There is no mention of `/.config/stylelintrc` whatsoever anywhere in the Internet(!).
- The error message about `"configBasedir"` is misleading.
- The `"configBasedir"` setting in `/.config/stylelintrc` has no effect whatsoever.
- Finally - the true cause of this issue - `stylelint` does not search `/usr/lib64` for the `node_modules` directory.

### Workaround

As a workaround (i.e. not a true solution, but a quick'n dirty fix in my case) I added a symbolic link

`/usr/node_modules -> lib64/node_modules`

by doing (as root)

`ln -s lib64/node_modules /usr/node_modules`

the idea :bulb: being that, since `stylelint` searches for `/usr/node_modules`, it will follow the symlink and find my global `node_modules` directory. And indeed! :heavy_exclamation_mark: as soon as I did this, the error went away. It even works without any `"configBasedir"` setting in `/.config/stylelintrc`. :sunglasses:

**Comment by ybiquitous** [comment]
@sedimentation-fault Thanks for the detailed report. I recommend install `stylelint` and `stylelint-config-standard` in your project, instead of the global installation. This is a very simple solution. Do you have any reason to avoid a local installation?

**Comment by sedimentation-fault** [comment]
> Do you have any reason to avoid a local installation?

I did a local installation in some dummy directory, just out of curiosity. It said it installed 172 packages. Now, imagine I work on multiple projects. I will have multiple copies of those 172 packages floating around! Why? There is no reason. I am one person, working on my one system. I don't need to clone those 172 packages all around. My stylelint rules will be the same across all projects. The dependency on stylelint is a "development" one, i.e. it does not need to be attached to any one of the projects.

All this really suggests a global installation is the best option for me. YMMV of course.

**Comment by sedimentation-fault** [comment]
You can read a rant :rage: about this dumping of all dependencies locally for each program/project [here](http://michael.orlitzky.com/articles/motherfuckers_need_package_management.xhtml). Please don't be offended by the harsh language it uses - the points it makes are perfectly valid.

**Comment by ybiquitous** [comment]
I see your motivation. So, can you try the following location of your Stylelint config file, for example?

```console
$ tree -a
.
|-- config
|   `-- .stylelintrc.json
`-- project
    `-- test.css

3 directories, 2 files

$ cat ./config/.stylelintrc.json
{"extends": "stylelint-config-standard"}

$ stylelint -c ./config/.stylelintrc.json 'project/*.css'

project/test.css
 1:2  ✖  Unexpected empty block  block-no-empty

1 problem (1 error, 0 warnings)

$ npm ls -g
/usr/local/lib
+-- corepack@0.22.0
+-- npm@10.2.3
+-- stylelint-config-standard@34.0.0
`-- stylelint@15.11.0
```

**Comment by sedimentation-fault** [comment]
Let's start from the bottom. :smile:

```
npm ls -g

npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.2.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.3
npm notice Run npm install -g npm@10.2.3 to update!
npm notice 
/usr/lib64
...
├── npm@9.6.7
...
├── stylelint-config-idiomatic-order@9.0.0
├── stylelint-config-prettier@9.0.5
├── stylelint-config-standard@34.0.0
├── stylelint-declaration-block-no-ignored-properties@2.7.0
├── stylelint-order@6.0.3
├── stylelint@15.11.0
└── yarn@1.22.17
```

In the above, I've left only the relevant pieces of information.

You show me how to use a local configuration file. This certainly has its merits if the settings are going to change from project to project. Currently, I am the one who decides on those settings, and I waant to use the same ones everywhere, in all projects. Therefore I prefer a global configuration file. If this file must be `/.configure/stylelintrc`, so be it (although, in Linux, such configuration belongs to `/etc/stylelint`).

There is another thing I did not tell you: I don't use stylelint the way you showed me above, i.e. manually from the CLI (although I am a big fan of CLI :grin:). I use it as a "formatter" in the [autoformat plugin for vim](https://github.com/vim-autoformat/vim-autoformat). That is, I have changed the standard formatter used for CSS in `autoformat` from `css-beautify` to a _wrapper bash script_ of mine that reads from `stdin`, pipes to `stylelint --fix`, saves the result in a temporary file, then runs `prettier` on it. `prettier`, by default, prints the result on `stdout`. This `stdin`:arrow_right:`stdout` piping is required for formatters used in `autoformat` and just using `stylelint --fix | prettier` is not going to work, because `prettier` will print an error:

`[error] No parser and no file path given, couldn't infer a parser.`

 Of course, my `/.configure/stylelintrc` is now a bit more elaborate, as I use some extra rules and plugins:

```
{
  "extends": [
  "stylelint-config-standard",
  "stylelint-config-idiomatic-order",
  "stylelint-config-prettier"
  ],
  plugins: [
    "stylelint-order",
    "stylelint-declaration-block-no-ignored-properties",
  ],
  rules: {
    "plugin/declaration-block-no-ignored-properties": true,
    "declaration-empty-line-before": [
      "always",
      {
        ignore: [
          "after-comment",
          "after-declaration",
          "first-nested",
          "inside-single-line-block",
        ],
      },
    ],
  },
}
```

You can read about the rationale of those settings in [Level up your CSS linting using Stylelint](https://blog.logrocket.com/using-stylelint-improve-lint-css-scss-sass/). The code for it is in https://github.com/robole/stylelint-config-roboleary/.

With all the above in place, all I have to do is press F3 (the standard `autoformat` key for triggering the formatter for a filetype in vim) and it will invoke my wrapper, which will pipe the CSS through

`stylelint --fix | prettier`

using the above configuration (which is designed to have no conflicts with `prettier`). I get linting, fixing and formatting at once. I already have set `stylelint` as a syntax checker in the [syntastic vim plugin](https://github.com/vim-syntastic/syntastic), so I get pure linting-on-save too). Very cool! :sunglasses:

Now, how would I do this with a local configuration file? Sure, I could

- set up the local configuration file as a symbolic link to the global one and
- adapt my bash wrapper (used by `autoformat` as formatter) to read the local config file.

But again, why? It's overkill for me. I will try to avoid local configuration files for the moment - at least as long as my rules remain constant across projects. It works like a charm the way it is, but IMHO you must take care of the points listed in my Conclusion above.

In your place, I would proceed as follows to find the location of the global `node_modules` directory:

1. Check if we are running in Linux.
2. If we do, add the output of 
   `npm ls -g 2>/dev/null | grep -v -E '(├|└|^$)'`
   (if non-empty, of course) to the list of places to search for `node_modules`.

This way you cover not only my `/usr/lib64`, but any possible location. :sunglasses:

**Comment by Mouvedia** [comment]
Can you prefix it with `NODE_PATH=/usr/lib64/node_modules `?

**Comment by jeddy3** [comment]
Closing as stale.

**Comment by sphakka** [comment]
This issue is still there on GNU/Linux Gentoo. `node.js` installed at OS level.

```shell
$ npm ls -g --verbose
npm verbose cli /usr/bin/node /usr/bin/npm
npm info using npm@10.8.1
npm info using node@v22.4.1
/home/marcoep/.npm/lib64
...
├── stylelint-config-standard@36.0.1
├── stylelint@16.8.2
...
npm verbose os Linux 6.6.47-gentoo-docker
npm verbose node v22.4.1
npm verbose npm  v10.8.1
npm verbose exit 0
npm info ok
```
Stylelint's config:
```shell
$ cat ~/.stylelintrc.json 
{
    "extends": "stylelint-config-standard",
    ....
}
```

KO run (neither `NODE_PATH` nor `configBasedir` set):
```shell
$ echo 'foo { ; }' | stylelint
Error: Could not find "stylelint-config-standard". Do you need to install the package or use the "configBasedir" option?
    at configurationError (file:///home/marcoep/.npm/lib64/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
...
```

OK run with either `NODE_PATH` or `configBasedir` set:
```shell
$ export NODE_PATH=~/.npm/lib64/node_modules/;  echo 'foo { ; }' |  stylelint  

<input css PpAhGk>
  1:1  ✖  Unexpected unknown type selector "foo"  selector-type-no-unknown

✖ 1 problem (1 error, 0 warnings)
```

Searching canonical node modules' paths would really spare some head scratching!

**Comment by ybiquitous** [comment]
It looks like Stylelint cannot know where `~/.npm/lib64/node_modules` is without `NODE_ENV`.

**Comment by sphakka** [comment]
@Mouvedia, thanks for the tip, but that doesn't work.

Could we please reopen this bug? I suggest searching some canonical paths before throwing an exception, in escalating order:

1. command line option `--config-basedir`
1. configuration `configBasedir`
1. environment `NODE_PATH`
1. local `./node_modules`
1. user `${HOME}/.npm/lib64/node_modules`
1. system `/usr/lib64/node_modules`

Meanwhile, I'm fine with the `NODE_PATH` workaround ^^

**Comment by ybiquitous** [comment]
As much as possible, I want to rely on the resolution mechanism provided by Node.js:
https://nodejs.org/api/modules.html#loading-from-the-global-folders

In other words, I want to avoid adding any custom resolution logic.

**Comment by sphakka** [comment]
For those landing here recently. The `NODE_PATH` method doesn't work any more, but the CLI option `--config-basedir` does. E.g.:

```shell
$ stylelint --config-basedir=/absolute/path/to/npm/lib64/node_modules/ ...
```
