### ISSUE TITLE
Consider using -before and -after rules instead of before/after options

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#73]
After writing *a lot* of tests now, I'm think that things would be simpler if we separated out before/after rules instead of using options. So we'd have, e.g., `block-opening-brace-space-before` and `block-opening-brace-space-after` (like JSCS).

The reasoning is this:

- Each rule function would be that much simpler, that much more focused.
- Tests would have fewer option-permutations to test -- so we could get by writing way fewer, more straightforward tests. Right now if we want to be really thorough we have to make sure that each permutation works as expected and that changing one option doesn't affect the outcome of the other option; but if we had separate rules each of those would be tested independently and we wouldn't have to worry about them possibly overlapping and affecting each other.

Any opposition?

**Comment by MoOx** [comment]
> Any opposition?

Nope.

**Comment by jeddy3** [comment]
> Nope.

Same. I've been trying to get my head around #71 and #72 for the last few minutes and if you think that splitting out `before` and `after` well help somewhat towards these issues, then I'm totally OK with it.

**Comment by davidtheclark** [comment]
Ok, cool ... it will take some refactoring work but I think it will help keep things clear and distinct and straightforward. I have a lot of computing to do today, so I'll work on it off-and-on and hope to have it done (existing functions and rules converted) by the end of today or early tomorrow.

**Comment by jeddy3** [comment]
I'm away from home until tomorrow evening, but I should be able to help out with the refactoring of the rules from Monday if there's still some left to do.

> so I'll work on it off-and-on and hope to have it done (existing functions and rules converted) by the end of today or early tomorrow.

Thanks again for all your continued hard work!

**Comment by MoOx** [comment]
Thanks both of you :)

**Comment by davidtheclark** [comment]
And thanks to you. I think the process & communication has been going really well.

**Comment by tunnckoCore** [comment]
> After writing a lot of tests now, I'm think that things would be simpler if we separated out before/after rules instead of using options.

Good morning. :+1: Will look really better.

**Comment by davidtheclark** [comment]
Cool. Implementing now.
