### ISSUE TITLE
Test on Node.js 21 and coverage on 20

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7302]
Node.js 21 is [now Current](https://nodejs.org/en/blog/announcements/v21-release-announce), and 20 moves to LTS.

Shall we update our [testing matrixes](https://github.com/stylelint/stylelint/blob/v16/.github/workflows/testing.yml) to:

- include 21
- ~~lint~~ coverage on 20 (as most recent LTS)

**Comment by ybiquitous** [comment]
> * lint on 20 (as most recent LTS)

The "lint" workflow is executed on LTS by default. See https://github.com/stylelint/.github/blob/98e4f80b00ad6fb96c117f0f5fb9c82c8f04f75e/.github/workflows/lint.yml#L9

**Comment by ybiquitous** [comment]
> * include 21

Sounds good. How about specifying `latest` as a [supported syntax by `actions/setup-node`](https://github.com/actions/setup-node#supported-version-syntax)?

```diff
- node-version: '["18", "20"]'
+ node-version: '["18", "20", "latest"]'
```

**Comment by ybiquitous** [comment]
If we specify `latest` or `current`, a commit switching `21` to `22` will not be needed.

**Comment by jeddy3** [comment]
> The "lint" workflow is executed on LTS by default.

Oops, I meant coverage rather than lint:
https://github.com/stylelint/stylelint/blob/main/.github/workflows/testing.yml#L34-L38

> If we specify latest or current, a commit switching 21 to 22 will not be needed.

Let's use "current" instead of "21".
