### ISSUE TITLE
Add support for nested properties in rule declaration-property-value-no-unknown.

### ISSUE THREAD

**Issue by pamelalozano16** [stylelint/stylelint#7310]
### What is the problem you're trying to solve?

Rule [declaration-property-value-no-unknown](https://github.com/stylelint/stylelint/tree/main/lib/rules/declaration-property-value-no-unknown) doesn't work for [SCSS nested properties](https://sass-lang.com/documentation/style-rules/declarations/#nesting). So `font-size: red;` raises an error, but `font: { size: red; }` does not. 

[Demo here](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AjABMAOgO0wFwHcALASzxngx33wGcAHAQzArRQgCdYOBadgDwDc1PAF9quPADMI2PJSyS6JAF6sOMKMMnjck4mRg8GzVuy4xeA7fhlzjq9Zu26cIADQgpJADYwAcowAtnCIMPzB9H5ItGC0tB7gst4A5gggimhomCDh5NhQtDmUANo4WVk5tHgAnn4+JPaQ2KnGeIwFjFzGcUUg5WgAuu4DORwArn59CgOVILBgPl2MeCSyPPQcEPSWtTwAbow+40bYEDzj2ADWZwS4CGh4EzADuqKJzakAYpxBK+kAK1oskSsHoCUQmWyIGqdRgDTkxWhS3I1RyI2wc1h9UaeB4nxIKTaHSgXSgPXiSJyKJgaP62HeoiAA).

### What solution would you like to see?

Although this is a SCSS-specific feature, @kristerkari [suggested](https://github.com/stylelint-scss/stylelint-scss/issues/882#issuecomment-1790960431) we support nested properties in `declaration-property-value-no-unknown` Stylelint CSS rule to avoid duplicate code and encourage code reusability.

**Comment by jeddy3** [comment]
@pamelalozano16 Thanks for the request and for using the template.

It's unlikely we'll add support for nested properties to the built-in rule as we're focused on balancing support for modern CSS against the long-term maintenance of the project. The CSS language is constantly improving and growing, so we have to focus the time we have on supporting that. 

We sometimes add secondary options, like `ignoreAtRules: []`, to help the stylelint-scss authors reuse code. But this is only applicable when SCSS uses a standard _construct_, like custom at-rules e.g. `@debug`.

As nested properties are a non-standard construct, stylelint-scss authors will need to mirror the rule if they want to support them. Or they may, and I'm just throwing this out there, add a `no-nested-properties` rule to discourage their use.

**Comment by jeddy3** [comment]
(@Mouvedia Thanks for triaging the issue. We've got a guide for [consistent label](https://stylelint.io/maintainer-guide/issues#labels)).

**Comment by jeddy3** [comment]
Closing as we are unlikely to add support for non-standard syntax to the built-in rules and will continue to use the `isStandardSyntax*` utils to ignore them so that the rules are somewhat useful for language extensions.
