### ISSUE TITLE
Add tally of fixable problems to string formatter

### ISSUE THREAD

**Issue by rakleed** [stylelint/stylelint#7338]
### What is the problem you're trying to solve?

There is currently no way to know how many problems will be fixed automatically with the `--fix` flag. When calling `stylelint`, only the number of problems found will be shown.

![CleanShot 2023-11-13 at 06 19 06](https://github.com/stylelint/stylelint/assets/19418601/044b02ae-c299-470e-8503-b157e309bde6)

### What solution would you like to see?

When calling `stylelint`, show how many problems can be fixed with the `--fix` flag, as ESLint does:

![CleanShot 2023-11-13 at 06 47 50](https://github.com/stylelint/stylelint/assets/19418601/20366b57-2e51-4027-8c5b-6e4f9ce27b56)

**Comment by ybiquitous** [comment]
@rakleed Thanks for the proposal. However, the `verbose` formatter shows the info:

<img width="529" alt="image" src="https://github.com/stylelint/stylelint/assets/473530/d956dff5-065f-4b25-86de-4aee7ef9a08f">

It may be helpful if the default formatter also shows the same info.

**Comment by jeddy3** [comment]
> It may be helpful if the default formatter also shows the same info.

SGTM. 

Let's move the 'You may fix some problems with the "--fix" option.' from the `verbose` formatter into the `string` one, rewrite it to include a tally and change the colour to white as it's informational.

For example, the string formatter:

```console
% npx stylelint "**/*.css"
src/components.css
 10:10  ✖  Unexpected unknown value "1" for property "gap"  declaration-property-value-no-unknown

74 problems (24 errors, 50 warnings)
10 errors and 3 warnings potentially fixable with the "--fix" option.
```

For example, the verbose formatter:

```console
% npx stylelint "**/*.css"
src/components.css
 10:10  ✖  Unexpected unknown value "1" for property "gap"  declaration-property-value-no-unknown

74 problems (24 errors, 50 warnings)
10 errors and 3 warnings potentially fixable with the "--fix" option.

1 sources checked
 /Users/jeddy3/components.css

10 errors found
 font-family-name-quotes: 5 (maybe fixable)
```

Let's only show numbers greater than one, e.g.

- 0 fixable errors & 3 fixable warnings = "3 warnings potentially fixable with the "--fix" option."
- 10 fixable errors & 0 fixable warnings = "10 errors potentially fixable with the "--fix" option."
- 0 fixable errors & 0 fixable warnings = ""

(We need to include "potentially" as a rule may be flagged as fixable in its metadata, but the particular pattern isn't.)

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by jeddy3** [comment]
I've pinned the issue as low-hanging fruit that'll help new users discover the `--fix` flag after completing the getting started guide.

**Comment by m-allanson** [comment]
Is this still open to be implemented?

If yes, what are the thoughts on shortening the "potentially fixable" text to the following:

```diff
74 problems (24 errors, 50 warnings)
- 10 errors and 3 warnings potentially fixable with the "--fix" option.
+ 13 potentially fixable with the "--fix" option.
```

Or even condensing to a single line:

```diff
- 74 problems (24 errors, 50 warnings)
- 10 errors and 3 warnings potentially fixable with the "--fix" option.
+ 74 problems (24 errors, 50 warnings). 13 potentially fixable with the "--fix" option.
```

As the `--fix` option always fixes both errors and warnings, it seems redundant to have the separate counts.

The overall _problem_ count is the most important piece of information. Therefore I think the _potential fix_ count should be less prominent than the problem count.

**Comment by ybiquitous** [comment]
Yeah, this is ready to implement. And your suggestion sounds good to me 👍🏼
