### ISSUE TITLE
Add `checkContextFunctionalPseudoClasses: []` to `selector-max-id`

### ISSUE THREAD

**Issue by brigitamaria** [stylelint/stylelint#7364]
### What is the problem you're trying to solve?

I'm using `selector-max-id: 0` on a project to disable ID selectors on the CSS files, but something like `:global(#foo)` is not throwing any errors.

### What solution would you like to see?

Currently, `:global` and `:local` is not included on `isContextFunctionalPseudoClass`. 
Including those scope selectors in that function will affect another rules which also use the same function, so what do you think about this use case?
I'd be happy to help so let me know about your opinion, thank you!

**Comment by jeddy3** [comment]
@brigitamaria Thanks for the request and for using the template.

The built-in rules only support standard CSS syntax from the specifications. However, we can discuss adding a `includeContextFunctionalPseudoClasses: []` option to the `selector-max-*` rules.  

For example:

```json
{
  "rules": {
    "selector-max-id": [0, {
      "includeContextFunctionalPseudoClasses": ["--custom-pseudo-class"]
    }]
  }
}
```

The new option would go alongside the existing [`ignoreContextFunctionalPseudoClasses`](https://stylelint.io/user-guide/rules/selector-max-id/#ignorecontextfunctionalpseudoclasses-regex-regex-non-regex) one.

**Comment by Mouvedia** [comment]
I found cases that warrants the addition: `:-webkit-any()`, `:-moz-any()`.

**Comment by brigitamaria** [comment]
I like the suggestion for adding a new option, but how should we treat the presedence if we pass the same elements to `includeContextFunctionalPseudoClasses` and `ignoreContextFunctionalPseudoClasses`?

**Comment by Mouvedia** [comment]
> but how should we treat the precedence if we pass the same elements to `includeContextFunctionalPseudoClasses` and `ignoreContextFunctionalPseudoClasses`?
> `["/regex/", /regex/, "non-regex"]`

I advise against order because it wasn't consistent for objects in ES5.
It's easy to detect conflicts for `non-regex` and warn.

A simple solution would be to have one of the two have the priority.
e.g. anything set by `ignoreContextFunctionalPseudoClasses` can be overruled by `includeContextFunctionalPseudoClasses`
