### ISSUE TITLE
Fix `ERR_UNSUPPORTED_ESM_URL_SCHEME` error on Windows

### ISSUE THREAD

**Issue by ali-hmer** [stylelint/stylelint#7382]
### What minimal example or steps are needed to reproduce the bug?

Running `stylelint` command on Windows fails after upgrading to 16.0.0. 
`stylelint src/**/*.css`

### What minimal configuration is needed to reproduce the bug?

{
    "defaultSeverity": "warning",
    "plugins": ["stylelint-prettier"],
    "rules": {
        "prettier/prettier": true
    }
}

### How did you run Stylelint?

stylelint src/**/*.css

### Which Stylelint-related dependencies are you using?

{
"stylelint": "16.0.1",
    "stylelint-config-prettier": "9.0.5",
    "stylelint-config-standard": "35.0.0",
    "stylelint-order": "6.0.4",
    "stylelint-prettier": "4.1.0",
}

### What did you expect to happen?

Stylelint should run with no issues

### What actually happened?

I got this error

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

### Do you have a proposal to fix the bug?

I did some research and it seems to be related to ESM. Not sure why it should fail though. My project is not ESM ready.

**Comment by JounQin** [comment]
Can you provide more error stack? I'd like to work on it.

**Comment by JounQin** [comment]
Just found the cause statement:

https://github.com/stylelint/stylelint/blob/2a82f4d2c3147a823241327fe6d6e0a069894d21/lib/getPostcssResult.mjs#L72

Working on a PR.

**Comment by ybiquitous** [comment]
Thanks guys. We must pass a URL string to `import()` as PR #7383 does to prevent the error.

Since @ali-hmer's config doesn't include `customSyntax`, I guess this error occurs at `plugins`.

So, I think we should fix `getModulePath()`. I'll open another PR.

https://github.com/stylelint/stylelint/blob/2a82f4d2c3147a823241327fe6d6e0a069894d21/lib/utils/getModulePath.mjs#L14

**Comment by JounQin** [comment]
> So, I think we should fix getModulePath(). I'll open another PR.

I think continue on #7383 is enough?

**Comment by ybiquitous** [comment]
@JounQin Yeah, of course. 👍🏼 

I'm considering how to add test cases to prevent future regressions.

**Comment by firefoxic** [comment]
If it's useful, I could test a pre-patch in our template repository.

**Comment by JounQin** [comment]
@firefoxic You can test it with `"stylelint": "stylelint/stylelint#fix/import_esm_win"`

**Comment by ali-hmer** [comment]
Sorry for the delay. I live in Canada :-)
Here is the stack trace:
`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:328:23)`

**Comment by ali-hmer** [comment]
Thank you guys for resolving the issue

**Comment by ybiquitous** [comment]
@ali-hmer Thanks a lot for your issue report. We've just merged the fix into `main`. Can you please confirm if the error is resolved with the unpublished version?

```shell
npm i 'github:stylelint/stylelint'
```

**Comment by firefoxic** [comment]
It's working 🚀
Thank you 🥰

**Comment by ali-hmer** [comment]
> @ali-hmer Thanks a lot for your issue report. We've just merged the fix into `main`. Can you please confirm if the error is resolved with the unpublished version?
> 
> ```shell
> npm i 'github:stylelint/stylelint'
> ```

I can confirm it's working. Thanks
