### ISSUE TITLE
Stylelint 16 compatibility with stylelint-use-logical 

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#7384]
### What minimal example or steps are needed to reproduce the bug?

1. Install Stylelint 16
2. Add `stylelint-use-logical`
3. Run Stylelint on empty CSS

### What minimal configuration is needed to reproduce the bug?

```json
{
  "plugins": ["stylelint-use-logical"],
  "rules": {
    "csstools/use-logical": "always"
  }
}
```

### How did you run Stylelint?

```sh
npx stylelint test.css
```

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "16.0.0",
    "stylelint-use-logical": "2.1.0"
}
```

### What did you expect to happen?

Print a warning but run

### What actually happened?

```
CommonJS plugins are deprecated ("/home/ai/Dev/slowreader/node_modules/.pnpm/stylelint-use-logical@2.1.0_stylelint@16.0.1/node_modules/stylelint-use-logical/index.cjs"). See https://stylelint.io/migration-guide/to-16

Unknown rule csstools/use-logical  csstools/use-logical
```

### Do you have a proposal to fix the bug?

Of course, it could be by `stylelint-use-logical` ([the issue](https://github.com/csstools/stylelint-use-logical/pull/22) was opened) but seems like compatibility layer between 15.x API and 16.x doesn’t work for every plugin.

All other plugins work with 16.x without a problem.

Feel free to close if it is because some strange or old API used by `stylelint-use-logical`.

**Comment by ybiquitous** [comment]
@ai Thanks for the report. I'll look into `stylelint-use-logical`.

**Comment by ybiquitous** [comment]
I've added a comment about details on <https://github.com/csstools/stylelint-use-logical/pull/22#issuecomment-1849017589>. The plugin can resolve this compatibility issue, so I'm closing this issue.
