### ISSUE TITLE
Version 16 & stylelint-config-standard-scss causing TypeError: Cannot read properties of undefined (reading 'rejected')

### ISSUE THREAD

**Issue by andrmoel** [stylelint/stylelint#7393]
### What minimal example or steps are needed to reproduce the bug?

Check out my repository: https://github.com/andrmoel/stylelint-bug

### What did you expect to happen?

It runs without issues

### What actually happened?

An error occurs

```
$ stylelint 'src/**/*.scss'
TypeError: Cannot read properties of undefined (reading 'rejected')
```

**Comment by JounQin** [comment]
https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/7dbcac2cf56849ea016321d6ce373db6bfcef65f/package.json#L47

**Comment by andrmoel** [comment]
Rel: https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/145

**Comment by JounQin** [comment]
Please search first before raising a new issue next time.
