### ISSUE TITLE
New rule: selector-pseudo-element-colon-notation

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#74]
Originally: `selector-pseudo-element-two-colons` `"always"|"never"`.

I was going to have a go at this one next. What do you guys think of renaming it to?:

`selector-pseudo-element-colon-notation` : `"single"|"double"`

As it feels like it has more in common with something like `string-quotes`: `"single"|"double"` as the values are explicit. Whereas "`never`" for `selector-pseudo-element-two-colons` *implies* only a single colon, which feel odd and in contrast to something clear like `declaration-block-trailing-semicolon` where `always` and `never` mean a semicolon must be present and must not be present respectively.

Also, there's [a lot](http://dev.w3.org/csswg/css-pseudo-4/) of pseudo-elements, but it looks like the single colon approach is [only valid for a handful of them](http://www.w3.org/TR/selectors4/#pseudo-elements), "namely: `:first-line`, `:first-letter`, `:before` and `:after`". Am I right in thinking this rule should only flag warnings against these four pseudo-elements and not the rest.

**Comment by davidtheclark** [comment]
Single vs double colon might be clarified by looking at the difference between [pseudo-classes](http://www.w3.org/TR/css3-selectors/#pseudo-classes) and [pseudo-elements](http://www.w3.org/TR/css3-selectors/#pseudo-elements), where only pseudo-elements get double-colons.

**Comment by MoOx** [comment]
Same as @davidtheclark
