### ISSUE TITLE
Error building Stylelint 4.3.3 with meteorhacks:npm

### ISSUE THREAD

**Issue by hoscb** [stylelint/stylelint#740]
Hi,

When I tried to install the latest stylelint 4.3.3, I get these errors.

```
  While building package npm-container:
   error: couldn't install npm package stylelint@4.3.3: Command failed: npm WARN engine get-stdin@5.0.1: wanted:
   {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})
   npm WARN engine postcss@5.0.16: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"1.4.28"})
   npm ERR! EEXIST, open '/home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock'
   File exists: /home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock
   Move it away, and try again. 
```

I have already install the latest node and npm. Appreciate if anyone could help me with this. Thanks.

**Comment by davidtheclark** [comment]
Your node is too old: `current: {"node":"0.10.40","npm":"1.4.28"}`

Whatever you thought worked when installing the latest node didn't seem to have worked. I'd suggest trying again.

**Comment by hoscb** [comment]
Hi david,

Thanks but I have checked my npm and its running the latest version 3.7.3. My node is running at 5.6.0.

**Comment by davidtheclark** [comment]
The error message you pasted above explicitly says that it's running node 0.10.40.

**Comment by jeddy3** [comment]
Also, it might be worth nuking your `.npm` folder as it's complaining about a `.lock` file:

```shell
npm ERR! EEXIST, open '/home/vagrant/.npm/bcc11fb1-babel-runtime-5-8-35-package-tgz.lock'
```

It looks like you're running `npm` from within vagrant. So I suggest double checking that you're updating the `npm` version within vagrant, rather than (if you are) updating the host one.

**Comment by hoscb** [comment]
Thanks guys. I have checked, I updated the one in Vagrant. 
Could it be that meteor is running its own version of node as well? 
I came across an article that said, meteor 1.2 is still using node 0.10.

**Comment by hoscb** [comment]
I solved my problem. My bad, I'm a noob when comes to ubuntu. I installed nodejs instead of node using the following commands:

```
curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
sudo apt-get install -y nodejs
```

Thanks guys!

**Comment by jeddy3** [comment]
No problem. Glad you got it working :)
