### ISSUE TITLE
Rule `color-hex-case` unexpectedly removed

### ISSUE THREAD

**Issue by fmigneault** [stylelint/stylelint#7400]
### What minimal example or steps are needed to reproduce the bug?

Just run stylelint with the rule defined.

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "color-hex-case": "upper",
  }
}
```

### How did you run Stylelint?

```shell
npx --no-install stylelint \
		--config "${APP_ROOT}/.stylelintrc.json" \
		--output-file "${REPORTS_DIR}/check-css.txt" \
		"${APP_ROOT}/**/*.css"
```

### Which Stylelint-related dependencies are you using?

Ran against 15.x (no error) and 16.x (error).

Here is my specific config, but I don't think those are relevant. 
```json
{
  "devDependencies": {
    "stylelint": "^14.15.0",
    "stylelint-config-standard": "^29.0.0",
    "remark-cli": "^11.0.0",
    "remark-gfm": "^3.0.1",
    "remark-lint": "^9.1.1",
    "remark-lint-checkbox-content-indent": "^4.1.1",
    "remark-lint-maximum-line-length": "^3.1.2",
    "remark-preset-lint-markdown-style-guide": "^5.1.2",
    "remark-preset-lint-recommended": "^6.1.2",
  }
}
```

### What did you expect to happen?

No error. 
Seems to be a rule that was mistakenly dropped from v16 refactor.

### What actually happened?

  1:1  ✖  Unknown rule color-hex-case. Did you mean color-hex-alpha, color-hex-length?  color-hex-case

### Do you have a proposal to fix the bug?

Revert the removed rule. 
Otherwise, at the very least, indicate how to migrate.
There are not referenced to deprecation of that rule, and even latest 15.x version applied performance improvements to it.

**Comment by ybiquitous** [comment]
@fmigneault Thanks for using the template.

Stylelint 16.0.0 removed the deprecated stylistic rules. Please read the migration guides. You can find alternatives there.
- https://stylelint.io/migration-guide/to-16#removed-deprecated-stylistic-rules
- https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules
