### ISSUE TITLE
vscode stylelint plugin: Unknown word (CssSyntaxError)Stylelint(CssSyntaxError)

### ISSUE THREAD

**Issue by zerobin** [stylelint/stylelint#7402]
I ended up removing all the custom configurations and found that it was the official version of the stylelint plugin for vscode that was turned on:
"stylelint.validate": ["css", "less", "postcss", "sass", "scss", "vue"], the vue version would have this problem
The stylelint version is the same no matter which

test code:
https://github.com/zerobin/stylelint-test

_Originally posted by @zerobin in https://github.com/stylelint/stylelint/issues/6832#issuecomment-1857272669_

**Comment by jeddy3** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using one of our templates.
