### ISSUE TITLE
Esm and commonjs suported package

### ISSUE THREAD

**Issue by Jordan-Hall** [stylelint/stylelint#7405]
### What minimal example or steps are needed to reproduce the bug?

In stylelint 16 you have rightly removed the support for commonjs. However I'm not sure if im packaging plugin wrong or if there something else.

https://github.com/Jordan-Hall/stylelint-use-logical-spec

For a long time I've used rollup to support both esm and commonjs without issue. However since v16 it's appears unable to find the rule.  Can anyone provide any help, it be nice to keep both so older version (until api changes) can be supported 

### What minimal configuration is needed to reproduce the bug?

Unknown rule liberty/use-logical-spec liberty/use-logical-spec

### How did you run Stylelint?

No

### Which Stylelint-related dependencies are you using?

Stylelint: 16

### What did you expect to happen?

I expect plugins to still be able to support commonjs as a output option

### What actually happened?

Unknown rule liberty/use-logical-spec liberty/use-logical-spec

**Comment by JounQin** [comment]
See https://github.com/csstools/stylelint-use-logical/pull/22#issuecomment-1849017589

**Comment by Jordan-Hall** [comment]
@JounQin  thank you! I only maintaining cause how out of spec it was for a while and PR wasn't accepted. Now people asking I'll get it sorted tonight thank you

**Comment by Mouvedia** [comment]
https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/e8a2c00444c21d3ca6007d59b7214267bcc4aab2/src/index.js#L40

**Comment by Jordan-Hall** [comment]
I think it's custool approach. Problem is I'm unsure there will accept prs. It took them 2 years to accept mine but by the time it happened the fork doubled the size of the original

**Comment by JounQin** [comment]
cc @stylelint/owners

**Comment by romainmenke** [comment]
I will fix any issues that are essentially the same bug under the `csstools` org.
I might not do so instantly and I will need to coordinate with Jonathan Neal.
