### ISSUE TITLE
Fix `ERR_UNSUPPORTED_ESM_URL_SCHEME` for  `--custom-formatter` on Windows

### ISSUE THREAD

**Issue by Senderek** [stylelint/stylelint#7428]
### What minimal example or steps are needed to reproduce the bug?

System: Windows
Run `stylelint "./src/**/*.scss" --custom-formatter stylelint-formatter.js`
The important part is to add a custom formatter argument, without it it works fine.
The code for a custom formatter can be copy-pasted from here: https://stylelint.io/developer-guide/formatters/

### What minimal configuration is needed to reproduce the bug?

Any I believe

### How did you run Stylelint?

` "lint:sass-devops": "stylelint \"./src/**/*.scss\" --custom-formatter ./stylelint-formatter-azuredevops.cjs",` command from npm.

### Which Stylelint-related dependencies are you using?

```
        "stylelint": "^16.1.0",
        "stylelint-config-standard-scss": "^12.0.0",
        "stylelint-no-unsupported-browser-features": "^7.0.0",
        "stylelint-order": "^6.0.4",
        "stylelint-scss": "^6.0.0",
```

### What did you expect to happen?

The command runs fine.

### What actually happened?

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:406:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:216:11)
    at defaultLoad (node:internal/modules/esm/load:118:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:396:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:290:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:248:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:229:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:315:23)
```

### Do you have a proposal to fix the bug?

I believe a similar bug has already been fixed for the main command, so maybe it is a matter of applying it to the arguments as well:
https://github.com/stylelint/stylelint/issues/7382
https://github.com/stylelint/stylelint/releases/tag/16.0.2

**Comment by jeddy3** [comment]
@Senderek Thanks for the report.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

It's likely we'll need to use our new `dynamicImport` util when we import custom formatters:

https://github.com/stylelint/stylelint/blob/58822901ab032b6cc3dd9515b64958202a460a30/lib/cli.mjs#L602-L609

**Comment by JounQin** [comment]
Working on it.

**Comment by jeddy3** [comment]
@Senderek Please can you try the fix branch and let us know if it resolves the issue for you:

```
npm i -D stylelint/stylelint#fix/import_esm_win
```

**Comment by Senderek** [comment]
Hello, thank you for the quick reply.

> @Senderek Please can you try the fix branch and let us know if it resolves the issue for you:
> 
> ```
> npm i -D stylelint/stylelint#fix/import_esm_win
> ```

I can confirm it's working (on my machine). Thank you.
