### ISSUE TITLE
Add `gitlab` formatter

### ISSUE THREAD

**Issue by tijsverkoyen** [stylelint/stylelint#7430]
### What is the problem you're trying to solve?

There is no formatter for `gitlab`.

Gitlab is able to report code quality issues. But it requires the errors, warnings to be reported in a specific format.

There is a package [Stylelint formatter for Gitlab](https://gitlab.com/leon0399/stylelint-formatter-gitlab) that makes this somewhat possible. But at the moment this package is broken: [Support stylelint 16.0.0 and upwards](https://gitlab.com/leon0399/stylelint-formatter-gitlab/-/issues/3)

### What solution would you like to see?

As there is already a formatter for `github` included, it would be nice if a `gitlab` formatter would be available.

**Comment by jeddy3** [comment]
@tijsverkoyen Thank you for the issue and pull request.

It makes sense to treat GitLab and GitHub the same. However, in hindsight, we probably shouldn't have added a formatter to the core for a commercial product like GitHub. 

I believe we have a couple of options that treat GitLab and GitHub (and other commercial products) the same:

1. Merge this formatter and keep it (and the GitHub one) forever (and add other commercial competitors)
2. Merge this formatter and then deprecate both formatters in favour of `--custom-formatter`
3. Don't merge this formatter and deprecate the GitHub (and perhaps other formatters too)

Interestingly, ESLint is [stripping back their bundled formatters for 9.0.0](https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/#removing-all-formatters-except-stylish%2C-html%2C-json%2C-and-json-with-meta) to reduce their bundle size.

Our formatters are generally small (except for our default `string` formatter which uses `table`) so we'll likely base our decision on whether we want to continue adding formatters for commercial products or not.

@tijsverkoyen If we decide to go with the third option, you can publish the code within your PR as a [custom formatter](https://stylelint.io/developer-guide/formatters).

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for summarizing this discussion. To prevent the bundle size from increasing, I agree with the 3. option:

> Don't merge this formatter and deprecate the GitHub (and perhaps other formatters too)

I can create a 3rd-party package for the GitHub formatter.

**Comment by tijsverkoyen** [comment]
I understand the discussion from a maintainer point of view.
But in my humble opinion with the `github` and `gitlab` formatters the majority of "commercial"/most used platforms are covered.

I will look into publishing a custom formatter.

**Comment by tijsverkoyen** [comment]
If a 3rd-party package for the GitHub formatter is created I think it would be a good idea to mention it in the documentation. And maybe also link to other "known" custom formatters.

**Comment by ybiquitous** [comment]
> If a 3rd-party package for the GitHub formatter is created I think it would be a good idea to mention it in the documentation.

I think so, too. It's [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint#formatters), which has a link list for 3rd-party formatters.

**Comment by jeddy3** [comment]
It'll appear on the website too:
https://stylelint.io/awesome-stylelint

I'll close this issue. @tijsverkoyen Thank you again for the issue and for opening a PR.  If you publish a new GitLab formatter package with the code from the PR, please send a PR to Awesome Stylelint to help people discover it.
