### ISSUE TITLE
ESLint 2.0.0

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#744]
Stylelint's ESLint shared config `eslint-config-stylelint` has been updated to support ESLint 2.0.0

• https://github.com/stylelint/eslint-config-stylelint

- [x] Publish new `eslint-config-stylelint` version to npmjs.com
- [x] Verify ESLint 2.0.0 `stylelint` compatibility

**Comment by ntwb** [comment]
Currently there are 183 instances of 1 single rule failure when testing this:
•  `error  Strings must use doublequote  quotes`

Running `eslint --config stylelint src/** --fix` results in [eslint2quotes.diff](https://gist.github.com/ntwb/0cdc9668aeb21afc5768)

The majority are due to using backticks rather than double quotes to avoid escaping, e.g:
```diff
-    t.equal(result.warnings()[0].text, `Expected "#eee" to be "#EEE" (color-hex-case)`)
+    t.equal(result.warnings()[0].text, "Expected \"#eee\" to be \"#EEE\" (color-hex-case)")
```

`eslint-config-stylelint` currently defines the `quotes` rule as `double`, the ESLint rule has a [secondary option]() `avoid-escape`:

> "The second option is the "avoid-escape" flag. When using "avoid-escape", this rule will not report a problem when a string is using single-quotes or double-quotes so long as the string contains a quote that would have to be escaped otherwise. For example, if you specify "double" and "avoid-escape", the string 'He said, "hi!"' is not considered a problem because using double quotes for that string would require escaping the double quotes inside of the string. This option is off by default."

I see two options:

1. Create an upstream issue with ESLint to support backticks with the secondary option `avoid-escape`, i.e:
> "...this rule will not report a problem when a string is using **backticks**, single-quotes or double-quotes so long as the string contains a quote that would have to be escaped otherwise.

1. Replace stylelint's use of backticks with single quotes for the above 183 instances

**Comment by ntwb** [comment]
Ah, here, already being discussed https://github.com/eslint/eslint/issues/5234

**Comment by ntwb** [comment]
Just tested the ESLint 2.x `eslint-config-stylelint` config with each of these repos and all passed: :+1: 
• `eslint-config-stylelint`
• `stylelint-config-cssrecipes`
• `stylelint-config-standard`
• `stylelint-config-suitcss`
• `stylelint-config-wordpress`
• `stylelint-rule-tester`

**Comment by jeddy3** [comment]
> Just tested the ESLint 2.x eslint-config-stylelint config 

Good stuff!

Lets wait for the outcome of that upstream eslint issue before taking any action within the main `stylelint` repo.

**Comment by jeddy3** [comment]
I'm now wondering whether this has correctly caught our inconsistent use of quotes and backticks i.e. we escape double quotes in some places and use backticks in others.

@davidtheclark What do you think? I'm happy to do the legwork on this i.e. I think there might be one or two tests that need tweaking after running the fix. It'd be nice to get the new config (with `no-console`) in before the next release.

**Comment by davidtheclark** [comment]
We have to be able to use quotes inside backticks. Quotes of both types, unescaped. I thought the ESLint bug was preventing the *correct* use of quotes in backticks.

**Comment by davidtheclark** [comment]
That said, feel free to give it a shot and see if you can get it to work.

**Comment by jeddy3** [comment]
> We have to be able to use quotes inside backticks. Quotes of both types, unescaped. 

Yep, that's fine. I don't think it's complaining about that.

I think it's complaining because we're doing `const string = "double quoted string with escaped \" in it"` sometimes and other times we're doing ``const string = `backtick string with " in it` `` for *single line strings that don't use interpolation*. If the string spans multiple lines  or use interpolation it doesn't complain about the backticks.

I think the upstream proposal is to offer options for this *more lenient* style. We can either wait for that, or adopt the default stricter stance i.e. only using backticks for multi-line string or those that use interpolation.

If that sounds about right to you? I can give it a shot :)

**Comment by davidtheclark** [comment]
Go for it.
