### ISSUE TITLE
Fix `Error: Could not find <package>` message clarity

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#7448]
### What minimal example or steps are needed to reproduce the bug?

```
npm i stylelint
```

(Note that I didn't install the standard config.)

### What minimal configuration is needed to reproduce the bug?

```
{
  "extends": ["stylelint-config-standard"]
}
```

### How did you run Stylelint?

```shell
npx stylelint "test.css"
```

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.1.0"
}
```

### What did you expect to happen?

To get an error message informing me that I probably forgot to install the shared config.

Ref: https://github.com/stylelint/stylelint/issues/7445

### What actually happened?

I got:

```console
Error: Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?
```

### Do you have a proposal to fix the bug?

Reword the error message for the more common use case of a missing package, whereas a local config needing `configBasedir` is uncommon.

```console
Error: Could not find "stylelint-config-standard". Do you need to install the package or use the "configBasedir" option?
```

**Comment by ybiquitous** [comment]
Nice idea. 👍🏼
