### ISSUE TITLE
ruleName exposing error

### ISSUE THREAD

**Issue by ulanfermann** [stylelint/stylelint#7458]
### What minimal example or steps are needed to reproduce the bug?

Running the command

stylelint "src/main/webpack/**/*.scss" --ignore-path .stylelintignore

in terminal, or per package.json script when trying to commit, leads to the error shared in the field "What actually happened?".

My colleagues do not have this issue and can commit the same scss code that I am trying to commit.

### What minimal configuration is needed to reproduce the bug?

.stylelintrc.json contents:
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-prettier-scss"
  ],
  "rules": {
    "selector-class-pattern": null
  }
}

.stylelintignore contents:
plop-templates
src/main/webpack/core-components/
src/main/webpack/styles/reset.scss
src/main/webpack/site/scss/_grid.scss
src/main/webpack/site/scss/_mixins.scss
src/main/webpack/site/scss/_normalize.scss

### How did you run Stylelint?

When trying to commit the below command is executed, also when using this command in terminal I get the same error:

stylelint "src/main/webpack/**/*.scss" --ignore-path .stylelintignore

### Which Stylelint-related dependencies are you using?

    "stylelint": "^15.10.2",
    "stylelint-config-prettier-scss": "^1.0.0",
    "stylelint-config-standard-scss": "^9.0.0",
    
    I also tried with the newest stylelint version with no difference in the outcome

### What did you expect to happen?

To be able to commit or to run stylelint without an error. 

### What actually happened?

✖ stylelint:
Error: stylelint requires plugins to expose a ruleName. The plugin "...\node_modules\stylelint-scss\dist\index.js" is not doing this, so will not work with stylelint. Please file an issue with the plugin.

### Do you have a proposal to fix the bug?

The error is self.referral, so I hope exposing a ruleName in the "stylelint-scss\dist\index.js" would fix this issue

**Comment by ybiquitous** [comment]
@ulanfermann Thanks for using the template. `stylelint` and `stylelint-config-standard-scss` in your `package.json` are outdated. Can you update them? Also, if you provider a minimal reproducible repo for this problem, we might be able to address it.

We can see the outdated packages by the following code and operation:

```json
{
  "dependencies": {
    "stylelint": "^15.10.2",
    "stylelint-config-prettier-scss": "^1.0.0",
    "stylelint-config-standard-scss": "^9.0.0"
  }
}
```

```sh-session
$ npm i
...

$ npm outdated
Package                         Current   Wanted  Latest  Location                                     Depended by
stylelint                       15.11.0  15.11.0  16.1.0  node_modules/stylelint                       foo
stylelint-config-standard-scss    9.0.0    9.0.0  13.0.0  node_modules/stylelint-config-standard-scss  foo
```

**Comment by ulanfermann** [comment]
Hi @ybiquitous , thanks a lot for your quick reply. I also tried running the command with the newest stylelint versions:

    "stylelint": "^16.1",
    "stylelint-config-prettier-scss": "^1.0.0",
    "stylelint-config-standard-scss": "^13.0.0",
    
 But I am running into the exact same issue.
 
 I prepared a minimal reproducible repo where I can reproduce the error locally:
 
 https://github.com/ulanfermann/ruleNameExposingError

The repo only consists of node_modules, an scss file, package.json/package-lock.json and .stylelintrc.json

**Comment by ybiquitous** [comment]
@ulanfermann Thanks for the reproducible repo. But it includes the old version of `stylelint` regardless of `package.json`:

```json
  "name": "stylelint",
  "version": "15.11.0",
```

https://github.com/ulanfermann/ruleNameExposingError/blob/9e945f808144b7f082ad8ab86730e5521c0ca969/node_modules/stylelint/package.json#L2-L3

**Comment by ulanfermann** [comment]
Hi @ybiquitous , sorry for that. You now have a repo to reproduce the error with the current stylelint versions at the same place

**Comment by jeddy3** [comment]
> You now have a repo to reproduce the error with the current stylelint versions at the same place

The versions don't match on `main`.

In your `package.json`:

https://github.com/ulanfermann/ruleNameExposingError/blob/fb8ed51b6d876afae285b3ad6ea7886fcec5c666/ui.frontend/package.json#L102C5-L102C26

```
 "stylelint": "^16.1",
```

In `node_modules`:

https://github.com/ulanfermann/ruleNameExposingError/blob/fb8ed51b6d876afae285b3ad6ea7886fcec5c666/ui.frontend/node_modules/stylelint/package.json#L3

```
"version": "15.11.0",
```

Can you make a reproducible repo with only Stylelint related dependencies, please?

You can ensure you're using the latest version of each package by using `@latest`, e.g. `npm install -D stylelint@latest`.

**Comment by ulanfermann** [comment]
Hi @jeddy3 , thanks for your reply. I reduced the repo as far as I can and updated to the latest version as recommended. Now I am running into a different error:

TypeError: Cannot read properties of undefined (reading 'rejected')

I've seen that this error was reported in another issue, but as far as I can see as solution it was recommended to update to the newest stylelint version, that didn't work for me

**Comment by jeddy3** [comment]
Try the latest version of all the stylelint related package:

```
npm install -D stylelint@latest
npm install -D stylelint-config-prettier-scss@latest
npm install -D stylelint-config-standard-scss@latest
```

And so on.

I'll close as the original issue wasn't reproducible with the latest version of Stylelint.

You're welcome to open a new issue with the _smallest possible_ reproducible example, if the above advice doesn't solve the `TypeError: Cannot read properties of undefined (reading 'rejected')` issue for you.

**Comment by ulanfermann** [comment]
Hi @jeddy3 , this solved the issue, I am finally able to commit. Thank you for your help!
