### ISSUE TITLE
Fix handling of plugins that are hybrid CommonJS and ESM packages

### ISSUE THREAD

**Issue by henryruhs** [stylelint/stylelint#7460]
### What minimal example or steps are needed to reproduce the bug?

The stylelint plugin that I build with rollup outputs a `index.cjs` and `index.mjs` file.

In `package.json` file:

```
"main": "index.cjs",
"module": "index.mjs"
```

# Package structure

![grafik](https://github.com/stylelint/stylelint/assets/1835397/359324bb-5118-470d-bf1e-1926d7997a4f)

### What did you expect to happen?

Stylelint 15 takes the `cjs` file and Stylelint 16 the `mjs` file

### What actually happened?

```
CommonJS plugins are deprecated ("/home/.../.../node_modules/@isnotdefined/stylelint-plugin/index.cjs")
```

Related issue: https://github.com/isnotdefinedcom/stylelint-plugin/issues/14

**Comment by JounQin** [comment]
I'll take a look on this.

**Comment by henryruhs** [comment]
Updates on this?

**Comment by ybiquitous** [comment]
@henryruhs Can you provide more details on the problem in your plugin? What do you expect?

**Comment by JounQin** [comment]
`module` is not a standard property for ESM, you need to use `exports` instead.

**Comment by henryruhs** [comment]
From my knowledge, the hybrid approach that I picked is valid. Stylelint ignores the ESM module entry point.

I'm probably too much of a TypeScript person and remember that "exports" are not supported.

What are we doing now? Should I just follow your advice or do you plan to investigate?

**Comment by henryruhs** [comment]
@JounQin I reopen the issue... this is loading the common.js version again.

```
"exports":
{
	"require": "index.cjs",
	"import": "index.js"
},
```

**Comment by JounQin** [comment]
@henryruhs 

Thanks for your investigation, I'm taking a look.

**Comment by henryruhs** [comment]
@JounQin You can used my failed approach: https://www.npmjs.com/package/@isnotdefined/stylelint-plugin/v/4.0.0-fix.1

**Comment by JounQin** [comment]
<img width="446" alt="image" src="https://github.com/stylelint/stylelint/assets/8336744/7ccb31d7-c975-4011-a26e-b3188a8df74e">

<img width="987" alt="image" src="https://github.com/stylelint/stylelint/assets/8336744/66144b75-57ac-4561-8197-bea809cfaa31">

I find another issue...

**Comment by JounQin** [comment]
<img width="1708" alt="image" src="https://github.com/stylelint/stylelint/assets/8336744/c4cc58f1-1154-449e-bd8f-df4fbb398b25">

@henryruhs OK

The `exports` should be

```json
{
  "exports": {
    "require": "./index.cjs",
    "import": "./index.js"
  }
}
```

**Comment by henryruhs** [comment]
There is no need for the ./ as the files are in the root.

The code of `4.0.0-fix.1` looked exact like you suggested: https://github.com/isnotdefinedcom/stylelint-plugin/commit/76febb3cb9ab464c158008caff96a4c88ea46f40

**Comment by JounQin** [comment]
@henryruhs 

> There is no need for the ./ as the files are in the root.

No, `./` is required AFAIK.

**Comment by henryruhs** [comment]
I disagree... the problem is not resolving the path - it's selecting the wrong package.

**Comment by JounQin** [comment]
> I disagree... the problem is not resolving the path - it's selecting the wrong package.

Did you see my comment?

> The issue here is, [resolve-from](https://github.com/sindresorhus/resolve-from) is a plain commonjs package, so it will resolve hybrid packages as commonjs, what means commonjs is preferred over ESM. I'll find better solution.

**Comment by henryruhs** [comment]
Don't use packages by this guy, he created thousands of them and there is no change he can maintain them all.

**Comment by ybiquitous** [comment]
@henryruhs Just to be sure, `@isnotdefined/stylelint-plugin@5.0.0` has resolved this problem, right?

**Comment by JounQin** [comment]
@ybiquitous That only resolves on the plugin's side with pure ESM only support, hybrid package will still warn about the deprecation message.

**Comment by henryruhs** [comment]
I did not resolve it, just limited it to ESM.

**Comment by ybiquitous** [comment]
Can you provide a reproducible demo/code with `@isnotdefined/stylelint-plugin@5.0.0`?

**Comment by henryruhs** [comment]
There is this tiny Angular playground that I just updated via my smartphone.

It uses my stylelint config which loads the stylelint plugin.

https://github.com/henryruhs/ngx-crud-playground

**Comment by JounQin** [comment]
Notice, `4.0.0-fix.1` is required for reproduction, `5.0.0` is an ESM only package now.

**Comment by ybiquitous** [comment]
Thanks. I can now reproduce the deprecation warning with the patched `@isnotdefined/stylelint-plugin@4.0.0-fix.1` 👍🏼 

```diff
--- node_modules/@isnotdefined/stylelint-plugin/package.json.orig	2024-02-21 13:20:26
+++ node_modules/@isnotdefined/stylelint-plugin/package.json	2024-02-21 13:19:57
@@ -62,7 +62,7 @@
 	},
 	"exports":
 	{
-		"require": "index.cjs",
-		"import": "index.js"
+		"require": "./index.cjs",
+		"import": "./index.js"
 	}
 }
```

`package.json`:

```json
{
  "dependencies": {
    "@isnotdefined/stylelint-plugin": "4.0.0-fix.1",
    "stylelint": "16.2.1"
  }
}
```

`.stylelintrc.json`:

```json
{
  "plugins": ["@isnotdefined/stylelint-plugin"],
  "rules": {"@isnotdefined/no-disable": true}
}
```

Run:

```sh-session
$ echo 'a{}' | npx stylelint
CommonJS plugins are deprecated ("/Users/masafumi.koba/tmp/foo/node_modules/@isnotdefined/stylelint-plugin/index.cjs"). See https://stylelint.io/migration-guide/to-16
```

So, I understand the problem that `resolve-from` returns a CJS file of the package, E.g.

```sh-session
$ node -pe "require('resolve-from').silent(process.cwd(), '@isnotdefined/stylelint-plugin')"
/Users/masafumi.koba/tmp/foo/node_modules/@isnotdefined/stylelint-plugin/index.cjs
```

**Comment by JounQin** [comment]
Yes, that's what I said at https://github.com/stylelint/stylelint/issues/7460#issuecomment-1953991359

**Comment by jpzwarte** [comment]
FYI: this happens with the `stylelint-use-logical` package which supports both CJS & ESM:

```
CommonJS plugins are deprecated (".../node_modules/stylelint-use-logical/index.cjs"). See https://stylelint.io/migration-guide/to-16
```

Using `stylelint-use-logical@2.1.2` and `stylelint@16.2.1`

See https://github.com/csstools/stylelint-use-logical/issues/25

**Comment by JounQin** [comment]
@jpzwarte #7532 will fix this issue.
