### ISSUE TITLE
Document CLI piping example

### ISSUE THREAD

**Issue by lucavb** [stylelint/stylelint#7467]
### Describe the documentation issue

The documentation states that authors of custom formatters may use their custom formatters like so `stylelint -f json "*.css" | my-program-that-reads-JSON --option`. Alright, fair enough. Only issue being that this only works when `stylelint` finds no errors / warnings and thus writes to `STDIN`. If it finds warnings / errors, stylelint writes to `STDERR` (which is fine) but that is not covered by `|` just like that. 

You can try this yourself by running 

```shell
stylelint -f json -c test/config/.stylelintrc.json test/assets/*.scss >stdout.txt 2>stderr.txt
```

or trust my screenshot ^^
<img width="682" alt="Screenshot 2024-01-17 at 15 38 32" src="https://github.com/stylelint/stylelint/assets/5306815/c6ab8880-d0f8-42d5-9db3-d4fcb8194e81">

### What solution would you like to see?

Updating the documentation to 

```shell
stylelint -f json "*.css" 2>&1 | my-program-that-reads-JSON --option
```

would at least at the surface fix the problem for me. But maybe this produces other issues somewhere else that I am not aware of.

**Comment by lucavb** [comment]
If you are fine with this documentation update, then I can prepare a PR with the commit that I already prepared https://github.com/stylelint/stylelint/commit/f450cf4f9a69ae9cf8c325e1643a0e873cab12aa

**Comment by ybiquitous** [comment]
@lucavb Great catch! Can you open a pull request?

**Comment by ybiquitous** [comment]
In addition, although this is nice to have, adding a new example for piping to [examples in the CLI guide](https://github.com/stylelint/stylelint/blob/d881c9df941d22a8cdc52bbd13e1b1900b0f95f8/docs/user-guide/cli.md#usage-examples) seems nice, too.

**Comment by lucavb** [comment]
> In addition, although this is nice to have, adding a new example for piping to [examples in the CLI guide](https://github.com/stylelint/stylelint/blob/d881c9df941d22a8cdc52bbd13e1b1900b0f95f8/docs/user-guide/cli.md#usage-examples) seems nice, too.

I added another commit to the PR :0
