### ISSUE TITLE
Comment got duplicated when put above a SCSS dollar variable

### ISSUE THREAD

**Issue by weebao** [stylelint/stylelint#7494]
### What minimal example or steps are needed to reproduce the bug?

```scss
// Comment
$variable: 1rem;
```

### What minimal configuration is needed to reproduce the bug?

None

### How did you run Stylelint?

```
stylelint \"src/**/*.scss\" --fix
```

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "^16.2.0"
}
```

### What did you expect to happen?

```scss
// Comment
$variable: 1rem;
```

### What actually happened?

```scss
// Comment
$variable: 1rem;Comment$variable
```

### Do you have a proposal to fix the bug?

It might have been something with the dollar variable configuration of stylelint. I will take a look.

**Comment by Mouvedia** [comment]
related: #7429

**Comment by jeddy3** [comment]
@weebao You should use a custom syntax when linting anything besides vanilla CSS.

From the [getting started guide](https://stylelint.io/user-guide/get-started#linting-css-like-languages-and-css-within-containers):

> For example, to lint SCSS you can extend the [SCSS community config](https://www.npmjs.com/package/stylelint-config-standard-scss). It includes the:
> - [SCSS syntax](https://www.npmjs.com/package/postcss-scss) - a custom syntax to parse SCSS
> - [SCSS plugin](https://www.npmjs.com/package/stylelint-scss) - a set of custom rules for SCSS

---

> related: https://github.com/stylelint/stylelint/issues/7429

I hope to find time later this week or at the weekend to pull these threads together. It seems [we made a change in `16.0.0`](https://github.com/stylelint/stylelint/pull/7357) that makes Stylelint less forgiving when the syntax is misconfigured.

**Comment by Mouvedia** [comment]
> > related: #7429
> 
> I hope to find time later this week or at the weekend to pull these threads together. It seems [we made a change in `16.0.0`](https://github.com/stylelint/stylelint/pull/7357) that makes Stylelint less forgiving when the syntax is misconfigured.

> `…you should use the "customSyntax" option when linting something other than CSS`

warning used to be outputted when you had a `CssSyntaxError` in version 15.11.0.
1e8517ec219f98d351b14663add9f85dcb8c8a01 is probably the _guilty_ commit.

**Comment by ybiquitous** [comment]
Here's a [online demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEkC2GYDsAuAOjgCQBmEE8qAjAE4wYDcRIANCKQJYA2MAcgENsCEHhgBnPADpxYceLbgIOLgHMRwIqlQEQtAK69xuqppzbtunBAC0nHADcB3TlBtQI+gEa8b47gLiABY2mNj4xgioeAYwWqgAvkQJipAqnKoAYhC0GAJ4IgBW4sqKsAAOCohmliCSAJ68LvgmOiDUAGxSAExSAAy6ySAJQA). It raises a syntax error. So, specifying `customSyntax: postcss-scss` is correct, as @jeddy3 suggested.

But [`no-invalid-double-slash-comments`](https://stylelint.io/user-guide/rules/no-invalid-double-slash-comments) autofix seems to have a problem.

**Comment by weebao** [comment]
> Here's an [online demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0SAEkC2GYDsAuAOjgCQBmEE8qAjAE4wYDcRIANCKQJYA2MAcgENsCEHhgBnPADpxYceLbgIOLgHMRwIqlQEQtAK69xuqppzbtunBAC0nHADcB3TlBtQI+gEa8b47gLiABY2mNj4xgioeAYwWqgAvkQJipAqnKoAYhC0GAJ4IgBW4sqKsAAOCohmliCSAJ68LvgmOiDUAGxSAExSAAy6ySAJQA). It raises a syntax error. So, specifying `customSyntax: postcss-scss` is correct, as @jeddy3 suggested.
> 
> But [`no-invalid-double-slash-comments`](https://stylelint.io/user-guide/rules/no-invalid-double-slash-comments) autofix seems to have a problem.

Yep it also raises a syntax error but the incorrect autofix was still applied.  As you and @jeddy3 said, seems like `customSyntax: postcss-scss` stopped it. Thank you!

**Comment by Mouvedia** [comment]
@ybiquitous should we add back the warning?

**Comment by ybiquitous** [comment]
@Mouvedia how can we warn? Do you have any idea?

**Comment by Mouvedia** [comment]
see https://github.com/stylelint/stylelint/commit/1e8517ec219f98d351b14663add9f85dcb8c8a01#diff-5a796b3daf3cbd1194a107ee4510d9c802312af9c7487158cd203e6b3f92caf9L135

**Comment by ybiquitous** [comment]
Do you mean checking a file extension? I guess doing that is not so good because:

- maintaining an extensions list is troublesome
- a file extension does not have enough information for syntax; e.g. a SCSS code *may* be a compatible CSS code

**Comment by Mouvedia** [comment]
> a SCSS code may be a compatible CSS code

We have a CSS syntax error so we ought to tell that it's not compatible—or at least we used to.
BTW unlike https://stylelint.io/demo, in the console `npx stylelint file.scss --fix` doesn't output anything.
i.e. the CSS syntax error is not evident/reported

**Comment by ybiquitous** [comment]
> BTW unlike [stylelint.io/demo](https://stylelint.io/demo), in the console `npx stylelint file.scss --fix` doesn't output anything.

I'm afraid, isn't it correct? The following is a try on my console:

```sh-session
$ cat foo.scss
// comment
$foo: 1rem;

$ cat .stylelintrc.json
{
  "rules": {
    "no-invalid-double-slash-comments": true
  }
}

$ npx stylelint foo.scss --fix

foo.scss
 1:1  ✖  Unexpected double-slash CSS comment  no-invalid-double-slash-comments

1 problem (1 error, 0 warnings)

$ npx stylelint -v
16.2.0
```

**Comment by Mouvedia** [comment]
Here's mine:

```json
{
  "rules": {
    "comment-no-empty": true
  }
}
```

```css
// Comment
$variable: 1rem;
```

```sh
npx stylelint file.scss --fix
```

which reproduces OP.

**Comment by ybiquitous** [comment]
Hum, there is some difference between console and demo. My example didn't output a syntax error, but a rule error, too.
So, I'll look into a problem in the demo. It's another problem.

In the case of console, I still don't want to rely on a file extension to determine a syntax. But I welcome other way.

**Comment by ybiquitous** [comment]
For reference, the difference between `--fix` and non `--fix` depends on `postcss-safe-parser`:

https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/lib/getPostcssResult.mjs#L127

**Comment by ybiquitous** [comment]
I've opened an issue #7497.
