### ISSUE TITLE
Add `--fix=lax` and `--fix=strict`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7497]
### What minimal example or steps are needed to reproduce the bug?

Analyzing a CSS file with an invalid syntax raises a syntax error expectedly, while doing the same specifying `--fix` succeeds unexpectedly.

`test.css`:

```css
// comment
```

---

For reference, this behavior difference depends on [`postcss-safe-parser`](https://www.npmjs.com/package/postcss-safe-parser):

https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/lib/getPostcssResult.mjs#L127

Note: we found this problem in #7494.

### What minimal configuration is needed to reproduce the bug?

```json
{"rules": {}}
```

### How did you run Stylelint?

Run the following commands in my console.

```sh-session
$ npx stylelint test.css

test.css
 1:1  ✖  Unknown word  CssSyntaxError

1 problem (1 error, 0 warnings)

$ npx stylelint test.css --fix

$ echo $?
0
```

### Which Stylelint-related dependencies are you using?

`package.json`:

```json
{
  "dependencies": {
    "stylelint": "16.2.0"
  }
}
```

### What did you expect to happen?

Expect to raise a syntax error. E.g.

```sh-session
$ npx stylelint test.css --fix

test.css
 1:1  ✖  Unknown word  CssSyntaxError

1 problem (1 error, 0 warnings)
```

### What actually happened?

A syntax error does not happen, and then Stylelint exits normally. E.g.

```sh-session
$ npx stylelint test.css --fix

$ echo $?
0
```

### Do you have a proposal to fix the bug?

1. do something similar to https://github.com/noahbrenner/xo/blob/8e4f4355c4b8e62bc28f37e3673bb6872e693bb0/main.js#L119-L133

2. update [fix option](https://stylelint.io/user-guide/options/#fix)

`true` maps to `"lax"`
`false` doesn't change
`"lax"` aliases to `true`
`"strict"` added

**Comment by Mouvedia** [comment]
I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.

**Comment by ybiquitous** [comment]
I looked into the introduction of `postcss-safe-parser`. The PR was #2886.

`postcss-safe-parser` can fix syntax errors like this:

```sh-session
$ echo 'a {' | npx stylelint

<input css 1>
 1:1  ✖  Unclosed block  CssSyntaxError

1 problem (1 error, 0 warnings)


$ echo 'a {' | npx stylelint --fix
a {
}%
```

Of course, this package cannot fix some syntax errors like `// comment`:

```sh-session
$ echo '// comment' | npx stylelint

<input css 1>
 1:1  ✖  Unknown word  CssSyntaxError

1 problem (1 error, 0 warnings)


$ echo '// comment' | npx stylelint --fix
// comment
```

For now, I cannot find a solution, but let us know if anyone has some information.

**Comment by ybiquitous** [comment]
For reference, an incomplete comment like `/* comment` is fixable:

```sh-session
$ echo '/* comment' | npx stylelint --fix
/* comment
*/%
```

**Comment by Mouvedia** [comment]
What about some heuristics based on the previous iteration that switch between `postcss.parse` and `postcss-safe-parser`?
i.e. a _partial_ revert of #7357

**Comment by ybiquitous** [comment]
That heuristics use file extensions supporting the `//` comment form (e.g. `.scss`, `.less` etc.), right? I think the way is against our standard CSS preferred policy:

https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/docs/developer-guide/rules.md?plain=1#L13

**Comment by Mouvedia** [comment]
The alternative of not using `postcss-safe-parser` for `--fix` is worse though.

The worst that can happen with the partial revert is having someone using CSS-compatible code in a scss file that would trigger the warning erroneously. In that case it's just a matter of detecting the absence of CSS syntax error and adding an hint regarding the possibility of changing the extension.

The list maintenance is not a strong argument against it IMHO.
It's either a blacklist—e.g. sss, sass, scss, styl, less—or the previous whitelist [plus `mcss`](https://github.com/stylelint/stylelint/issues/7116).
In both cases, it won't probably be touched for years because it covers most use cases.
i.e. the regression of the DX matters more than strictly enforcing our policy

**Comment by ybiquitous** [comment]
Hum..., I'm still concerned that the file extension list based on heuristics may grow at people's request. In addition, if we'd like to remove the list itself or some extensions from the list, we must care about backward compatibility.

First of all, performing autofix first is an edge case, right? I believe normal use cases are below:

1. Run `stylelint test.scss` -> raises a syntax error.
2. Then, most users should notice something wrong with their code.

Furthermore, we encourage using the `customSyntax` option in the "Getting started" guide:

https://github.com/stylelint/stylelint/blob/382961fb6eb67557910a1ff7430a7a180f888bcc/docs/user-guide/get-started.md?plain=1#L57

So, I doubt the worth of this heuristic, though ideally, the bug should not exist.

**Comment by ybiquitous** [comment]
For reference, we previously removed an inaccurate syntax inference (heuristic) with PR #6645.

**Comment by Mouvedia** [comment]
That one looks more like something I wouldn't recommend we maintain, I agree for _that_ list.

**Comment by ybiquitous** [comment]
Also, we can revisit if a better solution is found.

**Comment by Mouvedia** [comment]
> Also, we can revisit if a better solution is found.

What about a new flag?
i.e. `--validate-syntax` or `--force-validation` which defaults to `false` when used with `--fix`

We could use a different validator for that flag or simply `postcss.parse`.
e.g. csstree has a [`validator plugin`](https://github.com/csstree/stylelint-validator)
In that regard the only criterium should be spec compliancy, not speed.
i.e. I would expect that passing the flag without `fix: true` could switch to a stricter validator

**Comment by Mouvedia** [comment]
> Also, we can revisit if a better solution is found.

What about a new flag?
i.e. `--validate-syntax` or `--force-validation` which defaults to `false` when used with `--fix`

We could use a different validator for that flag or simply `postcss.parse`.
e.g. csstree has a [`validator plugin`](https://github.com/csstree/stylelint-validator)
In that regard the only criterium should be spec compliancy, not speed.
i.e. I would expect that passing the flag without `fix: true` could switch to a stricter validator
@romainmenke which one is the best in terms of strictness?

**Comment by Mouvedia** [comment]
Well it could be considered a feature instead of a bug fix.
For example it would fix #7631 by validating before all rules instead of specifically targetting `declaration-block-no-redundant-longhand-properties`.

**Comment by ybiquitous** [comment]
Agree with adding a note to the `--fix` doc. 👍🏼 

At this point, I'm not sure which is better: stricter autofix (that is the same behavior with non-autofix) or laxer one (that can fix some syntax errors).

**Comment by Mouvedia** [comment]
> At this point, I'm not sure which is better: stricter autofix (that is the same behavior with non-autofix) or laxer one (that can fix some syntax errors).
> I doubt people rarely might use the flag... 🤔

I would vote for a third option: stricter than `postcss.parse` so that it picks up problems, like #7631, early.
Whether it's in highly desirable or its discoverability is potentially low is subjective.
We may need to add a _low priority_ label to cover such cases.

**Comment by ybiquitous** [comment]
Indeed, reporting problems like #7631 should be more important than fixing other type of syntax errors. 👍🏼 

So, I suggest:

- Add support values to `--fix`
  - `--fix=lax` (default; same as `--fix`) uses `postcss-safe-parser`
  - `--fix=strict` doesn't use `postcss-safe-parser`
- Make `--fix=strict` default in the next major version
- Remove `--fix=lax` in the future

Any thoughts?

**Comment by Mouvedia** [comment]
> Any thoughts?

It's elegant because it doesn't require a new flag.
I would support

- `--fix=lax` as you described, uses `postcss-safe-parser`
- `--fix=strict` uses `postcss` (as previously)
- `--fix=stricter` uses a stricter parser (to be chosen in a dedicated issue)

> * Make `--fix=strict` default in the next major version
> * Remove `--fix=lax` in the future

I don't have an opinion. As long as it's configurable I am satisfied.

**Comment by ybiquitous** [comment]
At this time, what is "a stricter parser"?

**Comment by Mouvedia** [comment]
> what is "a stricter parser"?

Let's say that as a prerequisite, it should take into account the values.
e.g. it throws for `a { border-style: foo; border-width: -1px; }` but validates `a { -webkit-line-clamp: none; }`

It's a can of worms if the dependency is not well maintained but if `stricter` is considered experimental having edge cases would be acceptable.
i.e. if it's _that_ strict it might throw perfectly valid CSS erroneously

**Comment by romainmenke** [comment]
> what is "a stricter parser"?

> it throws for `a { border-style: foo; border-width: -1px; }` but validates `a { -webkit-line-clamp: none; }`

I would narrow the scope as much as possible so that it doesn't overlap with any other rule.

**Comment by Mouvedia** [comment]
> I would narrow the scope as much as possible so that it doesn't overlap with any other rule.

That would either
1. require the parser to have many option that we can disable or
2. to filter the errors in a switch-case (i.e. the parser provides a good granularity for the errors)

I would prefer 1. but I am pretty sure we won't find one, so 2. will be a hard requirement if we want to avoid overlaps.

**Comment by ybiquitous** [comment]
I also want to keep things simple. And, if the current `--fix` (lax) can produce invalid results, `--fix` should be strict. I think we should keep only `--fix` after making strict default in the future.

**Comment by Mouvedia** [comment]
Let's split this proposal into 2:

1. add `"strict"` and `"lax"` to the currently boolean flag `--fix`
2. define `"stricter"` precisely _and then_ add it

Concerning 2. I think that it's simpler to handle value position/type/enum validation when it matters (i.e. before `--fix`) than to add the validation for all affected rules one by one.

**Comment by ybiquitous** [comment]
Please read https://github.com/stylelint/stylelint/issues/7497#issuecomment-2075257705
I think it's better to provide only `--fix` finally.

**Comment by Mouvedia** [comment]
I am dropping my `"stricter"` proposal so that we can move on with the issue at hand.
For reference here's the issue that changed the parser: #7116

**Comment by Mouvedia** [comment]
I am dropping my `"stricter"` proposal so that we can move on with the issue at hand.
For reference here's the issue that proposed to change the parser: #7116
I have updated the _Do you have a proposal to fix the bug?_ section.

sindresorhus/meow#44 seems a blocker for this issue.
i.e. we want `--fix` to map to `--fix="lax"` so that existing code remains backward-compatible

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for sharing the Meow issue. Is there any workaround for the problem if Meow doesn't address it?

**Comment by Mouvedia** [comment]
There is, if you switch to ready to implement I will show you.

**Comment by ybiquitous** [comment]
Alright. I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.
