### ISSUE TITLE
Add ignore: "relative" option to exclude bolder and lighter in `font-weight-notation`

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#751]
font-weight for option: `bold`, `normal` are absoluted.
But `bolder` and `lighter` are relatived. I want to use `number`, but bolder and lighter are relative and may be used in code also.
https://developer.mozilla.org/ru/docs/Web/CSS/font-weight

**Comment by davidtheclark** [comment]
Sure. These would be `ignore` options, by convention.

**Comment by jeddy3** [comment]
I think "relative" [looks to be](https://drafts.csswg.org/css-fonts/#font-weight-prop) the _keyword_ to use for this option.

**Comment by jeddy3** [comment]
@evilebottnawi FYI, released in `4.4.0`.
