### ISSUE TITLE
Error: Unsupported URL Type "npm:": npm:string-width@^4.2.0

### ISSUE THREAD

**Issue by Turek** [stylelint/stylelint#7517]
### What minimal example or steps are needed to reproduce the bug?

```
bash-4.3$ npm install stylelint
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:string-width@^4.2.0
```

### What minimal configuration is needed to reproduce the bug?

Fresh project, empty `package.json` dependencies.

### How did you run Stylelint?

I try to install it on fresh project.

### Which Stylelint-related dependencies are you using?

None yet as I can't pass this step.

```
bash-4.3$ npm --version
5.6.0
bash-4.3$ node --version
v8.11.1
```

### What did you expect to happen?

It installs correctly.

### What actually happened?

```
bash-4.3$ npm install stylelint
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:string-width@^4.2.0
```

### Do you have a proposal to fix the bug?

Version ^15 installs correctly.
```
bash-4.3$ npm install stylelint@^15
+ stylelint@15.11.0
added 95 packages in 17.721s
```

**Comment by JounQin** [comment]
I don't think we support Node v8 for stylelint v15.

**Comment by Mouvedia** [comment]
FYI node 8 support was removed in version 13.

cf https://github.com/stylelint/stylelint/blob/main/CHANGELOG.md#1300
