### ISSUE TITLE
Support MUI CSS-in-JS style syntax

### ISSUE THREAD

**Issue by litera** [stylelint/stylelint#7523]
### What is the problem you're trying to solve?

I would like to use stylelint to lint my CSS-in-JS style definitions of my React application that uses MUI components. MUI provides complex styling scenarios how to *inline style* components, create your own styled components or even override MUI components' look/theme.

### What solution would you like to see?

These are the possible sources of CSS-in-JS styles in a MUI codebase, that linter should recognise and lint.

## `sx` component property ([MUI docs link](https://mui.com/system/getting-started/the-sx-prop/))
This is a kind of a DOM element inline styles definition
```jsx
// number only for dimensions, which get's translated to pixels where 1=8px (MUI theme default that can be changed)
<Box sx={{ margin: 1 }} /> 

// MUI supports shorthand CSS prop names (not mandatory to support in stylelint)
// https://mui.com/system/getting-started/the-sx-prop/#spacing
<Box sx={{ m: 1 }} />

// Theme configuration aware properties
<Box sx={{ margin: 1, gap: 1 }} /> // both equivalent to '8px'
<Box sx={{ borderRadius: 1 }} /> // equivalent to '4px'
<Box sx={{ width: 0.5 }} /> // equivalent to '50%'
<Box sx={{ width: 50 }} /> // equivalent to '50px'
<Box sx={{ typography: 'body1' }} /> // theme defines various named typography variants with full styling definitions
<Box sx={{ boxShadow: 1 }} /> // equivalent to theme => theme.shadows[1]
<Box sx={{ color: 'primary.main' }} /> // equivalent to theme => theme.palette.primary.main

// MUI theme defines responsive breakpoints and one can provide different CSS prop values for various screen sizes
<Box sx={{ m: { xs: 1, sm: 1.5, md: 2, lg: 2.5, xl: 3 } }} />

// Style definition as a callback
<Box sx={{ m: ({ theme, ownerState }) => theme.spacing(1) }} />
// or
<Box sx={({ theme, ownerState}) => ({ m: theme.spacing(1), p: theme.spacing(1, 2) })} />

// Array values
<Box sx={[{ m: 1 }, hasError && { color: '#f00' }]} />

// Nested selectors
<Box sx={{ m: 1, ':hover': { color: '#00f' } }} />
// Selectors being object prop names can of course (as per TS/JS) be interpolated
<Box sx={{ m: 1, [`&.${stateClasses.disabled}`]: { opacity: 0.5, pointerEvents: 'none' } }} />
```

## `styled` component generation ([MUI docs link](https://mui.com/system/styled/))
MUI uses emotion styled utility with a bit of a different syntax and extends it with the upper changes that are available on `sx`. All of those. It's usually also called as a function:
```js
const ComponentRoot = styled(Box, [optionsObj])({
  // component root styles
  '::before': {
    // nested styles
  },
  [`:has(${itemClasses.selected})`]: {
    // also complex interpolated nested selectors
    ':hover': {
      // even more nesting
    }
  }
});

// also callback styles
const ComponentRoot = styled(Box)(({ theme, ownerState }) => ({
  margin: theme.spacing(1,2,3,4),
  transition: theme.transitions.create('color'),
  ':hover': {
     color: theme.palette.secondary.main
  }
}));
```

## Component theming ([MUI docs link]())
MUI material components can be re-themed by providing style overrides or developers can write their own components that can be themed when used by other teams (and rethemed in the same way as MUI components).
```js
const themeOverides = {
  MuiButton: {
    styleOverrides: {
      root: {
        // button root "slot" style overrides as a simple object
      },
      secondary: ({theme, owserState}) => ({
        // button styles when variant "secondary" are provided as a callback
      })
    }
  }
}
```
All these styles can be very complex providing nested selectors, use theming variables/functions etc. When the theme is created these themes can be provided to it and the default MUI components will be restyled as per these style overrides.

## The most important
All these styles are provided as CSS-in-JS/TS, and especially when using Typescript there are very well defined types for all of these so you get code hinting, TS linting for invalid CSS prop values etc. But stylelint could support this syntax so it would be able to lint these styles according to preset rules. I'm not even going to think about browser compatibility issue linting (as per eslint-plugin-compat) that uses *browserslist* infromation coupled with *caniuse* data.

**Comment by ybiquitous** [comment]
@litera Thanks for the proposal. However, we focus on the standard CSS syntax now, so I recommend you build your own custom syntax via PostCSS.

See also https://stylelint.io/developer-guide/syntaxes

**Comment by ybiquitous** [comment]
I'm closing this because of no more activities.
