### ISSUE TITLE
Use `process.emitWarning()` instead of `console.warn()`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7533]
### What is the problem you're trying to solve?

Currently, Stylelint uses [`console.warn()`](https://nodejs.org/api/console.html#consolewarndata-args) to show deprecation warnings, e.g.

https://github.com/stylelint/stylelint/blob/c49f9b5a7b45cb35c58b5bc1cd669733896d0183/lib/augmentConfig.mjs#L325-L327

`console.warn()` is an alias for `console.error()` in Node.js and just prints a message to `stderr`. There is no easy way to handle the output, e.g. stop printing.

### What solution would you like to see?

How about using [`process.emitWarning()`](https://nodejs.org/api/process.html#processemitwarningwarning-options) instead? E.g.

```js
emitWarning( 
	`CommonJS plugins are deprecated ("${pluginLookup}"). See https://stylelint.io/migration-guide/to-16`,
	{ type: 'DeprecationWarning', code: 'stylelint:001' }
);
```

This function of `node:process` provides a common way to handle deprecation warnings in a Node.js program. `DeprecationWarning` is a reserved type and affects the `--*-deprecation` command-line flags of Node.js like `--no-deprecation`. For details, see <https://nodejs.org/api/process.html#event-warning>.

E.g.

```sh-session
$ npx stylelint '*.css'
(node:20670) [stylelint:001] DeprecationWarning: CommonJS plugins are deprecated ("foo"). See https://stylelint.io/migration-guide/to-16
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Using the `--no-deprecation` flag can suppress the warning:

```sh-session
$ NODE_OPTIONS='--no-deprecation' npx stylelint '*.css'
```

Please let me know if anyone knows some downsides of `process.emitWarning()`.

**Comment by Mouvedia** [comment]
Your example should be

```js
emitWarning(`CommonJS plugins are deprecated ("${pluginLookup}")`, {
    type: 'DeprecationWarning',
    code: 'stylelint:001',
    detail: 'See https://stylelint.io/migration-guide/to-16'
});
```

Apart from that I am all for it.

**Comment by ybiquitous** [comment]
Okay, since there seem to be no objections, I've labeled the issue as **ready to implement**. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by Mouvedia** [comment]
> Using the `--no-deprecation` flag can suppress the warning:
> 
> ```
> $ NODE_OPTIONS='--no-deprecation' npx stylelint '*.css'
> ```

If the tests still passes with that option we should update

https://github.com/stylelint/stylelint/blob/a02e4dd6d99e9159fd0f51d04caf324c1d990066/package.json#L72
