### ISSUE TITLE
Unknown word  CssSyntaxError

### ISSUE THREAD

**Issue by ducphamM2VN** [stylelint/stylelint#7534]
### Describe the documentation issue

I setup the @nuxtjs/stylelint-module and the stylelint for my Nuxt 3 project.

I run on terminal "stylelint **/*.{vue,css} --ignore-path .gitignore" then I got the error
components/Logo.vue
 79:1  ✖  Unknown word  CssSyntaxError 
 
<img width="787" alt="Screenshot 2024-02-22 at 15 17 13" src="https://github.com/stylelint/stylelint/assets/102281214/489a316d-ae52-4de6-b0b7-7de2b8034795">

### What solution would you like to see?

The setting for this issue

**Comment by JounQin** [comment]
`.vue` is not pure css, you may need https://github.com/ota-meshi/stylelint-config-recommended-vue.

**Comment by yoyo837** [comment]
![image](https://github.com/stylelint/stylelint/assets/6134547/ec1ca0a1-ddb2-4231-9a9e-5ab6d4367da4)

Andd this one?
