### ISSUE TITLE
Roadmap/ETA for full ESM

### ISSUE THREAD

**Issue by klaus-aunds** [stylelint/stylelint#7545]
### Describe the documentation issue

Dear devs, we got bitten by an issue similar to https://github.com/stylelint/stylelint/issues/7201. In our case it was caused by a ~recent nextjs14 upgrade, which has `string-width` v5.x in the dependency tree.

I searched the README, issues and MRs but couldn't find any info on full EMS implementation for this package.

### What solution would you like to see?

Would it be possible to add an ETA/roadmap to the README? Or an open ticket/MR to keep track of it?

**Comment by JounQin** [comment]
close in favor of #7396
