### ISSUE TITLE
Compatibility issue between `stylelint@16.3.0` and `stylelint-prettier@5.0.0`

### ISSUE THREAD

**Issue by AntoLC** [stylelint/stylelint#7576]
### What minimal example or steps are needed to reproduce the bug?

 Having stylelint@16.3.0 and stylelint-prettier@5.0.0 in the same repo.

### What minimal configuration is needed to reproduce the bug?

 Seems to be a compatibility issue between `stylelint@16.3.0` and `stylelint-prettier@5.0.0`.
![Capture d'écran 2024-03-25 104853](https://github.com/stylelint/stylelint/assets/25994652/157ebaa4-cb1b-447a-b35a-3a33cd0d3cc7)

### How did you run Stylelint?

`yarn stylelint`

### Which Stylelint-related dependencies are you using?

```json
    "stylelint": "16.3.0",
    "stylelint-config-standard": "36.0.0",
    "stylelint-prettier": "5.0.0",
```

### What did you expect to happen?

The linting to work.

### What actually happened?

![Capture d'écran 2024-03-25 104853](https://github.com/stylelint/stylelint/assets/25994652/57e20f15-b0a4-46ea-a994-fa3a0345b688)

**Comment by Mouvedia** [comment]
#7532 is probably the culprit.
@ybiquitous this needs to be investigated.

**Comment by ybiquitous** [comment]
Thanks for the report. Right, we should fix the error as soon as possible. I'll review the PR to try fixing it.

**Comment by ybiquitous** [comment]
For your information, here's a reproducible [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYBfEAaEAzAlgDYwBySAtnIjAB4UAOxAdGAM6vbgQB2BA5ghDAAOtxQphIWgBcY3KK0nwUAbVHjxk1tICexQvm7SAtPQBOMadPwwzAeguRyleTCiT1KALqjMOSLz4fABiEGbkSNKCAFasPJyw9ByIImISINp6MAZGSukAjABsTADMTAAMklieWrr6hibmlta2eZKEkTDaHtyY6EA), which raises:

```
Directory import '/home/httpschimericaltrifle8d3c21net-1ell/node_modules/stylelint-prettier/' is not supported resolving ES modules imported from /home/httpschimericaltrifle8d3c21net-1ell/node_modules/stylelint/lib/utils/dynamicImport.mjs
Did you mean to import /home/httpschimericaltrifle8d3c21net-1ell/node_modules/stylelint-prettier/index.js?
```
