### ISSUE TITLE
Can't complie concat string in less

### ISSUE THREAD

**Issue by NWYLZW** [stylelint/stylelint#7584]
### What minimal example or steps are needed to reproduce the bug?

```less
@prefix: test;
.@{prefix}-a {
  @root: .@{prefix}-a;
  display: flex;
  @{root}-text {
    display: block;
  }
}
```

[less playground](https://lesscss.org/less-preview/#eyJjb2RlIjoiQHByZWZpeDogdGVzdDtcbi5Ae3ByZWZpeH0tYSB7XG4gIEByb290OiAuQHtwcmVmaXh9LWE7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIEB7cm9vdH0tdGV4dCB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gIH1cbn0iLCJhY3RpdmVWZXJzaW9uIjoiNC4yLjAiLCJtYXRoIjoicGFyZW5zLWRpdmlzaW9uIiwic3RyaWN0VW5pdHMiOmZhbHNlfQ==)

### What minimal configuration is needed to reproduce the bug?

[stylelint playground](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAHATjAZgSwB7wAIAXGAZyIG4AdAOwDolh0s8BfAWgEMDhaCCkaCBCKEGTDDlwdO1GvyjZSKADacAnoUwqYuOf0ZCRHEriI8+-AouVrNBAEYqIYANb6CrWqxAAaEDg6AHKcALZwiLphqjB0OqSkfuAQNDgA5gggvPIEVCC6JDRQpHmEANqW-Hnk6joq2DRE7JCp2Gns5JxFnGhQeZYAur6WeRAAbjBoaNiwJQgEFTn8wLkB2PGlC3kAVNsA9NtxZHNDq2AAruQQoQDK6o2cuJt5KBDkYAns8XOeg95JLXSADEIGhQpwiJkAFakFJJWAoRKIbJVEA1OoNIjPEBqEjkPLDHLVIi1GD1RrNFLpDpELpQHp9eZ5XFkLF+EYgV7vT7fbEs-Egf6sIA)

### How did you run Stylelint?

[stylelint playground](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAHATjAZgSwB7wAIAXGAZyIG4AdAOwDolh0s8BfAWgEMDhaCCkaCBCKEGTDDlwdO1GvyjZSKADacAnoUwqYuOf0ZCRHEriI8+-AouVrNBAEYqIYANb6CrWqxAAaEDg6AHKcALZwiLphqjB0OqSkfuAQNDgA5gggvPIEVCC6JDRQpHmEANqW-Hnk6joq2DRE7JCp2Gns5JxFnGhQeZYAur6WeRAAbjBoaNiwJQgEFTn8wLkB2PGlC3kAVNsA9NtxZHNDq2AAruQQoQDK6o2cuJt5KBDkYAns8XOeg95JLXSADEIGhQpwiJkAFakFJJWAoRKIbJVEA1OoNIjPEBqEjkPLDHLVIi1GD1RrNFLpDpELpQHp9eZ5XFkLF+EYgV7vT7fbEs-Egf6sIA)

### Which Stylelint-related dependencies are you using?

[stylelint playground](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAHATjAZgSwB7wAIAXGAZyIG4AdAOwDolh0s8BfAWgEMDhaCCkaCBCKEGTDDlwdO1GvyjZSKADacAnoUwqYuOf0ZCRHEriI8+-AouVrNBAEYqIYANb6CrWqxAAaEDg6AHKcALZwiLphqjB0OqSkfuAQNDgA5gggvPIEVCC6JDRQpHmEANqW-Hnk6joq2DRE7JCp2Gns5JxFnGhQeZYAur6WeRAAbjBoaNiwJQgEFTn8wLkB2PGlC3kAVNsA9NtxZHNDq2AAruQQoQDK6o2cuJt5KBDkYAns8XOeg95JLXSADEIGhQpwiJkAFakFJJWAoRKIbJVEA1OoNIjPEBqEjkPLDHLVIi1GD1RrNFLpDpELpQHp9eZ5XFkLF+EYgV7vT7fbEs-Egf6sIA)

### What did you expect to happen?

No CssSyntaxError

### What actually happened?

Unknown word  CssSyntaxError

**Comment by NWYLZW** [comment]
I think postcss-less probably won't address this issue anymore as it hasn't been updated for a long time. Let's document the problem here so that future users can find a solution.
Thank your reply.

**Comment by ybiquitous** [comment]
Thanks for double-checking the issues. I strongly recommend opening an issue to `postcss-less` so others can find the same problem. The reported issue would also be useful for those who restart `postcss-less` activity or fork `postcss-less`.

Since this repository has focused on the standard CSS syntax, this issue will be closed soon.

**Comment by ota-meshi** [comment]
> I think postcss-less probably won't address this issue anymore as it hasn't been updated for a long time. Let's document the problem here so that future users can find a solution.

Their forks may have been maintained.

https://github.com/stylelint-less/postcss-less

**Comment by ybiquitous** [comment]
Oh I didn't know that! Thanks for the info.
It seems good to add the package to Awesome Stylelint.

**Comment by NWYLZW** [comment]
> stylelint-less/postcss-less

It looks like not work.😭

[stylelint playground](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAHATjAZgSwB7wAIAXGAZyIG4AdAOwDolh0s8BfAWgEMDhaCCkaCBCKEGTDDlwdO1GvyjZSKADacAnoUwqYuOf0ZCRHEriI8+-AouVrNBAEYqIYANb6CrWqxAAaEDg6AHKcALZwiLphqjB0OqSkfuAQNDgA5gggvPIEVCC6JDRQpHmEANqW-Hnk6joq2DRE7JCp2Gns5JxFnGhQeZYAur6WeRAAbjBoaNiwJQgEFTn8wLkB2PGlC3kAVNsA9NtxZHNDq2AAruQQoQDK6o2cuJvVRLUw9Y3s8XOeg95JLXSADEIGhQpwiJkAFakFJJWAoRKIbJVEA1OoNIjPEBqEjkPLDHIvN4fJqAtodIhdKA9PrzPK4shYvwjNGvDGfb7Yxn4kD-VhAA)

Do I need to make any other configurations, or should I open a new issue under that repository?

**Comment by NWYLZW** [comment]
> Thanks for double-checking the issues. I strongly recommend opening an issue to `postcss-less` so others can find the same problem. The reported issue would also be useful for those who restart `postcss-less` activity or fork `postcss-less`.
> 
> Since this repository has focused on the standard CSS syntax, this issue will be closed soon.

Ok, once I investigate the availability of the solution mentioned below, I will provide a new issue in the corresponding project.
