### ISSUE TITLE
Add `ignoreProperties` option to `length-zero-no-unit`

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7591]
### use case

`flex` used to require an unit for the `flex-basis` value.

> [unitless zero will either be interpreted as one of the flexibilities, or is a syntax error](https://www.w3.org/TR/2012/WD-css3-flexbox-20120322/#flexibility)

browsers affected: IE10–11

### What solution would you like to see?

```json
{
  "length-zero-no-unit": [true,  {
    "ignoreProperties": ["flex"]
  }]
}
```

**Comment by ybiquitous** [comment]
@Mouvedia Thanks for the report. But, `flex` is specially handled already. See #5315. Is a new option still necessary?

https://github.com/stylelint/stylelint/blob/3edaa03b101c41274b153d4806c4125db4bc7244/lib/rules/length-zero-no-unit/index.mjs#L136

**Comment by Mouvedia** [comment]
Indeed.

> Is a new option still necessary?

No it's not.

see #4831 for the reason
