### ISSUE TITLE
Indentation rule not working correctly "Unknown rule indentation"

### ISSUE THREAD

**Issue by jordyfontoura** [stylelint/stylelint#7595]
### What minimal example or steps are needed to reproduce the bug?

```css
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": 2
  }
}
```

### How did you run Stylelint?

I'm running `stylelint '**/*.{css,scss}'` but the same problem happens in the Stylelint demo itself
[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIQBoQDMCWAbGA5AhgLZyIwAeRADjgHRgDO9K4EAdpgOYIjAA6rAAgG8QAJwCuOeiPgC+gocJAZWsVgBd86jGxkCATPyEBffseaR2GDgDEIowlu4Arem2axKTRPKEj66gCeOFgq6noiWFowASJmIMZAA)

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "^16.3.1",
}
```

### What did you expect to happen?

I hope the indentation rule works exactly as described in the documentation

### What actually happened?

Local:
```
public/globals.css
  1:1  ✖  Unknown rule indentation  indentation
```

In the Demo:
```
Unknown rule indentation. [1:1-2]
```

### Do you have a proposal to fix the bug?

It appears that the indentation rule has been deleted from the project
We would need to return this rule or remove it from the documentation

**Comment by jordyfontoura** [comment]
I noticed that in commit 7dc40ed8ac42636429a47953bc9d8ab41ea604e4 this rule was removed
I believe it is a case of taking the previous operation and bringing it to the current project with small adjustments.

**Comment by ybiquitous** [comment]
@jordyfontoura Please have a look at https://stylelint.io/migration-guide/to-15, which mentions the `indentation` rule.

**Comment by nextgenthemes** [comment]
"Not planned" means what exactly? How are we supposed to set tabs as indentation now. AI tells me it's part of the root config now, but that seems to be a hallucination.

Or are you forcing everyone to use spaces now?
