### ISSUE TITLE
`function-calc-no-unspaced-operator` should support newer calc functions

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7618]
### What is the problem you're trying to solve?

> [fix the false negatives for `round` and other calc-sum functions by broadening the meaning of calc to calc-sum](https://github.com/stylelint/stylelint/issues/5695#issuecomment-1079960257)

> [It doesn't validate any of the newer math functions.](https://github.com/stylelint/stylelint/issues/7181#issuecomment-1713643664)

compare https://www.w3.org/TR/css-values-4/#calc-syntax and https://www.w3.org/TR/css-values-3/#calc-syntax

### What solution would you like to see?

I already have it working on a local branch for a subset of these.

- [x] `abs`
- [x] `acos`
- [x] `asin`
- [x] `atan`
- [x] `calc`
- [x] `cos`
- [x] `exp`
- [x] `sign`
- [x] `sin`
- [x] `sqrt`
- [x] `tan`
- [x] `min`
- [x] `max`
- [x] `hypot`
- [x] `clamp`
- [x] `round`
- [x] `mod`
- [x] `rem`
- [x] `atan2`
- [x] `pow`
- [x] `log`

**Comment by ybiquitous** [comment]
@Mouvedia If this issue is incomplete, feel free to reopen. 🙏🏼

**Comment by Mouvedia** [comment]
> @Mouvedia If this issue is incomplete, feel free to reopen. 🙏🏼

I did a partial quick fix. A follow-up PR will be needed to fix the last 10 functions.
I added skipped tests to pave the way.
