### ISSUE TITLE
Add `formatter` property in configuration

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7621]
### What is the problem you're trying to solve?

If a formatter in a configuration (e.g. `stylelint.config.js`) is supported, we can simplify `stylelint` CLI arguments or specify a formatter via an environment variable. For example:

Before:

```sh
stylelint a.css -f json
stylelint b.css -f json
# ...
```

After:

```sh
stylelint a.css
stylelint b.css
# ...
```

```jsonc
// .stylelintrc.json
{
  "formatter": "json"
}
```

```js
// .stylelintrc.js
export default {
  formatter: process.env['STYLELINT_FORMATTER']
};
```

### What solution would you like to see?

- Add a `formatter` property in a configuration

```js
// stylelint.config.js
import myCustomFormatter from 'my-custom-formatter';

export default {
  // A built-in formatter name
  formatter: 'string', // | 'compact' | 'json' | ...

  // Or a path to a custom formatter module
  formatter: './path/to/my-custom-formatter.js',

  // Or a custom formatter module
  formatter: myCustomFormatter,

  rules: { /* ... */ },
};
```

- It's possible to override the property by CLI arguments: `--formatter` or `--custom-formatter`

Background: https://github.com/stylelint/stylelint/issues/7617#issuecomment-2061279950

**Comment by Mouvedia** [comment]
I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

**Comment by emmacharp** [comment]
Hello, @ybiquitous !

I've begun working on this and was wondering if it wouldn't be better to create two config options (formatter, customFormatter) as to keep it as much the same as the cli.

What do you think?

**Comment by Mouvedia** [comment]
Since you cannot either have a formatter or a custom one I think it's simpler to only have `formatter`.
i.e. you would have to implement an overriding logic if you had both `formatter` and `customFormatter`

**Comment by emmacharp** [comment]
@ybiquitous, I'm actually scratching my head about standalone support of this feature. I think it should be supported but since I'm having a hard time with this, I thought I'd ask about your opinion on the matter. Maybe @Mouvedia could chime in too?

Thanks!

**Comment by ybiquitous** [comment]
@emmacharp Can you explain your problem specifically?

**Comment by emmacharp** [comment]
The code I wrote in `standalone.mjs` does not work. I had not properly understood the internals of this script. As of now, only `postProcessStylelintResult` gets access to the config file. This function is called three times in the file depending on the state of linted files. 

I think I can get the config formatter there too but it's duplication that I'm not sure is right. See [here](https://github.com/emmacharp/stylelint/blob/c7c8dd23058267437b5b869aa3602497246710d3/lib/standalone.mjs#L158C1-L167) for instance.

Hope I'm being clear!

**Comment by emmacharp** [comment]
Any thoughts, @ybiquitous?

**Comment by ybiquitous** [comment]
@emmacharp Sorry for the late response. In my understanding, we may focus on `getFormatterFunction()` in `standalone.mjs`: the new implementation would enhance `getFormatterFunction()` to fetch either one of:

- a built-in formatter name
- a path to a custom formatter module
- a custom formatter module

E.g.

```js
// a built-in formatter name
{
  formatter: 'verbose'
}

// a path to a custom formatter module
{
  formatter: './your/custom/formatter.mjs'
}

// a custom formatter module
import customFormatter from './your/custom/formatter.mjs'
{
  formatter: customFormatter
}
```

For importing a custom formatter, the following code would be helpful:

https://github.com/stylelint/stylelint/blob/fe1aa80ff731f1f1a5e576a5bc60329472903a79/lib/augmentConfig.mjs#L331

**Comment by ybiquitous** [comment]
Ah, you added `lib/utils/getFormatter.mjs` already. It seems nice to merge `getFormatterFunction()` in `standalone.mjs` into `getFormatter()`.

`cli()` would pass either of the following to `standalone()`:
- a built-in formatter name
- a path to a custom formatter

Then `standalone()` would call `getFormatter()` with the formatter argument, and ``getFormatter()` would resolve and return a formatter function.

**Comment by emmacharp** [comment]
Great. Thanks for the response, @ybiquitous!

I think I'll have to call the function in 2-3 places for it get the files needed to resolve. Are you alright with this duplication of the call?

**Comment by ybiquitous** [comment]
If I remember correctly, loaded configs are cached so multiple calls have no problems, I think.

**Comment by emmacharp** [comment]
Did a lot of work here and I think I've got a good working (if not optimal) implementation. There's a catch though.

The standalone function now has access to the `DEFAULT_FORMATTER` constant whereas before it had a specific `json` formatter default through the `getFormatterFunction` function. It breaks some tests since the report is now `string` rather than `json`.

How should we go about that, @ybiquitous? 

PS: some other tests are failing too but I'll look into them afterwards.

**Comment by ybiquitous** [comment]
Thank you. I'll look at the PR later. 👀

**Comment by ybiquitous** [comment]
@emmacharp Sorry for the late reply. The constant name `DEFAULT_FORMATTER` may be confusing now. I think the default formatter should be `json`, but the default one *for CLI* should be `string`. So, we may need to have the two constants like this:

```js
export const DEFAULT_FORMATTER = 'json';
export const DEFAULT_FORMATTER_CLI = 'string';
```

Luckily, these constants are internal, so we can refactor them freely.

**Comment by emmacharp** [comment]
Alright, I'll make the necessary changes and report back!

**Comment by emmacharp** [comment]
Sorry to bother you again, @ybiquitous, but since the `getFormatterFunction()` function is only called inside `standalone` I can't figure out an effective way of telling if stylelint is being called through the CLI or as standalone. Before refactoring anything I thought I'd ask you if you know of a simple way to do it..?

**Comment by ybiquitous** [comment]
I think it's the easiest to pass a default formatter from `cli.mjs` to `standalone.mjs`, as I suggested on <https://github.com/stylelint/stylelint/pull/7826#discussion_r1685175659>.

Let's discuss the code in PR #7826, not here, so that we can easily add a comment on a specific code.
