### ISSUE TITLE
If you manually specify the configPath path in VScode's stylelint extension, the.stylelintignore file will no longer be recognized, not even the array in the ignoreFiles property of the configuration object

### ISSUE THREAD

**Issue by NoeLiYa** [stylelint/stylelint#7627]
### What is the problem you're trying to solve?

All of the Eslint+stylelint+prettier+editor+husky+git configuration files are in the root directory and make my root directory look bloat, so I created a folder called lint-configs just for them

and I can specify the path to my config file via stylelint.configFile, a specialized property in the Vscode extension
![image](https://github.com/stylelint/stylelint/assets/129087019/77641059-21e8-4cbe-868d-5b75df45cef1)

But once I specify the configuration file path, the ignoreFiles path will not be specified or even used
![image](https://github.com/stylelint/stylelint/assets/129087019/9c08ea61-11e5-4f05-9503-42ab48d49e9b)

### What solution would you like to see?

If possible I want to manually specify the path to the ignore file and the path to the config file, just like prettier

**Comment by IOTA233** [comment]
请问这个问题怎么解决的？
