### ISSUE TITLE
Add support for disabling linting for single line (with inline comment)

### ISSUE THREAD

**Issue by deepfriedmind** [stylelint/stylelint#763]
I think it would be great if this could work in e.g. SCSS:

```css
selector {
  property1: value1;
  property2: value2; // stylelint-disable [rules]
  property3: value3;
}
```

Where stylelint would only be disabled for property2. 
As it is currently, this would disable all linting in the rest of the file if no `// style-lint enable` comment is found.

**Comment by jeddy3** [comment]
Ref: https://github.com/stylelint/stylelint/issues/714

Previously decided against, but this is the second request for it. And so perhaps worth thrashing out the details if someone is willing to contribute the enhancement?

**Comment by captbaritone** [comment]
At the risk of being noisy. I'd like to +1 this rule. Anything I can do to ease the use of Stylint is going to make it easier to get my colleagues on-board with adopting it.

It would especially ease the process of rolling out Stylelint across our existing, largish, code base; which we are currently considering.

**Comment by jeddy3** [comment]
> Anything I can do to ease the use of Stylint is going to make it easier to get my colleagues on-board with adopting it.

That sounds good to me! :) We've marked this as "help wanted" and we'd be more than happy to accept a PR for this feature. If you'd like to contribute, you'll find the disable ranges code here:

- https://github.com/stylelint/stylelint/blob/master/src/disableRanges.js

And the tests for it here:

- https://github.com/stylelint/stylelint/blob/master/src/__tests__/disableRanges-test.js
- https://github.com/stylelint/stylelint/blob/master/src/__tests__/disableRanges-integration-test.js
