### ISSUE TITLE
CLI doesn't seem to work as expected.

### ISSUE THREAD

**Issue by DanielTate** [stylelint/stylelint#7643]
### What minimal example or steps are needed to reproduce the bug?

```css
.selector {
    display: block;
    invalid: property;
}
```

### What minimal configuration is needed to reproduce the bug?

```javascript
/** @type {import('stylelint').Config} */
export default {
    extends: "stylelint-config-standard-scss",
    rules: {
        "block-no-empty": true,
    }
};

```

### How did you run Stylelint?

`npx stylelint --config stylelint.config.mjs --fix 01.css > 01-fixed.css`

### Which Stylelint-related dependencies are you using?

I don't have a package.json I installed globally

### What did you expect to happen?

for 01-fixed.css to contain the output:

```css
.selector {
    display: block;
}
```

### What actually happened?

I have the outline here: https://stackoverflow.com/questions/78369443/stylelint-not-automatically-fixing-content-as-expected. The expected output was empty. Have I missed some configuration?

### Do you have a proposal to fix the bug?

If this is not a bug possibly some more feedback to the user could be nice or some examples in the documentation under the CLI section.

**Comment by ybiquitous** [comment]
@DanielTate Thanks for using the template. But I don't think the CLI behavior is a bug. If you want to see a fixed CSS code in STDOUT, you should use STDIN, for example:

```sh-session
$ npx stylelint -v
16.4.0

$ cat a.css
a { opacity: 50%; }

$ npx stylelint --fix < a.css > a.fixed.css

$ diff -u a.css a.fixed.css
--- a.css	2024-04-24 20:46:11
+++ a.fixed.css	2024-04-24 20:48:16
@@ -1 +1 @@
-a { opacity: 50%; }
+a { opacity: 0.5; }
```

If you don't use STDIN, `stylelint --fix` overwrites a specified CSS file, instead of writing to STDOUT:

```sh-session
$ npx stylelint --fix a.css

$ cat a.css
a { opacity: 0.5; }
```

**Comment by ybiquitous** [comment]
I'm closing this since there are no more info. Please reopen it if you have still any concerns.
