### ISSUE TITLE
Provide links to message

### ISSUE THREAD

**Issue by StanislavSapogov** [stylelint/stylelint#7648]
### What is the problem you're trying to solve?

https://stylelint.io/user-guide/configure/#message
It would be great to provide a link to the message property

### What solution would you like to see?

`{
        "message": "Expected custom property name to be [kebab-case](https://kebab-case)"
  }`

**Comment by Mouvedia** [comment]
What type of link are you talking about?
An anchor link pointing to the core rule itself?
A string argument which would be added to every rules?
What's your use case? Why do you need that url?

**Comment by StanislavSapogov** [comment]
we have documentation for our design system and I'm writing a rule to help our developers use our variables, so I'd like to provide a URL to our docs :)

**Comment by ybiquitous** [comment]
@StanislavSapogov Perhaps, will #7484 resolve your problem?

**Comment by ybiquitous** [comment]
This issue seems inactive, so I'm going to close it. Please reopen it if you still have any concerns.
