### ISSUE TITLE
TypeScript reports "Type 'CosmiconfigResult' is not generic"

### ISSUE THREAD

**Issue by regseb** [stylelint/stylelint#7660]
### What minimal example or steps are needed to reproduce the bug?

The bug is not related to the analysis of a CSS file. It's the TypeScript verification of Stylelint's API.

`index.js`:

```javascript
import stylelint from "stylelint";

console.log(stylelint);
```

### What minimal configuration is needed to reproduce the bug?

N/A

### How did you run Stylelint?

1. `npm i`
2. `npx tsc --allowJs --noEmit --lib esnext index.js`

### Which Stylelint-related dependencies are you using?

`package.json`:

```json
{
  "name": "testcase",
  "version": "1.0.0",
  "dependencies": {
    "@types/node": "20.12.7",
    "stylelint": "16.4.0",
    "typescript": "5.4.5"
  }
}
```

### What did you expect to happen?

No error.

### What actually happened?

```
node_modules/stylelint/types/stylelint/index.d.ts:132:34 - error TS2315: Type 'CosmiconfigResult' is not generic.

132  export type CosmiconfigResult = Cosmiconfig.CosmiconfigResult<Config>;
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/stylelint/types/stylelint/index.d.ts:132
```

### Do you have a proposal to fix the bug?

The type [`CosmiconfigResult`](https://github.com/cosmiconfig/cosmiconfig/blob/a5a842547c13392ebb89a485b9e56d9f37e3cbd3/src/types.ts#L10-L14) isn't generic. The property `config` is type `any`.

The problem is probably related to the pull request [_Refactor Cosmiconfig types_ #7543](https://github.com/stylelint/stylelint/pull/7543/files#diff-9005bb639a6220616aebaf301054701ddc479adaac5c8885c0825e735794d234).

**Comment by ybiquitous** [comment]
@regseb Thanks for the report. Yes, this is my bad, the mentioned PR is a cause of the error. I'll revert it soon.
