### ISSUE TITLE
Stylelint --fix does not fix two problems at the same time: the order/properties-order property, and the removal of extra empty lines.

### ISSUE THREAD

**Issue by dmitriybo** [stylelint/stylelint#7668]
### What minimal example or steps are needed to reproduce the bug?

1. Watch [demo1](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0B3ATgQwA4AJgB0A7HHKASwGcsAbDAT3hwDNqYAPAbiJIAsYyA5jwAujAIwAGCQFIuxHCjJRhPcVNnccEAG4w0LCCkY8lsQnIC+Ra4SIgANCCZlWAOQwBbOInaeaMJDAKCgdwCEJnAQQQAnl8EHZhGEIoCnjGAG1NEniKYTpWajJCYQBaSAjBUsxhMnCMalKINFg0ePtsnFz8wuKyrDQYYVq9AHpByA8vFJgoeM0AXQ64kBoAVwFitIQcDKXNeLQ11m3GYCtCC9CKyIAxZo8MYWiAKwpw0NgsEMRYnJA8gUYEUSukuiAxAA2JAAFiQEnaBwBPWBfXK4Ui1SedUIDSaLT0YPiEiQYiQACZEStAb0SqUBkMRm0dvEAKzw+HzS4gCxAA) or [demo2](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0B3ATgQwA4AJgB0A7HHKASwGcsAbDAT3hwDNqYAPAbiJIAsYyA5jwAujAIwAGCQFIuxHCjJRhPcVNnccEAG4w0LCCkY8lsQnIC+Ra4RAAaEEzKsAchgC2cROw80YSMAoKe3AIQicBBBACeXwQdmEYQigKOMYAbU0SOIphOlZqMkJhAFosNBhhYTI9AHoKyHdPZJgoOM0AXTtNOJoAVwEi1IQcTPlskFz8mELikog0WDR2+S6ekDQ+1mHGGJIJhaXaw7000az9zPA+3Ih3MrQILD1qmGG7HDjYMFpMarD3p8Nls3nEPnEMKVNts4h0LmtxkCTmhauUni8ahQShhqFgeBgAEaVMhgHHzRanEbCTYwTRWQj0kKQcKCABiC3ckKiACsKGEQrAsMFEHsgVMCkVhGc4mIAGxIAAsSAkYPW4pmkvJS2lIHlEkVqtikzyErm5Uqr2WIziAFZlcqVhYQBYgA)
2. stylelint fixes the problem with empty lines, but does not fix the problem with sorting properties
3. If you remove empty lines, the sorting problem will be fixed

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-rational-order",
    "stylelint-prettier/recommended"
  ],
  "plugins": [],
  "rules": {}
}
```

### How did you run Stylelint?

[demo1](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0B3ATgQwA4AJgB0A7HHKASwGcsAbDAT3hwDNqYAPAbiJIAsYyA5jwAujAIwAGCQFIuxHCjJRhPcVNnccEAG4w0LCCkY8lsQnIC+Ra4SIgANCCZlWAOQwBbOInaeaMJDAKCgdwCEJnAQQQAnl8EHZhGEIoCnjGAG1NEniKYTpWajJCYQBaSAjBUsxhMnCMalKINFg0ePtsnFz8wuKyrDQYYVq9AHpByA8vFJgoeM0AXQ64kBoAVwFitIQcDKXNeLQ11m3GYCtCC9CKyIAxZo8MYWiAKwpw0NgsEMRYnJA8gUYEUSukuiAxAA2JAAFiQEnaBwBPWBfXK4Ui1SedUIDSaLT0YPiEiQYiQACZEStAb0SqUBkMRm0dvEAKzw+HzS4gCxAA) [demo2](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0B3ATgQwA4AJgB0A7HHKASwGcsAbDAT3hwDNqYAPAbiJIAsYyA5jwAujAIwAGCQFIuxHCjJRhPcVNnccEAG4w0LCCkY8lsQnIC+Ra4RAAaEEzKsAchgC2cROw80YSMAoKe3AIQicBBBACeXwQdmEYQigKOMYAbU0SOIphOlZqMkJhAFosNBhhYTI9AHoKyHdPZJgoOM0AXTtNOJoAVwEi1IQcTPlskFz8mELikog0WDR2+S6ekDQ+1mHGGJIJhaXaw7000az9zPA+3Ih3MrQILD1qmGG7HDjYMFpMarD3p8Nls3nEPnEMKVNts4h0LmtxkCTmhauUni8ahQShhqFgeBgAEaVMhgHHzRanEbCTYwTRWQj0kKQcKCABiC3ckKiACsKGEQrAsMFEHsgVMCkVhGc4mIAGxIAAsSAkYPW4pmkvJS2lIHlEkVqtikzyErm5Uqr2WIziAFZlcqVhYQBYgA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.4.0",
  "stylelint-config-rational-order": "0.1.2",
  "stylelint-prettier": "5.0.0"
}
```

### What did you expect to happen?

Both problems must be fixed at the same time

### What actually happened?

Fixed only problem with extra empty lines

**Comment by ybiquitous** [comment]
@dmitriybo Thanks for the report. But I am wondering if this issue might be caused by `stylelint-prettier`, instead of `stylelint` itself. Here is a [minimal reproducible demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilB3AllAC4AW8KADAA4AeA3FgL5ZYgA0IAZvgDYwBySALZxEMGsKp8AdGADOc9uAiZuAcwQgM2FOhBSArmvyY5e8gG09cogE8+PE0QC0VAE4wiRfDDd6AumxYOHpuBnxmCGjBOLogfJhqpM4AXr4QzpgZBpj4ROYoRGEwQToh+h5ePm4A9O6e3r4FRQYwMcyYjEqQqvhqAGIQbkJIRJoAVnIqSrBUioja5Tb2MI6Y+VF6AIwAbNIALNIUeqVLdg5OrpWNfpsgAKxHR3pMIIxAA):

```css
a {
  width: 0px; /* -> length-zero-no-unit problem; not autofixed */
}
  /* -> prettier/prettier problem; autofixed */
```

```jsonc
// .stylelintrc.json
{
  "plugins": ["stylelint-prettier"],
  "rules": {
    "length-zero-no-unit": true,
    "prettier/prettier": true
  }
}
```

Then, disabling the `prettier/prettier` rule corrects the autofix problem:

```diff
 a {
-  width: 0px;
+  width: 0;
 }
+/* stylelint-disable prettier/prettier */
  
```

So, can you confirm the problem again? And, if `stylelint-prettier` is a cause, can you report this to [prettier/stylelint-prettier](https://github.com/prettier/stylelint-prettier)?

**Comment by dmitriybo** [comment]
Created issue https://github.com/prettier/stylelint-prettier/issues/354

**Comment by ybiquitous** [comment]
@dmitriybo No, there is no built-in rule to handle stylistic problems (Stylelint 16.0.0 has [removed stylistic rules](https://stylelint.io/migration-guide/to-16#removed-deprecated-stylistic-rules)).

For your reference, another 3rd-party plugin [`@stylistic/stylelint-plugin`](https://github.com/stylelint-stylistic/stylelint-stylistic) has a rule fixing empty lines. See this [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYBfAOgOxyANCAGYCWANjAHJIC2ciMAHrQA4UB0YAzlweBNlIBzBCGA4UKTCDYBXISWxdp8FAG0cmAC7bpAAS5aAnmRKGSYAPSGTMU9i0BaOQtwhNWgLr4JUkACdZCmUENF9JfRtTcysaJEZHGBoWY0d7GBDVAEZfLGx0PkhBEiEAMQh-OK1RACsuAT5YFl5EcWwIkCi7RR1Q6TIkLQzen3a-A2NorQtrSe6HZzJ5RRU-AaHDaRwC9CA).

**Comment by dartess** [comment]
I confirm that this is a plugin problem. I described it and tried to fix it.
