### ISSUE TITLE
Remove `postcssResult.stylelint.disableWritingFix`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7735]
https://github.com/stylelint/stylelint/blob/b5b3799cc107ede5b418bef6ef64bab072b2deab/lib/lintPostcssResult.mjs#L44-L46

---

Context :

In https://github.com/stylelint/stylelint/pull/7730 a new plugin flag/option is introduced as part of the fix for https://github.com/stylelint/stylelint/issues/2643

There is already a very lengthy thread there about the nuances of `postcssResult.stylelint.disableWritingFix`

The code was originally introduced in https://github.com/stylelint/stylelint/pull/4573

But it doesn't specifically state why it prevents fixes in two distinct ways :
- communicate to rules that no fixes should be applied by setting `context.fix` to `false`
- forcing the usage of the CSS input as the program output

In https://github.com/stylelint/stylelint/pull/7730 I noticed that most of the added complexity is the result of trying to work around `postcssResult.stylelint.disableWritingFix`.

I would argue that it is sufficient to have one of these mechanics and that having both is redundant.

Removing `postcssResult.stylelint.disableWritingFix` would clear the path for https://github.com/stylelint/stylelint/pull/7730

-------

To illustrate the only observable effect of the original code I've added more tests in https://github.com/stylelint/stylelint/pull/7733/commits/5f3e1b933c949fc46ce6f9d6762249547718b70d

I then removed `postcssResult.stylelint.disableWritingFix` in a subsequent commit to illustrate exactly what would change for users : https://github.com/stylelint/stylelint/pull/7733/commits/fc5a6caf02a6d062ee95ab2b303ae2305afa74c5

Given the already flaky nature of `postcssResult.stylelint.disableWritingFix` and that it only affects rules that do not honor `context.fix` I am inclined to say that this is relatively safe to remove.

-------

I think we can even have a deprecation cycle for this.

We could emit a warning when :
- `postcssResult.stylelint.disableWritingFix` is `true`
- the original input is not the same as the output

This should only happen for users that have rules that do not respect `context.fix`.

Depending on the feedback on such a change we can decide how to proceed.

**Comment by romainmenke** [comment]
> Removing `postcssResult.stylelint.disableWritingFix` would clear the path for https://github.com/stylelint/stylelint/pull/7730

Forgot to explain why :)

A more refined fixer that respects disable comments won't have any effect if the program output is always forced to be the input when disable comments are present.

Removing `postcssResult.stylelint.disableWritingFix` makes it possible for rules with an updated fixer to coexist with others that haven't been updated yet.

Old rules will follow `context.fix`, which will still be false when disable comments are present.

Updated rules will have to use new API like a `fix()` function of a `fix` property in `report({ fix: () => {...} })`.

Either new API will internally determine if the `fix` callback should be skipped based on disable ranges. This new API can also skip if `config.fix` is false.

**Comment by Mouvedia** [comment]
> We could emit a warning when :
> 
> postcssResult.stylelint.disableWritingFix is true
> …

`postcssResult` being `@internal`, I don't think a `process.emitWarning('', { type: 'DeprecationWarning', … })` is needed.

**Comment by ybiquitous** [comment]
@romainmenke @Mouvedia Thanks a lot for digging into this problem. I just caught up. This sounds great to me. 👍🏼 

I think a deprecation warning is unnecessary here because we have documented how to support autofix with `context.fix` explicitly:

https://github.com/stylelint/stylelint/blob/b5b3799cc107ede5b418bef6ef64bab072b2deab/docs/developer-guide/rules.md?plain=1#L215-L224

I'd say that well-maintained plugins would follow this convention. Even if they don't, their authors could soon fix a bug.

Even if many people's linting would break with this removal in the worst case, we could revert and republish it, although I wish it would never happen.

**Comment by Mouvedia** [comment]
The first plugins that supported `--fix` were published in 2017. Unless someone knows of a popular one that doesn't use `context.fix` we shouldn't have to care.

**Comment by romainmenke** [comment]
Happy to hear that everyone sees this as a good step forwards :)

I will update the linked pull request so that it is ready for review.

**Comment by ybiquitous** [comment]
If there would be some possible effect on users, I'd say that we should consider this issue as a *bugfix*, not a refactoring. If so, it seems better to leave a changelog entry for this change. 🤔 

Any thoughts?

**Comment by Mouvedia** [comment]
@ybiquitous feel free to change the type. Either will do.
But I don't think it requires changeset.
