### ISSUE TITLE
Address potentially breaking changes in #7769

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#7779]
I am fairly certain that an unwanted breaking change was introduced in : https://github.com/stylelint/stylelint/pull/7769#pullrequestreview-2132231017

Adding `word` as an extra param to the `node.rangeBy` has side-effects:
- extra serialization of AST nodes, which will have a performance impact
- `word` has precedence over `index` and `endIndex` so the resulting `Range` might be different than it was before for plugins that pass both `index`, `endIndex` and `word` to `report()`

This change was not discussed in that PR.
It should at least be addressed before we release a new version.

**Comment by romainmenke** [comment]
In general I think we should always try to avoid `node.rangeBy({ word: "foo" })`.

Only in very specific cases can we be sure that this will always give the correct results.

For example a rule to test for nested `calc` (e.g. `calc(calc(1 + 1) * 2)` vs `calc((1 + 1) * 2)`).

When used in a larger context it is easy to see how `rangeBy` with a string arg can give unexpected results.

example : `padding: calc(1px + 1px) calc(calc(1px + 1px) * 2)`

When searching for `calc(1px + 1px)` you would find the first instance, which doesn't have any errors.

**Comment by ybiquitous** [comment]
@romainmenke Thanks for finding a potential problem. Here's the current code, and fortunately, it's not published yet:

https://github.com/stylelint/stylelint/blob/c04b77d9781100421634157e780665722980519f/lib/utils/report.mjs#L34

We're using this pattern in other places, for example:

https://github.com/stylelint/stylelint/blob/c04b77d9781100421634157e780665722980519f/lib/utils/fixEmptyLinesBefore.mjs#L37

Considering compatibility and usability, it may be difficult to forbid or deprecate the use of `word` for `report()`. But, at least, we can disallow it in the core rules. For example:

```js
if (process.env.NODE_ENV === 'test' && word) throw new Error('"word" is forbidden');
```

**Comment by Mouvedia** [comment]
I knew about the change. maybe I should have added something in the PR.
The usage of passing just `word` is common but the usage of passing `index`/`word` is pretty rare.
AFAIK using `word` with `index` restricts the search for the word to start at that specific index.
As @ybiquitous said maybe the restriction should be `if (node && word && !index)` then if the length of node.toString() !== to the one of word `throw`?

**Comment by romainmenke** [comment]
> IIRC using word with index restricts the search for the word to start at that specific index.

If that were the case I wouldn't have opened this issue :)

see : https://github.com/postcss/postcss/blob/f9a9868eb3a591cd99d504ac57bf7ee77380856b/lib/node.js#L222-L229

**Comment by romainmenke** [comment]
Thank you @Mouvedia  🙇
