### ISSUE TITLE
Add doiuse and cologuard

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#781]
I think it is bad, that many Stylelint users miss this awesome linters like doiuse or cologuard.

I think everyone will be happy if we integrate all that awesome linters together.

@anandthakker @SlexAxton what do you think?

**Comment by ai** [comment]
Also @jonathantneal create awesome `postcss-contrastguard` and should be discussed here.

**Comment by ai** [comment]
First possible solution:

1. Add “Third-party Linters” to Rules list.
2. Add some wrapper rules so we can define cologuard rule in Stylelint config.

**Comment by ai** [comment]
Maybe I should tell about benefits. Right now all PostCSS linters has separated marketing and often separated user base.

It is not a PostCSS spirit of love and win-win playing :D. Remember how we deprecate `grunt-autoprefixer` to `grunt-postcss` to help all PostCSS ecosystem.

So we should join all our powers together to become a best way to lint CSS.

**Comment by SlexAxton** [comment]
I'm not super free on time, but I'm happy to to merge up to everyone's best interests with colorguard as y'all see fit.

**Comment by davidtheclark** [comment]
With [stylelint-selector-bem-pattern](https://github.com/davidtheclark/stylelint-selector-bem-pattern) I kept [postcss-bem-linter](https://github.com/postcss/postcss-bem-linter) as a standalone library available as a  fully integrated rule in stylelint. I was thinking that could be a pattern for other linting libraries, as well. Do you think that approach works?

**Comment by davidtheclark** [comment]
Also: cf. https://github.com/stylelint/stylelint/issues/644

**Comment by ai** [comment]
@davidtheclark yeap, this rule’s wrappers looks like a best way. We can integrate them to Stylelint config without any changes in linters itself (so @SlexAxton will be happy).

Do we need to create a separated npm packages for them or we can put them to core rules?

If we will create a separated packages, we should mention them in Stylelint rules list and maybe put to the some popular presets. At least `contrastguard` and `cologuard` looks good to be enabled by default in standard presets.

**Comment by davidtheclark** [comment]
bem-linter is pretty specialized, so I thought maybe it should stay out of core. But postcss-colorguard is definitely valuable to everybody regardless of methodology or toolset, so I think an integration might make a good core rule. 

What are referring to as contrastguard?

**Comment by ai** [comment]
@davidtheclark here is a link to postcss-contrastguard. It was finished just few minutes ago :). https://github.com/jonathantneal/postcss-contrastguard

**Comment by jonathantneal** [comment]
@davidtheclark, contrastguard checks for WCAG 2.0 AA and AAA contrast compliance.

**Comment by davidtheclark** [comment]
Ah, the fact that it's so new explains why couldn't find it with a Google search. Thanks.

**Comment by ai** [comment]
@davidtheclark yeap, bem-linter is specialized. But at least we should mentioni them in docs. Maybe we need a some “Third-party Rules” section in stylelint.io?

**Comment by davidtheclark** [comment]
http://stylelint.io/user-guide/plugins/ --- do you think there's a place they should be more prominently featured?

**Comment by davidtheclark** [comment]
That is linked in the nav. But I guess we could also add an additional prominent link in the Rules page, because that's where people might want be looking for them.

**Comment by ai** [comment]
Maybe you should put some text in beggining of Rules page. Like “Here is official core plugins. But you can find many awesome rules in Plugins.”

**Comment by anandthakker** [comment]
I'm in a similar boat as @SlexAxton but I like the idea

**Comment by jeddy3** [comment]
> Maybe you should put some text in beggining of Rules page. Like “Here is official core plugins. But you can find many awesome rules in Plugins.”

Sounds good to me.

> bem-linter is pretty specialized, so I thought maybe it should stay out of core. But postcss-colorguard is definitely valuable to everybody regardless of methodology or toolset, so I think an integration might make a good core rule.

Good point. In addition, they meet our criteria of being for *standard css*. So, I also think I'd be happy to see rules based on `colorguard` and `contrastguard` in core.

I guess that means we should backtrack in #644 and bring `stylelint-feature-blacklist` into core too, as it meets the same criteria (i.e. valuable to everybody regardless of methodology or toolset and for standard css)?

What about `stylehacks` (in lint mode) that we discussed in https://github.com/stylelint/stylelint/issues/265? Do we include it for the same reasons?

**Comment by davidtheclark** [comment]
I'm good with core rules for all of those. At least, if somebody gets around to writing them, or me :)

**Comment by davidtheclark** [comment]
Added issues for rules using colorguard, doiuse, contrastguard, and stylehacks.

**Comment by ai** [comment]
Awesome. I think we can close this one.

**Comment by ai** [comment]
Do you need a help with that issues? They are pretty easy. I can promote them as “First PR” issues.

**Comment by davidtheclark** [comment]
Yeah help is always welcome. Promote away! I might do some work tonight, too.

Related: do you find that a First PR label helps encourage contributions on Github?

**Comment by ai** [comment]
Not sure about labels. But when I announce simple and important open source task, I always had a volunteer.

Many people want to join open source. They just need a direct task.

Maybe this is why lables is not good enouph. People afraid to choice? :)

**Comment by jitendravyas** [comment]
Has this been added? I'm looking to use Doiuse?

**Comment by hudochenkov** [comment]
@jitendravyas use https://github.com/ismay/stylelint-no-unsupported-browser-features plugin.

**Comment by jitendravyas** [comment]
@hudochenkov Thanks. I'm looking for plugin for Colorguard too but I guess nobody has made it yet.

**Comment by evilebottnawi** [comment]
@jitendravyas You can become a champion this plugin :+1:
