### ISSUE TITLE
New repository for testing ecosystem

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#7838]
Hello Stylelint folks, 👋🏼 

This issue aims just to share information, not for any feature requests or bug fixes.

Before releasing 16.7.0 in #7824, I created a repository to test a bunch of plugins and configs with the new version:
https://github.com/ybiquitous/stylelint-ecosystem-tester

See also the current test results:
https://github.com/ybiquitous/stylelint-ecosystem-tester/actions/runs/9903754245

There are still many errors, but most are unrelated to Stylelint. This repository doesn't aim to resolve *all* errors but to observe our ecosystem situation. I will try to fix as many errors as possible, though.

If there are no concerns or problems, I would like to move this repository under the Stylelint organization so that more people, like maintainers or plugin authors, can efficiently find any issues.

I would appreciate it if you would be interested in this topic and provide any feedback. 😃

**Comment by romainmenke** [comment]
No concerns!

I really like this way of unreleased updates.
Thank you for setting this up @ybiquitous 🙇

**Comment by Mouvedia** [comment]
> If there are no concerns or problems, I would like to move this repository under the Stylelint organization so that more people, like maintainers or plugin authors, can efficiently find any issues.

👍 

> provide any feedback

1.
Maybe add criteria related to package addition.
i.e. if someone request his package to be added you need your refusal to be based on/justified by something already mentioned in the README

2.
add popular formatters

3.
This new repository goes hand in hand with #2498.

**Comment by ybiquitous** [comment]
Thanks for the feedback. I agree with adding such a criteria. 👍🏼 If you're interested, creating a PR that updates the README would be great.

**Comment by ybiquitous** [comment]
I've added criteria. See https://github.com/ybiquitous/stylelint-ecosystem-tester#criteria

**Comment by Mouvedia** [comment]
> I've added criteria.

👍 

> was published within three years

Most of the formatters won't fit the bill because they often don't have any dependencies; they don't need to be updated often.

> move this repository under the Stylelint organization

Do it once you are satisfied with the list.

**Comment by ybiquitous** [comment]
I relaxed the criteria a bit: https://github.com/ybiquitous/stylelint-ecosystem-tester#criteria

**Comment by ybiquitous** [comment]
Once I arrange the packages based on the criteria, I'll move the repo under the <https://github.com/stylelint> org.

Please let me know if you have any concerns.

**Comment by Mouvedia** [comment]
@ybiquitous while you are at it can you delete stylelint/stylelint-scripts?

**Comment by ybiquitous** [comment]
Deleting archived repositories is out of the scope. I'll ask the owners in another place.

**Comment by ybiquitous** [comment]
Transferred: https://github.com/stylelint/stylelint-ecosystem-tester

**Comment by ybiquitous** [comment]
I'm closing this issue since the repo transfer is done. Please open an issue in https://github.com/stylelint/stylelint-ecosystem-tester for the future.

**Comment by Mouvedia** [comment]
@ybiquitous 

It seems like your idea inspired [ESLint](https://github.com/eslint/rfcs/pull/127).

We have 5 packages failing right now though.

**Comment by Mouvedia** [comment]
@ybiquitous you might find https://github.com/AriPerkkio/eslint-remote-tester interesting.

**Comment by ybiquitous** [comment]
Thanks for sharing. I'd be happy if you could borrow some ideas from the package to suggest improvements.
