### ISSUE TITLE
color-no-indistinguishable

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#785]
This would be a rule that uses [css-colorguard](https://github.com/SlexAxton/css-colorguard) to ensure you have not used colors that are so similar to each other that they probably represent a mistake (or a poor decision).

Ideas for better names welcome.

Secondary options would correspond to colorguard's: `ignore`, `threshold`, and `whitelist`.

We should point out in the docs that this rule would only compare colors within one stylesheet at a time, not across all the stylesheets you're linting. That means that if you want to compare colors across your whole codebase, you need to feed stylelint a single stylesheet that is the concatenatation of all the real ones. 

That's an unfortunate caveat, and maybe there's a clever workaround.

cc/ @SlexAxton

**Comment by davidtheclark** [comment]
Idea for this from @ai in #781.

**Comment by davidtheclark** [comment]
@SlexAxton: Does the `whitelist` option only accept hex values, or also other colors? https://github.com/SlexAxton/css-colorguard#whitelist

**Comment by SlexAxton** [comment]
If it doesn't accept others that'd be easy to add presumably.

**Comment by davidtheclark** [comment]
Ok, was just checking to write the options validator for the stylelint rule.

**Comment by SlexAxton** [comment]
Ah. I'm mobile but can get you a harder answer tomorrow evening when I'm
back home!
