### ISSUE TITLE
no-browser-hacks

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#787]
Basically re-opening #265, after discussion in #781.

Thinking it's a good idea, as we're opening the doors to more rules that utilize other awesome postcss analyticial tools.

We could use [stylehacks](https://github.com/ben-eb/stylehacks) to create this rule pretty painlessly.

cc/ @ben-eb, @ai.

**Comment by jeddy3** [comment]
I think the name is spot on.
