### ISSUE TITLE
Attempting to import stylelint to write a lint test in jest fails

### ISSUE THREAD

**Issue by heath-freenome** [stylelint/stylelint#7894]
### What minimal example or steps are needed to reproduce the bug?

import stylelint from 'stylelint';

### What minimal configuration is needed to reproduce the bug?

{}

### How did you run Stylelint?

I'm just trying to import it into a test file in jest

### Which Stylelint-related dependencies are you using?

    "stylelint-config-standard": "36.0.1"
    "@stylelint/postcss-css-in-js": "0.38.0",

### What did you expect to happen?

I was expecting to be able to import stylelint

### What actually happened?
```
 TypeError: The URL must be of scheme file

    > 1 | import stylelint from 'stylelint';
        | ^
      2 |
      3 | import stylelintConfig from '../../../stylelint';
      4 |

      at Object.<anonymous> (node_modules/stylelint/lib/utils/FileCache.cjs:17:32)
      at Object.<anonymous> (node_modules/stylelint/lib/createStylelint.cjs:7:19)
      at Object.<anonymous> (node_modules/stylelint/lib/index.cjs:7:25)
      at Object.require (src/__tests__/stylelint/stylelint.test.js:1:1)
```

**Comment by heath-freenome** [comment]
I did a little debugging by changing line 17 of `FileCache.cjs` to the following:
```
const url = new URL('../../package.json',
	(typeof document === 'undefined' ?
		require('u' + 'rl').pathToFileURL(__filename).href :
		(_documentCurrentScript && _documentCurrentScript.src || new URL('lib/utils/FileCache.cjs', document.baseURI).href)));
console.log(url);
const pkg = JSON.parse(node_fs.readFileSync(url, 'utf8'));
```

And got:
```
 URL {}
```

**Comment by heath-freenome** [comment]
Ok, found a work-around, albeit ugly. It forced me to dynamically import stylelint within the test itself after forcing the `document` to be nulled out

```
describe('validate stylelint config', () => {
  let oldDocument;
  beforeAll(() => {
    oldDocument = global.document;
    delete global.document;
  });
  afterAll(() => {
    global.document = oldDocument;
  });
    it('load config in stylelint to validate all rule syntax is correct', async () => {
    const { lint } = require('stylelint');
   ...
   });
};
```

**Comment by heath-freenome** [comment]
Ok, so I switched my test environment from `jsdom` to `node` so that I'm not loading `document` and I ran into a new problem:

```
 TypeError: A dynamic import callback was invoked without --experimental-vm-modules

      at dynamicImport (node_modules/stylelint/lib/utils/dynamicImport.cjs:16:87)
      at getCustomSyntax (node_modules/stylelint/lib/getPostcssResult.cjs:72:21)
      at getPostcssResult (node_modules/stylelint/lib/getPostcssResult.cjs:30:5)
      at lintSource (node_modules/stylelint/lib/lintSource.cjs:93:10)
      at node_modules/stylelint/lib/standalone.cjs:238:27
          at async Promise.all (index 0)
      at standalone (node_modules/stylelint/lib/standalone.cjs:283:22)
```

**Comment by heath-freenome** [comment]
Ok, it seems I'm forced to run with that flag set while testing. Closing this...Hopefully it helps others debug their issues

**Comment by michaelfaith** [comment]
Is there a way to run tests in jest without the `--experimental-vm-modules` flag?  If not, that should be documented in https://stylelint.io/developer-guide/plugins/#testing

**Comment by jeddy3** [comment]
> Is there a way to run tests in jest without the `--experimental-vm-modules` flag?

@michaelfaith I believe it's necessary. 

I've [opened a PR](https://github.com/stylelint/jest-preset-stylelint/pull/159) to document the requirement in the preset README. (I took the details from the [migration guide](https://stylelint.io/migration-guide/to-16/#jest-preset-stylelint).)
