### ISSUE TITLE
stylelint requires plugins to expose a ruleName: stylelint-scss

### ISSUE THREAD

**Issue by b3wii** [stylelint/stylelint#7910]
### What minimal example or steps are needed to reproduce the bug?

`npm install stylelint stylelint-scss`

`npx stylelint "**/*.scss"`

### What minimal configuration is needed to reproduce the bug?

{
    "plugins": ["stylelint-scss"]
}

### How did you run Stylelint?

Command line

### Which Stylelint-related dependencies are you using?

-

### What did you expect to happen?

That it works

### What actually happened?

Error: stylelint requires plugins to expose a ruleName. The plugin "node_modules/stylelint-scss/dist/index.js" is not doing this, so will not work with stylelint.

**Comment by b3wii** [comment]
Problem is an older version (4.3.0) of stylelint-scss somewhere in a sub directory.. How to tell stylelint not to use a plugin?

**Comment by Mouvedia** [comment]
Without any answer from your part for the last week, I am closing this issue.
Feel free to re-open if you can provide more details as requested.
If I had to guess I would say that you are probably using incompatible versions.
