### ISSUE TITLE
logOutput option for PostCSS plugin

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#792]
I was working on the CLI and realized that we could log invalid options in a better way (the current way means that every file will repeat the warnings; the better way is to print them once at the top of the output). 

The recommended way of getting console output when using stylelint as a PostCSS plugin is to use postcss-reporter. The trouble is that since postcss-reporter is generic it is not going to be able to make the above or other future improvements that are stylelint-specific.

So I was wondering if we might want to expose an option to `console.log()` stylelint's string-formatted reporter output when running stylelint as a PostCSS plugin like with gulp.

**Comment by jeddy3** [comment]
> So I was wondering if we might want to expose an option to console.log() stylelint's string-formatted reporter output when running stylelint as a PostCSS plugin like with gulp.

I don't think there is any harm in exposing an option to do so. The user could then decide whether `postcss-reporter` or  `stylelint`'s reporter is best for the task in hand. For example, if they have multiple plugins in their pipeline that add warnings then they'd probably want to use `postcss-reporter` as it'll group all the warnings by file. If they're are using just `stylelint` (or, am I right in thinking, if `stylelint` is last in the pipeline?) they'd probably want to use `stylelint`'s reporter.

**Comment by davidtheclark** [comment]
gulp-stylelint (#846) will probably be able to replace the need for this.

**Comment by davidtheclark** [comment]
Closed in favor of #917.
