### ISSUE TITLE
`color-function-notation`: do not attempt to autofix when the syntax is invalid 

### ISSUE THREAD

**Issue by eric-higgins-ai** [stylelint/stylelint#7945]
### What minimal example or steps are needed to reproduce the bug?

stylelint --fix changes ```a { color: rgb(white, .5) }``` to ```a { color: rgb(white .5) }```, which sass fails to compile.

### What minimal configuration is needed to reproduce the bug?

```json
{ "rules": { "color-function-notation": "modern" } }
```

### How did you run Stylelint?

```sh
pnpm exec stylelint path/to/file.scss -c path/to/stylelint.config.js --fix
```

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "16.8.2",
    "stylelint-config-standard-scss": "13.1.0",
    "stylelint-order": "6.0.4",
    "stylelint-scss": "6.5.0",
}
```

### What did you expect to happen?

stylelint should suggest a valid syntax in this case (probably `rgb(white, 50%)`)

### What actually happened?

stylelint replaces `rgb(white, .5)` with `rgb(white .5)` which sass fails to compile

**Comment by Mouvedia** [comment]
@eric-higgins-ai in which browser is `rgb(white, .5)` considered a valid value?
ref https://drafts.csswg.org/css-color/#typedef-legacy-rgb-syntax

**Comment by ybiquitous** [comment]
I can reproduce the behavior with the following demo:

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLpANhAE7wpEDmARgBQDuAFgJY4wA0KAdAKwCUA3FgC+IViABmjfDABySALZxEMAB7yADlI5gAztpHgImCeQQgMmFCnQgiAVynbrpc5cvWCxALRjbmMDkZDT0wIHCQAwycrEDloGCJsECxLQSF9SCNGcgAxYjlw0wArbUN9WDU9RBdo7RwATyl8RkwcKOt8cJha6zTBIA)

And I think `rgb(white, .5)` is invalid as the standard CSS syntax.

However, I guess Sass may [support this syntax](https://sass-lang.com/playground/#eJwzNExUqObiTM7PyS+yUihKT9Ioz8gsSdVR0DPVtOaqBQCR9wkJ).

```scss
a {
  color: rgb(white, .5);
  /* ↓ compiled */
  color: rgba(255, 255, 255, 0.5);
}
```

If so, this should be addressed by a plugin (e.g., `stylelint-scss`), not the Stylelint built-in rule `color-function-notation`.

Instead, `color-function-notation` may need to be quiet when an invalid syntax occurs.

**Comment by Mouvedia** [comment]
related: #7927

**Comment by ybiquitous** [comment]
I'm okay with turning off the rule in any 3rd-party configs, but I think we can fix this false positive bug by improving the logic below. For example, checking the number of function arguments before a comma (,) etc.

https://github.com/stylelint/stylelint/blob/19e515e05e7fff94523963ecfdd473cf17dcbd9d/lib/rules/color-function-notation/index.mjs#L70

**Comment by Mouvedia** [comment]
@ybiquitous something like #7948?

**Comment by ybiquitous** [comment]
Yes! Thanks for the quick fix. 😄
