### ISSUE TITLE
`selector-class-pattern`: ensure the first message argument is trimmed

### ISSUE THREAD

**Issue by SArpnt** [stylelint/stylelint#7958]
### What minimal example or steps are needed to reproduce the bug?

```css
.88x, .88x>img {width:88px}
```

### What minimal configuration is needed to reproduce the bug?

```json
{"extends": ["stylelint-config-standard"]}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AOFAPANAAlRgfAJYC2A5tsAO6FQAuAFvGgA7oC+ImIAZoQDYwAcgENicRDHSjmApGADO8zuAgA7XqQQhgAHRCTaMVVHl742ANp75tAJ4C+hVbQC0kdYVIubw48IBOUHoAuhxc7hoAYhD+xMK0WgBW8mrKsMxKiLqq2NjWdg5OtGZ5IHzxMDZ6mDo5pTb2MI7Obmoa3rS+UAFBCKXlhlUgtRxsQA)

### Which Stylelint-related dependencies are you using?

stylelint: '^16.8.2',
'stylelint-config-standard': '^36.0.1',

### What did you expect to happen?

class selector should be shown as ".88x"

### What actually happened?

in second case class selector is shown as " .88x", which has a space at the start, not part of a selector
```
1:1-5 Expected class selector ".88x" to be kebab-case
1:7-12 Expected class selector " .88x" to be kebab-case
```
any amount of whitespace can be added after the comma, tabs, newlines, etc.

### Do you have a proposal to fix the bug?

ignore whitespace after commas

**Comment by Mouvedia** [comment]
I have just confirmed the bug.
Lemme check it out, it should be easy to fix.
