### ISSUE TITLE
block-closing-brace-newline-after with number of lines

### ISSUE THREAD

**Issue by fliptheweb** [stylelint/stylelint#796]
Rule for supporting [sass guidelines](http://sass-guidelin.es/#css-ruleset) by @HugoGiraudel.
`block-closing-brace-newline-after` must get int argument, number of lines (e.g `1`) OR new rule `block-empty-line-after`:
```css
.foo {
}
⟵ that line
.bar {
}
```

**Comment by jeddy3** [comment]
I think what you're asking for is already covered by the `*-empty-line-before` rules i.e.:

- [`rule-non-nested-empty-line-before`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-non-nested-empty-line-before/README.md)
- [`rule-nested-empty-line-before`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-nested-empty-line-before/README.md)
- [`at-rule-empty-line-before`](https://github.com/stylelint/stylelint/blob/master/src/rules/at-rule-empty-line-before/README.md)
- [`comment-empty-line-before`](https://github.com/stylelint/stylelint/blob/master/src/rules/comment-empty-line-before/README.md)

So, `"rule-non-nested-empty-line-before": "always"` will enforce your example style.

**Comment by fliptheweb** [comment]
Oh, sorry, i did't find that, because tried to find in `block` section of documentation.

**Comment by jeddy3** [comment]
No worries :)

There's [a little section](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#about-rule-names) at the bottom of the rules page that explains the naming conventions. In this instance, blocks appear in both `@rules` and rules/rule-sets, so the `brace` rules are named `block-*`. Whereas its is the rules/rule-sets, `@rules` and comments themselves that have an empty line before them.
