### ISSUE TITLE
Move to `css-tree` 3.x

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#7995]
### What is the problem you're trying to solve?

`declaration-property-value-no-unknown` rule uses `css-tree` validator.

Right now it uses 2.x version, which doesn’t support many features including `oklch()`

https://github.com/csstree/csstree/issues/244

### What solution would you like to see?

`css-tree` 3.0 version was released with many fixes

https://github.com/csstree/csstree/releases/tag/v3.0.0

**Comment by Mouvedia** [comment]
> Right now it uses 2.x version, which doesn’t support many features including `oklch()`

Sorry but the update won't close #7241.

**Comment by ai** [comment]
> Sorry but the update won't close https://github.com/stylelint/stylelint/issues/7241.

@Mouvedia why?

**Comment by Mouvedia** [comment]
> > Sorry but the update won't close #7241.
> 
> @Mouvedia why?

[As explained in the issue](https://github.com/stylelint/stylelint/issues/7241#issuecomment-2302913135), [channel "values"](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch#defining_relative_color_output_channel_components) are not supported by `css-tree`.
e.g. `a { color: oklch(from hsl(180 100% 50%) calc(l - 0.1) c h); }`
