### ISSUE TITLE
Document new `.gitignore` examples

### ISSUE THREAD

**Issue by rakleed** [stylelint/stylelint#8012]
### Describe the documentation issue

The documentation mentions in four places that you can use a `.stylelintignore` file to ignore files [^1] [^2] [^3] [^4], but nowhere directly says that you can use `.gitignore` for this, although that seems like a pretty convenient way to do it in most cases.

[^1]: https://stylelint.io/user-guide/configure/#ignorefiles
[^2]: https://stylelint.io/user-guide/ignore-code/#files-entirely
[^3]: https://stylelint.io/user-guide/cli/#--ignore-path--i
[^4]: https://stylelint.io/user-guide/options/#ignorepath

### What solution would you like to see?

[Prettier](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore:~:text=Prettier%20will%20also%20follow%20rules%20specified%20in%20the%20%22.gitignore%22%20file%20if%20it%20exists%20in%20the%20same%20directory%20from%20which%20it%20is%20run.) does this by default, [ESLint](https://eslint.org/docs/latest/use/configure/ignore#including-gitignore-files) has a separate subsection for this, and [Biome](https://biomejs.dev/guides/configure-biome/#ignore-files:~:text=You%20can%20also%20ignore%20files%20ignored%20by%20your%20VCS.) also mentions VCS integration.

It's probably worth mentioning in the [Configure](https://stylelint.io/user-guide/configure/#ignorefiles) section that you can use files with gitignore-like syntax to ignore multiple files (instead of specifically `.stylelintignore`, and the link on it isn't particularly visible).

In the [Ignoring code](https://stylelint.io/user-guide/ignore-code/#files-entirely) section, it's probably worth putting ignoring files first, and then disabling specific rules. Since when you first configure Stylelint, you'll most likely need to add general exceptions, and now they are quite difficult to get to. Also, after "[You can also specify a path to your ignore patterns file (absolute or relative to process.cwd()) using the --ignore-path (in the CLI) and ignorePath (in JS) options.](https://stylelint.io/user-guide/ignore-code/#files-entirely:~:text=You%20can%20also%20specify%20a%20path%20to%20your%20ignore%20patterns%20file%20(absolute%20or%20relative%20to%20process.cwd())%20using%20the%20%2D%2Dignore%2Dpath%20(in%20the%20CLI)%20and%20ignorePath%20(in%20JS)%20options.)" it's worth citing `.gitignore` as an example.

And perhaps in [Options](https://stylelint.io/user-guide/options/#ignorepath) it's also worth citing `.gitignore` as an example.

**Comment by ybiquitous** [comment]
@rakleed Thanks for the proposal. Adding examples about `.gitignore` sounds good to me. 👍🏼

**Comment by ybiquitous** [comment]
To simplify changes, I suggest:

- Add an example using `.gitignore` to `ignore-code.md#files-entirely`, e.g.

```shell
stylelint "*.css" --ignore-path .gitignore
```

- Make the `ignorePath` text a link in `ignore-code.md#files-entirely` to [`options.md#ignorepath`](https://github.com/stylelint/stylelint/blob/5eb544dcfce0a076a31b5fa1198b693a828a6cd5/docs/user-guide/options.md#ignorepath).

https://github.com/stylelint/stylelint/blob/5eb544dcfce0a076a31b5fa1198b693a828a6cd5/docs/user-guide/ignore-code.md?plain=1#L90
