### ISSUE TITLE
Missing documentation - how to unit test a custom stylelint rule

### ISSUE THREAD

**Issue by scottlikestech** [stylelint/stylelint#8018]
### Describe the documentation issue

Since upgrading to stylelint 16.9.0 and jest-preset-stylelint 7.1.0 my custom scss rules fail when running the unit tests for them.  
The failure object has "text": "Unknown rule for MyRuleName" but the pre-checks before it gets this far already check these things I think.

The url https://stylelint.io/developer-guide/rule-testers/ seemed like the perfect place to go for seeing the latest code to write a unit test for a custom rule, but it does not work.

My unit test is like this.  I omit the reject tests to make the code smaller:

import testRule, { TestSchema } from 'jest-preset-stylelint';
import { ruleName, errorMessage } from './no-grayscale';

const schema: TestSchema = {
    plugins: ['./src/rules/scss/no-grayscale/no-grayscale.ts'],
    ruleName: ruleName,
    config: true,
    fix: false,
    accept: [
    {
        code: `.myclass {
            /*filter: grayscale(0);*/
        }`,
        description: 'Ignore usage if in comment.'
    }],
    reject: []
};

const runRule = testRule.getTestRule();
runRule(schema);

### What solution would you like to see?

Where is the documentation to write a unit test against a custom stylelint rule?

**Comment by ybiquitous** [comment]
@scottlikestech Thanks for the report. But I think the testing is already documented here: ⬇ 
https://stylelint.io/developer-guide/plugins#testing

For details of `jest-preset-stylelint`, the package's document should describe instead.
