### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#802]
- [x] `color-no-named`
- [x] `declaration-block-no-single-line`
- [x] `rule-no-duplicate-properties`
- [x] `rule-properties-order`
- [x] `rule-no-shorthand-property-overrides`
- [x] `rule-trailing-semicolon`
- [x] `declaration-block-properties-order` `true` value for `"emptyLineBefore"` option
- [x] `font-weight-notation` option `"named"`
- [x] `warn: true` option, inc. ignore in `optionsValidator`

**Comment by davidtheclark** [comment]
Closed by #902.
