### ISSUE TITLE
Promote project

### ISSUE THREAD

**Issue by ai** [stylelint/stylelint#805]
I think it is not fair, that so awesome project has only 24K download per month.

I think you should write a article to CSS Tricks about:

1. Why linting CSS is important
2. What is difference between Stylelint and other CSS linters
3. How to start to use it

CSS Tricks article was a very important booster for Autoprefixer in the past.

**Comment by davidtheclark** [comment]
Ha ha! Thanks, @ai. I agree that we can do more to promote it. Personally, I've been working so hard on adding new features and things that I've kept putting off the idea of promotion. I keep thinking, "I'll write an article about it after we finish a, b, c ..... hmm, maybe after x, y, and z .... and so on."

Now the website is structurally sound, the architecture is proven and pretty stable; so yeah, I'd agree that I should stop putting this off.

**Comment by ai** [comment]
I am glad to help you. But you can write a article much better than I can do it :)

**Comment by davidtheclark** [comment]
FYI: I've asked both CSS Tricks and Smashing Mag if they're interested in me writing an article about stylelint. We'll see.

**Comment by evilebottnawi** [comment]
@danieldiekmeier In the future, we can help in translation, and write article on https://habrahabr.ru/ for russian developer @ai .

**Comment by danieldiekmeier** [comment]
@evilebottnawi Seriously? Can you PLEASE PLEASE PLEASE stop mentioning me in random issues on this project? It can not be that hard! I get an email every time and it is incredibly annoying.

**Comment by jeddy3** [comment]
(issue triage)

Closing this as requests sent.

**Comment by davidtheclark** [comment]
CSS-Tricks showed interest in an article. And I just finished a draft. If anybody wants to take a few minutes to provide feedback, I'm open to suggestions! https://draftin.com/documents/840290

**Comment by ai** [comment]
Draftin requires a signup :(. Maybe Google Docs? =^_^=

**Comment by davidtheclark** [comment]
CSS-Tricks uses draft so I'll keep editing there. But here's the current state of it as a google doc: https://docs.google.com/document/d/1Qv15Fy6B-ZSXoJrUAzbG7h_BSatMuLQk4offBLNhOlU/edit?usp=sharing

**Comment by ai** [comment]
@davidtheclark pfff, why I even open a draft. You write great as always :). Really good text flow and story points.

**Comment by davidtheclark** [comment]
Thanks you :)

**Comment by m-allanson** [comment]
I'd like to second @ai's comment and point to a minor typo:

> birth of a might new stylesheet linter

**Comment by ntwb** [comment]
Fantastic David

One thought, should a reference be added to the ~72 "stylelint" config/plugins currently published?

**Comment by davidtheclark** [comment]
Good suggestion @ntwb.

**Comment by jeddy3** [comment]
@davidtheclark Looks brilliant! I've made a few suggestions in the google doc.

**Comment by davidtheclark** [comment]
@jeddy3 Thanks for the detailed feedback.

**Comment by ntwb** [comment]
Another suggestion, as part of each new release can stylelint make an announcement tweet of the release?

_With 10 major/minor and 12 patch releases this year stylelint itself has only tweeted three times and retweeted others release announcements twice._

**Comment by davidtheclark** [comment]
Who again has access to that account -- is it just @MoOx? Is there a way that I or @jeddy3 can use it?

**Comment by MoOx** [comment]
I transferred full access to @jeddy3, but he is not a twitter guy from what I know :)

**Comment by MoOx** [comment]
Btw I own the domain name, maybe I should transfer it to someone?

**Comment by davidtheclark** [comment]
Oh yeah, now I remember. @jeddy3 do you want to transfer to me? I use the Twitters :)

@MoOx if you'd like to transfer it to me I can take it on.

**Comment by ntwb** [comment]
> @jeddy3 do you want to transfer to me? I use the Twitters :)

You can share the Twitters :bird:

**Comment by MoOx** [comment]
@davidtheclark do you have a gandi.net account so I can easily transfer ownership of the domain to you?

**Comment by davidtheclark** [comment]
@MoOx I have a site5 account. Looks like it should be fairly straightforward: https://kb.site5.com/domains/how-to-transfer-a-domain-to-site5/. If you want to email me a transfer (EPP) code I can follow their instructions tonight. Sound good?

**Comment by MoOx** [comment]
@davidtheclark I just sent you the auth code to the mail I found on your github profile.
