### ISSUE TITLE
font-weight-notation: named should not complain about numbers without keyword equivalents

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#806]
Just realized this.

For example, there is no way to indicate `font-weight: 600` with a keyword, so the rule shouldn't complain. The option should probably be changed to `named-where-possible`, too.

Disagreement?

**Comment by jeddy3** [comment]
> The option should probably be changed to named-where-possible, too.

Sgtm. Does that mean deprecating the old option name?

**Comment by davidtheclark** [comment]
Yeah, I was thinking that we could make the transition smooth by keeping both available and deprecating.

**Comment by jeddy3** [comment]
Yep, it seems sensible to follow this approach whenever we can.

I suggest we keep track of all the deprecated features in https://github.com/stylelint/stylelint/issues/802. It's on the `5.0.0` milestone.

**Comment by dan-gamble** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

Based on the `Common weight name mapping` section it seems 1-900 are named or have i misunderstood this issue?

**Comment by davidtheclark** [comment]
@dan-gamble: What we're referring to as "named" are the keywords that are not numbers: `bold`, `normal`, `bolder`, `lighter`. What I mean is there's no keyword like `semibold` to get a font-weight of 600.
