### ISSUE TITLE
Add LESS parser support

### ISSUE THREAD

**Issue by patsissons** [stylelint/stylelint#810]
The LESS parser support would be fairly easy to add by simply extending how the `syntax` config option is processed and importing [postcss-less](https://github.com/gilt/postcss-less).

Even though `postcss-less` development is not fully complete, it already supports the majority of basic LESS syntax and usage. 

thoughts? if there is interest I could submit a PR pretty quickly.

**Comment by dan-gamble** [comment]
I'd say go for the PR :) I don't use Less myself but if theres a Sass option a Less option wouldn't go amiss

**Comment by davidtheclark** [comment]
What's going in between this postcss-less and the other: https://github.com/webschik/postcss-less?

Have you two talked?

**Comment by patsissons** [comment]
interesting, seems to be two independent attempts at the same result.

**Comment by davidtheclark** [comment]
Yeah. I would prefer if they sort that out before we pick one to integrate. I'm going to mark this issue as blocked.

@gilt, @webschik: Any input here?

**Comment by patsissons** [comment]
webschik's is available via npm so probably go with that one i guess?

**Comment by webschik** [comment]
Hi guys! It seems like for stylelint is better to integrate https://github.com/gilt/postcss-less, because I don't have enough time to contribute to my project. Probably @gilt leads a more active development.

**Comment by patsissons** [comment]
@webschik it looks like yours is most recently active. proposing that we perhaps attempt to merge the current dev efforts into your repo to simplify publishing to npm?

**Comment by davidtheclark** [comment]
@jeddy3 What do you think?

**Comment by jeddy3** [comment]
I'm not sure. There's another version here: https://github.com/matthew-dean/postcss-less

Do we wait until there is a *maintained* and definitive less parser before integrating?

**Comment by patsissons** [comment]
There is some value in adding an incomplete (and already npm-able) package, in that it brings immediate (although basic) support for LESS files. That said, I can put some time in this weekend looking at all three of these projects (and any others if they exist) to see if it is possible to merge any unique efforts. The primary goal for a basic LESS support milestone is to simply ignore LESS syntax that is not understood and give visibility to style syntax that is understood.

**Comment by davidtheclark** [comment]
We might want consider adding less support with an "experimental" flag or something until the various nascent projects have figured out what they're going to do. 

It's also true that by introducing a Less parser into stylelint it will help that Less parser along, because stylelint users will find bugs that can be redirected to the Less parser.

The "experimental" flag would just to prevent users from getting too upset at stylelint for promising they can use Less when in fact they hit parser bugs.

@patsissons If you want to do some legwork to try to merge unique efforts on Less parsers, that would be awesome. I'm sure @ai would really appreciate it, too.

**Comment by webschik** [comment]
@patsissons , I've created my [postcss-less](https://github.com/webschik/postcss-less) library exactly to use with stylelint. My devteam uses it now with stylelint (I had to change a couple of lines in stylelint) to vaidate our LESS stuff. It works normal, but has some problems and doesn't support all LESS features. Try to include this library to stylint locally and make some tests.

**Comment by ai** [comment]
@webschik if you will have questions about parser and tokenizer, feel free to ask me directly (by email for example)

**Comment by jeddy3** [comment]
> The "experimental" flag would just to prevent users from getting too upset at stylelint

Agreed. I think using an experimental flag is the right way to go about this.

> It's also true that by introducing a Less parser into stylelint it will help that Less parser along,

Yep, I agree with that.

> @patsissons If you want to do some legwork to try to merge unique efforts on Less parsers, that would be awesome.

That would be fantastic!

**Comment by patsissons** [comment]
I got started on this work today. https://github.com/patsissons/postcss-less/tree/develop will be my testing grounds for source integration. I did take a brief look at the other two repos but it will not be super easy to merge the efforts as there are slightly different approaches to certain things. I have already resolved a bug that was preventing the postcss integration tests from passing.

I began the stylelint less branch as well: https://github.com/patsissons/stylelint/tree/feature/less. not sure how you guys want to implement the experimental flag, I'm open to ideas. I just stubbed in the required code to start using the less parser for now. Eventually I will get my postcss-less repo pushing to npm (or create a new package if that's more appropriate).

I plan to do a small amount of looking into merging the efforts (my brief investigation showed that there was not much significantly different code betwee @webschik and @gilt repos). I will also do some various testing with my current repo and just using stylelint (specifically with the [vscode](https://github.com/shinnn/vscode-stylelint) extension).

let me know if you have any specific thoughts on this. hopefully i get to some of this during the week.

**Comment by davidtheclark** [comment]
Awesome, @patsissons.

Make sure to refer back to postcss-scss as the canonical example.

**Comment by jeddy3** [comment]
> I got started on this work today.

Excellent!

> not sure how you guys want to implement the experimental flag, I'm open to ideas.

@davidtheclark Were you imagining this just being a documentation thing, or something more?

> I plan to do a small amount of looking into merging the efforts

It might be worth approaching the main contributor of the gilt repo (@-shellscape), as I think @gilt is dropping off into a hole as that's a github org.

**Comment by patsissons** [comment]
I merged in @webschik's work tonight, I had to patch some of the code a bit to get the tests to pass, and it looks like there might be a benign branching issue (see below), but otherwise the merge was successful. If I have time tomorrow I will get these modules in place locally to test everything out in with the `vscode` extension.

branching issue concerns the following in the tokenizer:
```js
if (code === DOT || code === HASH) {
// ...
} else if (code === AMPERSAND) {
// ...
} else if (code === HASH && n === OPEN_CURLY) {
// ...
}
```
I'm not sure what the intent of @webschik's additions in this area are (the tokenizer is a little terse to just jump into for me) so I don't want to presume any fixes at this point. The branch does not get hit right now and as such doesn't interfere with existing tokenizer code.

**Comment by webschik** [comment]
Hi, guys!

I've just updated my library. I added test cases, made a code refactoring and fixed some bugs. 
@patsissons, it would be really nice if someone from Stylelint team checks these changes and tries to implement my library to Stylelint config. 

My front-end team use my LESS parser for PostCSS with Stylelint, we just use `syntax: 'less'` configuration for Stylelint and patched one .js file from its sources. We use about 90% LESS features and in general parser works fine, but with some [restrictions](https://github.com/webschik/postcss-less#restrictions). 

If I can help you more, please, feel free to ask me.

**Comment by jeddy3** [comment]
Good stuff! Thanks for the heads up @webschik .

@patsissons How does this update factor into your work? I'm still a little confused about which variant of `postcss-less` we should be consuming.

**Comment by patsissons** [comment]
Hey guys, I just finished merging @webschik's updates into my fork. I added a bunch of new tokenizer tests to capture some of the postcss integration tests that were failing on some of the nested mixin handling (as well as some other tokenizer issues).

@webschik maybe you want to take a look at what I have done today and see if we can merge our efforts soon?

**Comment by webschik** [comment]
@patsissons it will be nice.

**Comment by jeddy3** [comment]
@patsissons @webschik Excellent work the two of you!

Please let us know, once everything is merged up, which npm module we should consumed and we'll get a new release out with the less `syntax` option wired up :)

**Comment by patsissons** [comment]
I just finished merging my changes onto @webschik's repo. PR submitted and build passing.

**Comment by jeddy3** [comment]
Excellent! :) Keep up the good work and let us know once it's published to npm.

PR is here for those interested: https://github.com/webschik/postcss-less/pull/12

**Comment by thasner** [comment]
looks like @patsissons changes just merged [4 hrs ago!](https://github.com/webschik/postcss-less/commits/master).

Is the plan to maintain the npm repo via [webschik/postcss-less](https://github.com/webschik/postcss-less)?
