### ISSUE TITLE
Change `detail` sentence of `GITHUB_FORMATTER` deprecation warning

### ISSUE THREAD

**Issue by tagliala** [stylelint/stylelint#8111]
### What is the problem you're trying to solve?

A lot of linters have their own built-in GitHub formatter, and this is also the case with stylelint

However, the GitHub formatter has been deprecated and it suggests to switch to a third-party alternative which prints deprecation messages, it is not trivial to configure (apparently), and appears to not be maintained

### What solution would you like to see?

Reconsider the deprecation, or advise for an actively maintained alternative

The alternative,

- https://github.com/xt0rted/stylelint-actions-formatters

should be used in conjunction with (or entirely replaced by, this is not clear)

https://github.com/xt0rted/stylelint-problem-matcher

does not seem maintained. 

I didn't find a way to make it work in a GitHub action. I have some test cases here:

Ref: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/pull/984

I've asked for some clarifications one month ago at xt0rted/stylelint-problem-matcher#592 and also commented at the original request to make it the official suggested formatter at https://github.com/xt0rted/stylelint-actions-formatters/issues/187#issuecomment-2399118878

---

https://github.com/stylelint/stylelint/blob/13933eda2c6430ea2c595f02f47799adbda771df/lib/standalone.mjs#L114

**Comment by romainmenke** [comment]
Hi @tagliala,

I was facing the same issue. I investigated the alternatives and all of them were too complex for my taste. The formatter that was removed was much more elegant.

So I created a drop-in replacement: https://github.com/csstools/postcss-plugins/tree/main/plugins-stylelint/formatter-github#csstoolsstylelint-formatter-github

This is purely the formatter that used to be builtin, but then packaged as a standalone.
This is actively maintained.

**Comment by tagliala** [comment]
@romainmenke thanks for the prompt response and for the suggestion

I've configured the action and now it works without deprecations, thanks!

Changes to make it work (if you have better suggestions I'll be glad to improve the action): https://github.com/diowa/ruby3-rails7-bootstrap-heroku/pull/1006/files 

I would leave this open as a reference until:
- The entry in the readme is added
- Deprecation message `Please use "stylelint-actions-formatters" instead.` is changed into something else

**Comment by Mouvedia** [comment]
I've labeled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
