### ISSUE TITLE
Add `atRulesSyntax: {}` and `cssWideKeywords: []` options in `declaration-property-value-no-unknown`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint#8113]
### What is the problem you're trying to solve?

`csstree` is sometimes a bit behind the most recent CSS features resulting in false positives.

For `properties` and `types` we can already pass updated definitions as rule options.
However `atRules` and `cssWideKeywords` extensions are not exposed.

I want to be able to extend any part of the CSS syntax definitions in `csstree`.

### What solution would you like to see?

New plugin options:
- `atRulesSyntax: {}` [^1]
- `cssWideKeywords: []` [^2]

This will allow users to extend any part of the CSS syntax definitions.

[^1]: https://github.com/stylelint/stylelint/issues/8100#issuecomment-2462386218
[^2]: https://github.com/stylelint/stylelint/pull/8105#discussion_r1829506849

**Comment by ryo-manba** [comment]
I've added the type definitions.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71155

Without this update, type errors occur.

**Comment by jeddy3** [comment]
Closing this in favour on the new rules that have come out of https://github.com/stylelint/stylelint/issues/8133
