### ISSUE TITLE
Mention Adidas and GitLab as notable users of stylelint

### ISSUE THREAD

**Issue by blyedev** [stylelint/stylelint#8123]
### Describe the documentation issue

Marketing is important

### What solution would you like to see?

Submitted a matching issue in stylelint/awesome-stylelint#82.

**Comment by jeddy3** [comment]
@blyedev Thanks for the suggestion. We did list more users back in the day but shortened it to two big ones to keep the feature lines short and punchy. As there hasn't been any uptake of this issue by other maintainers, I will close.
