### ISSUE TITLE
Add `{ "ignore": ["at-rules", "declarations"] }` to `string-no-newline`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8151]
### What is the problem you're trying to solve?

The overlap between `string-no-newline` and `declaration-property-value-no-unknown`.

```css
a {
	content: "
	";
}
```

With:

```json
{
  "rules": {
    "declaration-property-value-no-unknown": true,
    "string-no-newline": true
  }
}
```

Gives:

```console
2:11-12 error Unexpected newline in string (string-no-newline)
2-3:11-3 error Cannot parse property value """" for property "content" (declaration-property-value-no-unknown)
```

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLpTOMB8K6IWuZA3FgL4gA0IAZgJYA2MAckgLZyIYADz4AHTgDowAZ2mNwETGwDmCEBkwpSIAE4BXTtLIkNWrWVhh2SHUhytFAWlE6IomDpwBPRwDck7HowjpgQjnqYANahAO7YCCg4+jAMWGba0kmsmMohYZgwMezZMMaJyWkotHTy+CoAYhA6vHZqAFbSivKwonKIphnenMUEZWTWhJlkqZqDXsPZOI51rLmZSJhQNlBjIBMwU+SY9LRAA).

### What solution would you like to see?

Adding an `"ignore": ["at-rules", "declarations"] }` option to `string-no-newline`.

**Comment by Mouvedia** [comment]
So the only node type that could not be ignored would be `'rule'`?

https://github.com/stylelint/stylelint/blob/22e39e2dd3a09ffccd6d1223720aa1fee3d92a62/lib/rules/string-no-newline/index.mjs#L37

**Comment by jeddy3** [comment]
Yes, that's correct. It'd only check the selectors of rules to avoid overlapping with checks for newlines in strings:

- declaration values by `declaration-property-value-no-unknown`
-  at-rule preludes by the proposed `at-rule-prelude-no-unknown`
