### ISSUE TITLE
Add `transform-notation`

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8164]
### What is the problem you're trying to solve?

Enforce a consistent notation for transforms.

[Properties](https://drafts.csswg.org/css-transforms-2/#individual-transforms):

```css
a {
  rotate: 45deg;
  scale: 2;
}
```

[Functions](https://drafts.csswg.org/css-transforms-1/#transform-property):

```css
a {
  transform: scale(2) rotate(45deg);
}
```

### What solution would you like to see?

A new rule:

- Name: `transform-notation`
- Description: Specify functions or properties notation for transforms.
- Message: `Expected "{$primary}" notation`
- Primary option: `"functions"|"properties"`
- Secondary options: none
- Category: Enforce conventions > Notation
- Autofix?: Yes, if possible 
- Included in sharable configs?: Yes, standard with `"properties"`
- Extended description: Something about individual properties being more modern but also any caveats

**Comment by romainmenke** [comment]
Thank you for opening this issue @jeddy3

On the surface the individual props seem to be mostly syntactic sugar but they aren't.
These are separate controls that are cumulative with the `transform` property.

I think that in the simple cases most authors will want to use either `transform` or the individual properties and this proposed rule would help maintain consistency.

But I also think that the more complex use case should not be advised against.

there is nothing wrong with writing:

```css
.component {
  transform: translate(10px, 10px) rotate(45deg);
}

.component[data-rotate=10] {
  rotate: 10deg; /* 10deg rotated from the base style -> 55deg */
}
```

In this case the author wants the cumulative effect of combining both `transform` and `rotate`.

I also don't think we can say that the individual properties are more "modern" as that could be misunderstood as "better". These were added later as an addition but not as a replacement.

I don't want authors to think that they are doing something wrong or following a bad practice by combining both in a single codebase. As combining both can be a good way to reduce duplication and achieve specific effects.

Maybe this shouldn't be in the standard or recommended configs?

--------

I also think it would be better if this doesn't have an autofix.
Or if we do add an autofix we might need to document several caveats.

Fixing is only safe for `transform` -> individual props when:
- we are 100% sure that no other rules set individual props (we can't know that with static analysis)
- the order in `transform` matches the predefined order for the individual properties
- there is only one of the matching functions and no others (e.g. `transform: rotate(10deg) rotate(20deg)`, `transform: rotate(10deg) matrix(...)`)

Fixing is only safe for individual props -> `transform` when:
- we are 100% sure that no other rules sets a `transform` (we can't know that with static analysis)
- we emit a `transform` property in the correct order (this is trivial, but we must make sure we get it right)

-------

For the order see:
https://codepen.io/romainmenke/pen/LEPVRjN

For the cumulative behavior see:
https://codepen.io/romainmenke/pen/GgKJjvv

**Comment by jeddy3** [comment]
@romainmenke Thank you for clearly explaining the problem space. 

As users can already use [`property-disallowed-list`](https://stylelint.io/user-guide/rules/property-disallowed-list) for the simple use case and because autofix has unsafe caveats, I'm inclined to close this issue.
