### ISSUE TITLE
Stylelint turns 10 years old today!

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#8169]
We opened our [first issue](https://github.com/stylelint/stylelint/issues/1) 10 years ago today.

A huge thank you to every volunteer who has contributed to Stylelint over the years! 

Through thousands of hours of effort, discussing, planning, and making decisions that balance competing needs and ultimately writing code, we have created a tool that has helped many people write better, cleaner and error-free CSS. 

On a personal note, I feel immense gratitude towards all my fellow contributors. It's been a pleasure collaborating with you. Your generous guidance has taught me so much about the CSS language and JavaScript tooling. Thank you.

(I've put out a tweet, too).

**Comment by Mouvedia** [comment]
@ybiquitous @davidtheclark @hudochenkov @ntwb @romainmenke @alexander-akait @mattxwang

**Comment by romainmenke** [comment]
Amazing milestone!
Thank you all for this decade of awesome work supporting fellow CSS authors 🎉 

Also wanted to thank everyone for being so welcoming and helpful to other contributors 🙇 
Stylelint really is a pleasure to contribute to.
