### ISSUE TITLE
Fix `selector-pseudo-class-no-unknown` false positives for `:open`

### ISSUE THREAD

**Issue by lukewarlow** [stylelint/stylelint#8183]
### What is the problem you're trying to solve?

If you use `:open` in your styles, stylelint will complain that it's an unknown pseudo class.

See demo: https://stylelint.io/demo/#N4Igxg9gJgpiBcICWA7ADgVwC7wmmKABMADoolYBGEATrDQLSQA2t8hNMUA3GQL4gANCABmSZjAByAQwC2cRDAAectBIB0YAM5ah4CCjEBzBCFJFCJEMqwEoWq+wDaZQm8sgtWAJ4TmqLCYDYwYvaRQoaTorV0IAXX49SEMkIwAxWllpLFMAKy0DPVg0XURzNysvXxh-FCxHD2ZsmC8rQVjKnz8AoJSjUKxwyOiERubWkES+IA

### What solution would you like to see?

It would be good if stylelint added support for `:open` pseudo class, so it didn't get flagged as an unknown pseudo.

See [CSS spec here](https://drafts.csswg.org/selectors-4/#open-state) and [HTML spec here](https://html.spec.whatwg.org/multipage/semantics-other.html#selector-open) for details on this new pseudo class.

**Comment by Mouvedia** [comment]
related: #7510

**Comment by skyclouds2001** [comment]
I've also fired https://github.com/mdn/data/pull/953 to fix it in upstream
