### ISSUE TITLE
font-size-unit-whitelist and font-size-unit-blacklist

### ISSUE THREAD

**Issue by nathanjessen** [stylelint/stylelint#822]
Feature request (new rules)

I'm beginning to work on a new rule for a whitelist/blacklist of acceptable units for font-size values. In my current project, we would like to warn developers every time a px value is used for a font-size. Our rule is that em or rem should always be used when setting a font-size. We are using scss but the rule should be useful for any CSS.

**Comment by jeddy3** [comment]
@nathanjessen You can use [`property-unit-whitelist`](http://stylelint.io/user-guide/rules/property-unit-whitelist/) or [`property-unit-blacklist`](http://stylelint.io/user-guide/rules/property-unit-blacklist/) to achieve this.

> I'm beginning to work on a new rule

It's great that you're wanting to contribute though! Free feel to see if any of [the planned new rules](https://github.com/stylelint/stylelint/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+rule%22) would be useful to you, and to give them a go :)
