### ISSUE TITLE
Have `declaration-property-value-no-deprecated` report "quirky" hex colors

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#8226]
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  background-color: 96ed2a;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-property-value-no-deprecated": true
  }
}
```

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.13.0",
}
```

### What did you expect to happen?

For the rule to report hashless color values for these properties:

- `background-color`
- `border-color`
- `border-top-color`
- `border-right-color`
- `border-bottom-color`
- `border-left-color`
- `color`

### Resources

https://www.w3.org/TR/css-color-4/#typedef-quirky-color
https://bugzilla.mozilla.org/show_bug.cgi?id=774122
https://issues.chromium.org/issues/40395348

**Comment by romainmenke** [comment]
Do we want to cover anything from quirks mode?
I would personally avoid this.

Maybe a community maintained plugin for quirks mode aspects is a better fit?

**Comment by Mouvedia** [comment]
I am not sure either, but our users would probably expect this rule to report any deprecated value.
It's also a way to propose renaming it `declaration-property-keyword-no-deprecated`.
i.e. should all types of values really be covered by this rule?

**Comment by romainmenke** [comment]
My thinking is more that anything from quirks mode isn't really deprecated in the typical way.
Very very few users still have quirks mode enabled in their browsers and likewise very few developers are targeting quirks mode.

This is such an ancient mechanic that I think we can just ignore it.
You can also see this in the age of the issues you linked, those are +10 years old. In all the time Stylelint has existed only a single issue has been filed about anything from quirks mode (https://github.com/stylelint/stylelint/issues/8096#issuecomment-2450965483) and that was when a developer accidentally enabled quirks mode.

Having a warning that says: `This is a quirks mode feature and those are not allowed in your project` would be more helpful than `This feature is deprecated`.

But I would personally just leave this up to a community maintained rule, dedicated to quirks mode features. For `declaration-property-value-no-deprecated` I would completely ignore any quirks mode features as if they never existed in the first place.

**Comment by Mouvedia** [comment]
Since we are reporting the "Deprecated CSS System Colors" of the [Appendix A](https://www.w3.org/TR/css-color-4/#deprecated-system-colors) I thought it would be logical to follow suit with the "Deprecated Quirky Hex Colors" of the [Appendix B](https://www.w3.org/TR/css-color-4/#quirky-color).

**Comment by jeddy3** [comment]
> This is such an ancient mechanic that I think we can just ignore it.

Sounds good to me.

> i.e. the scope—value—might be too large

We can clarify the scope of the rule in the README.
