### ISSUE TITLE
Document using type import in CommonJS config example

### ISSUE THREAD

**Issue by rakleed** [stylelint/stylelint#8230]
### Describe the documentation issue

If a user uses CJS in their project, they will most likely go straight to the [CJS example](https://stylelint.io/user-guide/configure#:~:text=and%20type%2Dcheck.-,CommonJS%20example%3A,-module.exports) and skip the ESM example. And accordingly, he will not see an example of how types can be imported.

### What solution would you like to see?

In the CommonJS example, add a line on top:
```js
/** @type { import('stylelint').Config } */
```

**Comment by jeddy3** [comment]
@rakleed Thanks for the suggestion. SGTM.

I've labelled the issue as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.
