### ISSUE TITLE
Feature request: new rule "disable-shorthand-properties"

### ISSUE THREAD

**Issue by WickyNilliams** [stylelint/stylelint#838]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I think it would be valuable to have a rule to enforce that no shorthand properties are used (e.g. `background`, `font`, `transition`).

I always prefer to explicit about CSS and use longhand properties

**Comment by jeddy3** [comment]
You can do this already with [`property-blacklist`](https://github.com/stylelint/stylelint/tree/master/src/rules/property-blacklist) :)

**Comment by WickyNilliams** [comment]
Of course! D'oh! Thanks for quick response, much appreciated :)

**Comment by jeddy3** [comment]
No worries :)
