### ISSUE TITLE
Display severity level in string and verbose formatters

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#843]
Ref: https://github.com/stylelint/stylelint/issues/836#issuecomment-191667554
![3b81c212-e128-11e5-9e51-6038cefbe0e3](https://cloud.githubusercontent.com/assets/808227/13491569/f65cc792-e12a-11e5-803f-fde1e83c734d.png)

**Comment by onigoetz** [comment]
I PR'd a new style in `postcss-reporter` postcss/postcss-reporter#23 that implements that proposition.

When (if) this is accepted and released, it will just be a version update away.

( but would also need to pass a different severity parameter, as explained in #842 )

**Comment by davidtheclark** [comment]
Closed in favor of #917.

**Comment by danpoltawski** [comment]
Given #917 is closed, i'm not quite sure what the solution is here? (Currently using grunt postcss,and would love to get errors and warnings differentiated)

**Comment by jeddy3** [comment]
I believe [`grunt-stylelint`](https://github.com/wikimedia/grunt-stylelint) exposes stylelint's built-in formatters. We [recommend using](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-lint-using-my-task-runner-of-choice) dedicated stylelint task runner plugins where available.

**Comment by danpoltawski** [comment]
Thanks, I just discovered that - for some reason I thought the documentation was pointing me towards postcss being the best way to handle my situation (using less). grunt-stylelint has much simplified my approach 🌟
