### ISSUE TITLE
Rename selector-no-descending-specificity

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#844]
https://github.com/stylelint/stylelint/issues/835#issuecomment-191693683 just made realise that we've misnamed `selector-no-descending-specificity`. Which is fortunate as we can correct the mistake before releasing `4.5`. It's my bad as I should've caught it in the review.

We had [originally agreed](https://github.com/stylelint/stylelint/issues/748#issuecomment-186662962) to call it `no-descending-specificity`, as the rule behaves more like `no-duplicate-selectors` (compares selectors across the sheet), than something like `selector-max-specificity` (tests each selector in isolation).

I can make the change this afternoon.

**Comment by davidtheclark** [comment]
Damn, sorry.
