### ISSUE TITLE
Advocate gulp-stylelint when using stylelint with gulp

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#846]
Ref: https://github.com/stylelint/stylelint/issues/842#issuecomment-191764353

**Comment by jeddy3** [comment]
Waiting on the outcome of https://github.com/olegskl/gulp-stylelint/issues/3 and https://github.com/olegskl/gulp-stylelint/issues/4

**Comment by davidtheclark** [comment]
Closed in favor of #917.

**Comment by davidtheclark** [comment]
Re-opening because of problems with #917, and because gulp-stylelint v1 is looking great (hopefully coming out soon).

**Comment by jeddy3** [comment]
> Re-opening because of problems with #917,

Yep, that was a shame but it didn't seem resolvable within the PostCSS reporter framework.

`gulp-stylelint` is looking great though. As is `stylelint-loader`.

**Comment by jeddy3** [comment]
`1.0.0` of `gulp-stylelint` [is out](https://www.npmjs.com/package/gulp-stylelint).

**Comment by davidtheclark** [comment]
Yeah. We just figure out how to document this suggestion.

**Comment by davidtheclark** [comment]
Done in #1042.
