### ISSUE TITLE
Rename color-no-indistinguishable

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#849]
I've been taking a much closer look at all the rule names in the hope of getting the new rule we're releasing in `4.5` right the first time.

I think we should rename `color-no-indistinguishable` to `no-indistinguishable-colors` as it compares the colors across the entire sheet. Therefore it's much more like:

- `no-duplicate-selectors`
- `no-unknown-animations`

Than these (which test each color in isolation):

- `color-hex-case`
- `color-hex-length`
- `color-named`
- `color-no-hex`
- `color-no-invalid-hex`

**Comment by davidtheclark** [comment]
Sure, seems fine to me. I worry that those distinctions (e.g. is it about colors compared or colors in isolation) are probably lost on most users; so their most important value is in providing *us* create names that are meaningful and discoverable and *probably* won't change. So whatever logical distinctions we make that help us towards that end, I'm in favor of. And I think this one is good. Thanks so much @jeddy3 for the thoughtfulness you put into this kind of organization and API UX.
