### ISSUE TITLE
Consider using balanced-match to read/ignore values for some tests

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#85]
Currently some test ignore `content` prop.
But `content` can use function too. And some other function (url ?) might contains characters like `)` which might break some tests...
So using something like balanced-match to read parenthesis/string content might be a solution. We need to double check that this solution will take care of escaped characters like `"blah\"blah"` and also handle this correctly `url("path/to/the(image).jpg")`.

Reference: https://github.com/stylelint/stylelint/pull/82/files#r30671474

**Comment by davidtheclark** [comment]
I wasn't sure that balanced-match was going to address exactly what we needed, so I wrote this `valueIndexOf()` function to find the index of characters within a declaration's value while ignoring strings (as in `content:` or `url()`) and optionally only looking on the inside or outside of functions (as necessary for the `function-comma-*` and `declaration-comma-*` rules). I think it's working pretty well, and tried to get enough tests in place to prove that. Please offer feedback or more tests if you've got it!
