### ISSUE TITLE
Bring `stylelint-statement-max-nesting-depth` into core

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#854]
With nesting support coming baked-in in the likes of `no-duplicate-selectors`, `no-descending-specificity` and `selector-max-specificity`... how do we feel about moving `stylelint-statement-max-nesting-depth` into core?

`stylelint-selector-bem-pattern` will still be around as the perfect example of a plugin i.e. it is applicable only to a particular methodology.

**Comment by davidtheclark** [comment]
Yeah that makes sense to me.
