### ISSUE TITLE
Pin to Eslint 2.2.0 until 'estraverse-fb' bug is fixed

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#877]
Until eslint/eslint#5476 is fixed, we need to use ESLint v2.2.0.

The semver used in `package.json` is `^2.2.0` which causes ESLint v2.3.0 to be installed on clean installs.

This is causing issues for `stylelint` v4.5.0 and `stylelint-config-standard` v4.0.0 with AtomLinter/linter-stylelint, see https://github.com/AtomLinter/linter-stylelint/pulls

**Comment by ntwb** [comment]
Likewise for all the `stylelint-config-*` repos should also pin to ESLint v2.2.0 until resolved upstream

This would also require a new release, stylelint `4.5.1` if my semver brain is working correctly :smirk:

**Comment by jeddy3** [comment]
Thanks for flagging this :)

Released in `4.5.1`.

**Comment by Arcanemagus** [comment]
Was this actually affecting `stylelint`? It doesn't look like this project uses `babel-eslint`, and it was the interaction between `eslint@2.3.0` and `babel-eslint` that was causing this issue.

`eslint@2.3.0` removed a dependency that they were no longer using, but `babel-eslint` was monkey-patching this dependency and throwing the above error when it could no longer find it.

In any case `eslint@2.4.0` has been released, which allows parsers to work without the monkey patching (`babel-eslint` hasn't updated to account for it yet though).

**Comment by jeddy3** [comment]
> Was this actually affecting stylelint?

Oooo. That a good question. @ntwb Were any tests failing? I skimmed through the original eslint issue and, at the time, I didn't grok it was a `babel-eslint` specific issue.

Anyway, I just unpinned `eslint` in https://github.com/stylelint/stylelint/commit/826cb00c8d5254aa96f1004c853ccb73612b9ad6 and released in `5.0.1`.

**Comment by ntwb** [comment]
The issue for me was not being able to run the tests on a fresh clone, or having done `npm update` where ESLint `2.3.0` was then installed the tests would fail to kick off.
