### ISSUE TITLE
Should rule-set-no-empty be block-no-empty?

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#88]
Otherwise I'd imagine we should make `at-rule-no-empty`, too. But who would want only one?

**Comment by MoOx** [comment]
Yeah that's ok http://apps.workflower.fi/vocabs/css/en#block :)

**Comment by jeddy3** [comment]
Agreed. `block-no-empty` makes the most sense here.

**Comment by davidtheclark** [comment]
Ok, changed listing in #1
