### ISSUE TITLE
Missing deprecation notice for rule-no-shorthand-property-overrides

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#886]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

In #820 rule `rule-no-shorthand-property-overrides` was deprecated in favour of `declaration-block-no-shorthand-property-overrides`

> Which rule, if any, is this issue related to?

`rule-no-shorthand-property-overrides` and `declaration-block-no-shorthand-property-overrides`

> What CSS is needed to reproduce this issue?

n/a

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "rule-no-shorthand-property-overrides": true,
  }
}
```

> Which version of stylelint are you using?

`4.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

To see a deprecated warning:

```shell
src/test.css
⚠  'rule-no-shorthand-property-overrides' has been deprecated and in 5.0 it will be removed. Use 'declaration-block-no-shorthand-property-overrides' instead. [stylelint]
```

> What actually happened (e.g. what warnings or errors you are getting)?

No deprecation warning is seen.

**Comment by jeddy3** [comment]
Aww, shucks. 

Thanks for reporting.

This should be a quick fix, but I think we'll need to resolve https://github.com/stylelint/stylelint/issues/869 first.

**Comment by davidtheclark** [comment]
The deprecation notices were causing problems with people using gulp and postcss-reporter. We're going to just bump to 5.0 and note on the website and readme that people should read the changelog when upgrading. In the future we'll have to make sure the deprecation notices do not break builds.
