### ISSUE TITLE
Improve documentation that would help potential contributors

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#912]
I think it would be worthwhile to write down some things that would rule developers. Including the @stylelint/core team and also potential outside contributors. Ideas:

- List commonly overlooked edge cases (e.g. variables, strings & comments, nesting)
- Give examples of different prototypical rules
- Document something about the utils
- Documentation template

**If anybody reading this is a *potential* contributor, what would help you become an *actual* contributor?** (Whether that's docs like I'm talking about or something else?)

**Comment by evilebottnawi** [comment]
@davidtheclark template for docs rule?

**Comment by davidtheclark** [comment]
@evilebottnawi Great idea. I added it to the list above.

**Comment by evilebottnawi** [comment]
@davidtheclark rule boilerplate, including all `.*rc` (eslint and etc) configuration and some stuff?

**Comment by davidtheclark** [comment]
@evilebottnawi That would be helpful for plugin development but not core rule development or bug fixes. I think that would also be a helpful project but maybe a separate one. Want to open a new issue about it?

**Comment by jeddy3** [comment]
The four ideas that you've listed look great to me.

Perhaps we can build on "Document something about the utils" idea, and include something about how `postcss`'s API (`walkRules`, `walkDecls` etc..) along with `postcss-selector-parser` and `postcss-value-parser` make dealing with CSS easier.

The [existing documentation](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) is very terse and dry, but I think everything in it is valid. So, I think it'll make a sound foundation to build upon.

**Comment by ntwb** [comment]
These are great docs improvements, I know they'll help me, hopefully others also :+1:

**Comment by davidtheclark** [comment]
Excellent!
