### ISSUE TITLE
CLI: Linting not working for subdirectories

### ISSUE THREAD

**Issue by frenzzy** [stylelint/stylelint#915]
```shell
stylelint **/*.css          # lints only the second level folder
```

How to reproduce: https://github.com/frenzzy/stylelint-subdirectories-test

**Comment by davidtheclark** [comment]
If you have not wrapped your glob in quotation marks, it is going to be interpreted by whatever terminal you're using. Please try wrapping your glob in quotation marks to ensure it is parsed by globby within stylelint, and let us know how that goes.

**Comment by frenzzy** [comment]
You are right, just need to use quote marks
```shell
stylelint "**/*.css"
```
Thank you!
