### ISSUE TITLE
Encourage the use of postcss-stylelint-reporter

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#917]
This plugin has yet to be created. But once it is, we'll add references all over the docs. It will replace postcss-reporter as the reporter-of-choice for stylelint.

**Comment by davidtheclark** [comment]
Maybe I was too hasty with my enthusiasm for this.

There's a fundamental problem. Runners might run each file individually through PostCSS and its plugins (like gulp-postcss). But stylelint wants to report on them all at once, with stats that cover them all. At the runner-plugin level (e.g. gulp-stylelint), there can be runner-specific tricks pulled in order to make this happen. But I'm not sure we can do it at the postcss-plugin level --- where postcss-stylelint-reporter would be.

I'm thinking a good stylelint reporter needs to accumulate results, instead of treating each file individually, for these reasons:

- To provide stats on the whole linting process, e.g. 26 warnings and 3 errors.
- To avoid repeating invalid option warnings or deprecation messages with every single file.

Unless I'm wrong, then, *somehow postcss-stylelint-reporter would have to accumulate PostCSS results from an indefinite number of PostCSS processes before it actually produces its report.*

All the ideas I can think of right now for solving this would not work in grunt, or some other runner that does not allow you the freedom to use JS arbitrarily.

@ai, @ben-eb: Do you think there's any smart PostCSS way for this problem to be solved --- or, because each file is run through its own PostCSS process in something like grunt/gulp-postcss, is the only way to get ideal stylelint reports to have specialized stylelint plugins for each runner (grunt/gulp-stylelint, etc.)???

**Comment by davidtheclark** [comment]
Also pinging @w0rm and @nDmitry, maintainers of gulp-postcss and grunt-postcss --- If either of you have any idea whether it's feasible at all to make a postcss plugin that runs on the accumulated results of all the files -- or, if that's impossible, is the only option special gulp-stylelint and grunt-stylelint plugins?

**Comment by ntwb** [comment]
Also pinging @35n139e of https://github.com/35n139e/grunt-stylelint-reporter
