### ISSUE TITLE
Add FAQ to documentation

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#918]
I find this to be a very helpful documentation pattern: a page of common recipes.

When people ask, "How do I use stylelint in X way?" (with gulp or grunt or whatever; in my text editor; from the command line; etc.) we should have a straightforward, copy-pasteable common answer.

**Comment by jeddy3** [comment]
I certainly found recipes useful for when I first starting using `gulp` as there we lots of little use-cases to understand e.g. generating sourcemaps, running tasks in a series etc. However, isn't our case a bit different and how would recipes differ from our current usage examples? Also, the usage is quite different depending on whether you're using the CLI, Node API or PostCSS plugin. 

Perhaps having a list of questions that link off the varies resources. For example:

> How do I lint in within the Atom editor?

Use [`linter-stylelint](https://atom.io/packages/linter-stylelint).

> How do I use the CLI?

Refer to the [CLI user guide](http://stylelint.io/user-guide/cli/).

> How do I use stylelint with gulp?

Refer to the [PostCSS plugin user guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md), in particular [example A](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md#example-a) / Use `gulp-stylelint` (depending on which route we go down).

We can expand out the example to include Grunt etc.

What do you think?

**Comment by davidtheclark** [comment]
Yeah, a kind of FAQ might be the answer.

**Comment by davidtheclark** [comment]
Let's list the questions that should be covered in FAQ:

- How do I lint from the command line?
- How do I lint from gulp or other task runners?
- How do I lint within my text editor?
- Should I lint before or after processing my stylesheets through PostCSS plugins or other processors?
- How do I lint SCSS, or other non-standard syntax?

Other ideas?

**Comment by VinSpee** [comment]
I think a good one to cover is "getting up and running with BEM", which would include configuring the conformance checking plugin.

**Comment by jeddy3** [comment]
All those sound great to me.

Additionally:

- How do I manage conflicts between rules? Ref: https://github.com/stylelint/stylelint-config-standard/issues/14#issuecomment-197038273
- What is the difference between a plugin and a rule?

**Comment by davidmaxwaterman** [comment]
:+1: for the grunt example.
