### ISSUE TITLE
Add documentation to new rules

### ISSUE THREAD

**Issue by MoOx** [stylelint/stylelint#92]
jeddy3: Shifting list up to top comment so we get a little progress indicator...

* [x] `at-rule-no-vendor-prefix`
* [x] `block-no-empty`
* [x] `color-no-invalid-hex`
* [x] `declaration-block-no-duplicate-properties`
* [x] `declaration-semicolon-newline-after`
* [x] `declaration-semicolon-newline-before`
* [x] `declaration-semicolon-space-after`
* [x] `declaration-semicolon-space-before`
* [x] `eof-newline`
* [x] `eol-no-whitespace`
* [x] `function-calc-no-unspaced-operator`
* [x] `function-parentheses-inside-space`
* [x] `function-space-after`
* [x] `function-token-no-space`
* [x] `function-url-quotes`
* [x] `indentation`
* [x] `media-feature-colon-space-after`
* [x] `media-feature-colon-space-before`
* [x] `number-no-trailing-zeros`
* [x] `property-no-vendor-prefix`
* [x] `property-value-no-vendor-prefix`
* [x] `root-no-standard-properties`
* [x] `rule-set-no-single-line`
* [x] `selector-delimiter-newline-after`
* [x] `selector-delimiter-newline-before`
* [x] `selector-delimiter-space-after`
* [x] `selector-delimiter-space-before`
* [x] `selector-no-vendor-prefix`
* [x] `selector-root-no-composition`
* [x] `string-quotes`

**Comment by jeddy3** [comment]
Gearing up for 0.1.0:

* [ ] `block-no-empty`
* [ ] `color-no-invalid-hex`
* [ ] `declaration-block-no-duplicate-properties`
* [ ] `declaration-semicolon-newline-after`
* [ ] `declaration-semicolon-newline-before`
* [ ] `declaration-semicolon-space-after`
* [ ] `declaration-semicolon-space-before`
* [ ] `eof-newline`
* [ ] `eol-no-whitespace`
* [ ] `function-calc-no-unspaced-operator`
* [ ] `function-parentheses-inside-space`
* [ ] `function-space-after`
* [ ] `function-token-no-space`
* [ ] `function-url-quotes`
* [ ] `indentation`
* [ ] `media-feature-colon-space-after`
* [ ] `media-feature-colon-space-before`
* [ ] `number-no-trailing-zeros`
* [ ] `property-no-vendor-prefix`
* [ ] `root-no-standard-properties`
* [ ] `rule-set-no-single-line`
* [ ] `selector-delimiter-newline-after`
* [ ] `selector-delimiter-newline-before`
* [ ] `selector-delimiter-space-after`
* [ ] `selector-delimiter-space-before`
* [ ] `string-quotes`

I'm back on the train this afternoon and so I'll try to make a start on documenting the more interesting rules like `color-no-invalid-hex`, `indentation`, `root-no-standard-properties` and `function-url-quotes`.
