### ISSUE TITLE
Regex to fix pre-existing errors

### ISSUE THREAD

**Issue by nathanjessen** [stylelint/stylelint#937]
Feature request.

It would be cool to have a markdown file added to the project that has example regex to fix pre-existing errors. We added stylelint to our project with a large codebase and initially had 700+ warnings of  property-unit-blacklist for font-size.

We fixed using a regex on the project in Atom editor
Find:
(font-size: )(\d+(.\d+)?)px

Replace:
$1rem($2)

It would be nice to have examples for some of the other rules like function-comma-space-after, color-hex-case, etc

**Comment by davidtheclark** [comment]
I'm afraid that regular expressions are not generally going to be accurate enough to broadly recommend them. People will just have to come up with the transformations that work for their codebase.

However, there's discussion over in #330 of implementing autocorrect, either within stylelint or in a separate package. I think that that's the more robust version of what you're suggesting; so if you'd like to help out over there, please do!
