### ISSUE TITLE
number-no-trailing-zeros: Mistakenly errors on inline SVG string

### ISSUE THREAD

**Issue by timothyneiljohnson** [stylelint/stylelint#946]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where using an inline SVG definition as a background causes a `number-no-trailing-zeros` error

> Which rule, if any, is this issue related to?

`number-no-trailing-zeros`

> What CSS is needed to reproduce this issue?

```
.icon-arrow-down {
  background-image: url('data:image/svg+xml;charset=US-ASCII,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3C!DOCTYPE%20svg%20PUBLIC%20%22-%2F%2FW3C%2F%2FDTD%20SVG%201.1%2F%2FEN%22%20%22http%3A%2F%2Fwww.w3.org%2FGraphics%2FSVG%2F1.1%2FDTD%2Fsvg11.dtd%22%3E%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20width%3D%2232%22%20height%3D%2232%22%20viewBox%3D%220%200%2032%2032%22%3E%3Cpath%20d%3D%22M16%2025l-16-16%202-2%2014%2014.063%2014-14.063%202%202z%22%20fill%3D%22%23000000%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E');
  background-repeat: no-repeat;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "number-no-trailing-zeros": true
  }
}
```
> Which version of stylelint are you using?

`5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin in Gulp with
```
var stylelint = require('stylelint');
var syntax_scss = require('postcss-scss');

gulp.task('stylelint', function() {
  var processors = [
    stylelint(),
    reporter({
      clearMessages: true,
      throwError: true
    })
  ];

  return gulp.src([
    paths.source.css + '**/*.scss',
  ])
  .pipe(postcss(processors, {syntax: syntax_scss}));
});
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors you are getting)?

The following warnings were flagged:

```shell
4:89 ⚠  Unexpected trailing zero(s) (number-no-trailing-zeros) [stylelint]
```

**Comment by davidtheclark** [comment]
Should be able to fix this way the same way other similar rules were fixed in https://github.com/stylelint/stylelint/pull/868
