### ISSUE TITLE
selector-no-qualifying-type

### ISSUE THREAD

**Issue by timothyneiljohnson** [stylelint/stylelint#949]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new rule to catch uses of a qualifying element (with configuration for using alongside ids, classes, or attributes). Or possibly separate rules.

Personally, I was thinking the rule may look something like [scss-lint's qualifyingElement](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#qualifyingelement):
```json
{
  "rules": {
    "selector-qualifying-element": [
      allowedWithClass: false,
      allowedWithId: false,
      allowedWithAttribute: true
    ]
  }
}
```

> What CSS is needed to reproduce this issue?

Qualifying element + class
```css
a.testClass {}
```
Qualifying element + id
```css
a#testId {}
```
Qualifying element + attribute
```css
a[data-foo='bar'] {}
```

> Which version of stylelint are you using?

`5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

**Comment by davidtheclark** [comment]
What exactly is the logic here -- you can't use a type selector chained with any other selector?

**Comment by davidtheclark** [comment]
Funny -- I wrote that rule! https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/qualifying_element.rb

**Comment by timothyneiljohnson** [comment]
Lol, nice! Yes, the logic is to disallow/allow the unnecessary chaining of *element* selectors to other selectors (e.g. 'span.testClass', 'span.testId', would error. '.testClass', '#testId' would pass).

**Comment by davidtheclark** [comment]
I think we'd want to name it `selector-no-qualifying-type` and make those options secondary `ignore`s. So your example above would end up like this:

```js
"selector-no-qualifying-type": [ true, {
  "ignore": [ "attribute" ]
} ]
```

**Comment by jeddy3** [comment]
> I think we'd want to name it selector-no-qualifying-type and make those options secondary ignores

Sgtm.

**Comment by timothyneiljohnson** [comment]
Hi @jeddy3 @davidtheclark - FYI I've created a few stylelint plugins very recently. One accomplishes this (I hope fairly well).

Would greatly appreciate any feedback! https://github.com/timothyneiljohnson/stylelint-selector-qualifying-element

**Comment by evilebottnawi** [comment]
@jeddy3 i think it is good rule for core, help do not mistake. @timothyneiljohnson please PR this rule for review.

**Comment by davidtheclark** [comment]
Agreed, please PR this rule! Would be excited to have it in core.

**Comment by jeddy3** [comment]
> Would be excited to have it in core 

Agreed. 

@timothyneiljohnson Great work with the plugin! Can you please rename it to "`selector-no-qualifying-type` and make those options secondary ignores" during the port over to bring it inline with our [naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#about-rule-names).

**Comment by evilebottnawi** [comment]
Merged. Close.
