### ISSUE TITLE
New rule: number-no-unitized-zero

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#95]

**Comment by MoOx** [comment]
Maybe this should be a *-no-* rule ?

**Comment by davidtheclark** [comment]
I actually think this is a case where the "never" might be used -- if somebody believes that it's always more clear to specify units, and they'd like to leave the stripping to a minifier.

**Comment by MoOx** [comment]
Hummm. 0px ? 0em ? How would you choose for the "always" ?

**Comment by MoOx** [comment]
Make no sens to me to force a unit. Maybe allow it (so no rules) or disallow (-no-).

**Comment by davidtheclark** [comment]
What I was thinking was that "always" would require you do something like this: `margin: 5px 0px 0px 3px`. We would ignore the unit, as it would be relative to whatever would *otherwise* be expected in that place. But if you and @jeddy3 think `-no-` is better, I'll certainly go with it as it's simpler.

**Comment by jeddy3** [comment]
> What I was thinking was that "always" would require you do something like this: margin: 5px 0px 0px 3px. We would ignore the unit, as it would be relative to whatever would otherwise be expected in that place.

Yeap, that's what I was anticipating when I originally changed this rule from a `-no-` one.  

I changed a few rules of the `-no-` rules when I saw an opportunity, however edge-case, to give the user more control. I probably went too far though (e.g. we, I think correctly, decided that `number-trailing-zero: "always"|"never"` went too far).

Having `"always"|"never"` for this rule feels less edge-case than `number-trailing-zero`, but it will be more complicated to implement and that might not be worth the effort.

Happy to follow your call on this one @davidtheclark

**Comment by davidtheclark** [comment]
It wouldn't be that much more complicated, so I'll build it with always/never.

**Comment by davidtheclark** [comment]
Actually, I've been thinking this through and I think it might be significantly easier to build just for "never". I'll work on that first, then we'll see :)

**Comment by jeddy3** [comment]
SGTM :)

**Comment by davidtheclark** [comment]
If we want to be very specific with the naming we *might* want to consider renaming this rule to `number-zero-length-no-unit`

**Comment by jeddy3** [comment]
Specific SGTM.

Also, `unitized` is a weird word at the best of times :)
