### ISSUE TITLE
property-no-unknown

### ISSUE THREAD

**Issue by timothyneiljohnson** [stylelint/stylelint#950]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A new rule to catch uses of a unknown properties. Is there any plan to support this against a whitelist of known properties? I think it would be extremely helpful!

P.S. I do see an attempt [here](https://github.com/betit/stylelint-known-property), however, it does not work with the latest stylint version / appears relatively unsupported.

> What CSS is needed to reproduce this issue?

```css
.testClass {
  bottom-border: 0 // No such property
}
```

> Which version of stylelint are you using?

`5.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

**Comment by ntwb** [comment]
There is also this new, and large project https://github.com/ben-eb/css-values but its very early days there.

**Comment by evilebottnawi** [comment]
@ntwb @timothyneiljohnson problems where get real and valid property on current css spec?

**Comment by timothyneiljohnson** [comment]
@ntwb - looks pretty interesting, unfortunate that it's in alpha. I would definitely attest to [scss-lint's property list](https://github.com/brigade/scss-lint/blob/master/data/properties.txt) working wonderfully for me. If only checking that the *property* exists in the whitelist, it may be fairly short — though it's much shorter if you were to choose to not include the incredibly long list of vendor-prefixed properties.

**Comment by evilebottnawi** [comment]
@timothyneiljohnson it is not good list property, plus browser based properties (example https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions etc).

**Comment by timothyneiljohnson** [comment]
Hi @ntwd @davidtheclark - I've created a few stylelint plugins very recently. One accomplishes this (using the same property whitelist as used in scss-list).

Would greatly appreciate any feedback! https://github.com/timothyneiljohnson/stylelint-property-unknown/

**Comment by ntwb** [comment]
>  https://github.com/timothyneiljohnson/stylelint-property-unknown/

Worked perfectly, so much so I had to rename a property to force an error to be detected :smirk: 

I think this should be a core stylelint rule :100: 

@timothyneiljohnson I know @davidtheclark has looked at the following repo also, comparing your list of properties with that of stylelint-known-property's I see you overall have more properties detected, though there are some CSS 2 properties listed in stylelint-known-property that you've not _yet_ added, would be great to see those added.

https://github.com/timothyneiljohnson/stylelint-property-unknown/blob/master/data/knownProperties.json
https://github.com/betit/stylelint-known-property/blob/master/data/properties.js

**Comment by evilebottnawi** [comment]
@ntwb @timothyneiljohnson i think we also add option `ignore` with array (string or regexp) for exclude some specific property (which used throw postcss plugins `w` for `width` example).

**Comment by davidtheclark** [comment]
@jeddy3 what do you think about adding this rule to core? I see the ultimate intention as a very linter-worthy one. The only questionable part is the manual maintenance of a list of issues. Once [css-values](https://github.com/ben-eb/css-values) is fully operational we *should* have a superior means of maintaining that list (it should also be able to check property-value pairs). But in the meantime if this is working on @ntwb's codebase (how about on @evilebottnawi's?) it's probably worth including ---- people can always add to it, ignore lines, turn it off, etc., if the list is not complete enough.

**Comment by davidtheclark** [comment]
@timothyneiljohnson @evilebottnawi : I agree that the `ignore` option is essential.

**Comment by evilebottnawi** [comment]
@davidtheclark I do think this is an extremely controversial rule and it gives us a lot of headaches

**Comment by davidtheclark** [comment]
@evilebottnawi I also see headaches because of the manually maintained list. Do you see others?

**Comment by evilebottnawi** [comment]
@davidtheclark some browser hack declaration may throw error in this rule.

**Comment by jeddy3** [comment]
> @jeddy3 what do you think about adding this rule to core? 

Sure. 

@timothyneiljohnson Would you be willing to port this rule into core with the following changes?:

1. It's called `property-no-unknown` to bring it inline with the [naming conventions](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#about-rule-names).
2. There is an `ignoreProperties` options, which accepts an array of strings or regexs. We idiomatically use `ignore` for only *keyword* options rather than [user defined lists](https://github.com/stylelint/stylelint/blob/master/src/rules/block-closing-brace-newline-after/README.md#optional-options).
3. We add a note to README explaining that browsers hacks aren't handled and so you probably don't want to turn this rule on if you use browser hacks and don't want to maintain an `ignoreProperties` array.

Btw, thanks again for nailing so many plugins recently. It's great to see :)

@davidtheclark Sound good?

**Comment by davidtheclark** [comment]
How does this rule handle vendor-prefixed properties? Ignore them completely, or check their unprefixed versions against the list?

**Comment by jeddy3** [comment]
> Ignore them completely, or check their unprefixed versions against the list

Checking the unprefixed version would be consistent with how we've treated prefixes elsewhere e.g. [`declaration-block-properties-order`](https://github.com/stylelint/stylelint/tree/master/src/rules/declaration-block-properties-order). Can we think of a reason to do otherwise here?

**Comment by davidtheclark** [comment]
I agree that that's the way to go.

**Comment by timothyneiljohnson** [comment]
@davidtheclark - I've been ignoring vendor prefixed properties, but yes, I can make an attempt at your suggestion above.

**Comment by jeddy3** [comment]
@timothyneiljohnson Good stuff. You'll find an example of how we do that in [`property-blacklist`](https://github.com/stylelint/stylelint/blob/master/src/rules/property-blacklist/index.js).  FYI, there's also a [developer guide](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md) for new rules which you might find helpful. Also, please don't hesitate to ask questions or fire over a Pull Request if you'd like feedback :)

**Comment by ntwb** [comment]
> ... Once css-values is fully operational we should have a superior means of maintaining that list (it should also be able to check property-value pairs).

@davidtheclark I fully agree with this :+1: 

One of the issues I've had with gaining broader adoption of stylelint is because it cannot detect _unknown properties_, or aka _spelling mistakes_, e.g. `margi:`. This `property-no-unknown` rule and the enhancements down the road gained from `css-values` will help here in this regard.

**Comment by jeddy3** [comment]
Following on from the discussion in #1004... this is ready to be built:

- Name: `property-no-unknown`
- Primary option: `true`.
- Secondary options: `ignoreProperties: []` (user defined array of unprefixed property names)
- Message: "Unexpected unknown property".

**Comment by mehcode** [comment]
@davidtheclark / @jeddy3 / @evilebottnawi 

I'd like to work on this. Before I get going -- how did you want this tackled? Should we have a css property JSON in this project or use a library like this: https://github.com/blakeembrey/just-css-properties ?

**Comment by jeddy3** [comment]
> Should we have a css property JSON in this project or use a library like this: https://github.com/blakeembrey/just-css-properties ?

Feel free to start with using that library (as it'll get you up and running more quickly). We can revisit its inclusion again during the Pull Request stage.

**Comment by evilebottnawi** [comment]
@jeddy3 i think be good have this repo in stylelint org, this would allow to react quickly and to add properties

**Comment by evilebottnawi** [comment]
@jeddy3 And in the future it is possible to use the same repo for `declaration-no-invalid`

**Comment by jeddy3** [comment]
FYI, there are two plugin in the wild that do this. I've also [reached out ](https://github.com/betit/stylelint-known-property/issues/6) to the 2nd one in the hope we can port the best of both into core.

**Comment by evilebottnawi** [comment]
@jeddy3 be good create seporate repo for properties or search existing.

**Comment by jeddy3** [comment]
Done in #1629
