### ISSUE TITLE
Rename at-rule-blockless-newline-after

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#954]
I'm catching up on issues and pull requests this morning. It's awesome to see so many contributions over the last few days btw! :)

I just realised that I suggested the wrong name for `at-rule-blockless-newline-after`. It should be `at-rule-semicolon-newline-after`.  That will be it inline with all the other `after` and `before` rules which specify the punctuation.

I'll push up a PR before the next release.

**Comment by davidtheclark** [comment]
Closed by #956.
