### ISSUE TITLE
New rule: statement-separation

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#97]
Just pasting the example config:

```js
{
  "statement-separation": {
    "default": 1
    "comment-blocks": true // separate comments-blocks by one line
    "statements": true, // separate statements by one line
    "at-rule-import-statements": false, // unless an @import rule (overriding, but OK as within a single rule?)
    "nested-statements": false // and unless the statement is nested
  }
}
```

Is the suggestion with "default" that any of those other properties could have integers as well as booleans for values, giving them different spacing?

**Comment by MoOx** [comment]
Maybe we should use "newline" instead of booleans to separate some part ?
Not sure for the last 2 parts.

**Comment by jeddy3** [comment]
> Is the suggestion with "default" that any of those other properties could have integers as well as booleans for values, giving them different spacing?

I'd take those options with a pinch of salt as I don't think we thought it through that far! :) I remember simply basing the options, without much thought, on those of `indentation` when I expanded the options for @MoOx original rules. So, I think you can safely ignore any suggestion it is making :)

Having said that, do those options make some sense or should we try something different as @MoOx suggested?

Perhaps going without `default` and only using booleans:

```
{
  "separation": {
    "comment-blocks": 1 // separate comments-blocks by one line
    "statements": 2, // separate statements by two line
    "at-rule-import-statements": 0, // unless an @import rule (overriding, but OK as within a single rule?)
    "nested-statements": 0 // and unless the statement is nested
  }
}
```

Does that simplify the options object a little, while still giving the user complete control?

Either way, I think this is the first rule we've done where some of the options are acting as overrides and I'm not sure if that is the right approach. What are you two's thoughts on that?

**Comment by davidtheclark** [comment]
Hm ......

If we want to allow granular control, what if we split this into a bunch of different rules?

- `comment-separation-before`
- `comment-separation-after`
- `statement-non-nested-separation-before`
- `statement-non-nested-separation-after`
- `statement-nested-separation-before`
- `statement-nested-separation-after`
- `at-rule-import-separation-before`
- `at-rule-import-separation-after`

Stuff like that?

That way we'd avoid the whole default / override situation, and we'd adhere to precedent. The difference between these and `*-newline-*` after rules would be that these accept an integer representing *the number of newlines*.

**Comment by davidtheclark** [comment]
There could be contradictions here, though...

**Comment by davidtheclark** [comment]
After having written that, I'm wondering if a default with overrides is the only way to go. That way we could consistently add overrides as people decide they're necessary (e.g. I don't want separation between `@font-face` statements but do want them between `@import`s.). But maybe instead of one general default we get a little more precise, e.g. `comment-default`, `rule-default`, `at-rule-default`?

**Comment by jeddy3** [comment]
> There could be contradictions here, though...

Correct. I think that's the difficulty here.

> I'm wondering if a default with overrides is the only way to go.

Same with me. I can't think of, if we want to provide the user with fine-grain control, another alternative at the moment. 

"`@font-face` statements but do want them between `@imports`" is a great example of how this rule could balloon in complexity and features. An alternative stop-gap could be just to tackle the multiple blank lines issue with something like `no-multiple-empty-lines` for now, as mentioned in #135?

> But maybe instead of one general default we get a little more precise, e.g. comment-default, rule-default, at-rule-default?

SGTM. I think that's the best option so far *if* we want to give fine-grain control.

**Comment by davidtheclark** [comment]
Ooo, I had another idea.

Am I wrong, or is this really about newlines *before* nodes? (The *after* part would be handled by the *before* rule of the next node.)

If that simplification works, then I'd say we could split this up nicely.
- `rule-set-non-nested-newline-before`
- `rule-set-nested-newline-before`
- `comment-newline-before`
- `at-rule-import-newline-before`
- `at-rule-media-newline-before`
- `at-rule-font-face-newline-before`

Each would have `"always"|"never"` options.

We could keep these granular, then, and indefinitely add rules if we wanted to, without bloating a single rule with possibly contradictory options. Because we only have *before*, we actually shouldn't run into contradictions. If some rule requires special options (e.g. newline before font-face unless the node before is another font-face) that special case would be contained within that rule via another keyword option (e.g. "always-except-after-font-face").

Also: I agree that we should have a `no-multiple-empty-lines` rule independent of this one.

**Comment by jeddy3** [comment]
> Am I wrong, or is this really about newlines before nodes? (The after part would be handled by the before rule of the next node.)

That's a fantastic insight!

> We could keep these granular, then, and indefinitely add rules if we wanted to, without bloating a single rule with possibly contradictory options. Because we only have before, we actually shouldn't run into contradictions

Awesome. 

The only, albeit minor, thing to clarify is what happens to the first node in a file? Do we either:

a. flag a warning if there isn't a blank line.
b. test if we're at the top of the file and don't flag a warning.

> If some rule requires special options (e.g. newline before font-face unless the node before is another font-face) that special case would be contained within that rule via another keyword option (e.g. "always-except-after-font-face").

Really nice.

Besides that little clarification your proposed solution looks totally stellar to me! :)

**Comment by davidtheclark** [comment]
Thanks. I think that for the first node of the file we will not enforce a newline. I have never seen a styleguide recommending an empty line at the top (have either of you?).

**Comment by davidtheclark** [comment]
Just saying "newline" is a little bit disingenuous, since it's really expecting *two* newlines. We could say "empty-newline" or just "separation"? (e.g. `at-rule-empty-newline-before` or `at-rule-separation-before`).

**Comment by jeddy3** [comment]
>  I think that for the first node of the file we will not enforce a newline

SGTM.

> Just saying "newline" is a little bit disingenuous, since it's really expecting two newlines. 

Agreed. How's about `at-rule-empty-line-before: "always"|"never"` as we're already using the `empty-line`, rather than `empty-newline`, language in `no-multiple-empty-lines`?

**Comment by davidtheclark** [comment]
Sure, good thinking

**Comment by davidtheclark** [comment]
I've already started on work on several of these more granular rules, so closing this issue.
