### ISSUE TITLE
Update `findAtRuleContext-test.js` to not use `eachRule`

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint#976]
`eachRule` was deprecated in PostCSS v5.0.0, [findAtRuleContext-test.js#L19](https://github.com/stylelint/stylelint/blob/master/src/utils/__tests__/findAtRuleContext-test.js#L19) util should be updated to use `walkRules`

**Comment by davidtheclark** [comment]
Huh, I wonder why I did that? Thanks for pointing it out.
