### ISSUE TITLE
Add SugarSS syntax option

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#985]
Ref: https://github.com/postcss/sugarss

@davidtheclark What do you think? Inline with our goal of making stylelint useful to the most number of users possible?

**Comment by davidtheclark** [comment]
Yeah, we should do this.

**Comment by jeddy3** [comment]
Sgtm. Marking this as `help wanted`. So that the first person [who needs](https://github.com/stylelint/stylelint/issues/978#issuecomment-202400107) this can fire over a PR.

For that person, here's the [equivalent PR](https://github.com/stylelint/stylelint/pull/926) for adding a LESS syntax option.

**Comment by davidtheclark** [comment]
I'm doing this one because I want to brag about it in my article for CSS-Tricks.
