### ISSUE TITLE
Old files being published to npm?

### ISSUE THREAD

**Issue by m-allanson** [stylelint/stylelint#995]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I think this is a bug(?), it looks like some old files are being published to npm.

> Which version of stylelint are you using?

5.2.1

> What did you expect to happen?

Following an `npm install stylelint`, the directory `./node_modules/stylelint/dist` should not contain the files `lintStream.js`, `plugin.js`, `ruleSeverities.js`

> What actually happened (e.g. what warnings or errors you are getting)?

The `dist` directory appears to contain files that don't exist in the `src` directory

**Comment by jeddy3** [comment]
Oops, we should probably `rimraf` the `dist` folder before we build to it.

**Comment by davidtheclark** [comment]
Yeah, that's the solution :)
